### ISSUE TITLE
CocoaLumberjack dependency @ 2.3.0

### ISSUE THREAD

**Issue by christocracy** [expo/expo#100]
Latest version of CocoaLumberjack is `3.1.0`.  Many other 3rd-party libs rely upon `CococaLumberjack` ([including *mine*](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation.podspec#L21)).

I managed to get my library working with a detached Expo app simply by editing `.expo-source/ios/ExpoKit.podspec`

```diff
+s.dependency 'CocoaLumberjack', '~> 3.0'
```

If you're going to use a *very* popular 3rd party Pod dependency, you better make sure *you're* using the latest version.

**Comment by terribleben** [comment]
Hello there! Thanks for bringing this to our attention. The next release will include this change. (We're updating our shipit bot right now, so I can't show you the commit.)

Since you sound like you were frustrated by this, here's a picture of a majestic lemur.

![image](https://cloud.githubusercontent.com/assets/1316332/24561090/5b8a9c5c-15fa-11e7-99d0-4ed4e5540ddd.png)

**Comment by christocracy** [comment]
I wasn't frustrated at all.  It took me < 30s to make it work.  For users (and potential customers of mine) unfamiliar with XCode, it's more likely impossible :)
