### ISSUE TITLE
Double slashes instead of tripple

### ISSUE THREAD

**Issue by macci10** [expo/expo#10012]
## 🐛 Bug Report

App was opening fine with myapp:// scheme. Suddenly it stopped opening with myapp:// scheme. I called Linking.makeUrl() and it returned myapp:///. Now when i open myapp:/// scheme the app works fine. I can't seem to find any place where this change happened. I want to use double slashes in my deeplink. It's an Expo App and the only configuration i can find for deeplink is setting the scheme in app.json file like "scheme": "myapp".

### Environment
Expo CLI 3.25.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.7.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.8 => 38.0.9 
      react: ~16.13.1 => 16.13.1 
      react-dom: ~16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2 
      react-native-web: ~0.13.4 => 0.13.8 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.25.0

### Expected Behavior vs Actual Behavior

I want to open my app with myapp:// with double forward slashes

**Comment by byCedric** [comment]
Hi @macci10, we changed this in SDK 37. You can [read more about that here](https://github.com/expo/expo/issues/6497#issuecomment-574882448), or in the changelogs for SDK 37. To summarize:

Custom URIs with only 2 slashes aren't valid URIs, usually it consists of `<scheme>://<host>/<path>[/<path>...]`. In these custom URIs, we don't have a `host` and must leave that blank in order to comply with [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3).

Hope this helps!
