### ISSUE TITLE
Updated my push notifications to new expo-notifications and noticed this error in logs sometimes

### ISSUE THREAD

**Issue by rafmst** [expo/expo#10020]
## 🐛 Bug Report

I updated my app to new sdk 38 with new expo-notification way of doing things and I noticed this bug on bugsnag that is happening to some users. I couldn't reproduce it locally. The error is:

```
Error[native code]:0
Error encountered while fetching Expo token: TypeError: Network request failed.
```

### Environment

Happening on iOS and Android, but 90% on iOS

```
Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      npm: 6.14.6 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.9 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.25.1
```

### Expected Behavior vs Actual Behavior

Not happening to a lot of people and no one complained, but I was wondering what could it be.

**Comment by byCedric** [comment]
Hi @rafmst! With the latest `expo-notification` refactor, we added more and explicit error handling. This error is probably coming from [this line](https://github.com/expo/expo/blob/248c02b4afae5a23daa661294502e5f6ecec3689/packages/expo-notifications/src/getExpoPushTokenAsync.ts#L71). It means that the device couldn't connect to our notification service to generate the Expo token, probably caused by an unstable or no internet connection. It shouldn't affect users that much, but it does mean you have to retry fetching the token before you can send notifications to that device. 

Hope this helps!

**Comment by rafmst** [comment]
Thanks @byCedric this helped me understand :)

**Comment by ankit2049** [comment]
@byCedric Similar issue on iOS. I am getting the following error on running Notifications.getExpoPushTokenAsync in bare workflow
`{"code":"ERR_NOTIFICATIONS_NETWORK_ERROR","line":109,"column":244,"sourceURL":"/var/mobile/Containers/Data/Application/87572C46-2EB7-42AD-9559-19AB1CED2DFA/Library/Application Support/.expo-internal/bundle-1599054471079"}`
Status code is 401. What could be the reason behind 401?
