### ISSUE TITLE
Include a message parameter in expo Sharing API

### ISSUE THREAD

**Issue by rewaant** [expo/expo#10039]
Hi,

I've been trying to use the Expo Sharing API which works good if we're just using the asset's url (a local image uri) but not if we have to pass in a message parameter in addition. It isn't clear from documentation if we even have this feature. The native Share API includes a message option but lacks in other aspects including sharing to social networks (say Instagram which allows to send it as a message but not post to feed) which is quite buggy.

External libraries like react-native-share aren't supported in managed workflow either which are quite liberating and have some awesome features like Share.single() that allows custom buttons.

This seems like a deal breaker for using expo in majority of projects as a feature so important as sharing an image attached with a message param is not properly implemented. Seems the only option at this point is to eject to bare workflow but that would introduce 3x the effort for completing the same requirement.

Is there anything that I'm missing or any workaround that can help out?

**Comment by barthap** [comment]
There's currently no possibility to share anything but asset uri using Expo Sharing API. Some more functionality has the SMS module (send text with image) and Mail Composer - ability to add attachments.
Maybe it's worth considering expanding sharing functionality in Expo.

**Comment by rewaant** [comment]
Definitely, I think its a feature mostly anyone would need once they're maintaining an expo app long enough that also allows any kind of share functionality. We should be able to do the basics as ejecting for a small feature (which is quite important) may be quite painful depending upon the app and it's development journey.

**Comment by MehmetKaplan** [comment]
Do you know if this is something planned or not?

**Comment by rewaant** [comment]
I don't think it is, yet. But there are some feature requests marked on canny you can upvote so they get some traction. It would make things so much easier...

Here they are:
https://expo.canny.io/feature-requests/p/add-message-to-shared-file-new-sharing-api
https://expo.canny.io/feature-requests/p/single-share-to-social-apps
https://expo.canny.io/feature-requests/p/support-for-react-native-share

**Comment by sumit-1510-sharma** [comment]
Guys just use "react-native-share" library instead. I know that is not managed by expo and you have to go native but as you already know we can use native libraries with the development build also. 

So if you are in a development build and when you install the "react-native-share", you can get 2 errors, first error will be that it will not let you even run "npx expo start" and the way to solve that is to properly update your plugins in app.json() as below:-

```
"plugins": [
      "expo-router",
      [
        "expo-splash-screen",
        {
          "image": "./assets/images/appIcon.png",
          "imageWidth": 200,
          "resizeMode": "contain",
          "backgroundColor": "#ffffff"
        }
      ],
      "react-native-iap",
      [
        "react-native-share",
        {
          "ios": ["fb", "instagram", "twitter", "tiktoksharesdk"],
          "android": [
            "com.facebook.katana",
            "com.instagram.android",
            "com.twitter.android",
            "com.zhiliaoapp.musically"
          ]
        }
      ]
    ],
```

just add the ios field as well even if you are building your app for android, I don't know why but I was getting the error until I updated it like this.

Then second error would be related about "RNShare file not found" something and that error is because you have to make a new development build after installing this library as this is a native code library and your new development build will be having the code and files it needs to run "react-native-share" functions.

After that just use it in your code, below is my final code in which I am sharing a screenshot of my component in the app and the attached message:-

```
import Share from "react-native-share";                                     // keep this in mind that it is not from "react-native"

const handleShare = async () => {
    try {
      const uri = await cardRef.current.capture();                          // (this is with "react-native-view-shot" library)    
      const shareOptions = {                                                                     
        title: "Check out this app!",
        message: "Download the app here: https://your-app-link.com",
        url: uri,
      };
      await Share.open(shareOptions);
    } catch (error) {
      console.log("Error sharing screenshot: ", error);
    }
  };
```
