### ISSUE TITLE
After I upgraded to SDK 38, it reports Invariant Violation: ART has been removed from React Native. It can now be installed and imported from '@react-native-community/art' instead of 'react-native'

### ISSUE THREAD

**Issue by painforever** [expo/expo#10045]
## 🐛 Bug Report

I did "expo upgrade", then I got this issue:
![image](https://user-images.githubusercontent.com/2458972/92004258-00637880-ed10-11ea-84fb-740542adbbde.png)

### Summary of Issue 
I googled a lot but no solution, there are other related post on Stackoverflow like caused by "react-native-progress", but seems no help. and I also did npm install @react-native-community/art --save but it needs "link" so should also no help. Can someone tell me how to solve this? I upgraded from sdk36, which was working fine. Thanks.

**Comment by barthap** [comment]
ART is now [removed](https://docs.expo.io/versions/latest/sdk/art). You can use Svg instead.
I'd you want _progress_, you can try [this](https://github.com/EvanBacon/expo-progress).

**Comment by byCedric** [comment]
Hi @painforever, thanks for the report. Just as @barthap mentioned, [we deprecated ART since SDK 36](https://docs.expo.io/versions/latest/sdk/art). It's also extracted from the React Native core into the community package. I'm not sure what part of your code is using ART, you might have more luck with the [`expo-progress`](https://github.com/EvanBacon/expo-progress) if you need `progress`. You can still use the ART from the community package, but you will need to eject to bare for that.

Hope this helps!
