### ISSUE TITLE
[expo-screen-orientation] 2.0.0 release missing from npm

### ISSUE THREAD

**Issue by thornbill** [expo/expo#10055]
### Summary of Issue 
According to the [changelog](https://github.com/expo/expo/blob/master/packages/expo-screen-orientation/CHANGELOG.md) and the [package.json](https://github.com/expo/expo/blob/master/packages/expo-screen-orientation/package.json#L3) the 2.0.0 release of expo-screen-orientation was released on August 11 but it is not available on [npm](https://www.npmjs.com/package/expo-screen-orientation). When should it be available? I am looking forward to the release fixing an issue with screen rotation for iPad users. Thanks!

**Comment by byCedric** [comment]
Hi @thornbill, thanks for writing in. I can see that we actually did publish `2.0.0` but under the `next` tag. You should be able to install this version with the commands below. I'm not 100% why it's listed under next, because we [do include it in SDK 38](https://github.com/expo/expo/blob/skd-38/packages/expo/bundledNativeModules.json#L98) (cc @lukmccall)

- `$ yarn add expo-screen-orientation@2.0.0`
- `$ yarn add expo-screen-orientation@next`
- `$ expo install expo-screen-orientation` (assuming you use SDK 38)

<img width="786" alt="Screenshot 2020-09-04 at 13 00 32" src="https://user-images.githubusercontent.com/1203991/92232417-caa8c600-eeae-11ea-99b0-dce95d595381.png">

**Comment by lukmccall** [comment]
Ohh, did we add it to `SDK 38`? It's weird cause it is listed in `bundledNativeModules.json`, but I couldn't find my changes on the sdk-38 branch.

So I believe that was published for bare projects but it isn't included in `SDK 38`. It will be part of the next release (`SDK 39`).

**Comment by thornbill** [comment]
Can it still be manually installed in a managed SDK 38 project?

**Comment by thornbill** [comment]
Thanks! I will close this then and just anxiously await 39 to be available! :raised_hands:
