### ISSUE TITLE
Push notifications working on iPhone SE but not iPhone 11

### ISSUE THREAD

**Issue by Jonofat** [expo/expo#10122]
I am testing push notifications and they work perfectly going to an iPhone SE and iPhone 6.  but when trying to send to iPhone 11 the notifications never appear. This is true for both using the push notification tool on the web and using code to send to the API. Push notification permissions are enabled so permissions don't seem to be the problem. 

Has anybody else has this issue?

**Comment by cruzach** [comment]
hey @Jonofat , we haven't had reports of this otherwise, and I'm not sure what could cause that behavior. Do local notifications work on the device?

I'm going to close this since we keep github reserved for bug reports, but it might help in debugging to check the push ticket and push receipt from Expo https://docs.expo.io/push-notifications/sending-notifications/#push-tickets
