### ISSUE TITLE
( iOS only ) Expo payment stripe stuck on promise in case of errors from stripe

### ISSUE THREAD

**Issue by debianw** [expo/expo#10124]
### Summary of Issue 
Stuck on promise when testing invalid params. Promise doesn't reject or throw any exception

```
try {
   const token = await Stripe.createTokenWithCardAsync(params);
}
catch(error) {
  console.log(error);
}

```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo SDK 38
expo-payments-stripe@8.2.3

### Reproducible Demo

```
try {
      const params = {
        // mandatory
        number: "4242424242424242",
        expMonth: 11,
        expYear: 14,
        cvc: "223",
        // optional
        name: "Test User",
        currency: "usd",
        addressLine1: "123 Test Street",
        addressLine2: "Apt. 5",
        addressCity: "Test City",
        addressState: "Test State",
        addressCountry: "Test Country",
        addressZip: "55555",
      };
      console.log("creating token!!");
      const token = await Stripe.createTokenWithCardAsync(params);
      console.log("token => ", token);
      setToken(token);
    } catch (error) {
      console.log("Stripe error => ", error);
    }
```

### Expected Behavior vs Actual Behavior
Should throw an exception due to an expiration date

**Comment by Connoropolous** [comment]
I am seeing this as well

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
