### ISSUE TITLE
push notification doesn't work in some android devices sometimes.

### ISSUE THREAD

**Issue by MaheshaBhat** [expo/expo#10143]
### Please note that discussions opened as issues in the core Expo repository will be closed.

Expo CLI 3.22.3 environment info:
    System:
      OS: Windows 10 10.0.16299
    Binaries:
      Node: 14.5.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\10980\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
      react-navigation: ^4.4.0 => 4.4.0

When i tried to send notification it works fine with ios but it will fail to send to some of the android devices like xiaomi, poco f1 sometimes.
Android version which I am using is 9.
please help me fix this issue.

**Comment by cruzach** [comment]
Hi- without more information there's not much investigation we can do. If you can provide a full description of what's happening, the error message // error object in the push ticket or push receipt, and a reproducible demo, we can investigate and try our best to help

As the template you used states, discussions are closed since we keep github reserved for bug reports. If you'd like to report a bug, please use the bug report template and provide all the info we ask for
