### ISSUE TITLE
OTA update crash (Android only)

### ISSUE THREAD

**Issue by gang544043963** [expo/expo#10188]
### Summary of Issue 
Kill the app before the updating completed, the app will crash when open in second time on Android device. (iOS works well)

### Environment
"expo": "^37.0.0",
Platform: Android
Device: I have tried three kinds of Android devices.

### Steps to Reproduce
Configuration as below:
`
"updates": {
      "enabled": true,
      "fallbackToCacheTimeout": 0
    },
`
1. Install the app you published in "prod_1_0_0" release-channel;
2. Publish a new version of build in same Release-channel;
3. Open the App installed previously, and kill it in 5 seconds.(make sure the updating not complete)
4. Open the App again;
5. Crash!

### Expected Behavior
Work well if the updating not complete in first time.

**Comment by byCedric** [comment]
Hi @gang544043963, thanks for the report. But without [a repro](https://stackoverflow.com/help/minimal-reproducible-example) we can't help you solve this. We need to be able to reproduce the error before we can write a fix. If you can provide one that would be helpful.

**Comment by gang544043963** [comment]
Hi @byCedric , I updated the "Steps to Reproduce". If anything is not clear, please feel free let me know.

**Comment by cruzach** [comment]
hey @gang544043963 I'm not really sure if that's what's happening here, but if it is- SDK 39 includes `expo-updates` which is a complete overhaul of the OTA updates library, and should resolve the issue when updates aren't fully downloaded.

Since it's possible that that isn't what's happening here, I suggest grabbing the native android device logs during the crash and looking there for anything interesting
