### ISSUE TITLE
By default my expo app includes a lot of permissions

### ISSUE THREAD

**Issue by LuD1161** [expo/expo#10206]
When I run `expo build:android -t apk` the built app has a lot of permissions by default.

This is my app's `AndroidManifest.xml` : 

```xml
 <permission android:name="com.hackingsimplified.notifyme.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
    <uses-permission android:name="com.hackingsimplified.notifyme.permission.C2D_MESSAGE"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-feature android:glEsVersion="0x00020000" android:required="true"/>
    <uses-feature android:name="android.software.leanback" android:required="false"/>
    <uses-feature android:name="android.hardware.touchscreen" android:required="false"/>
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:smallScreens="true" android:xlargeScreens="true"/>
    <uses-permission android:name="host.exp.exponent.permission.C2D_MESSAGE"/>
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-feature android:name="android.hardware.camera" android:required="false"/>
    <uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>
    <uses-feature android:name="android.hardware.location" android:required="false"/>
    <uses-feature android:name="android.hardware.location.gps" android:required="false"/>
    <uses-feature android:name="android.hardware.location.network" android:required="false"/>
    <uses-feature android:name="android.hardware.wifi" android:required="false"/>
    <uses-feature android:name="android.hardware.microphone" android:required="false"/>
    <uses-feature android:name="android.hardware.telephony" android:required="false"/>
    <uses-feature android:name="android.hardware.bluetooth" android:required="false"/>
    <uses-permission android:name="android.permission.STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>
    <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE"/>
    <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS"/>
    <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS"/>
    <uses-permission android:name="android.permission.READ_APP_BADGE"/>
    <uses-permission android:name="com.oppo.launcher.permission.READ_SETTINGS"/>
    <uses-permission android:name="com.oppo.launcher.permission.WRITE_SETTINGS"/>
    <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_READ"/>
    <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_WRITE"/>
    <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE"/>
```

I've set `permissions` to an empty array as following : 
```json
{
  "expo": {
~~~~~~~~~~~~ SNIP ~~~~~~~~~~~~~~~~~~~
    "ios": {
      "bundleIdentifier": "com.hackingsimplified.notifyme",
      "buildNumber": "1.0.5"
    },
    "android": {
      "package": "com.hackingsimplified.notifyme",
      "googleServicesFile": "./google-services.json",
      "versionCode": 5,
      "permissions": [],
      "enableDangerousExperimentalLeanBuilds": true,
      "useNextNotificationsApi": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

I've only one file `app.js` which gets an Expo token and displays on the screen.
**App.js**
```js
import React, { useEffect, useState } from "react";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~SNIP~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
import * as Notifications from "expo-notifications";
import * as Permissions from "expo-permissions";
import { create } from "apisauce";

function App() {
  const [token, setToken] = useState(false);
  const [serverValue, onChangeserverValue] = useState("");

  useEffect(() => {
    getToken();
  }, []);

  const getToken = async () => {
    const ans = await Permissions.getAsync(Permissions.NOTIFICATIONS);
    const { status: existingStatus } = ans;
    let finalStatus = existingStatus;
    try {
      if (existingStatus !== "granted") {
        const { status } = await Permissions.askAsync(
          Permissions.NOTIFICATIONS
        );
        finalStatus = status;
      }
      let token;
      try {
        token = await Notifications.getExpoPushTokenAsync();
        setToken(token);
      } catch (err) {
        console.log(err);
      }
    } catch (err) {
      console.log(err);
    }
  };

  const sendTokenToServer = async () => {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~SNIP~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  };

  return (
    <View>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~SNIP~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    </View>
  );
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~SNIP~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
export default App;
```

## Other Details
- Expo SDK: 38.0.0
- Release channel: default
- Workflow: Managed

Do I need to eject from expo to sort this :thinking: ?

**Comment by LuD1161** [comment]
I checked the forum as well : https://forums.expo.io/t/remove-the-request-for-location-permissions-from-your-app/41488/11
Seems no solution or workaround there as well.

**Comment by LuD1161** [comment]
I think this was/should've been fixed here : https://github.com/expo/expo-cli/pull/2458
But this has still crept in, not sure exactly if that did really solve this issue.

**Comment by brentvatne** [comment]
hello, please see: https://docs.expo.io/distribution/app-stores/#android-permissions

**Comment by LuD1161** [comment]
@brentvatne can I try those changes, like pull the latest branch ( it seems to be merged in the **master** ) ?

**Comment by LuD1161** [comment]
This release should work, right :thinking: 
https://github.com/expo/expo-cli/releases/tag/expo-cli@3.27.4

This seems to have the commit merged.
But is this an issue with expo-cli only ?

**Comment by LuD1161** [comment]
Seems the release is to be in October https://blog.expo.io/the-expo-sdk-39-roadmap-36bf5137e8db

**Comment by LuD1161** [comment]
@brentvatne 
I tried following the https://github.com/expo/expo-cli/blob/master/CONTRIBUTING.md#setting-up-the-repository-for-development

and got to this : 

![image](https://user-images.githubusercontent.com/17861054/93384904-0fefcf00-f883-11ea-9a6c-4a3ee1d1b9df.png)

However I haven't compiled a package before so I am kinda confused if this is the correct way to do that.
I've cloned this from **master**

If not can you suggest a better alternative, _ejecting_ ( I don't want that currently ) ?

**Comment by byCedric** [comment]
@brentvatne is right, we made some changed but that will be shipped when we roll out SDK 39. If you _absolutely need_ to remove some of the permissions, your best bet would be ejecting and [manually exclude some of the permissions from your `AndroidManifest.xml`](https://github.com/expo/expo/blob/master/docs/pages/versions/v39.0.0/sdk/permissions.md#excluding-android-permissions-in-bare-workflow). Be aware, you have to build it yourself after doing this.

You can always "revert" back to the managed flow though, so If you are going for this approach I would recommend not committing this to the main branch.

Hope this helps!

**Comment by brentvatne** [comment]
@LuD1161 - the code in the commit you referenced runs on our build machines, and just incidentally happens to also be included in expo-cli due to the way the package is currently structured. there isn't anything that you can do on your machine to modify this on the build service currently. we're working on getting sdk 39 out so if you can deal with having these permissions in your app for a week or two then you should be able to take advantage of the improvements soon enough

**Comment by LuD1161** [comment]
Hi @brentvatne and @byCedric 
Extremely glad for the quick response.
I did `expo eject` and followed the instructions.
![image](https://user-images.githubusercontent.com/17861054/93495278-94962800-f92b-11ea-9d92-d687a9e9452c.png)

I had one doubt here :
1. After running `yarn android` which produces a debug app and also with `./gradlew buildRelease` ( after following through this [here](https://farazpatankar.com/ejecting-from-expo/) ) I got an app with the same size as previously ~25MB 
I understand it's because of `unimodules` . so how should I not include those :thinking: 
```json
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~38.0.8",
    "expo-splash-screen": "^0.5.0",
    "expo-status-bar": "^1.0.2",
    "expo-updates": "~0.2.10",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "~0.62.2",
    "react-native-gesture-handler": "~1.6.1",
    "react-native-reanimated": "~1.9.0",
    "react-native-screens": "~2.9.0",
    "react-native-unimodules": "~0.10.1",
    "react-native-web": "~0.11.7",
    "apisauce": "^1.1.2",
    "expo-notifications": "~0.3.3",
    "expo-permissions": "~9.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.11.0",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true,
  "name": "my-notifications",
  "version": "1.0.0"
}
```
Do I need to change the dependencies here :thinking: ?

**Comment by supryan** [comment]
This is actually a more critical issue than is being discussed here. We are developing an app for children and the automatic including of location permissions is preventing us from releasing an app on the Google Play Store because location permissions need to be removed in a target audience of 13 years and younger.

Ejecting still seems to include the `expo-location` package even though it's not included in my npm modules.

**Comment by brentvatne** [comment]
@supryan - you can remove the permission and the package will have no impact. you can also remove the package by excluding it from autolinking, as described in https://docs.expo.io/bare/installing-unimodules/ under "Need to exclude some unimodules that are being automatically linked?"

**Comment by supryan** [comment]
@brentvatne thanks for the quick reply! We do have `permissions: []` set in the app.json but unfortunately this still includes `android.permission.ACCESS_BACKGROUND_LOCATION` automatically. This is the main reason we can't get our app released.

**Comment by brentvatne** [comment]
ah, got it! we are releasing sdk 39 *very soon* where we revamped the permissions on android and it should be possible for you to opt out of that permissions now. if all goes well we may release this today or tomorrow

**Comment by supryan** [comment]
@brentvatne amazing thank you so much!

**Comment by supryan** [comment]
@brentvatne can confirm there are no more location permissions automatically bundled in SDK 39! However, our app still go rejected for the same reason when target audience <13 years old. Error: `You have to remove location permissions.`? Checking the bundle, I see some location stuff under "Features" but not as a permission. Any idea what's up? We reached out to Play Store support as well.

![Screen Shot 2020-09-23 at 10 11 59 AM](https://user-images.githubusercontent.com/6980704/94053134-c88ba600-fd8e-11ea-8dda-d39ae79a63ba.png)

**Comment by ridgeO** [comment]
@supryan, running into the same issue with my latest app update. Did you find a solution?

**Comment by byCedric** [comment]
I've just double-checked this by creating an Android APK using `$ expo build:android -t apk` on a simple SDK 39 project. I've added the permissions with the `android.permissions = []` in the manifest and without. If you are still having issues with this, please send us an email at `secure@expo.io` containing the following info:

- App manifest
- full app name (+ release channel, if you use them), e.g. `@bycedric/myawesomeapp`
- The list of permissions you get from the APK, you [can use the aapt tool locally](https://stackoverflow.com/questions/21091022/listing-permissions-of-android-application-via-adb).

With that, we can try and see what's going on with your app.

<details>
<summary>List of permissions <b>without defining android.permissions</b> in the app manifest</summary>
<pre>
package: com.bycedric.myawesomeapp
permission: com.bycedric.myawesomeapp.permission.C2D_MESSAGE
uses-permission: name='com.bycedric.myawesomeapp.permission.C2D_MESSAGE'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.SYSTEM_ALERT_WINDOW'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.MANAGE_DOCUMENTS'
uses-permission: name='android.permission.READ_INTERNAL_STORAGE'
uses-permission: name='android.permission.READ_PHONE_STATE'
uses-permission: name='android.permission.USE_FINGERPRINT'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='com.android.launcher.permission.INSTALL_SHORTCUT'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.READ_CONTACTS'
uses-permission: name='android.permission.READ_CALENDAR'
uses-permission: name='android.permission.WRITE_CALENDAR'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_SETTINGS'
uses-permission: name='host.exp.exponent.permission.C2D_MESSAGE'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
uses-permission: name='android.permission.USE_BIOMETRIC'
uses-permission: name='android.permission.ACCESS_BACKGROUND_LOCATION'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='com.sec.android.provider.badge.permission.READ'
uses-permission: name='com.sec.android.provider.badge.permission.WRITE'
uses-permission: name='com.htc.launcher.permission.READ_SETTINGS'
uses-permission: name='com.htc.launcher.permission.UPDATE_SHORTCUT'
uses-permission: name='com.sonyericsson.home.permission.BROADCAST_BADGE'
uses-permission: name='com.sonymobile.home.permission.PROVIDER_INSERT_BADGE'
uses-permission: name='com.anddoes.launcher.permission.UPDATE_COUNT'
uses-permission: name='com.majeur.launcher.permission.UPDATE_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.CHANGE_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.READ_SETTINGS'
uses-permission: name='com.huawei.android.launcher.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.READ_APP_BADGE'
uses-permission: name='com.oppo.launcher.permission.READ_SETTINGS'
uses-permission: name='com.oppo.launcher.permission.WRITE_SETTINGS'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_READ'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_WRITE'
uses-permission: name='com.google.android.providers.gsf.permission.READ_GSERVICES'
uses-permission: name='com.google.android.gms.permission.ACTIVITY_RECOGNITION'
uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
</pre>
</details>

<details>
<summary>List of permissions <b>with android.permissions = []</b> in the app manifest</summary>
<pre>
package: com.bycedric.myawesomeapp
permission: com.bycedric.myawesomeapp.permission.C2D_MESSAGE
uses-permission: name='com.bycedric.myawesomeapp.permission.C2D_MESSAGE'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.SYSTEM_ALERT_WINDOW'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='host.exp.exponent.permission.C2D_MESSAGE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='com.sonymobile.home.permission.PROVIDER_INSERT_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.CHANGE_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.READ_SETTINGS'
uses-permission: name='com.huawei.android.launcher.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.READ_APP_BADGE'
uses-permission: name='com.oppo.launcher.permission.READ_SETTINGS'
uses-permission: name='com.oppo.launcher.permission.WRITE_SETTINGS'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_READ'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_WRITE'
uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'

</pre>
</details>

### Using bare instead of managed?

You should be able to control _all_ of the permissions from the `AndroidManifest.xml`. [Read more on the docs](https://docs.expo.io/versions/v39.0.0/sdk/permissions/#excluding-android-permissions-in-bare-workflow).

Hope this helps!

**Comment by supryan** [comment]
@ridgeO we are still experiencing this issue unfortunately but I did follow up with @byCedric and will report back if I hear any new information.

**Comment by igorbrandao** [comment]
Hi everyone! I am having this issue as well... We just recently upgraded from SDK 36 to SDK 38 (less than a month ago) and never realized that our app requested background location permissions. We do use location features, but they are needed only when our app is foregrounded.

All we do is:

```
import * as Permissions from 'expo-permissions';

const { status: existingStatus } = await Permissions.getAsync(Permissions.LOCATION);
if (existingStatus !== 'granted') {
      const { status } = await Permissions.askAsync(Permissions.LOCATION);
}
```

And if they grant that, we use that on two occasions:

1. `getCurrentPositionAsync` and `reverseGeocodeAsync` of `expo-location` to display the country and city of the user
2. Get their current coordinates and show a <MapView /> centered on their location

Can we opt out of that background location permission while in SDK 38? That would be ideal for us, but if not and we really need to upgrade again to SDK 39 for that, we can stretch a bit more and do it.

It would be very helpful not only if we had an expo command to list all currently requested permissions (just so we don't have to fiddle with `adb`), but also if we could have expo docs on how to get rid of background location while keeping foreground location on android.

**Comment by brentvatne** [comment]
@igorbrandao - we revamped permissions in sdk 39 - for your concern about background location see [this forums post](https://forums.expo.io/t/how-to-decrease-permission-on-android/43525/6?u=notbrent). you will only be able to do that on sdk-39 and greater.

for information on fine vs coarse, check out [the android permissions documentation](https://developers.google.com/maps/documentation/android-sdk/location) - anything that uses gps will need fine, if you want something approximate based off of wifi/cellular data. if you want it to be remotely accurate you should use gps fine location.

documentation on permissions for android is here: https://docs.expo.io/versions/latest/sdk/permissions/#permissions-on-android

<hr />

i'm locking this issue now because is enough information here for people to understand what they can do to control android permissions in their apps. see https://github.com/expo/expo/issues/10206#issuecomment-700967220 and https://docs.expo.io/versions/latest/sdk/permissions/#permissions-on-android to learn more.
