### ISSUE TITLE
[SDK39] Animated node with ID 2 already exists

### ISSUE THREAD

**Issue by Woong25** [expo/expo#10282]
### Summary of Issue 
`Animated node with ID 2 already exists` error after updating to sdk 39
![image](https://user-images.githubusercontent.com/44948010/93869016-393ab000-fd06-11ea-905e-3f073bcc06db.png)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

`Expo CLI 3.27.7 environment info:

    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\ST\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.13
      react-navigation: ^4.4.0 => 4.4.0
    Expo Workflow: managed
`

"react-native-skeleton-content": "^1.0.20"
"react-native-reanimated": "~1.13.0",

 
### Steps to Reproduce
This happens when you update SDK 39.

### Expected Behavior vs Actual Behavior
I updated all the packages, but the results were the same.
Should I wait for an update from another package?

In the previous case, it seems that the sdk has been updated and has been modified!..
https://github.com/alexZajac/react-native-skeleton-content-nonexpo/issues/15#issue-637139256

**Comment by sjchmiela** [comment]
Hey! This problem usually occurs when there are more than one `react-native-reanimated` version in the project. Try running `yarn why react-native-reanimated` / `npm ls react-native-reanimated` to see what versions of the dependency are installed. Most probably you'll have at least two: `v2.0.0-alpha.6` (from `package.json`) and `v1.x.x` (installed by some other dependency). Could you please verify if that's the case?

**Comment by Woong25** [comment]
Wow.. 
In my case, the result came out like this.

`yarn why v1.22.4`
`[1/4] Why do we have the module "react-native-reanimated"...?`
`[2/4] Initialising dependency graph...`
`[3/4] Finding dependency...`
`[4/4] Calculating file sizes...`
`=> Found "react-native-reanimated@1.13.0"`
`info Has been hoisted to "react-native-reanimated"`
`info This module exists because it's specified in "dependencies".`
`info Disk size without dependencies: "2.38MB"`
`info Disk size with unique dependencies: "10.9MB"`
`info Disk size with transitive dependencies: "18.72MB"`
`info Number of shared dependencies: 12`
`=> Found "react-native-skeleton-content#react-native-reanimated@1.9.0"`
`info This module exists because "react-native-skeleton-content" depends on it.`
`info Disk size without dependencies: "816KB"`
`info Disk size with unique dependencies: "9.32MB"`
`info Disk size with transitive dependencies: "17.14MB"`
`info Number of shared dependencies: 12`
`Done in 1.61s.`

 

So I solved it by adding the code below to the `package.json` file!

`
"resolutions": {
    "**/react-native-reanimated": "1.13.0"
  }
`


Thank you.

**Comment by aayushsin** [comment]
The issue is still existing my case where I just have 1 version of react native animated module.

yarn why react-native-reanimated --->
yarn why v1.22.0
[1/4] Why do we have the module "react-native-reanimated"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "react-native-reanimated@1.13.1"
info Has been hoisted to "react-native-reanimated"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "2.14MB"
info Disk size with unique dependencies: "10.67MB"
info Disk size with transitive dependencies: "18.48MB"
info Number of shared dependencies: 12
Done in 2.48s.

>npm ls react-native-reanimated
yush-app@0.1.0 D:\Users\Aayush\workspace\3xceed\yush-mobile
`-- react-native-reanimated@1.13.1

I just upgraded to:
"expo": "^39.0.3",
 "react-native-reanimated": "^1.13.1",
 "react-native": "^0.63.3",

**Comment by samixp02** [comment]
reinstall packages and ignore peer denpendencies for that package
