### ISSUE TITLE
Notifications.getExpoPushTokenAsync() network error on Android, incomplete on iOS.

### ISSUE THREAD

**Issue by NCMoseley** [expo/expo#10339]
### Summary of Issue

We have a production app that has notifications enabled. On September 18th, we started to log errors similar to the errors generated when Notifications.getExpoPushTokenAsync() is run on an iOS simulator. ('token' is not a string, or 'token' null). 

Our user's phones, on both operating systems, which were enrolled previous to Sept 18 still will receive notifications, but for any new users or for our test department, we are unable to successfully set the tokens in the devices. 

On Android, the logged token we receive from Notifications.getExpoPushTokenAsync() === 

```
Object {
  "data": "ExponentPushToken[ZREntTDF1FC2lCmd-sKI75]",
  "type": "expo",
}
```

But is followed by a client-side error: 

```
Network request failed

Stack trace:
  node_modules/whatwg-fetch/dist/fetch.umd.js:527:17 in setTimeout$argument_0
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:135:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:387:16 in callTimers
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:425:19 in __callFunction
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:6 in __guard$argument_0
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:373:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:4 in callFunctionReturnFlushedQueue
  [native code]:null in callFunctionReturnFlushedQueue
```

With iOS we receive the same data from the call, 

```
Object {
  "data": "ExponentPushToken[vgcnAQMXZ073nHbfr_Wysj]",
  "type": "expo",
}
```

But our API does not register the "data" to be a string. Leaving the client-side we can log the token on its way over and Javascript tells us it is in fact a string. 

Has anyone encountered this? Our code hasn't changed since it was working a few weeks ago. 

### Environment - 

```
Expo CLI 3.22.3 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9 
      react: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2 
```

### Expected Behavior vs Actual Behavior

Notifications.getExpoPushTokenAsync() is not resolving correctly on both platforms.

**Comment by byCedric** [comment]
Hi @NCMoseley, I'm a bit confused about your issue report. `Permissions.getAsync` never sends out a HTTP request, this uses the platform specific OS methods to gain access to protected APIs. But what you are reporting is related to notifications, not the permissions of the notifications.

[As you can see the `Permissions.getAsync/Permissions.askAsync`](https://docs.expo.io/versions/v39.0.0/sdk/permissions/#permissionresponse) returns an object containing the status of the permission, something like:
```
interface PermissionResponse {
  status: 'granted' | 'undetermined' | 'denied';
  granted: boolean;
  expires: 'never' | number;
  canAskAgain: boolean;
  permissions: { // an object with an entry for each permission requested
    [permissionType: string /* PermissionType */]: PermissionInfo;
  };
}
```

Could you elaborate on this, and provide a reproducible example? With that, we can dig right in and investigate this for you.

Hope it helps

**Comment by NCMoseley** [comment]
Forgive me, I made a typo. I have included the correct function that we are struggling with. I will start to put a demo together that demonstrates issue this for you. Thank you for your quick response.

**Comment by sjchmiela** [comment]
Hey @NCMoseley! Have you had time by any chance to put up a demo?

I'll try to respond with what I think could help you resolve the issue, but I'm not sure if that will suffice:

`getExpoPushTokenAsync` does call `fetch` and does send a network request, but what's important is that it's run inside the method, so if this library call would fail, you wouldn't have received the token at all

https://github.com/expo/expo/blob/96bc848c41a4cea9e004b8d7f79e438f3f900cf1/packages/expo-notifications/src/getExpoPushTokenAsync.ts#L62-L73

Moreover, the `Network request failed` is a general `fetch` fail and we do wrap the error with `CodedError`: https://github.com/expo/expo/blob/96bc848c41a4cea9e004b8d7f79e438f3f900cf1/packages/expo-notifications/src/getExpoPushTokenAsync.ts#L68-L73, so that must come from somewhere else.

Do you do any network request after fetching the Expo push token? How do you send the token to your server? Is there any chance the request is missing some important HTTP headers? As a reference, here's a pull request we had to implement for the request to be handled properly on Expo servers: https://github.com/expo/expo/pull/9332.

**Comment by NCMoseley** [comment]
@sjchmiela Thank you for your attention to this issue. I set out to make a demo today, and I am unable to reproduce the issue. I am logging data as expected and not getting the network error^^. I know we haven't changed anything related to this, I will report back if something changes.

**Comment by sjchmiela** [comment]
Sounds great! If so, let me close this issue tentatively, if this issue ever arises again and you're able to pinpoint the culprit to Expo code, feel free to reopen this issue or open a new one! 🙂
