### ISSUE TITLE
Another "React Native version mismatch" question

### ISSUE THREAD

**Issue by sglickman** [expo/expo#10355]
Hi,

I've inherited a project that hasn't been updated in about two years, and am having a little trouble getting started.

I installed the latest version of XCode, and when I try to launch the iOS simulator (from `expo start`), I see the dreaded error

```
console.error: "React Native version mismatch.

JavaScript version: 0.55.4
Native version: 0.63.2-undefined

Make sure that you have rebuilt the native code. If the problem persists try clearing the Watchman and packager caches with `watchman watch-del-all && react-native start --reset-cache`."
```

I'm a little bit unclear on where these version numbers are coming from. 

package.json contains, among other things, the following lines:
```
"dependencies": {
  ...
  "expo": "^28.0.1",
  ...
  "react-native": "^0.55.4",
  ...
}
```

I changed this from `"react-native": "https://github.com/expo/react-native/archive/sdk-28.0.1.tar.gz"` (and before that, it was `"react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz"`; nothing has worked so far).

Meanwhile, app.json specifies `"sdkVersion": "28.0.0"`. 

I *believe* version 28 specifies react-native version 0.55.4... so where is the newer "native version" of "0.63.2-undefined" coming from?

**Comment by sglickman** [comment]
I should also include the output of `expo diagnostics`:

```
  Expo CLI 3.27.7 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.0.18 - /usr/local/bin/bash
    Binaries:
      Node: 12.18.4 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.6 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.2
        System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^28.0.1 => 28.0.1 
      react: 16.3.1 => 16.3.1 
      react-dom: ^16.4.1 => 16.4.1 
      react-native: ^0.55.4 => 0.55.4 
      react-navigation: 2.17.0 => 2.17.0 
    npmGlobalPackages:
      expo-cli: 3.27.7
    Expo Workflow: managed
```

**Comment by byCedric** [comment]
Hi @sglickman! If you get a React Native version mismatch error like the one you mentioned, it means two things.

- Your JS-side code is targeting React Native `0.55.4`
- Your Expo Client is targeting React Native `0.63.2`

I'm not 100% if this is caused by a newer version of the Expo Client, but I think it is. Unfortunately, we don't support SDK 28 anymore. So the best thing you could do, without having to upgrade, is to eject and build the version manually. [Here you can see a walkthrough of a bare project](https://docs.expo.io/bare/exploring-bare-workflow/), it might help. At the moment we support SDK 36 and up. Keep in mind that both iOS and Android have higher minimum requirements to build against.

Hope this helps!

**Comment by brentvatne** [comment]
@sglickman - expo client only supports about a years worth of sdk releases at any given time. currently, this means sdk 36, 37, 38, and 39. for newer versions we've added the ability to continue to run the app in expo client in simulators/emulators even after it's been removed from the app store/play store client, but this wasn't available in sdk 28 yet. you could try your luck running `expo client:install:ios` / `expo client:install:android` still

you can see the supported versions by your expo client app here:

<img width="385" alt="Screen Shot 2020-09-24 at 10 48 04 AM" src="https://user-images.githubusercontent.com/90494/94180802-6d6fb700-fe53-11ea-9de5-99179b40bb2a.png">

i would recommend upgrading the project to sdk 36 at least. this may be a bit tricky since the project is very old, but it'll be a heck of a lot easier than upgrading if it weren't a managed expo project :P see https://docs.expo.io/workflow/upgrading-expo-sdk-walkthrough/ and follow the instructions
