### ISSUE TITLE
[Media Library] sortBy creation time failing with EXIF err.

### ISSUE THREAD

**Issue by natysoz** [expo/expo#10398]
Using get assets with getAssersAsync , working fine on emulators using options like 
sortBy: [[ SortBy.creationTime, false ]]

but when turn it to true (means new images / assets first and old images last)

its throw an error (ONLY on true android devices )
- "Could not read file or parse EXIF tags"

so you can work with it on real devices but only getting the older assets first for some reason

im building a package    =>  expo-images-picker 
https://www.npmjs.com/package/expo-images-picker
but i saw the package broken when upgrading from sdk 38 to 39.

you can easy reproduce on real android device only , with alot of images , just use 
sortBy: [[ SortBy.creationTime, false ]]
or
sortBy: 'creationTime'

and you will get this msg.

The Expected Behavior is to catch this exceptions throw this EXIF tag error that comes from GetAssets.java line 63 
and allow sorting both ways even when they are broken images

Actual behavior is that on real devices there are some assets that downloaded or moved into the gallery
which missing for example "CreationTime" and probably cause this execption .

    "expo": "^39.0.0",
    "react": "16.13.1",
    "expo-media-library": "~9.2.1",

**Comment by barthap** [comment]
It seems that this error already happened in SDK versions <= 38, but it wasn't displayed to the user and the promises were never resolved, because the only change in SDK 39 is the error handling:
https://github.com/expo/expo/commit/c6f36778f2442fb595e935338ab87f131c998d79#diff-d1e98b2a272f0cb479864153884ce4fc

I'll try to investigate it more, because media order shouldn't have any impact on that IOException.
Are you using bare workflow? And could you please provide minimal reproducible example on [Snack](https://snack.expo.io/)?

**Comment by natysoz** [comment]
There you go

https://snack.expo.io/@natysoz/sdk-39-exif-issue

just jump from Expo 38 to Expo 39 and see how in 38 and lower its crashing without any error ,
also make sure to clear the application cache when jumping back and forward and wait a min or 2.

the new error handling solve the issue but i am afraid a lot of users will not upgrade so fast to sdk 39.

anyhow i upgrade my npm package to support for now only SDK39 

but would be nice if we understand why its crashing on SDK38 .

my idea is that ,

it require sending the "after" on expo SDK38 no matter if thats the first or 2nd time u ask for assets,
sending  '0' ,will crash real device because there is no Asset reference with 0.

on real device on the first time you getting the assets you cant supply the after ..
because u never get a list before...
on Emulator the '0' will work because this is how the emulator works its starts from 0.
on real device the after expected Asset Type Reference which you cant send even when sending null
it will crash...

**Comment by barthap** [comment]
The demo is working for me in SDK 39 on real device, no crashes for now. It if crashed on SDK 39, it's obvious that it could crash without error on SDK 38, just because of the diff I linked in my previous comment.

Regarding to `after` option: I believe this option is totally unrelated to this issue. You shouldn't use the option when you call `getAssetsAsync()` for the first time because you don't know real asset IDs and hoping that asset ID "0" exists on the phone is shooting yourself in the foot.

Also, I'm not going to focus on why it was crashing on SDK 38 end earlier, because MediaLibrary was really buggy on these versions and there could be dozens of reasons for this call to crash.

**Comment by natysoz** [comment]
i see , ok thinking that it might help to fix also 38 and early versions , 
in 39 its not crashing so i guess we can close the issue then .

**Comment by eyu0415** [comment]
I got this error too.

I'm working in Bare Workflow

**Comment by mackan92** [comment]
I'm having the same issue. I'm working in managed workflow on Expo SDK 41.0.0 ad expo-media-library 12.0.2. Have read all similar issues but no luck yet. Tried to add permissions necessary in app.json despite it shouldn't be necessary in managed workflow. Has anyone solved this yet?

**Comment by maelthi** [comment]
@mackan92 did you solve this error ? I got it too

**Comment by natysoz** [comment]
guys please update to SDK 42 and try again

**Comment by natysoz** [comment]
well there is no fix as i can see it 

if images with unknown source like telegram , not all , but some of them , contain no exif and meta data , media library will failed

i suggest adding a try catch solution in the native code but no one really answers

**Comment by maelthi** [comment]
@natysoz yes thanks, not gonna use it anyway

**Comment by barthap** [comment]
If you guys open a new issue, I'll have a good foundation to fix it 😄  

The problem really exists - the "No EXIF data for this picture" is treated the same as "Picture file does not exist Error" and both throw, while only the latter one should, and the former should just set `EXIF data = null`.
