### ISSUE TITLE
Use a white loading indicator on the loading screen on iOS?

### ISSUE THREAD

**Issue by gregblass** [expo/expo#104]
I've got a dark image with white text for my loading screen on iOS (not making an Android version yet). It looks great except for the loading indicator still being dark. Is it possible to change it to white?

![splash-sm](https://cloud.githubusercontent.com/assets/279927/24839329/e91a748e-1d25-11e7-92a3-db274baffe39.jpg)

**Comment by sonaye** [comment]
in your `exp.json`:
```
"loading": {
    "loadingIndicatorStyleExperimental": "light"
  },
```

**Comment by gregblass** [comment]
Thank you so much that worked like a charm!

**Comment by Palisand** [comment]
I am getting a warning when I use this, but it still works.
`loading additionalProperty "loadingIndicatorStyleExperimental" exists in app.json when not allowed.`
It's `app.json` since I'm using CRNA.

**Comment by gregblass** [comment]
Yep there is still a warning. I reached out to the Expo team in Slack and their response was that they want to refactor the loading screen as a whole and handle a couple/number of different things. So at some point this will be addressed.

**Comment by gregblass** [comment]
But yeah, in the end there is nothing that the user will see and this works just fine besides the warning in the Expo XDE.

**Comment by Palisand** [comment]
@gregblass thanks for the info. It's exciting to hear of upgrades to expo's loading functionality. Currently, in order to have a nice fade-to-app-from-loading-screen effect, I've resorted to making a "duplicate" AppLoading component that is Animated (set to fade out on mounting) and gets rendered in front of the target screen after loading. Hopefully they implement exit animations so that we don't have to!
