### ISSUE TITLE
Splash screen background without image briefly visible before app is displayed

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#10436]
### Summary of Issue 

Notice the splash image disappears before the splash screen does.

![splashlogo](https://user-images.githubusercontent.com/90494/94500877-40096d00-01b5-11eb-89e4-a42db438c2eb.gif)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Android, bare.
 
### Steps to Reproduce

I think the easiest way to do this is:

- Initialize a project with the tabs template
- Set some non-white backgroundColor for splash in app.json
- Eject the project so it is configured

### Expected Behavior vs Actual Behavior

The image should remain visible as long as the background is visible.

**Comment by brentvatne** [comment]
related: https://github.com/expo/expo/pull/10130

**Comment by bbarthec** [comment]
@brentvatne, the problem here is not so easy to be resolved 🤔 
My idea for the root cause for this issue:
1. How the app is configured?
  - we want some meaningful splash behaviour from the beginning of the application launch, so we configure the application background color (the root window of the application) 
2. What's happening in runtime?
  - the app starts and shows it's background (the solid color in this case) - this background will be there for the whole app life
  - `expo-splash-screen` mounts it's view (with the very same color & additional image), so we see the image appears after a fraction of time
  - (optional) we instruct `expo-splash-screen` to keep the `SplashScreen` shown and render no content (the actual RN application has no content views/the `ReactRootView` is most possibly having the transparent background)
  - ReactNative creates some view hierarchy and instructs the `expo-splash-screen` to hide the `SplashScreen` or we intentionally hide the `SplashScreen` via `hideAsync`, but we still still need to render some app content (I assume to this point the JSApp was rendering `null`)
  - Android is performing it's tasks
    - removes the `SplashScreen`
    - creates the new view hierarchy that is created by RN
    - this is taking some time
  - 🔴 (culprit here) 🔴 we're at the state in which:
    - the app is showing it's background (this is constant behaviour) - solid color in this case
    - the `expo-splash-screen` is showing no view
    - the RN app is creating the app content and the ReactRootView (the view that serves as the mounting point for the RN app) is waiting for some children
    - ReactRootView is apparently transparent at this point in `Bare Workflow`
  - eventually we're given the app content, so the application background is finally covered by some views

**Comment by bbarthec** [comment]
The solution would be to do sth like this:
```tsx
import * as React from 'react';
import * as SplashScreen from 'expo-splash-screen';
import { View } from 'react-native';

function useSplashScreen(loadResources: () => Promise<void>) {
  const [isSplashScreenShown, setSplashScreenShown] = React.useState(true);
  React.useEffect(() => {
    (async () => {
      await SplashScreen.preventAutoHideAsync(); 
      await loadResources();
      setSplashScreenShown(false); // instruct the app that the splash is already hidden, but
      setTimeout(SplashScreen.hideAsync(), 500); // hide the splash screen a fraction of time later
    })();
  }, []);
  return isSplashScreenShown;
}

export default () => {
  const isShowingNativeSplashScreen = useSplashScreen(
    () => new Promise((resolve) => setTimeout(resolve, 4000))
  );

  if (isShowingNativeSplashScreen) {
    return null;
  }
  
  // once we reach this point, the native code was already sent the signal to hide native SplashScreen view, but the RN view hierarchy is yet to be assembled (and that is taking a little more time than simply removing the native SplashScreen?)
  // therefore we need hide the native SplashSreen once the RN views are actually rendered? we can use `onLayout` method maybe?

  return (
    <View style={{ flex: 1 }}>
    </View>
  );
};
```

**Comment by Ashoat** [comment]
I experienced this Android issue as a regression when I updated to `expo-splash-screen@0.6.1` (currently `latest` on npm). I bisected the issue to 0.6.0, so if anybody wants to avoid it for now I'd suggest sticking to 0.5.0.

@bbarthec - Do you know which commit introduced this issue, and why/how? If it's not easy to solve, and requires an API change to fix, then I'm curious why it worked fine before 0.6.0. I guess there must have been a change introduced in 0.6.0 (probably in 2770008129aef794dcdf5fcdaa35ef5056b6ff29) that caused the bug, and an API change is the only way to keep this change while fixing the bug?

**Comment by Ashoat** [comment]
Actually, I can't use 0.5.0 because of the iOS `SplashScreen.preventAutoHide` issue introduced in 0.4.0. It's not fixed until 0.6.1, at which point Android is broken as described above...

I mostly just wanted #9451 to fix the bug where the Android emulator crashes whenever you refresh in debug mode. I'll probably just stay on 0.3.1 and use `patch-package` to get that fix.

As always, big thank you for the contributions Expo makes to the community. But if I can give some frank feedback, my experience working with `expo-splash-screen` so far hasn't been great. I had to read a bunch of code to figure out missing parts of the documentation when I first installed 0.3.1, and it seems like several versions since then have introduced regressions.

**Comment by brentvatne** [comment]
from speaking with @bbarthec, this reason that this happens is because the behavior of `hideAsync()` changed slightly since the previous release.

`hideAsync()` currently does exactly what it says: it hides your splash screen, and it does it immediately. it used to **not** do this immediately. previously, calling `hideAsync()` was more of a signal to say "hey, you can now hide when you would have hidden if i had not prevented auto hide". the heuristic that we use for auto hiding is to wait until there is a child view attached to the react root view, this would happen when the user has been able to render some content in their app. to resolve this, we are going to change the behavior back so that `hideAsync()` by default will behave how it did before. this is generally what people want. we will make the current available behavior with `hideAsync({ immediate: true })`.

before we ship this we are trying to figure out an issue introduced recently in react-native that makes auto hiding a bit more complicated: the `AppContainer` component was changed to always render a view on ios (it's collapsed on android), so we can't assume that there will be no child views until the app has rendered one. we don't want to couple ourselves to a specific number of views (wait until > 1 child views on ios, > 0 on android) because if `AppContainer` or other react-native internals change again, then this won't work, and we'd need to add some switches on react-native versions inside of expo-splash-screen to handle this.

so, for now, a good way to handle this is to only call `hideAsync()` when your app has been rendered. you could, for example, have a root view that calls `hideAsync()` the first time `onLayout` is called. or as @bbarthec suggested above, add some delay of x milliseconds, to give your app time to render.

**Comment by Ashoat** [comment]
Hey, just wanted to check if there were any updates on this front. I noticed there had been a couple new releases since October, but they don't seem to have any relevant fixes in the changelog.

**Comment by mofengfs** [comment]
@Ashoat 
Yes, I have not seen the relevant content update. I think this kind of common problem should be solved sooner.

**Comment by brentvatne** [comment]
@Ashoat @mofengfs - i'm not sure what we can do about this because there is no reliable way to detect when the first view has been rendered by the user's application - we can only detect when react-native has first rendered a view, which is different.

i plan to update the splash screen docs for sdk 41 to provide guidance on how you can hide the splash screen at the appropriate time, eg: add `onLayout` to the root view in your app and hide the splash screen when that fires.

**Comment by mofengfs** [comment]
@brentvatne 
👍
