### ISSUE TITLE
[SDK 39] iOS interactive notifications don't work

### ISSUE THREAD

**Issue by bill-pairaktaridis** [expo/expo#10467]
### Summary of Issue 

As of SDK 39, interactive notifications don't work for iOS with the new `expo-notifications` package. The arguments expected from the API also seem wrong. It expects `_category` and that's not what's in the documentation

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```

  Expo CLI 3.27.12 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3, 29.0.2
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.7/11E801a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-navigation: ^4.4.0 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.27.12

```

Targeting both Android and iOS but currently it's an iOS issue

 
### Steps to Reproduce

Send a notification via the API with the following body:

```
{
    "to": "ExponentPushToken[****************]",
    "title":"New chat message",
    "body": "world",
    "categoryId": "chat",
    "categoryIdentifier": "chat",
    "_category": "chat",
    "category": "chat"
}
```

None of the category related arguments work. `_category` works for Android and you get the proper interactive notification as was setup in the app

### Expected Behavior vs Actual Behavior

Should get the ability to interact with the notification in both Android and iOS

**Comment by cruzach** [comment]
hi! I'm assuming you're testing in the Expo client app? When using notifications categories there, and sending notifications through Expo's push notification service, you'll need to prefix the category with your experience ID, so the `_category` you send to Expo is: `@yourUsername/yourProjectSlug-chat`. Adding the category ID will work with the Expo push service, but it's not fully public (hence the underscore), since we may want to change that parameter to match the `expo-notifications` package more closely. 

The arguments expected aren't wrong- the Expo push service is different from the `expo-notifications` package. [Here's the documentation for what the Expo push service expects](https://docs.expo.io/push-notifications/sending-notifications/#message-request-format), and what's documented in the `expo-notifications` docs are specifically for the `NotificationContent` Type, used for methods like `presentLocalNotificationAsync`. In your example, presenting a _local_ notification like this:
```
await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail! 📬",
      body: "Here is the notification body",
      data: { data: "goes here" },
      categoryIdentifier: "chat",
    },
    trigger: { seconds: 2 },
  });
```
would work, as well (local notifications don't need that experience prefix since they aren't going through Expo's push service.

**Comment by bill-pairaktaridis** [comment]
@cruzach I'm sorry but where in the link you sent is `category` mentioned? [Here](https://docs.expo.io/versions/latest/sdk/notifications/#managing-notification-categories-interactive-notifications) it mentions `categoryIdentifier` as the expected `NotificationContent`

I just feel like the documentation for the interactive notification is incomplete or at least unclear

**Comment by cruzach** [comment]
It's part of `expo-notifications` because that's a client-side library that you can use with _any_ notification service (APNs, FCM, Onesignal, Expo). And you _can_ consider it ready for use, we won't suddenly stop supporting that key with no warning. But until it's fully released I don't really think we want to document it

If you're uncomfortable with that, then I would suggest following this guide on communicating directly with APNs and FCM - https://docs.expo.io/push-notifications/sending-notifications-custom/

**Comment by bill-pairaktaridis** [comment]
Are there plans on officially support channels through the Expo push service?

**Comment by cruzach** [comment]
yes, definitely

**Comment by webjay** [comment]
It seems `_category: '@webjay/emojoe-activity'` works in the Expo app, and in standalone.
