### ISSUE TITLE
Expo crashes with no error

### ISSUE THREAD

**Issue by Florent75** [expo/expo#10489]
Hi,

We have found a small bug on Expo hapenning only on Android.

On SDK 38, 
I misused the style attribute, and more precisly the "alignItems" and put "start" instead of "flex-start".

The result :
- on iOS : everything works well
- on Android : Expo crashes with no error, no logs.

Hope you could fix it in a future release,

Regards

**Comment by byCedric** [comment]
Hi @Florent75, thanks for the heads up. Unfortunately, this is a limitation from React Native itself. If we want to fix it, we have to fix it there. I fully agree with you that the crash shouldn't happen, but there is no "clean" way for us to prevent this from happening. That being said, I think the React Native core team is looking to improve the typing support (see [this talk from Eli White at React Native EU](https://youtu.be/DduUntL2Sv4?t=2121)).

One suggestion I want to give is using TypeScript. This can help to check the props and types when developing and doesn't impact the runtime performance in any way (because it's transpiled to plain JavaScript). This would detect the invalid `alignItems` prop on your component 😄 

Hope this helps!
