### ISSUE TITLE
Fabric iOS?

### ISSUE THREAD

**Issue by JulianKingman** [expo/expo#105]
I just noticed some errors when building for iOS, saying that fabric is not allowed, and that in the docs for `exp.json`, it only mentions fabric for Android. Is this on purpose? Will fabric be allowed on iOS?

**Comment by terribleben** [comment]
TL;DR not any time soon.

Here's some information about it. This link hasn't been deployed to our docs yet; it will go out with SDK 16. In particular, see the explanation under "What about Native Errors?"

https://github.com/expo/expo-docs/blob/master/versions/unversioned/guides/errors.md

**Comment by JulianKingman** [comment]
Yeah, the point about native errors makes sense. What about other fabric features, like answers?

**Comment by terribleben** [comment]
From our past investigation of this, it seems that Fabric's iOS library configures itself at build-time for all Fabric-related services (under the assumption that everybody needs to upload their debug symbols at the minimum, regardless of other services). Therefore although we can theoretically configure an iOS Fabric key at runtime, it will never run their build hook, and so the app will never show up in your Fabric dashboard.

(Actually, the iOS standalone app builder _does_ pay attention to `config.fabric`, it just doesn't do anything, so we removed it from the docs.)

They have the same requirement on Android, but our standalone app builder actually does build the java APK from scratch on demand, so we're able to support this in that case.

Right now it's infrastructure-prohibitive for us to build iOS from source on demand, since that tooling must run on a Mac. I wish I could give a better answer about Fabric, but their configure-during-build requirement seems to be a blocker right now.

**Comment by dikaiosune** [comment]
Hi! Since we're now tracking feature requests on Canny, I've [created one](https://expo.canny.io/feature-requests/p/support-fabric-native-errors-on-ios) there. Thanks!
