### ISSUE TITLE
BareBones Expo project crashes on UleFone

### ISSUE THREAD

**Issue by JeffHooper** [expo/expo#10523]
### Summary of Issue 

Our company recently purchased several UleFone Armor X5 Android devices to deploy our app to, however I have not been able to stop our app from crashing on start-up with these devices. I have ran the app on at least 6 other phone models with no problem at all. I decided to build a new bare bones project and deploy that to see if there was a library or any code that this phone just didn't like for some reason. However, even with the bare bones project the app still crashes on start up and throws no errors. At this point it appears to be an Expo compatibility with this phone, but even still it doesn't make a lot of sense as the phone is running Android v10 and I have ran this app on other phone I have with the same Android version and it runs with no problem at all. I was able to gather some logs about the crash using adb logcat, and the stack trace looks identical for both the bare bones app and my app on crash.

It may be worth mentioning that the app will run on the phone if running locally through expo rather than building and installing an APK.

### Environment

- Targetting Android version 10

10-02 09:08:17.231 7366 7366 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jeffh79.testapp/host.exp.exponent.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3326) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3465) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2069) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:107) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.os.Looper.loop(Looper.java:214) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7417) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 10-02 09:08:17.231 7366 7366 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference

### Reproducible Demo

- No need for a demo, as any code at all, including a basic "hello world" app will crash, but only on UleFone Armor X5 running android 10.  All other phones I've tested on, work.
 
### Steps to Reproduce

- The only way to reproduce this would be to obtain a UleFone and install an APK that was built from Expo.

### Expected Behavior vs Actual Behavior

- All Expo Apps crash on start up

**Comment by brentvatne** [comment]
hi there! we don't have one of these phones to test on, so we will need your help to understand the issue here. can you try ejecting the app and seeing if building through android studio works? if it doesn't, you can debug from there, i'll be curious to hear what you find!

also, i know it seems silly to include a reproducible demo even if it's just a "hello world" app but you'd be surprised how often there is some small change that the developer thinks is inconsequential actually is responsible for the issue they are seeing, this is why we ask for reproducible demos. so if you can share the repository and ideally a link to the expo build page for the build that you are trying on your device it would be helpful.

**Comment by JeffHooper** [comment]
I won't be back into the office until Monday to provide and code or links,
but I have already ejected from Expo and built through android studio. The
app runs fine when built in this manner.

**Comment by JeffHooper** [comment]
Sorry for the delay, had a family issue that came up last week and was out of town for the entire week.

Unfortunately I am unable to share a the build as this is not a public facing app and contains sensitive information for our clients. We do not have to use the Ulefone for our project, as I've had no problem building on any other device to this point. However, we do not always provide the devices to our clients.  Sometimes they prefer to use existing devices.  My fear is that we may run into other devices in the future that have the same problem that we are currently experiences with the Ulefone.

At this point, I'm unsure what might help

**Comment by stevedenman** [comment]
Hi, I've had a report of what appears to be the same issue with our managed app (SDK 38) on a UleFone Armor 7 running Android 10. Seems to running fine on a wide range of other Android 10 devices.
Here's the stacktrace;
`
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3326)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3465)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2069)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7417)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
Caused by: java.lang.NullPointerException: 
  at android.os.Parcel.createException (Parcel.java:2077)
  at android.os.Parcel.readException (Parcel.java:2039)
  at android.os.Parcel.readException (Parcel.java:1987)
  at android.app.IAppTask$Stub$Proxy.moveToFront (IAppTask.java:253)
  at android.app.ActivityManager$AppTask.moveToFront (ActivityManager.java:4281)
  at host.exp.exponent.kernel.Kernel.moveTaskToFront (Kernel.java:969)
  at host.exp.exponent.kernel.Kernel.openShellAppActivity (Kernel.java:420)
  at host.exp.exponent.kernel.Kernel.openManifestUrl (Kernel.java:619)
  at host.exp.exponent.kernel.Kernel.openManifestUrl (Kernel.java:601)
  at host.exp.exponent.kernel.Kernel.openExperience (Kernel.java:539)
  at host.exp.exponent.kernel.Kernel.openDefaultUrl (Kernel.java:535)
  at host.exp.exponent.kernel.Kernel.handleIntent (Kernel.java:512)
  at host.exp.exponent.experience.DetachActivity.onCreate (DetachActivity.java:37)
  at android.app.Activity.performCreate (Activity.java:7817)
  at android.app.Activity.performCreate (Activity.java:7806)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1306)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3301)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3465)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2069)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7417)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)
Caused by: android.os.RemoteException: 
  at com.android.server.wm.ActivityStarter.shouldAbortBackgroundActivityStart (ActivityStarter.java:1131)
  at com.android.server.wm.AppTaskImpl.moveToFront (AppTaskImpl.java:119)
  at android.app.IAppTask$Stub.onTransact (IAppTask.java:135)
  at android.os.Binder.execTransactInternal (Binder.java:1021)
  at android.os.Binder.execTransact (Binder.java:994)
`

**Comment by brentvatne** [comment]
if someone with one of these phones can try to reproduce it locally and debug the issue it would be helpful. we don't have one and i'm not sure what could be causing this. perhaps there were some vendor-specific android operating system customizations, if anyone knows of documentation of other projects that have encountered and resolved issues with the device that would be useful to hear as well

**Comment by JeffHooper** [comment]
The stack trace that I provided above is about the only thing I can provide which came from adb when I attempt to launch the app.  The crash only happens when you install the APK on the phone, so it's not possible to debug through the metro bundler or by any other means that I'm aware of. I had been using the UlePhone all along through metro bundler for testing purposes with no problem at all and was only recently that I actually ran a build and put the APK on the phone.

**Comment by JeffHooper** [comment]
Just did a build for the playstore and installed the app on the phone from there.  The stacktrace looks a little different when doing it this way

`
10-15 10:34:09.766  1112  1130 W WindowManager: Token{a884cd5 ActivityRecord{eb27d8c u10 com.hotspot.lprscanner/host.exp.exponent.MainActivity t1000081}} failed creating starting window
10-15 10:34:09.766  1112  1130 W WindowManager: android.content.res.Resources$NotFoundException: Resource ID #0x7f0e0001
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:251)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:905)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.content.res.Resources.getDrawable(Resources.java:845)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.content.Context.getDrawable(Context.java:687)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.internal.widget.ToolbarWidgetWrapper.setIcon(ToolbarWidgetWrapper.java:322)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.internal.widget.ActionBarOverlayLayout.setIcon(ActionBarOverlayLayout.java:754)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2837)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2181)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.server.policy.PhoneWindowManager.addSplashScreen(PhoneWindowManager.java:3388)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.server.wm.SplashScreenStartingData.createStartingSurface(SplashScreenStartingData.java:56)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.server.wm.AppWindowToken$1.run(AppWindowToken.java:2226)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:883)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.os.Looper.loop(Looper.java:214)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-15 10:34:09.766  1112  1130 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
`

**Comment by kubala887** [comment]
Hi! Similar problem occured to me today on Ulefone Armor X5. The solution is to turn off "Virtual key" in Navigation Bar settings. It's a little bit annoying as the default gesture navigation is crappy... but at least all apps are working now.

**Comment by JeffHooper** [comment]
> Hi! Similar problem occured to me today on Ulefone Armor X5. The solution is to turn off "Virtual key" in Navigation Bar settings. It's a little bit annoying as the default gesture navigation is crappy... but at least all apps are working now.

I can confirm that this fix also worked for me.  A little too late as I rebuilt the app outside of Expo in order to use these phones, but it's sure good to know going forward.

**Comment by rvieceli** [comment]
Hello, @kubala887 and @JeffHooper, I have the same problem, but I don't have a Umidigi device to test. What exactly is "turn off Virtual key"? I tried to see in the react navigation documentation but I failed. Can you help me?

**Comment by JeffHooper** [comment]
> Hello, @kubala887 and @JeffHooper, I have the same problem, but I don't have a Umidigi device to test. What exactly is "turn off Virtual key"? I tried to see in the react navigation documentation but I failed. Can you help me?

Turn off the virtual key on the actual android device in the settings.  It's not a code issue.

**Comment by rvieceli** [comment]
@JeffHooper Thank you, Do you know if this problem has been solved with react-navigation 6?

**Comment by JeffHooper** [comment]
@rvieceli , sorry I am not sure. Since posting this issue I have migrated my entire app to a pure React-Native build and have dropped Expo all together.
