### ISSUE TITLE
ExpoSecureStore broken for Web

### ISSUE THREAD

**Issue by aeneasr** [expo/expo#10546]
### Summary of Issue 

What works fine in the iOS Simulator causes

```
Unhandled Rejection (TypeError): _ExpoSecureStore__WEBPACK_IMPORTED_MODULE_2__.default.getValueWithKeyAsync is not a function
```

in the web browser.

<img width="1904" alt="Bildschirmfoto 2020-10-05 um 12 16 05" src="https://user-images.githubusercontent.com/3372410/95067774-99692300-0704-11eb-957c-b69ab4c94eca.png">

 This worked before when running Expo SDK 0.38

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.27.13 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /usr/local/bin/node
      npm: 6.14.8 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.14 
    npmGlobalPackages:
      expo-cli: 3.27.13
    Expo Workflow: managed
```

### Reproducible Demo

Check out https://github.com/ory/kratos-selfservice-ui-react-native/tree/eeb4feedb661fd76b4b24b43fe8897c071b7c0d2 then do `npm i && npm start web`.

### Steps to Reproduce

See above

### Expected Behavior vs Actual Behavior

No TypeError is expected.

**Comment by byCedric** [comment]
Hi @aeneasr, thanks for writing in! Unfortunately, we [don't support SecureStore on web](https://docs.expo.io/versions/latest/sdk/securestore/). This is because there is no "secure storage API" that works similar to Android and iOS secure storage. Everything read and written in web can't be considered secure, you always have multiple options of fetching that data. 

If you need a storage that works for both web and native, I would suggest [taking a look at AsyncStorage](https://docs.expo.io/versions/latest/sdk/async-storage/). But again, this isn't as secure as the native secure storage.

Hope this helps!

**Comment by aeneasr** [comment]
Oh, my bad - thank you!
