### ISSUE TITLE
[IOS] Notifications permission asked by a module

### ISSUE THREAD

**Issue by Clonescody** [expo/expo#10576]
Hi guys, I am currently working on an ejected expo app and I've got a permission issue. 

I setup everything in my Manifest and Info.plist files, but when I try to publish the app on Testflight, I receive the following message : `Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement.`

The problem is that I'm not requesting the Notifications permission ever. It's not included in my certificate nor in xCode capabilities, and they are not called from anywhere in my app. 

From what I read on the subject, this permission request could come from a module, however, I don't have a clue on how to determine which one is requesting it. 

Here's my package.json : 
```
"dependencies": {
    "@react-native-community/art": "Brewskey/art#8ce7ec5812c8b5231700a6a3449d6fd9c003d9dd",
    "@react-native-community/datetimepicker": "3.0.0",
    "expo": "^39.0.0",
    "expo-asset": "~8.2.0",
    "expo-av": "~8.6.0",
    "expo-constants": "~9.2.0",
    "expo-font": "~8.3.0",
    "expo-linking": "^1.0.3",
    "expo-permissions": "~9.3.0",
    "expo-splash-screen": "~0.6.1",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.3",
    "formik": "^1.5.8",
    "md5": "^2.2.1",
    "moment": "^2.19.1",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "0.63.3",
    "react-native-check-box": "^2.1.7",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "~1.7.0",
    "react-native-modal-datetime-picker": "^8.7.1",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-render-html": "^4.1.2",
    "react-native-screens": "~2.10.1",
    "react-native-simple-gauge": "^0.3.0",
    "react-native-svg": "12.1.0",
    "react-native-svg-charts": "^5.3.0",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.7",
    "react-native-webview": "10.7.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^1.2.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "redux-saga": "^1.0.3",
    "reselect": "^4.0.0",
    "sentry-expo": "^2.1.2",
    "tipsi-stripe": "8.0.0-beta.10",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@react-native-community/eslint-config": "^1.1.0",
    "@storybook/addon-actions": "^5.1.9",
    "@storybook/addon-links": "^5.1.9",
    "@storybook/addons": "^5.1.9",
    "@storybook/react-native": "^5.1.9",
    "@storybook/theming": "^5.1.9",
    "babel-eslint": "^9.0.0",
    "babel-jest": "~25.1.0",
    "eslint": "^6.0.1",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.2",
    "flow-bin": "^0.102.0-rc",
    "husky": ">=1",
    "jest": "~25.1.0",
    "jest-expo": "^39.0.0",
    "jetifier": "^1.6.4",
    "lint-staged": ">=8",
    "prettier": "^1.5.3",
    "prettier-eslint": "^9.0.0",
    "react-devtools": "^3.6.1",
    "react-native-scripts": "^2.0.1",
    "react-native-svg-transformer": "^0.13.0",
    "react-test-renderer": "16.13.1",
    "remote-redux-devtools": "^0.5.12"
  },
```

I added `expo-permissions` lately to try to use it as a permissions manager but couldn't do anything with it. 

I'm not so sure on how to handle this issue. 

- I wanted to prevent Notifications usage on iOS but apparently iOS doesn't let you lock the permissions like android does. 

- Add "This feature wont be used" message to a permission request is imo the worst thing ever for user-trust so I hope it's not considered as an OK answer. 

- Add a legitimate message is a nonsense as well since it's never used in the app. 

My linking/building/achiving/signing does work and Apple is only blocking on this. 

This is a huge blocking point for me, any help appreciated guys, thanks 🙏

**Comment by sjchmiela** [comment]
Hey @Clonescody!

From what I think I know — Apple Review process statically analyzes app looking for code that could register for remote notifications. The `This feature won't be used` message does not apply here — there is no usage description applicable to notification permissions. To further investigate your issue I'd need to ask you try and search for `registerForRemoteNotifications` string in the Xcode project. This should let us know where does the registration happen. 

If you ejected your app in SDK39 and don't have `expo-notifications` installed (looking at your `package.json` you don't have) it isn't Expo which registers the app for notifications. Or maybe you still use ExpoKit?

**Comment by Clonescody** [comment]
Hi @sjchmiela. I resolved my issue by adding the Push Notification capability, it was decided to add it anyways to gain time. However the issue still stands I think. 

As for your questions : 
- Searching "registerForRemoteNotifications" doesn't show any result in xCode so I assume nothing is using it ? 
- I didn't add expo-notifications solely because I'm not using any notification
- When I ejected at the time, I indeed used ExpoKit ( Expo 34 ), could this come from it ? 

Thanks for your reply, I am now on a clean state with the certificate including Push Notifications, but I will keep an eye on this thread as I might get the same issue on another app.

**Comment by sjchmiela** [comment]
Hm… 

First of all I think you've made a good decision about enabling the Push Notifications capability — it doesn't do any harm and it removes the Apple message, so good for you!

Second of all, I haven't said that earlier, but there are more than one code pieces that may trigger static analyzer — one is surely `registerForRemoteNotifications`, another one is eg. `didRegisterForRemoteNotificationsWithDeviceToken`. I saw some thread on the Internet saying that Apple checks whether the `AppDelegate` implements a handler for `application:didRegisterForRemoteNotificationsWithDeviceToken:` and if it does it assumes the application _uses_ notifications (which isn't true as it is in your project). The single result you posted fulfils the requirement — your `AppDelegate` most probably subclasses `UMAppDelegateWrapper` which implements the offending function, thus triggering the message.

Frankly speaking I don't know how to solve this perfectly well.
- Removing these methods from the `UMAppDelegateWrapper` would make it more difficult to install and configure libraries like `expo-notifications` which use the unimodules x app delegate infrastructure.
- We could remove the methods and add method swizzling in runtime, but it isn't the always best practice (see [considerations](https://nshipster.com/method-swizzling/#considerations)).

Lastly, I've asked for ExpoKit because if you were still using ExpoKit, you'd get `registerForRemoteNotifications` code in there, but if there were no matches in Xcode you must be using bare-bare workflow! 👍 (If you were using `ExpoKit`, you'd have an `pod 'ExpoKit'` inside your `Podfile` which I believe you do not have.)

Do you consider:

> If you get this message from Apple and want to get rid of it, simply enable Push Notifications capability.

a satisfying response to this issue or should I keep it open to remember to some day (some day…) to try to implement method swizzling? (I can't promise we'll get to it in 2020 or 2021…)

**Comment by Clonescody** [comment]
@sjchmiela Wow thanks so much for such detailed explanation. I'm not at all familiar with iOS development but I still get what you said :D 

On my personal case I'd say the answer is fine, I'll probably have to implement them later anyways and as said it doesn't harm anybody, but if it stays as a "default" answer I think a few pieces of documentation would be great. 

Wandering around SO and github issues I found out that a lot of people had this problem and not having a clue about what to do. 

I think even a couple lines in the `expo-notifications` documentation would do it, I came across that page a lot searching for an answer. 

Thanks again so much for your time 🙏 

As for ExpoKit, I had that Pod inside my Podfile for a while, but the whole file got overwritten automatically when I ran `expo upgrade` to get to SDK 39.
