### ISSUE TITLE
Android expo-image-picker no "select" or "done" button 

### ISSUE THREAD

**Issue by oporter1** [expo/expo#10582]
### Summary of Issue 
when selecting an image from gallery or taking a photo, expo-image-picker UI has no "select" or "okay" or "done" button 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.2 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.9 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-native-web: ^0.11.7 => 0.11.7 
      react-navigation: ^3.13.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.21.5

### Reproducible Demo

`  import * as ImagePicker from "expo-image-picker";
    
    const chooseImage = async (useCamera, index) => {
    if (!(await checkPermission(useCamera))) {
      Alert.alert(
        "Permission missing.",
        "Camera permission is required to take image."
      );
      return;
    }
    const method = useCamera ? "launchCameraAsync" : "launchImageLibraryAsync";
    const result = await ImagePicker[method]({
      allowsEditing: true,
      base64: false,
      aspect: [3, 4],
    });
    if (!result.cancelled) {
      // upload image and retrieve image url
      const {height, width, type, uri} = result;
      profile.images[index] = uri;
      if (uri != null) {
        setProfile(profile);
      }
      setChangedValue("images");
    }
  };`

 
also posted on stack overflow: 
https://stackoverflow.com/questions/63971568/expo-image-picker-android-doesnt-have-a-select-button

### Steps to Reproduce
open android app
click add photo
select gallery or camera
select photo 
**then there is no where on the UI to "select" or "okay" or "done" to confirm the picture selection

### Expected Behavior vs Actual Behavior
expected to see some button or selection method to allow the user to choose the image. see below photo.

![image](https://user-images.githubusercontent.com/12777243/95264765-f3014880-07fd-11eb-8973-b00ddafbc250.png)

**Comment by byCedric** [comment]
Hi @oporter1! Thanks for the report. We use the default image library installed on the phone when cropping images. I think the screenshot you sent is the default Android one. In this app, the "CROP" button is the confirmation or "ok"/"done" button. This might be different for other people if they have installed their own image library app.

![Screenshot 2020-10-08 at 14 31 08](https://user-images.githubusercontent.com/1203991/95458765-e9e5b800-0972-11eb-8e56-feb9dea5ed80.png)

I don't think we can easily change that button to something different, without recreating the full crop functionality. If you think otherwise, please let us know.

Hope this helps!
