### ISSUE TITLE
React native expo App display blank page in IE 11

### ISSUE THREAD

**Issue by developers-pio** [expo/expo#10588]
I am using the below configuration for the react-native expo with es6.

> **Configuration** :
> 
> "expo": "~39.0.2",
> "react-native": "~0.63.3",
> "typescript": "~3.9.5"
> 

While I am trying to run an App by hitting command "expo start" and running in the localhost on IE 11.

**Current Result**:  IE 11 display blank page rendering App

**Expected Result**: It should show welcome or index page on IE 11 as showing on the other browsers (Google Chrome, Firefox, Edge).

**Error**: (“SCRIPT1002: Syntax Error”)

Please let us know how to overcome this issue?

**Comment by byCedric** [comment]
Hi @developers-pio, thanks for the issue report. Because IE11 is an outdated browser, with a [current market share of 1.4%](https://www.w3counter.com/trends) (and not supported anymore by [TopDesk](https://page.topdesk.com/internet-explorer-11) and [Microsoft 365](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666)), we don't support it out of the box. You have to add a custom webpack configuration and modules to support it.

If you do want to support it, please do this:

1. Add [webpack config](https://docs.expo.io/guides/customizing-webpack/) and [resize observer](https://docs.expo.io/guides/customizing-webpack/#resizeobserver) dependencies.
```bash
$ yarn add --dev @expo/webpack-config resize-observer-polyfill
```

2. Add a custom webpack config in `webpack.config.js`
```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

// These modules are targeting node and uses newer syntax IE11 can handle
const modulesToTranspile = [
  'ansi-regex',
  'ansi-styles',
  'chalk',
  'react-dev-utils',
];

module.exports = async function(env, argv) {
  env.babel = { dangerouslyAddModulePathsToTranspile: modulesToTranspile };
  return await createExpoWebpackConfigAsync(env, argv);;
};
```

3. (Re)start webpack bundler with `yarn web`

Hope this helps!

**Comment by pyros2097** [comment]
@developers-pio you can also try out this package.
https://www.npmjs.com/package/expo-legacy-browser-support
