### ISSUE TITLE
"Allow all the time" option is missing on android 10.

### ISSUE THREAD

**Issue by miroslavskela** [expo/expo#10593]
Hi, 
I want to ask is there possibility, when developing in expo, to ensure that the option "Allow all the time" will appear when asking for location permission. Currently it shows only "Deny" and, "Allow while Application is in use". After some testing I noticed that background location does not work when option  "Allow while Application is in use" is choosed. When I switch to all the time in settings it starts to work.

Thank you.

**Comment by gingkob** [comment]
Yap, same issue here. After some recent android update it disappeared.

**Comment by byCedric** [comment]
Hi @miroslavskela and @gingkob. I think this is related to a recent change in Android related to the background location. Google decided to lock down the background location functionality in Android, [soon you will need to specially request this permission when deploying to the Play store](https://www.theverge.com/2020/2/21/21146834/google-play-store-background-location-tracking-review-process-android-11). Probably because of this, Google also decided to remove the "Allow all the time" from the system dialog, [you now have to "enable" this in the app settings as mentioned here](https://developer.android.com/training/location/permissions?hl=fr#request-background-location).

Because this is a restriction enforced by the operating system, and not React Native or Expo, we can't really change this. We do have a shortcut to open the [Android settings with `Linking.openSettings()`](https://reactnative.dev/docs/linking#opensettings), which might help to make it easier.

Hope this helps!
