### ISSUE TITLE
Document Picker not showing local files in IOS

### ISSUE THREAD

**Issue by AnishaChhatwani** [expo/expo#10604]
### Summary of Issue 
I am able to see the the iCloud files with the document picker. But I am not able to see any local files(images, videos etc) when I click on On My iPhone in the screenshot below.
![Image from iOS](https://user-images.githubusercontent.com/26029391/95436294-1a2a5800-096d-11eb-8b8a-b52e8ff748bc.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/26029391/95436275-1696d100-096d-11eb-9cbe-1a985675b7b3.png)

### Reproducible Demo
https://snack.expo.io/@anisha27/disrespectful-candy
This is how I am using it in my code.
DocumentPicker.getDocumentAsync()
      .then(result => {
})
.catch((err) => {
    console.log('err in selecting file', err)
 })

### Expected Behavior vs Actual Behavior
I should be able to see the images stores locally on my iphone.

**Comment by byCedric** [comment]
Hi @AnishaChhatwani! On iOS we use the [`UIDocumentPickerViewController `](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller) to show the overlay and to pick documents. This overlay is only meant for picking documents, and not images or videos. If you want to allow picking media files, please check out [`expo-image-picker`](https://docs.expo.io/versions/latest/sdk/imagepicker/) instead of the document picker 😄 

Hope this helps!

**Comment by aprilmintacpineda** [comment]
Hmmm... what if we need both? Can't we really allow users to pick images, videos and other documents?

**Comment by zeroAps** [comment]
@byCedric You cannot access Documents with ImagePicker in iOS. You should re-open this ticket, since this is probably a valid issue. Even in documentation it states that we are able to ask for any document type, including image/video.

https://docs.expo.dev/versions/v42.0.0/sdk/document-picker/

Please correct me if i'm wrong.
