### ISSUE TITLE
The standalone APK is very big...

### ISSUE THREAD

**Issue by eladcandroid** [expo/expo#1061]
With a very simple app, it's almost 28mb file size.. (Created with CRNA)
Do you have any option to reduce it?

**Comment by AdamJNavarro** [comment]
"If you need to keep your app size extremely lean, Expo may not be the best choice. The size for an Expo app on iOS is approximately 25mb, and Android is about 20mb. This is because Expo includes a bunch of APIs regardless of whether or not you are using them — this lets you push over the air updates to use new APIs, but comes at the cost of binary size. We will make this customizable in the future, so you can trim down the size of your binaries."

Unfortunately, there isn't currently a way to reduce the file size but it is in the roadmap.

**Comment by radi-cho** [comment]
Yeah... 25MB for simple app.

**Comment by eladcandroid** [comment]
@AdamJNavarro Maybe you can implement these solutions for Android?
https://stackoverflow.com/questions/38184734/react-native-for-small-size-apk-with-low-internet-bandwidth
