### ISSUE TITLE
[docs] [expo-notifications] missing instructions for notifications listeners to work on iOS when adding the library to an existing app

### ISSUE THREAD

**Issue by mreda7** [expo/expo#10630]
When adding expo-notifications in an existing react-native application, notification listeners does not fire on iOS unless we set the expo-notifications delegate in `didFinishLaunchingWithOptions` function in the file `AppDelegate.m`

`  id<EXNotificationCenterDelegate> notificationCenterDelegate = (id<EXNotificationCenterDelegate>) [UMModuleRegistryProvider getSingletonModuleForClass:[EXNotificationCenterDelegate class]];`

`[[UNUserNotificationCenter currentNotificationCenter] setDelegate:(id<UNUserNotificationCenterDelegate>) notificationCenterDelegate];
`

I think this must be added to the installation part of the docs, so it will be clear for the future users . 
https://docs.expo.io/versions/latest/sdk/notifications/#installation

Nice library by the way , thanks for your efforts!

**Comment by sjchmiela** [comment]
Hello @mreda7! Good job on figuring out how to integrate `expo-notifications` with your bare React Native application on your own!

It looks like:
- your `AppDelegate` doesn't subclass `UMAppDelegateWrapper` which is a simple class that automatically calls these methods you mentioned on necessary singleton modules (that's why you needed to call them yourself) or
- your `AppDelegate` does subclass `UMAppDelegateWrapper` but you don't call `super` in `didFinishLaunchingWithOptions`.

When it comes to instructions, if you clicked:
<img width="723" alt="Zrzut ekranu 2020-10-12 o 10 28 18" src="https://user-images.githubusercontent.com/1151041/95723644-a7272700-0c75-11eb-889f-0950b118286a.png">

then

<img width="1096" alt="Zrzut ekranu 2020-10-12 o 10 28 41" src="https://user-images.githubusercontent.com/1151041/95723693-b5754300-0c75-11eb-85b4-507110497831.png">

and then

<img width="930" alt="Zrzut ekranu 2020-10-12 o 10 29 03" src="https://user-images.githubusercontent.com/1151041/95723735-c1f99b80-0c75-11eb-9f20-2effca086940.png">

you'd end up on [Installing Unimodules](https://docs.expo.io/bare/installing-unimodules/#configuration-for-ios) page which… does not call `super` in `application:didFinishWithLaunching:…`. 😃 

On it!

**Comment by mreda7** [comment]
Hello @sjchmiela !  
I tested your suggestions and it works 😃. 

I think it will be a great if you included also the changes that we have to make in `AppDelegate.h` when [configuring Unimodules fo iOS](https://docs.expo.io/bare/installing-unimodules/#configuration-for-ios).

Thanks !

**Comment by sjchmiela** [comment]
Done! Thanks for catching that! https://github.com/expo/expo/pull/10637/commits/762b61a21001da652d4c188a105630723d3a6435

**Comment by mreda7** [comment]
Nice !

**Comment by Enricopv** [comment]
I just want to confirm that applying the changes in the two commits (https://github.com/expo/expo/pull/10637/commits) to AppDelegate.h and AppDelegate.m fixed this iOS notification listener issue I had been having for a while! 

Thanks so much for figuring it out!
