### ISSUE TITLE
Ask for Gallery/Camera Roll Permission

### ISSUE THREAD

**Issue by alialaa** [expo/expo#107]
I am trying to use `import { Permissions } from 'expo';` in order to ask for accessing the gallery, but however the object only contains camera, contacts, location, notifications. Is there any way to do it?

**Comment by allpwrfulroot** [comment]
It might be included in Camera, I've had no problems accessing photos with my app using Expo.ImagePicker.launchImageLibraryAsync(options). The permissions request pops up as needed.

**Comment by terribleben** [comment]
Hi, the Image Picker library automatically asks for camera roll permissions right now if needed. This is just because we import `react-native-image-picker` and have not updated that API to use the Expo.Contacts API. You should be able to access the camera roll either way.

We have plans to consolidate the camera roll permission into our Permissions API soon, so that this is less confusing.

**Comment by eyalw** [comment]
@terribleben so I just request the CAMERA permission, and this will allow me to read the user photos gallery?
