### ISSUE TITLE
Background Location Update not working after put app in background...

### ISSUE THREAD

**Issue by ronal2s** [expo/expo#10712]
## 🐛 Bug Report
I need to get location each X minutes, now I'm testing each 5 seconds, is working well when the app is up but when I put in background is not working anymore

### Reproducible Demo
https://snack.expo.io/lgz!KGf6V

### Expected Behavior vs Actual Behavior

Expected: continue watching the log output in the console
Actual: Is not working after 1 minute (or less) in background

**Comment by codybutz** [comment]
@ronal2s I am having this issue as well on Expo SDK 39 but ONLY on Android 10+. What device were you testing on?

**Comment by ronal2s** [comment]
> @ronal2s I am having this issue as well on Expo SDK 39 but ONLY on Android 10+. What device were you testing on?

Same version, Samsung Note 10 with android 10

**Comment by codybutz** [comment]
I've experienced an issue after almost exactly 5 minutes tracking quits. No errors get printed in logcat. The same app works on iOS and Android 8 & 9 for hours. I believe this is an issue with Android 10 only.

**Comment by superyarik** [comment]
main issue
https://github.com/expo/expo/issues/9288

related
https://github.com/expo/expo/issues/8483
https://github.com/expo/expo/issues/10139
https://github.com/expo/expo/issues/6017
https://github.com/expo/expo/issues/6290

**Comment by byCedric** [comment]
Hi @ronal2s and @codybutz! What are the location permissions you granted for the app? If it works fine on Android <10 and only fails on Android 10, I'm afraid it's related to the "new" permissions Google introduced. [See my comment from this issue](https://github.com/expo/expo/issues/10593#issuecomment-705542216)

> Hi ... I think this is related to a recent change in Android related to the background location. Google decided to lock down the background location functionality in Android, [soon you will need to specially request this permission when deploying to the Play store](https://www.theverge.com/2020/2/21/21146834/google-play-store-background-location-tracking-review-process-android-11). Probably because of this, Google also decided to remove the "Allow all the time" from the system dialog, [you now have to "enable" this in the app settings as mentioned here](https://developer.android.com/training/location/permissions?hl=fr#request-background-location).
> 
> Because this is a restriction enforced by the operating system, and not React Native or Expo, we can't really change this. We do have a shortcut to open the [Android settings with `Linking.openSettings()`](https://reactnative.dev/docs/linking#opensettings), which might help to make it easier.

Hope this helps!

**Comment by codybutz** [comment]
Thanks @superyarik . However I do believe that this is a new issue separate from that Umbrella task since I was able to experience this in the Standalone Application as well.

**Comment by ronal2s** [comment]
> Hi @ronal2s and @codybutz! What are the location permissions you granted for the app? If it works fine on Android <10 and only fails on Android 10, I'm afraid it's related to the "new" permissions Google introduced. [See my comment from this issue](https://github.com/expo/expo/issues/10593#issuecomment-705542216)
> 
> > Hi ... I think this is related to a recent change in Android related to the background location. Google decided to lock down the background location functionality in Android, [soon you will need to specially request this permission when deploying to the Play store](https://www.theverge.com/2020/2/21/21146834/google-play-store-background-location-tracking-review-process-android-11). Probably because of this, Google also decided to remove the "Allow all the time" from the system dialog, [you now have to "enable" this in the app settings as mentioned here](https://developer.android.com/training/location/permissions?hl=fr#request-background-location).
> > Because this is a restriction enforced by the operating system, and not React Native or Expo, we can't really change this. We do have a shortcut to open the [Android settings with `Linking.openSettings()`](https://reactnative.dev/docs/linking#opensettings), which might help to make it easier.
> 
> Hope this helps!

Hi, this is the permissions for the app:
![image](https://user-images.githubusercontent.com/20154989/96500013-360ae500-121c-11eb-884a-8d5a347cb6ec.png)

I try to use `Linking.openSettings()` but this just open the settings app, is there a way to open 'permissions' options directly? We cant let that resposibility to the users, something like a prompt where they can just pick the option will be fine.

**Comment by byCedric** [comment]
@ronal2s that's good, but I was talking about the "permission you grant the app" when starting it up. You'd need to request your users to "allow location". Before Android 10 there was a list with 3 (or more) items, "Allow all the time", "Allow only when using the app" and "Deny". The one you need is "Allow all the time", since backgrounding the app isn't included in "Allow only when using the app". 

But, since Android 10 Google decided to change this. Your users can't be prompted with "Allow all the time" anymore. They have to manually open the permissions settings of your app and turn it on for this option ([see this post](https://developer.android.com/training/location/permissions?hl=fr#request-background-location)).

> I try to use `Linking.openSettings()` but this just open the settings app, is there a way to open 'permissions' options directly? We cant let that resposibility to the users, something like a prompt where they can just pick the option will be fine.
There is no simple helper to do this at the moment unfortunately. You might get something working by using the [Android intent launcher](https://reactnative.dev/docs/linking#send-intents-android) with [something like this](https://stackoverflow.com/a/32983128/2277025).

We still have to check if we need to update the default permissions for this change, but it looks like we'd have to change something for SDK 40. Of course, that will be announced if we need to make some changes.

**Comment by codybutz** [comment]
Hello @byCedric !

Here is a video of me showing off a test application that I built for testing this:
https://www.loom.com/share/48081853551a416ea429f561082ed4ec

Application code: https://github.com/codybutz/test-location-app
Attached logcat: https://gist.github.com/codybutz/82ff238e875808a3b0f03c9d171d86aa

As you can see from the logs, we start tracking at 1603135747623 and ended at 1603136077244, which is approximately 5 1/2 minutes. 

Same implementation works perfect on iOS.

Android permissions setup:
```
"android": {
      "useNextNotificationsApi": true,
      "package": "com.test.testlocationapp",
      "permissions": ["ACCESS_COARSE_LOCATION", "ACCESS_FINE_LOCATION", "ACCESS_BACKGROUND_LOCATION", "CAMERA", "FOREGROUND_SERVICE"],
      "versionCode": 6,
      "config": {
        "googleMaps": { "apiKey": "<key here>" }
      }
    },
```

**Comment by codybutz** [comment]
@byCedric is there anything else you need for this ticket?

**Comment by miroslavskela** [comment]
Hi everyone, I'm not sure what happens here, but as I saw in google explanation, there will not be "Allow all the time" option but from android 11 and API 30, currently I'm using android 10, API 29, and I added "ACCESS_COARSE_LOCATION", "ACCESS_FINE_LOCATION", "ACCESS_BACKGROUND_LOCATION" in app.json, but there is no third option still.Did someone managed to understanf this situation. Here is the google explanation which says that from android 11 third option will not be displayed. 
https://developer.android.com/training/location/permissions?hl=fr#request-background-location
 If someone have some idea, it would be great. Thank you.

**Comment by codybutz** [comment]
@byCedric Any updates to this please? Is there another thread I should be following?

**Comment by HYJ29** [comment]
I think this is really bad but I could make it keep working in the background. 
I hope somebody tells me if there is a serious problem with this solution or have a better solution. 

I just made another Task called "RESTART_RUNNINGLOCATION_TASK"
and did nothing on it. 
```
TaskManager.defineTask(
  RESTART_RUNNINGLOCATION_TASK,
  async ({ data, error }) => {

    console.log("restarted");
  }
);
```

and right after Loction.startLocationUpdateAsync,  
I registered that task like this with **expo-background-fetch** 
(these logic is in redux-saga, that's why I use yield)

```
yield Location.startLocationUpdatesAsync(RUNNING_LOCATION_TASK, {
    accuracy: Location.Accuracy.BestForNavigation,
    foregroundService: {
      notificationTitle: "WEDO 가 background 에서 실행중입니다.",
      notificationBody: "실시간으로 위치를 tracking 하고 있습니다.",
      notificationColor: "#RRGGBB",
    },
    showsBackgroundLocationIndicator: true,
  });
  yield BackgroundFetch.registerTaskAsync(RESTART_RUNNINGLOCATION_TASK, {
    minimumInterval: 10,
    stopOnTerminate: false,
  });
```

So I expected every 10 seconds, BackgroundFetch would wake up my app. 
and on BackgroundFetch, there is a 'stopOnTerminate' prop. I think setting it false prevents this task from terminating. 

and I unregistered backgroundFetchTask with Location.stopLocationUpdatesAsync. 

```
const hasStarted = yield Location.hasStartedLocationUpdatesAsync(
    RUNNING_LOCATION_TASK
  );
  yield BackgroundFetch.unregisterTaskAsync(RESTART_RUNNINGLOCATION_TASK);
  if (hasStarted) {
    yield Location.stopLocationUpdatesAsync(RUNNING_LOCATION_TASK);
    RootNavigation.navigate("RunningPauseScreen");
  }
```

**Comment by byCedric** [comment]
Hi people, sorry for not updating this issue earlier. We patched a few things for Android 10, and <9. Android 11 is up next. For more info, [checkout this comment](https://github.com/expo/expo/issues/11330#issuecomment-750894337).

Happy holidays!

**Comment by HYJ29** [comment]
@byCedric  Thank you for your really nice sample app.
 But I think the problem here is not solved on that app either. 

The problem is the background task started by Location.startLocationUpdateAsync() 
is not continue to work when the phone goes on "**sleep mode**". 
As you know we usually use the running fitness app with the phone is on sleep while running. 

my emulator is android 10 and the expo client is  2.18.5

every time I put the phone on sleep mode(running app in the background and turning off the screen)
it runs for a while like 3~ 5min and stops running.
and if I turn on the screen again, it work back again. (In your sample app, actually, it goes crazy for some reason. It does not stop tracking until I press the stop tracking button several times.) 

Is it happens because of the new google permission policies? or should I try another way to make it work on sleep mode?

**Comment by 2j2e** [comment]
There is group of issues which makes background location tracking impossible on Android 10+. SDK40 gets issue with "Not authorized to use background location services.", SDK39 is loosing background updates.

**Comment by 2j2e** [comment]
Anyone who experienced the issue with dead background service please also check https://dontkillmyapp.com Manufacturers can kill background services to make device live longer, some of them have whitelist of known apps. That's why your "no name" (for them) app can be killed.

**Comment by MaRaSu** [comment]
@HYJ29 & anyone else still wondering about this, there is an update on Expo plans in issue #11854.
