### ISSUE TITLE
Use expo-notifications in a react native project?

### ISSUE THREAD

**Issue by yarapolana** [expo/expo#10780]
I am using expo libraries and my project is already set with unimodules, I thought I could use expo-notifications since other libs work fine, but can't seem to get the new notifications lib to work.

1. The FCM and the APNS documentation asks to follow `expo credentials:manager` or `expo push:android ...` and both seem to require expo which I don't have in this project.

2. The `await Notifications.getExpoPushTokenAsync()` function does nothing, it just stops the app on this line, so I can't get the token.

Do I have to install expo and edit app.json to be able to use the expo-notifications? What am I missing?
Thanks

Testing this on
expo-notifications: 0.5.0
React Native 0.63
React: 16.13.1

**Comment by cruzach** [comment]
1- those are `expo-cli` commands, they don't require you to have the `expo` package installed in your project

2- this is probably because we don't have credentials for you? if you try/catch that code block, you might get more info, but iI recommend following the guidelines you mention in your first point before trying anything else

to summarize- you can use both the `expo-notifications` library and the [Expo push notification _service_](https://docs.expo.io/push-notifications/sending-notifications/) in bare and managed workflow apps. You can _also_ use the `expo-notifications` library **without** the Expo push notification service, [by communicating with FCM and APNs directly, on your own servers](https://docs.expo.io/push-notifications/sending-notifications-custom/)

**Comment by yarapolana** [comment]
Thanks for the fast reply @cruzach
1. I figured they were, but the commands didn't work, gave me an unusual error, then I installed expo just to try and they worked?!? 
```batch
Cannot determine which native SDK version your project uses because the module `expo` is not installed. 
Please install it with `yarn add expo` and try again.
```

2. By credentials you mean the ones that you can get with `expo credentials:manager` or `expo push:android ...` because if that was the case they do exist already, I managed to run the commands after all. We have the expo sdk setup in the backend as well but still get nothing. 
The function is wrapped in a try/catch it just stops at the command and nothing happens, expo installed and with everything else setup (app.json).

3. By closing this does that mean I have to move my enquiry to the forum?

**Comment by cruzach** [comment]
1- It looks like you might be trying to run a bare project in the Expo client app (which is _only_ doable with the `expo` package installed, see [here](https://docs.expo.io/bare/using-expo-client/))

2- Yeah those are the credentials I mean

3- If you're trying to report a bug in the Expo SDK, then you should follow the bug report template and provide all that info, especially a minimal reproducible demo and the steps to reproduce your issue. If you're just asking questions, then yeah our forums are the best place for that 😄
