### ISSUE TITLE
App still updating automatically on restart even though updates.checkAutomatically set to "ON_ERROR_RECOVERY".

### ISSUE THREAD

**Issue by camcarter131** [expo/expo#10783]
### Summary of Issue 
I am using expo-updates to prompt the user to accept OTA updates when my app is restarted or brought to the foreground. I referenced the expo docs here - https://docs.expo.io/guides/configuring-ota-updates/, and set updates.checkAutomatically to "ON_ERROR_RECOVERY" in the app.json in order to prevent app from automatically fetching updates on restart. I rebuilt the app and put it on Testflight, and tested this out, but restarting the app still automatically fetches updates. I rebuilt again, same issue.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.15.5 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 39.0.3 
      react: 16.9.0 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.15.5

### Reproducible Demo
I am using this code to prompt the user to accept updates:
```
    checkForUpdates() {
        UpdateUtil.getUpdateStatus(async (err, data) => {
            if (err) {
                console.log(`Err getting update status: ${err}`);
            } else if (data.canReceiveUpdates) {
                try {
                    const update = await Updates.checkForUpdateAsync();
                    if (update.isAvailable) {
                        await Updates.fetchUpdateAsync();
                        this.updateAlert('Update available');
                    }
                } catch (e) {
                    // handle or log error
                    console.log(e);
                }
            } else {
                console.log(`System unable to receive updates`);
            }
        });
    }
```
This is run in componentDidMount, and when the app otherwise comes to the foreground.

In my app.json I have this:
```
    "updates": {
      "fallbackToCacheTimeout": 0,
      "checkAutomatically": "ON_ERROR_RECOVERY"
    },
```

Could the "fallbackToCacheTimeout" be having an effect?

 
### Expected Behavior vs Actual Behavior
On app restart, app should not fetch updates but should prompt the user to accept updates. Instead, it fetches updates automatically.

**Comment by brentvatne** [comment]
hi there,

i'm quite confused about the output that i'm seeing here from `expo diagnostics`:

```
expo: ^37.0.0 => 39.0.3
react: 16.9.0 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.63.2
```

how is it that your package.json versions appear to be completely different than those installed through node_modules? it's hard to know what SDK version you are using based off of this.

an aside - you may want to update the expo-cli version as well - expo-cli 3.15.5 is 7 months old, and we've made a lot of improvements and changes since then.

<hr />

as for the specific issue at hand here, what you have provided here is *not* a reproducible example and there are no steps to reproduce. i tried to reproduce this creating a new app and i could not.

my steps:
- initialize a new app
- add `"checkAutomatically": "ON_ERROR_RECOVERY"` to the updates config
- run `expo build:ios -t simulator` to get a simulator build
- wait for build to finish, extract the tar.gz and drag and drop it into a running ios simulator
- see the old code running
- update the code locally, run `expo publish`
- close and reopen the app, wait a few seconds, repeat. do this five times. no update

please do follow the issue template instructions next time you open an issue and include a reproducible example (info on how to do that: https://stackoverflow.com/help/mcve) and steps to reproduce
