### ISSUE TITLE
expo-notifications cannot properly handle notifications received from Firebase Admin SDK 

### ISSUE THREAD

**Issue by arj-mat** [expo/expo#10789]
### Environment
```
Expo CLI 3.28.2 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^39.0.0 => 39.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    Expo Workflow: managed
```

### Issue details

1. When running on Expo's Client, the device push token always issue the following error with FCM: _The credential used to authenticate this SDK does not have permission to send messages to the device corresponding to the provided registration token_.
2. Running on a standalone Android app, the notification is presented on the screen but the Notification object returned by the event of `addNotificationReceivedListener` is the following:
```
{
   "request":{
      "content":{
         "autoDismiss":true,
         "sound":"default",
         "data":null,
         "body":null,
         "sticky":false,
         "badge":null,
         "title":null,
         "subtitle":null
      }, // The values above are not supposed to be null
      "trigger":{
         "remoteMessage":{ // This object was not supposed to be on the "trigger" node
            "originalPriority":1,
            "notification":{
               "usesDefaultVibrateSettings":false,
               "visibility":null,
               "notificationPriority":null,
               "titleLocalizationArgs":null,
               "clickAction":null,
               "color":"#332750",
               "eventTime":null,
               "link":null,
               "usesDefaultSound":false,
               "channelId":null,
               "lightSettings":null,
               "title":"My notification title",
               "imageUrl":null,
               "vibrateTimings":null,
               "tag":null,
               "localOnly":false,
               "bodyLocalizationArgs":null,
               "titleLocalizationKey":null,
               "ticker":null,
               "usesDefaultLightSettings":false,
               "sticky":false,
               "body":"My notification body",
               "sound":"default",
               "icon":null,
               "notificationCount":null,
               "bodyLocalizationKey":null
            },
            "from":"773587893199",
            "ttl":2419200,
            "sentTime":1603496294063,
            "data":{
               "test":"test value",
               "experienceId":"@mateus-araujo/[REDACTED]"
            },
            "to":null,
            "collapseKey":"com.[REDACTED]",
            "messageType":null,
            "priority":1,
            "messageId":"0:1603496294088136%e69c4a24e69c4a24"
         },
         "channelId":null,
         "type":"push"
      },
      "identifier":"0:1603496294088136%e69c4a24e69c4a24"
   },
   "date":1603496294063
}
```
3. Taping on the notification does not trigger the event of `addNotificationResponseReceivedListener`.

 
### Steps to Reproduce

1. The server code used to send the notification is the following:
```
admin.messaging().sendToDevice(
	"MY DEVICE TOKEN",
	{
		notification: {
			title: "My notification title",
			body: "My notification body",
			sound: "default",
			color: "#332750",
		},
		data: {
			experienceId: "@mateus-araujo/[REDACTED]",
			test: "test value",
		}
	},
	{
		collapseKey: "Test key",
		contentAvailable: true,
		priority: "high",
	}
)
```
2. On my "app.json", `android.useNextNotificationsApi` is set to `true`. Setting this property to `false` causes the displayed notification to be blank and no event is ever fired.

### Expected Behavior

1. To receive the notification's "content" object with no null fields, like when using the Expo Push Notification API.
2. For the event of responding to a notification to work.

**Comment by cruzach** [comment]
Thanks for this report! regarding
> When running on Expo's Client, the device push token always issue the following error with FCM: The credential used to authenticate this SDK does not have permission to send messages to the device corresponding to the provided registration token.

Since you don't have access to our FCM credentials, you can't send notifications to experiences running in the Expo client app (unless you use Expo's notification service)

**Comment by sjchmiela** [comment]
Hey @arj-mat!

First let's talk about the first issue, where you aren't able to send a notification to the device push token retrieved in Expo client. This comes from the fact that Expo client is built with our internal Expo client `google-services.json` which configures the application to use, well, our Expo client project. Thus, to send a notification to the device push token that you receive from `getDevicePushTokenAsync` you'd need to try to send it using Expo client credentials (which you obviously don't have). Sorry for the confusion. Basically, `getDevicePushTokenAsync` is useless when used in an app which has not been built with your Firebase config. (That's why you're able to send the message using token fetched from a standalone app — it has your configuration in place!)

When it comes to the latter issue, first we'll need to talk about Firebase Cloud Messaging a little bit. There are two types of FCM messages: notification and data messages.
- Notification messages are handled by Firebase library more, i.e. they are displayed by Firebase, they don't necessarily wake the app.
- Data messages are not handled by Firebase library at all, they are immediately handed off to the application for processing. That's where `expo-notifications` comes in, takes the data payload, interprets it, displays or pushes to your application.

Looking at the code you are sending the notification with, it looks like you're sending a message of _notification type_ (see [Firebase documentation on message types](https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages) — you're providing a value for root-level `notification` key. This makes `expo-notifications` unable to:
- display the notification applying a proper `contentIntent` which will trigger `expo-notifications` and then your app once someone a user on the notification ([`setContentIntent`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setContentIntent(android.app.PendingIntent))),
- interpret the payload properly, parsing content (`expo-notifications` expects notification content data under `data.[key]`), that's why stuff under `request.content` is all `null` as you noticed.

Using Firebase notification messages may have its upsides when you try to use some configuration option that has not been exposed by `expo-notifications` yet, but in general it may lead to less predictable situations than using only `expo-notifications` (plus it's not our field of responsibility, you'd have to go to Google to report issues).

The way that seems to be the easiest would be to use only the API that `expo-notifications` provides, i.e. move the notification description from Firebase's root-level key to under `data`, where our library will interpret it and process. Instead of
```ts
admin.messaging().sendToDevice(
  "MY DEVICE TOKEN",
  {
    notification: {
      title: "My notification title",
      body: "My notification body",
      sound: "default",
      color: "#332750",
    },
    data: {
      experienceId: "@mateus-araujo/[REDACTED]",
      test: "test value",
    },
  },
  {
    collapseKey: "Test key",
    contentAvailable: true,
    priority: "high",
  }
);
```

you'd use

```ts
admin.messaging().sendToDevice(
  "MY DEVICE TOKEN",
  {
    data: {
      experienceId: "@mateus-araujo/[REDACTED]",
      test: "test value",
      title: "My notification title",
      message: "My notification body", // changed body to message as per API
      sound: true, // if the sound should be the default let's use simple true
      color: "#332750",
    },
  },
  {
    collapseKey: "Test key",
    contentAvailable: true,
    priority: "high",
  }
);
```

as [Android push notification payload specification](https://docs.expo.io/versions/latest/sdk/notifications/#android-push-notification-payload-specification) suggests.

Would you care to try sending the notification this way and let us know if it worked for you?

**Comment by arj-mat** [comment]
Yes, sending a notification the way @sjchmiela specified makes both `addNotificationReceivedListener` and `addNotificationResponseReceivedListener` to fire the proper events.

Except that, even with a proper notification handler set with`setNotificationHandler`, the notification is not presented when the app is foregrounded. But that is easily worked around by showing the received notification with `presentNotificationAsync`.

Thank you for your explanation.

**Comment by sjchmiela** [comment]
Huh… that is very interesting… Are the methods of `NotificationHandler` called? You could verify by replacing your handler with:
```ts
import * as Notifications from 'expo-notifications';

Notifications.setNotificationHandler({
  handleNotification: async (notification) => {
    console.log('handling a notification', notification);
    return { // or whatever you have already
      shouldShowAlert: true,
      shouldPlaySound: true,
      shouldSetBadge: true,
    };
  },
  handleSuccess: notificationId => console.log(`Notification ${notificationId} successfully handled.`),
  handleError: (notificationId, error) => console.log(`Notification ${notificationId} wasn't successfully handled.`, error),
});
```

**Comment by arj-mat** [comment]
Well that's odd... I tried both your code and my old one and now the notification shows up properly when the app is foregrounded.
I might have missed something in between building many versions of a standalone app to test.

That said, everything looks fine now.

**Comment by sjchmiela** [comment]
Fixed by @cruzach in https://github.com/expo/expo/pull/10844! 🎉

**Comment by codingedgar** [comment]
> This comes from the fact that Expo client is built with our internal Expo client `google-services.json` which configures the application to use, well, our Expo client project. Thus, to send a notification to the device push token that you receive from `getDevicePushTokenAsync` you'd need to try to send it using Expo client credentials (which you obviously don't have). Sorry for the confusion.

I imagined this was the case but should be documented more explicitly, in the actual documentation it remains unclear if it is necessary to config android, and if after config it should or not work.
