### ISSUE TITLE
Missing _array intro SQLResultSetRowList interface (Expo-SQLite)

### ISSUE THREAD

**Issue by ramonfsk** [expo/expo#10797]
Hi there!
Today I came across a doubt when using Expo-SQLite with Typescript in a project, the lack of the _array variable within the SQLResultSetRowList interface...

```javascript
export interface SQLResultSetRowList {
    length: number;
    item(index: number): any;
}
```

That way it is mandatory to always send an id to get the item you need, however if I want all the items this becomes a limitation.

That way it is mandatory to always send an id to get the item you need, however if I want all the items this becomes a limitation. Is there any good reason why he is not inside SQLite.types.d.ts?

**Comment by ide** [comment]
`_array` sounds like it should be private. Looking at https://www.w3.org/TR/webdatabase/#sqlresultsetrowlist, the interface exposes length + item(1).

**Comment by ramonfsk** [comment]
Thanks! ;)

**Comment by afermon** [comment]
Seems like the documentation on Expo states that _array can be used instead of the Item call but the type does not expose it, _array is passed thought.

rows.item (function) -- rows.item(index) returns the row with the given index. If there is no such row, returns null.
rows.array (_number) -- The actual array of rows returned by the query. Can be used directly instead of getting rows through rows.item().

https://docs.expo.io/versions/latest/sdk/sqlite/#resultset--objects
