### ISSUE TITLE
issue with date time picker on iOS 14

### ISSUE THREAD

**Issue by chrisdrackett** [expo/expo#10817]
### Summary of Issue 

Using the `inline` display option does not work currently in expo projects.

snack here (must run on device or sim): https://snack.expo.io/@tiltshift/datetimepicker-display

more info here: https://github.com/react-native-datetimepicker/datetimepicker/issues/317

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Targeting iOS 14 devices

### Reproducible Demo

https://snack.expo.io/@tiltshift/datetimepicker-display

### Steps to Reproduce

Look at date picker

### Expected Behavior vs Actual Behavior

Should be inline, but is instead a spinner

**Comment by brentvatne** [comment]
we need to update our CI to use xcode 12 so that it's used when building expo client for distribution

**Comment by hufftheweevil** [comment]
Is there an timeline as to when expo client will be updated to use xcode 12?

**Comment by Dromedaren** [comment]
I'm wondering the same, first I've had issues with images not showing on iOS 14.x but I managed to work around that. At the time I had updated to the SDK 38 and tried building and publishing with expo build and then expo upload commands. It failed because of a missing java dependency or fastlane issues with mismatched dependencies leading me to realising it was probably using the wrong xcode version. It still seems the expo build servers are not building correctly for iOS. This breaks all of our datepickers for iOS 14 when publishing to testflight and the store (but not when running locally in the expo client)

Is there any updates on what version the CI servers are running, or a plan on when the update to xcode 12 will be in effect?
