### ISSUE TITLE
Expo Screen Capture is unable to prevent capturing of video in fullscreen

### ISSUE THREAD

**Issue by manjots1607** [expo/expo#10834]
### Summary of Issue 
        When I was using usePreventCapture(), to prevent my app for screen recording to protect my videos i.e using expo-av library and its Video Component, I noticed when I view video in fullscreen screen recording is there.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
      I am targeting IOS & Android Platform.
 
### Steps to Reproduce
        Call UsePreventCaptue() in App.js
       & after that use Video component in some child Component & run app in android mobile.

**Comment by Gift-retyu** [comment]
Well, you wont be able to achieve that with the api, because android and ios take the video outside your view when going to fullscreen, of which expo api cant detect,  thus, you have to create custom controls of which your full screen will be inside your view, then you can block screen recording on full screen

**Comment by AbdelhalimAhmed** [comment]
This issue still exists with Expo SDK 48 and "expo-screen-capture": "^5.3.0"
