### ISSUE TITLE
LocalAuthentication.supportedAuthenticationTypesAsync return only [1] in galaxy note10+ which supports Faceid and Fingerprint

### ISSUE THREAD

**Issue by treesen** [expo/expo#10850]
## 🐛 Bug Report

LocalAuthentication.supportedAuthenticationTypesAsync return only [1] in galaxy note10+(Android 10) which supports Faceid and Fingerprint

I am using "expo-local-authentication": "^9.2.0"

I think the root reason is that "Includes fingerprint and face authentication integration for BiometricPrompt" in android 10, please fix ASAP, thank you

**Comment by treesen** [comment]
I am using "expo-local-authentication": "^9.2.0"

**Comment by treesen** [comment]
I think the root reason is that "Includes fingerprint and face authentication integration for BiometricPrompt" in android 10, please fix ASAP, thank you

**Comment by byCedric** [comment]
Hi @treesen, thanks for the issue but please follow the bug report format. Without the information from this template, I'm not sure how we can help you. If we can't reproduce a bug, we can't fix it, and right now I'm not sure what your issue is. If you are still having trouble with the `expo-local-authentication` and think this a bug, please open a new bug report with the information we ask you.

Hope this helps!

**Comment by treesen** [comment]
> Hi @treesen, thanks for the issue but please follow the bug report format. Without the information from this template, I'm not sure how we can help you. If we can't reproduce a bug, we can't fix it. If you are still having trouble with the `expo-local-authentication` and think this a bug, please open a new bug report with the information we ask you.
> 
> Hope this helps!

than you for your kindle reply, I have resubmitted a new issue, please check, thank you #10861
