### ISSUE TITLE
Cellular.getCellularGenerationAsync() return UNKNOWN instead of 4G

### ISSUE THREAD

**Issue by bouchezb** [expo/expo#10875]
### Summary of Issue 

Hello,
I'm trying to optimize images payload in my APK with real life usage.
In order to do this I use Cellular module to switch images resolutions according to supposed current cellular bandwidth.

If 4G > max size picture
if 3G > middle size picture
if 2G > min size picture
if UNKNOWN > no picture

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.27.14 environment info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.22.0 - /usr/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-Q | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6821437
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-navigation: ^4.4.2 => 4.4.2 
    npmGlobalPackages:
      expo-cli: 3.27.14
    Expo Workflow: managed

### Steps to Reproduce

Simply run this on a phone with 4G mobile data network activated
```
const {type, isConnected, isInternetReachable} = await Network.getNetworkStateAsync()
const generation = await Cellular.getCellularGenerationAsync();
```
gives
```
Network info {"type":"CELLULAR","isConnected":true,"isInternetReachable":true}
Cellular generation 0 (UNKNOWN)
```

### Expected Behavior vs Actual Behavior

Since cellular network is currently 4G displayed on my phone, i expected Cellular generation to give value 3, not 0.

Edit: My phone is a Huawei with Dual Sim, don't know if it is revelant or not.

Regards.

**Comment by byCedric** [comment]
Hi @bouchezb, thanks for the issue report with all the info we need! I can confirm this is happening on my OnePlus 6 (Android 10) as well, so this is probably a bug we have to take a look at.

But, you are lucky this isn't the only library with cellular information available in Expo. We also support [the NetInfo module (`v5.9.6` for SDK 39), extracted from React Native core](https://docs.expo.io/versions/latest/sdk/netinfo/). Instead of `expo-cellular`, you can also try using this module. With this, you also have 2 methods to determine if an internet connection is considered "expensive". The `isConnectionExpensive` (boolean) or `cellularGeneration` (string) properties.

I wrote up two example hooks that you can use, in typescript:

```ts
import * as NetInfo from '@react-native-community/netinfo';

function useNetworkExpesive(): boolean | null {
  const info = NetInfo.useNetInfo();

  return info.details?.isConnectionExpensive ?? null;
}

function useNetworkGeneration(): NetInfo.NetInfoCellularGeneration | null {
  const info = NetInfo.useNetInfo();

  return info.type === NetInfo.NetInfoStateType.cellular
    ? info.details.cellularGeneration
    : null;
}
```

Hope this helps!

**Comment by bouchezb** [comment]
Hi, @byCedric, thanks for your help.

I'll take a look at the solution with the NetInfo module.
Reading the documentation, this module seems to fit my needs.

Regards.

**Comment by EmilianoMorghen** [comment]
2 years later and this is still a bug... Verified on Pixel 3aXL
