### ISSUE TITLE
Error in an Standalone app with an underscore in the package name.

### ISSUE THREAD

**Issue by taschdo** [expo/expo#10911]
## 🐛 Bug Report

I use expo-google-app-auth.  I will explain very briefly. For example I have the **package name** **com.app.name_surname**, in this the name of the package authorization is not working. And if you remove the underscore in the **package name** **com.app.namesurname** authorization in the Standalone app works fine. How do I make authorization with an underscore in the package name work?

**Comment by byCedric** [comment]
Hi @taschdo, thanks for the issue but I'm not sure how I can help here. If you take a look at [`expo-google-app-auth` code](https://github.com/expo/expo/blob/master/packages/expo-google-app-auth/src/Google.ts#L8-L64), we don't ask for the package name in any of the configuration options. We ask for the Google OAuth client IDs, which are linked to your package name. But that's not something we manage for you, that's up to the person managing that Google OAuth client and configured through the Google API console. Redirects should also not be affected, because you should link to a scheme or the settings in your Google OAuth client.

If you have more info or actionable items what doesn't work for you, that would be helpful. Again, the combination of Google OAuth client and the package name is not something we manage for you.

Hope it helps!

**Comment by taschdo** [comment]
@byCedric Well, how?! The logInAsync method has a redirectUrl parameter. Defaults to ${AppAuth.OAuthRedirect}:/oauth2redirect/google. Optionally you can define your own redirect URL, just make sure to see the note below. This AppAuth.OAuthRedirect is the package name.

**Comment by cruzach** [comment]
@taschdo although you _can_ include an underscore in your android package name, it's generally not recommended (because you can run into issues like this)
