### ISSUE TITLE
--no-publish option is publishing the build

### ISSUE THREAD

**Issue by mattiascaricato** [expo/expo#10981]
Hi there,

When I'm building the app as follow `expo build:ios --no-publish`, expo is still publishing it. Am I missing something?

![image](https://user-images.githubusercontent.com/4216599/98732969-9b1aac00-237e-11eb-94e6-82e3be79b6f2.png)

Thanks

**Comment by cruzach** [comment]
It's using an existing release, if it were publishing you'd see
```

Building optimized bundles and generating sourcemaps...
Starting Metro Bundler.
Building iOS bundle
Building JavaScript bundle [================                                                ] 25%
```

**Comment by mattiascaricato** [comment]
it's not using an existing release. As you can see in the following screenshots, it's creating a new one:

![image](https://user-images.githubusercontent.com/4216599/98735124-aae7bf80-2381-11eb-9264-9dc1d3a314b9.png)

**Comment by mattiascaricato** [comment]
@cruzach can you please re-open the issue? Thanks!

**Comment by brentvatne** [comment]
@mattiascaricato - you seem to misunderstand, this is where the existing published release is being used:

![Screen Shot 2020-11-10 at 1 28 31 PM](https://user-images.githubusercontent.com/90494/98735709-b1157600-2358-11eb-866f-f75cd001b28f.png)

when it says "Build queued" it is running a native app build against your published JS and assets. what you shared above is totally expected behavior.

can you elaborate on what you expect `expo build:ios --no-publish` to do for you?

**Comment by mattiascaricato** [comment]
I see, so even without publishing the build is being executed in expo CI. So I'll setup my local fastlane + turtle-cli to build locally. Thank you guys!

**Comment by brentvatne** [comment]
@mattiascaricato - it is using the release that you have previously published using `expo publish` or running the build without this flag before. if you hadn't published it before, this command would fail because we can't do a build of your app without release js and assets. turtle-cli is an option for doing the build on your machine, but it's significantly more difficult to set up and so if i were you i would just go with using our build service if your company policies allow for it.

note that if you don't want expo to host your js and assets you can use `expo export` - you can find more info about this in docs
