### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module: when running Jest-expo tests

### ISSUE THREAD

**Issue by teja-kandula** [expo/expo#11012]
### Summary of Issue 
Jest test case throwing the error -> SyntaxError: Cannot use import statement outside a module:

Updated the ```transformIgnorePatterns```  as told in the last ticket but it is throwing the same error.  #10996 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Android

Error :

({"Object.":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle, { clearThemeCache } from "./src/connectStyle";
^^^^^^
```
SyntaxError: Cannot use import statement outside a module
```

### Reproducible Demo
This is to reopen a closed issue. https://github.com/expo/expo/issues/10996 

 
### Steps to Reproduce
1. Run yarn install
2. Run yarn test ( to replicate the test case)

### Expected Behavior vs Actual Behavior

The test case shouldn't throw any import related errors.

**Comment by teja-kandula** [comment]
Please keep it open until the issue is resolved.

**Comment by teja-kandula** [comment]
After adding one import statement at a time, the test case failed with the import related error when the below import statement is being used. 
```
import {
	Content,
	Container,
	H2,
	Form,
	Item,
	Input,
	Button,
	Text,
	View,
} from "native-base";
```

This is an expo provided default library, added this path to the ```transformIgnorePatterns``` but still when tried to import the above module it is throwing this error: 
```
({"Object.":function(module,exports,require,__dirname,__filename,global,jest){import connectStyle, { clearThemeCache } from "./src/connectStyle";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by velnychukyuracv** [comment]
Hi! I have the same issue:
SyntaxError: Cannot use import statement outside a module

  1 | import React, { useEffect, useRef } from 'react';
> 2 | import { Animated, StyleSheet, View } from 'react-native';


package.json:

"jest": {
"preset": "jest-expo",
"transformIgnorePatterns": [
"node_modules/(?!(jest-expo-)?react-native|react-native|@react-native-community|expo(nent)?|@expo(nent)?/.|react-navigation|@react-navigation/.|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
],
"moduleFileExtensions": [
"js",
"jsx",
"json",
"vue"
],
"transform": {
"^.+\.jsx?$": "babel-jest",
"^.+\.vue$": "vue-jest"
}
},

babel.config.js:

module.exports = function(api) {
api.cache(true);
return {
presets: ['babel-preset-expo'],
};
};

Can you please help me with it.

**Comment by theetrain** [comment]
I have this issue as well. It appears that `jest-expo` does not respect the `transform` key set in my `jest.config.js` file when testing multiple platforms.

## Regular config example

Given the following `jest.config.js`:

```js
module.exports = {
  preset: 'jest-expo', // 👈 note this preset
  transform: {
    '\\.[jt]sx?$': 'babel-jest'
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)'
  ]
}
```

I can view the resolved config by running `jest --showConfig`:

<details>
<summary>Show output</summary>

```js
{
  "configs": [
    {
      ...,
      "transform": [
        [ // 👇  here, my `transform` config is respected
          "\\.[jt]sx?$",
          "[redacted]/node_modules/jest-config/node_modules/babel-jest/build/index.js",
          {}
        ],
        [
          "^.+\\.(js|ts|tsx)$",
          "[redacted]/node_modules/babel-jest/build/index.js",
          {}
        ],
        [
          "^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp|ttf|otf|m4v|mov|mp4|mpeg|mpg|webm|aac|aiff|caf|m4a|mp3|wav|html|pdf|obj)$",
          "[redacted]/node_modules/jest-expo/src/preset/assetFileTransformer.js",
          {}
        ]
      ],
      ...
    }
  ],
  "globalConfig": {...},
  "version": "25.5.4"
}
```

</details>

## Multi-platform config example

Given the following `jest.config.js`:

```js
module.exports = {
  preset: 'jest-expo/universal', // 👈 note this preset
  transform: {
    '\\.[jt]sx?$': 'babel-jest'
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)'
  ]
}
```

The resolved config does not show my `transform` value. By running `jest --showConfig`:

<details>
<summary>Show output with issue ⚠️ </summary>

```js
{
  "configs": [
    {
      ...,
      "transform": [
        [ // 👇 Here, my setting is not respected. *.jsx files will not get transpiled with babel
          "^.+\\.(js|ts|tsx)$",
          "[redacted]/node_modules/jest-config/node_modules/babel-jest/build/index.js",
          {}
        ],
        [
          "^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp|ttf|otf|m4v|mov|mp4|mpeg|mpg|webm|aac|aiff|caf|m4a|mp3|wav|html|pdf|obj)$",
          "[redacted]/node_modules/jest-expo/src/preset/assetFileTransformer.js",
          {}
        ]
      ],
      "transformIgnorePatterns": [
        "node_modules/(?!(jest-)?react-native|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
      ],
      "watchPathIgnorePatterns": []
    },
    ...
  ],
  ...
}
```

</details>

Based on my observations, I will not be able to use babel-jest with `*.jsx` files if I also decide to use `jest-expo` with the `jest-expo/universal` preset OR if I use the `projects` key in my jest config. This is a bit disruptive since I don't know any alternatives to run jest in a multiplatform manner other than maybe creating mocks for `Platform.OS`. 

I discovered this issue partly thanks to this guide on how to set up babel with jest in expo projects: https://levelup.gitconnected.com/setting-up-jest-under-expo-to-work-with-jsx-files-ba35a51bc25a

**Comment by brentvatne** [comment]
thanks for the info on this possible transform issue @theetrain! if you have a runnable reproducible example on your machine, would you like to try to fix it and open a pr? the source for jest-expo lives in https://github.com/expo/expo/tree/master/packages/jest-expo

**Comment by theetrain** [comment]
@brentvatne sure, I can attempt a pull request, though I can use a hint. Where is the user's jest config loaded?

**Comment by brentvatne** [comment]
that is handled by jest. jest will load the preset from jest-expo/jest-preset.js and then apply the rest of your config (https://jestjs.io/docs/en/configuration#preset-string)

**Comment by theetrain** [comment]
I've set up a repository to work out the issue and I've observed a few things:

- I need to have both `jest` and `jest-expo` added as dependencies
  - My tests are running for `web` and `ios` successfully, though I think it's calling the jest CLI from the `jest` dependency and not `jest-expo` since that's the command that resides in `node_modules/.bin/jest`
- I need to specify `transform` within each object in the `projects` array in my [jest.config.js](https://github.com/theetrain/expo-example/blob/0f927fdc14aee8eb2413e8e0ba268594a8f196ce/jest.config.js)

To see the successful example, clone my project https://github.com/theetrain/expo-example and then run:

```
npm ci
npm run test
```

While I got this working in a clean project, I tried using the exact same `jest.config.js` in my work project and I received the following error:

```
/[redacted]/components/UniversalLink/UniversalLink.test.jsx:3
    import React from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

---

With that said, there are still issues:

Current behaviour: 

1. The tests run properly with `*.jsx` files so long as `transform` is defined in `jest.config.js` within each object element inside the `projects` array [see jest.config.js example](https://github.com/theetrain/expo-example/blob/0f927fdc14aee8eb2413e8e0ba268594a8f196ce/jest.config.js)
2. When using the `jest-expo/universal` preset, the `transform` key is not acknowledged and my `*.jsx` files won't flow through babel. It sticks with the default `.[jt]s?(x)` pattern defined here (I think):
  https://github.com/expo/expo/blob/9e17169a9e3cf412ed538b6e2de043b38728ed83/packages/jest-expo/config/getPlatformPreset.js#L15

Proposed behaviour:

1. If there is a `transform` key defined at the root of `jest.config.js`, then it is respected by every preset defined in the `projects` array, or when using the `jest-expo/universal` preset
2. If a `transform` key is defined inside one of the preset objects inside `projects`, then that value takes priority over any `transform` key defined at the root of `jest.config.js`
3. The `jest` dependency shouldn't need to be explicitly installed in a project; perhaps it should be a peerDependency of `jest-expo`? I'm not sure why having both installed worked for me, but only having `jest-expo` does not work
3. The default regex pattern to transform test files is `\\.[jt]sx?$`; though I can imagine how this would be breaking so I'm not recommending this too much

If this sounds ideal, then I'm happy to continue helping with a contribution. It's a bit challenging for me to navigate the source code for `jest-expo` and I could use some pointers for the following:

- Though `jest` handles the processing of `jest.config.js`, where is that ingested within `jest-expo`, if at all? I've observed that a file `jest-preset.js` creates a base configuration, but it doesn't seem to be merging with any user-defined configs.

P.S. if you'd rather continue this conversation in a PR or separate issue, let me know.

**Comment by brentvatne** [comment]
> Though jest handles the processing of jest.config.js, where is that ingested within jest-expo, if at all? I've observed that a file jest-preset.js creates a base configuration, but it doesn't seem to be merging with any user-defined configs.

I suspect that the behavior that you are seeing is due to some quirk in the way jest handles merging configs - we don't ingest the developer's jest config in jest-expo, that's all handled by jest.

You can merge configs yourself though because it's a js file, and then you get more control. Something like this should work:

```js
const jestExpoPreset = require('jest-expo/jest-preset');

module.exports = {
  ...jestExpoPreset,
  transform: {
    '\\.[jt]sx?$': 'babel-jest'
  },
  transformIgnorePatterns: [
    ...jestExpoPreset.transformIgnorePatterns,
    'some-other-lib',
  ]
}
```

**Comment by theetrain** [comment]
Thanks for your suggestion. Importing the preset turned out to be part of the solution, but a few more things were needed. Things behaved correctly when we did the following:

1. Manually import the expo presets we needed, and then and add our own `baseConfig`
2. Set up a special babel config just for jest, without using the conventional `babel.config.js` filename in order to avoid conflicts with Expo and NextJS in our project
3. Install necessary babel dependencies. Our **package.json** includes the following:

```json
{
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/plugin-proposal-class-properties": "^7.12.13",
    "@babel/plugin-transform-runtime": "^7.12.15",
    "@babel/preset-env": "^7.12.13",
    "babel-jest": "^26.6.3",
    "jest-expo": "^40.0.2",
    "react-test-renderer": "^17.0.1"
  }
}
```

I think there's an opportunity for this preset-importing tip to be added to Expo's Jest documentation.

🎁  For those following this thread, here are copies of our working jest and special babel configs:

<details>
<summary>jest.config.js and babel-jest.config.js</summary>

**jest.config.js**

```js
const iOS = require('jest-expo/ios/jest-preset')
const android = require('jest-expo/android/jest-preset')

const baseConfig = {
  transform: {
    '\\.[jt]sx?$': ['babel-jest', { configFile: './babel-jest.config.js' }]
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)'
  ],
  testPathIgnorePatterns: [
    '<rootDir>/.next/',
    '<rootDir>/node_modules/',
    '<rootDir>/cypress/' // only needed if you use cypress
  ]
}

module.exports = {
  projects: [
    {
      ...iOS,
      ...baseConfig
    },
    {
      ...android,
      ...baseConfig
    },
    {
      displayName: 'Web',
      preset: 'react-native-web',
      // This is brittle, we did this so snapshot naming/modifying is consistent
      snapshotResolver: 'jest-expo/src/snapshot/resolver.web.js',
      ...baseConfig
    }
  ],
}
```

**babel-jest.config.js** (referenced only in jest.config.js)

```js
module.exports = function babelJestConfig (api) {
  api.cache(true)
  return {
    presets: ['@babel/preset-env', 'babel-preset-expo', '@expo/next-adapter/babel'],
    plugins: [
      '@babel/plugin-transform-runtime',
      '@babel/plugin-proposal-class-properties'
    ]
  }
}
```

</details>


Hat tip to @marcod1419 for figuring this out. 👏
