### ISSUE TITLE
Feature request - support OneSignal

### ISSUE THREAD

**Issue by eladcandroid** [expo/expo#1105]
It's a great and free cross platform push notification delivery that make it easy to integrate without all the overhead around.
Here's a library for react native:
https://github.com/geektimecoil/react-native-onesignal

**Comment by kadoshms** [comment]
+1

**Comment by btk** [comment]
Expo project takes feature requests via canny. You should open a thread there;

https://expo.canny.io/feature-requests

**Comment by terribleben** [comment]
Thanks! As mentioned in the last comment, we're tracking this on canny, so I'll direct this thread there. ^

**Comment by Nightsd01** [comment]
Hi everyone, just a quick notice. Previously, if you attempted to load OneSignal in an Expo app before detaching, you would see runtime errors.

We've recently updated the OneSignal react-native SDK (3.2.0) so that it will no longer cause a crash if you run it in the Expo client.

Essentially, we've made it so that the SDK will check to make sure the native bridge exists before attempting to use it.

Unfortunately, the Expo client can't let us run native code (iOS restriction), so we can't actually use our iOS/Android SDK's. This means that when you call OneSignal functions like sendTags() from within an app running in the Expo client, nothing will happen. But at least it's better than instantly crashing when the app launches.

The SDK should start functioning correctly once you detach from expo and link. If you have any questions, please feel free to contact our support (I will see your ticket) by going to the onesignal dashboard and clicking the ? button.

**Comment by tewris-rn** [comment]
Where is the documentation how to integrate it?
