### ISSUE TITLE
iOS v2.2.1 build fails

### ISSUE THREAD

**Issue by digitaledge** [expo/expo#1106]
Hi,
i just upgraded to v2.2.1, because i need the payment module wich was broken in the previous release.

Actually the build fails in xcode as you can see here:
![bildschirmfoto 2017-12-13 um 17 42 19](https://user-images.githubusercontent.com/3514563/33950710-5f872278-e02d-11e7-9a0b-af1314e7ddca.png)

Am i doing something wrong? Or is this a bug?

**Comment by terribleben** [comment]
Hi! v2.2.1 uses Expo SDK 24, which just started rolling out last night. SDK 24 targets a newer version of React Native, so you'll need to update all your dependencies before it will build. (the error you pasted suggests that your project is still referencing a previous version of React Native, because the macro definition for `RCT_REMAP_BLOCKING...` changed between versions.)

We'll be posting a blog sometime today with release notes and specific SDK 24 update instructions. Until then, I recommend waiting a few hours. Let me know if you're still having issues after that.

**Comment by digitaledge** [comment]
Hi, i have also tried to update all dependencies to SDK 24. That failed when detaching to android, but iOS did work:

`Validating project manifest...
Creating ExpoKit workspace at /Users/stefan/Documents/Apps/bars/ios...
Downloading iOS code...
Moving iOS project files...
Naming iOS project...
Configuring iOS dependencies...
Configuring iOS project...
Modifying NSBundle configuration at /Users/stefan/Documents/Apps/bars/ios/bars/Supporting...
We added some permissions keys to `Info.plist` in your detached iOS project:
  NSMotionUsageDescription
  NSCameraUsageDescription
  NSMicrophoneUsageDescription
  NSPhotoLibraryAddUsageDescription
  NSContactsUsageDescription
  NSPhotoLibraryUsageDescription
  NSLocationWhenInUseUsageDescription
You may want to revise them to include language appropriate to your project. You can also remove them if your app will never use the corresponding API. See the Apple docs for these keys.
Using shell config: { manifestUrl: 'exp://exp.host/@digitaledge/bars',
  isShell: true,
  releaseChannel: 'default',
  isManifestVerificationBypassed: true }
Your iOS ExpoKit project will not contain an .entitlements file by default. If you need specific Apple entitlements, enable them manually via Xcode or the Apple Developer website.
Configuring iOS Launch Screen...
Cleaning up iOS...
iOS detach is complete!
Downloading Android code...
Moving Android project files...
(node:3351) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '_isCommandError' of undefined
`
