### ISSUE TITLE
MediaLibrary.getAssetsAsync(expo-media-library) crashes on Android

### ISSUE THREAD

**Issue by Shing-Ho** [expo/expo#11067]
### Summary of Issue 
MediaLibrary.getAssetsAsync(expo-media-library) is crashing on Android right after call it. There's no console for it.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
Expo CLI 3.28.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.29 
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
      react-navigation: ^4.3.9 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 3.28.5
    Expo Workflow: managed
```

### Reproducible Demo

https://snack.expo.io/@talentexpo/expo-media-library-test

### Steps to Reproduce

Just open snack it will call right after open snack.

### Expected Behavior vs Actual Behavior

Should not crash

**Comment by Shing-Ho** [comment]
@brentvatne Could you please check this ticket?

**Comment by cruzach** [comment]
@Shing-Ho please don't tag Brent (or anyone else, really) in the issues you open. We work through the issues that get opened as quickly as we can, and tagging people unnecessarily will not result in your issue getting attention sooner. The best way to ensure a quick fix to your issue is to provide a reproducible demo. I tested your snack on Android and it is not crashing

**Comment by natysoz** [comment]
see my original post 
https://github.com/expo/expo/issues/10398

also post 
https://github.com/expo/expo/issues/10488

its still happen on latest expo 39 for me , and i can easy reproduce it ...

on real devices , if you get some random telegram pictures and videos , move them to your main camera folder for 
example , you'll easily get the EXIF error , i dont know why but maybe it something related to that the images come from telegram are not well formatted and indexed by android os .

i said that because if i go to my real device , click on Gallery , clear the app cache , then let it Index all images on my device again 

then everything become normal and working ...

maybe , i dont know i just suggest testing..
maybe the android system is not indexing some kind of telegram images and this cause this issue.

do you have telegram installed on your device @Shing-Ho

**Comment by Shing-Ho** [comment]
Yes, I think it's not working on the telegram installed phone

**Comment by brentvatne** [comment]
if you uninstall telegram does that resolve the issue? if so we can investigate with that information

**Comment by natysoz** [comment]
if u delete the assets that comes from telegram yes , you dont have to uninstall it , 
and not each asset its randomly , cause its telegram , there are so many types of assets there ,
but , if u go and delete your Gallery app cache , and let android Index all images on phone again , 
it will solve the issue , 

its like some images sent on telegram , has no information or not recognized and cause a crash .

**Comment by cyates81** [comment]
I just wanted to add that I'm experiencing the same problem, however, I don't have Telegram on my phone. I deleted the cache by going to Settings -> Storage - > Photos & Videos and clearing for Camera, Photos, and Videos and it's still crashing.

**Comment by cyates81** [comment]
Never mind, I think my issue was relate to #10398, I updated to expo 39 and it's working now.
