### ISSUE TITLE
localeCompare does not work as expected

### ISSUE THREAD

**Issue by KrisGerhard** [expo/expo#11076]
### Summary of Issue 
Sorting chars according to a defined locale does not work as expected on Android

### Reproducible Demo
https://snack.expo.io/@leifer/localcompare-sorting
 
### Expected Behavior vs Actual Behavior
Expected: `ABCDEFGHIJKLMNOPRSŠZŽTUVÕÄÖÜ`
Actual: `ABCDEFGHIJKLMNOPRSZTUVÕÄÖÜŠŽ`

**Comment by AdamJNavarro** [comment]
Hey @KrisGerhard, based on this [SO post](https://stackoverflow.com/questions/53189516/react-native-localecompare-not-working-on-android) it appears this is an issue with react-native rather than an Expo-specific one. The last post in the SO thread alludes to a change you can make at the native level that may remedy this and another post that mentions using lodash's `deburr` method which may allow you to keep your project in the Managed workflow if you desired.

Cheers,
Adam
