### ISSUE TITLE
[expo-image-picker] Issues with getPendingResultAsync() method

### ISSUE THREAD

**Issue by zandrei** [expo/expo#11103]
### Summary of Issue 
The getPendingResultAsync() method should provide results regardless of the way the camera was started. If the application starts the camera with "allowEditing" = false, then the picture taken is never added to the sharedPreferences. Going through the master code, the issue seems to be at line 323 in ImagePickerModule.kt in shouldHandleOnActivityResult() where it checks if requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE. This check will be false and the result of the whole method will be false which will lead to the current taken image to not be persisted in the sharedPeferences.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
react native bare 0.63.3
expo-image-picker 9.1.1

Android 10 emulator
 
### Steps to Reproduce
Try to use the getPendingResultAsync() functionality by checking the "Don't keep activities" in the Developer options of the Android emulator.

### Expected Behavior vs Actual Behavior
The last image before host application restart should be persisted and the library notify the host application of this picture through this callback.

The initial functionality was added through this merge request: https://github.com/expo/expo/pull/9697/files

**Comment by zandrei** [comment]
@lukmccall Do you have any input on why the specific check was done only for the CROP intent?

**Comment by lukmccall** [comment]
Hi @zandrei, this check was done only for the `CROP` intent because, in other flows, the `activity === experienceActivity` condition should be true.

Why is the `CROP` intent so special? The answer is pretty simple - when you trigger the edit mode, the new activity is launched so we can't compare references. 
In other cases, it should work because the RN should, in the `onActivityResult` callback, provided the destroyed activity (so the reference comparison returns `true` in that case).

**Comment by lukmccall** [comment]
However, it will be nice if you test this functionality without `requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE` check. Because maybe we can't assume that the RN gives the destroyed activity.

**Comment by zandrei** [comment]
Thank you for your answer. This is the exact reason why I asked about this condition, because the first part of the condition is never true. Without that condition (the crop intent verification), the flow works. However, there is a slightly even more worrying use case, in which the Android OS will kill the ReactContext (you can test this with "Don't keep activities" true and "Background process limit" set to "No background processes"). In this case, the onActivityResult of the ImagePicker sometimes does not get called (because of the different threads on which the reactContext gets recreated and the onActivityResult is passed in the ReactInstanceManager - issue opened here with React Native: https://github.com/facebook/react-native/issues/30277). Have you tested with this scenario? Do you have any suggestion of a solution/workaround for that use case?

**Comment by lukmccall** [comment]
Ohh... I see. 
I didn't test it using the `No background processes` option selected. Right now I don't know how we can fix that. Moreover, I'm not sure if it event possible without fixing the origin issue in the RN. 

But, I think the best solution for `expo-image-picker` is to change the request codes for `CAMERA` and `MEDIA_LIBRARY` here:
https://github.com/expo/expo/blob/677e71fa464494f7543802c90009af9e244a8012/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/ImagePickerConstants.kt#L7-L8
to something more unique. Then in `shouldHandleOnActivityResult` check if `mWasDestroyed` is true and the request code came from the `image-picker`.

It doesn't' fix the issue when the `ReactContext` was destroyed, but for other cases, it seems to work fine.

**Comment by HugoGresse** [comment]
For the sake of cross-referencing most related issues from other modules and working on a workaround, I've created a repo: https://github.com/HugoGresse/react-native-issue-30277/blob/main/README.md

**Comment by peterkuiper** [comment]
@HugoGresse Do you already have a workaround in mind for `expo-imagepicker`? I am currently having problems with this module (empty result from `getPendingResultAsync()`) and I would love to help out and fix it.

**Comment by HugoGresse** [comment]
@peterkuiper nop, I don't use expo but I've made one for "react-native-image-crop-picker" which should not be far from expo: https://github.com/HugoGresse/react-native-issue-30277/blob/main/PATCH-react-native-image-crop-picker.md
They are a lots of caveats and it's only a workaround, no way to only patch the expo module I think (the app is restarted entirely, state loss)

**Comment by peterkuiper** [comment]
@HugoGresse I also don't use `expo` directly, but through `unimodules`. It seems the `expo-image-picker` module should store the result in `SharedPreferences` so you can access it after the app is restarted. I think that is basically how you fixed `react-native-image-crop-picker`. Maybe I am mistaken how this should work since you mentioned `expo-image-picker` specifically in your issue repo.

**Comment by HugoGresse** [comment]
@peterkuiper you're right, I use SP to store the state of the module and be able to recover it when the app is restarted. However, I needed to re-establish the link between the app and the module on app restart. `react-native-image-crop-picker` return a promise from `openCamera()`. This promise is never resolved nor rejected because when the camera action is completed, the app is restarted before the promise can resolve. 
In my workaround, I've changed 3 things: 

1. The `SharedPreferences` data are used on the module initialization to recover it's internal state
2. The `MainActivity.java` is patched by the user to forward the [`onActivityResult` to the `mPickerModule30277Workaround`](https://github.com/HugoGresse/react-native-issue-30277/blob/main/patches/react-native-image-crop-picker%2B0.36.0.patch#L655). The `PickerModule30277Workaround` then wait for the ReactContext to be ready via a listener and then when the context is up and running, forward the call to the module. This is the last part regarding the module to be in the same state as in other device after expect `onActivityResult` flow. 
3.  Added a method on the module `ImagePicker.recoverLastImageUri()` which allow be to re-establish the link with the module and recover the results when the app is restarted.

Regarding the adaptation of the application itself, it is a little harder. When the app is restarted, I need to detect that it is able to recover the `lastImageUri` from the camera, open the proper screen and forward the results. If you are using redux and persisting the state on every change, there you should be mostly good. In my case I needed to make some adjusment as this state is not persisted (=volatile). 
On top of that, what about a second `openCamera()` action? Well, in my case I'll forbid the user to do that to prevent additional complexity within the app. But it's doable for sure.

**Comment by Sixtisam** [comment]
Any update on this? Is someone working to fix this? If I enable `Dont keep activities`, `getPendingResultAsync` always returns an empty array. So it seems like `getPendingResultAsync` isnt working at all.

As long as this is not fixed, `expo-image-picker` is basically unusable because on android phones, this will happen on phones with low memory.
I didn't test the fix of @HugoGresse yet, but for Managed Workflow users this isn't an option anyway.

**Comment by petecoop** [comment]
I've been struggling with this issue today too, `getPendingResultAsync` just didn't seem to work and I don't feel like there's enough documentation on this. After coming against it for a while I've found that I can work around this issue by storing a list of the files from `${FileSystem.cacheDirectory}/ImagePicker/` when I launch the camera, and then re-check against that list when the app re-opens, a new file is added if the user completed taking a picture.

**Comment by thariqwarsa** [comment]
maybe this thread can help [https://github.com/expo/expo/issues/19509](https://github.com/expo/expo/issues/19509)
