### ISSUE TITLE
Did Expo send a fix Push notifications to SDK 39?

### ISSUE THREAD

**Issue by podroomdevelopers** [expo/expo#11107]
My team upgraded to SDK 39 some weeks ago and we had push notification listener issues: our devices received push notification but when clicked, it opened the app but didn't lead to the exact tab. Yesterday, we ran "expo upgrade" just for fun and Voila! Notification leads to the exact tab. We want to know what happened, was this a fix by expo? Is Expo push notification unstable? Is there a chance that it could return to the previous state of not functioning properly?

We have both apks, same code base with SDK 39, push notification works properly on one and it doesn't work properly in the other.

Thanks.

**Comment by cruzach** [comment]
SDK 39 is the most recent release, so `expo upgrade` wouldn't upgrade the SDK further if you were already on SDK 39. Maybe if you had _manually_ upgraded SDKs before that, you may not have upgraded the `expo-notifications` library. Otherwise, we can't really help here unless you provide us with more information

If you're looking for a list of changes in `expo-notifications`, you can refer to the changelog: https://github.com/expo/expo/blob/master/packages/expo-notifications/CHANGELOG.md
And here's the changelog for SDK 39: https://github.com/expo/expo/blob/master/CHANGELOG.md#3900--2020-08-18
