### ISSUE TITLE
expo-image-picker launchCameraAsync can't edit button text of camera

### ISSUE THREAD

**Issue by jasonjiflyer** [expo/expo#11189]
OS: iOS
I can't find an API to set the button text when taking a picture. The texts are 'Cancel' 'PHOTO'
If a final customer doesn't speak English, he can't understand what does it mean.
![image](https://user-images.githubusercontent.com/39817873/100836966-3cdb7780-34ab-11eb-9c50-851383a193b2.png)

**Comment by byCedric** [comment]
Hi @jasonjiflyer! Under the hood we use Apple's [`UIImagePickerController`](https://developer.apple.com/documentation/uikit/uiimagepickercontroller). That means that the view you sent, is translated automatically to the language set on the device. Unfortunately, you can't edit the text on this view due to limitations in this API. But the concern related to language shouldn't be a problem 😄
