### ISSUE TITLE
expo xde does not connect iphone,  only android device work good. 

### ISSUE THREAD

**Issue by chipanda** [expo/expo#1119]
I use the lastest version expo xde (2.22.1）. Both ios and android phone load the blank example project and work successfully.Only the iphone can not output log in log panel, and there is only android device in connected devices.
Here is the app.json:
```javascript
{
  "expo": {
    "name": "expo-test",
    "description": "This project is really great.",
    "slug": "expo-test",
    "privacy": "public",
    "sdkVersion": "24.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "ios": {
      "supportsTablet": true
    }
  }
}
```

**Comment by terribleben** [comment]
Hi, thanks for the report. Can you help us out by adding:

- What steps you performed,
- What you expected to happen,
- What happened instead of your expectation?

Also, can you mention the following?

- iPhone device or simulator?
- Does XDE show you a "tunnel" or a localhost url?
- Does your XDE log show any errors in the packager or notifications pane?
