### ISSUE TITLE
The expo test project runs on the mobile phone and reports the network timeout

### ISSUE THREAD

**Issue by mofengfs** [expo/expo#11233]
### >>>Emulator
![image](https://user-images.githubusercontent.com/16655229/101232286-d4c7a400-36eb-11eb-95ac-06d206a699a3.png)
### >>>Phone
![image](https://user-images.githubusercontent.com/16655229/101232881-70a6df00-36ef-11eb-8edd-f371800e0cfc.png)

**Comment by AdamJNavarro** [comment]
Hey @mofengfs, can you provide the results of `expo diagnostics`? Also, do you potentially have any firewalls, anti-virus programs or some other networking functionality that could be interfering?

Cheers,
Adam

**Comment by mofengfs** [comment]
hey @AdamJNavarro ,
I live in a hell country and I need to `over the wall`. So I need to turn on VPN.

**Comment by byCedric** [comment]
Hi @mofengfs, that's unfortunate to hear. What's probably happening is that your phone is connected to a different subnet compared to your computer. We can't really avoid this or recover from this, it's mostly the developer's network configuration. The simulator might be working because we tunnel the connection from Expo CLI, through ADB, to connect it to "localhost".

A couple of things you can try to work around this issue:
1. Use tunnel instead of lan, if you start expo with `--tunnel` (or switch to tunnel network type), you avoid local VPNs or firewalls and tunnel the connection straight to ngrok. This might help to access it on your phone.
2. Try manual tunneling with ADB, [this guide can help with that](https://blog.usejournal.com/adb-port-forwarding-and-reversing-d2bc71835d43). We use the [same commands for Expo CLI and emulators](https://github.com/expo/expo-cli/blob/78911b41033d5ac2aa85552bcd71f571cafe155b/packages/xdl/src/Android.ts#L723-L798).

Hope this helps!
