### ISSUE TITLE
@expo/vector-icons -  IonIcons "ios" variants of icons showing "md" variant instead.

### ISSUE THREAD

**Issue by harterc1** [expo/expo#11237]
### Summary of Issue

`IonIcons` has icons:
- `ios-arrow-back`
- `md-arrow-back`

If you use `ios-arrow-back`, you'll get `md-arrow-back` rendered instead.

### Environment

Testing on iPhone X device

```
Expo CLI 4.0.8 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.13.0 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0-beta.5 => 40.0.0-beta.5 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 4.0.8
    Expo Workflow: managed
```

### Reproducible Demo

```
import { Ionicons } from '@expo/vector-icons';

<IonIcons name="ios-arrow-back" />

```
 
### Steps to Reproduce

Just look at it.

### Expected Behavior vs Actual Behavior

If you use `ios-arrow-back`, you'll get `md-arrow-back` rendered instead.

**Comment by AdamJNavarro** [comment]
Hey @harterc1, I created a new project and I'm seeing the appropriate icon being rendered (ios-arrow-back). Could you please provide a runnable repro of this so we can test it on our end? Once you do so and we can reproduce it on our end, I'll re-open this issue.

Cheers,
Adam

**Comment by harterc1** [comment]
`<div data-snack-id="@harterc1/ludicrous-hummus" data-snack-platform="web" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#F9F9F9;border:1px solid var(--color-border);border-radius:4px;height:505px;width:100%"></div>
<script async src="https://snack.expo.io/embed.js"></script>`

**Comment by harterc1** [comment]
@AdamJNavarro Any chance we re-open this?

**Comment by brentvatne** [comment]
@harterc1 - @expo/vector-icons is a modified version of react-native-vector-icons to use expo-font, we use the exact same icon configuration as react-native-vector-icons.

notice that in react-native-vector-icons they use the same icon code for ios-arrow-back and md-arrow-back:

https://github.com/oblador/react-native-vector-icons/blob/3458ae8e0d54f3fea821bfc8f5bbb5b67718e60f/glyphmaps/Ionicons.json#L1265
https://github.com/oblador/react-native-vector-icons/blob/3458ae8e0d54f3fea821bfc8f5bbb5b67718e60f/glyphmaps/Ionicons.json#L2492

that's why we have this configuration here. i do not know why they have decided to do this, it could be that the ionicons font family dropped the ios back icon and so they tried to provide some fallback for people. maybe it's a typo.

if you want to investigate further and open a pr or issue to react-native-vector-icons, we can sync the change to this repository once it has been made there :)

**Comment by harterc1** [comment]
@brentvatne I do **not** have plans to investigate further, but thank you for digging!  Makes sense.
