### ISSUE TITLE
Sending push notifications with custom sound via expo-server-sdk throws an error

### ISSUE THREAD

**Issue by todorone** [expo/expo#11248]
### Summary of Issue 

While `expo-notifications` is able to handle custom notification sounds, when trying to send push notifications with custom sound via `expo-server-sdk`, it throws a validation error:

```
Error: "[0].sound" must be one of [default, null, object].
    at Expo.getErrorFromResultError (/Users/work/Repositories/kiko-mobile/node_modules/expo-server-sdk/src/ExpoClient.ts:291:36)
    at Expo.getErrorFromResult (/Users/work/Repositories/kiko-mobile/node_modules/expo-server-sdk/src/ExpoClient.ts:280:41)
    at Expo.<anonymous> (/Users/work/Repositories/kiko-mobile/node_modules/expo-server-sdk/src/ExpoClient.ts:261:17)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/work/Repositories/kiko-mobile/node_modules/expo-server-sdk/build/ExpoClient.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'API_ERROR'
}
```

**Comment by cruzach** [comment]
Expo's push notification service does not support custom notification sounds yet ([you should refer to the documentation for more information](https://docs.expo.io/push-notifications/sending-notifications/#message-request-format)). If you'd like to send remote notifications with custom notification sounds, [you can communicate directly with APNS and FCM](https://docs.expo.io/push-notifications/sending-notifications-custom/)

**Comment by jmtimko5** [comment]
How can you claim this is supported fully in the notifications package, but not in the server sdk? If I can't use the server SDK, it makes using the notifcations package significantly less compelling. It sounds like it is not supported and what I need to do is expo eject. Is there anyway around this without ejecting?

**Comment by cruzach** [comment]
The `expo-notifications` package is separate from the Expo Push Notification service. It's important to give developers flexibility in terms of what services they want to use (i.e. if you would rather use FCM and APNs directly, you should be able to do just that). I totally understand that it'd be nicer if it was supported, and we're working on that (https://github.com/expo/expo/issues/12969), but that doesn't mean we _shouldn't_ add support for it in the client package so that developers can still use this feature (a) in local notifications and (b) in push notifications via FCM and APNs.

You do not need to eject, you just need to follow [this guide](https://docs.expo.dev/push-notifications/sending-notifications-custom/)

**Comment by jmtimko5** [comment]
Thank you for providing the guidance. Something that might be useful is explicitly calling out that developers must use APN/FCM to use this feature. The fact that is exclusive to to EAS led me to believe that this was a more "expo" feature and thus led me to expect that the simplest way forward would be to use Expo all the way through (Expo push notification service, EAS etc.). That's a easy mistake to fall into IMO, just would be helpful to be clear about the limitation here. Appreciate all your work.

**Comment by yoitscarolinee** [comment]
Just fell into this "trap", I totally got into the EAS and Expo stuff and right after I made all my codebase using this "Feature" that should work, but it doesn't.
![image](https://github.com/expo/expo/assets/86090176/7d4b1481-4831-40cd-977a-9aea83a80d03)

Thanks for the guidance too 😃
