### ISSUE TITLE
[expo-gl] Pass animation values as uniform

### ISSUE THREAD

**Issue by wcandillon** [expo/expo#11267]
I was wondering if it is possible with expo-gl to pass animation values as uniforms so that we can run animations on the UI thread without involving the JS thread. Changes in the animation values would trigger a redraw() on the UI thread. I realize that this might a bit too different than how are things done with OpenGL APIs. I am curious to see how we could solve this problem.

**Comment by byCedric** [comment]
cc @tsapeta or @bbarthec, do you have more context on this?

**Comment by tsapeta** [comment]
@wcandillon, that's interesting idea 🤔 I can't say too much off the top of my head, but I'm gonna investigate it, discuss with Reanimated team and come back here soon.
At first glance it seems to be possible to implement, but we also need to keep in mind that `expo-gl` is an implementation of WebGL 2.0 standard and that needs to stay as is, so we would have to offer some custom APIs for this.

**Comment by wcandillon** [comment]
maybe the ability to run the gl functions within an animation worklet? then
it would be the same API

**Comment by kmagiera** [comment]
I think this is a great idea @wcandillon – do you maybe have some time to expand on the issue description to add some "real-life" usecase and possibly a code snippets with some ideas of how the API could look like? This would be very helpful to other people from reanimated team to understand this proposal better and be able to participate in this discussion

**Comment by wcandillon** [comment]
I looked at examples such as this one: https://webglfundamentals.org/webgl/lessons/webgl-animation.html and "all we need" (😅) is the `gl` object available on the UI thread. Then a way to know when to redraw. for instance:

```
const ref = useAnimatedRef();
useAnimatedReaction(() => Math.round(new Date().getTime()/16)), (now) => {
  const gl = getGL(ref)
  reDraw(noew, gl.value)
})
return ( <GLView style={{ width: 300, height: 300 }} ref={ref} onContextCreate={onContextCreate}  />)
```

Of course it would be better to have something like this:

```
const ref = useAnimatedRef();
useAnimatedFrame((now) => {
  const gl = getGL(ref)
  reDraw(now, gl.value)
})
return ( <GLView style={{ width: 300, height: 300 }} ref={ref} onContextCreate={onContextCreate}  />)
```

I noticed that to expose RN methods to the UI thread, there is no generic yet (methods like scrollTo are de-duplicated, you're cannot generical invoke any method based on the animated ref). So I assume this might be a difficult problem to solve. Please let me know what I can do to help.

**Comment by kmagiera** [comment]
Would that meant that things like expo-three should also be available from the UI thread?

As for generic method support this is actually a separate thing from running native module commands. AFAIK expo-gl does not use native module commands or even native view commands, instead it injects its own native methods into the JS runtime (+ there is some scheduling done under the hood such that all gl methods can be synchronous). Maybe a possible approach would be for expo-gl to set everything up on the UI JS runtime instead of RN main JS runtime (cc @tsapeta – do you think it would be possible?)

**Comment by wcandillon** [comment]
That's sounds awesome. Then we would still need some sort of a scheduling mechanism on the UI thread (useAnimatedReaction or a new useAnimatedFrame hook)

**Comment by sergeymorkovkin** [comment]
Guys, this is a big thing which is missing. I personally see we need two things:

1. Be able to call expo-gl methods from the UI thread (currently not supported)
2. Something similar to useAnimatedStyle for passing animated value as uniforms

**By the way, is there any progress on this?**

**Comment by schiller-manuel** [comment]
Did anyone start working on this?

**Comment by sergeymorkovkin** [comment]
> Did anyone start working on this?

Looks like nobody needs sophisticated stuff in the scope of React Native. Most projects are lists/forms.

**Comment by schiller-manuel** [comment]
I need it and would like to contribute. But I am not sure where to start... 
@wcandillon since you experimented with https://github.com/wcandillon/react-native-shader
do you think it's feasible to implement this in expo-gl? or is a rewrite from scratch as you did the only way to go?

**Comment by sergeymorkovkin** [comment]
@schiller-manuel I've experimented with both expo-gl and react-native-shader. Can confidently state a two things on expo-gl:

- expo-gl is too slow for real-time animations, primarily due to JS <-> native communication
- even though it can become a good starting point for the job

Expo unimodules add some additional queueing to messages (read method calls) you invoke on expo-gl. This queue is a price to pay for syncing JS and native threads. It'll surely work well on even old iPhones (e.g. I was testing on 6s), but will produce janky animation on cheap Androids (e.g. Oppo A5). Primarily, you'll experience frame drops. 

If you want an adventurous technical journey - go for it. If you need to get things done - consider other platforms.

P.S. William's experiments with react-native-shader are static. For 60 FPS it's unacceptable - adds ~35% CPU overhead, even compared to expo-gl.

**Comment by tsapeta** [comment]
@sergeymorkovkin 
> expo-gl is too slow for real-time animations, primarily due to JS <-> native communication

There is almost no overhead here — methods of the `gl` object are native (C++) methods installed through JSI, so they bypass the JS <-> native bridge, so also the argument about unimodules is not valid. I know about many apps with real-time animations using `expo-gl` and having 60FPS, maybe your use case is just too complex or/and not optimized?

Together with Reanimated team, we've been researching the possibility to use `gl` on the UI thread and it seemed to be pretty complex to implement and we were not sure how big is the need for such functionality. I'd love to hear your use cases to better understand your needs.

**Comment by wcandillon** [comment]
I feel like the use-case is removing the overhead of having the animation value go from UI thread to the JS thread to then to the GL thread.

**Comment by schiller-manuel** [comment]
I think interactions based on react-native-gesture-handler would also be smoother, right?

**Comment by sergeymorkovkin** [comment]
> @sergeymorkovkin
> 
> > expo-gl is too slow for real-time animations, primarily due to JS <-> native communication
> 
> There is almost no overhead here — methods of the `gl` object are native (C++) methods installed through JSI, so they bypass the JS <-> native bridge, so also the argument about unimodules is not valid. 

I'm sharing my observations of the prototype I've built around half a year ago. I assume this overhead was coming not from the bridge itself, but the queue on the native side of unimodules. Have no confirmation of this - just an assumption.

> I know about many apps with real-time animations using `expo-gl` and having 60FPS, 

Please provide at least one example. I can test these apps on the same cheap Android phone.

> maybe your use case is just too complex or/and not optimized?

It was just a basic animation (rotating rectangle) implemented with a vertex shader. Used requestAnimationFrame for updating uniform and re-rendering. That's all. I was comparing to PixiJS demo open in a browser on the same device - [that looked perfect](https://pixijs.io/examples/#/demos-basic/container.js).

> Together with Reanimated team, we've been researching the possibility to use `gl` on the UI thread and it seemed to be pretty complex to implement and we were not sure how big is the need for such functionality. I'd love to hear your use cases to better understand your needs.

I've completely abandoned any idea of using GL in React Native due to the above case. In general, it worked, but for lower-end devices it was dropping frames. At least, half a year ago it was like this.

Attaching my prototype code below, so you guys could hint me whether I missed certain optimizations:

`import React, { useCallback, useRef, useState } from 'react'
import { GLView, ExpoWebGLRenderingContext } from 'expo-gl'
import { Asset } from 'expo-asset'
import { Text, TouchableOpacity, View } from 'react-native'
import { styles } from './App.styles'

const vertShader = `
  precision highp float;
  uniform vec2 u_rotation;
  attribute vec2 a_position;
  varying vec2 uv;
  void main () {
  
    vec2 rotatedPosition = vec2(
      a_position.x * u_rotation.y + a_position.y * u_rotation.x,
      a_position.y * u_rotation.y - a_position.x * u_rotation.x
    );
    
    uv = a_position;
    gl_Position = vec4(rotatedPosition, 0, 1);
  }
`

const fragShader = `
  precision highp float;
  uniform sampler2D u_texture;
  varying vec2 uv;
  void main () {
    gl_FragColor = texture2D(u_texture, vec2(uv.y, uv.x));
  }
`

export default function HelloExpoGL() {

  const [animating, setAnimating] = useState(false)
  const contextRef = useRef<ExpoWebGLRenderingContext>()
  const textureRef = useRef<WebGLUniformLocation>()
  const rotationRef = useRef<WebGLUniformLocation>()

  const vertices = new Float32Array([
    0.0,  0.0,
    1.0,  0.0,
    0.0,  1.0,
    0.0,  1.0,
    1.0,  0.0,
    1.0,  1.0,
  ])

  const onTestContextCreate = useCallback(async (gl: ExpoWebGLRenderingContext) => {

    // This sets drawing buffer size to physical pixel size.
    // For example, our GL View size is 150x150 virtual pixels and PixelRatio.get() returns 3.
    // Then, gl.drawingBufferWidth and gl.drawingBufferHeight will equal 450 physical pixels.
    gl.viewport(0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight)

    const vert = gl.createShader(gl.VERTEX_SHADER) as WebGLShader
    gl.shaderSource(vert, vertShader)
    gl.compileShader(vert)

    const frag = gl.createShader(gl.FRAGMENT_SHADER) as WebGLShader
    gl.shaderSource(frag, fragShader)
    gl.compileShader(frag)

    const program = gl.createProgram() as WebGLProgram
    gl.attachShader(program, vert)
    gl.attachShader(program, frag)
    gl.linkProgram(program)
    gl.useProgram(program)

    const buffer = gl.createBuffer()
    gl.bindBuffer(gl.ARRAY_BUFFER, buffer)
    gl.bufferData(gl.ARRAY_BUFFER, vertices, gl.STATIC_DRAW)
    const positionAttrib = gl.getAttribLocation(program, 'a_position')
    gl.enableVertexAttribArray(positionAttrib)
    gl.vertexAttribPointer(positionAttrib, 2, gl.FLOAT, false, 0, 0)

    const asset = Asset.fromModule(require('../assets/coin.png'))
    await asset.downloadAsync()

    const texture = gl.createTexture()
    gl.activeTexture(gl.TEXTURE0)
    gl.bindTexture(gl.TEXTURE_2D, texture)
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
    // @ts-ignore
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, asset)

    const textureLocation = gl.getUniformLocation(program, 'u_texture')
    const rotationLocation = gl.getUniformLocation(program, 'u_rotation')

    gl.clearColor(0, 0, 0, 0)
    gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)

    gl.uniform1i(textureLocation, 0)
    gl.uniform2fv(rotationLocation, [Math.cos(0), Math.sin(0)]);

    gl.drawArrays(gl.TRIANGLES, 0, vertices.length / 2)
    gl.flush()
    gl.endFrameEXP()

    // Store context and uniforms
    contextRef.current = gl
    textureRef.current = textureLocation as WebGLUniformLocation
    rotationRef.current = rotationLocation as WebGLUniformLocation

  }, [])

  const frameTimer = useRef<number>(0)
  const frameValue = useRef<number>(0)
  const frameHandle = useRef<number | null>()
  const frameTicker = useCallback((time) => {
    if (contextRef.current) {
      const gl = contextRef.current as ExpoWebGLRenderingContext

      frameValue.current += Math.PI / 600 // 180 degrees in 10 seconds
      gl.clearColor(0, 0, 0, 0)
      gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT)
      gl.uniform2fv(rotationRef.current as WebGLUniformLocation, [Math.cos(frameValue.current), Math.sin(frameValue.current)]);
      gl.drawArrays(gl.TRIANGLES, 0, vertices.length / 2)
      gl.flush()
      gl.endFrameEXP()
      frameTimer.current = time
    }
    frameHandle.current = requestAnimationFrame(frameTicker)
  }, [])

  const handleToggleAnimation = useCallback(() => {
    setAnimating(!animating)
    if (!animating) {
      frameHandle.current = requestAnimationFrame(frameTicker)
    } else {
      cancelAnimationFrame(frameHandle.current as number)
      frameHandle.current = null
    }
  }, [animating])

  return (
    <View style={styles.Section}>
      <GLView style={styles.Surface} onContextCreate={onTestContextCreate} />
      <TouchableOpacity style={styles.Button} onPress={handleToggleAnimation}>
        <Text style={styles.ButtonText}>{animating ? 'Stop' : 'Animate'}</Text>
      </TouchableOpacity>
    </View>
  )
}`

**Comment by sergeymorkovkin** [comment]
> I feel like the use-case is removing the overhead of having the animation value go from UI thread to the JS thread to then to the GL thread.

Confirm, @wcandillon. Unfortunately, for reanimated 2 this is still a limitation.

**Comment by sergeymorkovkin** [comment]
> I think interactions based on react-native-gesture-handler would also be smoother, right?
Yes, if we manage to eliminate this roundtrip to JS thread.

**Comment by wkozyra95** [comment]
@sergeymorkovkin I've run your code on xiaomi 4x (snapdragon 435, android 7.1.2) and samsung galaxy s4 (Qualcomm Snapdragon 600, android 5.0.1)

- on both phones I'm getting steady 60 fps despite the fact that they have significantly worse cpu/gpu that Oppo A5 phone you mentioned
- `requestAnimationFrame` is limiting to 60 fps so I also wanted to test max fps and i got about 150-200 fps on both devices, to test that I replaced `requestAnimationFrame/cancelAnimationFrame` with `setTimeout(frameTicker, 0)`/`clearTimeout` and added 
`gl.flushEXP()` at the end of the frameticker

without use of `flushEXP()` and with `setTimeout` implementation I have seen some frame drops on "samsung galaxy s4", but it's actually good news because it means that bottleneck is not in js, aka js is pushing to much frames that native code is not able to handle. Without flushEXP I was getting 300 fps with dropped frames and with `flushEXP` it was around 200, but without any visible stutter/drops

Above example suggests that 
- bottleneck is not in js code and using worklets would not help and maybe even decrease performance, (at least in this example)
- i also don't think that expo-gl implementation is at fault, anything that we are doing there should be order of magnitude faster than js code, unless for some reason e.g. mutex is very inefficient on some specific devices

> It was just a basic animation (rotating rectangle) implemented with a vertex shader. Used requestAnimationFrame for updating uniform and re-rendering. That's all. I was comparing to PixiJS demo open in a browser on the same device - that looked perfect.

There might few reasons for that:
- `requestAnimationFrame` behaves differently in browser  and in react-native. e.g if react-native gives you constant 60 fps and browser lowers fps dynamically or just have lower base value then image on browser will appear smooth and on the phone it will drop frames
- we implement webgl in pure opengl es, browsers and webviews might use apis that are not available to us that improve performance

I can't state to much about performance when compared to webview/browser, but based on above example I don't think that expo-gl implementation is slower more than (5-10%) compared to native android opengl implementation, certainly it's not an order of magnitude difference.

**Comment by wkozyra95** [comment]
Worklet support for expo-gl will land in sdk44(now in beta),

docs: https://docs.expo.dev/versions/v44.0.0/sdk/gl-view/#integration-with-reanimated-worklets
example with worklets and gesture handler: https://github.com/expo/expo/blob/master/apps/native-component-list/src/screens/GL/GLReanimatedExample.tsx
