### ISSUE TITLE
SDK 40 experimentalLeanBuild app crashing

### ISSUE THREAD

**Issue by jurica-penjgusic** [expo/expo#11300]
Standalone app crashes when experimentalLeanBuild is set to true on android.
This bug also occured in SDK 39.

Is there any plans for fixing this?
SDK 38 didn't have problems with lean builds but it has problems with touchable opacity (laggy) on IOS , so we ended up with SDK 38 on android and SDK 39 on ios and it is night mare to maintain features and apps like that. 
Yeah, we can always eject but we don't prefer because you are doing such a great job and it would be awesome to fix this also 
🥇 

Bug: 
java.lang.NoClassDefFoundError: Failed resolution of Lexpo/modules/updates/db/DatabaseHolder at ...

**Comment by sjchmiela** [comment]
Most probably it's caused by `expoview` using a class that subclasses an `expo-updates` class (`DatabaseHolder`) and `expo-updates` not being added to the lean build. A proper solution would probably be to always force including `expo-updates` in lean builds, but a workaround would be to add `expo-updates` to your `package.json` and rebuild the app. Could you try that?

```sh
expo install expo-updates
```

**Comment by jurica-penjgusic** [comment]
Yes, it is working after expo updates installed!

Maybe this this solution can helped folks on forum thread:
https://forums.expo.io/t/after-updating-from-sdk-38-to-sdk-39-apk-crash/44546

Tnx 👍.
