### ISSUE TITLE
After Expo SDK 40 ugprade, app completely hangs when using certain icons

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#11311]
### Summary of Issue 

After upgrading to Expo SDK 40, my app would sometimes completely hang. I finally narrowed it down to `<Ionicons name="md-arrow-round-back" />` even though [`md-arrow-round-back` still seems to exist](https://icons.expo.fyi/Ionicons/md-arrow-round-back) (although a private browser window shows a question mark instead of the icon). Switching to [`md-arrow-back`](https://icons.expo.fyi/Ionicons/md-arrow-back) fixes the issue.

I thought it was useful to report this because it completely hung the app and was very difficult and time-consuming to narrow down. It would be nice if there was some timeout or other exception for a bad icon. By the way, is there some way to get a backtrace of the expo threads to see where it's stuck?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
$ expo diagnostics

  Expo CLI 4.0.13 environment info:
    System:
      OS: Linux 5.9 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.14.0 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 6.14.8 - /usr/bin/npm
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.0.tar.gz => 0.63.2 
    npmGlobalPackages:
      expo-cli: 3.27.4
    Expo Workflow: managed
```

### Reproducible Demo

```
import React from 'react';
import { Ionicons } from '@expo/vector-icons';

export default function App() {
  console.log("Loaded @ " + new Date());
  
  // Works:
  //return <Ionicons size={25} name="md-arrow-back" style={{ padding: 50 }} />;
  
  // Hangs:
  return <Ionicons size={25} name="md-arrow-round-back" style={{ padding: 50 }} />;
}
```
 
### Steps to Reproduce

1. Start the app

### Expected Behavior vs Actual Behavior

Expect no hang but actually it hangs

**Comment by brentvatne** [comment]
looked into this and it appears to be because proptypes validation is sending an absolutely massive error message when it fails. proptype validation is not needed these days, typescript is a better choice, so i went ahead and removed proptype validation in @expo/vector-icons@12.0.2. go ahead and install that to resolve this issue.

re: https://icons.expo.fyi/Ionicons/md-arrow-round-back issues:

-  this route just tries to use the given icon name with the given font family, eg: https://icons.expo.fyi/Ionicons/kevgrig. it doesn't validate it exists, but it probably should.
- the reason the icon works except in incognito is possibly due to service worker issues. try opening this up and clearing service worker. i don't think we can do anything about this except move to a different domain.

<img width="687" alt="Screen Shot 2020-12-10 at 1 15 13 PM" src="https://user-images.githubusercontent.com/90494/101830677-be558a00-3ae9-11eb-882a-fc56410daf0c.png">

**Comment by hardcodet** [comment]
>  even though md-arrow-round-back still seems to exist (https://icons.expo.fyi/Ionicons/md-arrow-round-back)

I ran into a similar issue with a material community icon that was removed. Expo icons still lists it, so the don't seem to be using the same version (yet), so it's better to check with the original collections.

**Comment by brentvatne** [comment]
@hardcodet - did you read my comment above? you should clear your service worker to fix it. we'll look into other solutions but a good way to tell if you have the latest version is to look at the version on the top left of the website:

![Screen Shot 2020-12-10 at 2 34 31 PM](https://user-images.githubusercontent.com/90494/101838049-d252b900-3af4-11eb-8775-f78292cf6fbd.png)

if it's older than that, follow the advice i gave above about clearing service worker

**Comment by brentvatne** [comment]
in chrome: press ⌘+shift+R or the equivalent on windows to force hard refresh of website to get the new version

**Comment by kevgrig** [comment]
Thanks! For reference, this fixed it:
```
yarn add @expo/vector-icons@12.0.2
```
