### ISSUE TITLE
Cannot read property 'getContactsAsync' of undefined, expo-contacts, ANDROID

### ISSUE THREAD

**Issue by esteban199** [expo/expo#11313]
On my expo ejected project, im trying to use expo-contacts with no success.

"react-native": "~0.61.5",
"expo": "~37.0.3",

i ran `expo install expo-contacts`

```
import * as Permissions from 'expo-permissions';
import * as Contacts from 'expo-contacts';

 getContact = async () => {
    try {
      let { status } = await Permissions.askAsync(Permissions.CONTACTS);
        if (status === 'granted') {
          const { data } = await Contacts.getContactsAsync({
            fields: [Contacts.Fields.Emails],
          });
          console.log("getContact / data: ", data);
  
          if (data.length > 0) {
            const contact = data[0];
            console.log("getContact / contact: ", contact);
          }
        }
    } catch(e){
      console.log("getContact / error: ", e)
    }
  }
```

![Screen Shot 2020-12-10 at 6 01 54 PM](https://user-images.githubusercontent.com/32593721/101835265-e5c04d00-3b11-11eb-8fa3-67152a9a7e5e.png)

**Comment by brentvatne** [comment]
it sounds like the native api isn't linked. rebuild the native project after you add expo-contacts, and on ios you ned to run `pod install`. if your issue persists, please post a https://stackoverflow.com/help/minimal-reproducible-example if you believe it is a bug in expo. otherwise, general usage questions belong on https://forums.expo.io/
