### ISSUE TITLE
Expo web ignores updates (requires cache clear manually)

### ISSUE THREAD

**Issue by actuallymentor** [expo/expo#11372]
## 🐛 Bug Report

**Note:** I realise this is close to a feature request, if there is nobody working on this I can draft a PR over the coming weeks. If it is already in a pipeline let me know.

### Summary of Issue 

`expo-updates` has no impact on `expo web`. Not only that, the web builds cache aggressively (usually good) but have no (documented) configurability.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo web.

### Reproducible Demo

Not snackable.
 
### Steps to Reproduce

1. Deploy web app
2. Make update
3. Open web app and see old code

### Expected Behavior vs Actual Behavior

- expected: app checks remote `js` code for changes
- actual: cache is not smart

**Comment by jonsamp** [comment]
@actuallymentor Thanks for your issue! I think there are two things here:

**Caching issue**
There is indeed a caching issue that is not configurable and that defaults to being quite aggressive. I've also run into this on a personal project. It would be great to make that configurable, or less aggressive. I am happy to take this on for you. If you're excited about making a contribution though, let me know!

**expo-updates on web**
I am currently working on expo-updates, and it's a no-op on web because we don't yet have a good "expected behavior" case. There are two times when we might want to pull JS code from expo servers for a website:

1. When the website loads, we want to check for the most up-to-date code. This should happen already, since websites get the most recent code from whichever server is serving their website (barring any caching). Currently Expo does not host websites, so if we delivered your main website JS, the user would have to make a call to your website, then the website would have to make another round-trip call to Expo's servers to get back the website's JS code. This is not optimal and will likely mean a slower website load. Another solution we could set up is to make it so `expo publish` builds your website, then deploys it to another hosting service like Vercel or Netlify. Then, when you published, you'd see your new update on all platforms.

2. If a user is already on your website, and you push an update, it would be nice to check if there's more current code available and allow the user to download the new code and reload the page. I can see how this would be helpful for sites that remain open for a longer period of time.

Was there a situation/case that you have in mind that you'd like us to support?

**Comment by actuallymentor** [comment]
> Caching issue

The easy fix would be to add a `app.js?v=timestamp` on build time of the `html` file. The unique query string triggers the browser to see it as a new resource without having to create a unique backend file. this approach still allows for caching for as long as the `html` is identical.

> When the website loads, we want to check for the most up-to-date code. This should happen already, since websites get the most recent code from whichever server is serving their website (barring any caching)

Emphasis on **barring any caching** which is a big reason now.

> I am currently working on expo-updates, and it's a no-op on web because we don't yet have a good "expected behavior" case.

Update awareness and cache flushing seem to me the most important. If `Updates.checkForUpdateAsync()` would call the js with a `?v=randomstringprobablyuuidv4` and check it against the current js it could at least give a `true/false`.

Something like `Updates.reloadAsync()` and `Updates.fetchUpdateAsync()` are actually pretty  web-compatible I would say?

> Was there a situation/case that you have in mind that you'd like us to support?

The `app.js?v=timestamp` seems like low-hanging fruit, I'm not sure if that works in `PWA`s though.

**Comment by apapsch** [comment]
>  this approach still allows for caching for as long as the html is identical.

Wouldn't this be a non-issue because expo creates all the files, including the html file?

For build reproducibility, would it be possible to hash the script file and use the hash as the cache busting key?

**Comment by actuallymentor** [comment]
> > this approach still allows for caching for as long as the html is identical.
> 
> Wouldn't this be a non-issue because expo creates all the files, including the html file?

I fail to see your point. The timestamp creates a different html hash. 

> For build reproducibility, would it be possible to hash the script file and use the hash as the cache busting key?

That is a very good idea instead of the timestamp.

**Comment by apapsch** [comment]
> I fail to see your point. The timestamp creates a different html hash.

That's right. I took your bit "as long as the html file is identical" as meaning there could be a situation where the script file changes but not the html file. In practice that would be rather unlikely, hence my remark. But we seem to be on the same track.

> Update awareness and cache flushing seem to me the most important. If Updates.checkForUpdateAsync() would call the js with a ?v=randomstringprobablyuuidv4 and check it against the current js it could at least give a true/false.

In recent times I've seen some web apps that show a notification "a new version is available. [reload now]". My thought was that's a very nice feature and having it in expo would certainly be great! How do plan to check against current js? A plain GET request may be prohibitive over slow or metered links, especially as you would have to do it periodically. You could instead do a HEAD request. Together with `If-Modified-Since` or `If-None-Match` you get a cheap 200 or 304 response code. The only problem is getting the value for the `If` headers: embedded timestamp would again betray build reproducibility and Etags are server-specific. A solution might be to store the timestamp in local storage, if available, and disable the fancy update mechanism otherwise, relying on a reload happening sometime anyway.

In any case, thanks for working on this! Looking forward to it.

**Comment by actuallymentor** [comment]
@jonsamp is our above discussion enough for you to go on?

@apapsch:

> How do plan to check against current js?

User defined. `Updates.fetchUpdateAsync( 'force' )` could do a full pull and compare the `sha`. `Updates.fetchUpdateAsync()` alone count do a more intelligent check like you suggest.

---

Overarching note: done is better than perfect. A basic `?hash=xx` in the build html would solve 90% of the pain.

**Comment by jonsamp** [comment]
Been awhile since I responding to this thread, so updating: we are currently working on a new service named EAS Update. Right now our focus is on native iOS and Android apps. Once we ship support for those platforms, our plan is to work on Expo web to make it work so that an update is universal. Eventually, we want a command like `expo publish` to update web/iOS/Android. --I think we're also going to work on Expo web more later this year/next year.

Also, we no longer include the service worker in builds made with `expo build:web`, which used to have a service worker with `workbox.strategies.networkFirst({ "cacheName":"offlineCache" ...`, which I believe was causing this caching issue. I would assume that users who never get the service worker would get updates when they re-visit the site. Do you find that to be the case?

**Comment by actuallymentor** [comment]
Caching is not just a service worker activity, browsers do it as well based on the headers. You currently serve `js` with `cache-control: max-age=3600` and an `etag`. This should fix most browser caching issues and only update when the `js` has updated.

That said I have **not** tested this, but I can do so later this week. Additionally, I would like to point out that this is still true:

> Overarching note: done is better than perfect. A basic ?hash=xx in the build html would solve 90% of the pain.

This would be frontend-only code that can be run on build, I usually do this in all my `webpack` setups anyway. I'm happy to PR for it.

**Comment by jonsamp** [comment]
Thanks for the clarification! I'm definitely happy to review a PR and to get it included.

**Comment by actuallymentor** [comment]
@jonsamp I probably have some time this week, could you point me to where expo handles it's `react-native-web` implementation?

**Comment by jonsamp** [comment]
Not sure if this is the right place, but this is where the webpack config defaults are: https://github.com/expo/expo-cli/tree/master/packages/webpack-config/web-default

**Comment by actuallymentor** [comment]
Looks like in [ExpoHtmlWebpackPlugin](https://github.com/expo/expo-cli/blob/master/packages/webpack-config/src/plugins/ExpoHtmlWebpackPlugin.ts) the script tag is made.

In this bit:

```js
attributes: {
	// @ts-ignore
	defer: this.options.scriptLoading !== 'blocking',
	type: 'application/expo+javascript',
	'data-platform': this.platform,
	src: scriptAsset,
}
```

The basic fix would be changing `src: scriptAsset` to ``src: `${ scriptAsset }?xxxxxxxxx` `` where `xxxxxxxxx` is either:

1. timestamp of build (simple as `?${ Date.now() }`
2. hash of the file (would require loading the file and running it through `sha256` or something)

Personally, I think that the first (date based) option is the easiest way to to this, and there shouldn't be any cases where a newly published build has no changes to it.

Would you agree? Then I'll create the PR.

**Comment by jonsamp** [comment]
I tried replicating this issue again after talking with @EvanBacon and I was not able to replicate this caching issue. Do you have a replication repo of this caching issue? I'm trying to understand what behavior we should change, but it's hard without being able to make it happen myself. 

Here's what I did:
- Ran `expo init`, loaded the website with `yarn web`, and then saw it running locally.
- I pushed the site to GitHub (https://github.com/jonsamp/test-expo-web-caching), then pointed Netlify at it, which then built the site with `expo build:web` and deployed it to https://tender-agnesi-61475a.netlify.app.
- Then I made a change to the website, and had netlify build/deploy again.
- When I refreshed the page, I see the new website changes. 

What did I miss here?

**Comment by actuallymentor** [comment]
> I tried replicating this issue again after talking with @EvanBacon and I was not able to replicate this caching issue. Do you have a replication repo of this caching issue?

I haven't seen it in a while, is there a chance the `etag` in the headers is a reasonably recent addition?

Additionally, I believe that the issue was present in the PWA setup, and the url hash would have solved that.

**Comment by diatche** [comment]
Hi, I've been following along and have been experiencing the issue as well.

What I see after updating is errors in the console saying that js chunks are missing. Could it be that there is only an issue when there are dynamic imports, which cause webpack to split the code into different scrips?

**Comment by diatche** [comment]
I inspected output from `createExpoWebpackConfigAsync` in my webpack.config.js and found a few things:

1. The web plugin hash is false.
2. The chunk filename does not have a hash.

These configurations are beyond my understanding, so I cannot comment much. Hope it helps someone else to find the root of the issue though.

```javascript
{
  "mode": "development",
  "entry": {
    "app": [
      "<root>/node_modules/react-dev-utils/webpackHotDevClient.js",
      "<root>/node_modules/resize-observer-polyfill/dist/ResizeObserver.global.js",
      "<root>/node_modules/expo/AppEntry.js"
    ]
  },
  "bail": false,
  "devtool": "cheap-module-source-map",
  "context": "<root>/node_modules/@expo/webpack-config/webpack",
  "output": {
    "publicPath": "/",
    "path": "<root>/web-build",
    "globalObject": "this",
    "pathinfo": true,
    "filename": "static/js/bundle.js",
    "chunkFilename": "static/js/[name].chunk.js"
  },
  "plugins": [
    {
      "options": {
        "template": "<root>/node_modules/@expo/webpack-config/web-default/index.html",
        "templateContent": false,
        "filename": "<root>/web-build/index.html",
        "hash": false,
        "inject": "body",
        "scriptLoading": "blocking",
        "compile": true,
        "favicon": false,
        "minify": false,
        "cache": true,
        "showErrors": true,
        "chunks": "all",
        "excludeChunks": [],
        "chunksSortMode": "auto",
        "meta": {},
        "base": false,
        "title": "Glucose Diary",
        "xhtml": false
      },
      "version": 4,
      "platform": "web"
    },
...
```

**Comment by actuallymentor** [comment]
> Hi, I've been following along and have been experiencing the issue as well.
> 
> What I see after updating is errors in the console saying that js chunks are missing. Could it be that there is only an issue when there are dynamic imports, which cause webpack to split the code into different scrips?

I believe this is a different issue?

**Comment by ricklove** [comment]
Just had this happen to us, we are using React lazy and some modules are trying to load old versions after an update to the web.
