### ISSUE TITLE
Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.

### ISSUE THREAD

**Issue by asgeo1** [expo/expo#1138]
I'm getting that message when trying to submit my Expo app (ejected, expokit 2.1.4)

The `AdSupport.framework` is present in the XCode project, but really shouldn't be included in Expo apps by default.

Like what you did with Stripe payments, anything advertising related needs to be optional, otherwise you get rejected if your app doesn't actually display ads.

Anyway, I tried deleting `AdSupport.framework` from the project and rebuild and submitted, and I still get the error.

It's hard to know what is referencing it - there are a *ton* of Pods included in a default project. Most of them I'm not even using... (i.e. all the facebook and google ones, they should be optional too)

Any ideas?

**Comment by asgeo1** [comment]
Hmm, after more googling I noticed this:  https://segment.com/docs/sources/mobile/ios/quickstart/#step-5-submitting-to-the-app-store

And it says to say "yes" the app uses the IDFA...   OK, no worries, I'll try that.

**Comment by terribleben** [comment]
Hey there - we also have a note about it in our [docs](https://docs.expo.io/versions/latest/guides/app-stores.html#apple-will-ask-you-whether-your-app-uses-the-idfa-because-expo-depends-on-segment-analytics-the-answer-is-yes-and-youll-need-to-check-a-couple-boxes-on-the-apple-submission-form-see-segments-guide-for-which-specific-boxes-to-fill-in). Hope that helps.

**Comment by peferb** [comment]
What do Expo use Segment for?

**Comment by timarney** [comment]
Can someone explain the note in the docs as to why?

 ```Apple will ask you whether your app uses the IDFA. Because Expo depends on Segment Analytics, the answer is yes```

More information is needed to provide to clients.

**Comment by terribleben** [comment]
Expo apps depend on Segment because the Expo SDK [contains Segment](https://docs.expo.io/versions/latest/sdk/segment.html). Expo (the company) doesn't use it for anything right now. It's just available for you to use.

@timarney: there's a link in the docs to Segment's guide for which boxes to check.

You may ask, "why does my app contain Expo's Segment API if I don't use that API?" All Expo apps (at time of writing) contain the whole Expo SDK, which is how we offer all of our APIs without requiring you to touch native code. It's on our roadmap to offer a more advanced option to customize the native libraries that ship with your app. At that point, it will be possible to, for example, omit Segment if you don't want it.

Hope this information is useful.

**Comment by timarney** [comment]
@terribleben thanks for the response + additional information.

I had some added confusion as the Segment website was down and still is (3 days later) https://segment.com so I didn't have any information on the topic.  

Found an archived link from expo chat here: https://web.archive.org/web/20170711101650/https://segment.com/docs/sources/mobile/ios/quickstart so I knew what boxes to check.

**Comment by squatto** [comment]
This is what is on that archive link:

---

>Step 5: Submitting to the App Store
>
>When you submit to the app store, be aware that Segment collects the IDFA for use in doing mobile install attribution with integrations like Mobile App Tracking. Even if you’re not currently doing mobile install attribution, if you get asked, “Does this app use the Advertising Identifier (IDFA)?” on this page, you’ll want to check the following three boxes:
>
>“Attribute this app installation to a previously served advertisement”
>“Attribute an action taken within this app to a previously served advertisement”
>“I, YOUR_NAME, confirm that this app, and any third party…”
>
>Note, you should not check the box labeled “Serve advertisements within the app” unless you are actually going to display ads.

**Comment by brentvatne** [comment]
we're working on it, for now the only way to opt-out of apis is to use expokit

**Comment by smadinen** [comment]
Hi @terribleben @brentvatne,

Does Segment uses IDFA for displaying Ads or for some other purpose?

If IDFA has been used for some other purpose (like tracking unique devices) with out displaying Ads, will Appstore approves such Apps?

**Comment by ajshukury** [comment]
I am curious to know what is being tracked or collected? Is segment or whoever collects analytics of an app without consent? What is being tracked/collected? Please make this transparent.
