### ISSUE TITLE
Inputting server IP manually

### ISSUE THREAD

**Issue by nukeop** [expo/expo#114]
I might be missing something but it seems that scanning a QR code is the only way to connect to a server.

How do I input an IP manually? I'm running Expo in an Android virtual machine and can't take pictures.

**Comment by terribleben** [comment]
Hi, if you're using XDE with an Android emulator, you can click the "Device" button and then "Open on Android" to open on your emulator. If you're using `exp` rather than XDE, `exp send --android` should work.

Lastly, you can type a URL manually in the Expo search bar, but you shouldn't need to given the above workflows.

**Comment by lucfranken** [comment]
@terribleben I have to type in the local network ip quite a lot of times when developing on a physical device (which is needed for certain native features). 

There is, as far as I understand, no QR code in XDE available. Only for snacks? Or is there a better way to do it?

**Comment by dikaiosune** [comment]
XDE will have QR code support soon.

**Comment by lucfranken** [comment]
Great!
