### ISSUE TITLE
White screen when manually reloading iOS apps

### ISSUE THREAD

**Issue by terribleben** [expo/expo#1140]
The issue can lead to a white screen when reloading (via devtools or `Util.reload()`)

Fix pending but not deployed yet.

**Comment by parachute-dev** [comment]
@terribleben Hi there, I'm getting this white screen of death but I'm not using the this function. 

We built the app ok around 20 days ago -it was ok - and then rebuilt 10 days ago and now we have this problem. Can you tell me if I'm going to run into this again? I thought perhaps it was due to an upgrade from Expo 21 to 24 - but not I'm thinking there is something wrong with the build tool??

This one is super urgent, if you could respond as soon as possible that would be appreciated.

**Comment by terribleben** [comment]
Hi, if you're not using `Util.reload()` or manually triggering a reload in some way, then your issue is probably not the bug which this issue is addressing.

- Have you tried testing your app locally with the `dev` flag turned off? (this is always a good idea before publishing, since your published JS bundle will also have `dev` off.)
- We've recently (December 27, 2017) seen a large number of people's apps get broken by a [bad uglify dependency](https://github.com/expo/expo/issues/1173) which would only show up in production JS bundles, so you might double check that thread to see if this issue is affecting you.

**Comment by parachute-dev** [comment]
@terribleben Thanks for the reply

I've downgraded to sdk 21

I'm now getting an error -  undefined is not an object (evaluating 'this._component.getScrollableNode ')

when the app opens.

it's working fine in the expo app on iOS and on an emulator.

**Comment by fourcolors** [comment]
I tested this without development mode on and it's still broken. I'm thinking perhaps react navigation is some how triggering Util.reload() ?

**Comment by sloppycoder** [comment]
just want to report I'm getting the same problem with SDK 24.0.0. In app.json I  set lloadJSInBackgroundExperimental to true, and I call Expo.Util.reload() when user press an "Update" button.

**Comment by terribleben** [comment]
Fix for this will be going out with SDK 25. Also renaming the issue to disambiguate from similar symptoms.

If you still see trouble, please open a new issue and we can go from there.
