### ISSUE TITLE
File uploading failed using FormData API Request on Expo ejected Project with Expo SDK 39 and React-Native Version 0.63.4

### ISSUE THREAD

**Issue by tee4tayyab** [expo/expo#11422]
### Description
I have ejected the expo-cli SDK 39 Project to React-Native-Cli project.
Everything is working except File uploading using FormData Api request with Axios/Fetch using Content-Type: "multipart/form-data". I have implemented all the available solutions but only FormData is not sent using network request.
I have tested the same code with many other projects having same or different versions of react native. and this code is working fine. but this issue is specific to this expo-ejected Project of React Native Cli.

"react": 16.13.1,
"react-native": 0.63.4,
"axios": "^0.20.0",
"expo": "~39.0.2",
"expo-image-picker": "^8.4.0",

### Environment - output 

Expo CLI 4.0.15 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.9 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 23, 27, 28, 29
        Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.2, 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~39.0.2 => 39.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.0.15
    Expo Workflow: bare

### Code Screenshot

<img width="581" alt="Screenshot 2020-12-21 at 12 33 38 PM" src="https://user-images.githubusercontent.com/29449625/102767250-12d9ee80-43a1-11eb-991b-1d1dd3ac3d7e.png">

### Expected Behavior vs Actual Behavior

Expected Behavior : It should send FormData and upload file to server.

Actual Behavior: The API is working correctly but no formdata or file is being received or uploaded at the server side.

**Comment by byCedric** [comment]
Hi @tee4tayyab, thanks for the issue response. I think you are running into https://github.com/expo/expo/issues/11214. The file URIs from `ImagePicker` isn't always returning a file URI with `file:///data...` prefixed, instead it's just `file:/data...` which is incorrect. Because of that, the file can't be loaded by `FormData` and it thinks you are sending plain text.

I created an example using httpbin.org, that works on Android, iOS and web. You [can check that out here](https://snack.expo.io/@bycedric/expo-issue-11422), take a look at line 36. That contains the workaround that you can use for now. For now, I'll close this issue, let's continue tracking this issue in #11214.

Hope this helps!
