### ISSUE TITLE
[docs] Expo 40 requires manual "ACCESS_BACKGROUND_LOCATION"...but what are the defaults?

### ISSUE THREAD

**Issue by Aryk** [expo/expo#11467]
It says that "ACCESS_BACKGROUND_LOCATION" is not included by default: https://blog.expo.io/expo-sdk-40-is-now-available-d4d73e67da33. To get back to parity with Expo 39, do we need to list all these explicitly now in app.json?

```
ACCESS_COARSE_LOCATION
ACCESS_FINE_LOCATION
ACCESS_BACKGROUND_LOCATION
CAMERA
RECORD_AUDIO
READ_CONTACTS
WRITE_CONTACTS
READ_CALENDAR
WRITE_CALENDAR
READ_EXTERNAL_STORAGE
WRITE_EXTERNAL_STORAGE
USE_FINGERPRINT
USE_BIOMETRIC
WRITE_SETTINGS
VIBRATE
READ_PHONE_STATE
com.anddoes.launcher.permission.UPDATE_COUNT
com.android.launcher.permission.INSTALL_SHORTCUT
com.google.android.c2dm.permission.RECEIVE
com.google.android.gms.permission.ACTIVITY_RECOGNITION
com.google.android.providers.gsf.permission.READ_GSERVICES
com.htc.launcher.permission.READ_SETTINGS
com.htc.launcher.permission.UPDATE_SHORTCUT
com.majeur.launcher.permission.UPDATE_BADGE
com.sec.android.provider.badge.permission.READ
com.sec.android.provider.badge.permission.WRITE
com.sonyericsson.home.permission.BROADCAST_BADGE
```

**Comment by byCedric** [comment]
Hi @Aryk, to "get back to parity with SDK 39", simply append `ACCESS_BACKGROUND_LOCATION` to your existing `android.permissions` list. That will opt-in to this permission again.

It's _not_ recommended to include all permissions, instead add only the ones you use. It will avoid possible store rejections because you include too many permissions. These are documented in the `readme`'s, e.g. [Haptics](https://github.com/expo/expo/tree/master/packages/expo-haptics#configure-for-android) or [Camera](https://github.com/expo/expo/tree/master/packages/expo-camera#configure-for-android). To see a quick overview of these permission, [check out this code](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidShellApp.js#L921-L957).

Hope this helps

**Comment by Aryk** [comment]
> Hi @Aryk, to "get back to parity with SDK 39", simply append `ACCESS_BACKGROUND_LOCATION` to your existing `android.permissions` list. That will opt-in to this permission again.
> 
> It's _not_ recommended to include all permissions, instead add only the ones you use. It will avoid possible store rejections because you include too many permissions. These are documented in the `readme`'s, e.g. [Haptics](https://github.com/expo/expo/tree/master/packages/expo-haptics#configure-for-android) or [Camera](https://github.com/expo/expo/tree/master/packages/expo-camera#configure-for-android). To see a quick overview of these permission, [check out this code](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidShellApp.js#L921-L957).
> 
> Hope this helps

Right...but FWIU, if you didn't have a android.permissions list, then what exactly should be in that list now? Everything right?
