### ISSUE TITLE
LocalAuthentication.hasHardwareAsync() is returning false in simulator

### ISSUE THREAD

**Issue by RichMatthews** [expo/expo#11500]
LocalAuthentication.hasHardwareAsync() is returning `false` in iOS simulator even though I have Features > FACE ID > enrolled checked. and it is returning `true` when I uncheck this. why would this happen?

**Comment by brentvatne** [comment]
as far as i know we use the appropriate underlying apis for this: https://github.com/expo/expo/blob/c8501408a105c2feb23320fdb81310e2d77767a2/packages/expo-local-authentication/ios/EXLocalAuthentication/EXLocalAuthentication.m#L32-L49

please correct me if i am mistaken. it's quite possible that this is a quirk with simulator on the ios side

**Comment by RichMatthews** [comment]
it seemed to fix it when I erased all content. I am now running on a real device do you know why it's asking me "Do you want to allow "MyAPP" to use FaceID? I have included the relevant string in the info.plist like so

```
  <key>NSFaceIDUsageDescription</key>
  <string>$(PRODUCT_NAME) Authentication with TouchId or FaceID</string>
```

**Comment by cruzach** [comment]
Closing this since the original issue was resolved by clearing simulator content and settings. 

As for your subsequent question, I believe the custom `NSFaceIDUsageDescription` string should show _below_ the `Do you want to allow "MyAPP" to use FaceID` text (like a subtitle). Let me know if that's not the case
