### ISSUE TITLE
expo-av requires microphone permission even when not using microphone

### ISSUE THREAD

**Issue by rmccue** [expo/expo#11532]
### Summary of Issue 

expo-av provides both audio/video playback and audio recording functionality, requiring `NSMicrophoneUsageDescription` even when only used for playback.

To protect user privacy and reduce unnecessary access to protected APIs, expo-av should not require microphone usage when only used for playback. (I suspect this would require splitting microphone access into a new module.)

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Targeting iOS using the bare workflow after ejecting.

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.4.0/bin/yarn
      npm: 6.14.7 - ~/.nvm/versions/node/v14.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.3/12C33 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare
```

### Steps to Reproduce

1. Create an expo project
2. Add expo-av as a dependency
3. Eject
4. Build and submit to the App Store for approval.

### Expected Behavior vs Actual Behavior

Note rejection: "Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSMicrophoneUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data."

I don't need or want access to the user's microphone, so I would expect to not need to justify the app's usage of it.

**Comment by Crizzooo** [comment]
Whats current work around?

Do I seriously have to add this to my Info.plist and pretend Im actually using this permission in my app?

**Comment by felipefa** [comment]
I'm facing the same problem and I don't use the microphone in my app. Any work around?

**Comment by mifi** [comment]
I'm going to try to add:
```
<key>NSMicrophoneUsageDescription</key>
<string>This app does not require access to the microphone.</string>
```
and see how it goes 🤞 See https://stackoverflow.com/a/39519960/6519037

**Comment by kaushik-prasanna** [comment]
Facing the same issue, with Apple rejecting the binary.

Please check. Hoping this gets more notice : @AdamJNavarro , @brentvatne , @esamelson , @EvanBacon

**Comment by mifi** [comment]
FWIW my app was approved by using the string in my comment above.

**Comment by cruzach** [comment]
Has anyone tried responding to Apple and explaining that although the code for audio recording is _present_ in one of your dependencies, it’s never used precisely because you **don’t** include that usage description in your info.plist? `expo-av` first checks for the presence of `NSMicrophoneUsageDescription`, and if it's not included, all audio recording will fail anyways, so it's impossible for an app without that key to record audio

**Comment by brentvatne** [comment]
expo-av includes audio and video capabilities, and part of the audio api is audio recording. this was very practical from the point of view of writing the module and re-using the same code, but ultimately it led to this situation where microphone permissions are required here. it's not ideal, but using the solution mentioned by @mifi above should work fine for now. add this to your Info.plist:

```
<key>NSMicrophoneUsageDescription</key>
<string>This app does not require access to the microphone.</string>
```

in the future we will want to split out audio recording capabilities from expo-av in order to remove this requirement. sorry for the hassle.

**Comment by brentvatne** [comment]
adding to the above comment - you can use the expo-av config plugin to disable this: https://github.com/expo/expo/pull/17168#issuecomment-1931024586
