### ISSUE TITLE
WRITE_EXTERNAL_STORAGE Permission

### ISSUE THREAD

**Issue by ardyfeb** [expo/expo#11549]
How to ask permission `WRITE_EXTERNAL_STORAGE` permission with `expo-permission` ? on `Permission.ts` only have limited permission that we can ask. So how to ask permission that not listed in ?

```ts
export const CAMERA_ROLL = MEDIA_LIBRARY;
export const AUDIO_RECORDING = 'audioRecording';
export const LOCATION = 'location';
export const USER_FACING_NOTIFICATIONS = 'userFacingNotifications';
export const NOTIFICATIONS = 'notifications';
export const CONTACTS = 'contacts';
export const CALENDAR = 'calendar';
export const REMINDERS = 'reminders';
export const SYSTEM_BRIGHTNESS = 'systemBrightness';
export const MOTION = 'motion';
```

Edit: i use `expo-permission` on bare project

**Comment by AdamJNavarro** [comment]
Hey @ardyfeb, we do our best to reserve Github issues for reproducible and actionable bug reports. For questions such as this one, please feel welcome to post on our [Forums](forums.expo.io) and we'll get you an answer as quickly as we can.

Cheers,
Adam

**Comment by yaroslavnikiforov** [comment]
I asked this question on the expo forum in April and have no answer.
[https://forums.expo.dev/t/media-library-write-only-permission-with-expo-media-library/51486](https://forums.expo.dev/t/media-library-write-only-permission-with-expo-media-library/51486)

**Comment by JohnyClash** [comment]
This is a necessary thread, there is no documentation on this topic. Since permissions was deprecated for Module Specific permission methods there is no clear documentation on what permissions each module requests or gives. 

For instance the MediaLibrary needs the permission for WRITE_EXTERNAL_STORAGE to execute its MediaLibrary.addAssetsToAlbumAsync() however it seems on my Android device that the app has neither been given this permission nor requested it. Running MediaLibrary.addAssetsToAlbumAsync() throws an error telling me I need the WRITE_EXTERNAL_STORAGE permission. This is after I have confirmed that MediaLibrary.requestPermissionAsync() has run successfully and has been granted the permissions it requested.

**Comment by metkm** [comment]
@AdamJNavarro As @JohnyClash says. I have the same exact issue as them.
```
const downloadResumable = createDownloadResumable(
    `http://${process.env.API_DOMAIN}/videos/${videoId}`,
    `${documentDirectory}/${videoId}`,
    {},
    callback
  );

  const result = await downloadResumable.downloadAsync();
  if (!result) return;

  const { granted } = await MediaLibrary.requestPermissionsAsync(true);
  if (!granted) return;
  
  const asset = await MediaLibrary.createAssetAsync(result.uri);
  await MediaLibrary.createAlbumAsync("Download", asset, false);
```

This basic code can't the album because of WRITE_EXTERNAL_STORAGE permission.

**Comment by funkenpedro** [comment]
I was having this issue also in an app where I was trying to use {StorageFramwork} as well as MediaLibrary to access shared folders/albums. Oddly there was this behaviour in that app where after I removed StorageFramework from it, the app behaved as though it still needed permissions for it, when I started it asked me for permissions to the folder that I was formerly trying to use with storage framework and when I tried to use MediaLibrary it reported the WRITE_EXTERNAL_STORAGE problem. 

After I created a new app using only MediaLibrary, the WRITE_EXTERNAL_STORAGE issue disappeared

**Comment by JohnyClash** [comment]
> I was having this issue also, it seems to work and not ask for permissions if you change the move/copy flag to true. So the file or asset won't be moved it will be copied.

This does in fact work as a work around for my issue. However, this seems to be a problem within the Expo community. The original question is an easily validated flaw. As I said in my original post 

> This is a necessary thread, there is no documentation on this topic. Since permissions was deprecated for Module Specific permission methods there is no clear documentation on what permissions each module requests or gives.
> 
> For instance the MediaLibrary needs the permission for WRITE_EXTERNAL_STORAGE to execute its MediaLibrary.addAssetsToAlbumAsync() however it seems on my Android device that the app has neither been given this permission nor requested it. Running MediaLibrary.addAssetsToAlbumAsync() throws an error telling me I need the WRITE_EXTERNAL_STORAGE permission. This is after I have confirmed that MediaLibrary.requestPermissionAsync() has run successfully and has been granted the permissions it requested.

Mainly they deprecated permissions and then poorly communicate in Docs which permissions are implicitly granted for each module. And in this example Media Library fails to implicitly  grant the proper permissions for all of its methods. Expo admins close the topic it. I have been in several threads like these since working with expo in which problems are swept under the rug by controlling dialogue.  Is this an inherent problem with expo? Do they close valid threads simply to make it look like they take care of issues or are their other explanations? Simply stating the format of his post is incorrect is a cop out in my opinion. He clearly communicates a problem and other people in thread validate it.

**Comment by arnnis** [comment]
This issue is still present on Expo 52. setting move/copy flag to false fixes the WRITE_STORAGE permisison error but we have duplicates assets @brentvatne

**Comment by brentvatne** [comment]
what is the issue exactly @arnnis? can you create a new issue with a minimal reproducible example please?
