### ISSUE TITLE
Push notification icon is a gray square

### ISSUE THREAD

**Issue by komelabbbas** [expo/expo#11579]
### Summary of Issue 
Push notification icon is a gray square

### Environment
OS: macOS 11.1
expo: 40.0.0
expo-notifications: ~0.8.2
Platform: android

`"notification":` {
            "icon": `"./assets/notification.png"`
        `},`

### Issue
![notification_icon](https://user-images.githubusercontent.com/51354419/104090440-d2350d00-529c-11eb-8cef-69e8df411f8b.png)
![push notification](https://user-images.githubusercontent.com/51354419/104090445-deb96580-529c-11eb-8edc-4f8f140c7aa1.jpg)

I have tried different 96*96 icons but not working.
also, I have uploaded to the play store internal tester but still the same issue.

This is happening to all my projects upgraded to SDK 40.
Sorry to open an issue about this, I hope this is not something I'm doing wrong. Just to be clear, expo is amazing!!
Any solution please help...

**Comment by cruzach** [comment]
your push notification icon should _only_ include white. Otherwise, Google will force it to be a grey square/circle. Basically, to get the icon you're looking for, you should make all of the dark-grey section of your image transparent. 

Read [this stack overflow post for more info](https://stackoverflow.com/questions/45318614/why-is-my-smallicon-for-notifications-always-greyed-out)

**Comment by cruzach** [comment]
fixed in https://github.com/expo/expo/commit/b655ff28d924e2274c627294778a02dbec1268db

**Comment by komelabbbas** [comment]
Thanks okay I will check it again and fix the icon.

**Comment by komelabbbas** [comment]
Thanks, now it working fine after using a different icon

**Comment by kevgrig** [comment]
Hi, I just hit this issue and I'm a bit confused because the [app.json documentation](https://docs.expo.io/versions/latest/config/app/#icon-1) writes that the icon should be grayscale but the comment above, FAQ update in b655ff2 and SO post write that it should be white-only. I just created an image asset in Android Studio from a PNG and it converted it to white, so it seems the latter is correct. So should the [expo docs](https://docs.expo.io/versions/latest/config/app/#icon-1) be updated to say something like "96x96 png white-only with transparency"?

**Comment by cruzach** [comment]
you're right @kevgrig , I'll update those docs

**Comment by NathanC** [comment]
@cruzach just fyi, the documentation hasn't been updated: https://docs.expo.dev/versions/latest/config/app/#notification
