### ISSUE TITLE
not being able to load app for first time without internet and downloading data

### ISSUE THREAD

**Issue by idehweb** [expo/expo#1164]
Hi guys,
I made an app with `create-react-native-app`, I build it with `exp build:android`
after generating apk , I install it on my android phone, I don't want it download data from internet, and my app is offline, but it is going to download data from expo server, and it shows blue page and an error in it with home and retry icon.
![2017-12-26 15 09 23](https://user-images.githubusercontent.com/34858656/34355958-c75eb05c-ea4e-11e7-864b-514ca8a95695.jpg)
![2017-12-26 15 09 38](https://user-images.githubusercontent.com/34858656/34355962-cea04a2e-ea4e-11e7-9e49-dfe6ae334473.jpg)

I don't want user see this blue page if there is problem in it! How can I get rid of it,and make a fresh build from expo.
there was many issues about this but I didn't understand how to make it work offline!

**Comment by jesseruder** [comment]
Hello! Can you post your app.json and package.json? From the error message, it looks like you might have a mismatch between the version of react-native in your node_modules and the version you're telling Expo to load.

**Comment by idehweb** [comment]
@jesseruder tnx for your response
this is package.json:
`{
  "name": "AwesomeProject7",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.8.1",
    "jest-expo": "23.0.0",
    "react-test-renderer": "16.0.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^23.0.6",
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-simple-radio-button": "^2.7.1",
    "react-navigation": "^1.0.0-beta.21"
  }
}
`

And this is app.json:

`{
  "expo": {
    "name": "AwesomeProject7",
    "icon": "app-icon.png",
    "version": "1.0.0",
    "slug": "kcut-ir",
    "sdkVersion": "24.0.0",
    "orientation":"portrait",
    "ios": {
      "bundleIdentifier": "com.idehweb.kcut"
    },
    "android": {
      "package": "com.idehweb.kcut"
    }
  }
}
`

but after handling the errors, again my question is that how to disappear the blue page:'something went wrong'. and make the app not showing it again.for any reason.
tnx

**Comment by terribleben** [comment]
Hi, it looks like you have a version mismatch. Your `sdkVersion` indicates `24.0.0` but your `package.json` contains the dependencies for Expo SDK 23. Can you make sure you follow all of the upgrade instructions at the [bottom of this blog post](https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51)?

Let me know if you're still having an issue after that. Hope that helps.

**Comment by idehweb** [comment]
:| MR  @terribleben  I just want to know how to do something to not see the blue page anymore! 
for example when I install app on my android phone (after I built it with `expo build:android`), first of all: it should be connected to network to download what I have no idea about, second:it's size is not normal, 28 megabyte for just 5 inputs???? and ofCourse after connecting to internet it will download 25 megabyte data too!!!!!!!! what a mess! there is no documentation for these! I have searched just for a week! but nothing at all!   just let me know what to do so not seeing this page any more when I am not connected to the network!
![34355958-c75eb05c-ea4e-11e7-864b-514ca8a95695](https://user-images.githubusercontent.com/34858656/34419969-0e8de38e-ec1c-11e7-842f-affd102179fa.jpg)

**Comment by terribleben** [comment]
Hey there, sorry you sound pretty frustrated. If you follow the instructions in my previous post, it's likely to fix the blue screen issue you're seeing.

By default, Expo apps use an internet connection to update themselves. There is documentation about this [here](https://docs.expo.io/versions/latest/guides/how-expo-works.html), [here](https://docs.expo.io/versions/latest/introduction/project-lifecycle.html) and [here](https://docs.expo.io/versions/latest/guides/publishing.html). There is also documentation about making them work offline [here](https://docs.expo.io/versions/latest/guides/offline-support.html) if that's important to you.

There is more information about the size of Expo apps [here](https://docs.expo.io/versions/latest/introduction/why-not-expo.html#if-you-need-to-keep-your-app-size-extremely-lean-expo-may-not-be-the-best-choice-the-size-for-an-expo-app-on-ios-is-approximately-25mb-and-android-is-about-20mb-this-is-because-expo-includes-a-bunch-of-apis-regardless-of-whether-or-not-you-are-using-them--this-lets-you-push-over-the-air-updates-to-use-new-apis-but-comes-at-the-cost-of-binary-size-we-will-make-this-customizable-in-the-future-so-you-can-trim-down-the-size-of-your-binaries). If you need your app to be below ~25 megabytes then you might want to try another service for now.

**Comment by idehweb** [comment]
I did what it was said in documentation, I am using `assetBundlePatterns` and `ios.loadJSInBackgroundExperimental` in app.json.but as it is in picture, it is error!
<img width="760" alt="screen shot 2017-12-29 at 12 46 51" src="https://user-images.githubusercontent.com/34858656/34433730-723b9ea6-ec96-11e7-9169-87eedb511ec7.png">

**Comment by ide** [comment]
@idehweb The documentation that @terribleben linked is for SDK 24 (the currently latest version of the Expo SDK). Your app.json still specifies sdkVersion 23.0.0. Please read through https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51 and then follow the upgrade instructions at the end to upgrade to SDK 24 first.

**Comment by Bharat23** [comment]
@idehweb ios.loadJSInBackgroundExperimental means you have to insert inside the ios key
 `
ios: {
...
loadJSInBackgroundExperimental: true
}
`

this is a basic JSON object structuring.
