### ISSUE TITLE
Old version of react-navigation library warning on SDK40

### ISSUE THREAD

**Issue by butri71** [expo/expo#11675]
Hi Team,

I’ve recently moved to SDK40 on a managed App and start receiving warnings about my react-navigation libraries being old.

The message is prompting me to update to a version which **I already have**.
This warnings are annoying and appearing continuously on any action.

Message:

_It appears that you are using old version of react-navigation library. Please update @react-navigation/bottom-tabs, @react-navigation/stack and @react-navigation/drawer to version 5.10.0 or above to take full advantage of new functionality added to react-native-screens_

My packages:

@react-navigation/stack": “^5.12.8,
@react-navigation/bottom-tabs”: “^5.11.2,
@react-navigation/drawer”: "^5.11.4,

I'm using SDK40
My CLI is up-to-date
RN 0.62

I've already opened a ticket on Stackoverflow here https://forums.expo.io/t/old-react-navigation-library-warning-on-sdk40/47598 4 days ago but no one has replied yet

Thanks

**Comment by byCedric** [comment]
Hi @butri71! Thanks for writing in, but unfortunately I don't think we can do a lot about it. You could try doing the basic troubleshooting steps, e.g.
- Remove your `node_modules` and lockfile, reinstall everything
- Remove `.expo` and start again
- Clear cache with `expo start --clear`

If these steps aren't helping, I would suggest opening an issue on the [React Navigation repository](https://github.com/react-navigation/react-navigation). Because this is a 3rd party library, there is nothing we can do from here. And because this library is (mostly) JS, it's not pinned to specific versions in the managed workflow.

Hope this helps!
