### ISSUE TITLE
last version of expo-notifications 0.9.0 doesn't work expo SDK 40

### ISSUE THREAD

**Issue by webuijorgeGL** [expo/expo#11697]
### Summary of Issue 

Some of your project's dependencies are not compatible with currently installed expo package version:
 - expo-notifications - expected version range: ~0.8.2 - actual version installed: 0.9.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]

**Comment by AdamJNavarro** [comment]
Hey @webuijorgeGL, this is the expected behavior. As the cli states in the message you pasted, you are targeting an incompatible version. This is why when you are using the managed workflow that you use expo install to ensure your module versions will work with the bundled native versions.

Cheers,
Adam

**Comment by rfink** [comment]
> Hey @webuijorgeGL, this is the expected behavior. As the cli states in the message you pasted, you are targeting an incompatible version. This is why when you are using the managed workflow that you use expo install to ensure your module versions will work with the bundled native versions.
> 
> Cheers,
> Adam

So, which version of expo sdk is it compatible with?
