### ISSUE TITLE
Push Notification Restarts App on Android using SDK40

### ISSUE THREAD

**Issue by vrinch** [expo/expo#11704]
Push notifications restarts the built apps on android. I dint notice this on previous SDKs, so I suppose it’s an issue with SDK40.
I have tried this on three different android devices.
It works as it should on iOS

**Comment by byCedric** [comment]
Hi @vrinch, there are a lot of reasons why apps restart. It could be a fatal crash or an update issue for example. But, because you provided limited context I don't think we can help you in the right direction.

If you think this is an issue with Expo (SDK 40), please open a bug report with all the information we ask. With that, we might be able to reproduce the issue and solve it.

Hope this helps!
