### ISSUE TITLE
Expo camera not scanning QR code when `barCodeScannerSettings` is set on iOS

### ISSUE THREAD

**Issue by shahidcodes** [expo/expo#11726]
### Summary of Issue 
Expo camera not scanning QR code when `barCodeScannerSettings` is set on iOS but on Android, it works fine.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 12.20.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD  
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```
### Reproducible Demo
[Snack](https://snack.expo.io/@shahidcodes/crabby-french-fries)

 
### Steps to Reproduce
- Create new expo project
- Import `expo-camera` and render it
- set/unset  `barCodeScannerSettings` props on iOS device like below
```   
barCodeScannerSettings={{
          barCodeTypes: ['qr'],
        }}
```
- Scan QR  code and see

**Comment by jarvisluong** [comment]
I did a quick debugging session and the reason is that on iOS implementation, the string "qr" wasn't converted into the actual enum value of the QR code type that comes from `AVMetadataObjectType`. One workaround you can do for now is to use `BarCodeScanner.Constants.BarCodeType.qr` instead of `qr` string. Will submit a PR :)
