### ISSUE TITLE
Members with 'Viewer' role are unable to launch iOS simulator

### ISSUE THREAD

**Issue by ijmad** [expo/expo#11740]
Steps to reproduce:

1. Set up an Account
2. Go to Members
3. Invite someone and grant them 'Viewer' access
4. Have that person clone the source code repository (note that app.json contains an 'owner' field that matches the account name)
5. npm install
6. expo login
5. expo start
6. Navigate to http://localhost:19002/
7. Click 'Run on iOS Simulator'

Expected behaviour:

The team member, as a 'Viewer' should be able to run the app locally in a simulator.
I only wish to have a few 'privileged' developers able to do a full build for OTA update.

Actual behaviour:

The following error is displayed:

`ApiV2Error: Cannot sign manifest under that username.
    at ApiV2Client._requestAsync (/@expo/xdl@58.0.13/src/ApiV2.ts:245:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

This doesn't seem to affect Admin users. Additionally, if we remove the 'owner' field from app.json so expo is building using the developer's account instead of the main account for the company's app, this works too.

**Comment by byCedric** [comment]
Hi @ijmad! As you mentioned, this is a known issue related to the `expo.owner` property. Because [`viewer` is only allowed to](https://docs.expo.io/accounts/working-together/#managing-access) "Can only view your projects through the Expo client, but can't modify your projects in any way.", they can't start up a local development version.

I think we are working on something more permissive (locally) that would allow this usecase. (cc @brentvatne) But we don't have a clear timeline when that would be available.

**Comment by ijmad** [comment]
Thanks for the explanation. I am surprised that starting a local development version counts as a 'modify' operation, this seems counter-intuitive, as the code is not being changed. We will have to consider how to manage our workflow because we use pull requests and code review, we don't want all developers able to mistakenly send a release from their local development machine to the production channel.

We'll have to jerry rig something until the  enhancement becomes available I suppose, thanks for the explanation.

**Comment by byCedric** [comment]
It wasn't intended behavior, that's why we are working on a fix. If you can add the `owner` field from CI or from the user it's publishing, that works for now. But that would still allow your developers to publish their own version of the app, just not modify the "main" app.

**Comment by danrivett** [comment]
Any update on this?

We recently updated our developer's permisions to `viewer` since developers can publish to any release channel including Prod which is not restrictive enough as could be done accidentally and we want to have proper guard-rails when publishing to Prod.

However after changing to `viewer` the developers can't even do local builds in the simulator as discussed here, so we had to revert the permissions change but now open ourselves up to allowing Prod to be updated by anyone.

**Comment by ijmad** [comment]
@danrivett we came up with a workaround that works fairly well, if you use an app.config.js for expo, you can programmatically decide whether to set owner or not, i.e.:

```
const IS_LOCAL = process.env.IS_LOCAL == "1";

export default {
  expo: {
    owner: IS_LOCAL ? undefined : "our_app_account",
    ...
  }
}
```

We then set `IS_LOCAL=1 ` on our npm run start command for running the simulator for local dev.

**Comment by danrivett** [comment]
Thanks @ijmad that's a great suggestion, I will definitely give that a go as better than our current situation. Thank you!

For the benefit of any Expo readers, I would still love to see more granular publishing permissions in general though - for example being able to authorize publishing to some release channels but not others as it would make sense to allow some developers to publish to non-prod release channels, but not to the prod release channel.

**Comment by brentvatne** [comment]
thanks @danrivett for the feedback and @ijmad for sharing your workaround!

we plan to add more granular permissions but we prioritized it yet. the ability to have someone work on your app without giving them access to publish and build is important, and it's an omission that we should certainly resolve sooner than later. we'll follow up in this thread when we have updates.

**Comment by danrivett** [comment]
We would still love to have granular permissions to allow our devs to publish to non-prod release channels we have, whilst preventing them from publishing to Prod and affecting our customers.

Not sure this ticket is the right thing to keep open for that, or if I should create a new issue?

Either way, not sure if the original issue here is fixed, so probably should stay open?
