### ISSUE TITLE
Linking requires a build-time setting `scheme` in the project's Expo config

### ISSUE THREAD

**Issue by churichard** [expo/expo#11754]
### Summary of Issue 

I'm using expo-linking v2.1.1 and trying to call `createURL`. However, I'm getting the following error when I try to run a simple test that just renders the app (code is in the Steps to Reproduce):

`Linking requires a build-time setting 'scheme' in the project's Expo config (app.config.js or app.json) for bare or production apps.`

My scheme is already defined in `app.json`.

The only way I can suppress this error is by passing my scheme again when I call `createURL`. When I do this and I eject, though, I get another error:

`The provided linking scheme does not appear in the list of possible uri schemes in your expo config`

Even though the scheme that it prints out is encapsulated within the list of schemes it says it should match.

So I think for some reason it's just not recognizing the scheme that's defined in the `app.json`.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 4.1.0 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
      Yarn: 1.22.5 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.0/bin/npm
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: ^17.0.1 => 17.0.1
      react-dom: ^17.0.1 => 17.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ^0.14.8 => 0.14.10
    npmGlobalPackages:
      expo-cli: 4.1.0
    Expo Workflow: managed
```

### Reproducible example

https://github.com/churichard/expo-linking-bug

### Steps to Reproduce

Clone the repo, run `yarn install`, then run `yarn test`. The warning should show up when the `App.test.tsx` test is run.

### Expected Behavior vs Actual Behavior

This warning should not appear if `scheme` is already defined in app.json.

**Comment by brentvatne** [comment]
can you share the contents of the `App` file that you are importing please? the code that you provided is not runnable

**Comment by churichard** [comment]
I just created a very simple app that should demonstrate the issue: https://github.com/churichard/expo-linking-bug

Clone it and run `yarn test`. You should see the warning.

**Comment by byCedric** [comment]
Hi @churichard, thanks for writing in and providing the repository! I think we can split this issue up into two separate issues, based on your example repo.

1. `expo-linking` is installed twice, which isn't necessarily a problem but may cause unintended side effects.
This is related to the project using `expo-linking@2.1.1`, while we include `expo-linking@~2.0.1`. That being said, this is something not related to this error and it's something we have to fix internally.

2. `jest-expo` is mocking `expo-constants`'s manifest, _without the `scheme`_.
I'm fairly sure this is the issue you are experiencing. What happens here is [that `expo-linking` is requesting the manifest through `expo-constants`](https://github.com/expo/expo/blob/master/packages/expo-linking/src/Schemes.ts#L54-L77). But, because it's running in a Jest environment, [this module is mocked](https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/setup.js#L107-L114). 

Generally speaking, mocking these libraries is a good thing (and often a necessity) to make it runnable in a node environment. But, because the [mocked manifest isn't adding the `scheme` from the original manifest](https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/createMockConstants.js#L23-L35), there is no way for `expo-linking` to get to that value in Jest. Outside of Jest, e.g. Android or iOS, this works fine.

I'll open a PR to include this `scheme` property, if it was defined in the original manifest.

**Comment by brentvatne** [comment]
published jest-expo@40.0.2 with @byCedric's fix

**Comment by churichard** [comment]
Lovely, thank you so much @byCedric and @brentvatne! Appreciate the work you all are doing.

**Comment by jeremywhittington** [comment]
@brentvatne @byCedric I dont know for sure that im getting the error for the same reason but I do see this warning on a brand new project. Is there something I should do to fix it?

**Comment by 10000multiplier** [comment]
receiving it here too

**Comment by fabdrol** [comment]
me too

**Comment by eprice122** [comment]
+1

**Comment by brentvatne** [comment]
i'm going to lock this thread because i posted that we resolved it almost a year ago, so if you're encountering this then please create a new issue and follow the template to provide a reproducible example and so on
