### ISSUE TITLE
Constants.installationId is not changed by re-installation

### ISSUE THREAD

**Issue by Minminzei** [expo/expo#11785]
**Summary**

After upgrade to `Expo 40` & `expo-constants@9.3.5`, `Constants.installationId` is unique to particular device but _**not installation**_ . re-installation generates same `Constants.installationId`. 

Related to #11566

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

```
  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.2/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: ^17.0.1 => 17.0.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ^0.14.10 => 0.14.10
      expo-constants: ^9.3.5
    npmGlobalPackages:
      expo-cli: 4.0.17
    Expo Workflow: bare
```

**Reproducible demo or steps to reproduce from a blank project**

1. install and launch app on iOS simulator, Expo generates `AAA` as `Constants.installationId`.
1. remove the app from simulator.
1. install and launch again, Expo generates same `Constants.installationId` - `AAA`.

in `Expo 39` & `expo-constants@9.2.0`, re-installation generates different installationId  (AAA -> BBB).

**Comment by ide** [comment]
SDK 40 changed the way the installation ID works on iOS, which fixed an issue with push notification tokens getting duplicated after restoring from backup.

I don't think we'll revert that behavior and instead need to update the docs to explain that Constants.installationId's lifetime is greater than or equal to the current installation and may extend beyond it. In the future, since storing an installation ID can be done in user space, there is no fundamental need for the Constants module to provide installationId and the field may be phased out; it is currently deprecated.

![image](https://user-images.githubusercontent.com/379606/106489269-70199300-6469-11eb-9d7a-cc9273da2d2a.jpeg)

**Comment by Minminzei** [comment]
@ide ok, thank you!
