### ISSUE TITLE
AuthSession.getRedirectUrl() throws on Android Expo Go, works on iOS Expo GO

### ISSUE THREAD

**Issue by marikka** [expo/expo#11832]
**Summary**

`AuthSession.getRedirectUrl()` throws on Android Expo Go, works on iOS Expo GO

This seems to be due to `Constants.executionEnvironment` being `undefined`, here when using SDK39: https://github.com/expo/expo/blob/master/packages/expo-auth-session/src/SessionUrlProvider.ts#L15-L17
It looks like because of that, expo thinks it's "bare" when it is in reality "managed".

Expo Go versions tested:
Android: 2.18.7
iOS: 2.18.4

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

39

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.6.0 - ~/.nvm/versions/node/v15.6.0/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2
      react-native-web: ~0.13.7 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

Setup:
------
expo init --npm 
(select empty typescript project (managed))
expo upgrade 39 --npm
expo install expo-auth-session
expo install expo-constants

Failing code:
------------
import * as AuthSession from "expo-auth-session";
import Constants from "expo-constants";

const executionEnvironment = Constants.executionEnvironment; //This is undefined on Android
console.log(
  `Constants.executionEnvironment: ${JSON.stringify(executionEnvironment)}`
);
const redirectUrl = AuthSession.getRedirectUrl(); // This will throw on Android Expo Go, work on iOS Expo Go
console.log(`AuthSession.getRedirectUrl(): ${redirectUrl}`);

Full, minimal example repository:
---------------------------------
https://github.com/marikka/expo-constants-executionenvironment/blob/main/App.tsx

**Comment by cruzach** [comment]
`expo-auth-session@2.0.3` is released and should fix this. 

there were two issues here:
- expo-auth-session had a different expo-constants dependency than what is available in the managed workflow (^9.2.0 instead of ~9.2.0), so a newer expo-constants version was being pulled in than what should have been
- expo-linking had a patch version released that depended on the new version of expo-constants as well

so we published a new version of expo-linking and also of expo-auth-session to ensure that they depend on the correct versions of expo-constants. to prevent this in the future, we’re going to look at options of either a) removing dependencies from expo-auth-session and letting developers install them manually or b) validating that the dependencies match up with bundledNativeModules.json
