### ISSUE TITLE
[expo-av] Interval of onPlayBackStatusUpdate is not being updated

### ISSUE THREAD

**Issue by system32uwu** [expo/expo#11848]
**Summary**

Expected behavior: setting progressIntervalMilis with setProgressUpdateIntervalAsync or setStatusAsync should change the interval in which onPlaybackStatusUpdate is being invoked.

What's actually happening: It's ignoring the given value and using the default one (500ms).

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40

**Environment**

  Expo CLI 4.0.17 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 15.3.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

https://snack.expo.io/@system32uwu/setprogressupdateintervalasync-bug

Following what's on the [docs](https://docs.expo.io/versions/latest/sdk/av/).

Video component also seems to not be working in web for some reason, however this issue is regarding android.

**Comment by nsdub** [comment]
I'm also seeing this bug in the managed workflow on SDK 41 on iOS

**Comment by nikodraca** [comment]
Did you ever figure this out?

**Comment by system32uwu** [comment]
> Did you ever figure this out?

Never, [I ended up using WebView](https://github.com/system32uwu/sushi-night/blob/884b8a1e9f3560ec041a2c3a5ba607a0bc863935/src/stacks/Anime.js#L606).

**Comment by mnightingale** [comment]
I think its a race condition in your demo.

```js
this._video.loadAsync({ uri: this.state.videoUrl });

//method 2
this._video.setProgressUpdateIntervalAsync(5000);
```

Both of these are async calls, loadAsync always applies the [Default initial AVPlaybackStatusToSet](https://docs.expo.dev/versions/latest/sdk/av/#default-initial--avplaybackstatustoset).

So if because of the async `setProgressUpdateIntervalAsync` gets executed first (very likely) then `loadAsync` will change it back to the defaults.

You'd either need to make a async method and await each call to control the flow, or pass your own initial values via the second parameter to `loadAsync` (See [Playback API](https://docs.expo.dev/versions/v44.0.0/sdk/av/#playback-api))

A little example that I tried and appears to correctly update the interval.

```js
React.useEffect(() => {
  const setup = async () => {
    if (video.current) {
      await video.current.loadAsync({
        uri: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
      });

      await video.current.setProgressUpdateIntervalAsync(1000);
    }
  };

  setup();

  return () => {
    video.current?.stopAsync();
  };
}, [video.current]);
```

---

I would grant that the behaviour is a little odd, I would have expected `setProgressUpdateIntervalAsync` to carry over to the next video loaded by `loadAsync`.
However I can see how that behaviour could be confusing for developers which is why all the playback options are reset to a known state (play from start, don't change rate, volume, or loop, etc.) but it does seem that the `progressUpdateIntervalMillis` could be a kind of global setting for the instance and not reset on every `loadAsync` call.

**Comment by HannahCarney** [comment]
Still having this issue
