### ISSUE TITLE
[Android] [ExpoLocation] Unhandled promise rejection: Error: Not authorized to use background location services

### ISSUE THREAD

**Issue by dorthwein** [expo/expo#11854]
**Summary**

On Android 11+ if someone calls `Location.startLocationUpdatesAsync()` without having granted "Always" permissions, you a user will receive `Not Authorized`.  For apps, such as a run tracker or turn by turn navigation, we need to access background location while the app is "minimized".  This is different than strictly asking for ACCESS_BACKGROUND_LOCATION, which requires more strict approval and permissions.  Instead, we can have a foreground service that stays alive and handles the location events without requiring ACCESS_BACKGROUND_LOCATION.  This will also allow the user to select "When in use" and still be able to minimize the app and receive location events.

I am not an android developer so this is a little outside my scope on being able to implement effectively.  

Another package accomplishes by also using a Headless Task to handle the location events (react-native-background-geolocation). 

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 3.21.10 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 15.5.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-dom: ^16.13.1 => 16.13.1 
      react-native: 0.63.4 => 0.63.4 
    npmGlobalPackages:
      expo-cli: 3.21.10

**Reproducible demo or steps to reproduce from a blank project**

1. Install Expo Location
2. Ask/Grant "When in Use" Location Permissions 
3. Set Foreground Service Setting Config
4. Define on location task per expo documentation for background tracking  
5. Start location with startLocationUpdatesAsync() 
6. Error: Permissions not available.

**Comment by hetanthakkar1** [comment]
Can i work on this issue?

**Comment by dorthwein** [comment]
any update on this or anything I can do to help move it along by chance?

**Comment by hetanthakkar1** [comment]
you can start @dorthwein

**Comment by dorthwein** [comment]
@hetanthakkar1 unfortunately my Java abilities are non-existent beyond following guides :( 

I'll put up a $200 bounty though if you knock it out :)

**Comment by mariomurrent-softwaresolutions** [comment]
Same applies in managed workflow

**Comment by mariomurrent-softwaresolutions** [comment]
@dorthwein Have you submitted your app in the PlayStore? You need to submit it in order to use the background geolocation.
After submitting it for internal test at least I was authorised to use the background geolocation, but nothing is triggered

**Comment by dorthwein** [comment]
We current use the transistor soft plug in above for background tracking but have random crashes with it we can't seem to figure out.  It works generally well but with random issues.  The issues could be unrelated to Transitor soft so this isn't really a knock at them them.

**Comment by dorthwein** [comment]
A little bit more on the transistor soft solution and why we want to get off of it, its basically pretty sensitive to when you turn on and off the tracking.  If you call start too quickly after calling it before, it'll crash.  This has gotten better over time and is a pretty fringe case, but our application does a lot of conditional starting & stoping based on app state and whether tracking is on or not.

**Comment by MaRaSu** [comment]
@byCedric could you please comment this issue, specifically concerning the plans to address it (or in minimum at least confirming that it has been noted as a separate issue vs. the background location):
- as a fix for SDK40 or
- for the upcoming SDK41 which seems to have an on-going refactoring effort in addressing location permissions, however I do not know whether they will address this specifically

I read through +10 other Expo Github issues, some Expo forums discussions and some StackOverflow questions, however all were addressing the issue of "full" background location updates which with the new Google Play policies clearly are not in favor. Google is guiding apps to use foreground location with the "foreground service", which is what this issue is about. And my uninformed guess is that most apps that have used background location before could actually use this form of foreground location.

For my part I'm happy to then forward your answer to other channels were people are asking this same question without getting any answers e.g. #11918 last comment by @devashishsethia. Given Google's policy change for background location there is a lot of confusion around this and lots of time wasted by people desperately seeking for answers.

**Comment by byCedric** [comment]
Hi @MaRaSu (and everyone else)!

I can definitely comment more on this. Essentially Google made some pretty massive changes in 4 consecutive Android API versions. Android 8, 9, 10, and 11 have all different behavior related to location permissions. This is not only confusing for a lot of people, also outside React Native and/or Expo, it's also frustrating for developers. Especially in the Google Play Console, where Google doesn't give actionable feedback when something isn't configured or built property (see [this issue for example](https://github.com/expo/expo/issues/11918)).

That being said, we are sorry for the confusion and frustration some of you might have encountered. We are currently making 2 major changes in the SDK to fix this issue.

1. **Deprecating (but not yet dropping) `expo-permission`**
This sounds like a big change, but in the past few SDKs we moved to adding "permission requesters" in the packages themselves, like [`Camera.requestPermissionsAsync`](https://docs.expo.io/versions/v40.0.0/sdk/camera/#requestpermissionsasync). It should remove some ambiguity we currently have with both methods. We will still keep the `expo-permission` package around to give everyone enough time to eventually move over. We will give more context and info to this in the SDK release announcements.

2. **Splitting the `LOCATION` permission into `LOCATION_FOREGROUND` and a`LOCATION_BACKGROUND`**
This is the most important change related to this issue. Previously, we tried to guess or estimate whenever we need to request the background location permission. But this turned out to be even more confusing. In order to fix that, and to fully comply with Google's policy, we are giving APIs to make this decision yourself. This allows everyone to only request fore- or background location permissions. (_You can [see the change here](https://github.com/expo/expo/pull/12063)_)
We are trying to make these changes with some backward compatibility. Because these changes are fairly big, we will only make them for SDK 41. If you are running SDK 39 or 40 it should be fairly easy to update, we use the same RN version in these SDKs.

Hope this gives more context and some "hope" for the path forward.

**Comment by matheus-caldeira** [comment]
Hi guys,

I had to send an app without the background permissions directly to production. Because the last published version was with SDK 39.

**Comment by MaRaSu** [comment]
@byCedric thanks, much appreciate your swift reply. And as you said, Google has indeed made location capability unreasonably complex to navigate with all those changes.

I would still ask for one clarification, simply because the terminology is somewhat confusing here: Will SDK41 support (esp. for Android 11) asking user only for LOCATION_FOREGROUND permission and then calling Expo `Location.startLocationUpdatesAsync()` while providing in its options `foregroundService`in order for app to receive location updates (via TaskManager) **also** when it's not in the foreground or device display is off? 

This is where I think the term "foreground location service" is confusing because it can mean `Location.watchPositionAsync` or the much more capable location service I described in previous paragraph (and what this issue #11854 is all about). I would rather call this more advanced capability "semi-background location service" because it enables so many use cases like navigation, fitness record your run / walk / ride etc. type of apps.

**Comment by byCedric** [comment]
Short answer is yes, the changes we are making should allow exactly that 😄 

The long answer is best [described in this medium post](https://medium.com/@adrian.kajda/restrictions-to-background-location-and-foreground-services-in-android-11-9501adcd5795#665d) I think. We still need the "foreground service" to actively pull in the location data, but that's not part of the foreground/background issue here.

As for the terminology, we try to match Google's own terminology matched in [this guide](https://developer.android.com/training/location/permissions#request-location-access-runtime). In that guide they explain the use cases and how they relate to foreground/background location. They also recommend how to request it, making it compliant with their policies.

Hope this helps!

**Comment by MaRaSu** [comment]
@byCedric thanks once more, this indeed settles the matter. With this I can now spread the word to other places where people are asking about this.

**Comment by devashishsethia** [comment]
@byCedric Thank you for clarification and @MaRaSu  for updating different threads. 
One question wrt to the current Taskmanager implementation - Does the "foreground service" option mean the same thing as what is mentioned in the android guide. If yes, then is it possible to just use this without using the background location permission as of now also to get location updates after showing a notification. Asking this because I checked your office-marathon sample app and you've asked for Background Location permission in the app, which wasn't necessary (if we go by the android guide) as it was a user-initiated action.

I can speak for myself but I believe a lot of other people would be happy handling the permissions on their own (based on the Version number) if it means not having to ask for access_background_location permission so that they can publish their apps quickly. This whole android location permission thing is turning out to be a nightmare from android!

> Short answer is yes, the changes we are making should allow exactly that 😄
> 
> The long answer is best [described in this medium post](https://medium.com/@adrian.kajda/restrictions-to-background-location-and-foreground-services-in-android-11-9501adcd5795#665d) I think. We still need the "foreground service" to actively pull in the location data, but that's not part of the foreground/background issue here.
> 
> As for the terminology, we try to match Google's own terminology matched in [this guide](https://developer.android.com/training/location/permissions#request-location-access-runtime). In that guide they explain the use cases and how they relate to foreground/background location. They also recommend how to request it, making it compliant with their policies.
> 
> Hope this helps!

**Comment by MaRaSu** [comment]
@devashishsethia my interpretation of @byCedric reply is that in SDK41 it will be possible to do what you refer to (and what my app desperately needs too) without needing to request access_background_location permission and try to go through Google's special review.

However in the current SDK40 (and earlier versions) use of `Location.startLocationUpdatesAsync()` is linked to background location permission as @byCedric explained above. It was apparently an abstraction that worked well enough prior to Google tightening up the policy on background location permission. Now Expo's location & permission APIs need refactoring and therefore the fix will come only in SDK41.

**Comment by byCedric** [comment]
@MaRaSu That's right!

We still have specific methods which are built for background location access, like the `Location.startLocationUpdatesAsync`. This method communicates with the `expo-task-manager`, and runs _only_ in the background. Because of that, it requires background location permission. With the refactored permissions API in SDK 41, you can handle the permission request yourself and tailor it perfectly according to Google's policies for your app.

But, if you want to listen to location changes in the app itself (not in a background task), you can use other methods built for that. I think the [`Location.watchPositionAsync`](https://docs.expo.io/versions/v40.0.0/sdk/location/#locationwatchpositionasyncoptions-callback) is the counterpart of `Location.startLocationUpdatesAsync` that works without background location permission 😄 

Hope this clarifies a few things.

**Comment by MaRaSu** [comment]
@byCedric Hmmm, your comment made me now worry a bit. I'm afraid I can read your latest msg in 2 ways and one of them is not good for the type of app I am (and @devashishsethia apparently too is) building.

As of today with SDK40 I need to use `Location.startLocationUpdatesAsync`because it allows me to create a foreground service (with `expo-task-manager`) that enables my app to receive location updates also with device display off or my app not in the foreground. `Location.watchPositionAsync` only provides location updates when device display is on AND my app is on the foreground, which obviously does not work for navigation app or fitness exercise recorder which my app effectively is. NB! My need is different than in some geofencing or all-day fitness tracker app which under new Google policy probably continue to require background location access (& permission) without user specifically initiating the activity (and without showing a persistent user notification).

Now, based on previous comments and having read new Google policy, my impression of new SDK41 implementation was that new `Location.startLocationUpdatesAsync` would allow me to ask only for foreground location services permission AND it would implement the type of foreground service (with `expo-task-manager`) & provide also a persistent user notification that makes Google happy to regard it as "Foreground location" as described in the guide you linked [Google location service](https://developer.android.com/training/location/permissions#foreground).

I guess alternative would be to modify `Location.watchPositionAsync` to have the similar support for foreground service with persistent user notification etc. but not sure it would make sense as location "watching" would need to support 2 alternatives, one with callback function another with `expo-task-manager`.

However the point here is the need for this new "in-between" location service which Google considers "Foreground location" and yet if effectively works as a background service, all good as long as the user experience is a Google has defined.

**Comment by devashishsethia** [comment]
Thank you @MaRaSu  for articulating this so well. 
@byCedric, even in my app which is a scheduled rideshare app where a driver for example can get a ride for next day morning. I want to show the location of the driver to the riders when the driver "starts the ride" upon pressing a button (a user initiated action).
I want to be able to continuously get driver's location while the driver is navigating using another app (e.g. google maps). My understanding of this issue is exactly as what @MaRaSu described: 

1) That we create a "foreground service" which would ensure that our app keeps getting location updates even when the app's UI is not visible. If we go by the terminology that android uses, our app would still be in the foreground as long as a foreground service is created that displays a persistent notification. (We would also need to declare this service of type location in the manifest, but that's another question)

Quoting from the docs:
> The system considers your app to be using foreground location if a feature of your app accesses the device's current location in one of the following situations:

> An activity that belongs to your app is visible.
**Your app is running a foreground service. When a foreground service is running, the system raises user awareness by showing a persistent notification.** Your app retains access when it's placed in the background, such as when the user presses the Home button on their device or turns their device's display off.

When drivers complete a ride, we no longer need to track their locations and we can terminate the foreground service thus created with the help of TaskManager. Hence, our apps shouldn't be asking for background location permissions as per google's guidelines and hence we risk facing rejection. In fact I can think of a whole lot of examples where background locations are currently used but will not be required anymore.

2. `Location.watchPositionAsync` would not suffice our use cases as we'll stop getting any location updates as soon as the user leaves the app/turns off the display.

A part of me was relieved thinking that with a foreground service created we could bypass the whole background location permission thing that has resulted in a lot of app rejections but I'm now staring at an imminent rejection.

I guess decoupling permissions seem like a step in the right direction even at the expense of making it a little lower level API but I guess that also makes a little more future proof. Unfortunately, I have never written any native code otherwise I would have loved to help.

**Comment by byCedric** [comment]
Hi @MaRaSu and @devashishsethia! Thanks for the detailed write-up of your use cases. Locations turned out to be a dramatic complex thing, you can use it with a combination of all sorts. This definitely helps us to understand what the API should be capable of, so many thanks for that.

We are still in QA phase for the next SDK. Does either one of you have a simple plain Expo project that contains example code for this use case? If so, I'd be happy to test this during our QA or beta period. If not, I need to take some time to modify my test app "[office marathon](https://github.com/byCedric/office-marathon)" (which is live on the Play Store, got past the background review 😄 )

If I look at the Android docs, the use case you describe _should_ be possible. But I think we are missing really small specifics in our current code. Like [starting the service with a `FOREGROUND_SERVICE_TYPE_LOCATION` flag](https://developer.android.com/guide/components/foreground-services#loc-camera), to let Android know that "this _foreground service_ should have access to location while the pinned notification is active". (It's currently [not set in this method](https://github.com/expo/expo/blob/78cc872e23796b0617ce828994a75830f701d79c/packages/expo-location/android/src/main/java/expo/modules/location/services/LocationTaskService.java#L67))

**Comment by devashishsethia** [comment]
Thanks @byCedric. I have had to unfortunately eject, but I believe your office marathon example app is an excellent example of the kind of use case (user initiated action) that we have described. 

When one taps the `start tracking` button: 
1. We should check if access_foreground_location permission is granted.
 2. If yes, a foreground service should be started and the app should receive location updates regardless of whether app's main UI is visible or not. (A persistent notification should be visible though)
 3. When one taps the` stop tracking` app should unsubscribe from the location updates and terminate the service.
 
 We'll also need to find a way to declare this service in the app's manifest which is required version 10 onwards. 
 > On Android 10 (API level 29) and higher, you must declare this foreground service type.

**Comment by devashishsethia** [comment]
BTW, My desperation to get my app out has also sent me searching for answers elsewhere as well. I'm checking a few implementations of the foreground services as I write this to see if I can use those.  Specifically, [this package](https://www.npmjs.com/package/react-native-foreground-service)

**Comment by MaRaSu** [comment]
@byCedric I also took a quick look at "office marathon" app and the Track.ts is practically the same as in my app. Now, the trick is to make it work with foreground location permission only. I'm not competent with native Android, however I feel you are on the right track with your last paragraph on changes needed in Expo. That was also why I got worried and kept on pushing this issue when you were referring only to "permissions refactoring" but not detailing out the other changes needed ;=) 

My app is on managed workflow and I would prefer to keep it that way. I can well wait until SDK41 assuming this will be truly fixed. It seems some apps, like your "office marathon" have gotten through the Google special background location review - still it's very much an inferior solution because of the complications of getting the "allow all the time" permission from the user by requiring to guide her / him to Android settings.

**Comment by byCedric** [comment]
Yep, you are definitely right about the inferior option. I'll get back to you guys when I know more!

**Comment by devashishsethia** [comment]
> BTW, My desperation to get my app out has also sent me searching for answers elsewhere as well. I'm checking a few implementations of the foreground services as I write this to see if I can use those. Specifically, [this package](https://www.npmjs.com/package/react-native-foreground-service)

I don't want to hijack this thread but help people who are in the same boat as me and @MaRaSu . While we wait for the next expo release, I did a quick and dirty poc on android 11 with [this package](https://www.npmjs.com/package/@supersami/rn-foreground-service), and I see that it seems that I could use this along with react-native-geolocation-service (but I guess we could just as well use expo-location's watchPositionAsync). 

I didn't have to request access_background_location permission but still getting location updates every five seconds at least 15 minutes after I pressed the home button and turned the display off. 
I got a total of 172 updates in 860 seconds so seems very reliable on the emulator.

AndroidManifest.xml 
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.myapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <meta-data
      android:name="com.supersami.foregroundservice.notification_channel_name"
      android:value="Sticky Title"
    />
    <meta-data
      android:name="com.supersami.foregroundservice.notification_channel_description"
      android:value="Sticky Description."
    />
    <meta-data
      android:name="com.supersami.foregroundservice.notification_color"
      android:resource="@color/blue"
    />
    <!-- android:foregroundServiceType="location" -->
    <service android:name="com.supersami.foregroundservice.ForegroundService" android:foregroundServiceType="location"></service>
    <service android:name="com.supersami.foregroundservice.ForegroundServiceTask" android:foregroundServiceType="location"></service>
    </application>
</manifest>
```

![Screenshot_1616482745](https://user-images.githubusercontent.com/17251082/112106205-65f75380-8bd3-11eb-9dab-e650289be786.png)
<img width="490" alt="Screenshot 2021-03-23 at 12 28 59 PM" src="https://user-images.githubusercontent.com/17251082/112106212-6a237100-8bd3-11eb-8308-0ff584b492e6.png">
![Screenshot_1616482724](https://user-images.githubusercontent.com/17251082/112106215-6b549e00-8bd3-11eb-9d5b-c29491a908c6.png)

**Comment by devashishsethia** [comment]
working on android 9 and 10 as well. Checked on real devices. Working as expected.

**Comment by MaRaSu** [comment]
@devashishsethia great stuff!

@byCedric any chance you could confirm that just announced Expo SDK 41 beta implements support for the type foreground location (like "background" but with foreground permission & notification) service we have been discussing on this thread?

**Comment by strayiker** [comment]
Combination of [notifee foreground service](https://notifee.app/react-native/docs/android/foreground-service) and [react-native-geolocation-service](https://github.com/Agontuk/react-native-geolocation-service) is also works.
One extra step you need to do is after install `notifee` add `<service android:name="app.notifee.core.ForegroundService" android:foregroundServiceType="location" />` to your `AndroidManifest.xml`.


```typescript
initialize() {
  Notifee.registerForegroundService(() => new Promise(() => {}));
  this.channelId = await Notifee.createChannel(/* channel config (see the notifee docs) */);
}

start() {
  Notifee.displayNotification(/* notification config (see the notifee docs) */);
  this.watchId = Geolocation.watchPosition(/* location options */);
}

stop() {
  if (this.watchId !== undefined) {
    Geolocation.clearWatch(this.watchId);
  }
  Notifee.stopForegroundService();
}
```
