### ISSUE TITLE
Android app rejected because of background location

### ISSUE THREAD

**Issue by byCedric** [expo/expo#11918]
Google recently [added restrictions to the usage of background location](https://support.google.com/googleplay/android-developer/answer/9799150?hl=en). We've been getting multiple reports about this restriction blocking updates within the Google Play Console. Because of that, we want to list a few steps you can take to get your app unblocked.

## Configure your project

For **managed workflow**, make sure you upgraded to SDK 40. In this release, [the background location permission was changed to an opt-in permission](https://dev.to/expo/expo-sdk-40-is-now-available-1in0#background-location-is-now-an-optin-permission-on-android).

- Make sure you are using Expo SDK 40.
- Check if your app manifest has the [`android.permissions`](https://docs.expo.io/versions/latest/config/app/#permissions) list.
- Remove the `ACCESS_BACKGROUND_LOCATION` from this permission list.
- Build a new APK with `expo build:android --type apk --release-channel permission-audit`.

For **bare workflow**, make sure you target Android SDK 29. Google added the background location permission in this version. Before this version, [the background location is implied when using both coarse and fine location permissions](https://github.com/Baseflow/flutter-geolocator/issues/535#issuecomment-765181418).

- Make sure your `targetSdkVersion` and `compileSdkVersion` target `29` or higher.
- Check if your `AndroidManifest.xml` doesn't include the `ACCESS_BACKGROUND_LOCATION` permission.
- Optionally, you can force-exclude this permission by adding `tools:node="remove"` (see [the permissions docs](https://docs.expo.io/versions/latest/sdk/permissions/#excluding-android-permissions-in-bare-workflow)).
- Build a new APK with Android Studio or CLI.

## Validate the permissions from APK

When you built a new APK, we can validate the included permissions with [the AAPT2 tool](https://developer.android.com/studio/command-line/aapt2).

- Check if you can use `AAPT2` (see [getting started](https://developer.android.com/studio/command-line/aapt2#download_aapt2)).
- Run `aapt2 d permissions path/to/app.apk`
- Validate if the `ACCESS_BACKGROUND_LOCATION` is _not_ listed, if it is remove this permission (see above).

## Removing older binaries from Google Play Console

You might have older binaries uploaded in the Google Play Console that uses background location permissions. If you uploaded a new binary, and double-checked that it doesn't include that permission, remove the older binaries from the Google Play Console. See [this Stack Overflow thread](https://stackoverflow.com/a/65791133/2277025) for more info.

You can also create a new app in Google Play Console to test if the binary is allowed. If you want to try that, make sure to change the [`name`](https://docs.expo.io/versions/latest/config/app/#name) and the [`android.package`](https://docs.expo.io/versions/latest/config/app/#package) in your app manifest to create a different app.

---

## Still getting blocked?

If your binary is still getting blocked, even after removing older binaries with the `ACCESS_BACKGROUND_LOCATION` permission, you need to contact Google. ~~You can use [this link](https://support.google.com/googleplay/gethelp) to get in touch with Google Play Store support.~~

**Edit**, as @bryanstearns mentioned, it looks like Google removed the `Declare location app permissions` option and the ability to directly email Google Play Developer Support. That leaves us with fewer options, here are some that might help:

1. If your app is getting rejected, use the contact or appeal options in that email instead. 
2. Try [using Facebook Messenger to chat with them](https://m.me/googleplaydev)
3. Try [Tweeting them using `@GooglePlayDev`](https://twitter.com/GooglePlayDev)
4. Or try posting on their community forums, don't mention security sensitive info. But the community isn't getting answered that fast.

<details>
<summary>The old way of contacting Google Play Developer Support through email</summary>
<pre>
1. "Let's get started", fill in `App update blocked by background location permission`
2. Click "Next step"
3. "Confirm issue", click `Declare Location App Permissions`
4. Click "Next step"
5. "Contact options", click email (or chat if you need a faster response)
6. Fill in the required info for your account
7. "How can we help?", mention:
    - Your app is blocked from release because of the "background location permission" warning.
    - Your app does not include the `ACCESS_BACKGROUND_LOCATION` permission.
    - Your app is targeting Android SDK 29+.
    - Ask why the update is blocked.
8. Include a screenshot of:
    - Your warning in the Play Store
    - The output of the `AAPT2` command
</pre>
</details>

> Please keep in mind that a response from Google is taking longer than expected due to COVID.

**Comment by dmaslowski** [comment]
Thank you so much for posting this. I have been struggling for the past few weeks to understand why google keeps flagging my app.

**Comment by byCedric** [comment]
Sorry you are having issues with this. It's unfortunate that Google isn't providing actionable steps for developers to solve this, that would have helped everyone in this case. I hope you get this resolved asap. If you need to contact Google and receive a response, I'd love to hear about it. You can ping me directly on Slack or Discord (same username as here) 😄

**Comment by ghacosta** [comment]
Hi guys this post was really useful. But I found an issue.
Note, I'm using:
* expo managed version
* SDK 40
* my `android.permissions` just `["CAMERA", "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE"]`

If I build my app this way: `expo build:android --type apk` it doesn't add any LOCATION permissions here is my `aapt2` output:

```
package: com.something.some
permission: com.something.some.permission.C2D_MESSAGE
uses-permission: name='com.something.some.permission.C2D_MESSAGE'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.SYSTEM_ALERT_WINDOW'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='host.exp.exponent.permission.C2D_MESSAGE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='com.sonymobile.home.permission.PROVIDER_INSERT_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.CHANGE_BADGE'
uses-permission: name='com.huawei.android.launcher.permission.READ_SETTINGS'
uses-permission: name='com.huawei.android.launcher.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.READ_APP_BADGE'
uses-permission: name='com.oppo.launcher.permission.READ_SETTINGS'
uses-permission: name='com.oppo.launcher.permission.WRITE_SETTINGS'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_READ'
uses-permission: name='me.everything.badger.permission.BADGE_COUNT_WRITE'
uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
```

In the other hand, if I run `eas build` (both apk or aab) it adds LOCATION permissions which suppose an error on google play app submission.

```
package: com.plenocentro.admintienda
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.SYSTEM_ALERT_WINDOW'
uses-permission: name='android.permission.READ_PHONE_STATE'
uses-permission: name='android.permission.USE_FINGERPRINT'
uses-permission: name='android.permission.USE_BIOMETRIC'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.ACCESS_BACKGROUND_LOCATION'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.READ_CONTACTS'
uses-permission: name='android.permission.WRITE_CONTACTS'
uses-permission: name='android.permission.READ_CALENDAR'
uses-permission: name='android.permission.WRITE_CALENDAR'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
uses-permission: name='com.google.android.providers.gsf.permission.READ_GSERVICES'
uses-permission: name='com.google.android.gms.permission.ACTIVITY_RECOGNITION'
```

Would be great if you fix this issue on `eas build` because it's an excellent tool and I'm willing to continue paying for it.

Hope this comment help you somehow! I'll be around if you need more info to tackle this issue.

**Comment by brentvatne** [comment]
thank for your sharing that information @ghacosta!

EAS Build for managed apps is still experimental and not recommended for production. we plan to do our first official preview release of managed build support at the end of Q1/alongside SDK 41, and we'll definitely ensure that Android permissions are addressed before then.

**Comment by bryanstearns** [comment]
I also appreciate this, @byCedric - I'm stuck here too:

- I've updated my app to SDK 40, verified with `aapt2` that my new build doesn't use ACCESS_BACKGROUND_LOCATION, and my `targetSdkVersion` and `compileSdkVersion` are both `29`, but it got rejected apparently because the existing production-release version of the app (from last year, SDK 38) is still available. I appealed the rejection but was denied without any additional reasoning.

- I tried to find a way to somehow deactivate the released version of my app , but couldn't found a way. I also wasn't able to use the link you provided to get help from Google Play Support but `Declare Location App Permissions` isn't an available choice for me in step 3; I tried many of the choices, but they all lead to it recommending "Community" as the only contact option.

At this point, since there's still a bit of time before the March deadline, I decided to change my answer in the Policy / App Content / Sensitive app permissions / Manage / Location permissions / Manage to "No, this app does not meet the Location permissions policy". This should be approved;  once it is, I'll change my answer back to "Yes, this app meets the Location permissions policy" and submit _another_ new version - my hope is that this'll get approved because there'll no longer be a non-compliant released version in the way. 🤞

**Comment by kevmo314** [comment]
How can I test whether or not background location works with the expo client? It doesn't seem to have the requisite permissions, and I always receive a "background location not authorized" error.

**Comment by gp-birender** [comment]
@byCedric  - Thanks for the info, I have removed the ACCESS_BACKGROUND_LOCATION  from the expo versions(39) and pushed the next versions for review and it got rejected by Google even after removing permission. The current versions of the app which is on the store have this permission already. so what should be the next step for approval?
1. update to expo 40 
or
2. upload apk instead or aab
 or
3. remove the app and upload a new one
or
4.  talk to support?

**Comment by dhavaljardosh** [comment]
Those struggling with this issue, here is something that will solve this issue.

By default Expo asks for all permissions, which is ok while testing.
But while deploying to Play Store make sure that you add only those you need.

Example of my application:
```
"permissions": [
        "CAMERA",
        "MEDIA_LIBRARY",
        "CAMERA_ROLL",
        "NOTIFICATIONS",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ]
```

**Comment by brentvatne** [comment]
@dhavaljardosh is correct - it's also worth pointing out that we provide guidelines that include his recommendation on the "[Deploying to App Stores](https://docs.expo.io/distribution/app-stores/)" documentation page

**Comment by gp-birender** [comment]
@dhavaljardosh - In my case, app with expo 39 is in the store with the location permission but we are not using it anywhere. Now after google policy update we are trying to update app by removing the location by the expo to 40. but google still rejection it. we also tried it by adding `"permissions": []`

**Comment by msvargas** [comment]
@gp-birender I have the same problem, Do you try deleting the old binaries?

**Comment by gp-birender** [comment]
@msvargas -  how could I do that its already in the store. do you mean unpublish my current app?

**Comment by razzfox** [comment]
My solution was to remove these permissions after ejecting, and before building. 
```
sed -i '.last' -e 's/  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"\/>//' android/app/src/main/AndroidManifest.xml
sed -i '.last' -e 's/  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"\/>//' android/app/src/main/AndroidManifest.xml
sed -i '.last' -e 's/  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"\/>//' android/app/src/main/AndroidManifest.xml
```

**Comment by msvargas** [comment]
@gp-birender Check this: https://github.com/Agontuk/react-native-geolocation-service/issues/240#issuecomment-789649247

**Comment by gp-birender** [comment]
@byCedric  - @msvargas - Thanks it's approved now

**Comment by msvargas** [comment]
@gp-birender If you can upgrade to Expo 40, great!

**Comment by normenster** [comment]
Last week we uploaded  a new version of our app that targets children unter 13 (biggest german public broadcast kids channel). It`s based on the bare workflow. I`ve upgraded to SDK39 since last live version. App got rejected from Apple (using Ad SDK) and Google (Ad SDK and FINE_LOCATION permission error). I fixed that removing the "expo" dependency in package.json and force removed all location related permissions from Android Manifest. Apple got approved, but in Play Console i cannot resubmit the App for new approval, because it claims that i should remove location permission first from the release to meet the kids family policy :"You will need to remove location permission from your app if the app is for children under the age of 13": But the permission is definitely not in the newest build - i double checked that. It seems the wrong build ist blocking all updates, even if i change the version code. I can`t remove the "wrong" build and tried everything above with all the different release tracks.  Contacted Google via Email, Facebook, Twitter. Any more ideas?

**Comment by superyarik** [comment]
@normenster 
1) there is appeal form on google play console after reject mail
2) try to remove all old app version from all channels - open, close, etc. just submit there new version too.

**Comment by normenster** [comment]
thanks, we did that already. I cannot remove the wrong version, its simply not possible to delete it.

**Comment by superyarik** [comment]
@normenster remove = replace by new fixed. old version still available in bundle library but it does not affect you when all tracks are free from it.

**Comment by normenster** [comment]
the "wrong version" exists only in the release track. I create a new app, upload it and click "Check Release". Than this error appears. It doesnt matter if I upload a new binary in release or internal test track - the error message is always the same.

<img width="1079" alt="Bildschirmfoto 2021-03-16 um 07 48 21" src="https://user-images.githubusercontent.com/1347907/111267641-8308b100-862c-11eb-93a4-705a22bb4deb.png">

"You must remove the geolocation permission requirement from your app if the app is targeted only at children under the age of 13".

the permission overview in the app as listed in the play console:

<img width="659" alt="Bildschirmfoto 2021-03-16 um 07 56 45" src="https://user-images.githubusercontent.com/1347907/111268174-3d001d00-862d-11eb-8d62-f2c1dfb2a29e.png">


The Button "Start production release" is grey and not clickable. For now i think maybe we can change the target groups to "include all" and leave the "Designed for Families" Program. Then hopefully we can submit, and change it back when the new version is live.

**Comment by uen** [comment]
We needed to submit an update to our app but couldn't due to the old binary using location permissions, tried every suggestion that's been posted & tried contacting Google (no reply). In the end we had to submit a new app to the Play store. I believe it's impossible to resolve unless you create a new app unfortunately

**Comment by normenster** [comment]
@uen did you develop a kids app for under 13 that is in the designed for families program?

**Comment by uen** [comment]
@normenster No it wasn't for the families program, we were trying to submit an update removing location permissions but couldn't submit because our old binaries used the permissions. 

Your solution `For now i think maybe we can change the target groups to "include all" and leave the "Designed for Families" Program` sounds like it will work for you

**Comment by normenster** [comment]
Yeah, we try that. I will keep you updated :)

**Comment by normenster** [comment]
@uen didn`t work - now the target audience ist inaccurate. That´s just insane. Is this something that has to do with the new google play console? When did you encounter those issues?

**Comment by uen** [comment]
@normenster We've been having issues since February when we needed to update. I think that the old GPC used to have a radio selection where you could declare you don't use location permissions but it's not in the new design. It's a pretty big oversight on Google's part imho & it's made worse by the fact it's basically impossible to contact a human at Google

**Comment by normenster** [comment]
@uen We`re trying to get more help from them, our mail got answered but didn`t help. The issue is now handed over to another unit which is dealing with play console issues. Let`s see what happens. Worst Case is switching to a new App. but that means new package name and users can`t easily switch or update right? How did you handled that?

**Comment by uen** [comment]
@normenster 

> The issue is now handed over to another unit which is dealing with play console issues. Lets see what happens

That sounds familiar, when we contacted support we got the following reply after a few emails:

```
At this time, my team isn't able to provide support for publishing and distributing apps through the Play Console. I forwarded your question to the appropriate team at Google, and you can expect to hear from them soon.
```

That was on the 10th of February and they still haven't responded despite 3 follow ups so I wouldn't expect a response :disappointed:  


> Worst Case is switching to a new App. but that means new package name and users cant easily switch or update right? How did you handled that?

Our update was upgrading Expo to v40 from v38, so we actually waited until the iOS app got approved with SDK 40, then pushed an OTA to SDK 38 with a simple screen that said "Please download our new app... <button with link>"

Since the old app on SDK 38 wasn't updated, users would download the OTA on startup and be presented with the screen, while iOS users and the Android new app (on SDK 40) wouldn't get the OTA. If you don't want to upgrade Expo versions you could do a similar thing by switching release channels.

It's obviously not ideal but you might as well switch ASAP because I doubt this will be fixed anytime soon

**Comment by normenster** [comment]
@uen ok - Our app is on bare-workflow. We do have a built-in force update mechanism per platform. Backend define a min version - all apps below this version present on start a "please update our app" dialog with a configurable link. We could link there to the new app.

**Comment by devashishsethia** [comment]
Quoting from android docs:

> The system considers your app to be using foreground location if a feature of your app accesses the device's current location in one of the following situations:
> 
> An activity that belongs to your app is visible.
> Your app is running a foreground service. When a foreground service is running, the system raises user awareness by showing a persistent notification. Your app retains access when it's placed in the background, such as when the user presses the Home button on their device or turns their device's display off.
> 
> Additionally, it's recommended that you declare a foreground service type of location, as shown in the following code snippet. On Android 10 (API level 29) and higher, you must declare this foreground service type.

I have two questions, if anyone can confirm and help :
1. Do we need to ask for background location permissions when using startLocationUpdatesAsync because we can start a foreground service with TaskManager?

2. 
> Additionally, it's recommended that you declare a foreground service type of location, as shown in the following code snippet. On Android 10 (API level 29) and higher, you must declare this foreground service type.
What should be the name of the service?

I've ejected from expo so can update manifest file.

**Comment by MaRaSu** [comment]
@devashishsethia & anyone else wondering the same i.e. use of foreground location service to get location updates even when app is not on the foreground or display is off, latest info on supporting this is available in #11854.

**Comment by AntonioHReyes** [comment]
now I have problems loading an apk for the MANAGE_EXTERNAL_STORAGE permission, I have added an empty array to my app.json but it doesn't work, does anyone know how I can remove that permission from my application?

**Comment by superyarik** [comment]
@AntonioHReyes  build APK file without any additions in app.json, parse it with some apk analyzer - you will get list of permissions by default, edit this list and put it to the app.json

**Comment by byCedric** [comment]
@AntonioHReyes also see https://github.com/expo/expo/issues/12603

**Comment by colbygarland** [comment]
I have a bare workflow app currently, and I _need_ to access location in the background. I have the permission in the manifest. I believe I am following all the current criteria set out by Google, but we keep getting rejected, with little help as to why.

Has anybody come across this yet?

**Comment by brentvatne** [comment]
@colbygarland - make sure to follow the instructions on https://support.google.com/googleplay/android-developer/answer/9799150 - you need to fill out the google play "permissions declaration form" for example

**Comment by MaRaSu** [comment]
@colbygarland You probably have already checked that you truly need "full" background location rather than the much easier and more common special case of foreground location with the ability to get location updates while display is off or your app is in the background (works as long as app shows foreground service notification).

**Comment by leoafarias** [comment]
Having the same issue here. Quick question I am currently on SDK 40, I have added Permissions and removed permissions. However tried adding just `["NOTIFICATIONS"]`, after an `expo eject` the location background, and the others still show up on AndroidManifest. Does the fix above only apply for expo build, and eas? 

It seems that this would explain why some people continue to have the issue

**Comment by leoafarias** [comment]
Just a bit more insight on this, when running the deployment workflow through Bitrise which runs a expo eject that permissions are all populated, however when running `expo build` it works as expected.

**Comment by brentvatne** [comment]
@leoafarias - on sdk 42 this will no longer be the case, when you run `expo eject` or `expo prebuild` (prebuild is the new name for this command) then it will only include permissions used in your app

**Comment by nympheastudio** [comment]
i had app rejected for ACCES_BACKGROUND_LOCATION use .
so to build with **expo build:android** with expo SDK 45 i had to change my config to : 

  ```
android: {
    ...config.android,
    package: 'com.*******.app',
    versionCode: 17,
    blockedPermissions: ['ACCESS_BACKGROUND_LOCATION'],
    permissions : [
      "ACCESS_COARSE_LOCATION", 
      "ACCESS_FINE_LOCATION", 
    ],
```

and then google accepted the new version.

**Comment by bilboyk** [comment]
thank you so much i spent a lot of time to document and trying to resolve it

**Comment by bilboyk** [comment]
> i had app rejected for ACCES_BACKGROUND_LOCATION use . so to build with **expo build:android** with expo SDK 45 i had to change my config to :
> 
> ```
> android: {
>   ...config.android,
>   package: 'com.*******.app',
>   versionCode: 17,
>   blockedPermissions: ['ACCESS_BACKGROUND_LOCATION'],
>   permissions : [
>     "ACCESS_COARSE_LOCATION", 
>     "ACCESS_FINE_LOCATION", 
>   ],
> ```
> 
> and then google accepted the new version.

thank you so much i spent a lot of time to document and trying to resolve it

**Comment by superyarik** [comment]
i build apk with **expo build:android**, after get full list of permissions in this apk and move it to config with deleting ACCES_BACKGROUND_LOCATION permission.

**Comment by TyAzur** [comment]
ss
