### ISSUE TITLE
getDevicePushTokenAsync failing on Android build

### ISSUE THREAD

**Issue by n2ctech** [expo/expo#11937]
**Summary**

Getting the following error when trying to get expo push notification token on Android build. It is working fine on iOS.

`Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Please set your project ID. A valid Firebase project ID is required to communicate with Firebase server APIs: It identifies your project with Google.`

I am not using firebase anywhere in my app. I have followed expo documentation for setting up notifications on the managed workflow (I got the registerForPushNotificationsAsync function in my code straight out of expo docs).

app.json :
```
"android": {
      "softwareKeyboardLayoutMode": "pan",
      "useNextNotificationsApi": true,
      "versionCode": 400020160,
      "package": "com.package.name",
      "playStoreUrl": "https://play.google.com/store/apps/...",
      "icon": "assets/images/icon.png",
      "adaptiveIcon": {
        "foregroundImage": "assets/images/....png",
        "backgroundColor": "#FFF"
      },
      "config": {
        "branch": {
          "apiKey": "ewfewfwe"
        },
        "googleMaps": {
          "apiKey": "wefweewr"
        }
      }
}
```

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

40

**Environment**

`
 Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0 
      react: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-navigation: ^3.13.0 => 3.13.0 
    Expo Workflow: managed
`

**Reproducible demo or steps to reproduce from a blank project**

1. Add expo-notifications and getDevicePushTokenAsync to a managed expo project
2. Build and deploy Android
3. getDevicePushTokenAsync returns an error

**Comment by Larzack** [comment]
Same for me

**Comment by ide** [comment]
You may want to try following the Firebase setup instructions, namely just the part around google-services.json. Firebase (FCM) is the main Android push notification system (there's no "Google push notification service" the way there is one for Apple -- Android uses Firebase Cloud Messaging). The Expo docs may need to be updated to reflect this.

**Comment by artsnr1** [comment]
@n2ctech Same issue here. Did you find the solution

**Comment by n2ctech** [comment]
@artsnr1 it appears the documentation at https://docs.expo.io/versions/latest/sdk/notifications/ is incomplete and you might want to follow this one as well : https://docs.expo.io/push-notifications/using-fcm/. Haven't been able to confirm that it fixes my issue just yet.

**Comment by danprince** [comment]
We're seeing this behaviour on an app that has been using Expo's push service.

We only use the `Notifications.getExpoPushTokenAsync()` function from the `expo-notifications` package, and yet we're getting this error about `getDevicePushToken` and Firebase projects.

Nothing in the migration guide for `expo-notifications` mentioned that the Expo push service would require a Firebase project, so we're a little bit lost as to why the `getDevicePushToken` method even gets called.

These errors started showing up around the same time over the past few days. Did anyone get any further with this?

**Comment by classiebit** [comment]
Same here as @danprince

**Comment by danprince** [comment]
@classiebit We ended up doing the Firebase setup, which fixed things.

In the `expo-notifications` package [`getExpoPushTokenAsync`](https://docs.expo.io/versions/latest/sdk/notifications/#getexpopushtokenasyncoptions-expotokenoptions-expopushtoken) actually needs a `devicePushToken` (the one you get from Apple/Google) to work. If you don't pass one explicitly, it fetches it automatically.

https://github.com/expo/expo/blob/5e0a6bc252aa05e5fa5ea371169d01902ba6bb1a/packages/expo-notifications/src/getExpoPushTokenAsync.ts#L28-L30

> devicePushToken (DevicePushToken) -- The device push token with which to register at the backend. Defaults to a token fetched with getDevicePushTokenAsync().

The SDK upgrades didn't mention needing to configure a Firebase project to upgrade from the legacy notifications module, to `expo-notifications`, but the current docs for FCM Push make it clear that all Expo apps need it _unless_ they are running in Expo Go (which is why we couldn't repro the error in development).

> Firebase Cloud Messaging is required for all managed and bare workflow Android apps made with Expo, _unless you're still running your app in the Expo Go app_.

Finally found the spot in the docs where they mention it explicitly, too: https://docs.expo.io/push-notifications/push-notifications-setup/

> For Android, both managed and bare workflow users need to follow our FCM setup guide, it should only take about 5 minutes.

No idea why this wasn't flagged as a breaking change, unless we missed something previously and should have had this configured previously.

**Comment by classiebit** [comment]
@danprince  Thank you for your rapid response. And we've already FCM setup guide and also tried fetching DevicePushToken explicitly via getDevicePushTokenAsync but getting: "Fetching Token failed: FIS_AUTH_ERROR.

Actually, it was working fine before ejecting the Expo app to the Bare repo. And also, we published the previous Expo app via expo:build on Playstore & Appstore and the Push Notifications were working fine.

And it stopped working when we ejected to Bare app because we need to integrate Video Calling functionality.

We've done all these-
1. https://docs.expo.io/push-notifications/using-fcm/
2. Removed key restrictions from Google Developer Console.


Can you please tell us exactly what you did that resolved the issues. We're trying to fix this for 2 weeks straight. But no luck. Your help would be highly appreciated. 🙏 😢

**Comment by classiebit** [comment]
For now, we just removed the Key restrictions-
Application restrictions: none
API restrictions: Don't restrict 

And it's working fine. Bullshit!

**Comment by AtmasApps** [comment]
In case it may help olthers....

I ended up seeing a problem similar to this and it ended up being that I hadn't fully configured my Play Store app to have the proper keys in the app.json settings.

Once I did that, I then had to actually uninstall and reinstall the app from the play store. This part to me was very confusing, since I thought Google Play Store would automatically update it, but it wasn't.. Instead, the OTA updates were firing which WAS intrinsically updating the internal versions (i.e. Constants.manifest was apparently showing new numbers) which gave me the ILLUSION that the app was updating itself...

Unfortunately, it kept throwing the same issue (complaining about a project ID when attemping to get the pushToken asynch data)... I think what effectively happened was until I uninstalled and reinstalled the app from my Internal App link, I was still getting the OLD misconfigured original binaries that didn't have the proper keys set up....

So that was basically roundabout causing me to fail the step "Finally, make a new build of your app by running expo build:android." on https://docs.expo.dev/push-notifications/using-fcm/ -- In that, I was doing it, but the App Store wasn't actually pushing that down. (probably something I just need to learn how it works and do it right). In any case, the workaround of uninstalling and reinstalling fixed it.. Maybe some patience to actually have the published version update, too, on the Google Play side even for Internal Testing probably didn't hurt..

**Comment by kandurisv** [comment]
implementation 'com.google.firebase:firebase-iid:17.0.2' in your app build.gradle works.

**Comment by meedwire** [comment]
> 

this work in:
```
   "react-native": "0.66.1",
    "expo": "^43.0.5",
    "expo-notifications": "~0.13.3",
```

**Comment by brunolcarlos** [comment]
With expo 45 was working but expo 46 not

` WARN  [expo-notifications] Error encountered while updating server registration with latest device push token. [Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.]
 LOG  [Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.]`

**Comment by morganick** [comment]
I just hit my head on this as well going from Expo SDK 44 -> 45.

**Comment by Kaakans** [comment]
:+1: Didn't even upgrade. Still on 44, and did not update any packages.

**Comment by davidcort** [comment]
I loss all the day whit this issue. Expo 44 in the bare workflow :(

`Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;`

**Comment by davidcort** [comment]
> I loss all the day whit this issue. Expo 44 in the bare workflow :(
> 
> `Encountered an exception while calling native method: Exception occurred while executing exported method getDevicePushTokenAsync on module ExpoPushTokenManager: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;`

This issue only appears in Android. iOS go well.

Ok, I found a solution !!

1.- Take the WEB API KEY in the firebase in project configuration:
![Captura de Pantalla 2022-08-12 a la(s) 1 56 14](https://user-images.githubusercontent.com/6045573/184301115-803de06f-23af-4c02-a9ab-c5c840da95b4.png)

2.- Put the key of previous step into the google-services.json where say:  "api_key": [
        {
          "current_key": "WEB API KEY"
        }
      ]

3.- Add in the app/build.gradle file:
implementation 'com.google.firebase:firebase-iid:17.0.2'

4.- Sync the changes, select Build -> Clean Project.
5.- Clear the cache with command: expo r -c

And get the evil TOKEN   \ :v /

Object {
  "data": "ExponentPushToken[XXXXxxxxXXXXxxxx]",
  "type": "expo",
}

**Comment by noamkuMoDev** [comment]
I have a MANAGED project and I run it in the Expo GO app only.
Therefore according to documentation I do not need configure anything in Firebase, yet I still get this error when running the app on Android:
[Unhandled promise rejection: Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.]
at node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:106:50 in promiseMethodWrapper
at node_modules/expo-modules-core/build/NativeModulesProxy.native.js:21:23 in moduleName.methodInfo.name
at node_modules/expo-notifications/build/getDevicePushTokenAsync.js:15:29 in getDevicePushTokenAsync
at http://172.16.11.83:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in _getDevicePushTokenAsync
at http://172.16.11.83:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in getDevicePushTokenAsync
at node_modules/expo-notifications/build/getExpoPushTokenAsync.js:9:62 in getExpoPushTokenAsync
at http://172.16.11.83:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in _getExpoPushTokenAsync
at http://172.16.11.83:19000/index.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:null in getExpoPushTokenAsync
at managers/notificationsManager.ts:53:29 in registerForPushNotificationsAsync

In order to try and fix this I run "expo start -c --android" to make the android folder appear then opened a project in Firebase (with the exact same package name as in app.json) and followed the setup firebase required for android. Of course I added the google-services file at the root of my file. Added the path to it under "android" in app.json as well.
I made sure the auto-generated key in my cloud console is the same as the key in the google-services file.

All my code is taken directly from the expo documentation of expo notifications.
What am I doing wrong? How can I solve this?
SDK 46

**Comment by as1265513** [comment]
i am also ran into same  problem.

**Comment by maruthimaru** [comment]
I too facing same issue any solution?

[Unhandled promise rejection: Error: Fetching the token failed: Please set your Project ID. A valid Firebase Project ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.]

**Comment by othilacode** [comment]
I experienced the same issue with SDK 44. I tried to go to SDK45 but not worked. Is there a link with firebase cloud messaging API Legacy ?

**Comment by brunolcarlos** [comment]
The new Expo Go update fixed it!

Thank you

**Comment by othilacode** [comment]
you mean the v2.25.1 (deployed 2 weeks ago.?)

**Comment by brunolcarlos** [comment]
> you mean the v2.25.1 (deployed 2 weeks ago.?)

The version 2.25.2 fixed it

**Comment by othilacode** [comment]
it was that, Expo Go was not up to date. Thanks @brunolcarlos !

**Comment by brunolcarlos** [comment]
> it was that, Expo Go was not up to date. Thanks @brunolcarlos !

Sometimes the Google Play don't update for everyone, when your Expo Go update will fix it.

**Comment by ea1ik** [comment]
For anyone still looking for a solution with EAS Build, I had to do this (using Expo SDK 46)
In my root level build.gradle, I added this under dependencies
`classpath("com.google.gms:google-services:4.3.2")`
In app/build.gradle, add this at the end of the file
`apply plugin: 'com.google.gms.google-services'`

based on this s/o answer https://stackoverflow.com/questions/40081539/default-firebaseapp-is-not-initialized

**Comment by hislordshipprof** [comment]
> @classiebit We ended up doing the Firebase setup, which fixed things.
> 
> In the `expo-notifications` package [`getExpoPushTokenAsync`](https://docs.expo.io/versions/latest/sdk/notifications/#getexpopushtokenasyncoptions-expotokenoptions-expopushtoken) actually needs a `devicePushToken` (the one you get from Apple/Google) to work. If you don't pass one explicitly, it fetches it automatically.
> 
> https://github.com/expo/expo/blob/5e0a6bc252aa05e5fa5ea371169d01902ba6bb1a/packages/expo-notifications/src/getExpoPushTokenAsync.ts#L28-L30
> 
> > devicePushToken (DevicePushToken) -- The device push token with which to register at the backend. Defaults to a token fetched with getDevicePushTokenAsync().
> 
> The SDK upgrades didn't mention needing to configure a Firebase project to upgrade from the legacy notifications module, to `expo-notifications`, but the current docs for FCM Push make it clear that all Expo apps need it _unless_ they are running in Expo Go (which is why we couldn't repro the error in development).
> 
> > Firebase Cloud Messaging is required for all managed and bare workflow Android apps made with Expo, _unless you're still running your app in the Expo Go app_.
> 
> Finally found the spot in the docs where they mention it explicitly, too: https://docs.expo.io/push-notifications/push-notifications-setup/
> 
> > For Android, both managed and bare workflow users need to follow our FCM setup guide, it should only take about 5 minutes.
> 
> No idea why this wasn't flagged as a breaking change, unless we missed something previously and should have had this configured previously.

hi @danprince i am facing similar issues, i havent setup FCM yet but im able to get the token in my expo go app but doesnt get generated in standalone. using firebase will the generated token be stored over there or? also i am using laravel as backend do you have any idea i can send the device token that is saved in firebase to my backend?

**Comment by hislordshipprof** [comment]
> getDevicePushTokenAsync

Hi are you using any backend fort his or you are just using firebase? i have been able to set it up and send the notification via firebase to my app. but here i am using laravel as backend and i want to store the device token in the backend. any idea how to achieve that?
