### ISSUE TITLE
Black screen precedes splash screen upon  adding custom splash screen

### ISSUE THREAD

**Issue by danstepanov** [expo/expo#11968]
**Summary**

## Expected Behavior
Upon updating the app icon and splash screen assets to custom values based on [the docs](https://docs.expo.io/guides/app-icons/), I expect my custom loading screen to appear upon launch of the app on a physical device, followed by my app itself. 

## Actual Behavior
Upon adding a custom app icon and splash screen, a mysterious black screen precedes the custom splash screen. As more complexity is added to the app, the black screen's time on screen increases to upwards of 20-30 seconds. When running a published version of the app, it just crashes on initial launch. 

Videos for both experiences are available upon request. I'm in the Expo Discord under the name `childish danbino`.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

iOS

**SDK Version (managed workflow only)**

_No response_

**Environment**

Expo CLI 4.1.6 environment info:
    System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/danielstepanov/.rvm/gems/ruby-2.7.0-preview1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare

**Reproducible demo or steps to reproduce from a blank project**

I have created [a public repo](https://github.com/danstepanov/splashscreenBug) with only two commits (the first is just the initalized project after running `expo init splashscreenBug -t expo-template-bare-typescript` and the second after adding a custom app icon and splash screen). Just make sure to run on a physical device.

1. Clone the project
2. Select your own development team to run on a physical device
3. Build and run app on a physical device
4. Observe "black screen" -> "loading screen" -> "app"

**Comment by brentvatne** [comment]
> and the second after adding a custom app icon and splash screen

@danstepanov - can you detail how you did this?

**Comment by danstepanov** [comment]
@brentvatne I generated the images via https://appicon.co/, downloaded the image folders, copied and pasted the folder into xcode and replaced the existing app icon folder when prompted. For the splash screen, I followed the [video here](the docs) and created 2x and 3x versions in Sketch. I then deleted SplashScreen in image assets, renamed the "SplashScreenBackground" image asset folder to "SplashScreen", and deleted the View layer in the SplashScreen.storyboard. I changed the image link in the SpashScreenBackground View layer to use the "SplashScreen" image folder.

**Comment by danstepanov** [comment]
Does `yarn expo-splash-screen -p ios -i splash.png -b "#ffffff"` work for bare workflow?

**Comment by danstepanov** [comment]
After having run that command, I still get a brief black screen prior to my splash screen. Not sure what's happening but gonna submit to App Store anyway. Thanks for the help :)

**Comment by brentvatne** [comment]
@danstepanov - i'd revert those changes and then just use `yarn expo-splash-screen` instead. or you can remove expo-splash-screen if you prefer and just use the native splash screen directly. more information in https://github.com/expo/expo/blob/master/packages/expo-splash-screen/README.md

**Comment by reinink** [comment]
I can confirm that I also ran into this, and spent more hours than I'd like to admit trying to solve it, but wasn't able to. This only happens on iOS, not on Android.

**Comment by brentvatne** [comment]
@bbarthec maintains expo-splash-screen and is currently ooo for a couple weeks, he can look into it when he's back.

i would generally suggest avoiding making changes to the default splash screen related native files if you are going to use expo-splash-screen, and instead to follow the instructions in https://github.com/expo/expo/blob/master/packages/expo-splash-screen/README.md.

**Comment by chinieer** [comment]
same issue on ios 14

**Comment by matt-oakes** [comment]
The issue for me was that the image I was using was too large. Reducing the size, uninstalling the app, and restarting the device worked. See here: https://stackoverflow.com/questions/63978396/launch-screen-not-working-on-ios-14-with-xcode-12

**Comment by ajsmth** [comment]
I've been able to reproduce this fairly reliably at this point, here's what I've come up with: 

If you have the simulator running your app, and you add an image into Xcode, update the launch screen image via the Xcode inspector, and rerun the app - the simulator will not be aware of this image and instead displays an empty (black) screen. You have to restart the simulator and rebuild the app in order for the image to show up.

The time between the black screen and the splash screen image is an issue of configuration - e.g if you are seeing a black screen, Xcode is not configured properly. When the splash screen image appears, that is when the `expo-splash-screen` package takes over - we can't do anything about what is rendered before that time. 

This applies to a case where you might be  manually adding a new image to `Images.xcassets` - its better to keep Xcode closed in these cases and run  the `expo-splash-screen` config cli to properly set the image, or be aware that you will have to restart the simulator

If you never see an image, this must mean that there is something wrong with that image, could be the size of the image, or its not the right path to the image, etc. `expo-splash-screen` reads from the same path configured in your apps `Info.plist`, and in this case both are not able to find it. 

Through my brief experiments I ran into a couple of times where I had to restart Xcode just because. This probably contributes to some of the other issues like increased load times or apps not loading at all, often a restart of Xcode is the fix.

One other quick note: iOS 14 allows developers to drop launch screen storyboards all together - this is something we could update in `expo-splash-screen` at some point as the API is somewhat simpler. Here is a good reference for how to do that: https://useyourloaf.com/blog/dropping-launch-storyboards/

In any case, it might be helpful to write an  FYI doc or update the splash-screen docs to highlight these common pitfalls in case it's happening to a lot of people 


Lastly, I've messaged @danstepanov to follow up with the videos he's mentioned

**Comment by ajsmth** [comment]
for future reference: https://expo.fyi/black-screen-before-splash
