### ISSUE TITLE
[iOS] `pod install`: Invalid `Podfile` file: uninitialized constant Pod::Podfile::Expo.

### ISSUE THREAD

**Issue by huynguyen-n** [expo/expo#1200]
I have go throught the `Set Up` section from REAME.md, after that I try to run Expo client on my phone also follow the intrustion from you guys but I stucking on `pod install` with the detail messages like below:

`[!] Invalid `Podfile` file: uninitialized constant Pod::Podfile::Expo.`
` #  from /users/../expo-master/ios/Podfile:135`
 `#  -------------------------------------------`
 `#        'RCTWebSocket',`
`            Expo,ExpoOptional`
` #      ]`
 `#  -------------------------------------------`

**Comment by fxfactorial** [comment]
Hi, what platform are you on, version of SDK and version of exp. thanks!

**Comment by huynguyen-n** [comment]
Hi @fxfactorial,

SDK version is "1.4.0" and exp is "24.0.0". By the ways, I just run the JS packager by yarn but with npm it's can't with the bug is: "ENOENT: no such file or directory, open '.../expo-master/js/node_modules/react-native/packager/transformer.js'"

**Comment by brentvatne** [comment]
@terribleben - sorry for pinging, don't know how to solve this

**Comment by terribleben** [comment]
@huynguyen-n it sounds like you are trying to build Expo Client from source, is that correct?

- Just curious, what are you working on that requires you to do this? :) 
- Can you paste the full contents of your `Podfile` here?

**Comment by mogwai** [comment]
@kostimarko This worked for me but I also needed to add single quotes to the line

```
if target.pod_name == '#{EXPO_CPP_HEADER_DIR}'
```

**Comment by terribleben** [comment]
Hey all, it looks like some people have recently seen a symptom similar to, but different from, this issue.

1. The solution posted by @kostimarko is not related to the original issue from January, so I am going to change the title of this issue to stop conflating the two problems.
2. If you run into this message because you are missing the constant `EXPO_CPP_HEADER_DIR`, then you should define that constant, i.e. by adding this code to your Podfile:
```
EXPO_CPP_HEADER_DIR = 'ExpoKit'
```
3. Please avoid the "solution" of switching from double quotes to single quotes. This doesn't actually solve the problem, it just causes Ruby to stop trying to resolve `EXPO_CPP_HEADER_DIR`, so it won't complain any more. The best idea is to follow my recommendation.

Sorry for the trouble!
