### ISSUE TITLE
error: index.js: Transformer.transform is not a function

### ISSUE THREAD

**Issue by kevgrig** [expo/expo#12014]
**Summary**

After ejecting, starting Android Studio, starting `react-native start` in another terminal, and clicking Play in Android Studio to run and debug the app, the app launches in the Android emulator and starts to load from Metro but that errors with `error: index.js: Transformer.transform is not a function`

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

bare

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

_No response_

**Environment**

```
$ expo diagnostics

  Expo CLI 4.1.6 environment info:
    System:
      OS: Linux 5.10 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.15.4 - /usr/bin/node
      Yarn: 1.22.10 - /usr/bin/yarn
      npm: 6.14.10 - /usr/bin/npm
    SDKs:
      Android SDK:
        Android NDK: 22.0.7026061
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: bare
```

**Reproducible demo or steps to reproduce from a blank project**

1. `expo init my-project`
1. `cd my-project`
1. `expo eject`
1. `react-native start`
1. Start Android Studio
1. Click Play to run in an emulator (Pixel 3a API 30 x86)
1. Metro shows:
   ```
   [Mon Feb 22 2021 19:08:26.412]  BUNDLE  ./index.js 
   
   error: index.js: Transformer.transform is not a function
   ```

I feel like this used to work.

I'm running on Fedora Linux 33 Workstation (all the latest patches). So then I tried to see if I can reproduce this problem on a vanilla Fedora Linux install, so I created a Fedora VM, installed expo, Android Studio, etc., but I ran into a [crash in libOpenglRender.so](https://issuetracker.google.com/issues/180946604) (even though creating non-Android nested VMs works fine) so I can't try to reproduce this.

I tried deleting node_modules and running npm install as per [this issue](https://stackoverflow.com/questions/62794709/react-native-index-js-transformer-transform-is-not-a-function) but it didn't help.

So there's a chance something is wrong about my particular machine, but the basic question is: how do I investigate this issue? Is there some tracing? Should I try to re-install something or clear some caches?

My workaround is to create release builds through Android Studio and then manually install them but that's obviously a huge pain.

![Screenshot_1614049709](https://user-images.githubusercontent.com/6432587/108797983-75866c80-7541-11eb-88b6-668164d0cc33.png)

**Comment by byCedric** [comment]
Hi @kevgrig, thanks for writing in! At first glance, this seems like something is up with your project dependencies.

- You might be [running into this issue](https://github.com/facebook/react-native/issues/29301#issuecomment-662967508), where somehow metro (React Native bundler) and the configuration are out of sync (using incompatible versions). I'm not sure how, but this shouldn't happen with a fresh ejected project.

- Another thing in your screenshot that strikes me as "interesting" is that it's trying to load files from `jest-worker`. This should only be used when running Jest, not Metro. So that might be another area to look into.

Maybe it's a conflicting global dependency that's messing up your project, or at least causing the out-of-sync config. I would recommend removing any global `@react-native-community/cli` libraries, and even try reinstalling `expo-cli` and/or Node.

But without us being able to reproduce this, I'm not sure how we can help you further on this. If you can reproduce it in a docker environment, that would also be helpful.

Hope this helps!

**Comment by kevgrig** [comment]
Thanks @byCedric. Fully uninstalling expo-cli and Node and reinstalling worked.
