### ISSUE TITLE
[expo-payments-stripe] In Managed workflow, setOptionsAsync method crashes Android in APK

### ISSUE THREAD

**Issue by StarNeit** [expo/expo#12028]
**Summary**

I installed "expo-payments-stripe": "~8.0.0" for stripe payment integration.
It works like charm very well in the local development environment by running `expo start`.

But, after build APK using `expo build:apk`, the APK crashes with `setOptionsAsync()`

I am using managed workflow now, and my purpose is just building android APK.

But it doesn't work.

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Android

**SDK Version (managed workflow only)**

36

**Environment**

I used Expo managed workflow and SDK 36

**Reproducible demo or steps to reproduce from a blank project**

import {PaymentsStripe as Stripe} from "expo-payments-stripe";

 useEffect(() => {
    Stripe.setOptionsAsync({
      publishableKey: 'pk_test_aXXXXXXXXX',
      androidPayMode: 'test', // [optional] used to set wallet environment (AndroidPay)
    });
  }, []);

**Comment by mihir254** [comment]
same issue

**Comment by Cloudyrl** [comment]
Did you find a fix for this?

**Comment by marmagzzz** [comment]
I am still experiencing this issue on SDK 40.

**Comment by cruzach** [comment]
Hi! Since the expo-payments-stripe module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the @stripe/stripe-react-native library work seamlessly in Expo projects, so we recommend you use that library instead. Learn more in the API reference, and check out this excellent YouTube video that walks through integrating Stripe in your Expo app. Thanks!
