### ISSUE TITLE
"Linking" and "homepage" causes unwanted redirect 

### ISSUE THREAD

**Issue by tesla-cat** [expo/expo#12057]
**Summary**

in package.json: "homepage": "/SI",
in App.tsx: "const prefixes = [Linking.createURL('https://tesla-cat.github.io/SI/')]"
but when you visit "https://tesla-cat.github.io/SI/", the url is changed to "https://tesla-cat.github.io/tabs/home", this causes 404 when refreshing the page!

**Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!**

managed

**What platform(s) does this occur on?**

Web

**SDK Version (managed workflow only)**

_No response_

**Environment**

  Expo CLI 4.2.1 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.18.2 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Users\e0134117\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.5 - D:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 23, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64
    npmPackages:
      expo: ~40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2  
      react-native-web: ^0.15.0 => 0.15.0
    Expo Workflow: managed

**Reproducible demo or steps to reproduce from a blank project**

in package.json: "homepage": "/SI",
in App.tsx: "const prefixes = [Linking.createURL('https://tesla-cat.github.io/SI/')]"
but when you visit "https://tesla-cat.github.io/SI/", the url is changed to "https://tesla-cat.github.io/tabs/home", this causes 404 when refreshing the page!

in package.json: 
```javascript
"homepage": "/SI"
```
in App.tsx: 
```javascript
const prefixes = [Linking.createURL('https://tesla-cat.github.io/SI/')]
```
but when you visit "https://tesla-cat.github.io/SI/", the url is changed to "https://tesla-cat.github.io/tabs/home", this causes 404 when refreshing the page!

**Comment by byCedric** [comment]
Hi @tesla-cat, I'm not sure if I understand your issue here. It doesn't look like it's related to `Linking`, instead, it seems like you have 2 errors in the configuration:

1. I see you are using a subpath `SI` in your Expo web app, once you build the web app you also need to define this subpath if you use it. (See [this docs page](https://docs.expo.io/distribution/publishing-websites/#creating-a-build), under tips)

2. I think the path `tabs/home` comes from React Navigation. Double-checking the [documentation from React Navigation](https://reactnavigation.org/docs/configuring-links), about web URLs might be good.

So, why the "page not found" error when you refresh? It's because React Navigation rewrites the URL locally, with anything you configure it (see point 2). If you want to use this, you have to enable rewriting every call to the `index.html`. With this, you can use any path and React Navigation will determine what page it must render. See [this stack overflow thread](https://stackoverflow.com/a/59677657/2277025) on how to do that.

Hope this helps!

**Comment by tesla-cat** [comment]
hi @byCedric , thank you for the help.

- I **did** follow your first tip as said in the original question. I added to `package.json` the following before running `expo build:web`:

```javascript
"homepage": "/SI"
``` 

- My **1st issue** is that:
    - When I visit https://tesla-cat.github.io/SI, I can indeed see the desired home screen. 
    - However, this url gets **automatically** changed to https://tesla-cat.github.io/tabs/home after page load
    - This is the **issue**, because I expect it to change to https://tesla-cat.github.io/SI/tabs/home instead! Although this also is problematic, see **2nd issue**
- **2nd issue**:
    - I read about [the stack overflow thread](https://stackoverflow.com/a/59677657/2277025) and added `404.html` to `web-build` folder, as can be seen here: https://github.com/tesla-cat/tesla-cat.github.io/tree/master/SI
    - But the **issue** is that visiting https://tesla-cat.github.io/SI/tabs/home gives the **Github 404** page, even visiting https://tesla-cat.github.io/SI/404.html gives the **Github 404** page as well

**Comment by byCedric** [comment]
Per statement:

- 1st issue
  - Yes, because GH pages is loading the `SI/index.html` (which should exist)
  - That's because React Navigation (for web) is handling this. It hits the default page, which is configured to that URL. 
  - To configure it to `SI/tabs/home`, please [refer to their documentation](https://reactnavigation.org/docs/configuring-links/#mapping-path-to-route-names).
- 2nd issue
  - I can't see the `404.html` or `web-build` folders in your repo, but I'm not familiar with GH pages.
  - If you can't get the `index.html` or `404.html` pages to work, please [refer to their community](https://github.community/) to get help.

Because these issues aren't related to Expo itself, I'll close this issue. Good luck solving the last parts of your website!
