### ISSUE TITLE
Equivalent of Deployment Devices = iPhone (not Universal) when building for iOS

### ISSUE THREAD

**Issue by ryanhomer** [expo/expo#1206]
I've read issue #131 and #965 as well as testing my Expo-based app on an iPad and it seems to me that the app is being built as a Universal app. Wondering if there were changes by Apple regarding this, I just tried creating an iPhone-only app with Xcode 9.2 targeting iOS 11 and ran it on the iPad Pro 12.9" simulator. It showed the app in iPhone-compatible mode with the 1x/2x toggle.

I'm therefore guessing, and would like to confirm, that it's not possible to build an Expo app for iOS with true iPhone-only, non-Universal support without ejecting it. Is this the case?

The issue is that apps designed for iPhone only, stretched to fit a 12.9" screen is not necessarily better than the iPhone-compatible 1x/2x mode and some assets, like background images will need to be much larger than was initially procured.

I think it's quite important to properly support true iPhone-only mode to help developers starting off with a new app. It's hard to put effort in to support everything and the kitchen sink when you're trying to publish version 1.0.

Thanks in advance for any light you can shed on this.

**Comment by terribleben** [comment]
Adding the `supportsTablet: false` key under `ios` causes us to build `deviceFamily` as iPhone-only: https://github.com/expo/xdl/blob/master/src/detach/IosNSBundle.js#L347-L348

This will only show up in a standalone build, not in Expo client, since it's configured at the native level.

If you think there's an issue with that, can you take a look at the embedded `Info.plist` in your Expo app (created with `exp build:ios`) and see what it says for `UIDeviceFamily` ?

**Comment by ryanhomer** [comment]
@terribleben I'll need to get more details from the team member responsible for building/submitting the app.

In the meantime, however, that link looks like it has to do with detach. I'm trying to find out if it's possible to **not** detach an app and have it build with `UIDeviceFamily` set to `1` (iPhone). Are you saying that with `supportsTablet: false`, it is indeed possible to submit an app to the App Store built with `UIDeviceFamily` set to `1` without having previously detached the app?

**Comment by terribleben** [comment]
> In the meantime, however, that link looks like it has to do with detach.
The code in that link is used on both standalone apps created with `exp build:ios` and in ExpoKit apps. (at a low level they share much of the same code.) Our server runs that method while generating your build for you.

Try adding `supportsTablet: false` under `ios`, making a simulator build with `exp build:ios -t simulator`, and opening the resulting `.app` on an iPad simulator. If the behavior isn't what you expect, let me know, and see if you can check the value of `UIDeviceFamily` in that build.

**Comment by ryanhomer** [comment]
Thanks for the info @terribleben. The binary generated for the App Store did have `UIDeviceFamily` set to `1` and after installing it via Test Flight on an iPad, it does open in iPhone mode with the 1x/2x button. This is exactly what I was hoping for.

> exp build:ios -t simulator

I just tried this, downloaded the completed build and tried to install via Xcode but keep getting:
`The application does not have a valid signature.`

Not sure what I need to do to resolve this. If you could point me in the right direction, I'd appreciate that.

Thanks for all your help!

**Comment by terribleben** [comment]
The simulator build won't be signed, and the recommended way of installing it would be

1. Make sure you have Simulator already running
2. Go to a terminal and navigate to the same directory as the `.app`
3. Run `xcrun simctl install booted YourApp.app`

It won't launch but it should appear as an icon on the Simulator home screen.

**Comment by ryanhomer** [comment]
Silly me trying to install a simulator build on a device! I just wasn't thinking. Thank you for your assistance. I'm all squared away now.

**Comment by fedealconada** [comment]
Hey @terribleben @ryanhomer, I'm facing a similar problem. What I don't get is the following: if I set `supportsTablet: false`, am I supposed to be restricting people to even find the app on the store if they are using an iPad?

**Comment by ryanhomer** [comment]
I don't think this would restrict them from finding the app but it would probably be listed as an iPhone app and it would be up to the user to know that it can still be installed on an iPad but run in "iPhone" mode.

**Comment by outaTiME** [comment]
@fedealconada I'm using SDK31 in standalone mode and `supportsTablet: false` is not restricting the app to be iPhone-only (it will set `UIDeviceFamily` as `1`), I'm using a custom `infoPlist` section, I'm afraid it may be conflicting with `UIDeviceFamily` generated by `supportsTablet: false`.

I hope @terribleben can shed light on this since I need to target only iPhone.

´´
"ios": {
  "bundleIdentifier": "foo",
  "buildNumber": "1",
  "icon": "./assets/icons/app-icon.ios.png",
  "infoPlist": {
    "CFBundleDevelopmentRegion": "es",
    "NSLocationWhenInUseUsageDescription": "Esta aplicación necesita acceder a su ubicación para verla reflejada en nuestro sistema y/o mostrarla en el mapa.",
  },
  "supportsTablet": false,
  "config": {
    "usesNonExemptEncryption": false
  }
},
´´

(New code from xdl here: https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/IosNSBundle.js#L360)
