### ISSUE TITLE
Expo sdk doesn't recognize `.expo` extension when bundling for web

### ISSUE THREAD

**Issue by whitestranger7** [expo/expo#12074]
### Summary

When I try to use file with `.expo` extension, it works fine for mobile, but web runs file without extension.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

40

### Environment

System:
      OS: macOS 11.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 30.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.1.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Reproducible steps:
1. create bare expo project with typescript template
2. create `App.tsx` and `App.expo.tsx`
3. start expo bundle and see that in web there would be `App.tsx` loaded instead of the one with `.expo` extension.
4. start expo bundle and see that on ios simulator `App.expo.tsx` would be loaded

**Comment by brentvatne** [comment]
this is intended behavior, .expo was only meant to work for native ios and android.

further, we are deprecating the .expo extension and it will no longer be loaded in sdk 41+ projects

**Comment by whitestranger7** [comment]
Hey, @brentvatne. We're in [Kitten Tricks](https://github.com/akveo/kittenTricks) project using both expo bundling and bare RN application bundling. Now when we're switched to sdk 40 - we're faced the problem with `.expo` extensions that we used commonly in the application logic.

Maybe you can recommend some approach regarding our case? It seems odd that old feature has no backwards-compatibility or some counter solution)

**Comment by brentvatne** [comment]
the .expo extension continues to be loaded on sdk < =40 projects for ios and android. on sdk >= 41 it will not work. we never included the .expo extension on expo web projects.

the .expo extension should continue to work just fine in your project. if it doesn't, it may be due to a custom metro.config.js file that doesn't extend `@expo/metro-config`. we configure the .expo extension with the `sourceExts` property in the app metro config, and if you provide your own config that overrides our default then the extension won't be included. you can extend the `@expo/metro-config` to ensure that it's included: https://docs.expo.io/guides/customizing-metro/

for libraries, this doc explains some alternatives: https://github.com/expo/fyi/blob/master/expo-extension-migration.md

the `try/catch` around import alternative only became possible in react-native 63 and may not work on all projects due to it being included in a mid-cycle react-native cli upgrade that enabled it. more info on this feature in the proposal here https://github.com/react-native-community/discussions-and-proposals/issues/120. to ensure that this works on any version of react-native we have done stuff like this in other libraries: https://github.com/react-native-async-storage/async-storage/commit/aca9af97cc63dc258426aa2d223474f59aac3920. 

but in your case, it looks like you're only interested in making this work in your app. optional imports will work on sdk 40, so you can wrap the `require` in try/catch and use whichever module is available. for example, you can combine `web-browser.service.ts` and `web-browser.service.expo.ts` into one file:

```
import { Linking, Platform } from 'react-native';

export class WebBrowserService {
  // other code

  private static openInAppUrl = (url: string): Promise<any> => {
    try {
      const SafariView = require('react-native-safari-view').default;
      return SafariView.isAvailable()
                       .then(() => SafariView.show({ url }));
    } catch {
      const WebBrowser = require('expo-web-browser');
      return WebBrowser.openBrowserAsync(url);
   }
  };

  // other code
}
```
