### ISSUE TITLE
Adding more common native modules

### ISSUE THREAD

**Issue by jadbox** [expo/expo#1208]
Hello folks,
Most of my projects require the below native modules. Is there any chance to getting them into Expo soon? Thanks!
```
react-native-http, 
react-native-level-fs, 
react-native-os, 
react-native-randombytes,
react-native-tcp, 
react-native-udp
```

**Comment by terribleben** [comment]
Hey there! To get these APIs shipped with the Expo core SDK, probably the best thing to do is track these as a feature request on [canny](https://expo.canny.io/feature-requests) (or upvote them if they're already there). In the meantime another option is to detach to [ExpoKit](https://docs.expo.io/versions/latest/expokit/index.html) in order to gain control over the native code in your project and link them yourself.

For http requests I imagine the recommendation would just be to use the `fetch` API. For `fs` I think you can just import that without any native dependencies. Expo also has its [own FileSystem API](https://docs.expo.io/versions/latest/sdk/filesystem.html#content).

What kind of projects are you building that require os, randombytes, tcp and udp?

**Comment by brentvatne** [comment]
curious to hear more about why you want these libs, if you can post to forums with more info or on canny (as ben mentioned) that would be great
