### ISSUE TITLE
Notifications.requestPermissionsAsync has the wrong return type

### ISSUE THREAD

**Issue by special-character** [expo/expo#12191]
### Summary

`Notifications.requestPermissionsAsync()` does not return the [PermissionResponse](https://docs.expo.io/versions/latest/sdk/permissions/#permissionresponse) type. Specifically, the `status` field is a number and not one of the expected values of "granted", "undetermined", or "denied". The `Notifications.getPermissionsAsync()` function does return the correct response.

An example of a response from `Notifications.requestPeremissionsAsync()`:
```
{
  "status": 2,
  "ios": {
    "allowsSound": null,
    "allowsCriticalAlerts": null,
    "allowsAlert": null,
    "allowsDisplayInNotificationCenter": false,
    "allowsDisplayOnLockScreen": false,
    "allowsDisplayInCarPlay": null,
    "providesAppNotificationSettings": false,
    "allowsAnnouncements": null,
    "allowsBadge": null,
    "alertStyle": 0,
    "status": 0,
    "allowsPreviews": 2
  }
}
```

expected:
```
{
  "status": "granted",
  "canAskAgain": true,
  "ios": {
    "allowsSound": true,
    "allowsCriticalAlerts": null,
    "allowsAlert": true,
    "allowsDisplayInNotificationCenter": true,
    "allowsDisplayOnLockScreen": true,
    "allowsDisplayInCarPlay": null,
    "providesAppNotificationSettings": false,
    "allowsAnnouncements": null,
    "allowsBadge": true,
    "alertStyle": 1,
    "status": 2,
    "allowsPreviews": 2
  },
  "expires": "never",
  "granted": true
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 3.25.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.15.4 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.14.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.3 
      react-native: 0.63.2 => 0.63.2 

### Reproducible demo or steps to reproduce from a blank project

I can't use a snack because Notifications only work on device.

**Comment by brentvatne** [comment]
this documentation shows how to treat status: https://docs.expo.io/versions/latest/sdk/notifications/#getpermissionsasync-promisenotificationpermissionsstatus

it is indeed a bit different from `PermissionsResponse` on `expo-permission` - we're in the process of deprecating this library (it will be as of sdk 41) and permission responses will generally follow a similar format to that but may vary where it makes sense to do so. in the case of notifications, `granted`, `denied`, and `undetermined` don't capture the range of possible statuses:

https://github.com/expo/expo/blob/c45a6dac2c555a5ea6c1a75e7d421cd401c11009/packages/expo-notifications/src/NotificationPermissions.types.ts#L15-L21

this is pretty easy to use if you use typescript but i can understand it is confusing otherwise.

@cruzach - we should clarify docs around this, it looks like we don't document the `NotificationPermissionsStatus` type.

**Comment by special-character** [comment]
I used the docs you linked when I was working on this but they should be updated because they don't match what you linked for `IosAuthorizationStatus`. 

We use TS but it has incorrect types so it is confusing. Reading the docs and using TS both point to the response having `status` that is one of the `PermissionStatus` values.

It is typed as returning [NotificationPermissionStatus](https://github.com/expo/expo/blob/master/packages/expo-notifications/src/NotificationPermissions.types.ts#L23) which extends the PermissionResponse from the permissions module.

**Comment by brentvatne** [comment]
definitely something we should improve the docs for, thanks for calling it out

**Comment by cruzach** [comment]
fixed in https://github.com/expo/expo/commit/c481a5c58341aa2751f8da4b27b014d5191305dc, thanks again @special-character ! let me know if that clarifies things for you

**Comment by special-character** [comment]
Thanks for the help, this was all cleared up! I am using the correct status on the iOS object now
