### ISSUE TITLE
npm 5 not yet supported

### ISSUE THREAD

**Issue by birendra-90** [expo/expo#1230]
When will be update with npm 5*

**Comment by jimmylee** [comment]
Hey @birendra-90 welcome to Expo!

Long story short: **We don't have a timeline for when NPM5 will work with Expo.**

There are some open issues on the NPM repo that currently affect how NPM installs dependencies compared to NPM 4.  When NPM is fixes those issues, NPM 5 (or future versions) will work with Expo.

Sorry about that, closing this issue since theres nothing we can do right now.
