### ISSUE TITLE
[Android][Detached] expolib_v1.okhttp3.OkHttpClient incompatibility

### ISSUE THREAD

**Issue by James2516** [expo/expo#1231]
On a detached Expo app, it has integration issues with many other native modules due to the `okhttp3` library.
> Error:(54, 55) error: incompatible types: expolib_v1.okhttp3.OkHttpClient cannot be converted to okhttp3.OkHttpClient

See https://github.com/expo/expo/issues/561

Demo: https://github.com/James2516/expo-native-nav/tree/fetch-blob
Try run the project in Android Studio.

**Comment by dooboolab** [comment]
@James2516 
Home this [Link](https://forums.expo.io/t/stuck-on-upgrading-sdk-24-for-android/5902/9) helps you solve the problem. I've had the same problem and I've fixed many of those one by one.
It happens in expo sdk 24 for android detached app only. Works ok in ios.

**Comment by faustoct** [comment]
@James2516 got the same problem. Any progress?

**Comment by faustoct** [comment]
@dooboolab how did you solve.. looking the link didn't find any related issue..

**Comment by faustoct** [comment]
this is my workaround
> in all imports referenced by `okhttp3` I replaced by `expolib_v1.okhttp3`

It worked. It's not the best solution but is working as supposed to.

https://github.com/wkh237/react-native-fetch-blob/issues/481#issuecomment-358820091

**Comment by jesseruder** [comment]
This is a tricky problem for us to solve. I understand it's a big issue but don't have a great solution right now. Replacing the imports should work as a temporary fix.

**Comment by faustoct** [comment]
@jesseruder I don't know how often it happens. There are proxy-libs written in Java that's suppose to solve that easily. This approach would solve at runtime instead compiling time.

**Comment by AdamJNavarro** [comment]
Hey @James2516,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam

**Comment by gsunsnackv** [comment]
This issue still exists. For me it is the react-native-video package . There is another issue for that https://github.com/expo/expo/issues/2298

**Comment by FakhruddinAbdi** [comment]
Also, the issue still exists for me with the react-native-fast-image package.
I can not replace all `okhttp3` by `expolib_v1.okhttp3` because I have an import like this: 

`import com.bumptech.glide.integration.okhttp3.OkHttpUrlLoader;`
 and `expolib_v1.okhttp3` doesn't expose `OkHttpUrlLoader`
So if you update the rest of the `okhttp3` it will give you compatibility issue.

**Comment by raul-madrigal** [comment]
@FakhruddinAbdi check my last comment here https://github.com/DylanVann/react-native-fast-image/issues/249

**Comment by tncbbthositg** [comment]
@raul-madrigal, I don't think I'd consider that a solution per se.  This issue still exists in the react-native-fast-image package; just not in your fork.  

IMO, this should still be fixed in DylanVann/react-native-fast-image so that when additional updates are released, ejected expokit apps can take advantage of them.  If everyone on expokit makes their own fork, it somewhat defeats the purpose of sharing the package to begin with.
