### ISSUE TITLE
How to remove WatchPositionAsync

### ISSUE THREAD

**Issue by KatancicDenisz** [expo/expo#12326]
I have trouble removing the `watchPositionAsync` function.

```
  const [watchId, setWatchId] = useState(null);

  useEffect(() => {
    (async () => {
      let tmp1;
      if (tourStarted) {
        try {
          tmp1 = await Location.watchPositionAsync(
            {
              accuracy: Location.Accuracy.High,
              distanceInterval: 1,
              timeInterval: 1,
            },
            (pos) => {
              setLocation({ coords: pos.coords });
            }
          );
          setWatchId(tmp1);

        } catch (e) {
          Alert.alert("Error", { e });
        }
      } 
    })();

    return () => {
      if (!tourStarted) {
        if (watchId) {
          console.log("before.", watchId);
          let res = watchId.remove();
          console.log("after ", res);
          //setWatchId(res)
        } 
      }
    };
  }, [tourStarted]);
```
When I'm priting out `console.log("before.", watchId);`, I get a `Object {
  "remove": [Function remove],
}`, and after the `watchId.remove();`, I get undefined if I log it out. 
Should I get undefined or am I doing something wrong?

**Comment by byCedric** [comment]
Hi @KatancicDenisz, this issue is related to how hooks work when using references in methods. Basically, you are "depending" on `watchId`, while the method in your `useEffect` hook isn't reinitialized whenever that state variable changes. When updating the state, your method isn't updated with the new state value.

You might be able to work around that by either splitting the `useEffect` into multiple methods. Or use a `useRef`, which isn't tied to the methods.

Hope this helps!
