### ISSUE TITLE
AV/Sound volume up/down controls call instead media when playing sound via andorid earpiece

### ISSUE THREAD

**Issue by louxinbo** [expo/expo#12331]
### Summary

After setting Audio mode: playThroughEarpieceAndroid: true, when playing audio, the volume button controls call volume instead of media volume.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

  Expo CLI 4.3.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 15.5.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ^40.0.0 => 40.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Reproduce steps: 
1, Set audio mode playThroughEarpieceAndroid: true
2, Play an audio
3, Adjust the volume 
Relevant discussion: https://forums.expo.io/t/av-sound-volume-up-down-controls-call-instead-media/46366

**Comment by JorgeMoV** [comment]
Hello, I have the same problem here in bare project in Android. I am very desperate, I have been trying to fix this without success for weeks.

I really appreciate any information to any official developer or anyone who has any solutions.

I have the property playThroughEarpieceAndroid: true, and the volume up and down control controls the call volume and not the media volume. Because of this, the sound comes out of the phone's earpiece, but it does not go up or down.

I need to keep the playThroughEarpiece property active to have the sound through the earpiece, but I also need to be able to turn the volume up and down while listening through the phone earpiece.

Does anyone know how to get this?

Any way to fix this bug?



As a hint, I have verified that if I press the volume buttons continuously, since before the playback starts, then the sound is heard through the telephone earpiece and the affected volume is the medium volume instead of the call volume, and it increases and decreases.

Any ideas? Thanks.

**Comment by JorgeMoV** [comment]
In case the same thing happens to someone else, I managed to implement a solution using this component:
https://github.com/c19354837/react-native-system-setting

Simply if you need to have the audio active through the upper earpiece and you also need the volume up and down to work. So, if the audio affected is in-call when pressing the volume buttons, this is detected by an in-call volume listener and an automatic media volume increase or decrease is performed, both operations using the component indicated above.
