### ISSUE TITLE
Playback routed to phone receiver when recording

### ISSUE THREAD

**Issue by riwu** [expo/expo#1236]
[Expo docs](https://docs.expo.io/versions/latest/sdk/audio.html#allowsrecordingios--a-boolean-selecting-if-recording-is-enabled-on-ios-this-value-defaults-to-false-note-when-this-flag-is-set-to-true-playback-may-be-routed-to-the-phone-receiver-instead-of-to-the-speaker):
> allowsRecordingIOS : a boolean selecting if recording is enabled on iOS. This value defaults to false. NOTE: when this flag is set to true, playback may be routed to the phone receiver instead of to the speaker.

Why route playback to phone receiver when recording? 
Is it possible to implement some sort of noise cancellation in which the audio recorder ignores the playback the phone is playing, so that recording can be done clearly without routing playback to receiver?

**Comment by sjchmiela** [comment]
## Why route playback to phone receiver when recording?

`allowsRecordingIOS` is translated to `AVAudioSessionCategoryPlayAndRecord` on the native side, which according to [Apple's documentation](https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryplayandrecord) is:

> The category for recording (input) and playback (output) of audio, such as for a VoIP (Voice over Internet Protocol) app.

And since VoIP involves calling people, iOS may assume that with this category set a user wishes to raise the phone to his ear and use the receiver speaker and microphone this way.

## Is it possible to implement some sort of noise cancellation in which the audio recorder ignores the playback the phone is playing, so that recording can be done clearly without routing playback to receiver?

In the way that *noise cancellation* works I don't think so. **That's why playback may be routed to the phone receiver**—so the sound coming from the receiver doesn't interfere too much with the recorded sound (which unfortunately, depending on the volume of the playback, nonetheless happens, try https://snack.expo.io/B1a84WIEG).

Noise cancellation would require either native support (which neither of the supported OSes provide) or real-time Audio API in Expo for you to implement some sophisticated noice cancellation algorithm (which we also don't have at the current moment).

Feel free to reopen this issue and follow up with more questions if my response didn't answer your question. 🙂
