### ISSUE TITLE
Audio not able to pause on Android

### ISSUE THREAD

**Issue by RenierDev** [expo/expo#12442]
### Summary

I’ve ran into an issue where the audio I’m playing can’t be paused again after it starts playing.

During development all works fine, it’s only after the build process when this happens. Haven’t tried building iOS to verify that it’s only Android giving this issue, but building for web doesn’t produce this bug.

Both stopAsync() and unloadAsync() fail to actually stop the playing audio. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

40

### Environment

Expo CLI 4.3.4 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 12.19.0 - ~/node-v12/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.8.0 - ~/node-v12/bin/npm
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.3.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

I have a snack setup with a play button to demonstrate my issue.

https://snack.expo.io/@reniermyburgh/stream_player

you will find it working, but once you build for android it no longer stops the music once you press play.

**Comment by AdamJNavarro** [comment]
Hey @RenierDev, thanks for providing a snack but in this instance we would want a public github repo we can quickly clone and then build. Copy and pasting code from snack increases the opportunity for user error.

Your code is a little difficult to reason about. Having functions and functional components with the same name should be avoided. Also, I'd recommended using a boolean value instead of a string for your `isPlaying` state. Lastly, if you're only intending to pause a sound you should not call `unloadAsync`. I would strongly suggest taking a look at the Playlist example we have in our [docs](https://docs.expo.io/versions/v40.0.0/sdk/av/) to see how to reason about AV modules.

Could you please provide the aforementioned github repo link if you can reproduce the issue after taking a look at the playlist repo and making the changes I mentioned?

Cheers,
Adam

**Comment by RenierDev** [comment]
Hi @AdamJNavarro - sorry for the delayed response.

Thank you for the feedback and for taking the time to look at my code. As per your request I have put together a public repo with some changes to my code based on your advice, namely:
- I changed the name of the function inside the functional component to just 'play'
- Changed my state variable to a boolean
- replaced the unloadAsync with stopAsync

Unfortunately those did not sort the issue out, although I am thankful for the feedback as you did point out some bad practice I will try to avoid in the future.

The thing to note in this particular case, is that there is only one file, and it is never 'paused', since it is essentially a live stream where instead of pausing, it should be stopped. Once playback is resumed, the track plays from the present, not from where the user last stopped. Hope I'm explaining that alright.

The repo: https://github.com/RenierDev/StreamPlayer

If the above repo is run via Expo in development, it works as intended. As soon as I build for Android, the track can't be stopped, as mentioned in the original post.

Thanks again for having a look at my issue. I would so love to implement this player using Expo, as every other aspect of it is a great pleasure, it's only this play/pause issue that's holding me back.

Thanks in advance!
