### ISSUE TITLE
unable to read file with FileSystem.readAsStringAsync on IOS

### ISSUE THREAD

**Issue by pabeda-bt** [expo/expo#1245]
Hello,

I'm trying to read a jpg file that saved in applicaition with FileSystem.readAsStringAsync

I'm getting this error : 

![image](https://user-images.githubusercontent.com/15822986/34884862-1fae8ae2-f7cf-11e7-8ae6-de24e42ae16a.png)

Here is my code : 
```
FileSystem.readAsStringAsync(uri).then(function(data) {
            console.log(data);
});
```
I'm sure that uri is correct and JPG file exists.
This error occues only on IOS, android works great. Can you help me plese? What I am doing wrong?

**Comment by nikki93** [comment]
right now `.readAsStringAsync(...)` is only for text files readable as strings, while .jpg files are binary files. so this isn’t supported yet. :(

**Comment by rayj10** [comment]
@nikki93 Hi Nikki, just stumbled across this issue, and I posted on [Expo Forum](https://forums.expo.io/t/how-to-use-expos-filesystem-properly/11987) already about my use case which is similar to this OP.
just wondering what should I use instead if I want to save an image to my app instead of camera roll?

thanks in advance :)
