### ISSUE TITLE
AV interferes with other audio playing on iOS

### ISSUE THREAD

**Issue by reinhardholl** [expo/expo#12613]
### Summary

When playing audio through another library (in our case `react-native-track-player`) starting an `expo-av` sound kills all audio first. 

From what I can see the issue is on line 168 of `EXAudioSessionManager`. 

```
if (!shouldBeActive && _sessionIsActive) {
    [session setActive:NO error:&error];
    if (!error) {
      _sessionIsActive = NO;
    }
  }
 ```
When initiating an expo-av sound/video after another library has started using `AVAudioSession` iOS throws the following error: 

>Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

From my understanding you don't have to deactivate the audio session to change the category, and by the looks of the code that was the intention here. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

bare

### Reproducible demo or steps to reproduce from a blank project

Implement another library that uses the underlying `AVAudioSession`. Start playing a sound through this library then initiate an expo-av sound.

**Comment by AdamJNavarro** [comment]
Hey @reinhardholl, could you please create a public repo with a simple implementation/reproduction of this issue? Being able to quickly clone and test this helps greatly in our debugging efforts and expedites the support process!

Cheers,
Adam

**Comment by reinhardholl** [comment]
@AdamJNavarro will try put something together for you.

**Comment by Cixelyn** [comment]
fwiw, we're also running into this issue. Specifically, we're using FMOD for sound handling instead of expo-av's Audio class. However anytime a `<Video>` component is unmounted (even if `isMuted={true}`), all FMOD audio is killed app-wide.

Best guess is that since Expo assumes it's the only app controlling the AVAudioSession sharedInstance; it calls `[session setActive:NO]` when it detects all its own modules have finished playing sound.

Our current workaround is to just comment out the above lines mentioned by @reinhardholl via the following [patch-package](https://www.npmjs.com/package/patch-package) so that ExpoAV will never attempt to deactivate the session

```diff
diff --git a/node_modules/expo-av/ios/EXAV/EXAudioSessionManager.m b/node_modules/expo-av/ios/EXAV/EXAudioSessionManager.m
index e1f7012..f8af874 100644
--- a/node_modules/expo-av/ios/EXAV/EXAudioSessionManager.m
+++ b/node_modules/expo-av/ios/EXAV/EXAudioSessionManager.m
@@ -174,12 +174,12 @@ UM_REGISTER_SINGLETON_MODULE(AudioSessionManager);
   // If the session ought to be deactivated let's deactivate it and then configure.
   // And if the session should be activated, let's configure it first!
 
-  if (!shouldBeActive && _sessionIsActive) {
-    [session setActive:NO error:&error];
-    if (!error) {
-      _sessionIsActive = NO;
-    }
-  }
+  //  if (!shouldBeActive && _sessionIsActive) {
+  //    [session setActive:NO error:&error];
+  //    if (!error) {
+  //      _sessionIsActive = NO;
+  //    }
+  //  }
 
   if (error) {
     return error;
```

It would be nice to indicate to Expo-AV that some external code is using the shared audio session (in addition to it's own tracked `_foregroundedModules`) so that it doesn't shut it down prematurely.

**Comment by bbarthec** [comment]
Some changes in the following packages that may fix this issue have just been published to npm under `next` tag 🚀

| 📦 Package | 🔢 Version | ↖️ Pull requests | 📝 Release notes |
|:--:|:--:|:--:|:--:|
| [expo-av](https://www.npmjs.com/package/expo-av/v/11.1.0) | 11.1.0 | #16578 | [CHANGELOG.md](https://github.com/expo/expo/blob/main/packages/expo-av/CHANGELOG.md) |

If you're using bare workflow you can upgrade them right away. We kindly ask you for some feedback—even if it works 🙏

They will become available in managed workflow with the next SDK release 👀

Happy Coding! 🎉
