### ISSUE TITLE
How can implement paypal using expo am new in expo development 

### ISSUE THREAD

**Issue by githubmss** [expo/expo#1267]
Is it possible to implement paypal,  razorpay and payumoney payment gateway implementation using expo?
Please give me knowledge about this thing....Thanks in advance

**Comment by ccheever** [comment]
Hi-

This is a good question for the forums! 
If you ask your question here, the community will give you an answer: https://forums.expo.io/

In general, you probably need to "detach" your app and then `react-native link` in native libraries that support those things. This will be a little tricky for a new developer but it can be done. Good luck!

**Comment by githubmss** [comment]
Can u please make proper procedure how to detach ..

**Comment by ide** [comment]
The documentation on detaching is here: https://docs.expo.io/versions/latest/guides/detach.html. Be sure to read "Should I detach?" and if you decide to do so, to carefully follow the instructions. From the docs:

**Should I detach?**

You might want to detach if:
- Your Expo project needs a native module that Expo doesn’t currently support. We’re always expanding the Expo SDK, so we hope this is never the case. But it happens, especially if your app has very specific and uncommon native demands.

You should not detach if:
- All you need is to distribute your app in the iTunes Store or Google Play. Expo can build binaries for you in that case. If you detach, we can’t automatically build for you any more.

- You are uncomfortable writing native code. Detached apps will require you to manage Xcode and Android Studio projects.

- You enjoy the painless React Native upgrades that come with Expo. After your app is detached, breaking changes in React Native will affect your project differently, and you may need to figure them out for your particular situation.

- You require Expo’s push notification services. After detaching, since Expo no longer manages your push certificates, you’ll need to manage your own push notification pipeline.

- You rely on asking for help in the Expo community. In your native Xcode and Android Studio projects, you may encounter questions which are no longer within the realm of Expo.

---

After detaching, you may find these docs helpful: Developing in a detached app with ExpoKit - https://docs.expo.io/versions/latest/guides/expokit.html
