### ISSUE TITLE
[Typescript] Permissions types issues

### ISSUE THREAD

**Issue by yordis** [expo/expo#1273]
From the oficial code snippet

```js
import { Constants, Notifications, Permissions } from 'expo'

// Example server, implemented in Rails: https://git.io/vKHKv
const PUSH_ENDPOINT = 'https://expo-push-server.herokuapp.com/tokens'

export default (async function registerForPushNotificationsAsync() {
  // Remote notifications do not work in simulators, only on device
  if (!Constants.isDevice) {
    return
  }

  // Android remote notification permissions are granted during the app
  // install, so this will only ask on iOS
  const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS)

  // Stop here if the user did not grant permissions
  if (status !== 'granted') {
    return
  }

  // Get the token that uniquely identifies this device
  const token = await Notifications.getExpoPushTokenAsync()

  // POST the token to our backend so we can use it to send pushes from there
  return fetch(PUSH_ENDPOINT, {
    body: JSON.stringify({
      token: {
        value: token,
      },
    }),
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    method: 'POST'
  })
})
```

```
  const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS)
error TS2345: Argument of type 'string' is not assignable to parameter of type 'PermissionType'.
```

```
  const token = await Notifications.getExpoPushTokenAsync()
error TS2339: Property 'getExpoPushTokenAsync' does not exist on type 'typeof Notifications'.
```

**Comment by sjchmiela** [comment]
Hi! We don't provide Typescript typings at the moment, sorry! 🙁 Does your TS schema come from our Flow typings, or some third-party repository, like:

- https://github.com/janaagaard75/expo-and-typescript/blob/master/src/expo.d.ts
- https://github.com/PavelPZ/rw4/blob/master/typings/expo.d.ts
- https://gist.github.com/pierre-H/eef9a9225fb1c5a0f81180a8b0fbb2c2

(I got them all from https://github.com/expo/expo/issues/37)

All in all, the typings you use are outdated.

`Permissions.askAsync(Permissions.NOTIFICATIONS)` bug is fixed in the first link (see [line 1358](https://github.com/janaagaard75/expo-and-typescript/blob/master/src/expo.d.ts#L1358)).

All the links have outdated definitions of `Notifications`, [`getExponentPushTokenAsync()`](https://github.com/janaagaard75/expo-and-typescript/blob/master/src/expo.d.ts#L1311) has been renamed to `getExpoPushTokenAsync()`.

**Comment by yordis** [comment]
@sjchmiela i just install `@types/expo` which I am guessing it is just this one https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/expo

I am curious about it, does that means the Expo team will no support the type checking? 

I know you said you don't provide but will your provide it?

**Comment by sjchmiela** [comment]
The typings you've linked have the bugs I mentioned earlier — `Permissions.NOTIFICATIONS` is typed as `string` and there still is a `getExponentPushTokenAsync` method defined. I would recommend posting similar issue on the [DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped) or even better… submitting a pull request there! 💪

We use [Flow](https://flow.org) for type checking. There is [an open issue](https://github.com/expo/expo/issues/37) regarding TypeScript support on our repo. See this comment: https://github.com/expo/expo/issues/37#issuecomment-295357969. 🙂

**Comment by yordis** [comment]
@sjchmiela I would love to do a PR if I know Expo SDK and the internals.

To be honest, the core contributors should own this one. Nothing more secure than the creator of the package maintain the typespec (again it is not just about TS bug the tooling around it). 

Let see, hopefully we get your support on #37 sooner.

Cheers,

**Comment by sjchmiela** [comment]
@yordis, PR fixing this would consist of 2 lines. 🙂 (But while you'd be at it you could fix types for the rest of the permission types as well.)

Fix would include:

1. Changing types of permission categories from `string` to `PermissionType` in [line 1268](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/expo/index.d.ts#L1268):
   ```ts
   // before:
   const NOTIFICATIONS: string;
   // after:
   const NOTIFICATIONS: PermissionType;
   ```
2. Renaming `getExponentPushTokenAsync` to `getExpoPushTokenAsync` in [line 1216](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/expo/index.d.ts#L1216):
   ```ts
   // before
   function getExponentPushTokenAsync(): Promise<string>;
   // after:
   function getExpoPushTokenAsync(): Promise<string>;
    ```

**Comment by ide** [comment]
The Expo SDK is currently annotated with Flow types. I don't think there's a way to cleanly annotate code with both Flow and TypeScript, so TypeScript definitions need to be separate anyway. At this time I don't think we'd keep TS declarations always up-to-date and it's better served as a community responsibility.

**Comment by yordis** [comment]
@ide if your job and business model is to maintain a SDK and tools that support the technology, I do not share your point of view of pushing anything to the community, specially that `responsibility` is a big word

Think for a moment as Expo CTO and pretend that I am potential client that will give you the opportunity to keep running your company and grow up.

You are suggesting that I will get no support from you because I am using Typescript, once again, it is not just about Typescript but the tooling and the ecosystem around it what it is really valuable over Flow.

Basically should be your focus, as today, maintain and improve the experience of Mobile development and React ecosystem. Make it so simple and `convenience` that I shouldn't be thinking on roll with my own setup.

That is what companies will you for anyway right? Right?!

I hope that is valuable for you and Expo team, I hope everything goes on your way so you can keep supporting and helping business. Sadly a business is a business when make money and I really want you to succeeded (isn't it about money but what money allow you to do, like hire more people for improve the quality and scale)

That is why @sjchmiela isn't about me copying pasting but observing why should I do that when Expo business is about support https://expo.io/support 

P.S: you probably don't know about it but my team is 1 step away from go paid service with you (probably we are one of the early one for the full service) so definitely this is something I expect you to take ownership as a company.

**Comment by ide** [comment]
Hi @yordis - We (the Expo team) care about building a platform that people trust and helping developers get to good places. Part of building trust is setting expectations and following through on them and we'd prefer to be honest and commit to supporting things we're going to do well. We want developers who use Expo to be able to rely on us for those things -- like improving & maintaining the Expo client, having stable services for publishing and notifications, and incrementally adding new APIs to the Expo SDK. I try to be honest and to set expectations fairly to help developers anticipate when they may need to do more work, like writing TypeScript declarations.

Realistically, we have to prioritize our work and often say "no" or "not now" to many things people would like us to work on. Some people would like us to maintain TypeScript declarations, some would like ReasonML, and others would like ClojureScript. All of these technologies provide value --
 most do -- and frankly we need to decide holistically where to spend time and choose a set of priorities that altogether grow the Expo community and platform.

Looking at type declarations, we currently use Flow because that's what React Native and many React projects use. There are several appealing things about TypeScript but one thing I care about within Expo is sustainable software development so we can reliably follow through on expectations we've set with developers. Because we use Flow, the TypeScript declarations would need to live in separate files, dispersing two things (the code and the type declarations) that are intrinsically related. I think if we were to provide TypeScript support, we'd consider changing our source files to .ts and dropping the Flow declarations instead to manage our priorities.

Our support plans offer a closer channel to the Expo engineering team for when you might find a bug or need guidance when stuck. The support plans aren't saying that the Expo team will build features for you (with exceptions for special partnerships that would probably be a lot more than the basic and professional plans). So, writing, maintaining, and testing TypeScript declarations generally wouldn't be something we'd do as part of support. That said, we're really happy to see that several developers have contributed to the DefinitelyTyped declarations and in general want to give developers the agency to use Expo with TypeScript and other technologies even if the Expo team can't support all of them.

I hope this explains some of our viewpoints and sets expectations around TypeScript better. Even if you may disagree with some of our choices, I hope you can understand what we're working to accomplish.

**Comment by fxfactorial** [comment]
FWIW: I have started Expo bindings to ReasonML here: https://github.com/fxfactorial/bs-expo

**Comment by yordis** [comment]
@ide sounds good, now at least I know the details about the paid services.

Also I don't see where ReasonML and ClojureScript are coming from. 

I dont care about Typescript as a language but the set of tools that most of the Javascript engineers are building around it, specially with the type system.

But forget about it,

I got the memo.
