### ISSUE TITLE
[docs] AppLoading example uses deprecated properties

### ISSUE THREAD

**Issue by radoncreep** [expo/expo#12789]
### Summary

the props of this API (startAsync, onFinish, onError) appears deprecated on usage
But the documentation has no update on its new props 

### Link to the related docs page
https://docs.expo.io/versions/latest/sdk/app-loading/#props

_No response_

**Comment by byCedric** [comment]
Hi @radoncreep! Thanks for mentioning this, we should add it to the docs. Because we had some issues in the past with errors not surfacing, it's best that you handle this yourself. Here is an example of how that could [look like this Snack](https://snack.expo.io/@bycedric/spunky-ramen). By doing this yourself, you have full control over possible errors. 😄

**Comment by radoncreep** [comment]
Thank you @byCedric , i checked out the snack and it looks like it isn't supported on android

Currently building for android.

**Comment by microQZR** [comment]
Hi there, any progress on updating the docs? Because having the docs state "The following props are recommended", but those same props turn out to be marked as deprecated, kinda gives off an unease feeling..

**Comment by AkoNis** [comment]
> Hi there, any progress on updating the docs? Because having the docs state "The following props are recommended", but those same props turn out to be marked as deprecated, kinda gives off an unease feeling..

agree, the docs led me astray aswell

**Comment by joshuahigginson1** [comment]
Any update on this ticket?

**Comment by I2oy** [comment]
This issue is on the verge of being closed, but it still persists. I was a bit confused at first what is the supposed updated approach to using AppLoading as I'm new to Expo. After seeing the snack provided above from @byCedric, it helped clear it up. Would love to see an example like that add to the docs.

**Comment by ayyam** [comment]
[expo AppLoading startAsync Deprecated. what is the alternative?](https://stackoverflow.com/questions/71508154/expo-apploading-startasync-deprecated-what-is-the-alternative)

Please update

**Comment by hnazarparvar28782** [comment]
Please follow the pattern code below:
===============================================


import * as Font from 'expo-font';
import AppLoading from 'expo-app-loading';
import React ,{useState}from 'react';

export default function App() {
const [fontLoading,setFontLoading]=useState(false);
   
  Font.loadAsync( {
    yekan:require("./myapp/fonts/byekan.ttf"),
    ih:require("./myapp/fonts/ih.ttf")
      }
  ).then( () => setFontLoading('true') )
  
  
      if (!fontLoading){
       return(
         <AppLoading/>);
      
        } else{
          return(
         do someting.....
         ............
          ) 
}    ](url)

**Comment by michael-gates-techngs** [comment]
Please update

**Comment by Simek** [comment]
`AppLoading` is deprecated and its example probably won't be updated. 

The deprecation notice includes suggestion of how to migrate to `SplashScreen` methods, see the usage in there:
* https://docs.expo.dev/versions/latest/sdk/splash-screen/#usage
