### ISSUE TITLE
[docs] Inconsistent return types for getAllScheduledNotificationsAsync between docs and types

### ISSUE THREAD

**Issue by davidshepherd7** [expo/expo#12795]
### Summary

The [documentation for `getAllScheduledNotificationsAsync`](https://docs.expo.io/versions/v41.0.0/sdk/notifications/#getallschedulednotificationsasync-promisenotification) says that it returns `Promise<Notification[]>` but the types say that it will return `Promise<NotificationRequest[]>`.

As far as I can tell it does actually return `Promise<NotificationRequest[]>`, at least on android. Is that expected? I was hoping for an easy way to find out the datetime that a given notification will fire, which `Notification` provides but as far as I can tell `NotificationRequest` doesn't. I think I can use `getNextTriggerDateAsync`, but that will only get me the next time and not any future times.

### Link to the related docs page

https://docs.expo.io/versions/v41.0.0/sdk/notifications/#getallschedulednotificationsasync-promisenotification

**Comment by cruzach** [comment]
This will be fixed once we migrate this docs page over to being auto-generated from TS, which I will start work on soon. 

> I was hoping for an easy way to find out the datetime that a given notification will fire

the `NotificationTrigger` is returned as part of `NotificationRequest`, so you should know the time a notification will fire based off of that, I think (depending on the trigger type)

**Comment by masarbazi** [comment]
Hello after 3 years👋, I'm trying to get all scheduled notifications and having some problem with return types of this method.
As @cruzach said we should be able to know find out about notification trigger time depending on trigger `type` property!, but the problem is with the `DateTriggerInput` as part of the `SchedulableNotificationTriggerInput` union type. 
`DateTriggerInput` type: 
```typescript
export type DateTriggerInput =
  | Date
  | number
  | { type: SchedulableTriggerInputTypes.DATE; channelId?: string; date: Date | number };
....
// SchedulableNotificationTriggerInput which eventually gets asserted to NotificationRequest trigger property
export type SchedulableNotificationTriggerInput =
  | CalendarTriggerInput
  | TimeIntervalTriggerInput
  | DailyTriggerInput
  | WeeklyTriggerInput
  | MonthlyTriggerInput
  | YearlyTriggerInput
  | DateTriggerInput;
```
as you see there are two `Date` and `number` types which don't have `type` property and cause typescript not to have it on `SchedulableNotificationTriggerInput` and makes `type` property pointless. ://
shouldn't Date and number be removed?
