### ISSUE TITLE
[snack] ESLint parsing error when using property of type in TypeScript

### ISSUE THREAD

**Issue by TurtleWolfe** [expo/expo#12819]
### Summary

Just starting the default tabbed template, pushing it to a repo, and then pulling that into a snack, I get an error unexpected token

![Screenshot from 2021-05-04 20-36-43](https://user-images.githubusercontent.com/7327259/117087202-c58d6680-ad1c-11eb-8f7b-5ede4f6f60c1.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.4.3 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 14.16.1 - /usr/bin/node
      Yarn: 1.22.5 - /usr/bin/yarn
      npm: 7.11.1 - /usr/bin/npm
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.4.3
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

expo init FortyOne --npm
cd FortyOne
git remote add origin https://github.com/TurtleWolfe/FortyOne.git
git push --set-upstream origin main

**Comment by byCedric** [comment]
Hi @TurtleWolfe! Thanks for reporting this, it seems like this is an issue with the built-in ESLint version. The app is still rendered as you would expect on web, but this parsing error shouldn't be there. I think this might be related to the fact that the eslint community mostly focuses on `@typescrit-eslint` instead of `@babel/eslint-config` (cc @IjzerenHein). We probably need to bump a few dependencies to get this working.
