### ISSUE TITLE
[docs] Linking module strings are slightly wrong

### ISSUE THREAD

**Issue by quicksnap** [expo/expo#12830]
### Summary

Within https://docs.expo.io/guides/linking/#linking--module, the URLs for some of the results do not match what is documented in source. The actual code does what the code documentation states

### Link to the related docs page

https://docs.expo.io/guides/linking/#linking--module

### Anything else?

I'd be happy to update the docs if it seems appropriate! 

Thanks! Expo is amazing so far!

**Comment by quicksnap** [comment]
Particularly, "development" should be `exp://128.0.0.1:19000/--/`

**Comment by brentvatne** [comment]
hey @quicksnap! the url depends on how it's loaded. it may be 128.0.0.1 or localhost. that said, most people will end up seeing `127.0.0.1` or some network ip, so i think it's reasonable to change to that.

for the `/--/` bit - this is actually only added if you pass in a param to `Linking.makeUrl()`:

- `Linking.makeUrl()`: `exp://127.0.0.1`
- `Linking.makeUrl('/')`: `exp://127.0.0.1/--/`

so this part is correct, since the docs say:

> you can call `Linking.makeUrl()` and it will resolve to the following:

**Comment by quicksnap** [comment]
That makes sense. It is sort of confusing to me as a newcomer regarding the `/--/` aspect. I was trying to set up some login links for testing, and was initially just trying to use `exp://127.0.0.1:19000/MyRoute/`. Debugging external links resolving isn't fun =P

Think there's something worth adding in the docs for this?

**Comment by brentvatne** [comment]
@quicksnap - yeah we can add something to this page to clarify that better - i believe it was here before, perhaps it somehow was removed in an iteration of this docs page.

**Comment by quicksnap** [comment]
https://github.com/expo/expo/pull/12843 Is up. Happy for anyone to adjust the verbiage in the PR. Thanks!
