### ISSUE TITLE
Expo android app taking too much time in loading app

### ISSUE THREAD

**Issue by rastogitech** [expo/expo#1285]
I'm using expo android client from play store on Nexus 5x and expo ios app on iPhone 5S. Using both with same project on window-10, I observer that reloading app on android app takes too long time, the progress loader doesn't show correct progress on expo android client well, it doesn't load instant code changes on android app. But on iPhone expo app, it works awesome!!

Npm: 4.2.0
Node: 7.10.1
Expo: '^23.0.4'
React: 16.0.0
React-native: 0.50.3
React-native-cli: 2.0.1
O/S: Windows-10

**Comment by terribleben** [comment]
Hi there, I recommend checking the following:

- Does your device have a good internet connection? What about your computer?
- Is your project being served over LAN or tunnel? Tunnel is usually slower.
- Are you using `<AppLoading />` or downloading any large assets in your project which might increase load time? Have you tried [caching them](https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html)?
- Does your project's packager have a cache or is it bundling your project from scratch?
- Are you using any dev tools like Debugging or Hot Module Reloading? If so, what happens when you turn them off?

This is most likely an issue with one of the above, rather than an issue with Expo, so I'm going to close this. Let us know here or on the [forums](https://forums.expo.io) if you're still running into trouble.
