### ISSUE TITLE
"Default Activity Class Name" for Android?

### ISSUE THREAD

**Issue by snordgren** [expo/expo#1295]
I'd like to add the Facebook SDK to my project, and in the Quick Start for Android wizard it asks me for my default activity class name. Since I'm not writing the Java code for the app, I don't know which activity is the default one. Looking through the AndroidManifest.xml of my generated APK it seems that `host.exp.exponent.experience.ShellAppActivity` is the entry point activity, but there is also a `host.exp.exponent.MainActivity` which undoubtedly *looks more like* a main activity.

The documentation didn't help me here. What should I enter as my "default activity class name"?

**Comment by raphaelrk** [comment]
Would also appreciate this so that I can submit my app to Facebook for review. Did you figure this out @snordgren ?

<img width="982" alt="screen shot 2018-02-07 at 12 47 01 am" src="https://user-images.githubusercontent.com/3377845/35906708-7572a2d0-0ba0-11e8-90db-65e8f7e57ed2.png">

<img width="939" alt="screen shot 2018-02-07 at 12 48 15 am" src="https://user-images.githubusercontent.com/3377845/35906756-9dcfa5ac-0ba0-11e8-80f9-0a59b88fe72e.png">

**Comment by tommytcchan** [comment]
Same here looking for the same answer.

**Comment by kusaeva** [comment]
`host.exp.exponent.MainActivity` works for me

**Comment by nicknovitski** [comment]
As kusaeva says, `host.exp.exponent.MainActivity` should handle links from the Facebook app.

**Comment by gwalshington** [comment]
It's looks like it's  required to put a Class Name - this answer should be listed in the docs: https://docs.expo.io/versions/latest/sdk/facebook#add-hostexpexponent-as-an-ios-bundle-id

**Comment by spyshower** [comment]
@gwalshington Oh thanks for linking to the docs... So helpful.
/jk

**Comment by gwalshington** [comment]
@spyshower no problem. thanks for taking the time to leave a rude comment! It’s very helpful as well :)
