### ISSUE TITLE
Upgrade to exp 48.0.2 doesn't take changes into account anymore

### ISSUE THREAD

**Issue by PiTiLeZarD** [expo/expo#1306]
G'day,

I was happily building my apps with 47.1.2 and it tells me to upgrade to 48.0.2. I do and my next build doesn't build anything. On my side the exp build:android went super fast and it built something with the same code as the previous version.

I cleared all caches watchman, npm, exp and all: same story, it just doesn't get to that step "Building Android bundle".

I went back to 47.1.2 and it seems to work as expected, I have another error but I'll open another ticket for this.

I've seen similar errors with iOs in other tickets, sorry in advance if I'm doubling up you can trash this ticket.

Cheers

**Comment by ewein** [comment]
I'm having the same issue with 48.0.2, my changes are not taking affect after doing a `exp build:ios`

**Comment by fxfactorial** [comment]
@PiTiLeZarD @ewein Hi folks, have you tried with `--publish`? `exp build:ios --publish`?

**Comment by ewein** [comment]
Yeah that fixed it for me.

**Comment by PiTiLeZarD** [comment]
@fxfactorial yup, now it's building, is that an intended change? What's the goal of exp build:android without --publish? I'm just asking out of curiosity you can close that issue.

I'm just left with the other issue now (#1307 it builds but doesn't upload) ;)

**Comment by fxfactorial** [comment]
Its partially to conceptually separate out the idea of publishing the JS part of your app & publishing a binary, standalone update.

**Comment by fson** [comment]
Hi everyone! Because the new `--publish` flag for `exp build` has caused a lot of confusion, we've reverted back to the previous default behavior in the latest release (`exp@49.0.1`). Running `exp build:ios` will now automatically publish the app and there's no `--publish` flag anymore. You can just run `exp build:ios` and get an iOS app with the latest code.

For advanced use cases, we've added a new `--no-publish` flag that disables automatic publishing, if you want to manage JS releases separately using `exp publish`.

Sorry about the confusion!
