### ISSUE TITLE
Must update Facebook SDK for iOS

### ISSUE THREAD

**Issue by yuliankarapetkov** [expo/expo#13070]
I see the following message in Events Manager in Facebook Business:

> Your app is out of date. To run your app on iOS 14, update to the latest Facebook SDK for IOS.

My Expo version was `38.0` so I updated it to `39.0` but couldn't continue to `40.0` or `41.0` because there were too many errors caused by backward incompatible changes. For this reason I also updated `expo-facebook` to version `11.1.1`. However, I'm still seeing this warning in the Events Manager. 

How can I fix this? Isn't updating `expo-facebook` enough or is updating Expo to version `41.0` my only solution?

**Comment by cruzach** [comment]
You need to upgrade your SDK version to get the updates for native iOS facebook SDK in the managed workflow

**Comment by filipepratalima** [comment]
I have a side question, currently running SDK42 as the same updating to 43-44 brings in too many incompatible changes to our project. 
Does the expo-facebook in sdk42 support Limited Login mode? actually the opposite so to use the classic login mode with tracking, because currently everything I do it still seems to default to Limited Login, which won't give us an AccessToken for following GraphQL requests.
