### ISSUE TITLE
ios.supportsTablet not respected

### ISSUE THREAD

**Issue by sonaye** [expo/expo#131]
After publishing an app to the store with the configuration:
```
{
  "ios": {
    "supportsTablet": false
  }
}
```
users with ipads can still have access to the app. Isn't this supposed to not happen?

![fullsizerender](https://cloud.githubusercontent.com/assets/23000873/25428607/f685d846-2a7e-11e7-9cf7-3c9c97b8a13a.jpg)

**Comment by terribleben** [comment]
Hi, if your app targets iPad then it will have this message:
![image](https://cloud.githubusercontent.com/assets/1316332/25446115/5882aad4-2a65-11e7-8b04-b44607b5fe83.png)

I'm pretty sure all apps that target any recent iOS version will show the message you pasted, because they will technically _open_ on an iPad, they just won't have a special layout. (they will appear at iPhone resolution, scaled up.)

**Comment by sonaye** [comment]
All clear now, just wanted to double check. I will verify this once i get my hands on an iPad as well and confirm here. Thanks!
