### ISSUE TITLE
Facebook audience network switch to bidding

### ISSUE THREAD

**Issue by th96sayfo** [expo/expo#13185]
### Summary

Facebook audience network has switched to bidding only. How do we update expo managed workflow apps using expo-ads-facebook to make apps use bidding (mediation)? Please I need help with this one, this is a serious issue, I'm using facebook audience to make money from my apps, without this issue being fixed, I won't be able to earn money

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41

### Environment

Expo CLI 4.4.1 environment info:
System:
OS: Windows 10 10.0.17763
Binaries:
Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 4.1.0.0 AI-201.8743.12.41.7042882
npmPackages:
expo: ^41.0.0 => 41.0.0
react: 16.13.1 => 16.13.1
react-dom: 16.13.1 => 16.13.1
react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
react-native-web: ~0.13.12 => 0.13.18
Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

For iOS: https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/get-started/
For Android: https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/android/get-started/

**Comment by AbdnhVmpr** [comment]
I'm facing the same problem

**Comment by cruzach** [comment]
Can you explain how this relates to Expo? From [Facebook's guide](https://www.facebook.com/business/help/242842500123926), it looks like this is done on your end

**Comment by AbdnhVmpr** [comment]
This is related to Expo because:
Expo uses an old version of Facebook Audience SDK (6.2.1), the ads don't work because all apps must use the latest version (https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/android/add-sdk) which means that everytime facebook audience updates its sdk, the ads will not work until expo uses the latest version available

The Expo SDK and to expo-ads-facebook package have to be upgraded in order to use mediation in our apps

**Comment by cruzach** [comment]
Thanks for explaining @AbdnhVmpr !
