### ISSUE TITLE
Disable/remove IDFA tool(s) from Expo project

### ISSUE THREAD

**Issue by nikasvan** [expo/expo#1320]
I am submitting react native(expo) project to app store. I got to the step where I am told that my app uses IDFA and I had to tick some boxes so that I can confirm that I am using them which in fact is not true. From research I found out that expo uses analytics tools like Segment and Amplitude which is built in.

I would really prefer to say that I am not using the IDFA and I do not plan to use it in at all. How can I disable IDFA usage in my binary?

**Comment by nikasvan** [comment]
Also, interested what kind of information is sent from my app to Segment(or Amplitude)? I would not like to send sensitive or private information with or without users approval.

**Comment by terribleben** [comment]
Hey there, this is a good question.

- We collect anonymous usage statistics through Amplitude which aren't specific to your app and help us figure out how people are using Expo, as covered [here](https://expo.io/privacy).
- By default there is no data being sent to Segment at all, unless you use the [Segment](https://docs.expo.io/versions/latest/sdk/segment.html) API in your app for your own purposes.

Even though no Segment calls are made by default, since the code is statically present in your binary that _could_ run Segment, you still need to check the IDFA boxes listed in our [guide](https://docs.expo.io/versions/latest/guides/app-stores.html#ios-specific-guidelines).

Right now we don't offer a way to omit this Segment code from your app. Long term we'd like to build a way to do this, but we haven't yet. We haven't heard of anybody running into any trouble for this, so the easiest path forward is to just check the boxes during submission. If this is a dealbreaker for you, then you might not be able to use Expo for your app right now. We are tracking this as a [feature request](https://expo.canny.io/feature-requests/p/configurable-standalone-builds), so please upvote that.

**Comment by nikasvan** [comment]
Thanks for the answer @terribleben
