### ISSUE TITLE
Constants.installationId has been deprecated in favor of generating and storing your own ID

### ISSUE THREAD

**Issue by adarshkhatri** [expo/expo#13249]
### Summary

Installed `expo-firebase-analytics` and now it is throwing this alert: 

> Constants.installationId has been deprecated in favor of generating and storing your own ID. Implement it using expo-application's androidId on Android and a storage API such as expo-secure-store on iOS and localStorage on the web. This API will be removed in SDK 44.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

41.0.1

### Environment

Expo CLI 4.5.1 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312
    npmPackages:
      expo: ^41.0.1 => 41.0.1
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ^0.63.0 => 0.63.4
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Follow the blog: https://blog.expo.io/using-firebase-analytics-with-expo-222ca84e4d33

**Comment by byCedric** [comment]
Hi @adarshkhatri! Thanks for mentioning this. It's correct that we warn for this because this might affect a lot of apps. We haven't fully migrated all of our modules to not use this anymore. We will do so before fully removing this functionality though.

For now, you can ignore this warning [by using one of these options](https://stackoverflow.com/a/37083525/2277025).

Hope this helps!

**Comment by IjzerenHein** [comment]
@byCedric what is the plan for `installationId`, to remove it when SDK 44 hits?

**Comment by appsgenie** [comment]
Hi @byCedric, I am one of the bad users that ignored the warning until now when SDK 51 finally removed `Constants.installationId` 😅 

Do you know if there is an official suggested replacement? Looking for the exact same functionality. 
Or where in the expo source code could I find the previous implementation that maybe I could copy (not sure if this is possible in the managed flow)?

My main goal is to know where the existing `installationId` is being stored on the device so that existing clients can keep the existing ID during the upgrade. This way reporting is not affected by a completely new set of IDs for all users..

Thank you in advance for any suggestions on this topic 🙏
