### ISSUE TITLE
Images produced from takePictureAsync are much larger on iOS after SDK 25 update

### ISSUE THREAD

**Issue by ewein** [expo/expo#1324]
Images taken on iOS with takePictureAsync and SDK 25 are much larger than they were on SDK 24. They are now around 10 mb in size where before they were around 5-6 mb.

**Comment by aalices** [comment]
@ewein yes that's true - before we did not support the highest possible resolution by mistake. So the file size is bigger because the resolution is higher. However, if you find this as a problem please upvote here: https://expo.canny.io/feature-requests/p/capturequality-prop-for-camera-component - this is a request to have a prop for quality of taken pictures (high/medium/low).
