### ISSUE TITLE
Run detached app in Expo?

### ISSUE THREAD

**Issue by NdozHH** [expo/expo#1325]
Hello, is it possible to run a detached application in Expo using QR scanning, or after detached the application can only run on one device?

**Comment by nikki93** [comment]
One usually detaches so that their app can call native functions they provide in the native side of the code that aren't normally available in the Expo client app. Are you asking if Expo's QR code reader could open your own native app? If not, (and you want to open your app within the Expo home app) ould you plan on guarding those features in your application so that they are only used if the detached version is run?

**Comment by themakerman** [comment]
@nikki93 hey nikihilesh.... I have a detached app with few native modules linked to ios and android. It's a music player. Will it be possible for me to publish my app on expo so that people can also runy app by scanning QR code in expo client?

**Comment by sitorush** [comment]
@themakerman have you tried this with your detached app? is it possible? I am curious as well.

**Comment by anp** [comment]
@themakerman you could publish two versions of your app, one detached and one not, with the same code in each, as long as you wrap any non-Expo native module usage in try/catch or if statements that will keep it from executing.

Also, if you temporarily delete the detach info from app.json, you should be able to load your app in the client just fine. It might error if there are missing native modules, but that's something you can handle in your code.
