### ISSUE TITLE
Permission ACCESS_BACKGROUND_LOCATION missing on Standalone build

### ISSUE THREAD

**Issue by DCKT** [expo/expo#13253]
### Summary

Hello,

If I run the app through `expo run:android` or `eas` with `expo-location`, the permission `ACCESS_BACKGROUND_LOCATION` is missing from `AndroidManfiest.xml`.

I'm am missing something about configuration ? 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.1

### Environment

  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS 11.2.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-7921776/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.12 - /var/folders/k6/cqlnsz8x0756r83kbyb0s2700000gp/T/fnm-shell-7921776/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/colisweb/.rvm/gems/jruby-9.2.13.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

https://github.com/DCKT/expo-location-background

**Comment by byCedric** [comment]
Hi @DCKT! Yes, that is correct. Because Google started rejecting apps using background location without a proper reason, we moved this permission to be opt-in. We did this [starting from SDK 40](https://blog.expo.io/expo-sdk-40-is-now-available-d4d73e67da33#707e).

If you still want to use the background location permission, simply [add it to your `android.permissions` list in the app manifest](https://docs.expo.io/versions/v41.0.0/config/app/#permissions). Be aware that Google requires you to go through a separate review to use background location.

Hope this helps!
