### ISSUE TITLE
Remote Font Loading doesn't work

### ISSUE THREAD

**Issue by conrad-vanl** [expo/expo#1335]
Remote font loading is broken even though it is well documented in the Expo docs:
https://docs.expo.io/versions/latest/sdk/font.html

Was this ever working? Or was this documentation written pre-emptively? Is there a plan to implement this functionality?

Relevant code:
https://github.com/expo/expo-sdk/blob/master/src/Font.js#L105

If you could share more info about this issue, we might be able to put some resources behind it to get it working.

Thanks!

**Comment by esamelson** [comment]
@nikki93 - can you provide some clarification here?

**Comment by brentvatne** [comment]
I think the history of this is that we intended to add this but @nikki93 never ended up having time because other higher priority tasks came in. I updated the docs to remove this option from the API: https://docs.expo.io/versions/latest/sdk/font.html

I made a feature request that anybody interested can upvote to indicate that this is important to you: https://expo.canny.io/feature-requests/p/load-remote-fonts

**Comment by Lepozepo** [comment]
@esamelson @brentvatne we have remote URLs working [here](https://github.com/NewSpring/Apollos/tree/149-typography/src/%40ui/FontLoader), if anyone is willing to improve on that work and submit a PR into expo that would be awesome (it's dirty work right now)
