### ISSUE TITLE
Expo Go crashes on AsyncStorage numeric setItem

### ISSUE THREAD

**Issue by AndyTallack** [expo/expo#13391]
### Summary

Apologies if this is the wrong repo for Expo Go

When incorrectly passing a numeric value to AsyncStorage.setItem, Expo Go on IOS crashes, bypassing the try...catch statement.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41

### Environment

  Expo CLI 4.6.0 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\aretallack\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ~41.0.1 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

```
expo init asystor
cd .\asystor\
expo install @react-native-async-storage/async-storage

```
modify the default App.js per the below

`expo start`

open using Expo Go on IOS

**App.js**
```

import { StatusBar } from 'expo-status-bar';
import AsyncStorage from '@react-native-async-storage/async-storage';
import React, {useEffect} from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
	
	useEffect( () => {
	  
	  (async () => {
			console.log('About to setValue')
			try {
				let x = await AsyncStorage.setItem('test_value', 1);
				console.log('Value Stored')
			} catch (e) {
				console.log('Error writing to storage:')
				console.log(e)
			}
		})()
	}, []);
	
	  
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

No messages are logged to the console

**Comment by brentvatne** [comment]
hi there! AsyncStorage is in an interesting spot where we use the code from react-native itself in Expo Go and `expo build` apps, but elsewhere we use [@react-native-async-storage/async-storage](https://github.com/react-native-async-storage/async-storage) (under the hood, the latter library uses the native code from the former when running in Expo Go). i am unsure if this is the current behavior in `@react-native-async-storage/async-storage`, if it handles this better then when we switch over the native implementation from the version in react-native core to that, it will be resolved. but until then, this is just a bug in react-native upstream. closing this because native code lives in third party libraries outside of expo.

**Comment by Infinitism** [comment]
I just opened a ticket because this issues crashes ios standalone builds when built using EAS.
