### ISSUE TITLE
"No cache exists for this resource: kernel.ios.bundle" in SDK 25.0 detached app

### ISSUE THREAD

**Issue by sloppycoder** [expo/expo#1348]
I upgraded my app to SDK 25.0.0, then detached for building with Xcode. The resulted app doesn't work, giving me error "No cache exists for this resource: kernel.ios.bundle".

I thought offline JS bundle should be supported by now. Am I missing something?

I'm using exp 49.0.1, SDK 25.0.0. Steps to reproduce

```
 exp init ...
# modify app.json, update slug, package name etc.

exp detach

exp publish 

cd ios ; pod install
```
Then open the workspace in Xcode, Archive and export IPA for ad-hoc distribution.  Loaded the app onto my phone, then got the error. 

For more details see commit history in this repo
https://github.com/sloppycoder/expo_offline_test

**Comment by terribleben** [comment]
I suspect there is a bug (on our end) with `"isRemoteJSEnabled": false,` and detached iOS apps. Does the issue go away if you remove that key?

**Comment by sloppycoder** [comment]
I removed "isRemoteJSEnabled" from app.json, then run "exp detach" and etc, build a new app using Xcode. The app did work, but by using Charles Proxy I found that it was still downloading the JS bundle from exp.host. That's not what I intended. 

Apparently when "isRemoteJSEnabled" is removed from app.json, the EXShell.plist created by "exp detach" doesn't contain the key either. The resulted app will download JS bundle from exp.host. 

I then added "isRemoteJSEnabled" to EXShell.plist, set it to false, rebuild the app, the same error came back. The app does not trying to download from exp.host, but somehow doesn't use app-shell.bundle either.

I created new branch for this experiment.
https://github.com/sloppycoder/expo_offline_test/commits/re-detach

**Comment by terribleben** [comment]
Here is a workaround you might be able to use for now:

- Open https://expo.io/@exponent/home/index.exp?sdkVersion=25.0.0 in your browser
- Look at the value for `bundleUrl` there, and download the file at that url.
- Name the downloaded file `kernel.ios.bundle` and move it to the directory `ios/your-project/Supporting` in your detached project.
- Open your detached project in Xcode, right click the `Supporting` directory in the file tree, "Add files...", and add `kernel.ios.bundle` to your project.

The bug you reported is the result of Expo failing to perform this action automatically for you during detach. This workaround should work as long as your project is running SDK 25. You should be able to use the `isRemoteJSEnabled: false` behavior.

Hopefully I can come up with a fix in the meantime so that you don't need to do this any more.

**Comment by sloppycoder** [comment]
When I ran 'exp publish', it created __shell-app.bundle__ file under ios/<project>/Supporting. I then copy that file to __kernel.ios.bundle__. That gave me an app that launches correctly.

Is that a valid workaround? What's the difference between shell-app.bundle and the JS bundle downloaded from cloudfront?

I noticed that when __isRemoteJSEnabled__ is false, __Expo.util.reload()__ doesn't reload JS bundle from internet either. Is that by design? Would be nice if is a way to force a reload even when the app is started in offline mode.

**Comment by terribleben** [comment]
> When I ran 'exp publish', it created shell-app.bundle file under ios//Supporting. I then copy that file to kernel.ios.bundle. That gave me an app that launches correctly.

Not clear to me why that works at all, it's not the correct thing to do. The two bundles are different. But if you're unblocked, then great!

**Comment by LeiZeng** [comment]
Hi @terribleben, I have the same issue and do found the IOS template seems like missed this `kernel.ios.bundle.js` file.

Check this:
https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.3.3-sdk25.0.0-e7a4361a-631d-4caf-9692-1880d71c394a.tar.gz

The walk around works for me, thanks for that. Could be better if you can add the bundle file to the template for other detached apps.

**Comment by ide** [comment]
In the next (or next-next) release of ExpoKit, we will remove the need for `kernel.ios.bundle` so this entire class of issues should go away.
