### ISSUE TITLE
iOS WebBrowser: swipe right will turn off WebBrowser, but it can never be opened again

### ISSUE THREAD

**Issue by thomasttvo** [expo/expo#135]
Steps to reproduce:
1. get on iOS
2. trigger open WebBrowser
3. swipe right from the left edge
4. notice WebBrowser will go away
5. trigger open WebBrowser again
6. notice warning "Another WebBrowser is already being presented." and WebBrowser cannot open afterwards

**Comment by charlesvinette** [comment]
Hello Thomas, thanks for reporting the issue I will be taking a look.

**Comment by thomasttvo** [comment]
any luck on this @charlesvinette ?

**Comment by charlesvinette** [comment]
Hello @thomasttvo! I found the issue, it is related to SFSafariViewController didFinish delegate not being called when dismissed with swipe, causing the promise to never be resolved or rejected, causing the bug.more here -> https://forums.developer.apple.com/thread/29048

Bug was already filed on open radar, the workaround we will be using is basically to wrap the view controller in a UINavController (as we already are) but we need to set the modal presentation in order to "disable" the swipe, which didnt make sense anyway since we were presenting it modally, from the bottom.

Cheers!

**Comment by thomasttvo** [comment]
> which didnt make sense anyway since we were presenting it modally, from the bottom.

Very true, thanks for the hard work, @charlesvinette

**Comment by charlesvinette** [comment]
My pleasure! :)

**Comment by charlesvinette** [comment]
Fix will be in next release!
