### ISSUE TITLE
-- offline flag not starting app 'offline'

### ISSUE THREAD

**Issue by dale-french** [expo/expo#1363]
If I start my app using `exp start --offline` offline mode is not simulated - data is still being fetched from my api endpoints etc.

**Environment:**
Expo: 25.0.0
React: 16.2.0
React Native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz

Am I missing something?

Thanks in advance

**Comment by jimmylee** [comment]
Assigning our expert @fson to have a look at the issue and diagnose whether or not he needs more information.

**Comment by fson** [comment]
The `--offline` flag for `exp start` doesn't simulate offline mode – it merely tells `exp` itself to run in offline mode and without having to sign in with your Expo account, so that you can keep developing your app even if you don't have internet connection available.

Simulating offline mode for your app also sounds like a great idea, and something that people have asked for, but we don't have it yet. You can vote on the feature and add your comments on Canny: https://expo.canny.io/feature-requests/p/developer-workflow-for-offline-support.
