### ISSUE TITLE
[expo-location] Background location task does not fire in standalone Android build

### ISSUE THREAD

**Issue by srmagura** [expo/expo#13765]
### Summary

Calling `startLocationUpdatesAsync` causes my location task to execute immediately and after moving my phone around when running in Expo Go only. In a standalone Android build, the location task does not execute (or perhaps does so very infrequently).

Note: I have not tested this on iOS but can do that this week if desired.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

 Expo CLI 4.8.1 environment info:
    System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Minimal repro: https://github.com/srmagura/expo-location-repro

### Instructions for using the app
1. Allow location access when the app requests it.
2. Wait for the "permission status" label to change to "granted".
3. Use the switch to enable the location task.

Expected behavior: an alert with the geolocation is shown immediately after enabling the location task. Moving your phone around shows additional alerts.

### Technical instructions
```
git clone https://github.com/srmagura/expo-location-repro.git
cd expo-location-repro
yarn
yarn start        # Location task will show an alert with the geolocation when running in Expo Go
expo build:android    # build as an APK
```
Then download the APK from the Expo website and install it on your phone. The location task does not show an alert.

[Pre-built APK](https://drive.google.com/file/d/17XMHbM1Rd5JIC50KRv_ZokqDS-hexeG9/view?usp=sharing)

**Comment by srmagura** [comment]
@tsapeta @EvanBacon @byCedric Any help with this? I am sorry to bug you but this is a hot button issue for our customer. Unless there is an obvious issue in my code (entirely possible) this seems like a serious loss of functionality in Expo. Thank you!

If upgrading to a premium plan would help escalate this issue, I will speak with my boss.

**Comment by srmagura** [comment]
**Workaround:** Create a new React Native (non-Expo) project and use [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation). Do not use `expo-splash-screen` as it is currently not compatible with `react-native-background-geolocation`, see https://github.com/expo/expo/issues/14099.

**Comment by byCedric** [comment]
Hi @srmagura, sorry it took a while. On what Android device were you testing the background location? There were a lot of changes between Android 9, 10, and 11. Each of these versions behave differently compared to requesting and using background location.

I would recommend checking out our [earlier issue comments related to the permissions, and how they compare to all of the Android versions (incl. a demo app)](https://github.com/expo/expo/issues/11330#issuecomment-748196328). As of now, we separated the permission requests (as mentioned in that comment) and you don't need to use staging to install the latest Expo Go version. 

I would also recommend trying to [build a dev client instead of Expo Go](https://docs.expo.dev/clients/introduction/). By doing that, you are in full control of the permissions you want or need to include and could test the background processes a bit easier.

Hope this helps!

**Comment by srmagura** [comment]
Thanks for the response @byCedric. I was testing on Android 11. 

I tried out your Office Marathon app and it did track my location. I wonder why it works but my simple repro does not. Perhaps it is because you used 
```
"permissions": [
    "ACCESS_COARSE_LOCATION",
    "ACCESS_FINE_LOCATION"
]
```
while I used
```
"permissions": ["ACCESS_BACKGROUND_LOCATION"],
```
under the `android` key in `app.json`. I may come back to this and test that.

Regardless, my feeling is that `expo-location`'s background location tracking is not robust enough to use in production (and I say this having used it in production for about 9 months and receiving multiple complaints from our client). I wonder if a warning about this in the documentation would help prevent other developers from having the same negative experience.

Anyway, this is no longer a pressing issue for me as I switched to `react-native-background-geolocation`, but I appreciate the help nonetheless.

**Comment by byCedric** [comment]
I'm sorry for the experience you had. We are making some changes in the documentation, and the location docs will definitely get more context on how and when to use certain background or foreground permission flows. That being said, I'm happy you found a way to make it work for you.

I also want to give you a bit more context on the example app. Originally, I used the full background location workflow. But, as mentioned in the other issue comments, requesting permissions for the background is handled differently on different Android versions (which is kind of weird from Google).
  - For some older versions (<9), you have to request just the `ACCESS_COARSE_LOCATION` and `ACCESS_FINE_LOCATION`. This will give you background location access already since `ACCESS_BACKGROUND_LOCATION` doesn't exist in these versions of Android.
  - For Android 10, you have to add `ACCESS_BACKGROUND_LOCATION` to your manifest to get access.
  - For Android 11, you have to add `ACCESS_BACKGROUND_LOCATION` _and_ request the user to access it. This MUST NOT be requested together with the other two permissions (foreground location). When you try to do this, the permission is denied instantly.

Now, to make things even more exciting, you have to go through a different review from Google (but I guess you already did this). 

After we separated the permissions, I moved the example to another flow where you can get background location access without actually using the background location flow. This will increase the frequency stability in the background tasks, which is useful for scenarios like food delivery tracking. By requesting just the foreground location, with a pinned notification, you can use only the foreground permissions in a background task (as long as the permission is still pinned and communicating to the user their location is being used).

These workflows [should be explained on the Android documentation](https://developer.android.com/training/location/permissions).

Cheers!

**Comment by igorsps10** [comment]
Hi
Which version has the pinned notification?

I tested the latest version of the link and the location stops working when I change apps
