### ISSUE TITLE
[docs] [expo-updates] Changelogs missing breaking changes versioning

### ISSUE THREAD

**Issue by pweisensee** [expo/expo#13879]
### Summary

It seems some expo package Changelogs are not updating properly. It would be helpful to know when breaking changes are being released and which versions are safe to install or contain important fixes. What fixes or changes remain unpublished?

[See `expo-updates` changelog](https://github.com/expo/expo/blob/master/packages/expo-updates/CHANGELOG.md)

Notice the changelog stops at `0.7.0` release, [but currently `npm` has `0.8.3` published already](https://www.npmjs.com/package/expo-updates).

### Link to the related docs page

https://github.com/expo/expo/blob/master/packages/expo-updates/CHANGELOG.md

**Comment by esamelson** [comment]
Hey @pweisensee - thanks for pointing this out. We'll get the expo-updates changelog fixed on master.

After we cut the SDK release branches (`sdk-42` in this case) we generally publish further patches and fixes from that branch rather than master. We try to get the most important changes in before we cut the branch but that doesn't always happen 100% of the time. You can always look at the latest sdk branch if you don't see specific versions on master!

**Comment by pweisensee** [comment]
Ooof, okay, that sounds like an unfortunate mismatch between `master` and the versioned branches. I hope you all can find a way to automate these release notes trickling to `master`, but I understand the issue now and will try to remember to check the versioned branch in the future.

I see its up to date now, so thanks for that!
