### ISSUE TITLE
'expo-permissions' is deprecated. Use permissions getters and requesters in specific modules instead, such as MediaLibrary.getPermissionsAsync() and MediaLibrary.requestPermissionsAsync().

### ISSUE THREAD

**Issue by Soham2008** [expo/expo#13970]

**Comment by Soham2008** [comment]
Hello I am getting this error even though my app is working is properly... I just wanted to clear all the errors so I am asking this here... This is my first time asking a question here so I am sorry if I have done something wrong... Advanced thank you....

**Comment by barthap** [comment]
Hello there 👋 

This warning is being shown, because Expo deprecated using `expo-permissions` module. Instead, modules have their own methods for asking permissions.

You're probably doing something like this (I used camera just as an example):
```ts
import * as Permissions from 'expo-permissions';
//...
const result = await Permissions.askAsync(Permissions.CAMERA);
```

instead of using `expo-permissions`, you can do it by using `expo-camera` functionality:
```ts
import { Camera } from 'expo-camera';
//...
const result = await Camera.requestPermissionsAsync();
```

Generally, all modules requiring permission (camera, media-library, location, notifications...) have 2 methods: `requestpermissionsAsync()` and `getPermissionsAsync()` which should be used instead of `Permissions.askAsync()` and `getAsync()`.

Hope this helps 😄  Closing this now, but feel free to ask here if you still have questions.
