### ISSUE TITLE
Runtime is not ready for debugging.

### ISSUE THREAD

**Issue by shettyrahul8june** [expo/expo#140]
Every time I try to debug remotely, this is the error that pops up. I am not sure what's happening. I am not sure if it's the simulator that's causing the problem or expo. But, I just can't remotely debug. Below is the screenshot.

![image](https://cloud.githubusercontent.com/assets/8545078/25483967/a99e99b2-2b75-11e7-81ac-c98dd65eb995.png)

**Comment by terribleben** [comment]
Hello! This is an error message built into React Native. When you start remote debugging, your device (or simulator) tries to open a websocket connection to the debugger in Chrome. This message shows if that connection fails.

Some ideas for why your simulator can't connect to Chrome might be:
- Your connection is slow or unreliable.
- You are serving your project via tunnel instead of localhost, which won't necessarily cause this to fail, but makes the previous bullet point much more likely. In that case, try switching to localhost.
- Chrome didn't start the debugger for some reason, or the debugger is paused on a breakpoint (as the error message suggested).

**Comment by shettyrahul8june** [comment]
@terribleben Understood.

> You are serving your project via tunnel instead of localhost, which won't necessarily cause this to fail, but makes the previous bullet point much more likely. In that case, try switching to localhost.

How can I switch to localhost in this scenario?

**Comment by terribleben** [comment]
If you're using XDE, click the gear next to your project URL, then go to the Host menu and select localhost. If you're using exp, use `exp r --localhost`.

**Comment by shettyrahul8june** [comment]
@terribleben Thanks a lot for all the help.

**Comment by FourEyebrowXiake** [comment]
I used  create-react-native-app. I met the same issue.
here is my bug report:
```
Google Chrome exited with error: Error: Exited with code 1
11:25:28:     at ChildProcess.<anonymous> (/Users/fourfish/Desktop/react-native/UdaciFitness/node_modules/opn/index.js:86:8)
11:25:28:     at Object.onceWrapper (events.js:318:30)
11:25:28:     at emitTwo (events.js:125:13)
11:25:28:     at ChildProcess.emit (events.js:213:7)
11:25:28:     at maybeClose (internal/child_process.js:921:16)
11:25:28:     at Socket.stream.socket.on (internal/child_process.js:348:11)
11:25:28:     at emitOne (events.js:115:13)
11:25:28:     at Socket.emit (events.js:210:7)
11:25:28:     at Pipe._handle.close [as _onclose] (net.js:549:12)
```
How to solve this problem?
@terribleben
