### ISSUE TITLE
Ejecting expo app doesn't use variables from app.json

### ISSUE THREAD

**Issue by lucasfronza** [expo/expo#14011]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by lucasfronza** [comment]
We've used to have a CI workflow to eject using ExpoKit method, and this used all the configs from app.json in the respective Android and iOS configs. e.g. bundle ID, Google Maps config API Key

We have now moved away from ExpoKit, and we are trying to use the same approach with the Bare workflow. But, we've realized that none of these configs are used when generating the Bare project. Is there something I'm missing? Is that intentional?

**Comment by byCedric** [comment]
Hi @lucasfronza! In EAS, we use the exact same approach for managed Expo apps. When you build with EAS, we generate the native project files based on `app.json` (and something new called [Expo config plugins](https://docs.expo.dev/guides/config-plugins/)). The command we use is `$ expo prebuild`, the newer version of eject. I would recommend trying that command instead of `$ expo eject`.

Note that Expo config plugins and the prebuild command were introduced for SDK 41 and up. I'm not sure what you are using right now.
