### ISSUE TITLE
Expo Windows 10 Issues

### ISSUE THREAD

**Issue by yehudahkay** [expo/expo#1403]
I found that 

1. Only LAN works, localhost and tunnel do not work. This is really confusing since the default is on tunnel so I almost gave up before I realized I could try LAN.

2. I can't run npm install while expo is open which is difficult since expo takes a while to open.

3. It seems like hot loading may occur immediately when the expo xde is in focus but otherwise takes a bit longer?

**Comment by terribleben** [comment]
Hello! Thanks for the feedback!

Sorry you ran into trouble with your tunnel and connecting to localhost. Since we don't have much other information about what you were doing or what your environment looks like, there's not a lot of specific advice I can offer to troubleshoot. These settings do work for most Windows 10 users at the moment. I recommend searching around on the [forums](https://forums.expo.io) for reports of similar symptoms.

You should be able to run npm install whenever you want. Click the Restart button on your project to clear the packager cache and start the packager again.

I don't believe we've heard any other reports of HMR changing behavior when XDE is unfocused. The react native packager maintains a websocket connection to your device. XDE is just rendering the packager's log output.

**Comment by yehudahkay** [comment]
@terribleben here is the error given

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "native-base" "--save"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path C:\wamp64\www\rego\node_modules\.staging\hoist-non-react-statics-df319810
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\wamp64\www\rego\node_modules\.staging\hoist-non-react-statics-df319810' -> 'C:\wamp64\www\rego\node_modules\native-base-shoutem-theme\node_modules\hoist-non-react-statics'
npm ERR!  { Error
npm ERR!     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:29:7)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
npm ERR!     at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR! 
npm ERR! Error: EPERM: operation not permitted, rename 'C:\wamp64\www\rego\node_modules\.staging\hoist-non-react-statics-df319810' -> 'C:\wamp64\www\rego\node_modules\native-base-shoutem-theme\node_modules\hoist-non-react-statics' parent: 'native-base-shoutem-th
eme' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Yehudah\AppData\Roaming\npm-cache\_logs\2018-02-12T15_22_16_900Z-debug.log

As far as unfocused, the actual answer is that the code is rebuilt when webstorm loses focuses. This is actually quite useful, not sure exactly why this is happening though.
