### ISSUE TITLE
Calendars API not working on Android 6 (or maybe some specific devices)

### ISSUE THREAD

**Issue by HarshulSharma000** [expo/expo#1407]
### Environment
Expo version 2.3.0
I am testing this on android 6 letv leeco 1s eco
deviceName Le X509 

### Steps to Reproduce

1. Open the Expo Apis app within expo client. 
2. Goto calendars api within expo sdk.
3. Click on Find my calendars and you find Expo has stopped working error.

### Expected Behavior
Expo might have interacted with the calendars api of phone in some desired behaviour.

### Actual Behavior
But instead of even showing an error or warning app simply crashes.

### Reproducible Demo
Just open the expo client.

**Comment by nicknovitski** [comment]
I'm assigning @jesseruder to this because he knows way more than me about android.

In the system Settings app, maybe under something like Apps & Notifications -> App Permissions -> Calendar, does the Expo app currently not have permission to access the calendar?  And if you switch it to have permission, does the behavior change?

**Comment by HarshulSharma000** [comment]
Did that still no benefit. Camera permissions are already given. Still the app is simply crashing.

**Comment by AdamJNavarro** [comment]
Hey @HarshulSharma000,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate.

Cheers,  
Adam
