### ISSUE TITLE
[iOS] LocalAuthentification.isEnrolledAsync returns false when passcode is enabled

### ISSUE THREAD

**Issue by VincentQuillien** [expo/expo#14118]
### Summary

On iOS if the passcode is enabled but not TouchID or FaceID then `LocalAuthentification.isEnrolledAsync` returns false.
However `LocalAuthentication.authenticateAsync` doesn't throw 'not_enrolled', it waits for the user to enter the passcode then returns success.

It seems like `isEnrolledAsync` should return true in this case and maybe the enum `AuthenticationType` should have a member for iOS passcode for `supportedAuthenticationTypesAsync` to return.

I'm using the latest version of expo-local-authentication (11.1.1) 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Environment

  Expo CLI 4.9.1 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.6.1 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.20.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
      Android SDK:
        Android NDK: 23.0.7123448-beta1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 12.5/12E262 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.8 => 38.0.11
      react: ^17.0.1 => 17.0.1
      react-dom: 16.11.0 => 16.11.0
      react-native: ^0.64.0 => 0.64.0
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 4.9.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

```ts
await LocalAuthentification.isEnrolledAsync() // false
```

**Comment by M1ST4KE** [comment]
The `isEnrolledAsync` function works like it's described [in the docs](https://docs.expo.dev/versions/latest/sdk/local-authentication/#localauthenticationisenrolledasync) on both iOS and Android platforms, but we decided to provide additional methods allowing users to check if there is enabled biometrics only, or as you described in the issue if there is enabled any authentication method. As soon as it will be released, please use the `isDeviceAuthenticationEnrolledAsync` method, because `isEnrolledAsync` is going to be deprecated.
