### ISSUE TITLE
Guideline for Running Expo on Android Studio Emulator

### ISSUE THREAD

**Issue by leosurwiki** [expo/expo#1420]
I think we have successfully run Expo on Android Studio Emulator months ago, but it couldn't work now. Could you provide a new guideline for running expo on android studio emulator? Really appreciate!

**Comment by maxh** [comment]
here's the context from slack discussion a few weeks ago; we just wanted to file an issue to track this over time:

![image](https://user-images.githubusercontent.com/1289501/36174004-b33eb9f4-10bf-11e8-99b9-3fad7401defc.png)

do you recommend using genymotion instead of the default android emulator?

also, when we publish it works, so we aren't totally blocked on this, but hot reload on android would improve our cycle time.

thanks!

**Comment by brentvatne** [comment]
@maxh - indeed we recommend genymotion for now!

**Comment by jesseruder** [comment]
We recommend genymotion in the docs: https://docs.expo.io/versions/latest/guides/genymotion.html.

@leosurwiki can you provide more details about why it didn't work?

**Comment by barakcodes** [comment]
I think the emulator from android studio is way more perfomant than before and might be worth intergrating now

**Comment by barakcodes** [comment]
@jesseruder  Yes I think PR is what's needed but emphasis on using the latest version of android studio would be a great addition on it too .

**Comment by smusa** [comment]
In fact i can not use Genymotion because of enterprise rules enforced by McAfee endpoint security and McAfee blocked the executable because it's below the trust threshold enforced by McAfee rules. So it will be good to integrate Android simulator.

**Comment by esamelson** [comment]
Hi @smusa - I've not had any issues using the Android Studio emulator. It shouldn't be too hard to set up but we'll get something into the docs soon.

**Comment by esamelson** [comment]
Hi all - the relevant changes have been made to the docs and will go out at the time SDK 29 is released.

**Comment by FreshBreadLux** [comment]
Hello, I followed the instructions in the documentation for running my project on an emulator in Android Studio. I had it working for a while, but after a few hours I started getting this error message: "The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project."

I'm not sure what's going on, since the project runs fine on the iOS simulator. Does anyone know what I'm doing wrong? I've included some details below.
--
SDK Version: 30.0.0
Dev Environment OS: MacOS High Sierra version 10.13.6
Android Emulator Setup: I’ve followed the Expo documentation to set up Android Studio. I can successfully run adb from the command line. I’ve set up a Google Pixel as my Android Emulator.

Expected Behavior:
Running expo start and launching the project in the Android Emulator should successfully start the app.

Actual Behavior:
I get the error ‘The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.’

I've been poking around some of the other issues to see if anyone else is experiencing something similar. I saw some suggestions that I delete the /Users/myuser/.expo/android-apk-cache directory and then run `npm run android`; I went ahead and tried that, but still get the same error. Any ideas what I'm doing wrong?
