### ISSUE TITLE
[expo-image-manipulator] Exposes wrong height after manipulateAsync() in 9.2.2

### ISSUE THREAD

**Issue by xRiot** [expo/expo#14506]
### Summary

We're getting our portrait image from expo-camera@11.2.2 through:
```javascript
camera.takePictureAsync({
  quality: 1,
  base64: false,
  exif: false,
  onPictureSaved: processImage, // Forwards the image to manipulateAsync()
  skipProcessing: false,
});
```

This gives us:
> // Result
> Original height: 4032 // console.log("Original height:", image.height);
> Original width: 2268 // console.log("Original width:", image.width);
>
> // For comparison
> Gimp height: 4032
> Gimp width: 2268

Then we run the image through expo-image-manipulator@9.2.2
```javascript
imageResized = await ImageManipulator.manipulateAsync(
  image.uri,
  [{resize: {height: 640}}],
  {
    compress: 1,
    base64: true,
    format: ImageManipulator.SaveFormat.JPEG,
  },
);
```

**This gives us the wrong result:**
> // Result
> Resized height: 4032 // console.log("Resized height:", imageResized.height);
> Resized width: 360 // console.log("Resized width:", imageResized.width);
>
> // For comparison
> Gimp height: 640
> Gimp width: 360

### What we've tried

Disabling/enabling base64 in either expo-camera nor expo-image-manipulator solves this issue.

### Cause?
We believe this issue was caused by this change: https://github.com/expo/expo/pull/13726/files#diff-eb615cf718726d88c6ec636eef2522acbc0baa70e97c011931c800931f4fc2efR83

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

Phone model: Samsung Galaxy s20+
Phone os: Android 11
Package: expo-image-manipulator@9.2.2

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by xRiot** [comment]
Workaround until we can fix this upstream:
```javascript
import { Image } from 'react-native';

Image.getSize(image.uri, (width, height) => {
  image.width = width;
  image.height = height;
}, (error) => {
  console.error("Failed to retrieve image size:", error);
});
```

**Comment by mnightingale** [comment]
I believe the PR you've linked to actually fixed this issue (Android regressions caused by Kotlin rewrite in 9.2.0) - causes it to return the original unmanipulated height.
However the fix hasn't been published yet, I'm not really sure on the expo release process and why expo-image-manipulator hasn't been published for 3 months when there are quite a few bug fixes pending release.
Perhaps some of the other changes require it to wait until SDK 43 in which case why don't bug fixes get cherry-picked in and released?

I've had success fixing this kind of issue in the past using https://www.npmjs.com/package/patch-package so you'd still use the 9.2.2 release but patch it to include the fixes.

**Comment by timoisalive** [comment]
We are also experiencing this issue, hoping for a new release soon...
