### ISSUE TITLE
Expo image picker always include camera permission even if I don't need it

### ISSUE THREAD

**Issue by rikoriswandha** [expo/expo#14525]
### Summary

I'm using `eas build` to build and then submit the apk to Play Store but I noticed a message: _Your APK or Android App Bundle is using permissions that require a privacy policy: (android.permission.CAMERA)._ .

When I check `expo config --type introspect` here's the result: 
```
{
    android: {
    versionCode: 2,
    permissions: [
      'android.permission.ACCESS_COARSE_LOCATION',
      'android.permission.ACCESS_FINE_LOCATION',
      'android.permission.CAMERA',
      'android.permission.READ_EXTERNAL_STORAGE',
      'android.permission.WRITE_EXTERNAL_STORAGE',
      'android.permission.RECORD_AUDIO',
      'android.permission.INTERNET',
      'android.permission.FOREGROUND_SERVICE'
    ],
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#111828'
    }
  },
}
```

Even if my app only using a camera roll access, `expo-image-picker` will always set a permission for camera and record audio which I don't need

I tried to patch the package using `patch-packages` and set a `"eas-build-post-install": "patch-package"` on my package.json. I saw the post-install script is running but the .aab output will still have the same permissions.

I think `expo-image-picker` should have a config for us to set a permission based on our needs. Thanks!

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.10.1 environment info:
    System:
      OS: macOS 11.5
      Shell: 3.1.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.10.1 - ~/.asdf/installs/nodejs/14.10.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.8 - ~/.asdf/installs/nodejs/14.10.1/bin/npm
      Watchman: 2021.09.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /Users/rikoriswandha/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.10.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1) Run `expo init`
2) Install image picker `expo install expo-image-picker`
3) Run `eas build --platform all`

**Comment by anback** [comment]
@rikoriswandha great finding! @anyone actually issue is bigger. It also add the android.permission.RECORD_AUDIO permission even though we dont need it. In most europe because of GDPR there is a heightened awareness and averision not to install an app if it as RECORD_AUDIO permissions => bad. Also imagine the discussion between developer and stakeholder. StakeHolder: Why does google say that we need to record audio. We are building a simple image picker app. Developer: We are using expo-image-picker which requires RECORD_AUDIO on android platform. Stakeholder: Why are we using expo again ? :) lol

**Comment by colinux** [comment]
Did you find a workaround without migrating to bare workflow, with config plugins maybe ?
It's also blocker for us, some users are refusing to upgrade or install app because of that :)

**Comment by rikoriswandha** [comment]
@colinux @anback  my temporary workaround is by installing `patch-package` and patch the `expo-image-picker` permission inside your `node_modules`. Here's the step:

1. `npm install patch-package` or `yarn add patch-package postinstall-postinstall` if you're using yarn. Refer to [https://github.com/ds300/patch-package](url)
2. Open `node_modules/expo-image-picker/plugin/build/withImagePicker.js` and delete permissions that you don't need inside the `withImagePicker` function
3. Run `npx patch-package expo-image-picker` or `yarn patch-package expo-image-picker`
4. Add a script inside your `package.json` for patching after build. I'm using eas-build so in my case the script is: `"eas-build-post-install": "patch-package"`
5. Run locally or rebuild your app and resubmit to Play Store

Here's my edited `withImagePicker.js` for reference
```
const withImagePicker = (config, { photosPermission, cameraPermission, microphonePermission } = {}) => {
    if (!config.ios)
        config.ios = {};
    if (!config.ios.infoPlist)
        config.ios.infoPlist = {};
    config.ios.infoPlist.NSPhotoLibraryUsageDescription =
        photosPermission || config.ios.infoPlist.NSPhotoLibraryUsageDescription || READ_PHOTOS_USAGE;
    return config_plugins_1.withPlugins(config, [
        [
            config_plugins_1.AndroidConfig.Permissions.withPermissions,
            [
                'android.permission.READ_EXTERNAL_STORAGE',
                'android.permission.WRITE_EXTERNAL_STORAGE',
            ],
        ],
        withImagePickerManifestActivity,
    ]);
};
```

**Comment by colinux** [comment]
@rikoriswandha I was about to do the exact same thing, thanks a lot for confirming it's working !

**Comment by colinux** [comment]
The issue is still present @github-actions ;)

**Comment by BrodaNoel** [comment]
This issue still there and it's kind of important.
I'm getting this warning on Google Play Console, and probably because of this.

<img width="1026" alt="Screen Shot 2022-03-04 at 01 33 08" src="https://user-images.githubusercontent.com/1837969/156699949-89c49ddc-07b0-417a-ab11-0ad05d6558ea.png">

While my permissions for Android, in app.json are:

```
      "permissions": [
        "ACCESS_COARSE_LOCATION",
        "ACCESS_FINE_LOCATION",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ],
```

And my code:

<img width="618" alt="Screen Shot 2022-03-04 at 01 34 29" src="https://user-images.githubusercontent.com/1837969/156700082-a3c2728d-51f9-45ab-9798-c454ff046f94.png">

**Comment by BrodaNoel** [comment]
BTW, check the Conversion Rate in Google Play.

This bug was published on September 2021, exactly in the month where the conversion rate drops heavily.

Is there a patch/workaround for fixing this fast?

<img width="1130" alt="Screen Shot 2022-03-04 at 01 38 42" src="https://user-images.githubusercontent.com/1837969/156700470-da4e7d01-3a6a-4db9-a9ce-2e9683f58245.png">

**Comment by BrodaNoel** [comment]
@rikoriswandha @anback @colinux Could you check if your Conversion Rate also goes down because of this?

**Comment by BrodaNoel** [comment]
Line related to the bug: https://github.com/expo/expo/blob/main/packages/expo-image-picker/plugin/src/withImagePicker.ts#L64

I would say that MICROPHONE, and also CAMERA should be optional by the user.

I'm willing to help to fix this problem, but I would need a clue about how to tackle it.
Should we send some optional parameters in `MediaLibrary.requestPermissionsAsync()` ?

**Comment by felix-lambert** [comment]
I'm having the exact same problems. A user gave me a one star review because of this. Can we solve this issue?

**Comment by BrodaNoel** [comment]
I had a big bunch of bad reviews and churns because of this. So, I am totally willing to create a PR and help to speed up this fix.


@tsapeta @ide could somebody give me some clues about where should I start, or at least tell me which functionality I should "copy". I guess there are some "ask for permission" functions that receives some parameters. Should I do the same? Do you have any example (PR?) where I can get the idea?

I quit my job to work 100% in this project of mine. So... I am willing to spend some long hours working on this bug

**Comment by BrodaNoel** [comment]
Gonna get some attention from @EvanBacon as well here.

(Please read my last comment)

**Comment by BrodaNoel** [comment]
I implemented the patch, but the .aab file says it still has those permissions, but the warning in Google Play Console is gone... @rikoriswandha @colinux do you have any idea why this could be happening?

<img width="763" alt="Screen Shot 2022-04-20 at 17 08 42" src="https://user-images.githubusercontent.com/1837969/164314246-7e691df4-e1c1-406d-9d42-9f2447b1ea7d.png">

<img width="681" alt="Screen Shot 2022-04-20 at 17 09 27" src="https://user-images.githubusercontent.com/1837969/164314350-3b8f7311-220d-470f-8938-c712b734ba53.png">

**Comment by BrodaNoel** [comment]
We are changing the `build` file
`https://github.com/expo/expo/blob/9f72d43bf5b7a1dac5b836d834430ee686a49e2e/packages/expo-image-picker/plugin/build/withImagePicker.js`
So, it shouldn't be necessary to change the `src`
`https://github.com/expo/expo/blob/9f72d43bf5b7a1dac5b836d834430ee686a49e2e/packages/expo-image-picker/plugin/src/withImagePicker.ts`

But... I would like to double check if we are 100% sure it is not necessary to change it there as well.

**Comment by BrodaNoel** [comment]
The Warning is back :(

<img width="1028" alt="Screen Shot 2022-04-20 at 20 43 48" src="https://user-images.githubusercontent.com/1837969/164342261-37ce34e2-0861-4325-a91a-37eb701e7c6c.png">
