### ISSUE TITLE
Is there an ongoing list somewhere of apps using Expo in production?

### ISSUE THREAD

**Issue by isaachinman** [expo/expo#1458]
Usually with a project like this, it's nice to see public examples of apps built with the codebase. I am currently in the process of trying to decide whether or not using Expo in production is an appropriate choice at all, or if it's best suited as a prototyping tool.

I'm aware that quite a few users are deploying production apps with Expo. It'd be great to see some examples linked in the README or elsewhere to get an idea of what these apps can look/feel like (mostly concerned with navigation).

**Comment by mchen37** [comment]
There is a Featured page which showcases apps using Expo: https://expo.io/featured
There are other options to sort by as well, such as Recently published, Most liked, etc.

There is also a Cheer section on their forums where users can post the apps they made with Expo: https://forums.expo.io/c/cheer

**Comment by anp** [comment]
@isaachinman I agree that would be great! We don't have a super up to date list, but we do feature a number of projects on https://expo.io (its a nice compact list if you're logged in too). We've been posting interviews with some developers to our [blog](https://blog.expo.io) as well. The links that @mchen37 posted are also good places to look.

I'd also recommend taking a look at our [anti-pitch](https://docs.expo.io/versions/latest/introduction/why-not-expo.html) for information about some areas that we know need improvement.

Since you mentioned navigation specifically, I'll point out that for Expo projects the most commonly used off-the-shelf navigation library is React Navigation. They also have a [pitch/anti-pitch](https://reactnavigation.org/docs/pitch.html) page that I would recommend looking at. If you use React Native without Expo, you do have a number of "hybrid" navigation options that usually involve editing native code if you want to change or customize them. React Navigation has had a bit of a bumpy first year in use, but it recently had a 1.0 release with revamped docs and a bunch of fixes. Things seem trending in a good direction there.

Another useful resource is our [feature request board](https://expo.canny.io/) where you can find out about features people have been commonly requesting.

I'll make a note that we should try to formalize more of a "successful business projects with Expo" page. In the meantime, I'll give this a close and ask that if you have any follow up questions head over to our [forums](https://forums.expo.io) -- we mostly try to keep the issue tracker focused on bug reports.

**Comment by craigcosmo** [comment]
is there open source project built with expo we can check out the code?
