### ISSUE TITLE
Expo av loop causing touches to become unresponsive

### ISSUE THREAD

**Issue by thiago-cmont** [expo/expo#14644]
### Summary

When calling an audio in loop after 3~5 minutes the touches begin to be unresponsive and in ios im getting the warning excessive number of pending callbacks. The project was created with react native cli and using unimodules.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android, iOS

### Environment

Expo CLI 4.12.1 environment info:
    System:
      OS: Windows 10 10.0.19042    
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    SDKs:
      Android SDK:
        API Levels: 30, 31
        Build Tools: 28.0.3, 29.0.2, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      react: 16.13.1 => 16.13.1
      react-native: 0.63.3 => 0.63.3
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

https://snack.expo.dev/@thiagocorreia/soundloop

**Comment by gsevla** [comment]
This problem wasn't caused by malfunctioning of expo-av, sorry for any confusion.

To clarify, the problem happened because we are trying to expose playback status from a custom hook that create a expo-avd sound instance and play a sound. We are using a state to save playback status onPlaybackStatusUpdate. So in order to solve the problem, we are using a ref to save playback status and exposing the value by audio getStatusAsync.
