### ISSUE TITLE
[docs] Confused about unimodules and expo sdk

### ISSUE THREAD

**Issue by Qwin** [expo/expo#14652]
### Summary

So I been very confused about what to use right now for a Bare flow of expo, I saw this in the changelog of unimodules 
![image](https://user-images.githubusercontent.com/1026038/136121320-d6b56ab6-3ae8-4150-be5a-6b6ab5e1df3e.png)

But the link provided for the migration is going to a 404 ? can someone please provide me the latest way for me to just use 1 expo module, I am guessing you guys suggest just adding the expo library ? Does that mean I need to delete my unimodules and then somehow modify my AppDelegate as well as revert all the changes I did from this doc (which btw doesn't state that its deprecated either!) 

https://docs.expo.dev/bare/installing-unimodules/

Been running around in circles

**Comment by Qwin** [comment]
thank you for the quick answer! also I saw there is a alpha version of unimodules, I'd imagine thats the one I should be using once sdk 43 is out.

**Comment by Qwin** [comment]
@byCedric  I am having problems with the latest version sadly: 
https://github.com/unimodules/react-native-unimodules/issues/175

**Comment by brentvatne** [comment]
please refer to https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc and let us know if you run into any issues with expo libraries and `use_frameworks!`. please note that we can't add support for this to every library in the ecosystem, because we only control expo libraries. some react-native tools like flipper or hermes are incompatible with `use_frameworks!`, along with some [other tools mentioned in this comment](https://github.com/expo/expo/pull/14523#issuecomment-927121182) - but you are likely to encounter many more.

in this pr we fixed `use_frameworks!` support for the sdk 43 versions of the expo modules packages.

**Comment by Qwin** [comment]
@brentvatne  awesome will follow the guide and see if it works :)
