### ISSUE TITLE
[BUG] expo-calendar doesn't work on ios production build.

### ISSUE THREAD

**Issue by GeorgeHop** [expo/expo#14935]
### Summary

Hello guys! Really searching for some help here because we meet an issue in our project and can't resolve this bug at all. 

The problem: 
expo-calednar doesn't work on the production build for ios. When you test it on the production mode enabled everything working how expected but when you tested it on the ios build it just asking permissions and after allowing nothing happens. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

41.0.0

### Environment
```JS
  Expo CLI 4.7.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\George\AppData\Roaming\npm\yarn.CMD
      npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
        System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ^41.0.0 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

!!! You need to use build for IOS app to reproduce this bug !!!

Here I prepared some code for you in Snack: https://snack.expo.dev/@mistertvister/ca5b9d
You can see that by the link everything working how expected so please follow all next stepts to reproduce the bug correctly.

1. Also I have created new project using expo init after that I installed required packages using yarn

here is my package.json
```JS
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~41.0.0",
    "expo-status-bar": "~1.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.2",
    "react-native-web": "0.17.1",
    "expo-calendar": "~9.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

2. After installation I added all permissions for calendar to app.json 

```JS
{
  "expo": {
    "name": "expo-calendar-bug-app",
    "slug": "expo-calendar-bug-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "infoPlist": {
        "NSRemindersUsageDescription": "Access to the calendar is necessary for the purpose of data integration with calendar of the device.",
        "NSCalendarsUsageDescription": "Access to the calendar is necessary for the purpose of data integration with calendar of the device. Consent for access is voluntary, but failure to do so may result in restriction or loss of the functionality."
      },
      "bundleIdentifier": "com.mistertvister.expo-calendar-bug-app"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "permissions": [
        "READ_CALENDAR",
        "WRITE_CALENDAR"
      ]
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

3. For reproduce I used the code from Snack and just put it inside the App.js 

```JS
import {StatusBar} from 'expo-status-bar';
import React from 'react';
import {Text, View, StyleSheet, Platform} from 'react-native';
import * as Calendar from 'expo-calendar';

export default function App() {
    const [permissions, setPermissions] = React.useState(null);

    React.useEffect(() => {
        requestPermissionsForCalendar();
    }, []);

    const requestPermissionsForCalendar = () => {
        let permissions = {};

        Calendar.requestCalendarPermissionsAsync().then(async (res) => {
            permissions.calendar = res?.status === 'granted';

            if (Platform.OS === 'ios') {
                await Calendar.requestRemindersPermissionsAsync().then((res) => {
                    permissions.reminders = res?.status === 'granted';
                });
            }

            setPermissions(
                Platform.OS === 'ios'
                    ? !!(permissions?.calendar && permissions?.reminders)
                    : !!permissions?.calendar
            );
        });
    };

    if (permissions === false) {
        return (
            <View style={styles.container}>
                <Text>CALENDAR PERMISSION ERROR</Text>
            </View>
        );
    }

    return (
        <View style={styles.container}>
            <Text>CALEDNAR PERMISSIONS GRANTED</Text>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 20,
        backgroundColor: '#ecf0f1',
        padding: 8,
    },
});
```

4. And here we are, by running expo start you can see that everything is working okay. But how I describe at the top we need to create a build to full reproduce.

**Comment by brentvatne** [comment]
ah gotcha. can you try changing it as i suggested above?

**Comment by dorkyboi** [comment]
Hey @brentvatne, kudos to you for the time you are putting into our issue
I'm a fellow coworker of @GeorgeHop, we are working on this issue of our project together.

> can you try changing it as i suggested above?

If you mean `use getDefaultCalendarSource from expo-calendar on ios instead`, then i cant quite catch you.
In code that both you and us have provided `getDefaultCalendarSource` is already being used when `Platform.OS === 'ios'`.
If you mean that there is a method with same name defined in `expo-calendar` methods, sorry but i am unable to find it in the docs.
If its the permissions part you are reffering to, don't worry. Today we have ruled them out of probable causes. [^1]


On a side note,
- Could you please elaborate about these sources? It would be nice to know what we are dealing with under the hood. What are these sources? What are they used for? What is so important in using exactly the one named 'Default' and not just any source we can find (e.g. source of whatever first calendar in the phone happens to be)? What "default" _really means_ when we are talking about sources?
- There is `getDefaultCalendarAsync`. Perhaps we can use _that_ to retrieve default source? But can it be guaranteed that default calendar will always have default source (whatever 'default' means)?
- Could it be that calendar that used to have source named 'Default' has had its source changed, which lead to said 'Default' source not being attached to any of calendars and thus not being able to be found via `getCalendarsAsync`?
- Speaking of `getCalendarsAsync`, isn't `getSourcesAsync` a better way to find default source? Could it be related to previous bulletpoint (`getSourcesAsync` being able to find 'detached' sources)? Is there a reason behind docs' example using `getCalendarsAsync` instead of `getSourcesAsync` or is it just a case of example being somewhat outdated?

[^1]: fyi, we do use `requestRemindersPermissionsAsync` and only for ios

**Comment by brentvatne** [comment]
@dorkyboi - i am not an expert on this api and so i can't speak to the details, but i'm happy to bring in the developers who worked on this if needed.

what i was asking was for you to try using [getDefaultCalendarAsync](https://docs.expo.dev/versions/latest/sdk/calendar/#calendargetdefaultcalendarasync) directly rather than [getCalendarsAsync](https://docs.expo.dev/versions/latest/sdk/calendar/#calendargetcalendarsasyncentitytype) and attempting to filter out the default calendar.

source objects are described [here in the documentation](https://docs.expo.dev/versions/v43.0.0/sdk/calendar/#source). you can also read [the underlying native code for expo-calendar](https://github.com/expo/expo/tree/master/packages/expo-calendar) to learn more about the platform apis used here.

**Comment by dorkyboi** [comment]
@brentvatne 
It would seem that `getDefaultCalendarAsync` did the trick. Feels like that should've been the way to go from the get go.
Could I bother you to update the docs example to use `getDefaultCalendarAsync` instead?

**Comment by switz** [comment]
I'm attempting to add an event to an ios calendar that is _not_ the default calendar (my users set their preferred calendar for my app) but am getting:

```
add/remove event [Error: Event with id 20C21562-8089-4D26-935B-FBFDBFFBE0FB was not saved. Error Domain=EKErrorDomain Code=6 "The calendar is read only." UserInfo={NSLocalizedDescription=The calendar is read only.}]
```

This is via expo go – does it only work on a native build? Any ideas?

**Comment by brentvatne** [comment]
@dorkyboi - could you send a pull request to update the docs? 

same changes would be needed in these two files:

https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/sdk/calendar.md
https://github.com/expo/expo/blob/master/docs/pages/versions/v43.0.0/sdk/calendar.md

**Comment by dorkyboi** [comment]
Okay, i'll take care of that.

**Comment by dorkyboi** [comment]
We later had another error about default source not allowing to add/edit calendars.
This was because in the settings user had selected google calendar as default calendar.
So instead we had to add fishing for iCloud source.

```javascript
export const getDefaultCalendarSource = async () => {
    for (const source of await getSourcesAsync()) {
        if (source.type === SourceType.CALDAV && source.name === 'iCloud')
            return source;
    }

    const defaultCalendar = await getDefaultCalendarAsync();
    return defaultCalendar?.source;
};
```

Would probably be must better to use `getDefaultCalendarAsync` first but also add a testing sequence to it (adding calendar, adding calendar event, removing created event, removing calendar) to make sure that its source is valid and operatable and only resort to fishing if its not.

@brentvatne what do you think? We should definetely change docs example because apparently one cannot trust source of `getDefaultCalendarAsync`, there must be additional checks included to validate the source.
Personally i would suggest to add a method (e.g. `getDefaultSource`) that would do all of this under the hood, so that developers could reliably retrieve sources for their calendars.

**Comment by phillipjfry93** [comment]
For those of you still having issues with the API and still getting the error:

"Error Domain=EKErrorDomain Code=17 "That account does not allow calendars to be added or removed."

This problem: It is attempting to create a new calendar but your calendar on a physical device wont let that happen, so we have to work around that. 

My solution: Just return the default calendar id. Dont try to create your own because the permissions on iOS wont let you. You just have to use the default account. 

const createCalendar = async () => {
  console.log("inside create");
  const defaultCalendarSource =
    Platform.OS === "ios"
      ? await getDefaultCalendarSource()
      : { isLocalAccount: true, name: "New Calendar" };

  const newCalendarId = await Calendar.createCalendarAsync({
    title: "New Calendar",
    color: "blue",
    entityType: Calendar.EntityTypes.EVENT,
    sourceId: defaultCalendarSource.id,
    source: defaultCalendarSource,
    name: "internalCalendarName",
    ownerAccount: "personal",
    accessLevel: Calendar.CalendarAccessLevel.OWNER,
  });
  if (Platform.OS === "ios") {
    return defaultCalendarSource.id;
  } else {
    return newCalendarId;
  }

Hope this helps!
