### ISSUE TITLE
[document-picker][docs] Type DocumentPickerOptions showing error on "type" of type string[]

### ISSUE THREAD

**Issue by GustavoBonfimS** [expo/expo#15134]
### Summary

In the documentation it is said that you can pass a String array to the "type" property, but errors appear when doing this.

I'm in doubt if this is a module documentation or typing error. I apologize if I opened this Issue incorrectly.

I'm using DocumentPicker on version 9.2.4

![image](https://user-images.githubusercontent.com/50304935/141101851-22e38d2b-4461-416e-88a1-a790ec2da6b2.png)

![image](https://user-images.githubusercontent.com/50304935/141101980-f0c81593-8e2b-4fb7-9b32-390b46b6e19f.png)

![image](https://user-images.githubusercontent.com/50304935/141102053-2e72b0c8-a552-484d-8e2e-9d5addb558b1.png)

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/document-picker/#documentpickeroptions

**Comment by Simek** [comment]
Hi @GustavoBonfimS,

You need to update the `expo-document-picker` to at least version `10.0.0`, since multiple mime types feature has landed in this version:
* https://github.com/expo/expo/blob/master/packages/expo-document-picker/CHANGELOG.md#1000--2021-09-28
* https://github.com/expo/expo/blob/master/packages/expo-document-picker/src/types.ts#L7=L12

Latest docs always reflect the status of latest package version.

**Comment by GustavoBonfimS** [comment]
Thank's @Simek for your help!
I managed to do this and everything worked out, closing this Issue.
