### ISSUE TITLE
could not run unit tests for expo 43.0.3 with jest

### ISSUE THREAD

**Issue by xiongemi** [expo/expo#15328]
### Summary

follow the instructions to setup jest test for expo; however, got an error: `SyntaxError: /Users/emilyxiong/Code/nx-expo/node_modules/@react-native/polyfills/error-guard.js: Missing semicolon. (14:4)`

might be related to https://github.com/react-native-community/upgrade-support/issues/152?

This is what my jest.config.js looks like:
```
module.exports = {
  displayName: 'app',
  preset: 'jest-expo',
  transformIgnorePatterns: [
    'node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)',
  ]
}
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Web

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      expo: 43.0.3 => 43.0.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

### Reproducible demo

n/a

**Comment by byCedric** [comment]
Hi @xiongemi! I think this might be caused by your own `transformIgnorePatterns`. As you can see in the [React Native repository](https://github.com/facebook/react-native/blob/v0.64.3/packages/polyfills/error-guard.js), this file is written in Flow, and needs to be transpiled. If it's not getting transpiled, you can get a variety of syntax errors.

Try removing the `transformIgnorePatterns` and see if it works. If it does, and you need to add your own transforms, try copying the [latest one from here](https://github.com/expo/expo/blob/master/packages/jest-expo/jest-preset.js#L41) and add your own rules.

Hope this helps!
