### ISSUE TITLE
How to get unique id for a android device without ejecting Expo?

### ISSUE THREAD

**Issue by dbalodia** [expo/expo#1534]
I have used Expo.constants which provide the device id, device name etc. but the device id changed after some time. 
I want a device id or IMEI number using expo. So is there any kind of solution expo is providing?

**Comment by ide** [comment]
`Expo.Constants.deviceId` should not change for the lifetime of the installation of the app (though if the user clears their app data, that will also clear the device ID). Uninstalling and re-installing the app will generate a new device ID.

Expo does not expose the IMEI, partially since Apple does not expose it and it is sensitive information -- the IMEI and other similar identifiers would allow tracking people across apps.

You could detach and use: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getImei(int)

**Comment by verzil** [comment]
@ide I have read about your concerns regarding to exposing UDIDs, ones that could identify users across applications. I feel the same way in regards to this problem.

However I would feel that there should be a way to get an unique device id that is unique per application and does not change across installs. It is a very common case where the developers wants to setup some kind of reward or referral system that does not reward duplicate installs.

On IOS this can easily be achieved by saving an unique identifier using the SecureStore "keychain" service.

On android there should be a way to do this as well. Maybe writing a file in some kind of external location outside of the app folder. Or expose the ANDROID_ID (maybe this one is a little bit more exposing).

Please tell me what you guys think.

**Comment by ide** [comment]
@verzil I think that's reasonable and could be implemented safely with https://developer.apple.com/documentation/uikit/uidevice/1620059-identifierforvendor as it does not leak the UDID nor IMEI.
