### ISSUE TITLE
Question about react-native version of SDK 25 and status bar in modals

### ISSUE THREAD

**Issue by marcosmartinez7** [expo/expo#1551]
Hi, 

are you guys gonna update the react native version from https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz when it is accepted [this PR](https://github.com/facebook/react-native/issues/7474)? 

Thxs

**Comment by marcosmartinez7** [comment]
Can u guys include this in SDK 26? i mean, if the react native PR is accepted and merged.

**Comment by terribleben** [comment]
Hey there! That looks like an annoying StatusBar bug.

We update Expo's version of React Native every time we do a new SDK release. It looks like the fix for that bug just landed to react-native `master` a few days ago. React Native does a new release at the beginning of each month, and Expo typically follows up with a new update a few weeks later. So, yes we will eventually have the fix in Expo, but it probably won't be as soon as SDK 26.

Hope this information is helpful.
