### ISSUE TITLE
[media-library] getAssetAsync result empty when `after` present

### ISSUE THREAD

**Issue by ardyfeb** [expo/expo#15513]
### Summary

Media library `getAssetAsync` return empty `assets` when `after` option present with spesific asset id

### Managed or bare workflow? 

bare

### What platform(s) does this occur on?

Android

### Environment

```
Expo CLI 4.13.0 environment info:
    System:
      OS: Linux 5.15 Arch Linux
      Shell: 5.1.12 - /bin/bash
    Binaries:
      Node: 17.1.0 - ~/.nvm/versions/node/v17.1.0/bin/node
      npm: 8.1.2 - ~/.nvm/versions/node/v17.1.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 31.0.0
    npmPackages:
      expo: ^43.0.3 => 43.0.3
      react: ^17.0.2 => 17.0.2
      react-native: 0.66.3 => 0.66.3
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare
```

### Reproducible demo

Snack: https://snack.expo.dev/@ardyfeb/expo-media-library-reproduce

**Comment by barthap** [comment]
Hello,

I see the problem being slightly different - the option `after` on Android behaves differently than documented. To make it work, you should actually provide a stringified offset instead of an asset ID (like you'd do on iOS).

An example:
```js
// loads first 20 items
let firstPage = await getAssetsAsync({ first: 20, after: undefined }); // or { ..., after: "0" }

// loads 20 items, but with offset equal to "20"
// equivalent to SQL query: SELECT ... LIMIT 20 OFFSET 20
let secondPage = await getAssetsAsync({ first: 20, after: "20" });
```

So, if you're doing e.g. pagination, a workaround for both platforms would be:
```js
const pageSize = 20;
let firstPage = ...; // same as above
let lastItemID = firstPage.endCursor; // for iOS

let n = 2; // page number, starting from 1
let nthPage = await getAssetsAsync({
  first: pageSize,
  after: Platform.OS === 'android' ? `${(n-1)*pageSize}` : lastItemID 
});
lastItemID = nthPage.endCursor;
```

This is unfortunately an [Android Cursor's API behaviour](https://stackoverflow.com/questions/52129482/android-cursor-move-to-position-based-on-id), not a MediaLibrary fault. Internally, the [`Cursor.moveToPosition(after)`](https://developer.android.com/reference/android/database/Cursor#moveToPosition(int)) is called.

**Comment by ardyfeb** [comment]
Thanks @barthap for example code, it works.

**Comment by barthap** [comment]
Glad it works. Let's keep this issue open till the documentation about this is updated 😉

**Comment by barthap** [comment]
We're now tracking this internally, closing.
