### ISSUE TITLE
White background visible on orientation change in Expo client

### ISSUE THREAD

**Issue by dgreensp** [expo/expo#1563]
In the Expo app on iPhone, even with top-level View with a black background, there is a white backdrop visible during orientation change.

Is it possible to get rid of this white backdrop?  I tried making my black View be oversized to cover it, but it didn't work.

Possibly related to #1523 (except putting a black View in back doesn't help)

**Comment by terribleben** [comment]
Thanks for the report. There's probably not a way for you to get rid of this in Expo Client right now, since you are probably seeing a native iOS view peeking through underneath the React Native root view. I think it should not be a problem in standalone apps created with `exp build`. I'll track this issue and see if I can come up with something better (or more configurable).

**Comment by bduyng** [comment]
hi @terribleben any updates for this issue?

**Comment by alexandrosk** [comment]
Really interested into this.. any updates? @terribleben can I bypass this by using CTRootView/ReactRootView classes?

**Comment by cruzach** [comment]
@alexandrosk are you still seeing this on the most recent Expo Client version? I wasn't able to repro it. Will close this issue soon if no repro is provided

**Comment by mirshko** [comment]
yup it’s still visible! 

it also seems to be apparent when you’re using a Modal with the formSheet or pageSheet presentationStyle. 

heres a screenshot 

 ![image](https://user-images.githubusercontent.com/8116716/68979047-63713680-07f4-11ea-9cac-b4e378317683.jpg)

**Comment by samuelvisscher** [comment]
I can also confirm this issue is present (using SDK 35, iOS 13):

![image](https://user-images.githubusercontent.com/11761002/69085272-ad009200-0a3d-11ea-8965-fa5ce7080786.png)

I think that it relates to this:

https://github.com/expo/expo/issues/3306

This may be a solution, for ejected apps:

https://github.com/johniak/react-native-root-view-background

While until the new design of Page Sheets in iOS 13, the problem was very much limited. I think this will be a hot item for anyone using the Modal component with the `presentationStyle: "pageSheet"`.

**Comment by mirshko** [comment]
Yeah for sure. I presume the background color should always be black for this view. 

I don’t think pageSheet or formSheets on iOS would have a white background so the default root color should probably be black for this view. or at least configurable with a similar API to the StatusBar component. `RootView` or something

**Comment by lauridskern** [comment]
Whats the status on this issue? Is there a workaround? I have the same issue with the new ios13 stack navigator like @samuelvisscher

**Comment by brentvatne** [comment]
you can set the background color with this property in app.json https://docs.expo.io/versions/v36.0.0/workflow/configuration/#backgroundcolor

**Comment by samuelvisscher** [comment]
For anyone else wondering why this does not work for page sheets, @brentvatne already opened a new issue for this:

https://github.com/expo/expo/issues/6585
