### ISSUE TITLE
Example test (gl-camera) yields a white screen

### ISSUE THREAD

**Issue by ksesong** [expo/expo#1567]
I am trying to run an example from the `gl-test` repository, https://github.com/expo/gl-test/blob/master/Scenes/BasicCameraStreamScene.js (also visible [here](https://snack.expo.io/@bacon/gl-camera)), but there is a white screen in place of a camera view.

(FYI, I eventually want to put a filter onto the viewfinder.)
Thanks,

**Comment by ccheever** [comment]
Hi-

Can you fill out the information in this template? It will make it a lot easier to look into this.



### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment





### Steps to Reproduce



(Write your steps here:)

1.
2.
3.

### Expected Behavior



(Write what you thought would happen.)

### Actual Behavior



(Write what happened. Add screenshots!)

### Reproducible Demo



(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by ksesong** [comment]
### Steps to Reproduce

1. Run the scene from the `gl-test` repository entitled `BasicCameraStreamScene.js`

### Expected Behavior

A functional camera preview.

### Actual Behavior

White screen.

### Reproducible Demo

https://snack.expo.io/@bacon/gl-camera
