### ISSUE TITLE
expo.io unlisted favourites, won't show in list

### ISSUE THREAD

**Issue by jascodes** [expo/expo#1574]
Unlisted projects on expo.io, when favourited won't show in my favourite list. 
https://expo.io/@geekyants/nativebasekitchensink
So this one for example is i guess unintentionally being unlisted, but it doesn't make sense that I shall bookmark the link once available to me with my expo account

thx

**Comment by jimmylee** [comment]
Hey @jas99, I think what you're saying makes sense.

However when a user decides to *unlist* a project, by making that choice, they indicated to us they do not want their project discoverable by others. Since your list of favorites is public, showing `nativebasekitchensink` on your favorites list would be breaching that agreement.

However I have an idea: When a user views a list of projects they favorited, they can see unlisted projects only if they are viewing their own list.

Would that work for you?

**Comment by jas99** [comment]
That be perfect.

Thx

**Comment by terribleben** [comment]
Oops this isn't done yet

**Comment by ide** [comment]
Closing this since we are removing this part from the website.
