### ISSUE TITLE
Unresolved reference: core

### ISSUE THREAD

**Issue by Yandamuri** [expo/expo#15771]
### Summary

I have installed `expo-document-picker` and when I ran it from Android Studio getting following error,

    /node_modules/expo-document-picker/android/src/main/java/expo/modules/documentpicker/DocumentPickerModule.kt: (10, 21): Unresolved reference: core
The file above error pointing to looks like this,

package expo.modules.documentpicker

 import android.app.Activity
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import org.apache.commons.io.FilenameUtils
import org.apache.commons.io.IOUtils
import expo.modules.core.ExportedModule
import expo.modules.core.ModuleRegistry
import expo.modules.core.ModuleRegistryDelegate
import expo.modules.core.Promise
import expo.modules.core.interfaces.ActivityEventListener
import expo.modules.core.interfaces.ActivityProvider
import expo.modules.core.interfaces.ExpoMethod
import expo.modules.core.interfaces.services.UIManager
import expo.modules.core.utilities.FileUtilities
import java.io.File
import java.io.FileOutputStream
import java.io.IOException

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### Environment

This is my project configuration:

        "expo-document-picker": "10.1.0",
        "react": "17.0.2",
        "react-native": "0.66.4",
        "react-native-unimodules": "0.14.10"

Android configuration:

        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30

### Reproducible demo

I do not have any reproducible demo code As I am getting this issue when I ran project from android studio.

**Comment by byCedric** [comment]
Hi @Yandamuri, since SDK 43, unimodules has been deprecated and replaced by Expo modules core. It seems that you are missing this from your project. See this page for more info: https://docs.expo.dev/bare/installing-expo-modules/.

If you can't solve it, and you think this is an issue with the Expo SDK, please open a new issue _with_ repro. You always have the code that triggers this issue, if you can move the relevant code into a small example repository that would help.

Hope this helps!

**Comment by Yandamuri** [comment]
@byCedric Issue got resolved after migrating to Expo.
