### ISSUE TITLE
BlurView and useNativeDriver in Expo 26

### ISSUE THREAD

**Issue by wcandillon** [expo/expo#1584]
Since expo 26, `<BlurView>` cannot be animated anymore using `useNativeDriver: true`. I was curious to understand the change behind this behaviour.

Also I'm not able to reproduce the issue on snack, is it possible that snack is not yet up to date with expo 26. Is there a Module to display the expo version that is used?

I hope this is the right place for this question, thank you very much 🙌🏻

**Comment by dsc-ian** [comment]
I have the same issue since i'm using the theme made by wcandillon,

When useNativeDriver is set to true the blurview is not fading out but when it is set to false the blurview fades out.

Here is a sample code.

this.setState({ intensity: new Animated.Value(100) })
Animated.timing(intensity, { duration: 300, toValue: 0, useNativeDriver: true }).start();

**Comment by cruzach** [comment]
Hi, we're closing inactive issues that apply to older SDK versions. If you can repro this on a supported SDK in Snack (here's a basic [BlurView snack](https://snack.expo.io/@charliecruzan/blurviewexample)), please create a new issue with the repro! Thanks 🙏
