### ISSUE TITLE
[expo-av][iOS] .pauseAsync() on Video cause massive framedrops on UI thread

### ISSUE THREAD

**Issue by hirbod** [expo/expo#15873]
### Summary

When I pause a Video using `pauseAsync`, my UI Thread drops from 60 FPS to 22-30 on iOS. I don't have this type of framedrops on Android. It is extremely noticeable and freezes for up to 500ms until the app is reusable again.

Neither `stopAsync()` nor `playAsync()` cause any issues. unloadAsync does also drop frames a bit but not that much.
I am having a Flatlist with 25000 videos (highly optimized) and every paged slide starts a video and invisible videos stopAsync. Not a single framedrop (I swiped more than 10.000 videos). But when I change stopAsync() to pauseAsync() or open a modal (and trigger pauseAsync()), my modal needs 1-2 seconds opening up because pauseAsync() is blocking the whole thread.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

44

### Environment

```

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.2 - /usr/local/opt/node@14/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/opt/node@14/bin/npm
      Watchman: 2021.12.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.3
    Expo Workflow: managed
```

### Reproducible demo

-

**Comment by Hirbod** [comment]
Might also be related #5297

**Comment by mnightingale** [comment]
The problem is caused by... https://github.com/expo/expo/blob/4f5e6b33cdaa8294fede5944819f5848bb0930ab/packages/expo-av/ios/EXAV/EXAudioSessionManager.m#L216-L221

Commenting it out so the session is never set to inactive results in play/pause being near instant.

The docs even warn that it's a blocking operation and suggest not stopping it like this.

> Note that activating an audio session is a synchronous (blocking) operation.
> Therefore, we recommend that applications not activate their session from a thread where a long
> blocking operation will be problematic.

I'm a little out of practise with native iOS especially Objective-C but I think it probably needs something like `dispatch_async(dispatch_get_main_queue(), ^{ ... }` or one of the ther queues so the call doesn't block the main thread.
Might need to be careful of causing any race conditions - I can't remember.
Maybe the whole method can be deferred :shrug:

If I can find time to take a look at this problem I will but in the meantime if anyone else wants to fix it feel free :)

---

There is also another issue due to the currently implementation.

> Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

Seems to be that the audio session is being setActive:NO before it has actually been stopped/paused.
I'm not familiar with the AVQueuePlayer classes but maybe you are supposed to listen to when it is actually stopped/paused before the setActive call.

**Comment by hirbod** [comment]
The only time I actually touch AUDIO, is when my app booted.

```tsx
        await Audio.setAudioModeAsync({
          allowsRecordingIOS: false,
          interruptionModeIOS: InterruptionModeIOS.DoNotMix,
          playsInSilentModeIOS: true,
          staysActiveInBackground: false,
          interruptionModeAndroid: InterruptionModeAndroid.DoNotMix,
          shouldDuckAndroid: false,
        });
```

That's it. So is the whole reason why it doesn't work well because I've touched the AudioMode? Basically I just wanted to activate playsInSlitenModeIOS.

**Comment by mnightingale** [comment]
Audio/Video share significant parts of the codebase, basically playing audio is the same as playing a video without drawing the video.

If you want to verify that stopping the session is the issue, you'll need a bare workflow and configure expo-av to build from source so you can comment it out.
See https://expo.fyi/prebuilt-modules.

**don't not release an app with the code commented out, it'll break things.**

**Comment by hirbod** [comment]
@mnightingale commenting the lines worked PERFECTLY (I am using a custom dev client already)

Play/Pause react INSTANTLY!

**Comment by hirbod** [comment]
What could possibly happen if I would release my app like this? I mean there is 0 reaction on this issue since 2019.

**Comment by hirbod** [comment]
@mnightingale I tried following:

```objc
    dispatch_sync(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^(void) {
        NSError *error;
        if (!shouldBeActive && self->_sessionIsActive) {
          [session setActive:NO error:&error];
          if (!error) {
              self->_sessionIsActive = NO;
          }
        }
    });
```

But calling pauseAsync now does not lead to a crash or framedrops (so same result as commenting out), but now I see this in my console:

```
AVAudioSession_iOS.mm:1243  Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
```

**Comment by hirbod** [comment]
ping @bbarthec

**Comment by mnightingale** [comment]
@hirbod I can't really say what the consequences of not stopping the session would be, as far as I can tell if the system needs to it will deactivate it itself and whenever you need an active session you should assume it's inactive (so call setActive:YES).

I tried to do a little bit of research and the best documentation I could find was in the archive on [Audio Session Programming Guide](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/Introduction/Introduction.html)

[Audio Guidelines By App Type](https://developer.apple.com/library/archive/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioGuidelinesByAppType/AudioGuidelinesByAppType.html) I think guidelines from "Audio Guidelines for User-Controlled Playback and Recording Apps" and "Audio Guidelines for Browser-like Apps That Sometimes Play Audio" could be relevant.

**Audio Guidelines for User-Controlled Playback and Recording Apps** makes no mention of deactivating the session (except on background transitions)

A couple of the others mention passing option [AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation](https://developer.apple.com/documentation/avfoundation/avaudiosessionsetactiveoptions/avaudiosessionsetactiveoptionnotifyothersondeactivation) when playback finishes.

It's pretty difficult to find Objective-C examples of it these days and it's been a long time since I did anything in Objective-C, it's complicated a bit by use of AVQueuePlayer (I think these days it could use a AVPLayer and AVPlayerLooper, then delegate events for when an item finished playing to stop the session, I'd need to understand how the use of AVQueuePlayer affects this and how it decides to stop the session on pause).

I think one way of resolving it could be to add a bunch of completionHandler style callback blocks, making the `_updateSessionConfiguration` method async, but that's going to need a load of changes.
Maybe errors on setActive:NO could just be ignored and not reported to the app.

The `Deactivating an audio session that has running I/O.` errors do need fixing, it's probably all related.

I would like to get this fixed though, I extensively use the expo-av plugin in an app so try to keep any eye out for any issues that might affect it. I mostly deal with audio and am curious to see if the same problem happens with just playing/pausing audio, I can't say I've ever noticed it but maybe seeing videos makes it more obvious.

**Comment by bbarthec** [comment]
Hey @hirbod, @mnightingale 👋 
I see that you've done quite an impressive work on discussing the problem, checking if the proposed solution works and finding references in the official docs 👏 
I'm not an expert regarding this module's flow (but nobody actually is), so I guess I won't be of much help 🤷 
I'm also out of time to examine this case to the deepest code bits and I'm really sorry for that 😞 
As you've already tested the proposed solution I encourage you to provide a PR with it and I suppose we'll try to test it out 😁 
If something goes wrong we'll try to rollback and look for other options 😉

**Comment by hirbod** [comment]
@bbarthec thanks for you answer. I pinged you since I've seen you've done a lot on expo-av recently (android though), so I thought you might be the right person to tinker with.

What shall we do now? Remove the `setActive:NO` call? Dispatch the call? (which will cause the log `Deactivating an audio session that has running I/O.`)

I am no native expert, I feel like providing a PR won't be big of a help at my end.
I would just love to get this fixed before SDK 45.

**Comment by bbarthec** [comment]
@hirbod, I would go with complete removal at this point (with some comment though) as long as it does not affect the runtime (and other video/audio apps running on the phone) and it seems it doesn't. If something wrong comes up we could always examine it later and the Expo team is always prioritising fixing the possible regressions 👀 🛠️

**Comment by hirbod** [comment]
@mnightingale I tend to your proposal:

Remove setActive:NO and always call setActive:YES to assume the audio session was inactive. Going this route, we don't need to dispatch the call (so there will most likely be a single hick up when activating it). 


Personally speaking, I don't really care to "inform other apps" that I have deactivated my audio session. This wasn't the case anyway with expo (setActive wasn't called with options - once you've interrupted other apps, it did not restart music or anything)

@bbarthec if you're fine with this, we could go from here and I could bring up a PR. I think this is the way all the apps works anyway.

**Comment by hirbod** [comment]
And I see there is already a _deactiveAudioSession function with a listener for foreground/background. 
This explains why everything was still working smoothly.

Oh boy this PR will make a lot of people happy. (Even scrubbing video is smooth as butter now)

**Comment by hirbod** [comment]
@bbarthec  shall I set the variable `_sessionIsActive` to false (even though it is true) to prevent mutiple calls to `setActive: YES` or shall I remove the `_sessionIsActive` check and always call `setActive: YES`.

In my tests, calling `setActive: YES` on an active Audio session did not cause any errors or logs

**Comment by hirbod** [comment]
@bbarthec PR is ready
https://github.com/expo/expo/pull/16578

**Comment by arsotech** [comment]
hey guys and @hirbod thank you for helping with this issue. I've checked the thread and proposed solutions to make sense of the issue I am currently experiencing but can't get to a conclusion. My issue is when an audio file plays with expo AV, DuckOthers and DoNotMix modes lower and disable audio from other apps when my app is in foreground. I set the mode back to MixWithOthers but no luck. Any idea? And what's the expected behaviour of how it's set up currently?

**Comment by andrecrimb** [comment]
In my app, using the `duckOthers` property, the sound from other players is lowered, but even after the completion of the played sound (or unload), the volume never goes back up. Does anyone has insights about this?

**Comment by arsotech** [comment]
@andrecrimb  same issue happening for me. From what I gathered, this is the default native setup of expo-av.

**Comment by andrecrimb** [comment]
I must say but this feature sounds more like a bug to me 😅  
I'm impressed that the PR fixing the frame drops was merged even though another bug was introduced.

**Comment by andrecrimb** [comment]
I open an new issue about this duck/unduck problem https://github.com/expo/expo/issues/29077 👍🏽

**Comment by arsotech** [comment]
Hopefully it gets treated as a bug and not a feature. Ducking should not make other audio duck forever.
