### ISSUE TITLE
Publishing a project containing `sentry-expo` works from XDE but not CLI

### ISSUE THREAD

**Issue by iuliuvisovan** [expo/expo#1588]
Hello, I have configured `sentry-expo` as described [here](https://docs.expo.io/versions/latest/guides/using-sentry.html). I am able to publish using the XDE. However, when I try to run `exp publish` from the project's root directory, I get the following error:

> 11:45:41 [exp] Unable to load postPublishHook: './node_modules/sentry-expo/upload-sourcemaps'
> 11:45:41 [exp] Please fix your postPublish hook configuration.

I need to use the CMD in order to publish to a specific channel. What are the exact commands that the XDE runs behind the scenes when you publish? Any help greatly appreciated.

**Comment by qbig** [comment]
<img width="1458" alt="screen shot 2018-04-11 at 9 11 04 am" src="https://user-images.githubusercontent.com/5563225/38595220-5835af02-3d6c-11e8-96d3-efb021a51d36.png">
Not sure if this is related, but post publish hook stopped working since 6 days ago for me :(

**Comment by bruno-edo** [comment]
@iuliuvisovan I fixed this issue by updating exp to the latest version and using node 8.9.4.

Maybe that's your problem?

**Comment by soukupl** [comment]
I have the exact same problem...

**Comment by sjchmiela** [comment]
Hey all! Over a month ago we've released Expo CLI, which replaced `exp` and XDE tool. ([Release blog post](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c)) Could you please try to use latest version of Expo CLI and see if the issue is still there? If it isn't, 🎉! If it's still present, please open a new issue on the [`expo/expo-cli`](https://github.com/expo/expo-cli/) repo describing the problem (you can also link to this issue for some context 🙂).
