### ISSUE TITLE
process.env.API_URL returns "undefined" 

### ISSUE THREAD

**Issue by zaura-payments** [expo/expo#15888]
### Summary

I can grab my API key from the eas.json file using the following:

`const apiKey = process.env.API_KEY;`

Which returns my API key successfully, however if I try to do the exact same thing for API_URL it returns undefined. Here is my eas.json file for reference:

`{
  "build": {
    "release": {},
    "production": {
      "env": {
        "API_KEY": "myapikey",
        "API_URL": "https://api.my.com"
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "env": {
        "API_KEY": "myapikey",
        "API_URL": "https://staging-api.my.com"
      }
    }
  },
  "submit": {
    "release": {
      "android": {
        "serviceAccountKeyPath": "../path/to/api-xxx-yyy-zzz.json",
        "track": "internal"
      }
    }
  }
}`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

42

### Environment

Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7199119
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      react: 17.0.2 => 17.0.2
      react-dom: 16.13.1 => 16.13.1
      react-native: ^0.63.1 => 0.63.4
      react-native-web: ^0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

You can reproduce this by following the example in the Expo docs: https://docs.expo.dev/guides/environment-variables/

It even has an example using API_URL which should be returned successfully? For example:

const apiURL = process.env.API_URL;

Should return the API_URL value in eas.json but it just returns undefined.

**Comment by byCedric** [comment]
Hi @zaura-payments! You are missing one step to load env vars in your React Native code. I'll quote some parts of our docs to help you:

1. **eas.json** `.env` configuration behavior ([source](https://docs.expo.dev/build/eas-json/#environment-variables)) 
    > You can configure environment variables on your build profiles using the "env" field. _These environment variable those will be used to evaluate **app.config.js** locally when you run eas build_, and they will also be set on the EAS Build worker.

2. Using Babel to "replace" `process.env.*` variables ([source](https://docs.expo.dev/guides/environment-variables/#using-babel-to-replace-variables)) 
    > You can still use environment variables using another method, a Babel plugin. This approach replaces all references to `process.env.VARNAME` with the variable contents, and works in both Bare and Managed Workflows.

You are missing step 2 to replace `process.env.API_URL` variables in your React Native code. This is required because React Native doesn't evaluate `process.env.*` variables by default. In order to get them in the code, you need to add this transpile babel plugin.

Hope this helps!

**Comment by zaura-payments** [comment]
Hey thanks for the reply!

You mention app.config.js but im using eas.json, will this cause issues? The makeup of the files seem identical to me.

Thanks

**Comment by stesvis** [comment]
> Hey thanks for the reply!
> 
> You mention app.config.js but im using eas.json, will this cause issues? The makeup of the files seem identical to me.
> 
> Thanks

A long time later....I am having the same issue. Did you figure it out @zaura-payments ?
I use `eas` too and don't have `app.config.js` either. When I print `process.env.APP_URL` in the page it's always an empty string.

My **babel.config.js**:
```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      "nativewind/babel",
      "react-native-reanimated/plugin",
      "transform-inline-environment-variables",
    ],
  };
};
```

**Comment by VictorioMolina** [comment]
any updates?

**Comment by oleksii-jointoit** [comment]
you can use process.env to put some specific data into "extra" in your app.config.js (idk about app.json) like it's shown here
https://docs.expo.dev/workflow/configuration/#dynamic-configuration

and then pull that "extra" field using expo-constants (also shown in link)

**Comment by Nennae** [comment]
> Hi @zaura-payments! You are missing one step to load env vars in your React Native code. I'll quote some parts of our docs to help you:
> 
> 1. **eas.json** `.env` configuration behavior ([source](https://docs.expo.dev/build/eas-json/#environment-variables))
>    > You can configure environment variables on your build profiles using the "env" field. _These environment variable those will be used to evaluate **app.config.js** locally when you run eas build_, and they will also be set on the EAS Build worker.
> 2. Using Babel to "replace" `process.env.*` variables ([source](https://docs.expo.dev/guides/environment-variables/#using-babel-to-replace-variables))
>    > You can still use environment variables using another method, a Babel plugin. This approach replaces all references to `process.env.VARNAME` with the variable contents, and works in both Bare and Managed Workflows.
> 
> You are missing step 2 to replace `process.env.API_URL` variables in your React Native code. This is required because React Native doesn't evaluate `process.env.*` variables by default. In order to get them in the code, you need to add this transpile babel plugin.
> 
> Hope this helps!

Hey!
I am currently working on a project where I have the similar issue. The value returned is undefined, eventhough it seems as I have followed the documentations correctly ( except that I have declared the environment variables in eas.json instead of the babel.config.js). Might be worth mentioning that TypeScript is also used in the project. 

I declared my env variables in the eas.json file as below:

`
{
  "cli": {
    "version": ">= 3.0.0"
  },
  "build": {
    "development": {
      "android": {
        "buildType": "apk",
        "channel": "development",
        "env": {
          "API_URL": "myApiUrl",
          "API_KEY": "myApiKey"
        }
      },
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development"
    },
    "preview": {
      "android": {
        "buildType": "apk",
        "channel": "preview"
      },
      "channel": "preview"
    },
    "production": {
      "channel": "production"
          }
  }
}
`

Then I converted what originally was an app.json file into an app.config.json file, where I assigned those variables as below :
 
`import dotenv from "dotenv";

dotenv.config();

export default {
expo {
extra: {
      apiUrl: process.env.API_URL,
      apiKey: process.env.API_KEY,
      eas: {
        projectId: "b1rg788hu",
      },
    },
},
};`


Finally I imported  Constants  from "expo-constants",  and declared the following in one of the .tsx screens : 

`const apiKey = Constants?.expoConfig?.extra?.apiKey;
  console.log(apiKey); // returns undefined_
`

**Comment by Kojon74** [comment]
I had the same issue today and what fixed it was prepending `EXPO_PUBLIC_`to the environment variable name. From the Expo [docs](https://docs.expo.dev/guides/environment-variables/#reading-environment-variables-from-env-files):

> Create a .env file in the root of your project directory and add environment-specific variables on new lines in the form of EXPO_PUBLIC_[NAME]=VALUE

You also need to make sure you access it using the format `process.env["EXPO_PUBLIC_API_KEY"]`
