### ISSUE TITLE
Expo Permissions / Location problem with IOS 11.2.6^

### ISSUE THREAD

**Issue by dhustkoder** [expo/expo#1592]
Hello, I have this piece of code in my project:
```javascript
                               let { status } = await Permissions.askAsync(Permissions.LOCATION);
				if (status !== 'granted') {
				  return false;
				}

				let isEnabled = await Location.getProviderStatusAsync();
				if (!isEnabled.locationServicesEnabled) {
				  return false;
				}

				let location = await Location.getCurrentPositionAsync({});
				if (!location) {
				  return false;
				}

				return location;
```

It works perfectly on Expo with npm start. But when I build a binary with exp build:ios 
it does not work on iOS 11.2.6 or higher, works fine on older iOS versions though.

Is this problem with Expo / ReactNative API  or is it my code ?

I tried this code:

```javascript
		return new Promise(async function(resolve) {
			navigator.geolocation.getCurrentPosition(function(location) { resolve(location); },
			                               function(error) { resolve(false); });
		});
```

But the problem persists.

**Comment by nikki93** [comment]
Make sure the location permissions are enabled for the new app you are building (go to your iOS system settings, navigate to the settings for that particular app, and check the location settings from there). Also maybe display the errors rather than just returning 'false' so that you are able to collect more information on what's happening.
