### ISSUE TITLE
Network request failed (device and emulator)

### ISSUE THREAD

**Issue by viniciuscastelano** [expo/expo#1606]
Hello,

I am getting the error "Network request failed" (device and emulator) while accessing the URL https://reqweb.cast.com.br:5443/RequerimentoRest/req/login via fetch (). I can access this link via Postman or browser normally.

I wonder if there is a solution for this.

My code is:

```
import React from 'react';
import { Text, View } from 'react-native';

export default class App extends React.Component {
    componentDidMount(){
        return fetch('https://reqweb.cast.com.br:5443/RequerimentoRest/req/login')
            .then((response) => response.json())
            .then((responseJson) => {
                console.log(responseJson);
            }).catch((error) =>{
                console.error(error);
                alert(error);
            });
    }

    render() {
        return (
            <View style={{flex: 1, paddingTop:20}}>
                <Text>Test Rest</Text>
            </View>
        );
    }
}
```

Thank you very much in advance.

**Comment by ide** [comment]
The port for HTTPS is typically 443, you may want to double-check that. Additionally, if you are experiencing the issue on Android, the system uses a different set of root CAs than Chrome does, so you may want to verify that your TLS certificate is (transitively) signed by a root CA installed on your system: https://tamingthedroid.com/trusted-credentials

**Comment by aprilmintacpineda** [comment]
I run on the same issue. Here's what the situation looks like:

*frontend*

```js
axios.post('http://localhost:3000/authenticate/login', {
  testData: 'test data value!'
})
.catch(err => console.dir(err));
```

*express backend*

```js
import express from 'express';

const app = express();

app.post('/authenticate/login', (request, response) => {
  console.log(request.body);

  response.sendStatus(200);
});

app.listen('3000', () => {
  console.log('Dev server running at http://localhost:3000 or http://10.0.2.2 for android emulator');
});
```

```
Error: Network Error
```

I found some articles on stackoverflow and a lot more from my duckduckgo search but I wasn't able to find any answer.

###### NOTE

- I'm running my app via the expo app downloaded on my android phone. I'm not using any VMs to run my frontend and backend.
- I have tried 10.0.2.2:3000. Same result.
- I have tried my own IP. Same result.
- I have tried to search the best places that I know of, but I couldn't find any answers.

Help please.

**Comment by aprilmintacpineda** [comment]
I think it would be good to add these kind of info to the docs. "Making network requests to your localhost". Then add "Using an emulator." and "Using your phone.".

**Comment by aprilmintacpineda** [comment]
I think I found the reason why... https://docs.expo.io/versions/v27.0.0/workflow/debugging#if-you-are-using-lan-make-sure

**Comment by aprilmintacpineda** [comment]
I'm using the CLI, and I can't see any instructions how to actually configure this thing.

**Comment by aprilmintacpineda** [comment]
After going to sleep and upon waking up, I figured out what the answer was. I seem to have forgotten networking fundamentals.

What's going on here?

I'm pretty new to expo and how it managed to push my app on my phone with wireless connection was a magic at first until I remembered networking. Basically expo pushes the app using the "lan" connection (in my case), your PC and the mobile you are using must be connected to the same network for this to work. Don't get me wrong I don't fully understand how expo works on the foundation level though I'd love to know the secret spell for its magic. (LOLS).

My computer is running the localhost server (nodejs) on `localhost` port `3000` (`localhost:3000`), so I need to make a request to the computer's port 3000 in order for this to work, unfortunately for me, I was getting my IP thru https://duckduckgo.com/?q=what%27s+my+ip%3F&atb=v113-7_y which didn't work because I'm running on LAN so it needs to be the IP on the LAN network. So what you need is `LANIP:3000/path/to/request` for this network request to work.

Find out what your IP is: https://www.wikihow.com/Check-the-IP-Address-in-Linux

Now that you know your IP address, instead of doing `http://localhost:3000/a-request` do `http://TheIpGoesHere:3000/a-request`, in this case, your phone will make a request to your PC's port 3000 where the localhost is running. Example: `http://192.168.1.2:3000/login`.

If someone can explain this better or can add more information as to why the other works and why the other ones don't, please mention me.

**Comment by cadec** [comment]
@aprilmintacpineda I have been dealing with this issue for SO long and this is the first time I was able to successfully make a network request to my localhost!!! Thank you SOOO much!!!

**Comment by chirag773** [comment]
@aprilmintacpineda Hey Im still facing the problem even i replace my localhost to my IP . Done all the things you have told to do to run the app but Im still facing the problem please help me out

**Comment by sjchmiela** [comment]
@chirag773 My suggestion would be to check if the server and the device are in the same network (if they're not, the IP won't work).

Thank you, @aprilmintacpineda, for the detailed explanation of how to make it work! 🙂

**Comment by melitus** [comment]
@sjchmiela the server and the device are on the same network but i am still getting the error

**Comment by AdamZaczek** [comment]
I actually had the exact same issue and none of the solutions worked for me. I'm using expo 30. For now I ended up deploying the backend and using remote url but offline solution is something I really need. @aprilmintacpineda 's answer is excelent (thanks man!)and to my suprise even that did not help.

**Comment by jstarw** [comment]
I am also having the same issue, and I am on the same Wifi network.

**Comment by AleksandarSavic95** [comment]
What helps when testing from a real device is to use a service like [ngrok](https://ngrok.com/). It is easy to setup (3 minutes or so).
After that, just change the url in your config from `localhost` to something like `http://44dd0123.ngrok.io`
Good luck :)

**Comment by aleksanderkaminski** [comment]
☝️ @AleksandarSavic95  I had a problem with connecting to local server from iPhone expo client, used ngrok and it works perfectly. Thanks!
