### ISSUE TITLE
exp-cli throws warning when npm not installed

### ISSUE THREAD

**Issue by riwu** [expo/expo#1608]
I don't have `npm` and installed the exp-cli with `yarn`.
Whenever I run `exp start`, it throws a warning:
> [exp] `npm` command not found. If you have npm installed please run `npm install -g exp && exp path`.

exp version: 51.4.0
yarn version: 1.5.1
node version: v9.10.1
OS: mac Sierra 10.12.6

**Comment by esamelson** [comment]
Hi there - this is because virtually all systems that have node installed will have `npm` by default. Most `exp` commands will use `yarn` if it's available, but we can't guarantee that everything will work as expected if `npm` is not installed. To get rid of this warning, I'd suggest installing `npm` again, as lots of node-related things will expect it to exist.
