### ISSUE TITLE
Package expo-modules-core has been ignored, after upgrading expo to 44

### ISSUE THREAD

**Issue by AlenToma** [expo/expo#16085]
### Summary

Getting `warn Package expo-modules-core has been ignored because it contains invalid configuration. Reason: "dependency.platforms.ios" must be of type object` when I build my project.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44.0.2

### Environment

  Expo CLI 5.0.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ^44.0.2 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: bare

### Reproducible demo

Just upgraded my expo to 44 and this started to happen

**Comment by brentvatne** [comment]
this warning is coming from react-native-community autolinking. it looks like the api changed and they don't accept null values anymore, but this is [what they still specify in their docs](https://github.com/expo/expo/blob/main/packages/expo-modules-core/react-native.config.js). the behavior you see is expected still - expo-modules-core is and should be ignored by react-native-community autolinking, because it's handled by expo autolinking.

**Comment by AlenToma** [comment]
Yah, it did not couse any error. just been worried if it will impact other components that is using it. I should close this then thx alot.
