### ISSUE TITLE
Cannot run test with fetch() - TypeError: Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by bialasik** [expo/expo#1609]
### Environment

10:50:10 [exp] There is a new version of exp available (51.4.0).
You are currently using exp 50.0.1
Run `npm install -g exp` to get the latest version
10:50:10 [exp] Generating diagnostics report...
10:50:10 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.1.0
  Yarn: 1.2.1
  npm: 4.1.2
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.2 AI-145.3330264

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/mselerowski-4a7bb25e-c2bc-44a2-be21-827db91b744f.tar.gz

### Steps to Reproduce

.babelrc
```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    },
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}

```

App.test.js
```
import React from 'react';
import App from './App';
import renderer from 'react-test-renderer';

it('renders without crashing', () => {
    const rendered = renderer.create(<App />).toJSON();
    expect(rendered).toBeTruthy();
});
```

and usage of fetch() in one of App's files

### Expected Behavior

test passed

### Actual Behavior

```
TypeError: Cannot read property 'fetch' of undefined
      
      at node_modules/whatwg-fetch/fetch.js:1:139
      at Object.<anonymous> (node_modules/whatwg-fetch/fetch.js:1:9985)
      at Object.<anonymous> (node_modules/jest-expo/src/setup.js:1:482)
```

What should I do?

**Comment by ide** [comment]
If you comment out fetch within your code, do you still experience the issue? I'd recommend running Jest with `--debug-brk` and hooking up the Chrome debugger to Node (see the Jest instructions on debugging tests) to figure out what's going wrong and how to fix it.

**Comment by bialasik** [comment]
Yeah, it's still broken even after commenting fetch() code. This error came from whatwg-fetch library.

I found that issue is because of 'transform-es2015-modules-commonjs' used as plugin for babel.
But after changing it I have error that 'import' is a unexpected character. How can I fix this?

**Comment by bialasik** [comment]
```
SyntaxError: Invalid or unexpected token

    > 1 | import { Image, Platform, StyleSheet, TouchableOpacity, View } from 'react-native';
      2 | import React from 'react';
      3 | import Icon from 'react-native-vector-icons/MaterialIcons';
      4 | import { Actions } from 'react-native-router-flux';
```

**Comment by kulack** [comment]
I'm also hitting this issue.

**Comment by ide** [comment]
If you're hitting the import error, that means a Babel transform isn't running as expected. Diving into Jest internals is probably the best way to proceed.

**Comment by christopher-dierkens** [comment]
@ide  This is most likely a mismatch in what version of 'whatwg-fetch' is installed. 

// The next line expects whatwg-fetch@2.0.4
https://github.com/expo/expo/blob/sdk-32/packages/jest-expo/src/setup.js#L7

as defined in the top level package.json
https://github.com/expo/expo/blob/8864b1cd7ce15f5f9e058360d6474e2d02d455fd/packages/expo/package.json#L140

If I as a user pull in a completely separate package that has whatwg-fetch@3.0.0 as a dependency, or I just install it myself in my own top level package, then
`const { Response, Request, Headers, fetch } = require('whatwg-fetch');`
will fail because v3 does not export `fetch`.

The fix here is to add whatwg-fetch@2.0.4 to the jest-expo dependencies on the sdk-32 ( https://github.com/expo/expo/tree/sdk-32/packages/jest-expo) branch and publish a patch.

**Comment by skript-cc** [comment]
I'm hitting the same error.

```
TypeError: Cannot read property 'fetch' of undefined

      at node_modules/react-native/Libraries/vendor/core/whatwg-fetch.js:6:12
      at Object.<anonymous> (node_modules/react-native/Libraries/vendor/core/whatwg-fetch.js:486:3)
      at Object.<anonymous> (node_modules/jest-expo/src/setup.js:7:47)
```

Yarn seems to have installed whatwg-fetch@2.0.4, but looking at the stack trace, it looks like jest loads a forked whatwg-fetch from react-native. Probably that's not 2.0.4. Maybe this is introduced after the upgrade to react-native 0.57.1 in expo sdk 31.0.0.

I don't know if there is a way to make node require the installed 2.0.4 version, or if this has to be fixed here: https://github.com/expo/expo/blob/sdk-32/packages/jest-expo/src/setup.js#L7

**Comment by ide** [comment]
In `jest-expo@33`, we've added `whatwg-fetch@^3.0.0` as a dependency and have removed `whatwg-fetch` from the `expo` package's dependencies. Additionally, jest-expo's setup script defines `self` since whatwg-fetch expects it to be defined. 

From the synopsis above, this will make jest-expo more resilient to versions of whatwg-fetch pulled in by other packages. I'm going to close this issue and if it reoccurs in SDK 33, please open a new issue.
