### ISSUE TITLE
Segment analytics not working on Android emulator

### ISSUE THREAD

**Issue by caroldq55** [expo/expo#16203]
### Summary

I used `expo-analytics-segment` to do Segment analytics for react native project in Expo Go, but it's working only on IOS simulator, not on Android emulator (I can't see any data coming through when testing on Android emulator).

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

41.0.1

### Environment

Expo CLI 4.8.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
      Watchman: 2021.09.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.12.63 => 0.12.82 
      expo: ^41.0.1 => 41.0.1 
      react: 16.14.0 => 16.14.0 
      react-dom: 16.14.0 => 16.14.0 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: 0.16.2 => 0.16.2 
    Expo Workflow: managed

### Reproducible demo

**Steps to Reproduce**
```
// App.tsx
import * as Segment from 'expo-analytics-segment';
...
Segment.initialize({
  iosWriteKey: segmentReactNativeSourceWriteKey,
  androidWriteKey: segmentReactNativeSourceWriteKey,
});
...
```

```
// in other component
import * as Segment from 'expo-analytics-segment';

Segment.identifyWithTraits(id, someTrait);
```

**Expected Behavior**
Segment analytics running on both os - iOS and Android simulator

**Actual Behavior**
Segment analytics is working as expected on iOS simulator but not on Android emulator. I can only see identifyWithTraits call triggerred when testing on IOS simulator. And no error message shown when running apps.

**Comment by VictorHortonHA** [comment]
Having the same problem with Expo 44.0.0 Managed workflow

**Comment by brentvatne** [comment]
hi there! this isn't a priority for us at the moment because we plan to deprecate expo-analytics-segment. we now recommend using the official segment library instead: https://github.com/segmentio/analytics-react-native#readme

**Comment by Asgaroth** [comment]
Just want to bring up that https://github.com/segmentio/analytics-react-native#readme does not work with Expo-managed workflows, so it is not an option unless you eject. Plus it is in beta and not advised to be used in production.

Or am I missing something?

**Comment by mbyrne00** [comment]
Yep - confusing indeed for us all. Which version can we use with managed workflow? Or is all hope now lost for expo managed and segment?

**Comment by isaachinman** [comment]
@brentvatne Can we have an official response regarding managed workflows?

**Comment by brentvatne** [comment]
@isaachinman - we have deprecated expo-segment in favor of the official library. you can use the official library in the managed workflow, just not with classic builds (which are on the deprecation path and the last release we will support them is SDK 46 this summer). you can use the library with development builds and EAS Build.

I added some clarification to the README in this PR: https://github.com/segmentio/analytics-react-native/pull/517

**Comment by mbyrne00** [comment]
So there is a loss of support for non-eas build managed workflow. It seems like quite a harsh approach to force people down the dev client path just for an analytics lib when so many other libs work fine.

For me (and probably many others) the deprecated library is working fine and I'm not noticing any issues. From the outside it seems there is some core/basic api functionality that should not require anything special. Beyond this there are some more advanced use cases that require more privileges. Why make life so hard for the large number of people who want basic functionality? Could the library be broken up a bit better with a `core`/`basic` component that works fine with expo go, and further components that require porting to dev client or eject?

**Comment by isaachinman** [comment]
Agreed with @mbyrne00's suggestion. At its simplest form, this package should be an extremely lightweight HTTP client wrapper. OS-level hooks/events should be opt-in.

**Comment by brentvatne** [comment]
i agree it would be fantastic to a library that provides access to basic features built on top of web primitives like fetch. when we first started building expo go we were optimistic that people would do this, however it turns out that most platforms want to take advantage of features that are only available natively or, at least, not through the react-native core api. we are not the best people to build these js library wrappers for each service - that seems more in line with what the individual service providers would build if they felt it would benefit them and their customers.

i want to clarify that it's not necessary to switch to dev client to use the official segment library - you can avoid calling into it when you're in an expo go environment and just log instead. you could do one dev client build just to get things working, and then switch back to expo go. here's how that might work: https://github.com/brentvatne/segment-expo-go-example

the main file of interest: https://github.com/brentvatne/segment-expo-go-example/blob/master/Analytics.js

notice how i only import `@segment/analytics-react-native` when the native module is defined. this means that when you build your app with EAS Build (either for dev client or standalone release), the native module will be available and we'll call into it. in development, we'll fall back to just logging.

we are deprecating the expo-segment library because it is already falling behind what is possible with `@segment/analytics-react-native` and it is not going to be beneficial in the medium-long term for us to duplicate efforts on this front. you'll be able to keep using it for a while, and even when we stop releasing new versions of it the existing version should continue to work in one or two (or possibly more) of the following sdks when built with EAS Build, just not in expo go.

**Comment by Asgaroth** [comment]
@brentvatne, thank you for the thoughtful response. Very much appreciated.
