### ISSUE TITLE
[docs] expo linking

### ISSUE THREAD

**Issue by fabien-h** [expo/expo#16235]
### Summary

The documentation about the linking module give the following example :

`Published app in standalone: myapp://path/into/app?hello=world`

But his is not what happen. When you parse the given url with `Linking.parse('myapp://path/into/app?hello=world');`, you get his object :

```
{
  "hostname": "path",
  "path": "into/app",
  "queryParams": Object {
    "hello": "world",
  },
  "scheme": "myapp",
}
```

The issue is that after reading the doc, most people would do something like `const {path} = Linkin.parse(...`. But they would not find what they expect there because the first element of the path is actually in the hostname.

The documentation could explain the urls that way :

`myapp://path/into/app?hello=world`

is :

`_scheme_://_hosname_/_path_?_queryParams_`

- scheme ex: `my_app`, `myapp`
- hostname ex: `hello`, `hello.com`, `hello_com`
- path ex: `root`, `root/sub, root/sub/sub`
- queryParams ex: `hello=world`, `hello=world&hello2=world2`

### Link to the related docs page

https://docs.expo.dev/guides/linking/

**Comment by byCedric** [comment]
Hi @fabien-h! Technically, the response from  `Linking.parse('myapp://path/into/app?hello=world')` is correct. As you mentioned, it tries to parse the URL by `<scheme>://<host>/<path>?<qp>`. Because `path` is listed in the `host` section here, it's considered to be the host.

Try to parse `Linking.parse('myapp:///path/into/app?hello=world')` instead. This explicitly leaves the `host` empty, and starts the path at the 3rd `/`.

Hoep this helps!

**Comment by fabien-h** [comment]
You are technically correct. But the documentation is unclear.

If you could just change:
`Published app in standalone: myapp://path/into/app?hello=world`

By:
`Published app in standalone: myapp://hostname/path/into/app?hello=world`

It would make the behaviour more obvious to the reader.

**Comment by Simek** [comment]
For some reason I was not able to link the PR properly, but this has been fixed in:
* #16881
