### ISSUE TITLE
An unidentified property of certain Expo projects may be causing the tunnel to fail

### ISSUE THREAD

**Issue by austinyearlykim** [expo/expo#1626]
`Switched to a LAN URL because the tunnel appears to be down. Only devices in the same network can access the app. You can restart the project to try reconnecting.`

This is on the Expo XDE (fresh download yesterday) .

I am able to tunnel on a new project 100% of the time, but not the current one i've been working on for the past few weeks or so. This is beyond my knowledge of how Expo works and I understand that there have been threads before about this issue, this is a case where we have some sort of independent variable.  An old project vs. new project...

My current project was working just a few days ago... I'm hesitant to work on a new project just to have this happen again later.  Has something fundamentally changed that's been overlooked?  Can I look anywhere to help someone dive deeper?

I am on the same wifi connection and clearing the XDE cache every time i attempt to tunnel.

I love Expo and think it's the way react-native should be developed.  No hate here~

Thank you

**Comment by austinyearlykim** [comment]
SOLVED FOR ME:

As a hail mary I deleted my node server directory and launched the project again and it works.  I was never interacting with it in the first place, but deleting the directory solved it for me.

It it are:
node_modules
.dockerignore
docker-compose.yml
Dockerfile
index.js
package-lock.json
package.json

Is there anything that stands out that could be a culprit?  Nested node_modules? File named index.js? nested package.json?  Is this relevant with anybody else?  

I've lost a whole day to this issue and will try to find the root of the bug later.  For now I'm moving my server logic into a new repo independent of the client.

**Comment by spuzziboss** [comment]
Where can i find this node server directory do you mean node modules?

**Comment by austinyearlykim** [comment]
@spuzziboss 

I had my custom server logic in the same project as my client.  Deleting my /server directory solved the issue.

**Comment by spuzziboss** [comment]
ok in my case i am just starting out using expo blank options where can i find such a folder?

**Comment by austinyearlykim** [comment]
short answer is you wont, in my case there was a folder I created myself that was causing the issue. sorry @spuzziboss

**Comment by customtheme** [comment]
You just need to install the latest expo version and delete the log file before restarting your application, can see the following picture.
![remove log file](https://user-images.githubusercontent.com/32156532/38943642-283b0644-435c-11e8-9251-af623eedb5a8.png)

**Comment by muniperez** [comment]
Hey guys I'm having the same issue but I don't even have a separate server. It is just a regular Exp project.

Anyone has came up with a solution?

**Comment by austinyearlykim** [comment]
@muniperez 

have you already tried @customtheme 's solution?

**Comment by ide** [comment]
Sometimes the tunnel service doesn't work (could be related to service outage or issues with the router you're behind or networking settings on your computer) in which case you can use `exp start --lan` and as long as your device is on the same LAN as your computer you can connect with a local IP (e.g. 192.168.x.x or 10.x.x.x).

**Comment by muniperez** [comment]
Hello guys,

I found the solution for the problem. The tunnel would work for clean Expo projects but would go down on my app.
Then I cleared up my app.json and added each entry until it stopped working.

The problem was the ```"googleServicesFile"``` entry, which was pointing to the root of my project. I then replaced it with the full path in my filesystem and everything works.

So, basically: 

```
"android" : {
      "googleServicesFile": "./google-services.json",
...
```

Became:

```
"android" : {
      "googleServicesFile": "/Users/<username>/<folder>/google-services.json",
...
```

**Comment by muniperez** [comment]
@ide  should I open an issue with this bug?

**Comment by ide** [comment]
Yes, please open a separate issue regarding the `googleServicesFile` entry. It's helpful when there is one GitHub issue per problem, thank you!

**Comment by spuzziboss** [comment]
thanks i reinstalled it

**Comment by terribleben** [comment]
Hi! Here's what I understand from this issue:

- Our tunnel provider might have had a problem
- But maybe a different node_modules directory in an unrelated server project was interfering somehow
- But maybe the `googleServicesFile` key in `app.json` was having some effect

I'm not sure if there's any action we can take at this moment because it's not clear what the original problem was or whether the proposed solutions are directly related. If somebody comes up with a clear repro case, can you please open a new issue? :)

**Comment by ivanfranchi** [comment]
Solution for me was really easy. Visual Studio. After closing it and restarting (Restart button from Expo XDE) Tunnel was well connected. This solved the issue with `Switched to a LAN URL because the tunnel appears to be down. Only devices in the same network can access the app. You can restart the project to try reconnecting.`

**Comment by AshwinTayson** [comment]
For me Tunnelling started working after i installed ngrok and signed into my expo account. Might help someone.
