### ISSUE TITLE
Can't build an android app AND initiate the ./gradlew clean

### ISSUE THREAD

**Issue by realtril** [expo/expo#16418]
### Summary

An ability to create an android build has stopped, that's what I got :

![Screen Shot 2022-02-23 at 5 35 11 PM](https://user-images.githubusercontent.com/53015418/155353351-5ccdda1b-f6fb-4b51-811a-6bcf1b1ff457.png)

have tried to do ./gradlew clean but received that's errors:

![Screen Shot 2022-02-23 at 5 36 12 PM](https://user-images.githubusercontent.com/53015418/155353596-f13e35cf-9de8-4131-8ddd-e3cd6f938b49.png)

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

43

### Environment

```

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^8.3.0 => 8.5.1
      expo: ^43.0.1 => 43.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.66.2 => 0.66.2
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      expo-cli: 5.0.3
    Expo Workflow: bare
```

### Reproducible demo

My issue has seen while doing 

npm start / 

AND 

cd android ./gradlew clean

**Comment by byCedric** [comment]
Hi @realtril! It seems that there are issues executing [this script](https://github.com/expo/expo/blob/sdk-43/packages/expo-updates/scripts/create-manifest-android.gradle#L6), specifically:
> Cannot run program "node"

This is likely an issue in your environment, e.g. multiple Node versions installed where one of them is incompatible. This isn't something we can help debug, because we don't have access to your environment or setup. [This might help you further.](https://github.com/realm/realm-js/issues/1448#issuecomment-340757479)

Hope this helps!

**Comment by realtril** [comment]
Thanks @byCedric  !

What helped me:

1) just rebooting the mac
2) to make sure I have debug.keystore in android/app
