### ISSUE TITLE
'Failed to download manifest from URL' error after eas build

### ISSUE THREAD

**Issue by syazwanz** [expo/expo#16452]
### Summary

I have this code in my app to check if any OTA update available:
`await Updates.checkForUpdateAsync()`

When I build the app using `eas build` and run the app, it will notify an error in my Bugsnag saying:
`Failed to download manifest from URL: https://exp.host/@xxxx/xxxx`

This issue does not occur when I build using `expo build`

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

44

### Environment

expo-env-info 1.0.2 environment info:
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.22.0 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
  npmPackages:
    expo: ^44.0.0 => 44.0.3
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-native: 0.64.3 => 0.64.3
    react-native-web: 0.17.1 => 0.17.1
  Expo Workflow: managed

### Reproducible demo

1. This code is in App.js

```
const checkAppUpdates = async () => {
  if (!__DEV__) {
    try {
      const update = await Updates.checkForUpdateAsync()
      if (update.isAvailable) {
        setIsUpdateAvailable(true)
      }
    } catch (e) {
      Bugsnag.notify(e)
    }
  }
}

useEffect(() => {
  checkAppUpdates()
}, [])
```

2. Run `eas build -p android`
3. Install and run the app as a standalone build.

**Comment by kbrandwijk** [comment]
Did you `expo publish` at least once?

**Comment by syazwancode** [comment]
> Did you run `expo publish` at least once?

No, I did not run the `expo publish`

And I just realize this from the docs [Constants.manifest does not include update related fields until updated](https://docs.expo.dev/build-reference/migrating/#constantsmanifest--does-not-include-update-related). So I guess the manifest file was not created on the first build.

And in here [No more automatic publishing before building](https://docs.expo.dev/build-reference/migrating/#no-more-automatic-publishing-before-building), it says:

> `postPublish` hooks in app.json will not be executed on build.

I guess this is also the reason the error occurred in Bugsnag as Bugsnag need this to be filled in, in order to make it work

```    "hooks": {
      "postPublish": [
        {
          "file": "@bugsnag/expo/hooks/post-publish.js"
        }
      ]
    },
```

So is that the only way to make it work now? Do I need to run expo publish every time I run a new build?

**Comment by kbrandwijk** [comment]
I'm not sure how Bugsnag works, but seeing that error, it seemed that you might need to run `expo publish` at least once to make sure the manifest exists.

But if Bugsnag uses the postPublish hook to do something, then yes, this will only happen on publish. I took a quick peek at the docs, and that seems to be the case.

**Comment by ArthurDias01** [comment]
I ran into the same error using Sentry. And also, after releasing a new Build it still errors out (even though I also ran "expo publish again")

`
...
useEffect(() => {
        async function updateApp() {
            const { isAvailable } = await Updates.checkForUpdateAsync();
            if (isAvailable) {
                await Updates.fetchUpdateAsync();
                await Updates.reloadAsync();
            }
        }
        updateApp();
    }, [])
...
`

**Comment by ArthurDias01** [comment]
Has anyone gotten an solution for this? tried everything (from changing url to https://exp.host/@user/app/) and publishing again but nothing fixed.

**Comment by syazwancode** [comment]
> Has anyone gotten an solution for this? tried everything (from changing url to https://exp.host/@user/app/) and publishing again but nothing fixed.

Nope. I've been waiting for this as well. Can't find any solutions for this right now. I'm curious how others are dealing with this 🤔

**Comment by R4m0nz3r4** [comment]
> I ran into the same error using Sentry. And also, after releasing a new Build it still errors out (even though I also ran "expo publish again")
> 
> ```
> useEffect(() => {
>         async function updateApp() {
>             const { isAvailable } = await Updates.checkForUpdateAsync();
>             if (isAvailable) {
>                 await Updates.fetchUpdateAsync();
>                 await Updates.reloadAsync();
>             }
>         }
>         updateApp();
>     }, [])
> ...
> ```
> 
> new error after careful app revision:
> 
> ```
> Failed to download manifest from URL: https://exp.host/@user/app/index.exp?sdkVersion=44.0.0
> ```

I just realized that your link has no release-channel property, can this be the problem here?

> > Has anyone gotten an solution for this? tried everything (from changing url to https://exp.host/@user/app/) and publishing again but nothing fixed.
> 
> Nope. I've been waiting for this as well. Can't find any solutions for this right now. I'm curious how others are dealing with this 🤔

About two weeks ago I just started to face this problem. We've started to use EAS Build, and as long as we deal with three different apps that use the same code, we end up having to segmentize most project's variables turning our app.json into an app.config.js. In my particular case, the problem was our slugs, EAS was building the project with a given slug while operations performed locally, like publish, were using a different Slug which end up saving the manifest in the wrong folder. I believe that if you are using EAS Build, and your project is as far as complicated as mine, you might be facing something similar. Publishes always show you where to find your manifest, and this is very important information, make sure that everything matches because the manifest is out there somewhere.

In the worst-case scenario, knowing where Expo is saving a giving manifest, you can always use the `url` property in your [app.json's updates](https://docs.expo.dev/versions/latest/config/app/#updates) to point there.

Also, it's indeed necessary to perform at least one build in order to prevent the error from being thrown.

**Comment by ArthurDias01** [comment]
Unfortunattely I've tried the following without success:

change the app.json config expo.update.url from  https://exp.host/@user/app/index.exp?sdkVersion=44.0.0 to https://exp.host/@user/app.

And stills gives the error in production. (When I try it on a local release build it performs successfully)

**Comment by R4m0nz3r4** [comment]
> Unfortunattely I've tried the following without success:
> 
> change the app.json config expo.update.url from https://exp.host/@user/app/index.exp?sdkVersion=44.0.0 to https://exp.host/@user/app.
> 
> And stills gives the error in production. (When I try it on a local release build it performs successfully)

I believe that the release-channel query string is necessary in order to find where the manifest is located, as well as the sdkVersion. If you did not set one, Expo assumes that you are using the default channel.

Does [https://exp.host/`@user`/`app`/index.exp?release-channel=default&sdkVersion=44.0.0](https://exp.host/@user/app/index.exp?release-channel=default&sdkVersion=44.0.0) show you the manifest?

Replacing the 'default' channel with the production one above should do the trick, assuming that the SDK is indeed 44 in production. The info highlighted should be respectively your Expo account's name and the project's slug, you can change them if your production project is located in another account, or if it has a different slug. As soon as you access it and the manifest shows up, that's the correct link you should use on `expo.updates.url`.

**Comment by marcus-chr** [comment]
I'm getting similar error - "Failed to download manifest from URL: https://u.expo.dev/ddd8c9....".

The URL defined in `expo.updates.url` works. If I add `channel-name=staging&sdkVersion=44.0.0&runtime-version=exposdk:44.0.0&platform=android` I get the update.

Update is done by with EAS, i.e. `eas update`.

**Comment by marcus-chr** [comment]
Maybe not related but if: I experienced the same issue when having `releaseChannel` defined in `eas.json` and trying to push updates with `eas update`. Using `channel` in `eas.json` instead worked perfectly fine.

**Comment by BobbyCarelse** [comment]
> 

Can you please share a snippet of what this would look like

**Comment by ArthurDias01** [comment]
> > Unfortunattely I've tried the following without success:
> > change the app.json config expo.update.url from https://exp.host/@user/app/index.exp?sdkVersion=44.0.0 to https://exp.host/@user/app.
> > And stills gives the error in production. (When I try it on a local release build it performs successfully)
> 
> I believe that the release-channel query string is necessary in order to find where the manifest is located, as well as the sdkVersion. If you did not set one, Expo assumes that you are using the default channel.
> 
> Does [https://exp.host/`@user`/`app`/index.exp?release-channel=default&sdkVersion=44.0.0](https://exp.host/@user/app/index.exp?release-channel=default&sdkVersion=44.0.0) show you the manifest?
> 
> Replacing the 'default' channel with the production one above should do the trick, assuming that the SDK is indeed 44 in production. The info highlighted should be respectively your Expo account's name and the project's slug, you can change them if your production project is located in another account, or if it has a different slug. As soon as you access it and the manifest shows up, that's the correct link you should use on `expo.updates.url`.

After close reconfiguration of the app.json -> update.url => adding the release-channel=default on the URL did the trick for me...

**Comment by ScreamZ** [comment]
@brentvatne Any idea about that? That's a lot of supposition about the correct behavior of this. Thanks.

**Comment by BobbyCarelse** [comment]
@ScreamZ If you are migrating to EAS please follow [This Migration Guide](https://docs.expo.dev/build-reference/migrating/)

**Comment by ScreamZ** [comment]
@BobbyCarelse I'm not, I started on managed with eas directly

**Comment by BobbyCarelse** [comment]
Does your project have a index.js file

**Comment by ScreamZ** [comment]
> Does your project have a index.js file
Not directly, it is generated by eas build when building but as I'm using expo managed, I just have standard App.js without main entry

**Comment by brentvatne** [comment]
is someone able to provide a clonable minimal reproducible example? https://stackoverflow.com/help/minimal-reproducible-example

we can investigate if we get this

**Comment by selsamman** [comment]
I just wanted to say that for my app which uses eas build and traditional publish I found that when I released the production version on a separate release channel from testing version and without publishing I had the same issue.  My Updates.checkForUpdateAsync() returned an error the 'Failed to download manifest from URL' error.  After publishing, the error went away and the update was downloaded .  I have much the same code as other users had reporting this problem.

What is not clear to me is how one can submit a new build without publishing an update.  In my case I don't want to messaging the user about an OTA update since they are already up-to-date because of the App/Play store update.  Not a show stopper but there must be some way to improve this experience.

**Comment by s1mpl3** [comment]
Same thing here. SDK 46, migrated from the traditional update which worked great but now I'm stuck with that message.

**Comment by agencianeoplan** [comment]
Hello, I got the same error here. Look:

![image](https://user-images.githubusercontent.com/15374441/190248073-75569bd3-a12b-4f0b-a11a-a5acae792384.png)
![image](https://user-images.githubusercontent.com/15374441/190248118-50496f44-a9a7-40a4-b1a9-daa22086cd35.png)

Does anybody found a solution?

God bless you!

**Comment by agencianeoplan** [comment]
Hello again, Thank God, this issue was solved by changing the channel from **neoplan** to **production**.

I think the channel needs to exist. Maybe the following can be useful:
eas channel:create {channel_name}

Thank you!!!

**Comment by LucasJordi** [comment]
I sove this problem creating a channel like @agencianeoplan and configure my eas.json like this:

`eas channel:create myChannel`

eas.json:

`{
  "build": {
    "preview": {
      "channel": "myChannel"
      // ...
    },
    "production": {
      "channel": "myChannel"
      // ...
    }
  }
}
`
You can create differents channels for production and preview too.


Source: https://docs.expo.dev/eas-update/getting-started/

**Comment by jamiesyme** [comment]
It seems that you need a few details right in order for this to work correctly.

1. Set `app.json:expo.extra.eas.projectId` to your project ID seen in your project overview on [expo.dev](https://expo.dev).
2. Set `app.json:expo.updates.url` to `"https://u.expo.dev/YOUR-PROJECT-ID"`.
3. Set `app.json:expo.runtimeVersion` to `{ "policy": "sdkVersion" }`, or see the [Runtime versions and updates](https://docs.expo.dev/eas-update/runtime-versions/) guide to determine the correct value for your app.
4. Configure `eas.json` as described in the [EAS Migration](https://docs.expo.dev/eas-update/migrate-to-eas-update/#configure-your-project) guide.

In my case, I was missing step 2. My guess is that Expo tries to use an update URL meant for classic updates (ie. `https://exp.host/@user/project`) if an update URL hasn't been explicitly specified.

**Comment by dhcmega** [comment]
Hi! I Tried this, but when I try to publish using the good old way, I get this:

$ APP_TYPE=MyAppProfile1 npx expo publish --release-channel prod-opkg-a-sdk45-eas
WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
It seems like your project is configured for EAS Update. Please use 'eas update' instead.

Any ideas? thanks a lot.
