### ISSUE TITLE
No more developper menu on Android ?

### ISSUE THREAD

**Issue by ScreamZ** [expo/expo#1649]
Hey, i'm using snack and by shaking gesture I'm not getting the developper menu displayed…

It seems it is not referenced anymore in the documentation too ?

https://docs.expo.io/versions/v26.0.0/workflow/debugging#on-an-ios-device

Can you light me up ?

Thanks,
Regards

**Comment by schazers** [comment]
Hi scream! Would you mind letting us know more info. What device model do you have? What OS is it running? What version of the expo client? Sorry you're having this issue. (Keep in mind there's also a setting within the client to switch the gesture from shaking to two-finger force-touch. Did you maybe change it to that setting?)

**Comment by Klehm** [comment]
Hi !

Same problem here with a tablet Android 7.0 Archos oxygen 101b, last version of the expo client connected in tunnel mode. 
@schazers, I don't have that setting to switch either.

Any idea if it's an intentional remove ?

Thanks

**Comment by ScreamZ** [comment]
Switch feature is only available on iOS.

I'm using a `Samsung Galaxy S7 Edge (SM-G935F)` on `Android 7.0`

`Last expo client from PlayStore`

I'm asking myself if this is related to snack only, but this would be strange to not being able to use the inspector…

**Comment by terribleben** [comment]
As far as I know we still support the developer menu everywhere. Adding @esamelson to see if he can take a look.

**Comment by esamelson** [comment]
Hi @ScreamZ and @Klehm - I don't think we've ever supported the developer menu in snack on Android, since snack projects run somewhat differently from normal (bundled) react native projects.

However, the developer menu should be working fine for normal in-development projects served from `exp` or XDE. I do find that it's sometimes difficult to trigger the "shake" gesture on my device, though -- I usually resort to `adb shell input keyevent 82` which always works. Could you give that a try if you're having trouble opening the dev menu on a non-snack app?

**Comment by ikunyemingor** [comment]
`adb shell input keyevent 82` works... If you using expo and the app running in on the device, run CMD on windows as administrator then from the project directory run `adb shell input keyevent 82`
