### ISSUE TITLE
Can't use fetch after upgrading SDK 26

### ISSUE THREAD

**Issue by zerlpaMMT** [expo/expo#1650]
Hi

after i upgrade to SDK 26 i can't fetch any data.
I got the following error message:

<img width="352" alt="bildschirmfoto 2018-04-13 um 12 12 25" src="https://user-images.githubusercontent.com/22709503/38729746-3e7981a2-3f14-11e8-9401-bfec2292d44f.png">

Link to my repo: https://github.com/zerlpaMMT/mmp3Frontend_new/tree/upgradeSDK26

**Comment by terribleben** [comment]
We suspect this might be related to the introduction of Blob support in React Native 0.54 (used in Expo SDK 26). There were some changes around how fetch requests and responses are handled in React Native. The best place to start debugging is within `fetch.js`.

Since there's probably not much we can do about this on Expo's side, I'm going to stop tracking this issue. Let us know if you figured out a solution or a cause. Good luck!
