### ISSUE TITLE
[docs] Clarify that splash image can only be .png for now

### ISSUE THREAD

**Issue by geirman** [expo/expo#1654]
![2018-04-13_0855 build error](https://user-images.githubusercontent.com/1640318/38745217-c7bb6c3a-3ef8-11e8-9718-752fd59eeec2.png)

Firstly, love what you've done, huge fan of your work. 

This error was only presented when I attempted to "Publish", but shouldn't this have been caught much earlier? I've been developing in this state for a couple months now.

**Comment by schazers** [comment]
Hello! Glad you're happy using Expo :)

I think @fson or @aalices would know the underlying reason we support jpgs locally but not when publishing (sorry that I don't), but you can get around this error by just converting to a .png for now. 

I apologize if I'm saying something you already know, but .pngs are generally great for icons, splash screens, and overlays because they're much faster for the CPU to display than jpegs, which require a more complex decompression algorithm since they are lossy. Hope this helps!

**Comment by geirman** [comment]
Thanks @schazers. I was optimizing for image size, since this image compresses better as JPG than PNG. But that's interesting that the CPU has an easier time with it as a larger PNG file. THAT...I did not know and find very interesting. Thank you!

I did convert it to PNG, but I still think it's something that should be flagged earlier while developing locally rather than waiting till the build cycle (if possible)


![fq-splash](https://user-images.githubusercontent.com/1640318/38754520-08d4adda-3f17-11e8-8918-156eb75ec5fa.png)

**Comment by terribleben** [comment]
Hey there! You're right that we should provide clearer documentation about this. Right now our app builder only supports png files because  of the way we pre-embed the file in your native binary. It's possible we could add support for other formats in the future.

**Comment by geirman** [comment]
I don't think this is just a documentation issue. There should be consistency between the development process and the production build process. IOW, if JPGs aren't allowed as splash images when building for production, then they also shouldn't build in development.

**Comment by tsapeta** [comment]
Closing this issue as now I think our docs are clear enough that splash image must be a png file. Anyway, we will check out whether there is a difference between supported format in the development and production and if so, I'll create another issue for this.
