### ISSUE TITLE
Exp not seeing latest packages (since upgrade to metro bundler)

### ISSUE THREAD

**Issue by alecperkey** [expo/expo#1656]
### Issue Description

Exp is not seeing latest installed node_modules versions (since upgrade to metro bundler), and throwing warnings. It also throws a seemingly incorrect warning `[exp] Warning: Expo version in package.json does not match sdkVersion in manifest.` though my app.json consists: 

```
{
  "expo": {
    "sdkVersion": "26.0.0"
  }
}
```
For example...

Browsing my node_modules/react-navigation/package.json I see **v1.5.8 is the actual installed version.** 
Exp output is warning of old package versions (for example react-navigation exp sees 1.0.0-beta.27 )

**Where or which cache does exp cli get this incorrect 1.0.0-beta.27 from?**

I've already tried to clear the react native packager cache  (something called `metro-bundler` since expo v26 ?) as described at  https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352 
and left the latest comment with a few more details, but this issue should have enough information already  https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352/9

Repo: https://github.com/alecperkey/24/pull/6

Steps followed from expo forum link:

>These instructions are for macOS and Linux, but the general ideas apply to Windows as well.
> Stop XDE/exp, which should also stop the packager. Check your list of running processes to ensure these processes are not running.
> Delete node_modules in your project
> If your project depends on other local projects (e.g. has a file: URI in its dependencies), clear those local project’s node_modules directories too for good measure even though it’s probably unnecessary.
> Clear your Yarn or npm cache, depending on which you’re using, with yarn cache clean or npm cache clean
> Run yarn or npm i to install your dependencies again
> Run watchman watch-del-all to clear Watchman’s state
> Kill the watchman daemon process
> Delete the packager’s cache directory with rm -fr $TMPDIR/metro*
> Start XDE or exp
> With exp, run exp r -c for good measure
> And just to be sure, force quit the Expo client on your phone or simulator and re-open it.

~~Perhaps `yarn cache clean` is bugged on my environment?~~ `Exp doctor` gives the same output. ~~I'm considering backing up & deleting my entire windows temp directory... but that seems over the top~~ <-- that didn't work either

How else might I debug this? 
```
Environment:
  OS: Windows 10
  Node: 9.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4670197

Packages: (wanted => installed)
  expo: 26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/positivehead-b4f14b31-a70b-47ae-87e6-01c6503db30a.tar.gz
```

![metro-bundler-cache-problem-exp-52](https://user-images.githubusercontent.com/1241041/38771819-943a223e-3fde-11e8-8e4e-f6730bd1a8ab.png)

**Comment by alecperkey** [comment]
clearing windows `appdata/local/temp` did not help.
`yarn cache list` is showing correct versions.
...I am stumped

any ideas?

**Comment by salvatorecriscioneweb** [comment]
This comment is based on my personal experience through this issue

Had same issue, builder also trigger for some package others than exp sdk version, also some package was incorrect, getting 4-5 errors like "vx.x.x installed version does not sadisfy required version vy.y.y" and "package is not installed". fixed in this way.Therefore i tried every cache clean and so but was useless.

- Removed node_modules directory
- Updated yarn to 1.6.0
- **removed package lock ( yarn lock and package-lock files, but care about this, save it in case things goes wrong)**
- Updated global exp to latest version ( atm version current is 52.0.3 ) 
`C:\MyAppName>exp --version
52.0.3`
- Reinstalled every package using:
`yarn install`
on project folder
- Then restarted XDE ( yeah i'm using XDE ).

Now i'm getting 0 errors / warming and project seems run flawless.

# Issue:
Could be metro builder is based on package-lock? Or could yarn and npm conflicts? Problem appears when i switched from npm to yarn some times ago and upgraded to sdk version 26.0.0. But i don't think this issue is releated to exp directly, but more on npm ( or yarn ) misconfigured and mismanaged.

**Comment by alecperkey** [comment]
The [previous suggestion](https://github.com/expo/expo/issues/1656#issuecomment-381538761) DID WORK for me.

Now looking at the `package-lock.json` backed up in step 2 below(npm-generated) I see the incorrect versions `exp start` previously warned about-- the ones in OP screenshot's yellow text-- are contained in the `package-lock.json`. 

Essentially, seems `exp start` (or perhaps the metro-bundler which it uses with expo sdk 26) is comparing the `package-lock.json` versions to the `package.json`, **even when using yarn** (either 1.5.x or 1.6.0).

By putting the old backed-up `package-lock.json` back at root of the project, these warnings come back. So one could probably just remove their `package-lock.json` assuming they're using yarn. I hadn't done this when switching to yarn.

Steps:

1. update yarn to `1.6.0`
2. backup `package-lock.json` & `yarn.lock` (optional)
3. delete node_modules
4. `yarn install`
4. `exp start --clean` (might not be necessary, though I had been previously using shorthand `exp start -c --lan`) -- no more warnings
5. stop packager `ctrl+c`
6. `exp start --lan` (no more warnings)
