### ISSUE TITLE
The ios production app crashes immediately with no error

### ISSUE THREAD

**Issue by manidlou** [expo/expo#1657]
hey guys, will you please help me with this issue? I couldn't find any solution so far:

The built app `.ipa` that I get from `exp build:ios` for my app (created by `create-react-native-app`) crashes immediately at launch with no error! When I install the `.ipa` on iPhone 6 and 7plus (ios 11.3), it only shows a white screen for a second and immediately closes the app without any errors! While on android, the built app `.apk` from `exp build:android` works perfectly fine!
`react: 16.2.0`
`react-native: 0.52.3`
`expo: 25.0.0`

The strange thing is when I even build the simplest sample app using `create-react-native-app` the same thing happens: when I open the `.ipa` on device, it shows white screen for a second and immediately closes the app!

This is what happens:

![test](https://user-images.githubusercontent.com/16877268/38773570-b4da4e76-4004-11e8-9755-290cf0090b1e.gif)

I truly appreciate if anyone can help me with this!

**Comment by tsapeta** [comment]
hey @manidlou,
Have you tried uploading this `.ipa` to TestFlight and then testing if it works? I think, uploading `.ipa` directly to iOS device is not intended to work if you don't have appropriate profiles installed. It should work fine if you use a build uploaded to TestFlight.

**Comment by terribleben** [comment]
Another thing you can do is run locally with the `dev` flag set to `false` and `minify` set to `true`, which should give you the same behavior that your JS would get in production.

Certain types of JS issues (especially type issues) can cause crashes in production because React Native (and Expo) include safety checks around your JS types for performance reasons. Another way you can guard against this is to use something like Flow or TypeScript in your codebase.

**Comment by manidlou** [comment]
Well, using test flight fixed the issue. It wasn't a type-related problem. Just had to use test flight to run the app on ios. Thanks for your help guys!
