### ISSUE TITLE
Native Fullscreen Video on Android / Convenience cross-platform fullscreen video component

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#166]
Moved from: https://github.com/expo/expo-sdk/issues/39

@gkufera has some ideas for what to do here and it's on the roadmap.

**Comment by gkufera** [comment]
Note that you can create a fullscreen player that works on both platforms by making a `Video` component that fills the entire screen. This issue is just to either create an android equivalent of the iOS fullscreening available through the imperative API on `Video`, or a convenience cross-platform fullscreen video component implemented with `Video`.

**Comment by dikaiosune** [comment]
Closing in favor of https://expo.canny.io/feature-requests/p/fullscreen-video-on-android
