### ISSUE TITLE
Can't log in to Expo Go on ios.

### ISSUE THREAD

**Issue by LukeRl** [expo/expo#16667]
### Summary

On the ios version of Expo Go when I try to log in it says incorrect credentials. On the website my credentials are accepted just fine and I'm able to log in. 

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo

> try to log in via Expo Go on iOS
"Your username, email, password or one-time password was incorrect"
>try to log in via website
>log in successfully

**Comment by LukeRl** [comment]
bump. pls help anyone

**Comment by robin-garnham** [comment]
I'm also affected. I am able to login successfully, and the browser login window disappears, but the app state remains logged out.

**Comment by tcdavis** [comment]
If you are experiencing this, could you go to the Projects tab and let us know what it says after Client Version?

**Comment by robin-garnham** [comment]
Client Version: 2.23.2.1013698

**Comment by LukeRl** [comment]
> If you are experiencing this, could you go to the Projects tab and let us know what it says after Client Version?

Same client version as robin. 2.23.2.1013698

My username has no strange characters though, it's luk3r.

**Comment by tcdavis** [comment]
Thanks for the information, unfortunately I'm not able to reproduce on the that same version.  Could you try signing in to expo.dev in a mobile browser from the same device as you are experiencing the issue and let me know if the same thing happens?

**Comment by tcdavis** [comment]
Could you also share the error message that is displayed when you are not able to sign in?

**Comment by robin-garnham** [comment]
I can sign-in fine in using Safari. I don't actually get an error, upon completion of the successful sign-in, the auth modal is dismissed but the state of the application doesn't change and it looks like I'm still not logged in.

**Comment by tcdavis** [comment]
We have reproduced an issue that hopefully is the same as what is reported here.  If so, pressing the login button again should update your UI

**Comment by LukeRl** [comment]
> 

Sorry, this doesn't help. I get "Must be logged in to perform this request". I'm guessing it might have something to do with the new iOS/chrome/safari updates which may block the response to the auth attempt in a way that the client still thinks it was successful, since it's now always saying "Must be logged in to perform this request" as if I attempted another request after the login, like a redirect to a page or something.

**Comment by suhailkakar** [comment]
Hi @LukeRl @robin-garnham 

If you are still facing this issues, it might because Safari blocked the cookies. Here is how you can allow cookies 

- Open the Settings.
- Scroll down and select Safari.
- In the Safari settings, scroll down and select the Block Cookies option.
- Set the Block Cookies option to Always Allow. 

It show work :)

**Comment by muhammad-basil** [comment]
After some debugging - this worked for me:

- Open the Settings.
- Scroll down and select Safari.
- In the Safari settings -> Request Desktop Website
- Turn it off

It worked for me, might not work for you :)

**Comment by OkancanCosar** [comment]
This bug still alive...

**Comment by deepduggal** [comment]
I have this issue too on iOS!

Occurs in web browser after login (tried starting from the login button in the app and tried starting from the signup button in the app, then navigating to login via a link in the browser. Same result for both: app crash after logging in).

- Deleting data saved in iCloud didn't help.
- Deleting and reinstalling the app didn't help (be careful not to offload the app instead since the same data would be there)
- Logging into expo account directly in safari (and chrome) work with no issues.

After an initial login (the page loads the first time) that results in the app crashes, reopening the app and pressing login momentarily opens the web browser before the app crashes.

Clearing history and browsing data in settings for safari allows the website to reopen (ig bc a login cookie was cleared). That leads me to believe that the login was successful in the in-app safari web browser.

But yeah, I can't login to my account in the Expo Go app at all. Help?
