### ISSUE TITLE
"React Native version mismatch", but native and JS versions appear to match

### ISSUE THREAD

**Issue by kenhuang** [expo/expo#1680]
### Steps to Reproduce

1. XDE automatically upgrade to v2.24.3
2. Run iOS simulator getting "React Native version mismatch" error
JavaScript version: 0.52.0
Native version: 0.54.2
3. run `exp start -c` is working fine able to launch the app without issue

Workaround:
downgrade to v2.23.1 
https://github.com/expo/xde/releases/tag/v2.23.1

### Expected Behavior
should XDE upgrade automatically?

exp diagnostics
22:38:54 [exp] There is a new version of exp available (53.0.0).
You are currently using exp 52.0.3
Run `npm install -g exp` to get the latest version
22:38:54 [exp] Generating diagnostics report...
22:38:54 [exp] You can join our slack here: https://slack.expo.io/.

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.12.3
  Yarn: 1.3.2
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/ken_commit-17d6c7e6-c5fd-47d0-9538-03b44945aab9.tar.gz

**Comment by terribleben** [comment]
Interesting. 🤔 What does your project say for `sdkVersion` inside `app.json` ?

**Comment by kenhuang** [comment]
app.json:
"sdkVersion": "25.0.0"

**Comment by lc3t35** [comment]
+1 with "sdkVersion": "26.0.0",

**Comment by d41z** [comment]
@kenhuang  @lc3t35  did you solve it?

**Comment by lc3t35** [comment]
@d41z I'm still using exp cli.... For now, I don't have time/knowledge to find the origin and solve this kind of problems on XDE. So if I can work with cli, I use cli ;) do you face the issue too ?

**Comment by kenhuang** [comment]
@d41z the latest version of expo 27.0.0 and xde seems these issues.

**Comment by terribleben** [comment]
Can the original reporters verify whether this is still happening on newer versions of XDE/exp?

To make sure I understand, I think the issue was reported as this:

- `react-native` dependency in native and JS actually matches
- `sdkVersion` in app.json is correct
- But for some reason there's a warning of a version mismatch when none exists

**Comment by Rolando-Barbella** [comment]
This is happening in my app
`
  "react": "^16.4.2",
  "react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
`
My global react-native-cli vs is `react-native: 0.55.4`  I can't upgrade it more than that.

**Comment by qaz90930** [comment]
I got the same issue here: React Native version mismatch
JavaScript version: 0.56.0
Native version: 0.55.4

My Environment:
Xcode 10
High Sierra 10.13.6


expo version: 28.0.0

I have tried:
downgrade 
react-native: 0.55.4
babel-preset-react-native: 4.0.0
or
expo: 25.0.0
expo: 30.0.0

**Comment by sjchmiela** [comment]
This error may only happen if, well, JS and native versions mismatch. Where do these versions come from?

Native React Native version comes from Expo SDK. Every release blog post contains information about which RN version does, eg. SDK31 is based on React Native 0.57 ([source](https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49)):
> Expo SDK v31.0.0 is based on the recently released React Native 0.57 “September 2018”. The previous SDK release, v30.0.0, was based on React Native 0.55, “March 2018”.

JS React Native version comes, to be specific, from `node_modules/react-native/package.json`.

If the versions mismatch, it usually means `sdkVersion` in `app.json` points to an Expo SDK which uses different React Native than you have installed in your project.

Since we use [a fork of `react-native`](https://github.com/expo/react-native) where we can apply Expo-specific patches and fixes and we want to help developers use Expo more easily, we encourage/require use of GitHub-tagged package as `react-native` dependency. URL to which you should point your `react-native` dependency is always stated in release notes, eg. ([source](https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49)):
> In package.json, change these dependencies:
> - `react-native` to `"https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz"`

All in all, if `"react-native": "https://github.com/expo/react-native/archive/sdk-`**`XX`**`.0.0.tar.gz"` in `package.json` matches the `"sdkVersion": "`**`XX`**`.0.0"` in `app.json`, this problem shouldn't ever occur. 🙂 Sometimes to fix this issue, I believe, you'll need to remove `node_modules` and install the dependencies again. I hope this explanation lets you reassure your project setup is correct and ready for development!

I'll close this issue tentatively, this problem shouldn't occur in recent versions of Expo SDK and Expo CLI.
