### ISSUE TITLE
[expo-auth-session] Missing '/--/' on returnUrl

### ISSUE THREAD

**Issue by ivopr** [expo/expo#16844]
### Summary

I've set up the basic things to have a working Google signin with expo auth session, defined the `expo.originalFullName` to `at-myOrgName/myProjectName`, the `expo.scheme` to my app name (it's kind of a unique name, so we don't have trouble about having another app with the same scheme installed). Native sign in just works, but with the expo go proxy it seems to be stuck at "ValidationError: "returnUrl" must be a valid url". Then I had the brilliant idea of opening the thing in the browser de facto instead of just that internal browser, when I did it, I realized something about the following URL
```
https://auth.expo.io/at-myOrg/myProjectName/start?purposedlyOmittedByMe&returnUrl=exp%3A%2F%2F10.0.0.102%3A19000expo-auth-session
``` 
Note that the last query param `returnUrl` ends with 'expo-auth-session'. Removing it, it shows me the correct screen, a "Yes" and "No" button, to proceed or cancel the flow. Also note that after the flow finished, I wasn't redirected back to the app (I can't really find fault about this point, since the flow should've worked in the 'internal' browser).
It could be an error in my part, if so, I apologize about it beforehand. Following, we have the piece of code related
```ts
export const User: FC = observer(() => {
  const [isVisible, setIsVisible] = useState(false);
  const [request, response, promptAsync] = Google.useAuthRequest({
    expoClientId: process.env.GOOGLE_EXPO_CLIENT_ID,
    androidClientId: process.env.GOOGLE_ANDROID_CLIENT_ID,
  });
  const {
    constantStore: { colorMode },
    userStore: { getUser, uid, email, name, picture, setUser },
  } = useStores();

  useEffect(() => {
    if (response?.type === "success") {
      getUser(response.authentication.accessToken);
    }
  }, [response]);

  return (
    <>
      <Avatar />
      <Dialog>
        <Typography isTitle tx="modal-user.title" />
        {uid ? (
          <View>
            <Avatar />
            <Typography />
            <Typography />
            <Button />
          </View>
        ) : (
          <Button
            disabled={!request}
            icon="google"
            onPress={() => {
              promptAsync();
            }}
            style={{
              marginTop: Spacings["s4"],
            }}
            tx="modal-user.login-with-google"
          />
        )}
      </Dialog>
    </>
  );
});
```
I've also tried passing `useProxy: true` in `promptAsync` but faced the same thing. Again, this can be an error at my part. Thanks in advance

EDIT: after reading #16834 and #16852 we now know that the problem is a missing '/--/' instead of appending 'expo-auth-session'.

EDIT2: This seems to be related to the migration from expo linking, that changes makeUrl to createUrl. Don't really know If this is the desired behavior now.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

44

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.10 Manjaro Linux
      Shell: 5.8.1 - /usr/sbin/zsh
    Binaries:
      Node: 16.13.2 - /usr/sbin/node
      Yarn: 1.22.18 - /usr/sbin/yarn
      npm: 8.5.4 - /usr/sbin/npm
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed

Note that I'm running in WSL2 

### Reproducible demo

Don't know if the above should suffice, if not, let me know

**Comment by ivopr** [comment]
Scrolling down the issues here, seems related to #16834

**Comment by ivopr** [comment]
as mentioned by @NorthBlue333 in #16852 when the url is `https://auth.expo.io/infoAboutSignInMethod&returnUrl=baseServerUrl:19000/--/expo-auth-session` It goes back to our dev app in expo Go. So, what is missing is the '/--/' when the app is running in expo go

**Comment by mzanini** [comment]
I have the exact same issue trying to make Google auth with `Google.useAuthRequest` with Expo Go in iOS simulator. Providing additional options to `useAuthRequest` does not change anything because in the expo go simulator environment they are not taken into account. Digging into the code, this is what I have found:
1. `useProxy` is always `true` [at this line](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/providers/Google.js#L113) when in ExpoGo 
2. since `useProxy` is `true`, when using `promptAsync`, the request uses the `redirectUri` created [here](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/AuthRequest.js#L128)
3. in `getDefaultReturnUrl` [here](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/SessionUrlProvider.js#L15), the `urlPath` argument is `null` and `path` is set to `SESSION_PATH` which is `expo-auth-session` (without any slashes). 
4. As mentioned in the related issue, `Linking.createUrl` now receives a path argument that does not have a slash and creates the invalid return url that you (and I) have seen. 

One way to "resolve" this is to pass to `Linking.createUrl` the option `isTripleSlashed: true`. Unfortunately that option is not passed down from `Google.useAuthRequest` so specifying `isTripleSlashed` there is not going to change anything.

For now I just changed the code in `node_modules/expo-auth-session` to set `isTripleSlashed: true` [here](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/SessionUrlProvider.js#L19) and Google authentication works correctly.

Hope this gets fixed soon!

**Comment by otaviogaiao** [comment]
> I have the exact same issue trying to make Google auth with `Google.useAuthRequest` with Expo Go in iOS simulator. Providing additional options to `useAuthRequest` does not change anything because in the expo go simulator environment they are not taken into account. Digging into the code, this is what I have found:
> 
> 1. `useProxy` is always `true` [at this line](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/providers/Google.js#L113) when in ExpoGo
> 2. since `useProxy` is `true`, when using `promptAsync`, the request uses the `redirectUri` created [here](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/AuthRequest.js#L128)
> 3. in `getDefaultReturnUrl` [here](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/SessionUrlProvider.js#L15), the `urlPath` argument is `null` and `path` is set to `SESSION_PATH` which is `expo-auth-session` (without any slashes).
> 4. As mentioned in the related issue, `Linking.createUrl` now receives a path argument that does not have a slash and creates the invalid return url that you (and I) have seen.
> 
> One way to "resolve" this is to pass to `Linking.createUrl` the option `isTripleSlashed: true`. Unfortunately that option is not passed down from `Google.useAuthRequest` so specifying `isTripleSlashed` there is not going to change anything.
> 
> For now I just changed the code in `node_modules/expo-auth-session` to set `isTripleSlashed: true` [here](https://github.com/expo/expo/blob/a866317baefb16f0746a9e97432293057da97872/packages/expo-auth-session/build/SessionUrlProvider.js#L19) and Google authentication works correctly.
> 
> Hope this gets fixed soon!

Thank you so much. I was facing the same issue, and that works. At least I can test in development until this issue gets fixed.

😃

**Comment by matheuscouto** [comment]
Hey, I'm stil getting this error here. @mzanini fix works for now (thanks) but are there any plans to fix it soon? Or is there a new workaround that doesn't involves changing node_modules? Thanks!

**Comment by pamojadev** [comment]
i'm using ```AuthSession.makeRedirectURI({useProxy : false, isTripleSlashed : true})``` which allows the isTripleSlashed option but the url returned is not triple slashed
