### ISSUE TITLE
android debugger with expo-dev-client 0.8.4 and react-native-reanimated 2.4.1  crashes app

### ISSUE THREAD

**Issue by tyrauber** [expo/expo#16841]
### Summary

Version 2.4.1 of  react-native-reanimated resolves the android debugging crash, unless used in combination with the expo-dev-client.

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Package versions

    "expo": "~44.0.0",
    "expo-dev-client": "~0.8.4",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-reanimated": "2.4.1",
    "react-native-web": "0.17.1",
    "expo-splash-screen": "~0.14.1"

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.5.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/tyrauber/.rvm/gems/ruby-2.6.3/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: bare

### Reproducible demo

`$ expo init -t blank`
`$ yarn install react-native-reanimated@2.4.1`
Add 'react-native-reanimated/plugin' to the babel.config.js
`$ yarn android`
Enabling JS debugging. 
No crash.

Add expo-dev-client
`$ expo add expo-dev-client`
Create index.js and update package.json main:
```
import 'expo-dev-client';
import { registerRootComponent } from 'expo';
import App from './App';
registerRootComponent(App);
```
`$ expo run:android`
Enable JS debugging
Crash with a brief flash of an error. 
![android](https://user-images.githubusercontent.com/109972/160940317-00d2f050-8657-46ad-aaa0-0098a059e4b9.jpg)

No logs.

**Comment by patmay** [comment]
I'm also running into this problem

**Comment by byCedric** [comment]
The remote debugging on Android for 2.4.1 might be broken in general. [Other people also mentioned this here](https://github.com/software-mansion/react-native-reanimated/issues/2989). You could try a couple of things though:

1. Try to downgrade react-native-reanimated to `2.3.3`, that should kind of work but it's not ideal.
2. Upgrade to React Native Reanimated 2.5.x, you can do that because you are using dev clients. Note, that if you want to do this, [you'll also need to add this fix](https://github.com/software-mansion/react-native-reanimated/issues/3088#issuecomment-1074934609) to avoid "error: package expo.modules.adapters.reanimated does not exist" errors.

Hopet this helps!
