### ISSUE TITLE
[docs] Where to edit configuration schema?

### ISSUE THREAD

**Issue by bradjones1** [expo/expo#16861]
### Summary

The docs/contributing guide need to reference where the configuratoin schema, e.g. at

https://exp.host/--/api/v2/project/configuration/schema/UNVERSIONED

can be edited?

### Link to the related docs page

https://github.com/expo/expo/blob/main/docs/scripts/schema-sync.js#L22

### Anything else?

I need to update a URL in this schema (it's missing a scheme) and also potentially some content to make it clearer. See linked forum post

https://forums.expo.dev/t/docs-clarification-using-eas-build-for-ios-associateddomains/62808

**Comment by byCedric** [comment]
Hi @bradjones1! This configuration schema, or XDL schema as we used to call it, lives in the backend of our API. It's fully managed by us because every addition or change should be scrutinized before doing so. It's hard to remove things, as it could easily break a lot of apps.

What exactly is missing from this JSON schema? If you can give us a diff, [based on the JSON from the URL you linked](https://exp.host/--/api/v2/project/configuration/schema/UNVERSIONED) (or from [SDK 44](https://exp.host/--/api/v2/project/configuration/schema/44.0.0)), I can talk with the team to add it.

**Comment by byCedric** [comment]
Thanks for the diff. I applied it internally for SDK 38..45, and should be available soon (when we deploy).

> Specifically, I don't know what "Build with EAS" means.

When you run `eas build --platform ios`, we sync the capabilities for you. That happens locally and directly with the API if you let us authenticate with your Apple account. We can soo do this from CI environments too (within EAS build itself) - [see this tweet](https://twitter.com/Baconbrix/status/1514227461357199361).

Unfortunately, In case you are not using EAS, and don't have access to xcode, Apple doesn't leave us with a lot of alternatives here. [Their own docs only mention xcode as option to set this up.](https://developer.apple.com/documentation/xcode/adding-capabilities-to-your-app). So I'm not sure what we can do in that case.

Thanks again for the diff!

**Comment by byCedric** [comment]
FYI: the XDL schema changes just go merged! Will be out in next deploy.

**Comment by byCedric** [comment]
Done, it's live
