### ISSUE TITLE
[docs] How to persist metro/build cache in CI environments?

### ISSUE THREAD

**Issue by isaachinman** [expo/expo#17066]
### Summary

I've been looking for an answer to this question for about a week now – where does the Expo/metro cache live in linux environments?

I run `npx expo-cli publish` in my CircleCI workflows, to provide QA builds for my team. These take 5-7 minutes as they are fresh runs, whereas running `npx expo-cli publish` locally takes about 30 seconds.

I am already caching npm deps via CircleCI methods. I just need to cache the Expo build artefacts themselves. I believe the continuous integration docs should be updated with this info as well:

https://docs.expo.dev/guides/setting-up-continuous-integration/

### Link to the related docs page

https://docs.expo.dev/guides/setting-up-continuous-integration/

**Comment by byCedric** [comment]
Hi @isaachinman! The [default Metro cache location is this](https://github.com/facebook/metro/blob/7dca99af2e2af17921aa4a1e16b1972adc0d11e4/packages/metro-config/src/defaults/index.js#L121-L125). You can get the absolute path using:

```
$ node --print "require('path').join(require('os').tmpdir(), 'metro-cache')"
```

Before adding this to your CI pipeline, I would highly recommend testing this first. The main reason why we haven't added it to the docs is because it's Metro. It would likely speed up your build, but Metro's aggressive cache also has the tendency to cause unexpected behavior. [That's why their trouble shooting guide is mainly a "reset the cache"-guide.](https://facebook.github.io/metro/docs/troubleshooting)

> Personally, I think CI should be as reliable as possible. That's why I would recommend to let CI build it from scratch. That way, CI is basically exempt from possible caching issues across builds.

[There was also some discussion about this in the Metro repository here](https://github.com/facebook/metro/issues/331#issuecomment-446232241). Might be good to read that too.

Hope this helps!
