### ISSUE TITLE
FileSystem download large file

### ISSUE THREAD

**Issue by mchen37** [expo/expo#1706]
I am using the FileSystem API to download files. It seems that the file is loaded into RAM at some point. If I download a file larger than my iPad's 2GB RAM then the app will crash/presumably be killed by iOS due to their RAM management policies at some point during the download. Is there a way to download large files?

**Comment by jesseruder** [comment]
Hi @mchen37! No we don't currently have a way to download large files. We'd accept a PR to the FileSystem API if you're interested on working on that, otherwise it might be easiest to detach.

**Comment by cruzach** [comment]
Hi! We're currently going through our older issues, and closing any inactive ones. Since we keep Github issues for bug reports, rather than feature requests, I'm going to go ahead and close this issue (to keep things clean). Post any feature requests you have [on our Canny](https://expo.canny.io/feature-requests) so more people can see and upvote them!
