### ISSUE TITLE
Notifications coming from FCM won't work properly

### ISSUE THREAD

**Issue by Elijen** [expo/expo#1718]
When a notification is coming from a third party instead of Expo Push API there is a limited functionality.

### Background:
We have a legacy backend that has already implemented FCM notifications that work with legacy iOS and legacy Android app. We want to replace iOS and Android apps by new apps developed using Expo. To keep using FCM we get `getDevicePushTokenAsync` instead of `getExpoPushTokenAsync`. On iOS we call Google API to get a FCM token from a APNS token.

When we want to push a notification we call FCM API and it calls Apple or Google API the same way Expo Push API would do. Notifications work (except the problems below):

### Problems:
iOS & Android: `Notifications.addListener` is never fired 
Android: `notification.icon` and `notification.color` is not used

### Sources:
https://forums.expo.io/t/no-icon-or-title-in-android-notification/1544
https://forums.expo.io/t/notifications-addlistener-not-firing/9143

**Comment by Elijen** [comment]
@ide Thanks, we finally decided that migrating to Expo API will be easier than debugging FCM :-)

**Comment by Charlie-Hua** [comment]
This is how I got it work, after reading [this thread in the forum](https://forums.expo.io/t/issues-listening-to-incoming-notifications-with-native-raw-device-token-standalone-app/7003)

**Just add `experienceId` and `body` to the payload**

for example, my old app (non Expo) needs `chatroomId` from push payload to open the correct chatroom:
```js
// original payload, works on my old app
data = {
  title: 'title',
  message: 'message',
  chatroomId: 'chatroomId'
}

// new payload, works on my standalone Expo app
data = {
  title: 'title',
  message: 'message',
  experienceId: '@username/project',
  body: {
    chatroomId: 'chatroomId'
  }
}
```
Note
1. I use 3 different libraries to send push from server (rpush, node-apn, node-gcm) and got them all work after tweaking the code to add `experienceId` and `body` to the payload, so just keep trying!
1. it took me a while before figuring out what `experienceId` is, and I don't think it's necessary for push handling, since the notification is already delivered to the correct app. (to @ide , is it possible to remove the check for `experienceId` in the future?)

**Comment by ide** [comment]
@Charlie-Hua the experienceId is needed when developing in the Expo client which is why it's part of payload. For standalone apps we don't need it and could remove it, it's something we could do but probably won't focus on right now.

**Comment by Charlie-Hua** [comment]
@ide Thanks for your prompt reply, it's totally understandable.
Btw, what a great project! Thank you guys and wish you all the best!
