### ISSUE TITLE
ImagePicker - aspect on iOS not working. Square and cannot move around

### ISSUE THREAD

**Issue by Samesh** [expo/expo#1728]
The imagePicker component works well on both iOS and Android. 

The aspect ratio works perfectly on android however doesn't work on iOS. I am using create-react-native-app and I don't want to eject and use another package. 

I need to create three cropping options - Landscape, Square and Portrait. Right now I can only get square images. 

I get square dimensions for width and height when taking a picture from the camera but getting the original image dimensions when selecting from gallery.

I'm using a sample piece of code. Let me know what can be done to fix this please or another package I could use to achieve this without ejecting. Many thanks.

import React, { Component } from 'react';
import { Button, Text, ScrollView, StyleSheet } from 'react-native';
import { ImagePicker, Permissions, Constants } from 'expo';

export default class App extends Component {
    state = {
        result: null,
    };

    askPermissionsAsync = async () => {
        await Permissions.askAsync(Permissions.CAMERA);
        await Permissions.askAsync(Permissions.CAMERA_ROLL);
        // you would probably do something to verify that permissions
        // are actually granted, but I'm skipping that for brevity
    };

    useLibraryHandler = async () => {
        await this.askPermissionsAsync();
        let result = await ImagePicker.launchImageLibraryAsync({
            allowsEditing: true,
            aspect: [12, 3],
            base64: false,
        });
        console.log(result.width, result.height, "result");
        this.setState({ result });
    };

    useCameraHandler = async () => {
        await this.askPermissionsAsync();
        let result = await ImagePicker.launchCameraAsync({
            allowsEditing: true,
            aspect: [12, 3],
            base64: false,
        });
        console.log(result.width, result.height, "result");
        this.setState({ result });
    };

    render() {
        return (
            <ScrollView style={{flex: 1}} contentContainerStyle={styles.container}>
                <Button title="launchCameraAsync" onPress={this.useCameraHandler} />
                <Button
                    title="launchImageLibraryAsync"
                    onPress={this.useLibraryHandler}
                />
                <Text style={styles.paragraph}>
                    {JSON.stringify(this.state.result)}
                </Text>
            </ScrollView>
        );
    }
}

**Comment by terribleben** [comment]
Hi there! Unfortunately the `aspect` option is [only applicable on Android](https://docs.expo.io/versions/latest/sdk/imagepicker#aspect-array----an-array-with-two). This is because on iOS, the `ImagePicker` component just wraps Apple's `UIImagePickerController`, which doesn't provide any aspect ratio options.

One alternative you can use (without detaching) is to build your own custom Image Picker UI by using our [Camera](https://docs.expo.io/versions/latest/sdk/camera) API and [ImageManipulator](https://docs.expo.io/versions/latest/sdk/imagemanipulator) API. This will be more work to implement, because it won't just work "out of the box" the way ImagePicker does. But it is more powerful and you could add whatever aspect ratio UI you want.

Hope that helps!

**Comment by Samesh** [comment]
Sorry for the late reply. Thanks and I've missed it in the documentation.
