### ISSUE TITLE
[Android][expo-splash-screen] No longer working without call to SplashScreen.show(...) on react-native@0.68

### ISSUE THREAD

**Issue by thespacemanatee** [expo/expo#17296]
### Summary

After running `expo-upgrade`, `expo-splash-screen` no longer works unless I reintroduce the lines that were recently removed >12.0.0.

I have tried this on 2 separate projects, one with and one without Expo installed, and seems like the root cause is `react-native@0.68.1` not playing well with this library. Added back the lines below and the splash screen started showing again.

```java
// SplashScreen.show(...) has to be called after super.onCreate(...)
// Below line is handled by '@expo/configure-splash-screen' command and it's discouraged to modify it manually
SplashScreen.show(this, SplashScreenImageResizeMode.CONTAIN, ReactRootView.class, false);
```

Error:
```
No native splash screen registered for given view controller. Call 'SplashScreen.show' for given view controller first.
```

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

Android

### SDK Version (managed workflow only)

SDK 45 beta-8

### Environment

```
expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
        Android NDK: 21.4.7075529
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0-beta.8 => 45.0.0-beta.8 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
    Expo Workflow: bare
```

### Reproducible demo

On a new bare project (with or without Expo), install `expo-splash-screen` and run through the splash screen setup.

**Comment by wodin** [comment]
Possibly related to #17277

**Comment by Kudo** [comment]
hi @thespacemanatee! could you help to create a minimal reproducible example and upload to a github repository? i tested on a new sdk 45 project and it works for me. with the minimal reproducible example, maybe we can find out what i missed in the repro. thanks!

**Comment by raajnadar** [comment]
I had the exact same issue with expo bare, I took backup of `android` folder, ran `expo eject` on the root folder, it regenerated `android` folder with expo SDK 45 config.

I had minimal changes in the android folder reverted back them. After running everything is working now.

After sometime I will do the diff of both the folder and get back to you with what solved the issue.

I think the issue lies in the `splashscreen.xml` or `strings.xml` or `colors.xml` for splash screen related config.

**Comment by raajnadar** [comment]
Actually I used the android folder that was returned by eject cmd as it is the clone of what @Kudo tested, that is why they didn't find any issue.

https://github.com/expo/expo/tree/main/templates/expo-template-bare-minimum

Maybe we see the issue because we are upgrading, and we didn't configure something as per the docs. I was previously using react native cli.

I am doing a diff to find what solve it. Let me deploy the build to prod and confirm this is solved.

**Comment by wodin** [comment]
I'm not sure if this will help, but maybe verify the correct changes from ["Installing Expo modules"](https://docs.expo.dev/bare/installing-expo-modules/) have been applied.

Brent mentioned it in a similar iOS issue:

https://github.com/expo/expo/issues/17277#issuecomment-1119103417
