### ISSUE TITLE
Downloading iOS code error

### ISSUE THREAD

**Issue by Voyager-One** [expo/expo#1738]
1. are you blocking user connection using VPN? (I'm in PRC, gov blocked net, I have to use VPN), there is absolutely no speed when downloading ios code within procedure of ejecting.
2. by the way. even if you remove the QR scanner. using the iphone camera can show the link to expo.

**Comment by EvanBacon** [comment]
1. we are not blocking over VPN AFAIK, I have seen some posts from Russian users who have gotten it working - unfortunately it is slow due to the fact that circumventing gov-blocked-net is slow by nature 😭😓
2. This is an OS feature, the makers of said OS have blocked the in-app QR functionality (everythings getting blocked nowadays 😫). Said OS creators also have full control over the ironic feature, so... enjoy?
