### ISSUE TITLE
App crashes on standalone app - android - on fresh install 

### ISSUE THREAD

**Issue by ionut-nitu** [expo/expo#1744]
App only crashes on first install, if i click on refresh it workes after
This a release build created with ./gradlew assembleRelease
My application is detached using exp detach

![32235549_1776051332452736_804023907945283584_n](https://user-images.githubusercontent.com/25304806/39914052-844a1b52-550c-11e8-94f1-2fb16319373f.png)

**Comment by jimmylee** [comment]
@ionut-nitu hey thank you for writing in!

This is not enough information to work off of, can you please follow the guidelines provided after clicking "New Issue"? That would help us out greatly since we're actively working on many problems at the same time.

**Comment by terribleben** [comment]
Hi there! I'm going to close this since there's not enough info for us to help out here. I am actually quite curious to help identify and fix this issue, so please go ahead and open another one if you get a chance. Ideally we'd like to see your Expo SDK Version, react native version, relevant pieces of app.json if they apply, and possibly some steps we can take to repro. Thanks!
