### ISSUE TITLE
Expo monorepo guide doesn't work

### ISSUE THREAD

**Issue by MiguelNiblock** [expo/expo#17652]
### Summary

Clearly many people are hitting a wall when reading the guide on expo monorepos, and they keep commenting on a closed issue that still needs review. https://github.com/expo/expo/issues/17475
https://docs.expo.dev/guides/monorepos/

### Environment

All environments

### Reproducible demo

I don't have one at the moment but I tried several times, and plenty of others have the same issue. So perhaps somebody will provide a repro soon

**Comment by byCedric** [comment]
Hi @MiguelNiblock! It's unfortunate to hear that the monorepo guide doesn't work for you. A couple of things:

- With just saying "doesn't work", not providing context, and no repro, I'm not sure what you expect from us. There is not much we can do to help and/or solve the issue. 
- We won't review closed issues, when we close something it should always have a reason. In this case, the reporter found out the error was due to an environment issue on the reporter's side.
- In the guide we explicitly mention a couple of things to set the expectations (see items below)

**You'll need good knowledge of the tooling that you want to use**
We explicitly mention this right at the start because when using monorepos, you'll most likely run into a wide set of new issues. E.g. are the packages from the monorepo properly linked into your apps, are they built and ready to use, do you have conflicting versions of `react-native` and does that cause the app to have two `react-native` versions.

> Monorepos are not for everyone. It requires in-depth knowledge of the used tooling, adds more complexity, and often requires specific tooling configuration. You can get far with just a single repository.

On top of that, there are a lot of tooling for monorepos, each solving different problems but also causing different issues. You can combine each of these tools as well. It's not possible for us to document every possible configuration setup, and keep that up to date. Which brings me to the next point.


**We "officially" only support Yarn v1 monorepos.**
While it's possible to use Yarn v2+, npm, or even pnpm, every different package manager (and additional tool) has its own issues that you would need to fix. Because React Native is simply not compatible with plug and play setups, we won't be able to officially support that. 

<details><summary>e.g. see pnpm's doc on why `node-linker` is a configurable property</summary>

![image](https://user-images.githubusercontent.com/1203991/170502577-fc0df143-ed99-4fdd-b48b-2de52ca2ab13.png)

[source](https://pnpm.io/npmrc#node-linker))

</details>

**There are various example monorepos where Expo is being used**
I would recommend taking a closer look at those to compare them to your setup. Here are just some examples:
- [Fernando Rojo's Solito.dev](https://github.com/nandorojo/solito/tree/master/example-monorepos/blank)
- [Nrwl's Nx Expo support](https://dev.to/nx/introducing-expo-support-for-nx-3ien)
- [My EAS example monorepo](https://github.com/bycedric/eas-monorepo-example)


**Avoid `expo-yarn-workspaces` at all costs**
In the past, this used to be the only way to get Expo working inside a monorepo. Because of that, there is a lot of outdated documentation from 3rd parties on the internet that recommends using `expo-yarn-workspaces`.

The module does some tricks in the `node_modules` folder which was required for the [expo/expo](https://github.com/expo/expo) monorepo. It contains some edge cases where it's simply "not enough" or doesn't work.

---

That being said, if you run into issues I'd be happy to review a PR for the monorepo guide or test a repro.

**Comment by chris-chapin** [comment]
Would be great if the guide actually said to use yarn v1. I'll try submitting a PR.
