### ISSUE TITLE
Wrong port number

### ISSUE THREAD

**Issue by WilhelmErasmus** [expo/expo#1766]
### Environment

```
Environment:
  OS: Linux 4.13
  Node: 9.8.0
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2


```

The diagnostic report does not seem to generate in a timely manner. I will leave it running and add output if it produces any more.

Target: Android

### Steps to Reproduce

1. Run `expo start --lan`

### Expected Behavior

The project should generate a QR code and URL pointing to the MetroBundler instance.

### Actual Behavior

```
Starting Metro Bundler on port 19001.
13:54:19 [exp] Metro Bundler ready.
13:54:21 [exp] Tunnel connected.
13:54:22 [exp] Expo is ready.          
<QR CODE>
13:54:22 [exp] Your URL is: exp://192.168.x.x:19000

```

**Comment by esamelson** [comment]
@WilhelmErasmus - are you talking about the mismatch between the port numbers 19001 and 19000? If so, that's expected behavior -- `exp` serves different things on different ports and the client app should know how to request everything properly. Are you unable to open your app by scanning the QR code or opening the URL on your Android device?

**Comment by WilhelmErasmus** [comment]
Sorry, I noticed this when I was going through the Expo config files. I'm not sure why I couldn't connect. It seems to be working fine now.
