### ISSUE TITLE
SRCROOT not wrapped in quotation marks everywhere

### ISSUE THREAD

**Issue by rayraymond** [expo/expo#1772]
### Environment

ExpoKit, iOS

### Steps to Reproduce

1. Run the iOS simulator on a project that's within a directory structure with spaces, i.e. Documents/Directory With Spaces/Project Name
2. Observe any error logs that appear

### Expected Behavior

I expected the simulator to display the app as normal.

### Actual Behavior

Instead, I got an error that on line 4 of the build script "Script-B5722AD01DFB7E3F0084848F" that the pushd command couldn't resolve my directory. I checked out the file and saw that this code on line 4:

`pushd ${SRCROOT}/..`

From my understanding, pushd cannot resolve spaces in SRCROOT unless it's wrapped in quotations. So it seems ExpoKit will fail to build anything on ios or android if the project lives in a directory with spaces.

Best,

**Comment by terribleben** [comment]
Thanks! I've added a change to our template project which will resolve this for projects created after our next release.

Since this is just template code, we can't retroactively fix a project you've already generated with `exp detach`, but you are welcome to add the quotes yourself in any existing project.

**Comment by rayraymond** [comment]
Awesome thanks for the quick response!
