### ISSUE TITLE
Expose the ability to run packager on custom port in exp

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#178]
See https://github.com/react-community/create-react-native-app/issues/108 and https://github.com/expo/xde/issues/92

**Comment by murugaratham** [comment]
any plans for this?

**Comment by fson** [comment]
The Metro bundler port is currently configurable through the `expo.packagerOpts.port` property in `app.json`, e.g.:
```json5
{
  "expo": {
    "name": "my-app",
    ...
    "packagerOpts": {
      "port": 8787
    }
  }
}
```

**Comment by dawnmist** [comment]
@fson That setting does not work, as documented [here](https://github.com/react-community/create-react-native-app/issues/108#issuecomment-385317837)

**Comment by pcgeek86** [comment]
@dawnmist So how do you run the packager on a custom port then?

**Comment by dawnmist** [comment]
@pcgeek86 I created this patch and submitted it as [a pull request](https://github.com/expo/xdl/pull/26) in order to fix the issue in expo/xdl, so that it does now use the setting.

In the thread where I documented why the setting did not work, there is also a link to the pull request that fixed this issue.
