### ISSUE TITLE
Notification repeat does not work on ios after x number of seconds.

### ISSUE THREAD

**Issue by harisbaig100** [expo/expo#18068]
### Summary

when we try to repeat a local notification after x number of seconds following docs. 

The notification does not fire and repeat does not work on IOS.

https://docs.expo.dev/versions/latest/sdk/notifications/#scheduling-the-notification-that-will-trigger-repeatedly

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### SDK Version (managed workflow only)

45

### Environment

react: ~17.0.2 => 17.0.2
react-dom: ~17.0.2 => 17.0.2
react-native: ~0.66.1 => 0.66.1
react-native-web: ~0.11.7 => 0.11.7
Expo Workflow: bare

### Reproducible demo

It's 100% and very easy to reproduce.
The Following code doesnot trigger repeated notifications on ios

```
async function schedulePushNotification() {
  await Notifications.scheduleNotificationAsync({
    content: {
      title: "You've got mail 10 seconds! 📬",
      body: 'Here is the 10 seconds body',
      data: { data: '10 seconds' },
    },
    trigger: {
      repeats: true,
      seconds:10
    },
  });
}
```

OR run this snack code on by scanning QR code and running the app on real device (ios) the notification will not appear.

https://snack.expo.dev/x8eW7jsVC

**Comment by coldfireuc** [comment]
From my experience for iOS, if repeating a trigger that is less than 60 seconds, it gives this warning: 

"Error: Failed to schedule notification. time interval must be at least 60 if repeating"

Maybe it is an Apple limitation, since it works fine on Android?! 

From Apple Docs: 
https://developer.apple.com/documentation/usernotifications/untimeintervalnotificationtrigger/1649777-init

"repeats
Specify false to deliver the notification one time. Specify true to reschedule the notification request each time the system delivers the notification. If this parameter is true, the value in the timeInterval parameter must be 60 seconds or greater."

**Comment by barthap** [comment]
I can confirm that ⬆️. Repeating worked when I set it to 61 seconds.
