### ISSUE TITLE
Strange Issue with Expo publish 

### ISSUE THREAD

**Issue by zeeshanjan82** [expo/expo#1807]
I am facing a very strange issue. I have already finished building my app using react-native with Expo and recently have deployed the app in both apple and google app stores and after I have done so everytime I run the command ‘exp publish’ it deploys a new release or updates the app on app store instead I would like it only to update the app in expo so we can test the app in expo and once we are done we can run the command ‘exp build’ and then upload the new .ipa or apk file ourselves but I find it very strange that the command ‘exp publish’ actually deployed new release with same version on the app store. Please suggest what is causing this behaviour?

**Comment by iuliuvisovan** [comment]
Hey zeenshanjan, 

This is due to the fact that both your "expo" app and your "store" app use the 'default' channel to fetch for JS updates.  This is the default behaviour. If you don't want that (and you probably don't) I suggest you look at [release channels](https://docs.expo.io/versions/latest/distribution/release-channels).

This way, you can 'tell' your native side to fetch updates from the 'production' channel, and to only be updated when you do `exp publish --release-channel production`. (Expo app will still be using 'default')

Hope this helps.

**Comment by nicknovitski** [comment]
Iuliu is correct, release channels are the way to control this behavior.
