### ISSUE TITLE
Convert react-native cli project to expo cli project

### ISSUE THREAD

**Issue by ubaid-wp** [expo/expo#18118]
### Summary

There is any way to convert my react-native cli project into expo cli project ? I want to eject my react-native project into expo cli, like epxo eject.

### Link to the related docs page

http/

**Comment by barthap** [comment]
You might want to take a look at this article: https://blog.expo.dev/introducing-expo-run-commands-835ae8da4813

As a first step, you'd need to install [Expo CLI](https://docs.expo.dev/get-started/installation/#1-expo-cli).
You don't need to convert anything in your project files, as expo-cli commands work with any non-expo react-native project and are drop-in replacements for react-native-cli:
- `npx react-native start` -> `expo start --dev-client`
- `npx react-native run-android` -> `expo run:android`
- `npx react-native run-ios` -> `expo run:ios`

Recently, we are testing versioned expo-cli (installed as a local `expo` package instead of global expo-cli) - more details in this article: https://blog.expo.dev/new-versioned-expo-cli-cf6e10632656. Then you do: `npx expo run:ios` etc...

The future step would be to [install expo modules](https://docs.expo.dev/bare/installing-expo-modules/), to be able to use [Expo SDK libraries](https://docs.expo.dev/versions/latest/).

If you have any more questions, feel free to ask in this issue 😁

**Comment by redheet** [comment]
> You might want to take a look at this article: https://blog.expo.dev/introducing-expo-run-commands-835ae8da4813
> 
> As a first step, you'd need to install [Expo CLI](https://docs.expo.dev/get-started/installation/#1-expo-cli). You don't need to convert anything in your project files, as expo-cli commands work with any non-expo react-native project and are drop-in replacements for react-native-cli:
> 
> * `npx react-native start` -> `expo start --dev-client`
> * `npx react-native run-android` -> `expo run:android`
> * `npx react-native run-ios` -> `expo run:ios`
> 
> Recently, we are testing versioned expo-cli (installed as a local `expo` package instead of global expo-cli) - more details in this article: https://blog.expo.dev/new-versioned-expo-cli-cf6e10632656. Then you do: `npx expo run:ios` etc...
> 
> The future step would be to [install expo modules](https://docs.expo.dev/bare/installing-expo-modules/), to be able to use [Expo SDK libraries](https://docs.expo.dev/versions/latest/).
> 
> If you have any more questions, feel free to ask in this issue 😁

Thanks you :)
and I change my index.js following this https://docs.expo.dev/versions/latest/sdk/register-root-component/
