### ISSUE TITLE
Push notifications not working in Expo Go

### ISSUE THREAD

**Issue by alex-fournier** [expo/expo#18280]
### Summary

I don't receive push notifications when testing app in Expo Go with physical devices. I have tested with 3 different devices (2 Android & 1 iOS). However it seems to work fine in a standalone app.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

45

### Environment

N/A

### Reproducible demo

https://snack.expo.dev/@alexfournier/test-notifs

**Comment by brentvatne** [comment]
background the app and send the notification

**Comment by alex-fournier** [comment]
I don't see the notification using Expo Go, no matter if the app is backgrounded or foregrounded. I have also tested with the `useLastNotificationResponse` hook but same result. It works well with a standalone app (production or development build) but not with Expo Go.

**Comment by Lucas-Gardini** [comment]
I'm having the same problem, notifications works withthe compiled/builded version of the app (.apk), but don't show when testing with Expo Go, any solution for this?

**Comment by chaadow** [comment]
@Lucas-Gardini same issue. I struggled A LOT.  Because i needed to implement some redirection logic when a user taps on the notificatio,  what i've done is when i'm in development, I use the expo token : 
```javascript
    token = (await Notifications.getExpoPushTokenAsync()).data;
    // token = (await Notifications.getDevicePushTokenAsync()).data;
```
Then I go on this website https://expo.dev/notifications . and send manual notifications. this allowed me to implement my redirection logic. 
then I restore back to the device token ( because I send my notifications manually through Apn and FCM ).

However, beware of custom "data" 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/1371733/209384979-875e1944-970e-4377-93da-204be3d3b39b.png">

this would work on expo go, but not on native apps. because expo-notifications. What i meant is when you do 
```
notification.request.content.data
```
the website make it work for you easily. however if you look at `notification.request.trigger`. you'll see that the `data` is in a `body` key... anyways
anyways for me i decided to use the trigger ( which is the raw/real notification payload )
```javascript
  let trigger:any = response.notification.request.trigger
      let custom = ''
// { body: { custom: 'key' } } 
      if (Platform.OS === 'ios') {
        custom = trigger.payload.body.custom
      } else {
        const obj = JSON.parse(trigger.remoteMessage.data.body ?? '{}')
        custom = obj.custom
      }
```
as you can see, for android you need to json parse, wheras for ios no need💀

since i've formatted my gcm and apns to work properly for expo-go and native builds ( I put my custom keys inside the `body` field ), i could have gone through `content` instead of `trigger` with :  `notification.request.content.data`. 

But since it was too magical and i struggled to understand the relationship +mapping + for future developers, i decided to keep this "ugly" version.

Anyways i managed to 

Also if you want a proper working deep linking example let me know i ll paste my config( when a user tap on the notification it redirects to the proper page), the one in the docs is not quite right.

**Comment by Malin88** [comment]
@chaadow I`m having some problem implementing deep links, can U show your code?
