### ISSUE TITLE
Expo Managed Workflow + EAS Build + Firebase Analytics - UIViewController instead of screen's name.

### ISSUE THREAD

**Issue by VictorioMolina** [expo/expo#18348]
### Summary

Before building my app using EAS, I could see the screens titles inside the Analytics Dashboard of my Firebase Console. Now, after building using EAS, this code:

```javascript
analytics.logEvent("screen_view", {
  firebase_screen_class: "EditProfile",
  firebase_screen: "EditProfile",
});
```

doesn't track the screen names anymore. Instead, I get the "UIViewController" and "RCTModalHostViewController" titles for all my screens.

Why? Did I miss something?

-Note: I am using the managed workflow.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android, iOS

### SDK Version (managed workflow only)

^45.0.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    Expo Workflow: managed

### Reproducible demo

Just log a screen_view event like this:

```javascript
analytics.logEvent("screen_view", {
  firebase_screen_class: "EditProfile",
  firebase_screen: "EditProfile",
});
```

and build your app using EAS.

You will notice that the "EditProfile" screen title is ignored and replaced with "UIViewController" in the Firebase Console.

In the other hand, if you do not build the app using EAS, the correct title is tracked.

**Comment by VictorioMolina** [comment]
I have also noticed in the Expo documentation that we need to use the `@react-native-firebase/app` plugin. I suppose this is optional, since the Firebase JS SDK works fine in my standalone build... is it necessary for analytics? or just optional?

**Comment by amandeepmittal** [comment]
> analytics.logEvent("screen_view", {
  firebase_screen_class: "EditProfile",
  firebase_screen: "EditProfile",
});

Not sure how you are using the `analytics` module. As per the documentation, you'll have to import the `Analytics` package as below:

```js
import * as Analytics from "expo-firebase-analytics";
```

Link: https://docs.expo.dev/versions/latest/sdk/firebase-analytics/#api

> You will notice that the "EditProfile" screen title is ignored and replaced with "UIViewController" in the Firebase Console. In the other hand, if you do not build the app using EAS, the correct title is tracked.

> I have also noticed in the [Expo documentation](https://docs.expo.dev/guides/setup-native-firebase/#adding-the-native-firebase-plugin) that we need to use the @react-native-firebase/app plugin. I suppose this is optional, since the Firebase JS SDK works fine in my standalone build... is it necessary for analytics? or just optional?

This is only applicable when using [React Native Firebase library](https://rnfirebase.io/). If, in your case, Firebase JS SDK works, then it is not necessary. We recently updated the docs to remove any confusion and you can check out the [Configuration](https://docs.expo.dev/versions/latest/sdk/firebase-analytics/#configuration) for `expo-firebase-analytics` module for more information and limitations when using Expo Go during development.

> You will notice that the "EditProfile" screen title is ignored and replaced with "UIViewController" in the Firebase Console.

If you can share a minimal reproducible example so that I can clone and test it on my end, then I am happy to take a look 👍

**Comment by VictorioMolina** [comment]
@amandeepmittal https://github.com/expo/expo/issues/19880
