### ISSUE TITLE
Can't run snack app on my Android device (using expo go)[docs] 

### ISSUE THREAD

**Issue by DabaMcD** [expo/expo#18486]
### Summary

Note: I put this in the docs category simply because I didn't want to put it in any other category, though this category probably doesn't fit either.

When I try to run the pre-made expo-speech example app from snack on my own android device using expo go (android), my device says:

> Something went wrong.
>
> The snack "@dabamcd/speech" was found, but wasn't released for platform "android" and sdk version "46.0.0".

(@dabamcd/speech is a duplicate snack that I made. It identical to the one which is linked in the documentation. I experienced this same error when trying to run that app on my device as well.)

I have clearly selected the "android" option on the web page. Please help!

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/speech/#usage

**Comment by keith-kurak** [comment]
Hi!

Apologies for the confusion. The newest Android version of the Expo Go app, supporting SDK 46, [is still in review with the Play Store](https://blog.expo.dev/expo-sdk-46-c2a1655f63f7), which is why you're getting that error.

One of two options will allow you to use this Snack:
1. [Download the latest Expo Go APK directly](https://blog.expo.dev/expo-sdk-46-c2a1655f63f7) (see the top of the blog post).
2.  Use the switch at the bottom of the Snack to target SDK 45 (confirmed no error in this case).

**Comment by RNtaate** [comment]
I am having a similar problem, except mine results into a connection failed error. I have tried to search on google for a long while but I have no luck.
When I run the Expo Snack app on my android phone using the Expo Go app, it says: 
> Something went wrong

And when I view the logs, I find: 
> **_Uncaught Error: java.net.ConnectException: Failed to connect to exp.host/34.135.150.141.443_**

I could really use some help.

**Note:** The Expo go app works fine when I am running a local react native expo app I built using the `npx create-react-native-app` and ran `expo start`
