### ISSUE TITLE
CLI does not show logs from devices with Korean characters in name

### ISSUE THREAD

**Issue by obov** [expo/expo#18488]
### Summary

I'm Korean junior developer.

My cmd couldn't show any logs.
Because my name in my iphone was spelled in Korean.
After changing my name saved on myphone to English , it shows well all the logs from my app.

I have solved my problem but I wish it could be fixed.

Not critical but not trivial I think~
Thanks for reading my issue~

### Managed or bare workflow? If you have made manual changes inside of the `ios/` or `android/` directories in your project, the answer is bare!

bare

### What platform(s) does this occur on?

iOS

### Package versions

expo version : 6.0.1
node version : 16.16.0

### Environment

using Window
using Iphone X

### Reproducible demo

console.log( 'debug' )

**Comment by esamelson** [comment]
Thanks for the report @obov . I was able to reproduce by changing my iPhone's name to include korean characters, running `expo start` and opening a simple app in Expo Go; no logs showed up from the device as long as the device name included korean characters.

**Comment by obov** [comment]
Thanks for your replying!
and your changing report title more precisely!

**Comment by esamelson** [comment]
Hi @obov -- this is actually fixed in the new local CLI, which you can use by running `npx expo start` (instead of `expo start`) in your SDK 46+ project. (We won't be fixing this issue in the old CLI, as we'll be focusing on supporting the new one moving forward.) Hope that helps, let us know if you're still running into this issue!
