### ISSUE TITLE
"Unsupported scheme for location" when reading document from DocumentPicker with FileSystem

### ISSUE THREAD

**Issue by SheetJSDev** [expo/expo#18534]
### Summary

Described in https://github.com/SheetJS/sheetjs/issues/2758

After using the document picker (`DocumentPicker.getDocumentAsync`), the URI is not readable using `FileSystem.readAsStringAsync`.

### Managed or bare workflow? If you have `ios/` or `android/` directories in your project, the answer is bare!

managed

### What platform(s) does this occur on?

Android

### Environment

.

### Reproducible demo

Described in https://github.com/SheetJS/sheetjs/issues/2758

**Comment by brentvatne** [comment]
looked into this more and while this isn't a valid reproducible example this does look like a legitimate issue that we should investigate

**Comment by brentvatne** [comment]
hey @SheetJSDev - thanks for reporting this. I wasn't personally familiar with this API but it looks like the developer in the issue on your repository wasn't using it properly and we may need to improve our expo-document-picker API docs to make it more clear. It's not always possible to read a file from the file system immediately after it is picked with the document picker, and the `copyToCacheDirectory` option allows you to handle making the document immediately available for use by other Expo APIs. the reason you didn't encounter this with another react-native library in your website documentation is, I believe, because there is no document picker involved.

**Comment by SheetJSDev** [comment]
Thanks for following up both here and in the linked issue!  We're not that familiar with Expo, so the initial guess was based on the documentation.

What is the recommended way of using the DocumentPicker to select a file and using the FileSystem to read the data as a base64 string, ideally without having to perform a copy?  Is there a blocking version of `DocumentPicker.getDocumentAsync` that will wait until the document is ready?

**Comment by brentvatne** [comment]
> Thanks for following up both here and in the linked issue! We're not that familiar with Expo, so the initial guess was based on the documentation.

of course! very understandable. thanks for trying to help the developer in the other issue. i know it can be tricky when someone reports an issue that is more related to another tool!

> What is the recommended way of using the DocumentPicker to select a file and using the FileSystem to read the data as a base64 string, ideally without having to perform a copy? Is there a blocking version of DocumentPicker.getDocumentAsync that will wait until the document is ready?

as far as i know, it is required to perform a copy (but i am not deeply familiar with the document picker apis on ios/android). i believe the reason this is required is that the document may actually exist in icloud, for example, and so it's necessary first to actually download it to the filesystem.

there is no blocking version of `DocumentPicker.getDocumentAsync` but this sort of API works nicely with async/await.

here's an example of doing this, you can launch this in [Expo Go](https://expo.dev/client) on your device or in the in-browser simulator if you like.

https://snack.expo.dev/@brents/load-document-as-base64-string
