### ISSUE TITLE
Expo project created with create-expo-app errors

### ISSUE THREAD

**Issue by hayata-suenaga** [expo/expo#18545]
### Summary

An Expo project created with create-expo-app causes a bundle error when ran with expo start command. I'm using Expo Go on iOS (both simulator and physical devise).

This happens with both a blank project and a typescript project that is created with -t expo-template-blank-typescript flag and argument.

One of the dependencies apparently cannot find `expo-constants` module.

[Stack Overflow question](https://stackoverflow.com/questions/73199962/expo-project-created-with-create-expo-app-errors)

### What platform(s) does this occur on?

iOS

### SDK Version

45.0.8

### Environment

```  
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 7.22.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.56.0
      expo-cli: 6.0.1
    Expo Workflow: managed
```

### Reproducible demo

[https://github.com/hayata-suenaga/create-expo-app-error](https://github.com/hayata-suenaga/create-expo-app-error)

**Comment by brentvatne** [comment]
i suspect your npm version includes a bug with arborist that was briefly live but continues to impact users who happen to have that particular npm version installed. notice in your node_modules that `expo-constants` doesn't exist at the root (ie: there is no `node_modules/expo-constants`). this should exist, because the package should be hoisted, but it does not happen. i recommend updating to the latest npm.

if i delete your package-lock.json and node_modules and re-install using npm@8.11.0 or with yarn@1 the project works as expected.
