### ISSUE TITLE
Non-interactive login not working

### ISSUE THREAD

**Issue by purduebretty** [expo/expo#1855]
### Attention

  If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here! 
  (Unless the bug/issue pertains to a standalone, non-detached build)
  
### Environment

Environment:
  OS: Windows 10
  Node: 8.9.4
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

Packages: (wanted => installed)
  expo: ^27.0.2 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/offerpaddev-c3691c33-ed04-41fc-8ddd-48a45ff47dc7.tar.gz

### Steps to Reproduce

1.  Login using username and password in Git Bash or Mac Terminal
2.  Command execution does not exit and hangs not allowing other commands

### Expected Behavior

Expect that the commandsexits successfully as it does in Powershell

### Actual Behavior

The login command hangs and needs to be exited manually.

### Reproducible Demo

Login issue and not project specific.

**Comment by quinlanj** [comment]
hey @purduebretty ,
Thanks for filing this report. 

In `log.2`, its complaining about `C:\\Users\\brett.goldman\\source\\repos\\Mobile\\offerpad-mobile\\scripts\\package.json` having invalid JSON syntax. Could you verify that its well-formed?

**Comment by purduebretty** [comment]
Hi quinlanj,

I think that error is unrelated.  I think it came from when I may have run a publish or build while in the wrong directory so it was looking for a package.json that wasn't there.  The issue I was having was with the login command which I don't believe looks for any package or config files.

**Comment by pr0da** [comment]
Hi!

We have the same problem in Bitbucket pipelines. The `exp login` command just hangs and eventually the pipeline timeouts after 120 min. The command logs out `Success` but never returns.

![image](https://user-images.githubusercontent.com/1568701/43367633-7824cf98-9350-11e8-9871-603361a44c44.png)

**Comment by pr0da** [comment]
Hi!

We have the same problem in Bitbucket pipelines. The exp login command just hangs and eventually the pipeline timeouts after 120 min. The command logs out Success but never returns.

![image](https://user-images.githubusercontent.com/1568701/43367674-2105ba96-9351-11e8-96e4-4201f1ace27f.png)

**Comment by pr0da** [comment]
In our case `exp logout` before `exp login` seems to solve this problem.

I think the explanation is the following:
The Bitbucket pipeline caches node related stuffs, and I think the previous login was kept because of the cache. If `exp login` detects an active login it just hangs with a question (in interactive mode).
If you run the `exp login` with `--non-interactive` it just fails with `You are already logged in as ...`. Unfortunately there isn't a `--confirm` or `--yes` arg to acknowledge re-login.

I guess it would be nice to turn off interactive mode when CI=true environment variable is present. Most of the CI tools set it.

Sorry for spamming this issue, now I see that our case is not related to the original one.

**Comment by quinlanj** [comment]
hi @purduebretty , 

With the current version of `exp`, @pr0da 's solution of `exp logout` should work.

There was actually a bug with the `--non-interactive` flag that we've since fixed but have yet to release in `exp` (https://github.com/expo/exp/pull/105). But in future releases, the terminal should no longer hang if the `--non-interactive` flag is passed, even if you were previously logged in.

Sorry for the inconvenience

**Comment by jakubste** [comment]
I believe `--non-interactive` works as expected by now.
