### ISSUE TITLE
Problem with EAS build: Worker configuration failed

### ISSUE THREAD

**Issue by claudiofus** [expo/expo#18610]
### Summary

I'm having this problem during the build phase called `Spin up build environment`:
```
Creating new worker instance
Worker configuration failed.
Please try again later. If the problem persists, please report the issue.
```
And then in `Fail build` section I have:
```
Build failed: Internal Server Error.
Please try again later. If the problem persists, please report the issue.
```

### What platform(s) does this occur on?

iOS

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.1 - /usr/local/bin/node
      npm: 8.12.1 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.18 => 0.3.21 
      babel-preset-expo: ^9.1.0 => 9.2.0 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: managed
```

### Minimal reproducible example

Create an EAS build and check if it works for iOS

**Comment by brentvatne** [comment]
there was a brief outage for ios builds this morning: https://status.expo.dev/incidents/6vf1bqdfp1jk

**Comment by MateuszRostkowski** [comment]
Hi I still have this issue, is there a possibility if that is my fault or this is completly on expo servers?

Error: 
```bash
Build failed: Internal Server Error.
Please try again later. If the problem persists, please report the issue.
```

<img width="1201" alt="Zrzut ekranu 2022-08-12 o 15 54 42" src="https://user-images.githubusercontent.com/38006370/184368133-8ec38e4c-9d2c-4789-abd4-876a91b7cf94.png">

**Comment by chownation** [comment]
@MateuszRostkowski I'm seeing similar issue - saw

**Comment by puuble** [comment]
Android same

**Comment by stesvis** [comment]
Same today Nov 26, 2024

```
Build failed: We've lost connection to the worker.

Two common reasons:
1. Worker ran out of memory.
   Try running your build on a large worker. Learn more at https://docs.expo.dev/build/eas-json/#selecting-resource-class
2. Worker experienced a network issue.
   This is most likely an intermittent problem. Try running the build again.
```

**Comment by hmdNetizen** [comment]
I'm experiencing the same during my build as at today Dec 16 2024

```
Build failed: We've lost connection to the worker.

Two common reasons:
1. Worker ran out of memory.
   Try running your build on a large worker. Learn more at https://docs.expo.dev/build/eas-json/#selecting-resource-class
2. Worker experienced a network issue.
   This is most likely an intermittent problem. Try running the build again.
```

**Comment by Alaa-Ben** [comment]
Same issue for Android :/

**Comment by Deji-py** [comment]
Same here , don't understand what's going on 

Build failed: We've lost connection to the worker.

Two common reasons:
1. Worker ran out of memory.
   Try running your build on a large worker. Learn more at https://docs.expo.dev/build/eas-json/#selecting-resource-class
2. Worker experienced a network issue.
   This is most likely an intermittent problem. Try running the build again.

**Comment by jay-stance** [comment]
Same today5th February 2025

**Comment by svdvs** [comment]
Seeing the same thing here

**Comment by AFDHAL2009** [comment]
Also 06 /02/2025 the same issue in preview

**Comment by kbvac** [comment]
i think we have to pass to larger worker, :)

**Comment by samuelsuu** [comment]
seeing same thing

**Comment by oldbettie** [comment]
Same issue, clearly you guys need to increase the resources for the free tier if everyones builds are failing....

**Comment by Pastorkid** [comment]
@jay-stance  @svdvs @brentvatne  @puuble @stesvis @chownation 
i just find a solution to this issue because today i myself encounter the same issue 

the first thing you have to do is to head to expo documentation here: https://docs.expo.dev/build/eas-json/#selecting-resource-class

They talk about a service worker: 

Selecting resource class
A resource class is the virtual machine resources configuration (CPU cores, RAM size) EAS Build provides to your jobs. By default, the resource class is set to medium, which is usually sufficient for both small and bigger projects. However, if your project requires a more powerful CPU or bigger memory, or if you want your builds to finish faster, you can switch to large workers.

For more details on resources provided to each class, see [android.resourceClass](https://docs.expo.dev/eas/json#resourceclass-1) and [ios.resourceClass](https://docs.expo.dev/eas/json#resourceclass-2) properties. To run your build on a worker of a specific resource class, configure this property in your build profile: 
 
{
  "build": {
    "production": {
      "android": {
        "resourceClass": "medium"
      },
      "ios": {
        "resourceClass": "large"
      },
    }
  }
}


for my use case i need to build for preview only so your eas.json file will be like this: 


{
  "cli": {
    "version": ">= 5.9.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "android": {
        "resourceClass": "medium"
      },
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "resourceClass": "medium"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

**Comment by oldbettie** [comment]
@Pastorkid for early stage apps it is not feasable to upgrade to large since its a paid feautre. At my current stage I am running 4-5 builds each day if not more. If I used large that would be $10USD per day to run my builds. The issue is how they have setup the workers, I personally think they just have bad settings and resource allocation. When I run the builds locally I use about 5gb of ram and it finished in like 6-7 minutes, but EAS falls over after 20min. I have an open thread on discord about the issue and I personally feel like its a bit of a gatcha gimmick to get people to upgrade for the paid service. If apple builds failed I would feel more strongly this way but for now its only android that times out.

**Comment by Pastorkid** [comment]
Yes @oldbettie using large workers requires you to pay but I guess medium will work for you ,I already sort out my requirements with medium. Nice meeting you sure my name is Miracle a full stack developer from Nigeria, experience in other languages and framework like nextjs, react, nodejs , JavaScript, typescript, angular, Ionic, react native, nestjs and solidity

**Comment by brentvatne** [comment]
@oldbettie - where are you builds failing? if it's during the JS bundling step then you may be able to optimize it further: https://docs.expo.dev/guides/analyzing-bundles/#analyzing-bundle-size-with-atlas - if it's during native compilation you can try precompiling parts, eg: into xcframeworks on ios. have you tried doing release builds locally or just debug builds? it could be that release builds are involving more resources or perhaps invoking a code path that causes other issues

**Comment by oldbettie** [comment]
@brentvatne Its in the gradlew build that if seems to spend the most time. The rest of the build is less then 3-4 minutes but it spends 15 minutes in gradle and then fails. I have gone through loads of optimisations over different versions of the app, it would work when I could get the timer below 20minutes but since iv added more to the app now its very hard to make any more optimisations to get it under the 20 minute mark. Iv even tried removing all the assents and fetching them at request time to reduce bundle size but still cant get under the timer that seems to cause issues.

**Comment by oldbettie** [comment]
@Pastorkid medium is the default size as explained in the docs

**Comment by yair123123** [comment]
Same

**Comment by AhmadRazaKhokhar1** [comment]
Build failed: We've lost connection to the worker.

Two common reasons:
1. Worker ran out of memory.
   Try running your build on a large worker. Learn more at https://docs.expo.dev/build/eas-json/#selecting-resource-class
2. Worker experienced a network issue.
   This is most likely an intermittent problem. Try running the build again.

**Comment by oldbettie** [comment]
@AhmadRazaKhokhar1 I don't think thats a well justifed solution. Considering the larger workers are behind a paywall its not going to be viable for most people starting out with a new app. 

I had a discussion with the team they have adjusted the settings and as such my builds now succeed. There was an issue with over allocation of memory causing the service itself to fail not so much the build. Hopefully this will improve for other people but it fixed the issue for my builds

**Comment by AhmadRazaKhokhar1** [comment]
> [@AhmadRazaKhokhar1](https://github.com/AhmadRazaKhokhar1) I don't think thats a well justifed solution. Considering the larger workers are behind a paywall its not going to be viable for most people starting out with a new app.
> 
> I had a discussion with the team they have adjusted the settings and as such my builds now succeed. There was an issue with over allocation of memory causing the service itself to fail not so much the build. Hopefully this will improve for other people but it fixed the issue for my builds

Well its the expo team's fault to not maintain the app and give solutions to the developers. I had one issue last time in the useIsDrawerOpen() hook to get the current state of drawer and it was not working. For that issue I reached out to an issue on expo repository and guess what the team had closed that issue without any solution been given. Such a dedicated team we have.
