### ISSUE TITLE
after upgrading to sdk 46 firebase 9.6.0 dont work and the error is: Unable to resolve "idb" from "node_modules\@firebase\app\dist\esm\index.esm2017.js"

### ISSUE THREAD

**Issue by arielmazor** [expo/expo#18635]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by arielmazor** [comment]
the error is Unable to resolve "idb" from "node_modules\@firebase\app\dist\esm\index.esm2017.js"

**Comment by amandeepmittal** [comment]
Hey @arielmazor, you can install the specific version for Firebase JS SDK: `9.6.11` by running the command at the root of your Expo project: `npm install firebase@9.6.11`.

This is an issue with Firebase JS SDK since they seem to be using `.cjs` file extension, which isn't supported in Expo or in React Native by default.

I can also suggest the long way in which you'll have to create `metro.config.js` at the root of your Expo project and paste the following snippet:

```js
const { getDefaultConfig } = require('@expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.resolver.assetExts.push('cjs');

module.exports = defaultConfig;
```

And then restart your Expo project.
