### ISSUE TITLE
[docs] MapView doesn't work in Expo Go client

### ISSUE THREAD

**Issue by findhumane** [expo/expo#18638]
### Summary

The [MapView documentation](https://docs.expo.dev/versions/latest/sdk/map-view/) states:

> No setup required for use within the Expo Go app.

However, creating a simple app with `<MapView />`, using `expo publish`, and running it in the Expo Go app doesn't work and `adb logcat` shows:

```
08-14 11:43:24.946 18942 19139 E Google Maps Android API: Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
08-14 11:43:24.947 18942 19139 E Google Maps Android API: In the Google Developer Console (https://console.developers.google.com)
08-14 11:43:24.947 18942 19139 E Google Maps Android API: Ensure that the "Google Maps Android API v2" is enabled.
08-14 11:43:24.947 18942 19139 E Google Maps Android API: Ensure that the following Android Key exists:
08-14 11:43:24.947 18942 19139 E Google Maps Android API: 	API Key: 
08-14 11:43:24.947 18942 19139 E Google Maps Android API: 	Android Application (<cert_fingerprint>;<package_name>): AD:15:BE:F8:B5:23:99:96:7E:E7:C1:1B:37:90:D5:84:60:27:91:7E;host.exp.exponent
```

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/map-view/

**Comment by findhumane** [comment]
Example Expo Go app demonstrating the problem: https://expo.dev/@findhumane/test849237987432

This uses [the code from the MapView example](https://docs.expo.dev/versions/latest/sdk/map-view/#usage).

**Comment by amandeepmittal** [comment]
Hi @findhumane, the issue with the latest Expo Go app and `react-native-apps` on Android has been already been reported and there is an ongoing discussion happening at #18554. We are investigating it to what's the underlying cause for it with Expo Go app. I don't think this issue is related to docs solely. I am going to close this for now but will update the docs in the future if required or if something related to the MapView component changes.
