### ISSUE TITLE
Expo Go stops doesn't load projects with runtimeVersion field set in app.json

### ISSUE THREAD

**Issue by liemdo** [expo/expo#18631]
### Summary

**Steps**
1. Our app is a bare project. Update the legacy update to the new EAS update by following the instruction: https://docs.expo.dev/eas-update/migrate-to-eas-update/
2. After starting the dev server using `expo start`, the expo Go client on my phone can't launch the app

**Workaround:** If I remove the `runtimeVersion` and `updates` options in app.json which were added by eas-cli, the expo Go client can launch the app again

Log from expo start when I tap `Try again` on expo Go client

> Manifest request: URL "/", Headers {"host":"192.168.4.38:19000","eas-client-id":"D8B9ABC9-A7DC-466B-B7E8-98335CB95CA9","expo-session":"{\"id\":\"37a0b29c-b930-4c0f-839e-3c93814f70b0\",\"version\":1,\"expires_at\":1974585600000}","user-agent":"Exponent/2.24.3 (iPhone13,1; iOS 15.5; Scale/3.00; en_US)","expo-client-release-type":"APPLE_APP_STORE","exponent-platform":"ios","expo-updates-environment":"EXPO_DEVICE","expo-json-error":"true","expo-client-environment":"EXPO_DEVICE","exponent-accept-signature":"true","expo-expect-signature":"sig, keyid=\"expo-root\", alg=\"rsa-v1_5-sha256\"","expo-api-version":"1","expo-platform":"ios","connection":"keep-alive","expo-release-channel":"default","accept-language":"en-US,en;q=0.9","expo-sdk-version":"43.0.0,44.0.0,45.0.0","exponent-version":"2.24.3","expo-accept-signature":"true","exponent-sdk-version":"43.0.0,44.0.0,45.0.0","accept":"multipart/mixed,application/expo+json,application/json","accept-encoding":"gzip, deflate"}

![IMG_C8178251E25F-1](https://user-images.githubusercontent.com/989817/181593122-9793d043-df13-4336-a5bd-9a0646e3b7cf.jpeg)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      npm: 8.4.1 - ~/ringblaze/mobility/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/mycomp/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 32
        Build Tools: 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0
        System Images: android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.0 => 44.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.5.1
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

iphone 12

### Reproducible demo or steps to reproduce from a blank project

n/a

**Comment by aballister** [comment]
> was doing the same. after eas update:configure and eas update my bare RN app can't launch expo go again. its says
> 
> ```
> Incompatible SDK version or no
> SDK version specified. This version of Expo
> Go only supports the following SDKs
> (runtimes): 46.0.0, 45.0.0, 44.0.0. A 
> custom development build must be used
> to load other runtimes
> ```

same

**Comment by A13k2** [comment]
> was doing the same. after eas update:configure and eas update my bare RN app can't launch expo go again. its says
> 
> ```
> Incompatible SDK version or no
> SDK version specified. This version of Expo
> Go only supports the following SDKs
> (runtimes): 46.0.0, 45.0.0, 44.0.0. A 
> custom development build must be used
> to load other runtimes
> ```

having the same problem...

**Comment by jdubs1994** [comment]
We are actually running into the same issue. A work around which sucks is when you want to run expo go change the runtimeVersion to policy sdk version https://docs.expo.dev/eas-update/runtime-versions/. When you want to send the build to eas you then need to change runtimeVersion to the format eas expects such as 1.0.0 or 2.122 is what im seeing from the docks. Not a great solution so hopefully the expo team has a better way of tackling this.

**Comment by zetter** [comment]
We found ourselves with this problem after we included the [`expo-secure-store`](https://docs.expo.dev/versions/latest/sdk/securestore/) package. This broke our app because the EAS update was incompatible with the previous version. Following the [runtime version docs](https://docs.expo.dev/eas-update/runtime-versions/) docs we changed our `runtimeVersion` from `{"policy": "sdkVersion"}` to a number we could control (e.g. `"1.0.1"`). This fixed our EAS update problem, but meant that we could no longer use Expo Go to run our app, even though we're still using the managed workflow.

It feels to me that the use of `runtimeVersion` is overloaded - EAS is using it to decide if updates are compatible, and Expo Go is using it to decide if you using a compatible SDK on the managed workflow or not.

We've worked round this problem for now by dynamically setting the `runtimeVersion` in our  `app.config.js` file based on an environment variable.

We added the variable config to our `app.json`:

```json
   "extra": {
      "expo_go": {
        "runtimeVersion": {  "policy": "sdkVersion"  }
      },
      "build": {  
        "runtimeVersion": "1.0.1" 
       },
    }
```

And switched to it in our `app.config.js`
```js
export default ({ config }) => {
  const runtimeTarget = process.env.DEVELOPMENT ? "expo_go" : "build";
  const runtimeVersion = config.extra[runtimeTarget].runtimeVersion;

  return {
    ...config,
    runtimeVersion,
  }
})
```

**Comment by robennals** [comment]
My impression is that you aren't really supposed to use Expo Go if you are using "eas update". You should be building a custom dev client instead (which fortunately is super-easy now).

This is a good idea anyway. If you are testing your code with Expo Go then you won't know if your update includes new native code that could crash your production app when you push it. By contrast, if you are using a custom dev client, you'll be forced to build a new dev client when you install new native code, and you bump up the runtimeVersion when you do that.

Expo Go is part of the old Expo model (along with expo build and expo publish), where the native app always contains the same fixed set of native packages and the only thing you change when you update is the javascript. In the new EAS model, each build can contain different native modules, and you build your own dev client that has those modules, rather than using Expo Go.

**Comment by zetter** [comment]
@robennals thanks for comment, I didn't know that this wasn't an expected use of Expo Go

Perhaps it could be clearer in the docs - I found [this](https://docs.expo.dev/build/updates/#previewing-updates-in-development-builds) that mentions published updates not being able to be loaded in Expo Go, but it doesn't mention development builds.

**Comment by robennals** [comment]
It's possible they just updated it. When I look at that link I see 

"Updates published with the runtimeVersion field can't be loaded in Expo Go; instead, you should use [expo-dev-client](https://docs.expo.dev/clients/introduction/) to create a development build."

But I agree the docs should be clearer about this. I banged my head against a wall for about a day on this issue until I realized that I shouldn't be using Expo Go with eas update.

**Comment by vanjaoljaca** [comment]
Running into this problem. It's not obvious that EAS and the Expo GO app are separate products. The workflow I found for developing locally involves a 5 step process of manually extracting a file onto the simulator? That's hardly reasonable

https://docs.expo.dev/build-reference/simulators/

**Comment by michaek** [comment]
It's been observed several times that Expo may expect people to stop using Expo Go after adopting EAS build. Perhaps if a codebase produces only a single app, that's feasible, but if you are producing multiple apps with the same codebase, that's slow and fails regularly (because not all aspects of the ios/ and android/ directories are managed effectively by EAS): quite often Expo Go is better.

I've talked to folks at Expo a few times about features, and they've generally seemed really surprised that someone would use Expo to produce more than one app from a single codebase. This is perplexing to me, as it seems like it would be one of the primary use cases for [dynamic configuration](https://docs.expo.dev/workflow/configuration/#dynamic-configuration).

For an app that has no additional native dependencies, there is no reason at all to require a development build instead of Expo Go. In my own usage, I exclude the features of the app that require additional native dependencies from Expo Go, only opting into a slow, error-prone development build when development against those features is required.

For the development workflow to be effective, one of two things must be true:

1. Development builds are fast and bullet-proof for projects that produce multiple apps
2. Expo Go continues to be supported and remain compatible with the overall Expo ecosystem
