### ISSUE TITLE
SDK 45.0.8 uselastnotificationresponse is not working when app killed/closed

### ISSUE THREAD

**Issue by code4muktesh** [expo/expo#18641]
### Summary

On real android device, tap to notification is not navigating to specific screen. Did some debugging and found uselastnotificationresponse is not called when app is in close/ killed.

Note: It is working when app in foreground.

"expo-notifications": "~0.15.4"

### What platform(s) does this occur on?

Android

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^45.0.8 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Minimal reproducible example

Use Firebase Cloud Messaging(FCM) notification to send  notification
Click on notification when app is closed
Use this code to handle click:
```
 React.useEffect(() => {
    if (
      lastNotificationResponse &&
      lastNotificationResponse.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER
    ) {
      try {

        const req = lastNotificationResponse.notification.request;

        let params = {};
        var content;
        if (req.trigger.remoteMessage) {
          content = req.trigger.remoteMessage;
        } else {
          content = req.content
        }

        if (content.data.navigation_screen) {
          params[content.data.navigation_param] = content.data.navigation_param_value;
          props.props.navigation.navigate(content.data.navigation_screen
            , params);
        } else {

          props.props.navigation.navigate("Notifications");
        }

      
      } catch (e) {

        Logger.Error(e, "TapHandler");
      }
    }
  }, [lastNotificationResponse]);
```

**Comment by Codelica** [comment]
I'm seeing this as well with Expo 46 and expo-notifications ~0.16.1.   When the app is in foreground o background the hook works fine, but not when Android app is fully closed/exited -- using the compiled app.  iOS works fine through all app states.  Curiously Android works fine in exited state when using Expo Go client for testing.

**Comment by code4muktesh** [comment]
Yes right, The is only with Android when Android app is fully closed/exited. Still not woking

**Comment by Codelica** [comment]
@code4muktesh is was able to to get it working my moving the creation of the listener to the very beginning of my code (top namespace, before my React component tree), storing the value, and then accessing it from the React components per info on [this issue](https://github.com/expo/expo/issues/14078#issuecomment-1249547012).

**Comment by code4muktesh** [comment]
@ Codelica It is a workaround when we can expect a fix with official release version?

**Comment by appsgenie** [comment]
> @code4muktesh is was able to to get it working my moving the creation of the listener to the very beginning of my code (top namespace, before my React component tree), storing the value, and then accessing it from the React components per info on [this issue](https://github.com/expo/expo/issues/14078#issuecomment-1249547012).

Also having this issue and with SDK 46 as well with expo-notifications ~0.16.1...
But I've tried putting the listener all the way to the top and that still has not helped..
How did you do it here?

**Comment by Codelica** [comment]
@appsgenie I'd start by setting up a `addNotificationResponseReceivedListener()` listener *very* early in App.tsx (before your components -- top namespace) and then just verifying you're getting the notification touch event passed into your handler function (via alert, console.log, Sentry, etc).   

Once you verify that, you can store the event info and process it however it best makes sense for your app.  (I send it into my linking handler to be processed by the `getInitialURL()` function.

**Comment by code4muktesh** [comment]
@Codelica @appsgenie  I tried multiple ways as suggested but nothing is working with android real device.  Please share a working code if any workaround.

**Comment by Codelica** [comment]
@code4muktesh did you try making a simple listener at the very top of the file for your root component (App.tsx/App.js/etc) to test and make sure you're getting the event?

The listener **can't be created inside any of your React components themselves**, it must be done outside of the components to be early enough to receive the event in Android when the app is fully exited/killed.  Like adding like this at the top of your file (after your imports) just to test and make sure you're getting the event:

```js
.... your other imports....

import {Platform} from 'react-native';
import * as Notifications from 'expo-notifications';

let androidExitedListener;

if (Platform.OS == 'android') {
  androidExitedListener = Notifications.addNotificationResponseReceivedListener((event) => { 
    alert('We received a touched notification event in Android');
    androidExitedListener?.remove();
  });
}

... inside your root component ...

androidExitedListener?.remove();
```

**Comment by code4muktesh** [comment]
@Codelica I tried in App.js as 
```
enableAndroidOffNotificationListener();
class App extends React.PureComponent {}
enableAndroidOffNotificationListener = () => {
  if (Platform.OS !== "android") {
    return;
  }

  androidOffNotificationListener = Notifications.addNotificationResponseReceivedListener(
    ({ notification }) => {
       alert('We received a touched notification event in Android');
    }
  );
};
```

But event not receive on real android device however working fine with expo go client

**Comment by Codelica** [comment]
@code4muktesh that seems like it could work, although I'm not wrapping the listener into a function to be called and it's a little hard to tell for sure without seeing your actual code.  But yes, the problem only shows up in the compiled app, not Go.  

Your App.js file is just exporting your App class component?  And I guess I didn't notice you're in Expo 45.0.8? (i'm in 46)  if you want to post the raw App.js code somewhere, I'll take a look. Or try just putting things in directly at the top rather than creating and calling a function, like:

```js
...your imports....

let androidOffNotificationListener;
if (Platform.OS !== "android") {
  androidOffNotificationListener = Notifications.addNotificationResponseReceivedListener(
    ({ notification }) => {
       alert('We received a touched notification event in Android');
    }
  );
}

class App extends React.PureComponent {}
... 
```

Of course this is just a test, as nothing is removing the listener, etc.

**Comment by code4muktesh** [comment]
@Codelica using expo 46, sharing raw code

```
let androidOffNotificationListener;
if (Platform.OS !== "android") {
  androidOffNotificationListener = Notifications.addNotificationResponseReceivedListener(
    ({ notification }) => {
       alert('We received a touched notification event in Android');
    }
  );
}

class App extends React.PureComponent {
async componentDidMount() {}
 render() {return (<MyComponent/>}}

}
export default App;
```
App is getting open when tap the notification but notification event is not triggered. Also, I have tried `Notifications.useLastNotificationResponse()`  
This is returning null when app is killed/close
However, It is working fine with ios and expo go ...getting issue android real device.

**Comment by Codelica** [comment]
@code4muktesh if that's your test code, then:

`if (Platform.OS !== "android")` should be `if (Platform.OS == "android")`

From what I've seen, the hook (`useLastNotificationResponse`) won't work with an exited Android app on real device, regardless where it's used.  The same goes for the async `getLastNotificationResponseAsync` call.  The only working call for a compiled Android app (currently) that's been exited is addNotificationResponseReceivedListener` done early and outside of any React component.

**Comment by code4muktesh** [comment]
@Codelica Sorry !! last time, I posted wrong code however i was using condition `Platform.OS == "android"` Now, To be double sure i tested again but still not receiving the event
```
let androidOffNotificationListener;
if (Platform.OS == "android") {

  androidOffNotificationListener=Notifications.addNotificationResponseReceivedListener(
    ({ notification }) => {
     alert('We received a touched notification event in Android');
    }
  );
}
```
 
Note: I am FCM to send notification. 
This is critical issue for my app. Could you please help me to get it fixed.? If you can create a sample app repo using working code to receive notifications and when touch the notification then navigate to specific screen. It would be really helpful. Thanks in advance.
My Env info:
```
 npmPackages:
      expo: ^46.0.15 => 46.0.15
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.9

    Expo Workflow: bare

"expo-notifications": "~0.16.1"
```

**Comment by Codelica** [comment]
Sorry, but I don't have time to put something like that together.   Navigation/linking is a completely separate topic, and because this only happens on a built and installed app, making a demo would get involving as it would involve setting up push notifications for it and a valid app id, etc.

I can tell you that the key to the specific bug of not getting the notification touch event when the Android app is killed is creating the listener with `addNotificationResponseReceivedListener`very early the file for your root component, but **outside** of any component itself (where it would be too late).   I've helped a couple other people on the Expo Discord with this bug and eventually both got it working by following that instruction.  (one had trouble when they kept putting in the component thinking it wouldn't matter, which won't work). So it does seem to be the answer. 

Since you seem to already be doing that in your example it does make me think you have something else going on though.  As I'm not using FCM, I'm using Expo's service to send alerts.  So perhaps your running into something like this:

https://github.com/expo/expo/issues/14078#issuecomment-1250902475

**Comment by code4muktesh** [comment]
uselastnotificationresponse is not working when app killed/closed is not working with android real device(sdk46). Please fix it asap.
@expo-community

**Comment by code4muktesh** [comment]
@expo-bot  Any update?

**Comment by iamromec** [comment]
uselastnotificationresponse is not working when app is killed/closed with android. Neighter is addNotificationResponseReceivedListener in Android.

**Comment by BerkePalamutcu** [comment]
its still not working any help with that?

**Comment by vkupar** [comment]
Does not work on closed Android app. `useLastNotificationResponse` returns null.

**Comment by janusqa** [comment]
response to push notifications are not working on android.  Not sure If I should post here or create a new issue for SDK 49.  Does anyone have this working?

**Comment by doublex** [comment]
@janusqa 
Same on SDK 49...

**Comment by tomkra** [comment]
I was able to get this working and read data from the notification on both Android and iOS devices. In my Android application I have this piece of code:

```javascript
// App.js
import * as Notifications from 'expo-notifications';
import { useEffect } from 'react';

Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: true,
    shouldPlaySound: true,
    shouldSetBadge: true,
  }),
});

export default function App() {
  useEffect(() => {
    if (!lastNotificationResponse) return;

    let data = null;

    if (Platform.OS === 'android') {
      data = lastNotificationResponse?.notification?.request?.trigger?.remoteMessage?.data;
    } else {
      data = lastNotificationResponse?.notification?.request?.trigger?.payload?.data;
    }

    console.log(data);
  }, [lastNotificationResponse]);


  return <></>;
}


```

But here is the catch, notification data send to firebase needs to look like this:

```ruby
def firebase_notification
  {
    data: {
      title: title,
      message: message,
      badge: user.notifications.unread.count,
      link: url,
      data: {
        link: url
      }
    },
    android: {
      priority: 'normal'
    }
  }
end
```

You have to use only `data` part of notification, when you use `title` or `body` in your notification, the data read in JS hook will be undefined. I don't know why it's behaving this way, but after I've removed `title` and `body` keys from my notification and kept then under `data` the notification hook started working and returned correct notification data.

Please note that you can't test this from Firebase Cloud Console, because google requires you to fill title of notification, but when you fill the title, payload will have `title` key and ExpoNotification will fail to read the data.

Most important part was to send notification in correct format. However if you don't have control over
sended data, I think there's currently no way to fix this.

**Comment by doublex** [comment]
@tomkra 
Strange enough it works using the legacy FCM push service...

**Comment by janusqa** [comment]
@tomkra 

I am wondering if its expo-router that is at issue here.  I do not have an app.js only a _layout.tsx in the /app directory.

I've put your above code into the _layout.tsx in the root directory of /app

on nodeJS i am creating my notification like this
```
{
	to: result.token,
	sound: "default",
	title: "My Title",
	body: "My Body",
	data: {
		notificationType: env.APP_EVENT,
		someParams: {
			param1,
			param2,
			param3,
		},
	},
}
```

I changed it to this.

```
{
	to: result.token,
	sound: "default",
	data: {
		title: "My Title",
		body: "My Body",
		notificationType: env.APP_EVENT,
		someParams: {
			param1,
			param2,
			param3,
		},
	},
}
```
In the first case the message arrives but on clicking on it it does not receive the data, 
In the second case when I moved title and body into data block no message is received at all

Can you show me the snippet where you create your message like above?

This sounds promising.

**Comment by tomkra** [comment]
@janusqa 

Maybe try remove `notificationType` key and rename `someParams` to `data` (or maybe `body`) and see if that works. Otherwise I'm not sure what can be causing problem. I have Rails as backend and I'm using this [fcm library](https://github.com/decision-labs/fcm) with HTTP V1 API to send notification.

For iOS I'm using another library and structure of data sent are like I've shown above:

Android:

```ruby
{
      data: {
        title: 'Test title',
        message: 'Test message',
        badge: 0,
        link: 'https://example.com',
        data: {
          link: 'https://example.com'
        }
      },
      android: {
        priority: 'normal'
      }
    }
```

For iOS I'm using [apns](https://github.com/jpoz/APNS):
```ruby
Push::ApnsService.new.send(
  tokens, 
  { title: 'Test title', body: 'Test message' },
  payload: { data: { link: 'https://example.com' } }
)
```
Try make notification as similar to this [example](https://docs.expo.dev/push-notifications/sending-notifications-custom/#firebase-notification-types) with green checkbox and It should work.

In my opinion docs should be updated or at least nofication format and behaviour should be better explained by someone from expo team.

**Comment by janusqa** [comment]
Thanks @tomkra 
This is interesting....
I'm not using FCM or APN directly I'm using the Expo Push API which is a middle-man that will then communicate with FCM and APN directly.  I am using NodeJS to send the messages with this SDK https://github.com/expo/expo-server-sdk-node

They have a code snippet, which is were I got the formatting for the message from.
```
// Construct a message (see https://docs.expo.io/push-notifications/sending-notifications/)
  messages.push({
    to: pushToken,
    sound: 'default',
    body: 'This is a test notification',
    data: { withSome: 'data' },
  })
```
I'll do some more digging and file a bug report for the node-sdk.

**Comment by RoyalAdvisor** [comment]
I am using Expo SDK 48.0.7. A managed workflow. This is how I got notification navigation to work when the app is killed. Works on IOS and Android.

Create this redirect function:

`function redirect(notification: Notifications.Notification) {
        const url = notification.request.content.data?.url;
        if (url) {
            replace({
                pathname: url.pathname,
                params: {
                    title: url.title,
                }
           });
       }
   }`
   
In your root app component, create a useEffect and use add this code:
   
`useEffect(() => {
    registerForPushNotificationsAsync().then((token) => setExpoPushToken(token));
    let isMounted = true;
    Notifications.getLastNotificationResponseAsync()
    .then(response => {
        if (!isMounted || !response?.notification) {
            return;
        }
        redirect(response?.notification);
    });
    const subscription = Notifications.addNotificationResponseReceivedListener(response => {
        redirect(response.notification);
    });
    return () => {
      isMounted = false;
      subscription.remove();
    };
  }, []);`
  
registerForPushNotificationsAsync() function can be found in the expo docs. I have been struggling for weeks to get notifications to navigate when the app is killed. This is what works for me.
