### ISSUE TITLE
expo-camera ImagePicker.launchCameraAsync no video option on android

### ISSUE THREAD

**Issue by rick89** [expo/expo#18759]
### Summary

Using the expo-camera plugin on iOS you have an option of image or video, on Android you only have image.

### What platform(s) does this occur on?

Android

### Environment

npx: installed 2 in 4.754s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.19 - ~/Sites/s47/app/node_modules/.bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.7 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.4 => 0.69.4 
      react-native-web: ~0.18.7 => 0.18.7 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Minimal reproducible example

I have created a snack with the problem: https://snack.expo.dev/@ric89/no-video-option-android

**Comment by hssdiv** [comment]
Temporary workaround that I use is
```
if (Platform.OS === 'android') {
      Alert.alert(
        'Select photo or video',
        'Do you want to take a photo or video?',
        [
          {
            text: 'Close',
            onPress: () => null,
          },
          {
            text: 'Photo',
            onPress: () =>
              launchCameraWithType(ImagePicker.MediaTypeOptions.Images),
          },
          {
            text: 'Video',
            onPress: () =>
              launchCameraWithType(ImagePicker.MediaTypeOptions.Videos),
          },
        ],
        { cancelable: true },
      );
    } else {
      launchCameraWithType(ImagePicker.MediaTypeOptions.All);
    }
```

and my 'launchCameraWithType' will looks something like:
```

const launchCameraWithType = async (type) => {
    const result = await ImagePicker.launchCameraAsync({
      mediaTypes: type,
      aspect: [4, 3],
      quality: 1,
      allowsEditing: true,
    });
```

**Comment by rick89** [comment]
Yeah I noticed that the photo and video options work just not “All” on android, I deployed something very similar to your suggestion to production last week. Thanks!

**Comment by dustinvforsyth** [comment]
This is still and issue. Looking deeper into the code here in in the expo-image-picker it looks like this was never meant to work on android. Probably should be documented so that developers know that. I tried to look a little deeper to see if it was just a bug but it looks like android's provided camera capture intents don't actually support launching an intent that would allow for ether an image or a video, you have to specify which intent you want either image or video before launching the capture intent. 

I am not an android developer and know very little Kotlin and Java though so I maybe wrong.

Seems like the workaround posted above by @hssdiv is likely how it should be implemented in this package for android so that the 'All' option actually works.

**Comment by R4tch3t** [comment]
why is closed if not fixed?

**Comment by bjarheim** [comment]
+1

**Comment by gustavohbeg** [comment]
já foi corrigido?

**Comment by ChristopherGabba** [comment]
Still an issue, please re-open @expo-bot.
