### ISSUE TITLE
Latest update of iOS Expo application disallows starting the projects build with SDK 21

### ISSUE THREAD

**Issue by LAITONEN** [expo/expo#1885]
I have an application, which was build with expo SDK 21. The latest update of iOS application disallows running this application, which I have been using on a regular basis. The update's release notes did not mention disablement of the support for this type of apps whatsoever.

This is being compounded by the fact that the latest Expo Desktop Client disallows the development on macOS Sierra so I can't even rebuild the application. [Details here](https://forums.expo.io/t/cant-use-xde-on-macos-sierra-simulator-not-installed/10392).

Is this going to be fixed? 
If not, how can I run my application using the set-up that I have?

**Comment by brentvatne** [comment]
hi there! this error just means that it can't find `xcrun` executable on your machine. if you open a terminal and type `xcrun` what do you see?

**Comment by terribleben** [comment]
Thank you for the feedback and sorry this frustrated you. We did actually mention this in our [SDK 28 release notes](https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530) and we also [warned about it last April](https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4). Basically, since Expo is a tiny team, we need to periodically drop support for old versions in order to continue providing the best support for the newer ones. Let us know if you'd like help updating your project to a newer SDK.

**Comment by LAITONEN** [comment]
@brentvatne 
Usage: xcrun [options] <tool name> ... arguments ...

Find and execute the named command line tool from the active developer
directory.

The active developer directory can be set using `xcode-select`, or via the
DEVELOPER_DIR environment variable. See the xcrun and xcode-select manual
pages for more information.

Options:
  -h, --help                  show this help message and exit
  --version                   show the xcrun version
  -v, --verbose               show verbose logging output
  --sdk <sdk name>            find the tool for the given SDK name
  --toolchain <name>          find the tool for the given toolchain
  -l, --log                   show commands to be executed (with --run)
  -f, --find                  only find and print the tool path
  -r, --run                   find and execute the tool (the default behavior)
  -n, --no-cache              do not use the lookup cache
  -k, --kill-cache            invalidate all existing cache entries
  --show-sdk-path             show selected SDK install path
  --show-sdk-version          show selected SDK version
  --show-sdk-build-version    show selected SDK build version
  --show-sdk-platform-path    show selected SDK platform path
  --show-sdk-platform-version show selected SDK platform version

**Comment by LAITONEN** [comment]
@terribleben I meant that I did not see any warnings in the release notes of the application in the AppStore itself. Please, have at least such breaking changes mentioned there as well.

I would definitely like to get help with that, but I am not sure where to start, since [as I said](https://forums.expo.io/t/cant-use-xde-on-macos-sierra-simulator-not-installed/10392)., I can't open my project in Expo Desktop Client anymore as well.

**Comment by terribleben** [comment]
I responded to the forum thread, it looks like there's something going on with your iPhone Simulator which is confusing XDE. Sorry again for the trouble.

**Comment by LAITONEN** [comment]
@terribleben replied

**Comment by sjchmiela** [comment]
Hey, @LAITONEN, it's been a while now since the last reply and since then we've released Expo CLI 2.0, replacing both `exp` and Expo XDE ([release blog post](https://blog.expo.io/expo-cli-2-0-released-a7a9c250e99c)). I think this issue should have been fixed in Expo CLI, but if it persists, feel free to open an issue on the [`expo/expo-cli`](https://github.com/expo/expo-cli) repository! 🙂
