### ISSUE TITLE
ImagePicker is able to access all photos on iOS despite "Selected Photos" in Privacy settings

### ISSUE THREAD

**Issue by jeffreylauck** [expo/expo#18954]
### Summary

I am following the tutorial and building the "Image Share" app. I have also installed Expo Go to try out the app.

I have followed along and installed expo-image-picker (https://docs.expo.dev/tutorial/image-picker/)

Then I tried to click "Pick a photo" on my iPhone and chose only to permit access to "Selected Photos" (I chose 2 photos from my library).

But then my Expo Go is able to show all photos in my iPhone Photo Library, not only the 2 selected photos. I am able to pick and use other photos as well.

Expected behaviour:
Only photos permitted access are shown in image picker

Actual behaviour:
ALL photos in the Photo Library are shown and usable

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.9.0 - ~/.nvm/versions/node/v17.9.0/bin/node
      npm: 8.19.0 - ~/.nvm/versions/node/v17.9.0/bin/npm
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.9 
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed

Expo Go Client Version: 2.25.1.1015582

iOS 15.6.1

### Minimal reproducible example

Snack Link: https://snack.expo.dev/@jeffreylau/imagepickerissuedemo

1. Choose iOS
2. Tap to play
3. Click "Pick a photo"
4. Click "Select Photos..."
<img width="242" alt="image" src="https://user-images.githubusercontent.com/70197122/188036400-73855029-3e3b-4fab-97f3-539586b49c81.png">
5. Select only 1 photo and click Don
<img width="291" alt="image" src="https://user-images.githubusercontent.com/70197122/188036429-36a1b6c5-66ea-47be-84da-2ac56c9084bb.png">
6. Observe all photos are available to pick and use
<img width="298" alt="image" src="https://user-images.githubusercontent.com/70197122/188036574-e4d6f133-cce7-4453-a046-4a670fa2efec.png">

**Comment by brentvatne** [comment]
expo-image-picker uses UIImagePickerController.

https://developer.apple.com/forums/thread/653414 - see the reply here from an engineer at Apple:

![image](https://user-images.githubusercontent.com/90494/188063603-731b632a-8d1d-4ca8-b355-8badded0f2e8.png)

in other words, this isn't a security concern for the user because only photos that are explicitly selected in the picker will be readable by the application. permissions restrictions apply to [expo-media-library](https://docs.expo.dev/versions/latest/sdk/media-library/), however.

we should update the tutorial to remove the permissions request, since we currently support only iOS 12.4+, so the permissions request in the tutorial is unnecessary.

**Comment by jeffreylauck** [comment]
Thanks @brentvatne ! In this case, I guess it is an expected behaviour of the underlying `UIImagePickerController`.

I will go ahead and close the issue.

**Comment by nakedgun** [comment]
> in other words, this isn't a security concern for the user because only photos that are explicitly selected in the picker will be readable by the application

@brentvatne @jeffreylauck Not true sadly. The images **are readable** despite not being part of the user's "Selected Photos". 

For example, limit your photo selection to one or two photos. Then, select an image which is not in the **Selected Photos** and the callback from `ImagePicker.launchImageLibraryAsync()` still returns the processed photo URI. This URI is readable by the app:

```
Object {
  "cancelled": false,
  "selected": Array [
    Object {
      "assetId": "16B8CEA9-6DB2-45B8-B397-E714A0F45BBF/L0/001",
      "fileName": "02b70a94-23e0-4ffc-8e4a-deff1071e535.jpg",
      "fileSize": 115930,
      "height": 768,
      "type": "image",
      "uri": "file:///var/mobile/Containers/Data/Application/6971596A-2094-4D2D-854A-CCA73E7FD0BE/Library/Caches/ExponentExperienceData/<experience>/ImagePicker/BFAD337E-0638-4F70-ADE5-ED4DCA46FEC6.jpg",
      "width": 1024,
    },
  ],
}

```
`ImagePicker.getMediaLibraryPermissionsAsync()` confirms that the access privileges are **limited**:

```
 {
  "accessPrivileges": "limited",
  "canAskAgain": true,
  "expires": "never",
  "granted": true,
  "status": "granted",
}
```

And confirmed in the iOS app privacy settings & response of `MediaLibrary.getAssetsAsync()` (in this case, I had only allowed one photo):

```
{
  "assets": Array [
    Object {
      "creationTime": 1662691917286,
      "duration": 0,
      "filename": "IMG_6735.HEIC",
      "height": 4032,
      "id": "8AF8C5F7-5540-42D6-9BA9-448D8CE19351/L0/001",
      "mediaSubtypes": Array [
        "livePhoto",
      ],
      "mediaType": "photo",
      "modificationTime": 1662709024329,
      "uri": "ph://8AF8C5F7-5540-42D6-9BA9-448D8CE19351",
      "width": 3024,
    },
  ],
  "endCursor": "8AF8C5F7-5540-42D6-9BA9-448D8CE19351/L0/001",
  "hasNextPage": false,
  "totalCount": 1,
}
```

We didn't want to risk an app store rejection or bad reviews concerning user privacy, so to handle this case we call `ImagePicker.getMediaLibraryPermissionsAsync()` and if the response for `accessPrivileges` is `limited` we show a custom image picker which *just shows* the user's selected photos.

This approach is in alignment with Apple's own docs on managing the UX of this flow (see: [video](https://developer.apple.com/videos/play/wwdc2020/10652/), [docs](https://developer.apple.com/documentation/photokit/delivering_an_enhanced_privacy_experience_in_your_photos_app)), which suggest that if the user has limited photo access privileges then this case *needs to be handled by the application itself*.

Anyway, I don't think there's a bug here, but updating the Expo docs would be useful. Many developers will assume this workflow is handled automatically by Expo or the iOS photo library, which it is not.

**Comment by hraschan** [comment]
@nakedgun Hello Jack. Did you build your own custom picker when the user selects limited access on IOS? If so how did you manage to accomplish the picker?

**Comment by nakedgun** [comment]
> @nakedgun Hello Jack. Did you build your own custom picker when the user selects limited access on IOS? If so how did you manage to accomplish the picker?

@hraschan We did yes, but in the end, we simplified the code to just use the native image picker. If all you need is to ask the user to pick photos for uploading, the native photo browser is fine - there's no need to check for permissions before hand, and it handles the UX of letting the user know that the app can only access photos they select (on iOS 17+ at least).

A side note for clarifying some confusion around limited photo selection UX: on iOS 17 +, when the image picker is launched, it will display a notice in the UI saying: "the photo library is shown here, but [app name] can only access the items you select". In older versions of iOS, it didn't - it was just "implied". Obviously Apple realized this was confusing which is why it's different in iOS 17. The [new photo picker UI in Android](https://github.com/expo/expo/pull/22658) also shows a similar message: "this app can only access the photos you select".

All this to say: unless you need _persistent local access_ to a user's selection of photos (or, for some reason, to show a custom photo picker UI), there is no need to check for permissions or use a custom image picker. Just launch the native one. 

That said, there are a couple of bugs with expo 49 to be aware of, which are in referenced in the comments below, with their respective workarounds. Other than that, we have had no issues with this code on iOS/Android (in production for about 3 months now). Hope that helps!

```
      // no permissions are needed to launch the image picker!
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: false,
        allowsMultipleSelection: true,
        // IMPORTANT: https://github.com/expo/expo/issues/25098
        // sdk 48/49+ android bug, setting a compression value other than 1 (zero compression)
        // will cause the image selection to fail.
        // to work around this bug, we disable image compression for Android
        // and handle compression after images are selected 
        // using manipulateAsync() from expo-image-manipulator.

        // note: we do not use the same compression workflow on iOS, 
        // due to this crash in expo-image-manipulator
        // https://github.com/expo/expo/pull/25756 (fixed in SDK 50)
        quality: Platform.OS === 'ios' ? 0.5 : 1,
      });
```
