### ISSUE TITLE
[expo-av] Ducked Audio doesn't stop being ducked.

### ISSUE THREAD

**Issue by JacobJaffe** [expo/expo#19042]
### Summary

I'm working on updating an app that utilizes Audio playback from Expo 44 to Expo 46. (expo-av ~10.2.0 to ~12.0.4).
Prior to updating, using `sound.stopAsync` / `sound.pauseAsync` would resume the ducked audio (e.g. of music playing). 

Now, no matter what I do, the ducked audio won't resume at full volume. Also, the ducked audio will pause when the app is closed now. 

Note that *unlike* https://github.com/expo/expo/issues/16272 , this is for *ducked audio*:
```tsx
      await Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
        interruptionModeIOS: InterruptionModeIOS.DuckOthers,
      });
```

See snack for a simple reproduction of this.

It's unclear to me if the API has changed, and the audio mode needs to be cleared, or something else done with the sound when paused now, or if this is broken. Any help would be very appreciated! 

### What platform(s) does this occur on?

iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

### Minimal reproducible example

Reproduction steps:
1. Have a background sound playing (e.g. music from spotify).
2. Load the snack onto your device
3. play the audio (music should duck)
4. pause the audio (music should un-duck, but does NOT)
5. close the expo app (music will STOP, which is further-bad)

https://snack.expo.dev/@jacobjaffe/ludicrous-yogurt

**Comment by JacobJaffe** [comment]
Note that this *also* occurs on all other audio  interruption modes, but from https://github.com/expo/expo/issues/16272#issuecomment-1036894404 (And from how the API previously worked on 10.2.0), it seems like it *should* work, at *least* for ducking.

**Comment by JacobJaffe** [comment]
I've downgraded to `~10.2.0`, and things go back to working as expected, on Expo 46, so I'm pretty sure this is isolated to a change within `expo-av`

**Comment by JacobJaffe** [comment]
I've stepped through the versions here: https://github.com/expo/expo/blob/sdk-46/packages/expo-av/CHANGELOG.md
And found that the breaking change for this behavior occurs between 11.0.1 and 11.1.0. (11.0.1 works as expected, 11.1.0 has the issue with ducking)

From this testing, I think that the changes in https://github.com/expo/expo/issues/15873 caused this

**Comment by hirbod** [comment]
Hm, that's a bummer. The fix in #16578 is pretty important, otherwise you will constantly freeze the UI thread when pausing/starting/resuming videos. It was crucial to build a video feed where you constantly wanna pause or stop videos when they leave the visible viewport. Without the introduced change, people have been also reporting multiple times that the UI kept freezing when they paused or resumed a video.

We tested this change pretty intensive but guess that one slipped through. Now we need to find a way to fix this without reintroducing UI thread blocks. Summoning the OG @Pickleboyonline

**Comment by JacobJaffe** [comment]
@hirbod I think a special prop to toggle this behavior would be a good starting point for this.

A backdoor to achieve the old behavior would be immensely helpful.

Out of curiosity, does this ducking-issue not apply for video sessions?

As in, does background audio resume after pausing a *video* currently?

**Comment by hirbod** [comment]
No, music does not resume. We thought notifying other apps might not be super important but I made some tests with Insta TikTok while having Spotify running and closing those apps will automatically start music on Spotify again, while opening my app will pause Spotify and not resume it, even after I've closed my. While I don't think that this is super important (since we care about our app, not about Spotify) some users could be annoyed by this.

**Comment by JacobJaffe** [comment]
Gotchya, thanks for the context. In my app's use case, it's only playing audio, and this would be a regression to previously not having ducking support-- audio plays only occasionally, and users requested the ducking support previously. 

I don't have much experience working with native code, so I don't know how I'd go about wiring / testing making that behavior conditional on a prop. 

As an intimidate workaround though, it seems relatively simple to patch this on my side (since I'd just like to revert those few lines changed). However, I don't know how to go about applying that change with how the prebuilt-modules work. 

Any help on this would be greatly appreciated! I've also created an expo-forums issues to track that (the how-to of rebuilding modules from source in managed workflow) more specifically: https://forums.expo.dev/t/how-to-apply-changes-to-native-modules-build-modules-from-source-in-managed-workflow/66355

**Comment by hirbod** [comment]
If you want to patch that line, you'll need to go with a custom dev client. Let's first get some more thoughts on all of this and we might be able to figure out something better.

**Comment by JacobJaffe** [comment]
I'm currently using a custom dev client -- the issue I'm facing is that when I change those lines, and rebuild the dev client, the changes don't apply. I believe this is because the module is deferring to the pre-built binary, and ignoring the source changes?
https://github.com/expo/fyi/blob/master/prebuilt-modules.md

Or I may be wrong and am missing something else when making a new dev client 😓

**Comment by hirbod** [comment]
Go into node_modules/expo-av/... and patch that file. Use patch-package to apply your patches. Create a new native build. Thats it.

**Comment by byCedric** [comment]
You can try building the dev client with `expo run:ios -d` instead. That might help you bypass the prebuild step. You'll get the `/ios` folder and some other changes in your repo, so make sure to use a throw-away branch for this.

(assuming your local environment is set up to build natively, since you are using `eas build --local`)

**Comment by JacobJaffe** [comment]
@byCedric thank you for the suggestion. 
I've tried doing that, it looks like it's still using the prebuilt module when doing that approach.

I also tried manually deleting `EXAV.xcframework` / adjusting `EXAV.podspec` to not use the `s.vendored_framework`, but only use the source files, but I think I'm missing something because it's still attempting to copy the prebuilt-- 
I get this error, indicating it's still trying to copy it:

```
› Executing expo-av Pods/EXAV » [CP] Copy XCFrameworks
 rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/xxxxx/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
 ```
 
 Is there something I need to do to inform expo at a higher level to exclude the AV source? 
 https://github.com/expo/fyi/blob/master/prebuilt-modules.md seems to indicate that with:
 ```
 $ExpoUseSources = ['expo-camera', 'expo-notifications', '@unimodules/code']
 ```
 
 But I'm not sure how / where I should be including that in either a local `eas build` or an `expo build` workflow.

**Comment by JacobJaffe** [comment]
Is there a sanity check I can run to ensure that the source *is or is not* being used? This is especially tricky to debug since I'm basing that off the bug persisting (which I evaluated to go away when using `expo-av: 11.1.0`, but I'm now patching the change on `12.0.4`).

**Comment by JacobJaffe** [comment]
I've managed to apply the patch against `12.0.4`, and against `11.1.0`.
FWIW, my steps were:
```
1. patching the file EXAudioSessionManager.m
2. prebuilding, to get ios/
3. editting the podfile, adding $ExpoUseSources = ['expo-av']
4. EXPO_USE_SOURCE=1 pod install --clean-install
5. npx expo run:ios
```

I first applied the patch to `11.1.0` to sanity check the change. It goes back to working as expected.

I then applied the patch to `12.0.4`, to test the change against the most recent version of the package. 
_Good News_: the change *does* allow background audio sessions to resume. 
_Bad News_: the UI thread issues @hirbod has described now affect my application when pausing audio. When pausing audio, my application now freezes up for about a second. **This is unexpected, because in version 11.0.1 and prior, pausing audio did NOT have the UI thread issue**. 
 
This is unfortunate -- it seems to me like there's been other changes that have been introduced, building on top of the changes to how audio sessions work, that add more issues. This means there's probably not an easy workaround for fixing this issue on top of `12.0.4`. 

My main motivation for bumping versions in the first place is to get the changes landed in [11.2.0](https://github.com/expo/expo/blob/sdk-46/packages/expo-av/CHANGELOG.md#1120--2022-04-18) working, which bump the Android SDK version to 31. Without this, the package won't work on Expo 46.

I'm going to work on making a compatible patch for `11.2.0` for this issue. The underlying issue here looks beyond my ability to debug on the iOS side.

**Comment by JacobJaffe** [comment]
It looks to me like this is the same underlying issue as:
https://stackoverflow.com/questions/31090320/ios-avaudiosession-ducking-is-slow-and-synchronous

I don't think this came up in the discussion on https://github.com/expo/expo/issues/15873

The suggestion there is to put the `setActive` calls on a different thread:
```objc
        dispatch_queue_t myQueue = dispatch_queue_create("com.myname.myapp", nil);
        dispatch_async(myQueue, ^{
            [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient withOptions: AVAudioSessionCategoryOptionDuckOthers error: nil];
            [[AVAudioSession sharedInstance] setActive:YES error:nil];
        });
```

I don't know what ramifications that would have, but this might be useful for someone skilled in iOS development who looks at this.

**Comment by hirbod** [comment]
I digged into this a little more and also struggled to find a good solution, but I've came up with one - at least for my use case. (even though I've removed expo-av in favor for another library, but because of different reasons (mainly video))

Right now, we're activating the audio session, but never inform the system that we're done. This is fine, because it's a sync and blocking task and should not be called frequently just because we paused or played an audio/video. The decision should be done imperatively. 

So what I've done now:

1) I've updated my library [react-native-volume-manager](https://github.com/hirbod/react-nat) and added functions like .setCategory(), .setMode(), setActive(). If you like, try the newest version. I can't promise you that it will work together with expo-av, I had some issues with expo-av and the audio session (I think expo-av did overwrite everything). If you're only using Audio, you could also consider using `react-native-sound`.

2) You need to inform other Apps correctly that you have deactivated the audio session. You're not forced to, but without informing, stopped background audio won't resume. This is currently missing totally in `expo-av`. To make this work, I had to pass `withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation`. So when you decide to use my library, you can call `VolumeManager.setActive(false)` which will automatically resume background audio. You will need to call `setActive(true)` before you wan't to play another audio. I am not calling it on another thread though. You could also circumvent this totally and use a combination of setMode() and setCategory(). I think it has to be Ambient with 

3) To make background audio resume whenever I backgrounded my App, I added:
```ts
   import { VolumeManager } from 'react-native-volume-manager';

  const onAppStateChange = useCallback(async (status: AppStateStatus) => {
    if (status === 'active') {
      VolumeManager.setActive(true);
    } else if (status === 'background') {
      VolumeManager.setActive(false);
    }
  }, []);

  useAppState({
    onChange: onAppStateChange,
  });
```

This triggers with `withOptions:AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation` automatically, using my library. Afaik, Expo has not implemented this. My library does the active/inactive calls async, so its not blocking.

I would recommend not changing the current behaviour in expo-av. Instead, I would recommend to add a method like I've done, so we can call it imperatively.

**Comment by de1acr0ix** [comment]
From what I have observed, when app is switched to background, `expo-av` will set the audio session category to `AVAudioSessionCategorySoloAmbient` in the following call
https://github.com/expo/expo/blob/86589e9cabb9542cb535a4aa28182437640c79f8/packages/expo-av/ios/EXAV/EXAudioSessionManager.m#L159-L174
As all foreground modules are removed, the `_getRequestedCategory` in `_updateSessionConfiguration` will always return `AVAudioSessionCategorySoloAmbient`. This means application will interrupt other apps audio sessions as `expo-av` is not deactivating its audio session anymore.
My proposal would be removing the `[self _updateSessionConfiguration]` call in `moduleDidBackground`.

**Comment by ferrannp** [comment]
I can confirm there are some issues here. @de1acr0ix your proposal fixes my problem. Basically:

1. I have a video playing in the app using `isMuted` (the video has not even an audio track)
2. In the background I am listening to music
3. I put down the Control Center from iOS... and my music/session (background) is stopped

This basically happens because of `[self _updateSessionConfiguration]; ` in `moduleDidBackground`.

I am using `expo-av: 13.1.0`. 

cc @brentvatne hope this is helpful 😄 .

**Comment by datgreatkhan** [comment]
Having the same issue myself. I couldn't even get ducking to work with Speech (Expo Speech / Text to Speech) because it isn't part of the Audio Session, so I had to first manually play a silent audio clip to "activate" it.

After doing that, ducking works but does on Speech stop, it does not return the ducked volume back to original like this issue outlines. Is there any chance a fix coming for this soon (for `expo-av` and `expo-speech`)? I am lost on this issue right now :/

**Comment by louislatreille** [comment]
I have the same issue. Expo SDK 48.0.9 and expo-av 13.2.1

**Comment by datgreatkhan** [comment]
Is there anyone who is trying to push a fix for this? It's frustrating that it isn't resolved.
