### ISSUE TITLE
[Android] Cannot load app

### ISSUE THREAD

**Issue by lilosir** [expo/expo#1910]
In my detached app, I was using sdk 25.0.0, recently I upgraded to 27.0.0. It is working on Android in development mode. So I generated a signed APK to upload to play store for testing. While, after downloading the app, it cannot be loaded, it came with blue screen and saying **java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference**
Does anyone know the reason, and how to fix that. Thx

**Comment by esamelson** [comment]
Hi @lilosir - I assume that since you've closed this issue you found a solution. For anyone looking at this in the future, you probably need to [follow these one-time instructions](https://gist.github.com/janicduplessis/30ec95451733d34ffcf7d5cb27ba0e28) to add support for bundled assets into your app. This was part of the SDK 27 upgrade for detached apps but is easy to miss.

**Comment by lilosir** [comment]
@esamelson thanks for your tips~~ Actually, I gave up the sdk 27.0.0, and try to using 28.0.0 instead. While similar issue 

> Uncaught Error: java.lang.Exception: Could not load embedded manifest. Are you sure this experience has been published?

Maybe I missed the bundled assets as you said, I will try that. Thank you sir

**Comment by esamelson** [comment]
@lilosir make sure you've run `exp publish` at least once also, after following those instructions. The error you're describing happens when the app cannot find a bundled version of your JS.
