### ISSUE TITLE
Detached Expo app error (Android) - java.lang.Exception: Could not load embedded manifest

### ISSUE THREAD

**Issue by lilosir** [expo/expo#1916]
I just upgraded to sdk 28.0.0, it was working on both IOS and Android in development mode. So I uploaded to app store and play store as staging app for testing. While, when I open the app after installing from play store, it said `Uncaught Error: java.lang.Exception: Could not load embedded manifest. Are you sure this experience has been published?` Any ideas?

**Comment by esamelson** [comment]
Hi @lilosir - as the error message suggests, you need to run `exp publish` at least once before building a release mode app.

This is because in dev mode, the JS bundle is pulled from your computer's development server, but a release build needs a release version of your JS, so you need to publish your experience at least once. (Publishing the experience in this case both publishes it to expo.io and places a copy to be embedded in your apk.)

**Comment by tunguyenbhtech** [comment]
I'm also getting this error when upgraded to sdk 28.0.0, it's was working well before (exp published)

**Comment by tunguyenbhtech** [comment]
@lilosir i solved it by

> Add the following keys to your manifest:
> android.publishBundlePath: "android/app/src/main/assets/shell-app.bundle"
> android.publishManifestPath: "android/app/src/main/assets/shell-app-manifest.json"
> Make sure to publish a new version first and then production builds will work offline!

your manifest -> app.json

**Comment by slorber** [comment]
hi

Just wondering, why `android.publishBundlePath` keys are not set by default on android ejected projets?

A freshly ejected project produces this config:

```json
{
  "expo": {
    "sdkVersion": "27.0.0",
    "ios": {
      "bundleIdentifier": "dfgdfgdg",
      "publishBundlePath": "ios/test-eject/Supporting/shell-app.bundle",
      "publishManifestPath": "ios/test-eject/Supporting/shell-app-manifest.json"
    },
    "android": {
      "package": "com.dsfgdgfdg"
    },
    "name": "test-eject",
    "slug": "test-eject",
    "version": "0.1.0",
    "isDetached": true,
    "detach": {
      "scheme": "exp2be0efe83f4e4c5389768e240de0c321",
      "iosExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.5.10-sdk27.0.0-7e6dd135-e649-48e2-ab7c-e76521ce6259.tar.gz",
      "androidExpoViewUrl": "https://s3.amazonaws.com/exp-exponent-view-code/android-v2.5.3-sdk27.0.0-408c8d77-8d1f-4784-b7b4-93826250663a.tar.gz"
    }
  }
}
```

And it seems that if you add the following:

```js
    "updates": {
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    },
````
it stops working because it fallbacks to cache on load and there's no cached version for android


@esamelson doesn't it make sense to setup the `android.publishManifestPath` keys by default on detach? Because by default, when running exp publish, nothing is updated in the android folder (only ios). cc @terribleben

**Comment by esamelson** [comment]
@slorber the `android.publishBundlePath` and `android.publishManifestPath` keys are set on detach and publish for me 🤔 is it possible you're running outdated version of `exp`?

**Comment by webdevbyjoss** [comment]
I'm running "28.0.0" and the android.publishBundlePath and android.publishManifestPath keys are not set for me during detach.

**Comment by loganwedwards** [comment]
I ran into this issue as well by upgrading from SDK 27 to SDK 30. I already had the `publishBundlePath` and `publishManifestPath` in `app.json`, but ultimately, by starting a fresh Android project with SDK 30 solved the issue. My guess is so much has changed in the build process that some link was broken or using a non-backwards compatible API.

**Comment by webdevbyjoss** [comment]
The issue returned occasionally. Nothing changed in my code, it just started skipping the JS bundle from APK. Here is the issue narrowed now: 
https://www.bountysource.com/issues/58866793-could-not-load-app-can-t-connect-to-internet-please-try-again-sdk27-30-w-expokit
