### ISSUE TITLE
SDK46: Unable to resolve module uuid/v5 in expo go

### ISSUE THREAD

**Issue by bit-void** [expo/expo#19160]
### Summary

With a yarn monorepo (workspaces) In the latest expo sdk 46 the app us unable to run due to this error:

```
Unable to resolve "uuid/v5" from "../../node_modules/expo/build/environment/getInstallationIdAsync.js"
```

### What platform(s) does this occur on?

iOS

### Environment
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.1 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2022.09.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```
### Minimal reproducible example

https://github.com/bit-void/expo-46-monorepo

**Comment by bit-void** [comment]
I believe this is my fault, if I nohoist the uuid dep it works. That makes sense, I guess I was confused since the expo docs mention not using hoisting. Relatively new to yarn workspaces so that was confusing. Thanks!

**Comment by bit-void** [comment]
@ianwalter in the `package.json` of my expo app (not the top level) I put this:

```json
{
  //...
  "workspaces": {
    "nohoist": [
      "uuid"
    ]
  },
}
```

**Comment by chris-chapin** [comment]
I had this problem as well and "nohoist" didn't solve it for me. I'll add what worked for me since I didn't see a lot of documentation or detail in Expo's monorepo guide. I did create a PR to update the guide and call out using classic Yarn since I don't know if Expo supports modern yarn (without Plug N' Play).

I was using modern yarn (v3.2.4) with `nodeLinker: node-modules` in .yarnrc.yml file (because React Native\Expo + monorepos isn't compatible with Plug N' Play). I tried for a few hours, with various combinations, even modifying the import statement as per [this workaround](https://github.com/expo/expo/issues/17261#issuecomment-1112598478), which led to another issue, and eventually gave up and went back to classic yarn (v1.22.19).

Classic yarn told me I needed "name" and "version" in my app's package.json. I have been upgrading my project from Expo for a few years and apparently it wasn't put there during bootstrap and I never added it. Once I added those fields, yarn install completed, and app started right up in Expo Go without crashing.

I may try to modern yarn 1 more time now that I know the project is configured correctly with classic yarn.

For anyone interested in my monorepo setup, you can see if [here](https://github.com/Living-Snow-Project/LivingSnowProject). I still need to update my own readme's and a few other things.
