### ISSUE TITLE
takeSnapshotAsync degrades image quality while increasing image size

### ISSUE THREAD

**Issue by jhalborg** [expo/expo#1930]
### Environment

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.2.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Targeting both iOS and Android, reproducible on both standalone and Expo

### Steps to Reproduce

As discussed in [this forum post](https://forums.expo.io/t/how-to-improve-image-quality-ppi-of-takesnapshotasync/9915), the resulting images from using `takeSnapshotAsync` results in grainier image quality, as well as increased file size. 

1. Find image to use, preferably reasonably high quality (12 MP or more)
2. Render it in `Image` in app
3. Use `takeSnapshotAsync` to take and save a snapshot of the image
4. Inspect the result. Not only is it grainier than the original, even if providing `quality:1` and the same target pixel count of the original, but it's also a much larger file. For example, I just tried with a 3024x3024 image of size 3.4 MB from my Nexus 6P. It resultet in a 6.8 MB file that was a bit distorted. 

### Expected Behavior
I expect the result of `takeSnapshotAsync` with appropriate `quality` and target pixel values to return a comparable image to the original - if not i size, then at least in quality

### Actual Behavior
A lot of screenshots can be found in links to Imgur on the forum post, but please see the reproducible demo below to experiment and verify yourself. Use the slider to set target pixel count. You can either see the snapshot result by sliding right on the list, or save the snapshot to local storage and inspect the result and it's size, resolution etc. in your favourite camera roll browser. 

### Reproducible Demo
https://snack.expo.io/HJ2QpEzM7

**Comment by quinlanj** [comment]
hi @jhalborg, isn't this the expected behavior of a screenshotting tool? (ie) if i display a high quality image on the phone screen, the screenshot will be of lower quality than the original high quality image

**Comment by jhalborg** [comment]
Hey @quinlanj - I don't know, is it? I wouldn't assume so. I would assume that the screen/display quality has nothing to do with the output. Seeing as it's a software operation, the hardware should not matter. 

In any case, I've tried it on both an iPhone 8 and Nexus 6P - both pretty high end devices with dense screens - and they both produce suboptimal results. 

To me, `takeSnapshotAsync` should save an image of the software render on the screen. Additionally, if the quality would be determined by the screen, then why does the API allow for `quality` and `pixel` args?

**Comment by terribleben** [comment]
Hi @jhalborg, can you paste all of the arguments you are using for the `takeSnapshotAsync` method in step 3 of your repro steps?

`png` is a lossless image format, whereas `jpg` is an inherently lossy format. If you're using `jpg` then you should expect some loss no matter what the `quality` parameter says; this parameter simply gets plugged into the jpg compression algorithm. If you're using `png` then you should expect a lossless image.

Our code does this:

- Create a graphics context at the pixel size given by the `width` and `height` args
- Draw your view to the graphics context
- Render the result of the context as a png (lossless) or a jpg (with the quality argument given).

Relevant code:
https://github.com/expo/expo/blob/90ebcc81e9872cd157033da237368ff59b0a2dec/ios/Exponent/Versioned/Core/Api/EXViewShot.m#L66-L71

**Comment by jhalborg** [comment]
Hey @terribleben , 

Sure, it's the same code as in the top of the forum post I linked to:

```
takeSnapshotOfImageContainer = async (type: 'file' | 'data-uri') => {
    const targetPixelCount = __DEV__ ? 640 : 1080; // We want full HD pictures in prod
    const pixelRatio = PixelRatio.get(); 
    const pixels = targetPixelCount / pixelRatio;

    const result = await takeSnapshotAsync(this.imageContainer, {
      result: type,
      height: pixels,
      width: pixels,
      quality: 1,
      format: 'png',
    });
    return result;
  };
```

The originals taken by my iPhone 8 and Nexus 6P are all .jp(e)g's , and I save the result as a .png. 

I'm not super into how image compression works, but in my mind, if the original .jpeg from i.e. my iPhone is 4032 × 3024 pixels, and the native code draws it onto a 1080x1080 canvas/graphics context, it should at least hold pixels/quality enough to satisfy a 1080x1080 requirement - there should be enough pixels to go around :-) Is that assumption completely wrong?

**Comment by terribleben** [comment]
So a few things are probably going on here--

1. The image is getting scaled when rendered in the ImageView by React Native (by way of UIKit on iOS and some other framework on Android). Generally, image scaling can use one of a number of algorithms depending on whether you want sharp pixels or some level of interpolation. This property is controlled by the `magnificationFilter` on iOS (I'm again not sure about Android) and as far as I know RN doesn't expose it at all; it's just always set to [trilinear](https://github.com/facebook/react-native/blob/1ee6396c566f038a1081796c77a1ecad6a24cef6/Libraries/Image/RCTImageView.m#L129).
2. You're screenshotting large JPG images as PNG files, so that explains why the filesize would be quite a bit larger. JPG files are lossy but good at handling high color content (e.g. photos); PNG files are lossless but their image size scales with the number of colors (so they are well suited to, e.g., icons and other software/assets which aren't photos).

**Comment by terribleben** [comment]
Also, with regards to PNG representation looking blurrier than your original, it looks like [iOS has a known issue with this exact usecase](https://stackoverflow.com/questions/6541352/kcafilternearest-maginifcation-filter-uiimageview). Unfortunately I can't find any obvious solution from a quick read around. But I believe between this comment and my previous comment, I've explained (a) the strange change in quality and (b) the larger filesize. Hope all of that makes sense!

**Comment by jesperbrandheroes** [comment]
First of all, thanks for such a detailed answer, that was really helpful. 

> I think if you're sure your particular usecase will typically be for photos, then you'll likely get better results by encoding your screenshots as JPG. I would try something like quality: 0.6 with JPG format and go from there.

They're all user photos, with a `png` sticker on top. From what you're saying, I'm guessing I should be using `.jpg` anyway for the best results. However, why do you recommend a `quality` of `0.6` instead of `1.0`? Will saving to `jpg` instead of `png` cause large files/slow saving process?

**Comment by jhalborg** [comment]
First of all, thanks for such a detailed answer, that was really helpful. 

> I think if you're sure your particular usecase will typically be for photos, then you'll likely get better results by encoding your screenshots as JPG. I would try something like quality: 0.6 with JPG format and go from there.

They're all user photos, with a `png` sticker on top. From what you're saying, I'm guessing I should be using `.jpg` anyway for the best results. However, why do you recommend a `quality` of `0.6` instead of `1.0`?

**Comment by terribleben** [comment]
I recommended `0.6` as a place to start because (for some reason) it's a really common quality with  which to encode JPGs. Maybe there is some reason why it's a local maximum for size and perceptive quality. If you don't think it looks good enough, you could then tweak upward toward 1.0 (at the expense of file size) until you like what you see.

**Comment by jhalborg** [comment]
If anyone finds this in the future, this was a good overview of quality vs size of JPG Lightroom exports: http://regex.info/blog/lightroom-goodies/jpeg-quality
