### ISSUE TITLE
Notifications.getExpoPushTokenAsync() won't return anything

### ISSUE THREAD

**Issue by gogojimmy** [expo/expo#1938]
I'm working on detach version for iOS.

Here is my code to fetch token

```
  registerForPushNotificationsAsync = async () => {
    const { status: existingStatus } = await Permissions.getAsync(
      Permissions.NOTIFICATIONS
    );
    let finalStatus = existingStatus;

    if (existingStatus !== 'granted') {
      const { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
      finalStatus = status;
    }

    // Stop here if the user did not grant permissions
    if (finalStatus !== 'granted') {
      return;
    }

    // Get the token that uniquely identifies this device
    console.log('token is fetching: ....');
    console.log(finalStatus); ==> 'granted'
    let token = await Notifications.getExpoPushTokenAsync();  ==> hang in here. Even I use Promise.then()
    console.log('token is: ', token) ==> this line never executed.
  }
```
```
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.0.0
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^27.0.2 => 27.0.2
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.2.tar.gz => 0.55.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/gogojimmy-e55b806a-6f81-4147-8e8d-11243ef5f1b4.tar.gz
```

**Comment by sjchmiela** [comment]
Hi @gogojimmy!

Unfortunately, using Expo to manage notifications in detached applications is not supported at the moment—see [documentation](https://docs.expo.io/versions/v28.0.0/expokit/detach#you-require-expos-push-notification-services-after). In fact for a detached application calling this method (and it is called when you call `getExpoPushTokenAsync()`):

https://github.com/expo/expo/blob/75bbc66716c72d9705cae7348d9822b6bf010b12/ios/Exponent/Kernel/Services/Notifications/EXRemoteNotificationManager.m#L50-L59

should do nothing but warn “Expo Remote Notification services won't work in an ExpoKit app because Expo cannot manage your APNS certificates.”, as `_supportsCurrentRuntimeEnvironment` is implemented like this (and a detached application is not built by a service):

https://github.com/expo/expo/blob/75bbc66716c72d9705cae7348d9822b6bf010b12/ios/Exponent/Kernel/Services/Notifications/EXRemoteNotificationManager.m#L229-L241

**Comment by gogojimmy** [comment]
Thanks. I'll find another way to do.

**Comment by faustoct** [comment]
Not supported yet in detach projects?
