### ISSUE TITLE
for expo-dev-menu 0.8.4 isn't compatible with android SDK +31

### ISSUE THREAD

**Issue by djmbdv** [expo/expo#19404]
### Summary

Targeting S+ (version 31 and above) requires that an explicit value for android:exported

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

expo-dev-menu 0.8.4

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
        System Images: android-28 | Google APIs Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0
      expo: ^41 => 41.0.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

### Reproducible demo

please try compilation

**Comment by Simek** [comment]
Hello @djmbdv,

This is an expected behavior, since `expo-dev-menu` is tight to the `expo-dev-client` version, which has the compatibility requirements for each Expo SDK version:
* https://docs.expo.dev/development/compatibility/#expo-sdks

To fix the issue you need to update all dev client related dependencies to the version specified in the table.

Additionally, we officially support Android SDK 31 from the Expo SDK 45 upwards (https://blog.expo.dev/expo-sdk-45-f4e332954a68) and it looks like you are using deprecated Expo SDK (41), which might also cause some problems, so I would start with upgrading it first:
* https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/
