### ISSUE TITLE
Android app force stops, works on iOS and React native web.

### ISSUE THREAD

**Issue by tarunkolla** [expo/expo#1944]
### Issue:

Android app force stops when trying to run the following code. I could figure out the problem though. It's when we pass a string in "margin" but works when a number is passed. 

[Click here for snack.expo.io code](https://snack.expo.io/SJhqIzFzQ)
  
### Expected Behavior

I think it has to work when a string is passed in the margin field according to the [documentation](https://facebook.github.io/react-native/docs/layout-props#margin) . Also, as this problem only occurs on android.

Android app version: SDK 28. 

It isn't device specific as it crashes on other android phones too.

Thank you.

**Comment by jesseruder** [comment]
Hi, thanks for the report. This is actually an issue in upstream React Native, Expo doesn't change any of this code. Can you check for an issue on the React Native repo? Thanks!

**Comment by terribleben** [comment]
Looks like there's [at least one issue](https://github.com/facebook/react-native/issues/16491) about  this in RN. In general, things with the  wrong type are prone to crashing RN, since it doesn't type-check at runtime. It seems like maybe this is a documentation issue with RN, since the docs claim this field could be a string.

Closing since I think this discussion belongs upstream.
