### ISSUE TITLE
[expo-config-plugins] cannot add `<receiver>` or `<service>` to the AndroidManifest.xml

### ISSUE THREAD

**Issue by xseignard** [expo/expo#19548]
### Summary

Hello,
From my custom plugin I try to add a `<receiver>` or a `<service>` to the AndroidManifest.xml

For some reason they are not persisted when I run `expo prebuild`

It works fine with `<meta-data>`

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.09.05.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/xavier.seignard/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.16 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.6
    Expo Workflow: managed
```

### Minimal reproducible example

See here https://github.com/xseignard/plugin-manifest

**Comment by xseignard** [comment]
ok, the bug was me, sorry for the noise 😅

**Comment by RichardLindhout** [comment]
I still have problems with this?

**Comment by mounaiban** [comment]
Note to beginners: I ran into the same exact problem with adding services recently, due to mistakenly adding `service` (to `manifest.application`) as an object, when it should be an array of objects.

I also attempted to manipulate the `manifest` object like a regular JS object, instead of using `find()` to locate sub-objects. Using `find()` might be essential to ensure that that the format of the `modResults` object is correct as the conversion to the XML-formatted Manifest can be pretty strict, and non-compliant objects may be dropped without warning.
