### ISSUE TITLE
androidStatusBar

### ISSUE THREAD

**Issue by eeeman1** [expo/expo#1958]
How do I make a transparent StatusBar when I download an application?
app.js - 
```
    "androidStatusBar": {
      "translucent": true,
      "animated": true,
      "barStyle": "light-content",
      "backgroundColor": how to make it transparent?????
    }
```
in the documentation it is written that the color can only be in the hex value -
"The valid value is a hexadecimal color string. e.g. - #C2185B"
for example, in the application itself, I can make the BtatusBar transparent
```
                <StatusBar
                    animated={true}
                    translucent={true}
                    barStyle={'light-content'}
                    backgroundColor={'rgba(0,0,0,0.5)'}
                />
```

"expo": "^28.0.0",
 "react-native": "^0.55.3",

**Comment by schazers** [comment]
HI @eeeman1 :) If you wouldn't mind, when you're curious how to do something, please post on the forums here so that others may benefit from your issue: https://forums.expo.io/new

As for your question, check this page here:
https://docs.expo.io/versions/v28.0.0/guides/configuring-statusbar

It explains, "Keep in mind that the Android status bar is translucent by default in Expo apps. But, when you specify an opaque background color for the status bar, it'll lose it's translucency."

Read the rest of the page for other relevant details.
