### ISSUE TITLE
Expo Print works in Expo go but not in build apk

### ISSUE THREAD

**Issue by LouisMuriuki** [expo/expo#19581]
### Summary

I am trying to use the expo print api to be able to generate and print a receipt, however on button press it shows the preview on development (the expo go app) but on the build apk, nothing is shown/happens

### What platform(s) does this occur on?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^46.0.0 => 46.0.9
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.8
    Expo Workflow: managed

### Minimal reproducible example

This hook generates my html data:

  export const DynamicTable = async () => {   
   const receipthtml = `
       <html>
       <head>
       <style>
       </style>
       <body> 
       //some html
       </body> 
       </html>`
       return receipthtml;
        }

function to do the printing

   const dynamiccontainer =DynamicTable(); //accessing the html data
   const printReceipt = async () => {   
   await Print.printAsync({
   html:await dynamiccontainer,
   height: 1754,
   width: 1240,
  });
 };

A button to handle the event
return(
     <Button
        text="Print Receipt"
       //backgroundColor="#0091ea"
        rippleColor="#367588"
        borderRadius={8}
        paddingHorizontal={5}
        icon={faPrint}
        onPress={printReceipt}
        height={50}
      ></Button>
)

**Comment by keith-kurak** [comment]
Hi! If you can create a github repo that demonstrates this issue and allows us to build the app so we can see it firsthand, feel free to open a new issue. Also, if you're able to take a video or screenshot demonstrating the difference between Expo Go and your build so can be better visualize what you see, that would be a great help, as well.

**Comment by LouisMuriuki** [comment]
@keith-kurak thank you for the reply, i have created a github repo with the minimal replica of the print functionality find it here https://github.com/expo/expo/issues/19632 
i have also atached the video as requested

**Comment by Danthony023** [comment]
@LouisMuriuki  please have you been able to solve this problem?

**Comment by LouisMuriuki** [comment]
@Danthony023 not yet however I ejected my expo app and opted to use some native packages for the print functionality , the expo team didn't get back to me on the issue, @keith-kurak any progress or workaround on this?

**Comment by Danthony023** [comment]
None, I also encountered the issue and I am facing a block here, please can
you say how u went about with the other react native packages

**Comment by LouisMuriuki** [comment]
Try react-native-thermal-printer or react-native-thermal-receipt-printer
You must eject you expo app to react native

**Comment by Danthony023** [comment]
Alright thanks

**Comment by JuanRamon96** [comment]
Hi, check if you have a base64 image, the problem is that the eas build command doesn't upload certain files. In the case of images, if they aren't used as splash or icon, they aren't found and the print dosen't open.
Then it will work in expo go, but when you generate the app it won't anymore.

Eas build doesn't find the path once you build the apk because it doesn't upload the image.

Try to remove the image and generate your apk and you will see that it works.

I think there is a way to specify the files you want to include in the eas.json when you build the app, in my case what I did was convert the image to base64 online and paste the generated text:

`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4 //8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />`

https://docs.expo.dev/build-reference/migrating/

Read the part of "Files ignored in Git are not uploaded" in the link I sent

**Comment by Danthony023** [comment]
Thanks very much, I do have an image and I will convert my image to base 64
and input it directly

Again Thanks

**Comment by ZYBORX** [comment]
> eject you expo app to react native

Is there no way to implement a printer with expo RN app without ejecting? I am willing to build apk files multiple times if it will be possible to use that way. I just need a package that will help me use a bluethooth printer via Expo RN app.
