### ISSUE TITLE
exp and expo-cli permissions error on macOS 10.14 beta 3

### ISSUE THREAD

**Issue by Elijen** [expo/expo#1966]
This worked fine in macOS 10.14 beta 1 and beta 2. Broke in beta 3. Simulator itself works fine and Expo Client that is already installed from previous macOS version works too.

### Environment

Environment:
  OS: macOS 10.14
  Node: 10.1.0
  Yarn: 0.27.5
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/peller-f2d6109c-5845-420c-8eac-4bfb3203ece5.tar.gz

### Steps to Reproduce

1. `expo start`
2. press **i**

OR

1. `exp i`

### Expected Behavior

Expo Client opens in Simulator.

### Actual Behavior

Error thrown:
```
[12:26:32] Error installing or running app. Error: Command failed: osascript -e tell app "System Events" to count processes whose name is "Simulator"
28:69: execution error: Not authorized to send Apple events to System Events. (-1743)
```

**Comment by terribleben** [comment]
Hi there! Thanks for letting us know. We don't target macOS beta software right now. I quickly searched Google for that error message and there is very little information about it yet; there's probably nothing we can do to reproduce it right now since nobody on the team is running 10.14, and we don't know if this behavior will still be around when the final 10.14 comes out.

Let us know if you find out any other information, and we'll keep an eye out for it when Mojave comes out later this year.

**Comment by Elijen** [comment]
@terribleben Cool, I'll keep an eye on it. Maybe it's just a temporary beta quirk as you said.

In case somebody has the same issue and needs to install Expo on simulator:

1. Download Expo IPA: https://expo.io/tools
2. Decompress the archive
3. Install in the running Simulator: `xcrun simctl install booted ./Exponent-2.6.7`

**Comment by dankegel** [comment]
This is not a quirk.
See https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave

**Comment by Elijen** [comment]
@dankegel Yeah, I should have linked this article in the original post. If the API stays the same on the official release expo cli just needs to request permissions before trying to control Simulator, right?

**Comment by popcornAC** [comment]
@Elijen  Have you tried this on the latest release? I still have the same issue.

**Comment by tetreault** [comment]
I'm on the official release of MacOS Mojave, and can confirm that expo is not loading the app after scanning the QR code with my iphone X. I can however use the simulator. This is obviously problematic though as I'm also building another app that is Expo AR based and cannot be run on the simulator. 

Any insight into this? I can confirm it was the switch to Mojave, because up until this morning I had the prior MacOS and had no expo issues with opening projects on my actual phone.

**Comment by tetreault** [comment]
To expand on that more - I also see no errors or warnings from Expo as seen in the other person's screenshot above.

**Comment by desduvauchelle** [comment]
Same issue for me, except it asked for permission and I denied accidentally. How can i grant it permission again?

**Comment by tomjohn1028** [comment]
@desduvauchelle Open system preferences, security & privacy, then allow terminal to control other applications 
<img width="658" alt="allowterminaltocontrolotherapps" src="https://user-images.githubusercontent.com/32071703/47269938-426ae300-d519-11e8-99f7-618e00f37ae1.png">

**Comment by BenQuirk** [comment]
Same issue here. Tried everything here but still can't get it to work.

"[12:03:51] Error installing or running app. Error: Command failed: osascript -e tell app "System Events" to count processes whose name is "Simulator"
28:69: execution error: Not authorized to send Apple events to System Events. (-1743)"

**Comment by georgetmayorga** [comment]
@BenQuirk Didn't work for me either. Ended up having to reset all System Event permissions to get the permission request again.

Running `tccutil reset AppleEvents` will reset permissions, then it will prompt you again.

Found here: https://bitsplitting.org/2018/07/11/reauthorizing-automation-in-mojave/
