### ISSUE TITLE
Expo Client Android app working very slow

### ISSUE THREAD

**Issue by Harish-Hk** [expo/expo#1968]
### Steps to Reproduce

(Write your steps here:)

1.I'm a beginner to react native and expo,I;ve been using it for the past two months.
2.Earlier, the expo client app used to work well, the Hot Loading or the Building or Downloading of java script bundles was done very fast.
3.Since the past update of the Expo Client android app, the loading of JS Bundle is taking too long.
4.Please look into the update or the bugs it is generating.
### Expected Behavior

Loading of the expo app super fast,
bundling of JS used to be done very fast.

(Write what you thought would happen.)

### Actual Behavior

Sometimes, the App crashes jus like that,
It bundles upto 100% and then the same Logo of Expo gets on to the screen.
It's making me kill the App, restart the whole process of Scanning the QR Code and JS bundling happens once again which again takes 6-8 minutes every time it bundles.

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)
There is no way reproducing these steps, I'm just creating the project using Expo XDE,
Scanning the QR code 

One more thing is, I can't use LAN or localhost,
I need to use Tunnel as am on a corporate network, My PC and Mobile can't be on the same network.
you can suggest me to use Expo App in the Android Emulator,
I can't do that either as am trying to develop a Pedometer App which I need to make the mobile device move in order to track or generate the steps.

**Comment by terribleben** [comment]
Hey there! Sorry you're having trouble.

Tunnel connection is always slower than LAN or localhost, because it requires a round-trip through some other server. That's too bad that your corporate network doesn't allow other types of connections. Have you tried changing your firewall settings to accommodate this?

A lot of things can change how fast your app bundles, so it's going to be hard for me to help you much with this information. Here are some things you can take a look at:

- Did you add new dependencies which include a ton of source files?
- Did you include some large assets? If so, have you tried caching them?
- Did you change your project's Expo SDK version?
- Have you tried clearing your packager cache? (This will definitely cause the subsequent load to be slow, but might clear out some bad state in the future)

I hope you can get on the right track! :) I'm going to close this thread because I don't believe it's an issue with Expo. Please feel free to follow up on the [forums](http://forums.expo.io/) if you're still stuck.

**Comment by EnginYilmaz** [comment]
I suffered the same problem because I am using an SD card as mounted disk with Android phone and when I upload the signed apk to phone it crashes or slows down some way.
