### ISSUE TITLE
[iOS] expo-speech has missing voices in iOS 16

### ISSUE THREAD

**Issue by remigallego** [expo/expo#19756]
### Summary

Since iOS 16 we noticed that the text-to-speech voice in German has switched for another one that we don't like. 

After a little investigation, we found that voices returned by `Speech.getAvailableVoicesAsync()` only contains _eloquence_ voices, aka TTS voices for 15 years ago.

Testing back on iOS 15 we were able to use the voice with identifier `com.apple.ttsbundle.Anna-compact`, which we liked, but this one is not recognized anymore when setting it up manually. 

Any chance the `getAvailableVoicesAsync` function can be updated to return all available voices again?

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/lib/ruby/gems/2.7.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^8.3.0 => 8.3.0
      react: 17.0.2 => 17.0.2
      react-native: 0.65.1 => 0.65.1
    Expo Workflow: bare

### Minimal reproducible example

```typescript
const selectVoiceIOS = (voices: Speech.Voice[]) => {
  // When logging this, we noticed only eloquence voices show up on iOS 16.
  console.log("german only voices = ", voices.filter((voice) => voice.language === 'de-DE'));
  return voices.find((voice) => voice.language === 'de-DE') ?? voices[0];
};

Speech.getAvailableVoicesAsync()
        .then((voices) => {
          const germanVoice =
            Platform.OS === 'ios'
              ? selectVoiceIOS(voices)
              : selectVoiceAndroid(voices);
          read(paragraphIndex.current, germanVoice.identifier);
          setVoiceID(germanVoice.identifier);
        })
```

**Comment by barthap** [comment]
Are you sure the iOS 16 still contains the voice you like? Apple could have removed it.
The only thing expo-speech does is do [a system call](https://developer.apple.com/documentation/avfaudio/avspeechsynthesisvoice/1619697-speechvoices?language=objc) to get all available voices [here](https://github.com/expo/expo/blob/6cdcf6514c85e7aacc5fc9167d11b678228eb3bb/packages/expo-speech/ios/EXSpeech/EXSpeech.m#L131).

**Comment by Irrelon** [comment]
Hey folks. It definitely appears that the voices available on iOS Safari as well as MacOS Safari (and I haven't tested but I assume iPadOS Safari) are limited to mostly "eloquence" voices. These voices are robotic and while impressive for their time, are ancient in tech-terms and can create a really REALLY bad user experience.

The "bug" is definitely NOT releated to either the expo-speech code or the underlying use of the web speech API. The issue appears to be a change that Apple has made to the available voices being presented as options to the web speech API specifically on Safari.

For instance, Chrome on MacOS is able to see all available voices whereas the same getVoices() call on MacOS Safari returns a much smaller subset. Interestingly, *some* voices returned are not eloquence-based and you can tell which ones by looking at the voiceURI (they tend to say "com.apple.voice" at the beginning, however it appears that all the available supported voices are fairly robotic-sounding. I've tried a LOT of them to see if any are ok... they are crap.

This is an Apple issue, not an expo-speech issue. The issue affects web-based speech api usage on Safari. You can test different browsers easily with this page: https://plnkr.co/edit/wQzoL69b5vLH7UTb

We need to let Apple know because this is a pretty horrible breaking change to Safari. There is an open discussion in the Apple developer forums here: https://developer.apple.com/forums/thread/723503 but it has garnered only a single, rather disappointing response from an Apple Engineer.

**Comment by niubility000** [comment]
Ios18 still has this problem. Terrible.
I think maybe we can use edge tts （online） in Safari.
