### ISSUE TITLE
unexpected end of script error on Android 4.4

### ISSUE THREAD

**Issue by joacub** [expo/expo#1987]
The stepts to reproduces is very simple, create a new project with expo, detach and run in android phisical device with android kitkat 4.42, always the error is in bundle load, the error change every the line error.

any solution

**Comment by brentvatne** [comment]
I don't have an Android 4.4 device handy to try this on, does this happen on newer devices for you as well?

**Comment by r1nkel** [comment]
Is this related to mine, because I tried to run detached android app (expoKit v1.4.0, expo v29) in the nox emulator which have kitkat 4.4.2, the result is loading screen looping and finally resulted in crash. While in the real device it is fine (but not tested below lollipop version).

![capture](https://user-images.githubusercontent.com/8698419/43706721-5d30cda4-9990-11e8-8d9b-387cb5bfa6fd.JPG)

**Comment by n-sviridenko** [comment]
Same issue

**Comment by JulianKingman** [comment]
@r1nkel any progress on the issue? I'm seeing the same error

**Comment by docaustyne** [comment]
https://github.com/expo/expo/issues/737

also having this issue on production! kind of crazy dev with react-native

**Comment by somangshu** [comment]
Any updates on this. I am having this issue on Expo v32, Expokit 32.0.7. As usual this issue can be found only on some particular devices.

Kindly point to any possible workarounds you may have come across

**Comment by cruzach** [comment]
Since Expo supports only Android 5 and above, I'm going to close this issue in favor of the more generally-applicable [#3674](https://github.com/expo/expo/issues/3674). If you're still seeing this, as stated in the linked issue:

> We know the limitations of the current system, and we're planning to do a significant revamp and rewrite of the OTA updates/code loading system in the clients and standalone apps to focus more on atomicity, consistency, and proper handling of issues like this across the board. However, this is likely on the timescale of 6 months- end of the year and will not be helpful in addressing this particular issue right now.

> With regards to this, we do have an error handling system in place for OTA updates. The expected behavior is that if a given OTA update errors on its first run, the app will mark it as unsafe and revert back to the previous version of the app. It sounds like that mechanism may not working correctly in this particular case. If this issue is important to you, I'd recommend doing some more digging and trying to find the root cause of this issue -- i.e. why the error handling system is failing in this case.

If you do some digging and find something, please share it on that issue!
