### ISSUE TITLE
Splash Screen still not working on web. AppLoading is not deprecated.

### ISSUE THREAD

**Issue by benflightpro** [expo/expo#19957]
### Summary

Splash screen doesn't work on web. Still. And i'm tired of getting warnings that AppLoading is deprecated and i should use splash screen instead because splash screen flat out doesn't work on all the platforms i'm trying to deliver to. 

They straight up deleted the support page for Apploading but its still here cached in google:
https://webcache.googleusercontent.com/search?q=cache:mHY6qX_nOGwJ:https://docs.expo.dev/versions/latest/sdk/app-loading&cd=1&hl=en&ct=clnk&gl=my

now check splash screen:
https://docs.expo.dev/versions/latest/sdk/splash-screen/
That big red check mark under web, haunting me, taunting me. As are the warnings in my console.

You can't say something is deprecated if the thing that deprecated it doesn't even fulfill its use case.

### What platform(s) does this occur on?

Web

### Environment

doesn't matter

### Minimal reproducible example

literally just try it yourself

**Comment by Kudo** [comment]
hi there! i'm sorry we didn't have a smooth migration plan toward AppLoading on web. the main reason is that the AppLoading is just a thin wrapper upon SplashScreen. since SplashScreen doesn't support web, AppLoading on web actually renders nothing.
you could check the implementation of AppLoading [here](https://github.com/expo/expo/tree/sdk-45/packages/expo-app-loading/src) for more information. thanks!
