### ISSUE TITLE
assetBundlePatterns does not allow getting files offline

### ISSUE THREAD

**Issue by orangecoloured** [expo/expo#1999]
### Environment
```
Environment:
  OS: Linux 4.15
  Node: 8.11.3
  Yarn: Not Found
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^27.0.1 => 27.1.0
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/rckt-39bd57e4-d3da-4f22-9eab-66540e19510a.tar.gz
```

An Android app. The bug occurs as in emulator running as Expo app as in standalone apk.

### Steps to Reproduce
1. in `app.json`I have this
```
{
  "expo": {
    "assetBundlePatterns": [
      "assets/snd/*.mp3",
      "assets/fonts/*.ttf"
    ]
  }
}
```
2. in `App.js` I have this
```
export default class App extends React.Component {
  state = {
    isReady: false,
  }

  async loadAssets() {
    await Promise.all([
      Asset.loadAsync([
        require('./assets/snd/win.mp3'),
        require('./assets/snd/deal.mp3'),
        require('./assets/snd/lose.mp3'),
        require('./assets/snd/button.mp3'),
        require('./assets/snd/discard.mp3'),
        require('./assets/snd/avoid.mp3'),
      ]),
      Font.loadAsync({
        'Work Sans Regular': require('./assets/fonts/WorkSans-Regular.ttf'),
      }),
    ]);
  }

  render() {
    if (!this.state.isReady) {
      return (
        <AppLoading
          startAsync={this.loadAssets}
          onFinish={() => this.setState({ isReady: true })}
        />
      );
    }

    return (
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <NavMain />
        </PersistGate>
      </Provider>     
    );
  }
}
```
3. In one of other files I have this piece of code
Here I tried different kinds of paths: relative, absolute. Makes no difference.
```
loadSounds = () => {
  this.props.requestSound('win', require('./../../../assets/snd/win.mp3'));
  this.props.requestSound('lose', require('./../../../assets/snd/lose.mp3'));
  this.props.requestSound('deal', require('./../../../assets/snd/deal.mp3'));
  this.props.requestSound('button', require('./../../../assets/snd/button.mp3'));
  this.props.requestSound('discard', require('./../../../assets/snd/discard.mp3'));
  this.props.requestSound('avoid', require('./../../../assets/snd/avoid.mp3'));
}
```
that uses this saga
```
try {
  const sound = new Audio.Sound();

  yield call(async () => {
    await Audio.setIsEnabledAsync(true);
    await sound.loadAsync(Asset.fromModule(action.src), { shouldPlay: false, positionMillis: 0, volume: 1 }, true);
  });

  yield put({
    type: SOUNDS.ADD,
    sound: {
      [action.name]: sound,
    },
  });
} catch (e) {
  yield fork(() =>  reportError(e));
}
```
and then I play it like this
```
try {
  const sounds = yield select(state => state.Sounds);

  yield fork(async () => {
    await Audio.setIsEnabledAsync(true);
    await sounds[action.name].stopAsync();
    await sounds[action.name].setVolumeAsync(preferences.volume);
    await sounds[action.name].playAsync();
  });
} catch (e) {
  yield fork(() =>  reportError(e));
}
```

### Expected Behavior
Sounds play no matter whether the device is online or offline, as they've been bundled and packaged in the apk.

### Actual Behavior
Being online everything goes well. But being offline throws an error, because it gets `undefined` instead of the sound file.

### Reproducible Demo
[Here's](https://expo.io/@rckt/battle-of-cards) the project.
[Here's](https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40rckt%2Fbattle-of-cards-d73828d7-89eb-11e8-bd7b-0a580a780751-signed.apk) the apk.

**Comment by brentvatne** [comment]
Hi! I'm not super familiar with this API but can ping someone who knows more. A quick question for you:

> But being offline throws an error, because it gets undefined instead of the sound file.

can you elaborate on what you mean by this? what is undefined exactly?

**Comment by orangecoloured** [comment]
@brentvatne 
Here are the errors that Sentry got from the app:
```
Errorblob:file:///dbd6da72-d6be-4177-ab07-b5a91b41feb4
Cannot complete operation because sound is not loaded.
```
```
TypeErrorNone
Cannot read property 'stopAsync' of undefined
```
```
TypeError[native code]
undefined is not an object (evaluating 'n[e.name].stopAsync')
```

**Comment by orangecoloured** [comment]
Any news on this?

**Comment by sjchmiela** [comment]
Hi, @orangecoloured!

Is it possible that you try to play the sound before it loads successfully? This is what the first error, _“Cannot complete operation because sound is not loaded”_ says. 🤔 

In fact the two latter errors suggest that the code that should play the sounds runs before the `requestSound`/`loadAsync` completes (i. e. `await sounds[action.name].stopAsync();` encounters `sounds[action.name] === undefined`).

When it comes to the sound files being unavailable offline, if you change

```js
await sound.loadAsync(Asset.fromModule(action.src), { shouldPlay: false, positionMillis: 0, volume: 1 }, true);
```
to
```js
await sound.loadAsync(action.src, { shouldPlay: false, positionMillis: 0, volume: 1 }, true);
```
the sounds should play when offline. 🙂

I would expect `Asset.fromModule(action.src)` to work as well, so this is a bug I will further investigate. 🕵️

**Comment by orangecoloured** [comment]
Thanks, @sjchmiela 

As for the first assumption, it **is** possible, but if it was the case for the whole issue I wouldn't be filing it. These errors occur no matter how long I am waiting before executing something that involves playing sounds.

As for the `Asset.fromModule`, I think I've already done it the usual way, but I will give it a try once more and will post here the results.

**Comment by sjchmiela** [comment]
I found out what's going on. 🎉 

The argument that is passed to `loadAsync` goes through many functions, one of which is

https://github.com/expo/expo-sdk/blob/bdb61e1990e3794c595244907cb1e82fb75a839d/src/av/AV.js#L76-L88

Let's explain what the function does:

- if a given source is a number (i. e. a `require(…)`), return an `Asset` created from this module,
- if a given source is already an `Asset`, return the asset,
- otherwise, return null.

So, to sum up, `_getAssetFromPlaybackSource` ensures that it does what it can to turn the argument passed to an `Asset`, otherwise it returns `null`.

Result of this function [is used in `_getNativeSourceFromSource`](https://github.com/expo/expo-sdk/blob/master/src/av/AV.js#L94), which tries to return an object that can be passed as source directly to the native player. [If `_getNativeSourceFromSource` gets an `Asset`](https://github.com/expo/expo-sdk/blob/bdb61e1990e3794c595244907cb1e82fb75a839d/src/av/AV.js#L94-L95) from `_getAssetFromPlaybackSource` it knows [it can use its `localUri`](https://github.com/expo/expo-sdk/blob/master/src/av/AV.js#L96) so that the native player uses the local file it it's there.

**What's the problem?** In bundled code `source.constructor.name` isn't `Asset`, but `e`! `_getAssetFromPlaybackSource` doesn't recognize that the source passed is an asset and `getNativeSourceFromSource` doesn't use `localUri` of the object passed. We should have been using `instanceof` to check whether an argument passed is an `Asset`. Submitting a PR!
