### ISSUE TITLE
[expo-crypto] Cannot build app on android

### ISSUE THREAD

**Issue by bombillazo** [expo/expo#20000]
### Summary

Using `expo-auth-session` which imports `expo-crypto` as a dependency brakes the build process when compiling for Android. This is the message one gets:
```sh
> Task :expo-crypto:compileDebugKotlin FAILED
e: /Users/user/Projects/Code/app/node_modules/expo-crypto/android/src/main/java/expo/modules/crypto/DigestAlgorithm.kt: (3, 34): Unresolved reference: Enumerable
e: /Users/user/Projects/Code/app/node_modules/expo-crypto/android/src/main/java/expo/modules/crypto/DigestAlgorithm.kt: (5, 49): Unresolved reference: Enumerable
e: /Users/user/Projects/Code/app/node_modules/expo-crypto/android/src/main/java/expo/modules/crypto/DigestOptions.kt: (5, 34): Unresolved reference: Enumerable
e: /Users/user/Projects/Code/app/node_modules/expo-crypto/android/src/main/java/expo/modules/crypto/DigestOptions.kt: (11, 44): Unresolved reference: Enumerable

FAILURE: Build failed with an exception.
```

### What platform(s) does this occur on?

Android

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/user/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 30, 31, 32
        Build Tools: 30.0.3, 31.0.0, 32.0.0
        System Images: android-28 | Google APIs ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.4.0 => 0.4.0 
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

To reproduce, import the `expo-auth-session` package into a project and install on a device/emulator using `expo run:android`.

**Comment by bombillazo** [comment]
I can confirm this issue props up when using `expo-crypto` v 12, is working

**Comment by bombillazo** [comment]
This commit bumped the `expo-crypto` version from 11 to 12:
https://github.com/expo/expo/commit/eab2b09c735fb0fc2bf734a3f29a6593adba3838

**Comment by tsapeta** [comment]
Thanks for the report! Looks like `expo-auth-session@3.7.1` should work fine (depends on `expo-crypto@11`) so you can downgrade to this version or upgrade SDK to 47. Could you try that?

**Comment by bombillazo** [comment]
Yup! Im using that for now while we can migrate to the newer version.

**Comment by tsapeta** [comment]
Cool, thanks! I also changed `expo-auth-session` version that expo CLI installs for SDK 46 from `~3.7.1` to strict `3.7.1` (so it won't pick `3.7.2` anymore).

**Comment by dansau84** [comment]
it still does not work for me  :  i ´ve got  expo native react project and for just having installed    
npx expo install firebase
npx expo install expo-auth-session expo-crypto expo-web-browser
npx expo install expo-application
npx expo install @react-native-async-storage/async-storage

and if adding just this import   import * as Google from 'expo-auth-session/providers/google';     i got below consistent error when npx expo start     ( not in expo app but dev client )

Android Bundling complete 3307ms
 ERROR  Error: Cannot find native module 'ExpoCrypto', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes


packages.json file is : 

{
  "name": "mytestingapp",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "eas-cli": "^3.15.0",
    "expo": "~48.0.18",
    "expo-application": "~5.1.1",
    "expo-auth-session": "~4.0.3",
    "expo-crypto": "~12.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-web-browser": "~12.1.1",
    "firebase": "^9.23.0",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "sharp": "^0.32.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "tailwindcss": "^3.3.2"
  },
  "private": true
}

any fix ?
