### ISSUE TITLE
StatusBar BackgroundColor not working as expected

### ISSUE THREAD

**Issue by psyanite** [expo/expo#2010]
### Environment

Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4720617

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Running on Genymotion emulator, Samsung S8 Android version 8.0

### Steps to Reproduce

Set androidStatusBar.backgroundColor in app.json and try to make a translucent StatusBar on a specific screen.

Do not have any androidStatusBar configs in app.json and try to apply backgroundColor to a StatusBar on a specific screen.

### Expected Behavior

The properties of the StatusBar on the corresponding screen should be taken at highest priority regardless of the properties in app.json.

### Actual Behavior

The properties in app.json restrict what is modifiable at screen-specific level.

For example, when `"androidStatusBar": { "backgroundColor": "#C2185B" },` is set, translucent status bars `<StatusBar translucent barStyle="dark-content" />` or <StatusBar translucent={true} barStyle="dark-content" />are displayed as opaque with #C2185B, 

Or when app.json does not have any androidStatusBar settings, status bars where backgroundColor is set e.g. `<StatusBar backgroundColor="blue" barStyle="dark-content" />`, are displayed as translucent.

See the screenshots of the snack where the backgroundColor has been set to 'blue', but appears translucent.

![image](https://user-images.githubusercontent.com/24215698/43029458-dd31d1c0-8cc9-11e8-8739-7533e1fceda9.png)

### Reproducible Demo

https://snack.expo.io/@psyanite/statusbar-backgroundcolor-not-working

**Comment by psyanite** [comment]
@ccheever 

Hi, thanks for taking the time to look at my issue.

I have tried to apply the translucent prop but still no luck.

I have updated the original post to follow the issue template as you asked, sorry about that.

Please ask any questions if I have not described my issue clear enough.

**Comment by smbeiragh** [comment]
1. For the first case "**When androidStatusBar settings is an opaque color but translucent is set via StatusBar Component**". 
Turning translucent only changes layouting. so content will render from under status bar. for a non-opaque color you should set a color using the alpha channel like e.g. rgba(r,g,b,a)

2. For the second case "**when app.json does not have any androidStatusBar settings**", 
It's because Expo sets StatusBar translucent mode ON by default and any subsequent change via code has no effect (why?).  and this is intentional "this is what I find out after 3 hours".
Turn translucent mode off by setting the StatusBar color in app.json. After that, you can change StatusBar configuration as mentioned in RN documents using StatusBar component.

**Comment by iwikal** [comment]
Is there really no way to have a translucent statusbar with a custom color while the app is loading?
according to the docs,

>Keep in mind that the Android status bar is translucent by default in Expo apps. But, when you specify an opaque background color for the status bar, it'll lose it's translucency.

This makes it sound like you have the option to specify a non-opaque background color and thereby preserve translucency, but this:
```json
{
  "backgroundColor": "#00000000"
}
```
only seems to make it transparent but not translucent, as the app's background color is shown behind the statusbar instead of my splash image set to `"resizeMode": "cover"`. When the app loads, and I set the statusbar to translucent from the javascript api, the splash image clearly snaps to cover the whole screen.

**Comment by ste-hibo** [comment]
I have the same issue. 
Any solution to this?
This is the issue I am experiencing:
![bar-1](https://user-images.githubusercontent.com/59731643/83144142-426a9600-a0f3-11ea-89f0-2a98874ea865.png)
This happens installing my app from a standard apk after I built it.

And this is the behaviour I expect and that IT WORKS COMPLETELY FINE launching the same app through Expo:
![bar-2](https://user-images.githubusercontent.com/59731643/83144375-865d9b00-a0f3-11ea-8ab8-e30ff835be46.png)

So the status bar works as expected from Expo during development, but it change its behaviour after the build and installing the apk. I noticed that the status bar take its color from the backgroundColor of the splash object defined in app.json. Very weird.
Here my app.json configuration:
![json](https://user-images.githubusercontent.com/59731643/83144643-f10ed680-a0f3-11ea-8fc3-4be768432a0d.png)

**Comment by psyanite** [comment]
FYI I'm using Flutter now :)

**Comment by iwikal** [comment]
@psyanite why did you close this issue, when it's not yet resolved? Even if you're no longer interested in a solution, others might be. If you don't want to participate in the discussion anymore, you can unsubscribe from notifications instead.

**Comment by Noitidart** [comment]
I'm also having same situation. In my production build this below is making the status bar translucent, but there is a transparent light gray background, even though I set `#00000000` for full transparency:

```
    "androidStatusBar": {
      "barStyle": "light-content",
      "translucent": true,
      "backgroundColor": "#00000000"
    },
```

**Comment by b0n1q** [comment]
hey guys, don't you have the same?
<img width="619" alt="image" src="https://user-images.githubusercontent.com/26281760/154943131-61dea25c-4590-49e0-a275-afb0b3330870.png">

**Comment by b0n1q** [comment]
> I'm also having same situation. In my production build this below is making the status bar translucent, but there is a transparent light gray background, even though I set `#00000000` for full transparency:
> 
> ```
>     "androidStatusBar": {
>       "barStyle": "light-content",
>       "translucent": true,
>       "backgroundColor": "#00000000"
>     },
> ```

hi, have you found a solution?

**Comment by Noitidart** [comment]
@b0n1q I haven't yet found a solution :(
