### ISSUE TITLE
[Android] [Expo v47] React Native Debugger doesn't show component tree

### ISSUE THREAD

**Issue by garrettg123** [expo/expo#20119]
### Summary

In my Android Simulator I'm connected to the React Native Debugger on port 8081 and can see console logs and sources, however I can't see the component tree on the left. It's just blank white, even after pressing "Toggle element inspector".

### Managed or bare workflow?

bare

### What platform(s) does this occur on?

Android

### Package versions

"react": "18.1.0",
"react-dom": "18.1.0",
"react-native": "0.70.5",
"expo": "47.0.6",
"expo-dev-client": "~2.0.0",
"expo-updates": "~0.15.5",

React Native Debugger 0.13.0

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    Expo Workflow: bare
```

### Reproducible demo

1. Set up bare Expo project on latest
2. `npx expo run:android`
3. Open React Native Debugger

**Comment by brentvatne** [comment]
this doesn't seem related to the `expo` package being installed in the project. you can verify this by initializing a new project with `npx react-native init`, testing this, and then running `npx install-expo-modules@latest`, and testing again. if you are able to reproduce with those steps then please share a repro. otherwise there isn't much we can do about it from this repository and the issue is better suited for either react-native-debugger or the react-native repo.

**Comment by GabrielMerigo** [comment]
Did you click on `reload app`? When I clicked on it, the app tree showed to me :)
![image](https://github.com/expo/expo/assets/72055874/0597731e-e2fb-4c2f-b46d-777e805fdb15)
