### ISSUE TITLE
MapView "Rubberbanding" (Video & Snack included)

### ISSUE THREAD

**Issue by ballenwillis** [expo/expo#2015]
### Environment
<b>This is also happening in the expo snack emulator</b>

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.4.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/bwillis98-e59f2454-7748-4dd3-8a5f-f1a84c2a01cb.tar.gz

### Steps to Reproduce

1. exp init project
2. Paste the snack (link at bottom)
3. Observe

### Expected Behavior

Map would move how a map should move.

### Actual Behavior
Map is "rubber banding" back and forth.
Video: https://cl.ly/0C1j1e1j2z1f

### Reproducible Demo
Snack: https://snack.expo.io/@bwillis98/google-maps-mapview

**Comment by ballenwillis** [comment]
I updated my version of react native to the desired and here's my new disagnostics:

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.4.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: Not Found
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/bwillis98-95a5992f-7eda-4745-a085-4a5938be0a56.tar.gz



Behavior did not change.

**Comment by sjchmiela** [comment]
Hi @ballenwillis!

The `MapView` is _rubberbanding_ because you've supplied it the `region` prop, which forbids the `MapView` to change `region` to something else (it already knows what to display!) In other words you use it as a controlled component (for the difference between controlled and uncontrolled components see [this article](https://goshakkk.name/controlled-vs-uncontrolled-inputs-react/)).

For the map view to be allowed to behave as you would expect it to behave you'd have to:
- either try using the [`initialRegion` prop](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md) instead of the `region` (the component would become uncontrolled, you could get notified of the changes with other props) [example](
https://github.com/react-community/react-native-maps#mapvie)
- or use the `region` prop with `onRegionChange` (the component stays controlled) [example](https://github.com/react-community/react-native-maps#using-a-mapview-while-controlling-the-region-as-state).

Let me know if you have any more questions!

**Comment by ballenwillis** [comment]
Just in case someone else stumbles upon this, I'll save you the research a little bit.
```
import { MapView } from "expo";
export default class MapScreen extends React.Component {

  static defaultProps = {
    location: null
  };

  render() {
    const {
      location,
      mapRef
    } = this.props;
    return (
          <MapView
            ref={mapRef}
            provider={MapView.PROVIDER_GOOGLE}
            showsUserLocation={location != null}
            followsUserLocation={location != null}
          </MapView>
    );
  }
}
```

And then in the container we have:
```
import { Location, Permissions } from "expo";
import MapScreen from "./MapScreen";

class MapScreenContainer extends React.Component {
  state = {
    location: null
  };

  setRef = input => {
    this.map = input;
  };

  componentDidMount() {
    this.getLocationAsync();
  }

  getLocationAsync = async () => {
    const { status } = await Permissions.askAsync(Permissions.LOCATION);
     if (status === "granted") {
      const locationEnabled = await Location.getProviderStatusAsync();
      if (locationEnabled) {
        const location = await Location.getCurrentPositionAsync({});
        const region = {
          latitude: location.coords.latitude,
          longitude: location.coords.longitude,
          latitudeDelta: LATITUDE_DELTA, // Up to you
          longitudeDelta: LONGITUDE_DELTA // Up t oyou
        };
        this.map.animateToRegion(region);
        await this.setState({ location });
      }
    } 
  };

render() {
    const { location } = this.state;
    return (
      <MapScreen
        mapRef={this.setRef}
        location={location}
      />
    );
  }
}
```

I apologize if something is incorrect or if this doesn't compile or whatever. I just wanted to post something to quickly help someone out.
