### ISSUE TITLE
Reading local .txt file asset

### ISSUE THREAD

**Issue by arpecop** [expo/expo#2029]
Is it possible to read the contents of file located in ./assets/  projects directory with FileSystem , or it operates on completely separated directory ?

**Comment by sr3d** [comment]
@arpecop if you just need to read some external info from a file, instead of having the plain text file, you can convert it to a JSON file and use import, for example

import content from './assets/file.json';

Just make sure your file.json is a proper JSON file and you should be able to read it in.
