### ISSUE TITLE
[docs] TypeScript setup using both `app.config.js` + `app.config.ts` not working as documented

### ISSUE THREAD

**Issue by shiftinv** [expo/expo#20330]
### Summary

The configuration page references `ts-node` for allowing imports of other modules in `app.config.ts`:
https://github.com/expo/expo/blob/dce2e1d65bb3e68237d093a29dce000faeb15c42/docs/pages/workflow/configuration.mdx?plain=1#L145

The link leads to this part, which mentions using `app.config.js`, registering `ts-node` hooks there, and then importing `app.config.ts` which would contain the main config:
https://github.com/expo/expo/blob/dce2e1d65bb3e68237d093a29dce000faeb15c42/docs/pages/guides/typescript.mdx#L129-L143

In practice, `app.config.ts` takes precedence over `app.config.js` (which is documented behavior), resulting in `app.config.js` being ignored completely in this setup and ts-node hooks not being registered.

### Link to the related docs page

https://docs.expo.dev/guides/typescript/#appconfigjs

### Anything else?

I'm not sure what alternative approach would be correct here, both of these appear to work:
- Using `require('ts-node/register')` in `app.config.ts`, completely dropping `app.config.js`
- Renaming `app.config.ts` to something else, and importing that in `app.config.js` as outlined in the documentation, resulting in `app.config.js` being used

**Comment by mryan-rbi** [comment]
I'm also encountering this issue. I think it is due to the order in [`getDynamicConfigFilePath`](https://github.com/expo/expo/blob/97e1898c5797cd25cdefed427683c1e76ead7621/packages/%40expo/config/src/Config.ts#L219).

If both `app.config.js` and `app.config.ts` are present, I would expect that `app.config.js` is there to register `ts-node` for `app.config.ts` and that we would usually want `app.config.js` to take precedence.

If we were to check for `app.config.js` first in `getDynamicConfigFilePath`, would that solve this issue without introducing unexpected behavior?

Where is it documented that `app.config.ts` takes precedence over `app.config.js`?

**Comment by shiftinv** [comment]
Yeah, checking for `app.config.js` first in `getDynamicConfigFilePath` looks like it would solve the issue.

In any case, digging through the history a bit brings up https://github.com/expo/expo-cli/pull/1855, which also makes it seem like the current behavior is intentional(?); I completely agree that it's a bit counter-intuitive though.

> Where is it documented that `app.config.ts` takes precedence over `app.config.js`?

It's somewhat hidden at the bottom of this page:
https://github.com/expo/expo/blob/75692cd5b9ce01245a100e76307a67eae8d1a8a8/docs/pages/workflow/configuration.mdx#L153
