### ISSUE TITLE
ExpoModulesCore PropertyComponent doesn't take owner

### ISSUE THREAD

**Issue by s-abstract** [expo/expo#20543]
### Summary

``` Swift
/**
 Creates the read-only property whose getter takes the caller as an argument.
 */
public func Property<Value: AnyArgument, Caller>(
  _ name: String,
  @_implicitSelfCapture get: @escaping (Caller) -> Value
) -> PropertyComponent {
  return PropertyComponent(name: name).get(get)
}
```

This variant of Property doesn't work because the appropriate `get` method doesn't set `takesOwner` to `true`

``` Swift
  /**
   Modifier that sets property getter that receives the caller as an argument.
   The caller is an object on which the function is called, like `this` in JavaScript.
   */
  public func get<Value, Caller>(_ getter: @escaping (_ this: Caller) -> Value) -> Self {
    self.getter = SyncFunctionComponent(
      "get",
      firstArgType: Caller.self,
      dynamicArgumentTypes: [~Caller.self],
      getter
    )
    return self
  }
```

### What platform(s) does this occur on?

iOS

### Environment

System:
  OS: macOS 12.6
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 17.9.1 - ~/Mirror/.nvm/versions/node/v17.9.1/bin/node
  Yarn: 1.22.19 - ~/.yarn/bin/yarn
  npm: 8.19.2 - ~/Mirror/.nvm/versions/node/v17.9.1/bin/npm
  Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
Managers:
  CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
  Android SDK:
    API Levels: 23, 30, 31, 33
    Build Tools: 28.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
    System Images: android-23 | Google APIs ARM 64 v8a, android-24 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9123335
  Xcode: 14.1/14B47b - /usr/bin/xcodebuild
npmPackages:
  expo: ~47.0.1 => 47.0.1 
  react: 18.1.0 => 18.1.0 
  react-dom: 18.1.0 => 18.1.0 
  react-native: 0.70.4 => 0.70.4 
  react-native-web: ~0.18.9 => 0.18.10 
Expo Workflow: bare

### Minimal reproducible example

Any simple Class with the Property component in any Module

**Comment by s-abstract** [comment]
Worth to mention that I'm open to preparing PR for suggested changes to the ExpoModulesCore API if it's convenient and will speed up the process 😃

**Comment by tsapeta** [comment]
Hi @s-abstract! Thanks for opening the issue 🙂 
Implementations of `Property` and `Class` definition components are not fully finished and their APIs are not stable yet. That's also why they don't appear in the documentation. We were planning on finishing them soon, but now that you've found them, I'll try to fix this sooner 😄
Out of curiosity, may I ask what do you want to use them for? And how did you find them? 😂

**Comment by s-abstract** [comment]
Hey @tsapeta!

First of all, thank you for the quick reply! 😃 

`Out of curiosity, may I ask what do you want to use them for?`

I'm developing VoIP telephony app and want to achieve the following structure:

```Swift
public class ReactNativeVoIPModule: Module {
  public func definition() -> ModuleDefinition {
    Name("ReactNativeVoIP")
    
    Events(...)
    
    Constants(...)
    
    Class(Device.self) {
      Constructor { (accessToken: String, options: Options) -> Device in
        Device()
      }

      Property("calls", \Device.calls)

      AsyncFunction("register") { (device: Device) in
          try await device.register()
      }
      
      AsyncFunction("unregister") { (device: Device) in
          try await device.unregister()
      }

      ...
      
      Class(Call.self) {
        Constructor { (params: [String: String]) in
          Call(uuid: UUID(), params: params)
        }
        
        Property("id", \Call.uuid.uuidString)
        
        Property("to", \Call.to)
        
        AsyncFunction("disconnect") { (call: Call) in
          call.disconnect()
        }

        ...
      }
      
      Class(Audio.self) {
        Constructor {
          Audio()
        }
        
        AsyncFunction("switchOutput") { (audio: Audio, to id: String) in
          audio.switchOutput(to: id)
        }

        ...
      }
    }
  }
}
```

For instance, Imagine if I had a module with all these abstractions and methods flattened to the module level. Starting from that, I would have to add a guard for every method to ensure the correctness of the state. I.e., the device should be initialized before any other action is called.

I love the idea of Classes and how it elegantly solves my structural issues.

I have a couple of ideas about what would be cool to have, will drop them here. Curious to hear what you'd think 😃 
- Events in classes
- Return instances of classes conforming AnySharedObject protocol so that it would instantiate both ways Swift <-> JS
- Use custom registries or sub-registries for nested classes to access collections of native objects/js objects
- Property paths (simply sugar for pleasant builder API)
- Async functions variants with an async/await closure
- Control over destructor for the Class component (probably not always necessary to destruct a native object once js mirrored object is gone)

`And how did you find them? 😂`

As for the Class components, I couldn't find a satisfying solution for the quite complex module's API. My first attempt was to create several modules in a single package, it worked out, but the communication between modules could have been better in terms of synchronization. I've also faced minor matters, which I've reported in another ticket: https://github.com/expo/expo/issues/20488. At this point, I assumed since the Module is a javascript object, it should be possible to implement it in the same module. And I became curious about how Expo does it. So I started investigating how everything is implemented under the hood looking for opportunities to extend interfaces.

That is how I found it 😂

With some extensions and custom builder components, I succeeded in connecting my CallRegistry (aka SharedObjectRegistry) and building those classes I wanted. The code above is actually working. The only component I couldn't do this is the Property 😃 

If you would need any help with implementation or any further information, please, feel free to reach me 😃

**Comment by tsapeta** [comment]
Wow, that's great! Nice to hear that some of the ideas behind Expo Modules API might be helpful for you 😊 
We encountered the same problem (flat module API) in some of our modules, especially `expo-av` where we have a lot of JS code around the native module just to make it object-oriented...

Regarding your ideas, I'll try to address all of them,

> Events in classes

Yeah, we are planning to build a better solution for sending events. Right now they still go through the bridge and limit us in terms of what we can pass as an event payload, so we want to move everything to JSI. One of the ideas is to add native functions like `addListener` and `removeListeners` to every object that has `Events` component. I experimented with that here: https://github.com/expo/expo/commit/16f58c528d48c54b79ec43f38aabbe3469a839dd but that was quite a long time ago 🙈 

> Return instances of classes conforming AnySharedObject protocol so that it would instantiate both ways Swift ↔ JS

I think that was the original plan, it's just not implemented yet and one of the reasons why classes and shared objects are not documented yet 😅 

> Use custom registries or sub-registries for nested classes to access collections of native objects/js objects

Sounds like a good idea!

> Property paths (simply sugar for pleasant builder API)

So basically you mean something like `Property("foo.bar") {}` that would map to `{ foo: { bar: <value> } }` right?
The problem here is that you may also want to have "foo.bar" as a key of the JS object 😅 
We are leaning towards something like this:

```swift
Object("foo") {
  Property("bar") {}
}
```

As we need the `Object` component for other things too. For example we would like to return its definition from the function and automatically convert it to a JS object.

> Async functions variants with an async/await closure

I've tried that already, but implementing it requires more work than I assumed 😞 Anyway, it's on the roadmap!

> Control over destructor for the Class component

It's probably a rare case, but I think it's doable to implement quite easily 🙂 


I'll try to push forward with some of these ideas soon. Our top priority after releasing the stable API was to finally make `expo-image` and then migrate all native views to the new API to make them compatible with Fabric. Since the image is out for alpha testing and there is only one view on iOS to migrate, I think I can prioritize your issues 😄 

Thanks for your feedback, I really appreciate it and digging into the internals and undocumented code 🙌

**Comment by s-abstract** [comment]
I saw you commit with public initializer, you've made my day, thank you! 👏 

> So basically you mean something like Property("foo.bar") {} that would map to { foo: { bar: <value> } } right?
The problem here is that you may also want to have "foo.bar" as a key of the JS object 😅

I meant to use Swift paths 😃  to write something like:

```Swift
func Property<Value: AnyArgument, Caller: AnySharedObject>(_ name: String, _ keyPath: KeyPath<Caller, Value>) -> PropertyComponent {
  Property(name) { (caller: Caller) -> Value in
    caller[keyPath: keyPath]
  }
}
```

And use it the following way:

```Swift
      Class(Call.self) {
        Constructor { (params: [String: String]) in
          Call(uuid: UUID(), params: params)
        }
        
        Property("id", \Call.uuid.uuidString)
        
        Property("to", \Call.to)

        ...
      }
```

I.e., the Swift native object has a more complex and nested structure than we want to see on the JS side. Maybe even try to infer Caller by declaring a dedicated Constructor expression builder as an entry point. And we could write properties `Property("id", \.uuid.uuidString)` or in case the name is the same `Property(\.to)`.

**Comment by tsapeta** [comment]
Hey, I published `expo-modules-core@1.1.0` with a fix for this issue and with some new features like the key paths 😉 To use it in your app, you'll need to use yarn resolutions or npm overrides to make sure the proper version is installed, because the latest `expo` package still depends on `~1.0.x` — I'll update that soon though.

**Comment by s-abstract** [comment]
Thank you so much! You are the best! I will check this out soon and will let you know how it goes :)

**Comment by tsapeta** [comment]
`expo@47.0.10` is now published as well, so you can update it in your example app without resolutions on expo-modules-core 😉
