### ISSUE TITLE
mute:true not working in recordAsync()

### ISSUE THREAD

**Issue by TalTomax** [expo/expo#20626]
### Summary

Upgrading to sdk 47.
expo camera upgrade to the latest version (13.1.0) using expo doctor.

const cameraOption = { mute: true } 
await camera.current?.recordAsync(cameraOption)

The video still recording audio.

Downgrade expo-camera to 12.3.0 fix the problem.
Which means the problem not related to sdk 47 but to expo-camera version 13.1.0.

### What platform(s) does this occur on?

Android, iOS

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/opt/node@16/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/opt/node@16/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.0, 33.0.1
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.9 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.7.0
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

import * as React from 'react';
import { Text, View, TouchableOpacity } from 'react-native';
import { Camera } from 'expo-camera';

export default function App() {
  const [hasPermission, setHasPermission] = React.useState(null);
  const [type, setType] = React.useState(Camera.Constants.Type.back);
  const [isRecording, setIsRecording] = React.useState(false);

  React.useEffect(() => {
    (async () => {
      const { status } = await Camera.requestPermissionsAsync();
      setHasPermission(status === 'granted');
    })();
  }, []);

  if (hasPermission === null) {
    return <View />;
  }
  if (hasPermission === false) {
    return <Text>No access to camera</Text>;
  }

  async function startRecording() {
    if (isRecording) {
      return;
    }

    setIsRecording(true);
    const video = await camera.recordAsync({
      mute: true, // this will disable audio recording
      quality: Camera.Constants.VideoQuality['480p'],
      maxDuration: 30,
    });

    console.log(video);
    // do something with the recorded video
    setIsRecording(false);
  }

  return (
    <View style={{ flex: 1 }}>
      <Camera style={{ flex: 1 }} type={type} ref={ref => { camera = ref; }}>
        <View
          style={{
            flex: 1,
            backgroundColor: 'transparent',
            flexDirection: 'row',
            justifyContent: 'space-around',
            alignItems: 'flex-end',
          }}>
          <TouchableOpacity
            style={{
              alignSelf: 'flex-end',
              alignItems: 'center',
              backgroundColor: 'transparent',
            }}
            onPress={() => {
              setType(
                type === Camera.Constants.Type.back
                  ? Camera.Constants.Type.front
                  : Camera.Constants.Type.back
              );
            }}>
            <Text style={{ fontSize: 18, marginBottom: 10, color: 'white' }}> Flip </Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={startRecording} style={{ alignSelf: 'flex-end' }}>
            <Text style={{ fontSize: 18, marginBottom: 10, color: 'white' }}> Record </Text>
          </TouchableOpacity>
        </View>
      </Camera>
    </View>
  );
}

**Comment by bfar97** [comment]
Facing the same issue. expo-camera@13.1.0 and expo sdk47.

**Comment by TalTomax** [comment]
any updates? this is the only reason i'm still on expo 46.

**Comment by gnoel** [comment]
I'm having the same problem.
Looks like the `mute` option is ignored.

When calling the `recordAsync` function with parameter `{ mute: true }`, I'm getting this error: 
`Unhandled promise rejection Error: "Call to function 'ExponentCamera.record' has been rejected.
→ Caused by: Missing permissions: android.permission.RECORD_AUDIO" in construct@[native code] << construct@[native code] << a << t`
It doesn't work because it needs the microphone authorization (but it doesn't need it as I don't want to record the audio)

If you grant the microphone access permission, the recording work well but the created video will have the sound captured by the microphone.

Here a Snack exemple that trigger the microphone authorization error (you need to remove Expo Go authorisations first, or do a fresh install of the app, before testing it)
https://snack.expo.dev/@nono4747/camera-video-recording-with-mute-true-not-working
Running Expo Camera `~13.1.0` on SDK `47.0.0`
Based on the basic camera exemple from the Expo doc
Reproduced on a Google Pixel 6
