### ISSUE TITLE
 Exception occurred while executing 'list': getting expection error on expo app.

### ISSUE THREAD

**Issue by theabhayprajapati** [expo/expo#20636]
### Summary

I am using expo to build react native apps.
on windows .
and when ever i run the npx expo start and then 'a' to start the app on android it show me error.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/88815641/209908394-771fbc02-4df4-4aeb-9a52-c0b5f8e603c8.png">

### Environment

system cannot read specified path

### Minimal reproducible example

create  a new expo app with `npx create-expo-app newapp`
run the app.
`npx expo start`
Click `a` for 'running on android phone
 
![image](https://user-images.githubusercontent.com/88815641/209909926-eb3e3fc4-b916-4ed5-883b-7d45b6758930.png)

**Comment by brentvatne** [comment]
this looks like it may be an issue with the state of your device: https://android.stackexchange.com/questions/243104/getting-java-lang-securityexception-shell-does-not-have-permission-to-access-u

**Comment by Kubaguette** [comment]
Same problem for me, youre not the only one here. 

When I try to compile my app on my galaxy Z Fold 3 I get the same error message as you.
On the other side, when I connect my Nokia 8 with android to my pc and try to compile it there, its working flawlessly. 

Still trying to figure out how to solve that.

**Comment by plfmoura** [comment]
Same problem for me, when i running my app with
`"npx expo run:android" `
and press
`"a"`
 to run in my real USB device...

**Comment by VagnerSilva** [comment]
> Same problem for me, when i running my app with `"npx expo run:android" ` or `'npx expo start'` and press `"a"` to run in my real USB device... the app appears in my device but don't works...

I solve it with native

Before solving this problem, it is necessary to confirm that when running

```bash
 npx expo start
```
make sure the service is running on the localhost machine.


open the browser and enter the IP/Host and PORT.

192.168.x.x:8081

If any content appears, everything is fine.

If by chance it does not load even one content, some steps can be followed to correct it.


make sure your host machine is on the same network as your device by performing the ping test to your device's IP

Check firewall settings, enable port 8081
if you are on PC/Windows, reset the firewall with the following command.
```bash
 netsh advfirewall reset
```
If you are using 'Windows', you need to manually modify the 'metric' parameter in the IPv4 protocol of your connection

Follow the tutorial in the link changing the parameter "metric" to 10 and restart the connection

[metric_10](https://stackoverflow.com/questions/47966887/expo-lan-configuration-doesnt-work-for-new-reactnative-project)


Test again in browser
192.168.x.x:8081
(these steps fixed this first problem for me. In some cases I had to change the port)


Now that we validate the connection on the host
we can follow the steps for error '150'

in terminal

```bash
 cd  android
./grandlew clean 
```

Or delete android/ios folder and run again
```bash
npx expo prebuild
```

in root dir

```bash
 npx expo customize metro.config.js  
```
```bash
  npx react-native start
```
press "a" for install app

In some cases it will automatically open the app in others you must open it manually
look for the name of the application. In some, the installed device only appears after a few seconds of the error or you have to look for the name for it to appear.
If you search and don't find the app press "a" again, usually the second time it installs

With the app open, even if an error appears, press the letter "d" in the terminal to open the menu on the device

If the menu does not appear, it means that the host is not working correctly.
To check, open your browser and enter IP/Host and port "192.168.x.x:8081"
Usually some process is blocking the port.
Terminate RN process in terminal and look for open processes on port 8081 and terminate them or change port and run "start" process again and test in browser IP:PORTA
(**Remember** _if when doing the test in the browser, no content is opened, the problem is in some blocking/configuration of your local machine_)

With the menu open on your device click on "settings/debug server host & port for device"

add IP/Host and port

"192.168.x.x:8081"  press "OK"

in terminal press "d" again and click "reload" in device

If your application doesn't even have an error it will work normally.

You can use "expo start or reac-native start"

<a href='https://ko-fi.com/vagnersilva82/goal?g=0' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://cdn.ko-fi.com/cdn/kofi3.png?v=3' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>

**Comment by Fang86** [comment]
The only solution that worked for me was uninstalling Secure Folder (user 150).

Source: https://android.stackexchange.com/questions/243104/getting-java-lang-securityexception-shell-does-not-have-permission-to-access-u

**Comment by Shahzaib114** [comment]
here's possible workaround solution
problem regarding to platform/adb.js
https://github.com/expo/expo/issues/22473#issuecomment-1546718389
