### ISSUE TITLE
Dependency conflict for react-native-firebase/auth and expo-face-detector

### ISSUE THREAD

**Issue by northfoxz** [expo/expo#20644]
### Summary

Hi, when installing expo-face-detector into my project, I got the following error
```
Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    EXFaceDetector (from `../node_modules/expo-face-detector/ios`) was resolved to 12.0.0, which depends on
      MLKitVision (= 3.0.0) was resolved to 3.0.0, which depends on
        GTMSessionFetcher/Core (~> 1.1)

    RNFBAuth (from `../node_modules/@react-native-firebase/auth`) was resolved to 16.5.0, which depends on
      Firebase/Auth (= 10.3.0) was resolved to 10.3.0, which depends on
        FirebaseAuth (~> 10.3.0) was resolved to 10.3.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)
```

this may be resolved by upgrading the MLKitVision to the latest version and some workarounds.

reference: [https://issuetracker.google.com/issues/254418199#comment48](https://issuetracker.google.com/issues/254418199#comment48)

### What platform(s) does this occur on?

iOS

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
      npm: 9.1.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Managers:
      CocoaPods: 1.11.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 24, 26, 27, 28, 29, 30, 31
        Build Tools: 23.0.1, 23.0.3, 24.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.1, 28.0.2, 28.0.3, 29.0.2, 30.0.0, 30.0.2, 31.0.0, 33.0.0, 33.0.0
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.9 => 47.0.9 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 3.1.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Minimal reproducible example

Install react-native-firebase/auth and expo-face-detector with dev client.
Run `npx expo prebuild --clean` and you will get the error message above.

**Comment by brentvatne** [comment]
expo-face-detector isn't always kept up to date, and this may occur in some cases. the most likely path forward with this module is that we will deprecate it and stop supporting it, so it may be best to explore other alternatives.

**Comment by northfoxz** [comment]
Got it, thanks for replying

**Comment by RazaShehryar** [comment]
@northfoxz you can actually make it work by patching it. I acutally removed the version mentioned alongside each of the dependencies.

So in order to make it work, go to `ios => EXFaceDetector.podspec` file, then paste this.

`
require 'json'

package = JSON.parse(File.read(File.join(__dir__, '..', 'package.json')))

Pod::Spec.new do |s|
  s.name           = 'EXFaceDetector'
  s.version        = package['version']
  s.summary        = package['description']
  s.description    = package['description']
  s.license        = package['license']
  s.author         = package['author']
  s.homepage       = package['homepage']
  s.platform       = :ios, '13.0'
  s.source         = { git: 'https://github.com/expo/expo.git' }
  s.static_framework = true

  s.dependency 'ExpoModulesCore'

  # even though `GoogleMLKit/FaceDetection` depends on all `MLKit*` references below
  # framework generation code (prebuilds) cannot locate them properly, so these are defined explicitly
  # TODO: research why xcodegen fails to detect dependencies of dependencies (resulted .xcodeproj is missing them)
  s.dependency 'GoogleMLKit/FaceDetection'
  s.dependency 'MLKitFaceDetection'
  s.dependency 'MLKitCommon'
  s.dependency 'MLKitVision'

  if !$ExpoUseSources&.include?(package['name']) && ENV['EXPO_USE_SOURCE'].to_i == 0 && File.exist?("#{s.name}.xcframework") && Gem::Version.new(Pod::VERSION) >= Gem::Version.new('1.10.0')
    s.source_files = "#{s.name}/**/*.h"
    s.vendored_frameworks = "#{s.name}.xcframework"
  else
    s.source_files = "#{s.name}/**/*.{h,m}"
  end
end
`
