### ISSUE TITLE
Release Build

### ISSUE THREAD

**Issue by waheed25** [expo/expo#2071]
I want to know about expo is it makes release build every time by default with exp build:{android, ios}  or we need to mention this in some command like release build channel?

**Comment by AdamJNavarro** [comment]
Hey @waheed25,

This type of question is better suited for our forums. We like to keep github issues limited to bugs. I'm not entirely sure what you mean by your question, but the build command creates a release build (rather than a debug one) if that's what you are getting at. As for using release channels, this command can be used to specify where to publish your bundle `exp build:ios --release-channel <your-channel>`

If that doesn't answer your question, please make a post on our forums https://forums.expo.io/

Cheers,

Adam
