### ISSUE TITLE
Uncaught Error: java.net.SocketTimeoutException error within windows 11 android subsystem

### ISSUE THREAD

**Issue by JakeWayneMurray** [expo/expo#20748]
This is an issue I am running into while trying to use the android subsystem with windows 11. I got expo go installed and when I go to open an application that is running locally within expo in my account.

When I go to open an app that is currently running on my account within expo I am now getting this error.

![image](https://user-images.githubusercontent.com/109402063/211221115-c448e08a-6a91-4931-988c-8e7f06802edf.png)

_Originally posted by @JakeWayneMurray in https://github.com/expo/expo/issues/20650#issuecomment-1374937088_

**Comment by ys-333** [comment]
even same problem I am facing, I tried to configure the IPv4 and then also added new bundler in window firewall, but still not working..

**Comment by ys-333** [comment]
okay so I turned off Microsoft defender firewall and it's working for me, I don't think that's right approach as it could lead to some potential threat to system.

**Comment by byCedric** [comment]
You'd have to check if Windows subsystem for Android has access to the host machine's IP, and maybe add [special networking config](https://gist.github.com/bergmannjg/461958db03c6ae41a66d264ae6504ade#enable-access-to-metro-bundler-from-windows). Generally speaking, Expo Go requires network access for Metro.

The `192.168.x.x` seems like the LAN IP within your network. Sometimes Windows could see this as access from outside, depending on if you configured your local network as a public or private network. That could explain why disabling the firewall fixes access. Alternatively, you could open port 19000 and 8081 in your firewall instead of entirely disabling it.

Hope this helps!

**Comment by ys-333** [comment]
@byCedric Thanks man, it's working!!

**Comment by JakeWayneMurray** [comment]
Kind of a side note, but the main reason I want this working is so I don't have to use Android Studio's emulator to run local code. Could be a big marketing point for the app if you get it on the amazon appstore (as that's where you install android apps from in windows 11).

I'm sure replacing Android studio for dev work would be a big win for Expo!

**Comment by JakeWayneMurray** [comment]
After opening ports 19000 and 8081 and even turning my windows firewall off I still can't get the android subsystem to connect to my locally running server (on the same device)
