### ISSUE TITLE
expo bundle-assets --platform ios --dest bundle-dest err

### ISSUE THREAD

**Issue by juvham** [expo/expo#2075]
Error: read ETIMEDOUT
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)

**Comment by jakubste** [comment]
Could you provide more details?

**Comment by juvham** [comment]
when run this command is take very long time,and throw err like that . I don't understand what's happened, Isn't it a local command?

**Comment by casieber** [comment]
I've been running into the same issue and may have found a reason.

This is not just a local command. It attempts to download your assets from https://d1wp6m56sqw74a.cloudfront.net/~assets as seen here:
https://github.com/expo/expo-cli/blob/bf16aeef6b72cfbe3f6b586013feeb524d0058cf/packages/xdl/src/detach/AssetBundle.js

If you are running this behind some sort of corporate proxy, like I am, this download can fail.

Unfortunately, it always seems to use this URL, even if you (like I do) are using `expo export` to host your assets yourself. There isn't currently a way to provide it with a custom URL / path to your `export` results to use to get the assets instead. You can see here that they are always passing `null` for the `context` param that would otherwise allow you to specify: https://github.com/expo/expo-cli/blob/bf16aeef6b72cfbe3f6b586013feeb524d0058cf/packages/xdl/src/detach/Detach.js

**Comment by casieber** [comment]
Was there a resolution here?

**Comment by cruzach** [comment]
over-simplistic summary: the `expo-updates` scripts that run this bundle-assets command are no longer used (unless you're on `expo-updates@0.1.0`, in which case you should update but make sure to look at the changelog), so you shouldn't see this problem any more in the future. The new scripts do not ping Expo's CDN, and also function a lot more intuitively by following the same patterns as React Native's default asset-bundling behavior
