### ISSUE TITLE
[docs] expo-task-manager

### ISSUE THREAD

**Issue by jreason** [expo/expo#20856]
### Summary

How do you use this in a bare react native app?

The suggested link on the documentation appears to be out of date?

https://gist.github.com/mczernek/a62413ca517cfd5dac015f5527dafef0

### Link to the related docs page

https://github.com/expo/expo/tree/sdk-47/packages/expo-task-manager

**Comment by amandeepmittal** [comment]
Hi @jreason, you can use the automatic installation part in this doc: https://docs.expo.dev/bare/installing-expo-modules/#automatic-installation that configures Expo modules in an existing bare app. If the command mention in that step fails (for some reason), then you can use the manual steps in the same doc link referenced.

Will look into updating the package docs link you referenced. Thanks for catching that.

**Comment by amandeepmittal** [comment]
Hi @jreason, we've updated the instructions in bare section for installing `expo-task-manager` package for the latest SDK (on main branch).

As you pointed out, the gist was outdated since the changes that gist suggested outdated and up-to-date instructions are now included in manual bare workflow installation instructions for iOS on this page: http://localhost:3002/bare/installing-expo-modules/#configuration-for-ios. The latest SDK requires replacing `RCTAppDelegate` with  `EXAppDelegateWrapper`.

Closing this issue for now.
