### ISSUE TITLE
[expo-asset] Local uri is incorrect in Android prod builds

### ISSUE THREAD

**Issue by AadneEM** [expo/expo#21072]
### Summary

After calling `asset.downloadAsync()` the localUri seems to always just be `assets_{filename}`. When running expo locally it works as I would expect, and it doesn't seem to have any similar issues on iOS.

This is the result of the minimal reproducible example bellow:
| Running through `expo start` | Prod Build | 
| ---------| ----------| 
|![dev-small](https://user-images.githubusercontent.com/16845330/216540614-b4b5a03c-d44b-4e35-8fd7-ce8e7b4fc969.jpg)|![prod-small](https://user-images.githubusercontent.com/16845330/216540635-37fc633d-8ece-4009-9d31-496b233851d5.jpg)|

It does seem to get fixed after a eas update, but untill then this is the result. 

### What platform(s) does this occur on?

Android

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed
```

### Minimal reproducible example

```javascript
import { StatusBar } from 'expo-status-bar';
import { useEffect } from 'react';
import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';

import { useAssets } from 'expo-asset'

export default function App() {
  const [assets, error] = useAssets([require('./assets/icon.png')])

  useEffect(() => {
    if (assets?.length && !(assets[0].downloaded || assets[0].downloading)) {
      assets[0].downloadAsync()
    }
  }, [assets])

  if (!assets?.length || !assets[0].downloaded) {
    return (
      <View style={styles.container}>
        <ActivityIndicator />
      </View>
    )
  }

  return (
    <View style={styles.container}>
      <Text>Asset URI:</Text>
      <Text>{assets[0].localUri}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by matheustdinni** [comment]
I have the same problem, I'm using expo SDK 45. When I load the assets (images and pdf) the app can't return the URI, but this only happens in build.

Debugging the app I get the following message:
`FileSystem Module: Unsupported scheme for location`

Did you find any solution?

**Comment by AadneEM** [comment]
I have not found any solution yet, no.
Only the unoptimal workaround I mentioned in my original comment where you can push out an update through `eas update` after deploying a new version through the normal means.

**Comment by pafry7** [comment]
@AadneEM @matheustdinni It is not a bug: https://github.com/facebook/react-native/issues/18216#issuecomment-412569517

**Comment by carri9372** [comment]
I find the image is under res/drawable folder after prod build, you can get it by the local uri.

**Comment by draco961** [comment]
# expo-asset `downloadAsync()` does not download bundled images on Android production builds (AAB)

## Environment

- **expo-asset**: ~12.0.x (tested with 12.0.9)
- **Platform**: Android (AAB production builds only — debug builds are unaffected)
- **Expo SDK**: 52+

## Description

When using `useAssets()` or `Asset.fromModule()` to load bundled image assets, `localUri` returns a **drawable resource name** (e.g., `assets_images_coloredlogo`) instead of a valid `file://` path on Android production builds.

Calling `downloadAsync()` has **no effect** because the asset is already flagged as `downloaded = true`.

This makes it impossible to read the file contents (e.g., converting to base64 for embedding in HTML).

## Root Cause

In `expo-asset`'s `Asset.fromModule()`, bundled image assets on Android are pre-marked as downloaded with the drawable resource name as `localUri`:

```ts
// expo-asset/src/Asset.ts — fromModule()
if (Platform.OS === 'android' && !uri.includes(':') && (meta.width || meta.height)) {
    asset.localUri = asset.uri;   // drawable resource name, NOT a file:// path
    asset.downloaded = true;       // prevents downloadAsync() from actually downloading
}
```

Then in [downloadAsync()](vscode-file://vscode-app/c:/Users/guill/AppData/Local/Programs/Microsoft%20VS%20Code/ce099c1ed2/resources/app/out/vs/code/electron-browser/workbench/workbench.html), the early return skips the native module call that would copy the asset to cache:

``` ts
// expo-asset/src/Asset.ts — downloadAsync()
async downloadAsync(): Promise<this> {
    if (this.downloaded) {
        return this; // ← skips native download entirely
    }
    // ... native download that produces a proper file:// localUri
}
```

| Debug vs Production |  |  |  |
|---|---|---|---|
| Build type | localUri value | downloaded | downloadAsync() |
| Debug | file:///data/user/0/.../cache/ExponentAsset-2693f8fd.png | false → true | Works correctly |
| Production (AAB) | assets_images_coloredlogo | true (pre-set) | No-op, returns immediately |

## Workaround
Before calling [downloadAsync()](vscode-file://vscode-app/c:/Users/guill/AppData/Local/Programs/Microsoft%20VS%20Code/ce099c1ed2/resources/app/out/vs/code/electron-browser/workbench/workbench.html), check if [localUri](vscode-file://vscode-app/c:/Users/guill/AppData/Local/Programs/Microsoft%20VS%20Code/ce099c1ed2/resources/app/out/vs/code/electron-browser/workbench/workbench.html) is a drawable resource name (not a  URI) and reset the [downloaded](vscode-file://vscode-app/c:/Users/guill/AppData/Local/Programs/Microsoft%20VS%20Code/ce099c1ed2/resources/app/out/vs/code/electron-browser/workbench/workbench.html) flag:


``` ts
import { useAssets } from 'expo-asset';
import { File } from 'expo-file-system';

const [assets] = useAssets([
    require('@/assets/images/my-image.png'),
]);

async function getImageBase64(): Promise<string> {
    const asset = assets?.[0];
    if (!asset) return '';

    // On Android AAB builds, localUri is a drawable name like
    // "assets_images_my_image" — not a file path.
    // Reset the flag to force the native download to cache.
    if (asset.downloaded && asset.localUri && !asset.localUri.startsWith('file:')) {
        asset.downloaded = false;
    }

    await asset.downloadAsync();
    // localUri is now: file:///data/user/0/<app>/cache/ExponentAsset-<hash>.png

    if (asset.localUri) {
        const file = new File(asset.localUri);
        const base64 = await file.base64();
        return `data:image/png;base64,${base64}`;
    }

    return '';
}
```

## Expected Behavior
[downloadAsync()](vscode-file://vscode-app/c:/Users/guill/AppData/Local/Programs/Microsoft%20VS%20Code/ce099c1ed2/resources/app/out/vs/code/electron-browser/workbench/workbench.html) should detect that [localUri](vscode-file://vscode-app/c:/Users/guill/AppData/Local/Programs/Microsoft%20VS%20Code/ce099c1ed2/resources/app/out/vs/code/electron-browser/workbench/workbench.html) is not a valid file path and proceed with the native download regardless of the [downloaded](vscode-file://vscode-app/c:/Users/guill/AppData/Local/Programs/Microsoft%20VS%20Code/ce099c1ed2/resources/app/out/vs/code/electron-browser/workbench/workbench.html) flag.

# Thanks

Big thank to Claude Opus 4.6 to have helped me finding this issue (Claude sonnet 4.6 and Gemini 3.1 pro couldn't help me )
