### ISSUE TITLE
Something went wrong, signature was incorrect error on android emulator after eas update

### ISSUE THREAD

**Issue by akifmertturk** [expo/expo#21484]
### Minimal reproducible example

eas update --branch master --message "Updating the app"

### Summary

These new lines were added and **caused** the problem;
- `"updates": {
      "url": "https://u.expo.dev/<<projectId>>"
    },
  "extra": {
      "eas": {
        "projectId": "<<projectId>>"
      }
    },
    "runtimeVersion": {
      "policy": "sdkVersion"
    }`

When I try to load the app on the emulator, the app shows a blue screen saying :
 _`Something went wrong. Sorry about that. You can go back to Expo home or try to reload the project`_
And when I view the **error logs** :
_`Uncaught Error: java.io.IOException: Manifest download was successful, but signature was incorrect`_

**Solution**
Discard the changes on app.json ( or delete those newly added lines after running the `eas update --branch master --message "Updating the app"` command), and restart the project, that's it.

I wonder where am i doing right and wrong, thanks in advance.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 31, 33, 33
        Build Tools: 31.0.0, 33.0.0, 33.0.2
        System Images: android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ~46.0.13 => 46.0.15
      react: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed
```

**Comment by douglowder** [comment]
@akifmertturk the command `eas update` bundles your JS and assets into an update bundle that is then uploaded to the EAS service. The extra lines you see are added because your project is missing the required EAS project ID and URL need for updates to work. The URL is where the app sends the request to see if there is an update that needs to be downloaded and launched. `eas update` detects that your app is not yet configured for using the update service, and attempts to fix the issue by essentially running `eas update:configure` to set everything up.

The best way to use EAS Update is with EAS builds. I would recommend going through the guides below:

Getting started with EAS Build: https://docs.expo.dev/build/setup/
Getting started with EAS Update: https://docs.expo.dev/eas-update/getting-started/

If you want to try out updates with a local build on your development machine, which seems to be what you are attempting to do, you should go through this tutorial: https://docs.expo.dev/eas-update/eas-update-with-local-build/

**Comment by reflect-zz** [comment]
> ### Minimal reproducible example
> eas update --branch master --message "Updating the app"
> 
> ### Summary
> These new lines were added to `app.json` file and **caused** the problem;
> 
> * `"updates": { "url": "https://u.expo.dev/<<projectId>>" }, "extra": { "eas": { "projectId": "<<projectId>>" } }, "runtimeVersion": { "policy": "sdkVersion" }`
> 
> When I try to load the app on the emulator, the app shows a blue screen saying : _`Something went wrong. Sorry about that. You can go back to Expo home or try to reload the project`_ And when I view the **error logs** : _`Uncaught Error: java.io.IOException: Manifest download was successful, but signature was incorrect`_
> 
> **Solution** Discard the changes on app.json ( or delete those newly added lines after running the `eas update --branch master --message "Updating the app"` command), and restart the project, that's it.
> 
> I wonder where am i doing right and wrong, thanks in advance.
> 
> ### Environment
> ```
> expo-env-info 1.0.5 environment info:
>     System:
>       OS: Windows 10 10.0.19044
>     Binaries:
>       Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
>       Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
>       npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
>     SDKs:
>       Android SDK:
>         API Levels: 28, 31, 33, 33
>         Build Tools: 31.0.0, 33.0.0, 33.0.2
>         System Images: android-31 | Google APIs Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
>     IDEs:
>       Android Studio: AI-213.7172.25.2113.9123335
>     npmPackages:
>       expo: ~46.0.13 => 46.0.15
>       react: 18.0.0 => 18.0.0
>       react-native: 0.69.6 => 0.69.6
>     Expo Workflow: managed
> ```

**This solve the problem, thank you.**
