### ISSUE TITLE
Implement Featherjs  3.0 in Expo

### ISSUE THREAD

**Issue by pankajtft** [expo/expo#2153]
In one of our project previously we are using the Featherjs(V 2.0)(https://docs.feathersjs.com) and  application was running smoothly . Few month ago a new version of featherjs was released(3.0) and we decided to migrate the feather 2.0 to 3.0. We follow this link for migration([https://docs.feathersjs.com/migrating.html]. 
After updating and making all these the change when we run the application we got below error.

The package at "node_modules/@feathersjs/socketio/lib/index.js" attempted to import the Node standard library module "http". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo.

As per above link of expo we could not use the code node apis with react-native and expo.
so there is any way to resolve this error i mean how to configure the node http api in expo project.

**Comment by ide** [comment]
The JS environment Expo provides is different than Node's, similar to how the JS environment in a web browser is different from Node's. Expo is not designed to be a Node.js replacement and there are several subtle impedance mismatches between clients and servers and providing polyfills for Node APIs isn't something we're focusing on.

The technically best approach I'd suggest is to write a socketio replacement that is designed for a client rather than a server and patch it in with Yarn's "resolutions" feature. You might be able to achieve the same by writing an http module as well.
