### ISSUE TITLE
iOS Location Permission askAsync not resolving

### ISSUE THREAD

**Issue by lijtong** [expo/expo#2155]
This issue arises only in a standalone iOS app, when calling Permissions.askAsync the call never resolves. #1668 was closed but we're still having this issue currently.

SDK Version 29.0.0

Steps to reproduce:
Create new standalone expo app for iOS with the following infoplist:
```
"ios": {
  "infoPlist": {
    "NSLocationAlwaysUsageDescription": "stuff",
    "NSLocationWhenInUseUsageDescription": "stuff"
  }
}
```
Call Permissions.askAsync(Permissions.LOCATION)

Expected outcome:
Dialog popup for permission granting

Actual outcome:
Dialog doesn't show up, and subsequent code doesn't execute as well

There was a possible suggested solution in #1668 stating that removing the infoplist would allow the call to resolve, but this is not a practical fix due to future problems that it poses with the AppStore uploading.

**Comment by ide** [comment]
From this [StackOverflow post](https://stackoverflow.com/questions/26005122/requestalwaysauthorization-not-showing-permission-alert/47050635#47050635) it sounds like adding `NSLocationAlwaysAndWhenInUseUsageDescription` so you have all three plist keys may help.

**Comment by lijtong** [comment]
Adding ```NSLocationAlwaysAndWhenInUseUsageDescription``` to the plist still ends up with the same result, askAsync does not get resolved.

**Comment by ide** [comment]
Try removing `NSLocationAlwaysUsageDescription` then, unless you've manually patched the location module to support background location updates?

**Comment by thu-sama** [comment]
@wassgha Thanks. By adding all solved in detached app too.

**Comment by sjchmiela** [comment]
Hi all! This bug has just been fixed in https://github.com/expo/expo/commit/24751424a0f1803979734b2d610ffec430c78f9c.

It turns out you shouldn't ever have to provide `NSLocationAlwaysUsageDescription` as it won't ever be used properly (apps built by Expo won't have background mode and won't be able to use the alwaysity of the permission). After this fix lands apps will always ask for `whenInUse` permission.

We'll push the update to the builders as soon as possible and close the issue then. Thank you for your understanding! 🙂

**Comment by farzd** [comment]
related: https://github.com/expo/expo/issues/2099

**Comment by farzd** [comment]
@sjchmiela is this fixed with expo 30?

**Comment by sjchmiela** [comment]
Hi all! The fix has been pushed to builders a long time ago, but I forgot to close this issue.

@aatreya Could you please open a new issue regarding your problem? This will require a little bit of R&D to fix properly. 🙂
