### ISSUE TITLE
Error rendering in Smartphone after command line: "exp start --tunnel --dev --exp"

### ISSUE THREAD

**Issue by dantejauregui** [expo/expo#216]
Hello Expo Team,
My computer is ubuntu 32bits, so I can just use Expo CLI,
I had days ago a problem after writting at cli: "exp start --tunnel --dev --exp", appear the QR Code but in my cellphone appear Error Log: **"Uncaught Error: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:19000"**

After this, I have been reading this issue [](https://github.com/react-community/create-react-native-app/issues/81)
and **I tried the solution to specify the QRCode URL with the IP of my computer** with:  **REACT_NATIVE_PACKAGER_HOSTNAME=' 192.168.**.** ' npm start**

![qrcoderenderingexpo](https://cloud.githubusercontent.com/assets/10466343/26529838/af468c8c-438d-11e7-93e0-c0031237d752.png)

My problem Im having the same error (error log), maybe because is not recognizing the IP address that I configured in order to render :(

Please Team can you help me cause I cannot see the react code im writing with EXPO cli :(

**Comment by terribleben** [comment]
Hi, can you try `exp start --tunnel` again? It's possible our tunnel service was intermittently failing. In that case it may have fallen back to providing you with a `localhost` url. Localhost won't work on your mobile device (since it refers to your laptop).

If you're still having trouble, can you open a topic on forums.expo.io ?
