### ISSUE TITLE
Do you subscribe topic on push notification?

### ISSUE THREAD

**Issue by weeravit** [expo/expo#217]
Do you have any idea?
https://docs.expo.io/versions/v17.0.0/guides/push-notifications.html

**Comment by terribleben** [comment]
Hi, can you clarify your question?

**Comment by weeravit** [comment]
I'm sorry for information.
Can I push notification to every user in my app by don't use specify token of users?

**Comment by terribleben** [comment]
You will need to specify the push tokens of all the users in that case. That's just how the underlying Apple and Google APIs are designed.

**Comment by travoux** [comment]
Understand how APNS and Google APIs are designed. 
But like other Push services (Firebase, OneSignal, SNS etc.,) does Expo support delivering push notifications to a group of users subscribed to a topic? I think it is a common requirement for all apps. Otherwise the app developers will end up managing all the subscriptions and posting hundreds of notifications from the server..
It will be really useful if this feature is supported
