### ISSUE TITLE
[ImagePicker] - When choosing a video on iPhone, the size of the video is larger than what is reported by the iPhone

### ISSUE THREAD

**Issue by jsindos** [expo/expo#21708]
### Minimal reproducible example

https://github.com/jsindos/slow-video-picker

### Summary

I have a video on my iPhone which is 129.8 MB, as reported by the Photos app. However, when running the code below, I log `251654391` bytes (230 MB). Why is the size of the video bigger than what is reported by the Photos app?

```
const result = await ImagePicker.launchImageLibraryAsync({
  quality: 0.2,
  mediaTypes: ImagePicker.MediaTypeOptions.Videos
})

console.log(result.fileSize)
```

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 12.6.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
Watchman: 2023.02.27.00 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.10.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
IDEs:
Android Studio: 2021.2 AI-212.5712.43.2112.8815526
Xcode: 14.1/14B47b - /usr/bin/xcodebuild
npmPackages:
expo: ~48.0.6 => 48.0.6
react: 18.2.0 => 18.2.0
react-native: 0.71.3 => 0.71.3
npmGlobalPackages:
eas-cli: 3.3.2
expo-cli: 6.0.1
Expo Workflow: managed

**Comment by gabrieldonadel** [comment]
This is likely because the video has already been compressed. The quality parameter specifies the quality of compression, but if the selected image or video has been compressed before, the size of the output file may be bigger than the size of the original image.

You can find more information about this in our official documentation at https://docs.expo.dev/versions/latest/sdk/imagepicker/.
