### ISSUE TITLE
Unable to resolve "uuid/v5" from "../../node_modules/expo/build/environment/getInstallationIdAsync.js"

### ISSUE THREAD

**Issue by olalonde** [expo/expo#21769]
### Minimal reproducible example

Nah

### Summary

I'm getting this error on a new expo project in iOS:

```
iOS Bundling failed 553ms
Unable to resolve "uuid/v5" from "../../node_modules/expo/build/environment/getInstallationIdAsync.js"
```

I'm using npm workspaces, not sure if that's relevant. No problem on web and android.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /opt/homebrew/bin/zsh
    Binaries:
      Node: 19.6.0 - ~/Library/Caches/fnm_multishells/85281_1679282538153/bin/node
      npm: 9.4.0 - ~/Library/Caches/fnm_multishells/85281_1679282538153/bin/npm
    SDKs:
      Android SDK:
        API Levels: 21, 31, 32
        Build Tools: 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Google ARM64-V8a Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
        Android NDK: 21.4.7075529
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: /undefined - /usr/bin/xcodebuild
    Expo Workflow: managed
```

**Comment by olalonde** [comment]
Fixed with `npm install uuid@3.4.0` but still a bug.

**Comment by maticzav** [comment]
If it's helpful to anyone, I had the same issue and didn't pay enough attention to the version specification (i.e. the `3.4.0` part). I use `pnpm` and have a "monorepo" structure (i.e. it's a monorepo, but the Expo App part doesn't reference any other library except from TypeScript type checking). To get it working right, I added a `.npmrc` file with `node-linker=hoisted` configuration that "flattens" out the `node_modules` in the root (https://pnpm.io/npmrc#node-linker).

I had two projects and they seemed almost identical, but one was failing. It turns out that the failing one had a `uuid@9.0.0` dependency in the server subproject. I think what happened is that pnpm hoisted the `uuid` package that was listed as a dependency (`v9.0.0`) in the root and the `v3.4.0` inside the app directory. When metro tried to resolve the dependency, it bumped into the v9 one first and crashed.

To shed more light, I added the following two images that compare the folder structure of `v3.4.0` and `v.9.0.0`.

<img width="344" alt="CleanShot 2023-06-18 at 22 56 07@2x" src="https://github.com/expo/expo/assets/3924224/f60eb0e4-93dc-4585-9c3a-8400eee2d314">

<img width="332" alt="CleanShot 2023-06-18 at 22 55 32@2x" src="https://github.com/expo/expo/assets/3924224/1ebc9a12-2a74-48d7-99cf-8ef7ce369db4">

Since `uuid@3.4.0` is officially deprecated as you can see in the error message that PNPM shows during installation, I suppose it would make sense to sort this out. My suspicion is that the following file is the problem. 

https://github.com/expo/expo/blob/173c63ba926dea3e395cc75ce3fe41fd543c19c3/packages/expo/src/environment/getInstallationIdAsync.ts#L4

If there's any chance that this gets fixed, I'd be more than happy to contribute my time.

**Comment by BradyEdgar94** [comment]
Any updates, I am stuck on this at the moment.
