### ISSUE TITLE
[expo-image] Android cannot display animated AVIFs

### ISSUE THREAD

**Issue by RRaideRR** [expo/expo#21890]
### Minimal reproducible example

https://github.com/RRaideRR/expo-image-avif

### Summary

Displaying an animated AVIF works on iOS but not on Android.

Tested against expo-image 1.1.0 and 1.0.0.

iOS:

https://user-images.githubusercontent.com/3411292/228460109-6cb3c811-5139-4999-bd36-7b77522a6722.mov

Android:
<img width="319" alt="Bildschirmfoto 2023-03-29 um 09 34 01" src="https://user-images.githubusercontent.com/3411292/228459982-3d12ba20-49ab-4d98-8b00-3d35bbc17e00.png">

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.9 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.4 => 0.71.4 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

```

**Comment by VictorioMolina** [comment]
I think this is the only way to render a huge amount of "GIFs" without extreme compressions and crashes on Android. Any ideas if this will be supported soon on Android?

**Comment by RRaideRR** [comment]
Hi @VictorioMolina . The last time I had a look, expo-image used on Android Glide v4. [Glide does simply not support it yet.](https://bumptech.github.io/glide/int/avif.html)

My solution was to fallback to animated webp on Android. They are still significantly smaller than GIFs - for my use case it was a good compromise.

**Comment by lukmccall** [comment]
@RRaideRR, you're right. The Glide library we used under the hood doesn't support animated AVIF, and it doesn't look like they will add it soon.

**Comment by VictorioMolina** [comment]
@RRaideRR What was the average size of your GIFs?

In my use case, I have to work with JPEGs (no option due to incompatibilities with some AI APIs) and then generate a GIF.

Suppose JPEGs dimensions are 1080x1350.

The steps I am following are:

1. Compress the JPEGs with mozjpeg (default options, quality = 75), which is great, since my 2MB images are reduced to 100KB.
2. GIF generation with the compressed JPEGs
  2.1. I prepare the GIF frames with canvas, reducing their dimensions (without losing proportion) to a 450px
  2.2. For quality reasons, I am applying 'dithering patterns' when generating the GIFs.
3. Compress the generated GIF with imagemin, using the gifsicle plugin, which gives me a nice GIF of 400KB, but still too high.
4. The last step is the webp conversion. I have tried this but results are bigger (from 400-450KBKB to 600-700KB).
  4.1. Convert the compressed GIF to WebP with cwebp-bin (gif2webp -lossless -min_size)

Quite frustrating :c

**Comment by RRaideRR** [comment]
Hey mate,

I have not the knowledge to go very deep into detail, but what I'm doing is the following:
- I also grab six frames
- I'm doing the processing on my Django backend using pillow. Not sure what pillow internally uses 

Average sizes: GIF 250kb, AVIF 50kb, WEBP 70kb

However, my image sizes are rather small (276x206px)

I attached some samples. Hopefully it helps you a little bit 
[samples.zip](https://github.com/expo/expo/files/12816631/samples.zip)

**Comment by obayomi96** [comment]
Hi, I have the same issue as well which is now resolved.
I have an animated .png image that worked fine on IOS but remained static on Android, after seeing @RRaideRR comment here I tried converting the images to .webp and it works fine on both platforms (Simulator, Emulator, and actual devices).
This is of course testing using expo and not prod yet.
