### ISSUE TITLE
How can you implement Safari on the share function?

### ISSUE THREAD

**Issue by ru88s** [expo/expo#2237]
How can you implement Safari on the share function?
I want to display a Web page displayed in WebView in Safari.

**Packages:**
expo: 30.0.0
react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz

**Reproducible Demo**
Snack: https://snack.expo.io/@wataruyonamine/i-want-to-display-a-web-page-displayed-in-webview-in-safari

**Expected Behavior**
The Safari button appears in the Share function.
<img width="675" alt="window" src="https://user-images.githubusercontent.com/42270511/45865755-74254880-bdb9-11e8-90cc-e9c271043a28.png">

**Comment by esamelson** [comment]
Hi @ru88s - this is not natively supported on iOS (requires external libraries or custom code) and is not yet a supported feature of react native. I see you've also posted to our canny, which is where we track feature requests, so I'm going to go ahead and close this issue. (You could also try posting to the react-native repo, since this module is under their domain.)

**Comment by ru88s** [comment]
Hi @esamelson Oh, I understand. Thank You for your perfect explanation.
