### ISSUE TITLE
Expo blur borderRadius

### ISSUE THREAD

**Issue by itsezc** [expo/expo#22385]
### Minimal reproducible example

https://snack.expo.dev/51q-mxt9v

### Summary

Currently, its not possible to add a `borderRadius` to an Expo `blurView` like you can with `View`, there are alot of design use cases where this may be necessary.

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 19.8.1 - ~/.proto/bin/node
      npm: 9.5.1 - ~/.proto/bin/npm
    Expo Workflow: managed
```

**Comment by ouwargui** [comment]
@itsezc You can actually use `borderRadius` as long as you use `overflow: 'hidden'` as well, since all style props are passed to a normal `View` that wraps the `BlurView` component.

I'm sorry for the screenshot low quality.

![image](https://user-images.githubusercontent.com/44242141/236357349-fcec6224-49c5-435d-84b3-3e782b57fae2.png)

**Comment by itsezc** [comment]
This is a great workaround—thanks! But it'd be great if we didn't have to do this and/or if it's better documented.
