### ISSUE TITLE
create-expo-app@1.3.3 | mid/high vulnerabilities

### ISSUE THREAD

**Issue by kode-neko** [expo/expo#22404]
### Summary

Hi everyone!

I'm using `create-expo-app` to init my new React Native project. The problem is the bunch of package vulnerabilities. Although you use `npm aufit fix --force`, it doesn't work. 

I've watched the version list and the `@1.3.3` last one was released 10 days ago. Maybe the team is aware about this and is working on a new patch. I tried to install the `@1.3.2` version but it happens the same.

Below I show you the terminal output:
```
$ npx create-expo-app .
√ Downloaded and extracted project files.
> npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 1216 packages, and audited 1217 packages in 1m

61 packages are looking for funding
  run `npm fund` for details

14 vulnerabilities (9 moderate, 5 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.


✅ Your project is ready!

To run your project, run one of the following npm commands.

- npm run android
- npm run ios # you need to use macOS to build the iOS project - use the Expo app if you need to do iOS development without a Mac
- npm run web

```

I don't like to hurry, but it's difficult to justify a project with package vulnerabilities. Please, resolve this as soon as possible because expo and its tools are awesome for React Native.

Have a nice day!

### SDK Version

1.3.3

### Environment

``` 
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.4.1 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~48.0.15 => 48.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.71.7 => 0.71.7
    Expo Workflow: managed
```

### Minimal reproducible example

npx create-expo-app .

**Comment by brentvatne** [comment]
Nearly all non-trivial packages in the Node ecosystem will come with messages like this on install due to the unfortunate way that unactionable warnings are exposed to users. Some tools use `ncc` to vendor the dependencies, which essentially hides the warnings, but the underlying code is the same.

In all but the most rare of cases, these vulnerability warnings don’t actually apply to any of the usage in the context of Expo tools — they often relate to usage in the context of running a web server. If we become aware of a case that may impact Expo tools, we will update the dependency as soon as we are aware. In other cases, we update dependencies when it’s a good time to do so, taking into account factors such as the supported Node version.

Usually the warnings you see are from distant downstream dependencies, eg: `expo-*` depends on package `a` which depends on `x` which depends on `y` which depends on `z`. We have to wait for `a` to update their dependency on `x` which results in updating `y` and `z`. 

If you believe that any particular warning message points to a legitimate vulnerability that may be exploitable, please send an email to security@expo.dev with more information.
