### ISSUE TITLE
Get started tutorial missing images [docs] 

### ISSUE THREAD

**Issue by Ngoakor12** [expo/expo#22514]
### Summary

Hi I've been going through the tutorial [here](https://docs.expo.dev/tutorial/introduction/), so far so good.

I think it would be smoother to link the images used in these chapters:
- [build a screen](https://docs.expo.dev/tutorial/build-a-screen/#display-the-image) - placeholder image(although it's there, some directions to download or just a link to download would be an improvement in my opinion)
- [create a modal](https://docs.expo.dev/tutorial/create-a-modal/#display-a-list-of-emoji) - emoji list images

I'm still in the process of going over the tutorial so I might find more places that require assets or images to be linked

### Link to the related docs page

https://docs.expo.dev/tutorial/introduction/

**Comment by amandeepmittal** [comment]
We do provide all the assets in the first chapter's first step: https://docs.expo.dev/tutorial/create-your-first-app/#initialize-a-new-expo-app

<img width="819" alt="CleanShot 2023-05-17 at 14 51 14@2x" src="https://github.com/expo/expo/assets/10234615/a5249ca2-1620-40a4-8a05-19d8369b3728">

I think, since you mentioned, it might be skimmed. Will look into improving the step to highlight that link more.

**Comment by Ngoakor12** [comment]
Ah I see. thanks :smile:
