### ISSUE TITLE
"npx expo install" wrong reanimated version

### ISSUE THREAD

**Issue by maxibenner** [expo/expo#22573]
### Summary

installing react-native-reanimated with `npx expo install` installs version 2.14 when support for 2.3 was already introduced in expo 44 according to the changelog.

### What platform(s) does this occur on?

iOS

### SDK Version

48

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
    Expo Workflow: managed

### Minimal reproducible example

Installing react native reanimated in a new project.

**Comment by brentvatne** [comment]
2.14 > 2.3

(14 > 3)

**Comment by maxibenner** [comment]
Hey @brentvatne, not sure what you are trying to tell me. Can I specify v2.3 when installing? I always assumed that `expo install` would automatically choose the compatible version which made me hesitant to specify my own.

**Comment by brentvatne** [comment]
i'm saying that 2.14 is a more recent version than 2.3. this is confusing in terms how we typically treat decimals, because 2.14 < 2.3 when it comes to math. however, with versions, 2.14 refers to major version 2 minor version 14, and 2.3 refers to major version 2, minor version 4. so 2.14 is more recent than 2.3. ~2.14.4 is the expected version for sdk 48: https://github.com/expo/expo/blob/84ec26b15ea2f429ec88753c0fcadb5b2e1d7b61/packages/expo/bundledNativeModules.json#L92

**Comment by maxibenner** [comment]
Hey @brentvatne, thanks for the clarification! Odd mistake to make on my side considering that I version my apps in the same way 😅
