### ISSUE TITLE
`bar-code-scanner` crashes with `set display orientation failed`

### ISSUE THREAD

**Issue by szmarczak** [expo/expo#22836]
### Minimal reproducible example

https://gist.github.com/szmarczak/7ecf6a54ba98175d4452acc24a23cab8

### Summary

```
 ERROR  Cannot set prop 'type' on view 'class abi48_0_0.expo.modules.barcodescanner.BarCodeScannerView'
→ Caused by: java.lang.RuntimeException: set display orientation failed
```

Always happens after locking the screen, waiting a while and opening the app afterwards.

### Environment

```
> npx expo-env-info
Need to install the following packages:
  expo-env-info@1.0.5
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 20.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    npmPackages:
      expo: ~48.0.18 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed
```

Using Expo Go on Android.

**Comment by szmarczak** [comment]
This might have the same reason as #22837 but I'm not sure.

**Comment by douglasjunior** [comment]
We are seeing this crash in crashlytics logs, seems to be related to the camera being displayed and close quickly.

For example, when you navigate to a screen that uses the `<BarCodeScanner />` and then the screen is closed before the camera setup finishes. (I'm not sure because we can't reproduce the error locally)

![image](https://github.com/expo/expo/assets/1512341/466fb69e-fac7-4cb0-8519-0af991592039)
