### ISSUE TITLE
expo and jest commands don't do anything (Windows)

### ISSUE THREAD

**Issue by blakew** [expo/expo#2306]
Please see [expo-cli #48](https://github.com/expo/expo-cli/issues/48)

In short, `expo` and `jest` commands don't do anything on my system in v30. The simply run and exit. I have to use the following workarounds:

**expo** -> `expo-cli`

**jest** -> `node .\\node_modules\\jest\\bin\\jest.js`

I'm on Windows 10, latest node (8.12.0)

**Comment by esamelson** [comment]
Hi @blakew - please don't double post issues across repos, it just creates more confusion and work for us. Someone will help you out on the other issue.

**Comment by blakew** [comment]
@esamelson I was following the doc instructions to post jest issues on expo. I ran into the jest issue after posting the other issue. The other issue doesn't cover jest. Isn't that helpful information to report? I also linked to minimize confusion.

I'm posting this to let you know there's an issue with my setup. I posted the workaround as well.

**Comment by esamelson** [comment]
Hi @blakew - thanks for clarifying, and sorry I came across more brusque than I intended. It seems like the issue is with your node installation -- package names aren't being correctly recognized in the command line. Thanks for posting your workarounds.

`jest-expo` is actually just a set of presets that work with Expo apps, but since your issue is happening with `jest` itself, you may also find it fruitful to post on the actual jest repo here: https://github.com/facebook/jest

**Comment by blakew** [comment]
Thanks @esamelson appreciate your help. I closed the other ticket and will look into root cause with node more carefully.

**Comment by ahlechandre** [comment]
Same problem on Node v8.12.0
