### ISSUE TITLE
sdkVersion does not support assigning version to the same as package.json [docs] 

### ISSUE THREAD

**Issue by sean-fletching** [expo/expo#23092]
### Summary

The current expo package in my package.json is 48.0.18.

I recently upgraded, and I assigned that same version to the 'sdkVersion' property of 'app.json'.

Here's a synopsis of the misbehaviors that were caught:

1. After running `npx start expo`, an error is emitted in the console as follows: "Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project."
2. After running (above) and then connecting to the server via Expo Go,an error is emitted in the console as follows: "Warning: Unable to resolve manifest assets. Icons and fonts might not work. Version '48.0.18' does not exist.."
3.  After connecting to the server, Expo Go (android running on chromeos) displays an error as follows: "This project requires a newer version of Expo Go - please download the latest version from the Play Store."

After assigning 'sdkVersion' to '48.0.0' the app stack functions normally. 
Note: excluding the minor and major versions from the configuration property are not supported either. e.g. '48'

### Link to the related docs page

https://docs.expo.dev/versions/latest/config/app/#sdkversion

**Comment by vargaszabolcs** [comment]
I don't think you are supposed to set it to a specific version such as 48.0.19. If I set anything other than 48.0.0 I am also getting similar errors and then some more. But if I am wrong please someone correct me, because if I set it to 48.0.0 I am getting package version compatibility issues with expo/config-plugins from expo-doctor, saying some packages are referencing a newer version then the one supported by expo, but if I set it to 48.0.19 these errors go away.
