### ISSUE TITLE
Bare workflow android app with product flavors with different application id/package names fails to initialize activity

### ISSUE THREAD

**Issue by rafael-fecha** [expo/expo#23266]
### Summary

I encountered an issue while working with Expo on Android, specifically when utilizing product flavors and changing the application ID. After modifying the application ID, the main activity of the app cannot be found, resulting in an error.

Expected Behavior:
The app should launch successfully with the modified application ID, and the main activity should be found and displayed.

Actual Behavior:
When attempting to launch the app with the modified application ID, the following error is encountered:
```
CommandError: No development build (com.bareflowproject) for this project is installed. Please make and install a development build on the device first.
```
If i go to the emulator i see the app there and i click in the app icon and it will be launched. 

### What platform(s) does this occur on?

Android

### SDK Version

48.0.15

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/rafaelfecha/.rvm/gems/ruby-2.7.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild

### Minimal reproducible example
Github Repo: https://github.com/rafael-fecha/expo-bareflow-flavors-error

1. Install sample repo: npx react-native@latest init BareflowProject
2. Followed this guide to install expo and adapt the files: https://docs.expo.dev/bare/installing-expo-modules/#manual-installation
3. Add flavors in build gradle
```
flavorDimensions "env"
    productFlavors {
       production {
            dimension "env"
            applicationId = "com.bareflowproject"
        }
        dev {
            dimension "env"
            applicationId = "com.bareflowproject.dev"
        }
        staging {
            dimension "env"
            applicationId = "com.bareflowproject.staging"
        }
    }
```

**Comment by erdenezul** [comment]
+1

**Comment by WHKL-9** [comment]
+1

**Comment by rafael-fecha** [comment]
@brentvatne what do you expect here to define the provided code snippet as invalid minimal reproducible example ? it is just a standard expo project with the following flavors definition in the build.gradle and that AndroidManifest.xml - which I provided. I think I also followed the `Please do not provide your entire project, or a project with more code than is necessary to reproduce the issue.`

**Comment by brentvatne** [comment]
what is expected is a runnable project that has no code or dependencies beyond what is absolutely required to reproduce the issue. so, if you create a new project and make a minimal set of changes to it to reproduce this, then share that project, it would be helpful! also, if you can let me know how i can update this message to be more clear it'd be helpful too

**Comment by rafael-fecha** [comment]
@brentvatne here it is a public sample github repo: https://github.com/rafael-fecha/expo-bareflow-flavors-error. I've updated the description. Please some support here :)

**Comment by s-chand** [comment]
Any updates on this? Still experiencing this

**Comment by walidmaouche** [comment]
i have the same problem

**Comment by deepak-dpt** [comment]
Facing the same issue

**Comment by mlecoq** [comment]
> I have a similar issue with react native 0.73 / expo 50 canary
> 
> When I launch my app I have
> 
> ```
>      defaultConfig {
>         applicationId "com.my_app"
>         minSdkVersion rootProject.ext.minSdkVersion
>         targetSdkVersion rootProject.ext.targetSdkVersion
>         versionCode 5002
>         versionName "0.5.2-canary.34"
>     }
> 
> 
>       production {
>             dimension "env"
>             applicationId 'com.my_app.my_app'
>         }
>         staging {
>             dimension "env"
>             applicationId 'com.my_app.my_app_staging'
>         }
>         development {
>             dimension "env"
>             applicationId 'com.my_app.my_app_dev'
>         }
>     }
> ```
> 
> and then running `run-android` I have the following issue :
> 
> `Error: Activity class {com.my_app.my_app_dev/com.my_app.my_app_dev.MainActivity} does not exist.`
> 
> It worked fine with rn 0.72 / expo 49

I think that's related to a react-native cli issue on rn 0.73

**Comment by geydson** [comment]
Did you manage to solve it?
I don't know if it would be the same thing, I'm having a problem running it in the simulator, in SDK 50.

I have an application that was on SDK-44, I am upgrading to SDK-50(50.0.11), and I used Install app variants on the same device, I followed the documentation correctly but when trying to run the command to execute in the simulator using a variant in the development case, I receive the error below, it is an error that I do not receive running on the old version.

BUILD SUCCESSFUL in 20s
586 actionable tasks: 26 executed, 560 up-to-date
› Opening br.com.integralservices.development.mob/.MainActivity on Pixel_4_API_34
CommandError: Couldn't open Android app with activity "br.com.integralservices.development.mob/.MainActivity" on device "Pixel_4_API_34".
The app might not be installed, try installing it with: npx expo run:android -d Pixel_4_API_34
Activity class {br.com.integralservices.development.mob/br.com.integralservices.development.mob.MainActivity} does not exist.

![Captura de Tela 2024-03-13 às 20 11 05](https://github.com/expo/expo/assets/33293615/8e93d691-8ace-4c99-a176-55ff947ce5e4)
![Captura de Tela 2024-03-13 às 20 12 10](https://github.com/expo/expo/assets/33293615/d817d0a0-75a2-46fb-bb03-c85d9814ff39)

![Captura de Tela 2024-03-13 às 20 12 41](https://github.com/expo/expo/assets/33293615/5e86f3d5-7460-4b03-8b73-e86a3da9d518)


I believe it is caused by the "namespace" parameter in build.gradle, I can only run it in the simulator if I keep the applicationId the same, as in the example below:

    namespace "com.integralservices"
    defaultConfig {
        applicationId "com.integralservices"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        buildConfigField("boolean", "REACT_NATIVE_UNSTABLE_USE_RUNTIME_SCHEDULER_ALWAYS", (findProperty("reactNative.unstable_useRuntimeSchedulerAlways") ?: true).toString())
    }
    flavorDimensions "env"
    productFlavors {
        production {
            dimension "env"
            applicationId 'br.com.integralservices.production.mob'
        }
        development {
            dimension "env"
            applicationId 'com.integralservices'
        }
        staging {
            dimension "env"
            applicationId 'br.com.integralservices.staging.mob'
        }
    }
In the project in the SDK 44 version, it is like this below and works correctly, however in this version of react-native it still did not have this "namespace" parameter:

  defaultConfig {
        applicationId "br.com.integralservices.development.mob"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }

    flavorDimensions "env"
    productFlavors {
        production {
            dimension "env"
            applicationId 'br.com.integralservices.production.mob'
        }
        development {
            dimension "env"
            applicationId 'br.com.integralservices.development.mob'
        }
        staging {
            dimension "env"
            applicationId 'br.com.integralservices.staging.mob'
        }
    }

can anybody help me?

**Comment by prathameshmm02** [comment]
expo-cli probably doesn't have access to the modified the applicationId for the different flavors, only gradle knows about the correct applicationId.

So, the potential solution could be to add two new command line arguments, `--appId` & `--applicationIdSuffix` similar to what react-native currently provides, so the correct applicationId can be set.

PS: I would love to work on this, if required.

**Comment by chakravarthi-bb** [comment]
Any update on this??

**Comment by fedeel** [comment]
I'm currently facing the same issue. I created a simple expo project, using expo's SDK 51 to reproduce it.
[Reproducible example](https://github.com/fedeel/expo-playground-app)

I created 2 simple flavors, like so:

`    flavorDimensions "default"
    productFlavors {
        production {
            dimension "default"
            applicationId "com.fedeel.expoplaygroundapp"
            resValue "string", "app_name", "prod playground"
        }
        development {
            dimension "default"
            applicationId "com.fedeel.expoplaygroundapp.dev"
            resValue "string", "app_name", "dev playground"
        }
    }`

And i'm running it using:

`NODE_ENV=development npx expo run:android --variant=developmentDebug`

or

`NODE_ENV=production npx expo run:android --variant=productionDebug`

I'm getting this error in both cases:

`CommandError: No development build (com.fedeel.expoplaygroundapp) for this project is installed. Please make and install a development build on the device first.`

It's curious, because the builds end up installed in the android simulator I'm running, and i can't start metro separately with `npx expo start`, open the apps in the simulator and get them hooked up to metro and expo. But there seems to be an issue when android's MainActivity kicks in.

Also, this minimal example works just fine on iOS (although I didn't add that config to the repo to keep it simple and minimal). 
Any ideas/clues on what the issue may be?. I have no issue running these flavors on a bare react-native app without expo.

**Comment by ph8nt0m** [comment]
Maybe delete applicationId in defaultConfig may help.

**Comment by fedeel** [comment]
Small bump here, issue's still going on!

**Comment by garawalid** [comment]
I'm facing this issue as well. I went through the code and I found that expo-cli resolve the applicationId with a regex [getApplicationIdAsync](https://github.com/expo/expo/blob/main/packages/%40expo/config-plugins/src/android/Package.ts#L245)  
```javascript
export async function getApplicationIdAsync(projectRoot: string): Promise<string | null> {
  const buildGradlePath = getAppBuildGradleFilePath(projectRoot);
  if (!fs.existsSync(buildGradlePath)) {
    return null;
  }
  const buildGradle = await fs.promises.readFile(buildGradlePath, 'utf8');
  const matchResult = buildGradle.match(/applicationId ['"](.*)['"]/);
  // TODO add fallback for legacy cases to read from AndroidManifest.xml
  return matchResult?.[1] ?? null;
}
```

**Comment by markwitt1** [comment]
Am I right with the assumption that "expo prebuild (--clean)" does not work if we configured multiple flavors / app variants? Because we need to write native config for the schemes / flavors that doesn't have a suited expo plugin?

**Comment by byCedric** [comment]
#31756 will be available starting from SDK 52 and [the documentation](https://github.com/expo/expo/pull/31785/files) is also ready to be merged.

---

@markwitt1 Yes, that's correct. If you want to use `expo prebuild`, you'd have to create a config plugin that adds the product flavors to your **android/app/build.gradle**. Expo likely won't be providing a config plugin to do this, as we can't really recommend using different product flavors instead of using a dynamic App manifest `app.config.js`.

But, when creating the `--app-id` feature for SDK 52 in #31756, I've used this config plugin to quickly test the app.

<details><summary>./withAndroidProductFlavors.js</summary>

```js
const { withAppBuildGradle, createRunOncePlugin, WarningAggregator } = require('expo/config-plugins');

const setAndroidProductFlavors = (buildGradle) => {
  // Hook into `buildTypes {` and prepend the product flavor configuration
  return buildGradle.replace(
    /buildTypes\s?{/,
    `flavorDimensions "version"
    productFlavors {
        production {
            dimension "version"
            resValue "string", "app_name", "myapp"
        }
        development {
            dimension "version"
            applicationIdSuffix ".dev"
            resValue "string", "app_name", "myapp (dev)"
        }
        staging {
            dimension "version"
            applicationIdSuffix ".stage"
            resValue "string", "app_name", "myapp (stage)"
        }
    }
    buildTypes {`
  );
};

const withAndroidProductFlavors = (config) => {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language === 'groovy') {
      config.modResults.contents = setAndroidProductFlavors(config.modResults.contents);
    } else {
      WarningAggregator.addWarningAndroid(
        'android.productFlavors',
        `Cannot automatically configure app build.gradle if it's not groovy`
      );
    }
    return config;
  });
};

// This plugin should only run once, running multiple times will add multiple product flavors in your android/app/build.gradle
module.exports = createRunOncePlugin(withAndroidProductFlavors, 'withAndroidProductFlavors', '1.0.0');
```

</details>
