### ISSUE TITLE
[iOS] SQLite not opening database successfully

### ISSUE THREAD

**Issue by gtfargo** [expo/expo#234]
Hey all!  Just wanted to say I'm having an awesome time messin around with Expo - kudos.  

I've been working through a couple edge cases with @nikki93 on my current project.  Finally hit one that needs to be logged.

The API for SQLite provided in the current documentation does not successfully open a downloaded database on iOS.   I've put together a sample project that I've confirmed works on a real Android device, but not a real iOS device.   Neither simulator works.

https://expo.io/@gtfargo/sqlite-pooped-its-pants 💩 

Willing to help work through this however I can, thanks!

**Comment by nikki93** [comment]
This would be more useful with the source code of the project in question. Also the intended use of the `SQLite` API as it stands does not involve opening downloaded databases at the moment. See https://github.com/expo/expo-docs/issues/63 for more information. Closing this because it's not actually a bug because the behavior described is not advertised by the API.
