### ISSUE TITLE
[expo-image] Expo Image does not work with Reanimated 3's shared element transition feature.

### ISSUE THREAD

**Issue by gorbypark** [expo/expo#23407]
### Minimal reproducible example

https://github.com/gorbypark/sdk49

### Summary

It appears that Expo Image does not work (well, not smoothly) with Reanimated 3s new shared transition feature, at least when being used as a child of an `Animated.View` component.  I am not sure if Expo Image would explicitly need to support Animations or not.

Here's an example video:
https://github.com/expo/expo/assets/19569469/903ce4c6-bae4-482d-a3f2-de76522971c9

And here's the repo for the above video (see `app/tabs/(home)/index.tsx` and `app/tabs/(home)/image.tsx`)
https://github.com/gorbypark/sdk49

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.1 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.4 - /opt/homebrew/opt/node@16/bin/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/mhamilton/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.0-beta.0 => 49.0.0-beta.0 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.1 => 0.72.1 
      react-native-web: ~0.19.6 => 0.19.6 
    Expo Workflow: managed

**Comment by andresribeiro** [comment]
i can confirm that's working fine on android, but not on ios

**Comment by etkramer** [comment]
Can confirm - it looks as though images don't appear immediately after mounting, and by the second frame (when they do appear) reanimated has already taken its snapshot.

**Comment by andresribeiro** [comment]
Still not working with `expo-image 1.12.15` on old architecture (iOS), works fine on Android. not sure when new architecture is enabled

**Comment by brentvatne** [comment]
@chrfalch - this is a good one to dig into when you want a break from background tasks!

**Comment by chrfalch** [comment]
Hi @gorbypark! Thanks for submitting the issue. Remember that Reanimated's shared transition support is still marked as experimental - and it does not work in the new architecture yet.

I've tested the case you provided on both Expo SDK-51 and SDK-52-beta and it seems to be working correctly with a small fix - you need to create an animated version of the ExpoImage component and use it instead of the ExpoImage directly. You also need to add the `sharedTransitionTag` to the image itself.

The reason for this is described in the [Reanimated documentation](https://docs.swmansion.com/react-native-reanimated/docs/shared-element-transitions/overview/):

> The layout for shared view children is not computed during the transition.

If you omit this you'll get the behavior you describe in this issue - this is also reproducible using the regular React Native Image component - see this video where I'm using RN Image instead of Expo Image:

```tsx
import { Image as RNImage } from "react-native";

export const ExampleImage: React.FC = () => {
  return (
    <RNImage
      style={{ flex: 1 }}
      source={{ uri: "https://picsum.photos/seed/696/3000/2000" }}
    />
  );
};
``` 

https://github.com/user-attachments/assets/17d1c34e-9413-4617-b888-4eb643a0d075

When wrapping the image component into an animated component it works correctly - this example is using the `ExpoImage` component:

```tsx
import { Image as ExpoImage } from "expo-image";
import Animated from "react-native-reanimated";

const AnimatedExpoImage = Animated.createAnimatedComponent(ExpoImage);

export const ExampleImage: React.FC = () => {
  return (
    <AnimatedExpoImage
      sharedTransitionTag="image2"
      style={{ flex: 1 }}
      source={{ uri: "https://picsum.photos/seed/696/3000/2000" }}
    />
  );
};
```

https://github.com/user-attachments/assets/56eb966f-8706-4a22-8cfc-81f11137b737

**Comment by chrfalch** [comment]
Let's close this issue @gorbypark if you agree with my explanation above :)

**Comment by gorbypark** [comment]
> Let's close this issue @gorbypark if you agree with my explanation above :)

Yup, sounds good.  Thanks for clearing that up!

**Comment by chrfalch** [comment]
My pleasure :)

**Comment by chrfalch** [comment]
> @chrfalch could this be related? #31803

Don't think so - it looks like something else is going on there.

**Comment by buildnewapp** [comment]
I've tested the case you provided on both Expo SDK-51 and SDK-52-beta and it seems to be working correctly with a small fix -

@chrfalch May I ask if you are using the new architecture in SDK version expo 51? Is it effective?
