### ISSUE TITLE
Clarification on Expo packages' support of New Architecture [docs] 

### ISSUE THREAD

**Issue by irisjae** [expo/expo#23410]
### Summary

According to the Expo 48 release, https://blog.expo.dev/expo-sdk-48-ccb8302e231
`Support for the New Architecture/Fabric in all Expo packages except expo-dev-client`

According to the Expo 49 release, https://blog.expo.dev/expo-sdk-49-c6d398cdf740
`The only module that does not yet support the New Architecture is expo-updates`

Taking these statements at face value, it seems to indicate that between Expo 48-49, support for the New Architecture was added to expo-dev-client, and removed from expo-updates. A more sensible picture would probably be that support for the New Architecture was never implemented for expo-updates. Perhaps these could be corrected?

It would be great if we could also be informed regarding the nature of the missing support.

### Link to the related docs page

https://blog.expo.dev/expo-sdk-48-ccb8302e231, https://blog.expo.dev/expo-sdk-49-c6d398cdf740

**Comment by brentvatne** [comment]
hi @irisjae! that was my fault for not realizing that expo-updates did not yet support the new architecture in the sdk 48 notes. the notes from sdk 49 are correct.

as it stands, any support for the new architecture in any library in the react-native ecosystem is experimental, because the new architecture is still in an experimental state itself in react-native open source. we'll add documentation around this when it stabilizes more and we want to begin to encourage developers to adopt it.
