### ISSUE TITLE
Deploying to App Stores should explain Android permissions customization

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2395]
https://docs.expo.io/versions/v34.0.0/distribution/app-stores/

In order to address this common question: https://twitter.com/benawad97/status/1050070616559296515

**Comment by Maxwell2022** [comment]
> To use ALL permissions supported by Expo, do not specify the "permissions" key.

I believe this should not be the default behaviour. If the `permissions` is not set, it should default to no permissions. If expo wants to default the configuration supporting all the permissions, then it should generate the permissions key with all the supported permissions.

**Comment by brentvatne** [comment]
@Maxwell2022 - I disagree. We add them all by default because this is how it works in the client, and the default behavior should be as close to the client as possible.

**Comment by brentvatne** [comment]
@cruzach - :)

**Comment by Maxwell2022** [comment]
> @Maxwell2022 - I disagree. We add them all by default because this is how it works in the client, and the default behavior should be as close to the client as possible.

What do you mean this is how it works in the client? When you build a native app, the app is not requesting every single permission by default

**Comment by brentvatne** [comment]
@Maxwell2022 - in the expo client all of the permissions that you may possibly request with `Permissions.askAsync` are added to `AndroidManifest.xml` because that's the only way that it will work in the client. if we change the behavior so that in a standalone app none of the permissions are enabled by default, then if you do nothing and assume that `expo build:android` will produce an app that works the same as it did in the client, you will be surprised when the app you build will crash immediately. it's better for it to just work and then have people opt out of what they don't use.

**Comment by Maxwell2022** [comment]
@brentvatne - If the app crash immediately I know there is something wrong with the permissions and so I can just add the one I need for the app, I'm in control. 

If you add all permissions (to my experience) to solve this, you publish the app without noticing it and then you have all these happy customers that 1 star rate your app because they say that it's trying to do to something fishy requesting access to things that the app has no needs to. By the time you fix it, it's too late.

It reminds me of another really bad experience we had with Expo, having the auto-update enabled by default in the config between 2 versions of Expo. Publishing our new feature for testing in Expo and having our client calling us to let us know that it's live in the production app.

I really don't like this automatic behavior that makes it really useful for some devs, but on the other side, it messes up big time. Anyway, that was just my experience with Expo and it's just my point of view.

**Comment by brentvatne** [comment]
thanks for the feedback. we should do more to educate people on the defaults!
