### ISSUE TITLE
Confusing pop-up permission when using AuthSession in standalone apps.

### ISSUE THREAD

**Issue by adonandal** [expo/expo#2396]
Hi,

I am using expo AuthSession for social authentication with other providers. Google for example.

on IOS, when I try to sign in, the app asks first for permission with a pop-up. the pop-up message says the following:

**_"App" Wants to Use "expo.io" to Sign in. This allows the app and website to share information about you._**

This is happening on standalone apps on ios, but not on android. 

I find this message confusing for the end-user as they expect to login with google and not with expo.io. Is it possible to avoid the pop-up or customize it. Why is this only happening on ios?

Thanks!

### Environment

Environment:
  OS: macOS 10.14
  Node: 8.11.2
  Yarn: 1.10.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

**Comment by sjchmiela** [comment]
Hi, @adonandal!

Reading through the `AuthSession` documentation one can find a section explaining why this API is different than any normal social authentication API. What's special is that it leverages `auth.expo.io` service to provide you painless development experience. Read more about it [here](https://docs.expo.io/versions/v30.0.0/sdk/auth-session#what-authsession-does-for-you).

Why does the iOS modal say what it does?

`AuthSession`'s feature is that it instructs authentication provider that once the authentication process completes, it should redirect user to `auth.expo.io`, which in turn will immediately redirect the user back to your application, no matter if it is being developed with `localhost:19000` URL or whether it's already published `exp://exp.host/@username/experienceName` app.

Both redirections: to auth.expo.io and to your application may (will, if the authentication succeeded) contain tokens issued by the provider that any receiver could use to advertise himself as the user. That's why iOS informs the user so explicitly that it will let `[auth.]expo.io` see those tokens. It's two features (AuthSession and iOS) working together!

Fortunately (as always with Expo 😎) there is a way to opt out of this behavior. `AuthSession` is [just a convenient wrapper](https://github.com/expo/expo/blob/master/packages/expo/src/AuthSession.ts) around [`WebBrowser.openAuthSessionAsync`](https://docs.expo.io/versions/v30.0.0/sdk/webbrowser#expowebbrowseropenauthsessionasyncurl-redirecturl) API, so you could use it instead to redirect to your own URL (auth.expo.io-like service or `yourscheme://someUrl` in standalone apps) which would open your application with tokens from the provider. 🙂

**Comment by adonandal** [comment]
Hi, @sjchmiela !

Thank you for your detailed answer!

I actually started first with WebBrowser following this example https://github.com/expo/examples/blob/master/with-webbrowser-redirect/app/App.js
before I tried AuthSession.

With WebBrowser I couldn't get Linking.addEventListener to trigger when I redirect. 
It looks like there are others having the same issue: https://forums.expo.io/t/linking-addeventlistener-url-working-on-ios-but-not-on-android-in-production/14627

Let me know if you have a working example of WebBrowser with linking to get the queyParams on android! I'd be more than happy to give it a try 🙂

**Comment by sjchmiela** [comment]
Hey, I just tried the `with-webbrowser-redirect` example building it with `expo build:android` and it turned out <kbd>Tap here to try it out</kbd> button was doing nothing, because `Linking.makeUrl` was throwing an error:

> Cannot make a deep link into a standalone app with no custom scheme defined

https://github.com/expo/expo/blob/26c473d87f765eed8cca5fa71501ca7a468fa95b/packages/expo/src/Linking.ts#L45-L52

and apps built with `expo build:android` are obviously standalone. After adding a custom scheme to `app.json`, rebuilding and reinstalling the application on the device the app started to behave properly.

A fixing PR can be found [here](https://github.com/expo/examples/pull/9).

**Comment by adonandal** [comment]
Hi again @sjchmiela !

Thanks for the update! I have now tried your fix but somehow the redirect stops without passing dow the redirect data. I get the follow error-message displayed on the page : 

> "Something went wrong trying to finish signing in. Please close this screen to go back to the app."

However, when I open the same screen in chrome I could see that I got my data (queryParams) after the redirect uri. But it's not passed down. The whole application stops with the message above. I will try some more.

**Comment by sjchmiela** [comment]
Huh… 🤔 What service do you use as the authentication provider?

**Comment by adonandal** [comment]
Facebook through https://auth0.com/

I can see the code returned from the provider after the ? in the redirect uri, but somehow it doest get passed down. everything stops with the error-message I referred to earlier.

**Comment by colinrlly** [comment]
Is there a definitive fix to this issue? I am attempting to log into Google using the Expo.AuthSession.startAsync method explained in the docs here: https://docs.expo.io/versions/latest/sdk/google#server-side-apis. But I am getting the "Something went wrong trying to finish signing in. Please close this screen to go back to the app." error.

**Comment by sjchmiela** [comment]
Could you please submit a new issue? Thanks!
