### ISSUE TITLE
Map not showing on standalone APK

### ISSUE THREAD

**Issue by helloeyesimple** [expo/expo#240]
Hi,

As title suggested, Google map on Android (or in this case Airbnb maps) not showing on standalone APK.
It is showing when using Expo XDE, but not showing on generated standalone APK.

I have put all required information on app.json as stated on https://docs.expo.io/versions/v17.0.0/sdk/map-view.html - deploying APK section.

Here's the screenshot:
![image](https://user-images.githubusercontent.com/24649774/26941861-397e4bcc-4caa-11e7-8472-c722d330ba95.png)

Please help me.

**Comment by sonaye** [comment]
What API key are you using?

**Comment by sonaye** [comment]
https://developers.google.com/maps/documentation/ios-sdk/start#step_4_get_an_api_key
https://developers.google.com/maps/documentation/android-api/signup#key

**Comment by jesseruder** [comment]
@helloeyesimple that key doesn't look like a Google Maps API key. None of ours have underscores. Are you sure you followed all the directions including https://docs.expo.io/versions/v17.0.0/sdk/map-view.html#press-save-and-then-rebuild-the-app-like-in-step-1? You can look up your existing keys here: https://console.developers.google.com/project/_/apiui/credential

**Comment by terribleben** [comment]
Closing this because things seem to have dropped off here - let me know if it needs to be reopened.

**Comment by iamrommel** [comment]
I have the same issue. I was not able to view the map. I have read the documentation and even change the API key several times. I dis-agree with @jesseruder, some keys that i previously generated has underscore,

**Comment by Irosshipaz** [comment]
Reopen this. I'm facing same problem and my key do have underscores

**Comment by Irosshipaz** [comment]
Reopen this. I'm facing same problem and my key do have underscores

**Comment by iamrommel** [comment]
My issue was i have google maps api still disable..i went to google setting and enable the google maps api and it turns ok

**Comment by Irosshipaz** [comment]
What's exactly the name of the library I need to enable? Could you please copy paste it?

**Comment by haakandev** [comment]
In Google Play Console, do you have Google Play App Signing enabled?
If yes, the SH1 fingerprint you need to enter for the credentials for Google Maps API is different than the one generated as per the MapView page's instructions.
To get the correct SHA-1, go to the Google Play Console, go to Release Management, and then App Signing. Here, copy the SHA-1 under 'App Signing Certificate'. Enter this under the API credentials in the Google Maps API (as per [MapView instructions](https://docs.expo.io/versions/v17.0.0/sdk/map-view.html#if-you-already-have-not-configured-google-sign-in)).

This did it for me. My APK worked fine if I installed from my machine to my phone, but it didn't load the map when I had the build from Google Play. After doing this, it worked fine from Google Play as well!

**Comment by markbiek** [comment]
Thanks to @iamrommel. I _thought_ I had enabled the Google Maps Android API (https://console.developers.google.com/apis/library/maps-android-backend.googleapis.com/?id=01d8f5af-dc9a-4b12-af6f-37029d8e3e71&project=earthquake-map-191014&organizationId=384916252399) but I hadn't actually.

As soon as I turned that on, my standalone app started working.

**Comment by gogogous88** [comment]
guys, I solved the problem with following steps

Describe what was my problem:

expo client in Genymotion - Google Map working!
expo build:android - manually download(not from play store) and install in any android device - working!

HOWEVER, app download from playstore - google map - blank screen.......(not working)

Here is how I solved my problem:

there is a mistake of expo fetch:android:hashes, it give me a WRONG SHA-1 Fingerprint....

Do use adb logcat(https://developer.android.com/studio/command-line/logcat)

open the playstore downloaded app and go into the map -

it will show you the correct SHA-1 Fingerprint.... as following:

`2019-05-27 12:33:18.736 30552-30801/? E/Google Maps Android API: Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
2019-05-27 12:33:18.737 30552-30801/? E/Google Maps Android API: In the Google Developer Console (https://console.developers.google.com)
    Ensure that the "Google Maps Android API v2" is enabled.
    Ensure that the following Android Key exists:
     API Key: AIzaSyA4FDPR8y6yAPhF30kyff_B3VK0mxxxeeSU
     Android Application (<cert_fingerprint>;<package_name>): 13:2B:AA:09:E1:xx:xx:41:B8:59:C3:A4:xx:xx:23:63:C0:B9:D7;com.<yourbundle>.<name>`

******* 13:2B:AA:09:E1:xx:xx:41:B8:59:C3:A4:xx:xx:23:63:C0:B9:D7 **** instead of the fetch:android:hashes give me is the right Sha1 Fingerprint....

Please do log the reason why it not work~

**Comment by rjsajnani** [comment]
Thanks for pointing out this 
Sha1 was different, once i added the correct one, my maps load properly.

**Comment by ThiagoLovatine** [comment]
@haakandev Thanks! That's exactly what was wrong for me!
