### ISSUE TITLE
[docs] No documentation about the time of caching in expo-image

### ISSUE THREAD

**Issue by xerdnew** [expo/expo#24108]
### Summary

I cant find any documentation about the time of caching for expo-image. Is it mutable like in the native Image component or is it immutable?

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/image/

**Comment by xerdnew** [comment]
Any update on this? :)

**Comment by amandeepmittal** [comment]
Hi @xerdnew, I've asked this internally and will provide updates soon.

**Comment by amandeepmittal** [comment]
Hey @xerdnew, so I talked with our team and here are some updates.
- Caching time is controlled by underlying libraries: Glide and SDWebImage for native platforms. It differs for each platform. We have a plan to work on this but it is not our priority right now.
- Once we have more information we'll update the docs on this accordingly. I've created a task to follow this up internally.

Thank you for being patient with us, in advance :)

**Comment by xerdnew** [comment]
Thank you for your answer @amandeepmittal 

The thing is i am really trying to find a replacement for [react-native-fast-image](https://github.com/DylanVann/react-native-fast-image) as it is no longer maintained. 

react-native-fast-image also use Glide and SDWebimage so i dont know if the caching will behave the same in expo-image or is it caching like the default Image component in react-native which is more "browser like" ?

Best regards

**Comment by amandeepmittal** [comment]
> react-native-fast-image also use Glide and SDWebimage so i dont know if the caching will behave the same in expo-image or is it caching like the default Image component in react-native which is more "browser like" ?

It should be similar to that as you mentioned react-native-fast-image also uses the same native libraries.

I'll close this issue for now but will let you know once we update our docs.

**Comment by svrakicfaris** [comment]
Any update on this?

**Comment by rgomezp** [comment]
I am also interested in having control over this

**Comment by Vimiso** [comment]
Yeah what's going on here? Does the current implementation continue caching images indefinitely until the users' device is nice and full?! Sporadically having to clear the cache (just to ease the pain) seems sketchy without any documented specifications as to what's actually happening under the hood.

**Comment by seungholee-dev** [comment]
I can't believe expo doesn't support  TTL for caches...

**Comment by 0xFA11** [comment]
I'm curious if there's any ideas or plans to support specifying or controlling lifetime of disk cached images because it'd be really useful to purge cached images over time either by respecting HTTP response headers or potentially more simply by adding it as a cache option/prop. Nevertheless, even a simple "clean disk cache async" function with some useful built-in default criteria would be super helpful.

How can I start a conversation around this? @brentvatne (cc @tsapeta @lukmccall)

**Comment by lukmccall** [comment]
Hi @0xFA11. We're planning to add more advanced cache control in the future. It's not a straightforward task due to Glide, the library we're using to load images on Android. To change the default behavior, you need to override a significant portion of the library. Currently, you can clear the [disk](https://docs.expo.dev/versions/latest/sdk/image/#cleardiskcache) and [memory](https://docs.expo.dev/versions/latest/sdk/image/#cleardiskcache) caches.

**Comment by 0xFA11** [comment]
> Currently, you can clear the [disk](https://docs.expo.dev/versions/latest/sdk/image/#cleardiskcache) and [memory](https://docs.expo.dev/versions/latest/sdk/image/#cleardiskcache) caches.

One problem with this approach is that the entire cache would be wiped. It might not be desirable because we might want to keep last X images hence why I mentioned "with some useful built-in default criteria" (perhaps built-in LRU/LFU etc.).

Hypothetically speaking, if we get files in the cache directory with `getCachePathAsync()` and manually do bookkeeping and delete files from the cache/disk, would that be a simpler approach that wouldn't require more in-depth Glide behavior override? @lukmccall

**Comment by akshaykale17** [comment]
Hey any plans to add a maybe `ExpiresIn` or something field for this? Also has any faced issue where the image quality just keeps on degrading if the cache is not set to none ?

**Comment by brentvatne** [comment]
hey folks, we're open to ideas for how to add more control to caching in expo-image! if you'd like to post your ideas to https://github.com/expo/expo/discussions/categories/proposals-and-ideas and mention me on it, we can discuss there! or reach out to me on the expo discord (where i am also brentvatne)
