### ISSUE TITLE
Successful notification not returning receipt id

### ISSUE THREAD

**Issue by jonsgreen** [expo/expo#2414]
I apologize if this is not an appropriate place to ask this question.

We are sending notifications using the ruby exponent sdk. We are finding that about 10% of notifications have a successful response but do not include a receipt id so we cannot then verify if they actually were delivered. About 5% of successful initial responses do not actually get sent when we check back with a call to “https://exp.host/--/api/v2/push/getReceipts” so if we don’t have ids we could be losing track of those messages.

Is this a known issue? Why would a successful send not include a receipt id?

**Comment by ide** [comment]
What platform are these for? And to clarify -- these are push responses that include "status": "ok" in them?

**Comment by jonsgreen** [comment]
Not sure what you mean by Platform? We are using [this gem](https://github.com/expo/expo-server-sdk-ruby) for sending the messages but basically it making requests to your "https://exp.host/--/api/v2/push/send" endpoint. Most requests come back with a response like:
```
{"status"=>"ok", "id"=>"4e0d4fb2-f545-45fd-a083-9416044188aa"}
```
but about 10% come back with just: 
```
{"status"=>"ok"}
```
Let me know if there is more information I can provide you with. Thanks!

**Comment by ide** [comment]
By platform I mean iOS or Android. Also for Android, it's helpful to know whether you've set up FCM or are using the deprecated default system.

**Comment by jonsgreen** [comment]
We have devices that are both iOS and Android though mostly iOS. I am not sure whether we are using FCM but I bet we have not done that. Do you suggest that we do that? We are on expo 28.0.0 if that is helpful? 

Maybe the Android messages don't return receipt ids? Is there a way to see what type of device an expo token maps to?

**Comment by ide** [comment]
It's likely those are legacy Android notifications, for which we don't return receipt IDs.

**Comment by jonsgreen** [comment]
Thank you for the help; we will look into getting an FCM account.

**Comment by jonsgreen** [comment]
@ide I closed this issue but since you seem so knowledgeable and have been helpful I was hoping you might be able to answer to more questions that might help us understand some strange behavior we are noticing.

Our app is in development still on test flight. Whenever someone logs in we do a call to Notifications.getExpoPushTokenAsync() and then add the token to a unique list on our backend for the current user. So if someone logs in as a different user on the same device they will start getting notifications for both users. That is desired behavior. However, we are also noticing that if a user updates versions they start getting a new token. Sometimes old tokens are rejected but sometimes they are not. Even when we do a request for receipt_ids for the tokens that are not rejected from the get_receipts endpoint they will show as all having succeeded. However, typically a user will only see one notification. Does the device or app somehow know that a notification might be from a token that is from a old version of the app that has now been upgraded and so it knows not to show it?

**Comment by ide** [comment]
> So if someone logs in as a different user on the same device they will start getting notifications for both users. That is desired behavior.

Just to reaffirm, yes, push tokens are per-device and not per-user.

> However, we are also noticing that if a user updates versions they start getting a new token.

This shouldn't be happening. On iOS -- since you mentioned TestFlight -- Expo maintains a 1:1 association between a unique installation ID and the Expo push token. This way, even if the native APNs token changes, the Expo push token should remain the same for a given device. The installation ID is used [when registering for an Expo push token](https://github.com/expo/expo/blob/41458d1de91544c41097818db21e44e9aa84688c/ios/Exponent/Kernel/Services/Notifications/EXApiV2Client%2BEXRemoteNotifications.m#L36) and is [stored in NSUserDefaults](https://github.com/expo/expo/blob/41458d1de91544c41097818db21e44e9aa84688c/ios/Exponent/Kernel/Core/EXKernel.m#L88-L97). So as long as NSUserDefaults isn't cleared -- and it isn't between app updates AFAIK -- the installation ID and therefore the Expo push token should remain the same.

Uninstalling an app will clear NSUserDefaults, which will create a new token, but a plain app upgrade via the App Store shouldn't. There's a chance that TestFlight behaves differently, though.

> Does the device or app somehow know that a notification might be from a token that is from a old version of the app that has now been upgraded and so it knows not to show it?

There isn't any verification like this. It is something we could perhaps look into on the server side, namely expiring Expo push tokens that refer to a native APNs token that has been registered with a newer installation ID, but this scenario shouldn't come up except in the uninstalled-then-soon-reinstalled scenario.

**Comment by jonsgreen** [comment]
@ide Thanks again so much for your help with this. We are getting close to sending out app to the App Store but these push notifications are critical to the purpose of the app so out client is quite concerned that this work properly. 

I have a user that just upgraded versions on test flight and definitely got a new push token. Both that token and the one from right before it are sending notifications to the same device. Do you think this might be a defect? Would it help you to have the tokens to verify what might be happening?

**Comment by jonsgreen** [comment]
I am going to reopen this ticket since it would be nice to confirm that this is not a bug with expo issuing push tokens on upgrades. It seems like this is undesirable behavior even with testflight but certainly going to the AppStore.

**Comment by ide** [comment]
From [this comment](https://stackoverflow.com/questions/35196228/nsuserdefaults-gets-cleared-when-app-updates#comment58111094_35196228) it appears that TestFlight clears NSUserDefaults between updates, which would reset the installation ID and therefore change the Expo push token. When you publish to the App Store, this should no longer be an issue (except when someone uninstalls and then soon re-installs an app -- there is a potential fix for this but nothing actively worked on).

**Comment by jonsgreen** [comment]
@ide I appreciate all of your support on this. That is good news that this problem should be resolved on the App Store. 

Nevertheless one of the developers on my team who is mostly a native ios developer feels like something is not quite right with your matching algorithm because Apple doesn’t send duplicate messages when an app is updated on test flight. What do you think?

**Comment by ide** [comment]
When a TestFlight app is reinstalled, it clears NSUserDefaults and resets the Expo push token. However, the native APNs token might not have been reset. In this scenario, if you were to use the native APNs token you wouldn't have duplicates, while with Expo push tokens you'd have two push tokens associated with the same native APNs token. The fix is to use a different ID mechanism than NSUserDefaults but the current behavior shouldn't affect normal App Store apps in the general case as detailed above.

**Comment by cruzach** [comment]
Closing this since the original issue was resolved, and the unwanted behavior in TestFlight should not occur in apps downloaded through the App Store
