### ISSUE TITLE
Published new versions not accessed by Android (detached) or Expo app (iOS), no issue on iOS (detached)

### ISSUE THREAD

**Issue by tgehrs** [expo/expo#246]
I am publishing new versions via XDE, in testing my detached app on iPhone via the App Market everything seems to be fine: I make a few changes, hit publish, reload the app and the new stuff is there (sweet!). However I went to test on my Android device using the detached app installed via Google Play and it seems to be stuck on an older version. The same thing happens if I open the app through the Expo app on my iPhone -- an older version still shows up... Any ideas why this would be happening?

**Comment by ide** [comment]
If you force quit the Android app and open it again do you get the latest code? We run a cached copy of your code if we can't fetch the latest copy quickly.

**Comment by tgehrs** [comment]
Tried open/close, restarting device, etc. For both the Expo and Android they seem to be stuck on an old version. manifestUrl in EXShell.plist and publishedUrl in MainActivity.java match. The only difference I have found is that the SDK version in iOS points to 15.0.0, while the SDK version in Android points to 16.0.0. Switching that value in the Android version solved the issue! It looks like I changed this value in the app.json a month or so ago to match the iOS version...

<img width="635" alt="screen shot 2017-06-12 at 10 34 49 am" src="https://user-images.githubusercontent.com/9788919/27039065-d143281c-4f5a-11e7-95e4-1c485e6bddff.png">

**Comment by ide** [comment]
The way Expo, the publishing system, and versions work is this:

- The Expo client and standalone apps support multiple SDK versions (ex: 18, 17, 16, 15).
- When you publish your project, the Expo server saves your project bundle and the "sdkVersion" value in exp.json or app.json.
- When the Expo client loads your project, the server sends back the latest bundle with the greatest SDK version that your client supports. So if your client supports SDKs 15 through 18 and you've published your project with SDK 15 and SDK 16, the server will send back the latest bundle for SDK 16.

So if you had published your project with SDK 16 before but then went back to SDK 15, any client that supports SDK 16 would still receive the old SDK 16 bundle.

If your issue has been resolved, please close this issue.

**Comment by tgehrs** [comment]
Thank you @ide !!

**Comment by camnicklaus** [comment]
I'm having this problem with iOS. honestly...for the life of me, I can't find info on what versions are available for ios client. I believe I have the most resent SDK version (23) and my app version is 2.2.0.1011491
I'm updating my phone atm to make sure I have the most recent client running. 

the correct code is served to the sim but not my device. tried restarting everything etc...
this is a detached app...
what else...

**Comment by ide** [comment]
@camnicklaus The most recent version is SDK 24 but if you've never published with it, using SDK 23 should be fine (and in the near future we're making so that apps get the most recent copy of your published project regardless of SDK version as long as the client can support it).

The "Developing with ExpoKit" docs might also provide a hint as to what could be going on: https://docs.expo.io/versions/latest/guides/expokit.html#3-ios-configure-build-and-run

**Comment by camnicklaus** [comment]
@ide thanks so much for the reply. Unfortunately nothing in that doc helped me. Maybe I'm trying to do something that just isn't intended to work? 
I'm on a team, the devs working on integrating stripe and facebook login for our app said they needed to detach. 
After detaching, I found that I could still run my sim by launching it from the expo XDE or from xcode. I prefer the expo XDE for the live reload speed.
Since that still worked (after detaching) I assumed I could also launch our app on my personal device with the XDE's "share" feature but it seems to be serving a previously cached JS bundle.

Should I be able to launch the current detached JS bundle on a real device by using the XDE's sharing feature (either by sending a link or scanning the qr code)?

**Comment by ide** [comment]
Once you detach, you continue to use XDE (for serving the JS) in addition to Xcode and Android Studio (for building the native code). The Expo client app that you downloaded from the App Store or Google Play doesn’t have the custom native code in your detached app, so it probably can’t run your JS fully.

You can use the Expo client to scan the QR code and it should tell your mobile OS to switch to your detached app (the URL of the QR code has a URL scheme that is specific to your detached app). But the JS code always should run in your detached app, not the Expo client.

**Comment by camnicklaus** [comment]
@ide thanks again...man, I'm so sorry but I just don't quite understand your answer. 

> The Expo client app that you downloaded from the App Store or Google Play doesn’t have the custom native code in your detached app, so it probably can’t run your JS fully.

this sounds like the Expo client will run some version of my latest code on my phone but without any of the native code I may have added since detaching

> You can use the Expo client to scan the QR code and it should tell your mobile OS to switch to your detached app (the URL of the QR code has a URL scheme that is specific to your detached app).

this sort of sounds like it IS possible to run the detached version of my app on my phone.

> But the JS code always should run in your detached app, not the Expo client.

forgive my ignorance but I'm not quite sure what this means.

Does this mean that, when I use the qr code or link to "share" to my phone I should be able to see the latest version of my detached app running but without any of the functionality the Native code would be adding?

here's a plain example of what I'm experiencing:
I have the XDE open and have started an instance of my detached app on the sim with XDE's "Device" button. 
I added a "hello world" text to my home view to make sure I'm seeing the latest change. 

I open the expo client on my phone and scan the qr code. the app opens and I don't see the "hello world" confirming that whatever is running on my phone is not the current code.

Is sounds to me like you're saying I should be able to see the "hello world" I've added as it's a part of the react-native JS, even if there may be some native code not running. yes? no?

thanks for bearing with me, I'm just trying to sort out if I've got some other issue going on, or if I simply trying to do something not possible with the expo client app for iphone.

**Comment by ide** [comment]
Hi @camnicklaus, to answer your questions, once a project is detached, it might no longer run correctly in the Expo client if you have added a custom native module to your detached project. This is because your project JS depends on that native code that the Expo client doesn’t have.

In general, once you detach, you should use your detached native app to run your project. By this I mean that you compile the Xcode Obj-C / Android Java projects that are created by detaching and run those on your phone. The Expo Client app you downloaded from the App Store or Google Play no longer can run your app completely (as explained above in this post).

Advanced caveat: If you are careful to use the custom native module after ensuring it exists (pseudo code might look like `if (NativeModules.CustomModule) { NativeModules.CustomModule.doSomething(); }`), your project JS will run in the Expo client but you won’t be able to use that custom functionality.

For your XDE sim example, instead of installing and running the Expo Client in the simulator (it’s fine if you did this, you just won’t use it), you want to build your detached project in Xcode and run it in the simulator. This is the native app that should open up.

I’m not quite sure what you ran into with the URL options. The localhost and LAN IP options should work fine for the simulator since it’s on the same computer as XDE/exp. React Native does have several caches and sometimes it’s helpful to clear them - here is a post on that: https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352. I’d also recommend force-quitting the app in the simulator too and launching it after you’ve got XDE/exp serving your project again.

The [Developing with ExpoKit guide](https://docs.expo.io/versions/latest/guides/expokit.html#3-ios-configure-build-and-run) covers a lot of this from a more hands-on angle, I’d recommend taking another look maybe with the teammates who also looked into ejecting.

**Comment by camnicklaus** [comment]
@ide thanks again...for the more detailed reply!
I do think I've got some caching issues. I'm new to pretty much all of this so that's likely my biggest problem :)
thanks so much for the links and holding my hand through this

**Comment by lilosir** [comment]
@ide Sir, I am also facing this issue. Every time I published to expo, the detached app updated perfectly. While, on Android, it still is using the first version when I uploaded to play store, never updated. Can you help me to fix that?
