### ISSUE TITLE
MailComposer.isAvailableAsync always returning false on iOS

### ISSUE THREAD

**Issue by floatplane** [expo/expo#24613]
### Minimal reproducible example

https://snack.expo.dev/@floatplane/mailcomposer

### Summary

MailComposer seems to have changed its behavior on iOS - I'm not seeing it open the registered mail app, in either Expo Go or in a build that's published to TestFlight. Weirdly, a `mailto:` link works as expected on iOS (in both Expo Go and in a published build).

In my app, I'm using `expo-mail-composer` version 12.3.0 and Expo version 49 (managed workflow). My iOS device is running iOS version 17.0.2.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.10.0 - ~/.nodenv/versions/18.10.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - ~/.nodenv/versions/18.10.0/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/brians/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.6 => 0.19.8 
    npmGlobalPackages:
      eas-cli: 5.2.0
    Expo Workflow: managed
```

**Comment by kadikraman** [comment]
Hi @floatplane I was looking into this as I was easily able to reproduce it on my phone.

The reason we were seeing this is because `expo-mail-composer` uses Apple's Mail client so if you don't have it set up [`canSendMail`](https://github.com/expo/expo/blob/8c6ee2a3dcc166ae9e9c53a139be50eba1ca0bba/packages/expo-mail-composer/ios/MailComposerModule.swift#L44) will always return `false`.

The `mailto://` links still working is also expected behaviour and is the suggested workaround if the user does not have the mail client set up. [This SlackOverflow answer](https://stackoverflow.com/questions/62940266/does-changing-the-default-email-app-affect-mfmailcomposeviewcontroller-usage/66379220#66379220) has some good detail.

This is what I did to get it working:
1. download the mail app if you don't have it installed https://apps.apple.com/us/app/mail/id1108187098
2. log in using your favourite mail provider (I used Gmail and it took me 2 tries as the 2FA is a bit temperamental, but it did auth in the end)

At this point I was able to open the mail composer, but the fields didn't get filled in properly as it still wasn't 100% set up, so I had to do one more step:

3. go to Settings -> Mail -> Accounts -> Gmail and toggle the "Mail" button on

| Seeing the same issue    | When I open the mail client | After adding Gmail | The extra step in Settings | it works 🎉 |
| -------- | ------- | ------- | ------- | ------- |
| ![IMG_9136](https://github.com/expo/expo/assets/6534400/9d35573b-f1e1-485d-b4a3-ba9c044ba4e7)  | ![IMG_9151](https://github.com/expo/expo/assets/6534400/233d3a94-2545-4ba4-9e64-48d2d8633c7f)    | ![IMG_9154](https://github.com/expo/expo/assets/6534400/a5ae9acc-9eec-4258-85a0-b2612b9f3e5c) | ![IMG_9158](https://github.com/expo/expo/assets/6534400/b7ac3e9d-afdd-46ed-98d8-881e4cacca78) | ![IMG_9156](https://github.com/expo/expo/assets/6534400/3e8e6a4b-d74e-4f1c-92a4-1c71de38a39b) |

**Comment by floatplane** [comment]
@kadikraman, thank you so much for the clear and thorough investigation. I wish Apple had implemented this differently, but this behavior at least makes sense now!
