### ISSUE TITLE
[docs] 

### ISSUE THREAD

**Issue by valentimcanejo** [expo/expo#24840]
### Summary

Basically I'm using the "expo-notifications" lib to send notifications, it works well when I accept notifications from the app myself, but when the user doesn't have, the apllication can't ask the user to do it, the "Notifications.requestPermissionsAsync();" doesn't open the prompt.

I read everything in this documentation: [expo-notifications-documentation](https://docs.expo.dev/versions/latest/sdk/notifications/) and still not working. I uploaded my project in github so you guys can see: [github project](https://github.com/valentimcanejo/notify) , I simply created a project with expo and put the expo-notifications example there, and still doesn't work, I'm really getting frustrated, help me please. I've tried eveythinng I saw here and in other forums.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/notifications/

**Comment by kadikraman** [comment]
Hi @valentimcanejo - the sample code in our docs works for me (that is, when I open it on my phone I get prompted for push permissions).

If the prompt not appearing is on iOS, then it could be because the user has rejected push permissions in the past. Every app can only ask for push permissions once, after which the user would have to update the permissions manually in Settings -> "App Name" or re-install the app so they can be prompted again.

If that doesn't help, I suggest logging the result for `getPermissionsAsync` which should help you debug what the user's permission state actually is.

**Comment by valentimcanejo** [comment]
> Hi @valentimcanejo - the sample code in our docs works for me (that is, when I open it on my phone I get prompted for push permissions).
> 
> If the prompt not appearing is on iOS, then it could be because the user has rejected push permissions in the past. Every app can only ask for push permissions once, after which the user would have to update the permissions manually in Settings -> "App Name" or re-install the app so they can be prompted again.
> 
> If that doesn't help, I suggest logging the result for `getPermissionsAsync` which should help you debug what the user's permission state actually is.

In my case isn't working even in Android, he shows the error that he couldn't get the notification token, and doesn't show the prompt to accept.

This is the log from "getPermissionsAsync":
`{"android": {"importance": 0, "interruptionFilter": 1}, "canAskAgain": false, "expires": "never", "granted": false, "status": "denied"}`
