### ISSUE TITLE
Keyboard becomes absolute when NavigationBar is set to absolute

### ISSUE THREAD

**Issue by Darhagonable** [expo/expo#24926]
### Minimal reproducible example

https://snack.expo.dev/@darhagonable/absolute-keyboard

### Summary

Expected Behavior: Once the keyboard is shown the view is expected to automatically adjust it's height as it does by default

Issue: When Navigation bar is set to be absolute positioned with `NavigationBar.setPositionAsync("absolute")` the keyboard also behaves absolute positioned and will overlap the content of the view as seen in the snack.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 KDE neon 5.27 5.27
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.2.0 - /usr/local/bin/npm
      Watchman: 20231001.212519.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      expo: ^49.0.10 => 49.0.11 
      react: ^18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ^0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by behenate** [comment]
@Darhagonable Hi, this seems to be intended behaviour. If you want the view to automatically adjust to the keyboard you should consider wrapping your component in a [`KeyboardAvoidingView`](https://reactnative.dev/docs/keyboardavoidingview).

**Comment by pekq** [comment]
@Darhagonable did you find a solution?

For @behenate, this is a legit issue. They are using KeyboardAvoidingView in their minimum 
reproducible example https://snack.expo.dev/@darhagonable/absolute-keyboard

**Comment by Darhagonable** [comment]
@pekq I did not sadly

**Comment by Vimiso** [comment]
Can anybody confirm this is indeed the intended behaviour, ie. position `absolute` consistently overlays the keyboard on android devices?

The reason I ask is because this seems to be less buggy than `"softwareKeyboardLayoutMode": "pan"` (which also overlays the keyboard on android) but unfortunately causes shifting of the entire window (even with `KeyboardAvoidingView` logic). 

In summary, position absolute seems to more closely replicate iOS' overlayed keyboard and is superior to `pan`. It enables you to use `KeyboardAvoidingView` for both ios and android using the same `behaviour`.
