### ISSUE TITLE
expo-location Inaccurate location acquisition

### ISSUE THREAD

**Issue by lengziyu** [expo/expo#24938]
### Minimal reproducible example

import * as Location from 'expo-location';

### Summary

Unable to obtain precise positioning, which differs by several hundred meters from the actual situation. Whether I set the accuracy to `Location.Accuracy.High` or `4`, or other low values, the position is at the position shown in the figure, which means setting the accuracy parameter to be invalid. 'expo-location': '~16.1.0'.
Attempting to execute multiple times is also the same, without any changes.
```
import * as Location from 'expo-location'

const getLocationAsync = async () => {
const location = await Location.getCurrentPositionAsync({
  accuracy: Location.Accuracy.High
})

const { latitude, longitude } = location.coords
```
![image](https://github.com/expo/expo/assets/9267469/6c1ef1bc-a7f5-449a-b83c-efd37cc9e791)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~49.0.5 => 49.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
      react-native-web: ~0.19.6 => 0.19.8
    Expo Workflow: bare

**Comment by behenate** [comment]
Hi, 
we have two PR's which will likely to fix the issue: https://github.com/expo/expo/pull/25028, https://github.com/expo/expo/pull/24737. It would be really helpful if you could wait until we publish a version of `expo-location` that includes at least #24737 and see if it fixes the problem.

Sice you are using a bare workflow you could also patch the package with the changes from the PRs yourself, this way we would know if the issue is fixed much sooner 😄  (be careful if you are using `react-native-maps` in that case make sure you're running `react-native-maps` `1.8.0` or newer)

Let's keep this issue open until we make sure that the issue is fixed

**Comment by behenate** [comment]
Hi, can you let me know if the issue appears on iOS or Android?

**Comment by XHFkindergarten** [comment]
> Hi, can you let me know if the issue appears on iOS or Android?

in my case, it appears on IOS.

**Comment by llli0v0** [comment]
It appears on iOS
