### ISSUE TITLE
iOS: Sound playback have too much echo when rate is changed with pitch correction enabled

### ISSUE THREAD

**Issue by colinux** [expo/expo#2497]
### Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 11.0.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: 3.0 AI-171.4408382

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/dacotha-54edd315-d75b-4e26-ba72-b2045111e527.tar.gz

Tested on iOS (iPhone 6S) in an app & a snack.
There is no problem on the Android device tested.

### Steps to Reproduce

Load and play a sound, whatever the format, with`rate` quite different from 1.0 (0.6 for example) combined with `shouldCorrectPitch: true` option : the sound is played with a lot of echo.

### Expected Behavior

The sound is played without echo, like with other tools allowing rating change (any html 5 browser with audio tag, or on a server with ffmpeg).

### Actual Behavior

Too much echo, some sounds become unintelligible with a large change in rate (< 0.6 or > 1.5). **There is no echo when `shouldCorrectPitch` is off.**

I know this is normal to have sound deformations when we alter rate & pitch, especially when rate is slowing down with pitch control, but the current implementation seems to me particularly poor comparatively to other alternatives like I described, or in native apps allowing changing rate on the fly (i.e. not on server side).

For what I tested, this is not relevant to a particular format (wav/mp4/mp3…) or caracteristics like frequency or bitrate.
 
### Reproducible Demo

https://snack.expo.io/@colinux/sound-echo-when-rate-is-changed-with-pitch-control-

**Comment by ide** [comment]
The iOS implementation uses Apple's built-in API, with the default configuration for all iOS playback: https://github.com/expo/expo/blob/1451335ae573dcbd1ac6305dd8e9230c9adc96fa/ios/Exponent/Versioned/Core/Api/AV/EXAVPlayerData.m#L295 (https://developer.apple.com/documentation/avfoundation/audio_track_engineering/audio_settings_and_formats/time_pitch_algorithm_settings?language=objc). We could try AVAudioTimePitchAlgorithmSpectral instead but it is tricky since that is optimized for music while AVAudioTimePitchAlgorithmTimeDomain is optimized for voice.

**Comment by tsapeta** [comment]
This issue seems to be outdated – SDK30 is no longer supported and a lot of changes have been made since that time, so I'm closing it but feel free to comment here or open a new issue if you're still experiencing this 🙂
