### ISSUE TITLE
How to get an original push token from ios?

### ISSUE THREAD

**Issue by alexesDev** [expo/expo#250]
I try to integrate onesignal.com, but i cannot to find original token... only expo push token.
PushNotificationIOS from react-native not work because the native code for this not included in the expo client.
I can not get it?

**Comment by terribleben** [comment]
Hi there, we don't support platform-specific push notification libraries since our existing notification API needs to work on iOS and Android out of the box and is deeply integrated with our native code. It's also a sandboxing issue to give out native device tokens in our Expo Client app, since it can run many different projects.

If you really need a native APNS push token, your best bet is to [detach](https://docs.expo.io/versions/v17.0.0/guides/detach.html#content) and write your own native hook for this, and forego Expo's built-in notifications API. But I can't think of a use case where you would want to do that.

**Comment by terribleben** [comment]
Just kidding, we'll add support for this in SDK 18, in Standalone builds only. See this magnificent pull request: https://github.com/expo/expo/pull/258#issuecomment-307938266

**Comment by robbiemu** [comment]
How can you. get this now?
