### ISSUE TITLE
[android][expo-image-picker] Error "Uri lacks 'file' scheme" when using allowsMultipleSelection and quality < 1

### ISSUE THREAD

**Issue by jvaldenor** [expo/expo#25098]
### Minimal reproducible example

https://snack.expo.dev/@jvaldenor/image-picker

### Summary

ERROR Error picking images: [Error: Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000012115]

version

"expo": "^49.0.3",
"expo-image-picker": "~14.6.0",
This only happens if the quality is not 1 while allowsMultipleSelection:true or allowsEditing:false

not working:

```
const result = await ImagePicker.launchImageLibraryAsync({
mediaTypes: ImagePicker.MediaTypeOptions.All,
quality: 0.2, //1 is working
allowsMultipleSelection: true,
selectionLimit: 10
});
```

not working:

```
const result = await ImagePicker.launchImageLibraryAsync({
mediaTypes: ImagePicker.MediaTypeOptions.All,
quality: 0.2,
allowsEditing: false
});
```

This is working

```
const result = await ImagePicker.launchImageLibraryAsync({
mediaTypes: ImagePicker.MediaTypeOptions.All,
quality: 1
allowsMultipleSelection: true,
selectionLimit: 10
});
```

This too is working:

```
let result = await ImagePicker.launchImageLibraryAsync({
mediaTypes: ImagePicker.MediaTypeOptions.Images,
allowsEditing: true,
aspect: [4, 4],
quality: 0.2,
});
```

Succes log:
{... "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540....", "width": 3000}], "canceled": false}

all scenarios working in IOS

affected: samsung galaxy s22 ultra, android version 13

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 13.5
Shell: 5.9 - /bin/zsh
Binaries:
Node: 18.17.0 - /usr/local/bin/node
npm: 9.6.7 - /usr/local/bin/npm
SDKs:
iOS SDK:
Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
IDEs:
Android Studio: 2022.2 AI-222.4459.24.2221.10121639
Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
npmPackages:
expo: ^49.0.3 => 49.0.16
react: 18.2.0 => 18.2.0
react-native: 0.72.3 => 0.72.3
npmGlobalPackages:
eas-cli: 3.16.0
Expo Workflow: managed

**Comment by bdow** [comment]
Fwiw, I have a feeling this is an Android version issue. I also am unable to select any photos from my library due to the above error. I am _pretty_ sure this used to work. I am currently on v13

**Comment by nakedgun** [comment]
@brentvatne @alanjhughes I can confirm this is an **Android expo SDK 49 only bug** introduced by switching to the new photo picker UI as per this case: https://github.com/expo/expo/pull/22658 . The issue was originally raised here but closed: https://github.com/expo/expo/issues/24172

It repros on Expo Go and EAS builds when `quality < 1` and `allowsMultipleSelection: true`. The original snack in this case doesn't include these settings. Here's an updated one: https://snack.expo.dev/@yaxo/expo-bug-25098 . 

You have to run that Snack on a *physical android device* to get the new photo picker UI. In which case the image selection will fail. Tested on Android 12/13 with pixel/samsung phones. It will probably affect Android 11 too. The only workaround at the moment is to use SDK 48, set `quality` to 1 or handle image compression manually after the images are selected.

**Comment by alanjhughes** [comment]
Hi @nakedgun - I've been testing this on pixel devices from android 12 to 14 and cannot reproduce the issue. I've used all of the options variants marked as not working by @jvaldenor and also yours and it works correctly on both physical devices and emulators.

**Comment by nakedgun** [comment]
Hey @alanjhughes. Well, these are always fun ones. It repros for me on a Pixel 3 XL (Android 12, Play System Update Feb 1st 2023), a Galaxy A14 (Android 13, Play System Update Nov 1st 2022) as well as some older samsung and LG phones :/ 

The exact bit of code is this:

```
 const result = await ImagePicker.launchImageLibraryAsync({
  mediaTypes: ImagePicker.MediaTypeOptions.Images,
  allowsEditing: false,
  allowsMultipleSelection: true,
  quality: 0.5 // setting this to 1 stops the issue
});
```
Which triggers the _new_ Android photo picker UI (if it shows the old UI, the bug won't occur):

![Screenshot_20231208_092325_Media jpg](https://github.com/expo/expo/assets/5262234/813c579d-ebe7-4689-b3ba-0711d8c7d2e3)

Which always errors with:

```
[Error: Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000000035]
```

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.5.0 => 9.5.2
      expo: ^49.0.0 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9

Other npm packages

expo-image-picker@14.3.2
expo-image-manipulator@11.3.0
expo-media-library@15.4.1
```

Also tried `expo-image-picker@14.5.0` - same issue. Is there any more info or debugging that would help?

**Comment by weijian6791** [comment]
Had the same problem with Expo 48 + pixel or iPhone, but not for standalone app.

**Comment by Mrudula-Nemani** [comment]
I have the same problem with android 13 and also iOS, this happened when I didn't allow the permissions for gallery first and did allow the permission later in app settings from then the permission status is "granted", image launcher is opening but after selecting the image, getting the below error.
[Error: Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: java.lang.IllegalArgumentException: Uri lacks 'file' scheme: content://media/picker/0/com.android.providers.media.photopicker/media/1000000250]

**Comment by AlimovSV** [comment]
Please do not close the issue, the problem was not solved and there was no workaround found.

**Comment by matejkriz** [comment]
Reported in our Sentry from Android 14, moto g14. SDK 51.
