### ISSUE TITLE
Permissions.getAsync(Permissions.LOCATION) returns denied on launch 

### ISSUE THREAD

**Issue by farzd** [expo/expo#2510]
### Environment
```
environment:
  OS: macOS 10.14
  Node: 8.12.0
  Yarn: 1.9.4
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4907809

Packages: (wanted => installed)
  expo: ^30.0.0 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/farzd-ea65e8cb-5b69-4bd9-b1fa-4429dd6c49f1.tar.gz
```

### Steps to Reproduce

Location permission on initial read returns DENIED on Android [this is not the case for iOS]
for example if you read the permissions on component did mount and show button to toggle permissions dialogue 
```
const { status } = await Permissions.getAsync(Permissions.LOCATION)
```

### Expected Behavior
It should be same as iOS, should return UNDETERMINED 

### Actual Behavior
Location permission on initial read returns DENIED on Android

**Comment by iliandy** [comment]
Any update on this? I'm still seeing this with my setup:

env:
  OS: Win 10.0.17134 Build 17134
  Node: 11.9.0     
  NPM: 6.1.0       
  Yarn: 1.3.2
  Android Studio: 3.3.1
  Android Emulator: 28.0.23

packages:
  Expo: 32.0.1
  React: 16.5.0
  React-Native: 0.57.1

Thanks!

**Comment by simsketch** [comment]
Yeah I had this break in a production app...no idea how to resolve...yikes!

**Comment by mutablestudio** [comment]
on Android 26+ expo Permissions doesn't seem to work at all. `Permissions.NOTIFICATIONS` and `Permissions.LOCATION` never prompt for permission request. 

Workaround is to use `PermissionsAndroid` from 'react-native'.

**Comment by scraappy** [comment]
Wow...thanks for that bit of advice...you're a life saver!

**Comment by simsketch** [comment]
Wow...thanks for that bit of advice...you're a life saver!

**Comment by simsketch** [comment]
using react-native PermissionsAndroid proved to be helpful but required a lot of rewriting, so I explored another option which was upgrading expo-location to 3.0.0

Below was copied from https://github.com/expo/expo/issues/946
I had success getting location to work for Android, using expo 32.0.6:

`npm install expo-location`
make sure it is now in your package.json file as "^3.0.0"
`rm -rf node_modules/`
`npm i`
check inside `node_modules/expo-location/package.json` to make sure that version 3.0.0 was installed
`expo start` to test locally if you'd like
`expo build:android` to generate apk because changes any changes to `app.json` require a new store submission.

My expo Location code that was working in previous builds and then broke, is now working again as expected. I was using expo-location 2.0.1 previously and it looks like they came out with 3.0.0 6 days ago https://www.npmjs.com/package/expo-location, so I thought I would give it a shot because in another issue around here they said they had some fixes in the works.

Thanks for the fix Team Expo!

**Comment by lukmccall** [comment]
I'm closing this issue because it was fixed.
