### ISSUE TITLE
expo-camera returns to the previous page, the green dot of iOS recording does not disappear

### ISSUE THREAD

**Issue by xha123** [expo/expo#25181]
### Minimal reproducible example

https://github.com/xha123/expoDemo.git

### Summary

For iOS, use expo-camera and react-navigation. Enter the camera page, the preview is normal, and click back to the previous page. The green indicator light in the iOS phone status bar still exists.
![screenshot-20231102-180332](https://github.com/expo/expo/assets/25577710/cfc44ed5-73b1-4010-afbb-47344174eab5)

### Environment

   System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.20.1 - D:\az\node-v16\node.EXE
      Yarn: 1.22.19 - D:\az\node-v16\yarn.CMD
      npm: 8.19.4 - D:\az\node-v16\npm.CMD
    npmPackages:
      expo: ^49.0.8 => 49.0.16
      react: 18.2.0 => 18.2.0
      react-native: 0.72.4 => 0.72.4
    Expo Workflow: bare

**Comment by marlonschlosshauer** [comment]
I can't say for certain, but I had similiar issues with React Navigation (I saw that you use that), because they cache each screen. Components don't unmount when you change screens, which causes the camera to stay active (and therefore the green dot stays on). This is also why you wouldn't be able to use another camera on another screen. 

What fixed it for me was to always purge the cache by using `navigation.reset` instead of `navigation.navigate`.

**Comment by xha123** [comment]
[https://github.com/software-mansion/react-native-reanimated/issues/3124](url)
This is a possible reason, but I didn't succeed in solving the problem

**Comment by 0hhanum** [comment]
I'm experiencing the same issue.

Could anyone provide an update on this issue or share a workaround if available?
Should we open a new issue to track this ongoing problem?

**Comment by 0hhanum** [comment]
@zwenza 
 I manually unmount the camera component before the page unmounts and it works to me.
(with `useFocusEffect`)
