### ISSUE TITLE
Google Pay not working in Android, am getting false when I call isPlatformPaySupported

### ISSUE THREAD

**Issue by Stancobridge** [expo/expo#25427]
### Summary

I can't seem to get Google Pay to work on Android, am using Expo Custom dev client, and after installing Stripe I rebuilt the dev client, but I get a false when I call isPlatformPaySupported, am using "@stripe/stripe-react-native": "0.28.0",

I also added this in my app.json
```
  [
      '@stripe/stripe-react-native',
      {
        enableGooglePay: true,
      },
    ],
```

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

Android

### Package versions

"expo-dev-client": "~2.4.11",
"expo-updates": "~0.18.16",

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.1 (Vera)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.17.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.6.7 - /usr/bin/npm
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7 
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ^49.0.9 => 49.0.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 5.6.0
    Expo Workflow: managed

### Reproducible demo

https://github.com/Stancobridge/google-pay-rn-example

**Comment by Kudo** [comment]
hi there! sorry that the issue is internal to stripe sdk, i don't have enough expertise to investigate the issue. at the same time, i noticed you opened an issue for stripe at https://github.com/stripe/stripe-react-native/issues/1561. would keep attention to their response and see if there's anything we can help from expo side.

- would be good to attach your [example](https://github.com/Stancobridge/google-pay-rn-example) for the stripe issue you opened. that would help their investigation.
- not sure if that helps, i checked the doc and they need a step for [adding the `StripeProvider`](https://stripe.com/docs/google-pay?platform=react-native#stripe-initialization). maybe you can try to add this.

**Comment by Stancobridge** [comment]
> hi there! sorry that the issue is internal to stripe sdk, i don't have enough expertise to investigate the issue. at the same time, i noticed you opened an issue for stripe at [stripe/stripe-react-native#1561](https://github.com/stripe/stripe-react-native/issues/1561). would keep attention to their response and see if there's anything we can help from expo side.
> 
> * would be good to attach your [example](https://github.com/Stancobridge/google-pay-rn-example) for the stripe issue you opened. that would help their investigation.
> * not sure if that helps, i checked the doc and they need a step for [adding the `StripeProvider`](https://stripe.com/docs/google-pay?platform=react-native#stripe-initialization). maybe you can try to add this.

thank you for your response, for the StripeProvider, I tried that too none worked

**Comment by zewas-digital** [comment]
Any updates on this?
