### ISSUE TITLE
AppLinks not auto-verified on Android

### ISSUE THREAD

**Issue by jamzi** [expo/expo#25537]
### Minimal reproducible example

https://github.com/jamzi/expo-test-universal-links

### Summary

I followed the deeplink docs: https://docs.expo.dev/guides/deep-linking/ to implement Universal Links on iOS and AppLinks on Android.

This issue occurs on Android, where the release app doesn't auto verify the deeplink. I've added the next the `intentFilters` part in the app.json config with the autoVerify set to true. In the app settings it shows 0 verified links, but I can manually select the link.

Running the expo prebuild produces the AndroidManifest.xml file without the necessary intent filter.

I've also tried adding the custom config plugin mentioned here, but to no luck: https://github.com/manifoldmarkets/manifold/blob/461bcc1c0c7b2e0457dd85505a760a0a9d817be9/native/plugins/withAndroidVerifiedLinksWorkaround.js. I'm not sure that this config plugin is related to the deeplink config.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
      Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/janez/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.20 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.9.0
    Expo Workflow: managed

**Comment by reistence** [comment]
Hi @jamzi,  did you, by any chance, get the deep links working? I followed your same steps as per docs but still experiencing your same issues on Android.

**Comment by DSp4wN** [comment]
Same issue here as well I added assetlinks.json as well as added intent filters and made sure everything is as per my google play console, still it wont take it to my app

**Comment by zakwalters** [comment]
In my case, the issue was that Expo development builds have a different SHA-256 fingerprint to either the Google Play build fingerprint, or an EAS build fingerprint (the one you get from `eas credentials`). I had the Google Play and EAS fingerprints in my `assetlinks.json` file, but not the development build one, so the auto-verification wasn't working.

To get the local development build fingerprint, run:

```
keytool -list -v -keystore android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android
```

If you add the SHA-256 fingerprint from the output to your `assetlinks.json` file, deep links should work on Android development builds.

Cross-linking the other issues I went through while trying to figure this out: https://github.com/expo/expo/issues/18769, https://github.com/expo/expo/issues/19745, https://github.com/expo/expo/issues/21705, https://github.com/expo/expo/issues/25537, https://github.com/expo/expo/issues/29210, https://github.com/expo/expo/issues/30248

**Comment by jeanpaulsio** [comment]
@zakwalters - I think i'm experiencing a similar issue here. If i use the SHA-256 straight from the Google Play console, everything seems to be green. Still however not able to get my app on Android to open links

![CleanShot 2024-10-17 at 09 06 39@2x](https://github.com/user-attachments/assets/01051160-99b9-4edb-a5e4-458f76aae415)

Is it necessary to get the local development build fingerprint for prod and add this to my assetlist.json file in addition?

When you're running this command...

```
keytool -list -v -keystore android/app/debug.keystore -alias androiddebugkey -storepass android -keypass android
```

... is this grabbing `debug.keystore` from the android folder in your expo directory? Secondarily, I don't have an `/android` directory unless I do something like run `npx expo prebuild -p android`

**Comment by RahulMandyal1** [comment]
Thanks @zakwalters for the help! 
We do have an existing app where deeplinking wasn't working. The issue was that it worked on iOS with the previous SHA-256 fingerprint, but not on Android. 
The reason for this is that the domain wasn't getting auto-verified on Android devices. This is because we are using EAS for building, which generates a different SHA-256 fingerprint.

This has been mentioned in the documentation as well. Here's the link:
[Auto-verified on Android devices, and the issue seems to be related to our use of EAS for building, which generates a different SHA-256 fingerprint.](https://docs.expo.dev/linking/android-app-links/#set-up-two-way-association)

I’ve updated the SHA-256 fingerprint generated by Expo CLI, and it worked for me.

**Comment by ziga-hvalec** [comment]
Any other solutions for this? i have coppied the sha-256 from play store and added it to assetlinks.json file but when installing app it's still not verified.
Our minSdkVersion is set to 24.
