### ISSUE TITLE
Client should reload when it handles opening a URL without params

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2562]
- Start expo-cli for project A, press i to open exp://localhost:19000 in simulator
- Close expo-cli for project A, open it for project B, press i to open exp://localhost:19000 in simulator
- Notice that it doesn't change to project B, it just shows the previously open project A.
- I would expect it to open project B as if it were an experience with a completely different URL.

There's a similar, but not identical problem with Snack:
- Open a saved Snack in your browser then open it in the Expo client
- Reload the Snack page in your browser
- Go to the Expo menu, you now have two entries for the Snack - they are differentiated by the + with the URL. It doesn't matter which one you press, it'll bring you back to the Snack -- the first one you opened with the first session. We could potentially fix this on Snack by adding `Linking.addEventListener` - this seems desirable. We probably don't want to reload experiences if the URL has deep links, just do the usual deep linking behavior.

**Comment by tcdavis** [comment]
The snack side of this is resolved

**Comment by terribleben** [comment]
Just to chime in on some cases we were trying to support when we built this originally--

- You should be able to test deep linking to your app in Expo Client, and it should behave however it would behave in standalone. My impression is that in a standalone app we wouldn't reload in this case, we'd send a Linking event to the running JS.
- In most circumstances we probably don't want to wait for a manifest roundtrip before deciding what to do with a deep link -- though I agree james suggestion seems correct in this case, so maybe we should localize that behavior to be when we see a localhost or LAN url?

**Comment by ide** [comment]
Good point about deep linking -> it seems like the problem is that we need to distinguish between sending a URL to an already-open project vs. opening a new project.

Here's a strawman idea:
- when opening a project from Home or Expo CLI -- whether that's entering a URL in the search bar, tapping on a featured project, or running `expo ios/android` from a terminal -- we interpret that always as "open this project" and fetch the manifest and launch a new app. In all these cases, the URL is opened from Expo's software and we have the opportunity to include some metadata (namely a signal to open a new project) with the URL.
- when opening a URL any other way, we treat it as a deep link with the current behavior i.e. if the project with the same URL origin (protocol + host + port) is open then we just send it a Linking event, and if the project isn't open then we launch it (fetch manifest + run bundle).

**Comment by tsapeta** [comment]
It seems to be resolved – as far as I know we're already reloading the manifest in such cases.
