### ISSUE TITLE
Development Build with expo-camera results in `Cannot find native module 'ExponentCamera', js engine: hermes` Error

### ISSUE THREAD

**Issue by yossydev** [expo/expo#25796]
### Minimal reproducible example

https://github.com/yossydev/expo-camera-development-build-error

### Summary

Expected Behavior: The application works without errors.
What is actually happening: An error occurs stating ERROR  Error: Cannot find native module 'ExponentCamera', js engine: hermes, and the application does not run.
Affected Platform: iOS

### Environment

```
expo-env-info 1.0.5 environment info:
  System:
    OS: macOS 14.1.2
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.volta/tools/image/node/20.10.0/bin/node
    Yarn: 4.0.1 - ~/.volta/tools/image/yarn/4.0.1/bin/yarn
    npm: 10.2.1 - ~/.volta/tools/image/npm/10.2.1/bin/npm
  Managers:
    CocoaPods: 1.14.3 - /Users/s20106/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.11005911
    Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
  npmPackages:
    expo: ~49.0.18 => 49.0.21
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-native: 0.72.6 => 0.72.6
    react-native-web: ~0.19.6 => 0.19.9
  Expo Workflow: managed
```

**Comment by Kudo** [comment]
hi there! thanks for sharing the repro. as the steps in your [README](https://github.com/yossydev/expo-camera-development-build-error/blob/main/README.md), you didn't mention how you build your development build. could you share the information of how you build the app with me? i tried `npx expo run:ios` with the repro and it works for me.

**Comment by steveliles** [comment]
I'm seeing this problem while trying to upgrade from expo ~49.0.13 with expo-camera ^13.6.0, to expo ^50.0.4 and expo-camera ~14.0.3. 

I am also using a development build, not expo go.

Per the upgrade instructions I ran `npm install expo@latest` and then `npx expo install --fix`.

Camera was working fine prior to attempting the upgrade.

Now on startup the iOS bundling fails with:
"Error: Cannot find native module 'ExpoCamera', js engine: hermes"

Earlier in the log I see the following warning (also new since upgrading Expo):
 WARN  The native view manager required by name (ExpoCamera) from NativeViewManagerAdapter isn't exported by expo-modules-core. Views of this type may not render correctly. Exported view managers: [ExponentCamera, RNCSafeAreaProvider, ExpoBarCodeScanner, ExpoImage].

**Comment by steveliles** [comment]
Thanks @yossydev, unfortunately `npx expo run:ios` results in cocoapods issues.

```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "React-FabricImage":
  In Podfile:
    React-FabricImage (from `../node_modules/react-native/ReactCommon`)

Specs satisfying the `React-FabricImage (from `../node_modules/react-native/ReactCommon`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by steveliles** [comment]
OK, so removing my local ios directory and re-running `npx expo run:ios` seems to have sorted it out.
