### ISSUE TITLE
[expo-barcode-scanner] Incorrect BarCodeScannerResult coordinates in development builds

### ISSUE THREAD

**Issue by daankennes** [expo/expo#25851]
### Minimal reproducible example

https://snack.expo.dev/@daank/expo-barcode-scanner-coordinates

### Summary

I've noticed that the coordinates returned with a barcode scan result are off. They are increasingly inacurate when further away from (0,0). This only seems to happen in development builds, so the MRE will work just fine. I am however able to reproduce this by creating a fresh development build, installing expo-barcode-scanner and pasting the above code in the new project. Tested on Android only.

I've tried with both bounds and cornerPoints. Both are off by the same distance. Here's a screenshot of what's happening (the purple shape should cover the qr code):
![Screenshot_2023-12-11-14-47-55-411_be moonchase labonline](https://github.com/expo/expo/assets/32707088/c953aee7-d9e7-401a-b359-24ea297f075e)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621 (--> this in incorrect, I am on Windows 11)
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^49.0.21 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

### Package.json of development build project:
{
  "name": "expo-barcode-scanner-test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.15",
    "expo-barcode-scanner": "~12.5.3",
    "expo-dev-client": "~2.4.12",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-barcode-mask": "^1.2.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}

**Comment by micbaumr** [comment]
same here

**Comment by steveliles** [comment]
I'm currently running into this while scanning ean13 barcodes (standard stripey barcode). The problem seems to be a transposition of the x and y coordinates, as if the scanner thinks I am working in landscape (but the app is locked to portrait).

If I transpose `x` with `y`, and `width` with `height` when destructuring `boundingBox` on Android `{ boundingBox: origin: { x: y, y: x }, size:{width:height,height:width }}` the box position is then correct.

If I transpose `x` with `y` when destructuring `bounds` on iOS, `x` and `y` are then correct (as proportion of screen width/height in the range 0-1, so to get the actual coordinate use e.g. `Dimensions.get("window").width * x`). 

This is happening in my development builds. I don't know what an MRE is(?) but I assume the same issue will be present in production builds (and tbh if the development build and prod build do not behave the same i'ma 🤯 🤯 🤯 ).

I tried datamatrix codes which behave exactly the same on android (transposed), but on iOS the coords do seem to be transposed but the x value (after swapping) is always a bit random and moves around well away from the code itself unless you move the camera to get the code in the middle of the screen. I'm assuming that this difference is because some codes are scanned with zxing and others are not (guessing from a quick look at the source, but i didn't dwell on it as i'm not a native ios dev).

my minimal repro is here: https://github.com/steveliles/expo-barcode-scanner-coords-issue (note that in my repro i am transposing the coordinates so the box (android) or crosshair (ios) are in the correct positions, but i should not have to do this transposition).

**Comment by steveliles** [comment]
just want to add: I am using expo-camera not expo-barcode-scanner, but I believe its the same issue.

I cannot upgrade to expo-camera/next scanner because of other blocking issues (#26952 and #26953).

**Comment by shehanGuruge** [comment]
I am always getting undefined for barcode bounds in my debug android project.

**Comment by kepman** [comment]
I am also facing problems with the New version of the cornerPoints..
The Legacy version used pixel and the cornerPoints are straightforward and correct.
Yet the Legacy version I need to convert values between 0-1 to actual pixels in the container and like @steveliles mentioned need to transpose..

doing the transpose makes the cornerPoints inaccurate. see the attached video below for comparison between Legacy and Next camera:


https://github.com/expo/expo/assets/2862907/1f84ee11-ea77-4257-9142-d17026c74787


https://github.com/expo/expo/assets/2862907/4ba50244-fc73-4b4f-ab85-90541738b111

**Comment by kepman** [comment]
I forgot to mention that it is most noticeable when you rotate the device. in the video below I show both version starting with the legacy which works perfect and then the legacy that is way off especially when the device is held diagonally:

https://github.com/expo/expo/assets/2862907/02e09273-888b-4922-af8a-46c258f321f7

**Comment by alanjhughes** [comment]
> I'm kinda confused why you guys changed this in the Next version which made the cornerPoints broken 😞

It wasn't intentional and has been fixed in #28931
