### ISSUE TITLE
[expo-location] Selecting "Allow once" when requesting foreground permissions does not update background permissions

### ISSUE THREAD

**Issue by thomasgrivet** [expo/expo#25873]
### Minimal reproducible example

https://github.com/Cocolis-1/blank-expo/tree/feat/expo-location

### Summary

After selecting "Allow once" when using `requestForegroundPermissionsAsync`, I have to call `requestBackgroundPermissionsAsync` two times for the background permissions to update and give a canAskAgain: false.

https://github.com/expo/expo/assets/18561703/0d372aed-7a8e-46c3-9c82-74e3ce1c49ed

This behaviour seems strange considering the fact that it does not occur when selecting "When app is active"

https://github.com/expo/expo/assets/18561703/c6ed3464-a95d-4758-abe3-c0de076fb990

### Environment

```
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v21.1.0/bin/yarn
      npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.15 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: managed
```

**Comment by balloman** [comment]
I also have this issue, and just decided to call the function twice as a workaround

**Comment by brentvatne** [comment]
i'd like to just say thank you for not only providing a reproducible example project but also videos demonstrating the issue!

**Comment by BrodaNoel** [comment]
@brentvatne seems like this issue is still present for asking access to get location in background.

I have to ask for the background access 2 times in order to get the "granted" true

Have this fix being released?

**Comment by chrfalch** [comment]
I've added a note about how permissions work in iOS under our documentation site:

https://docs.expo.dev/versions/v52.0.0/sdk/location/#expo-and-ios-permissions

It clarifies some of the complexities behind the iOS location permission system - like that fact that requesting for foreground permissions directly followed by requesting background permissions is not needed - requesting background permissions automatically requests foreground permissions if they're not given.

**Comment by josephineweidner** [comment]
@chrfalch thank you for adding this documentation, very helpful! 

> If you call [requestBackgroundPermissionsAsync](https://docs.expo.dev/versions/v52.0.0/sdk/location#locationrequestbackgroundpermissionsasync) without first requesting foreground permissions, iOS treats it as a request for both When In Use and Always authorization. The system will then prompt the user for When In Use access, and the Always authorization prompt will be displayed when the system determines that Always authorization is required.

I'm observing the following: 
1. On a fresh install, I call [requestBackgroundPermissionsAsync](https://docs.expo.dev/versions/v52.0.0/sdk/location#locationrequestbackgroundpermissionsasync) without first requesting foreground permissions. I see the OS pop up, with the options (1) Allow Once (2) Allow While Using App and (3) Don't Allow
2. When I click "Allow While Using the App" and then navigate to OS Settings a few moments later, I see that "Allow Location Access" is set to "While Using the App" (as expected)

Two things are confusing to me here: 
1. The result of requestBackgroundPermissionsAsync is `{"canAskAgain": true, "expires": "never", "granted": true, "scope": "always", "status": "granted"}` - why is the `scope` `always` here instead of `whenInUse`?
2. Could you please expand on what you mean by "when the system determines that Always authorization is required"? How do you recommend bumping permissions from "When Using the App" to "Always" here?
