### ISSUE TITLE
A duplicated assets folder inside dist is being created when Static exporting with Metro

### ISSUE THREAD

**Issue by arun-spar** [expo/expo#25919]
### Summary

npx expo export -p web creates a duplicated assets folder inside dist.
![image](https://github.com/expo/expo/assets/121198022/0543ed20-bb43-4c4a-8cfb-ce33388e6732)

More Info: 
https://github.com/expo/expo/issues/24073#issuecomment-1818184377
https://github.com/expo/expo/issues/24073#issuecomment-1812033682
https://github.com/expo/expo/issues/24073#issuecomment-1853307937

### SDK Version

49

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.11090377
    npmPackages:
      expo: ~49.0.18 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: managed

### Minimal reproducible example

https://github.com/spar-dev/expotabapp.git

**Comment by marklawlor** [comment]
@arun-spar This isn't a duplication, but rather a coincidence that both you and Expo have chosen the same folder name.

In React Native, `assets` is a special term used by Metro. Assets are bundled differently than J, with their own customisatizable (Metro allows you to configure asset resolution and transformation) workflow. For users to easily identify files that have been processed by this workflow we output the `asset` files in an `assets` folder. Because your "assets" are in a user created folder (also called assets) it creates the folder structure `assets/assets`.

If you rename your `assets` folder you'll see the output is `assets/<new-folder-name>`. Or you can simply move your `fonts` & `images` to the top level, so the output will be `assets/fonts`
