### ISSUE TITLE
Can not add react-native-system-settings module

### ISSUE THREAD

**Issue by mojtabamarashee** [expo/expo#2592]
Why  <a href="https://github.com/c19354837/react-native-system-setting">react-native-system-setting</a> dependency can not be add to project?

<a href="https://github.com/mojtabamarashee/Expo">my repo</a>

Error:<span style="color:blue">**_Failed to install module 'react-native-system-setting': Native module cannot be null_**.</span>
 imported from null

thanks

**Comment by sjchmiela** [comment]
Hey, @mojtabamarashee!

Expo Client and standalone apps contain a predefined set of native modules. You can see a list of available APIs in the [docs](https://docs.expo.io/).

`react-native-system-setting` library requires native code to work properly (notice it has both `android` and `ios` directories in [the repo](https://github.com/c19354837/react-native-system-setting). Since we don't support adding your custom modules to neither Expo Client nor standalone apps yet, even if you would install the package, the library wouldn't work properly ([setup](https://github.com/c19354837/react-native-system-setting#install) wouldn't be complete).

In your situation you can either:
- if you need all the features `react-native-system-setting` supports (or to be specific, more than just `Brightness`) — [eject your project](https://docs.expo.io/versions/v31.0.0/expokit/eject) and add the native module yourself,
- if you need only `Brightness` — you can use Expo's [brightness API](https://docs.expo.io/versions/v31.0.0/sdk/brightness).

**Comment by mojtabamarashee** [comment]
Thanks for reply.
I need Enable Airplane mode (for android) , Can I do it using Expo sdk or any Epxo supported module?
