### ISSUE TITLE
Error in ExponentImagePicker.launchImageLibraryAsync on Android

### ISSUE THREAD

**Issue by janicduplessis** [expo/expo#26056]
### Minimal reproducible example

N/A

### Summary

I am getting the following error in production for a few users. Sadly I am currently unable to reproduce it so I was just wondering if you have any idea what could cause this. I will try to gather more information since right now the error message is truncated so it is harder to know where it is coming from.

I am using the following parameters when calling `launchImageLibraryAsync`

```ts
ExpoImagePicker.launchImageLibraryAsync({
  mediaTypes: MediaTypeOptions.Images,
  quality: 0.8,
  exif: true,
  allowsMultipleSelection: false,
});
```

Error:

```
Call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected.
→ Caused by: The 1st argument cannot be cast to type expo.modules.imagepicker.ImagePickerOptions (received class com.facebook.react.bridge.ReadableNativeMap)
→ Caused b...
```

More info from sentry:

```
Model	
SM-G981W (TP1A.220624.014)

Name	
Galaxy S20 5G

Permissions
{
ACCESS_COARSE_LOCATION: granted, 
ACCESS_FINE_LOCATION: granted, 
ACCESS_NETWORK_STATE: granted, 
ACCESS_WIFI_STATE: granted, 
AD_ID: granted, 
BIND_GET_INSTALL_REFERRER_SERVICE: granted, 
CAMERA: not_granted, 
DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: granted, 
FOREGROUND_SERVICE: granted, 
INTERNET: granted, 
POST_NOTIFICATIONS: granted, 
READ_CONTACTS: not_granted, 
READ_EXTERNAL_STORAGE: not_granted, 
READ_MEDIA_IMAGES: granted, 
READ_MEDIA_VIDEO: granted, 
RECEIVE: granted, 
RECEIVE_BOOT_COMPLETED: granted, 
RECORD_AUDIO: not_granted, 
VIBRATE: granted, 
WAKE_LOCK: granted, 
WRITE_EXTERNAL_STORAGE: not_granted
}
```

Let me know if there is anything else I can try to get to help investigating this.

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - ~/Developer/th3rdwave/node_modules/.bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/janicduplessis/.rvm/gems/ruby-2.7.4/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    Expo Workflow: bare

**Comment by janicduplessis** [comment]
I will try to get a non-trucated version of the native error stack trace

**Comment by brentvatne** [comment]
@janicduplessis - that would help, thanks!

**Comment by enestatli** [comment]
> @janicduplessis - that would help, thanks!

I am getting the same error only in the Android prod release. I believe expo-image-picker version is not compatible with SDK49. If you need to know proguard is enabled.

"expo": "^49.0.0",
"expo-image-picker": "~14.7.1",
"react-native": "0.72.11",


call to function 'ExponentImagePicker.launchImageLibraryAsync' has been rejected. -> Caused by: The 1st argument cannot be cast to type expo.modules.imagepicker.ImagePickerOptions(received class com.facebook.react.bridge.ReadableNativeMap) -> Caused by: Cannot find type converter for 'kotlin.Pair<kotlin.Int,kotlin.Int>?

**Comment by enestatli** [comment]
Disabling ProGuard resolved the issue, confirming that the problem is related to ProGuard's code obfuscation and optimization processes. This leads me to believe that there might be a specific ProGuard rule missing or an incompatibility issue between the Expo Image Picker module and ProGuard settings required for SDK 49.

I understand that similar issues have been reported but were closed. However, given this finding, I'd like to request further investigation or guidance on specific ProGuard configurations that could prevent this type casting error without disabling ProGuard entirely. Disabling ProGuard is not a viable solution for production builds due to its role in optimizing and protecting the app's code.

Thank you for your time and support.

**Comment by enestatli** [comment]
Upgrading my proguard rules as following fix the issue.

-keep class kotlin.** { *; }
-keep class kotlinx.** { *; }

-keep class kotlin.Pair { *; }

-keep class kotlin.Metadata { *; }
-keepattributes *Annotation*, InnerClasses, Signature, EnclosingMethod, RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keepnames class kotlin.** { *; }
-keepclassmembers class ** {
    @kotlin.Metadata *;
}

**Comment by shubhamdeol** [comment]
@enestatli how you came to conclution that these are the specific classes to exclude?
I am facing similar issue from other expo packages(expo-file-system, expo-local-authentication etc). I am not using `expo-cli`. I am using react native cli with `expo modules`.

**Comment by shubhamdeol** [comment]
https://github.com/expo/expo/issues/28010
This was also similar issue.

**Comment by enestatli** [comment]
> @enestatli how you came to conclution that these are the specific classes to exclude?
> 
> I am facing similar issue from other expo packages(expo-file-system, expo-local-authentication etc). I am not using `expo-cli`. I am using react native cli with `expo modules`.
> 
> 
> 
> 

You can reply with something like:

I found this solution through trial and error. I also set up a bare react native project and then added the expo modules on top of it, without using expo-cli.
