### ISSUE TITLE
Several packages are still affected by CVE-2022-25883

### ISSUE THREAD

**Issue by CtrlZvi** [expo/expo#26154]
### Minimal reproducible example

Run `npm install @expo/image-utils` then `npm audit`

### Summary

It looks like several @expo packages were migrated to this repository _after_ #23113 was merged. Some of the packages (at least [@expo/image-utils](https://github.com/expo/expo/blob/2a96b86e780a2cc6c4cf4d5b38849f108f0517b0/packages/%40expo/image-utils/package.json#L42), [expo-doctor](https://github.com/expo/expo/blob/2a96b86e780a2cc6c4cf4d5b38849f108f0517b0/packages/expo-doctor/package.json#L46), and [install-expo-modules](https://github.com/expo/expo/blob/2a96b86e780a2cc6c4cf4d5b38849f108f0517b0/packages/install-expo-modules/package.json#L51)) are still using versions of semver affected by CVE-2022-25883. They should be updated to at least 7.5.2.

I would submit a PR, but my only exposure to expo is through dependency chains, so I have no understanding required to ensure there isn't some subtle issue caused by the upgrade. This issue was surfaced to me by npm audit.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.5.0 - /usr/local/bin/node
      npm: 10.2.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      react: ^18 => 18.2.0 
      react-dom: ^18 => 18.2.0 
    Expo Workflow: managed
```

**Comment by GaelCO** [comment]
PR https://github.com/expo/expo/pull/26876 was merger in main. I think this issue could be closed

**Comment by rahulshamkuwar** [comment]
While I do see that the PR did update the `semver` versions to be `^7.5.4`, when using `npx create-expo-app@latest --template`, the `semver` version that gets installed is `^6.3.1`. @GaelCO The issue seems to stems from the version of [cacache](https://github.com/expo/expo/blob/9b8d30c9071323d6c6a17bda649b55c0afdeb083/packages/%40expo/cli/package.json#L63C5-L63C26) for the Expo CLI package. Currently, the Expo CLI depends on `^15.3.0` of `cacache`, which depends on `^1.0.0` of `@npmcli/fs`, which depends on `^7.3.5` of `semver`, which is a vulnerable version. The earliest version of `cacache` that updates the minimum version for `semver` is `^17.0.0`. I do not know how `cacache` is used by the CLI, nor do I know what issues would arise from updating, but I think this is where you would want to start looking at...

**Comment by sainjay** [comment]
@CtrlZvi  @GaelCO  @croaky  @expo-bot  @rahulshamkuwar  

i can also see the vulnerability coming from @expo/image-utils : @expo/image-utils@0.4.1 › semver@7.3.2
can we update the semver version to v7.5.2 to fix this>

**Comment by descorp** [comment]
Just to confirm @sainjay point: 
Even tho GitHub's [@expo/image-utils@0.4.0](https://github.com/expo/expo/blob/main/packages/%40expo/image-utils/package.json) updated to `"semver": "^7.6.0"`
NPMJS [@expo/image-utils@0.4.2](https://www.npmjs.com/package/@expo/config-plugins?activeTab=code) still contains `"semver": "7.3.2"`

**Comment by Simek** [comment]
Hello everyone. We have released the new minor version of `@expo/image-utils` package along side SDK 51 release a while ago, which includes [`semver@7.6.0` in the dependencies](https://www.npmjs.com/package/@expo/image-utils/v/0.5.1?activeTab=code). 

Updating package to the latest `0.5.*` release should fix the audit warnings, please LMK if it's fine to mark this issue as resolved.
