### ISSUE TITLE
Execution failed for task ':expo-modules-core:prepareBoost'.

### ISSUE THREAD

**Issue by kenisad5566** [expo/expo#26297]
### Minimal reproducible example

npx react-native run-android

### Summary

Execution failed for task ':expo-modules-core:prepareBoost'. > Could not read node_modules\expo-modules-core\android\build\downloads\boost_1_76_0.tar.gz.    > Not in GZIP format

### Environment

Environment
expo-env-info 1.0.5 environment info:
System:
OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
Shell: 5.1.16 - /bin/bash
Binaries:
Node: 21.4.0 - ~/.nvm/versions/node/v21.4.0/bin/node
Yarn: 1.22.21 - /usr/local/bin/yarn
npm: 10.2.4 - ~/.nvm/versions/node/v21.4.0/bin/npm
npmPackages:
@expo/webpack-config: ^0.17.2 => 0.17.4
expo: ~47.0.12 => 47.0.14
react: 18.1.0 => 18.1.0
react-dom: 18.1.0 => 18.1.0
react-native: 0.70.5 => 0.70.5
react-native-web: ~0.18.9 => 0.18.12
Expo Workflow: managed

**Comment by Marcuspo** [comment]
same

**Comment by Ryu0408** [comment]
same...

**Comment by wodin** [comment]
Boost is distributed by JFrog. JFrog had some issues a couple of weeks ago and again a couple of days ago.

In Expo SDK 47 and lower, expo-modules-core downloads Boost during the build process. Expo SDK 48 and above no longer do this. So one workaround is to upgrade to a later Expo SDK version.
If you can't upgrade now, you can use patch-package to change the URL. See https://github.com/expo/expo/issues/26302#issuecomment-1881188095

**Comment by AteebNoOne** [comment]
# Fixing Expo Boost Download Issue with a Patch Script

## Overview
If you're facing issues related to Boost archive download errors while running your Expo project, here's an easier approach to fix it.

## Installation
First, install the required dependency:

```sh
npx expo install fs-extra
```

## Creating the Patch File
Create a file named `patches.ts` in the root of your project and add the following code:

```ts
const fs = require("fs-extra");
const path = require("path");

const FILE_TO_DELETE = "./node_modules/expo-modules-core/android/build/downloads/boost_1_76_0.tar.gz";
const FILES_TO_MODIFY = [
  { path: "./node_modules/react-native/ReactAndroid/build.gradle" },
  { path: "./node_modules/expo-modules-core/android/build.gradle" },
];

const OLD_URL = `https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz`;
const NEW_URL = `https://archives.boost.io/release/${BOOST_VERSION.replace("_", ".")}/source/boost_${BOOST_VERSION}.tar.gz`;

const patch = () => {
  // Delete the file
  if (fs.existsSync(FILE_TO_DELETE)) {
    fs.removeSync(FILE_TO_DELETE);
    console.log(`Deleted file: ${FILE_TO_DELETE}`);
  } else {
    console.log(`File not found: ${FILE_TO_DELETE}`);
  }

  FILES_TO_MODIFY.forEach(({ path: filePath }) => {
    if (fs.existsSync(filePath)) {
      const fileContent = fs.readFileSync(filePath, "utf8");
      const updatedContent = fileContent.replace(OLD_URL, NEW_URL);

      if (fileContent !== updatedContent) {
        fs.writeFileSync(filePath, updatedContent, "utf8");
        console.log(`Updated file: ${filePath}`);
      } else {
        console.log(`No changes made in: ${filePath}`);
      }
    } else {
      console.log(`File not found: ${filePath}`);
    }
  });
};

patch();
```

## Modifying `package.json`
Next, update your `package.json` scripts to run the patch automatically before building your project:

```json
"scripts": {
  "start": "npx expo start",
  "android": "node ./patches.ts && npx expo run:android",
  "ios": "node ./patches.ts && expo run:ios"
}
```

This ensures that every time you run the project, the necessary patches are applied automatically, preventing future issues.

## Explanation of `npx expo` Commands
Expo provides two ways to run commands:

1. **`npx expo <command>` (Direct Command Execution)**
   - This method is useful when you don’t have Expo CLI installed globally.
   - It fetches and runs the latest Expo CLI version every time.
   - Ideal for one-time or occasional use, ensuring you always get the latest version.

2. **`expo <command>` (Installed CLI Usage)**
   - Requires Expo CLI to be installed globally (`npm install -g expo-cli`).
   - Runs faster since it doesn’t need to download the CLI every time.
   - Suitable for developers who frequently work with Expo projects.

### When to Use Which?
- Use `npx expo` if you don’t want to install Expo CLI globally or need the latest CLI version.
- Use `expo` if you have it installed globally and want faster execution without downloading the CLI every time.

By following these steps, your Expo project should now work smoothly without encountering Boost-related errors!
