### ISSUE TITLE
expo-auth-session promptAsync stalls when iOS app is reopened

### ISSUE THREAD

**Issue by isakstenstrom** [expo/expo#26303]
### Minimal reproducible example

https://github.com/isakstenstrom/expo-auth-debug

### Summary

I have an Expo app that uses Azure and `expo-auth-session` for authentication. The authentication is automatic, meaning that when the user opens the app, they are immediately shown the login window, without having to press a button. This is done by placing the call to `promptAsync()` inside of a `useEffect()`. On Android and when using Expo Go, everything is working as expected, but when running a prod-build on iOS the authentication is not working.

The first time that you open the app everything works as it should, but when the app is opened for the second time (and not just sent to the background and opened but restarted completely) the popup asking to open the login webpage never appears. The call to `promptAsync()` is called, but it seemingly stalls. It also blocks any new calls of `promptAsync()` and it isn't cancelled by calling `dismiss()`.

The only way around this that I have found is to add a 1 second delay before the call to `promptAsync()` but I don't view that as a solution to the problem.

How to reproduce with the example:
1. Replace the placeholder tenant ID and client ID in App.tsx. (I can't share my Azure tenant, unfortunately)
2. Build the app somehow. I have used EAS.
3. Install the app on an iPhone or simulator.
4. Open the app and login
5. Force-close the app
6. Open the app again. For me the popup asking to open the login page never appears.

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.18.0 - ~\.nvm\versions\node\v18.18.0\bin\node.EXE
      npm: 9.8.1 - ~\.nvm\versions\node\v18.18.0\bin\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10811636
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

**Comment by Daniel-Cross** [comment]
We're have exactly the same use case and issue. 

+1 for this.

**Comment by RikKeistoer** [comment]
I am also facing the exact same issue. Thanks @isakstenstrom for the delay-tip. That seems to work.

To summarize, this **DOES** work:
```
const request = await loadAsync(params, discovery);
await new Promise((resolve) => setTimeout(resolve, 1000));
const promptRes = await request.promptAsync();
```

This does **NOT** work:
```
const request = await loadAsync(params, discovery);
const promptRes = await request.promptAsync();
```

**Comment by sgadboisuv** [comment]
I'm having a very similar issue with the same behavior where it works on Android and in debug but not on production build for iOS and figured out the same workaround as well. The only difference is in my case I'm calling a logout prompt followed by a login when the logout prompt returns, and the same happens where the second prompt seems to stall.

**Comment by dconlisk** [comment]
We've also had similar issues, where the browser was not always opening for authentication on iOS devices. This happens from the splash screen of our app: if the user does not have tokens stored then they need to authenticate in a browser. This issue was causing havoc with our BrowserStack tests which were totally inconsistent.

Adding the delay has worked for us, and our app is behaving consistently now after a couple of weeks of trying to figure out the issue. Thanks @isakstenstrom and @RikKeistoer for getting us to a solution, even if it does seem like a hack. It would be nice to see a proper fix for the issue released.

**Comment by VilleMiekkoja** [comment]
Same happening for us. The promptAsync stalls, even it is called with valid data. It's like if the popup would be open, and waiting for user's input. But nothing is visible still.

**Comment by CodyPredy** [comment]
@VilleMiekkoja Ran into the same issue. Had to call the dismiss(); callback and add an additional loading state while the user is waiting but the above fix works but it not ideal.
```typescript
setLoginPending(true);
dismiss();
await new Promise(resolve => setTimeout(resolve, 1000));
```

Perhaps I'm less familiar with `expo-auth-session` but from what I've noticed:
* having the _authLock to prevent multiple sessions (eg. 'Attempted to call AuthSession.startAsync multiple times while already active. Only one AuthSession can be active at any given time.') is preventing any additional prompts from triggering after it iOS simply sides it when moving away from the app or locking the device.

**Comment by LukeHalby** [comment]
I encountered the same issue here and while the delay solutions also worked for me, ensuring that `AppState.currentState` was set to `active` seemed to work even better.

I needed to authenticate a user immediately if they responded to a notification (and were unauthenticated), this is effectively my working implementation:

```ts
React.useEffect(() => {
  if (appState !== 'active') return;
  if (!isValidRequest(request)) return;
  promptAsync().then((response) => handleAuthenticationResponse(response));
}, [request, appState])
```

Where `appState` is a value provided by this hook:

```ts
// useAppState.tsx

import { useCallback, useEffect, useState } from 'react';
import { NativeEventSubscription, AppState, AppStateStatus } from 'react-native';

export default function useAppState() {
  const [appState, setAppState] = useState<AppStateStatus>(AppState.currentState);

  const handleAppStateChange = useCallback(async (nextAppState: AppStateStatus) => {
    setAppState(nextAppState);
  }, [setAppState]);

  useEffect(() => {
    let eventListener: NativeEventSubscription;
    eventListener = AppState.addEventListener('change', handleAppStateChange);

    return () => {
      eventListener && eventListener.remove();
    };
  }, [handleAppStateChange]);

  return appState;
}
```
(Credit to [this](https://miknoup.medium.com/mastering-app-state-in-react-native-with-useappstatecheck-1e00cd5d35d3) Medium article for the original hook implementation that I modified)

No idea if this is the true root cause of everyone's issues, but perhaps worth mentioning in the docs.
