### ISSUE TITLE
expo-notifications getExpoPushTokenAsync SERVICE NOTAVAILABLE

### ISSUE THREAD

**Issue by lengziyu** [expo/expo#26335]
### Minimal reproducible example

          const token = await Notifications.getExpoPushTokenAsync({             projectId: Constants?.expoConfig?.extra.eas.projectId           })

### Summary

Hello, I used message push to get Notifications.getExpoPushTokenAsync and reported an error. I'm from Chinese Mainland. I guess the firewall in Chinese Mainland cannot connect with Google FCM. Is there any other way for Chinese developers?```[Error: Fetching the token failed: java.util.conc"ent.ExecutionException: java,io.IOException: SERVICE NOTAVAILABLE]```
![image](https://github.com/expo/expo/assets/9267469/1b72735f-46fc-4642-ac33-5c168b6aaf41)

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.18.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Expo Workflow: managed
expo 4.9.0

**Comment by yinhuiyang** [comment]
在中国无法使用FCM,我这边的使用的解决方案是使用getui来实现安卓的消息推送。需要使用prebuild来构建安卓包。如果需要帮助的话可以联系我。

**Comment by christopherwalter** [comment]
Hi @lengziyu, `SERVICE_NOT_AVAILABLE` likely reflects an issue at the network level as opposed to the service level (i.e. FCM servers) or client level (i.e. a problem/bug in the code running on Android). So I'd expect to see this error when the network itself is unavailable, or when FCM servers cannot be reached (e.g. because of the mainland firewall). 

Unfortunately I don't have a workaround to suggest. If you do end up finding a solution here, please let us know so we can communicate to future users who run into this problem when setting this up inside mainland China.
