### ISSUE TITLE
Cannot find native module 'ExpoScreenOrientation'.

### ISSUE THREAD

**Issue by Snouzy** [expo/expo#26334]
### Summary

When I try to install `expo-screen-orientation`, the build (only on iOS) is not working and tell me `Cannot find native module 'ExpoScreenOrientation', js engine: hermes`

### What platform(s) does this occur on?

iOS

### SDK Version

49

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v12.22.12/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /Users/mathiasbradiceanu/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 33.0.0
        System Images: android-33 | Google Play ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11076708
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: bare
```

### Minimal reproducible example

i tried : 
```
npx expo install expo-screen-orientation
```
and then
```
cd ios && pod update && pod install --verbose && cd ..
```
and then
```
npx react-native run-ios --scheme=myApp-prod --simulator='iPhone SE (2nd generation)'
```

And i have this message : 
```
 WARN  The "EXNativeModulesProxy" native module is not exported through NativeModules; verify that expo-modules-core's native code is linked properly
 ERROR  Error: Cannot find native module 'ExpoScreenOrientation', js engine: hermes
 LOG  Running "myApp" with {"rootTag":1,"initialProps":{}}
 ERROR  Invariant Violation: "myApp" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

![screenshot-2024-01-09_23h14m19s](https://github.com/expo/expo/assets/32961176/a6cf65d2-7c7b-4127-b019-bbde3c194630)

**Comment by behenate** [comment]
@Snouzy Hi, I can't reproduce the issue with a fresh SDK49 project, but the warning suggests that expo modules might not be linked properly in your project. See https://docs.expo.dev/bare/installing-expo-modules/

If this doesn't help please provide a minimal reproducible example project so that we can look deeper into the issue 😃

**Comment by Snouzy** [comment]
@ansmlc i loosed too much time on that, so i ended up using [react-native-orientation-locker](https://github.com/wonday/react-native-orientation-locker)

**Comment by legubiao** [comment]
I encountered the same issue for `expo-screen-orientation`, `Cannot find native module 'ExpoScreenOrientation'`. In My project I used expo-dev-client to build development build app and I didn't used expo-go app, and the solution is build a new development build after adding `plugins` item in the `app.json`. I guess the problem is because in my old development build it didn't have native module for `expo-screen-orientation` but in new development build it contained.
