### ISSUE TITLE
[SDK 50][expo-updates][iOS][prebuild] EXUpdates/AppController.swift:151: Assertion failed: AppController.sharedInstace was called before the module was initialized

### ISSUE THREAD

**Issue by MAgungHKM** [expo/expo#26417]
### Minimal reproducible example

https://github.com/MAgungHKM/expo-updates-intune-crash

### Summary

I'm not sure where I'm supposed to report this. But I'll try to report here first because the error message is related to `expo-updates`, and the issue is resolved after uninstalling it.

The app crashes on startup after setting up [Microsoft Intune SDK](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios) wrapper. We were able to use this wrapper just fine in previous SDKs, the setup guide can be found [here](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-ios-phase3). Here is the logs that I manage to collect when launching the app from Xcode:

```
container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
A NULL string is not a valid group container identifier.
container_create_or_lookup_app_group_path_by_app_group_identifier: client sent invalid parameters
Current file index 0
nw_proxy_resolver_create_parsed_array [C1.1 proxy pac] Evaluation error: NSURLErrorDomain: -1003
nw_proxy_resolver_create_parsed_array [C1.1 proxy pac] Evaluation error: NSURLErrorDomain: -1003
nw_proxy_resolver_create_parsed_array [C1.1 proxy pac] Evaluation error: NSURLErrorDomain: -1003
nw_proxy_resolver_create_parsed_array [C2.1 proxy pac] Evaluation error: NSURLErrorDomain: -1003
nw_proxy_resolver_create_parsed_array [C2.1 proxy pac] Evaluation error: NSURLErrorDomain: -1003
nw_proxy_resolver_create_parsed_array [C2.1 proxy pac] Evaluation error: NSURLErrorDomain: -1003
Running application main ({
    initialProps =     {
    };
    rootTag = 1;
})
🟢 Registering module 'ExponentConstants'
🟢 Registering module 'EASClient'
🟢 Registering module 'ExponentFileSystem'
🟢 Registering module 'ExpoKeepAwake'
🟢 Registering module 'ExpoUpdates'
🟢 Registering module 'NativeModulesProxy'
EXUpdates/AppController.swift:151: Assertion failed: AppController.sharedInstace was called before the module was initialized
```

My assumptions are that there are some changes to how the modules were initialized and that these changes are not compatible with the Intune wrapper. I hope you guys can take a look at this a little bit, since you guys probably know the stuff that has been changed. In the meantime, I'll report another issue to the Intune repo as well.

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/n/bin/node
      npm: 9.8.1 - ~/n/bin/npm
      Watchman: 20230625.125958.0 - /Users/e127558/.local/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /Users/e127558/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
      Android SDK:
        API Levels: 28, 29, 30, 31, 32, 33, 34
        Build Tools: 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom, android-34 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      expo: ~50.0.0-preview.9 => 50.0.0-preview.10 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
    npmGlobalPackages:
      expo-cli: 6.3.9
    Expo Workflow: bare
```

**Comment by wschurman** [comment]
@MAgungHKM - I cloned the repo and ran in Debug and Release profile. Wasn't able to reproduce the crash. Is it fully set up to cause the crash? If not, please update the repo to the state at which running prebuild, pod install, and then running it in xcode causes the crash.

**Comment by MAgungHKM** [comment]
@wschurman I see, that's weird. I already fully set it up to crash on both my and my colleague's devices; all we need to do is `npm install` and then `npx expo run:ios`. 

Are you able to get to the `Open up App.js to start working on your app!` screen? It doesn't seem like the app is crashing because Xcode can catch and stop it right before it does. 

Also, can you tell me which Xcode version and iOS version you are using? It might have something to do with the crash as well.

I noticed just now that when I tried to run it from Xcode using the release scheme, it didn't crash either, and I was able to get to the `Open up App.js to start working on your app!` screen.

**Comment by wschurman** [comment]
Ah, it's probably because I ran prebuild. Sorry, will try again without prebuild.

**Comment by wschurman** [comment]
Alright, was able to hit the crash in the project, thanks. Looking into it now.

**Comment by wschurman** [comment]
Comparing this to a blank app with expo-updates installed, the point of divergence is in expo-modules-core in the mechanism that forwards selectors. In particular `[EXAppDelegateWrapper forwardingTargetForSelector]` is called in the blank app but not in the demo repo, which causes `EXExpoAppDelegate` not to be called and the updates controller not to be initialized (amongst other app delegate subscribers, so other libraries break as well).

My guess is that something in the Intune SDK intercepts or prevents `forwardingTargetForSelector` from being called, but since it's closed source I can't be sure.

Passing this over to @tsapeta who might know how to debug further, but since it's closed source I can't be sure we'll be able to get further. The point I reached was adding a breakpoint at `forwardingTargetForSelector` and seeing it gets hit in a blank app but not in this repro.

To set up the repro:
1. Clone
2. pod install
3. open in xcode
4. build in debug mode

**Comment by wschurman** [comment]
Looking slightly deeper, it does look like `IntuneMAMSwift` intercepts the app delegate somehow (closed source so can't really tell how, but the stack traces for App Delegate invocations comes from `IntuneMAMSwift`), so it is incompatible with the way `expo-modules-core` does app delegate intercepting. Unfortunately, because it's closed source we can't offer too many suggestions about how to proceed.

Some options:
- Manually pass all relevant selectors from your AppDelegate instance to `EXExpoAppDelegate` (essentially what `EXAppDelegateWrapper` does). I can't know for sure whether this will work though since it's still unclear how MS library does their forwarding.
- File an issue for the intune library indicating that it is not compatible with expo-modules-core app delegate.

Hope this helps.

**Comment by MAgungHKM** [comment]
@wschurman Thank you so much for looking into this and sharing your insights as well! 
I'll discuss this with my colleagues whether we will raise a ticket to MS or try to resolve this ourselves.
