### ISSUE TITLE
[SDK 50] Unable to access bundled media assets

### ISSUE THREAD

**Issue by mihailapuste** [expo/expo#26474]
### Minimal reproducible example

https://github.com/mihailapuste/ExpoAssetTestApp

### Summary

I'm wondering if there's been any progress on resolving the issue with bundled assets in Expo SDK 50. In my bare React Native project, I'm currently using [Expo 50.0.0-alpha.6](https://www.npmjs.com/package/expo/v/50.0.0-alpha.6) and running RN version `0.72.9` without any issues when playing local audio and video files.

However, after upgrading to [Expo 50.0.0-preview.11](https://www.npmjs.com/package/expo/v/50.0.0-preview.11), I'm facing an issue where bundled assets, particularly local audio and video files, are missing, leading to errors. I've only tested this on `iOS` so far.

```bash
Error: Module "268" is missing from the asset registry
    at fromModule ...
```

Could anyone please confirm if this is indeed the case? Specifically, will bare React Native apps using Expo SDK 50 and beyond no longer support asset files included in the bundle?

This issue is posted in relation to https://github.com/expo/expo/issues/26195#issuecomment-1895475086 and in response to @wschurman https://github.com/expo/expo/issues/26195#issuecomment-1896278011

In my bare react native [example app](https://github.com/mihailapuste/ExpoAssetTestApp), I demo the expo-av Video component working with both a remote and bundled asset. The remote source is selected by default, but you can toggle to the bundled asset and it will crash.

For comparison, I've also added the video component from [react-native-video](https://github.com/react-native-video/react-native-video) and you can also toggle the remote and bundled source to see no crash occurs. 

Thank you all for your help!

### Environment

```bash
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.1.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.0 - /opt/homebrew/bin/npm
      Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/mihailapuste/.rvm/gems/ruby-3.1.2/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
```

**Comment by wschurman** [comment]
Hi @mihailapuste - thanks for separating out this into this new issue. We noticed a couple things:
- This uses react native `0.72.9` while SDK 50 uses (and is tested with) react native 0.73. Upgrading may help.
- It looks like the cause of the missing assets may be a custom metro config that doesn't make use of `@expo/metro-config`: https://docs.expo.dev/guides/customizing-metro/ . I'm not quite as familiar with this part of our stack, but it stands out as a likely possibility that this is where the issue is.

I'm curious what the steps you used to generate this repro repo were?

**Comment by mihailapuste** [comment]
Thanks for the quick reply @wschurman 

I tried both suggestions, and upgrading to react native latest 73.2 seems to have solved this issue.

> * This uses react native `0.72.9` while SDK 50 uses (and is tested with) react native 0.73. Upgrading may help.


I've repro'd the same project in a different repo here: https://github.com/mihailapuste/Rn73ExpoMediaAssetTestApp/blob/main/App.tsx demonstrating that the same code using the local asset and expo 50 & latest expo av works on react native 73.2.

---

> I'm curious what the steps you used to generate this repro repo were?


I'm currently working on an app that is using both the audio player and video player from expo-av. I was forced to upgrade to the beta version as I was faced with https://github.com/expo/expo/issues/26149 when using react native 72.5 and expo sdk 49. Upgrading to sdk 50 beta 6 solved the issue.

But now that the stable version has been release, we would like to upgrade to it. However during the upgrade to sdk 50 preview 11, I noticed that the video and audio files that were being loaded from our bundled assets were crashing.

I still hope that expo sdk 50 will support bundled assets for rn versions 72.X.


Hope this helps

**Comment by wschurman** [comment]
Glad to hear that fixed it! The expo SDK and portions thereof are tested and support one RN version, and while pieces of the SDK may work with other RN versions we don’t officially support it. RN and expo should be updated in tandem as they're closely coupled.

**Comment by gretzky** [comment]
I'm seeing this exact issue (along with the linked #26195) with the latest release of SDK 50 (`50.0.2`) and RN 0.73.2. An error is throwing for fonts and images that should be supported by default by Metro.

Running `npx expo export` fails and throws `Unable to resolve module @react-native/assets-registry/registry`. If I download that package, export works, as does a local build. But when running the build, fonts/images aren't loaded and throw `Error: Module "1" is missing from the asset registry`.

Any help is appreciated, it doesn't seem like this issue was resolved 🙏

**Comment by wschurman** [comment]
@gretzky - if you could file a separate issue with it's own repro steps, that'd be the best way for us to investigate and address this. That way we can be sure we aren't conflating two separate issues.
