### ISSUE TITLE
requireAuthentication not working with setItemAsync on Android with Face recognition

### ISSUE THREAD

**Issue by richmondp** [expo/expo#26615]
### Minimal reproducible example

https://snack.expo.dev/@prichmond/thankful-blue-mixed-nuts

### Summary

I am attempting to save a value using `SecureStore.setItemAsync` with the option `{requireAuthentication: true}` but I am getting mixed results based on platform and biometric type. 

Using a physical Samsun Galaxy device running Android v14, I am able to successfully save a value when I have a Fingerprint registered. However, if I only have Face Recognition registered. The `setItemAsync` call throws the exception `ERR_SECURESTORE_AUTH_NOT_CONFIGURED No biometrics are currently enrolled`. However, using `isEnrolledAsync` from `expo-local-authentication` it detects that I am enrolled for biometrics. I would expect that it should work the same regardless of whether I am using Fingerprint or Face Recognition. 

I believe the Face Recognition is setup correctly, as I am able to use it to unlock my phone. It also successfully works if I use `authenticateAsync` from `expo-local-authentication`. 

The same error also occurs when retrieving a value using `SecureStore.getItemAsync`. 

I am not noticing any errors on iOS. 

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - ~/Library/Caches/fnm_multishells/95796_1705881749006/bin/node
      Yarn: 1.22.21 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - ~/Library/Caches/fnm_multishells/95796_1705881749006/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /Users/peterrichmond/.rvm/gems/ruby-3.0.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.21 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
      react-native-web: ~0.18.12 => 0.18.12 
    Expo Workflow: managed

**Comment by richmondp** [comment]
I have tested the snack example on the following devices with mixed results

* Samsung Galaxy (Android 14) - **Fails**
* Pixel 3 (Android 13) - **Works**
* Samsung Galaxy (Android 12) - **Fails**

**Comment by mbyrne00** [comment]
To add to the comment above, the Pixel 4 does not have a fingerprint sensor so that seems to be the differentiator in these tests. Android phones with fingerprint capability that have face recognition enabled seem to fail.

**Comment by behenate** [comment]
@mbyrne00 Is right. The difference comes from strong biometrics requirement. This is because Android's keystore [only allows strong biometric authentication](https://developer.android.com/privacy-and-security/keystore#:~:text=For%20each%20key%20that%20you%20create%2C%20you%20can%20choose%20to%20support%20a%20strong%20biometric%20credential%2C%20a%20lock%20screen%20credential%2C%20or%20both%20types%20of%20credentials.%20To%20determine%20whether%20the%20user%20has%20set%20up%20the%20credentials%20that%20your%20app%27s%20key%20relies%20on%2C%20call%20canAuthenticate().). 
Therefore we can't add configuration option that would also allow for weak biometrics (such as samsung's face scanning)

Regarding the device inconsistencies in `expo-secure-store`, Pixel 4 uses something similar to Apple's FaceID (it has an actual 3D face-scanning sensor), which means that it is a lot more secure than 2D image-based recognition used by the Samsungs and is treated as strong by Android.

I will try create a PR which solves the issue of `expo-local-authentication` not differentiating between strong and weak biometrics soon 😄 

I'm closing this issue for now, because we won't be able to make `expo-secure-store` accept weak biometrics without using some workarounds due to Android's security policy (if it's possible at all).

**Comment by richmondp** [comment]
Thanks for the details explanation @behenate.

I have created an [issue](https://github.com/expo/expo/issues/26777) related to being able to determine between strong and weak biometrics to help track the issue. 

And for anyone following this thread and has similar issues, I have also created[ this issue](https://github.com/expo/expo/issues/26776) to be able to determine when a user has failed Face Recognition on Android with too many attempts.
