### ISSUE TITLE
MapView expo detach

### ISSUE THREAD

**Issue by babelom** [expo/expo#2685]
### Environment

Expo CLI 2.2.6 environment info:
    System:
      OS: macOS 10.14.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^30.0.1 => 30.0.1 
      react: 16.3.1 => 16.3.1 
      react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4 
      react-navigation: ^1.5.8 => 1.5.8 
    npmGlobalPackages:
      expo-cli: 2.2.6

  Diagnostics report:
    https://exp-xde-diagnostics.s3.amazonaws.com/django-c0b807d1-1018-4d15-8cbd-5868554c4ae3.tar.gz

IOS

### Steps to Reproduce

I've just detach my project to install it on my device with Xcode.
In this project I import and use the MapView component from expo.
It works when I use the application "expo" on the Appstore, I'm able to see my map.
But now when I build it (with success) and install it from Xcode to my device, the application crash without error and not showing my map anymore... 

1.Detach to expokit
2.Open and build it with Xcode
3.Open the app on the device

### Expected Behavior

Possibility to see and use my app without it crash ...

### Actual Behavior

When I launch the app on my device, it crash when I go on the screen that contain the MapView component import from expo.
I have this error in xcode: 

The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'Google-Maps-iOS-Utils')

 Thanks for helping us help you!

**Comment by sjchmiela** [comment]
Hey, @babelom!

Judging by the error message

> The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'Google-Maps-iOS-Utils')

the problem is that your Xcode project has deployment target set to 7.0, whereas `Google-Maps-iOS-Utils` dependency that the native project uses has deployment target set to 8.0.

Deployment target is in short the lowest iOS version that the project is intended to be able to run on. If the dependency cannot handle iOS 7 and your projects states that it does, it sure looks like an unstable situation! 😉 

My suggestion would be to bump the deployment target of your project to iOS 8.0. Expo recently dropped support even for iOS 9.0 (if your project is ejected it doesn't concern you until you upgrade your project to at least SDK31).

![Change deployment target](https://lab.sonicmoov.com/files/2016/02/lab_debug_3.png)

Let me know if this fixes your issue! 🙂

**Comment by sjchmiela** [comment]
Glad to hear that, always happy to help! 🙂
