### ISSUE TITLE
After upgrading expo version to 50, i got error: error: ../../node_modules/expo-router/_ctx.ios.js: ../../node_modules/expo-router/_ctx.ios.js:Invalid call at line <unknown>: undefined First argument of `require.context` should be a string denoting the directory to require.

### ISSUE THREAD

**Issue by anhphamminh** [expo/expo#26927]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by edmbn** [comment]
@anhphamminh did you find anything related? Because I can't see how to solve this issue. Thanks.

**Comment by edmbn** [comment]
In my case it was because I was installing the dependency "babel-preset-expo" inside my package.json. It is not needed so remove it in case you are installing it too.

**Comment by gaishimo** [comment]
It seems that this happens when "transform-inline-environment-variables" babel plugin is used in babel.config.  Removing this fixes the problem that process.env.EXPO_ROUTER_APP_ROOT is not set.

```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ["transform-inline-environment-variables"]
  };
};
```

**Comment by kav** [comment]
Just a heads up, will try to remember to update docs but you can disable transform of the variable causing the issue with:
```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: ['transform-inline-environment-variables', { exclude: ['EXPO_ROUTER_APP_ROOT'] }],
  };
};
```

**Comment by zgid123** [comment]
for my case, I am using yarn 4 and expo 51.0.2, at first, my monorepo app won't have `node_modules` inside whenever I run `yarn install`. But when I add `zustand` to a mono package, my app project will have a `node_modules` folder, and this issue will happen. So I guess whenever I add any package that will force yarn to create `node_modules` folder to the expo app, the problem will occur. I don't know how to fix this one

**Comment by douglowder** [comment]
I found that in fact you need to _include_ the expo-router env variables to avoid the error, as below:

```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: [
      [
        "transform-inline-environment-variables",
        {
          include: [
            "EXPO_ROUTER_APP_ROOT",
            "EXPO_ROUTER_IMPORT_MODE",
          ],
        },
      ],
      [
        "babel-plugin-module-resolver",
        {
          root: ["./"],
          alias: {
            "~": "./",
          },
        },
      ],
      "react-native-reanimated/plugin",
    ],
  };
};
```

**Comment by kav** [comment]
@zgid123 what is the contents of your `babel.config.js` file. If it has 'transform-inline-environment-variables' you will need to use the exclusion above.

**Comment by psongers** [comment]
Hi everyone I was experiencing this issue as well. I was not using `transform-inline-environment-variables` in `babel.config.js`. My problem was in a monorepo similar to #27299  (threads locked so cannot comment) even though it is set up as described in https://docs.expo.dev/guides/monorepos/

The issue is on this line here of the `babel-preset-expo` library. 
https://github.com/expo/expo/blob/41c96200719e27cdcd7393503c0a3d70db0aae27/packages/babel-preset-expo/src/index.ts#L275
The `hasModule` check doesn't check across different `node_modules` folders. It seems to only work if `expo-router` lives in the same `node_modules` as `babel-preset-expo` see its implementation here: 
https://github.com/expo/expo/blob/41c96200719e27cdcd7393503c0a3d70db0aae27/packages/babel-preset-expo/build/common.js#L8

The way I fixed this is to set `"hoistingLimits": "workspaces"` in package.json to force `babel-preset-expo` to always be installed next to `expo-router` Of course unfortunately this means we are not getting the benefit of sharing dependencies across yarn workspaces.

**Comment by zgid123** [comment]
I created a repo for expo monorepo: https://github.com/zgid123/react-native-expo-monorepo-boilerplate

In my real project, I am using expo 51.0.2, I faced this issue, and I need to create a dummy project, and then try to install some packages that I installed for other projects. If yarn does not create folder node_modules inside the expo project, then I can run project without this issue.

Now for this boilerplate, I am using `51.0.14`, I don't face this issue anymore without dummy project. Maybe the setup is still simple. I will try to update my real project like the boilerplate later when it is released to check the result
