### ISSUE TITLE
Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by silentcloud** [expo/expo#270]
My app is everything ok in  the development environment, the error occurred after publishing the app.

<img src="https://user-images.githubusercontent.com/1698185/27114713-0adea062-50f8-11e7-98bc-30fdc4f289d0.png" width="280" />

I try to use `create-react-native-app` and  `expo to create new project`, both have this error.

app code: https://github.com/ant-design/antd-mobile-samples/tree/master/antm-expo

**Comment by brentvatne** [comment]
hi there! this usually means that there is some bug in your app that only surfaces in production. i'll clone the repo and give it a try

**Comment by brentvatne** [comment]
hi @silentcloud - the problem was that the "antd-mobile" library was only imported in babelrc in development. this fixed the problem for me:

```
{
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        ["import", { "libraryName": "antd-mobile" }]
      ]
    },
    "production": {
      "plugins": [
        ["import", { "libraryName": "antd-mobile" }]
      ]
    }
  }
}
```

**Comment by silentcloud** [comment]
@brentvatne Thanks very much !

**Comment by brentvatne** [comment]
the error message is a little unclear, yeah :( it basically happens if the app fails to start

**Comment by donedgardo** [comment]
Hi, I'm having the same issue. How should I go about debugging. It appears once published and in the standalone app, not in development. @brentvatne

**Comment by JulianKingman** [comment]
ditto

**Comment by mrtnzlml** [comment]
I have the same problem and I don't know where to start with debugging since the only help is:

> "Module AppRegistry is not a registered callable module (calling runApplication)" (code 2)

How should I fix it (or debug it)? Thank you... 🙂

**Comment by donedgardo** [comment]
@mrtnzlml I debugged using an android device connected to my computer and looking at its logcat error log.

It turned out to be a native code error 'lottie' in this case. I fixed the issue after debugging this way.

**Comment by suhabaobaid** [comment]
@donedgardo is there a keyword indicating such errors?...I am looking at the logical but hard to filter down the meaningful logs.

**Comment by coderLius** [comment]
Hi, I have the same problem as @silentcloud , and i can not solve it, hope you can help me , thanks!
code URL: [https://github.com/coderLius/rnx-ui-expo/tree/master/rnx-ui](https://github.com/coderLius/rnx-ui-expo/tree/master/rnx-ui)

**Comment by suhabaobaid** [comment]
@coderLius Hey I just ran your code, the trick here is to turn off development mode when running with expo so you get to see the errors. Run it through a simulator or a physical phone and it will show you where is the problem. Your code has `undefined Is not an object (evaluating _reactNtive.View.propTypes.style)` => this is because View.propTypes is deprecated, just replace it with ViewPropTypes in your code or packages (or you can update them if they have fixed this issue in their repos already) 
You might find this link useful: https://github.com/facebook/react-native/issues/14032

**Comment by coderLius** [comment]
thanks very very much ~

**Comment by julesmoretti** [comment]
Same issue here:
```Error: Module AppRegistry is not a registered callable module (calling runApplication) (code 2)`

**Comment by loganwedwards** [comment]
I had this issue with SDK 25 (upgrading from SDK 19, yikes!) and my issue turned out to be an invalid `app.json` format. Specifically, I removed the root `splash` object into the respective `ios` and `android` objects.

**Comment by terribleben** [comment]
Warning to anybody finding this thread:

"Module AppRegistry is not a registered callable module" doesn't tell us anything about your error. It is a downstream symptom in all React Native projects (at time of writing) indicating "your app had some other error before it could finish loading." You are unlikely to find a useful solution to your problem in this thread because everybody here is posting about different issues.

Recommended steps:

- Check your packager logs for any other errors that may have happened in advance of "Module AppRegistry is not a registered callable module"
- If the error only happens after publishing, try running your app with dev=false and minify=true to get a JS bundle closer to what you'd see in production
- Open a new issue with more information (because unfortunately we won't be able to help much if we only see this message alone)
