### ISSUE TITLE
`onBarCodeScanned` result doesn't contain bounds of the barcodes

### ISSUE THREAD

**Issue by patrickklze** [expo/expo#2700]
<img width="393" alt="screenshot 2018-11-13 at 8 50 30 pm" src="https://user-images.githubusercontent.com/31715990/48414479-ce250780-e785-11e8-8ac7-073173716089.png">

![img_5036](https://user-images.githubusercontent.com/31715990/48414401-9322d400-e785-11e8-85dc-599908f14c62.PNG)

**Comment by sjchmiela** [comment]
Hey, @patrickklze! The issue you've posted isn't totally clear, but I think I know what's the problem. 🙂

`Camera` component available in Expo isn't the same component that `react-native-camera` exports. That's why using the same code that you could use with `react-native-camera` won't always work in Expo environment. Here, as I understand it, you're trying to use `bounds` property on bar code scanning result, which `react-native-camera` adds ([see documentation](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#onbarcoderead)). Unfortunately, Expo's Camera calls `onBarCodeRead` function (only) with `type` and `data` properties ([see documentation, search for `onBarCodeRead`](https://docs.expo.io/versions/v31.0.0/sdk/camera#props)).

If my intuition is right, a simple workaround for you would be to not use `bounds` property (and not be able to highlight the barcode position 🤷‍♂️). If that won't work (you really need to do so), you could:
- eject to [ExpoKit](https://docs.expo.io/versions/v31.0.0/expokit/) to be able to add `react-native-camera`'s native module to your project. This, however, will get rid of some of the advantages Expo gives you.
- submit a pull request to Expo, which would add `bounds` to:
  1. [`BarCodeScannerResult.java`](https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner-interface/android/src/main/java/expo/interfaces/barcodescanner/BarCodeScannerResult.java),
  2. handling result points in [`ZXingBarCodeScanner.java`](https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/ZxingBarCodeScanner.java#L69)
  3. handling corner points in [`GMVBarCodeScanner.java`](https://github.com/expo/expo/blob/master/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/scanners/GMVBarCodeScanner.java#L62)
  4. serializing those bounds saved in `BarCodeScannerResult` in [`BarCodeScannedEvent.java`](https://github.com/expo/expo/blob/d85cf10adb8ce2f381b3492e35857c200fb764e7/packages/expo-barcode-scanner/android/src/main/java/expo/modules/barcodescanner/BarCodeScannedEvent.java#L51-L56)
  5. (optional step) add handling to iOS side too. 😃 
- create a feature request at https://expo.canny.io/ describing the problem (lack of `bounds` property in `onBarCodeScanned` results) — we'll get to it some day (maybe not that far in the future). 🙂

**Comment by patrickklze** [comment]
@sjchmiela Thank you for getting back to me about this issue! Will in your suggestion!

**Comment by Juta** [comment]
Yes it works for me by adjusting the example at https://docs.expo.io/versions/latest/sdk/bar-code-scanner/ with this barcode handler
```
handleBarCodeScanned = data => {
  console.log(JSON.stringify(data));
   this.setState({ cornerPoints: data.cornerPoints, boundingBox: data.bounds});
};```

**Comment by visto9259** [comment]
It does not for me.  I am using `SDK Version 34.0.0`.  The callback function is called with an argument of this shape, as an example:
    rawData = {
       data: "1102397",
       target: 1179,
       type: "com.intermec.Code93",
    }
Check out this snack:
https://snack.expo.io/@visto9259/9e28df

**Comment by visto9259** [comment]
Looking at [#2904](https://github.com/expo/expo/pull/2904), it seens that this is a fix for Android only.  Anybody working on a solution for `ios`?

**Comment by helciofranco** [comment]
@visto9259 I also checked it... Unfortunely just for Android :(

**Comment by lukmccall** [comment]
Fixed by https://github.com/expo/expo/pull/8865.
