### ISSUE TITLE
Android build failed, release property unknown

### ISSUE THREAD

**Issue by enexusde** [expo/expo#27001]
### Summary

Build a expo app failed in the expo.dev.
The build said release is a unknown property.
This is the source line: https://github.com/expo/expo/blob/7cf52f4f1444926989a454d60cb329e71643d6d4/packages/expo-modules-core/android/ExpoModulesCorePlugin.gradle#L65

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Environment

unable to use that command

### Reproducible demo

not allowed

**Comment by enexusde** [comment]
Any progress this?

**Comment by enexusde** [comment]
Any progress on this?

**Comment by enexusde** [comment]
Any progress on this?

**Comment by enexusde** [comment]
Any progress on this?

**Comment by enexusde** [comment]
Any progress so far?

**Comment by Jedclark** [comment]
Hey, not sure if you fixed this but I had the exact same issue recently and the problem was actually in a previous step. The issue was some packages were incompatible with the version of Expo I was using, updating them to the correct versions fixed it for me. Try running expo doctor and seeing if it flags any issues, resolve those, and then try the build again when you get the "Didn't find any issues with the project!" output. That worked for me.

**Comment by GiovanniColonni** [comment]
I also have this problem and it has been solved by:

`npx expo install --check`

problably some outdated modules

**Comment by mohak64** [comment]
Hi, I'm facing same issue. can you guys help?
npx expo install --check
I have tried this as well

**Comment by lukhol** [comment]
Any updates on this?

**Comment by shayanHosseinChari** [comment]
change  from components.release  to  from components.findByName("release")

:)
