### ISSUE TITLE
Nested navigator: index.ts takes precedence on initialRouteName parameter

### ISSUE THREAD

**Issue by ColleSerre** [expo/expo#27005]
### Minimal reproducible example

https://github.com/ColleSerre/techbalance-expo

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

I want to raise attention about the ways in which the initialRouteName parameter can be ignored. In my case I had a Drawer navigator nesting two stacks. One is called Home, the other Resources. **I noticed that regardless of which params I set in order to make the Home route take precedence, the fact that I had my file called index.ts rather than resources.ts (in app/(resources)) meant that expo-router** (or react navigation, not sure of which one to blame) **would automatically detect this file as the root of my app.** 

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.0
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.6.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /Users/darenpalmer/.rbenv/versions/3.0.1/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.11090377
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.6 => 50.0.6 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed

**Comment by marklawlor** [comment]
The logic for Expo Router is on app load it will load the most specific route that matches `/` (the `index.tsx`). This is because Expo Router is URL based. 

The `initialRoute` option in React Navigation sets the first screen within the Stack, not necessary the currently rendered screen. In your example, if you change `(resources)` to be the initial route. The app will load to `/(home)/index.tsx` but if you press "back" it will go to `/(resources)/index.tsx` (as your app loaded with two screen on the stack, the "initialScreen" and the screen matching "/").

Right now your app has two competing routes for the URL `/`. In this instance, we show the most specific route (the one with the most parameters/groups). In the event of a tie (like in your case) we simply show the first alphabetical one.

The simplest fix your for issue is simply change `(resources)` from being a group, to a path segement `resources` (remove the brackets
