### ISSUE TITLE
[expo/metro-config]: polyfills get applied in wrong order (works with `@react-native/metro-config`)

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/expo#27070]
### Minimal reproducible example

https://github.com/stefan-schweiger/expo-metro-bug

### Summary

I've recently updated my project to the most recent version of expo. I noticed that `expo-doctor` complained that my project uses `@react-native/metro-config` and it should instead be using `expo/metro-config`.

But when I changed to use `expo/metro-config` I started getting the following error when I try to connect my devclient/Expo Go app (both on Android/iOS):

```
TypeError: Cannot read property 'bind' of undefined, js engine: hermes
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
```

The source of this error is some code in jsPDF which basically does `const atob = globalThis.atob.bind(globalThis)`. I polyfill `atob` and `btoa` in my app and with the old metro-config that worked correctly. But with the new metro-config `atob`/`btoa` are `undefined` when the code of the package is run.

I assume that whatever the expo metro-config does changes the order of the generated code in such a way that the polyfill is only applied after the module code.

**App.js**
```javascript
import { decode, encode } from "base-64";
import { jsPDF } from "jspdf";
import React from "react";
import { Text, View } from "react-native";

// polyfill for jsPDF
globalThis.btoa = encode;
globalThis.atob = decode;

const App = () => {
  const handlePicture = () => {
    const document = new jsPDF({ unit: "px", putOnlyUsedFonts: true });
    console.log(document.getNumberOfPages());
  };

  return (
    <View style={{ flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center'}}>
      <Text onPress={handlePicture}>TEST</Text>
    </View>
  );
};

export default App;
```

**metro.config.js**
```javascript
// Produces following errors:
// TypeError: Cannot read property 'bind' of undefined, js engine: hermes
// Invariant Violation: "main" has not been registered. This can happen if:
// * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
const { getDefaultConfig } = require('expo/metro-config');
const config = getDefaultConfig(__dirname);
module.exports = config;

// Works as usual
// const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
// const config = {};
// module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.6.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    Expo Workflow: managed
```

**Comment by EvanBacon** [comment]
Confirming polyfills are applied in the same order between both configs:

- community config https://github.com/facebook/react-native/blob/4236538cbd36d5bc607b3108df45fc51fc8335db/packages/metro-config/src/index.flow.js#L58
- expo config https://github.com/expo/expo/blob/8cc11815565476c5569359e8cbb7001ebec0d870/packages/%40expo/metro-config/src/ExpoMetroConfig.ts#L232
  - (plus a slight modification for server support) https://github.com/expo/expo/blob/8cc11815565476c5569359e8cbb7001ebec0d870/packages/%40expo/cli/src/start/server/metro/withMetroMultiPlatform.ts#L60C16-L60C25

**Comment by stefan-schweiger** [comment]
@EvanBacon I'm not talking about the integrated polyfills, but about polyfills applied for example in `App.js`.

**Comment by EvanBacon** [comment]
The issue is that the community config has `inlineRequires` enabled by default, which is generally unsafe because code will execute in an unexpected order, and not respect side-effects in other modules (inline requires is applied _before_ imports are processed) https://github.com/facebook/react-native/blob/4236538cbd36d5bc607b3108df45fc51fc8335db/packages/metro-config/src/index.flow.js#L83

You have two options here:

1. (Preferred) Ensure `btoa` and `atob` are polyfilled *before* the `jspdf` file is imported. This can be done by simply moving the polyfill to its own file and importing that file before `jspdf` is imported. This is because the order of imports is predictable with `inlineRequires` disabled. I recommend this approach regardless as it ensures the behavior is more consistent with the larger JS ecosystem (all bundlers work this way).

```js
// This will run first.
import "./polyfill-atob"
// This will run second.
import { jsPDF } from "jspdf";
```

2. You could also enable inline requires in the `metro.config.js` to get the previous behavior, but it would be subject to break, assuming the usage of `jspdf` appears before the `atob` polyfill:

```js
const { getDefaultConfig } = require("expo/metro-config");
const config = getDefaultConfig(__dirname);

config.transformer.getTransformOptions = () => ({
  transform: {
    experimentalImportSupport: false,
    inlineRequires: true,
  },
});

module.exports = config;
```

Behind the scenes, inlineRequires is moving the import to where it was used, which in this specific case, is after the global polyfill (side-effect) is applied.

We're hesitant to enable inline requires for a number of reasons, my understanding is that it may have been accidentally enabled upstream in lieu of bundle splitting / tree shaking, and now it's too difficult to turn off without causing cryptic issues like the one you encountered.
