### ISSUE TITLE
Expo router going deep on nested layout

### ISSUE THREAD

**Issue by Deegiimurun** [expo/expo#27124]
### Minimal reproducible example

https://github.com/Deegiimurun/expo-router-test

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Sample layouts in example. Problem is when routing to nested layout (to (app)) expo router goes much deeper (all the way to (register)).

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.14.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.6 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.1.1
    Expo Workflow: managed

**Comment by Deegiimurun** [comment]
Adding
```
export const unstable_settings = {
  initialRouteName: 'index',
};
```
fixes issue but i am not so sure why.

**Comment by Deegiimurun** [comment]
Replacing (app)/_layout.tsx with

```
import { Slot } from "expo-router";

export default function AppLayout() {
  return (
    <Slot/>
  )
}
```

It render (app)/(register)/index.tsx not (app)/index.tsx. Can anyone tell me why?

**Comment by marklawlor** [comment]
This is to be expected. The logic is that the router will match the most comprehensive route. 

Specifying the group in a URL is optional. If not included, Expo Router will match the groups based upon your current location. If you navigate to a URL, and that route is inside a new group, it will automatically include you within that group.

There is no way to opt out of groups (As groups as optional, how could we represent that as a URL?). So the fix to your issue is to simply move `/(app)/index.tsx` into its own group. If two groups have the same specificity (e.g both routes both have new the same number of new groups), it will pick in alphabetical order.

We should implement a compiler error that catches this scenario, sorry for the hassle.
