### ISSUE TITLE
[expo-router] Vercel api routes export fails when using bun 

### ISSUE THREAD

**Issue by mwarger** [expo/expo#27155]
### Minimal reproducible example

https://github.com/mwarger/expo-api-experiment

### Which package manager are you using? (Yarn is recommended)

bun

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Vercel deployment with api routes does not work when using bun.  The expo export command fails:

```

App exported to: dist
--
12:02:12.967 | Running "bun run vercel-build"
12:02:12.978 | $ expo export -p web
12:02:13.225 | ConfigError: The expected package.json path: /vercel/path0/api/package.json does not exist
12:02:13.230 | error: script "vercel-build" exited with code 1
12:02:13.236 | Error: Command "bun run vercel-build" exited with 1

```

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.7 => 50.0.7 
      expo-router: ~3.4.7 => 3.4.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed

**Comment by kitten** [comment]
Hiya 👋 I just had a quick look and just to leave a quick solution here so you can get yourself unblocked, this seems to only be happening when `vercel-build` is defined in the `package.json` and the “vercel.json v2” template is used, as per the docs: https://docs.expo.dev/router/reference/api-routes/#vercel

If you follow the “vercel.json v3” template and remove the `vercel-build` task from your `package.json` this works properly again, since Vercel will pick up on the `"buildCommand": "expo export -p web"` configuration option instead.

I'll try to get to the bottom of why this command seems to fail when `vercel-build` is used specifically in the meantime

**Comment by kitten** [comment]
This seems to be an issue in Bun. Unlike `npm` or `yarn`, for example, `bun run` doesn't seem to change the current working directory of a script that’s being run to the `package.json`’s `dirname` directory. This means that the Vercel task in this case runs in `/api` rather than `/`, which makes our export task fail.

Unfortunately, we rely on the working directory quite heavily and fixing it just for the `@expo/config` case doesn't fully resolve this issue throughout the CLI.

I'll have to check first whether this is something that is already reported in Bun (and whether this is intended behaviour) and/or whether we want to try to address this with a change in our CLI by potentially relying on `process.env.npm_package_json` when it's available and set.

---

Local Reproduction Steps:
- Add a `"vercel-build": "expo export -p web"` script to the `package.json` of an Expo project
- Run `cd api` (or any other subdirectory)
- Observe that `bun run vercel-build` fails
  - `yarn run vercel-build` succeeds
  - `npm run vercel-build` succeeds

To double check that the working directory is the issue:
- Add a `"test-cwd": "pwd"` script to a `package.json`
- Run `cd api` (or any other subdirectory)
- Observe that `bun run test-cwd` outputs the subdirectory
- Observe that `{yarn,npm} run test-cwd` outputs the project root directory

**Comment by mwarger** [comment]
@kitten Thank you.  I see what you're saying.  The package.json script should only be added when using v2.  I will give this a shot as instructed since I'm using v4.

**Comment by kitten** [comment]
I didn't even spot that. Thanks for pointing that out! I'll make sure to update the docs so we don't suggest to add that script for the v3 vercel.json 🙌

**Comment by mwarger** [comment]
@kitten I tried that in my repo and it worked.  Thanks for the help!

**Comment by dnlgrgly** [comment]
The docs weren't updated in the end, so I've [opened a PR](https://github.com/expo/expo/pull/30252) to clarify this in the docs, so that others don't have to go through the same steps 🙌
