### ISSUE TITLE
Segment Selecting Destinations

### ISSUE THREAD

**Issue by jorge-sanz** [expo/expo#2729]
Is it possible to select Segment Destinations with the Expo Segment library?

**Comment by esamelson** [comment]
Hi @jorge-sanz - if you're looking to use a Device-Based connection mode that requires a third-party native library for your destination, you'd need to eject to ExpoKit in order to make this work, and we cannot guarantee it would be possible without modifications to the Segment API in ExpoKit.

However, my understanding is that Cloud-Based connection modes should work just fine as all of the work is done on the server side.

Hope this helps!

**Comment by jorge-sanz** [comment]
What I want to do is this: https://segment.com/docs/sources/website/analytics.js/#selecting-destinations

**Comment by esamelson** [comment]
@jorge-sanz - this can be done with the `alias` call in the current version of the API: https://docs.expo.io/versions/v31.0.0/sdk/segment#segmentaliasnewid-options . However, it is not available on the other methods.

Reopening this to track, but we cannot promise this will be added on any given timeline.

**Comment by Sylvain-L** [comment]
Hello,

we need to track sessions, using expo-analytics-segment, and Amplitude as a destination.
Per the Segment/Amplitude docs, we need to use this:  https://segment.com/docs/sources/website/analytics.js/#selecting-destinations to our events.

Still no plan to add it ? Or do you know any other way to track session data on Amplitude using expo ?

**Comment by cruzach** [comment]
Hi! I just added this behavior, and it will be included in the next SDK release (39). You can check the [changelog](https://github.com/expo/expo/blob/master/packages/expo-analytics-segment/CHANGELOG.md#unpublished) for details, but this is done by passing an `integrations` object in your `options` param
