### ISSUE TITLE
[expo-camera/next][IOS]: Switching from `picture` to `video` mode breaks `recordAsync`

### ISSUE THREAD

**Issue by lodev09** [expo/expo#27528]
### Minimal reproducible example

https://github.com/lodev09/expo-camera-issue

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Switching from `picture` to `video` mode will break `recordAsync` method. This is most likely due to camera not being ready yet during the switch.

Possible workarounds so far:
- Adding a little delay does make it work like [this](https://github.com/lodev09/expo-camera-issue/blob/28672d5a37b4bb12e9e0ae5988b908c08709338b/App.tsx#L76-L82) but not ideal imo.
- Re-mounting the camera seems to be inefficient as well.
- I also tried setting it to always `video` which works but `expo-haptics` will no longer work -- I like haptics :(

Is there a better solution than a delay? Can it maybe re-trigger `onCameraReady` when modes are switched?

Please advise. Thank you!

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - /opt/homebrew/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.2 AI-232.10227.8.2321.11479570
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.11 => 50.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.4 => 0.73.4 
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: bare
```

### Expo Doctor Diagnostics

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!
```

**Comment by alanjhughes** [comment]
Hi @lodev09 - Unfortunately, I'm not sure there is a better solution for this use case other than adding a delay. This was an issue with legacy camera also. You'll notice even with your delay that you are capturing dark or dead frames at the beginning of the video. This is because the camera has just finished mounting the new preview at the time when you call `record`. Switching between video and picture requires an entire reconfiguration on the native side and this takes some time. 

Because all configuration is async, it is difficult to coordinate everything smoothly. I've tried to contain most of it in the same scope but some functions require opening their on async blocks on the sessionQueue and there isn't an easy and thread safe way to coordinate them.

I believe the smoothest experience is to allow the user to select whether they are taking a picture or a video. Making this selection creates a natural delay between when they change modes and press the shutter button.

**Comment by lodev09** [comment]
Hey @alanjhughes, thanks for the clarification. I guess it is what it is. How about the 2nd solution? Can we force haptics to work even in "video" mode? Taking picture while in video still works and there's no dela although I don't know about the battery impact. Any suggestion?

**Comment by alanjhughes** [comment]
Hey @lodev09, I'd have to try it with haptics. First thought would be if the video is being setup up at the same time as haptics is triggered, the thread could be blocked. I'll have a look.

**Comment by alanjhughes** [comment]
Hey @lodev09 - The latest version of this library has received a number of improvements that should make configuration smoother. I've fixed the dead frames issue and changed how the camera is setup so it should be more predictable. I'm not sure if it will solve the problem of rapid switching but I'm not sure if there is much more we can do there. It's a heavy operation to switch unfortunately.

**Comment by lodev09** [comment]
Thank you for the update @alanjhughes. I will check it out 👍

**Comment by BoavistaLudwig** [comment]
I have similar issues:
Without setting the mute prop, my app crashes on video.
If video, I can only conditionally set the mute prop to false with a 250 delay. Without this delay the app crashes.
But like you observed, switching from picture to video breaks the recordAsync method.

I now have the camera set to video only (also for taking pictures) and also lose haptics because of it.

@lodev09 have you found a better solution by now or with SDK 51?

**Comment by lodev09** [comment]
@BoavistaLudwig I'm at `Expo 50` and currently implemented a `600ms` timeout before actually starting to record.

```tsx
const cameraRef = useRef<CameraView>(null)
const [isRecording, setIsRecording] = useState(false)

const startRecording = () => {
  // Flag as recording right away
  setIsRecording(true)

  setTimeout(async () => {
    const video = await cameraRef.current?.recordAsync()
    setIsRecording(false)
  }, 600)
}

return (
  <View>
    <CameraView
      ref={cameraRef}
      mode={isRecording ? 'video' : 'picture'}
    />
    <Button title="start recording" onPress={startRecording} />
  </View>
)
```

This works well with a drawback. A dead frame gets recorded lol.
I'm living with it for now until `Expo 51`, which is much better the last time I tested.
