### ISSUE TITLE
Detached app is unable to load the app

### ISSUE THREAD

**Issue by EgidioCaprino** [expo/expo#2753]
Hi all 👋

We have this issue with an ejected app:

![image](https://user-images.githubusercontent.com/5156120/48769488-124f6500-ecbc-11e8-9cb5-a6fc9caf6659.png)

We're using these deps:
```
"expo": "^31.0.5",
"expokit": "^31.0.2",
```
and globally I have `├── expo-cli@2.4.0`.

Our start script is `"start": "expo start --clear",`

Do you know what the issue is and how we can fix that?

**Comment by theixbass** [comment]
You need to run expo start and rebuild the app.

**Comment by ReinisL** [comment]
@EgidioCaprino  Try to run `yarn start` or `npm run start` and while it's running, rebuild the detached project on xcode

**Comment by EgidioCaprino** [comment]
Hi @ReinisL 

We've tried that but it didn't work.

**Comment by sjchmiela** [comment]
Hey, @EgidioCaprino! Are you sure that when you were upgrading your ExpoKit project you followed all the necessary instructions? Error message visible on the screenshot, _The experience you requested requires a newer version of Expo Client…_ suggests some steps from [Upgrading ExpoKit](https://docs.expo.io/versions/latest/expokit/expokit#upgrading-expokit) may have been omitted (`app.json` requests a higher version than your ExpoKit thinks that can provide).

Could you please ensure you've followed those instructions? 🙂

**Comment by EgidioCaprino** [comment]
@sjchmiela we've upgraded following the instructions at the bottom of [this article](https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49)

**Comment by sjchmiela** [comment]
Let me clarify that — at the bottom of the article you've linked there is the following section:

<img alt="zrzut ekranu 2018-11-24 o 13 04 30" src="https://user-images.githubusercontent.com/1151041/48968021-899d3580-efe9-11e8-9fa4-8aeab5c8e158.png">

Have you also followed instructions from the link highlighted, i. e. [these instructions](https://docs.expo.io/versions/latest/expokit/expokit#upgrading-expokit)?

**Comment by EgidioCaprino** [comment]
@sjchmiela yes we did. That doc got updated later on. For instance we lost 2 days because of the issue with `okhttp3` on Android.

**Comment by sjchmiela** [comment]
Sorry for that! 😕 

Have you closed the issue on purpose — have you figured out the problem and are you able to run the ejected project now?

**Comment by sjchmiela** [comment]
😞 I understand. Next time please ensure all the steps from all the instructions are completed, I'm pretty sure the original error message is caused by [`EXSDKVersions.plist`](https://github.com/expo/expo/blob/master/exponent-view-template/ios/exponent-view-template/Supporting/EXSDKVersions.plist) not having the new version inside, which causes `errorCode` to be set:

https://github.com/expo/expo/blob/d85cf10adb8ce2f381b3492e35857c200fb764e7/ios/Exponent/Kernel/AppLoader/CachedResource/EXManifestResource.m#L355-L357

which then sets the offending message:

https://github.com/expo/expo/blob/d85cf10adb8ce2f381b3492e35857c200fb764e7/ios/Exponent/Kernel/AppLoader/CachedResource/EXManifestResource.m#L430-L431

If you follow all the instructions included [here](https://docs.expo.io/versions/latest/expokit/expokit#ios-1) you should end up with a working, upgraded iOS project. 🙂
