### ISSUE TITLE
Expo 31.0.0 Webview now opening up in android browser instead of wrapping native

### ISSUE THREAD

**Issue by menzer2015** [expo/expo#2779]
Hi in version 30.0.0 the Webview wrapped my website fine even when browsing my website it stayed in the webview as though it was native but since 31.0.0 when you open the app and click a link on the website or try to login it opens a new browser. I am using the below code to wrap my website, also for some reason I cannot access the android Camera Roll to upload images on to my website even though I put "permissions": ["CAMERA","READ_EXTERNAL_STORAGE","WRITE_EXTERNAL_STORAGE"] in app.json  

export default class Webview extends Component {

    constructor(props) {
        super(props);
        this.src = 'URL';
    }

    render() {
        return (
            <View style={{ flex: 1 }}>
                <WebView
                    source={{ uri: this.src }}
                    style={{ flex: 1 }}
                />
            </View>
        );
    }
}

**Comment by esamelson** [comment]
Hi @menzer2015 - could you please put your code into a [snack](https://snack.expo.io) that fully reproduces the problem? It's hard to tell exactly what's going on without a clear repro case. Thanks!

**Comment by kashifghaffarasim** [comment]
@esamelson WebView not working in ios too. Will you please check it?

**Comment by AdamJNavarro** [comment]
Hey all,

In an effort to create a clearer picture for our team about what is still actionable, we are going through older and inactive issues that were missing the necessary information for us to attempt to debug (see: Needs more info label).

If anyone is still encountering this issue on a presently supported SDK version (30-34) and has Minimal, Complete and Verifiable Example (MCVE) and better yet, the root cause identified, we encourage you to create a new issue with said information!

Cheers,
Adam
