### ISSUE TITLE
Change application configuration

### ISSUE THREAD

**Issue by clementino36** [expo/expo#278]
Hi,
I'm wondering how to change an expo app's configurations. Examples of what I mean by configurations: 
Make the app only available for tablets, require location/wi-fi connection/bluetooth connection, specify multiple icon sizes, etc ...
I'm asking this because I generated an ipa, tried to build it with Application Loader but I got this error:

> Missing required icon file. The bundle does not contain an app for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0

Does this have anything to do with `exp.json` ?
Thanks!

**Comment by terribleben** [comment]
Hi, yes, those things are all configured in exp.json, and the details are in [this guide](https://docs.expo.io/versions/v17.0.0/guides/configuration.html#content).

For the specific error you reported with icons, make sure the icon you have specified in exp.json is square. If it's not square, it won't be valid for submission to Apple.

Let me know if this solves your issue.

**Comment by clementino36** [comment]
Hi, thanks for your answer, resizing the icon to square values sure did the trick!
One more question about the guide though. If for instance I want to make my app only available for tablet (not for phones), should I play with the `supportsTablet ` param or something else ? Also, is there an example of what can be put in the `infoPlist ` param ?
Thanks!

**Comment by terribleben** [comment]
We recently added tentative support for iPad-only builds with a key `ios.isTabletOnly` (instead of using `supportsTablet` at all). Looks like I forgot to document this, sorry, I'll add that to the docs.

The `infoPlist` param is just an arbitrary dictionary (e.g. `{ someKey: someValue }`) which will be merged into your app's `Info.plist` before any other configuration.

Closing because I think we've answered your original issue - let me know if something doesn't work or feel free to open a topic on the [forums](http://forums.expo.io).
