### ISSUE TITLE
[expo-location][expo-background-fetch] : Location Background Updates not working in iOS after App is terminated

### ISSUE THREAD

**Issue by macsinte** [expo/expo#27933]
### Minimal reproducible example

https://github.com/macsint/expo-background-location-issues

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Both `expo-background-fetch` and the `expo-location` packages do not seem to support providing updates and/or executing code in iOS specifically once the app is killed/terminated. They work while the app is in the Foreground or Background, but not once the app is manually closed by the user.

Both of these work in Android once the App is terminated.

According to [your documentation](https://docs.expo.dev/versions/latest/sdk/background-fetch/#known-issues), as well as many issues that were created and closed without resolution (e.g - [issue example 1](https://github.com/expo/expo/issues/4860), [issue example 2](https://github.com/expo/expo/issues/3582) it seems like background fetch supports bringing up the app live in the background once it was closed on Android only, and thus enabling us to execute certain tasks even after the app was closed.

It is also recognized by your team that this is a problematic behavior for iOS that was apparently not on the roadmap when the issue was acknowledged.

Both iOS and Android support background fetches and executing code post app termination using native packages. For example `react-native-location` supports retrieving location in the background even when the app is terminated by the user not only while in Foreground or Background. So does the native `background-fetch` React Native package.

Since `expo-location` is essentially using the `TaskManager` and what I would assume to also use `expo-background-fetch` and Background Fetches in general, I would assume that by solving this issue for `expo-background-fetch` would solve the rest.

What my team wants to achieve is to be able to send users specific notifications even when the app is terminated based on their location. This works well using your location package complemented by using your background fetch for Android for when the app is terminated but the latter does not work for iOS.

Therefore what I’m asking is if there’s a way we can work together towards making the background fetch work, while the app is terminated a reality for iOS as well.

The docs which I linked above recognize this as an issue and point to a GitHub issue which was closed even though it was not resolved, which according to your team’s comments does not seem to present a high priority.

I hope that makes more sense.

### Environment

```
➜  getmoonbeam-app git:(feat/location-updates-notification) ✗ sudo npx expo-env-info
Password:
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) y

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
      Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.6.0
    Expo Workflow: managed
```

### Expo Doctor Diagnostics

```
➜  getmoonbeam-app git:(feat/location-updates-notification) ✗ sudo npx expo-doctor@latest
Need to install the following packages:
expo-doctor@1.5.0
Ok to proceed? (y) y
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  react-native@0.73.4 - expected version: 0.73.6
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

### Please Note

I might be wrong and this might be an iOS limitation. There are a lot of conflicting articles around this so if this is indeed a limitation which we can confirm together that it is still the case in 2023, then we can disregard this issue.

There are some additional articles which would suggest that this is working using the Native Package as well. For example: [this article](https://jandemel.medium.com/react-native-background-location-background-terminated-app-6bedfb1f46e2).

Nevertheless there is other literature that suggest that I am wrong and this is indeed an iOS limitation:
[this Github package for example](https://github.com/transistorsoft/react-native-background-fetch)

**Comment by macsint** [comment]
One thing to mention here is I do not need any help in sending silent notifications or sending notifications at all, and I would like to make that clear as there are many issues concerning this that mixed up this issue with sending silent notifications.

I have the notifications portion handled without the need for help or Silent Notifications. In the example that I provided, we only `console.log` the location, but in our actual code base we call an endpoint of our own which handles the location whether it is coming from the Foreground, Background or from Background Fetches once the app is closed/terminated. That works very well for Android for all instances but it does not work for iOS once the app is killed/closed/terminated (hence why this is acknowledged by your documentation and why I created this issue in the first place).

**Comment by macsint** [comment]
Additional Note: 
- this has been tested using Expo Go and Development Builds, as well as Production Builds via `aab` or `ipa` files for both Android and iOS.

**Comment by macsint** [comment]
In #3582 @brentvatne you mentioned that 

> for anyone that stumbles on this - @ajsmth recently wrote up some useful instructions for trigger background fetch manually, which is much easier than waiting for the operating system to kick in for you: https://docs.expo.io/versions/latest/sdk/background-fetch/#triggering-background-fetches
keep in mind the following limitation for iOS as well: BackgroundFetch only works when the app is backgrounded, not if the app was terminated or upon device reboot.
i'm going to lock this thread because as far as we know this is working as expected, please make a new issue if you continue to encounter issues.

Not sure if this is working as expected as the native libraries support this behavior for iOS. Was there a reason of why this ticket was closed and acknowledged as `working as expected` ?

I'm sorry if I'm missing something as this seems to be possible on iOS as well. For example Google Maps sends me notifications in the US if I'm visiting a particular place and sends me a notification along the lines of:
`You're at Restaurant X. Click here for their menu`.

**Comment by tsapeta** [comment]
Thanks for opening a new issue for this!

So, from my understanding these are essentially two different unrelated blockers for your team. As I previously said https://github.com/expo/expo/issues/4860#issuecomment-2026135546, background fetch will never be triggered by the platform (OS) when the user intentionally closed the app. Let me quote Apple employee from [Apple Developer Forums discussion](https://forums.developer.apple.com/forums/thread/666149).

> The system interprets this gesture (removing your app from the multitasking UI) as a strong indication that the user doesn’t want your app running. The system will not give the app background fetch time until after the user manually launches the app again.

I can also confirm this from my own experience. I'm force-closing all apps quite often to save battery power when I plan to use my phone more extensively during that day. The difference is especially visible for social media apps that send a lot of silent notifications as an addition to background fetch.

As for `expo-location` and background location updates, I'm not actually sure if the same limitation applies, we'll need to search for that a bit more. However, I'm sure that geofencing is not limited in this case and that's what many apps (like Google Maps) are using. I bet they even monitor multiple regions around your last known location so they know when you left that region, then they update regions accordingly based on the region that you just entered.

We're of course open to contributions, but first I'd like you to check and confirm what I just said so we're on the same page. You can message me on discord and we can make a call if that works for you.

We're also planning to rewrite `expo-location` at some point as it's still in Objective-C and is using the old API for native modules. I can't give any estimation right now though.

**Comment by macsint** [comment]
@tsapeta thanks for your comment. 

I'm assuming that you're suggesting that we use `Location.startGeofencingAsync` instead of `Location.startLocationUpdatesAsync` ? 

If so, you're saying that you're sure that geofencing is not limited for apps which are intentionally closed by the user and we will be receiving updates through Geofencing? 

I can try that, but I doubt that's the case because I'm assuming that under the hood both location updates and geofencing are using the `TaskManager` and thus if Apple limits that for closed apps then it wouldn't work regardless no?

**Comment by tsapeta** [comment]
Yeah, as far as I know geofencing can "relaunch" the app after being closed by the user, giving it a few seconds to execute some code. It's worth trying anyway.

The task manager is only managing defined/registered tasks and executing your JS code. As itself, it has nothing to do with the platform limitations. It's the OS that automatically calls

- https://github.com/expo/expo/blob/8a676eb4222652ac7bab27e4203b673b5bef79f8/packages/expo-location/ios/EXLocation/TaskConsumers/EXLocationTaskConsumer.m#L84 for background location updates

- https://github.com/expo/expo/blob/8a676eb4222652ac7bab27e4203b673b5bef79f8/packages/expo-location/ios/EXLocation/TaskConsumers/EXGeofencingTaskConsumer.m#L125 for geofencing

And yes, it may work differently on Android because it's different platform and has its own limitations. In older Android versions you could get background location updates as often as if the app was in foreground. Now I think it's necessary to use a foreground service to achieve that behavior, but the user will see that your app is tracking him.

**Comment by tsapeta** [comment]
So I dig deeper into this and so far I can tell that it may actually be an issue in task manager that somehow can't launch a React app after app termination. It's slightly different process than when the app is in background as after termination (by the OS or by the user) it needs to create a new RCTBridge, load the previously used bundle and execute only the top-level scope with defined tasks, without mounting the views.

That logic, even if it gets fixed, wouldn't work in the new architecture in RN 0.74 due to bridgeless mode being enabled, so we'll need to allocate some resources to figure that out as we want all our libs to support the new architecture.

This doesn't apply to background fetch though – it will not work as you expect after the user killing the app.

**Comment by macsint** [comment]
@tsapeta thanks for checking.

Does that issue apply for geofencing and location updates, since they both use the Task Manager?

And would that essentially mean that once we address that, that we would be able to get the user’s background location even after the app was terminated in iOS?

If so, I can retitle this issue and just focus it around location. For us, we don’t really care whether we get the background location once the app is terminated through background fetch or using the actual location  subscription mechanism from the expo-location package.

**Comment by tsapeta** [comment]
@macsint Yeah, rephrasing the title so it doesn't include background fetch sounds good to me.

> And would that essentially mean that once we address that, that we would be able to get the user’s background location even after the app was terminated in iOS?

As far as I know, yes, but only for significant location updates. It will probably doesn't fire as frequent and not as accurate as when the app wasn't closed by the user.

**Comment by macsint** [comment]
@tsapeta changed that title on the issue. Whenever your team is done reviewing it internally, I volunteer to help if needed to expedite a solution/resolution for it.

If you determine that this is still not possible in iOS, let us know and I can close the issue and we will revisit it whenever Apple and/or iOS makes this a reality.

**Comment by tnovas** [comment]
@macsint @tsapeta is working using `startGeofencingAsync`, if user kill app before trigger an event of Geofencing the TaskManager became live again without instance of app.

#### POC
When app start define task for Geofencing and Location

```js
TaskManager.defineTask(GEOFENCING_TASK_NAME, ({ data: { eventType, region }, error }) => {
  if (eventType === GeofencingEventType.Enter) {
    console.log("You've entered region:", region);
  } else if (eventType === GeofencingEventType.Exit) {
    console.log("You've left region:", region);
  }
});

TaskManager.defineTask(LOCATION_TASK_NAME, ({ data, error }) => {
  if (data) {
    const { locations } = data;
    console.log(locations);
  }
});
```

Run `startLocationUpdatesAsync`, get currentPosition and `startGeofencingAsync` with the currentPosition and region with 300 meters

```js
await Location.startLocationUpdatesAsync(LOCATION_TASK_NAME, {
   showsBackgroundLocationIndicator: false,
    deferredUpdatesDistance: 300,
   accuracy: Location.Accuracy.Balanced,
});

const currentLocation = await Location.getCurrentPositionAsync();
Location.startGeofencingAsync(GEOFENCING_TASK_NAME, [{
   latitude: currentLocation.coords.latitude,
   longitude: currentLocation.coords.longitude,
   radius: 300,
}])
```

Before pass the 300 meters kill de app, the TaskManager became alive again when pass the region.

This POC was testing with:

`Simulator: Iphone 15 Pro - iOS 17.4`
`Tool: Expo Go`

Versions:
```json
"expo": "~50.0.14",
"expo-location": "~16.5.5",
"expo-task-manager": "~11.7.2"
```

Regards!

**Comment by kotsh23** [comment]
its not working on android 2025
