### ISSUE TITLE
Standalone Jest `.test` files in /app directory with expo-router cause bundling error

### ISSUE THREAD

**Issue by OoDeLally** [expo/expo#28000]
### Summary

According to the documentation https://docs.expo.dev/develop/unit-testing/ there are two ways to provide test files.

Put the test files along with the tested module (1st way mentioned by the doc)
```
MyComponent.tsx
MyComponent.test.tsx
```
Expo Go seems to want to bundle the test file as well, provoking errors during the build, for example if the test files uses some nodejs modules e.g. `fs`:
```
Android Bundling failed 12853ms (node_modules/expo-router/entry.js)
You attempted to import the Node standard library module "fs" from "app/MyComponent.test.ts".
It failed because the native React runtime does not include the Node standard library.
```

HOWEVER
The same test files are succesfully ignored if put inside a `__tests__` folder (2nd way mentioned by the doc).

### What platform(s) does this occur on?

Android

### SDK Version

0.17.8

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    npmPackages:
      expo: ~50.0.14 => 50.0.14 
      expo-router: ~3.4.8 => 3.4.8 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: managed

### Reproduction repo

https://github.com/OoDeLally/expo-test-file-not-ignored-bug

### Other

PS: GET #28000 issue :1st_place_medal:

**Comment by amandeepmittal** [comment]
Hi @OoDeLally, thanks for sharing the reproducible example. It was very helpful! 

You're getting the error following the first approach from the Unit Testing guide because any file inside the `app` directory is considered to be part of the bundle when using the Expo Router library. In other words, the library doesn't ignore the `*.test.*` file pattern. This is also why the second approach works, where the test files are not included in the `app` directory.

You'll have to continue using the second approach and only include test files outside the `app` directory. Meanwhile, we'll call this out in our docs so that any subsequent developers are mindful of this issue and also look into respect patterns specified by Jest on the library level.

**Comment by marklawlor** [comment]
This is a feature we will explore in the future but as @amandeepmittal stated, for now you'll need to perform the second approach. 

Testing with React Native isn't as simple as a single `.test` file, as due to the multi-platform nature of Expo Router you'll most likely have multiple `.test.ios`/`.test.android`/`.test.web` files. Is having a 1:3 route:test file ratio good? We're a bit worried that it bloats the `app` and makes locating files harder in larger projects.

Also the current standard is using `-test.ios` (see [jest-expo](https://www.npmjs.com/package/jest-expo)), so there's also a compatibility issue (what is someone wants a `-test` route?)
