### ISSUE TITLE
After ejecting from Expo while logged out, AsyncStorage can't see any data

### ISSUE THREAD

**Issue by Overtorment** [expo/expo#2805]
### Environment

```
  React Native Environment Info:
    System:
      OS: Linux 4.18 elementary OS 0.4.1 Loki
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 180.82 MB / 15.43 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
    SDKs:
      Android SDK:
        API Levels: 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 26.0.3, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom_64, android-P | Google APIs Intel x86 Atom
    npmPackages:
      react: ^16.6.3 => 16.6.3 
      react-native: ^0.57.5 => 0.57.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.3.2
```

### Steps to Reproduce

After ejecting from Expo and doing testflight build, I install the app on device. App sees no data at all.
If I revert to previous build via testflight (build that is still on Expo) - all data is there, so I assume there are some kind of separate namespaces for pure RN and Expo RN.
I would really like it to be the same namespace, as users who update to our newest build with shiny new pure RN will have all their data lost.

### Expected Behavior

After update to newest build from appstore/testflight, app should see all data saved by AsyncStorge in previous builds.

### Reproducible Demo

Make 2 builds of an app. First is via Expo, second - pure RN after eject.
Save some data in first build; update to second build; app sees no data; revert back to 1st build;
app sees data

**Comment by Overtorment** [comment]
Yep, looks like different folders.

Pure RN: /Documents/RCTAsyncLocalStorage_V1/
Expo: /Documents/ExponentExperienceData/%40anonymous%2Fbluewallet-c4b47811-ba78-4320-96f9-1f7db4ad0523/RCTAsyncLocalStorage/

Is threre a way to 'pin' folder folder AsyncStorage works with..?

**Comment by bartolkaruza** [comment]
> Yep, looks like different folders.
> Pure RN: /Documents/RCTAsyncLocalStorage_V1/
> Expo: /Documents/ExponentExperienceData/%40anonymous%2Fbluewallet-c4b47811-ba78-4320- > 96f9-1f7db4ad0523/RCTAsyncLocalStorage/

If I'm reading these correctly, it should be at `/Documents/ABI31_0_0RCTAsyncLocalStorage_V1/` instead of in the location you mention. 

It looks like [`ExponentExperienceData`](https://github.com/expo/expo/blob/0848ab02aacc03e99fa3d926f5943814f3f775c8/packages/expo-file-system/ios/EXFileSystem/EXFileSystem.m#L791) is only being referenced from [`expo-file-system`](https://github.com/expo/expo/tree/master/packages/expo-file-system).
I'm unsure how Expo interacts with the underlying React Native code in the ABI though.

> Is there a way to 'pin' folder folder AsyncStorage works with..?
I don't think there is, [yet](https://github.com/facebook/react-native/issues/19692).

Maybe you can solve your problem by migrating the content manually, using [`react-native-fs`](https://github.com/itinance/react-native-fs) ?

**Comment by esamelson** [comment]
Hi all -- the AsyncStorage data is scoped not by the SDK/ABI version number but by the experience ID, as shown in the previous comment:

> Expo: /Documents/ExponentExperienceData/%40anonymous%2Fbluewallet-c4b47811-ba78-4320-  96f9-1f7db4ad0523/RCTAsyncLocalStorage/

Therefore, if the experience ID (a combination of your Expo username and `slug` from app.json) changes, the previous data will no longer be accessible. @Overtorment - has your `slug` changed in between the different versions, or were you possibly signed into a different user (or not signed in at all) when you ran the `expo eject` command?

**Comment by Overtorment** [comment]
Not signed in at all. Other developer did it, he was not signed in.
Can you please give instructions what exactly can be adjusted in xcode project to access same folder..?
Thanks

**Comment by bartolkaruza** [comment]
> Hi all -- the AsyncStorage data is scoped not by the SDK/ABI version number but by the experience ID, as shown in the previous comment:
> 
> >

@esamelson I wasn't able to find the relevant code that makes this happen in Expo. Could you point me in the right direction? Purely out of curiosity :)

**Comment by ide** [comment]
@bartolkaruza Start here: https://github.com/expo/expo/blob/99ed68475434ba18a498f0982cc11f0c1efd6b0c/ios/versioned-react-native/ABI30_0_0/Expo/Core/ABI30_0_0EXVersionManager.m#L277

**Comment by davidgruebl** [comment]
Thanks everyone here for all the insights shared!
This issue caused a lot of trouble on a project I've been working on as it resulted in loss of data on production. 
While I highly appreciate how Expo helps to simplify building applications I do think that ejecting an application should be side effect free. By forking react native instead of trying to stay an abstraction layer on top of react native and introducing changes like this one Expo doesn't hold up to its claim
[Expo apps are React Native apps which contain the Expo SDK.](https://docs.expo.io/versions/latest/#introduction)

As some sort of quick fix I'd suggest to add information about the changed file path to both, the documentation as well as the cli itself.

Keep up the great work!

**Comment by Overtorment** [comment]
We implemented a migration to ensure no data loss in production.
For everyone stumbling across the same issue, you can see how we did that here: https://github.com/BlueWallet/BlueWallet/pull/126/commits/925c537b90d26a8054929736f19101ffa6cc3dd8
Props to @marcosrdz for good work

**Comment by jeonghoonkim** [comment]
@Overtorment It's been a while but did you solve this problem on Android platform as well ?? 
On the iOS, your solution work perfectly.

**Comment by ericluong** [comment]
@Overtorment Thank you for your solution!

After ejecting from SDK 34, I found out that RCTAsyncLocalStorage what not anymore located at `/ExponentExperienceData/%40project-owner%2Fproject/` but directly in the document directory path.

@jeonghoonkim After some debug attempts, I finally found a native solution that is working for me on Android!

For a Vanilla React Native project, the SQLite database name is `RKStorage` and the file is located at `/data/data/com.yourpackage_name/databases/`.

Expo is prefixing the database name as you can see here:

https://github.com/expo/expo/blob/73c4d23244e24edfca24d7a60b6e86557cf7d85b/android/expoview/src/main/java/versioned/host/exp/exponent/modules/internal/ExponentAsyncStorageModule.java#L24

The name of the table used for AsyncStorage is `catalystLocalStorage`. 
For my particular project, because I am using Redux with Redux Persist, I just had to copy one entry of this table from the Expo database to the new one.

More information can be found here:
https://gist.github.com/ericluong/8176413b6f02bdc97b97dc0f92aa1f69
