### ISSUE TITLE
EAS Build not including local custom module when building

### ISSUE THREAD

**Issue by pmk1c** [expo/expo#28121]
### Summary

I'm using EAS Build to build an Expo Project with CNG Workflow (we just migrated from React Native Workflow to this).

Unfortunately when building with EAS Buil, the local custom native module we have in our project is not included in the build. When using `npx expo run:android` it is included.

The issues appears on Android, I'm currently checking if I can reproduce this on iOS.
I can reproduce it with running `eas build --local -p android`

### What platform(s) does this occur on?

Android

### SDK Version

50.0.14

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.asdf/installs/nodejs/18.16.1/bin/node
      npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/ruben.grimm/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11330709
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.14 => 50.0.14 
      react: 18.2.0 => 18.2.0 
      react-native: ^0.73.6 => 0.73.6 
    npmGlobalPackages:
      eas-cli: 7.8.0
    Expo Workflow: bare

### Minimal reproducible example

https://github.com/pmk1c/expo-example-local-native-module

I created this example with:

```
npx create-expo-app expo-example-local-native-module --template=expo-template-blank-typescript
cd expo-example-local-native-module
npx create-expo-module@latest --local
```

And added the local module view into `App.tsx`.

**Comment by brentvatne** [comment]
hi there,

this is due to the following lines in your gitignore: https://github.com/pmk1c/expo-example-local-native-module/blob/main/.gitignore#L37-L38

this will ignore any directory named `ios` and `android`, regardless of where they are in your app. you should instead write:

```
/ios
/android
```

so it only ignores the directories in the root of your project

**Comment by ibmmt** [comment]
I  tried importing a module in app.js using ../module/my-module. It's working fine using npx expo run android, but it's not working after the EAS build.

Error: Cannot find the native module 'mymodule', js engine: Hermes
ERROR Invariant Violation: "main" has not been registered. This can happen if:

**Comment by kendallroth** [comment]
Sorry to bring this up, but can you confirm that the _intended_ behaviour is to _not_ exclude `plugin/build` from source control? Does this mean that we will need to commit compiled code to the repository? Is there anyway around this (since it seems like it should be built each time instead)?

Also, does this only occur for local builds, or also for remote builds (if `plugin/build` is added to `.gitignore`)?

**Comment by gameveloster** [comment]
> hi there,
> 
> this is due to the following lines in your gitignore: https://github.com/pmk1c/expo-example-local-native-module/blob/main/.gitignore#L37-L38
> 
> this will ignore any directory named `ios` and `android`, regardless of where they are in your app. you should instead write:
> 
> ```
> /ios
> /android
> ```
> 
> so it only ignores the directories in the root of your project

What was the original code in the `.gitignore` that is causing this issue? The repo is no longer available.

What is prevented from being ignored by eas when you replace the line with `/ios` and `/andorid`?

**Comment by pmk1c** [comment]
The problematic lines in the .gitignore where the same without a leading slash:

```
android
iOS
```
