### ISSUE TITLE
[expo-firebase-database] ReferenceError: Can’t find variable: ThenableReference

### ISSUE THREAD

**Issue by theixbass** [expo/expo#2817]
Hi,

.push function not working because of this error

`ReferenceError: Can’t find variable: ThenableReference`

All other functions working fine!

expo-firebase-database: 1.0.0
react-native: SDK-31.0.1
expo: 31.0.4

@EvanBacon Take a look at this! 👍

**Comment by EvanBacon** [comment]
on iOS, Android, both? 1.0.0 doesn't actually exist, could you share which RC version you are using.

**Comment by theixbass** [comment]
Currently, I tested only on IOS.
![image](https://user-images.githubusercontent.com/10323718/49427376-d6cc9480-f7ab-11e8-926a-392e61ca5eee.png)

**Comment by EvanBacon** [comment]
OK this appears to be fixed in rc-5 which came out roughly when this issue was 😅

**Comment by chris35469** [comment]
I am also seeing this error. Other database functions seem to work fine.  

expo-firebase-database: 1.0.0-rc.5
expo: 31.0.6

@EvanBacon

**Comment by OwnedTom** [comment]
Getting this issue also, with 

expo-firebase-database: 2.0.0
expo: 31.0.6

@EvanBacon

**Comment by grdaneault** [comment]
Also seeing this issue. Adding `ThenableReference = Reference` makes the issue go away :puking:

https://rnfirebase.io/docs/v5.x.x/database/reference/Reference says that `react-native-firebase` doesn't actually differentiate between the two types of reference. The latest 5.x.x version of `react-native-firebase` actually returns `Reference | Promise<void>` rather than the `ThenableReference` https://github.com/invertase/react-native-firebase/blob/v5.x.x/src/modules/database/Reference.js#L306-L327

Not sure what the update path from there to here is 🤷‍♂️
