### ISSUE TITLE
Push Notification token doesn't update with a new device

### ISSUE THREAD

**Issue by ckknight** [expo/expo#2824]
### Environment

Production Standalone iOS

### Steps to Reproduce

1. User installs the app
2. Enables push notifications
3. Get token via `Notifications.getExpoPushTokenAsync()`
4. User receives a push notification successfully
5. User makes a backup of their device
6. User gets a new device
7. User restores from backup
8. User opens already-installed app
9. Push token via `Notifications.getExpoPushTokenAsync()` is the same as in 3
10. No push notifications are ever received by the new device

### Expected Behavior

A new token should probably be generated so that the server can send to the new device.

### Actual Behavior

No push notifications are received by the new device.

Only course of action for the user seems to be to uninstall + reinstall, at which point, push notifications work without issue.

**Comment by mschreiber68** [comment]
This issue affects our standalone, non-ejected iOS app as well. The push notification token, as well as `Constants.installationId`, have the same values on the new device. Users don't receive push notifications until they uninstall and reinstall the app.

**Comment by jenshandersson** [comment]
I just restored a backup to my new phone and can confirm this issue. I have 3 different standalone Expo apps that this happened to. My theory: the two devices have different (APNs) Device Tokens, but Expo sees the new device as the old one, thus not updating the device token stored in Expo database.

I had to reinstall all the apps to get push working.

**Comment by travislang** [comment]
@cruzach In reference to #6658 yes I verified that the notification settings were correct on the new phone.

I actually checked my database and copied the old push token that the app was generating, then deleted the app from my new phone and reinstalled, and compared the old push token with the new one and it was definitely different.

I am pretty sure I read somewhere in the expo docs that expo only generates on unique push token on **app install**, and I am guessing that this is not triggered when restoring from a backup...

A solution may be to check the underlying device ID every time the function is called....?

I feel like this is a serious bug because both developers and users will be unaware there is any issue at all since the push tickets and receipts all return "ok"

**Comment by imjuststeve** [comment]
Not sure if this is the place to ask, but I'm running out of ideas. I have the exact same issue as described above. However... even after an uninstall/reinstall, a new token isn't generated. And ofc notifications don't work.

**Comment by cruzach** [comment]
this will be resolved in sdk 40, see #10908 for context
If you'd like to get your hands on the fix out right now- you can [try out the SDK 40 beta](https://blog.expo.io/expo-sdk-40-beta-is-now-available-2e98264f66b2) 💻 thanks in advance for helping us make our releases even smoother!

**Comment by cruzach** [comment]
SDK 40 is released so I'm going to close this issue, lmk if you're still seeing this on the newest version
