### ISSUE TITLE
Write a guide for installing Expo universal modules in a vanilla project

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#2846]
We should have a guide that shows you step-by-step how to install some package like expo-gl in a fresh `react-native init` project.

**Comment by shubhamdeol** [comment]
I am also waiting for this. I have an app build with expo. I wanted to eject it to expo-kit but as my previous expo kit experience was not great. So I am waiting for guide to install universal modules like expo-core, expo-permissions. so that it would be easier to convert expo project to pure rn project.

**Comment by shubhamdeol** [comment]
@brentvatne  If you already installed expo universal modules. can you help me out with this.

**Comment by brentvatne** [comment]
https://github.com/unimodules/react-native-unimodules
