### ISSUE TITLE
get diretory size on Android always return 4096 bytes

### ISSUE THREAD

**Issue by kiu95** [expo/expo#2849]
When I use FileSystem.getInfoAsync to get directory size on Android, the size is always 4096, no matter how many files inside the directory.
But in iOS the original size is 64 bytes and increase after adding a file

snack to reproduce problem:
[https://snack.expo.io/rJyvhQT07](https://snack.expo.io/rJyvhQT07)

**Comment by bbarthec** [comment]
In general, measuring directory size is always tricky.
`FileSystem` is providing **size of file** via `getInfoAsync` method and in terms of file being a directory we do the same thing - measure size of this **particular directory file**, not it's content (we return what native OS tells us about a file - please notice that iOS directory size changes a little when some file is added (this size change is far less than actual size of the file being added though), while on Android directory size is constant no matter adding new files into a directory).

If you want to measure size of directory as a container I offer you this [snack](https://snack.expo.io/@bbarthec/github---filesystem---android---getinfoasync---incorrect-size), because that's what you probably want to achieve 😉

Further reading on directory size could be found [here for iOS](https://stackoverflow.com/questions/2188469/how-can-i-calculate-the-size-of-a-folder) and [here for Java/Android](https://stackoverflow.com/questions/2149785/get-size-of-folder-or-file).
