### ISSUE TITLE
[expo-router] Shared Routes with Single Routes

### ISSUE THREAD

**Issue by the-devbear** [expo/expo#28556]
### Minimal reproducible example

https://github.com/the-devbear/expo-router-shared-routes-mre/tree/master

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

Hey, so I asked this question in the [Forum](https://github.com/expo/expo/discussions/27605#discussioncomment-9282249) and in the Discord(copy paste). And @marklawlor, encouraged me to create an Issue.

What I basically wan't (when speaking web routes) are these routes: 
- `/`
- `/users/[id]`
- `/profile`
- `/profile/settings`

`/` and `/profile` should be tabs, with their own Stack, and `/users/[id]` should be a shared routed between them. 
So in the end I want these routes in expo-router:
- `/(tabs)/(home)/index` -> `/`
- `/(tabs)/(home)/users/[id]` -> `/users/[id] -- inside home tab`
- `/(tabs)/(profile)/users/[id]` -> `/users/[id] -- inside profile tab`
- `/(tabs)/(profile)/profile` -> `/profile`
- `/(tabs)/(profile)/profile/settings` -> `/profile/settings -- settings should only be acessible from profile tab`

I currently have this setup, but I would like to use `/users/[id]` as a shared route
```
src
└── app
    ├── (app)
    │   ├── (home)
    │   │   ├── _layout.tsx -- Stack
    │   │   ├── index.tsx
    │   │   └── users
    │   │       └── [id].tsx
    │   ├── (profile)
    │   │   ├── _layout.tsx -- Stack
    │   │   ├── profile.tsx
    │   │   ├── settings.tsx
    │   │   └── users
    │   │       └── [id].tsx
    │   ├── _layout.tsx -- Tabs
    ├── +html.tsx
    ├── +not-found.tsx
    └── _layout.tsx -- Stack
```
The MRE looks like this
```
app
├── (tabs)
│   ├── (home,profile)
│   │   ├── (home)
│   │   │   ├── awesome.tsx
│   │   │   └── index.tsx
│   │   ├── (profile)
│   │   │   └── profile
│   │   │       ├── index.tsx
│   │   │       └── settings.tsx
│   │   ├── _layout.tsx -- segments Stack
│   │   └── users
│   │       └── [id].tsx
│   └── _layout.tsx -- Tabs
├── +html.tsx
├── +not-found.tsx
├── _layout.tsx -- Stack
└── modal.tsx
```
It makes sense how the routes are generated. I think it would be cool, when a group inside shared routes with the same name is only accessible from that segment.

In the MRE I made some Links with comments and colours.
- Green: works as expected
- Orange: Works as expected, but I think it should behave differently
- Red: Doesn't work as expected

Maybe this is only have an Issue and half a feature request. 

Sorry for this super long text. If anything is unclear, please let me know.
Thanks in advance and have a good one!

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
      Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.17 => 50.0.17 
      expo-router: ~3.4.10 => 3.4.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 7.7.0
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
To clarify how Expo Router works - all routes are accessible from any router if you link to it. Likewise, all routes are deep-linkable. If you have a link to a route, it will work, no matter where you are.

Groups have 1 purpose, to select what `_layout` (and consequently what navigator) is rendered.

If you want a `/users/[id]` route that keeps within the same navigator that you are currently in , then your files structure should be 

```
(home)/
├─ _layout.tsx
├─ index.tsx
├─ users/
│  ├─ index.tsx
(profile)/
├─ _layout.tsx
├─ profile.tsx
├─ users/
│  ├─ index.tsx
```

Where both `users/index.tsx` files reexport the same UsersPage component. This is similar to React Navigation where you would need to have two `<Screen />` components that have the same component.

Shared groups are for when you have routes that have their own layouts, but could belong to multiple groups. We can't do what we did before (create multiple `users/index.tsx` files) because they are still under their parents `_layout`. The shared groups syntax allows you to express this. 

The other purpose are pages with unique layouts

```
(home)/
├─ _layout.tsx
├─ index.tsx
├─ users/
│  ├─ index.tsx
(profile)/
├─ _layout.tsx
├─ profile.tsx
├─ users/
│  ├─ index.tsx
(profile,home)/
├─ _layout.tsx
├─ settings.tsx
```

Say we have have navigated from `/` to `/settings`. The Settings page has a Href to `/users/1`, but which route do we navigate to? Shared groups retains the state of which group you were in so it will navigate you to the correct `/users/1`

**Comment by the-devbear** [comment]
Thank you a lot for taking the time and writing this detailed answer. It makes much more sense now for me. 
Thanks again, and have a nice day!
