### ISSUE TITLE
[docs] expo-location and expo-task-manager

### ISSUE THREAD

**Issue by srinivasbevara** [expo/expo#28631]
### Summary

Hello,

I need to continuously track the user's live location in my app. I've implemented this functionality using expo-location and expo-task-manager, following a reference example. After deploying the app to the Google Play Store and conducting tests, we discovered that while the app is in the foreground, we successfully receive the user's live location. However, when the app is minimized or running in the background, we no longer receive live location updates. Could you provide any guidance or reference code to ensure that we can consistently obtain the user's live location even when the app is running in the background?

background-fetch:
We've implemented background-fetch to retrieve the user's live location every minute while the app is running in the background. However, our goal is to receive location updates at least every 10 seconds.

Reference code:

https://docs.expo.dev/versions/latest/sdk/task-manager/
https://docs.expo.dev/versions/latest/sdk/background-fetch/

https://arnav25.medium.com/background-location-tracking-in-react-native-d03bb7652602#:~:text=The%20task%20of%20location%20tracking,or%20stop%20tracking%20your%20location.

### Link to the related docs page

https://docs.expo.dev/versions/latest/sdk/task-manager/

**Comment by choutianxius** [comment]
I was facing the same issue. Found out that the JavaScript process might be suspended by the OS when the app is not in foreground, so probably nothing can be done on the Expo end. My solution was to cache the collected GPS data and send them when possible.

**Comment by canodav** [comment]
I had the same problem when I upgraded the SDK to version 51. I downgraded to version 49 and it works now.

**Comment by kevin-griley** [comment]
Hi, Im doing the same thing. Im just curious what you mean by caching? do you mean storing the data in the local expo sqlite? See my example, is this what you mean by caching because this still uses JavaScript to cache, so Im guessing you mean it disables fetching not JavaScript. 

`
import type * as Location from 'expo-location';
import type * as TaskManager from 'expo-task-manager';

import { sendGpsCurrent } from '~/utils/functions/fetchFunctions';
import { deleteGpsCache, getGpsCache, storeGpsCache } from '../stores/sqliteStore';

export const LOCATION_TRACKING = 'mycartage-location-task';

export type LocationTask = {
    locations?: Array<Location.LocationObject>;
};

export const currentLocationTask = async ({
    data,
    error,
}: TaskManager.TaskManagerTaskBody<LocationTask>) => {
    try {
        if (error) {
            throw new Error(error.message);
        }

        if (!data) {
            throw new Error('Event has no data');
        }

        await storeGpsCache(data, 'LocationTask');
        const cachedData = await getGpsCache();
        console.log('__LOCATION_TRACKING__', cachedData);

        const resp = await sendGpsCurrent({
            method: 'POST',
            body: JSON.stringify({ cachedData }),
        });

        if (resp.ok) {
            await deleteGpsCache(cachedData.map((d) => d.id));
        } else {
            throw new Error(resp.statusText);
        }
    } catch (e) {
        console.log('Location Error:', JSON.stringify(e));
    }
    return;
};

`
