### ISSUE TITLE
Allow debugging using IntelliJ/WebStorm

### ISSUE THREAD

**Issue by raarts** [expo/expo#288]
I'd really like to use the IntelliJ debugger instead of the Chrome Tools debugger.
Not sure what needs to be done, where and by whom. So decided to create a ticket here.
There's an open ticket with Jetbrains [here](https://youtrack.jetbrains.com/issue/WEB-26951).

**Comment by terribleben** [comment]
Thanks for the suggestion! I'm not sure what exactly would be involved either but I strongly suspect this would be an upstream improvement to React Native, rather than to Expo.

If you think it's an Expo feature, we accept feature requests an upvotes on [canny](https://expo.canny.io/feature-requests), so please open something there if that makes sense. I'm closing this issue as we're hoping to keep this venue limited to issue reports.
