### ISSUE TITLE
useLocalSearchParams should not use Partial for params

### ISSUE THREAD

**Issue by rodrigorm** [expo/expo#28813]
### Minimal reproducible example

Does not have yet

### Which package manager are you using? (Yarn is recommended)

yarn

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

When using `useLocalSearchParams`, I am expecting to type the params according to its usage. For an route file like `app/[teamId]/(root)/(pickups)/pickups/[id]/index.tsx`, whe using the hook in typescript like below, I should expect `teamId` and `id` to be required and not optional as it is required in the route path, but the usage of `Partial` at [https://github.com/expo/expo/blob/main/packages/expo-router/src/hooks.ts#L102] forces me to use the non-null assertion `!` on every variable usage inside the page.

```typescript
const {
    id,
    teamId,
    status = "",
    type = "",
    position = "",
  } = useLocalSearchParams<{
    id: string;
    teamId: string;
    status?: string;
    type?: string;
    position?: string;
  }>();
  ```

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.17.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 9.6.7 - /usr/bin/npm
    npmPackages:
      expo: ~51.0.4 => 51.0.4 
      expo-router: ~3.5.12 => 3.5.12 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.11 => 0.19.11 
    npmGlobalPackages:
      eas-cli: 9.0.5
    Expo Workflow: managed

**Comment by marklawlor** [comment]
This is a limitation of TypeScript. TypeScript is not "file" aware, it doesn't know (or care) where the types are being used. The best "fix" to this I've seen is SveltKit, but that adds a layer of complexity I'm not sure that we want (e.g importing from a "magical" path instead of the module)

I'm going to close this as at this current time, we're not going to fix this - but that may change in the future

**Comment by rodrigorm** [comment]
Sorry, I dont get it. Why not just remove Partial from the useLocalSearchParams definition and allow developer to set its types?

**Comment by elfennani** [comment]
I upgraded expo-router, and now I have tons of files to "fix". I don't understand why you used `Partial`?

**Comment by simoncubera** [comment]
I agree with @rodrigorm and @elfennani, it's not clear to me why the `Partial<>` type-definition cannot be removed. Removing it would still allow to define optional parameters by explicitly specifying them as optional parameters using the `?` syntax. Or is there anything we're overlooking? Is there a chance this issue can be re-opened @marklawlor?

**Comment by kyliau** [comment]
Running into this issue, and I think it's worth a second look.
To be clear, we are referring to the type signature of `useLocalSearchParams`:
https://github.com/expo/expo/blob/32c14ee18c750002ea88166675223817415082b8/packages/expo-router/src/hooks.ts#L102-L104

Since it's a generic, it should be up to the developer to decide whether a property is optional, and not make the *entire* object `Partial`.
In fact, according to expo-router [docs](https://docs.expo.dev/router/reference/search-parameters/#route-parameters-versus-search-parameters):

> When the app/[user] route is matched, the user parameter is passed to the component and never a nullish value.

The `Partial` signature contradicts the statement above.

**Comment by marklawlor** [comment]
This is being address in https://github.com/expo/expo/pull/29612.  This removes the partial and also allows a route to be passed as a generic

```tsx
const params = useLocalSearchParams<'/folder/[slug]/[...catchAll]'>()
//    ^? params = { slug: string, catchAll: string[] } & Record<string, string | string[]>
```
