### ISSUE TITLE
Permissions : SDK 30.00 ios getting "Cannot access getAsync of undefined" when requesting Notification Permissions. Permission object is available while debugging.

### ISSUE THREAD

**Issue by shreyanshevince** [expo/expo#2885]
# READ THIS FIRST, PLEASE!

Hello! Thanks for reporting an issue. Please make sure you're posting this in the right place:

1. If this is an issue with Expo CLI, our command line tool, please post it in the
  https://github.com/expo/expo-cli repo instead.
2. If this is a feature request, please vote or post it at https://expo.canny.io instead.
3. If you are unable to create a reproducible Snack example that demonstrates the bug/issue,
  please first post in our forums at https://forums.expo.io/ before opening an issue here!
  (Unless the bug/issue pertains to a standalone, non-ejected build)

Thanks for helping us make Expo better!

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by quinlanj** [comment]
hey @shreyanshevince , thanks for reporting this issue. We need more information from you to help root cause your problem. First, we need a clear set of instructions from you, so we can reproduce the problem you are seeing. Can you please fill out the issue template? Second, we need a [snack](snack.expo.io) or a small app demo that shows this issue.

**Comment by pencilcheck** [comment]
Experiencing the same issue here: I'm on SDK 30.0.0, calling await Permissions.getAsync(Permissions.CAMERA_ROLL) gives me an error about Cannot read property getAsync of undefined, to my knowledge, Permissions of module 'expo' exists, but the ReactNative Proxy Permissions inside the Permissions (somehow they used the same name which adds more confusion, is somehow not defined....

**Comment by pencilcheck** [comment]
I don't know how to reproduce it, but it seems like detached expokit for SDK30 is incompatible with all the universal modules created in expo-permissions, expo-react-native-adapter, etc.

I was guessing because theoretically, if using cocoapods, all native modules should be linked and taken cared off but somehow it still doesn't work when calling from javascript side, so perhaps something in SDK 30 is interfering it?

**Comment by shubham-2710** [comment]
Hi ,
 I am getting below exception error when fetching contact using Contacts.getContactByIdAsync(id) , 
            Callback with id 1332: undefined.undefined() not found
            The callback callMethod() exists in module ExpoNativeModuleProxy, but only one callback may 
            be registered to a function in a native module.
SDK used is 32.0.0

**Comment by shreyanshevince** [comment]
Finally, I found the solution, the issue is Expo is exporting ExpoPermisions from the NativeModuleProxy in ExpoPermissions.js how ever NativeModuleProxy return **ExponentPermissions**. I used expo-permissions separately and changed the ExpoPermisions.js file in node-modules folder. May the issue is there because i upgraded from SDK 29 to SDK 30.
