### ISSUE TITLE
[SDK 51] promise.resolve(null) is throwing NullPointerException in java code

### ISSUE THREAD

**Issue by meteorlxy** [expo/expo#28941]
### Minimal reproducible example

https://github.com/meteorlxy/expo-51-repro

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

Yes

### Summary

`promise.resolve(null)` started to throw `NullPointerException` in java code since expo 51

<img width="269" alt="image" src="https://github.com/expo/expo/assets/18205362/8c5b8d0d-b030-4752-af9c-641f019d733f">

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/Library/Caches/fnm_multishells/46513_1715917422753/bin/node
      Yarn: 1.22.22 - ~/Library/Caches/fnm_multishells/46513_1715917422753/bin/yarn
      npm: 10.5.0 - ~/Library/Caches/fnm_multishells/46513_1715917422753/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/meteorlxy/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    Expo Workflow: bare

### Expo Doctor Diagnostics

Not related

**Comment by lukmccall** [comment]
Also, you can cast the null to Object to choose the correct version of the resolve function:
```java
promise.resolve((Object) null);
```
or
```Java
Object result = null;
promise.resolve(result);
```
It will force the compiler to choose the version that can handle nulls. We will not fix it because the new API was designed to work well with Kotlin, and we don't want to sacrifice anything, either DX or performance, to support all edge cases when interacting with Java. Unfortunately, the behavior you're seeing is not the only one that causes problems when using Kotlin code from Java. If you want to wrap existing Java code with our API, I would advise creating an abstraction layer that wouldn't use primitives from Expo, like promises, when passing data between languages. This gives you the most control.
