### ISSUE TITLE
Submitting iOS app through eas submit is failing because of a fastlane pilot error

### ISSUE THREAD

**Issue by surya-inbasagaran** [expo/expo#28956]
### Summary

![image](https://github.com/expo/expo/assets/123365066/b902d2ee-ed5b-4670-9475-791dd0f86175)

### SDK Version

47

### Environment

eas build --platform ios --auto-submit

### Minimal reproducible example

![image](https://github.com/expo/expo/assets/123365066/1ef3dbb8-b07d-451f-aa8c-31110a33b6fd)

**Comment by brentvatne** [comment]
hi there, this looks like you built your app using an older xcode version. see https://expo.dev/changelog/2024/03-29-eas-build-upcoming-ios-images-updates for context on why you need to use xcode 15 or greater. we don't change the image by default on very old projects, like sdk 47, because they may not build on the latest xcode version. you can try it as described in that post above, but you may need to upgrade to a more recent sdk version in order to submit your app. this is part of the cost of maintaining an app that is distributed on app stores.

**Comment by brentvatne** [comment]
i've updated our error detection to provide the same guidance that i gave above, but automatically inside of submission logs, to help prevent similar confusion in the future.

<img width="1089" alt="image" src="https://github.com/expo/expo/assets/90494/6ba51523-8303-4e50-ac01-251bbbf9f734">
