### ISSUE TITLE
[camera] torch not working

### ISSUE THREAD

**Issue by jamesthomp** [expo/expo#29095]
### Minimal reproducible example

https://snack.expo.dev/atz9lObk9ghMSvZh-cib6

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Using the new expo camera (not legacy), I'm not able to get the torch to work. See https://snack.expo.dev/atz9lObk9ghMSvZh-cib6 -- after loading, the torch does not come on in either iOS or Android devices.  You can uncomment a couple of lines to test the legacy camera and see that the torch does work there.

### Environment

Not relevant.

### Expo Doctor Diagnostics

Not relevant.

**Comment by alanjhughes** [comment]
Hi @jamesthomp - The torch cannot be started immediately during the first render as the camera has not been connected. I'm not sure what the use case would be for immediately starting the torch but you can use an effect to turn it on once the camera has rendered. The legacy camera can do this because of some inefficiencies in it's setup. These have been removed in the new package and as a side effect you will need to do it like this if you want this behaviour.

**Comment by jamesthomp** [comment]
Thanks for this explanation @alanjhughes. Is this behaviour of the props not applying if set before the first render exclusive to the torch prop or are there others that also need to be handled through the useEffect trick? It might be nice to add a warning to the documentation for anyone migrating given the difference in behaviour from the prior implementation.

In my case I "remember" the user preference for the torch, so if the torch was previously used then the torch prop is set even before the render, which is why I bumped into this when migrating
