### ISSUE TITLE
"Unhandled JS exception: Can't find variable: nil" After upgrading Expo

### ISSUE THREAD

**Issue by MarcusHurney** [expo/expo#291]
My project was working fine with Expo in the iOS simulator but after I upgraded, I get an error screen that says "there was a problem running expo" with an error at the bottom saying "Unhandled JS exception. Can't find variable: nil"

There was never a problem like this before the upgrade.

**Comment by terribleben** [comment]
Sorry about that. What happens if you completely delete the iOS app and reinstall it?

**Comment by MarcusHurney** [comment]
I am referencing the iOS simulator on Mac OS. I can view my project on the Expo iOS app as usual.

**Comment by terribleben** [comment]
I understand, my question is the same.

**Comment by MarcusHurney** [comment]
I deleted the iOS app and reinstalled it. Same result.

**Comment by terribleben** [comment]
Interesting. Does the error message happen as soon as the Expo app starts, or does it only happen when you try to open your project from XDE/exp?

**Comment by MarcusHurney** [comment]
It only happens when I try to open my project from the XDE. After deleting the iOS app and reinstalling it, I am now getting the same error in the iOS app. I open my project, the bundle builds, and for a moment my root component will render but then the error screen pops up:
<img width="373" alt="screen shot 2017-06-22 at 5 30 39 pm" src="https://user-images.githubusercontent.com/13347886/27461711-933c4c60-5770-11e7-8704-75a237412e4e.png">

**Comment by terribleben** [comment]
It seems like something somewhere in your app has managed to crash the Expo environment. That shouldn't happen, as we try to sandbox errors to the originating project.

This may be hard for me to debug without more specific info about the part of your project leading to this crash. You have a couple options:

1) Try to find the code in your app which causes this and let me know.
2) If you're willing, you can email me your app's source code (ben@expo.io) and I can try to help narrow the problem down for you. I probably won't have time to do this today but can follow up when I get a chance.

Also, just as a sanity check, you might want to double check that all your app's dependencies are installed correctly and you are running a new version of XDE or exp.

**Comment by huynhquocmy** [comment]
I got a problem with the newest version, when I scan the QR, I always get message
```
No experience found at exp://jv-k2w.myname.....
```

I did not change anything on my code till last success test.
I tried to uninstall and reinstall both mobile app and desktop exp app.
Please help.

**Comment by terribleben** [comment]
@huynhquocmy can you open a topic on the [forums](forums.expo.io) where somebody can help you out? I don't think that's the same problem.

**Comment by terribleben** [comment]
@MarcusHurney (I changed the issue name slightly to avoid having other people confuse this with similar symptoms.)

**Comment by leanminmachine** [comment]
Hey there I was gonna open an issue and I experienced the same problem, current version of expo is now 2.19.1 after i upgraded. I too have the "There was a problem running Expo." and unhandled js exception can't find variable nil. My project seems to be ok because using QR code to run my app on my phone works... just going to down grade until this bug is fixed :( More information, I am running on Host: Tunnel, Protocol: Exp, Tried switching development mode on and off but no difference for this.

**Comment by leanminmachine** [comment]
Hey guys I managed to fix this issue ☺️ 
You can try updating the package.json of your project

I realised that for my project, my dependency was expo: 16.0.0 or something like that,
i just had to change it to include newer versions ie.    "expo": "^18.0.4",

**Comment by lukevenediger** [comment]
I tried updating my expo dependency to "^18.0.4" and I get the same issue. I'm on 2.1.4 of Expo XDE and did an npm --install after updating. Any ideas?

**Comment by a-shark** [comment]
I have found that I can get past this maybe half the time in the simulator by holding the shake-gesture key combo down (repeatedly triggering it) right after I tap my app on the list to open it, until my app is fully running. _However_ if I try to trigger the shake-gesture debug menu after that, I get this crash again.

**Comment by a-shark** [comment]
This is _feeling_ like a change in an external dependency causing problems. My `node` and `npm` are `nvm`-managed and haven't changed in approximately _forever_ so that isn't it. Are there any other external tools `expo` depends on that might have been updated through Homebrew or something around that time?

**Comment by atMari** [comment]
I am also experiencing this exact issue.  The app started crashing and showing the `Can't find variable nil` after I upgraded to 2.19.1.   I have tried:

1. Updating my expo dependency to 18.0.4
2. Deleting Expo and re-installing 2.19.0
3. Switching to localhost instead of ngrok tunnel

and the error still remains.  None of these proposed fixes are working.

**Comment by a-shark** [comment]
Expo in my simulator, where I first encountered the problem, claims to be connecting to `localhost` already. On my phone, which initially worked but eventually started exhibiting the same seemingly-impossible-to-squash problem, it displays my local network address. AFAI can tell I've not been tunneling through `ngrok` at all. Client project so I can't supply it for testing, sorry.

**Comment by lukevenediger** [comment]
@terribleben sure thing, I'll send my project to you shortly.

**Comment by a-shark** [comment]
Update: I tried making a new create-react-native-app project to see whether that crashed too, and it didn't. So I tried my app again in the simulator... and now it's fine. Then I tried my existing (broken) project in Expo on my phone, but _without_ first loading the new CRNA app, and that _still displayed the error_.

Did the next obvious thing: loaded the new CRNA app on my phone via QR code. Worked. Tried mine again (all this without restarting the console/server for my app, without re-installing expo on my phone, and so on) and now it works. For some reason.

Loading the new CRNA app seems to reset _whatever_ is wrong with my existing project. Note that re-installing expo on simulator and phone, re-setting simulator, _re-creating_ the simulated device entirely, various nuke-it-from-orbit operations on my NPM packages and cache, and so on, _all failed_ to fix the problem, even temporarily. I have _exactly_ no idea why this worked, or where the problem is/was.

**Comment by lukevenediger** [comment]
Ok so I've put my code in a strange state and I'm not convinced the issue isn't something I've done. Resetting back to a known state and will report back @terribleben.

**Comment by atMari** [comment]
Thank you @a-shark!  This worked for me as well.  All I did was load an empty, brand new project into Expo and sent it to my iOS simulator.  Then, I closed that empty, new project and re-opened my current project. Boom. Everything magically works again.

**Comment by a-shark** [comment]
That I could sometimes bypass the error with a quick succession of shake-gesture commands makes me think "race condition". The timing of when the error popped up—a split second after the launch screen for my app loaded—and the fact that once I've successfully opened _any_ app the broken one is fine has me wondering whether the onboarding/education screen is to blame, somehow. Maybe my shakes-gestures worked around the problem because they kept that screen from loading (indeed, it didn't when that worked, it just went straight to my app). This could explain why it suddenly started happening on my phone, after working for a while—I probably re-installed Expo to reset my app's state, so it decided to show me the onboarding/edu screen again.

My best guess is some bad interaction between certain apps and that screen. Explains why it survives all kinds of cache-clearing and reinstalls (_of course_ it does) and such.

In fact, I just re-installed expo on my phone and sure enough, the problem's there again. Run the empty, new CRNA project, shows the onboarding screen, proceeds OK. Then try my app again, and it works. So yeah, signs point to that screen interacting poorly with certain projects.

**Comment by terribleben** [comment]
Thanks for the additional info. I still haven't managed to reproduce this, but the last few comments in this thread are helpful. Would love to ship a fix as soon as I can pin this behavior down.

In the meantime, for anybody perusing this thread, I guess the stopgap fix for now is @a-shark's [recommendation](https://github.com/expo/expo/issues/291#issuecomment-311167646) of loading a blank app and then reopening your project.

**Comment by a-shark** [comment]
Looks like the relevant term in the code is "nux" (new user experience?). If I'm reading this right and 1.17 came out ~5 days ago, that lines up with when this started happening, as best I can tell. I don't know enough about the codebase to do much else useful. Looked through some commit messages and diffs but nothing stood out. If you can give me instructions for a relatively quick/easy way to git-bisect against the iOS client with my known-bad project (again, can't just send it to you, unfortunately) I can try to find some time for that tomorrow, maybe get it pinned down to a particular commit.

**Comment by terribleben** [comment]
Ah, I think I might have found it: https://github.com/expo/expo/commit/d9707169fd708f068157155e374a5014e0ef3c6c#diff-603bdc42f8c2c2a16e9201e2ccbb9c57R314

This is rendered when the menu pops up in development mode (with or without the NUX). This is just my fault for jumping between objective-c and JS constantly. I will work on a fix and push it and we can see if that resolves the issue.

**Comment by a-shark** [comment]
Yeah, I think you got it. I can pull up that menu with a shake on my phone after doing the work-around, but it's not displaying the full debug menu, only the refresh/copy link/home options. In the simulator, where it apparently _does_ try to display the whole thing (it does so, successfully, in the new CRNA-initted app), triggering a shake gesture crashes it every time.

**Comment by terribleben** [comment]
The deeply complicated fix is [here](https://github.com/expo/expo/commit/85284117d423261cfed16dea9e622d33b0c9ec94), we'll deploy this over the air today if QA checks out.

**Comment by terribleben** [comment]
This is released - quit Expo on your device and reopen once or twice to make sure you have the update. (alternatively, get the iOS 1.17.1 simulator build from XDE/exp.)

Let me know if you're still seeing this issue after updating, and I'll reopen.
