### ISSUE TITLE
[windows] Test not running because spawnSync called with wrong parameters

### ISSUE THREAD

**Issue by DavideCanton** [expo/expo#2921]
### Environment

 Expo CLI 2.6.5 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD

### Steps to Reproduce

(Write your steps here:)

Install jest npm package
Follow steps to install jest-expo in jest-expo ReadMe file
Start project application using expo start
Create the following test in the 'tests' directory at the root of the project
Attempt to run test using npm test as directed in jest-expo ReadMe file

### Expected Behavior

Expected test to run

### Actual Behavior

> @ test <dir>
> jest

test are not run

I suppose that the problem is in the "jest-expo\package.json", at the lines:

`const jestPackageJson = require('jest/package.json');`
`const jestPackagePath = path.resolve(require.resolve('jest/package.json'), '..');`
`const jestProgramPath = path.resolve(jestPackagePath, jestPackageJson.bin.jest);`
`const jestProgramArgs = process.argv.slice(2);`
`const result = childProcess.spawnSync(jestProgramPath, jestProgramArgs, { stdio: 'inherit' });`

because jestPackageJson.bin.jest is "bin/jest.js", that can't be run by spawnSync.

I suppose that the correct line should be:

`const result = childProcess.spawnSync("node", [jestProgramPath, jestProgramArgs], { stdio: 'inherit' });`

With that, the tests are run.

**Comment by quinlanj** [comment]
hi @DavideCanton , I'm following the README instructions here https://github.com/expo/expo/tree/master/packages/jest-expo and my tests are to be running. Looking at your repro steps, can you ensure that:
1. your test directory is named `__tests__` instead of `tests`?
2. `__tests__` has a test js file with the basic jest test?

If your jest tests are still not running, could you let us know what steps you are running to get the empty test files (ie) i ran `npm test`, show contents of your tests, `package.json`, upload `tar.gz` of your project files, etc

**Comment by reggie3** [comment]
@quinlanj I ran into this same issue.  I changed the code in jest.js as @DavideCanton directed, and testing is working again.

Version info from my package.json:
"expo": "^31.0.2",
"jest-expo": "^31.0.0"

**Comment by Artorp** [comment]
I also have this problem on Windows 10, and changing the childProcess.spawnSync call makes jest start up as expected.

I suspect this isn't an issue on Linux or Mac since the script `jest-expo/node_modules/jest/bin/jest.js` starts with the shebang `#!/usr/bin/env node`, which will start jest with node as expected, while failing to execute the script on Windows.

**Comment by ide** [comment]
We have a fix for this on master and it will go out with SDK 33 (and maybe backported 32.0.1 but am having some npm permission issues).
