### ISSUE TITLE
export without source maps produces significantly larger byte code

### ISSUE THREAD

**Issue by iway1** [expo/expo#29243]
### Summary

When running 

```
expo export --source-maps --platform ios
```

We are seeing a much smaller byte code file being produced than when running:

```
expo export --platform-ios
```

![Screenshot 2024-05-31 at 10 56 51 AM](https://github.com/expo/expo/assets/12774588/3b7289bc-622e-40f7-86e1-e696f049052f)

With source maps ^

![Screenshot 2024-05-31 at 10 57 26 AM](https://github.com/expo/expo/assets/12774588/4bb766cd-84f2-4642-a187-2736301f929e)

Without source maps ^

I think there should not be a much larger bundle / byte code created when --source-maps is not passed

### What platform(s) does this occur on?

iOS

### SDK Version

50.0.19

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
      Yarn: 1.22.22 - ~/code/work/revdoc-mono/node_modules/.bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
      Watchman: 2023.09.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 9.0.6
    Expo Workflow: bare

### Minimal reproducible example

Any expo app, IE https://github.com/kanzitelli/expo-starter

**Comment by EvanBacon** [comment]
Can confirm this behavior. Will add my findings here.

1. The terminal logging is not an error, the output is larger.
2. With `--no-bytecode` enabled, both JS files are the same size. This means the issue is either with the pipeline or the HBC command. I suspect that the hbc command automatically inlines source maps when source maps aren't explicitly enabled. Skipping source maps is an optimization we added to Expo CLI to reduce unused work, but it might not be worth it.
3. I checked the HBC command help output to see if it indicated this behavior:
  4. `EXPO_DEBUG=1 npx expo export` prints the hbc command we use.
  5. `/Users/path/to/expo/node_modules/react-native/sdks/hermesc/osx-bin/hermesc -help` doesn't show anything about inlining source maps. Leading me to believe it may still be a hidden default.
6. When I decompile the hbc for both larger and smaller bundles, they both come out to be the same size! This could be the result of comments (inline source maps) getting removed on decompilation.
7. There's no plain-text comment at the end of the bin file so it's hard to confirm my theory, perhaps executing in an engine and throwing an error could show more results.

**Comment by EvanBacon** [comment]
@iway1 I opened a PR so if you can see how I approached this. Feel free to try in your own project and report back if error handling was still reasonable in production.

**Comment by tmikov** [comment]
This is not really about inlining source maps. Source maps are really orthogonal to the issue here. Hermes can consume a source map, if it is given to it, but this is almost never done by the existing tools, and even if it was, it does not affect the size of the generated bytecode file, it just affects the source locations.

This is something else entirely. Hermes bytecode by default always contains line number information, because that is required to generate proper stack traces.

If we take this source, for example:
```js
function foo() {
    throw Error("Noo!");
}
function bar() {
    foo();
}
bar();
```
We can compile it to bytecode:
```sh
$ hermesc -emit-binary prog.js -out prog.hbc

$ ls -l prog.hbc
-rw-r--r--  1 tmikov  staff  520 Jun  3 11:50 prog.hbc
```
And then run it:
```sh
$ hermes prog.hbc
Uncaught Error: Noo!
    at foo (prog.js:2:16)
    at bar (prog.js:5:8)
    at global (prog.js:7:4)
```
As you can see, we get a nice stack trace. This is not debug information, this is just expected functionality provided by all JS engines.

**Optionally**, it is possible to strip this line number information in order to get an even smaller binary. The `--output-source-map` CLI flag forces Hermes to save the line numbers information in a separate source map file:
```sh
$ hermesc -emit-binary prog.js -out prog.hbc --output-source-map

$ ls -l prog.*
-rw-r--r--  1 tmikov  staff  376 Jun  3 11:49 prog.hbc
-rw-r--r--  1 tmikov  staff  173 Jun  3 11:49 prog.hbc.map
-rw-r--r--  1 tmikov  staff   81 Jun  3 11:42 prog.js
```

Note that `prog.hbc` decreased from 520 bytes to 376 bytes. However if we run it now, we don't get a nice stack trace:
```sh
$ hermes prog.hbc
Uncaught Error: Noo!
    at foo (address at prog.hbc:1:63)
    at bar (address at prog.hbc:1:79)
    at global (address at prog.hbc:1:43)
```

The "columns" in the above stack trace are actually bytecode offsets. The engine no longer has access to the line numbers, so all it can do is dump numbers.

You can still get to the original lines, but you need to use the generated source map. For example:
```
$ npm install sourcemap-lookup

$ node ./node_modules/sourcemap-lookup/index.js prog.hbc:1:79

Original Position:
	prog.js, Line 5:7

Code Section:
1 | function foo() {
2 |     throw Error("Noo!");
3 | }
4 | function bar() {
5>|     foo();
           ^
6 | }
7 | bar();
8 |
``` 

So, it is up to the integrator whether to remove the line numbers and use the generated source map for symbolication of stack traces.
