### ISSUE TITLE
Updgrade to expo from 48 to the 51 cause an error with my image upload (Expo image picker, axios and Multer)

### ISSUE THREAD

**Issue by Lyesbcb** [expo/expo#29260]
### Minimal reproducible example

.

### What platform(s) does this occur on?

Android, iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

Hey, I just updgrade my expo from 48 to the 51 and I have an error with my image upload. 

I use on my mobile app :
    "expo-image-manipulator": "~12.0.5",
    "expo-image-picker": "~15.0.5",
    "axios": "^1.3.4",

And on my backend I use :
    "multer": "^1.4.5-lts.1",
    "multer-s3": "^3.0.1",

I don't change my code but after the upgrade of expo the image upload don't work anymore. Here my code :

// On my mobile app
  const addImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      aspect: [4, 4],
      allowsEditing: true,
    });

    if (!result.canceled) {
      const { uri } = result.assets[0];
      const compressedImage = await ImageManipulator.manipulateAsync(
        uri,
        [{ resize: { width: 512, height: 512 } }],
        { compress: 0.8, format: ImageManipulator.SaveFormat.JPEG }
      );

      setItemDTO(prev => ({ ...prev, image: compressedImage.uri }));
    }
  };

    let data = new FormData();

    data.append('file', {
      uri: itemDTO.image,
      name: itemDTO.image,
      type: 'image/jpg'
    });

async function createItem(item: FormData, token: string): Promise<CreateItemResponse | undefined> {
    const axiosConfig = getAxiosConfig(token, {
        headers: { 'Content-Type': 'multipart/form-data' }
    });

    try {
        console.debug("item::createItem", JSON.stringify(item));
        const response: AxiosServerResponse<CreateItemResponse> = await axios.post(API_URL, item, axiosConfig);
        return response.data.data;
    } catch (error: any) {
        console.error("item::createItem", error);
        throw error;
    }
}

// On the backend 

import { S3Client } from '@aws-sdk/client-s3';
import multer from 'multer';
import multerS3 from 'multer-s3';
import dotenv from 'dotenv';

// Créer une nouvelle instance S3
const s3 = new S3Client({
  credentials: {
    secretAccessKey: process.env.S3_ACCESS_KEY ?? '',
    accessKeyId: process.env.S3_ACCESS_ID ?? '',
  },
  region: process.env.S3_REGION ?? ''
});
// Configurer Multer pour utiliser S3
const upload = multer({
  storage: multerS3({
    s3: s3,
    bucket: process.env.S3_NAME ?? '',
    metadata: function (req, file, cb) {
      file.originalname = file.originalname.split('?')[0];
      cb(null, { fieldName: file.fieldname }); 
    },
    key: function (req, file, cb) {
      file.originalname = file.originalname.split('?')[0]; 
      const extension = file.originalname.split('.').pop(); 
      const fileName = Date.now().toString() + '.' + extension; 
      cb(null, fileName);
    }
  })
});

export default upload;

### Environment

<img width="702" alt="image" src="https://github.com/expo/expo/assets/94790249/96465fa1-197f-43fe-ac8b-62aaf9f0fe67">

### Expo Doctor Diagnostics

<img width="879" alt="image" src="https://github.com/expo/expo/assets/94790249/335d6185-ceb6-4644-9f97-dd51d0eb6ff1">

**Comment by khushal87** [comment]
Hey @Lyesbcb, did you find a fix? I see this issue on iOS as well. Though for android it works fine for me.

**Comment by Lyesbcb** [comment]
> Hey @Lyesbcb, did you find a fix?

Yes ! It's a issue with the name of the file. I don't realy know why but before the update there is no issue with the same name and after the update there is this issue with the name of the file when I create the FormData !

**Comment by JonathanYeeW** [comment]
I ran into a similar issue recently, so I’m sharing my notes here in case it helps anyone down the line. ❤️

## The Issue

The problem appeared after upgrading from Expo 49 to 52, which also updated `expo-camera` from version 13 to 16. Suddenly, my server’s Multer file handler wasn’t processing images correctly anymore. It seemed like the file didn’t exist in the form at all.

### The Setup

Multer is built on top of Busboy, which is responsible for parsing the parameters in the form-data and writing the stream. 

**Before Expo 52 (Expo 49):**

```plaintext
content-disposition: form-data; name="file"; filename="123::upload.jpg"
```

**After upgrading to Expo 52:**

```plaintext
content-disposition: form-data; name="file"; filename="123::upload.jpg"; filename*=utf-8''123::upload.jpg
```

Notice the new addition: `filename*`. What’s going on here?

## What Is `filename*`?

- The `filename` attribute by itself only supports **ASCII** characters.
- `filename*` allows specifying a **character set** (e.g., `utf-8`), ensuring filenames with non-ASCII characters are parsed correctly.

You can see how this is handled in Busboy’s code:
[Here is where Busboy processes the `filename*` attribute](https://github.com/mscdex/busboy/blob/6b3dcf69d38c1a8d53a0b3e4c88ba296f6c91525/lib/utils.js#L233).

## The Issue with `::` in Filenames

In my case, the problem was due to the use of `::` as a delimiter in filenames. 

- **Busboy doesn’t handle extended encoding for `filename*` well in this scenario.**
- [Here is where Busboy fails to properly handle this](https://github.com/mscdex/busboy/blob/6b3dcf69d38c1a8d53a0b3e4c88ba296f6c91525/lib/utils.js#L279-L301).
- `filename*` falls into the **"extended value"** category, which only properly handles the `%` encoding edge case.

When `Busboy` encounters the `:` delimiter, it halts processing because it doesn’t recognize the character as part of the valid encoding. The logic is: "Hmm, this isn’t `%`, so I’ll just stop here."

## Solutions

### Solution 1: Change How You’re Delimiting Filenames

This is the simplest fix and the one that worked for me. By removing the `::` delimiter from my filenames, the server started processing the form data correctly again.

However, I understand this might not be feasible for everyone—especially if your infrastructure relies on specific filename formats or delimiters.

### Solution 2: Update the `filename*` Encoding

You could try updating the `filename*` encoding to something simpler, like **ASCII**. 

[Here’s where Busboy manages this encoding](https://github.com/mscdex/busboy/blob/6b3dcf69d38c1a8d53a0b3e4c88ba296f6c91525/lib/utils.js#L391-L402).

However, I didn’t pursue this solution because Solution 1 resolved my issue. From what ChatGPT explained, this solution might require custom handling for HTTP headers because everything defaults to `UTF-8` under the hood, and overriding that isn’t straightforward.

---

I hope this helps anyone running into a similar issue!
