### ISSUE TITLE
expo-task-manager stopped working after expo upgraded from expo version 50 to 51

### ISSUE THREAD

**Issue by Rohit-Parte** [expo/expo#29558]
### Minimal reproducible example

https://github.com/codybutz/test-location-app/blob/main/App.js

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

~Yes~ No (Tested in Expo Go)

### Summary

Reproducible code was working perfectly before upgrade expo version from 50 to 51.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22000
    Binaries:
      Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~51.0.11 => 51.0.11
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by brentvatne** [comment]
@Rohit-Parte - can you explain your exact repro steps?

**Comment by vonovak** [comment]
Hello and thanks for reporting,
@Rohit-Parte the reproduction you linked is using Expo SDK 39. Are you sure you attached the correct repro? Can you verify this with SDK 51? Also, what are the steps to reproduce? Having this information will enable us to resolve this.
Thank you

**Comment by Rohit-Parte** [comment]
Hi @vonovak, I'm using exact same code which i mentioned in repo with expo version 51. It was working very smoothly on 50, but suddenly stopped working in 51.
As per my analysis, there is no change in task manager setup, so you can try exact by copying and pasting above code with latest expo SDK.

**Comment by vonovak** [comment]
@Rohit-Parte thanks for the response. When you say it's "not working" what exactly does that mean?
Could you maybe record a video that shows what steps you take to get the issue, and shows what the issue is also? Or describe in a more detailed way what the issue is?

Thank you 🙂

**Comment by Rohit-Parte** [comment]
@vonovak Stopped working as in, task is getting defined but it won't trigger in foreground and background.

**Comment by vonovak** [comment]
> @vonovak Stopped working as in, task is getting defined but it won't trigger in foreground and background.

Okay thank you. Let me ask a bit more: are you getting this issue on a real device (what device?). Do you have location access enabled in settings? 
Thank you

**Comment by Rohit-Parte** [comment]
@vonovak I'm facing issues on expo go, production version as well with different devices as well. 
Location settings is enabled with allow all the time. Actually, I went through Discord, some other people are also had same issue after upgrade.

**Comment by vonovak** [comment]
> @vonovak If required, I can create separate repo with latest expo as well. Because resolving this issue is very important for me. My whole tracking functionality is broken.

Hello @Rohit-Parte 
I'm unable to reproduce the issue from the repo that you shared after upgrading it to SDK 51. It'd be great for me to have the exact same base setup that exhibits the issue for you. Would you please create a reproduction using SDK 51? 

When you create your repro, you'll need to change how permissions are requested because `expo-permissions` is no longer used for that. Instead you'll likely need something this:

```
      const { status: foregroundStatus } = await Location.requestForegroundPermissionsAsync();
      console.log({foregroundStatus})
      if (foregroundStatus !== Location.PermissionStatus.GRANTED) {
        return
      }

      const { status: backgroundStatus } = await Location.requestBackgroundPermissionsAsync();
      console.log({backgroundStatus})
      if (backgroundStatus !== Location.PermissionStatus.GRANTED) {
          return
      }
```

Thank you! :)

**Comment by Rohit-Parte** [comment]
Hi @vonovak Please check this repo

https://github.com/Rohit-Parte/expo-task-manager-debug

**Comment by vonovak** [comment]
@Rohit-Parte in the original bug report, you reported that you're using a [development build](https://docs.expo.dev/develop/development-builds/introduction/), not Expo go. Hence I was reproducing this with a development build.

If you use development build, the issue was in missing permissions, which you can add [like this](https://github.com/Rohit-Parte/expo-task-manager-debug/pull/1). Permissions were also present in the [original repro](https://github.com/codybutz/test-location-app/blob/cc370ec3089f7afeb822b7baf12eeba36a043deb/app.json#L33).

Does this resolve the issue?

**Comment by Rohit-Parte** [comment]
Hi @vonovak , After adding permissions in app.json also not working in expo go. 

I've triggered eas build, once done will check that development build again.

**Comment by vonovak** [comment]
hello, I suggest you run the `android` [script](https://github.com/Rohit-Parte/expo-task-manager-debug/blob/a375bf01c1cdd824ddec66be6f9003bb65777d10/package.json#L7).

**Comment by Rohit-Parte** [comment]
@vonovak Yes it is resolved on eas build apk. Issues was with permissions only.

Thanks for your support!

**Comment by kiorq** [comment]
I'm having this issue with iOS preview build, seems bot background fetch and notify remote doesn't work. I assume it wouldn't work in expo go because the docs mentioned so?

**Comment by vonovak** [comment]
Hello!
To follow up on this:

expo-location won't work on Expo go on Android because foreground and background services are not available in Expo Go for Android: [docs](https://docs.expo.dev/versions/latest/sdk/location/#android). So the behavior @Rohit-Parte is seeing is expected.

@kiorq for your question: please open a new issue and include the necessary details, your question seems to be separate from the original one in this issue.

Thank you 🙂
