### ISSUE TITLE
[docs] OAuth guides for Google use react-native-google-signin

### ISSUE THREAD

**Issue by oddanderson** [expo/expo#29553]
### Summary

Currently all OAuth guides on Expo recommend using react-native-google-signin. However, this project puts known core functionality behind a paywall.

Specifically, react-native-google-signin does not support web authentication. The creator has built web support, but only makes the functionality available to sponsors. See thread [here](https://github.com/react-native-google-signin/google-signin/issues/1149).

I don't think Expo guides should recommend using a 3rd party library for something as core as OAuth if that library is gating functionality behind a paywall. This is not the case for any other OAuth guide, and the original Google OAuth guide, using `expo-auth-session` has been taken down despite having out-of-the-box support for all three platforms (iOS, Android, and Web). 

### Link to the related docs page

https://docs.expo.dev/guides/google-authentication/

**Comment by brentvatne** [comment]
hey @oddanderson - we recommend this library because it is the only one high quality library that i am aware of that provides the functionality of wrapping the google sign in SDK. i understand it can be frustrating to run into a paywall for some functionality, and i certainly don't think it's ideal, but if that exists in this case then perhaps it's because there was no other way of receiving financial support to maintain the package - and it's better for part of the functionality to be paywalled than to have no package at all.

**Comment by brentvatne** [comment]
unfortunately, `expo-auth-session/providers/google` is deprecated ([see notice](https://docs.expo.dev/versions/latest/sdk/auth-session/#google)) - but it's pretty stable so if you copy the implementation over to your project you should be able to keep using it indefinitely and make any adjustments as needed.

we think the best way to integrate with google auth is with the native google sdk, this provides the experience that folks expect in native apps. you could use the native sdk on ios/android and create a `.web.ts` file that handles the different behavior for web. perhaps in the near future the maintainer will make the google-signin library completely open source! in the meantime, apologies for the quirks - we have to prioritize our focus and wrapping third party services is something that just hasn't proven to be a good use of our time in the past.
