### ISSUE TITLE
ANDROID - TypeError: Cannot read property 'NativeModule' of undefined, js engine: hermes When upgrated to new react native and expo packages

### ISSUE THREAD

**Issue by murugeshnadar** [expo/expo#29568]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by mendozammatias** [comment]
Any solution for this error? I'm getting the same one after upgrading.

**Comment by mukash** [comment]
Getting same after updating to react-native 0.74.4

**Comment by WKampel** [comment]
Same error on 0.74.5, but only with development build (expo go works fine).

**Comment by billomore** [comment]
same here. 
```json
"expo": "~51.0.24",
"react-native": "0.74.5",
```

works fine on iOS, the fail occurs on Android only

**Comment by murugesh-iqvia** [comment]
I am using [react-native-biometrics] for my Project and For Face ID only I used expo and [expo-local-authentication] But when I upgraded the react_native version to latest it started giving issue. Now, I removed the expo and [expo-local-authentication] from the project and used a custom solution. 

I created FaceIDModule.kt & MyReactPackage.kt files and linked it in the MainApplication.kt. In React Native code i imported the FaceIDModule kotlin module using NativeModules and it works like how [expo-local-authentication] used to work.

I am attaching the files will have to be renamed to .kt instead of .txt. 

[FaceIDModule.txt](https://github.com/user-attachments/files/17265459/FaceIDModule.txt)
[MyReactPackage.txt](https://github.com/user-attachments/files/17265461/MyReactPackage.txt)

In MainApplication.kt you have to link "add(MyReactPackage())" like below

PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
              add(MyReactPackage())
}

In React Native attach is the changes on how to trigger the Face ID will have to be renamed to .tsx instead of .txt. 
[App.txt](https://github.com/user-attachments/files/17265480/App.txt)

**Comment by murugeshnadar** [comment]
I am using [react-native-biometrics] for my Project and For Face ID only I used expo and [expo-local-authentication] But when I upgraded the react_native version to latest it started giving issue. Now, I removed the expo and [expo-local-authentication] from the project and used a custom solution. 

I created FaceIDModule.kt & MyReactPackage.kt files and linked it in the MainApplication.kt. In React Native code i imported the FaceIDModule kotlin module using NativeModules and it works like how [expo-local-authentication] used to work.

I am attaching the files will have to be renamed to .kt instead of .txt. 
[FaceIDModule.txt](https://github.com/user-attachments/files/17265538/FaceIDModule.txt)
[MyReactPackage.txt](https://github.com/user-attachments/files/17265539/MyReactPackage.txt)


In MainApplication.kt you have to link "add(MyReactPackage())" like below

PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
              add(MyReactPackage())
}

In React Native attach is the changes on how to trigger the Face ID will have to be renamed to .tsx instead of .txt. 
[App.txt](https://github.com/user-attachments/files/17265541/App.txt)
