### ISSUE TITLE
Expo Camera barcodeScanner returns incorrect bounds based on device orientation

### ISSUE THREAD

**Issue by henryornellas** [expo/expo#29762]
### Minimal reproducible example

https://snack.expo.dev/@henry_ornellas/curious-orange-mixed-nuts

### What platform(s) does this occur on?

Android

### Did you reproduce this issue in a development build?

No (tested in Expo Go)

### Summary

While using `CameraView`, `onBarcodeScanned` returns the wrong boundingBox coordinates when in **portrait** mode.

For testing: with the provided snack, scan any `code128` barcodes in portrait, and then landscape.

Example:

https://github.com/expo/expo/assets/106675861/77a41939-362c-43e1-9a39-1f54c2ef5eba

~Typing of `BarcodeScanningResult` is also wrong.~

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.20.3 - C:\Program Files\nodejs\node.EXE
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^51.0.14 => 51.0.14
      expo-router: ~3.5.16 => 3.5.16
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.2 => 0.74.2
    Expo Workflow: managed

### Expo Doctor Diagnostics

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

**Comment by chunghn** [comment]
Similar issue. In my case, I managed to make boundingBox in portrait orientation. But in landscape mode the data is screwed.

Noted that I locked device orientation with expo-orientation

Ref
```js
      //  check android barcode bounds
    } else if (barcode.boundingBox !== undefined) {
      barcodeBounds = {
        height: barcode.boundingBox.size.width,
        width: barcode.boundingBox.size.height,
        left:
          width - barcode.boundingBox.origin.y - barcode.boundingBox.size.width,
        top: barcode.boundingBox.origin.x,
      }
    }
```

**Comment by igoro00** [comment]
Same problem here.

It's because currently screen orientation has nothing to do with how the barcode is scanned and how the corner points are processed. The orientation is taken from [rotationDegrees](https://developer.android.com/reference/androidx/camera/core/ImageInfo#getRotationDegrees()) which are also used for creating EXIF data when taking pictures. 
https://github.com/expo/expo/blob/b62618a8f99582621e1252c7a8013c62e1c6e013/packages/expo-camera/android/src/main/java/expo/modules/camera/analyzers/BarcodeAnalyzer.kt#L36-L39

FYI `CameraViewHelper.getCorrectCameraRotation` seems to calculate discrete up,down,left,right values based on rotation.

Maybe I'm wrong but IMO the only real use case for corner points and bounding box is to show that to the user as an overlay. And for that we need it tied to the screen orientation and not physical orientation. Or at the very least we need to somehow get that info to javascript so we can process it ourselves.

**Comment by igoro00** [comment]
Update: Since my app is always portrait anyway I decided to hardcode the angle for now.
Here's my patch:

```
diff --git a/android/src/main/java/expo/modules/camera/analyzers/BarcodeAnalyzer.kt b/android/src/main/java/expo/modules/camera/analyzers/BarcodeAnalyzer.kt
index 8d3f8796363d4a42b440add55b2506cb0d4d556c..1328f41ac3668d41c2c5ded3e3542080ff1db5b7 100644
--- a/android/src/main/java/expo/modules/camera/analyzers/BarcodeAnalyzer.kt
+++ b/android/src/main/java/expo/modules/camera/analyzers/BarcodeAnalyzer.kt
@@ -33,7 +33,8 @@ class BarcodeAnalyzer(private val lensFacing: CameraType, formats: List<BarcodeT
     val mediaImage = imageProxy.image
 
     if (mediaImage != null) {
-      val rotation = CameraViewHelper.getCorrectCameraRotation(imageProxy.imageInfo.rotationDegrees, lensFacing)
+      val rotation = CameraViewHelper.getCorrectCameraRotation(90, lensFacing)
       val image = InputImage.fromMediaImage(mediaImage, rotation)
 
       barcodeScanner.process(image)

```

It was created using bun patch but you probably can patch that using other tools. Idk if custom patches work in EAS. I build apks on my own infra (docker image + some scripts) and patches are applied automatically with every `bun install`.

**Comment by phuoctai12t** [comment]
> Similar issue. In my case, I managed to make boundingBox in portrait orientation. But when I rotate the phone to landscape the data is screwed.
> 
> Noted that I locked device orientation with expo-orientation
> 
> Ref
> 
> ```js
>       //  check android barcode bounds
>     } else if (barcode.boundingBox !== undefined) {
>       barcodeBounds = {
>         height: barcode.boundingBox.size.width,
>         width: barcode.boundingBox.size.height,
>         left:
>           width - barcode.boundingBox.origin.y - barcode.boundingBox.size.width,
>         top: barcode.boundingBox.origin.x,
>       }
>     }
> ```

Thanks, this solution works for me.
