### ISSUE TITLE
CLI can't install pods

### ISSUE THREAD

**Issue by budzHors7** [expo/expo#29956]
### Summary

I'm trying to create a build locally but every time I do a prebuild, I get this error.

### What platform(s) does this occur on?

iOS

### SDK Version

51

### Environment

`bunx expo prebuild -p ios --clean`

(node:13840) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Your git working tree is clean

To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard
✔ Cleared ios code
✔ Created native directory
✔ Updated package.json | no changes
✔ Finished prebuild
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+rb_sysopen+-+%2FUsers%2Fbudzhors7%2F.cocoapods%2Frepos%2FSpec_Lock&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

pod install --repo-update --ansi exited with non-zero code: 1

### Minimal reproducible example

https://github.com/budzHors7/Expo-Authentication-SDK-51

**Comment by byCedric** [comment]
Hi @budzHors7! Unfortunately, your issue seems environment related. The output you mentioned contains information about the underlying cocoapods error that was thrown:

```
Permission denied @ rb_sysopen - /Users/budzhors7/.cocoapods/repos/Spec_Lock
```

> From the first URL after "Search for existing GitHub issues similar to yours:" ([this URL](https://github.com/search?q=repo%3ACocoaPods%2FCocoaPods+Permission+denied+%40+rb_sysopen+-+%2FUsers%2Fbudzhors7%2F.cocoapods%2Frepos%2FSpec_Lock&type=Issues))

This is likely related to cocoapods not having access to your `/Users/<user>/.cocoapods` folder. Might have been caused by a `sudo pod install` run.

You'd either have to:
- Install the cocoapods yourself with root permissions: `cd ./ios && sudo pods install --allow-root`
- Fix the permissions of your cocoapods folder, e.g. with https://stackoverflow.com/a/17542841

Expo does not support running cocoapods with sudo privileges.

Hope this helps!

**Comment by budzHors7** [comment]
Thanks @byCedric, it works now and by using these commands.

`sudo chown -R $USER ~/Library/Caches/CocoaPods`

`sudo chown -R $USER ~/.cocoapods`
