### ISSUE TITLE
Expo CLI suddenly started giving 401 errors and can't npx expo login anymore.

### ISSUE THREAD

**Issue by eusouoviana** [expo/expo#29973]
### Summary

Here's a video demo: https://www.loom.com/share/948f9ea4ecba4abdba6ba81ffbfdead9

### What platform(s) does this occur on?

Android, iOS, Web

### SDK Version

51.0.14

### Environment

[I] ❯ 21 ❯❯  main ❯❯ ✔ ❯ npx expo-dev-info                                                                                                                                  ❮ + ✱ ● ✭ ❮❮ ~/W/F/App ❮
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/expo-dev-info - Not found
npm ERR! 404
npm ERR! 404  'expo-dev-info@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/joaopedroviana/.npm/_logs/2024-06-24T14_47_15_265Z-debug-0.log

### Minimal reproducible example

Here it goes: https://www.loom.com/share/948f9ea4ecba4abdba6ba81ffbfdead9

**Comment by byCedric** [comment]
Hi @eusouoviana! In your video, the CLI logged the general message that it can't reach the Expo server:

<img width="1016" alt="image" src="https://github.com/expo/expo/assets/1203991/e60106c0-947e-4d1f-88e2-ba79b86ae1ad">

This indicates that something is wrong connecting to endpoints like https://api.expo.dev/v2/versions. If you can access this in the browser, you might be using a proxy through the CLI that can't access Expo.

For now, you could use `npx expo start --offline` to use Expo without using any of the services. Unfortunately, this is not something we can fix since it's related to your connection.

Hope this helps!
