### ISSUE TITLE
Fast reload is not working 

### ISSUE THREAD

**Issue by Beki78** [expo/expo#30105]
### Minimal reproducible example

https://github.com/Beki78/haleta

### Which package manager are you using? (Yarn is recommended)

npm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

None

### Summary

it is weird that  the fast reload is not working when you use your component name in small letter but works in uppercase like this 
![image](https://github.com/expo/expo/assets/146061009/ad0669f4-9028-47ab-87ba-4208c40f5316)
but the below image is not working it redirects you back to the initial screen or the index screen which is really annoying
![image](https://github.com/expo/expo/assets/146061009/8ceafc50-a3ba-4c8a-86d1-0d7f12ce1bf9)
 fix this or add a short description in the documentation 

### Environment

![image](https://github.com/expo/expo/assets/146061009/654864cd-ec4e-4498-bcaa-058b922ac266)

**Comment by marklawlor** [comment]
This is expected behaviour and comes from the `[react-refresh](https://www.npmjs.com/package/react-refresh)` library. The JSX specification states that all user defined components need to start with a capital letter. If you don't follow the specification, then React cannot guarantee you are updating a component, hence it will fall back to a full app reload.
