### ISSUE TITLE
expo-asset requires expo-file-system package to be installed and linked

### ISSUE THREAD

**Issue by gabriel-TheCode** [expo/expo#3027]
### Environment

* Android device & emulator
* iOS device & emulator

### Steps to Reproduce

1. add @expo/vector-icons
2. add expo-font
3. add expo-constants
4. add expo-file-system

### Expected Behavior

It should compile and run without an error

### Actual Behavior

When I run my app "expo-asset requires expo-file-system package to be installed and linked"

![expo error](https://user-images.githubusercontent.com/26333609/50225076-cddce500-039f-11e9-9011-82fc24a51f36.PNG)

When I try to fix the error by adding this code below in App.js

 ```
 componentDidMount() {
    require("expo-file-system").FileSystem
  }

```
it show me another error: "undefined is not an object (evaluating 'FS.documentDirectory')".

**Comment by gabriel-TheCode** [comment]
https://github.com/jtaylor1989/Zopher/issues/1#issuecomment-449126362

**Comment by MichaelQ1an** [comment]
@gabriel-TheCode How did manage to get it solved? I'm having the same problem but I can't solve it with the your reference to Zopher. Could you be a little more specific?

**Comment by gabriel-TheCode** [comment]
npm install react-native@0.55.2

This will resolve your problem

**Comment by sarveshcchauhan** [comment]
@gabriel-TheCode 

Not working displaying 
`rror: Cannot find module './bundle/unbundle'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\rnp\myapp\node_modules\react-native\local-cli\commands.js:44:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (D:\rnp\myapp\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader (D:\rnp\myapp\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)`

**Comment by gabriel-TheCode** [comment]
I think this problem is more complicated than it seems since it results from a package conflict, so the way to solve it will necessarily be different.

**Comment by sarveshcchauhan** [comment]
@gabriel-TheCode  I have tired adding multiple expo package but none of them works even Icons are not working displaying the same error shown above

**Comment by YanRevuz** [comment]
I have the same problem :(

**Comment by brentvatne** [comment]
it sounds like OP here is trying to use @expo/vector-icons in a bare react-native project. We have only recently started supporting this workflow and it's experimental, but I have created an example project for you.

1. `expo init VectorIconsExample --template bare-minimum`
2. `cd VectorIconsExample`
3. `yarn add expo-font @expo/vector-icons`
4. `cd ios` and then `pod install`
5. `open VectorIconsExample.xcworkspace`
6. Run the project.
7. Open `App.js` and change it to something like this: https://github.com/brentvatne/vector-icons-example/blob/master/App.js

If you follow the above, it will work as expected. I only set up iOS here but to set up on Android you only need to do [this one additional thing](https://github.com/expo/expo/blob/r/packages/expo-font/README.md#configure-for-android).

If you want to use expo-asset, expo-permissions, or expo-file-system then you can import them as usual because in the `bare-minimum` template we use `react-native-unimodules` which includes all of these - see https://github.com/unimodules/react-native-unimodules#api
