### ISSUE TITLE
[Question] Using a react native library outside of Cocoapods

### ISSUE THREAD

**Issue by danielravina** [expo/expo#303]
Hi! Loving expo so far. I only have one problem with adding [react-native-youtube](https://github.com/inProgress-team/react-native-youtube)
I followed their installation instructions:
```
react-native link
rnpm link
```
And I'm trying to expose it to expo but without much success.
I keep getting this error from the app:
```
Warning: Native component for "RCTYouTube" does not exist
```
I followed the guide here: https://docs.expo.io/versions/v18.0.0/guides/expokit.html And I don't really understand this part:
> You’ll want to determine the relative path from your library to Pods/Headers/Public.

Can you give an example of how this would work? Tried so many different things (noob with xcode)
I even tried to sym link the library code to the public pods 
```bash
$ cd ios
$ ln -s ../node_modules/react-native-youtube/ Pods/Headers/Public/RCTYouTube
```
And add the path to it like: 
<img width="518" alt="screenshot_2017-06-25__11_20_pm" src="https://user-images.githubusercontent.com/3150871/27526796-f1af0826-59fc-11e7-8ac5-27b33fe5f252.png">

How do I make the two work together? Thanks!

**Comment by dikaiosune** [comment]
Hi! In general we'd like to make this process smoother (c.f. https://github.com/expo/expo/issues/254). I'll ping @terribleben here in case there's something we can do to make these docs clearer.

**Comment by terribleben** [comment]
Hey there, yeah, I don't know if I'll be able to help debug this specific YouTube library issue. It actually doesn't seem like you are having any problems finding headers, otherwise your project wouldn't build at all. It seems like there is an issue at runtime where the YouTube component isn't getting exported correctly. So I don't think this is related to CocoaPods necessarily.

If you're still blocked, I think your best course of action is to raise the topic on our [forums](forums.expo.io) and see if anybody there can help you out.

**Comment by chenkaiC4** [comment]
my way is that:

1. react-native link package   (for android)
2. git checkout ios/*   (important! remove change of ios, because we will set it by pod)
3. vim ios/Podfile, add pop config, like

```
pod 'react-native-orientation',
      :path => "../node_modules/react-native-orientation"
```
4. pod install

works fine!
