### ISSUE TITLE
Xcode Unsupported Swift Version

### ISSUE THREAD

**Issue by gkasireddy202** [expo/expo#30337]
### Minimal reproducible example

Company repo

### What platform(s) does this occur on?

iOS

### Did you reproduce this issue in a development build?

Yes

### Summary

I added the "expo": "^50.0.17", "expo-local-authentication": "^13.8.0", in my project.I got the below error when i open the Xcode.

the target “AppnameAppTests” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.
 
Use Xcode 10.1 to migrate the code to Swift 4.
 and 

### Environment

react-native version:0.73.7
Xcode:Version 15.1 (15C65)

### Expo Doctor Diagnostics

<img width="347" alt="Screenshot 2024-07-11 at 1 22 20 PM" src="https://github.com/expo/expo/assets/90603484/9365d1cd-1e79-4b24-ba50-b9cc3de8712d">

**Comment by shuo-hiwintech** [comment]
I opened Xcode with the react native cli project npx install-expo-modules@latest and ran into the same problem.

My version:

Xcode: 15.3 react-native: 0.74.2
expo: ^51.0.18

**Comment by vonovak** [comment]
Hello and thanks for reporting,
Most likely, what's happening is that your app had an existing `AppnameAppTests` target and the target contains old swift code. That is code in your repository, inside your app. If you delete the code and try again, or migrate it to swift 4, that should resolve your issue.
Hope this helps 🙂

I'm going to close this because the issue doesn't follow the issue template and some important information is missing.

**Comment by gkasireddy202** [comment]
We don't have to run any test cases in our app.
After upgrading the expo I got this message.

**Comment by vonovak** [comment]
@gkasireddy202 please see https://github.com/expo/expo/issues/30378
