### ISSUE TITLE
[docs] Discrepancy between headerStyle of Tabs and Stack

### ISSUE THREAD

**Issue by baltagih2** [expo/expo#30339]
### Summary

`Tabs` from expo router allow in their `screenOptions` to pass a `headerStyle` prop accepting regular styles. On the other hand, `headerStyle` in the `Stack`'s `screenOptions` only accepts `backgroundColor` as a style.

This means that if for example we need to set `borderBottomWidth: 1` on headers across the app to set a clear separation, we would only be able to do it on the initial screen of the tabs and would need to create a custom header component for the rest of the app.

Here's a small example:

```
import { Tabs } from 'expo-router';

 <Tabs
    screenOptions={{
      headerStyle: {
        borderBottomWidth: 1, // This works perfectly
      },
    }}
  >
{...tabs}
</Tabs>

 <Stack
    screenOptions={{
        headerStyle: {
          borderBottomWidth: 1, // This is not allowed
        },
    }}
  >
{...stacks}
</Stack>
```

I understand that we can create a custom header component so this is not a bug but it would be good to have a consistent setup to be able to apply shared header styles across the app

### Link to the related docs page

https://docs.expo.dev/router/advanced/stack/#statically-configure-route-options

**Comment by gorbypark** [comment]
I believe this is because Stack (as exported by expo-router) is using a react-navigation native stack and bottom-tabs uses a "regular" react-navigation stack (non-native JS based).

The native stack has less options because it can only do what an actual native header can.  If you check out the react-navigation docs for screenOptions on a "regular" stack and a native stack you'll see the differences there, too.

The solution is to use the regular stack in expo-router (this isn't exported by default, there's a section in the docs that has an example of how to use it using a custom navigator) or use the native stack with the tabs.  For that you just need a _layout.tsx for each tab that exports Stack from expo-router.

**Comment by baltagih2** [comment]
@gorbypark Thank you for the explanation, this makes sense. 

Wouldn't it be better to either expand on the props of the native stack and/or use a native version to bottom tabs so there's a consistent approach between stacks?

I believe this would be a react-navigation thing not an expo thing and I'd love to collaborate on it if this is doable on the expo side of things. 

If not, maybe we could add in this explanation to the docs to explain the differences?

Thanks again!
