### ISSUE TITLE
https://exp.host/--/api/v2/push/send should Require Authentication

### ISSUE THREAD

**Issue by gerardo15** [expo/expo#3034]
Hello Guys!

I finished my app and realized of something, if an attacker manages to get access to all of my users ExpoPushTokens not only he will be able to send notifications on the application behalf, worst thing is that I won't be able to stop those notifications, as currently there is no way to invalidate push tokens.

I know best thing is prevention, but there should always be a plan B.

What do you guys think?

**Comment by ide** [comment]
It's reasonable to add. The current system is secure as the push tokens are sufficiently long, random, and unguessable -- they have the same qualities as a session secret token, for example. Adding an additional API token makes sense to provide revocation. We could also provide revocation of individual push tokens as well though, it's all isomorphic.

**Comment by ide** [comment]
Closing this as this is now possible with EAS access tokens.

**Comment by samuel-andres** [comment]
In case someone else is worried about this:
- Go to `expo.dev` 
  -> `accounts` 
  -> `your-account` 
  -> `settings` 
  -> `access-tokens` 
  -> `Enhanced Security for Push Notifications`
  
 Once enabled, the Expo's Push API will require an access token with the `Bearer` prefix to be set in the authorization header in order to send push notifications.
