### ISSUE TITLE
Limit Permissions on IOS standalone

### ISSUE THREAD

**Issue by gerardo15** [expo/expo#3065]
Hello Guys,

In android we have the following way to limit the permissions that the app asks on the playstore

https://docs.expo.io/versions/v31.0.0/workflow/configuration#android

android.permissions

 /*
      List of additional permissions the standalone app will request upon installation,
      along with the minimum necessary for an Expo app to function.
*/

For IOS, the App Store Feedback says that its required to explain why i Use Calendar, Sms, microphone, when im not using them in my app.

How to limit the permissions on IOS standalone, a few of us have been asking on the slack group with no luck.

**Comment by zth** [comment]
I'm also very interested in this! 🙂

**Comment by esamelson** [comment]
Hey @gerardo15 - sorry for the slow followup here. Long story short, currently there is no way to remove permissions from an iOS app without ejecting. Since Apple statically analyzes app binaries and looks for specific objective-C method calls to determine which permissions may be requested, the only way to remove permissions would be to completely remove the `Calendar`, `SMS`, etc. modules. This is not currently something we support with `expo build:ios`, though it's fairly straightforward if you eject.

To help your app pass Apple review, we include some boilerplate usage strings [like this](https://github.com/expo/expo/blob/f20188d6916aceb150ab603db214b3cf94a1c086/exponent-view-template/ios/exponent-view-template/Supporting/Info.plist#L34-L35) in your Info.plist. In the past, this has worked for most developers, assuming you never actually request these other permissions at runtime. You can also customize these usage strings however you'd like, as described in [this guide](https://docs.expo.io/versions/v31.0.0/guides/app-stores.html#system-permissions-dialogs-on-ios).

Could you clarify for us if you're asking for support on this (e.g. you've submitted your app to the App Store, and Apple has rejected it citing permissions that you're not using), or if you're just asking a clarification question?

**Comment by gerardo15** [comment]
Hello @esamelson 

I was asking as a clarification, I try to read all the documentation before asking a question and I feel this should be noted on the documentation, as I asked on the slack and no one knew and there were like 4 people looking for this answer.

This is really good explained for android and it does not mention it for IOS, so it seems like its missing.

Thanks for your answer!

**Comment by esamelson** [comment]
Hi @gerardo15 - thanks for the suggestion, I've added a bit more clarification to the docs. We also love accepting PRs for our docs (they're part of this repo), so if you find anything else that's unclear, please go ahead and open a PR 😄
