### ISSUE TITLE
(expo-secure-store) deleteItemAsync not prompting user when "authenticationPrompt" and "requireAuthentication" are set

### ISSUE THREAD

**Issue by MattWeiler** [expo/expo#30716]
### Minimal reproducible example

https://github.com/MattWeiler/ExpoBug-expo-secure-store

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development build, in Expo Go

### Summary

When using the `expo-secure-store`, calling the `deleteItemAsync` function does not prompting the user when setting `authenticationPrompt` to some string and setting `requireAuthentication` to `true`.

Also, when calling the `getItemAsync` function, and setting `requireAuthentication` to `false`, the user is always prompted if the key is present.
If the key is not present, then the user is not prompted.
I'm not sure if this is expected or not, but thought I'd mention it.

In the example repo, look at the `App.tsx` file.

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD   
    IDEs:
      Android Studio: AI-241.15989.150.2411.11948838  
    npmPackages:
      expo: ~51.0.23 => 51.0.23
      expo-router: ~3.5.19 => 3.5.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.10 => 0.19.12
    Expo Workflow: managed

### Expo Doctor Diagnostics

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

**Comment by behenate** [comment]
Hi! What you are describing is the expected behaviour. The `requireAuthentication` option is meant to be used only when writing the data - that makes sure that it's impossible to decrypt the data without user authentication. When used with `getItemAsync` the `requireAuthentication` option won't do anything - the data can't be read without authenticating. 

The authentication is not required for deleting the value, because you don't have to know the contents of a value to delete it.

If you want to requireAuthentication when deleting I suggest [using https://docs.expo.dev/versions/latest/sdk/local-authentication/](`expo-local-authentication`) to emulate the behaviour

**Comment by larcho** [comment]
Sorry to add a comment to a closed issue. But I don't think ignoring `requireAuthentication` flag during `getItemAsync` should be the default behavior. I have an use-case where I want to be certain that I'm asking for the non-authenticated Keychain service and there's no way for me to check that now. I wonder if it makes sense changing the `requireAuthentication` flag to optional defaulting to the current behavior, otherwise enforce the check? (During set I'd consider undefined `requireAuthentication` as false.)

**Comment by larcho** [comment]
This would be the reproducible failing example:
```js
t.describe(
  'store auth -> store non-auth -> fetch auth',
  () => {
  t.it('Sets a value with a key authenticated', async () => {
    try {
      const result = await SecureStore.setItemAsync(key, `${value}-auth`, {requireAuthentication: true});
      t.expect(result).toBe(undefined);
    } catch (e) {
      t.fail(e);
    }
  });
  t.it('Sets a value with a key non-authenticated', async () => {
    try {
      const result = await SecureStore.setItemAsync(key, `${value}-no-auth`, {requireAuthentication: false});
      t.expect(result).toBe(undefined);
    } catch (e) {
      t.fail(e);
    }
  });
  t.it('Fetch the value stored with key authenticated', async () => {
    try {
      const result = await SecureStore.getItemAsync(key, {requireAuthentication: true});
      t.expect(result).toBe(`${value}-auth`);
    } catch (e) {
      t.fail(e);
    }
  });
});
```
