### ISSUE TITLE
Flickering in splash screen on iOS

### ISSUE THREAD

**Issue by johnsiah** [expo/expo#30729]
### Summary

There's a flickering in the splash screen on IOS when the `expo-dev-client` package is added, if the `expo-dev-client` package is being removed then the issue is gone. 

Below is the reproduction of the issue on a new expo project using a development build.

https://github.com/user-attachments/assets/145dca99-1fc2-4b29-b9fd-b9d9653d6061

### Managed or bare workflow?

managed

### What platform(s) does this occur on?

iOS

### Package versions

```
"expo": "~51.0.22"
"expo-dev-client": "^4.0.21"
```

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
      Watchman: 2024.06.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.22 => 51.0.22 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
    npmGlobalPackages:
      eas-cli: 10.2.1
    Expo Workflow: bare
```

### Reproducible demo

1. Create a new Expo project
2. Configure as development build
3. Add `expo-dev-client`
4. `npm run ios`

**Comment by brentvatne** [comment]
hey there! what you are seeing is the following:

- the splash screen is displayed when you launch the app
- the splash screen is then hidden and the app is loaded, bundling begins

we aren't actually showing the splash screen for the app outside of the initial launch, the flickering (splash -> black background -> your app) is the app loading.

cc @alanjhughes to verify that we display splash appropriately in expo-dev-client in the sdk 52 changes

**Comment by johnsiah** [comment]
Yes, and this only happens after `expo-dev-client` is added. It seems like the splash screen somehow gets displayed wrongly when the bundle begins. Any update on this?

**Comment by brentvatne** [comment]
@johnsiah - this shouldn't impact any production use case, so we aren't prioritizing it at the moment, but @alanjhughes will verify that it will be resolved by sdk 52

**Comment by johnsiah** [comment]
@brentvatne got it. By the way, we also saw this reproducible in the production app when we built the production profile. Exactly the same as the demo video display above.

**Comment by johnsiah** [comment]
@brentvatne Note that the bare expo project for testing this issue doesn't install the `expo-splash-screen` yet, just a basic expo new project setup + adding `expo-dev-client`. 

The reason for not adding `expo-splash-screen` is that we'll be using a library like `react-native-bootsplash` for the splash screen. I've tried using back `expo-splash-screen` and it seems like it fixed the issue, but if we were to choose an alternative library or manual splash screen handling or even not adding splash screen at all, it seems like there's some logic in `expo-splash-screen` sort of handling this `expo-dev-client` issue reported above.

More interesting is that when I build a release internal preview using the profile below, it should be building a release build but the same flickering is still there.
```
// eas.json
  "build": {
    "preview": {
      "distribution": "internal"
    }
  },
```

Pasting all my dependencies here for more clarity.
```
  "dependencies": {
    "expo": "51.0.28",
    "expo-build-properties": "~0.12.5",
    "expo-dev-client": "4.0.23",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
```

**Comment by matthieugicquel** [comment]
The same black flicker/flash is reproducible in production scenarios.

Here's a minimal repro: https://github.com/matthieugicquel/bootsplash-black-flash

The minimal setup to have the issue seems to be (I usually don't notice a black flicker with just this):

- `react-native-bootsplash` setup according to their docs (this includes disabling autolinking for expo-splash-screen
- release build 
- `expo-updates` installed, enabled, with `checkAutomatically: "ON_LOAD"` (the default value)

To make the black screen visible every time, you can add (this is included in the repro above):

- `fallbackToCacheTimeout: 10000`
- and a slow network (I use the network link conditions option in [proxyman](https://docs.proxyman.io/advanced-features/network-throttling))

Another way to make the flicker more noticeable seems to be to add other packages that do some work during app init (eg `react-native-unistyles`)


@brentvatne Is there anything I can do to help debug/fix this?

https://github.com/user-attachments/assets/c46bb27d-1b32-4398-9ad7-b4d811eb2084

**Comment by brentvatne** [comment]
@matthieugicquel - the repo you shared uses bootsplash, i don't believe this is related to expo.

@erickreutz - what you are observing may be related to the new architecture. are you using it? the way that we present a spalsh screen placeholder is using a `loadingView` - an API that react native provides - and it appears that with the new arch there is sometimes a bit of a flicker here. we'll look into it

**Comment by dkahdwk** [comment]
@brentvatne @erickreutz @matthieugicquel 
No, the issue is related to expo. The issue is related to expo-updates, bootsplash also gave the answer that expo needs to solve it. Currently, the fix has been completed in Expo sdk 52.
(The issue also occurs in expo-splash-screen)

- reference 1: https://github.com/zoontek/react-native-bootsplash/issues/654#issuecomment-2488163098
- reference 2: https://github.com/zoontek/react-native-bootsplash/pull/578#issue-2273853937

**Comment by brentvatne** [comment]
@dkahdwk - great, i will close this issue then

**Comment by erickreutz** [comment]
@brentvatne I'm not using the new architecture. This is what I'm seeing with `run:ios --configuration "Release"`

https://github.com/user-attachments/assets/9e7c1f8b-5407-42f5-aa51-8e23bf5b2064

**Comment by brentvatne** [comment]
@erickreutz - can you share a minimal reproducible example?

**Comment by MaksymA26** [comment]
@brentvatne Hi, I added reproducible example in the new issue https://github.com/expo/expo/issues/33257. For me it started happening after adding expo-updates. Through some testing I found out that the more assets you have the longer the black screen is shown, for example in the videos provided by the guys above the black screen is shown for ±0.15 seconds, but for me it's shown for more than 2 seconds since I have more than 4000 assets.

**Comment by dkahdwk** [comment]
I thought it was resolved in exposdk 52, but the problem still persists.

**Comment by jstroh** [comment]
Still there. It flickers the default white with circles splash screen even if I have all the expo-splash-screen configured and the expo slash params.

**Comment by jstroh** [comment]
> [@dkahdwk](https://github.com/dkahdwk) - great, i will close this issue then

Wait why did you close this?

**Comment by raahimkhan** [comment]
I can confirm this issue is still there.

**Comment by andreirizeaa** [comment]
Any updates?

**Comment by TianMeh** [comment]
For IOS bare workflow, what worked for our white flicker issue was: 

- Open your project in Xcode
- Expand [AppName] (where you see [AppName] and Pods in the sidebar) -> expand [AppName] again -> press "SplashScreen"
- In there, open "View Controller Scene" -> open "View Controller" -> open "ContainerView" -> click "SplashScreenBackground"
- In the right sidebar toolbar click the 5th icon ("Show the Attributes inspector")
- Set the "Background" property to your desired color instead of default
