### ISSUE TITLE
[docs] expo-calendar deprecated iOS permissions

### ISSUE THREAD

**Issue by HaythamT95** [expo/expo#30973]
### Summary

In the expo-calendar docs it is listed for iOS description keys:
1. NSCalendarsUsageDescription
2. NSRemindersUsageDescription

But Apple deprecated these description keys.

Apple docs:

1. NSCalendarsUsageDescription has been deprecated. If your app needs read and write access to a person’s calendar data, use [NSCalendarsFullAccessUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscalendarsfullaccessusagedescription) instead. If your app needs to create events in a person’s default calendar, use [NSCalendarsWriteOnlyAccessUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscalendarswriteonlyaccessusagedescription) instead.
2. NSRemindersUsageDescription has been deprecated; use [NSRemindersFullAccessUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nsremindersfullaccessusagedescription) instead.

### Link to the related docs page

https://docs.expo.dev/versions/unversioned/sdk/calendar/

**Comment by alanjhughes** [comment]
This was addressed in #24545. We can't remove the old permissions while we still support devices below iOS 17

**Comment by 0xPT** [comment]
@alanjhughes 

Would you be able to add this information to the [documentation](https://docs.expo.dev/versions/latest/sdk/calendar/#ios) to state the permissions that the package uses? It took me a few hours to find this information. The reason it's important that the documentation states what permissions the package uses correctly is because in my case, we have localization and we have Info.plist overrides that need to be configured properly to show the correct permission request message to the end user. Because the documentation is not up to date, I was trying to override the wrong permission.
