### ISSUE TITLE
Inconsistent behavior of -t flag with bun in create-expo-app

### ISSUE THREAD

**Issue by NishantGautam023** [expo/expo#31039]
### Summary

I am trying to create a blank template  using bun package manager. 

The **-t** flag (short for **--template**) works as expected with npm when using create-expo-app, but it doesn't work when using bun. With bun, only the full --template flag works.

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
      Yarn: 3.7.0 - ~/.volta/tools/image/yarn/3.7.0/bin/yarn
      npm: 10.8.2 - ~/.volta/tools/image/npm/10.8.2/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.14.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild

### Minimal reproducible example

![image](https://github.com/user-attachments/assets/37734b33-4e1a-485f-b3dd-67ddaababc7e)
![image](https://github.com/user-attachments/assets/ba429811-42fe-4e8a-8b23-eaa93179b88b)

**Comment by byCedric** [comment]
Hi @NishantGautam023! Thanks for opening an issue! There are a couple of things going on here.

1. Unfortunately, `npm create expo(-app)` doesn't allow passing through flags _unless_ you write it as `npm create expo(-app) -- -t tabs` (with a delimiting `--`)
2. Since Bun `1.0.8`, the shorthand flag (`-t`) in `bun create` is broken. I opened an issue report at the end of last year about this: https://github.com/oven-sh/bun/issues/7114. Maybe it would help if you could create another issue report about this to bring this back to the top of the minds of the maintainers.

Since both of these issues are directly related to npm or bun itself, there isn't a lot we can do about it ourselves. When using Bun, you'd have to use the full flag name until oven-sh/bun#7114 is resolved. Npm itself likely isn't going to remove the `--` requirement.

Hope this helps!

**Comment by NishantGautam023** [comment]
Thanks,  appreciate you sharing your insights on  the -- delimiter requirement for npm and the current bug with Bun's shorthand flags.
