### ISSUE TITLE
[docs] Broken LiveStore link in Local-first documentation

### ISSUE THREAD

**Issue by israataha** [expo/expo#31148]
### Summary

The link to LiveStore, under Other tools, navigates to a page not found.

### Link to the related docs page

https://docs.expo.dev/guides/local-first/#other-tools

**Comment by amandeepmittal** [comment]
Thank you for catching this issue!

It seems the link to the repo has been recently marked only available for "invite-only" (I don't remember coming across this issue when we published this guide a few weeks ago). 

In https://github.com/expo/expo/pull/31178, I've replaced the link to the main GitHub org link so that the message is available as the first thing when visiting that GitHub org.
