### ISSUE TITLE
'Prebuild' command creates 'ios' script in package.json even if --platform is set to 'android'

### ISSUE THREAD

**Issue by erickriva** [expo/expo#31162]
### Summary

**Expected behavior:**
Create 'run' scripts in package.json only for selected platforms, if it does not exists.

**Current behavior:**
It creates 'ios' run command (expo run:ios) even if platform is set to 'android'

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
      Yarn: 1.22.22 - ~/.bun/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
      bun: 1.0.26
    SDKs:
      Android SDK:
        API Levels: 34
        Build Tools: 34.0.0, 35.0.0
    Expo Workflow: managed
```

### Minimal reproducible example

Command: `bunx expo prebuild --clean --platform android --skip-dependency-update react-native,react`

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I believe this is expected - when you run `prebuild` it's understood that you'll be using prebuild for both android and iOS as well. Hence the command is added and when you run it it will generate the `ios` directory.

I'm going to close this but please let me know if the current behavior is a problem for some reason.
Thank you 🙂

**Comment by erickriva** [comment]
> when you run `prebuild` it's understood that you'll be using prebuild for both android and iOS as well

Why exactly?
I am building only for android at the moment, not thinking in iOS.

When running with `--platform android`, `ios` folder is not created. So, this is working fine. If I wanted iOS, I would not pass `--platform android`.
So, why do I need an `ios` command for an `ios` folder that does not even exists (and I do not want it to exist)?

If iOS version will be used someday in this project, I can use `prebuild --platform ios` or `prebuild` without `--platform` argument and create a folder for it.

Am I making sense?

**Comment by vonovak** [comment]
Hello and thanks for getting back,
I understand what you're saying.

Consider this scenario:
1. You start with a clean app, there are no ios and android folders and you only write JS code.
    The commands in package.json which you use to run the app are `"ios": "npx expo start --ios"` and `"android": "npx expo start --android"`
2. you add a native dependency (which is the most frequent reason to use prebuild) or you have some other reason to run prebuild. You run `expo prebuild --clean --platform android`
3. Now consider that the iOS command stays the same: `"ios": "npx expo start --ios"`. If you were to run it, it'd attempt to run the code in Expo Go, but because you have added a native dependency in the mean time, that would not work because the native code would not be built into the native app. **The package json file is therefore in a state where it easily allows people to error.** People would be opening issues about the command not working. Therefore we change the command to `"ios": "npx expo run:ios"` which runs prebuild for you and then the app works as expected with native code.

Does this make sense?
Thank you 🙂

**Comment by erickriva** [comment]
Sure it makes sense.
I thought it was something that should not be working that way.

Now, reading from your point of view, i can see it is a minor problem, and specifically of mine.

Thanks for clarification.
