### ISSUE TITLE
[expo-sensors][iOS] setUpdateInterval doesn't work as expected

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#3116]
Here is a reproduction of the issue: https://snack.expo.io/@bacon/c2Vuc2 

AFAICT this applies to every sensor.

**Comment by EvanBacon** [comment]
It seems like the interval a user defined is ignored when the sensor is started/restarted.

https://github.com/expo/expo/blob/41458d1de91544c41097818db21e44e9aa84688c/ios/Exponent/Kernel/Services/EXSensorManager.m#L55

**Comment by dexterlohnes** [comment]
@EvanBacon I am seeing behavior in my application which I believe is related to this. It seems like 1) somewhat randomly and 2) when I double tap the home button to bring up the app switcher, my manually set update interval is overwritten. 

Is there some kind of event which is fired that my RN application can listen for so that I can proactively reset the updateInterval whenever the accelerometer starts/restarts?

**Comment by dexterlohnes** [comment]
To put the bug in context for our application:

We are creating a Three JS powered game that uses DeviceMotion to rotate the user's camera, allowing you to explore a 3d space. We need to send DeviceMotion data at 60 frames a second in order for the game to run smoothly, otherwise we experience significant lag with our camera and it greatly disturbs the user's ability to play and enjoy our game. 

As it stands, the issue we are running into is reproducible by switching to another app and coming back into our app, which causes us to run at the default 100ms rate, effectively making our game appear to run at 10 frames per second, which is not good. The issue is also producible, as stated above, by double tapping the Home button on the iPhone or otherwise bringing up the fast app switcher interface. 

The issue also appears to randomly occur intermittently.

**Comment by dexterlohnes** [comment]
@EvanBacon @esamelson Any chance of someone taking a look at this? Thanks for your time.

**Comment by ide** [comment]
The team is looking into other things but if this is important enough to you, we would review PRs that carefully investigate and fix the root cause.

**Comment by atroudi** [comment]
Have similar problem on ipad in my case, but works fine on iphone.

**Comment by atroudi** [comment]
> Have similar problem on ipad in my case, but works fine on iphone.

I found a solution in my case, I had to use setUpdateinterval after adding the sensor listener.

**Comment by AdamWP** [comment]
> > Have similar problem on ipad in my case, but works fine on iphone.
> 
> I found a solution in my case, I had to use setUpdateinterval after adding the sensor listener.

Hi @atroudi  Would it be possible to see an example of how you do this?
