### ISSUE TITLE
Expo Push Notifications are not received when the app slug was changed

### ISSUE THREAD

**Issue by AbdulazizGH** [expo/expo#3137]
### Environment
Android and iOS.
SDK v28.0.0
Expo CLI v55.

### Steps to Reproduce
1. Publish app
2. Change slug
3. Update app
4. **Sending a batch of notifications** does not work anymore, and Expo's notification API returns this error: ExponentPushToken[xxxxxxxxx]" is associated with a different experience than "@username/old-app-slug

### Expected Behavior

Notifications received(or a new push token is generated when slug is changed?)

### Actual Behavior
No notifications are received by users and an exception is returned from Expo notifications API.

### Reproducible Demo

Can't provide reproducible demo due to the nature of this error.  
  
### Related issue
https://github.com/expo/expo/issues/556
(Closed without a solution.)

I suspect that the notifications are mixed from different experiences(i.e. old versions vs new versions), which is causing Expo's **batch** notifications API to fail.

**Comment by esamelson** [comment]
Hi @AbdulazizGH - when you change the your app's slug, from Expo's point of view it is a completely new and separate app. You'll need to call `getExpoPushTokenAsync` again on all of your clients and collect new push tokens, and you'll need to send notifications in separate batches for each app (old and new).

I hope this makes sense! Feel free to follow up with any questions, but I'm going to go ahead and close this as this is expected behavior -- the slug is the unique identifier of the app and we don't support changing it without treating the new app as a totally separate experience.

**Comment by robertobrogi** [comment]
uhm i have the same problema.... befaore was expo 30.0.0 without slug and now i have expo 32.0.6 with slug and no t arrive the push notification for app store....
i call getExpoPushTokenAsync for to have a new token but not working....
