### ISSUE TITLE
[docs] Expo ChangeLog is getting out of date.

### ISSUE THREAD

**Issue by bob-devereux** [expo/expo#31603]
### Summary

No updates since 51.0.24, and the current version is 51.0.32
https://github.com/expo/expo/blob/main/packages/expo/CHANGELOG.md

### Link to the related docs page

https://github.com/expo/expo/blob/main/packages/expo/CHANGELOG.md

**Comment by Simek** [comment]
Hey @bob-devereux, 

this is an expected in our current release process, since we release minor SDK versions from `sdk-*` branches, and the changelogs are updated when releasing. We also do not backport the Changelog files, to do not disrupt the development flow on `main` branch.

So, to get the newest changelog for a given SDK release the best way is to check out the file on mentioned earlier SDK branch instead of `main`, for example:
* https://github.com/expo/expo/blob/sdk-51/packages/expo/CHANGELOG.md

**Comment by bob-devereux** [comment]
Thanks for your reply and explaining to look on the version branches for the most up-to-date changelogs.

I'm not following your explanation 100% though.  The changelog on the main branch now has changes for 51.0.32 and later releases.  It seems like it was simply out of date when I posted the issue, and that minor SDK version changelogs make it to the main branch but can be delayed.  It confused me to see minor version changelogs, but not the latest ones.

I think it would be helpful if those delays were called out in the main branch in case others look on the main branch like I did.
Thanks for looking at this issue.
