### ISSUE TITLE
[expo-notifications][Android] Notifications response not get properly

### ISSUE THREAD

**Issue by jay-unikwork-mobileapp** [expo/expo#31650]
### Minimal reproducible example

See https://github.com/expo/expo/issues/27503

### What platform(s) does this occur on?

Android

### Where did you reproduce the issue?

in a development & production build

### Summary

See https://github.com/expo/expo/issues/27503 and also https://github.com/expo/expo/issues/28656. At the moment, I use [Native Notify](https://nativenotify.com/) for individual push notifications with production set-up for specific users. 

Data I push : 

```
{
    "subIDs": ["aaaaaaaaaaaaaaaaaaaaaaaaaa"],
    "appId": XXXXX, (number)
    "appToken": "XXXXXXXXXXXXXXXX", (string)
    "title": "put your push notification title here as a string",
    "body": "Push message here as a string",
    "message": "put your push notification message here as a string",
    "pushData": "{\"NotificationTitle\":\"test\",\"NotificationDescription\":\"test\",\"ArticleId\":\"\",\"CategoryId\":\"\",\"Type\":\"Generic\",\"userType\":\"Test\",\"id\":\"XXXXXXxX-XXxX-XXXx-XXxX-xxXXXxxxXxXX\"}"
}
```

Using expo-notifications event listener **`addNotificationResponseReceivedListener()`** response I get : 

```
{
  "request": {
    "trigger": {
      "remoteMessage": {
        "originalPriority": 2,
        "sentTime": 1727096177772,
        "notification": null,
        "data": {
          "message": "Test",
          "title": "Test",
          "body": "[object Object]"
        },
        "to": null,
        "ttl": 2419200,
        "collapseKey": null,
        "messageType": null,
        "priority": 2,
        "from": "476408896825",
        "messageld": "0:1727096177781465%8c840977f9fd7ecd"
      },
      "channelid": null,
      "type": "push"
    },
    "content": {
      "title": null,
      "badge": null,
      "body": null,
      "sound": "default",
      "sticky": false,
      "autoDismiss": true,
      "data": {
        "message": "Test",
        "title": "Test",
        "body": "[object Object]"
      },
      "priority": "default",
      "subtitle": null
    },
    "identifier": "0:1727096177781465%8c840977f9fd7ecd"
  },
  "date": 1727096177772
} 
```

In the above code `"body": "[object Object]"` how to manage this thing because `JSON.stringify()` and `JSON.parse()` are not working. I got untitled and no description notification.

This does not work only on Android.

### Environment

```text
SDK 51
expo 51.0.21
expo-notifications 0.28.17
native-notify 4.0.4
```

### Expo Doctor Diagnostics

```text
Not applicable
```

![image](https://github.com/user-attachments/assets/cfa92c62-9a83-4b40-96c3-28aa1a3799b6)

**Comment by RohovDmytro** [comment]
After updating to the latest version of `expo-notifications` I experience the same bug.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
I just tested the `addNotificationResponseReceivedListener` functionality and it works as expected for me. In the listener, the `notification.request.content.data` looks like this:

```
        "data": {
          "body": "{\"value\":\"123\",\"title\":\"This is the data in a test notification\",\"body\":\"This is the data in a test notification\",\"url\":\"/(tabs)/settings\"}",
          "title": "This is a test notification",
          "message": "",
          "categoryId": "submit_reply_placeholder"
// other entries
        },
```

@jay-unikwork-mobileapp you're referring to the reproducible example of https://github.com/expo/expo/issues/27503 but the repro from that issue gives a 404 - not found.

Please open a new issue for your problem and follow the issue template. It's especially important that you include:

1. runnable reproduction
2. what behavior you're seeing (with steps to reproduce) and what you expect to see instead.
3. For push notifications: the request you're sending to the push service in order to send the notification (especially the request body is important)
4. Add the "Notifications" label to the Github Issue - this helps with visibility.

Thank you 🙂
