### ISSUE TITLE
[docs] NPM monorepo with Typescript

### ISSUE THREAD

**Issue by JoshBot-Debug** [expo/expo#31826]
### Summary

NPM is fairly popular, so is typescript. I use it in all my projects as I'm sure many people do. While the [Expo documentation](https://docs.expo.dev/guides/monorepos/)  provides a guide on monorepos, it doesn't include an example specifically for NPM monorepos. Additionally, the [NPM documentation](https://docs.npmjs.com/cli/v8/using-npm/workspaces)  doesn't clarify how to set things up with TypeScript.

I've set up my project and it works beautifully. I love monorepos  now :smiley:. With more people adopting this approach, I believe they would agree that it’s an excellent way to build projects, as it allows for code reuse without the need to copy files around.

I’d love to write a guide on setting up Expo with an NPM monorepo using TypeScript. Let me know you're thoughts. I'm ready to create the doc anytime!

### Link to the related docs page

https://docs.expo.dev/guides/monorepos

**Comment by byCedric** [comment]
Hi @JoshBot-Debug! The main reason why we only describe how to set up a basic monorepo with Yarn v1 is because we can't provide a guide for all types of monorepos. For example:
- Monorepos are configured differently in bun, npm, and yarn compared to pnpm.
- Monorepos can be set up "isolated", where every workspace can even use a different language (as long as it compiles to JS)
- Monorepos can be set up with just typescript so that every workspace doesnt need to be build individually

There are too many variations to document in a comprehensive guide, and its especially hard to keep that up to date. If you are using monorepos, we assume you know how you want to set it up, the guide is just an example implementation that you can use to understand the basic required structure.

That being said, Metro transpiles all code, even from `node_modules`. Meaning that you can "ship" typescript code in every workspace, and import it in your Expo app. You don't have to transpile it before using it in the app. But with that setup you also can't heavily customize typescript in every workspace, as the app's config isn't shared.

Hope this helps!
