### ISSUE TITLE
[Expo.Google.logInAsync] reversed refreshToken value/key pair in response object

### ISSUE THREAD

**Issue by gerbus** [expo/expo#3190]
Hi. I just started seeing an issue with `Expo.Google.logInAsync` where the `refreshToken` comes back with the key/value pair reversed. I recently upgraded from Expo SDK `31.0.0` to `32.0.0`, so good possibility a bug was introduced there.

### Environment
```
Expo CLI 2.6.14 environment info:
    System:
      OS: macOS Sierra 10.12.6
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 11.2.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.0
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: 3.0.0 => 3.0.0
    npmGlobalPackages:
      expo-cli: 2.6.14
```
I'm testing the app both in the Android Expo client (installed on my device) and the iOS Expo client (installed on various models in the iOS Simulator).

### Steps to Reproduce

1. Call Expo.Google.logInAsync with valid clientIds (my code below)
2. Look at the response

```
  const accessToken = await Expo.Google.logInAsync({
    behavior: 'web',
    scopes: [
      'https://www.googleapis.com/auth/userinfo.email',
      'https://www.googleapis.com/auth/userinfo.profile',
      'https://www.googleapis.com/auth/calendar',
      'https://www.googleapis.com/auth/calendar.events',
    ],
    androidClientId: clientIds.android.web,
    iosClientId: clientIds.ios.web,
    androidStandaloneAppClientId: clientIds.android.web,
    iosStandaloneAppClientId: clientIds.ios.web,
    webClientId: clientIds.web
  })
  .catch(err => {
    console.error("[promptLogin] User refused or failed to log in");
    console.error(err);
    return 'CANCELLED';
  })
  .then(resp => {
    console.log("[promptLogin] User logged in.");
    console.log(resp);
  });
```

### Expected Behavior
In the response object you find: 
`"refreshToken": "yfda.whatever-something-somethingelse"`

### Actual Behavior
In the response object you find:
`"yfda.whatever-something-somethingelse": "refreshToken"`

But all the other key/value pairs are as usual. Only `refreshToken` is reversed!

**Comment by skylerrichter** [comment]
I just noticed this issue too.

**Comment by gerbus** [comment]
And actually I think I'm seeing

`"8vn7.your-access-token": "refreshToken"`

So even if I reversed it to work around this issue, I don't think it would help, because it's not the proper refreshToken.

**Comment by mkuipers** [comment]
YES! YES I THOUGHT I WAS CRAZY FOR THE PAST WEEK OH MY GOD SOMEONE ELSE EXPERIENCED THIS TOO.

**Comment by mkuipers** [comment]
So this does not appear to be a problem with the google api. When I'm in the google API playground messing around, I don't get any issues with getting a refresh token back. So I traced the source code for this but I'm a little blocked because I don't understand the iOS code in the NativeModulesProxy as well as I understand the js and typescript.

My guess is that the problem is somewhere in here since I don't see the `refreshToken` as one of the keys that should be returned https://github.com/expo/expo/blob/sdk-32/packages/expo-app-auth/ios/EXAppAuth/EXAppAuth%2BJSON.m#L19-L34

**Comment by mkuipers** [comment]
Wait, no this is probably the problem (again I've never really used Objective C, so I could be completely wrong) 
https://github.com/expo/expo/blob/sdk-32/packages/expo-app-auth/ios/EXAppAuth/EXAppAuth.m#L172 this line appears to have the `setValue` and the `forKey` values backwards.  

It also appears to be setting the accesstoken as equal to the refresh token because of these lines: 
https://github.com/expo/expo/blob/sdk-32/packages/expo-app-auth/ios/EXAppAuth/EXAppAuth.m#L166-L169

**Comment by EvanBacon** [comment]
Thanks @mkuipers for fixing this issue.

**Comment by vinhhrv** [comment]
@EvanBacon Thank you
how to fix this issue now ?
when do you release new version with issue fixed

**Comment by gerwim** [comment]
Sorry to leave a comment on this, however this issue is still present in Expo SDK 32. Is there any update on this fix?
