### ISSUE TITLE
Android-Expo.Permissions.SMS does not prompt user if permission is not provided

### ISSUE THREAD

**Issue by HamzaKV** [expo/expo#3203]
### Environment

From console: Encountered an exception while calling native method: Exception occurred while executing exported method askAsync on module ExpoPermissions: null

Platform: Android

### Steps to Reproduce

Code below produces exception.
`async getPermisssion() {
        try {
            const { status } = await Permissions.askAsync(Permissions.SMS);
            if (status === 'granted') {
                console.log('Permission granted');
            } else {
                console.log('Permission denied');
            }
        } catch (error) {
            console.log(error);
        }
    }`

### Expected Behavior

Allow app to send sms

### Actual Behavior

Produces an exception and hinders code to allow the app to send sms

**Comment by BoyPersoon** [comment]
Getting same error with the following code:
` import { AppLoading, Asset, Font, Icon, Permissions } from 'expo';`

`async function checkMultiPermissions() {
      const { status, expires, permissions } = await Permissions.getAsync(Permissions.CAMERA, Permissions.READ_EXTERNAL_STORAGE)
      if (status !== 'granted') {
        alert('Hey! You heve not enabled selected permissions');
      }
    }`

Error
Possible Unhandled Promise Rejection (id: 0): Error: encountered an exception while calling native method: Exception occured while executing exported method getAsync on module ExpoPermissions: null
createErrorFromErrorData...

**Comment by justinsoong** [comment]
Experiencing this on expo 32, standalone android build

**Comment by bbarthec** [comment]
Hello @HamzaKV! As we stated in [SDK32 release blog post](https://blog.expo.io/expo-sdk-v32-0-0-is-now-available-6b78f92a6c52) `SMS` permission is gone as we're complying with Google’s new policy regarding SMS and Call Log permissions. 

@BoyPersoon there was never permission called `READ_EXTERNAL_STORAGE` (because this is causing this issue).

Please refer to [SDK 32 documentation](https://docs.expo.io/versions/latest/sdk/permissions).
