### ISSUE TITLE
Expo auto install bad dependency

### ISSUE THREAD

**Issue by Ymajuscule** [expo/expo#32049]
### Summary

hey ! i'm trying to install fresh expo but it auto install these dependency and i cannot make anything someone know how i can patch this ?

### What platform(s) does this occur on?

Android

### SDK Version

51

### Environment

```text
expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-232.10300.40.2321.11567975
    npmPackages:
      expo: ~51.0.37 => 51.0.37
      expo-router: ~3.5.23 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: ^0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.11
    Expo Workflow: managed
```

### Minimal reproducible example

# npm audit report

cookie  <0.7.0
cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x
fix available via `npm audit fix --force`
Will install expo-router@3.1.0, which is a breaking change
node_modules/cookie
  @remix-run/server-runtime  *
  Depends on vulnerable versions of cookie
  node_modules/@remix-run/server-runtime
    @remix-run/node  *
    Depends on vulnerable versions of @remix-run/server-runtime
    node_modules/@remix-run/node
      @expo/server  *
      Depends on vulnerable versions of @remix-run/node
      node_modules/@expo/server
        expo-router  <=0.0.1-canary-20240418-8d74597 || >=3.1.1
        Depends on vulnerable versions of @expo/server
        node_modules/expo-router

send  <0.19.0
Severity: moderate
send vulnerable to template injection that can lead to XSS - https://github.com/advisories/GHSA-m6fv-jmcg-4jfg
fix available via `npm audit fix --force`
Will install expo@45.0.8, which is a breaking change
node_modules/send
  @expo/cli  <=0.0.0-canary-20231123-1b19f96-4 || 0.0.1-canary-20231125-d600e44 - 0.0.1-canary-20240418-8d74597 || >=0.2.0
  Depends on vulnerable versions of send
  node_modules/@expo/cli
    expo  >=46.0.0-alpha.0
    Depends on vulnerable versions of @expo/cli
    node_modules/expo

8 vulnerabilities (5 low, 3 moderate)

To address all issues (including breaking changes), run:
  npm audit fix --force

**Comment by gwashburne** [comment]
I am also getting the vulnerable versions of **send** error when I run npm audit:
`send  <0.19.0
Severity: moderate
send vulnerable to template injection that can lead to XSS - https://github.com/advisories/GHSA-m6fv-jmcg-4jfg
fix available via `npm audit fix --force`
Will install expo@45.0.8, which is a breaking change
node_modules/send
  @expo/cli  <=0.0.0-canary-20231123-1b19f96-4 || 0.0.1-canary-20231125-d600e44 - 0.0.1-canary-20240418-8d74597 || >=0.2.0
  Depends on vulnerable versions of send
  node_modules/@expo/cli
    expo  >=46.0.0-alpha.0
    Depends on vulnerable versions of @expo/cli
    node_modules/expo`

**Comment by AfrokingJasper** [comment]
Ive been having similar issues as well and i cant seem to find a solution 

send  <0.19.0
Severity: moderate
send vulnerable to template injection that can lead to XSS - https://github.com/advisories/GHSA-m6fv-jmcg-4jfg
fix available via `npm audit fix --force`
Will install @expo/cli@0.1.7, which is a breaking change
node_modules/send
  @expo/cli  <=0.0.0-canary-20231123-1b19f96-4 || 0.0.1-canary-20231125-d600e44 - 0.0.1-canary-20240418-8d74597 || >=0.2.0
  Depends on vulnerable versions of send
  node_modules/@expo/cli
    expo  >=46.0.0-alpha.0
    Depends on vulnerable versions of @expo/cli
    node_modules/expo

**Comment by brentvatne** [comment]
Nearly all non-trivial packages in the Node ecosystem will come with messages like this on install due to the unfortunate way that unactionable warnings are exposed to users. Some tools use `ncc` to vendor the dependencies, which essentially hides the warnings, but the underlying code is the same.

In all but the most rare of cases, these vulnerability warnings don’t actually apply to any of the usage in the context of Expo tools — they often relate to usage in the context of running a web server. If we become aware of a case that may impact Expo tools, we will update the dependency as soon as we are aware. In other cases, we update dependencies when it’s a good time to do so, taking into account factors such as the supported Node version.

Usually the warnings you see are from distant downstream dependencies, eg: `expo-*` depends on package `a` which depends on `x` which depends on `y` which depends on `z`. We have to wait for `a` to update their dependency on `x` which results in updating `y` and `z`. 

More information on the downsides of `npm audit` in "npm audit: Broken by Design”: https://overreacted.io/npm-audit-broken-by-design/

If you believe that any particular warning message points to a legitimate vulnerability that may be exploitable in the context of Expo tooling, please send an email to security@expo.dev with more information.
