### ISSUE TITLE
How to build detached app locally WITHOUT publish?

### ISSUE THREAD

**Issue by N1ghtly** [expo/expo#3219]
I can't seem to figure out a way to build my expokit app locally, without having to publish. It seems that the JS doesn't get bundled unless I publish. Is this intended behaviour? And if so, is there a workaround?

**Comment by tsapeta** [comment]
Hmm, in debug mode you don't have to bundle these files and include them into the project, because in debug it loads assets from your development server (`expo start`).

If you asked about the release mode, I guess there is no such way right now. As a workaround you could try to publish to a specific release channel that is not used by any of your other builds. I assume you just don't want to push an update to your existing builds, right?

**Comment by N1ghtly** [comment]
It's actually more of a privacy issue that our company has with publishing our code to an external server. But I guess we could setup in-house hosting then?

**Comment by tsapeta** [comment]
Yes, you can host them on your own servers, see https://docs.expo.io/versions/v32.0.0/distribution/hosting-your-app for more details 😉 
Closing this thread, but feel free to comment if you have any questions 😄
