### ISSUE TITLE
Bug on Haptic.notification(Haptic.NotificationFeedbackType.Error)

### ISSUE THREAD

**Issue by softhib** [expo/expo#3224]
### Environment

Iphone X
SDK 32

### Steps to Reproduce

Write the following code for example in an onPress button props:
```
Platform.OS === "ios" &&
        Haptic.notification(Haptic.NotificationFeedbackType.Error);
```
### Expected Behavior

Haptic notification happens

### Actual Behavior

This error happens:
`Error: The method or property Haptic.notification is not available on this platform, are you sure you ve linked all the native dependencies properly?
`

**Comment by joelgetaction** [comment]
Hi,

I am also seeing this.  Haptic feedback is absolutely critical to our app and upgrading to Expo 32 has totally broken our app since Haptic feedback now barfs with this incorrect error on every button press *even* when we are running on an iOS device and *even* when the only mention of `Haptic` is made in a file named like `MyFile.ios.js`.

This is an absolutely critical bug for us - can we get a patch release of Expo 32.0.1 to fix this?  It's pretty major functionality impacted.  Otherwise we'll need to downgrade to Expo 31 until it can be fixed by the Expo team.

I'm happy to help with testing of patches or PR's if there's a desire - please let me know ... @tcdavis @EvanBacon 

Thanks!  And thanks for all of your hard work on expo.  :-)

**Comment by JakeHedman** [comment]
I'm also experiencing this. Using a couple of `Haptic.impact` as a workaround for now. It's less juicy than `Haptic.notification` but still better than vibration. :)

**Comment by EvanBacon** [comment]
Yo guys, I opened a PR to fix this. Adding web support messed with the logic. Here is a work around:

```js
import { NativeModules } from 'react-native';
const { ExponentHaptic = {} } = NativeModules;

import { Haptic } from 'expo';

if (ExponentHaptic.notification) {
  ExponentHaptic.notification(  /* Haptic.NotificationFeedbackType.* */ )
}

```

**Comment by JakeHedman** [comment]
Thank you! 😍

**Comment by joelgetaction** [comment]
HI @EvanBacon , thanks for the update.

Unfortunately, your suggestion doesn't work well in VSCode or other editors that reorder/sort imports because your suggestion only works if `Haptic` is imported last/after the other two imports but most editors will reorder it to come before those two imports because "expo" comes first.

Not sure how to make this work in VSCode - any suggestions?  I can't use another editor as that is our team standard and I can't turn off import reordering by file type or workspace as having it on is also our project standard.  Any idea how to tell VSCode to not reorder just this one import so that your fix works?

Thanks again!

**Comment by simsketch** [comment]
Using Vibrate was a perfectly acceptable alternative for me...thanks!

**Comment by MartinLeedotOrg** [comment]
I'm still having this problem in 32.0.6 on my local machine with an iPhone 7.

**Comment by brentvatne** [comment]
hey folks! sorry for this hassle. I have removed `Haptic.notification` from the expo docs for SDK32, it will return in SDK33
