### ISSUE TITLE
Facebook login Platform Policy 8.2

### ISSUE THREAD

**Issue by ybanina** [expo/expo#3230]
Hi,

Received this alert from Facebook today: **“Your app doesn’t comply with the following:
Platform Policy 8.2: Native iOS and Android apps that implement Facebook Login must use our official SDKs for Login. Please make sure your Android app is using the most recent version of out SDK for Login”.**

Specifically, it violates this policy: https://developers.facebook.com/policy#7-2-photo (**Android apps should use the default login behavior defined by the SDK, which may use the web-view Login dialog. On iOS, only kiosk apps may use a web-view Login dialog.**)
Facebook requests to fix it in 6 days, in other way the app will be subject to enforcement.

The issue is that we didn’t apply any changes to Facebook login on our own. The last thing that we did was updating expo version to “31.0.7", it went to Play Store on Jan, 15, 11:19. Before that we had version 30.

We need help with this. Could it be an Expo issue or something else?

Thanks!

**Comment by sjchmiela** [comment]
Hey all,

@undef1ned, what `react-native-fbsdk` version are you using in your project? Moreover, what `FBSDKLoginKit` pod version do you have installed in your application? (Try running `cat Podfile.lock | grep FBSDKLoginKit` in the directory where your `Podfile.lock` is.)

Latest `FBSDKLoginKit` version is `4.39.1`. When we were releasing Expo SDK 32, latest version was `4.39.0` which contained a major bug due to which we couldn't include it in the release. Latest release _contains various bug fixes_, so I guess it would be safe to upgrade to.

Maybe upgrading to SDK32 would help you solve your issue, @ybanina? (At least it would upgrade `FBSDKLoginKit` from `4.37.0` to `4.38.1`…)

I'll see if upgrading this native dependency to `4.39.1` is possible in SDK32 and if so, I'll backport this change to SDK32 turtle builders so we're certain we're on latest version.

**Comment by undef1ned** [comment]
After upgrading to use the latest SDK, FB team reviewed our app and told the same - "there is unofficial SDK used".

In fact we're using
- Official react-native built and maintained by FB
- Official react-native-fbsdk built and maintained by FB
- Official FB SDKs (4.39.1) built and maintained by FB

Any more ideas how to fix that? Do they know in FB there is react-native framework built by FB? Stupid

**Comment by nickjuntilla** [comment]
We are also having this problem with expo 31.0.2. Will this be solved by upgrading to 32.0.0?

**Comment by jamesreilly5** [comment]
I got an email a few days ago about this. I'm using version 4.26.0 of the SDK but looking to upgrade to the latest version. Would be interested to know other experiences

**Comment by nickjuntilla** [comment]
@jamesreilly5 The answer for us we switching to native login from 'web'

**Comment by morenoh149** [comment]
Im on expo 33. We got this email from Facebook saying we need to use the latest sdk or the login will be cancelled. Whats the solution here? Happy to dedicate an engineer to this problem.

**Comment by quochungndvt** [comment]
i have the same issue, my app using expo version 33, but FB send an email that say **Native iOS and Android apps that implement Facebook Login must use our official SDKs for Login.
**

**Comment by morenoh149** [comment]
@quochungndvt update your expo version, later versions of expo have later version of the fbsdk. Facebook stopped complaining after we updated.

**Comment by quochungndvt** [comment]
> @quochungndvt update your expo version, later versions of expo have later version of the fbsdk. Facebook stopped complaining after we updated.

Thanks @morenoh149 i have been upgrade version sdk and resubmit, hope it fix this issue

**Comment by quochungndvt** [comment]
@morenoh149 after upgrade version to sdk 35 i still can't login in facebook with behavior 'native' (default) with package expo-facebook
[https://ibb.co/n8hcYdR](url) 
with web view login success still reject from FB

**Comment by morenoh149** [comment]
@quochungndvt the expo behavior is still buggy. But at least fb wont delist your app due to an outdated sdk.

For me I'm adding google and email sign up for users that cannot do fb login. I'm sure the expo team will fix the bugs eventually.
