### ISSUE TITLE
Error instaling NPM package with default template of Expo 52

### ISSUE THREAD

**Issue by nechmads** [expo/expo#32389]
### Minimal reproducible example

Createa. new project using npx create-expo-app@latest --template default@beta

### What platform(s) does this occur on?

Android, iOS, Web

### Where did you reproduce the issue?

in a development build

### Summary

After creating a new project with npx create-expo-app@latest --template default@beta
"npm install" fails with the following message:

<img width="1026" alt="Screenshot 2024-10-27 at 6 02 46 PM" src="https://github.com/user-attachments/assets/5c4cc328-ce58-4e74-8259-3ff5c18fef79">

### Environment

```text
Can't run the tool as can't install npm packages of project.
```

### Expo Doctor Diagnostics

```text
Can't run doctor as can't install npm packages of project.
```

**Comment by nickrugge** [comment]
Hi, i had the same error, i managed to work around using yarn as package manager.

If you need to use npm you can try with: `npm install --force`
or 
adding an .npmrc file in the root of the project with this flag:

```
legacy-peer-deps=true
```

**Comment by gabrieldonadel** [comment]
Hi @nechmads, thanks for the report. This error is happening because of @react-navigation/bottom-tabs v7, which internally depends on the beta version of react-native-screens, but we have already contacted the react-navigation team and this will be resolved soon.

Here is some additional context on how npm handle version comparisons and why the RC versions of react-native-screens are not being resolved correctly https://github.com/npm/npm/issues/8854

For now you can fix this by running `npm install --legacy-peer-deps`, use the `--force` flag or using a different package manager like yarn or pnpm

**Comment by RyanTG** [comment]
Although you said this is occurring on bottom-tabs v7, I am getting what seems like a similar error with v6.

```
npm ERR! Found: react-native-screens@4.0.0-beta.14
npm ERR! node_modules/react-native-screens
npm ERR!   react-native-screens@"4.0.0-beta.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-screens@">= 3.0.0" from @react-navigation/bottom-tabs@6.6.1
npm ERR! node_modules/@react-navigation/bottom-tabs
npm ERR!   @react-navigation/bottom-tabs@"^6.6.1" from the root project
```
