### ISSUE TITLE
WebView in Card does not render on Android

### ISSUE THREAD

**Issue by akirmse** [expo/expo#3247]
Starting with SDK 31, putting a WebView in a Card causes the WebView and everything preceding it not to render.  This happens on Android and the Android simulator, though appears to work on iOS and the iOS simulator.  It worked on Android and iOS in SDK 30 (and we shipped standalone apps with the correct behavior).

https://snack.expo.io/@akirmse/web-view-bug

demonstrates the failure to render.  If the Card element is removed around the WebView, everything renders (though the layout isn't what we want).

**Comment by davidmargolin** [comment]
add `flex: 1` to the card style

**Comment by satya164** [comment]
Don't think it's specific to Card. I just tried a`WebView` by itself and the behaviour doesn't look right: https://snack.expo.io/@satya164/web-view-bug

Notice how the text looks like it’s absolutely positioned on top of webview, rather than below it.

![image](https://user-images.githubusercontent.com/1174278/51402874-01519180-1b4f-11e9-9e43-1c64e5bb3343.png)

**Comment by odusseys** [comment]
Can confirm, on Android, I had to add fixed heights and `overflow: hidden` to my webviews to avoid the above behavior.

**Comment by tsapeta** [comment]
The above comment seems to be a solution to this problem, so let me close this issue 🙂
