### ISSUE TITLE
Background Location not working as expected

### ISSUE THREAD

**Issue by oliverdolgener** [expo/expo#3256]
### Environment

Android, iOS, Client, Standalone

### Steps to Reproduce

1. TaskManager.defineTask() in global scope in app entry file (App.js)
2. Location.startLocationUpdatesAsync('location', {
  accuracy: Location.Accuracy.BestForNavigation,
  timeInterval: 0,
  distanceInterval: 0,
}) in another component (MapScreen.js)
3. Log output

### Expected Behavior

Background location updates should work exactly as if the app were active.

### Actual Behavior

When the app goes in the background the frequency of location updates are getting reduced from every second to every 10 - 20 seconds (with fake GPS app) or worse (with real GPS data from walking around outside). After being in the background for about 3-4 minutes the app crashes silently without any logs. It just disappears from the open apps.

### Additional Info

https://forums.expo.io/t/expo-location-startlocationupdatesasync-doesnt-work-on-android/18231

**Comment by ide** [comment]
The crash in unexpected but frequency of location updates and generally any kind of background activity is expected to drop in the background to preserve battery life. The default policy (of mobile platforms -- not something Expo decided) is to notify when there are significant changes in background location.

**Comment by oliverdolgener** [comment]
oh ok, so there isn't really anything we can do to increase it? Maybe my expectation were to high but I thought with setting the accuracy we are able to control how often the location gets updated. Is there any kind of documentation on how signification the changes need to be to get updates?

**Comment by superyarik** [comment]
first of all, i use galaxy s7 and if i close application via list of applications there is no calling task from this moment, till i open application and call Location.startLocationUpdatesAsync again

also i have one question:
@tsapeta how we need to use TaskManager.isTaskRegisteredAsync?

if i use something like this
`TaskManager.isTaskRegisteredAsync(BACKGROUND_LOCATION_UPDATES_TASK).then(
    (val) => {
        if (!val) {
            TaskManager.defineTask(BACKGROUND_LOCATION_UPDATES_TASK, ({ data, error }) => {
                if (error) {
                    console.log(error);
                    return;
                }
                if (data) {
                    try {
                        const { locations } = data;
                        console.log('locations: ', +locations);
                    } catch (e) {
                        console.log(e);
                    }
                }
            });
        }
    },
    (e) => {
        console.log(e);
    },
);`

i face error "TaskManager.defineTask must be called during initialization phase!"

i ask because you make this check in sources and i confused about TaskManager.defineTask: if i just put it in App.js, every launch of application there is redefining task?

**Comment by superyarik** [comment]
> The crash is unexpected but frequency of location updates and generally any kind of background activity is expected to drop in the background to preserve battery life. The default policy (of mobile platforms -- not something Expo decided) is to notify when there are significant changes in background location.

maybe there some miscommunication, expo team means under "background location updates" something else. as for me i think that this is feauture, that fires cb function with current location in listed delay. there is many applications in google and appstore with this functionality(deliver services, taxi), so it is possible to implement this.

**Comment by tsapeta** [comment]
Hey @superyarik,

> how we need to use TaskManager.isTaskRegisteredAsync?

There is a difference between **registering** and **defining** a task. Task is **registered** when you register it by for example `Location.startLocationUpdatesAsync`.

If I understand correctly, you wanted to use `TaskManager.isTaskDefined` instead of `TaskManager.isTaskRegisteredAsync`. However, there is no need to check that here - you can just call `defineTask` 😉 

> if i just put it in App.js, every launch of application there is redefining task?

Yes, every launch will be redefining a task, but there is nothing wrong with that. It just sets a callback. 

> maybe there some miscommunication, expo team means under "background location updates" something else. as for me i think that this is feauture, that fires cb function with current location in listed delay. there is many applications in google and appstore with this functionality(deliver services, taxi), so it is possible to implement this.

On iOS there is nothing more we can do to improve the frequency in the background and I guess, all other apps using background location have this problem as well. I use Strava app very often and the route drawn while in background was of much poorer quality. Also, most navigation apps are not even using significant location updates after killing the app - Google Maps is the best example - when you kill it while it's navigating you, it just stops doing that. 

On Android (Oreo and above, frequency on older versions should be acceptable) there is one thing we could do to improve the frequency of updates - we would have to use foreground service, but it's a bit more complicated to implement than the current version and if we're to implement this (I believe we'll do it at some point), it must be an additional option of background location because it also puts a sticky notification to the notifications center.

**Comment by superyarik** [comment]
@tsapeta thanks for reply.
about notifications: in iOS there is we can define **NSLocationWhenInUseUsageDescription**, **NSLocationAlwaysUsageDescription** and **NSLocationAlwaysAndWhenInUseUsageDescription** and then system ask location permissions we can use "_Always_", so there is no blue location sticky notification appear. But on Android when application in background i even don't see location icon on status bar(but task is running and callback receive locations), is it ok?

**Comment by tsapeta** [comment]
> But on Android when application in background i even don't see location icon on status bar(but task is running and callback receive locations), is it ok?

The location icon should appear there, I'll check that out.

**Comment by BernardRadman** [comment]
Hi, I have a similar problem to this and I was wondering is there any way to fix it. I'm woking on android app, and have defined a background location task in global scope, and I call startLocationUpdatesAsync in componentDidMount of App.js. The problem is that the task is run only once, on start up of the app, and not ever again, even tho it should be periodic. I've read that this is a problem with android version, but can it be fixed?

**Comment by Ares513** [comment]
I'm also getting this issue, following the example from the documentation. I get one location update, then it usually doesn't publish a new location after that. Tried setting it to the highest possible accuracy (which I believe from looking at the source is BestForNavigation), but still, not publishing new location data after application start as far as I can tell. I'll try updating my device because that might be it; let's hope that works.

**Comment by superyarik** [comment]
in some cases there is one trick can help to keep application in backgrounded state:
in power options there is need to add application to avoid any memory optimizations on it or add your application in excludes for never unload it. This options depends from phone model and OS version, but i think you make sense.

**Comment by Foosballfan** [comment]
I had this issue where I was defining my task every time a user began a trip within the app.

I have since put a conditional to only define the task if it doesn't exist. 
```
if (!TaskManager.isTaskDefined('geofence')) {
      TaskManager.defineTask('geofence',  ....
```
This does mean that your callback has to be generic in order to work for any future case as it can't be modified during the operation of the app.

**Comment by superyarik** [comment]
@Foosballfan it's magic, but now there is no **isTaskDefined** in docs :)

**Comment by tsapeta** [comment]
@superyarik it was never in the docs as this method is not really needed. Tasks can be redefined so there is no need to check if it is already defined 😉

**Comment by Foosballfan** [comment]
Redefining a task causes an error : `TaskManager.defineTask must be called during initialization phase!`

**Comment by superyarik** [comment]
@tsapeta yep, thanks, i don't remember where i found it.

@Foosballfan, from docs

> It must be called in the global scope of your JavaScript bundle. In particular, it cannot be called in any of React lifecycle methods like componentDidMount

also as i see it can not be called from any async functions

**Comment by Foosballfan** [comment]
Well the behaviour is different between initial creation and updating later on. 
I only call defineTask in one place in the whole app and its fine the first time, just not when re-defining.

**Comment by ManalLiaquat** [comment]
I am getting this error for the first time when the app is loaded, What can I do? I am calling the function in `componentDidMount`

**Comment by Foosballfan** [comment]
Tasks can persist in Android even after the app is closed. If you do the following it will let you know if it has already been defined
```if (!TaskManager.isTaskDefined('geofence')) {
      TaskManager.defineTask('geofence',  ....```

**Comment by superyarik** [comment]
@Foosballfan as @tsapeta [wrote](https://github.com/expo/expo/issues/3256#issuecomment-457182565) there is no need to use isTaskDefined. Problem of @ManalLiaquat is that you can not use **defineTask** in **componentDidMount**, read [docs](https://docs.expo.io/versions/v32.0.0/sdk/task-manager/#taskmanagerdefinetasktaskname-task)

**Comment by Foosballfan** [comment]
I agree that you must do it outside `componentDidMount` for background tasks. I disagree about there being no need to use `isTaskDefined`.

**Comment by hadnazzar** [comment]
@tsapeta this problem still exists. I can not get new locations when application on background. 
I am using all the things as in documentation of `Location.startLocationUpdatesAsync`

**Comment by superyarik** [comment]
i think this fixes will available only in future release

**Comment by DevUsmanGhani** [comment]
I am having this problem as well. On IOS everything is working smoothly when I am using the Background Location feature but on android the callback is only fired once when the application is initially backgrounded and then not called again. This occurs even if I set the minimum distance interval and time interval to 0. A fix would be greatly appreciated

**Comment by allicanseenow** [comment]
Is there an official way to increase the frequency of the location tracking when the app is in the background?

**Comment by fathurhidayat3** [comment]
I'm still getting this problem with `TaskManager.defineTask` in App.js. But mine has 8-14 seconds update and each update has 2 data returned, updating `timeInterval` / any option has no effect at all. Trying to log this by its timestamp from response data it's shows something like :

1st update : 
// Fri May 17 09:02:29 2019
// Fri May 17 09:02:24 2019

2nd update :
// Fri May 17 09:02:39 2019
// Fri May 17 09:02:45 2019

3rd update :
// Fri May 17 09:02:59 2019
// Fri May 17 09:02:50 2019

**Comment by ankhzet** [comment]
`isTaskDefined` method *is* needed, as otherwise during development console will be polluted with misleading `TaskManager.defineTask must be called during initialization phase!` error when root script (where `defineTask` is called) is hot-reloaded (live-reload doesn't have this issue, i presume).
