### ISSUE TITLE
Standalone Android getting FCM notification twice in background

### ISSUE THREAD

**Issue by rthernes** [expo/expo#3307]
Expo SDK 32
We have set up our app as per https://docs.expo.io/versions/latest/guides/using-fcm/

We are not using Expo's notification back end, but are using Notification.getDevicePushTokenAsync()

When a notification comes in while the app is backgrounded the notification gets displayed twice.

Example notification that does this:
{
"GCM": "{ \"notification\": { \"text\": \"test message\" } }"
}

Google Pixel running Android 9
OnePlus 6 running Android 9
As well as any other Android device we have tried.

**Comment by rthernes** [comment]
Another thing to add: only one instance of the notification uses the notification icon from the app.json (but doesn't seem to use the color), and the other just gets a gray square.

**Comment by dereknelson** [comment]
I've also been facing this problem for some time - this happens even when we tried pushing fcm notifications via cURL.

**Comment by esamelson** [comment]
Hi @rthernes and @dereknelson - the double notifications are because the FCM library automatically creates and renders a notification if you send a message with FCM's `notification` field in the payload, but the Expo client separately renders its own notification with information from the `android.data` payload so that we can have more customization of how the notification appears.

We strongly recommend that you use the Expo Push Token and the method described [here](https://docs.expo.io/versions/latest/guides/push-notifications/) to send notifications, as this is the method we officially support. If you want to try sending notifications directly to FCM yourself, ymmv, but you should not include the `notification` field in the request. I'd suggest a payload that looks something like the following -- for me, this produced the same result (one single notification) as sending it through Expo, just now:

```
{
"message":{
  "android": {
        "priority": "high",
        "data": {
          "experienceId": "@esamelson/fcm", // --> your username & app slug here
          "title": "Hello",
          "message": "World",
          "body": "Optional body",
          "channelId": "Optional name of Android notification channel"
        },
      },
  "token": "fcm-token-here"
  }
}```

Hope this helps! I'm going to go ahead and close this issue as we don't have any immediate plans to change the current client behavior. However, if none of these suggestions work for you feel free to ping me and I'll reopen.

**Comment by rthernes** [comment]
@esamelson This doesn't really help because the data messages aren't displaying while the app is backgrounded, which is why we're using the notification ones. We're already using AWS SNS so the Expo Push backend isn't going to work for us.

**Comment by redsolo** [comment]
@esamelson Couldnt get it working with your suggestion.
@rthernes I was able to get the expo app to show a background notification (and only one) using the FCM data messages suggested in [this forum post](https://forums.expo.io/t/solved-android-receive-data-from-a-fcm-push-notification-in-detached-app/12940/3)
