### ISSUE TITLE
Problem with notification icon in status bar.

### ISSUE THREAD

**Issue by abduraufsherkulov** [expo/expo#3335]
Have been trying to change icon of notification on status bar for a day. Cannot make it work properly. On standalone app, expo icon is showing up on status bar instead of my app.

### Expected Behavior
Click below (it is a white icon)
![notification_icon1](https://user-images.githubusercontent.com/17489128/51787990-48b4cf00-219a-11e9-8ef4-6d79bc67053a.png)

The icon below should be shown instead of expo icon.
![photo_2019-01-26_18-15-53](https://user-images.githubusercontent.com/17489128/51788008-9598a580-219a-11e9-9623-857341a33368.jpg)

Screenshots below explain the issue more clearly.
![photo_2019-01-26_18-16-19](https://user-images.githubusercontent.com/17489128/51788043-2e2f2580-219b-11e9-837d-41f78e365661.jpg)
![photo_2019-01-26_18-16-23](https://user-images.githubusercontent.com/17489128/51788044-2e2f2580-219b-11e9-8a54-afca839e18ae.jpg)

(Write what happened. Add screenshots!)

### Reproducible Demo
app.json file
`{
  "expo": {
    "name": "Delivera Business",
    "slug": "Delivera-Restaurants",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": ["ios", "android"],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "notification": {
      "icon": "./assets/notification_icon.png",
      "color": "#8ac53f",
      "androidMode": "default",
      "androidCollapsedTitle": "Delivera Business"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "android": {
      "package": "restaurants.delivera.uz"
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "restaurants.delivera.uz"
    }
  }
}
`

**Comment by Rithie** [comment]
have you found the solution?

**Comment by abduraufsherkulov** [comment]
Try clearing the cache and build.

**Comment by michaelAdewunmi** [comment]
> Try clearing the cache and build.

I am presently struggling with the same issue too. Does that mean I need to make a new build? Also, how do I clear the cache? Are you talking about **npm cache clean --force**?

**Comment by abduraufsherkulov** [comment]
@michaelAdewunmi `exp r -c`

**Comment by michaelAdewunmi** [comment]
> @michaelAdewunmi `exp r -c`

Thanks @abduraufsherkulov. Got it to work without clearing the cache. 

I Realised I needed to make a new build after adding the expo.notification property. So, After the new build, my custom PN icon started showing.

Thanks for the reply. This will definitely be useful for future purpose.

**Comment by sreubenstone** [comment]
@michaelAdewunmi I am also struggling with the same issue here. Could you state more clearly what you mean by expo.notification property? Are you referring to something that has to go in my app.json? I can't find a reference to a expo.notification field in app.json. Also, regarding custom push icon -- what are the requirements of this icon -- my initial review of the spec showed me I just needed a transparent background for android. Thanks for any tips you can provide.

**Comment by michaelAdewunmi** [comment]
> @michaelAdewunmi I am also struggling with the same issue here. Could you state more clearly what you mean by expo.notification property? Are you referring to something that has to go in my app.json? I can't find a reference to a expo.notification field in app.json. Also, regarding custom push icon -- what are the requirements of this icon -- my initial review of the spec showed me I just needed a transparent background for android. Thanks for any tips you can provide.

Hello @sreubenstone , Pardon me if this is coming late. 

First, you are right that expo.notification is found in the app.json.

` "expo": {
    "name": {
   ...
   }
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "**notification**": {
      "icon": "**./assets/pnicon.png**"
    },
  ...
}`
I am sure you presently do not have the _notification_ property in your app.json. So, just add it yourself and give it an _icon_ property whose value will be the relative path to the folder containing the icon you wish to use.

Now, concerning the icon nature. Expo specified they need a 96px by 96px PNG8 grayscale type icon with transparency. You can easily achieve that with photoshop, In case you want to check out the official expo link, this is it here - https://docs.expo.io/versions/latest/workflow/configuration/

Meanwhile, you can also check the screenshot from the expo page below for confirmation.

![Screenshot (6)](https://user-images.githubusercontent.com/16537939/58754413-5622f280-84c7-11e9-8166-96c4c138d725.png)

In my case, even after the whole configuration, my PN icon didnt show until I made a new build. I guess thats due to the preciously cached icon which had to be replaced in the new build.

I hope this helps. Please let me know if there's anything you don't understand. Thanks!

**Comment by sreubenstone** [comment]
Michael I greatly appreciate this. Now I have it working. I'm surprised Expo doesn't stress these app.json settings in the push notification documentation. I read through that page about 100x and I see no mention of this requirement. Thank you again.
