### ISSUE TITLE
QR code stopped working in --dev-client mode ("No usable data found" error when scanned)

### ISSUE THREAD

**Issue by ax-vasquez** [expo/expo#33421]
### Summary

In an ongoing project that has been using Expo in `--dev-client` mode, the QR code seems to have stopped functioning on iOS (Android is untested as of yet). When scanned in the iOS camera app, I get a "No usable data found" message and it does nothing when tapped.

The development tunnel remains functional, so if the application has already been linked to the current installation of Expo Go on the test device, then it's still possible to work on the app (for example, hot reloading still works as expected). This seems to be a problem with the QR code only.

This issue does not seem to affect brand new projects created via the steps outlined in Expo's "Getting started" guide, so it seems to be specific to something in our project setup, though I don't know what. It's possible for us to workaround this by scanning the QR code generated when running Expo in `--go` mode, but it's not as straightforward.

### What platform(s) does this occur on?

iOS (Android untested)

### SDK Version

52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
      Yarn: 4.1.1 - ~/.nvm/versions/node/v18.20.4/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.7 => 52.0.7
      expo-router: ~4.0.6 => 4.0.6
      react: 18.3.1 => 18.3.1
      react-dom: 18.3.1 => 18.3.1
      react-native: 0.76.2 => 0.76.2
      react-native-web: ~0.19.13 => 0.19.13
    Expo Workflow: managed
```

### Minimal reproducible example

https://github.com/ax-vasquez/expo-booboo

**Comment by byCedric** [comment]
Hi @ax-vasquez! Thanks for reporting and providing a repro. I think this is not necessarily an issue with Expo though, here is why:

`expo start` has two distinct modes that affects how the QR code is generated, `--dev-client` and `--go`.

- When using `--go`, to open your project on Expo Go, the QR code embeds something like `exp://<lan ip>` (e.g. `exp://192.168.86.xx`). This URL is then passed to the mobile OS to launch the app, and because we start with `exp` - iOS/Android recognizes that Expo Go should handle this URL.
- When using `--dev-client`, we usually can't use Expo Go. Dev clients can have different native modules than what's available in Expo Go. That's why the QR code changes to something like `exp+<app slug>://expo-development-client/?url=http%3A%2F%2F192.168.86.xx%3A8081`. The system will check for installed apps that can open `exp+<app slug>`, and use that app instead.

Whenever iOS says "no usable data found", it means that the QR code deeplink can't be handled by any installed app. In other words, it means you have to install your dev client or development build before being able to open it.

It is possible to manually open Expo Go and try to load your app with `--dev-client` mode, but that would require you to open the Expo Go app and enter the IP manually.

For more info on how to use dev clients or development builds, see: https://docs.expo.dev/develop/development-builds/introduction/

Hope this helps!

**Comment by ax-vasquez** [comment]
I'm confused then - why did this work before?

**Comment by ax-vasquez** [comment]
@byCedric I'm a little bothered by the ticket being closed without any meaningful resolution being reached.

If you read my repo and Stack Overflow post, you'll see that the QR code _did_ work for my in `--dev-client` mode. The flow _used to_ work like this:

1. Run `expo start --dev-client`
2. Scan the QR code
3. Expo Go opens the app
4. I start development

**NOW,** (as you call "the correct way"), I have to:

1. Run `expo start --go`
2. Scan the QR code
3. Open my device browser
4. Click "Expo Go" as the app to use to open the link
5. Click the "Allow" prompt
6. Start development

Why are there now 2 extra steps for me, and why was `--dev-client` working for me before? It sounds like you're saying it should not have worked that way. If I'm still having this issue, I'll have no choice but to open a new ticket. I don't want to spam, but my issue is not resolved.

**My workflow has been degraded as a result of using `--go`, and I didn't need to do that before. Why do I now?**

**Comment by ax-vasquez** [comment]
@byCedric I actually realized my issue is likely something a bit different than what this issue was targeting.

I've created a new ticket to better describe the actual discrepancy I am seeing here in #33454

**Comment by Jawschamp** [comment]
Same issue as above
