### ISSUE TITLE
[Bug] Memory leak when using router.replace

### ISSUE THREAD

**Issue by focux** [expo/expo#33510]
### Minimal reproducible example

https://github.com/focux/expo-router-replace-bug

### Which package manager are you using? (Yarn is recommended)

pnpm

### If the issue is web-related, please select the bundler (`web.bundler` in the `app.json`)

metro

### Summary

Screen content is duplicating in the DOM when using expo-router's `router.replace` for navigation. Each navigation action creates a new duplicate of the screen content and re-registers hooks, rather than replacing the existing content. This leads to multiple instances accumulating in the DOM, causing unexpected behavior, potential performance issues and memory leaks.

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 23, 24, 28, 29, 30, 31, 32, 33, 34, 34
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-25 | ARM 64 v8a, android-29 | Intel x86 Atom_64, android-31 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2023.1 AI-231.9392.1.2311.11255304
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.17 => 52.0.17 
      expo-router: ~4.0.11 => 4.0.11 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: managed
```

**Comment by marklawlor** [comment]
Invalid repro provided, possibly a private repro?

**Comment by focux** [comment]
I just noticed that repro was private, should be public now...

**Comment by marklawlor** [comment]
This is expected behaviour of React Navigation, as it is mimicking the behaviour of a Native Stack. In a Native Stack, screens are not unmounted when navigating, they are layered on top of each other. They are only unmounted when the screen is dismissed. You are navigating to "/explore" with a push, and then replacing it with "/" so your stack ends up being multiple "/" screens.

Maybe a better option would be `router.dismissTo()`? `dismissTo` will dismiss screens until the route is found, or if the route is not present in the history it will push forwards to it.
