### ISSUE TITLE
Cannot found module expo/fingerprint 

### ISSUE THREAD

**Issue by Abhishekranjan56** [expo/expo#33531]
### Summary

After upgrading my project from Expo SDK 51 to SDK 52, I’ve encountered an error. The error occurs when I try to either build the app locally or run it. This issue persists despite updating all dependencies. I need help understanding and resolving the issue.
`Error: Cannot find module 'expo/fingerprint'
Require stack:
- /Users/username/sample-app/node_modules/expo-updates/utils/build/createFingerprintAsync.js
- /Users/username/sample-app/node_modules/expo-updates/utils/build/resolveRuntimeVersionAsync.js
Error: Cannot find module 'expo/fingerprint'
Require stack:
- /Users/username/sample-app/node_modules/expo-updates/utils/build/createFingerprintAsync.js
- /Users/username/sample-app/node_modules/expo-updates/utils/build/resolveRuntimeVersionAsync.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/username/sample-app/node_modules/expo-updates/utils/build/createFingerprintAsync.js:27:34)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32) `

### What platform(s) does this occur on?

Android, iOS

### SDK Version

52

### Environment

```text
expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.9.0 - /opt/homebrew/bin/node
      npm: 10.8.3 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /Users/abhishekranjan/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 16.0/16A242d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^52.0.17 => 52.0.17 
      react-native: 0.76.3 => 0.76.3 
    npmGlobalPackages:
      eas-cli: 14.0.2
      expo-cli: 6.3.10
    Expo Workflow: bare
```

### Minimal reproducible example

I am getting the error during build and running it.

**Comment by Abhishekranjan56** [comment]
@stephena-cloud Did you manage to solve it ?

**Comment by Abhishekranjan56** [comment]
Is it during build process @stephena-cloud

**Comment by raulmangolin** [comment]
@Abhishekranjan56 I had the same issue after upgrading. To make it work, I had to delete package-lock and node_modules.

**Comment by Abhishekranjan56** [comment]
@raulmangolin Done that already but no luck might be it is due to the expo-updates package .

**Comment by sainijagjit** [comment]
![Screenshot 2024-12-14 at 6 57 30 PM](https://github.com/user-attachments/assets/163b9f55-669b-4308-b685-38d83322452c)
I am also facing same issue

**Comment by CarlosDinoCloud** [comment]
I'm ALSO facing this issue please re open this issue.. 
<img width="991" alt="Screenshot 2024-12-16 at 7 38 33 PM" src="https://github.com/user-attachments/assets/97208e4c-9cf8-4d28-9d51-5a246bdf314e" />

**Comment by luccas-moraes-smartfit** [comment]
I have a React Native CLI project that originally used AppCenter and CodePush for OTA (Over The Air) updates. Since AppCenter and CodePush will soon be discontinued, I decided to migrate to EAS Build and EAS Update from Expo. I installed the EAS CLI and was able to generate builds without any issues. To use EAS Update, I installed the expo-updates package and added the following versions to the project: “expo”: “^50.0.15” and “expo-updates”: “^0.26.10”. After the installation, the project ran locally without any problems.

However, when running the local build command using EAS with the following command:
eas build -p android --profile preview --local

I get the following error:

Error: Cannot find module 'expo/fingerprint'
Require stack:
/node_modules/expo-updates/utils/build/createFingerprintAsync.js
/node_modules/expo-updates/utils/build/resolveRuntimeVersionAsync.js

Here are the versions in my project:
“react-native”: “0.73.6”,
“expo”: “^50.0.15”,
“expo-updates”: “^0.26.10”.

Does anyone know how to solve this issue? I couldn’t find a solution that works for the error “Cannot find module ‘expo/fingerprint’” during the local build with EAS. I appreciate any help or suggestions! 🚀

**Comment by marctorsoc** [comment]
> @Abhishekranjan56 I had the same issue after upgrading. To make it work, I had to delete package-lock and node_modules.

Same here, but did not need to remove node_modules. I also took the chance to update
- react-native from "0.73.5" to "0.76.5" 
- expo from "51" to "52"
- node from 22.11 to 22.12
 
Not sure if they are related at all, but finally worked

**Comment by davidoort** [comment]
Same issue here...

**Comment by Pedromigacz** [comment]
I have this issue and deleting node_modules and bun.lockb doesn't fix it.

**Comment by Pedromigacz** [comment]
Downgrading from `expo-updates@0.26.*` to `expo-updates@0.25.*` solves the issue to me.
I tested all `expo-updates@0.26.*` 10 versions manually to be sure.

**Comment by Abhishekranjan56** [comment]
@luccasfraga Yeah it's the issue with the expo-updates. I think removing it solves the issue that means surely to do with expo-updates.

**Comment by sainijagjit** [comment]
Can somebody please re-open this issue ? This is the blocker for many of use to upgrade to expo v52.

**Comment by Esarhaddon** [comment]
> I have a React Native CLI project that originally used AppCenter and CodePush for OTA (Over The Air) updates. Since AppCenter and CodePush will soon be discontinued, I decided to migrate to EAS Build and EAS Update from Expo. I installed the EAS CLI and was able to generate builds without any issues. To use EAS Update, I installed the expo-updates package and added the following versions to the project: “expo”: “^50.0.15” and “expo-updates”: “^0.26.10”. After the installation, the project ran locally without any problems.
> 
> However, when running the local build command using EAS with the following command: eas build -p android --profile preview --local
> 
> I get the following error:
> 
> Error: Cannot find module 'expo/fingerprint' Require stack: /node_modules/expo-updates/utils/build/createFingerprintAsync.js /node_modules/expo-updates/utils/build/resolveRuntimeVersionAsync.js

@luccasfraga You should be able to fix this either by upgrading to Expo 52 or by pinning `expo-updates` to `0.26.3`.

I also ran into this error while trying to migrate from CodePush to EAS Update while staying on an earlier version of Expo. The issue is that in [this commit](https://github.com/expo/expo/commit/11e29db4d8a6e1a4fc1b97416fa1749131e89442) the Expo devs removed `@expo/fingerprint` as an explicit dependency of the `expo-updates` package, instead relying on the dependency in the top-level `packages/expo/package.json`. I don't want to deal with the hassle of upgrading from Expo 51 to Expo 52 just yet, so I pinned `expo-updates` to `0.26.3`, which is the last version before the explicit dependency was dropped, and I don't get the "Cannot find module 'expo/fingerprint'" error anymore.

**Comment by brentvatne** [comment]
please share a minimal reproducible example. `@expo/fingerprint` is a dependency of the `expo` package, and it's imported via `expo/fingerpint` which will pull it from the `expo` package. that change was made in this commit: https://github.com/expo/expo/commit/11e29db4d8a6e1a4fc1b97416fa1749131e89442 and you can verify that `@expo/fingerprint` is included here: https://github.com/expo/expo/blob/ede63bbccd01f1ecfa43786e6403beaf6d2acf1d/packages/expo/package.json#L74 and re-exported here: https://github.com/expo/expo/blob/sdk-52/packages/expo/fingerprint.js

**Comment by mikezucc** [comment]
> You should be able to fix this either by upgrading to Expo 52 or by pinning expo-updates to 0.26.3.

I also let dependency bot update expo-updates to `0.26.10` and it blew up my build with same error about missing @expo/fingerprint so I pinned expo-updates to `0.26.3` and now build is happy again. that is all I have to say.

I am on `"expo": "~51.0.26"`

**Comment by hieucd04** [comment]
Same issue here.
Downgrading `expo-updates` to `0.26.3` fixed it for me!
