### ISSUE TITLE
Async functions resulting in undefined is not an object (evaluating '_ref.page')

### ISSUE THREAD

**Issue by msukmanowsky** [expo/expo#3457]
### Environment

```
  Expo CLI 2.10.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      npm: 6.7.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.4
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.10.0
```

App Target: iOS

### Steps to Reproduce

1. Create new Expo app via `expo init`
2. Write an `async function` that fetches from randomuser.me
3. See `undefined is not an object (evaluating '_ref.page')` error

**Note that `fetch` itself works (i.e. removing the `async function`).** This seems to be an issue with `async function`s specifically.

### Expected Behavior

No exceptions :D

### Actual Behavior

Exceptions :(

### Reproducible Demo

https://snack.expo.io/@msukmanowsky/YnJvd3

**Comment by msukmanowsky** [comment]
I feel like I'm missing something.

It seems like `fetch` works if used directly within a component's method like `componentDidMount` but if I use it inside of a module, I immediately get the `_ref.page` error.

Is this documented somewhere?

**Comment by tsapeta** [comment]
Hey @msukmanowsky,
It does throw an exception because you're trying to call `foo` method without arguments, while the first one must be an object (not `undefined`).

So instead of 
`async function foo({ page = 1, pageSize = 10, seed = 1, gender = 'female' }) {`
I'd recommend to do
`async function foo({ page = 1, pageSize = 10, seed = 1, gender = 'female' } = {}) {`
or even
`async function foo({ page, pageSize, seed, gender } = { page: 1, pageSize: 10, seed: 1, gender: 'female' }) {`

Closing as this is an issue in your code, not in Expo 🙂

**Comment by msukmanowsky** [comment]
D'oh! Thanks @tsapeta :)
