### ISSUE TITLE
Why is the expo ios app so slow?

### ISSUE THREAD

**Issue by MarcusHurney** [expo/expo#346]
I've enjoyed using expo so far, but whenever I publish or share my project, other users tell me that the app runs so slowly from their expo ios apps that it is almost unusable. Is there some way to make sure I am optimizing the speed when I share or publish my React Native app using Expo?

**Comment by nikki93** [comment]
We could try your app out if you're comfortable sharing the Expo URL!

**Comment by MarcusHurney** [comment]
I sent you an email to the email address you have listed on your Github profile a few days ago. Is there a better way to share the URL with you?

**Comment by terribleben** [comment]
Hi, a few suggestions here:

- Try testing your app with dev mode switched off
- Make sure you test on an actual device rather than your simulator, if possible
- Ask for help on our slack or forums or slack (not sure @nikki93 saw this message)

I'm going to close this since it sounds like it's something specific with your app's implementation. Let me know if you think there's an underlying tool issue and i'll reopen.

**Comment by keyeMyria** [comment]
yes extremely slow.
