### ISSUE TITLE
Expo link packages

### ISSUE THREAD

**Issue by tomderudderetna** [expo/expo#3489]
A lot of npm package need

`react-native link react-native-module`

But this do nothing, how link with expo?

**Comment by mrikirill** [comment]
You have to eject Expo first and after that you will able to use  react-native link <native-module-name>

**Comment by AdamJNavarro** [comment]
Hey @tomderudderetna,

As @mrikirill mentioned, in order to use libraries that require native code modification either manually or via `react-native link` you have to eject as they do not work within a standard, managed Expo project. I'm going to close this issue now. If you have any other questions like this, please take them to our [forums](https://forums.expo.io/)!
