### ISSUE TITLE
Issue with Expo.Google.logInAsync 

### ISSUE THREAD

**Issue by adititipnis** [expo/expo#3525]
### Environment

Expo sdkVersion = 31.0.0

### Steps to Reproduce

With version 32.0.0, Expo would not return to the app at all. So I switched to version 31.0.0.

With this version, if I try the Google sign in an Android it seems to work fine. But for iOS devices, nothing happens. The accounts page does not even show up.

### Reproducible Demo

https://snack.expo.io/BJrYmeeB4

**Comment by NativLouie** [comment]
i am experiencing the same issue, any fix for this ? thanks

**Comment by vandrieu** [comment]
Same for me, when I log in with google inside my app, Expo app goes back to "Expo Projects" screen instead of continuing inside my app. SDK 32.

**Comment by Lerosen** [comment]
I've got a similar Problem but in my App with expo 32.0.0 the browser does not even open for Authentication. I tried your snack and while it's working fine in the Browser with appetize, but running it on my android phone reveals the same problem. The installed Version of the Expo Android App is 2.10.6.

**Comment by cruzach** [comment]
Hi everyone, I just tested `Google.logInAsync` on SDKs 33, 34, and 35, and it worked without any issues in the Expo Client (Android + iOS), and in a standalone app. Looks like this problem must have been solved since this issue was opened, so I'm going to go ahead and close it. If you still see this behavior, please open up a new issue with a full repro, thanks!
