### ISSUE TITLE
After eject expo app not working in android

### ISSUE THREAD

**Issue by rb162215** [expo/expo#3547]
**Environment**

OS: macOS High Sierra 10.13.6
Node: v10.15.0
npm: 6.4.1
Android Studio: 3.3.1

"expo": "^30.0.2",
"expokit": "^1.7.1",
 "react": "16.4.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"

below is my build.gradle file inside app folder - 

` 
compileSdkVersion 27

  defaultConfig {
    applicationId 'com.myapp'
    minSdkVersion 21
    targetSdkVersion 26
    versionCode 2
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    multiDexEnabled true

    versionName '1.0.5'
    ndk {
      abiFilters 'armeabi-v7a', 'x86'
    }

dependencies {
  implementation fileTree(dir: 'libs', include: ['*.jar'])
  implementation 'com.android.support:multidex:1.0.1'
  implementation 'com.android.support:appcompat-v7:27.1.1'
  implementation('host.exp.exponent:expoview-30.0.0@aae')
}
`

I am using Visual Studio code as editor in which i hit command expo start and after Metro bundler ready i open android studio and try to sync project but getting below error message- 

```
ERROR: Failed to resolve: host.exp.exponent:expoview-30.0.0:
Affected Modules: app
```

I am searching from last 2 days but nothing is working for me.

**Comment by AdamJNavarro** [comment]
Hey @rb162215,

We prefer to reserve Github issues for reproducible bugs. In the future, can you please create a forum issue so we can help you there. This helps other users because they will be able to see the process as well!

On that note, can you take a look [here](https://forums.expo.io/t/android-error-after-ejecting-from-crna-failed-to-resolve-host-exp-exponent30-0-0/14603/9) and see if the solutions provided work for you? If not, please proceed to create a forum issue [here](https://forums.expo.io/c/expokit)!

Cheers,
Adam
