### ISSUE TITLE
Android device contacts API getContactsAsync very slow

### ISSUE THREAD

**Issue by kylebebak** [expo/expo#357]
OS version: Android 6.0.1
Expo version: 18

Execute the following code on an Android device with ~500 contacts:

~~~js
if (permission.status !== 'granted') {
  return;
}
const contacts = await Expo.Contacts.getContactsAsync({
  fields: [
    Expo.Contacts.PHONE_NUMBERS,
    Expo.Contacts.EMAILS,
  ],
  pageSize: 1000,
  pageOffset: 0,
});
~~~

Result:
Call to retrieve ~500 contacts takes ~60s.

Expected result:
Contacts return much much faster. We've disabled our contact picker on Android because of this.

**Comment by skevy** [comment]
cc @nikki93

**Comment by kylebebak** [comment]
Hello all. I created an expo snack (very cool BTW) to show behavior.

<https://snack.expo.io/SyFwMsMB->

**Comment by nikki93** [comment]
Is your application to search through all the contacts once they are returned? We are considering whether a contacts querying API would make sense.

**Comment by kylebebak** [comment]
@nikki93 

That is indeed our application. But tbh the JS code for filtering the full list of contacts was easy for us to write.

I figure that the important problem to solve is to make reading contacts, whether they're filtered or not, a lot faster on Android.

In past projects I've used [react-native-contacts](https://github.com/rt2zz/react-native-contacts) and that was very fast on Android.

**Comment by charlesdeb** [comment]
I have the same use case - and have also written JS code for filtering the full list. I need all the contacts in a pick list so that I can select one of them - but it takes more than 60 seconds to bring them in (with extra overhead for sorting and removing the duplicates). 

BTW, since it takes so long, I get a message on my phone saying "Debugger and device times have drifted by more than 60s " - and then it all reloads, so I can't actually see them on my phone. Perhaps this will work a lot faster when not in development mode but ideally, I'd expect all contacts (sorted and ready to do) to load in a second or two - just like in other apps on my Android phone. I am running Android 7 BTW. A contacts querying API might help - assuming it offered a near instantaneous response. I shall try the react-native-contacts API and see if that works for me.

**Comment by arrygoo** [comment]
@nikki93 We also have a similar usecase. 
Also experiencing the same issue (extremely slow) on expo 19 :(.

**Comment by dikaiosune** [comment]
Heads up that we have a contacts search API in progress (cc @hgale). Keep an eye out for when that's released!

**Comment by dikaiosune** [comment]
@charlesdeb are you running into this in a debugger? I'm not surprised that it's taking that long -- when debugging React Native actually sends all of the bridge messages over to Chrome's JS engine to execute, instead of running your code on the phone.

Unfortunately we don't have a status update on a contact search API, but it's still on our roadmap.

**Comment by dikaiosune** [comment]
Also, we're trying to keep GitHub focuses on bug reports, if this is affecting your app can you please upvote this [feature request](https://expo.canny.io/feature-requests/p/query-contacts)? Thanks!

**Comment by EsdrasEtrenne** [comment]
It could possibly be a bug? I found this in case it might speed up the way the query is written?

https://stackoverflow.com/questions/12109391/getting-name-and-email-from-contact-list-is-very-slow

Seems like an android thing that can be made faster

**Comment by raphaelrk** [comment]
Hi all, running into this as well. Not looking for a way to query contacts but rather fetch all of them quickly (and believe the other posters were looking for this as well rather than a query contacts API @anp @nikki93). Currently takes very long to fetch contacts on Android, 30-70 seconds for 400 contacts.

Our code:
```javascript
const getContacts = async () => {
  const permission = await Expo.Permissions.askAsync(Expo.Permissions.CONTACTS);
  if (permission.status !== 'granted') {
    return false;
  }

  let hasMore = true;
  let contacts;
  let offset = 0;
  let pageSize = 100;
  while (hasMore) {
    contacts = await Expo.Contacts.getContactsAsync({
      fields: [
        Expo.Contacts.PHONE_NUMBERS,
        Expo.Contacts.EMAILS,
      ],
      pageOffset: offset,
      pageSize: pageSize,
    });
    hasMore = contacts.hasNextPage;
    offset += pageSize;
    console.log(`page done`);
  }

  let contactsObj = contacts.data.reduce((acc, item) => {acc[item.id] = item; return acc;}, {})
  let contactList = Object.keys(contactsObj).map(key => contactsObj[key]);

  return contactList;
}
```

**Comment by raphaelrk** [comment]
Edit: saw [https://forums.expo.io/t/loading-all-contacts/1066/6](this link) on the expo forums which addresses this and why Query Contacts is supposed to solve the slowness.

**Comment by arrygoo** [comment]
@raphaelrk we ended up switching to [react-native-contacts](https://github.com/rt2zz/react-native-contacts), it's fast, but obviously not as well maintained as Expo's API.

**Comment by robertobrogi** [comment]
Hi, there are news about the contacts? because in adroid is very very slow...
there is any workaround with expoKit 25.0.0?

thanks

**Comment by mitajunior** [comment]
Too slow and annoying

**Comment by robertobrogi** [comment]
wow! with expo 27 work fine in Android! thanks a lot for your job!

**Comment by JakeNolan** [comment]
ExpoSDK 27 may be more performant but getContactsAsync is still returning duplicate users if the have more than one number, referenced here: https://github.com/expo/expo/pull/1188

**Comment by anp** [comment]
@JakeNolan glad to hear the performance is improved! Could you open a new issue with more details on the duplicates? Much easier to work on with that.
