### ISSUE TITLE
Clickable SVGs not working properly 

### ISSUE THREAD

**Issue by maketroli** [expo/expo#3587]
Hi, Expo.

I recently opened an  [issue on the react native svg GitHub](https://github.com/react-native-community/react-native-svg/issues/939) and also I realize there was another [issue open for the same reason](https://github.com/garblovians/react-native-svg-pan-zoom/issues/8).

If you see the issue I opened, there is [this comment](https://github.com/react-native-community/react-native-svg/issues/939#issuecomment-464227188) from one of the react native svg guys. Where he points this out:

> Upgrading Expo to v32 seems to make it work correctly in Android. iOS seems to have the bug you describe. https://snack.expo.io/@msand/playful-tea
>You can request Expo to upgrade their version of react-native-svg to the latest one for v33.

So, can you guys do that what the comment above says?
I really need to get that done and without that update it seems to be impossible. I've been working on this for weeks already with no success.

**Comment by AdamJNavarro** [comment]
Hey @maketroli,

We tend to upgrade `react-native-svg` versions with each new SDK version so as long as there are no breakages with `9.2.x` we will do our best to include it in SDK33.

I'm going to close this issue as we track these upgrades internally.

All the best,

Adam

**Comment by maketroli** [comment]
Hi, @AdamJNavarro. Can you at least tell us how long is it going to take?

**Comment by AdamJNavarro** [comment]
Unfortunately we are not in the practice of publicly setting timelines or targets. We are a small team and have a lot of moving parts so we prefer not to promise on something we can not deliver. If you are not already, be sure to subscribe to our blog post [Exposition](https://blog.expo.io/) so you can be notified when the next SDK drops!

**Comment by augustosamame** [comment]
Hey @AdamJNavarro. From you answer I guess there's no way to force Expo to use the latest react-native-svg version ourselves? I asked this on Stack Overflow but got no answer yet: https://stackoverflow.com/questions/55231330/upgrade-expo-react-native-svg-dependency-version

If that's the case, I'd really appreciate it if you can include v.9.3.5 (latest as of today) in SDK33 since it fixes issues with PNG-embedded SVGs as detailed in this issue: https://github.com/kristerkari/react-native-svg-transformer/issues/9

Thanks for all your hard work!
