### ISSUE TITLE
[docs] announcement: availability of documentation in ebook formats (pdf, epub, mobi)

### ISSUE THREAD

**Issue by warren-bank** [expo/expo#3590]
Hi.

Nothing makes me happier than to download full documentation in pdf format; ..I'm a very cheap date.

I'm reading a book on _React Native_ at the moment, and it speaks glowingly about the benefits of using _Expo_ for rapid development. I wanted to learn more, but quickly hit a wall: the documentation is only available on the website.. no pdf.

I took a brief detour.. and wrote some scripts to convert the docs from markdown (obtained from this [repo](https://github.com/expo/expo/tree/master/docs)) to various ebook formats: _pdf_, _epub_, and _mobi_.

The repo containing the scripts can be found [here](https://github.com/warren-bank/expo-docs-ebook). Generated ebooks are included under [tagged releases](https://github.com/warren-bank/expo-docs-ebook/releases).

The scripts are GPLv2.

**Comment by AdamJNavarro** [comment]
Hey @warren-bank,

This is so cool! Thanks a ton for doing this and sharing this the community. It would be awesome if you could make an announcement on our [forums social category](https://forums.expo.io/c/cheer) so that more people can see this!

With that said, we intend to keep Github issues reserved for bug reports so I'm going to close this issue.

Cheers,

Adam
