### ISSUE TITLE
Use audio buffer as a texture

### ISSUE THREAD

**Issue by weepy** [expo/expo#361]
I notice that you can use the camera as a GL texture. Is it possible to do the same with an audio buffer ?

**Comment by jimmylee** [comment]
I imagine @nikki93 or @gkufera could help shine some light on this question?

**Comment by weepy** [comment]
Basically I'd like to do a visualisation something like : https://www.shadertoy.com/view/4ljGD1

**Comment by terribleben** [comment]
I am guessing that this might just end up being a feature request we can move to Canny, but will wait for more info from nikki/greg first.

**Comment by weepy** [comment]
Is canny a person ?

**Comment by brentvatne** [comment]
Haha oops, [Canny is our feature request board](https://expo.canny.io/feature-requests)

ping @nikki93 @gkufera

**Comment by nikki93** [comment]
You can't do this right now and we don't advertise this as a feature so it's technically not an issue. We do hope to eventually have something like this and are moving toward engineering the API so that this is possible -- the camera -> GL API, as you noted, is a step in such a direction. Will update when audio -> GL is on the horizon!
