### ISSUE TITLE
Notification rejection status is always "undetermined"

### ISSUE THREAD

**Issue by markgoodyear** [expo/expo#366]
When I use `Permissions.askAsync(Permissions.REMOTE_NOTIFICATIONS);`, and reject notification preferences, I get:

```
Object {
  "expires": "never",
  "status": "undetermined",
}
```

I would expect the `status` to be set to `denied` so it's possible to handle notifications have been specifically denied.

I get the same result from `Permissions.getAsync` when checking after rejecting the permissions too.

This is running on a physical device (iPhone) and running Expo XDE Version 2.19.2, with Expo 18.

**Comment by terribleben** [comment]
Hi, unfortunately this is just because the underlying iOS API does not disambiguate those cases, so we can't provide any better information. Specifically, the only information given by iOS is "are they granted? (yes/no)." See the [note](https://docs.expo.io/versions/v18.0.0/sdk/permissions.html#expopermissionsremote_notifications) in the docs about this.

Probably the best solution is to store a persistent flag (e.g. in `AsyncStorage`) keeping track of whether you've asked for permissions before.

**Comment by markgoodyear** [comment]
Thanks @terribleben — I didn't spot that in the docs, my bad!
