### ISSUE TITLE
[iOS][Production][API] PushNotificationsIOS.abandonPermissions() or unregisterForRemoteNotifications()

### ISSUE THREAD

**Issue by techpanga** [expo/expo#3734]
Hi

[IOS][Standalone][Production] 

Is there a reason why PushNotificationsIOS.abandonPermissions() not available in expo?

In case of the issues like [https://github.com/expo/expo/issues/2648](url), Looks like this command may help to reset notifications permissions.

I am facing the issue [https://github.com/expo/expo/issues/2648](url) and trying to RESET/UNREGISTER Notification Permissions...

**### abandonPermissions()**
PushNotificationIOS.abandonPermissions();
Unregister for all remote notifications received via Apple Push Notification service.
You should call this method in rare circumstances only, such as when a new version of the app removes support for all types of remote notifications. Users can temporarily prevent apps from receiving remote notifications through the Notifications section of the Settings app. Apps unregistered through this method can always re-register.`

 Please Help!

**Comment by AdamJNavarro** [comment]
Hey @techpanga,

We prefer to keep Github issues reserved for bugs rather than questions. I see you've already made a [forum post](https://forums.expo.io/t/how-to-unregister-notifications-in-expo/20532) which is great. I'm going to investigate this internally and get back to you on the forums. Sorry the delay in response here.

Cheers,
Adam
