### ISSUE TITLE
Splash screen image not showing on ExpoKit Android

### ISSUE THREAD

**Issue by kelvinlawson** [expo/expo#3754]
### Environment

  Expo CLI 2.10.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.4.0 
    npmGlobalPackages:
      expo-cli: 2.10.1

Android ExpoKit target.

### Steps to Reproduce

1. expo init [Advanced workflow or followed by 'expo eject']
2. Run in Android Studio on simulator device.

### Expected Behavior

Default Expo project assets/images/splash.png is shown. The documentation suggests that it should work:
> If you run exp detach on iOS and your app already uses the splash API, the resulting ExpoKit project will contain an Interface Builder launch screen file configured correctly for your app. After this, if you want to make changes to your app's splash screen, just edit the Interface Builder file directly.

### Actual Behavior

White background is shown.

### Reproducible Demo

This happens for the default Expo project created, no changes required.

**Comment by bbarthec** [comment]
@kelvinlawson I've just followed this scenario:
- downloaded `expo-cli@2.14.0`
- `expo init`
  - `managed workflow`#`blank` template
- cd `newly_created_project`
- `expo eject`
  - fill `iOS`/`Android` with some random values
- Android Studio
  - open generated project
  - build & start
  - obtained:
<img src="https://user-images.githubusercontent.com/16623003/55632871-78e0a580-57bb-11e9-9004-7fd0c0d55518.png" width="300" />

Can you provide more specific steps to achieve your issue?
Please ensure that you have newest `expo-cli` installed.

**Comment by kelvinlawson** [comment]
Hi, I've upgraded to expo-cli 2.14.0 and it is working now. splash_background.xml now contains:
`<item><bitmap android:gravity="center" android:src="@drawable/shell_launch_background_image" /></item>`

And the android folder now contains images called shell_launch_background_image.png.

It must have been caused by an older version of expo-cli. Thanks for investigating.

**Comment by tattivitorino** [comment]
Here's how I solved it in case anyone gets into the same problem:
Expo SDK 33 when you eject your app there are a few things you need to do in order to get your splash screen working on android

1. app.json
I put the splash config into the android key so it won’t interfere with the IOS configs
Check this https://docs.expo.io/versions/v33.0.0/guides/splash-screens/ for limitations on resizeMode
"android": {
      "package": “xxxxx”,
      "versionCode": 100,
      "icon": "./assets/imgs/icon-android.png",
      "splash": {
        "image": "./assets/imgs/splash.png",
        "resizeMode": "cover",
        "backgroundColor": "#ededed"
      },
      "publishBundlePath": "android/app/src/main/assets/shell-app.bundle",
      "publishManifestPath": "android/app/src/main/assets/shell-app-manifest.json"
    }

2. splash_background.xml
This file is created without the reference to the bitmap splash screen 
This is how I fixed it:

`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splashBackground"/>
    <item><bitmap android:gravity="center" android:src="@drawable/splash" /></item>
</layer-list>`

3. AppConstants.java
`public static boolean SHOW_LOADING_VIEW_IN_SHELL_APP = false;`

4. Here https://romannurik.github.io/AndroidAssetStudio/index.html you can create 9 patch images for android (Simple NinePatch generator) that you can use for the splash screen
I put each image resolution into their directory and rebuild the app on android studio
You need to reference them here: 
`<item><bitmap android:gravity="center" android:src="@drawable/splash" /></item>`

I hope it helps someone!
Cheers
