### ISSUE TITLE
Configuring Minify/Uglify options

### ISSUE THREAD

**Issue by cogwirrel** [expo/expo#378]
Hey,

I was wondering if it's possible to configure the Minify/Uglify options for an expo app?

Taking a look at the [gulpfile](https://github.com/expo/expo/blob/9a9dfb4103cb0cd5bfff8a97710350321655059f/ios/versioned-react-native/ABI18_0_0/Libraries/Animated/release/gulpfile.js#L84) it looks like we compress, but I'm quite keen to use other minify features such as 'mangle'.

Thanks,
Jack

**Comment by cogwirrel** [comment]
Hmm that gulpfile I linked is probably not actually minifying my code, probably a red herring! Still interested to know if configuring minification is possible though :)

**Comment by terribleben** [comment]
Hello! Sorry for the slow reply. This is all taken care of inside https://github.com/facebook/metro-bundler - specifically I'd check out https://github.com/facebook/metro-bundler/blob/1e6b34f415afe518268be461e70dd75c65db5a91/packages/metro-bundler/src/JSTransformer/worker/minify.js#L23-L26.

We've never had this question before so I'd be curious to know what your motivation or use case is. Maybe there is a different approach.

**Comment by cogwirrel** [comment]
Hey Ben,

No worries! Thanks for pointing me to the right lines! :)

I'm making a mobile game and need to post highscores to a leaderboard, and I'd like to make it difficult for power users to work out how to post arbitrary ones! It's a bit of an [age-old problem](https://gamedev.stackexchange.com/questions/4181/how-can-i-prevent-false-score-reports-to-global-highscore-tables) as the client always has to be authorised to post legitimate scores, so it's more about making it difficult enough that an attacker will give up! Some uglification (particularly changing property names) helps a bit with this :)

Thanks,
Jack

**Comment by cogwirrel** [comment]
@terribleben if it's hard to mangle the JS, are there any other layers of obfuscation/security that come with expo? Either out of the box or configurably? :)

**Comment by dikaiosune** [comment]
@cogwirrel sorry for the delay (again). In general I'd recommend implementing your own symbol mangling or obfuscation techniques before you pass your JS to the root component that is packaged by react native.

For slightly different examples of this, you might look at how Clojurescript, Typescript, or ReasonML are used in React Native -- usually they point their build tools to an output directory and then require from that build directory in their App.js.

We don't provide too much explicit obfuscation, although our protocol for getting JS onto the device is currently undocumented.

You might also be able to do something crazy like `eval`ing some code you fetch from your server.

Sounds like an interesting problem! However since it's a little bit niche I'm going to give this a close. If you have questions about implementing any of these strategies, our [forums](https://forums.expo.io) are a great place to ask general questions.

**Comment by cogwirrel** [comment]
Thanks for the pointers, will check them out! :)

**Comment by Overtorment** [comment]
Might be relevant. Minifying was braking some of my packages when publishing with Expo.
Workaround is here: https://github.com/facebook/react-native/issues/9711
