### ISSUE TITLE
[expo-app-auth][ios] JSON error parsing token response

### ISSUE THREAD

**Issue by mrmuhammadali** [expo/expo#3826]
## 🐛 Bug Report

When using AppAuth.authAsync for Github authentication on iOS, it gives me following error:
`Error: ERR_APP_AUTH: JSON error parsing token response: The data couldn’t be read because it isn’t in the correct format.`
even though I've completed the authentication flow of Github.

### Environment
```
  System:
      OS: macOS 10.14.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo-app-auth: 4.0.0
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1
      react-native-unimodules: 0.2.0
```
**target**: iOS

### Steps to Reproduce
1. Create app using `expo init --template bare-minimum`
2. Install expo-app-auth by `yarn add expo-app-auth`
3. Use following config for AppAuth.authAsync
```
{
  issuer: 'https://github.com',
  clientId: CLIENT_ID,
  clientSecret: CLIENT_SECRET,
  scopes: ['user', 'gist'],
  redirectUrl: 'APP_NAME://oauthredirect',
  serviceConfiguration: {
    authorizationEndpoint: 'https://github.com/login/oauth/authorize',
    tokenEndpoint: 'https://github.com/login/oauth/access_token',
  },
}
```
### Expected Behavior
I expect to get token response object in authAsync.then.

### Actual Behavior
Response sent by token provider(Github) doesn't gets parsed.

**Comment by EvanBacon** [comment]
Kadi Kramer does a good job explaining the problem here https://github.com/FormidableLabs/react-native-app-auth/issues/194 it looks like you have already attempted to open a PR https://github.com/expo/expo/pull/3828. Due to the many issues and disparities associated with native AppAuth I have started working on a rewrite which would shift the fetching to JS and use the `fetch` API, this'll have first class support for Github authentication. https://github.com/expo/expo/pull/7450

**Comment by EvanBacon** [comment]
This is fixed in the new expo-auth-session API which is pure JS, I've also written a guide for using Github auth with it https://docs.expo.io/guides/authentication/#github
