### ISSUE TITLE
Expo- android client 1.18.0 crash

### ISSUE THREAD

**Issue by ngochuu90** [expo/expo#390]
Since I updated Expo -android to version 1.18.0. I can not run any projects.
Expo app always crash when Expo XDE "Building JavaScript bundle"

**Comment by jamsch** [comment]
Having the same problem here. The overlay shows that the app is loading but Expo itself crashes. 

Tried the boilerplate create-react-native-app project as well as the Expo boilerplate.

Problem seems to persist on Android 5.1, 6 and 7. Pretty sure it's not my end because I haven't changed anything project-wise.

![2017-07-20 15_01_45-expo- android client 1 18 0 crash issue 390 expo_expo](https://user-images.githubusercontent.com/12927717/28398788-e9a24d50-6d5c-11e7-9b28-9ff567294ae7.png)

**Comment by jesseruder** [comment]
Taking a look at this now

**Comment by jamsch** [comment]
Upgraded Expo on my personal phone and connected to my remote PC. [video link](https://drive.google.com/open?id=0B8PSYpL5R0x-dnpuZ0trZ08ybUE).

**Comment by jesseruder** [comment]
Pushed out a new version with a fix, should be available soon

**Comment by jamsch** [comment]
Sweet, thanks for the quick fix.

**Comment by jesseruder** [comment]
Sorry about that! The new version should also be available in XDE/exp
