### ISSUE TITLE
Build Error: iOS Could not get BatchedBridge -- Suddenly appearing on Testflight builds +1

### ISSUE THREAD

**Issue by Davidzhu001** [expo/expo#3900]
![151553957338_ pic_hd](https://user-images.githubusercontent.com/9436230/55277715-16605300-533e-11e9-9e22-590869fc0ed8.jpg)

**Comment by nmakiya** [comment]
+1

**Comment by degamer106** [comment]
+1

**Comment by esamelson** [comment]
we're working on a fix for this right now -- hold tight!

**Comment by esamelson** [comment]
The issue has been resolved in production. Unfortunately, bundles produced during the period of downtime may continue to not load correctly. This can be fixed by making any change, even a whitespace one, and republishing with the same version. If it is not workable to make a whitespace change to your bundle, you'll need to republish anyway and email us at secure@expo.io with your username and app slug.

We really apologize for the interruption and any inconvenience this might cause. 😞  We'll be continuing to investigate why this occurred and how we can improve our process to prevent issues like this in the future. If you have any other concerns, please email the address above.

Thanks everyone for reporting this issue so quickly!
