### ISSUE TITLE
Build Error: iOS Could not get BatchedBridge -- Suddenly appearing on Testflight builds

### ISSUE THREAD

**Issue by ptariche** [expo/expo#3901]
### Environment
In the Expo Emulator everything seems to work fine.

### Steps to Reproduce

Build a standalone and deliver application to Testflight.
Open App.
"Could not get BatchedBridge" 

### Expected Behavior

To open the app. The only difference between my build from yesterday to today was updating the expo-cli dependency. Issue may stem from XDL changes? There is definitely a build misconfiguration just for ios. The issue is not present on android.

**Comment by nmakiya** [comment]
+1 Also running into this right now

**Comment by adriankott** [comment]
+1

**Comment by Davidzhu001** [comment]
@nmakiya i think is the building thing errorr. Cause, yesterday i was building everything is fine

**Comment by nmakiya** [comment]
Yeah it's the same as #3900 and #3902 I think

**Comment by Davidzhu001** [comment]
@nmakiya i have debuged for 2 days

**Comment by Davidzhu001** [comment]
@nmakiya do you know when they can solve it? my clients are waiting

**Comment by nmakiya** [comment]
Sorry I'm not from the Expo team, but I'm guessing they'll respond soon

**Comment by degamer106** [comment]
Same here pls fix :( . https://forums.expo.io/t/ios-builds-broken/21064/4

**Comment by fbrunosm** [comment]
+1

**Comment by bcpugh** [comment]
+1 also. Only on second load.

**Comment by ElliotReeve** [comment]
+1 here too since deploying a new version of my app this afternoon.

**Comment by esamelson** [comment]
we're working on a fix for this -- hold tight!

**Comment by nathandallaire** [comment]
Hey all, I see that in the above status link "As of now, new builds and publishes are no longer affected by this issue." 

Do I need to rebuild ios and resubmit to the app store?

**Comment by esamelson** [comment]
The issue has been resolved in production. Unfortunately, bundles produced during the period of downtime may continue to not load correctly. This can be fixed by making any change, even a whitespace one, and republishing with the same version. If it is not workable to make a whitespace change to your bundle, you'll need to republish anyway and email us at secure@expo.io with your username and app slug.

We really apologize for the interruption and any inconvenience this might cause. 😞  We'll be continuing to investigate why this occurred and how we can improve our process to prevent issues like this in the future. If you have any other concerns, please email the address above.

Thanks everyone for reporting this issue so quickly!

**Comment by ptariche** [comment]
👏 👏 👏
