### ISSUE TITLE
Error calling AppRegistry.runApplication in standalone apps

### ISSUE THREAD

**Issue by abdealiaden** [expo/expo#3902]
### Environment
 Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.0.0 - ~/.nvm/versions/node/v10.0.0/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v10.0.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.0.0/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.5.1
    npmGlobalPackages:
      expo-cli: 2.14.0

I am targetting the app to Android. The app is working completely fine with expo, but when I build the app using expo build:android, the apk is not working. When I open the app, it gives me the errors in the screenshots below. The same error appears even when using a simple blank application created via expo init. It was working completely fine until yesterday.

### Steps to Reproduce

1. Create a simple app with tabs using expo init.
2. Run the command expo build:android.
3. Install the apk on the phone.
4. Run the apk which will result in the error in screenshots.

### Expected Behavior

Expected the standalone app to work normally like it was working in expo.

### Actual Behavior

![Screenshot_20190330-225309](https://user-images.githubusercontent.com/13415303/55279887-398e0100-5344-11e9-8857-04f78be87677.jpg)
![Screenshot_20190330-225336](https://user-images.githubusercontent.com/13415303/55279888-398e0100-5344-11e9-8640-4e549eaa340c.jpg)

### Reproducible Demo
This can just be tested with the app created using expo init. (I tried with the one having bottom navigator).

**Comment by viktorvsk** [comment]
+1, also build for ios doesn't work too.
Tried downgrading expo-cli to 2.13.0 but it didn't help

**Comment by nmakiya** [comment]
+1 running into this right now

**Comment by adriankott** [comment]
+1

**Comment by Davidzhu001** [comment]
+1

**Comment by mndev** [comment]
+1

**Comment by degamer106** [comment]
+1 running into this issue as well.  I opened a thread in the General section of the forums: https://forums.expo.io/t/ios-builds-broken/21064/4

**Comment by Davidzhu001** [comment]
anyone know expo team fix problems during weekeds?

**Comment by degamer106** [comment]
pls help fast i must submit to prod on monday :*(

**Comment by esamelson** [comment]
hi all -- we're working on a fix, hold tight!

**Comment by Davidzhu001** [comment]
@easadler thanks  so much. we are waiting here

**Comment by esamelson** [comment]
The issue has been resolved in production. Unfortunately, bundles produced during the period of downtime may continue to not load correctly. This can be fixed by making any change, even a whitespace one, and republishing with the same version. If it is not workable to make a whitespace change to your bundle, you'll need to republish anyway and email us at secure@expo.io with your username and app slug.

We really apologize for the interruption and any inconvenience this might cause. 😞  We'll be continuing to investigate why this occurred and how we can improve our process to prevent issues like this in the future. If you have any other concerns, please email the address above.

Thanks everyone for reporting this issue so quickly!

**Comment by Slapbox** [comment]
@esamelson, things happen; the Expo team rocks!
