### ISSUE TITLE
Error installing or running app. Error: getaddrinfo ENOTFOUND dpq5q02fu5f55.cloudfront.net dpq5q02fu5f55.cloudfront.net:443

### ISSUE THREAD

**Issue by merlin-li** [expo/expo#3906]
### 

I got the problem during "Run on iOS simulator" : 

Error installing or running app. Error: getaddrinfo ENOTFOUND dpq5q02fu5f55.cloudfront.net dpq5q02fu5f55.cloudfront.net:443

Then:
/We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN.

anyone can help? I reinstall the expo, but still remains.

**Comment by cruzach** [comment]
Please use the issue template, it provides us with a lot of the info we need to help you out

There doesn't seem to be issues with our tunnel provider as this is the only instance I've seen of this recently.

**Comment by cruzach** [comment]
@yarapolana I think you must have run into [this issue](https://github.com/expo/expo/issues/1966), and maybe at some point changed those settings or something else when updating? In any case, I'm going to close this issue since it's been inactive for a while, and a fix was made for a similar issue referenced above
