### ISSUE TITLE
Initializing task consumer 'expo.modules.location.a.b' failed.

### ISSUE THREAD

**Issue by xanderdeseyn** [expo/expo#3918]
### Environment

```

Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.4 => 4.1.6 
      expo: ^32.0.0 => 32.0.1 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 

```

### Steps to Reproduce

Define task in App.js file (not in Class)

```js
TaskManager.defineTask('TEST', ({ data: { locations }, error }) => {
  console.log(locations)
  Alert.alert('New location')
  if (error) {
    console.log(error.message)
    return
  }
  console.log('Received new locations', locations)
})
```

Next, in componentDidMount of App, we start tracking location:

```js
await Location.startLocationUpdatesAsync('TEST', {
      distanceInterval: 50,
      accuracy: Location.Accuracy.Highest,
    })
```
### Expected Behavior

Starts tracking location updates

### Actual Behavior

Crashes and throws `Error: Initializing task consumer 'expo.modules.location.a.b' failed.`

IMPORTANT NOTE:

This crash only happens in production, it works fine in development.

**Comment by cruzach** [comment]
Hey @N1ghtly ,

Right off the bat since you said the problem only happens in production, have you [added the appropriate keys](https://docs.expo.io/versions/latest/sdk/task-manager/#configuration-for-standalone-apps) to your app.json file? (TaskManager works out of the box in the Expo Client, but some extra configuration is needed for standalone apps.)

Let me know if that fixes it!
-Charlie

**Comment by N1ghtly** [comment]
Hi guys, I figured out what the problem was: Proguard.
Add this rule to your `proguard-rules.pro` file and it will work: 

`-keep class expo.modules.location.** { *; }`

If you look at the source, some voodoo is happening with retrieving the name of the constructor and calling that (which proguard messes up with their obfuscation).

I think this should be mentioned in the docs.

**Comment by expjess** [comment]
@N1ghtly thanks for the update! We'd welcome a PR to the docs if you'd like!

**Comment by andrejpavlovic** [comment]
> Hi guys, I figured out what the problem was: Proguard. Add this rule to your `proguard-rules.pro` file and it will work:
> 
> `-keep class expo.modules.location.** { *; }`
> 
> If you look at the source, some voodoo is happening with retrieving the name of the constructor and calling that (which proguard messes up with their obfuscation).
> 
> I think this should be mentioned in the docs.

I had to add this for SDK 50
