### ISSUE TITLE
Update react-native-reanimated to >= 1.0.0 and remove from DangerZone

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#3969]
@kmagiera released stable 1.0.0 at App.js Conf, we should include this in SDK33 because it also adds support for the powerful Transitions API which we are already using in react-navigation

**Comment by sjchmiela** [comment]
@dsokal — for upgrading third party libraries there are Gulp tasks in `tools` which you run to fetch the latest changes into Expo project. For reanimated it's:
https://github.com/expo/expo/blob/a98199422933f0ed9fc00cff0d720ba320083ca6/tools/gulpfile.js#L299-L312

Sometimes you would need to also update our fork of the repo, like with [`react-native-maps` task](https://github.com/expo/expo/blob/a98199422933f0ed9fc00cff0d720ba320083ca6/tools/gulpfile.js#L182-L207), but that's not the case with reanimated.

When I upgrade third party libraries I usually upgrade one platform per commit (so `gulp update-… --android`, commit, `… --ios`).

These scripts conveniently change some strings in imported files, like eg. package name of Android classes, so that it matches `versioned.host.exponent.…` which ensures that they'll be versioned when we create a new SDK release.
