### ISSUE TITLE
Exp build ios asks for certificate password

### ISSUE THREAD

**Issue by stochris** [expo/expo#405]
When trying to build an ios app, the cli asks for the .p12 certificate password. However, the certificate doesn't have a password.

Also, I cannot generate any more certificates, since the limit was reached

How could I overcome / work my way around this ?

**Comment by brentvatne** [comment]
cc @dikaiosune

**Comment by stochris** [comment]
I've managed to clear one of the already existing certificates from Apple. However, I can confirm that none of the existing certificates had empty password, and that I could not add any one of them through the exp cli

**Comment by dikaiosune** [comment]
@stochris unfortunately there are a few implementation details that mean we won't be able to support p12 files without a password in the near future. I believe that when generating the p12 file (https://calvium.com/how-to-make-a-p12-file/) you can choose to provide a password for the export, even if there wasn't a password set upon uploading to the Developer Portal.

**Comment by Maxwell2022** [comment]
@anp from what I could see in the `expo-cli` project, [it uses Fastlane](https://github.com/expo/expo-cli/blob/675362affce65f815f37ec5b9682c3da967f019b/packages/exp/src/commands/build/auth.js#L93) to generate the `.p12` Provisioning certificate and Fastlane is not setting passphrase for the certificate. 

So it means that we cannot re-use the certificate that has been generated by the `expo-cli` because expo is requiring a password of at least 1 character for certificate's passphrase.

It seems to be a bit contradictory unless there is a very good reason to not re-use generated `.p12` certificates that are generated by expo.

**Comment by et304383** [comment]
@anp please reopen this.  This is a pretty big issue.  We shouldn't have to generate brand new distribution certificates just to use expo.

**Comment by ide** [comment]
Have you tried adding a password to a password-less .p12 file? I expect openssl offers this out of the box with something like `openssl pkcs12 -info -in cert.p12 -noout`.

**Comment by AlexCatch** [comment]
Not all certs will have password (like those exported from Fastlane Match) it would make more sense to have entering a password optional.
