### ISSUE TITLE
Crashlytics / Fabric on iOS?

### ISSUE THREAD

**Issue by oliverbenns** [expo/expo#408]
Should there be a config object for ios too? Is this just missing from the docs or does this functionality not exist?

```
"ios": {
  "bundleIdentifier": "",
  "buildNumber": "",
  "config": {
    "fabric": {
      "apiKey": "",
      "buildSecret": ""
    }
  }
},
```

It seems this might have been an issue since `9.0.0`:
https://www.reddit.com/r/exponent/comments/58sfj9/to_get_fabric_crashlytics_to_work_what_steps/

**Comment by terribleben** [comment]
Hi, we can't support this right now due to an architectural limitation (see [docs](https://docs.expo.io/versions/v19.0.0/guides/errors.html#what-about-native-errors)). Nonetheless, we are tracking it as a [feature request](https://expo.canny.io/feature-requests/p/support-fabric-native-errors-on-ios), so please upvote!

**Comment by radiodario** [comment]
I'm wondering why is crashlytics a dependency on ejected projects? if so, how can we configure it (we're mainly interested on crash reporting)

**Comment by brentvatne** [comment]
hi @radiodario! I'm not familiar with why that is the case, @terribleben can you speak to it?
