### ISSUE TITLE
Remove Branch from iOS as well

### ISSUE THREAD

**Issue by ide** [expo/expo#4108]
See https://forums.expo.io/t/expokit-branch-io/21656/9 for context. Essentially, the fact that Branch is available on iOS but not Android makes it difficult to install react-native-branch. We should be consistent here and either support Branch well or not at all -- and given that Google has shown to remove apps with Branch without notice, this is undue risk for everyone who doesn't use Branch.

**Comment by jivasoft** [comment]
My app was built with Expo SDK 31.0.0. Google removed it from the store because it includes Branch (which I don't use or want) and there isn't an opt-in within the app. It seems from the reading I've done that the latest SDK does not include Branch. Is this right? I don't want to update to a new SDK, resubmit my app and then have it rejected or published and then abruptly removed.

**Comment by zachdixon** [comment]
Any updates on this? My app was just removed from the Play store for having Branch (which I don't use either) and I'm on the latest SDK (32)

**Comment by ide** [comment]
This issue is about iOS only. The Android issue has been resolved; please see https://blog.expo.io/changes-to-expo-branch-support-d002c4bc564e.

**Comment by jivasoft** [comment]
Yes, I rebuilt my Android app and removed all prior builds from the Play Store. The app is available again in the Play Store.

**Comment by kirkness** [comment]
Just ran into an issue around this, ive got an ExpoKit app with react-native-branch installed on android and the expo branch existing on ios. Since [this change](https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/commit/07e2be4e982b622c384ed51477d960c97cc60c46) calling `Branch.getLatestReferringParams()` on iOS crashes the app - works on android. I've had to do the following:

```js
Platform.OS === 'ios'
  ? RNBranch.getLatestReferringParams()
  : Branch.getLatestReferringParams()
```


Is there a better way to get this consistently installed across both platforms?

**Comment by llamaluvr** [comment]
One more data point for removing iOS branch from the ExpoKit side of things. I had installed `react-native-branch` separately after it was removed from Android. I just went to upgrade to Expo 35, and am getting this error on `pod install`:

```
[!] CocoaPods could not find compatible versions for pod "Branch":
  In snapshot (Podfile.lock):
    Branch (= 0.27.1, ~> 0.27.1)

  In Podfile:
    ExpoKit/Core (from `http://github.com/expo/expo.git`, tag `ios/2.13.0`) was resolved to 35.0.0, which depends on
      Branch (~> 0.28)

    react-native-branch (from `../node_modules/react-native-branch`) was resolved to 3.1.1, which depends on
      Branch (= 0.27.1)

It seems like you've changed the constraints of dependency `Branch` inside your development pod `react-native-branch`.
You should run `pod update Branch` to apply changes you've made.
```

3.1.1 is the last version of react-native-branch that supports React Native <0.60, and it uses Branch 0.27.1. expo-branch (https://github.com/expo/expo/blob/ios/2.13.0/packages/expo-branch/package.json) also uses react-native-branch@3.1.1, yet the podspec specifies Branch 0.28.

**Comment by sgatenby** [comment]
@ill

> One more data point for removing iOS branch from the ExpoKit side of things. I had installed `react-native-branch` separately after it was removed from Android. I just went to upgrade to Expo 35, and am getting this error on `pod install`:
> 
> ```
> [!] CocoaPods could not find compatible versions for pod "Branch":

Did you find a solution?
Hit this as well as we had to upgrade to deal with an issue in 34 that was crashing apps with Guided assistance on and now Branch conflicts are preventing a release. 

I've managed to hack the podfile.lock file to look selectively at old versions, but it's not a serious solution. 

Are we able to reference expokit packages separately so we don't get slugged with the latest experiment in this way?

**Comment by jste7102** [comment]
Any advice on what to do here? I am experiencing the same issue as llamaluvr.  Is it possible to remove Branch from what is pulled into ExpoKit/Core through configuration settings on the podfile?

I guess the solution here is to just upgrade to Expo 36.
