### ISSUE TITLE
[docs] Document Third Parameter for IntentLauncherAndroid.startActivityAsync

### ISSUE THREAD

**Issue by SteveAquino** [expo/expo#4123]
After a lot of trial and error, I discovered an undocumented third parameter for `IntentLauncherAndroid.startActivityAsync`, which is required for some intents (specifically opening the app settings page).

The documentation listed [here](https://docs.expo.io/versions/latest/sdk/intent-launcher/#intentlauncherstartactivityasyncactivityaction-intentparams) describes the first two params, but neglects to document the third param which appears to be required in some cases.

Here is an example code snippet that uses the third param:

```javascript
IntentLauncherAndroid.startActivityAsync(
  IntentLauncherAndroid.ACTION_APPLICATION_DETAILS_SETTINGS,
  {},
  'package:com.company.app'
);
```

**Comment by ankhzet** [comment]
As far as i can see, this issue is now outdated. `IntentLauncherAndroid` is deprecated, and the documentation for `IntentLauncher` mentions the `data` prop of the params object (tho, documentation lacks the example on how to use it, imo).

Documentation: https://docs.expo.io/versions/latest/sdk/intent-launcher/

Currently, you can pass data to an activity using `data` prop of the params object, f.e. this works for me:

```typescript
await IntentLauncher.startActivityAsync(IntentLauncher.ACTION_APPLICATION_DETAILS_SETTINGS, {
  data: `package:${(
    (Constants.appOwnership === 'standalone')
      ? Constants.manifest.android.package
      : 'host.exp.exponent'
  )}`,
});

```
