### ISSUE TITLE
Pick up change to dev mode when reloading the app

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#413]
Currently if you disable or enable development mode, you need to close the experience and reopen it. For iOS, this means either closing Expo client or opening another experience and then opening the original one again. We should fix this

Edit by Ben: Closing the Expo client is no longer required, this was due to a separate issue with Refresh. Now you can "Refresh." But you still can't "Reload" to pick up the change, so leaving this issue open.

**Comment by brentvatne** [comment]
# iOS

- Open app in dev
- Toggle dev mode in XDE
- Press ⌘+r: does not update `__DEV__`
- Press *Reload* in dev menu: does not update `__DEV__`
- Press *Refresh* in dev menu: updates `__DEV__` as expected

**Comment by brentvatne** [comment]
# Android

- Open app in dev
- Toggle dev mode in XDE
- Press *Reload* in dev menu: does not update `__DEV__`
- Press refresh icon notification bar: updates `__DEV__` as expected

**Comment by terribleben** [comment]
"Reload" or Cmd+R in iOS are just the standard React Native devtool for reload, which will always request the same bundle URL. These are useful sometimes (because they are fast) but they won't pick up changes to your manifest, which in this case would include a change to the bundle url.

Possible solutions:
- Change upstream to pass dev mode as something other than a query param?
- Change upstream packager server to use http redirect when the bundle url changes?
- Disable the Reload option and only offer the Expo Refresh option on both platforms?
