### ISSUE TITLE
[Amplitude] Events properties not working

### ISSUE THREAD

**Issue by adriller** [expo/expo#4135]
### Environment

    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.7.0 - C:\laragon\bin\yarn\bin\yarn.CMD
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

Target: Expo managed app for Android

### Steps to Reproduce

import { Amplitude } from 'expo';
componentDidMount = () => {
    Amplitude.logEventWithProperties('PageView', {name: "home_screen"});
}

I have also built the .apk file to test in production mode, but it doesn't work as well.

### Expected Behavior
Amplitude.logEventWithProperties should display the event properties on Amplitude dashboard, like "name" as property and "home_screen" as value.

### Actual Behavior

The event PageView is caught by Amplitude, but the properties aren't.
![image](https://user-images.githubusercontent.com/7690416/57237549-d7d54c80-6ffd-11e9-8f8c-39b8be62259e.png)
![image](https://user-images.githubusercontent.com/7690416/57237581-e7549580-6ffd-11e9-8ba2-f34eed71d4f7.png)

### Reproducible Demo

https://snack.expo.io/B1vFpAajN

**Comment by cruzach** [comment]
Hi @adriller!

I just tested this and was able to see the event property in the Amplitude Dashboard.
![image](https://user-images.githubusercontent.com/35579283/57252538-58a24180-701a-11e9-9d40-f08d1e11d83e.png)

Not sure what could be different since you used a Snack so SDK version is identical.

Can you try putting the Amplitude calls in **not** a lifecycle method? For instance, I just put them in an `onPress` for a `Button` (for ease of testing). Idk why that would cause any difference but other than that everything is the same.

-Charlie

**Comment by adriller** [comment]
Thank you! 
Sounds weird, but I've just changed the property key 'name' to 'screen' and it worked both in a lifecycle and onPress methods.
