### ISSUE TITLE
setTimeout executes callback immediately when Remote JS Debugging is enabled

### ISSUE THREAD

**Issue by srmagura** [expo/expo#4172]
### Environment

Expo CLI 2.17.1 environment info:
  System:
    OS: Windows 10
  Binaries:
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files (x86)\nodejs\npm.CMD

Target: Android and iOS

### Steps to Reproduce

1. Create a new expo app with `expo init`, using the blank template.
2. Add the following function to App.js and invoke the function from componentDidMount()
```
function loop() {
    console.log(new Date().getSeconds())
    setTimeout(loop, 1000)
}
```
3. `expo start` and open the app on an iOS or Android device. Tested on iOS 12.2 and Android 7.1.1.
4. By default, remote JS debugging is disabled. The log messages in the expo console window will show the expected behavior: "1, 2, 3, 4, 5, ..."
5. On the mobile device, enable remote JS debugging from the developer menu. The log messages in the Expo console windows will be "4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, ...". I.e. the loop is executing very rapidly.

### Expected Behavior

The console.log() messages show each second exactly once while Remote JS Debugging is enabled:
```
1
2
3
4
5
6
...
```

### Actual Behavior

console.log() is called rapidly and each second displays many times, e.g.:
```
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
...
```

### Reproducible Demo
https://github.com/srmagura/expo-settimeout-repro

**Comment by cruzach** [comment]
Hey @srmagura ,

I just tried reproducing this, and got the correct behavior (as you described under `Expected Behavior`. So I'm thinking it must be something configured in your environment..

What SDK version are you using, what version of Node are you running, and what version of the Expo Client are you running this on? 

Thanks!
Charlie

**Comment by srmagura** [comment]
Hey Charlie, my version information is below. 

I did some more testing just now and I found that the issue had magically fixed itself on my Android phone. I cannot think of anything that has changed, so it's possible I made a mistake during my original Android testing, or expo / metro had gotten into a messed up state.

The issue is still there on iPhone, which I have tested more thoroughly than Android. I tried a number of things to see if they would fix the issue: upgrading Node versions, restarting the iPhone, and testing without using mitmproxy. None of them seemed to make a difference. It's an iPhone 6, by the way.

Thanks. This isn't a showstopper issue for me because I don't rely on the JS debugger very much.

**Expo Client versions**
Android: 2.10.6
iOS: 2.10.0.105122

**Expo SDK version:** 32

**Node version:** 10.13.0
Upgraded to latest LTS (10.15.3) but issue persisted. Upgraded to latest (12.2.0) with the same result.

**Comment by cruzach** [comment]
Glad it fixed itself for Android, at least! 

Just tested on physical iPhone and simulator, neither resulted in the issue (same environment, also tried opening the remote debugger URL in chrome & safari). Only difference seems to be OS

**Comment by srmagura** [comment]
Here's a detail I accidentally left out - not sure if it is useful. When using the React Native Debugger standalone application, I get the warning "react-devtools agent got no connection" each time my app starts up. I do not get this message when using the default remote debugger that opens in Chrome.

**Comment by cruzach** [comment]
@srmagura I still haven't been able to repro this. I was wondering if updating to recent version of `expo-cli` or the react native debugger helped to fix this?

**Comment by srmagura** [comment]
Unfortunately, the issue is still present with SDK 35 and `expo-cli` 3.11.3.

This time, I tested it in my main app where I originally noticed the problem. I can update the minimal repro to SDK 35 as well if that would be helpful.

The issue occurs when using the standalone React Native Debugger (v0.10.5 - latest stable) or the browser-based JS debugger that comes with Expo.

`expo diagnostics` output:
Expo CLI 3.11.3 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD

Node version is 12.9.0.

**Comment by cruzach** [comment]
Hm that's so odd, I still can't reproduce it, same React Native Debugger version. 

expo diagnostics output is
```
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^36.0.0 => 36.0.0
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.11.3
```
so same expo-cli, same node, same RNdebugger. Maybe this is a windows issue? But it hasn't been reported anywhere else

Can you try this on a bare React Native project and see if you get the same behavior?

**Comment by srmagura** [comment]
Here are some additional tests I ran. All of these were using the built-in debugger that opens in Chrome, not the standalone React Native Debugger.

<table>
<tr><td>Expo or bare react-native?</td>
<td>OS for `expo start` / `react-native run-ios`</td>
<td>Device/simulator</td>
<td>Is setTimeout behavior correct?</td></tr>
<tr><td>Expo</td><td>Windows 10</td><td>iPhone 6</td><td>❌</td></tr>
<tr><td>Expo</td><td>OS X</td><td>iPhone 6</td><td>❌</td></tr>
<tr><td>Bare</td><td>OS X</td><td>iPhone 11 simulator</td><td>✔</td></tr>
</table>
Let me know if you want me to run any other cases.     

If I am really the only person who is hitting this, probably not worth fixing. I just use Android when I need to connect to the debugger.

**Comment by cruzach** [comment]
Did you happen to try on Expo with the same simulator as you did on bare? Would be interested if it worked correctly then

**Comment by srmagura** [comment]
Behavior was correct when running the Expo app on the iPhone simulators. I updated my table accordingly.

So it seems to happen only on real hardware, and there is no evidence that the issue is specific to Expo.

I can try testing the bare app on my iPhone 6, though it will probably not be anytime soon. I only have access to a Mac at work and I'll need to jump through the hoops to get my iPhone "provisioned" for testing, or whatever Apple calls it.

**Comment by srmagura** [comment]
I was able to reproduce it in bare React Native and found that there is already an issue for it in the React Native repo, [#26828](https://github.com/facebook/react-native/issues/26828).  😁

Turns out it occurs when the iPhone's time and the PC's time don't match. My iPhone's clock has been 10+ minutes in the future this whole time (possibly because it is lacking a SIM card), so that explains it!

**Comment by sandinosaso** [comment]
This is still an Issue I can confirm, in the latest expo version 0.40.0

```
expo@~40.0.0:
  version "40.0.0"
  resolved "https://registry.yarnpkg.com/expo/-/expo-40.0.0.tgz#6caf03587532cd18b482991332a8b75eeca2fcb7"
```

It was hard for me to figure out what was going on, I literally expended hours thinking my Hooks logic was wrong, then I doubted the Snackbar component from 'react-native-paper' (internally uses setTimeout for the duration it uses to show the snackbar) was not working ok, till I figured out that it was this issue.

This also happens when you go to https://snack.expo.io/ and Choose Android as Device (so I assume that it using debug mode on).

Try for example: [SnackBar Expo Example](https://snack.expo.io/?name=Snackbar&description=https%3A%2F%2Fcallstack.github.io%2Freact-native-paper%2Fsnackbar.html&code=import%20*%20as%20React%20from%20%27react%27%3B%0Aimport%20%7B%20View%2C%20StyleSheet%20%7D%20from%20%27react-native%27%3B%0Aimport%20%7B%20Button%2C%20Snackbar%20%7D%20from%20%27react-native-paper%27%3B%0A%0Aconst%20MyComponent%20%3D%20()%20%3D%3E%20%7B%0A%20%20const%20%5Bvisible%2C%20setVisible%5D%20%3D%20React.useState(false)%3B%0A%0A%20%20const%20onToggleSnackBar%20%3D%20()%20%3D%3E%20setVisible(!visible)%3B%0A%0A%20%20const%20onDismissSnackBar%20%3D%20()%20%3D%3E%20setVisible(false)%3B%0A%0A%20%20return%20(%0A%20%20%20%20%3CView%20style%3D%7Bstyles.container%7D%3E%0A%20%20%20%20%20%20%3CButton%20onPress%3D%7BonToggleSnackBar%7D%3E%7Bvisible%20%3F%20%27Hide%27%20%3A%20%27Show%27%7D%3C%2FButton%3E%0A%20%20%20%20%20%20%3CSnackbar%0A%20%20%20%20%20%20%20%20visible%3D%7Bvisible%7D%0A%20%20%20%20%20%20%20%20onDismiss%3D%7BonDismissSnackBar%7D%0A%20%20%20%20%20%20%20%20action%3D%7B%7B%0A%20%20%20%20%20%20%20%20%20%20label%3A%20%27Undo%27%2C%0A%20%20%20%20%20%20%20%20%20%20onPress%3A%20()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Do%20something%0A%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%7D%3E%0A%20%20%20%20%20%20%20%20Hey%20there!%20I%27m%20a%20Snackbar.%0A%20%20%20%20%20%20%3C%2FSnackbar%3E%0A%20%20%20%20%3C%2FView%3E%0A%20%20)%3B%0A%7D%3B%0A%0Aconst%20styles%20%3D%20StyleSheet.create(%7B%0A%20%20container%3A%20%7B%0A%20%20%20%20flex%3A%201%2C%0A%20%20%20%20justifyContent%3A%20%27space-between%27%2C%0A%20%20%7D%2C%0A%7D)%3B%0A%0Aexport%20default%20MyComponent%3B&dependencies=react-native-paper)
