### ISSUE TITLE
[document-picker] Passing multiple mime types on document picker

### ISSUE THREAD

**Issue by maharjanaman** [expo/expo#4263]
I'm trying to get spreadsheet format files only but seems it is currenty not possible. It would be nice to have this. Also is it possible to use some wildcard for showing spreadsheets format only? I tried `application/*` but its not working.

**Comment by cruzach** [comment]
Hey again @maharjanaman,

Please remember that we keep Github for bug reports, and when reporting a bug we need you to follow the issue template we provide, so that way we can help as best/fast as we can!

I suggest posting questions like this on the [Forums](https://forums.expo.io/) 👍

**Comment by aizaz-mesearch** [comment]
If this issue is still open, is there an update on whether DocumentPicker is capable of taking in an array of mime-types?

**Comment by SampsonCrowley** [comment]
Bump, this is a huge UI issue. on android, it's not possible to do even simple filters like `image/*` because android cameras save both a `raw` and `jpg` image. need to be aple to specify multiple specific formats. this is definitely something that is possible for all of the main platforms (web, android, iOS); there for it's unexpected to not be able to do something so fundamental to a proper file picker

**Comment by ursNj** [comment]
@EvanBacon any fix for this ???

**Comment by varstos** [comment]
Any progress on this having the same issue. My problem would be fixed by enabling `application/*` or being able to pass array of mime-types.

**Comment by jOR13** [comment]
Already fixed?

**Comment by DaniSido** [comment]
Sorry, i didn't understand how to fix this bug
