### ISSUE TITLE
[expo-app-auth][android] Android OS asking which app to open the redirect with

### ISSUE THREAD

**Issue by derekstavis** [expo/expo#4287]
### Environment

```

  Expo CLI 2.15.4 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.0.0 - /usr/local/bin/fish
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.4 => 32.0.5 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.9.2 => 3.9.2 
```

This issue happens only on *Android*.

### Steps to Reproduce

- Let `app.json` have `"scheme": "com.example.mobile", "android": { "package": "com.example.mobile" }`.
- Add a login button that calls `AppAuth.authAsync` against the issuer.
- Build a standalone version of the app using `expo build:android`.
- Run the app and touch the login button.
- Complete the authentication on details.
- Android will ask what app to use to open the redirect, but present two equal options.

### Expected Behavior

Android shouldn't ask for which app to open the redirect with and the flow should continue as usual.

**Comment by IvanKovnovic** [comment]
Same problem here. My only difference to thread opener is that I'm working on Windows, but aside of that same expo / rn stack

**Comment by derekstavis** [comment]
This issue only happens when the `scheme` and `android.package` have the same value. Ideally I want to be able to use the same bundle identifier for scheme and package name.

**Comment by EvanBacon** [comment]
Will investigate this further after https://github.com/expo/expo/pull/7450 lands

**Comment by doubleh311** [comment]
@EvanBacon, @cruzach  how are you doing?

I am facing the similar issue. I am integrating the expo-google-app-auth to an existing app and facing the issue that

1. Follow the instruction everything works well on Expo Client for both Android and iOS
2. On Standalone app, the package name contains underscore cause error invalid redirect_uri. I have change the package name and standalone apps work well with package name without underscore but the app is lived on stores so I cannot suggest to change the package name. 
3. I am creating the custom scheme for redirect instead of the package name. The Sign-in-flow can redirect after user select the account to sign in but it hangs/stuck and cannot resolve the Google.logInAsync result.
4. This issue occur on Android (still not test wil standalone iOS) and I have spent some days on looking for any solution but no hope
5. I have upgrade from SDK 38 to SDK 39 but it is not fixed.

Would you guy have any suggestion or workaround for this case?

Many thanks

**Comment by treyhoover** [comment]
I'm experiencing this as well. I would actually be okay with changing the scheme to something other than `android.package` to avoid this behavior but anything else results in a redirect_uri_mismatch error...

**Comment by taschdo** [comment]
@doubleh311 Good afternoon. I have the same problem. Did you manage to solve it?

**Comment by doubleh311** [comment]
@taschdo still not have any progress for this issue, I plan to try another way to login, give up this expo-google-app-auth because there is not any response from other guys

**Comment by dacevedo12** [comment]
This still happens even with auth-session btw

**Comment by dacevedo12** [comment]
@EvanBacon this behaviour isn't documented in https://docs.expo.io/versions/latest/sdk/auth-session/#usage-in-standalone-apps

`mycoolredirect` can't be the same package identifier. Is this intended?

**Comment by acrdlph** [comment]
I had the same issue and it disappeared when I removed the explicit `"scheme": "com.myapp"` from my `app.json`.

I had set this explicitly because I wanted to make sure it's equal to my `android.package` as prescribed in the docs. But it turns out that this not necessary and I should have let expo handle it.. Now it works for me on Android standalone without any additional workaround.

PS: I tried to reproduce the issue in an MCVE, but there it worked fine even with the scheme specified explicitly in app.json. So it must additionally have something to do with the other dependencies/components I have in my project..

**Comment by GavinConnolly** [comment]
We are also experiencing the same issue when authenticating with Google - the `scheme` is required to match the `android.package` name but this exposes the bug of a duplicate handler (one interfering with the auth process).

Has anyone found a successfully way of dealing with this?

Thanks all!

**Comment by sjelena97** [comment]
> 

Any solutions?

**Comment by ferdinanddoremus** [comment]
Problem also occurs on `expo-auth-session` package.
Only way I've found to avoid duplicate handler is to remove `expo.scheme` on config file.
But this actually breaks Linking module in production standalone build, and I need it.
Also tried [this solution](https://forums.expo.dev/t/app-appears-twice-on-open-with-list-after-google-auth/55659/6?u=tlmader) with no luck, google throwing a `redirect_mismatch_url` error.
