### ISSUE TITLE
[ios] BarCodeScanner takes a lot of time to render (testing on NCL)

### ISSUE THREAD

**Issue by ide** [expo/expo#4309]
Eric is going to look into this - depending on what we find and how far we get, we may or may not need help from Tomasz.

**Comment by esamelson** [comment]
underlying issue is that `layoutSubviews` call is delayed by ~5-10 seconds when navigating to the BarCodeScanner screen in NCL, but I was unable to reproduce outside of NCL (preview displays as soon as the view is mounted in react). my guess is that the issue is something in react-navigation or one of its dependencies (react-native-screens maybe?). i'm not sure yet why it's showing up only on this particular screen.

**Comment by esamelson** [comment]
after more investigation, this seems to have to do with the number of other views that are mounted on the screen at the same time as the BarCodeScanner view. for example, commenting out these three `Button`s makes the delay go away: https://github.com/expo/expo/commit/94ad6b1dc4af1635017de74dca9feb86b417660c#diff-f2bb4551d40677f5e1560c5d463eb601R117

still not sure what the underlying cause is here. however, i confirmed that this behavior was the *same* in SDK32, so going to move this issue to nonblocking for now.
