### ISSUE TITLE
App does not launch on clicking notification in Android 6

### ISSUE THREAD

**Issue by vasyas** [expo/expo#4344]
Expo CLI 2.18.4 environment info:
```
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.0 => 32.0.0
      @types/react: ^16.8.1 => 16.8.1
      @types/react-native: ^0.57.32 => 0.57.32
      expo: ^32.0.0 => 32.0.4
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      expo-cli: 2.18.4
```

Also checked on expo=32.0.6

Android version 6.0.1, Xiaomi Redmi4.
Standalone app, using Expo notifications.

### Steps to Reproduce

I can deliver push notifications successfully to the status bar of Android devices.
But when the app is in the background or it is closed, the app doesn’t open on clicking notification in the status bar.

When the app is in the foreground, it receives the notification as expected.
Also, on receiving the notification, app launcher icon has the badge attached.

iOS and Android 7 works ok - only Android 6 seems to be affected.

### Reproducible Demo

Nothing special here.

Saving the token:
```
    // skipped permission check
    const notificationToken = await Notifications.getExpoPushTokenAsync().
    await backend.post(api.client.setNotificationToken, { notificationToken })
```
Listening for notifications:
```
    Notifications.addListener(this.receiveNotification)
    ...
    receiveNotification = (notification) => {
        if (notification.origin == "selected") {
            console.log("=== Got notification", notification)
        }
    }

```

Sending the notification from the server:
```
    const [chunk] = expo.chunkPushNotifications([{
        to: notificationToken,
        title: "Title",
        body: "Body",
        data: { key: "value" },
    }])
   await expo.sendPushNotificationsAsync(chunk)
```

The bug is also reproducible with Expo notification test tool.

**Comment by cruzach** [comment]
Hey @vasyas, sorry for the lack of response here, but this has been fixed in the new `expo-notifications` module which was released with SDK 38 🎉 [here's the relevant documentation](https://docs.expo.io/versions/latest/sdk/notifications/)

I used [this snack](https://snack.expo.io/@charliecruzan/notifications4344) to test on an Android 6 emulator (had to use local notifications since emulators don't support push notifications), and the app was launched when tapping on the notification both when it was backgrounded & killed. Let me know if you do still see this issue with the new module though, thanks!
