### ISSUE TITLE
Compile TypeScript project with SDK 33 and legacy APIs

### ISSUE THREAD

**Issue by wcandillon** [expo/expo#4357]
## 🐛 Bug Report

Congratulation on SDK 33 🎉 What an incredible achievement from you guys. It works great.
It works great with TypeScript too! But I'm not able to use the legacy APIs. It seems to be related to the `expo/build/deprecated.d.ts` file being empty. Which conflict with the following declaration in `expo/build/Expo.d.ts`:

```ts
export { Accelerometer, AdMobBanner, AdMobInterstitial, AdMobRewarded, Animated, Amplitude, AppAuth, Asset, Audio, BackgroundFetch, BarCodeScanner, Barometer, BlurView, Brightness, Calendar, Camera, Constants, Contacts, Crypto, DocumentPicker, Easing, Facebook, FacebookAds, FaceDetector, FileSystem, Font, GestureHandler, GL, GLView, GoogleSignIn, Gyroscope, Haptic, Haptics, Icon, ImageManipulator, ImagePicker, IntentLauncher, IntentLauncherAndroid, KeepAwake, LinearGradient, LocalAuthentication, Localization, Location, Magnetometer, MagnetometerUncalibrated, MailComposer, MapView, MediaLibrary, Permissions, Print, PublisherBanner, Random, SecureStore, Segment, Sensors, Sharing, SMS, Speech, SQLite, Svg, takeSnapshotAsync, TaskManager, Transition, Transitioning, Video, WebBrowser, WebView, } from './deprecated';
```

### Environment

TypeScript 3.2.4
[tsconfig.json](https://gist.github.com/wcandillon/a3af2aa201614091b8b2c0a6ffe97034)

### Steps to Reproduce

```sh
expo init --template blank@next typescript-test
cd typescript-test
curl -O https://gist.githubusercontent.com/wcandillon/a3af2aa201614091b8b2c0a6ffe97034/raw/ba9bb14ae595755556aef912956b7531a6bccadc/tsconfig.json
yarn add @types/react @types/react-native --dev
mv App.js App.tsx
tsc
```

Project compiles great. However if I import a legacy API, via `import {} from "expo";` (for instance: `import {AppLoading} from "expo";`, I'm getting the following compile errors:

```
Module '"../../../../../../../../../Users/wcandillon/can-it-be-done-in-react-native/season2/spotify-header/node_modules/expo/build/deprecated"' has no exported member 'WebView'.

Module '"../../../../../../../../../Users/wcandillon/can-it-be-done-in-react-native/season2/spotify-header/node_modules/expo/build/deprecated"' has no exported member 'WebBrowser'.
```

And so on.

**Comment by ide** [comment]
If you set the option skipLibCheck (or something similar) does the error go away? Also, we have an easy way to rewrite the imports: try npx expo-codemod sdk33-imports “**/*”

**Comment by wcandillon** [comment]
@ide You rock, thank you 💪🏻

**Comment by SimenB** [comment]
Should be fixed, no? `deprecated.d.ts` is empty: https://runpkg.com/?expo@33.0.1/build/deprecated.d.ts

**Comment by wcandillon** [comment]
@SimenB yes it should probably still be fixed. `deprecated.d.ts` should export an any no?

**Comment by ide** [comment]
It's empty because the file is full of ts-ignore directives so there is no .d.ts file to generate. It would need to be written by hand, and would be overwritten by the build step. This shouldn't stop your app from running, because babel-preset-typescript doesn't perform type checking and there is a codemod to rewrite the imports for you.

**Comment by SimenB** [comment]
Doesn't stop it from running no, but it stops it from building when we typecheck :) the codemod works though, so maybe fine? Should remove the re-export from Expo.d.ts regardless as it won't build even if we don't use those exports

**Comment by wcandillon** [comment]
I've been using `skipLibCheck` instead of the codemod, is there a downside of `skipLibCheck` I should be aware of?

**Comment by SimenB** [comment]
It's less safe as it'll skip checking libraries. Of course, this might not affect you (and should not, if you assume all libraries are correct), but there's a reason it's an option that defaults to false

**Comment by wcandillon** [comment]
@SimenB thks!

**Comment by ide** [comment]
Hi - just wanted to follow up on `skipLibCheck`. Independent from the `deprecated.ts` issue, `@types/react-native` defines several types that conflict with TypeScript's built-in `dom` types and `@types/node`. The `dom` types in particular present an issue with web projects -- including Expo Web -- because we need both `dom` and `@types/react-native`. This isn't something that will likely get resolved in the short term and is separate from Expo.

Additionally, unrelated to Expo or React Native, sometimes there will be interactions between libraries that cause issues. For example, a library (ex: `react-some-component`) might import another (ex: `react`) as a peer dependency, and a minor or patch update to the peer dependency's types (ex: `@types/react`) or changes to TypeScript (ex: stricter JSX rules) end up breaking the library's type checks. Flow had/has this issue and in my experience it takes away much more time & attention than it gives back. TS fortunately has `skipLibChecks` to address this.

So for practical reasons -- some related to Expo and some not -- I'd recommend using `skipLibChecks` in June 2019 and it also will be part of our new TS starter template.

**Comment by wcandillon** [comment]
Thank you @ide. I appreciate that you took the time to make this clarification.
