### ISSUE TITLE
Phone <> Computer connection issues for Windows users

### ISSUE THREAD

**Issue by lnsane** [expo/expo#438]
I just started using expo
When entering the project there is a project url is the case
Exp: //df-zkx.lnsane.my-new-projectllll.exp.direct: 80
But I found that every time debugging is very slow
I saw the computer under the cpu and memory are no problem, with the network is 100M, the phone is iphone 6s
So I went to see the document, the original Host - Tunnel this will have a lot of network delay
I changed to Host --- Lan but I found that I was not on the project
So I clicked on Restart and then I clicked on the result of the share or the connection failed
I am very upset, I see expo app has a button to enter the url so I entered
Exp: //192.168.56.1: 19000
The result is the connection failure, which is why, so I replaced the Host - localhost is also a connection failure
Only in the Host - Tunnel mode only online success, I read the official website of the document, and no detailed description
Just that in the same network can be, I use the same network but not, why?

**Comment by lnsane** [comment]
I did a try I put my cell phone open wifi and then use my computer to connect the phone wifi results still fail

1. already in the same network
2. Turn off the computer firewall
3.wifi does not have password restrictions
4. The phone does not use any security software
5. Repeat the 10-side XDE prompt steps


So I am now very puzzled to ask, how can we use LAN and localhost

**Comment by jimmylee** [comment]
Whoa I feel so bad you're running into this issue,

This issue has historically been a tough one for our windows users (I'm making a guess you're on windows, you may be on another operating system).

I'd like to share with you some issues where others have found solutions to debugging this problem:

Solution *Assigning interface matric (priority) for your Wifi Adapater*
https://github.com/react-community/create-react-native-app/issues/60

> 1. first I connected my laptop through my mobile hotspot.
2. Then Control Panel > (search for 'network connections') > network connections
3. Right-Click on 'Wifi' > select 'Properties' > 'Internet Protocol Version 4 (TCP/IPv4)' [don't uncheck the mark]
4. Go to "Properties" > "Advanced..." > (Uncheck 'Automatic Metric') > Type in the text-box below that (Interface Metric) : 10.
5. Click OK and OK and OK :)
6. Then do the same for the other "Virtual Box-xxxxx" networks. But instead put 20 in the Interface Metric text-box.
7. Click OK, OK and OK.
8. Try restarting your app on Expo. It must work now!

Solution *Setting REACT_NATIVE_PACKAGER_HOSTNAME* as a windows env
https://github.com/react-community/create-react-native-app/issues/81

> REACT_NATIVE_PACKAGER_HOSTNAME="192.168.1.2"
seems to work for some people.

Solution *Behind a NAT, add port redirects for firewall*
>I had the same troubles when I was behind a nat, what I did (and worked) was to add port redirects to the firewall for the ports 19000 and 19001.

Solution *Disable virtualbox since Expo is taking the IP address of virtualbox*
> Solution for windows 10.
Go to cmd and write ipconfig.
Look what is the first Ethernet adapter.
It should be Ethernet adapter Ethernet.
If it is not and it is something like Ethernet adapter Virtualbox...
Then this is the problem voalaa. Expo is taking the ip adress of the virtualbox.
So go to "Network connections" right click on the adapter you want disable and change the status to disable.
Connect you computer to ethernet and you phone to the same wifi network.
Restart Expo, then the default url should be changed.
Select host->lan, start the app and then -> run on android.
That's it.

_________

I hope one of these 4 solutions will help you. If you can, provide me more information about your node, npm, OS and maybe we can try some other things! Sorry you're encountering this bug.

**Comment by lnsane** [comment]
@jimmylee thank you I can now happily write ios on the iPhone

**Comment by MikeA1** [comment]
> what I did (and worked) was to add port redirects to the firewall for the ports 19000 and 19001.

I had a problem connecting my iPhone to Windows 10. I resolved it by punching a hole in the Windows Firewall: I opened up _Windows Defender Firewall with Advanced Security_ and created a new _Inbound Rule_ for ports _19000-19001_ using [these instructions](https://technet.microsoft.com/en-us/library/cc749323.aspx).

![image](https://user-images.githubusercontent.com/9297054/34141480-c09668fc-e43e-11e7-9cbf-380a8a1139d6.png)

**Comment by sawangupta** [comment]
Still having this issue in OSX Sierra. Any suggestions ?

**Comment by AnthonyLamot** [comment]
I'm also experiencing something similar:
- Running node express on localhost:9001
- When I run expo on iOS simulator I'm able to fetch data from the server (using `axios.get`)
- When I run expo on AVD I'm not able to fetch the data - not via tunnel, localhost, or LAN?

**Comment by alanlanglois** [comment]
Same problem on detached project and windows10. 
I had it working on emulator doing the hotspot trick but trying to have debug on a real device broke the good vibe... 
The only way I get something is install the app via android studio, running the packager via the expo client, and clicking on Device > Open on Android, but still, it's not pointing the right place, my guess is that it's serving the production version in the App Installed. 
This is very frustrating, I can access 19000 et 19001 (with feedback on the log on my console) in the emulator's browser, but for some reason, the app is trying on port 80 and I can't change it, or at least didn't find a way to change/force it. 
![image](https://user-images.githubusercontent.com/712986/37063744-bd41e62e-219a-11e8-8eec-a00fe6e74b8b.png)

Please help, I've spend more than 8 hours diggin' around with no luck... :)

**Comment by jimmylee** [comment]
@alanlanglois hey! I'm so sorry you're running into this issue! I hope I can help you out since my previous advice seemed to help out other detached users.

I know you are:

- Running in a windows environment and simulating using an android simulator.

Here are some ideas I have that you can try, if these don't work I'd ask if you could share any more details about your setup.

**Warning: Any changes in node_modules folders will be blown away when you update your packages.**

# Idea no. 1
A user has reported success after doing these steps, they were on a windows machine and simulating using android simulator. Which seems like something you are doing too.

1. Change the port of `\node_modules\react-native\local-cli\server\server.js` from the default

> process.env.RCT_METRO_PORT || 8081

to 

> default: process.env.RCT_METRO_PORT || PORT_OF_YOUR_CHOICE

2. Run the command `react-native run-android --port PORT_OF_YOUR_CHOICE`.
3. In android studio simulator, press `ctrl + m`, and go for `Dev Setting`, then select `Debug server port & host for device`, and set `localhost:PORT_OF_YOUR_CHOICE`.
4. Open developer console in a browser using: `http://localhost:PORT_OF_YOUR_CHOICE/debugger-ui`.

# Idea no. 2
Another user made a suggestion for how to get around a firewall. Here are the steps I've taken from them:

```
open run dialog
-type wf.msc
-click on inbound rules
-click new rule on right hand side
-select port from pop up menu and click next
-select tcp port and specific local ports and enter the port number like 8081(default) 
-allow the connection
-select all in profile section
-give some appropriate name and description
-click finish

2. you have to make your pc accessible to outside, for doing this follow the following steps:
-open network and sharing centre from control panel
-change adapter settings
-select your wifi network
-right click, properties
-click on sharing tab
-check all the checkboxes

You are good to go, now try running react-native run-android.
```

# Idea no. 3

I found this medium post for you: https://medium.com/error-healer/react-native-could-not-connect-to-development-server-2b39c7f15ddc. The issue feels related to some of the technology that bundle for you.

## Hope that helps

Let us know if none of this works and I'll keep trying to find a solution for you. I'm really sorry you are experiencing this @alanlanglois

**Comment by SirPhemmiey** [comment]
Had the same issue. Re-installing the Expo app on my device, and restarting (clear cache) the packager did it. Relieved!

**Comment by moahammadalt** [comment]
I tried all the solutions above but xde even exp start --lan still connecting to a wrong ip address "exp://192.168.42.6:19000" which i don't have it at all
i set react native packager to this:

> setx REACT_NATIVE_PACKAGER_HOSTNAME 192.168.42.124 /M

`C:\Users\XWorker_02>ipconfig
Windows IP Configuration

Ethernet adapter Ethernet 2:
   Connection-specific DNS Suffix  . : localdomain
   Link-local IPv6 Address . . . . . : fe80::119e:d39:fbfb:d84e%12
   IPv4 Address. . . . . . . . . . . : 192.168.42.124
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.42.1

Wireless LAN adapter Wi-Fi:
   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Wireless LAN adapter Yerel Ağ Bağlantısı* 10:
   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Bluetooth Ağ Bağlantısı:
   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Tunnel adapter Yerel Ağ Bağlantısı* 11:
   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : 2001:0:9d38:6abd:1070:68b2:e06e:5a33
   Link-local IPv6 Address . . . . . : fe80::1070:68b2:e06e:5a33%10
   Default Gateway . . . . . . . . . : ::`

i started to lose my hope so please any help!!

**Comment by anp** [comment]
@moahammadalt are you also starting XDE from the command line? GUI apps don't have access to your normal environment variables unless they're started from a terminal that exposes those variables. Since you're on Windows, you could use the GUI editor for environment variables which I *think* makes them accessible by XDE as well.

**Comment by Laurensdc** [comment]
Been having a lot of issues with this. Finally it works. THANKS @jimmylee

**Comment by rolznz** [comment]
I'm solely working in public networks such as cafes/hotels etc and for me the tunnel option doesn't work at all (always falls back to LAN). Other users have mentioned this is slow anyway.

I found two solutions using Windows 10:

**Solution 1: Hotspot from phone** (Downside: You have to run on mobile data)

1. Turn on mobile hotspot on your phone.
2. On your PC, connect to the mobile hotspot.
3. On windows firewall, go to advanced settings and add an inbound rule for ports 19000 and 19001.
4. Start the expo development server / create react native app on your pc.
5. On mobile, test by using http://<your-pc-ipv4-address>:1900 (the app should print your IP, or use ipconfig to find it)
6. If that works, you should be ok to run exp://<your-pc-ipv4-address> (the app should print it, or use ipconfig)

Debugging:
1. use ipconfig on your PC and find your gateway address. Ensure the phone can ping that gateway address. (Download a ping app from the app store)
2. ensure you can ping the IPv4 address - will only work once the firewall rule has been setup as above.

**Solution 2: Hotspot from PC.**

I couldn't ping the hotspot ipv4 address from my phone which delayed me from finding this solution. 

1. Connect to a WIFI network on your PC. Also enable the hotspot option using the following guide: https://support.microsoft.com/en-us/help/4027762/windows-use-your-pc-as-a-mobile-hotspot
2. On windows firewall, go to advanced settings and add an inbound rule for ports 19000 and 19001.
3. open cmd and type ipconfig. Get the ip address from "Wireless LAN adapter Wi-Fi".
4. On your phone, connect to the hotspot you created.
5. Start the expo development server / create react native app on your pc.
6. In safari, test the connection with http://<your-pc-ipv4-address>:19000
7. If all is fine, change it to exp://<your-pc-ipv4-address>:19000.

**Comment by nniclas** [comment]
I would like to share my findings regarding connectivity and firewall issues. 
As recommended by @MikeA1, adding ports 19000-19001 to the firewall was not enough for me.

I found out that an inbound rule for node "Node.js: Server-side JavaScript" had to be disabled in addition.

**Comment by jimmylee** [comment]
@rolznz thanks for posting your solution. I wish this was easier for everyone. I hope more people post their solutions and we can find out more quirks on our operating systems.

**Comment by atha-github** [comment]
I am using tp-link router for wifi. My phone and laptop both are connected with same wifi but unable to load expo app in LAN or Tunnel. Expo showing "Something Went Wrong", "Could not load exp://.....","Response time out". But when I turn on mobile hotspot and connect to my laptop it is working fine. Anyone can help me?

**Comment by aleksanderkaminski** [comment]
☝️  I had the same problem today, but disabling `VirtualBox Host-Only Network #2` in my internet connections that @jimmylee suggested and restarting expo worked.

What didn't work:
- Adding inbound rules
- Turning off the windows defender
