### ISSUE TITLE
How can I write a new package to extend expo and avoid ejection?

### ISSUE THREAD

**Issue by wbrickner** [expo/expo#4400]
I'd like to know what steps are involved in creating an expo package to extend the Expo API.

Specifically, I'd like to incorporate/repackage the functionality of [react-native-zeroconf](https://github.com/balthazar/react-native-zeroconf), so that I can write Expo apps which can leverage ZeroConf / Bonjour functionality.  I saw this wasn't a highly-requested feature on the feature tracker, so I'm wondering how I can do this myself, giving back to the community and improving Expo.

I have rudimentary experience with real native development, and the package has all of the functionality already, but even so I may be in over my head and not realize the complexity involved.

My real question is, are there any resources you can point me to which will describe how to contribute to the Expo API / packages (I assume they're the same thing), and how these are supposed to be structured?  Does Expo accept pull requests which incorporate new native functionality like what I've described?

If not, is there any way to improve the relevance of this feature?  I think the attention it's received is not representative of the enormous value this API would add to Expo.  

I depend on the existence of this API for a few commercial projects which are stalled until it's supported, so I would also be willing to fund it's incorporation into Expo (if I lack the expertise to do it myself).

Thank you for reading, I hope the content of this post was appropriate to open as an issue.

**Comment by ide** [comment]
We choose which packages go into the Expo client from a few criteria including how general the package is (ex: almost every app needs to display text, while few apps need VoIP capabilities), the level of permissions needed (ex: playing video requires no permission, while background location is much more sensitive), and the maintenance cost of the package (preference for stable, multi-platform APIs rather than company-proprietary libraries/services).

Zeroconf fits somewhere in the middle but is not near the top of the list so I don't think it would be included in the managed workflow anytime soon. The maintenance cost of each module is high -- writing a module is easy, keeping it working is hard -- and beyond a few $k for example especially when you consider opportunity cost.

> Does Expo accept pull requests which incorporate new native functionality like what I've described?

It really depends on what the module is. If it is low-risk (ex: no new permissions) and simple to maintain, and widely applicable, then it is a better candidate for the managed workflow, in which case a PR looks like high-quality package added to `expo-xxxxx` under `packages`. In general, maintaining software is much more costly than writing software, so we need to be protective of the health of the project.
