### ISSUE TITLE
expo-yarn-workspaces: Unable to resolve "expo-keep-awake" from "__generated__/AppEntry.js"

### ISSUE THREAD

**Issue by koredefashokun** [expo/expo#4427]
### Environment

Expo CLI 2.18.2 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.16.0 - ~/.npm-global/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.6 => 32.0.6 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1

Targets: iOS & Android

### Steps to Reproduce

Create an expo project in a yarn workspaces environment, install `expo-yarn-workspaces` and follow the setup instructions. Try starting the app.

### Expected Behavior

I expected the app to start and work fine in the yarn workspaces environment.

### Actual Behavior

The app does not run, and outputs this error: Unable to resolve "expo-keep-awake" from "__generated__/AppEntry.js"

### Reproducible Demo

[Public Repo](https://github.com/overthq/Auxilium/tree/feat/notifications-server)

**Comment by tsapeta** [comment]
Hey @koredefashokun,
Could you try to use `expo-yarn-workspaces@1.1.0`, delete `__generated__` folder and start it again? I suppose you use the latest one (1.2.0) which should work only with `expo@33.0.0` and newer. 
In version 1.1.0 we import KeepAwake module directly from `expo` package because it was included in that package in SDK32, but it was extracted to `expo-keep-awake` unimodule in SDK33.

**Comment by koredefashokun** [comment]
Thanks @tsapeta for your help. Can't wait for SDK 33, though ;)
