### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#4429]
We have many compiler warnings in our projects. Fixing the ones that are related to our code will:
- improve our code’s correctness
- reduce noise
- encourage us to keep our warnings to a minimum in the future

It mostly refers to Xcode warnings as they are more annoying, but it would also be nice to do something with Android Studio warnings.

**Comment by ide** [comment]
A few things I wanted to add:

- Since this is a very broad issue, it probably makes sense for several people to work on this. If you decide to work on something, tell the others so that we don't overlap too much.
- Some warnings may be in code that we don't maintain, in which case suppressing warnings for those libraries is more practical (especially for Obj-C / Java dependencies).
- For the nullability warnings in iOS, take your time and be careful to make sure we get the types right.
