### ISSUE TITLE
After upgrading to SDK33, it still shows packages warnings (from npm packages)

### ISSUE THREAD

**Issue by xrofa** [expo/expo#4444]
### Environment

Expo CLI 2.19.1 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 2.2 AI-145.3537739
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.2 => 4.1.18
      expo: ^33.0.0 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.0.9 => 3.8.1
    npmGlobalPackages:
      expo-cli: 2.19.1

Target: iOS

### Steps to Reproduce

After upgrading Expo through [the following link](https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/) and using the codemod provided with the transform `sdk33-imports`, it still shows the following warning when running the simulator (even though I'm not using those packages):
```
1. Add correct versions of these packages to your project using:

   expo install expo-blur expo-file-system

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { BlurView } from 'expo' -> import { BlurView } from 'expo-blur'
 - import { FileSystem } from 'expo' -> import * as FileSystem from 'expo-file-system'
```

### Expected Behavior

It shouldn't show the warnings.

### Actual Behavior
It shows the warnings

**Comment by rxhivzero** [comment]
I'm use react-native-expo-image-cache the same shows warnings.
I fork or change it code.

**Comment by ru88s** [comment]
I also have the same bug.

**Comment by changLiuUNSW** [comment]
+1

**Comment by brettdh** [comment]
Noticed this as well, sometimes with third-party code - which was hard to discover. Though having the warning is good, it would be even more helpful if it include a file path and line number.

**Comment by ide** [comment]
@fson - do you think we could capture some information about where the legacy imports are, and perhaps print the warnings different when they are under node_modules?

The issue here seems to be that there are npm dependencies that haven't been updated yet. So, even if a developer updates their own imports and runs `expo install`, they will still get warnings from their dependencies.

**Comment by fson** [comment]
These warnings are generated at runtime and I think it's not feasible to detect which module imported the deprecated module.

However, one way to do this would be static analysis. I think you could run the `sdk33-imports` transform on the `node_modules` folder with `jscodeshift` in verbose mode (`--verbose=2`) to reveal which modules still have these imports. (I expect most of them have been fixed by now.)
