### ISSUE TITLE
[docs] Need some clarification about calling super method when override AppDelegate

### ISSUE THREAD

**Issue by changLiuUNSW** [expo/expo#4506]
In [document](https://docs.expo.io/versions/v33.0.0/expokit/expokit/#upgrading-expokit) it says: 

```
If you override any AppDelegate methods to add custom behavior, 
you'll need to either refactor your AppDelegate to subclass EXStandaloneAppDelegate and call super methods when necessary, 
or start with the new template files above and add your custom logic again (be sure to keep the calls to super methods).
```
We need some clarification when override ```AppDelegate``` methods :
1. Which ```AppDelegate``` methods need to call ```super``` method
2. The order when call ```super``` method eg: at beginning or at the end
3. Why need to call ```super``` method

**Comment by expjess** [comment]
Hey @changLiuUNSW - sorry we haven't addressed this specifically in the ExpoKit docs. We realized we needed a better, end-to-end experience for customizing Expo-made apps with native code, and have addressed this with the [Bare workflow](https://docs.expo.io/introduction/managed-vs-bare/).

[ExpoKit is now deprecated](https://blog.expo.io/time-to-start-using-expos-bare-workflow-expokit-now-deprecated-d6052890c18b), and we released the final ExpoKit version with SDK38 last month. (After SDK 38, your ExpoKit apps in the App Store and Play Store will continue to run indefinitely, but you’ll need to migrate to the Bare or Managed workflows in order to get bugfixes and new features in Expo modules.)
