### ISSUE TITLE
Upgrade to CocoaPods 1.7

### ISSUE THREAD

**Issue by ide** [expo/expo#4522]
Blog post: http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

The most significant feature for us is multiple xcodeproj files, which speeds up Xcode performance. Additionally, "incremental installation" skips over xcodeproj files that don't need to change, making `pod install` faster.

**Comment by ide** [comment]
Re-opening this so that we can try out the opt-in feature of multiple xcodeproj files and incremental installation. If we try those and they don't work, that's fine, but let's test it.

**Comment by sjchmiela** [comment]
I already tried it, turned out `FBSDK` pods are incompatible with multiple projects configuration as of yet (with this option enabled all pods must have module-style imports and `FBSDK` uses `#import "file.h"`). Excluding `expo-facebook` from the project resolved the issue (but we don’t want to do it, so 🤷‍♂️).

**Comment by ide** [comment]
OK, thanks for trying it and sharing your findings here. I imagine that FBSDK will make a change once enough people ask for it and enough time passes.
