### ISSUE TITLE
ExpoAppAuth.Get Auth: Missing experienceUrl

### ISSUE THREAD

**Issue by sabativi** [expo/expo#4544]
### Environment

I created a standalone app, installed unimodules and wanted to use AppAuth

### Steps to Reproduce

simply run `react-native run-android` inside the demo project

### Expected Behavior

Can connect with google signin

### Actual Behavior

```
Error: ExpoAppAuth.Get Auth: Missing experienceUrl in the experience Constants
```

When I launch `AppAuth.authAsync(config);`

### Reproducible Demo

Here is a github : https://github.com/sabativi/ReproExpoAppAuth
Note that the first problem I had was due to https://github.com/expo/expo/issues/4518, see the second commit diff : https://github.com/sabativi/ReproExpoAppAuth/commit/93f78330d10a627b564b0c1505cfa68976f0e0a4

I have no idea what is experienceUrl and how to set it

Thanks

**Comment by BlackCod3** [comment]
@sabativi did you manage to get away with it ? 
I'm facing the same issue

**Comment by sabativi** [comment]
No I did not

**Comment by archieherbias** [comment]
Currently facing it as well on Android. It's fine in iOS.

**Comment by ezechielk** [comment]
I have the same issue, using expo-google-app-auth. No problem on iOS, only on Android. Did someone found out a way out ?

**Comment by artalat** [comment]
any update on this?

**Comment by gamertense** [comment]
I'm also currently facing this bug on Android. I found this [comment](https://github.com/expo/expo/issues/5615#issuecomment-541995626) but didn't dare to give it a try.
Any better solution pointed or some guarantee before I switch to use native package would be appreciated.

**Comment by JofBigHealth** [comment]
I think @alexyangjie's proposal in that issue is legit. I've not spent any time with expo internals, so take this as wild speculation, but what I do know is that running the app outside of expo (e.g. in our case we've rolled our own RN app and imported expo and unimodules) that `constantsService.getAppOwnership()` is `guest` (as explained here: [Constants.md](https://github.com/expo/expo/blob/0eaf836e49a233e31907f5b5b41b5622208a558b/docs/pages/versions/v34.0.0/sdk/constants.md#constantsappownership)). The first part of that `if` statement should only be executed for projects launched within expo. Therefore changing the code to `if ("expo"...` is correct I think.

What I'm not sure about - since I've not had time to get it fully working yet - is whether or not this creates issues with redirecting auth back to your app. I.e. it's not clear to me from reading the code briefly that the direct url isn't baked in from extracting your app's identifier. I'll report back if I get it fully working.

**Comment by todorone** [comment]
@cruzach @EvanBacon @ide @sjchmiela  This is an issue for almost a year, `expo-app-auth` module just does not work on bare workflow on Android, the reason is check that is pointed [here](https://github.com/expo/expo/issues/5615#issuecomment-541995626), that is not compatible with bare workflow. Is there any chance this issue will be fixed any time soon? Thanks for your dedication.

**Comment by cruzach** [comment]
Hey @todorone, we're actually looking into this now, and hopefully we have a fix for it soon. We have two open issues for this, so I'm going to close this one in favor of https://github.com/expo/expo/issues/5615

Btw- we prefer if you refrain from @-mentioning several people in threads, especially if they're not already participating in the thread

**Comment by brambang** [comment]
is there any solution fot this issue?
My apps upgrade to Expo SDK 37 then eject to bare, now my AppAuth.authAsync not working
`Error: ExpoAppAuth.Get Auth: Missing experienceUrl in the experience Constants`

**Comment by gamertense** [comment]
@brambang Since you have "ejected" from Expo, I suggest you to try this package that I've been using for a while with no problem:
https://github.com/FormidableLabs/react-native-app-auth

**Comment by cruzach** [comment]
from - https://github.com/expo/expo/issues/5615#issuecomment-624984235

> I recommend using the new expo-auth-session API which has first class support for bare-workflow https://docs.expo.io/versions/latest/sdk/auth-session/
I will be deprecating expo-app-auth in favor of expo-auth-session in time.

**Comment by brambang** [comment]
> @brambang Since you have "ejected" from Expo, I suggest you to try this package that I've been using for a while with no problem:
> https://github.com/FormidableLabs/react-native-app-auth

what is different?
expo-app-auth used react-native-app-auth right?

i would try react-native-app-auth as you suggest.

**Comment by brambang** [comment]
> @brambang Since you have "ejected" from Expo, I suggest you to try this package that I've been using for a while with no problem:
> https://github.com/FormidableLabs/react-native-app-auth

great..
react-native-app-auth working just fine with my setup from expo-app-auth, simple and easy to work with
Thanks..
