### ISSUE TITLE
how can i know push notification available token in backend?

### ISSUE THREAD

**Issue by yoojeen126** [expo/expo#4558]
i had save my push token in my db when running app.
but reinstall app push token added different token. 
the before token pushing its not worked, new token is work fine.
no problem with app running, but this make more no available data.
how i know is not available token ? 
the best way is have unique id like device id? but expo not supportted.
please tell me how can i solve it.

**Comment by cruzach** [comment]
Since a unique device ID that persists across installations isn't something Expo supports, this isn't a bug and I'm going to close the issue (questions like this are better suited for [Forums](https://forums.expo.io/))

That being said- when you push notifications to "dead" tokens, it will return an error saying so- AKA`DeviceNotRegistered`. When you get a response like that, you know to stop sending push notifications to that device

**Comment by yoojeen126** [comment]
@cruzach  thanks. :)
 i checked its not return 'DeviceNotRegistered', just return status ok for before token.
 wish the issue will be solve.

**Comment by cruzach** [comment]
We have a [guide to Push Notifications](https://docs.expo.io/versions/latest/guides/push-notifications/#push-tickets) that explains it pretty well, suffice to say the "ok" isn't enough. You need to check receipt
