### ISSUE TITLE
Push Notifications Not Being Shown on iOS

### ISSUE THREAD

**Issue by Enijar** [expo/expo#4594]
## 🐛 Bug Report

Using the [official Snack demo for push notifications](https://snack.expo.io/@documentation/pushnotifications) on my iPhone 7 device, running iOS 11, I am unable to see a push notification, after tapping "Press to Send Notification".

I have completely removed my expo and reinstalled it and still no luck.

### Environment

N/A

N/A

### Steps to Reproduce

1. Open [https://snack.expo.io/@documentation/pushnotifications](https://snack.expo.io/@documentation/pushnotifications)
2. Open Expo app on iPhone
3. Tap "Press to Send Notification"

### Expected Behavior

1. Open [https://snack.expo.io/@documentation/pushnotifications](https://snack.expo.io/@documentation/pushnotifications)
2. Open Expo app on iPhone
3. Tap "Press to Send Notification"
4. See a push notification card on my phone's OS

### Actual Behavior

1. Open [https://snack.expo.io/@documentation/pushnotifications](https://snack.expo.io/@documentation/pushnotifications)
2. Open Expo app on iPhone
3. Tap "Press to Send Notification"
4. Nothing happens

### Reproducible Demo

[https://snack.expo.io/@documentation/pushnotifications](https://snack.expo.io/@documentation/pushnotifications)

**Comment by AdamJNavarro** [comment]
Hey @Enijar,

This is not a bug, but rather the expected behavior. On iOS, push notifications will not be presented while the app is foregrounded so you will have to handle them with some form of in-app system.
 
https://docs.expo.io/versions/v33.0.0/guides/push-notifications/#3-handle-receiving-andor-selecting-the-notification

Cheers,
Adam
