### ISSUE TITLE
Can I translate your document in Chinese and post it on my github?

### ISSUE THREAD

**Issue by AieraFlyyyy** [expo/expo#4641]
Hi Expo! 
I'm a Chinese student.
I want to know that if I can translate your document in Chinese and post it on my github?
Because there is few Chinese document to introduce Expo.

**Comment by cruzach** [comment]
Hi @AieraFlyyyy! Thanks for checking with us to make sure.

That's absolutely fine with us, just make sure you're providing references to the original [docs](https://docs.expo.io/versions/latest/) (and our [blog](https://blog.expo.io/) too!) for the most updated information on Expo tools, so we can take care of readers even if they are coming across your translations a year from now. Since we update our docs quite often (with each SDK release), it's important readers are getting the most up-to-date information 👍
