### ISSUE TITLE
Clarify in documentation that redbox shows error message for transpiled code and how you should read redbox

### ISSUE THREAD

**Issue by amandeepmittal** [expo/expo#4672]
I am not sure the error message shown below is valid or not. I mean the number in the statement, `this2.` or is this issue related to React Native API. Please do not mind me if the issue is not valid. That is why I put this as a question.

![Screenshot 2019-06-20 at 10 02 51 PM](https://user-images.githubusercontent.com/10234615/59865708-608a2b00-93a7-11e9-8afe-cd81944ca745.png)

**Comment by brentvatne** [comment]
when you run a react-native app it is transformed through babel and your code won't look exactly the same. the error that is reported is exactly as it appears in the transformed/transpiled source.

under that error you'll see the stack that tells you where the error comes from along with the line number, eg: in the following screenshot I know that this error came from App.js on line 11 and column (character) 19.

![Screen Shot 2019-06-20 at 13 04 28](https://user-images.githubusercontent.com/90494/59877967-0a43ca80-935c-11e9-9966-0ad163b59a02.png)

it'd be nice to improve this upstream so that we see both the transpiled error and the original line in the source code directly inside the redbox. for now we should perhaps document this

**Comment by AdamJNavarro** [comment]
https://github.com/expo/expo/commit/0733b8b233c768276cb8984998bfd1736ecac60b
