### ISSUE TITLE
[expo-av] Bare React Native app Error:No known instance method for selector 'executeUIBlock:forView:ofClass:'

### ISSUE THREAD

**Issue by Pines-Cheng** [expo/expo#4722]
### Environment

Bare React Native app

```
  Expo CLI 2.5.0 environment info:
    System:
      OS: macOS High Sierra 10.13.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.8.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1 
      react-native: 0.55.4 => 0.55.4 
    npmGlobalPackages:
      expo-cli: 2.5.0
```

### Steps to Reproduce

1. install expo-av@5.0.2 package
2. add `pod 'EXAV', path: '../node_modules/expo-av/ios'` to Podfile
3. run `pod install`
4. build project use xcode

### Expected Behavior

run app normal

### Actual Behavior

throw Error:
```shell
/Users/chengshuai/Work/taro-native-shell/node_modules/expo-av/ios/EXAV/Video/EXVideoManager.m:80:14: No known instance method for selector 'executeUIBlock:forView:ofClass:'
```
![image](https://user-images.githubusercontent.com/9441951/60146539-8e82cb80-97fc-11e9-8277-bd2e3bf6a233.png)

I have tried expo-av@4.0.0 , expo-av@5.0.0 , there are also throw different errors ,  develop work is stagnant.

**Comment by cruzach** [comment]
Hi @Pines-Cheng 

I just tested this in a bare `expo init` project (except for your step 2, as that's not part of the [installation instructions](https://github.com/expo/expo/tree/master/packages/expo-av)-- although you should make sure that `unimodules` were installed correctly, since that's done for you automatically in bare `expo init` projects) and it worked just fine. I suggest upgrading `expo-cli`, and also Xcode (version 10 was released in September of last year).

**Comment by Pines-Cheng** [comment]
I  have  update Xcode to 10.1 , but the issue is still exist .

**Comment by Pines-Cheng** [comment]
It fine after I update `react-native-unimodules` from 0.2.0. to 0.4.1 ， and should remove the `andExperienceId:… ` base on https://github.com/expo/expo/issues/4195
