### ISSUE TITLE
expo web doesn't have proper babel presets

### ISSUE THREAD

**Issue by lifeiscontent** [expo/expo#4751]
in react native this preset is enabled.

https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

in expo web, these transforms aren't applied and break libraries that use them.

**Comment by EvanBacon** [comment]
it's right here: https://github.com/expo/expo/blob/bf3e8710343c1c03ff7ef792a71f8524c6d7a067/packages/babel-preset-expo/index.js#L41

**Comment by brentvatne** [comment]
@lifeiscontent - can you point us to which library you were having an issue with?

**Comment by lifeiscontent** [comment]
@brentvatne it was native base that was throwing errors

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EvanBacon** [comment]
Native base doesn't follow the correct library name format (`react-native-*`) so you need to manually add the package name to the list of files that babel compiles. [**expo-web-native-base-demo**](https://github.com/EvanBacon/expo-web-native-base-demo)

Check out this: [native-base config](https://github.com/EvanBacon/expo-web-native-base-demo/blob/f4dd16b79acba73da5354565ad512c4ebce615d0/app.json#L23-L29)

**Comment by lifeiscontent** [comment]
@EvanBacon you rock, thanks for the explanation and demo project! 🎉

**Comment by calumjames** [comment]
@EvanBacon, I'm seeing this problem with Expo Web not using the **@babel/plugin-proposal-class-properties** on my own code (rather than code from a library). I'm using class properties in my code because this code was written before React Hooks was a thing. I'd just like to get it running with Expo Web as a proof-of-concept.

What's the best way to get Expo Web to use that Babel transform on my code? It works fine with Expo when running as an iOS app (`expo start`).

I've tried including my own files in the way you included native-base in that example project but to no avail. The [app.json documentation](https://docs.expo.io/versions/latest/workflow/configuration/) doesn't suggest anything else.

Any help would be much appreciated. Thanks!

**Comment by ru88s** [comment]
I have same bug.
I'm using SDK36.
![スクリーンショット_2020-02-26_18_37_14](https://user-images.githubusercontent.com/42270511/75332073-20c8fb00-58c7-11ea-80e3-f9d0a3f5df71.png)

Not resolved after installation.
