### ISSUE TITLE
Little fixes on push notifications (client-side)

### ISSUE THREAD

**Issue by slorber** [expo/expo#476]
Let's say I emit the following toast:

```
curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '{
  "to": "ExponentPushToken[xyz]",
  "title":"hello",
  "body": "world",
}'
```

I think it would be quite convenient to include the title/body directly in the notification object of the notification listener. For example on iOS if we handle the notification in foreground, we have somehow to add a new "data.message" attribute so that we can display something to the user (like a toast). It can be convenient to pass in the callback the title/body to avoid this extra attribute.

Also, on Android, I think it would be very convenient to be able to disable the notification if it is received in foreground. Currently when the app is open and you receive a push, the notification always appear at the top and there's no way to disable that behavior. I don't know if it is possible but it would be handy so that we can more easily provide uniform cross-platform behavior for both platforms (Ie if notification is received when app is in foreground, never display a notification but always display an in-app toast)

**Comment by karsens** [comment]
Hey, did you find any solution or is there any change regarding this? I also don't want my users to receive notifications if they are currently inside the app. 
I can come up with my own solution:
1) let my own backend know when a user is using the app
2) if a user that should receive a notification is using the app currently, don't send the push notification at all.  So check for (1) before sending the push 

But it would be easier if expo provided a solution that it can be handled differently. Toasts on iOS would be cool indeed, for example.

**Comment by slorber** [comment]
Sorry, don't know, as I detached recently and added OneSignal

**Comment by ide** [comment]
@karsens: the way iOS works (Android is different), if the app is open, the OS won't show the notification at all but you can still programmatically handle it.

**Comment by ide** [comment]
To summarize the original post in this issue, there are two separate things to improve:

1. Include the top-level fields (like title and body) of the notification payload so that a notification callback in the app can access those fields (this might happen on Android but doesn't on iOS). We may want to whitelist these top-level fields (in a kernel service) so that if we send a new, sensitive field from the server, it doesn't get exposed automatically.

2. Provide an API to disable displaying notifications on Android when the app is foregrounded. (This happens automatically on iOS, because the OS handles it and in fact allows only this behavior.)

**Comment by wdinau** [comment]
@ide thanks so much for summarizing!
@sjchmiela is disabling notification foreground a priority that would possible made early in May? It is a show stopper for android user experience. I've never seen Slack, weChat, What's app... etc. have popup notification while a reader is already looking at the message.

If not, is there any hint/tips how I can handle decently with the notification so that our users won't be opening the app and getting notification while they are already looking at the chat/message?

Many thanks!

**Comment by Oele** [comment]
I'm too running into the second issue (no possibility to surpress android push notifications when app is in foreground).  

IMHO it would be better to surpress these notifications by default and leave it to the developer to programatically fire a notification when needed - that would make it consistent with what happens on iOS! But at least being able to configure the default behaviour would be a major improvement. 

I know that it's possible to listen for push notiffications and immediately dismiss the push message when it comes in and the app is in foreground, but the problem with that workaround is that the notification sound is still being played about half of the times, sometimes only partly, dependent on how fast the notification listening code is executed.. 

Is there any way to get this on the expo developers' todo list? 

Alternatively, would expo consider accepting a pull request if i would manage to solve this myself?

**Comment by EvanBacon** [comment]
@Oele lmao yes expo will consider accepting a PR. 👍 
Canny is how expo tracks features: https://expo.canny.io/feature-requests
