### ISSUE TITLE
Second gif load crashes iPhone 7s and older for SDK 31, 32, 33

### ISSUE THREAD

**Issue by bscaspar** [expo/expo#4766]
## 🐛 Bug Report
snack: https://snack.expo.io/@bcaspar/jealous-waffles
This is not reproducible in a simulator environment - need to load it through the expo app on an iPhone 7s or older.
## Behavior
The app simply crashes on the second gif load. It closes and returns to the phone home screen. Not sure if this may have something to do with the javascript timeouts but the behavior does not happen on newer phones (tested on X and XS Max) with no issue.

**Comment by bscaspar** [comment]
After a bit more testing it looks as though this is due to the size of the files required in the initial loading screen. It's hard to say above what size the error happens but significantly compressing the gif mitigated the issue.

**Comment by ide** [comment]
We currently use RN for GIF display and the current implementation is the least efficient possible. It decodes every frame of the GIF into raw 32-bit color all at once. Obviously this isn’t an intentional implementation goal. There is/was a PR to fix this so that every frame doesn’t get decoded all at once. Until then (and after TBH) I’d recommend using a video instead. Any video format and especially H.264/265 will outperform GIF.

**Comment by Simek** [comment]
Hi @bscaspar, is this issue still valid in your use-case?

I was not able to reproduce this crash using provided Snack with SDK 43, on iPhone SE (1st gen) and iPhone 12 Pro.

**Comment by bscaspar** [comment]
> Hi @bscaspar, is this issue still valid in your use-case?
> 
> I was not able to reproduce this crash using provided Snack with SDK 43, on iPhone SE (1st gen) and iPhone 12 Pro.

I can't confirm if this is still an issue for me as I am no longer using expo. Please close if you'd like.
