### ISSUE TITLE
[LocalAuthentication][iOS] Still falls back to Passcode after TouchID fails several times with `fallbackLabel` set to empty string

### ISSUE THREAD

**Issue by latusdenis** [expo/expo#4799]
### Environment

  Expo CLI 2.20.6 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.6

### Actual Behavior
If the iOS device doesn't support touchID(e.g iPhone 5) or it's disabled by default the fallback native modal with the phone password is shown. Is it possible to remove it and navigate user to the Pin Code screen.

![image](https://user-images.githubusercontent.com/34662936/60530939-9530a780-9d02-11e9-8af8-bcb26a331ab7.png)

### Expected Behavior
There's an option to remove fallback modal

**Comment by cruzach** [comment]
Hey @latusdenis,

Correct me if I'm wrong- you're asking that instead of the modal asking for the passcode being shown in the app, you want it to navigate to the passcode screen shown when unlocking the device? (as show [here](https://stackoverflow.com/questions/47201176/if-touchid-fails-forward-to-system-passcode-authentication))
If that's correct, then this is more of a feature request rather than a bug report, so I'd ask you to open a new request at our [Canny](https://expo.canny.io/feature-requests), and close this since we prefer to keep Github just for bug reports

Side note- You can take a look at how that module works by looking at the [iOS source code](https://github.com/expo/expo/blob/master/packages/expo-local-authentication/ios/EXLocalAuthentication/EXLocalAuthentication.m). I believe the current behavior stems from [LAPolicyDeviceOwnerAuthentication](https://developer.apple.com/documentation/localauthentication/lapolicy/lapolicydeviceownerauthentication?language=objc)

**Comment by latusdenis** [comment]
Hey @cruzach,
Not exactly, I’d like to navigate to my own pin code screen on the app, not the system one. Is it possible to do this?

**Comment by cruzach** [comment]
Afaik, we don't we expose a method of doing this with Expo.

 I'm not sure if it's even possible through native code changes

**Comment by cruzach** [comment]
Thanks for the in-depth explanation @AlgirdasVZ! Repro of this behavior [here](https://snack.expo.io/@charliecruzan/healthy-yogurt)

**Comment by amsimoes** [comment]
I'm having this exact issue, want to avoid device passcode input to appear, after 3 times.

And would also like for it to navigate to an authentication screen inside my app, but I think that's already possible with the value returned from the authenticate method, not sure!

Is this being worked on?

**Comment by amsimoes** [comment]
@cruzach Because I want to use my own in-app authentication in case TouchID or FaceID fails. 

Like Revolut does, for example.

**Comment by amsimoes** [comment]
@cruzach Any news on a PR that would fix this and also the fallbackLabel flexibility?

**Comment by cruzach** [comment]
The PR to allow more flexibility in what arguments are supplied has been merged to master (not released yet, that will probably come in SDK 36).

As for this particular issue, finding the root cause will definitely speed up the solution time. We are always open to a high quality PR to fix this as well 😄

**Comment by shamilovtim** [comment]
Going to chime in here. Working on an app for healthcare. For tight security it's important that if biometrics fail, only our app's regular auth pattern (typing in a password) be allowed afterwards. My hunch is that most people implementing biometrics for the security are going to be in this exact same boat. If they can't prove they're the owner of the phone through biometrics we want them to have to type in the password as usual.

**Comment by mstankov** [comment]
I'm in the same boat :) I'm currently using @xaviraol 's suggested approach as my app is a banking app, and pretty much the same case as @shamilovtim 's, requires the user to authenticate via the his password/pin, in case bio fails N times. Falling back to the OS's native PIN screen is a security issue.

**Comment by jamiesage123** [comment]
This issue is also preventing me from implementing biometrics authentication in an app I am working on. We should be able to fall back to our own authentication screen if biometrics authentication fails. We cannot use the native PIN screen as our app requires a stronger and more control PIN/password if bio was not successful.

As stated above, this would be a security issue for us if we used this feature in the app as it stands.

**Comment by xaviraol** [comment]
@jamiesage123 if you are stuck because of that, you can always use [patch-package](https://www.npmjs.com/package/patch-package) and replace [in this line](https://github.com/expo/expo/blob/b7d2b987b56d312bf247570e7af292cbd8443a16/packages/expo-local-authentication/ios/EXLocalAuthentication/EXLocalAuthentication.m#L91)  the current `LAPolicyDeviceOwnerAuthentication` with `LAPolicyDeviceOwnerAuthenticationWithBiometrics`. This is how we addressed it for now.

**Comment by jamiesage123** [comment]
@xaviraol Thanks for the workaround, really appreciate it.

Looks like we will have to approach it like this until Expo releases a fix.

Cheers.

**Comment by beaurushton** [comment]
I'm also seeing this issue.  Would be great if someone from the Expo team could take a look as it is a blocker for us as well.

**Comment by beaur** [comment]
I've created a pull request to fix this issue.

**Comment by tian-yi** [comment]
Hi all,

Thanks for all your great work to fix this.

So I wonder do I have to wait for the next SDK coming out to use this? Or Can I upgrade `expo-local-authentication` package itself somehow?

**Comment by cruzach** [comment]
Closing this since it was addressed in the above PR

@tian-yi are you in a managed expo project, or bare? You'll most likely need to wait for the next SDK release, unless we backport this fix to SDK 36 as well

**Comment by tian-yi** [comment]
Hi @cruzach , thanks for you reply. I am in a managed expo project. Any ETA on the next release? Or any issue I can subscribe with the progress made towards the next SDK?

**Comment by cruzach** [comment]
We plan to release SDK 37 by March 31st

**Comment by wesleyrafael** [comment]
any updates on this? I'm only waiting for this update to add this funcionality on my application

**Comment by CostachescuCristinel** [comment]
It seems it's fixed :)
https://docs.expo.io/versions/v37.0.0/sdk/local-authentication/#arguments

**Comment by iamrekhaverma** [comment]
Is there any way to avoid this passcode on android also? In my app, on one of my android devices, faceid is enabled but it asks for Screen Lock is asked to the User when a user tries to login with Face Recognition ID, User is not directly login by face scan even though the user has allowed the Face login for the application.

**Comment by kolaade271** [comment]
Am Having the same issue when the user clicks on the biometric process the dialog is still showing the option "USE PIN" which I don't like
