### ISSUE TITLE
More `FileSystem` root directories

### ISSUE THREAD

**Issue by nikki93** [expo/expo#481]
Add more `FileSystem` roots, for example, a non-user-visible persistent storage location as described in https://forums.expo.io/t/when-will-filesystem-add-more-directories/2113

**Comment by alexrussell** [comment]
Just to add to this issue with my own problems. As I mentioned to @brentvatne in The [Camera component Canny request](https://expo.canny.io/feature-requests/p/camera-component) (scroll to the bottom), we currently have issues with the FileSystem API and the URIs returned by the non-Expo media stuff.

(I have also added a [new Canny request](https://expo.canny.io/feature-requests/p/videopicker-or-imagepickertypevideo) to actually create the API that I feel is missing, that is related to this issue.)

In a nutshell, here is the issue: I need to provide a UI for my users to select a video (rather than an image) from their camera roll (and the equivalent in Android). There are several ways to go about making this happen:

1. Expo is missing what I need, but currently has ImagePicker for selecting images. I haven't tested it on Android but can only assume it's cross platform.
2. RN [`ImagePickerIOS`](https://facebook.github.io/react-native/docs/imagepickerios.html) (iOS only so far from ideal)
3. RN [`CameraRoll`](https://facebook.github.io/react-native/docs/cameraroll.html) using `getPhotos` and `assetType` set to `'Videos'` + roll my own UI
4. A third party solution that does the previous point for me, e.g. [`react-native-mediapicker`](https://github.com/stoffern/react-native-mediapicker)

Here are the issues (and here's where FileSystem issues come into play):

1. Doesn't exist. But if it did, it's probably be made in such a way that the videos are [copied to the cache directory like images currently are](https://github.com/expo/expo/blob/master/ios/Exponent/Versioned/Modules/Api/EXImagePicker.m#L135-L138), so it'd be perfect. Hence why I opened the [Canny request](https://expo.canny.io/feature-requests/p/videopicker-or-imagepickertypevideo) for it.
2. Is iOS only, but does use some native UI (which is great) and even copies the files into the application's own storage. Unfortunately it does not copy to the documents *or* cache storage (it uses `tmp`), and either way does not copy into the individual Expo app's own namespaced area. Specifically, the URI type I get form this are: `file:///private/var/mobile/Containers/Data/Application/[APPLICATION_UUID]/tmp/[MEDIA_UUID].MOV`
3. and 4. Aren't hugely desirable as they lose the native UI (and in the case of 3 I'd have to make my own), but also don't return usable URIs: `assets-library://asset/asset.MOV?id=[MEDIA_UUID]&ext=MOV`

So, none of the URIs returned by ImagePickerIOS or the CameraRoll API are usable by FileSystem, and therefore I'd have to eject just to implement my own native FS access (e.g. using [`react-native-fs`](https://github.com/itinance/react-native-fs)).

@brentvatne suggested I open an issue here specifically to address the fact that FileSystem doesn't have access to these areas, and then I found this issue. However I'm not sure that changing FileSystem is the best way here. Certainly I imagine allowing FileSystem access to that weird `assets-library:` scheme URI could work, but is the solution whereby us devs have to handle our own UI, which would put video selection at odds with image selection in an Expo app. The URIs returned from ImagePickerIOS on the other hand I imagine would be even worse for Expo, as the URLs are not namespaced/sandboxed, which means that, theoretically, other Expo apps (if that root was enabled in FileSystem) could have access to stuff that my app did, so I bet that's just a no-go.

**Comment by alexrussell** [comment]
@beaurushton shortly after I added my comment here I think Expo gave us the ability to pick images from the "camera roll". As such, I no longer needed to access these files directly, and instead could just use Expo's image picker, thus meaning that while these FS issues may still persist, they no longer affected me. Sorry.

**Comment by Rutulpatel7077** [comment]
@alexrussell Did you find any solution for URL like this 

```
file:///private/var/mobile/....
```

**Comment by sjchmiela** [comment]
The fix landed in SDK32 which will be available soon. 🙂

**Comment by alexrussell** [comment]
Out of interest, what has the fix in question actually fixed? This original issue suggests "adding more roots" (but, following the trail, specifically something to allow Cordova people to migrate to Expo) and my comment suggested two possible URI types that could do with being supported for media library access.

**Comment by sjchmiela** [comment]
In SDK31 and before, Expo blocked access to any directory outside the `FileSystem.documentDirectory` and `.cacheDirectory`. Since SDK32 it should be possible to access directories outside of [Expo Client/standalone app] directory (like SD card on Android or DCIM or whatever). 🙂

**Comment by sjchmiela** [comment]
Hey, @nikolakanacki! There are no new `.<something>Directories`. However, Expo now allows accessing filesystem outside of Expo Client's scope.

**Comment by robinpaulson** [comment]
@sjcmiela According to https://docs.expo.io/versions/latest/sdk/filesystem/ . the SDK can only access certain areas, namely the documentDirectory and cacheDirectory. There is no mention of other directories on that page. Could you point us to documentation please? Thanks

**Comment by robinpaulson** [comment]
@sjchmiela  Further, trying to write to a directory other than the Documents and cache directories produces this:
[Unhandled promise rejection: Error: Location '/storage/emulated/0/Download/blah.txt' isn't writable.]

**Comment by franzmoro** [comment]
> Hey, @nikolakanacki! There are no new `.<something>Directories`. However, Expo now allows accessing filesystem outside of Expo Client's scope.

@sjchmiela  How would one do this?

**Comment by robinpaulson** [comment]
@franzmoro i opened a new bug at #4848 to cover the broader question of filesystem docs
