### ISSUE TITLE
Disabling facebook call in Android app

### ISSUE THREAD

**Issue by sblondon** [expo/expo#4827]
At work, we are using expo in our mobile app (iOS and Android).

We have noticed that, on the Android app, many requests are made to graph.facebook.com when the app launches. According to Privacy International NGO (https://privacyinternational.org/report/2647/how-apps-android-share-data-facebook-report 1), it appears that it is sufficient to integrate the Facebook SDK to be tracked by Facebook. 

Wireshark screenshot of the mobile phone traffic captured when connecting on our app on an Android phone:
![f0c9d376e0eb33abffb1c4ca4bfd61fb5112e404_2_690x110](https://user-images.githubusercontent.com/1708780/60679709-ea96c100-9e88-11e9-8b37-a0aeda716938.png)

We would like to completely disable this part of expo for iOS as well as for Android app.
According to expo docs, it seems to be already possible to completely disable Facebook libraries on iOS. It seems it's not the case for Android.

Asking in the forum does not provide answers: https://forums.expo.io/t/how-to-completely-disable-facebook-libraries-for-android-apps/23854

We see two ways to fix it:
1. We could try a workaround by loading a fake Facebook SDK to override the defined functions in the real SDK.
2. Expo could have a way to not add Facebook SDK. Probably with the SDK by default for backward compatibility.

The solution 1 is probably the easiest one but it's unsure it will work and the maintenance will not be great. The solution 2 is better in the long term but does not seem to be a priority (according to https://expo.canny.io/).
Is it interesting we give a try to solution 2 or is it a waste of time?

**Comment by cruzach** [comment]
Hi @sblondon! I'm not sure about your first listed workaround, but in regards to the second- we are in the midst of providing paid services for developers with more specific needs like this. Otherwise, the bare workflow is always an option, which gives you full control over the native code (with some trade-offs, explained more fully explained [here](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/))

**Comment by MicroCheapFx** [comment]
Here in EU, privacy is not a _specific_ need. It is a need. Period.
I think you should be able to offer this feature for free for being RGPD compliant (wich should NOT be a paid option) and ethical.

**Comment by ide** [comment]
Depending on your needs, there is always the bare workflow which lets you exclude or include whichever modules you need. Including/excluding modules is very costly ($) because it takes extra time to compile different builds, so there is an actual constraint there and we need to be realistic about the services we can offer. And to reaffirm, because with the bare workflow you can compile on your own computer and Expo doesn't need to front those costs, you have much more flexibility to meet those needs.

**Comment by luizfonseca** [comment]
What’s the status on this issue? I am considering using Expo for a big project, but automatically including Facebook or any tracking is a big blocker...

**Comment by brentvatne** [comment]
see https://blog.expo.io/expo-sdk-36-is-now-available-b91897b437fe?source=collection_home---6------0----------------------- - this is disabled by default in sdk36 now

**Comment by luizfonseca** [comment]
@brentvatne thats amazing! I will definitely continue my plans then. 

I wonder if I can remove anything (track of any sort) by using the paid version, or if they have plans for it.
