### ISSUE TITLE
[docs] Reconcile info from #481 with info on https://docs.expo.io/versions/latest/sdk/filesystem/

### ISSUE THREAD

**Issue by robinpaulson** [expo/expo#4848]
According to @sjchmiela, in the comments of #481, expo now supports accessing file systems outside the cache and documents directory. Looking at the docs for filesystem, this does not appear to be the case. Also, using filesystem to access other directories does not work. Please could you clear up the differences. This may be a bug in expo rather than a docs issue, I'm not sure which to put it under. Thanks

**Comment by robinpaulson** [comment]
When I attempt to write to the filesystem, in places other than cache and documents, I get this error:
[Unhandled promise rejection: Error: Location '/storage/emulated/0/blah.txt' isn't writable.]

**Comment by sjchmiela** [comment]
Hey, sorry for the delay in response here. It turned out that since Android API level 23 you need to ask for special permissions to be able to access directories outside of your app's sandbox.

To do this, in Expo, you can `Permissions.askAsync` for `Permissions.CAMERA_ROLL`. This will trigger a permission check for `READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE`, which, if you allow, will let you access more directories.

After allowing permissions for `CAMERA_ROLL` I was able to fetch information about `file:///storage/` successfully:

```js
FileSystem.getInfoAsync('file:///storage/').then(console.log).catch(console.log);

// Object {
//   "exists": true,
//   "isDirectory": true,
//   "modificationTime": 1569428079,
//   "size": 100,
//   "uri": "file:///storage",
// }
```
