### ISSUE TITLE
Expo payment stripe stuck on promise in case of errors from stripe

### ISSUE THREAD

**Issue by gigalabs18** [expo/expo#4849]
### Environment
ExpoKit `33.0.0`
expo-payment-stripe `5.0.1`
### Steps to Reproduce

```
const params = {
  number: '4242424242424290',
  expMonth: 11,
  expYear: 17,
  cvc: '223',
  addressZip: '55555',
};
const token = await stripe.createTokenWithCardAsync(params);
```

### Expected Behavior
Should return error codes with message i.e. invalid card number

### Actual Behavior

The promise returned by `createTokenWithCardAsync` doesn't gets resolved/rejected if passed a wrong  card number in params.

**Comment by sdadrianalvarez** [comment]
I have this problem too. Please give us a solution!!

**Comment by srobledo** [comment]
Same here :(

**Comment by tonyea** [comment]
Long time to resolve an issue. I'm going to apply timeouts to these promises that don't resolve: https://italonascimento.github.io/applying-a-timeout-to-your-promises/

**Comment by debianw** [comment]
Any progress on this issue ?. This is only happening for iOS. Android is ok

**Comment by Connoropolous** [comment]
linked to #10124 
having same issue myself

**Comment by vigzmv** [comment]
Using createTokenWithCardAsync with wrong data crashes the app. Is there any way to handle the error without crashing?
Thanks

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
