### ISSUE TITLE
expo-google-sign-in is not supported in the expo client

### ISSUE THREAD

**Issue by mishkeTz** [expo/expo#4854]
Expo Cli: 2.21.2
Expo SDK: 33.0.0

Hello,
I am trying to set up the GoogleSignIn in my expo app.
When I call: 
`GoogleSignIn.initAsync({ clientId: '<VALID_ID>' })`

I get the following error:

> expo-google-sign-in is not supported in the Expo Client because a custom URL scheme is required at build time. Please refer to the docs for usage outside of Expo www.npmjs.com/package/expo-google-sign-in

When I invoke the the signIn function and try to login with this code:
`await Google.askForPlayServicesAsync();
 const { type, user } = await Google.signInAsync();`

I get this error:

> expo-google-sign-in is not supported in the Expo Client because a custom URL scheme is required at build time. Please refer to the docs for usage outside of Expo www.npmjs.com/package/expo-google-sign-in

I am not sure what I am missing here, I followed the docs. 
I have set up the Firebase project and updated the app.json file.

**Comment by cruzach** [comment]
`GoogleSignIn` can't be used in the Expo client, since the native `GoogleSignIn` library expects your `REVERSE_CLIENT_ID` in the info.plist at build-time, so that is expected.

I recently tested the `Google.signInAsync` behavior and (barring [this bug]()), it seemed to be working fine. It looks like maybe you're still making a call to `expo-google-sign-in`? Otherwise I'm not sure how that error could pop up. I'd make sure you don't have `expo-google-sign-in` as a dependency, and then delete your `node_modules` folder and reinstall via npm/yarn
