### ISSUE TITLE
Couldn't start project on Android:

### ISSUE THREAD

**Issue by KingCosmic** [expo/expo#486]
ive updated to the newest Expo XDE version ive turned on usb debugging and i cant get anything to work any suggestions

**Comment by KingCosmic** [comment]
the only error im getting is "Couldn't start project on Android:" sorry for the long reply didnt see you replied lol

**Comment by flieks** [comment]
no problem. Check your it's the right IP address. I had virtual ip's so it was taking the wrong IP. On LAN and exp. Tunnel should work mostly if LAN doesn't work.

**Comment by nicolocardana** [comment]
I had the same problem. Just solved by uninstalling and reinstalling the Expo XDE

**Comment by terribleben** [comment]
Let me know if you're still blocked here. Sounds like maybe resolved.

**Comment by snooty7** [comment]
I had the same problem and it seems that  127.0.0.1:5037 had more than one socket connections. My advise is to restart your laptop or workstation and check port 5037. Then kill the service than is using it and try again.

**Comment by sudo-man** [comment]
I had the same problem on my mac. the reason is expo was trying to list devices from terminal some how by adb command. so i had to install adb for terminal and every thing works fine after that.
try to run this command if you have already `brew` 
```
brew cask install android-platform-tools
```
here is adb installation guides link.
[https://stackoverflow.com/questions/17901692/set-up-adb-on-mac-os-x#answer-28208121](url)

I hope that will help somebody.

**Comment by Sphinxs** [comment]
Same problem on Expo 4 on Linux
