### ISSUE TITLE
SDK 33 - App size is huge !

### ISSUE THREAD

**Issue by aejaex** [expo/expo#4946]
Hey guys,

In SDK 32 two projects of mine were at 16.5 MB and 17.4 MB for Android, and 27.8 and 28.4 MB for IOS versions of the standalone app.

In SDK 33, the same projects are now sizing at 28 MB for Android, while I am yet to check for IOS. Has the app size increased dramatically from SDK 32 to 33? If so, why?

**Comment by ide** [comment]
This is likely because of 64-bit support, which is a new requirement from Google. If you use Android App Bundles, the actual APK downloaded from Google Play will include code for only the ABI at hand and be much smaller.

To be clear, *the size of the IPA or APK that you upload to the App Store or Google Play is larger (sometimes much larger) than the size of the IPA or APK actually downloaded to the device.*
