### ISSUE TITLE
[Permissions] Major rework

### ISSUE THREAD

**Issue by lukmccall** [expo/expo#4972]
I will try to make permissions rework.

Here I post some information about what and how I want to change. 
It would be nice if you provide me some feedback, then we figure out how new permissions will look like. 

Firstly I want to focused on iOS implementation.

Here is our current flow graph for permission asking:

![PermissionsFlow](https://user-images.githubusercontent.com/9578601/61320629-13fd0880-a80a-11e9-9544-259b0c289c85.png)

So my suggestions:
- move more logic from `ScopePermission` (SP) to `expo-permission` (P). Now, the decision on how to check given permission came from `ScopePermission` (SP). This solution forced a lot of jumps between SP and P. If we move decision logic to P we could treat SP like iOS extension, which provides API for permissions per experience. 
- treat "particle permission" as a full-fledged permission type (`Location in the foreground` will be a subtype of `LocationPemission`).
We could make a permission family, for example:
LocationPermission will be divided into `foreground` and `background` permission, so the user will be able to ask for all 3 permissions (LocationPermission will still be available to the user).  
  - If he asked for the main permission, this will be treated as asking for all children permissions. 
  - In a situation when he asked for child permission and the current platform doesn't support the required type of permission, the system will ask for the main permission. 

For now, I will try to refactor the current permissions code to make it more readable.

**Comment by tsapeta** [comment]
Some thoughts to note:
1. Can we move permission requesters to the specific modules that are actually needing them? We install `expo-permissions` in all React Native apps using unimodules (it is a dependency of `react-native-unimodules`) and the bad thing is that every such app contains the code that asks for all available permissions - it isn't good for Apple review since their static code analyzer detects that we ask for microphone permissions and requires us to have `NSMicrophoneUsageDescription` in the Info.plist. Our users are forced to add usage description for every permission that `expo-permissions` supports - I'd like to change that. So, in other words, the microphone permission requester would be implemented by `expo-av` or even separate unimodule package `expo-permissions-microphone` that `expo-av` depends on. 
2. This thought is somehow related to the previous one – I feel like the APIs offered by some unimodules are not fully completed if we look at them from the permissions side. If you're working on the app with unimodules, and once you decide to use for example `expo-media-library` for getting photos from the camera roll, you will finally need to also import `expo-permissions` because media library doesn't have any method for checking/requesting the permission that *is required* to use anything from that unimodule! To make things simpler for the users, every unimodule requiring any permission should have its own `ask` and `get` methods. So, already mentioned `expo-media-library` would have two new methods: `getPermissionAsync` and `requestPermissionAsync`.
I've already added something like that in `expo-location` and `expo-calendar`, but I think this should be the main and official way of handling permissions.

cc @brentvatne @ide @esamelson

**Comment by esamelson** [comment]
@tsapeta I agree, think that makes sense and would be a good improvement. The original design made more sense when the `expo` package was a monolith and you'd always have the permissions module whenever you had any of the others, but the points you've brought up for distributing permissions throughout individual modules now make sense to me. We would just want to do it in a way that preserves the single source of truth (PermissionsKernelService) for scoping permissions in the Expo client.

**Comment by brentvatne** [comment]
@tsapeta - moving permission requester to the module that uses seems like an elegant way to accomplish this, and i definitely like having a simple way to request permissions built in to each api.

it's worth perhaps noting the implementation that react-native-permissions is opting for, which uses subspecs for different permissions: https://github.com/react-native-community/react-native-permissions/pull/291. if we took this approach we could combine it with autolinking by perhaps using some configuration in app.json that selects the permissions being used.

i'm open to either, although i'd want to be sure that if we opt for the first approach that it preserves a single source of truth like @esamelson suggested. also, i'm curious what we would do to handle the case where multiple libraries depend on the same permissions.

**Comment by lukmccall** [comment]
I cleaned the permission module a little bit (see #5034). 

Now, I'm working on dividing all requester into separate podspec (something similar to `react-native-permissions`). I think this option is best for us because we will divide the permission module into parts which people can import separately into their projects. Also, we can achieve one more goal - our current unimodule, which using permissions, could depend only on specific for them podspec. 

Our new permission module structure:
- Core (interfaces and EXPermission class, which export method to js side)
- Calendar (separate requester)
- Location (separate requester)
...

@tsapeta suggest changing the official way of handling permissions. I think it's a good path and I want to use our current mechanism (`UMPermissionInterface`) to accomplish this. Every module will be able to handle own permission. 

cc @tsapeta @brentvatne @easadler

**Comment by mcmar** [comment]
One thing that isn't mentioned here is that currently the location permissions library says this:
```
What location usage descriptions should I provide? Due to the design of the location permission API on iOS we aren't able to provide you with methods for asking for whenInUse or always location usage permission specifically. However, you can customize the behavior by providing the following sets of usage descriptions
```
But then if I don't include `NSLocationAlwaysUsageDescription`, I get a warning from Apple telling me that my app will be rejected beginning Spring 2019. We're obviously well past Spring 2019, but I live every day in terror that Apple will soon begin rejecting our app for this alleged violation. 

Hopefully the new API design can overcome this drawback and either allow me to request only `whenInUse` even with `NSLocationAlwaysUsageDescription` or simply not include the code for calling `always` in the same module. This might be related to the expo-location module as well and we are using expo-location and permissions with unimodules in the bare workflow.
