### ISSUE TITLE
onCalloutPress on MapView.Marker only trigger in Apple Map not with Google Map

### ISSUE THREAD

**Issue by sloppycoder** [expo/expo#499]
the project is up on Expo  https://expo.io/@sloppycoder/cam-proto
code is here.
https://github.com/sloppycoder/crna-cams/blob/master/src/screens/AccountListMapViewScreen.js

When testing on iOS simulator and iPhone, the onCalloutPress is triggered only when using Apple Map. When switched to Google Map (by using the toggle in Settings screen), the call out is displayed, but tapping on it has no effect. I'm new to this and I'm lost as to how to track down the problem from here. 

Any suggestions and help is appreciated. 

RN 0.46.4
Expo 19.0.0

**Comment by sloppycoder** [comment]
Just tested this again with Expo client. Apparently it only happens on my iPhone 6s (iOS 10.3.3) not on my Android phone. Nexus 5x Android 7.1.2.

**Comment by terribleben** [comment]
Hey there, sorry for the very slow followup. Under the hood we're just using [react-native-maps](https://github.com/react-community/react-native-maps), and also we've updated that library since this issue was open. I recommend updating to a newer Expo SDK, and if the issue persists, opening an issue on the rn-maps repo.
