### ISSUE TITLE
How Can I remove SYSTEM_ALERT_WINDOW permission?

### ISSUE THREAD

**Issue by alirezadarvishi** [expo/expo#5025]
I want to delete android.permission.SYSTEM_ALERT_WINDOW  permission but in expo I can't do it.

https://facebook.github.io/react-native/docs/removing-default-permissions

How can I do that?

**Comment by alirezadarvishi** [comment]
@cruzach 

It's is not possible?

**Comment by cruzach** [comment]
Hey @alirezadarvishi - no need to tag people in Github issues, we will get to them as soon as we can!

This is a better question for our [forums](https://forums.expo.io/), as it's not a bug report. I suggest looking through our [docs on app.json Android configuration](https://docs.expo.io/versions/latest/workflow/configuration/#android) first though. It discusses how to request/not request certain android permissions, and which ones are absolutely necessary for Expo. If you don't want to include a permission that Expo requires, you'll have to use the bare workflow instead of managed
