### ISSUE TITLE
Invalid exp protocol link

### ISSUE THREAD

**Issue by coockoo** [expo/expo#508]
Got weird behaiour in Expo XDE. Project builds successfully, but link (and as a result QR-code) is wrong. So I have to type url manually to open my app.

Expected result:
```
exp://192.168.0.103:19000
```
Actual result
```
expb04f43aa082c43ac83ea0acb940e5017://192.168.0.103:19000
```

node `v7.8.0`
npm `4.2.0`
XDE version `Version 2.19.3 (2.19.3)`

**Comment by jesseruder** [comment]
Seems like your app is detached, in which case that scheme is intentional. Your app won't work in the main Expo client if you've added extra native modules. Can you explain why you expected the `exp` scheme?

**Comment by coockoo** [comment]
@jesseruder Yes, I did detach my app. My primary goal was to add icons to my app and I didn't find any solution, except to insert them using XCode, which requires detaching. So I detached, added my icons  [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) and then I want to continue using Expo. And you are trying to say that I can't use it anymore after detaching. That makes me sad. I really enjoy this product. Are there any other tools on the internet, which work as Expo, but for detached apps?

**Comment by terribleben** [comment]
You can use [vector icons without detaching](https://docs.expo.io/versions/latest/guides/icons.html#expovector-icons).

If you detach, you need to develop your project from Xcode / Android Studio, as we don't manage your native code any more. You can still serve your project from Expo XDE (or exp), and you're still "using Expo", but you can't load within the Expo Client app any more, since it won't have your specialized native code.

Let me know if you're still blocked or feel free to follow up on the [forums](https://forums.expo.io/).
