### ISSUE TITLE
expo-payments-stripe npm package 5.0.1 misses unimodule.json

### ISSUE THREAD

**Issue by yegorius** [expo/expo#5082]
### Environment
```
> expo diagnostics
Cannot read property '1' of null
Set EXPO_DEBUG=true in your env to view the stack trace.
```
```
> env EXPO_DEBUG=true expo diagnostics
Cannot read property '1' of null
TypeError: Cannot read property '1' of null
    at a.run.then.e (/home/aries/.config/yarn/global/node_modules/envinfo/dist/envinfo.js:1:97193)
    at <anonymous>
```
App target: ExpoKit

### Steps to Reproduce

create fresh Expo 33 project
run `expo eject`
run `expo install expo-payments-stripe`
try to build iOS or Android project

### Expected Behavior

expo-payments-stripe shows up in the dependency list of Xcode or Android Studio.

### Actual Behavior

The absence of `unimodule.json` doesn't allow the build system to pick up expo-payments-stripe native module.

### Reproducible Demo

`npm pack expo-payments-stripe@5.0.1 2>&1 | grep unimodule`

**Comment by cruzach** [comment]
Does this also happen in `"expo-payments-stripe": "^6.0.0"`?

**Comment by yegorius** [comment]
No, it doesn't, since 6.0.0 has `unimodule.json` in it.

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
