### ISSUE TITLE
Webview doesn't render in react-native-web

### ISSUE THREAD

**Issue by cdcv** [expo/expo#5088]
## 🐛 Bug Report
Using simple webview in react-native-web doesn't render (for a webview that renders correctly in mobile).
I think this should work in browser without changes.
In the meantime, is there a workaround for displaying the same content in browser (eg rather than webview use iFrame, etc)?

Thanks for your help!

### Environment

 Expo CLI 3.0.2 environment info:
    System:
      OS: macOS 10.14.1
      Shell: Unknown - /usr/local/bin/fish
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      npm: 6.10.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^5.1.3 => 5.1.9 
      @types/react: ^16.8.23 => 16.8.23 
      @types/react-native: ^0.60.0 => 0.60.2 
      expo: ^33.0.0 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.0.9 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.2

### Steps to Reproduce
Minimal example straight from the docs:

### Expected Behavior
Renders webview correctly in native, also in react-native-web.

### Actual Behavior
In web browser, just renders white area.
Renders correctly on device / simulator.
### Reproducible Demo
     <WebView
        originWhitelist={['*']}
        source={{ html: '<h1>Hello world</h1>' }}
        style={{ marginTop: 20 }}
      />
I ran this in a component visualized through storybook... not sure if that had anything to do with it or not.

**Comment by raajnadar** [comment]
Try adding flex to 1

```
<WebView
    originWhitelist={['*']}
    source={{ html: '<h1>Hello world</h1>' }}
    style={{ flex: 1}}
 />
```

**Comment by cdcv** [comment]
Thanks for the suggestion @raajnadar, but no change unfortunately.  I see a skinny red border of some kind, but not the actual content.

**Comment by cdcv** [comment]
Looking at the DOM in the browser, this is what's rendered for what appears that it's supposed to be the webView:
<div class="css-view-1dbjc4n r-flex-13awgt0 r-width-13qz1uu r-zIndex-1tisrxv" style="align-self: flex-start; border-color: rgb(255, 0, 0); border-width: 1px;"></div>

It's just rendering an empty red border...

**Comment by cruzach** [comment]
Looks like it's not rendering the `source`, but the styles applied are working correctly. At least I'm able to change those (adding a border for example)

**Comment by FiberJW** [comment]
React Native Web [currently doesn't implement WebView](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/WebView/index.js).

[react-native-web is going to delegate WebView needs](https://github.com/necolas/react-native-web/issues/1025) to https://github.com/react-native-community/react-native-webview since react-native core is dropping it from its group of supported APIs and components.

It looks like the ball hasn't moved on react-native-community/react-native-webview's part for web support,  so I would make an issue to put it on their radar. For now, using an iframe will likely serve your purposes, so I suggest to go that route.

If you have any further related bugs or problems, feel free to open a new issue. Thanks :)
