### ISSUE TITLE
Too much permission

### ISSUE THREAD

**Issue by Gaserd** [expo/expo#510]
Hey, guys!

But may be this : “Remove the field to use the default list of permissions” not correctly ?

Because, if create empty Android App you have two permission : INTERNET and ALERTS.

May be you can change “default permissions” not to aggressive, because users don’t understand why they allow so much permissions.

I can write this:
```
permissions : [ "default" ]
```
And you create AndroidManifest.xml for default Android App.

Thanks!

link forum : https://forums.expo.io/t/delete-permission/2330/5

My app.json 
```
{
  "expo": {
    "name": "BitcoinRate",
    "description": "Bitcoin Rate – small project of monitoring Bitcoin",
    "slug": "BitcoinRate",
    "privacy": "public",
    "sdkVersion": "19.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "primaryColor": "#BD10E0",
    "icon": "./assets/icons/app-icon.png",
    "loading": {
      "icon": "./assets/icons/loading-icon.png",
      "hideExponentText": false
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.gaserd.bitcoinrate"
    },
    "android": {
      "package": "com.gaserd.bitcoinrate"
    },
    "androidStatusBarColor": "#BD10E0",
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#BD10E0",
      "permissions" : [
        "com.android.launcher.permission.INSTALL_SHORTCUT"
      ]
    }
  }
}
```

**Comment by jesseruder** [comment]
I don't really understand your question. Does this key not work for you https://docs.expo.io/versions/latest/guides/configuration.html#permissions? Going to close this issue until we clarify what's going wrong.

**Comment by Gaserd** [comment]
@jesseruder 

Okay.

Build app without Expo - app size 7mb, 16mb install on Android and allowed permission : 3

Build app with Expo - app size 23mb, 72mb install on Android and allowed permission : 13

**Comment by danikane** [comment]
I think docs are not specific enough and Gaserd is frustrated about the default permissions list, which you will get when not using the property in app.json.
```
 /*
      List of additional permissions the standalone app will request upon installation.
      Along with the minimum necessary for an expo app to function.  

      Don't use "permissions" to use the default list.

      Set "permissions" to [] to use ONLY the MINIMUM necessary permissions.
    */
```
What exactly is the MINIMUM, because the docs don't specify that?
I created a new app, didn't specify permissions, as a result I got tons of them.
The next build I set only "VIBRATE" so none of the privacy policy related permissions got installed.

@Gaserd The app size is a different thing and there is a canny for that:
https://expo.canny.io/feature-requests/p/reducing-app-size

**Comment by ifalldev** [comment]
Hello Guys!

Any update on that? I think those questions can be easy answered by the expo team.

What "minimum" and "default" mean?

Google now is about to remove apps which have a ton of permissions asks without a reason.

Please help us :(

**Comment by danikane** [comment]
Check the docs:
https://docs.expo.io/versions/latest/workflow/configuration#android
https://docs.expo.io/versions/v31.0.0/sdk/permissions#android-permissions-equivalents-inside-appjson

Use permissions: [] if you don't require access to camera, location or whatever otherwise you'll get the default list.

**Comment by ifalldev** [comment]
Thank you @danikane!

The second link was enlightening
