### ISSUE TITLE
Couldn't adb reverse: Invalid source port: 'null' - When connecting phone via usb

### ISSUE THREAD

**Issue by avalanche1** [expo/expo#511]
When connecting phone via usb and trying to run `exp android --offline` I get the fol.:
`Couldn't adb reverse: Invalid source port: 'null'`.
It still opens Expo on the phone but fails to load the app with error `Failed to connect to /192.168.0.99:80`

**Comment by jesseruder** [comment]
Is your phone on the same network as your computer? Can you access that IP address from your phone's browser?

**Comment by cdmitri** [comment]
Found this through google, might not be the same issue, but same error so here is my case for info.

I'm getting the same error but running Expo in emulator (Genymotion 2.0) says: "Could not load exp://lo
calhost:80".

I've create the app with create-react-native-app and can successfully run it with "npm start android", that command returns the exp://192.168.56.1:19002 url and that works after pasting to the clipboard on the emulator (great feature :). Emulator phone is on the 192.168.56.* network.

adb is setup for XDE and I can open the same project with XDE and connect/run with Device->Open on Anroid. When I do that both "tunnel" and LAN hosts work and appropriate links are in Expo on emulated device instead of "localhost:80"

**Comment by avalanche1** [comment]
@jesseruder yes; yes

**Comment by mauroporrasp** [comment]
Try with `exp start --lan`

**Comment by lijunle** [comment]
I got into this. Found that, I need to run `exp start` in another window before run `exp android`.

**Comment by wurikiji** [comment]
@lijunle I solve this problem using your solution. Thanks.

**Comment by sjchmiela** [comment]
Thanks, @lijunle, for explaining how to fix that problem! 🙂

**Comment by MingBillCheng** [comment]
Need to run `expo start` to start the server first, then run `expo android`

**Comment by AhmedNj** [comment]
hey, i have a problem, when i lance expo run they said : Couldn't start project on Android: Error running adb: Request failed with status code 502
can you help me plz, if anyone has the same error

**Comment by Aaronik** [comment]
May 2019 and I'm having the same issue as OP. I'm trying to run the expo app on my android phone that **isn't connected to the same network** and is **not connected to the internet**.

The help docs say it should work while offline:

```
expo android --help   

  Usage: android [options] [project-dir]

  Opens your app in Expo on a connected Android device

  Options:

    --offline        Allows this command to run while offline
    --config [file]  Specify a path to app.json
    -h, --help       output usage information
```

It's not clear *which device can be offline*, though. Or what the network status needs to be. Is it that both the phone and the computer need to be connected to the same network, but *that network* itself can be offline?
