### ISSUE TITLE
Push Notifications (expo-server-sdk-node) batched by sendPushNotificationsAsync fail when using Push Tokens initialized by different users

### ISSUE THREAD

**Issue by connor-odoherty** [expo/expo#5111]
### Environment

```
  Expo CLI 2.20.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.14 => 16.8.23 
      expo: ^33.0.0 => 33.0.7 
      react: ^16.8.3 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.20.2
```

App target: Both TestFlight binary and Expo CLI, when launching push notifications using expo-server-sdk-node 

### Steps to Reproduce

1. Create a project shared by multiple users.

2. Generate a push token from a device running a TestFlight binary

3. Generate a push token from a device running the app through Expo dev tools

4. Create a list of push notification objects and send like:

```
pushNotifications = [
  {
    to: expoCLIPushToken,
    ...
  },
  {
    to: testFlightBinaryPushToken,
    ...
  }
]
expo.sendPushNotificationsAsync(messages)
```

My organization currently has a company account (which we will call @company and some users associated with it (which we will refer to as @user.

When we test our Expo app, we initially test it against a development server. Whether we are running the app from an Expo simulator locally, or from a binary downloaded through TestFlight, we want to use the same server.

Unfortunately, this creates some major issues when storing and using Expo Push Tokens. Because this development server wants to send batched push notifications using Push Tokens from both the Test Flight binary and Expo simulator, our Push Notification batch sends short circuit and fails.

Even if the local Expo instance has the same project UUID as the TestFlight instance, we still see these failures because the TestFlight binaries are prefixed by @company and local builds are prefixed by @user.

### Expected Behavior

So long as each of the push tokens was generated from the same project, the push notifications should send successfully regardless of whether they were generated by a TestFlight instance of the app, or a Expo CLI instance of the app.

### Actual Behavior

As soon as the Node JS Expo Push Client sees that a push token was generated by @user/my-project-uuid instead of @company/my-project-uuid, the send short circuits and it fails to send. We see a receipt like:

```
[ { status: 'ok', id: '05621305-8ab0-40a0-9a23' },
  { status: 'error',
    message: 'The recipient "ExponentPushToken[ZjJhtKCNc_Xw]" is associated with a different experience than "@user/my-project-uuid"' },
  { status: 'error',
    message: 'The recipient "ExponentPushToken[vpBWCKD]" is associated with a different experience than "@user/my-project-uuid' } ]
```

### Reproducible Demo

It is not possible to provide a reproducible demo because the behavior relies on running the same code from multiple binaries. The issue is the push platform itself, and described above.

So, a few questions:

1. Is there any way for users that are running the app from the Expo CLI to behave as if their project id was @company/my-project-uuid instead of @user/my-project-uuid?

2. Is it a bug or by design that these Push Notifications are failing? I would think that it is a common use case for multiple users to be working on the same development server for a shared project

3. Are the only current solutions to either: a) store the user project ID with each push token and batch them separately or b) Send every message individually

**Comment by ide** [comment]
To give you the context behind the answer, it is by design that all notifications need to be for the same user + project. The reason for this restriction is to support (optional) API tokens so that HTTP requests to the push service are protected by both the API token and the individual push tokens.

As with most other services, the API token would be linked to an account (`@user`) or a specific project (`@user/app`). The push service requires all push tokens to be for the same project so that you can use a project-specific API token with the HTTP request.

(Note: API tokens aren't currently implemented, but we're starting to work on them.)

These are the answers to your specific questions:

1. For business teams, we recently rolled out a paid plan ($29/mo) that includes support for teams. The way teams work is that any account can be a team account. You log into the team account (ex: `@company`) and then add other users to the account (`@user`, `@teammate`) and choose their permission level.

In your project's app.json file, you'd add `{ "expo" { "owner": "company" } }` (replace "company" with your team account's name). Then when any of your teammates runs `expo publish`, the app will get published to `@company/project` (assuming they have permission to do so).

This is a pretty new feature and might not address all your needs but I'd recommend giving it a try (you can try it out for free) here: https://expo.io/developer-services.

2. This is by design. I wrote more about this above at the start. Hopefully that explains what is going on and why.

3. I'd recommend `(a)` so that you get the benefits of batching.
