### ISSUE TITLE
[devmenu] Tools to clear caches in client

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#5129]
- A button to clear the cached network data
- A button to clear local Expo data

**Comment by CostachescuCristinel** [comment]
Hi, I have noticed this thread is opened since July 2019, but it seems none of these features are available yet. Do you have any updates or roadmap for their implementation ?

**Comment by tsapeta** [comment]
Hi @CostachescuCristinel 👋 
We're now preparing other things to implement these features, see #6793 and #6829 - they both are actually finished, but not merged yet. As we have some other and higher priority tasks on SDK37 roadmap, there is only a small chance they will be implemented in that release.
Which feature of these you need the most? Are there any other devtools that you'd like to see in the dev menu?

**Comment by CostachescuCristinel** [comment]
I am not using network cached resources yet, so I am more interested into the local data cache.
If not anything hard, just make the Expoclient completely clear all cached resources when the clear button of the apps list is pressed.
This is also useful to debug user experience like in a fresh app install, so I think most people would be looking forward to this rather than the separate features of clearing network caches and local data caches.

However, since my original issue is not exactly a commonly repeating pattern during development, I would be fine if you skipped this for a proper implementation in SDK38. Should you choose this road, please add a note in the documentation about possible caching issues, otherwise, more developers might waste half and hour before understanding that their fonts had nothing to do with the issue they're experiencing.

**Comment by brentvatne** [comment]
not a bug so i'll close this. this is something that @tcdavis and the team may get to at some point with expo-dev-client
