### ISSUE TITLE
SDK 34 build size is way larger

### ISSUE THREAD

**Issue by sayem314** [expo/expo#5167]
SDK 33
- Final build (~27MB)
- Simulator build (~21MB)

SDK 34
- Final build (~40MB)
- SImulator build (~41MB)

**Comment by cruzach** [comment]
Hi! We had this asked about [on our Forums recently](https://forums.expo.io/t/sdk34-android-google-play-store-not-accepting-apk-because-of-permissions/25890/8?u=charliecruzan). Basically, the apk size increase is expected now that `FaceDetector` is being included in SDK34 apps — it was being (erroneously) excluded from SDK33 apks, as well as any SDK34 apks built before yesterday’s fix.

**Comment by edoantonioco** [comment]
good to know the reason.
Also, since facedetector is part of expo-face-detector, I though it would mean is not part of the expo apps that doesnt implicitly import it. 

It uses 10 mb of every single expo apk, for a feature that most does not use at all.

**Comment by cruzach** [comment]
We're working on making some modules optional, but still early in the process

**Comment by Slapbox** [comment]
Just for the team's reference, since the increase in APK size seem larger than I'd ever expect:

- **SDK 31:** ~20mb
- **SDK 32:** ~16mb
- **SDK 33:** ~30mb
- **SDK 34:** ~49mb

That's an almost tripling of size since SDK32. I knew APK size would increase with SDK33, but I didn't expect it to be so much by the time we reached SDK34. I don't even feel that my app has that much in terms of assets/total code compared to plenty of other apps.

**Comment by sayem314** [comment]
I had to eject for huge size increase. The last version of my app with expo was 52MB. So after ejecting the iOS version is now 8.5MB and android version is 9.3MB, not just it it feels faster as well.

**Comment by jgutierro** [comment]
same problem here

**Comment by rabihiawaludin** [comment]
any updates? how to decrease this big apk?

**Comment by Slapbox** [comment]
@rabihiawaludin you can use  `expo build:android -t app-bundle` to build a `.aab` but as far as a smaller `.apk` I haven't heard anything from the Expo team stating they plan to remove `FaceDetector`. I hope they will, it's just enormous.
