### ISSUE TITLE
[android] App can not start after splash screen

### ISSUE THREAD

**Issue by hoangtrucit** [expo/expo#5210]
### Environment

```
Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
      Yarn: 1.15.2 - ~/.nvm/versions/node/v8.11.4/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.9
   ```

### Steps to Reproduce

I build standalone and install directly apk on samsung node 5 with android version 7.0, it will run  very stable. When i publish on google play and after that i install from google play the app only display slash screen 

Thanks for you help.

**Comment by cruzach** [comment]
Hi! Could you provide a little more info so that we can figure out the root cause a little better? A way for us to reproduce this would be best!

My guess is that your app is having trouble fetching the JS bundle. What flags (if any) did you pass to the `expo build:android` command? Do you use [release channels](https://docs.expo.io/versions/latest/distribution/release-channels/)?

Also, please paste your app.json here

**Comment by hoangtrucit** [comment]
Thanks @cruzach, after i reset my phone and reinstall apk it's work normal. I think my phone cache wrong account in my system
