### ISSUE TITLE
[docs] Three separate pages required to upgrade Expo

### ISSUE THREAD

**Issue by WouterFlorijn** [expo/expo#5214]
Upgrading Expo for an ejected/bare Expo app is difficult. I don't think that's a secret. I understand that making this process easy is hard to do technically from the side of Expo, but in terms of documentation, there's a lot of room for improvement.

Currently, upgrading requires you to go through three different sets of instructions, in no specified order:

- [Developing With ExpoKit / Upgrading ExpoKit](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit)
- [Expo SDK X is now available](https://blog.expo.io/expo-sdk-34-is-now-available-4f7825239319)
- [Upgrading Expo SDK Walkthrough](https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/)

Besides that, there are a number of issues with the content of the docs that make it more difficult.

- Upgrading to a version other than the latest version is especially difficult, since documentation and expo-cli assume you want the latest version.
- [Developing With ExpoKit / Upgrading ExpoKit](https://docs.expo.io/versions/latest/expokit/expokit/#upgrading-expokit) doesn't mention which version you're upgrading to. Instructions change if a new version is released. In my case, this actually happened while I was upgrading my app, which was extremely confusing.
- It's unclear what the difference between "detached", "ejected" and "bare" in, and when which term was introduced.

Currently, the only way to get close to a working project is to run `expo init`, copy the files from the newly initialized project to your project, and then manually adding in the changes you have for packages you're using. Please make it easier.

**Comment by cruzach** [comment]
Hi @WouterFlorijn , we've officially deprecated Expokit with the last SDK release (38) in favor of the bare workflow, and also removed any references to Expokit from our documentation. Now, there are two workflows: bare and managed, that's all. We document these [here](https://docs.expo.io/introduction/managed-vs-bare/). Hopefully that clears up some of the confusion around "detached", "ejected", and "bare" 😃 

As for upgrading, it's gotten significantly easier in the managed workflow since all you have to do is run `expo upgrade`. In the bare workflow, you don't rely on the Expo SDK version, so you can upgrade your dependencies as you wish. The one caveat there is upgrading React Native, since ymmv if you upgrade to a higher React Native version than the most recent version of the Expo SDK (and thus, any expo modules) supports.
