### ISSUE TITLE
Sdk 34, new modular format and IDFA. Do I still have to answer yes ?

### ISSUE THREAD

**Issue by borgogelli** [expo/expo#5265]
I use the sdk 34 to build an ios standalone (managed) app and I have read the following paragraph in the doc:

> Apple will ask you whether your app uses the IDFA. Because Expo depends on Segment Analytics, the answer is yes, and you'll need to check a couple boxes on the Apple submission form. See Segment's Guide for which specific boxes to fill in.

I haven't include the expo-analytics-segment package in my project, so the question is: 

Even with the **new modular format**, do I still have to answer yes to the IDFA queston on the AppStore ?

**Comment by cruzach** [comment]
You still will answer yes since in the managed workflow, the native code for those modules is bundled in. Modularized imports paves the way for tree-shaking and smaller JavaScript bundles, but it doesn't allow for opting in or out of modules, yet.

If you need to exclude certain modules, the bare workflow is your best way to achieve that
