### ISSUE TITLE
Flex wrapped items act unexpectedly ONLY in web view

### ISSUE THREAD

**Issue by dnorth** [expo/expo#5271]
### Environment

```
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
      Yarn: 1.5.1 - ~/.nvm/versions/node/v10.16.1/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.9
```

### Steps To Reproduce

1. See related snack - https://snack.expo.io/B13SVavQH

Describe what you expected to happen:

Items that are wrapped should be grouped closely together based on layout.
If you run the "Android" or "iOS" version you can see that what is shown there is the expected behavior. So this seems to only happen in the web version of the application.

**Comment by EvanBacon** [comment]
This appears to be a bug with react-native-web.

**Comment by FiberJW** [comment]
If your desired effect is having the row fill the screen's width, `width: '100%'` will fix your issue. This may seem to be a bug, but using `flex: 1` isn't the way to go about styling your row since you don't want your row to take up the max vertical space too. Here's a snack with the styling fix: https://snack.expo.io/@datwheat/52e713 

If you have any further related bug reports, please open another issue. Thanks :)
