### ISSUE TITLE
Just created typescript Project by using expo cli, when I build android bundle, it include expo-ads-admob:6.0.0

### ISSUE THREAD

**Issue by openmaya** [expo/expo#5283]
Recently my app was removed from Google Play Store, and they sent a email tha my app is collecting advertisement Id. 

My app is very simple text input and text list. that's all.

Can you tell me how to remove the any kinds of ad?

**Comment by cruzach** [comment]
Hi! Sorry this caught you by surprise, we have a [forum post about this](https://forums.expo.io/t/how-to-stop-transmitting-android-advertising-id/13838/11) which contains (I think) the exact message you received. To remedy this, we suggest [in our docs](https://docs.expo.io/versions/latest/distribution/app-stores/#privacy-policy) to add a simple privacy policy to your app (all iOS apps require it, anyways).

Since all managed Expo projects will contain code for the entire SDK, there's no way (yet) to exclude a particular module unless you go with the bare workflow instead.

**Comment by openmaya** [comment]
Thanks @cruzach I will try it.
