### ISSUE TITLE
Connection problem to expo servers from Iran

### ISSUE THREAD

**Issue by sinapcs** [expo/expo#530]
Hi. First thank you for this great project.
But I have one problem. I can't open expo.io or any expo project without VPN.
It's not a big problem for me. I can use VPN, but my app's users are in Iran and they can't do update from expo servers.
Is this problem intentional?

**Comment by jimmylee** [comment]
We are **not** intentionally prohibiting users from Iran, and we definitely want anyone in the world to be able to use Expo.

Iran has a large blacklist of websites that they do not allow their citizens to access, if one of the  services we use is blocked, there is not much we can do. And I'm **really sorry** about that.

**Comment by danielstocks** [comment]
@jimmylee Just to clarify here: This is NOT iranian goverment blocking their citizens, This is US companies that for some or other geo political reason is blocking iranian IP adresses from accessing their services.

For example this is the case with the Google Cloud platform, and is probably why Expo is not working for Iranian users. Giving app developers a choice of CDN/platform to host on will be helpful since AWS is not restricting access to anyone, and works fine in Iran.
