### ISSUE TITLE
Support iOS 7 style receipt in in-app-purchase

### ISSUE THREAD

**Issue by OscarYuen** [expo/expo#5322]
During Apple in app purchase workflow, server side needs to verify the base64 string receipt sent from the notification by Apple. 

The verification endpoint would return a receipt json to server if the base64 string receipt is valid. However, I found that the receipt json is in iOS 6 style which is deprecated instead of iOS 7 style.

After some brief study, it seems that the style of the receipt depends the API called under native module and not depends on the mobile iOS version.

iOS 6 style receipt is retrieved from transactionReceipt which is also deprecated. In order to get iOS 7 receipt, appStoreReceiptURL is needed
[transactionReceipt](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1617722-transactionreceipt)
[appStoreReceiptURL](https://developer.apple.com/documentation/foundation/nsbundle/1407276-appstorereceipturl)

Is it possible to support iOS 7 style receipt in the future?  It is quite hard to find iOS6 style receipt in official document.

Document Reference:
[https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1)

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
