### ISSUE TITLE
whenever i use alignItems: 'center' on a react navigation page, the page shows up as white.

### ISSUE THREAD

**Issue by papacheech** [expo/expo#533]
I am following a udemy course that uses expo, which was created about 4 months ago. The instructor had no issues, but it does not render anything except a white screen for me. The issue goes away when i remove alignItems: 'center' from my styles.

zip file incoming with project source.

**Comment by jimmylee** [comment]
Hey @papacheech welcome to Expo! Glad you're here.

Is there anyway you could provide us an example of the code you're trying to use? This is really hard to work off of.

**Comment by papacheech** [comment]
hey there,
code incoming! Sorry for the lack of description i was going to come back and provide more info once i did some more research. 

I am following a udemy course that uses expo, which was created about 4 months ago. The instructor had no issues, but it does not render anything except a white screen for me. The issue goes away when i remove alignItems: 'center' from my styles.

zip file incoming with project source.

**Comment by jimmylee** [comment]
If you think your issue is just a general React Native issue, you can try to reproduce it in a https://snack.expo.io, otherwise I'm excited to take a look and help you with your problem.

Meanwhile, this is a useful resource: https://facebook.github.io/react-native/docs/flexbox.html

I use this a lot: https://github.com/vhpoet/react-native-styling-cheat-sheet

**Comment by dikaiosune** [comment]
Going to give this a close since it appears to be a general RN/react-navigation issue. Please reply back with a repro on Snack if we need to reopen! Thanks!
