### ISSUE TITLE
How does assets preloading work with the new "splash" property in app.json?

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#534]
Hi,

Expo v20 has introduced the [`splash` property in `app.json`](https://docs.expo.io/versions/latest/guides/configuration.html#splash).

Does this change anything in the [assets preloading process](https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html)?

Thanks!

**Comment by dikaiosune** [comment]
Not AFAIK -- cc @nsillik

**Comment by pensierinmusica** [comment]
Meaning is the splash screen displayed before the assets get preloaded, or while the asssets are preloaded?

If you want the screen while the app load and the assets are preloaded how is that achieved?

Thx!

**Comment by sonaye** [comment]
> If you want the screen while the app load and the assets are preloaded how is that achieved?

I am interested in knowing about this too.

**Comment by nsillik** [comment]
So, the `loading.splash.image.ios` key on iOS will cause the image specified to be saved directly to the app's bundle during the `exp build:ios` process. The `xib` that is used as the launch screen (and also displayed while the JS packager runs) will point to that bundled image (named `launch_background_image.png`). That means they should load immediately. This does mean however that changes to your splash screen image can't be changed without re-submitting to Apple.

In a subsequent release the same should happen on android as well (again when using the `loading.splash.image.android` key, not yet available).

**Comment by pensierinmusica** [comment]
> The xib that is used as the launch screen (and also displayed while the JS packager runs) will point to that bundled image (named launch_background_image.png)

@nsillik just to make sure I understand this correctly, so you're saying that when a `loading.splash.image` property is set that overrides `loading.icon`?

**Comment by nsillik** [comment]
Yes, the new splash screen doesn't include an icon. Also, I think I've identified a part of our build process which is failing to copy some assets correctly. I'm working on fixing that now. Hopefully shouldn't require waiting until a new SDK lands.

**Comment by pensierinmusica** [comment]
@nsillik I just want to make sure I understand the difference between `loading.splash.image` and `loading.icon`. Also once we have it all workign and figured out I think it'd be great to make the whole concept a bit clearer on the docs  :)  Thx!

**Comment by nsillik** [comment]
@pensierinmusica I think we've fixed the problem in our build system. Please try `exp build:ios` again and let me know if things are working as expected.

Re: the difference between `loading.splash.image` and `loading.icon`. `loading.icon` and `loading.backgroundImage` aren't packaged with the application which means that they have to be downloaded at run time, `loading.splash.image` is actually packaged into the app bundle (`.ipa` or `.app`) so that they are available during startup, meaning there's no delay when displaying them. Additionally the bundled image is included in the `LaunchScreen.xib` which means that as soon as the app is launched you get to see your custom loading screen (prior to this it was just a white screen with a spinner).

There's new features coming in a future release, hopefully SDK21, which includes Android support as well as better less visible flashes-of-white throughout the app-startup process.

**Comment by pensierinmusica** [comment]
@nsillik ok, thx for the reply! It'd be cool to have this info included in the docs. Also, it's important imho to make clear how the transition between `loading.splash.image` and `loading.icon` happens, since in most cases I assume developers want to show the **same image**, without flickering.

**Comment by terribleben** [comment]
Update - for SDK 22, we're making it so that the splash screen hides using the same logic as `AppLoading`, so yes, it will cover your preloading assets logic if you make use of `AppLoading`. (If you don't use the `AppLoading` component, it will hide when your app's JS has finished loading.)

We'll also write a dedicated docs guide which explains all of this.

Tracking here: https://github.com/expo/expo/issues/718

**Comment by pensierinmusica** [comment]
@terribleben awesome, thx!
