### ISSUE TITLE
expo about third-party login

### ISSUE THREAD

**Issue by ptScaler** [expo/expo#5356]
How to achieve third-party login (qq, WeChat, weibo), push, share and other functions?

**Comment by cruzach** [comment]
Hi! There's a whole bunch of pages in our [documentation](https://docs.expo.io/versions/latest/) on this stuff, so I'd search for what your looking for there.

Currently, we don't support any 3rd party push notification parties in the managed workflow, since most will require some native configuration.

If you can't find what you're looking for in the docs, then feel free to post a question over on our [forums](https://forums.expo.io/) (we keep github reserved for bug reports)
