### ISSUE TITLE
[ios13] Add an app.json key to override the app appearance (ex: forced light mode)

### ISSUE THREAD

**Issue by ide** [expo/expo#5362]
To make the transition to supporting dark mode easier there is an Info.plist key called `overrideUserInterfaceStyle` that lets people force their app to run in light mode or dark mode, regardless of the system preferences. This task is to add support to set that key (either via an iOS-only config property, or a universal config value).

https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13/56545696#56545696

**Comment by brentvatne** [comment]
Ah, I was about to post an issue about this as well, here is what mine said:

<hr />

Lots of people probably won't want to bother fully implementing support for dark mode in their apps, and if we don't explicitly prevent the dark mode then the system rendered UI within their app may adapt and the rest will not. So it is probably best for us to add an option to `app.json` that lets people pick what [interface styles](https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13/56545696#56545696) are supported. The default value if `null` should be just `["light"]` so that apps continue to work as they always have. 

```json
  "ios": {
    "supportedInterfaceStyles": ["light", "dark"]
  }
```

**Comment by ide** [comment]
In the long run it seems like we should have all UI styles enabled by default (and have dark mode work out of the box). To start with I think we can have "no key" mean just "light" (or not -- it's easy enough to provide the override) but eventually should switch to "light" + "dark" as the default.

**Comment by Aragorn450** [comment]
This maybe is too late but apparently Apple is now rejecting apps that have the UIUserInterfaceStyle key set in the Info.plist file. See https://forums.developer.apple.com/thread/121028 and https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13#comment101598390_56545696

This means that this pull request will make apps using these changes likely fail when attempting to submit to Apple.

**Comment by ide** [comment]
We'll keep an eye on things since there is a chance they will change since no one can submit iOS 13 apps yet anyway.

**Comment by Aragorn450** [comment]
Haha, you're a lot more optimistic than I am. I'm going with the assumption that they blocked it because they would prefer apps not force themselves to light and do auto choosing instead. So removing it means it's more work to force light and therefore fewer apps will do it.

But it'd certainly be nice if I'm wrong about that!

**Comment by brentvatne** [comment]
@Aragorn450 - you can still force it by setting preference on root view controller so it wouldn't make much sense for them to get rid of the property imo
