### ISSUE TITLE
Error when logging "this"

### ISSUE THREAD

**Issue by pensierinmusica** [expo/expo#537]
When trying to log `this` Expo seems to run in an infinite loop.

Any idea what is causing the problem?

For example:

```js
shouldComponentUpdate (nextProps) {
  console.log('this', this);
  return true;
}
```

**Comment by dikaiosune** [comment]
It probably depends on what component `this` refers to. Can you provide a repro via https://snack.expo/io? Thanks!

**Comment by pensierinmusica** [comment]
It always has the same problem, no matter the component. Try to create a brand new project and log `this` inside a component lifecycle hook.

**Comment by imrockerman** [comment]
I encounter this as well. Makes debugging my components quite frustrating

**Comment by ide** [comment]
We rewrote some of the logging code in SDK 23 and added unit tests for logging React components (still not recommended since there's a huge amount of content logged and it will slow things down, definitely don't do this in an animation loop): https://github.com/expo/expo-sdk/blob/master/src/logs/__tests__/LogSerialization-test.js#L76. When SDK 23 is released please give it another try.
