### ISSUE TITLE
expo-facebook: Facebook login only works on iPhone 6.

### ISSUE THREAD

**Issue by dusan-dragas-vivify** [expo/expo#5417]
Hello everyone!
I have a problem with facebook login on all iPhones except iPhone 6.
It does work as expected on all Android devices AND iPhone 6, but on all other iPhones it just redirects me back to the app login screen when I try to "continue login with Facebook app". However, everything is fine when I try facebook login by typing email and password, popularly known as "web" behaviour.
I would add that this issue is not constant, sometimes it works, sometimes not.
All iPhone devices including iPhone 6 that has no problems are on iOS version 12.*.

expo SDK version: 33.0.0
expo-facebook: 6.0.0

Any idea what can cause the problem?
Thanks in advance!

**Comment by cruzach** [comment]
Hey @dusan-dragas-vivify, could you provide a Snack or link a repo we can use to reproduce this? Does this happen in the Expo Client, or in standalone apps (or both)?

**Comment by OscarYuen** [comment]
I guess your issue is same as this one. Facebook login always return 'cancel' in the response after successful login. 
[https://github.com/expo/expo/issues/4701](https://github.com/expo/expo/issues/4701)

There is a temporary workaround to make 'native' type Facebook login work. You can use it to solve your issue shortly.

**Comment by cruzach** [comment]
closing as a duplicate, see 4701
