### ISSUE TITLE
Cannot disable android remotejs

### ISSUE THREAD

**Issue by stochris** [expo/expo#543]
We encountered a situation where, on android, builds done with exp CLI update the javascript code on already deployed .apk's.

Currently, we are using beta releases for testing android builds, and whenever we do a local build with the exp CLI the production ( on the play store ) apps start using the staging api's.

Is there any way to avoid this kind of behaviour ?

**Comment by dikaiosune** [comment]
Hi! I created a feature request for this: https://expo.canny.io/feature-requests/p/support-isremotejsenabled-on-android

**Comment by yangga** [comment]
Any progress?

**Comment by ide** [comment]
@yangga We'll post updates on the feature request link (https://expo.canny.io/feature-requests/p/support-isremotejsenabled-on-android). There is one workaround, though, using release channels (a feature in beta): https://docs.expo.io/versions/latest/guides/release-channels.html

With release channels, you could create your standalone app with a release channel called `prod-2017-12-30`, for example. Then if you published JS to any other release channel (or the default channel if you don't specify a channel), your standalone app would not get those updates.

We also do hope to provide a way to configure a standalone app not to check for updates at all, but currently Expo doesn't have that feature.

**Comment by yangga** [comment]
@ide thanks for you reply. I've using release channel features. 

Recently, i detached expo, cause i need using some libraries which expo doesn't support. (ex. react-native-fs, react-native-zip-archive ...)
Even i detached expo, it looks still use release channel features. (am i right?)

The problem is...after detaching, it's hard to set the 'release channel' on building. (I can't use exp build command anymore)

I found a topic below.
https://forums.expo.io/t/release-channels-on-detached-expokit-app/4902

It looks, i can handle release channel manually. But i'm not sure that do build perfectly without any mistake every time...

Is there any easy way to set release channel for detached project?
(or turning off fetching published js)

Thanks.

**Comment by ide** [comment]
Hi @yangga:

> Is there any easy way to set release channel for detached project?

The [forum post](https://forums.expo.io/t/release-channels-on-detached-expokit-app/4902/10) you linked to is the recommended way.

> (or turning off fetching published js)

We're hoping to offer this soon. SDK 26 will likely have a way to disable checking for updates.
