### ISSUE TITLE
[expo-tipsi-stripe] Migrate to clone of tipsi-stripe with unimodules integration

### ISSUE THREAD

**Issue by sjchmiela** [expo/expo#5628]
For us not to waste time on tedious process of upgrading `expo-tipsi-stripe` manually (and since our ultimate goal wasn't to provide a cross-platform implementation of Stripe payments, but rather adding Stripe integration to Expo projects) let's try to migrate `expo-tipsi-stripe` to `expo-branch`-like architecture.

`expo-branch` is a wrapper around `react-native-branch`, to which we copy real code from the upstream library, but using `@unimodules/core` infrastructure we are able to connect to `UIAppDelegate` callbacks etc.

This should fix/shift responsibility for `expo-tipsi-stripe` bugs to `tipsi-stripe` (we aren't able to maintain `expo-tipsi-stripe reliably 😞).

Resources:
- https://github.com/expo/expo/pull/5165
- https://github.com/expo/expo/tree/master/packages/expo-branch

Payments issues:
- https://github.com/expo/expo/issues/3714
- https://github.com/expo/expo/issues/5082
- https://github.com/expo/expo/issues/4849
- https://github.com/expo/expo/issues/3597
- https://github.com/expo/expo/issues/4499

**Comment by alaminopu** [comment]
Any progress on this? or is there any work around without detaching the app from expo?

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
