### ISSUE TITLE
Make Expo Push Notification servers more robust (502 Bad Gateway)

### ISSUE THREAD

**Issue by SleeplessByte** [expo/expo#564]
Pushing 3600 notifications, on 36 calls. First round 14 fail with a 502 Bad Gateway. Second round 11 fail. Worst one I had to retry 6 times before it got through. The 502 also doesn't give information about what went wrong, if it got queued or not. 

Is the expo push server at it's limit? Should there be a status page reporting this?

**Comment by ide** [comment]
It's possible your requests overloaded the servers, that's the most likely explanation.

**Comment by SleeplessByte** [comment]
I was doing 8 calls (of a 100 tokens) each 5 minutes. 

If this is too much, what algorithm should I be using? There are no mentions in the documentation; naturally I'd like not to overload the servers -- and I don't think this order of magnitude should.

**Comment by skevy** [comment]
For now @SleeplessByte the best thing to do is add backoff/retry logic in your application and just resend any pushes that fail.

It's on our roadmap to make this more robust.

**Comment by terribleben** [comment]
Hi, just renaming so we can track this more easily internally.

**Comment by js1599** [comment]
Any updates on this yet? I'm getting a 502 error as well every few calls to the notifications service

**Comment by ide** [comment]
We significantly reduced our database query load for an unrelated endpoint which may ease up on all endpoints that potentially query the database. We also restarted some internal networking configuration which was causing 502 errors in other areas. This probably won't clear out all of the 502s (some is likely related to push notification load) and we are incrementally improving reliability.

**Comment by owencm** [comment]
I'm still regularly seeing this, although I'm sure you have better view of the stats from your side 🐱 

For now I'm just catching the error and retrying once after a random period of 5-15 seconds, but FWIW it'd be nice to not need to worry about building some kind of queuing + backoff system on my end.

**Comment by ide** [comment]
Sorry about the reliability issues. Stability and reliability are two things we are actively working on improving. We are deploying a change to our push notification processing (just for iOS) that should fix (at least one causes of) 120-second long requests that result in 502 errors.

We recommend developers still have a queuing and backoff system because it means that Expo can offer a synchronous HTTP/2 API, in which you get delivery receipts (`ok` / `error`) in the HTTP response. Often this is much nicer to program with, in contrast with an API where you have to later ask for a notification's status. (As a data point, Apple's old push notification API was asynchronous and they moved to a synchronous HTTP/2 one as well.)

**Comment by ide** [comment]
A couple days ago we deployed an update to the servers that we believe fixed the main cause of the 502 errors. Please tell us if you see them again when sending push notifications. We also have end-to-end monitoring of push notifications as well and are alerted when they fail.

**Comment by ide** [comment]
According to our uptime monitor, push notifications has been one of the most reliable endpoints in the past month so I'm going to close this out. If you see issues with this again, please open a new issue, thanks.

**Comment by SleeplessByte** [comment]
Thanks!

We'll be back with 3k a day in the summer so I'll act accordingly if
necessary around then.
