### ISSUE TITLE
Expo client sdk 34, app stuck at “Building JavaScript bundle… 100%”

### ISSUE THREAD

**Issue by JorgeMoralesLopez** [expo/expo#5689]
I have updated expo from sdk 33 to sdk 34, in the console I don't see any errors, I have installed all the packages that I needed as expo install expo-font or linear-gradient but when I run expo start -c it does not happen Downloading Javascript Bundle 100.00%.
But when I open the Crome debugger I get this warning that in sdk 33 it was not:
Require cycle appears: node_modules/@unimodules/react-native-adapter/build/index.js -> node_modules/@unimodules/react-native-adapter/build/errors/UnavailabilityError.js -> node_modules / @ unimodules / react-native -adapter / build / index.js
I don't know if that will be the problem ...
Help please

**Comment by ide** [comment]
The require cycle likely is not causing the issue. I'd try to load the bundle directly in a browser (Expo CLI displays a project URL to the left, which is the JSON manifest URL, which has a field named "bundleUrl" that you can load). Other than that, I think you'll need to debug further since the root cause is hard to divine from this report.

**Comment by JorgeMoralesLopez** [comment]
Thanks, I could find the error and it was fixed. The fact is that _loadResourcesAsync to load fonts gave me an error and I passed it to componentDidMount ...
Now it's back in place and it works perfect
Thank you
