### ISSUE TITLE
Set initialization and logging to false by default for the Facebook SDK

### ISSUE THREAD

**Issue by ide** [expo/expo#5702]
- Make the Expo default more private and disable "auto-logging," since most apps don't need this default. See https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#add-events and https://developers.facebook.com/docs/app-events/getting-started-app-events-android/#disable-auto-events.
- Provide a method from JS to programmatically re-enable app-event logging for apps that want it. Developers can also control this on iOS via the `ios.plist` keypath in app.json. 
- I think it'd also be good to disable auto-initialization if that doesn't create technical issues. Auto-initialization is covered in the links above.

As a litmus test, when we open the Expo client or a standalone app, if it doesn't make any network requests to FB that'd be a good target.

**Comment by sjchmiela** [comment]
So far I was able to disable autoinit for FBSDKCoreKit,Login pretty easily, but FBAudienceNetwork keeps sending a registration request to Facebook and I can't yet see any setting for this.

<img width="1086" alt="Zrzut ekranu 2019-10-8 o 09 19 14" src="https://user-images.githubusercontent.com/1151041/66375054-b4e40580-e9ac-11e9-924b-1a6d4bede5e3.png">

**Comment by sjchmiela** [comment]
When excluding `expo-ads-facebook` from the build the request is not sent.

**Comment by sjchmiela** [comment]
Which is interesting, given that versioned ABIs do include `FBAudienceNetwork` nonetheless.

**Comment by sjchmiela** [comment]
Ok, it is probably due to https://github.com/expo/expo/blob/73c4d23244e24edfca24d7a60b6e86557cf7d85b/packages/expo-ads-facebook/ios/EXAdsFacebook/EXAdSettingsManager.m#L107 being executed when Home starts.

**Comment by ide** [comment]
It sounds like this issue involves multiple PRs:

- Turn off automatic initialization for FBSDKCore/Login. Re-enable it, if needed, when the developer starts using the Facebook SDK.
  - Do we need to add a new function like `Facebook.initializeAsync()` so that developers can initialize the native FB SDK without user-facing side effects (such as starting the login flow)? Is this useful?
  - Do developers need a way to turn this back on via Info.plist/AndroidManifest.xml so that they can initialize the Facebook SDK whenever their app launches?
- Turn off automatic event logging for FBSDKCore/Login. This is similar to turning off automatic initialization, but is a separate configuration field.
  - Is it useful to turn this back on ever?
  - Do developers need a way to turn this back on via Info.plist/AndroidManifest.xml so that they can log app events whenever their app launches?
- Turn off automatic initialization of the FBAudienceNetwork library until it is actually used.

**Comment by sjchmiela** [comment]
I will split https://github.com/expo/expo/pull/5924/ into 2 PRs, one with that small `FBAudienceNetwork` change and the other one with all the rest. Answers to questions below: 🙂 

### Turn off automatic initialization for FBSDKCore/Login. Re-enable it, if needed, when the developer starts using the Facebook SDK.

**Do we need to add a new function like Facebook.initializeAsync() so that developers can initialize the native FB SDK without user-facing side effects (such as starting the login flow)? Is this useful?** Yes, the SDK has to be initialized before calling the login method. Extracting initialization to a separate function lets developers ensure easily that the configuration is missing and not the login failed.

**Do developers need a way to turn this back on via Info.plist/AndroidManifest.xml so that they can initialize the Facebook SDK whenever their app launches?** Yes, if they want to log app events they want both Facebook SDK to autoinit and events enabled.

### Turn off automatic event logging for FBSDKCore/Login. This is similar to turning off automatic initialization, but is a separate configuration field.

**Is it useful to turn this back on ever?** Yes, if a developer wants to track app installs with Facebook, one would use this.

**Do developers need a way to turn this back on via Info.plist/AndroidManifest.xml so that they can log app events whenever their app launches?** Yes, enabling it back in runtime won't cut it — all the events before enabling are probably lost.

### Turn off automatic initialization of the FBAudienceNetwork library until it is actually used.

As easy as https://github.com/expo/expo/pull/5924/files#diff-6c7e805f98f089a84e76f46f3bcb22ee

**Comment by ide** [comment]
Because of the changes in initialization (you must call `Facebook.initializeAsync()` and you must tell app.json to modify Info.plist and AndroidManifest.xml if you want to automatically track app events), updating our docs is an important part of this task.

Also, reading your responses, it sounds like it is not useful to introduce a new method like `Facebook.enableAppEventLoggingAsync()` because a correctly written app would want to log events when it launches, so the correct way to log app events would be to enable auto-initialization 
+ auto-logging through Info.plist/AndroidManifest.xml. Does that sound correct?

**Comment by sjchmiela** [comment]
> Because of the changes in initialization (you must call Facebook.initializeAsync() and you must tell app.json to modify Info.plist and AndroidManifest.xml if you want to automatically track app events), updating our docs is an important part of this task.

Yes!

> Also, reading your responses, it sounds like it is not useful to introduce a new method like Facebook.enableAppEventLoggingAsync() because a correctly written app would want to log events when it launches, so the correct way to log app events would be to enable auto-initialization
& auto-logging through Info.plist/AndroidManifest.xml. Does that sound correct?

The most correct way to enable logging app events would be to configure it via `Info.plist`/`AndroidManifest.xml`, but I can imagine scenarios where one would need to first receive some consent from the user that the app can log events (GDPRish). Developer shouldn't enable logging app events in buildtime in such case, but in runtime with `setAppEventLoggingEnabledAsync` 🤔
