### ISSUE TITLE
Use Vibrator on android

### ISSUE THREAD

**Issue by miracle0930** [expo/expo#5798]
I was trying to use vibrator on Android and it seems that I need to have the VIBRATE permissions, but I cannot find such permissions in expo-permissions, I tried removing the "permissions" key from the app.json or making it like "permissions": ["VIBRATE"], but they did not work

**Comment by cruzach** [comment]
You should have the `VIBRATE` permission if you omit the `Android.permissions` key in your app.json (provided this is a managed Expo project). Make sure to take a look at the [Vibration docs](https://docs.expo.io/versions/latest/react-native/vibration/)

If this is a bug report, please follow the issue template. Otherwise, best to post/look around at our [forum](https://forums.expo.io/)
