### ISSUE TITLE
Apps sometimes crash (call stack at BaseExperienceActivity$2.run)

### ISSUE THREAD

**Issue by sweebee** [expo/expo#5839]
after the battery bug i released a new android app. But I still see some crashes:

SDK: 35

```
java.lang.RuntimeException: 
  at host.exp.exponent.experience.BaseExperienceActivity$2.run (BaseExperienceActivity.java:196)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7076)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```

Devices: 
Galaxy A50 (a50) android 9
Galaxy A40 (a40) android 9

**Comment by cruzach** [comment]
You might want to check out [this forum post](https://forums.expo.io/t/android-production-build-high-crash-rate/28444) which points to GCM as the cause of this crash

**Comment by sweebee** [comment]
I'm not using GCM. I'm using FCM.

**Comment by cruzach** [comment]
Okay, can you provide more information regarding this? We provide an issue template that asks for everything we need. Most helpful would be a repro

**Comment by linus** [comment]
We see this as well. See below:

## 🐛 Bug Report

### Environment

  Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.15
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /var/folders/tk/1c86q3t945j098jmhrnbzh7m0000gn/T/yarn--1570607473880-0.8337767224368917/node
      Yarn: 1.17.3 - /var/folders/tk/1c86q3t945j098jmhrnbzh7m0000gn/T/yarn--1570607473880-0.8337767224368917/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    IDEs:
      Xcode: 11.0/11A419c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.12.1 

We target Android and iOS. Bug appears on Android.

### Steps to Reproduce

Some users report crashes on app start. We see this in Google Play Console:

java.lang.RuntimeException: 
  at host.exp.exponent.experience.BaseExperienceActivity$2.run (BaseExperienceActivity.java:196)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6990)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)

### Expected Behavior

The app starts without crashing.

### Actual Behavior

The app crashes.

### Reproducible Demo

I cannot reproduce it on a device of my own, so it's going to be tricky I suppose?

**Comment by cruzach** [comment]
@linus are you seeing this on certain devices only? Does it happen with all SDK 35 builds, or is it after publishing a new bundle that causes the error?

**Comment by linus** [comment]
@cruzach tricky to say -- we see it in Google Play Console, for a bunch of Android versions and device makes. It started on upgrade to Expo SDK 35, but right now I can't say if it's tied to publishing new bundles. It's a minority of users that are affected.

**Comment by RodolfoGS** [comment]
I have the same crashes. Any solution? I'm using expo 35.0.1

![image](https://user-images.githubusercontent.com/870365/68881095-201ea700-06d2-11ea-80f0-8a1350b9f9c4.png)

**Comment by bulby97** [comment]
any updates ?

**Comment by rxhivzero** [comment]
at SDK 36 same

**Comment by cruzach** [comment]
No updates yet, what would really help us debug this is a method to reproduce the issue on a blank `expo` project

**Comment by Xrew** [comment]
Can this be the same issue or it is sth different? (SDK 36)
I realy don't know what to do..it doesn't work only in standalone APK. It works correctly in debug. 

`2019-12-20 16:56:22.269 3073-3118/? E/BufferQueueProducer: [xxxxx.xxx.xxx/host.exp.exponent.MainActivity[25602]#0] disconnect: not connected (req=1)
2019-12-20 16:56:25.347 25602-25602/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxxxx.xxx.xxx, PID: 25602
    java.lang.RuntimeException: Expo encountered a fatal error: Error while updating property 'onLayout' in shadow node of type: RCTView
        at host.exp.exponent.experience.a$b.run(BaseExperienceActivity.java:7)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
`

**Comment by cruzach** [comment]
@Xrew I suggest running your app locally in production mode with `expo start --no-dev --minify`, that may help you find out what is causing your app to crash

**Comment by Xrew** [comment]
@cruzach I tried it, but it works correcty :( so, there has to be some different in build standalone APKs..

**Comment by RodolfoGS** [comment]
same issue, SDK 36, any solution?

**Comment by cruzach** [comment]
@RodolfoGS check the above linked issue 6523, it looks like it points to `react-native-calendars` as the source

**Comment by RodolfoGS** [comment]
@cruzach I'm not using `react-native-calendars` nor any of my dependeces use it. I can't reproduce the crash, in my devices all works great, but I can see a lot of crashes in the Play Store Console. Any idea that what I can make to fix this? I have hundreds of crashes.

**Comment by cruzach** [comment]
I'm not sure, hard to say how to fix without knowing what's causing the crashes

Is it after a certain OTA update? Or is the binary you're shipping causing crashes without ever downloading a new javascript bundle?

**Comment by wen-kai** [comment]
Seems related to https://github.com/expo/expo/issues/6523

Same issue here -- upgraded 35 - > 36 and standalone android app continuously crashes with similar error as above. I'm not using `react-native-calendars` either. Initial load works and subsequent loads crash with the above errors. IOS works fine. Ended up having to downgrade to 35 for our android builds in the meantime unfortunately.

**Comment by RodolfoGS** [comment]
> I'm not sure, hard to say how to fix without knowing what's causing the crashes
> 
> Is it after a certain OTA update? Or is the binary you're shipping causing crashes without ever downloading a new javascript bundle?

I'm not sure, I pushed OTA updates, so I don't know if it happen specifically for OTA updates. I'm using expo ejected (with expokit). I have the issue since SDK 35, currently I'm in SDK 36 and the issue persist.

**Comment by felipefdl** [comment]
Same problem here on SDK 35 and SDK 36

![image](https://user-images.githubusercontent.com/3098271/71622038-feaa4980-2bb1-11ea-9ba6-51fd206d7a1c.png)
_(From google play crash screen)_

I don't know what I can do.

**Comment by LaszloDev** [comment]
> Same problem here on SDK 35 and SDK 36
> 
> ![image](https://user-images.githubusercontent.com/3098271/71622038-feaa4980-2bb1-11ea-9ba6-51fd206d7a1c.png)
> _(From google play crash screen)_
> 
> I don't know what I can do.

Same problem on a `Samsung Galaxy S9 (starlte), Android 9`

**Comment by robertcreaner** [comment]
Same issue here on two different standalone expo apps. 
- started happening last month 
- happening for both expo 35 & 36
- using latest expo-cli 3.11.3
- getting no error reports on sentry for both apps

I created an issue on the Expo forum about this last month but the issue was unresolved and closed. My app crash rate has gone from below 1% to 10% and I've been getting terrible review on the play store. I know it's hard to debug without being able to reproduce, but please look into this  if you have the time. Thanks. 
https://forums.expo.io/t/expo-sdk-35-android-standalone-app-crashing-on-start-up/30303

**Comment by cruzach** [comment]
I'm not sure yet if this is definitely the case, but comments on another very similar issue seem to indicate that disabling dark mode prevents the crashes https://github.com/expo/expo/issues/6523#issuecomment-571185329 might be worth a shot

**Comment by robertcreaner** [comment]
Unfortunately disabling dark mode does not fix the issue. I tried setting "userInterfaceStyle": "light" in the app.json and installing the react-native-appearance module but the app is still crashing. 

The crash rate on both of my apps has spiked dramatically within the last month. Both have been tested extensively in the expo client and work fine in production mode, which indicates that it's not an issue with my JS. 

Also can't reproduce the issue on a blank expo project because it only occurs on standalone builds

**Comment by LaszloDev** [comment]
> Unfortunately disabling dark mode does not fix the issue. I tried setting "userInterfaceStyle": "light" in the app.json and installing the react-native-appearance module but the app is still crashing.
> 
> 
> Also can't reproduce the issue on a blank expo project because it only occurs on standalone builds

I think he meant that you should disable dark mode on the android phone you trying to open the app with.
This solved the crashing issue for me.

**Comment by robertcreaner** [comment]
I cannot reproduce the crash on any of my android devices. It seems to only occur on certain devices. 
Also requesting my app users to disable dark mode on their android devices is not a viable option.

**Comment by robertcreaner** [comment]
I was able to get my hands on a Huawei device that was crashing as soon as I opened my app. I don't think it has anything to do with dark mode. As soon as I reset the app cache and storage the app started working fine. 

Is it possible that this crash might be related to over the air updates and/or release channels?

**Comment by wodin** [comment]
> Is it possible that this crash might be related to over the air updates and/or release channels?

@robertcreaner Yes, that is a definite possibility. I experienced that myself and was able to reproduce it. It happened when I was on a Wifi network with poor signal although that might not be required. Running `adb logcat` showed things like this (summarised):

```
12-26 21:58:33.473 10444 10444 E AndroidRuntime: FATAL EXCEPTION: main
12-26 21:58:33.473 10444 10444 E AndroidRuntime: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
12-26 21:58:35.786 10651 10651 E AndroidRuntime: FATAL EXCEPTION: main
12-26 21:58:35.786 10651 10651 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.example.myapp/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
12-26 21:58:35.786 10651 10651 E AndroidRuntime: Caused by: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
12-26 21:58:40.029 10781 10781 E AndroidRuntime: FATAL EXCEPTION: main
12-26 21:58:40.029 10781 10781 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.example.myapp/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
12-26 21:58:40.029 10781 10781 E AndroidRuntime: Caused by: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
12-26 21:58:44.934 10907 10907 E AndroidRuntime: FATAL EXCEPTION: main
12-26 21:58:44.934 10907 10907 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.example.myapp/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: com.facebook.react.devsupport.JSException: Unexpected end of script
12-26 21:58:44.934 10907 10907 E AndroidRuntime: Caused by: java.lang.RuntimeException: Expo encountered a fatal error: com.facebook.react.devsupport.JSException: Unexpected end of script
12-26 21:59:08.619 11153 11153 E AndroidRuntime: FATAL EXCEPTION: main
12-26 21:59:08.619 11153 11153 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.example.myapp/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
12-26 21:59:08.619 11153 11153 E AndroidRuntime: Caused by: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: RCTDeviceEventEmitter.emit()
```
The only thing that fixed it was clearing the app's data.

In order to reproduce it I did this:

Clear the data, then open and close the app quickly (1 to 3 seconds after app has loaded) until it either showed the latest bundle or crashed. If it showed the latest bundle I cleared the data again and continued trying. Did not take too many attempts.

@cruzach  advised as follows, but have not tried it yet:

> if you set `fallbackToCacheTimeout` to 0, you can use `Updates.addListener` to listen for when the update has fully finished downloading https://docs.expo.io/versions/latest/sdk/updates/#updatesaddlistenereventlistener
> 
> you can implement some logic around requiring the `DOWNLOAD_FINISHED`  event type
> 
> you can add a listener using `Updates.addListener`, which will then return this event type https://docs.expo.io/versions/latest/sdk/updates/#event
> 
> If you get a `DOWNLOAD_FINISHED` event, then you know the bundle has successfully downloaded, and is in your cache. Then, just call `Updates.reloadFromCache`
> you should turn off automatic updates before implementing that, though
> 
> Afaik, since you turned off automatic updates, it won't reload from a new bundle until you explicitly say to

**Comment by robertcreaner** [comment]
@wodin  I disabled OTA updates and published a new build to the Play Store hoping it would fix the issue but the app is still crashing. Prior to that I added implemented the proposed solution by @cruzach but no luck either :/

**Comment by wodin** [comment]
Are you also getting errors like the following?
```
12-26 21:58:40.029 10781 10781 E AndroidRuntime: FATAL EXCEPTION: main
12-26 21:58:40.029 10781 10781 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.example.myapp/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
12-26 21:58:40.029 10781 10781 E AndroidRuntime: Caused by: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
```
or:
```
11-30 09:26:45.507 18414 18414 E AndroidRuntime: FATAL EXCEPTION: main
11-30 09:26:45.507 18414 18414 E AndroidRuntime: Process: blah.my_app, PID: 18414
11-30 09:26:45.507 18414 18414 E AndroidRuntime: java.lang.RuntimeException: Expo encountered a fatal error: Unexpected end of script
```
I got that sort of thing before:
```
11-30 09:26:45.507 18414 18414 E AndroidRuntime: no stack
11-30 09:26:45.507 18414 18414 E AndroidRuntime: 	at host.exp.exponent.experience.a$2.run(BaseExperienceActivity.java:197)
11-30 09:26:45.507 18414 18414 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
[...]
```
This `BaseExperienceActivity$2.run` or `a$2.run` stuff is just where the exception gets thrown from, so it doesn't tell you much by itself:

```java
        // we don't ever want to show any Expo UI in a production standalone app
        // so hard crash in this case
        if (Constants.isStandaloneApp() && !isDebugModeEnabled()) {
          throw new RuntimeException("Expo encountered a fatal error: " + errorMessage.developerErrorMessage());
        }
```

Also, if the app has downloaded a bad bundle (I think this can only happen if the bundle download doesn't complete, e.g. because the user closed the app while it was being downloaded) then in theory it will fall back to the previous one or the one bundled in the APK, but when this happened to me it did not appear to do so and required the app's data to be cleared in order to get back to a working state. So in order for @cruzach's suggestion to help the app data might need to be cleared and then the new bundle successfully downloaded (or of course a new APK installed). When you say "but no luck", how did you verify that? I still haven't had a chance to test the suggested changes. If and when I do I'll let you know whether it seemed to fix the bad bundle issue for me.

It could be there's another issue causing a crash with the same stack trace, but a different error message. So I think we need to see what you're getting in `adb logcat` just before the stack trace. i.e. the "Expo encountered a fatal error:" error message. Then figure out where to go from there.

**Comment by robertcreaner** [comment]
@wodin here's the thing, I'm unable to reproduce the crash myself. I ended up having to downgrade my app from expo 36 -> 35 and the crashes have stopped so maybe that fixed it, or else expo fixed the issue and was pushed when I rebuilt the app.

**Comment by wodin** [comment]
@robertcreaner Are you able to get the "Expo encountered a fatal error:" error messages from these crashes? I suspect they are not all caused by the same thing.

SDK 36 introduced dark mode on Android, so if downgrading to SDK 35 fixed the crashes then I think there's a good chance they are as a result of the [dark mode issue](https://github.com/expo/expo/issues/6523). Unfortunately it does not look like there's a workaround or fix for this issue yet.

I have now had a chance to try @cruzach's suggestions for the crash caused by a truncated bundle after an OTA update and I am no longer able to reproduce that crash, unless I host the files on my own server and manually truncate the bundle. So it seems that it is a good workaround for the truncated bundle crash.

**Comment by RodolfoGS** [comment]
I have **489 crashes** in the last 7 days!
![image](https://user-images.githubusercontent.com/870365/72294339-ff63c680-361a-11ea-9e37-13f95bb36bb8.png)

This maybe can help, some errors have the follow error message:
java.lang.RuntimeException: **Expo encountered a fatal error: Unexpected end of script no stack**

![image](https://user-images.githubusercontent.com/870365/72294460-30dc9200-361b-11ea-8e08-995b415942e9.png)

Not always says that message, in the most cases I haven't a message. Ex:
![image](https://user-images.githubusercontent.com/870365/72294628-8ca71b00-361b-11ea-927a-d88e07fd9828.png)

Any suggestion?

**Comment by wodin** [comment]
> Unexpected end of script

This looks like an incomplete OTA update. I experienced that too and was also able to reproduce the problem by opening and closing the app several times while it was auto-downloading an update until I was able to catch it in the middle of a download.

I tried @cruzach's suggestions here:

https://github.com/expo/expo/issues/5839#issuecomment-572296759

After that I have not been able to reproduce the bug.

**Comment by RodolfoGS** [comment]
@wodin I'll try that, thanks!

**Comment by wodin** [comment]
I hope it helps. In my case it's just a single instance of the app. I do not yet have an app on the Play store. So I can't guarantee it will fix the problem, but it seems like it at least makes the problem less likely.

**Comment by liogate** [comment]
Crash ratios of the app:

![image](https://user-images.githubusercontent.com/17850842/72299696-e7fbfc00-3661-11ea-9501-74ecdb7f8f84.png)

I'm facing the same issue here with around 1k crash in the last 24 hours. I'm forced to downgrade on sdk 35 😢 Looks like a main thread issue on android devices ?

Hope you'll find a solution soon 🤞

**Comment by ide** [comment]
The first line of the log is the relevant part. The line that contains `host.exp.exponent.experience.BaseExperienceActivity$2.run(BaseExperienceActivity.java:206)` doesn't provide much information about the error since it's generic error-handling code:

https://github.com/expo/expo/blob/1d89094dade869a6506f4ff4d096283b6f874cda/android/expoview/src/main/java/host/exp/exponent/experience/BaseExperienceActivity.java#L206

I suspect that the root causes of several of the issues in this thread are unrelated. The stack trace is currently a red herring.

**Comment by liogate** [comment]
Totally agree. I've found this interesting article about this kind of situation.

https://blog.bam.tech/developer-news/debugging-a-non-reproducible-crash

Using a fully managed expo app (and I don't want to eject to keep it easy), I changed nothing from the sdk 35 and sdk 36 except dependencies versions, accordingly to the new expo requirements.

I'm trying this code, hope it work :
👉  https://github.com/testing-library/native-testing-library/issues/26#issuecomment-569335460

**Comment by wodin** [comment]
> Error while updating property 'fontSize' in shadow node of type: RCTText

@liogate I think you might be running into the [dark mode issue](https://github.com/expo/expo/issues/6523)

**Comment by dkulagin** [comment]
I have just encountered a similar type of crash on a freshly updated app running on SDK 36.

```
java.lang.RuntimeException: 
  at host.exp.exponent.experience.BaseExperienceActivity$2.run (BaseExperienceActivity.java:206)
  at android.os.Handler.handleCallback (Handler.java:874)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:198)
  at android.app.ActivityThread.main (ActivityThread.java:6729)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

**Comment by wodin** [comment]
Hi @dkulagin 

Unfortunately that stacktrace doesn't really tell you anything. You will need to get the error message just above the stacktrace in the `adb logcat` crash log. e.g.:

```
12-26 21:58:35.786 10651 10651 E AndroidRuntime: Caused by: java.lang.RuntimeException: Expo encountered a fatal error: Attempting to call JS function on a bad application bundle: AppRegistry.runApplication()
```
or
```
12-26 21:58:44.934 10907 10907 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.example.myapp/host.exp.exponent.MainActivity}: java.lang.RuntimeException: Expo encountered a fatal error: com.facebook.react.devsupport.JSException: Unexpected end of script
```

If you're getting errors like the above then try the workaround mentioned here:
https://github.com/expo/expo/issues/5839#issuecomment-572296759

If you're getting other error messages what are they?

**Comment by dean9703111** [comment]
I also have this issue:
```
java.lang.RuntimeException: 
  at host.exp.exponent.experience.a$b.run (BaseExperienceActivity.java:7)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:6986)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1445)
```
Only android device : Samsung Galaxy S9 (starlte), Android 9, Huawei P20 (HWEML), Android 9

My package.json
```
"dependencies": {
    "expo": "36.0.2",
    "expo-constants": "8.0.0",
    "expo-file-system": "8.0.0",
    "expo-image-picker": "8.0.1",
    "expo-keep-awake": "8.0.0",
    "expo-linear-gradient": "8.0.0",
    "expo-mail-composer": "8.0.0",
    "expo-media-library": "8.0.0",
    "expo-permissions": "8.0.0",
    "expo-sensors": "8.0.0",
    "humps": "2.0.1",
    "prop-types": "15.7.2",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
...
```
app.json not use userInterfaceStyle
```
{
  "expo": {
    "name": "...",
    "slug": "...",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
```
Does anyone have same issue?

**Comment by wodin** [comment]
@dean9703111 you will need to get the error message from just before the stack trace. The stack trace itself unfortunately doesn't tell you what the problem is.

e.g.:

```
Expo encountered a fatal error: <the error message is here>
<stack trace here>
```

If you post the error message we are more likely to be able to help.

**Comment by bogrees** [comment]
> > Unexpected end of script
> 
> This looks like an incomplete OTA update. I experienced that too and was also able to reproduce the problem by opening and closing the app several times while it was auto-downloading an update until I was able to catch it in the middle of a download.
> 
> I tried @cruzach's suggestions here:
> 
> [#5839 (comment)](https://github.com/expo/expo/issues/5839#issuecomment-572296759)
> 
> After that I have not been able to reproduce the bug.

@wodin, would you mind posting your complete fix?  I assume that you implemented it in App.js?  Thanks

**Comment by wodin** [comment]
I've put the code [here](https://gist.github.com/wodin/4b337348583fe66886fb743a4500be92)

Please let me know if you have improvements :)

I wanted to check for updates periodically. I originally tried using `setInterval()` but found out that's not a good idea when you're trying to do something every 6 hours.

The `tick`, `setTick()` stuff in my code is a workaround for that. So every time the user clicks on a button to navigate to another screen the app checks if enough time has passed since the last update check. If so, it updates `tick` which causes the `useEffect()` body to run again, which causes it to check for updates.

So this is all a bit convoluted and I'm sure there's a better way.

**Comment by bogrees** [comment]
@cruzach and @ide, is there a plan to include fixing this in an upcoming release of ExpoKit?  It seems to have been narrowed down to a problem with OTA updates being incomplete on Android and then getting into an unrecoverable state.  Thanks for looking into this.

**Comment by wodin** [comment]
Bear in mind that the title of this issue is very non-specific, so a truncated/corrupted bundle would be just one cause of this `BaseExperienceActivit$2.run` error.

That said, the Updates module is being extracted so that it can be used in the Bare workflow. I think it's supposed to be released with SDK 37 at the end of March.

I can find the issue or the pull request now, though :sweat_smile: 

If you find it perhaps you can try it out and test how it behaves if you deliberately truncate the bundle. I was able to reproduce the crashes in a managed app like this:

```
$ expo export --public-url https://example.com/blah/
$ rsync -avxz --progress --delete --stats dist/ example.com:/blah/
$ rm -r dist
$ expo ba --public-url https://example.com/blah/android-index.json
$ expo export --public-url https://example.com/blah/
[Manually truncate dist/bundles/android-*.js] 
$ rsync -avxz --progress --delete --stats dist/ example.com:/blah/
```

**Comment by bogrees** [comment]
Just an update from my side, I decided to finally throw in the towel on ExpoKit --- this error was the last straw, unfortunately.

I spent the last two days removing ExpoKit from the app, and I now have it successfully working on both iOS and Android.  The Android project was a nightmare to get working, but overall, it simplified a **_TON_** of code --- and I can still use most of the Expo libraries that I was previously using (sweet!).

I'll be moving to CodePush for the OTA update functionality. ¯\_(ツ)_/¯

**Comment by ektasahu027** [comment]
I also have this issue:

![Screenshot 1398-12-21 at 14 58 56](https://user-images.githubusercontent.com/41745899/76499124-2a746600-6464-11ea-9184-bf52d118bd16.png)

` "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",`

app.json 

`{
  "expo": {
    "name": "...",
    "slug": "...",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],`

**Comment by tindery** [comment]
I've had this issue for a while now and cases really spiked after upgrading to SDK 36 (sometimes up to 200+ a day). Two days ago, I uploaded a version, where I increased "fallbackToCacheTimeout" from 1000 to 5000 and since then I've had only one instance of this error. I'm not really sure if that's the reason, but I didn't change anything else that could be related to this.

**Comment by gasolin** [comment]
@tindery according to https://docs.expo.io/versions/latest/workflow/configuration/#updates the default is `30000` (30s) which is still 6x larger than you config. Or do you mean 50s instead of 5s?

**Comment by RodolfoGS** [comment]
Maybe the timeout of **fallbackToCacheTimeout** is breaking the bundle 🤔
I have that in 30000

**Comment by tindery** [comment]
I only had it set to 1 second for a long time, and there wasn't a single problem with it until SDK 34/35 I think. I'm not sure why that was, but It might have been done before we were handling cases without internet connection and it took too long to load the app. I'm not saying increasing to 5 seconds fixed the issue, but those errors almost stopped, and I don't have any other explanation for it 😄 
Maybe just something to try or look into?

**Comment by ManigandanRaamanathan** [comment]
Guys how to downgrade to SDK 35?

**Comment by wodin** [comment]
@ManigandanRaamanathan it would probably be a good idea to figure out what is causing your crashes, but if you are sure you want to downgrade, make sure everything is committed to Git so you don't lose any changes. Then with a recent version of `expo-cli` installed, run:

```
expo upgrade 35.0.0
```

There might be dependencies you need to downgrade manually after that, to versions that are compatible with SDK 35.

**Comment by feliperaul** [comment]
We're also having this issue unfortunately.

![image](https://user-images.githubusercontent.com/743879/85768617-987d2a00-b6ef-11ea-9210-67568ded4bf3.png)

The last update on this issue was on March 28, and it's still open. Does the Expo team know what is causing this already?

**Comment by ide** [comment]
This stack trace is coming from a generic handler. Many different errors could be causing this; there is not necessarily one cause.

The best way to help out is to figure out how to attribute the error to the actual place it was caused so that the stack trace is accurate instead of pointing to this error handler.

**Comment by feliperaul** [comment]
@ide Unfortunately that's all we have. Customers are sending printscreens of the app crashing on open. The only thing we have available is the "send feedback" button on Android, which sends it to our Google Apps Console, and that's all we get there, nothing more :(

Plese tell me if there's anything else I can do to help you guys debug this.

**Comment by rphlmr** [comment]
Same problem here on some devices (same stack https://github.com/expo/expo/issues/5839#issuecomment-649716057)
Trying to disable OTA. We'll see  ¯\ (ツ) /¯

**Comment by sheshashayan** [comment]
Facing same issue. Having worked on 4-5 cross platforms I recommend not to use Expo. Umpteen endless issues.

**Comment by sheshashayan** [comment]
Facing same issue. Having worked on 4-5 cross platforms I recommend not to use Expo. Umpteen endless issues.

**Comment by sheshashayan** [comment]
My app come to a last stage.... keeping it haulted because of this issue...

**Comment by amorimlucas** [comment]
Getting this same issue only on some android phone models.

**Comment by satyamdorville** [comment]
Any news ?

**Comment by isotopeee** [comment]
Any updates?
