### ISSUE TITLE
Disable live reload through expo-cli

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#584]
In order for [Detox](https://github.com/wix/detox) to work on an app in development, we need to be able to start the app with live reload disabled, otherwise it hangs with this:

<img width="708" alt="screen shot 2017-09-02 at 11 55 41 am" src="https://user-images.githubusercontent.com/90494/29998022-a96ce24a-8fd5-11e7-9b51-bdbce181af05.png">

Would be good to expose this on Android too but Detox is currently only stable on iOS at the moment.

**Comment by terribleben** [comment]
Brent figured out we don't need this for Detox, but it still seems like a good feature to have, so leaving the issue open.

**Comment by crearc** [comment]
This is actually something that would be very helpful to add for Detox purposes because I have not been able to get Detox to work due to live reload polling. Blacklisting does not seem to be properly working within the detox-helpers library either (at least right now, it may have for y'all in the past).

**Comment by pkozhin** [comment]
Hi, would be great to have some additional options for exp start CLI to disable live reload. Without disabling it manually each time I get timeout error with Detox (tried v8 and v9).

**Comment by donnes** [comment]
I have trying to use Detox with iOS and it's only works when live reload is disabled.
I'm at latest version of Expo SDK and Detox. I'll provide a demo project and maybe record a video demonstrating the issue.

**Comment by donnes** [comment]
Hi guys, sorry about the delay to provide the demo.
Follow a demo video with the issue:
https://www.dropbox.com/s/msr3bcoy3vb8kz5/Sem%20T%C3%ADtulo.mov?dl=0

You can see on video that I need to disable the live reload to start the test.

**Comment by yutamgit** [comment]
@donnes What happens if you build your app for the simulator and run detox with that? My detox tests run with Expo only passed when I disabled live reload, but when I tried running detox with a standalone build for the simulator, all my tests passed. 

1) Build for the simulator.

`expo build:ios -t simulator`

2) Copy the build over to where you have your binary.

3) Update package.json
  
 ```
"detox": {
    "configurations": {
      "ios.sim": {
        "binaryPath": "bin/app-name.app",
        "type": "ios.simulator",
        "name": "iPhone 8"
      }
    },
    "test-runner": "mocha"
  }
```

4) Remove the `reloadApp` calls in your detox tests.

**Comment by pwfcurry** [comment]
@brentvatne I think https://github.com/wix/Detox/pull/1000 fixes your problem (although does not disable the reload functionality).

**Comment by FiberJW** [comment]
Hi, we're closing inactive issues that apply to SDK versions we no longer support. I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
