### ISSUE TITLE
Notification Listener doesn't fire with foregrounded iOS notifications

### ISSUE THREAD

**Issue by AdamJNavarro** [expo/expo#5842]
Adding `_displayInForeground` to notifications results in the Notification displaying but `Notifications.addEventListener` does not fire. We the listener to fire so that users are able to update badge count and any other in-app information they desire. Initially raised here: https://forums.expo.io/t/received-notifications-when-iosdisplayinforeground-true/28385

**Comment by xcarpentier** [comment]
Hi @AdamJNavarro,
I had the same issue but `displayInForeground` option not enabled.
- SDK Version: 35
- Platforms(Android/iOS/web/all): iOS v13.1
Thanks

**Comment by salutrubs** [comment]
I got the same issue ! Any idea when the issue will be solved ?

**Comment by joshg2k** [comment]
Commenting to show my support for this issue.

**Comment by xcarpentier** [comment]
any news?

**Comment by NotifydLLC** [comment]
Bumping this to show my continued support for this issue.

**Comment by joshg2k** [comment]
Bumping this to show my continued support.

**Comment by YahiaBadr** [comment]
any updates?

**Comment by birdca** [comment]
any updates? or is there any workaround solutions for now?

**Comment by cruzach** [comment]
Hi everyone- glad to say this is fixed in SDK 38 with the new `expo-notifications` module 🎉 [here's the relevant documentation](https://docs.expo.io/versions/latest/sdk/notifications/).

You can now configure your notification handling with `Notifications.setNotificationHandler`, this particular behavior is controlled via `shouldShowAlert`

I should note that you can still pass `_displayInForeground` in your notification objects. If you set:
```
Notifications.setNotificationHandler({
  handleNotification: async () => ({
    shouldShowAlert: false,
  }),
});
```
but send a notification with `"_displayInForeground": "true"`, then the notification **will** show the alert when the app is foregrounded. 

However, if `shouldShowAlert` is set to `true`, then that will override a `"_displayInForeground": "false"` notification setting.

Once again- this is fixed in SDK 38, and after upgrading you'll need to follow the [`expo-notifications` documentation](https://docs.expo.io/versions/latest/sdk/notifications) for the set up
