### ISSUE TITLE
Expo OTA not working after published in play store

### ISSUE THREAD

**Issue by stageover** [expo/expo#5852]
Hey Expo team! Our company is having issues with OTA. We have detached expo, our app is deployed on app store and play store, but the app won't refresh after publish. We have "fallbackToCacheTimeout": 0 set in app.json. Were expecting that after we publish it would reflect in all users app who already installed it and also will see the updates after they download it in play store.

we already check the app.json
we also publish it in same channel and sdk version 33

Thanks in advance Expo Team :)

**Comment by OscarYuen** [comment]
You need to kill the app and re-open it at least one time to see the change.
And the first download user would not see the change and only see the version at the time you bundle the apk.

**Comment by cruzach** [comment]
@stageover have users already killed/reopened the app? Since `updates.fallbackToCacheTimeout: 0`, the app will start with its cached bundle, and download the new published bundle in the background.

Also, updates won't be downloaded if the binary is on a different SDK version from the bundle (in your case, anything other than SDK 33)

**Comment by AdamJNavarro** [comment]
Hey @stageover,

I'm going to close this issue as we haven't heard back from you. I'm hoping you got things sorted out, but if you did not, please create a topic on our [forums](https://forums.expo.io/) and we can do our best to get to the bottom of things.

Cheers,
Adam
