### ISSUE TITLE
Permissions askAsync and getAsync returns undefined after permission was granted

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/expo#5853]
### Environment

 Expo CLI 3.1.2 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.2.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.1.2

IOS, Android, ExpoKit

### Steps to Reproduce

askPermissionNotification = async () => {
        let { status } = await Permissions.askAsync(Permissions.NOTIFICATIONS);
        if (status === 'granted') {
            this.setState({ notificationAllowed: true })
        }
        let { notificationStatus  } = await Permissions.getAsync(Permissions.NOTIFICATIONS);
        if (notificationStatus === 'granted') {
            this.setState({ notificationAllowed: true })
        }
    }

### Expected Behavior

I will get status granted once user allowed notification

### Actual Behavior

I get always status undefined

**Comment by lukmccall** [comment]
Hi @Luckygirlllll, please check out this comment https://github.com/expo/expo/pull/3510#issuecomment-516036592.
There is walkaround to your problem. Currently, we work on two module rework - permissions and notifications module. In the further, we will fix it. Unfortunately, for now, we suggest using a walkaround. 

I'm closing this issue because it is duplication of https://github.com/expo/expo/issues/5093.
