### ISSUE TITLE
Icons appear as `?` in SDK 35 in Expo Snack

### ISSUE THREAD

**Issue by Derewith** [expo/expo#5885]
## 🐛 Bug Report
Hey all, i am trying to get Icons works but they don't work.

### Environment
Expo Snack https://snack.expo.io/@derewith/sdk35-icons-bug

### Steps to Reproduce
`import { FontAwesome } from '@expo/vector-icons';
<FontAwesome name="angle-right" size={24} />`

### Expected Behavior
Render the icon.

### Actual Behavior
Render a `?`.

### Reproducible Demo
Expo Snack https://snack.expo.io/@derewith/sdk35-icons-bug

**Comment by pzatorski** [comment]
Hey @Derewith Thanks for reporting this issue. I have tested it on my project locally and everything works fine.
The problem is with the `'@expo/vector-icons'` library version. Expo Snack is using the `8.1.0` version. That's why the icons are not working. If you have same issue in your project I recommend to upgrade this package with `expo install @expo/vector-icons` command to `10.0.0` version.

Thanks! Let me know if this helps.

**Comment by Derewith** [comment]
Thanks @pzatorski . Locally everything works fine. So I think the bug should be closed when Snack will be updated. 

Thanks again ! 🎉

**Comment by FiberJW** [comment]
Hello, I wasn't able to reproduce this just now on SDK 35. Please create a new issue with a full repro case if this still happens in any of the currently supported SDK versions.
