### ISSUE TITLE
First time user get old version of app.

### ISSUE THREAD

**Issue by nsisodiya** [expo/expo#591]
I uploaded the mobile app using expo. I released it on PlayStore. The first released.
Since Expo handle update process, we need not upload a new apk file again and again.
Users just need to restart the app.
My our app, we were having a modification and we published its new version today. Now, this is happening.
1. User who go to play store and install the app get older version when he/she clicks on `Open`.
But If she/he restart the app, he gets the new version.
This is not at all a good user experience. 

If I publish a new version of my mobile app, then anybody who downloads it from PlayStore should get new version instead of getting old version loaded the first time.

**Comment by dikaiosune** [comment]
Hi! This was changed in SDK 20: https://docs.expo.io/versions/latest/guides/publishing.html#deploying-to-the-app-store-and-play-store

> Updates are handled differently on iOS and Android. On Android, updates are downloaded in the background. This means that the first time a user opens your app after an update they will get the old version while the new version is downloaded in the background. The second time they open the app they’ll get the new version. On iOS, updates are downloaded synchronously, so users will get the new version the first time they open your app after an update.

You can listen for background updates with a [utilty function](https://docs.expo.io/versions/latest/sdk/util.html#expoutiladdnewversionlistenerexperimentallistener), and prompt the user to reload (or call `Util.reload()` yourself if you want).

We made this change due to long download times being a poor user experience for most use cases -- in the near future this behavior will be configurable in your app.json.
