### ISSUE TITLE
Prevent video download with native controls

### ISSUE THREAD

**Issue by alexbelletti** [expo/expo#5941]
### Please note that feature requests opened in the core Expo repository will be closed.
Is it possibile to implement something like controlsList="nodownload" of HTML5 videos for native video players? I need to stream a mp4 file video with native controls in fullscreen, but I need to prevent the download. Any other suggestions are appreciated.

**Comment by cruzach** [comment]
You can set `downloadFirst` to `false` on the [playback object](https://docs.expo.io/versions/latest/sdk/av/#playback-api), but I don't think that would completely solve what you're looking for. How might try asking on [our forums](https://forums.expo.io/) to see if someone has found a workaround for this already!

Closing this since we keep Github reserved for bug reports
