### ISSUE TITLE
Fix Detox iOS tests for CI

### ISSUE THREAD

**Issue by ide** [expo/expo#5984]
The Detox tests are failing because the server never receives `isReady` after upgrading to RN 0.61. Rather than a timeout due to Earl Grey, it looks like there perhaps is an error on the client.

**Comment by EvanBacon** [comment]
https://github.com/wix/Detox/pull/1713

**Comment by LeoNatan** [comment]
Hello,
Just to explain. Detox should support RN61 already. The issue is with how RN is integrated in the user project, which in Detox' case is the internal test project.

Do you see `isReady` not being sent in a clean RN project (without expo)? If so, please open an issue on the Detox tracker.
Otherwise, that PR is for bureaucracy purposes only.

**Comment by EvanBacon** [comment]
The project we use Detox in (bare-expo) is a standard React Native project.

**Comment by kopax** [comment]
> Hello,
> Just to explain. Detox should support RN61 already. The issue is with how RN is integrated in the user project, which in Detox' case is the internal test project.
> 
> Do you see `isReady` not being sent in a clean RN project (without expo)? If so, please open an issue on the Detox tracker.
> Otherwise, that PR is for bureaucracy purposes only.

Hi. I have an app that I am thinking doing in react native and web with the same code base. It's imminent, do you think I should go with expo and if I do, will it be possible to upgrade to RN 0.61 without hassle ? I am also thinking of not using expo. I have no clue it is my first native web project  and I want to target ios android and web. Any opinion and feedback is appreciated.

Best and thanks for sharing !
