### ISSUE TITLE
Firebase Crashlytics

### ISSUE THREAD

**Issue by chayancbnits** [expo/expo#6015]
how to integrate about firebase Crashlytics for android and ios. I am using Expo SDK 35 and expo-cli version 3.4.0.

**Comment by cruzach** [comment]
In the managed workflow, you can implement the [firebase JS SDK](https://github.com/firebase/firebase-js-sdk).

You'll have to go with the bare workflow in order to implement any native Firebase tools. The firebase SDK fully expects that there is one binary per app, and the Expo client has multiple apps inside of it

**Comment by chayancbnits** [comment]
So it means that I can not use the Crashlytics features in my managed workflow setup, would I need to switch to bare workflow? Can I use previous features that were handled by managed workflow?

**Comment by cruzach** [comment]
You would need to switch to the bare workflow to use any outside native module, and at the moment that does mean missing out on just a few features (we hope to minimize that even more over the next few SDK releases)

[This page](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/) of our docs will probably help you make the right decision 👍

**Comment by tattivitorino** [comment]
Hi there, I see the issue is closed but I'll try anyway.. I've seen a few things about implementing Crashlytics with Expo and we need to eject.. thats fine but some say it needs to be ejected to Expokit! is it true? I saw on Expo Docs that ejecting to Expokit is not recommended! In order to make Crashlytics work what's the best way, Expokit or Bare?
Thanks!!

**Comment by cruzach** [comment]
Where diid it say it needs to be ejected to Expokit and not bare? You should be able to do anything you can do in a regular react native project in a bare Expo project (bare stands for "bare react native")

**Comment by cbm-rmezzi** [comment]
does sentry offer the same fonctionnality for cash analytics as firebase ?
