### ISSUE TITLE
Picker (input) styles on web

### ISSUE THREAD

**Issue by vjsingh** [expo/expo#6060]
I'm trying to add 'fontFamily' and 'textIndent' styled to the <input> that's generated when using the react-native Picker component.

These properties are not supported by the PickerStyle defined in react-native, so I get an error in the console:

```
Warning: Failed prop type: Invalid props.style key `fontFamily` supplied to `Picker`.
Bad object: {
  "height": 56,
  "backgroundColor": "white",
  "fontFamily": "proxima-nova",
  "textIndent": 7
}
```

Ideally there would be support for these things somehow, but in the meantime Is there a way around this so I don't keep getting the error?

**Comment by cruzach** [comment]
This doesn't look like a bug with the Expo SDK, so I'm going to close this issue. If you're looking for some general help, I suggest posting on our [how-to forums section](https://forums.expo.io/c/how-to). 

Otherwise I suggest searching around on Github and Stack Overflow, since I'm sure changing the font styling of the Picker component is a pretty common question

**Comment by vjsingh** [comment]
@cruzach That's absolutely right, sorry about that. I guess I was confused about the border between RNW and expo-web but this is definitely a RNW thing.

For anyone who finds this I think the answer is to override the default for `<select>`s globally, by injecting css
https://github.com/necolas/react-native-web/issues/1342
