### ISSUE TITLE
Performance monitor unreadable when dark mode is enabled

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#6108]
# Dark mode

<img width="483" alt="Screen Shot 2019-10-28 at 18 03 22" src="https://user-images.githubusercontent.com/90494/67729232-848cf700-f9ad-11e9-9c20-1afc20a85bb9.png">

# Light mode

<img width="483" alt="Screen Shot 2019-10-28 at 18 05 15" src="https://user-images.githubusercontent.com/90494/67729252-98385d80-f9ad-11e9-8426-9810ceb25784.png">

**Comment by IjzerenHein** [comment]
FYI, this has been fixed in upstream RN v0.62.1
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#v0621

Will be fixed automatically when the next SDK uses 0.62.1 or higher

**Comment by IjzerenHein** [comment]
Verified that this has been fixed in Expo client for SDK 38.

When dark mode is enabled:

![image](https://user-images.githubusercontent.com/6184593/87402252-95bd7880-c5bb-11ea-8b4d-f2dce7936e8e.png)


And in light mode:

![image](https://user-images.githubusercontent.com/6184593/87402274-9c4bf000-c5bb-11ea-9ff0-ee7c1b4c5930.png)

Closing this issue.
