### ISSUE TITLE
It is possible to change the keyboard language?

### ISSUE THREAD

**Issue by Alekano** [expo/expo#6145]
It is possible to change the keyboard language, ignoring the phone settings ?

**Comment by cruzach** [comment]
The best place to look for this is probably RN's [textinput docs](https://facebook.github.io/react-native/docs/textinput). Although, I don't think it's possible to override the user's setting

Closing this since we keep Github reserved for bug reports. Questions like this are better off posted on the [Expo forums](https://forums.expo.io/)
