### ISSUE TITLE
Modals open over expo menu. 

### ISSUE THREAD

**Issue by brunoreis** [expo/expo#615]
Hi, modals are opening over the expo menu. So, when I get stuck I'm not able to reload and I need to reboot the device. 

I'm talking about default modals, loaded with: 
```
import { Modal } from 'react-native'
```

**Comment by ide** [comment]
This is probably because react-native's Modal component sets up a new UIViewController that covers everything. This is one of the reasons we recommend using react-navigation and pushing a modal screen on top. Also just to be clear - you shouldn't need to reboot the device, just force quit the app and reopen it (though that is still inconvenient, I understand).

**Comment by dikaiosune** [comment]
@ide is this a limitation we expect to ever be able to overcome? If not it seems like we should cover this in our documentation and close this.

**Comment by terribleben** [comment]
Assigning some people so we can decide what to do here.

**Comment by terribleben** [comment]
Pending in our next minor release

**Comment by terribleben** [comment]
Fix released today, give it a try and let us know if you're still seeing issues.

**Comment by Roman-Jordan** [comment]
The issue still persists. I have found after rebuild, while app is open on android, if you pull down your phones top menu and hit the refresh button, it forces modal to reset. Making sure the modal is closed before every save is how I got around this; 
Expo CLI 2.18.0

**Comment by tvillafane** [comment]
Still seeing this.
