### ISSUE TITLE
`expo-yarn-workspaces` bare install doesn't compile external packages with JSX.

### ISSUE THREAD

**Issue by sartaj** [expo/expo#6157]
### Environment

```
  Expo CLI 3.4.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/n/bin/node
      Yarn: 1.19.1 - ~/n/bin/yarn
      npm: 6.9.0 - ~/n/bin/npm
      Watchman: 4.9.0 - /Users/sartaj/.brew/bin/watchman
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.4.1
```
attempting `expo start --web --clear`

### Steps to Reproduce

- Create fresh yarn workspaces package.json
- Install fresh `expo-cli`
- Initialize new Expo bare project as workspace package (i.e. under `packages` directory)
Follow [`expo-yarn-workspaces`](https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces) instructions, modifying `package.json`, adding `metro.config.js`, and modifying `app.json`.
- Create package new in workspace that requires `react-native`.
- Export `index.js` with bare bones React component with jsx.
- Have bare Expo project require this new module.
- Rerun yarn to have everything link together.
- Run bare project (`expo start --web --clear`)
- Expo fails can't read JSX.

### Expected Behavior

Expo should be able to compile files in other packages that have JSX.

### Actual Behavior
```
Module parse failed: Unexpected token (5:30)
You may need an appropriate loader to handle this file type.
| import * as R from 'ramda'
> export const TestView = () => <Text>Hello: {R.add(5,7).toString()}</Text>
```

### Reproducible Demo

- `git clone https://github.com/sartaj/expo-yarn-workspaces-blank.git`
- run `yarn` in the root
- run `yarn start --web --clear` inside of `packages/test-react-native`

**Comment by ItsRhen** [comment]
I, too am having this issue after converting a project. Spent several hours trying different solutions. A fix or help fixing would be much appreciated.

**Comment by ItsRhen** [comment]
@sartaj in case you're still having this issue, I solved mine last night. There's a special config that expo relies on for compilation that, when overridden, can just get weird. After a loooong time fighting with it, I finally stumbled upon this thread: https://github.com/hectahertz/react-native-typography/pull/31

Eventually, all I needed to do was add this to the app.json so that the expo config would include my shared packages in the build:
`"web": {
      "build": {
        "babel": {
          "include": [
            "name_of_my_shared_package_here"
          ]
        }
      }
    }`

Then it fired right up. Hope it helps you or someone else. :)

**Comment by cruzach** [comment]
Thanks for finding the fix @ItsRhen ! Seems liek this might be better placed in docs for web than for yarn workspaces?

**Comment by EvanBacon** [comment]
I will be deprecating the `app.json` approach in favor of a more stable JS solution. Here are the docs regarding the new method [webpack-config: include modules](https://github.com/expo/expo-cli/tree/master/packages/webpack-config#include-modules). This method is better because the Webpack config is versioned, strongly typed, and updates more often with bug fixes.
