### ISSUE TITLE
Does expo-google-sign-in need to be configured with Firebase?

### ISSUE THREAD

**Issue by crofoot** [expo/expo#6159]
In Expo 32, we could configure our applications keys through the Google developer console. But now in SDK 35 it says to configure it through the Firebase dev console for expo-google-sign-in. So I am just wondering if this is the only way to configure it now?

**Comment by cruzach** [comment]
I think you might be thinking of [`expo-google-app-auth`](https://docs.expo.io/versions/latest/sdk/google/), since the [first version of the google-sign-in docs](https://github.com/expo/expo/commit/2215303a9a82328d73bdac7969887e3fe1f623cb#diff-dc49eea196145fbe71bc9929e42c6c7c) only mentions Firebase
