### ISSUE TITLE
IPA file submit error

### ISSUE THREAD

**Issue by caesar-c4** [expo/expo#6247]
![photo_2019-11-12_19-51-31](https://user-images.githubusercontent.com/38320075/68677219-e5a7f380-0585-11ea-9505-b05314a126ae.jpg)
After creating an IPA file, while I try to upload it to Apple store I get this error. What could be the possible reason? Am I making a mistake somewhere? I edited the code in VS Code on a PC. Borrowed a MacBook to upload the IPA FIle.

**Comment by cruzach** [comment]
What version of xcode are you using? Seems from a quick search this might be due to you using an older version. It's best to do a quick search for any error message you get, as there are a few threads already on this topic

I'd take a look [here](https://github.com/expo/expo-cli/issues/195) and [here](https://forums.expo.io/t/what-version-of-xcode-is-expo-using-when-building-ios-apps/15627/15) for more info. 

Closing as this doesn't look to be a bug with the Expo SDK
