### ISSUE TITLE
Image picker issues on Android

### ISSUE THREAD

**Issue by divyakoshy** [expo/expo#627]
ImagePicker.launchImageLibraryAsync() and ImagePicker.launchCameraAsync() do not seem to work on Android standalone apps. The permissions are requested correctly, but the async calls never return and the view for taking/picking photos never appears.
Permissions have been put into the app.json, and on iOS things are working correctly. Not sure what I am missing D:

**Comment by dikaiosune** [comment]
Hi! Can you provide an example of your code where this is happening? Maybe using [Snack](https://snack.expo.io)? Thanks!

**Comment by akazimir** [comment]
Same problem (two samsung different model, one launch, one not)
[https://snack.expo.io/HJ2aKjTcW](url)

**Comment by terribleben** [comment]
@aalices is this something you're familiar with? Not sure

**Comment by ledfusion** [comment]
I'm having the same issue. 

On Android, `ImagePicker.launchCameraAsync` will work in development but will fail with the compiled standalone APK.

The error I get is that the user rejected the permissions (I accepted them), and the data object contains:

```
{
   framesToPop: 0,
   code: "EUNSPECIFIED"
}
```

The same works fine on iPhone

**Comment by aalices** [comment]
@divyakoshy @akazimir @ledfusion I tested this on Xiaomi 4a, Nexus 5 and Samsung Galaxy Tab S2 and everything's fine. What devices are you using ?

**Comment by ledfusion** [comment]
Hi @aalices,
I'm using Huawei P8 lite (Android 7.0) and BQ Aquaris X5 (Android 7.1.1)
Thank you

**Comment by akazimir** [comment]
@aalices, Xiaomi Redmi 4 Prime (android 6.0.1), but I have no error in try-catch, just nothing happens and promise awaits result, permission in console.log - Object {expires: "never", status: "granted"}

**Comment by ledfusion** [comment]
Switching to the Expo's camera component, and the problem is gone:
https://docs.expo.io/versions/latest/sdk/camera.html

**Comment by divyakoshy** [comment]
Apologies for the delay in responding. I was able to fix this issue by removing all Permissions for android in app.json.

**Comment by dikaiosune** [comment]
@akazimir looks like the other reporters resolved this by using the Camera component or by changing their permissions in app.json. Can you double check that you haven't removed the necessary permissions in app.json?

Since the original report has been resolved, going to give this a close. If it's still an issue and we have a reproduction, I'll happily reopen. Thanks!

**Comment by rintoj** [comment]
@dikaiosune, I still see the same issue. I have the following permissions in app.json. Am I missing something here?

```json
{
   "android": {
      "permissions": [
        "CAMERA",
        "READ_INTERNAL_STORAGE",
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE"
      ]
    }
}
```

**Comment by aalices** [comment]
@rintoj a new type of permission that you will be able to use via `Permissions` module will be probably available along with SDK 23 and you'll have to use it before opening the picker.

**Comment by budiadiono** [comment]
I have same issue.

This one was working fine:
```javascript
  /**
   * Get picture from camera
   */
  async _takePicture() {
    const result = await ImagePicker.launchCameraAsync()
    if (!result.cancelled) {
      await this._setImage(result.uri)
    }
  }
```

But NOT for this one:
```javascript
  /**
   * Select picture from image library
   */
  async _selectPicture() {
    const result = await ImagePicker.launchImageLibraryAsync()
    if (!result.cancelled) {
      await this._setImage(result.uri)
    }
  }
```
Nothing happens after image get selected -- I don't see any exception been thrown. I've tested on Android only using Xiaomi Redmi 2 Prime -- not sure about IOS.

I've made dummy project to reproduce this issue here: https://github.com/budiadiono/react-native-expo-image-picker-demo. 

Published here: https://expo.io/@budiadiono/image-picker-demo.

Previously I was also trying to play with permissions things as discussed above but it didn't helps.

Any clue?

**Comment by budiadiono** [comment]
I found out that this issue raising when I'm using **Gallery** or **Explorer** to browse and select the image. Having no problem with **Photos** and **Drive**.

![img_20171214_080259](https://user-images.githubusercontent.com/796331/33970604-78a9cb6a-e0a6-11e7-8179-c4a658e64653.jpg)

**Comment by aalices** [comment]
@budiadiono fix in on it's way. Thanks! This was not related to previous reports anyway.

**Comment by donedgardo** [comment]
@aalices  Any updates? running into the same issue.
Thanks.

**Comment by aalices** [comment]
@donedgardo it is not yet merged. Not sure if there will be a minor release or it will be fixed in next SDK, @terribleben  ?

**Comment by donedgardo** [comment]
@terribleben ?

**Comment by ArsenyYankovsky** [comment]
@aalices This is still isn't fixed. Why is this closed?

**Comment by terribleben** [comment]
Hello recent repliers!

We don't think recent comments are related to the original issue in this thread, "Image picker issues on Android", opened last September, since the author of the issue was able to resolve their problem without us changing anything.

We've made lots of changes to this code in the last five months. If you have a new bug to report with ImagePicker, please open a new thread and follow the issue template.
