### ISSUE TITLE
BackgroundFetch on Android with startOnBoot: true crashes on restart

### ISSUE THREAD

**Issue by jeromecornet** [expo/expo#6290]
### Environment
 Expo CLI 3.7.1 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.6.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.7.1

I'm building an android app using the managed workflow. 
The logs come from Pixel emulator running android 9, but I've reproduced the problem on a real Pixel device running android 10.

### Steps to Reproduce

In an expo app, create a BackgroundFetch task, and register it with startOnBoot: true
build an android app with the managed workflow, install the app on the phone

Run the app, make sure that the background task works as expected
( in the example below `adb logcat | grep ReactNative` should show `running background task` )
For example in the https://github.com/jeromecornet/expo-android-backgroundfetch/raw/master/first_run.log, you will see:
`11-15 14:02:57.200  4386  4473 I ReactNativeJS: running background task`

Restart the phone

the app registers the task again, and starts the timer
for example in https://github.com/jeromecornet/expo-android-backgroundfetch/raw/master/after_reboot.log you will see
```
11-15 14:07:39.732  3987  3987 I TaskService: Registered task with name 'background-fetch-restart-test' for app with ID '@jerome.cornet/expo-android-backgroundfetch'.
11-15 14:07:39.732  3987  3987 I TaskService: Handling intent with action 'android.intent.action.BOOT_COMPLETED'.
11-15 14:07:39.736  3987  3987 I BackgroundFetchTaskConsumer: Starting an alarm for task 'background-fetch-restart-test'.
```

Wait 1 minute or so for the task to be executed

### Expected Behavior

The task should run, showing the expected console.log line

### Actual Behavior

Instead, the standalone app crashes and the background task gets unregistered, the following message appears in the logs instead
```
TaskService: Cannot execute background task because application loader can't be found.
```
From there the task gets unregistered and no longer works until the app is manually started again.

here's a relevant snippet of adb logcat (full log at https://github.com/jeromecornet/expo-android-backgroundfetch/raw/master/after_reboot.log)
```
11-15 14:09:10.998  1865  1882 I ActivityManager: Start proc 4461:com.jeromecornet.expobackgroundfetch/u0a85 for broadcast com.jeromecornet.expobackgroundfetch/expo.modules.taskManager.TaskBroadcastReceiv
er
11-15 14:09:11.001  4461  4461 W backgroundfetc: Unexpected CPU variant for X86 using defaults: x86
11-15 14:09:11.002  4461  4461 E backgroundfetc: Not starting debugger since process cannot load the jdwp agent.
11-15 14:09:11.023  4461  4461 I backgroundfetc: The ClassLoaderContext is a special shared library.
11-15 14:09:11.031  4461  4461 I MultiDex: VM with version 2.1.0 has multidex support
11-15 14:09:11.031  4461  4461 I MultiDex: Installing application
11-15 14:09:11.031  4461  4461 I MultiDex: VM has multidex support, MultiDex support library is disabled.
11-15 14:09:11.054  4461  4476 V FA      : Deferring to Google Analytics for Firebase for event data collection. https://goo.gl/J1sWQy
11-15 14:09:11.060  4461  4476 W backgroundfetc: Unsupported class loader
11-15 14:09:11.067  4461  4461 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
11-15 14:09:11.069  4461  4461 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
11-15 14:09:11.069  4461  4461 I FirebaseInitProvider: FirebaseApp initialization successful
11-15 14:09:11.072  4461  4476 W backgroundfetc: Skipping duplicate class check due to unsupported classloader
11-15 14:09:11.072  4461  4476 I DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21001
11-15 14:09:11.072  4461  4476 I DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 21001
11-15 14:09:11.073  4461  4476 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
11-15 14:09:11.083  4461  4476 W backgroundfetc: Unsupported class loader
11-15 14:09:11.085  4461  4461 W com.facebook.UserSettingsManager: Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase e
vents automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-ev
ents/getting-started-app-events-android#disable-auto-events.
11-15 14:09:11.085  4461  4461 W com.facebook.UserSettingsManager: You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertisi
ng and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/a
pp-events/getting-started-app-events-android#disable-auto-events.
11-15 14:09:11.099  4461  4476 W backgroundfetc: Skipping duplicate class check due to unsupported classloader
11-15 14:09:11.110  4461  4485 D NetworkSecurityConfig: No Network Security Config specified, using platform default
11-15 14:09:11.133  1865  1884 E BatteryExternalStatsWorker: no controller energy info supplied for wifi
11-15 14:09:11.174  4461  4481 I FA      : App measurement is starting up, version: 16250
11-15 14:09:11.174  4461  4481 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
11-15 14:09:11.174  4461  4481 I FA      : To enable faster debug mode event logging run:
11-15 14:09:11.174  4461  4481 I FA      :   adb shell setprop debug.firebase.analytics.app com.jeromecornet.expobackgroundfetch
11-15 14:09:11.188  4461  4461 D SoLoader: init start
11-15 14:09:11.188  4461  4461 D SoLoader: adding system library source: /vendor/lib
11-15 14:09:11.188  4461  4461 D SoLoader: adding system library source: /system/lib
11-15 14:09:11.188  4461  4461 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.jeromecornet.expobackgroundfetch-A0PwZZDTIP-cwTsS3PjhoA==/lib/x86 flags =
 0]
11-15 14:09:11.189  4461  4461 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.jeromecornet.expobackgroundfetch/lib-main flags = 1]
11-15 14:09:11.189  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
11-15 14:09:11.189  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
11-15 14:09:11.190  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.jeromecornet.expobackgroundfetch-A0PwZZDTIP-cwTsS3PjhoA==/lib/x86 flags = 0]
11-15 14:09:11.190  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.jeromecornet.expobackgroundfetch/lib-main flags = 1]
11-15 14:09:11.191  4461  4461 V fb-UnpackingSoSource: locked dso store /data/user/0/com.jeromecornet.expobackgroundfetch/lib-main
11-15 14:09:11.192  4461  4461 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.jeromecornet.expobackgroundfetch/lib-main
11-15 14:09:11.193  4461  4461 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.jeromecornet.expobackgroundfetch/lib-main
11-15 14:09:11.193  4461  4461 D SoLoader: init finish: 4 SO sources prepared
11-15 14:09:11.193  4461  4461 D SoLoader: init exiting
11-15 14:09:11.188  4461  4461 D SoLoader: init start
11-15 14:09:11.188  4461  4461 D SoLoader: adding system library source: /vendor/lib
11-15 14:09:11.188  4461  4461 D SoLoader: adding system library source: /system/lib
11-15 14:09:11.188  4461  4461 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.jeromecornet.expobackgroundfetch-A0PwZZDTIP-cwTsS3PjhoA==/lib/x86 flags = 0]
11-15 14:09:11.189  4461  4461 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.jeromecornet.expobackgroundfetch/lib-main flags = 1]
11-15 14:09:11.189  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
11-15 14:09:11.189  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
11-15 14:09:11.190  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.jeromecornet.expobackgroundfetch-A0PwZZDTIP-cwTsS3PjhoA==/lib/x86 flags = 0]
11-15 14:09:11.190  4461  4461 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.jeromecornet.expobackgroundfetch/lib-main flags = 1]
11-15 14:09:11.191  4461  4461 V fb-UnpackingSoSource: locked dso store /data/user/0/com.jeromecornet.expobackgroundfetch/lib-main
11-15 14:09:11.192  4461  4461 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.jeromecornet.expobackgroundfetch/lib-main
11-15 14:09:11.193  4461  4461 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.jeromecornet.expobackgroundfetch/lib-main
11-15 14:09:11.193  4461  4461 D SoLoader: init finish: 4 SO sources prepared
11-15 14:09:11.263  4461  4461 D SoLoader: init exiting
11-15 14:09:11.282  4461  4461 I TaskService: Registered task with name 'background-fetch-restart-test' for app with ID '@jerome.cornet/expo-android-backgroundfetch'.
11-15 14:09:11.283  4461  4461 I TaskService: Handling intent with task name 'background-fetch-restart-test' and appId '@jerome.cornet/expo-android-backgroundfetch'.
11-15 14:09:11.299  4461  4461 I TaskService: Handling job with task name 'background-fetch-restart-test' for app with ID '@jerome.cornet/expo-android-backgroundfetch'.
11-15 14:09:11.300  4461  4461 E Expo    : Cannot initialize app loader. <init> [class android.content.Context]
11-15 14:09:11.300  4461  4461 E TaskService: Cannot execute background task because application loader can't be found.
11-15 14:09:11.300  4461  4461 I TaskService: Unregistering task 'background-fetch-restart-test' for app '@jerome.cornet/expo-android-backgroundfetch'.
11-15 14:09:11.432  4461  4497 D b       : Loaded exp.host status page.
11-15 14:09:11.455  4461  4486 E GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
11-15 14:09:11.460  4461  4485 E GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
11-15 14:09:11.473  4461  4469 W System  : A resource failed to call close. 
11-15 14:09:11.522  4461  4486 E GraphResponse: {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api}
11-15 14:09:11.663  4461  4504 E Fabric  : Failed to retrieve settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/com.jeromecornet.expobackgroundfetch/settings
11-15 14:09:11.665  4461  4504 E Answers : Failed to retrieve settings

```

### Reproducible Demo

I have put a minimal sample app here https://github.com/jeromecornet/expo-android-backgroundfetch. I set the minimumInterval to 1mn for debugging, but I've had the problem with a 15mn interval so I don't believe it's related.

The matching apk (built with `expo build:android`) is here: https://github.com/jeromecornet/expo-android-backgroundfetch/raw/master/app.apk
the full adb logcat  output of the app working when executed is at https://github.com/jeromecornet/expo-android-backgroundfetch/raw/master/first_run.log
the full adb logcat  output of of the app crashing upon reboot is at https://github.com/jeromecornet/expo-android-backgroundfetch/raw/master/after_reboot.log

**Comment by superyarik** [comment]
face same crashes for app with background location

11-18 09:57:10.466 8496-8605/? D/ReactNative: Initializing React Xplat Bridge.
11-18 09:57:10.468 8496-8605/? D/ReactNative: Initializing React Xplat Bridge before initializeBridge
11-18 09:57:10.477 8496-8605/? D/ReactNative: Initializing React Xplat Bridge after initializeBridge
    CatalystInstanceImpl.runJSBundle()
11-18 09:57:10.477 8496-8605/? D/CatalystInstanceImpl: Loading script from file
11-18 09:57:10.478 8496-8614/? D/ReactNative: ReactInstanceManager.setupReactContext()
11-18 09:57:10.479 8496-8614/? D/ReactNative: CatalystInstanceImpl.initialize()
11-18 09:57:10.480 8496-8614/? D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
11-18 09:57:10.483 8496-8496/? I/TaskService: Handling intent with task name 'myapp-location' and appId '@solo_developers/##appid##'.
11-18 09:57:10.485 8496-8496/? I/TaskService: Handling job with task name 'myapp-location' for app with ID '@solo_developers/##appid##'.
11-18 09:57:10.485 8496-8496/? E/Expo: Cannot initialize app loader. <init> [class android.content.Context]
11-18 09:57:10.485 8496-8496/? E/TaskService: Cannot execute background task because application loader can't be found.
11-18 09:57:10.485 8496-8496/? I/TaskService: Unregistering task 'myapp-location' for app '@solo_developers/##appid##'.
11-18 09:57:10.499 8496-8496/? I/LocationTaskConsumer: get last location: Location[fused 59,178248,30,115362 hAcc=23 et=+1d11h28m20s309ms alt=47.39999771118164 vAcc=2 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}]
11-18 09:57:10.500 8496-8496/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
11-18 09:57:10.500 8496-8496/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ##appidg##, PID: 8496
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Map org.unimodules.b.j.d.getOptions()' on a null object reference
        at expo.modules.location.taskConsumers.LocationTaskConsumer.shouldReportDeferredLocations(LocationTaskConsumer.java:316)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.maybeReportDeferredLocations(LocationTaskConsumer.java:273)
        at expo.modules.location.taskConsumers.LocationTaskConsumer.access$100(LocationTaskConsumer.java:44)
        at expo.modules.location.taskConsumers.LocationTaskConsumer$1.onComplete(LocationTaskConsumer.java:123)
        at com.google.android.gms.g.s.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
11-18 09:57:10.501 8496-8614/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
11-18 09:57:10.502 8496-8614/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
11-18 09:57:10.504 5763-5807/? E/RequestManager_FLP: [FusedLocationApi] Location remove 75ef3e3 from ##appidg##
11-18 09:57:10.504 8496-8614/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
11-18 09:57:10.505 8496-8614/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
11-18 09:57:10.506 8496-8614/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
    Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
11-18 09:57:10.507 8496-8614/? W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
11-18 09:57:10.507 5141-5917/? D/Debug: !@DumpState : SHIP
11-18 09:57:10.508 5141-5917/? D/Debug: !@DumpState : debug level:0x4f4c
    !@Dumpstate : Finally, system will skip dumpstate
11-18 09:57:10.508 5141-5917/? W/ActivityManager: crash : ##appidg##,0
11-18 09:57:10.510 5141-5917/? W/ActivityManager:   Force finishing activity ##appidg##/host.exp.exponent.MainActivity

**Comment by jeromecornet** [comment]
Looks like it's very similar to https://github.com/expo/expo/issues/6017 . I'm going to close this issue and link back to the original

**Comment by bill-pairaktaridis** [comment]
So what's our option right now? Stop using `Location.startLocationUpdatesAsync` until it's updated?

**Comment by eggnukes** [comment]
> So what's our option right now? Stop using `Location.startLocationUpdatesAsync` until it's updated?

I guess so - I just find it weird that this has not been fixed yet. Seems like a big problem, especially for those working on transportation apps.

**Comment by bill-pairaktaridis** [comment]
> > So what's our option right now? Stop using `Location.startLocationUpdatesAsync` until it's updated?
> 
> I guess so - I just find it weird that this has not been fixed yet. Seems like a big problem, especially for those working on transportation apps.

Yup. That's our exact vertical. We need to track the user's location even when they're not using the app. Funnily enough, I've never personally encountered this issue but there are enough crashes in the Google Console to warrant a fix.

**Comment by cristianbriscaru** [comment]
same issue here, google play console actually flagged our app with Bad Behaviour as this bug is causing a 15% crash rate to our production app. 

80% of the crash reports are with this error: 

java.lang.NullPointerException: 
  at expo.modules.location.taskConsumers.LocationTaskConsumer.shouldReportDeferredLocations (LocationTaskConsumer.java:316)
  at expo.modules.location.taskConsumers.LocationTaskConsumer.maybeReportDeferredLocations (LocationTaskConsumer.java:273)
  at expo.modules.location.taskConsumers.LocationTaskConsumer.access$100 (LocationTaskConsumer.java:44)
  at expo.modules.location.taskConsumers.LocationTaskConsumer$1.onComplete (LocationTaskConsumer.java:123)
  at com.google.android.gms.g.s.run (Unknown Source:4)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7811)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)

15% with this error : 

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:2753)
  at android.app.ActivityThread.access$1800 (ActivityThread.java:156)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1429)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5469)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: 
  at expo.modules.location.taskConsumers.LocationTaskConsumer.didReceiveBroadcast (LocationTaskConsumer.java:115)
  at expo.modules.taskManager.TaskService.handleIntent (TaskService.java:313)
  at expo.modules.taskManager.TaskBroadcastReceiver.onReceive (TaskBroadcastReceiver.java:15)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:2741)

5% with this error : 

java.lang.RuntimeException: 
  at host.exp.exponent.experience.a$2.run (BaseExperienceActivity.java:197)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6806)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)

We had to disable location updates until it will get fixed

**Comment by diaraujo13** [comment]
> same issue here, google play console actually flagged our app with Bad Behaviour as this bug is causing a 15% crash rate to our production app.
> 
> Expo CLI 3.8.0 environment info:
> System:
> OS: macOS 10.14.6
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 8.12.0 - /usr/local/bin/node
> Yarn: 1.15.2 - /usr/local/bin/yarn
> npm: 6.9.0 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> IDEs:
> Android Studio: 3.3 AI-182.5107.16.33.5199772
> Xcode: 10.3/10G8 - /usr/bin/xcodebuild
> npmPackages:
> expo: ^36.0.0 => 36.0.2
> react: 16.9.0 => 16.9.0
> react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4
> react-navigation: ^2.18.2 => 2.18.3
> npmGlobalPackages:
> expo-cli: 3.13.1
> 
> 80% of the crash reports are with this error:
> 
> java.lang.NullPointerException:
> at expo.modules.location.taskConsumers.LocationTaskConsumer.shouldReportDeferredLocations (LocationTaskConsumer.java:316)
> at expo.modules.location.taskConsumers.LocationTaskConsumer.maybeReportDeferredLocations (LocationTaskConsumer.java:273)
> at expo.modules.location.taskConsumers.LocationTaskConsumer.access$100 (LocationTaskConsumer.java:44)
> at expo.modules.location.taskConsumers.LocationTaskConsumer$1.onComplete (LocationTaskConsumer.java:123)
> at com.google.android.gms.g.s.run (Unknown Source:4)
> at android.os.Handler.handleCallback (Handler.java:883)
> at android.os.Handler.dispatchMessage (Handler.java:100)
> at android.os.Looper.loop (Looper.java:237)
> at android.app.ActivityThread.main (ActivityThread.java:7811)
> at java.lang.reflect.Method.invoke (Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)
> 
> 15% with this error :
> 
> java.lang.RuntimeException:
> at android.app.ActivityThread.handleReceiver (ActivityThread.java:2753)
> at android.app.ActivityThread.access$1800 (ActivityThread.java:156)
> at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1429)
> at android.os.Handler.dispatchMessage (Handler.java:102)
> at android.os.Looper.loop (Looper.java:148)
> at android.app.ActivityThread.main (ActivityThread.java:5469)
> at java.lang.reflect.Method.invoke (Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
> at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
> Caused by: java.lang.NullPointerException:
> at expo.modules.location.taskConsumers.LocationTaskConsumer.didReceiveBroadcast (LocationTaskConsumer.java:115)
> at expo.modules.taskManager.TaskService.handleIntent (TaskService.java:313)
> at expo.modules.taskManager.TaskBroadcastReceiver.onReceive (TaskBroadcastReceiver.java:15)
> at android.app.ActivityThread.handleReceiver (ActivityThread.java:2741)
> 
> 5% with this error :
> 
> java.lang.RuntimeException:
> at host.exp.exponent.experience.a$2.run (BaseExperienceActivity.java:197)
> at android.os.Handler.handleCallback (Handler.java:873)
> at android.os.Handler.dispatchMessage (Handler.java:99)
> at android.os.Looper.loop (Looper.java:201)
> at android.app.ActivityThread.main (ActivityThread.java:6806)
> at java.lang.reflect.Method.invoke (Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)
> 
> We had to disable location updates until it will get fixed

Did you find any solution?
