### ISSUE TITLE
RNAudioRecorder not working as Expo SDK 35 does not support React Native 0.60.4

### ISSUE THREAD

**Issue by abir4u** [expo/expo#6354]
### Environment

>   Expo CLI 3.7.1 environment info:
>     System:
>       OS: macOS 10.14.6
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 12.13.0 - /usr/local/bin/node
>       npm: 6.12.0 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     IDEs:
>       Android Studio: 2.3 AI-162.4069837
>       Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
>     npmGlobalPackages:
>       expo-cli: 3.7.1

App's Target: iOS and Android

### Steps to Reproduce

1. create a react-native project with expo
2. Try to implement audio recorder or player using `RNAudioRecorder`
3. Run using `expo start`

### Expected Behavior

App should run without errors.

### Actual Behavior

Error received: `[Unhandled promise rejection: TypeError: null is not an object (evaluating 'RNAudioRecorderPlayer.startRecorder')]`

**React-Native Issue Reference**: https://github.com/facebook/react-native/issues/27297

**Comment by cruzach** [comment]
We will be releasing SDK 36 in the coming weeks, which will bring support for RN 0.61, so that should solve this

However, you could always use Expo's [Audio API](https://docs.expo.io/versions/latest/sdk/audio/), which provides access to both audio playback and recording.

You can keep track of the shipment of SDK 36 in [this issue](https://github.com/expo/expo/issues/6264)
