### ISSUE TITLE
AuthSession on Expo Web

### ISSUE THREAD

**Issue by thebetterjort** [expo/expo#6370]
I need an authentication solution on expo web, but it doesn't appear to be ready for expo web.

**Comment by cruzach** [comment]
Hi! Since this isn't a bug report, I'm going to close this issue. General questions are better off posted on our [forums](https://forums.expo.io/)

To answer your question- Expo's `AuthSession` and `AppAuth` libraries are native-only (I'd imagine since each of them uses a WebBrowser). But, there are plenty of 3rd-party authentication solutions for web auth. Integrating those into existing libraries might be something we look into in the future for web. (Feel free to open up a [feature request](https://expo.canny.io/feature-requests) for that!)

**Comment by YikSanChan** [comment]
Created a feature request: https://expo.canny.io/feature-requests/p/authsession-on-expo-web

**Comment by SolbiatiAlessandro** [comment]
any workaround for this?
