### ISSUE TITLE
Vibration & Haptic not working on standalone app 

### ISSUE THREAD

**Issue by apswak** [expo/expo#6375]
## 🐛 Bug Report

I've had this issue for several months, originally posted here: https://forums.expo.io/t/haptic-and-vibration-causing-app-to-crash-in-standalone-expo-app/22698

Have had no answer and I'm unable to post another thread/message on forums so here I am.

When using Vibration and Haptics through expo development app they are working fine. On a standalone app (through expo build:android) they don't work.

- Haptics usage example

```js
import * as Haptics from 'expo-haptics';

Haptics.selectionAsync()
```

- Vibration usage example

```js
import { Vibration } from 'react-native'

Vibration.vibrate()
```

### Environment

Expo CLI 3.0.8 environment info:
    System:
      OS: macOS 10.14
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
      Yarn: 1.15.2 - ~/.yarn/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
      Watchman: 4.9.4 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.3 => 34.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.9.0

### Steps to Reproduce

See code above, in my case the bug is appearing on an android phone for both cases (haven't tried iOS)

### Expected Behavior

Haptics should work when called within a function (such as on a TouchableOpacity onPress)
Vibration should work when called within a function (such as on a TouchableOpacity onPress)

### Actual Behavior

Haptics does nothing
Vibration crashes the application

By "standalone application" I am running `expo build:android` which pushes the update OTA to my application which is hosted on Play Store.

### Reproducible Demo

https://snack.expo.io/B16A9P5nr

**Comment by sjchmiela** [comment]
`expo build:android` does two things:
1. publishes an OTA update
2. triggers a build of a new APK

There are two matters to discuss here:

- you wrote
  > I am running expo build:android which pushes the update OTA to my application which is hosted on Play Store
  
  which suggests you're using `expo build:android` as a way to publish OTA updates to your app. I would propose using `expo publish` for that — this way
  1. the process takes less time — the command finishes right after uploading JS bundle to Expo servers, it doesn't have to wait for native app build
  2. the process doesn't drains unused resources — if for every OTA update you're triggering an APK build without intent of pushing it to the Store, more resources (Expo, planet) is used than needed
- you wrote you tried to add `VIBRATION` permission to `app.json`. I think the permission that actually would work in that case is `VIBRATE` ([image source](https://docs.expo.io/versions/v35.0.0/workflow/configuration/))

  ![Zrzut ekranu 2019-11-27 o 13 27 41](https://user-images.githubusercontent.com/1151041/69723393-b5ca2580-1119-11ea-86bd-2907d8149de7.png)
- as per [Some native configuration can't be updated by publishing](https://docs.expo.io/versions/v35.0.0/workflow/publishing/#some-native-configuration-cant-be-updated-by) section of the documentation
  > If you make any of the following changes in app.json, you will need to re-build the binaries for your app for the change to take effect:
  > - Increment the Expo SDK Version
  > - Change anything under the ios, **android**, or notification keys
  so even if you changed `android.permissions` in `app.json` and added `VIBRATE` permission, this configuration change can't be executed through an OTA update — you will need to update the native app for the change to have an effect.

**Comment by tommybru** [comment]
Due to inactivity from the OP, I am going to assume that the suggestions from @sjchmiela worked to solve this issue, so I am going to go ahead and close this. 

If you come across a similar issue that is reproducible with the latest SDK version, please feel free to open a new issue.

**Comment by bhavesh-trentium** [comment]
@tommybru 
Issue: Haptics & Vibration Not Working on Android 15 (HyperOS)

📱 Environment
Device: Xiaomi Redmi 13C 5G
OS: Android 15 (HyperOS)
Framework: React Native (Expo)
Haptics Library: expo-haptics
Permissions: "android.permission.VIBRATE" added in app.json

Problem Description
Haptic feedback and vibration are working correctly on:
iOS ✅
Android versions ≤ 14 ✅

However, on Android 15, neither haptics nor fallback vibration is triggering.

Code Used
```
import * as Haptics from 'expo-haptics';
import { Platform, Vibration } from 'react-native';

export const triggerErrorHaptic = async (): Promise<void> => {
  try {
    if (Platform.OS === 'ios') {
      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
    } else {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
    }
  } catch {
    Vibration.vibrate([0, 80, 60, 80]);
  }
};
```

Expected Behavior
On Android 15, either:
Haptics.impactAsync() should trigger vibration, OR
Fallback Vibration.vibrate() should work

Actual Behavior
No vibration or haptic feedback occurs on Android 15 devices
No errors are thrown
Fallback vibration also does not trigger

Additional Notes
Permission "android.permission.VIBRATE" is already added
Issue specifically observed on Xiaomi HyperOS (Android 15)
Same codebase works perfectly on Android 14 and below
Could be related to:
Android 15 vibration API changes
OEM-level restrictions (Xiaomi HyperOS)
Expo Haptics compatibility

Questions
Is expo-haptics compatible with Android 15?
Are there new permission or API changes required for vibration in Android 15?
Is this a known issue with Xiaomi HyperOS?

Request
Any guidance, workaround, or confirmation would be helpful.
If needed, I can provide a minimal reproduction repo.
