### ISSUE TITLE
[AppleAuthentication] How to get data user apple ?

### ISSUE THREAD

**Issue by ballza95** [expo/expo#6397]
Please help how to get data user apple ?

im need get email,fullname.

1.My log this project after sign in apple 
![Screen Shot 2562-11-28 at 9 26 45 AM](https://user-images.githubusercontent.com/32051406/69772496-abb03180-11c2-11ea-900b-d487fc49b8ad.png)

2.My code
![Screen Shot 2562-11-28 at 9 27 00 AM](https://user-images.githubusercontent.com/32051406/69772577-e1edb100-11c2-11ea-829a-157207a7ce5c.png)

Thank you.

**Comment by aryaminus** [comment]
For more info, it's null in my case when testing on actual device, not on Simulator

**Comment by aryaminus** [comment]
[This comment](https://github.com/SystangoTechnologies/react-native-apple-authentication/issues/3#issuecomment-559825886) solved my issue

**Comment by ballza95** [comment]
> For more info, it's null in my case when testing on actual device, not on Simulator

Im testing by Device Iphone 7+

**Comment by cruzach** [comment]
This is probably due to it not being the first time you are signing into your app. As we state in the [documentation](https://docs.expo.io/versions/latest/sdk/apple-authentication/#appleauthenticationappleauthenticationcredential):
> May also be null if this is not the first time the user has signed into your app

If that's the case, then this is the expected behavior and is not a bug with the Expo SDK
