### ISSUE TITLE
Expo ImagePicker throws a Typescript error

### ISSUE THREAD

**Issue by edoantonioco** [expo/expo#6407]
### Environment

Linux, expo 35, expo-cli 3.9.1

Android, iOS
### Steps to Reproduce

1. Go to https://docs.expo.io/versions/latest/sdk/imagepicker/#usage
2. Implement that code into a Typescript project
3. Visual studio code (its what  use) shows this
![Screenshot_20191128_185755](https://user-images.githubusercontent.com/5560824/69836825-1a1be080-1211-11ea-8263-0bca57ba966a.png)
4. If you put your mouse in top of it, it says:
```
Property 'uri' does not exist on type 'ImagePickerResult'.
  Property 'uri' does not exist on type '{ cancelled: true; }'.ts(2339)
```

### Expected Behavior

Code should work without Typescript complaining about it

### Actual Behavior

Typescript shows that there is an error

**Comment by lukmccall** [comment]
Hi @edoantonioco. I think this bug is in a `visual studio code` not in `expo-image-picker`. 
When you run `yarn tsc` everything compiles. Moreover, I've tried reproducing it on the `TypeScript Playground` and it also compiles ([you can check it out here](https://www.typescriptlang.org/play/index.html#code/KYDwDg9gTgLgBAE2AYwDYEMrDjAnmbASQFt0BzYQgOwDMI4BeOAbwCg4O4BXKASwC44AZxh8qZANztOAd14IYAC0FUuxAEbAoUznEXBeZRTBVrN26RzwEA-IIDkvUhXtwAPnHsA3ecAj2dTlBeGjsWS104AG0Aa2BcQRExMgBdQXQqXECOAF9suHV0IWAANgAWMKTecSk81lBIWEQUDCwcfCJnYAAFXmQ4qAAlYCEuVHgmNl1kDORgVFRgBEFRLmBa9zgACinOGao5haXBGnRUYvycuAAyOBJySloIAEopVhouA5heCCo4Chgw1G4y2+0Oi2WBQgEEWGWegnuFF6-S0QLG8F2HBC2zB8whzwiuiwMB4f0xkWmszxxxwUDWhM4dSJwBJUDJDI4uKOkNO52AABoOXoDEYTHAAIwABklgopHDkCmUEulMqFPAEcAARAh0AhNawIjlWEbWMhfiI4FhgRN-iy0SDecVXqxsVsAIRW9EAOi5+PC03NMOAXtQEDIW094y9+kMxmdVyAA)). 

It's worth to mention that you can trick visual studio writing something like this:
<img width="462" alt="Screenshot 2019-11-29 at 16 23 34" src="https://user-images.githubusercontent.com/9578601/69879701-6a09ae80-12c8-11ea-9255-13f2972f698b.png">

**Comment by edoantonioco** [comment]
yeah that fixed it. Its a issue with visual studio code, I hope they will fix it

**Comment by aadelgrossi** [comment]
```typescript
import { ImageInfo } from 'expo-image-picker/build/ImagePicker.types'

 if (!result.cancelled) {
      const { uri } = result as ImageInfo
      ...
    }
```    
This is what I did and the error went away.

Since ImagePickerResult is a union of the cancelled attribute + ImageInfo, I casted the result to ImageInfo so it matches the correct and expected properties. I guess TS can't match ImageInfo props correctly because it depends on the result of the expression !result.cancelled. 

```typescript
export declare type ImagePickerResult = {
    cancelled: true;
} | ({
    cancelled: false;
} & ImageInfo);

export declare type ImageInfo = {
    uri: string;
    width: number;
    height: number;
    type?: 'image' | 'video';
    exif?: {
        [key: string]: any;
    };
    base64?: string;
};
```

**Comment by pinocchio-life-like** [comment]
Cast your result type to something like this instead:

```
const response = await fetch(
            (result as DocumentPicker.DocumentPickerSuccessResult).assets[0].uri,
          );
```
