### ISSUE TITLE
WebBrowser and html <input type='file'> in android

### ISSUE THREAD

**Issue by timpalander** [expo/expo#6410]
## 🐛 Bug Report

When opening a URL with WebBrowser.openBrowserAsync in an Android device, and then attempt to use a html file input on said URL to browse for and select a file, the browser is closed and return to the previous app context without events or errors. Looks the same as this issue from 2017: https://forums.expo.io/t/problem-with-openbrowserasync-and-input-type-file/914/5

### Environment

https://snack.expo.io/HkTaPOc2B

### Steps to Reproduce

Open the snack. Select Android in the right column and run it. When the app is running, tap "Choose file". In the file browser, select a file or simply cancel.

### Expected Behavior

A file should be selected in the file input.

### Actual Behavior

WebBrowser is closed for no apparent reason and you return to the previous app context.

### Reproducible Demo

https://snack.expo.io/HkTaPOc2B

**Comment by mczernek** [comment]
For such cases, we left undocumented flag in `WebBrowser.openBrowserAsync`arguments. Please set `{showInRecents: true}` as a second argument, and it should work.

This behavior is side effect of current implementation. We switched from WebView to CustomTabs some time ago, and in order to remain as much as original behavior as possible, we decided to set this flag to false by default. It's side effect is, that since there is no instance of CustomTabs in history, there is no way for file selecting app to return to it.

I am closing for now, feel free to comment in case this doesn't help.
