### ISSUE TITLE
Local Image slow to display

### ISSUE THREAD

**Issue by objectiveSee** [expo/expo#6458]
### Environment

``` 
Expo CLI 3.8.0 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
      Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
      npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^35.0.0 => 35.0.1
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^4.0.10 => 4.0.10
    npmGlobalPackages:
      expo-cli: 3.8.0
```

iOS

### Steps to Reproduce

I am displaying images that are loaded from within the App's `Assets` directory. The images take several seconds to display on screen. They behave as if they are being loaded over the network, however they are part of the app. The only happens on device, not simulator. I have tried running in `Production` mode in Metro Bundler. Any help is appreciated!

Sample code:
```
const baby1 = require('../../assets/guesser_step1.png')
...
return (
        <View style={babyContainerStyle}>
            <Image  
                style={styles.babyImage}
                source={baby1} 
                resizeMode='contain'
            />
        </View>
    )
```

**Comment by cruzach** [comment]
Since you're serving your app locally, then the images aren't bundled into the app, yet. You'd need to build the binary, first (probably a good idea to test this!) see [these docs for help](https://docs.expo.io/versions/latest/guides/offline-support/#bundle-your-assets-inside-your-standalone-binary)

Maybe this has to do with your network connection? I'm not seeing the behavior when testing locally.
