### ISSUE TITLE
LayoutAnimation not working on 'web' browser.

### ISSUE THREAD

**Issue by nmpribeiro** [expo/expo#6460]
Hi all!

I have been learning `react-native` and using expo for it's awesome ease of use while debugging in my iOS phone. Many times I go straight for using the `w` command just to get going fast:

`› Press a to run on Android device/emulator, or w to run on web.`

The other day I was learning about the `LayoutAnimation` and got stuck trying to understand why it wasn't working on my browser. It turns out it works fine on my iOS but it doesn't animate at all in my web browser.
The example I was using came from here:
https://gist.github.com/Jpoliachik/0dd83689646d1051b0bc

I wonder if this is documented somewhere or if the web is not meant to support everything? Or even if this  has been overlooked?

**Comment by cruzach** [comment]
That's part of the `react-native` package, actually, but it looks like `react-native-web` does support it with RN 0.60 - > https://github.com/necolas/react-native-web

So you'll have to use Expo SDK 36 with it

Closing this since we keep Github for bug reports. our [forums](https://forums.expo.io/) are a better place for questions like this
