### ISSUE TITLE
WebView html local in Android

### ISSUE THREAD

**Issue by oron11** [expo/expo#6492]
I'm trying to open in expo-sdk-35 html file that loads script file.
In IOS everything works fine as expected like this:
`<WebView source = { require('./file.html') } />`

On the other hand, for Android the above code doesn't work for me.

I tried: 
`  const myHtml= Asset.fromModule(require('./file.html')).uri;
  <WebView uri= {{uri: myHtml}} />
`

I tried with loading the html before in a async way :
`
const file = await AssetUtils.resolveAsync(require("./file.html"));
const paypalHtml = await FileSystem.readAsStringAsync(file.localUri);
`

Nothing is working for me.
I saw some comments that said to attach the file to android assests folder.
I don't know how to that in expo (I tried with expo assests directory).

I would appreciate any help,
Thank you from advance.

**Comment by cruzach** [comment]
Hi!

So from the `react-native-webview` docs:
> However on Android, you need to place the HTML file inside your android project's asset directory. For example, if local-site.html is your HTML file and you'd like to load it into the webview, you should move the file to your project's android asset directory which is your-project/android/src/main/assets/. Then you can load the html file as shown in the following code block

Since you don't have access to that folder in development, it doesn't look like you can do this in the managed workflow. The workarounds [here](https://forums.expo.io/t/what-is-path-to-location-of-files-bundled-with-assetbundlepatterns-in-sdk-v25/7311/16) suggest hosting your html files somewhere, rather than bundling them into your binary

Sorry that the exact functionality you're looking for isn't possible in the managed workflow right now, but the bare workflow does support this!

**Comment by oron11** [comment]
Hi,

I tried to host the html file in the server, it worked in Android like this:
`<WebView uri= {{uri: myHtml}} `

However, in the IOS it doesn't work :(

Does this make sense?
