### ISSUE TITLE
SDK 36: Linking.parse w/ custom scheme breaks path (uses hostname now)

### ISSUE THREAD

**Issue by bayoremit** [expo/expo#6497]
## 🐛 Bug Report

The new shinny Linking module's parse method in SDK 36 no parses the path for custom schemes properly as documented by (https://docs.expo.io/versions/latest/workflow/linking/) & (https://github.com/expo/expo/pull/5179)

the path property is now parsed as hostname

### Environment

```
  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.1
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.11.1
```

### Steps to Reproduce

Use Linking.parse on these urls
- `lyft://ridetype?id=lyft&pickup[latitude]=37.764728&pickup[longitude]=-122.422999&destination[latitude]=37.7763592&destination[longitude]=-122.4242038`
- `myapp://path/into/app?hell`
- `custom://my/path?query=param`

### Expected Behavior

```
[
    {
        "hostname": null,
        "path": "ridetype",
        "queryParams": {
            "destination[latitude]": "37.7763592",
            "destination[longitude]": "-122.4242038",
            "id": "lyft",
            "pickup[latitude]": "37.764728",
            "pickup[longitude]": "-122.422999"
        },
        "scheme": "lyft"
    },
    {
        "hostname": null,
        "path": "path/into/app",
        "queryParams": {
            "hell": ""
        },
        "scheme": "myapp"
    },
    {
        "hostname": null,
        "path": "my/path",
        "queryParams": {
            "query": "param"
        },
        "scheme": "custom"
    }
]
````

### Actual Behavior

```
[
    {
        "hostname": "ridetype",
        "path": "",
        "queryParams": {
            "destination[latitude]": "37.7763592",
            "destination[longitude]": "-122.4242038",
            "id": "lyft",
            "pickup[latitude]": "37.764728",
            "pickup[longitude]": "-122.422999"
        },
        "scheme": "lyft"
    },
    {
        "hostname": "path",
        "path": "into/app",
        "queryParams": {
            "hell": ""
        },
        "scheme": "myapp"
    },
    {
        "hostname": "my",
        "path": "path",
        "queryParams": {
            "query": "param"
        },
        "scheme": "custom"
    }
]
````

### Notes

If a 3rd slash is added to the custom schemes, they work as expected. Does this mean this could be a documentation bug from a breaking change?

- `lyft:///ridetype?id=lyft&pickup[latitude]=37.764728&pickup[longitude]=-122.422999&destination[latitude]=37.7763592&destination[longitude]=-122.4242038`
- `myapp:///path/into/app?hell`
- `custom:///my/path?query=param`

**Comment by brentvatne** [comment]
@ide - perhaps related to https://github.com/expo/expo/commit/72e694e0078e034bc51769bab9b800e2eda68219#diff-05479392689210b6698fc7ec7e5bc120

**Comment by jamesbechet** [comment]
I have the same issue

**Comment by ide** [comment]
@cruzach did you merge your PR that addresses this? (If so we can cherry pick to the release branch and publish a new expo package to npm.)

**Comment by cruzach** [comment]
No, the [PR i think you're talking about](https://github.com/expo/expo/pull/6688) fixed a different issue

Seems this issue and https://github.com/expo/expo/issues/6528 both have to do with using the `URL` parsing function from `url-parse. 

Although this could be more of a documentation bug, because afaik when a URI doesn't have a host, the path has to begin with a slash (resulting in the 3 slashes that make the url parse correctly e.g. `myapp:///path/into/app`)

**Comment by ide** [comment]
Expounding on @cruzach's latest post above, **the new behavior is standards-compliant with the URI specification.** We will add a note about this breaking change to the SDK 36 release notes.

According to the specification, the host of `myapp://hello/world` is `hello` and the path is `world`. After all, if you wrote `myapp://hello.com/world`, the host would be `hello.com` and the path would be `world`. The host does not need to contain a dot character -- consider dotless hosts like `http://localhost/world` or TLDs like [`http://ai`](http://ai).

So, there are three approaches you can take:

1. If you have control over the URI, add a third slash after the scheme (`myapp:///hello/world`) so that the host portion of the URI is empty.
2. If you have control over the URI, remove the two slashes after the scheme and use a URN instead of URL (`myapp:hello/world`).
3. If you don't have control over the URI, change your application code to join together the parsed URL's host and path with a slash (`'hello' + '/' + 'world'`).

---

URI spec reference: https://tools.ietf.org/html/rfc3986#section-3:

```
3.  Syntax Components

   The generic URI syntax consists of a hierarchical sequence of
   components referred to as the scheme, authority, path, query, and
   fragment.

      URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

      hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty

   The scheme and path components are required, though the path may be
   empty (no characters).  When authority is present, the path must
   either be empty or begin with a slash ("/") character.  When
   authority is not present, the path cannot begin with two slash
   characters ("//").  These restrictions result in five different ABNF
   rules for a path (Section 3.3), only one of which will match any
   given URI reference.

   The following are two example URIs and their component parts:

         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
          |   _____________________|__
         / \ /                        \
         urn:example:animal:ferret:nose
```
