### ISSUE TITLE
Look into extracting AR into unimodule

### ISSUE THREAD

**Issue by esamelson** [expo/expo#6514]
Partial step of #6513

We want to look into extracting the AR module into a unimodule while keeping the API and implementation as consistent as possible. Aside from the module implementation itself, this PR should not have a large surface area and the resulting unimodule should not be difficult to install or set up.

AR is an experiemental module, and if we can only support it in the managed workflow it's not the end of the world. Whoever is assigned to this should work with @tsapeta to timebox 1-2 days on this, and if it looks like it's not easily doable in a short period of time after that we will close this issue.

(assigning to @tsapeta for now)

**Comment by tsapeta** [comment]
I think it's generally impossible to do right now because AR module contains a lot of synchronous methods that we don't support yet in unimodules abstraction. They cannot be just changed to asynchronous.
Probably it would make more sense once we add support for TurboModules, so maybe we could work on this in SDK 38 or 39 🤔
I'm closing this issue but hopefully we will come back to this later! 😄
