### ISSUE TITLE
Initialization error in GLView

### ISSUE THREAD

**Issue by awinograd** [expo/expo#6583]
## 🐛 Bug Report

We got the following event in sentry.

`undefined is not an object (evaluating 't.__exglCtxId=n')`

https://github.com/expo/expo/blob/75276a110528b8d65b9e63d6a744927beb21b6f7/packages/expo-gl/src/GLView.tsx#L502

I was able to track it down to these relevant lines but don't have much of an idea of how to proceed. It seems like the NativeView isn't always creating the EXGLContext object properly and so trying to read a property in `_onSurfaceCreate` results in the undefined error.

https://github.com/expo/expo/blob/75276a110528b8d65b9e63d6a744927beb21b6f7/packages/expo-gl/src/GLView.tsx#L116
https://github.com/expo/expo/blob/d8c4a4f298a00216e26ce844faeaa0efe1d7175f/packages/expo-gl-cpp/cpp/EXGLContext.cpp#L49

### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.4 - ~/.nodenv/versions/8.11.4/bin/node
      Yarn: 1.12.1 - ~/.yarn/bin/yarn
      npm: 6.11.3 - ~/.nodenv/versions/8.11.4/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.22 => 16.8.22 
      @types/react-native: 0.60.23 => 0.60.23 
      expo: ^36.0.0 => 36.0.0 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.0.6 => 4.0.6 

```
appOwnership
standalone
device
iPhone Xr
expoAppPublishedTime
2019-12-19T01:39:16.997Z
expoAppVersion
0.0.4
expoReleaseChannel
default
expoVersion
36.0.0
level
fatal
os
iOS 13.1.3
os.name
iOS
release
0.0.4-r.SyTp48d0r
user
```

### Steps to Reproduce

This occurs unpredictably when mounting a GLView. I haven't been able to reproduce in development yet, but if someone has an idea of how to isolate the issue I'm happy to try to create a small repro example.

### Expected Behavior

Context object is created properly and no js exception occurs

### Actual Behavior

`undefined is not an object (evaluating 't.__exglCtxId=n')`
https://github.com/expo/expo/blob/75276a110528b8d65b9e63d6a744927beb21b6f7/packages/expo-gl/src/GLView.tsx#L502

### Reproducible Demo

I haven't been able to reproduce in development yet, but if someone has an idea of how to isolate the issue I'm happy to try to create a small repro example.

**Comment by cruzach** [comment]
It's hard to debug without a repro, but @tsapeta or @bbarthec may have a suggestion on how you might be able to narrow down the causes and dig a little more

**Comment by vischnabel** [comment]
Hi guys, how are you? 

I'm currently experiencing the same error in production, and I have no idea why it's happening (my only guess is that the problem is somehow related to low memory at the moment of creating a new GlContext). Did someone was able to find a repro or something like that?

Thanks in advance.

**Comment by awinograd** [comment]
No updates on my end. Haven't seen the error happen since

**Comment by tsapeta** [comment]
We haven't received any other bug reports too. How often is this error happening @vischnabel?

**Comment by vischnabel** [comment]
First of all, thanks for the quick responses.

This problem happened randomly in our TestFlight environment, 4 times in a single device over the past days. Since our test environment is small, I can't measure the exact proportion of this bug, it can be just an occasional error in a small population or something game breaker.

Device Info:
&nbsp;&nbsp;&nbsp;&nbsp;Model: iPhone 11 Pro Max
Operational System:
&nbsp;&nbsp;&nbsp;&nbsp;Version: 13.3.0 (17C54)

The free Space in RAM in the device were, respectively, 276.11, 622.05, 272.06 an 611.20MB.

My environment info is he following:

Expo CLI 3.11.3 environment info:
&nbsp;&nbsp;&nbsp;&nbsp;System:
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OS: macOS 10.15.2
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shell: 5.7.1 - /bin/zsh
    &nbsp;&nbsp;&nbsp;&nbsp;Binaries:
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yarn: 1.19.2 - /usr/local/bin/yarn
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Watchman: 4.9.0 - /usr/local/bin/watchman
    &nbsp;&nbsp;&nbsp;&nbsp;IDEs:
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    &nbsp;&nbsp;&nbsp;&nbsp;npmPackages:
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;react: 16.9.0 => 16.9.0 
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;react-native: 0.61.5 => 0.61.5 
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;react-navigation: ^4.0.10 => 4.0.10 
    &nbsp;&nbsp;&nbsp;&nbsp;npmGlobalPackages:
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expo-cli: 3.11.3

I'm using react-native with unimodules version 0.7.0 and gl-react and gl-react-native at version 4.0.0.

**Comment by pacoelayudante** [comment]
I found a related problem, in the new RN 0.62 
And a temporary solution #7623
I hope this helps someone
