### ISSUE TITLE
Google Play Campaign Attribution

### ISSUE THREAD

**Issue by anasanzari** [expo/expo#6626]
Would be great if this feature could be added as part of expo.
Link: https://developers.google.com/analytics/devguides/collection/android/v4/campaigns

**Comment by cruzach** [comment]
Hi! I'm going to close this since we like to keep github reserved for bug reports, feature requests belong on our [canny](https://expo.canny.io/feature-requests)

If that feature is part of the Firebase JS SDK, then you can use it in a managed expo project. Otherwise, if it's only available as part of the native SDKs, you'll need to use the bare workflow to use it
