### ISSUE TITLE
Firebase phone authentication in expo project

### ISSUE THREAD

**Issue by Uttu316** [expo/expo#6640]
How will I use react-native-firebase in my expo project?
I am getting this error when I include react-native-firebase:

RNFirebase core module was not found natively on Android, ensure you have correctly added the RNFirebase and Firebase Gradle dependencies to your android/app/build.gradle file.

But when I only include "firebase" instead of "react-native-firebase" then it requires captcha which does not make any sense to me to include that in my project.

**Comment by Hirbod** [comment]
Firebase does not work in Expo projects, you need to eject to bare in order to use it.

**Comment by Uttu316** [comment]
Just "expo eject" is enough to convert the expo project into a bare native project or I will need something else so that there will be no issue later.
I am asking this because I am not able to find any video tutorial on youtube.

**Comment by Hirbod** [comment]
It depends on your project. You will lose some functionality (such as OTA updates and expo push notifications). 

Consider carefully before ejecting. Some packages might break and you need to find a native replacement for it. Usually it’s not very complicated. Try to eject to bare and not to ExpoKit, since it’s deprecated and more unimodules being released currently. Check the expo documentation, there is enough information inside of it

**Comment by Uttu316** [comment]
Thanks @Hirbod

**Comment by cruzach** [comment]
Depending on what you need from firebase, you may want to give the [Firebase JS SDK](https://firebase.google.com/docs/reference/js) a look. Not sure if phone authentication is included, though

**Comment by Hirbod** [comment]
Phone auth is not available in JS SDK
