### ISSUE TITLE
Couldn't start project on Android

### ISSUE THREAD

**Issue by wen0428** [expo/expo#6653]
请问一下，我点击的是 run on Android device/emulator , 错误出现的是 Error open simulator, 想不通
Couldn't start project on Android: Error running adb: adb: failed to install /Users/a1/.expo/android-apk-cache/Exponent-2.14.0.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl663326345.tmp/base.apk: AndroidManifest.xml]
We noticed your tunnel is having issues. This may be due to intermittent problems with our tunnel provider. If you have trouble connecting to your app, try to Restart the project, or switch Host to LAN.
![image](https://user-images.githubusercontent.com/47655948/71667551-92da0380-2da0-11ea-84e0-9dc05081e942.png)
![image](https://user-images.githubusercontent.com/47655948/71667567-a2f1e300-2da0-11ea-90df-2137a75a6598.png)

**Comment by cruzach** [comment]
I'm going to close this since there's not really enough information here yet to effectively help/troubleshoot- there was a [similar GH issue opened](https://github.com/expo/expo-cli/issues/694) and there are some solutions shared there. Try them out and I hope they work! If not, please fill out the full bug report template

**Comment by acfunelas** [comment]
I created a new virtual device to fix this. Hope it helps.
