### ISSUE TITLE
[ios] SDK 36 permissions require individual modules to be installed for askAsync to work

### ISSUE THREAD

**Issue by PeterTran0609** [expo/expo#6682]
### Environment

  Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.13.1 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: * => 16.9.17 
      @types/react-native: ^0.57.65 => 0.57.65 
      @types/react-navigation: ^2.0.23 => 2.13.10 
      expo: 36.0.2 => 36.0.2 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
      react-navigation: git+ssh://git@gitlab2.atalink.com:phucdph/bluesky-mobile.git#react-navigation-2.18.3 => 2.18.3 
    npmGlobalPackages:
      expo-cli: 3.11.3

### Steps to Reproduce

I'm using this code to check for permission for access to Photo in iOS.

`const { status } = await Permissions.askAsync(Permissions.CAMERA_ROLL);`

### Expected Behavior

return PermissonReponse

### Actual Behavior

it return `Error: Unrecognized permission: cameraRoll`

**Comment by PeterTran0609** [comment]
I don't know why but when I debug in native code EXPermissions.m, the `_requesters` doesn't have type `cameraRoll`, but when I add `expo-media-library`, it have now have `cameraRoll `. 
In default, it only have 
Printing description of self->_requesters:
{
    location = "<EXLocationPermissionRequester: 0x6000032d2ce0>";
    notifications = "<EXRemoteNotificationPermissionRequester: 0x600003c42550>";
    userFacingNotifications = "<EXUserNotificationPermissionRequester: 0x6000032d33c0>";
}

**Comment by YikSanChan** [comment]
@PeterTran0609 Can you paste what you import?

**Comment by esamelson** [comment]
Hi @PeterTran0609 -- sorry you're running into this 😞 are you getting this error in the iOS Expo client or only in the standalone app? And does running `expo install expo-media-library` fix the issue?

**Comment by benhjames** [comment]
I had the same issue: running `expo install expo-media-library`, installing pods and rebuilding makes it work once again.

I'm guessing this may be because the requester for the `cameraRoll` permission now lives in `expo-media-library` as a result of the permissions rework?

**Comment by esamelson** [comment]
Ah, @benhjames are you using the bare workflow?

**Comment by benhjames** [comment]
Yep!

**Comment by esamelson** [comment]
Ok, thanks for the info. We'll look into this. Out of curiosity, what did you need the `CAMERA_ROLL` permission for that was outside of the `expo-media-library` package?

**Comment by benhjames** [comment]
I'm currently using [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) and need to check the gallery permission to prompt the user to either accept it or show them how to change it. Thanks for looking into this! :+1:

**Comment by lukmccall** [comment]
Hi everyone, since SDK 36 `expo-permissions` doesn't contain code responsible for requesting system permission (expect `system notifications`- however, it will be moved too). These requesters were moved to different packages. For example, `CAMERA_ROLL` permission was migrated to the `expo-image-picker` and `expo-media-library` packages. 

So if you are getting `Error: Unrecognized permission: <your permission>`, please install expo package which contains required permission requester. That should fix it. 

Which module contains the needed requester? Please check out the table below. 

| Permission type  | Packages |
| ------------- | ------------- |
| `NOTIFICATIONS` | `expo-permissions`  |
| `USER_FACING_NOTIFICATIONS`  | `expo-permissions` |
| `LOCATION` | `expo-location` |
| `CAMERA` | `expo-camera`, `expo-barecode-scanner` |
| `AUDIO_RECORDING` | `expo-av` |
| `CONTACTS` | `expo-contacts` |
| `CAMERA_ROLL ` | `expo-image-picker`, `expo-media-library` |
| `CALENDAR` | `expo-calendar` |
| `REMINDERS` | `expo-calendar` |
| `SYSTEM_BRIGHTNESS` | `expo-brightness` |

Moreover, if you want to use some external package with `expo-permissions`, unfortunately, you still need to install an expo' package with a requester. However, let us know what is missing in our package. We will try to add absent functionality.

**Comment by benhjames** [comment]
Thanks @lukmccall for the clarification!

It may be worth mentioning the above in the Expo 36 blog article, or the Changelog, as it's not immediately obvious as a breaking change.

**Comment by lukmccall** [comment]
@benhjames, for sure I will update the documentation.

**Comment by shamilovtim** [comment]
Guys, this was a breaking change that was never called out in the docs.

**Comment by ide** [comment]
It is mentioned in the docs now: 
![docs](https://user-images.githubusercontent.com/379606/74864855-0ad69b80-5305-11ea-8539-e0f57bcad306.png)
