### ISSUE TITLE
ExpoKit: `expo export` does not update native files

### ISSUE THREAD

**Issue by rodneyrehm** [expo/expo#6683]
On an ExpoKit project running `expo publish` updates various files in `ios` and `andrdoid` directories. This does not happen for `expo export`.

I needed to build standalones without using `expo publish` (and disable OTA) and ended up with https://gist.github.com/rodneyrehm/b6726c119233c81a0bc2a0a179d0fa0e

Since a similar request [showed up in slack](https://expo-developers.slack.com/archives/C04Q3JTSV/p1578239943349300) today I guess it's time to ask if the current behavior of `expo export` is intentional or an oversight.

**Comment by cruzach** [comment]
`expo export` will have the same limitations that `expo publish` has ([listed here](https://docs.expo.io/versions/latest/workflow/publishing/#some-native-configuration-cant-be-updated-by), and it includes changes made to native code files)

But, if you're also not able to update js/asset files, then I suggest opening an bug report on [`expo-cli`](https://github.com/expo/expo-cli) and include a repro method, and your `expo-cli` and `expo` sdk versions

**Comment by tasn** [comment]
Hey @cruzach, I think you misunderstood him. Please re-read it.
The problem is that you can't build an ejected (expokit) app without first running `expo publish` which is a problem if you're using a standalone app (`expo export`) and therefore don't have an expo account + don't publish to expo...

`expo export` should be fixed to also modify the required files for detached apps, the same way `expo publish` does.

With that being said, maybe `expo-cli` is the more appropriate repo to report it, what do you think?

**Comment by jameswilddev** [comment]
I can't find an issue for this on the expo-cli; was this raised?  I think it's what's breaking my CI builds.

**Comment by tasn** [comment]
I never opened it, because I never got a response from @cruzach.
With that being said, I think things are very different nowadays with the updates module being outside of expo.
