### ISSUE TITLE
http request Network Error

### ISSUE THREAD

**Issue by chenguzhen87** [expo/expo#6709]
## 🐛 Bug Report
HTTP API can be successfully adjusted on browsers, but failed to call in Expo, and I can use other HTTP API to successfully call.
### Environment
expo ~36.0.0
window 10
react-native sdk-36.0.0

### Steps to Reproduce
npm start 

### Expected Behavior
fetch or axios has no Network Error

### Actual Behavior
 Network Error

### Reproducible Demo
![image](https://user-images.githubusercontent.com/28331609/71970960-9956f800-3244-11ea-8d6f-3abeb576c5cc.png)

**Comment by cruzach** [comment]
Hi! I just put together [this snack](https://snack.expo.io/@charliecruzan/fetchhttpexample) which fetches from an http endpoint, and it seems to work fine on iOS and Android, just not on web since if you load a page in your browser using HTTPS, the browser will refuse to load any resources over HTTP. (In my example, just changing http to https resolves the issue)

**Comment by snacpro16** [comment]
https://domain name:7000/api/0.1/user

but still getting error
