### ISSUE TITLE
Barcode_Type different type in android or ios

### ISSUE THREAD

**Issue by Thibaultferre** [expo/expo#6717]
The barcode works well in ios but in android i have some troubles. 

When i perform a console.log to know the type of a barcode , i have a string type like "org.gs1.EAN-13" in ios but in android i have a int like "32". 

So there is a solution to have the same type on both platform ? 

Thank you for you help

**Comment by cruzach** [comment]
Looks like this is just the difference in how the types are represented in native Android/iOS. [This is used behind the scenes for Android](https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/Barcode.html) (formats are all represented by ints). What remains constant/what you need to use in react-native land is the key (`BarCodeScanner.Constants.BarCodeType.qr`), not the value (`256` on android, and `org.iso.QRCode` on iOS)

Closing since this isn't a bug with the Expo SDK

**Comment by fks6** [comment]
At least for 2i5, it won't work on Android. You have to handle each OS separately: (Replace i2o5/128 with qr/256 or whatever you need)

barCodeTypes={[128]} works on Android, but not iOS

all the following work on iOS but not on Android:

{[BarCodeScanner.Constants.BarCodeType.interleaved2of5]}
{[BarCodeScanner.Constants.BarCodeType.interleaved2of5, 128]}
{["BarCodeScanner.Constants.BarCodeType.interleaved2of5"]}
{[Camera.Constants.BarCodeType.interleaved2of5]}

BarCodeScanner.Constants.BarCodeType.interleaved2of5 becomes
on iOS: org.ansi.Interleaved2of5
on Android: undefined

**Comment by cruzach** [comment]
As the docs state, `interleaved2of5` is not available for Android. 

if you want to use `code128`, then you should pass `BarCodeScanner.Constants.BarCodeType.code128`

**Comment by fks6** [comment]
As I already wrote, 2i5 works on Android if you put `barCodeTypes={[128]}`. I know that the docs say it doesn't work, but it does—just not if you use `BarCodeScanner.Constants.BarCodeType.interleaved2of5`.

My solution from 2018 which still works is
`
barCodeTypes={
Platform.OS === 'android' ? [128] : [BarCodeScanner.Constants.BarCodeType.interleaved2of5]
}
`

**Comment by cruzach** [comment]
Ah okay, I see what you mean now. In the future @fks6 , if you fill out the entire bug report template, it helps to minimize this back-and-forth so that we can resolve issues faster. If I'm understanding you correctly, the "bug" you are reporting is that `interleaved2of5` barcodes **are supported** on the Android side, but you need to pass the number `128`? This makes sense, since the int value for ITF on the Android API is `128` - https://developers.google.com/android/reference/com/google/android/gms/vision/barcode/Barcode

**Comment by meet2amit** [comment]
![image](https://user-images.githubusercontent.com/1227685/206153019-8af7b67c-43ee-4912-a856-004d9128b1d6.png)

@cruzach @Thibaultferre @kalin @fks6 @croaky 

we got correct barcode in android but in ios it add one ZERO at starting

Any one know solution then please suggest us
