### ISSUE TITLE
Expo Push Notifications stopped working

### ISSUE THREAD

**Issue by khurram-s** [expo/expo#6761]
### Environment

  Expo CLI 3.11.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - /usr/local/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.12.1 
    npmGlobalPackages:
      expo-cli: 3.11.1

slmac:trustgrid-verify khurrams$ 

### Steps to Reproduce

Use this tool to send push notification to your device.
https://expo.io/notifications
App never receives push notification

### Expected Behavior

Expecting to have a push notification on that device.
### Actual Behavior

No notification is received. Same app was receving push notifications using this tool a while ago.

### Reproducible Demo
I beleieve above tool is enough to demonstrate push notifications not working.

**Comment by cruzach** [comment]
Hi! Not sure if [this forum post](https://forums.expo.io/t/expo-push-notifications-stopped-working-since-6-hours/32120) regarding the same thing is yours, but we should probably try to keep the conversation in just one thread

I just tested push notifications using [this snack](https://snack.expo.io/@charliecruzan/pushnotifications34) and the push notification tool you linked, and they worked just fine.

If this is a standalone app, then like I said in the forum post, I would investigate your certificates (specifically your APN key). There should also be more information in the push tickets and push receipts regarding errors.

**Comment by srdzdv** [comment]
I am also seeing the same issue. Push receipts say status ok but the push notification never arrives to the device. TicketIds: 3b5b5f82-821b-4017-87af-8f03f8db7719
bd9894f3-d070-44a0-8e6d-c03572ce800a

**Comment by khurram-s** [comment]
It looks like when i build app almost same time when we have this issue. https://forums.expo.io/t/expo-build-ios-ssl-verify-failed/32102 
Somehow app got detatched. So i was getting this error on push notifications
 {
  "data": {
    "status": "error",
    "message": "Could not find APNs credentials for com.trustgrid.citizenapp (@securelogic/trustgrid-citizen). Check whether you are trying to send a notification to a detached app. If not, you may need to clear your push credentials and regenerate or upload new ones.",
    "details": {
      "error": "InvalidCredentials"
    }
  }
}

After clearing the credentials and publishing app on same channel fixed it.

So i am closing this issue.
