### ISSUE TITLE
[EXPO PUSH NOTIFICATION] Too Many Experience Ids

### ISSUE THREAD

**Issue by blackwolf08** [expo/expo#6771]
### Please note that discussions opened as issues in the core Expo repository will be closed.

Error: All push notification messages in the same request must be for the same project; check the details field to investigate conflicting 
tokens.
    at Expo._getErrorFromResultError (D:\New Projects\jiit_app\expo_push_noti\node_modules\expo-server-sdk\build\ExpoClient.js:212:21)     
    at Expo._getErrorFromResult (D:\New Projects\jiit_app\expo_push_noti\node_modules\expo-server-sdk\build\ExpoClient.js:202:26)
    at Expo.<anonymous> (D:\New Projects\jiit_app\expo_push_noti\node_modules\expo-server-sdk\build\ExpoClient.js:184:25)
    at Generator.next (<anonymous>)
    at fulfilled (D:\New Projects\jiit_app\expo_push_noti\node_modules\expo-server-sdk\build\ExpoClient.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'PUSH_TOO_MANY_EXPERIENCE_IDS',

How to remove bad tokens as I have 3000+ tokens?

**Comment by cruzach** [comment]
The `details` object returned with the error will have a mapping of experience names to the push tokens associated with that experience, for example:
```
{
  "@username/projectAAA": [array of push tokens],
  "@username/projectBBB": [array of push tokens],
}
```

So you can catch this error and, depending on whether you are trying to send notifications to `projectAAA` or `projectBBB`, remove the tokens from the opposite project.

**Comment by BillyIvy** [comment]
@cruzach What if we are wanting to send push notifications to both or all experience ID's?  The situation below is prevents the expo server from sending any notifications even though it is the same project.  Additionally, neither array is invalid they just happened to be created by two different developers.
`{
"@username1/projectA": [array of push tokens],
 "@username2/projectA": [array of push tokens],
}`
While my team has not run into this issue yet, it seems that this bug can be triggered when rolling out updates to app stores see https://forums.expo.io/t/push-notification-expo-server-error-push-too-many-experience-ids/31516/3.  My team's application cannot feasibly "delete all id from our back-end" nor apparently require our users to re-install the app.

**Comment by cruzach** [comment]
Notifications to different experience IDs must be sent in different requests, so you will not see any errors if you batch your push notifications by experienceId.

I'm not sure I understand what you mean that a bug for push notifications can be triggered when rolling out updates to stores, could you explain that a little more?

**Comment by BillyIvy** [comment]
I am not the one that experienced that occurrence of this bug as my team has not rolled out any updates to our application.   From the discussion at https://forums.expo.io/t/push-notification-expo-server-error-push-too-many-experience-ids/31516/3, it seems that when a different developer from the original builds the updated version of the app for rolling out to the store any new device ID's will now be registered to a different project.  While I have not experienced this directly, it lines up with what my team is currently experiencing in testing for an update. 

If I have an array of Expo Push Tokens, how am I supposed to know which experienceID they belong to?  If the only solution is to do a try catch for an error that is bad especially for a system with thousands of tokens.

Why are there different experienceID's when developers are working on the same project?
Why is the experinceID associating with a different user than the owner in the app.json?

**Comment by cruzach** [comment]
The standalone builds, even when built by different team members on the same Expo team, will always have push tokens associated with the owner of app.json

In the past, push tokens associated with the different Expo users can make their way into a database when a developer is testing it locally with `expo start`, and is connecting to the same database/server as other developers, or the main production app, is. If this is the case, then those push tokens are safe to remove

**Comment by BillyIvy** [comment]
You say "in the past" running 'expo start' with multiple users could cause this.  Is there a fix for running the apps with `expo start`?  We are using 'expo start' for testing. That is likely what is causing errors in our test database.

**Comment by cruzach** [comment]
You should connect to a different development database/server when running your app locally with `expo start` to avoid this problem. As for tokens from different experiences that are currently there, you should implement logic that checks if a token is associated with the proper experienceId, and if it's not, remove it

**Comment by BillyIvy** [comment]
@cruzach 
Our developers are connecting to a test database and test servers when running the app locally.  We do not have the "too may experiences" error in our production database or on our production servers as they are isolated from development and testing.  Based on what you are saying, each developer would have to connect to a test database/server set-up for only that developer.  Meaning our test database that is supposed to allow different developers to collaborate and holds the devices ID's for batch push notifications gets polluted with different experience ID's because each developer has their own expo account.

e.g. Johnny is developing the application and runs a test that causes his device to be added to the test DB.  Timmy is developing a different functionality that uses the same DB.  When the batch push is to be sent it should send a push to the entire team for testing, but because Johnny and Timmy used `expo start` to locally test their different features, they updated the DB with deviceID's from different experience ids.  So the batch push fails, and throws the error "Too Many Experience Ids" 

Since the app.json has the "owner" attribute any developer on the team should be able publish or build the app and the experienceID's in production would all be from "owner/projectname", but this does not fix a major set back for development.  What is the way for developers to test applications that use batch push notifications?

**Comment by cruzach** [comment]
The ways teams are currently designed, it's generally better to allow each team member to run the app locally under their own username, rather than the `owner` username. You're right that this does mean that if you all connect to the same test database/server, you'll have push tokens from multiple projects (e.g. `@johnny/helloworld` and `@timmy/helloworld`). We're working on a better implementation for this to make it much easier and even more secure, but that will take time. For now, the best solution is to add logic which handles this scenario. For example, the error returns a mapping of project IDs to an array of the push tokens associated with them. remove the push tokens from the other project, and then retry

**Comment by bwesen** [comment]
Got bitten by this also. Yes please make this work more smoothly. Obviously I can send my pushes one-by-one, why should it fail when sending them in batches? This just seems like an artificial limitation (from an API-user perspective - I guess there are some underlying reasons for why it's like this... :).

If there was a way to get the "experience id" from the expo push token it would be easy to sort and split the pushes from our backend client.

Otherwise, the only entity that has that info is the expo server, so after receiving a batch, it could itself sort by experience id and do multiple "sub-batches" or whatever is necessary?

Doing it by error returns is workable but for every push of 100 (max batch size is 100) you have to get the 100 errors, re-sort by experience id according to the error return, then re-send the batches split up, then loop for every 100. So if I need to send to 100,000 users, and there is a serious spread of experience id's sprinkled over my user database (for whatever reasons), I need to do in the worst case N times the number of Expo API batch sends with N being the number of experience ids.

**Comment by cruzach** [comment]
> Obviously I can send my pushes one-by-one, why should it fail when sending them in batches?

Even sending pushes one-by-one, you'd still be sending push notifications to the wrong experience (e.g. `@developer/projectName` instead of `@team/projectName`)

You wouldn't receive 100 errors for a batch size of 100, you'd receive 1 error. You don't have to re-sort by experience ID, the error returns an object with them already sorted. The `details` object returned with the error will have a mapping of experience names to the push tokens associated with that experience, for example:
```
{
  "@developer/projectName": [array of push tokens],
  "@team/projectName": [array of push tokens],
}
```
So you can catch this error and only retry with the `@team/projectName` array of push tokens.

It would be better to avoid adding push tokens from separate experiences into your production database in the first place to avoid hitting this error at all in your production app

**Comment by bwesen** [comment]
> Even sending pushes one-by-one, you'd still be sending push notifications to the wrong experience (e.g. `@developer/projectName` instead of `@team/projectName`)

I don't understand this, I did exactly this and it worked fine (whereas the batched version doesn't). The pushes are only sent through an expo push token, you don't specify any experience id.

It seems the batch only complains that you mix tokens for different experience ids in the same batch, not that any particular experience id is invalid or so. This is what is so counter-intuitive.

> You wouldn't receive 100 errors for a batch size of 100, you'd receive 1 error. You don't have to re-sort by experience ID, the error returns an object with them already sorted.

Yes I know, but if there is one odd user per 100, you will have to resend that user for every 100, causing twice as many API calls for every run through the database. At the very least it's inefficient for the Expo server as well.

> It would be better to avoid adding push tokens from separate experiences into your production database in the first place to avoid hitting this error at all in your production app

In practice this is often not possible, as noted by other answers in this thread. Different teams do the apps and backend. For example I have no idea how the tokens are generated or how the expo apps are built or identified as different experience ids. At some point someone will by accident or intentionally change this id.

It simply doesn't make sense for this to work one-by-one but not in a batch :)

**Comment by Svarto** [comment]
@cruzach Ran into this problem just now, have a fix been thought of or will be introduced soon?

**Comment by cruzach** [comment]
Not sure I understand what you mean @Svarto , the fix is to only send push notifications for a single experience per batch

**Comment by Svarto** [comment]
@cruzach thanks for the quick reply! Just as noted, this is not practically possible for our development flow, so a way to handle this upfront rather than wait for the error and then correct would be great. Alternatively, just define which experience should take precedence even would help in our case.

**Comment by Billy-IV** [comment]
@Svarto The expo team has made it clear that they have not plan to solve this as they do not view it as a problem.  My solution was to have my team stop using expo and switch to pure react native.  It removed a lot of headaches and switching to google firebase for push notifications was not that hard.

**Comment by cruzach** [comment]
> Alternatively, just define which experience should take precedence even would help in our case.

This depends on which experience you are trying to send notifications to (we can't know ourselves if you'd rather send notifications to X or Y)

The best (and easiest) way to avoid this problem is to add code to your server that is something along the lines of:

```
sendNotificationsForProjectAAA(batch)

catch(e)
  if (e is "too many experience ids" error)
    for token in ArrayOfTokensAssociatedWithExperienceBBB // available in error details
      batch.remove(token)
    retry request
```

**Comment by Svarto** [comment]
@cruzach @Billy-IV thank you both! Very helpful and I really appreciate the quick replies on this!

**Comment by Billy-IV** [comment]
@cruzach 
The problem is a normal development flow is going to have individual developers using `expo start` or other methods for running and testing the expo project that creates `@developer-A/projectName` and `@developer-B/projectName`, and doing a try catch for a large batch of anything to divide them up by type is super impractical.

@Svarto 
Another solution I thought of depends on how your team is tracking push notifications but you could store with each ID the experience and query by those.  table e.g. 
`user          |   pushID            | experience ID
tom Jones | expo[d89hf49] | @dev-A/projectName`
You would have to custom build a way to generate the experienceID or you could have each dev track it in an environment file like an .env file.  I would recommend the latter.

**Comment by cruzach** [comment]
Setting the `owner` field _does_ change the experience ID in development (I just tested this, but let me know if you see different behavior- `console.log(Constants.manifest.id);`), so in the case of local development amongst different developers on the same project, you can address this by using [organizations](https://docs.expo.io/accounts/account-types/#organizations) and setting `owner: yourOrgName`

**Comment by edjiang** [comment]
We have the owner field set correctly in `app.json` but for some reason we're still getting tokens registered from other owners. Namely, `GitHub (robot)` which is registered from GH Actions.

Could this be a problem with Expo infrastructure? 

<img width="641" alt="image" src="https://user-images.githubusercontent.com/918770/114812490-f6edc480-9d64-11eb-8e4c-3b8634201408.png">

**Comment by cruzach** [comment]
> Could this be a problem with Expo infrastructure?

Most likely no, as we haven't received other reports of that behavior. I would make sure that all your deployments (both in development, staging, and prod) are all either under the same account, or you're connecting to separate databases, or you guard against this error by catching and removing the bad tokens

**Comment by edjiang** [comment]
> > Could this be a problem with Expo infrastructure?
> 
> Most likely no, as we haven't received other reports of that behavior. I would make sure that all your deployments (both in development, staging, and prod) are all either under the same account, or you're connecting to separate databases, or you guard against this error by catching and removing the bad tokens

Not sure how we could be publishing against an account called `@Github (robot)`, although we are using https://github.com/expo/expo-github-action to build & release, using a GitHub Token. 

We're guarding against the error and removing the bad tokens at the moment. It would be nice to have this documented, as well as the error returned in the same format as the Error Ticket.

**Comment by cruzach** [comment]
This is documented- https://docs.expo.io/push-notifications/sending-notifications/#request-errors

As for the `@Github (robot)` account, I'm not really sure what's happening there, but a couple questions:
1. Do you use the `owner` field in app.json?
2. Do you use [Expo bot users or access tokens](https://docs.expo.io/accounts/programmatic-access/#organizations-bot-users--access-tokens)?

**Comment by edjiang** [comment]
Sorry, my bad. Was only looking at ticket errors.

1. Yes we use the owner field, as we're using an org account.
2. Yes, we're using a bot access token to run `expo build:ios` / android. Could that be why?

**Comment by edjiang** [comment]
I decompressed the ipa/apks for the latest builds on Expo 41, and I didn't see any evidence that the `app.manifest` file was written improperly. Will keep monitoring!

**Comment by the-simian** [comment]
It would be great if we could send a batch of tokens to an endpoint and they are not sent but returned and grouped like the `details` object of the returned error.
 
Then we could go get the experience IDs and maybe do some sort of migration, or just check them beforehand by hitting a lightweight endpoint.

The problem with the existing design is you need to try to send a push before you know there's a problem. Much in the way we can validate if something IS a token, we should be able to introspect the token before committing to a push.

I agree with the engineers that have pointed out that this is a design concern. There is a reason that nearly every developer that's "runs into this". Is at first frustrated and confused.  

I implore you to reconsider the fact that this might not be unavoidable for some organizations at worst and at best will be discovered "by surprise" by any orgs that ultimately do work around it. There's a lot of very plausible reasons why there could be multiple experience id's for a project over its lifespan. 

One example is if the software is sold/IP changes and the organization changes, but there's historical data in the database that was unaware it needed to be segmented by experience just to work. Another, that has been brought up in situations with multiple developers or CI bots. Also, situations where the additional work of spinning up multiple environments just to deal with tokens isn't feasible time-wise or cost-wise. Also, situations where the experience ID is largely irrelevant across multiple applications, and you're segmenting push notifications in totally other ways. There are lots of situations.

anyways, please consider making an introspection endpoint. I think most folks are happy to 'prebatch' the tokens if there's a way to ascertain the experienceID without trying and failing first.

**Comment by chris-snow** [comment]
We have run into the same issue - I would just like some clarity if all possible (sorry for replying on a closed issue).

Do all the tokens need to be from the same experienceId for each **message** or do all tokens need to be from the same experienceId when using expo.sendPushNotificationsAsync?

i.e. do I have to ensure that the "chunk" itself contains the same experienceIds?

We are attempting to re-add the mismatched tokens back to our queue for processing, but if they then get chunked again with the other message then I can only assume we will experience the same issue.

**Comment by sealabcore** [comment]
We are running into this same issue. We have a beta app and a production app that both point to the same production database. The two different experiences are generating different tokens that can't be sent together. 

We need a way to query which experience a token is related to so we can group them before hitting the push endpoint. 

Going through the details response works but that means the first request will fail, and any future requests will fail when unknown tokens come in where we don't know the experience id. So that means the endpoint will forever intermittently work if we have two experiences using the same database.

Or, you could group and send them by experience on the expo servers and stop returning an error. You are already grouping them to display the error, so why not just send the push notifications across multiple experiences?

**Comment by Billy-IV** [comment]
@sealabcore 
Hello, the best I can offer from monitoring this issue evolve over the last ~3 years is this:  

Make sure you have a matching owner field in the app.json for any build that will be targeting the same environment or database table.  One improvement that was made is that the owner field is supposed to affect the experienceID no matter where it is built.  A way to help manage that is using an Org Account.  Admittedly both these changes were made after my team moved away from Expo.  So I cannot confirm that they would fix the deployment and experienceID issue for your team, but that is the place to start.

The trend has been prevention rather than providing a solution after this issue has happened to someone.  The above changes are emblematic of that.  They are supposed to reduce the likelihood of this issue.

As far as the "please fix this query to just do the grouping on Expo's side" request, they have not done that in 3 years, and based on what they have released that does not seem likely.  (Not 100% sure why as they are sorting them.)  For the "add another one that lets us group them before the push endpoint" request, the answer is that the push endpoint essentially already does this.  I don't know if there is anything else that does this.  Perhaps @expo can confirm.  So the best option there is to do what you said:

> Going through the details response works but that means the first request will fail, and any future requests will fail when unknown tokens come in where we don't know the experience id. So that means the endpoint will forever intermittently work if we have two experiences using the same database.

I have advised previously using this to add an attribute in your table that would track the experienceID's.  You could update the table when you send the push notifications.  This basically makes push notifications into a many-step process.  

```
1) Send Production 
  2) Send Beta 
  3) Send unknown
  4) Get error
  5) Resend the first group in the error message and update the table
  6) Resend the second group in the error message and update table
```
  
  Ironically it could be more simple, more efficient, and faster to not track the experiences, but that depends on your system.
  
```
  1) Send with experienceID unknown
  2) Get error
  3) Resend the first group in the error message
  4) Resend the second group in the error message
```
  
Honestly, I generally advise people to switch to something other than Expo for the push notifications mainly due to these kinds of issues.  Please let me know if you have any questions.

**Comment by IsaiaPhiliph** [comment]
In case anyone has this issue, here is the code I used to fix it: 

```javascript
  const chunks = expo.chunkPushNotifications(messages);

  (async () => {
      for (let chunk of chunks) {
          try {
              await expo.sendPushNotificationsAsync(chunk);
          } catch (error) {
              if (error.code === 'PUSH_TOO_MANY_EXPERIENCE_IDS') {
                  console.log("Detected PUSH_TOO_MANY_EXPERIENCE_IDS error, reading details to separate by project")
                  for (const [key, value] of Object.entries(error.details)) {
                      const expo_tokens = value;
                      const messages = expo_tokens
                          .map((tk) => ({
                              to: tk,
                              title,
                              body,
                          }));
                      const chunks = expo.chunkPushNotifications(messages);
                      (async () => {
                          for (let chunk of chunks) {
                              try {
                                  await expo.sendPushNotificationsAsync(chunk);
                              } catch (error) {
                                  console.error(error);
                              }
                          }
                      })();
                  }
              } else {
                  console.error(error);
              }
          }
      }
  })();
```

**Comment by edi** [comment]
Additionally to @IsaiaPhiliph's solution, here's my cleaner version, of the same implementation, in a recursive manner.

```javascript
/**
 * Send push notification to manager's devices
 * @param {array} tokens List of tokens to send notification to
 * @param {string} message Notification message
 */
export const pushNotification = async (tokens, message) => {

  if (!tokens.length)
    return false

  let messages = []

  tokens.forEach(token => {
    messages.push({
      to: token,
      body: message
    })
  })

  // split into chunks
  const chunks = expo.chunkPushNotifications(messages)

  for (let chunk of chunks) {
    try {
      await expo.sendPushNotificationsAsync(chunk)
    } catch (err) {

      if (err.code === 'PUSH_TOO_MANY_EXPERIENCE_IDS') {
        for (const tokens of Object.values(err.details))
          await pushNotification(tokens, message)
      } else
        console.log(err.message)
    }
  }

}
```

The above can be called as follows:

```javascript
await pushNotification(['expoPushToken1', 'expoPushToken2', '...etc' ], 'This is a test notification')
```

Feel free to adjust the params to include a title, or swap it with an object-based config. I just think it's cleaner to do it recursively.

Regards

**Comment by andordavoti** [comment]
> It would be great if we could send a batch of tokens to an endpoint and they are not sent but returned and grouped like the `details` object of the returned error.
> 
> Then we could go get the experience IDs and maybe do some sort of migration, or just check them beforehand by hitting a lightweight endpoint.
> 
> The problem with the existing design is you need to try to send a push before you know there's a problem. Much in the way we can validate if something IS a token, we should be able to introspect the token before committing to a push.
> 
> I agree with the engineers that have pointed out that this is a design concern. There is a reason that nearly every developer that's "runs into this". Is at first frustrated and confused.
> 
> I implore you to reconsider the fact that this might not be unavoidable for some organizations at worst and at best will be discovered "by surprise" by any orgs that ultimately do work around it. There's a lot of very plausible reasons why there could be multiple experience id's for a project over its lifespan.
> 
> One example is if the software is sold/IP changes and the organization changes, but there's historical data in the database that was unaware it needed to be segmented by experience just to work. Another, that has been brought up in situations with multiple developers or CI bots. Also, situations where the additional work of spinning up multiple environments just to deal with tokens isn't feasible time-wise or cost-wise. Also, situations where the experience ID is largely irrelevant across multiple applications, and you're segmenting push notifications in totally other ways. There are lots of situations.
> 
> anyways, please consider making an introspection endpoint. I think most folks are happy to 'prebatch' the tokens if there's a way to ascertain the experienceID without trying and failing first.

@cruzach is there any plan to make an endpoint like this?

Another consideration could be to add something like FCM has with validate_only (was dryRun previously), this way we could do testing without worrying about sending push notifications to all our users.

I'm running into this issue myself, and haven't found a proper way around this.
