### ISSUE TITLE
[ImagePicker] return height and width on Web

### ISSUE THREAD

**Issue by jjg77** [expo/expo#6788]
SDK 35

ImagePicker results on Android:

```
pickerResult: Object {
  "base64": "/9j/4AAQSkZJRgABAQAAAQABAAD/4gIoSUNDX1BST0ZJTEUAAQEAAAIYAAAAAAIQAABtbnRyUkdC
```

ImagePicker result on web:

`pickerResult: {cancelled: false, uri: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQAB`

I think the web output is better.  Can they be made to return the same output?

For my use case, where I use ImageNative.getSize() post upload, I need the "data:" part of the URI.

**Comment by brentvatne** [comment]
you can prepend the data uri to it manually if you want to. web does not output a `base64` field, only `uri` which is a base64 encoded data uri. the `uri` result on web is not actually a very good api right now in my opinion, because it doesn't play well with the web share api, for example. maybe it should return a `File` object or a `FileList` instead and not a uri.

anyhow, are you referring to https://facebook.github.io/react-native/docs/image#getsize when you say `ImageNative.getSize()`? if so, i don't see why you need to use this. on ios and android you get the width and height returned when you pick an image

**Comment by brentvatne** [comment]
you can prepend the data uri to it manually if you want to. web does not output a `base64` field, only `uri` which is a base64 encoded data uri. the `uri` result on web is not actually a very good api right now in my opinion, because it doesn't play well with the web share api, for example. maybe it should return a `File` object or a `FileList` instead and not a uri.

anyhow, are you referring to https://facebook.github.io/react-native/docs/image#getsize when you say `ImageNative.getSize()`? if so, i don't see why you need to use this. on ios and android you get the width and height returned when you pick an image

**Comment by jjg77** [comment]
You are right, on mobile do get width and height.  
But on web, the width and height are coming back as 0 and 0.
For now I'm doing this to append the data uri:

```
if (!uri.startsWith('data:')){
    uri = "data:;base64," + uri;
  }
```

**Comment by brentvatne** [comment]
this is an inconsistency caused by a limitation in the browser api as far as i know. if you know how to have imagepicker return a width and height on web please open a pull request to add that to expo-image-picker!
