### ISSUE TITLE
DocumentPicker Output Inconsistent Mobile vs Web

### ISSUE THREAD

**Issue by jjg77** [expo/expo#6789]
SDK 35

android

```
pickerResult: Object {
  "name": "menu.pdf",
  "size": 178600,
  "type": "success",
  "uri": "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%name%252Faog/DocumentPicker/addef52c-3d59-4d5d-b584-b9be6b337d48.pdf",
}
```
web

`pickerResult: {type: "success", uri: "data:application/pdf;base64,JVBERi0xLjMKMyAwIG9iag…vSW5mbyA3IDAgUgo+PgpzdGFydHhyZWYKMTU5MQolJUVPRgo=", name: "history.pdf", file: File, lastModified: 1575519155785, …}`

I prefer the web output that is base64 because I'm uploading to s3 after.  Will have to figure out how to upload the local file URI.

**Comment by brentvatne** [comment]
https://github.com/expo/examples/tree/master/with-formdata-image-upload/app

**Comment by cruzach** [comment]
for the `uri` field differences, I believe Brent answered it in [your other issue on the same topic in regards to ImagePicker](https://github.com/expo/expo/issues/6788#issuecomment-575444605)

Just a note @jjg77 - issues are much more likely to be addressed quickly if you fill out the entire bug report template. Keeping this issue open since we should either be consistent across platforms or document those differences in the meantime

**Comment by EvanBacon** [comment]
closing due to platform limitation.
