### ISSUE TITLE
Update google-sign-in docs for non-Firebase users?

### ISSUE THREAD

**Issue by raRaRa** [expo/expo#6850]
Hi,

I was just reading over docs for Google Sign In at: https://docs.expo.io/versions/latest/sdk/google-sign-in/

I noticed that the documentation is very dependent on Firebase, is this a hard requirement? In my use case I don't want to use Firebase. Can I use the following config instead:

```
"android": {
    "package": "com.mycompany.myapp",
    "config": {
        "googleSignIn": {
            "reservedClientId": "<YOUR_ANDROID_CLIENT_ID>"
        }
    }
},
```

Because the docs explain that the reservedClientId for Android will be automatically fetched from the google-services file generated by Firebase, which is again something I don't have since I'm not using Firebase.

Thanks!

**Comment by expjess** [comment]
Hi! I don't _think_ it's a hard requirement (we outline this particular method because it's pretty straightforward and most people are using Firebase), but it's possible that something has changed around whether Google has rolled Sign-In into Firebase? 

If you try out that config and it works, and you think there's a clear / streamlined way to build it into the google-sign-in docs, definitely feel free to shoot a PR our way!

**Comment by raRaRa** [comment]
Hey thanks for the quick response @expjess 

I tried using `reservedClientId` for Android but when I create a build I get the following error:
```
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v36.0.0/workflow/configuration/
 • Field: android.config.googleSignIn - should NOT have additional property 'reservedClientId'.
```

It feels like it was designed with Firebase in mind. I'll try creating my own `google-services.json` to see if that helps.
