### ISSUE TITLE
Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':expo-mail-composer:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by saidhappy010** [expo/expo#6867]
I ejected my expo project at expokit and I run it on android studio and I got this error:
>Caused by: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':expo-mail-composer:compileDebugJavaWithJavac'.

please, how could we solve this problem.
thanks

**Comment by cruzach** [comment]
We need you to fill out the full bug report template so that we can help you troubleshoot effectively. 

I suggest trying to learn more about what that exception - - means. here are a few threads where people were able to troubleshoot similar problems:
- https://github.com/facebook/react-native/issues/5528
- https://stackoverflow.com/questions/49631154/compilation-failed-org-gradle-internal-exceptions-locationawareexception

Also- a lot of Android Expokit issues end up being caused by using the wrong version of gradle. Make sure you **do not** upgrade gradle when Android Studio prompts you to. Expokit ships with the appropriate gradle version
