### ISSUE TITLE
Payments docs don't cover bare-workflow

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo#6922]
We currently only cover the ExpoKit workflow.

**Comment by chris-aeviator** [comment]
This is very confusing, the docs mention payments are only supported in the bare workflow while this issue mentions you only support ExpoKit workflow?!

**Comment by chris-aeviator** [comment]
also this issue is more than one year old?

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
