### ISSUE TITLE
Very large size of a simple app

### ISSUE THREAD

**Issue by Pravandan** [expo/expo#693]
When I make a simple app I get a very large size of the app around 25 mb, any way of fixing it?

**Comment by xcarpentier** [comment]
Hello,

I'm not an Expo Guy but I use it a lot... and no nothing can thining your standalone app easely (maybe search for unused dependencies with depcheck?)

But a feature request exist to change the architecture of Expo to plugable one: https://expo.canny.io/feature-requests/p/native-plugins

May help to decrease the size of the app and much more... like create new natives plugins... 😉

Vote for that!

**Comment by quinlanj** [comment]
Hi @Pravandan, at the moment we dont have a way to make your app smaller (see https://docs.expo.io/versions/latest/introduction/why-not-expo.html#if-you-need-to-keep-your-app-size-extremely-lean-expo-may-not-be-the-best-choice-the-size-for-an-expo-app-on-ios-is-approximately-25mb-and-android-is-about-20mb-this-is-because-expo-includes-a-bunch-of-apis-regardless-of-whether-or-not-you-are-using-them--this-lets-you-push-over-the-air-updates-to-use-new-apis-but-comes-at-the-cost-of-binary-size-we-will-make-this-customizable-in-the-future-so-you-can-trim-down-the-size-of-your-binaries)

But please do vote for the feature on expo.canny.io!
