### ISSUE TITLE
Expo crashes on Android with no errors

### ISSUE THREAD

**Issue by impactcolor** [expo/expo#6976]
It appears that the following method makes my app crash.
  ```
  orderPhotoAlbum() {
        return new Promise((resolve, reject) => {
        const { currentOrderId } = this.state;
        const albumResult = MediaLibrary.getAlbumAsync(currentOrderId);
        albumResult.then(result => {
          if(result) {
            resolve(result);
          } else {
            resolve(this.createPhotoAlbum(currentOrderId));
          }
        });
      });
    }
```
I don't have any logs because there are no error logs being logged on to the cli console like normally happens.

Also this doesn't show any errors pertaining to the crash:
`adb logcat *:S ReactNative:V ReactNativeJS:V`

I'm running this on android simulator and testing on a real android device.  When I run the above the app closes, again with no errors.  Any idea what's going on or how I can debug this further?

**Comment by cruzach** [comment]
Hi! We keep github reserved for bug reports, for general help with React Native or Expo, you're better off posting on our [forums](https://forums.expo.io/) or Stack Overflow. If you're running this in the Expo Client, and the Expo Client itself is crashing, then this could be a bug and a reproducible example would be great! If this is a standalone app, then any fatal JS errors will crash the app, and you should run it in development to debug

Otherwise, it's hard to help you with just what's shared here, since it's not a full repro. For instance, I ran essentially the same thing myself and it worked:
```
return new Promise((resolve, reject) => {
      const albumResult = MediaLibrary.getAlbumAsync("WhatsApp");
      albumResult.then(result => {
        if (result) {
          console.log(result);
          resolve(result);
        } else {
          resolve("nothing");
        }
      });
    });
```

**Comment by impactcolor** [comment]
Ok thank you, I posted it here cause it was report as a bug here:
https://github.com/expo/expo/issues/5637
According to that issue it says it's going to be "resolved in the latest release" but nothing else was posted on it.  @cruzach
