### ISSUE TITLE
How to remove “android.hardware.location” permission request from ejected Expo project?

### ISSUE THREAD

**Issue by MarcelloGrita** [expo/expo#6979]
I have a React Native Expo project that started out using the Expo "managed workflow". However, since then I have ejected out of the managed workflow (while still using some expo modules).

The issue I'm experiencing is that Expo seems to have added arbitrary permission requests to my Android app. I must remove this particular permission request from the app: android.hardware.location.

I've tried many ways to remove it in my `AndroidManifest.xml `file, for example:

`<uses-permission tools:node="remove" android:name="LOCATION_HARDWARE" />`
`<uses-permission tools:node="remove" android:name="ACCESS_COARSE_LOCATION" />`
`<uses-permission tools:node="remove" android:name="ACCESS_FINE_LOCATION" />`
`<uses-feature android:name="android.hardware.location" android:required="false" tools:node="remove" />`
But in the end the bundled Android app still requests the android.hardware.location permission.

How can I remove it before bundling the app?

**Comment by cruzach** [comment]
In a bare workflow project, you have total control over everything, including the permissions your app requests. I'm not too familiar with this, but anyways I believe this question fits better on SO (which, it looks like [you've already posted it on](https://stackoverflow.com/questions/60005741/how-to-remove-android-hardware-location-permission-request-from-ejected-expo-p0) 👍 ) since we like to keep github reserved for bug reports

**Comment by subhadippramanik** [comment]
Removed `expo` from `package.json` as suggested in the external link. But there is a new warning while running `expo build:android`

`  expo build:android currently only supports managed workflow apps.
If you proceed with this command, we can run the build for you but it will not include any custom native modules or changes that you have made to your local native projects.
Unless you are sure that you know what you are doing, we recommend aborting the build and doing a native release build through Android Studio.`
