### ISSUE TITLE
npm ERR code ENOENT

### ISSUE THREAD

**Issue by Sreesankar-G-Warrier** [expo/expo#6981]
when I run npm start command it shows some err msgs as well as for npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/naver/hammer.js.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\srees\AppData\Roaming\npm-cache\_logs\2020-02-06T11_00_37_506Z-debug.log

**Comment by cruzach** [comment]
Hi! I'm going to close this, since there's not enough information to help debug here, but there have been similar errors posted on the expo-cli github repo (like [this issue](https://github.com/expo/expo-cli/issues/47)) and people have suggested different methods to fix it. Iirc this could be correlated to your node version, or some others have been able to fix it by just re-installing dependencies with `npm install`

If you still can't resolve this, and can provide your environment and a full bug report, please open an issue on the [`expo-cli` repo](https://github.com/expo/expo-cli) 😄
