### ISSUE TITLE
[expo-safe-area] Unifying the Safe Area related APIs

### ISSUE THREAD

**Issue by LinusU** [expo/expo#7097]
Hey 👋 

I was looking thru the documentation on how to use the Safe Area related APIs, and they came across as quite messy.

First there is [SafeAreaView](https://docs.expo.io/versions/latest/react-native/safeareaview/) which only supports iOS.

Then there is [SafeAreaContext](https://docs.expo.io/versions/latest/sdk/safe-area-context/) which exposes a hook (`useSafeArea()`) and a context consumer. This despite there being anything that would need a context here as far as I can see? A context is used for scoping variables to a sub-set of the render tree, but the Safe Area insets is a global value that is the same throughout the app. This makes the hook annoying to use since you need to add a provider in the root of your app.

-----

My suggestion is a new package, `expo-safe-area`, that exposes two APIs:

A standalone hook, `useSafeArea()`, that doesn't need any context provided to it, and that correctly triggers updates when the Safe Area changes (e.g. when the device orientation changes).

A view, `<SafeAreaView />`, that makes sure that it's `children` are within the Safe Area, implemented with the aforementioned hook.

Both of these APIs would work on iOS, Android & Web.

-----

Would you be open to a pull request that adds a new `expo-safe-area` package as described above?

**Comment by brentvatne** [comment]
There is actually a library that does exactly what you describe: https://github.com/react-native-community/react-native-safe-area-view

Notice that we re-export the tools from react-native-safe-area-context: https://github.com/react-native-community/react-native-safe-area-view/blob/b84445b13d26fd8c5a990175becf340b0179b140/src/index.tsx#L23

And we also export a SafeAreaView component that uses that API: https://github.com/react-native-community/react-native-safe-area-view/blob/b84445b13d26fd8c5a990175becf340b0179b140/src/index.tsx#L54

It could use some help for documentation and maintenance though, are you interested in contributing to it?

**Comment by LinusU** [comment]
Thanks for taking the time to answer @brentvatne, the problem I have with the `useSafeArea` that is exported from `react-native-safe-area-context` is that it requires a provider to be put higher up in the render tree.

My end goal is to have a `useSafeArea()` that I can use without any prior setup, that doesn't require any special context be passed to it.

I also think that there would be a big gain in having a `expo-safe-area` package that can easily be used both inside and outside of expo, that would be easily discoverable and be the most up-to-date implementation.

I don't see any benefit by having a provider of the safe area, and passing it via context, but maybe I'm missing something?

**Comment by brentvatne** [comment]
It's a necessary implementation detail because we need to get the insets from an actual view, so the provider is actually more than just a typical context provider, it also renders a view that we need to have in the app in order to get this information. We could add this to every Expo managed app by adding it to [withExpoRoot](https://github.com/expo/expo/blob/master/packages/expo/src/launch/withExpoRoot.tsx) but this is not used in bare workflow and so the instruction would be required. [We tried to upstream the implementation of safe area context to react-native itself](https://github.com/facebook/react-native/pull/20999) but we were unable to for a variety of reasons you can see in that thread.

Open to ideas for how we can automatically add this provider and make people's lives easier!

**Comment by LinusU** [comment]
> It's a necessary implementation detail because we need to get the insets from an actual view [...]

I was thinking that since this is already a native package it should be possible to programatically query for the insets from the native side, which I thought should work without actually rendering a view (need to double check that though, but it really should be possible).

When I looked thru the code it seemed like it became that way since it copied the native implementation from the React Native project, which was built to only provide a view since it was created before hooks was a thing. Again, I might be misstaken here though...

I'm going to read thru the thread you posted, and also try and create an actual implementation that does what I want ☺️

**Comment by brentvatne** [comment]
the only way to query the safe area insets programmatically on iOS is from a view. the original implementation that @janicduplessis did for the upstream PR was to use the root view for this, but because it was too difficult to land it we pulled it into this separate library and opted for using a provider view instead
