### ISSUE TITLE
[expo-google-sign-in][Android][bare workflow] GoogleSignIn doesn't work on Android in bare React Native app

### ISSUE THREAD

**Issue by yaroslavnikiforov** [expo/expo#7210]
### Environment

| software         | version
| ---------------- | -------
| expo | detached to bare RN app
| react-native     | 0.61.4
| expo-google-sign-in     | 8.0.0
| device    | Redmi Note 7
| platform OS | Android 9

### Steps to Reproduce

After detaching from Expo SDK 36 to bare RN workflow (expo eject) and after installing `expo-google-sign-in` according to the instruction ([npmjs.com](https://www.npmjs.com/package/expo-google-sign-in#installation-in-bare-react-native-projects)) GoogleSignIn doesn't work.
We managed to make it work on iOS with some additional to the instructions in README.md setup - by adding array of reversed client IDs to the Info.plist:
`<dict>
    <key>CFBundleTypeRole</key>
    <string>Editor</string>
    <key>CFBundleURLName</key>
    <string>GoogleSignIn</string>
    <key>CFBundleURLSchemes</key>
    <array>
	<string>*****</string>
	<string>*****</string>
	<string>*****</string>
	<string>*****</string>
     </array>
</dict>`
But failed to make it work on Android. In the Android project in addition we set up Google Services Gradle plugin according to the instruction [(developers.google.com)](https://developers.google.com/android/guides/google-services-plugin) - updated build.gradle files and added google-services.json in the android/app directory. When build is finished it generates values.xml file in android/app/build/generated/res/google-services/release/values. We also have set SHA certificate fingerprint for the project in Firebase console. 

### Expected Behavior

Should work as before ejecting after setup instructions for the npm package.

### Actual Behavior

GoogleSignIn.signInAsync() returns response with idToken equals to null. Here is the response object:
![Screenshot_2020-02-27-15-56-18-930_life stroller preggers](https://user-images.githubusercontent.com/42115630/75464296-ab752d00-598f-11ea-8718-0629271d0426.jpg)

If there should be some steps, which were missed, please let us know.

ping @EvanBacon

**Comment by serhiipalash** [comment]
Hi @EvanBacon ! Can you please help us with this bug in bare workflow? 

The main problem is that on Android in bare workflow `expo-google-sign-in` returns `idToken` equal to `null`.  It's a known issue with Google Sign In on Android with other libraries too and from what we read it is related to incorrect `google-services-plugin` setup that leads to missing `web_client_id` in `/values/strings.xml`, but we build the bundle and during the build we see this value is added, so it's something else.

Did you ever experience this bug? Can you give us some tip why it doesn't work on Android (iOS works fine in both workflows)?

Here is our `build.gradle`
<img width="588" alt="Screenshot 2020-04-09 at 11 52 28" src="https://user-images.githubusercontent.com/14208343/78876952-ce97ff80-7a58-11ea-9ad7-0eae95ebc3a6.png">

Maybe it's because of not composable with `expo-google-sign-in` Google Services Plugin version? You have it different in Expo example-app for bare workflow https://github.com/expo/expo/blob/master/apps/bare-expo/android/build.gradle#L27

Please help us :) We are out of ideas why it doesn't work.

**Comment by michaek** [comment]
While this is filed as an issue affecting ejected apps, I'm also observing what appears to the the same behavior (successful login, present accessToken, null idToken) for standalone Android builds from Expo. My app bundle build distributed through the Play Store does not display this issue, but my apk build installed via `adb install` does. I'm using the appropriate SHA1 signatures for each build, or the sign in process would not be working at all.

**Comment by michaek** [comment]
I don't know whether the issue I described above was transient, or whether this change fixed it: I added an (unused) iOS app to my Firebase config and replaced my google-services.json. After rebuilding, I'm seeing an idToken. I'm sure that's the only change I made, as I inspected the diff of the config file.
