### ISSUE TITLE
Show download progress for published projects in Expo client

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#7248]
We should let people see if the bundle is downloading or being loaded from cache, related: https://github.com/expo/expo/issues/7247

**Comment by SleeplessByte** [comment]
(Consider _not_ doing this during splash, but before, because otherwise the splash size becomes non-deterministic).

**Comment by brentvatne** [comment]
by non-deterministic you mean that it will be different between expo client and standalone apps?

**Comment by SleeplessByte** [comment]
Currently the bar is not necessarily present, based on the current cache, and based on the mode.

This adds additional variables indeed, and depending on the launch method, and connection and cache become even less predictable.

Personally I would love the bar at the bottom to become an overlay, so that the splash screen is always the same size, that would completely remove this argument.
