### ISSUE TITLE
npm ERR! peer dep missing

### ISSUE THREAD

**Issue by julesmoretti** [expo/expo#726]
Expo is throwing the following:

```
npm list --depth=0 
@logitech/pavarottisetup@1.0.0 /Users/jmoretti/Git/logitech/ux-smarthome/PavarottiSetup
├── expo@21.0.2
├── react@16.0.0-beta.5
└── react-native@0.49.1

npm ERR! peer dep missing: react@>=15.4.0, required by react-native-branch@2.0.0-beta.3
npm ERR! peer dep missing: react@> 15.0.0, required by react-native-gesture-handler@1.0.0-alpha.22
npm ERR! peer dep missing: react@16.0.0-alpha.12, required by react-native-svg@5.3.0
```

Things that I did to get there with no errors:

created a new folder
npm init
npm i --save react-native
npm i --save react@16.0.0-beta.5 
npm list --depth=0  

```
├── react@16.0.0-beta.5
└── react-native@0.49.1
```

then `npm i --save expo` and I get the above error...

Thanks for your help with this.

Other issues linked to this:
https://github.com/facebook/react-native/issues/16174
https://github.com/facebook/react-native/issues/16120
https://github.com/react-community/create-react-native-app/issues/420

**Comment by jayeszee** [comment]
Seems like your react-native-svg requires react 16.0.0-alpha.12 why are you using beta.5? I believe expo only supports alpha.12 right now.

**Comment by julesmoretti** [comment]
@jayeszee This is a fresh setup using only `react-native` and `react`.. so no `react-native-svg` involved at this point. Try it yourself and let me know.

**Comment by jimmylee** [comment]
Try using our fork of React Native: `"react-native": "https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz"`

**Comment by julesmoretti** [comment]
@jimmylee - I am not sure I follow? As a first time repo creation. I expect the ability to create a react-native virgin environment to be flawless, but that is currently not the case.

The expected flow is to use `create-react-native-app` which does not work.

So the next best thing is to try to create the repo from scratch, hence the npm init, npm install react-native, npm install react, npm install expo (which crashes)....

So not sure how much more info you need as the issue seems to be pretty explicit to me.

**Comment by jimmylee** [comment]
Oh sorry I must have misunderstood,

I was assuming that you wanted to use Expo / ExpoKit in a detached project. But I wasn't 100% sure because you didn't share your full intent, If my eyes don't deceive me: all you shared was that something wasn't working and I thought I was clever by offering a potentially "quick" solution. I am sorry about that @julesmoretti, I will be more thoughtful next time.

Here are some follow up thoughts:
 - If you want to use `react-native` without Expo I think this is the wrong place to raise that issue. Again I don't know, I'm just guessing and you should tell me.
 - You can try `yarn` if `NPM` is giving you issues. You'll need to have Node v6 or later on your machine. Would you like some guidance on that?
 - Documentation says that you should be using npm v3, v4. Can you double check for me? I'd like to help as much as possible.

**Comment by dikaiosune** [comment]
Hi! I'm not sure what the bug report here is exactly, but since you're referring to a CRNA issue I'm assuming that you're just raising the same issue in multiple locations. Please see my reply at ﻿https://github.com/react-community/create-react-native-app/issues/420#issuecomment-334882447 and please don't spam multiple repositories with identical reports.

**Comment by julesmoretti** [comment]
@dikaiosune wow dude, your quite a champ... locking me out of my own issue. 

I dont appreciate at all you calling my efforts to track down issues as spamming, when specific individuals have explicitly asked me to open new issues in other repo's. Again I dont think that would have happened if you had taken the time to read the threads.

No you are closing these issues like they are solved, but they are resolved, your just giving me an answer that does not resolve anything, which in short is wait a month... I dont think thats the purpose of issue tracking but rather to unlock blockers.... Not being able to run a simple react-native app from scratch is a pretty severe blocker.

@jimmylee - thank you for your response I will try out the `yarn` I do have Node V6 so will see.

**Comment by dikaiosune** [comment]
@julesmoretti I offered an explanation and a solution, which you apparently did not read. I've also replied to https://github.com/react-community/create-react-native-app/issues/425.
