### ISSUE TITLE
Make it possible to use Hermes in standalone apps

### ISSUE THREAD

**Issue by tsapeta** [expo/expo#7267]
As a first step, we'd like to allow users to opt in for using Hermes in their standalone apps. We will probably need to add an app.json field and make clear documentation for how to use this and common pitfalls encountered when switching to Hermes from JSC (since developers will not have the opportunity to test this in the Expo client).

**Comment by brasilikum** [comment]
Any updates on this? I found it impossible to know if with expo 39 and bare workflow:
- can you use it at all?
- does it work with expo updates?

**Comment by brentvatne** [comment]
you can use it in bare workflow, we do not support hermes for expo-updates yet though

**Comment by tonycoco** [comment]
Is there any progress on updating `expo-updates` to be compatible with [Hermes](http://hermesengine.dev)? I'd love to help.

**Comment by brentvatne** [comment]
@tonycoco - we haven't worked on that yet, we plan to get started on it around the beginning of may. it might be difficult for an external contributor to get involved on this before then because we won't have a lot of bandwidth to support you, but if you'd like to explore it for your own curiosity and share your findings then i would encourage that :)

**Comment by tonycoco** [comment]
Biggest problem is possibly shipping different packages for updates depending on if the client needs a Hermes compat one or not. That seems like it might require some infrastructure in the Expo side. Is that mechanism open-sourced somewhere? (lazy question, but I just need some direction pointing)
