### ISSUE TITLE
 iOS: There was an error with this build.

### ISSUE THREAD

**Issue by koushikmohan1996** [expo/expo#741]
While I was trying build IOS , got stuck with this error. "exp build:ios -c" doesn't solve the problem. Any Help?  
Build ID: 4b089bc2-d0e1-454c-bfd8-07600b7187a1

**Comment by jimmylee** [comment]
Hey it looks like you had the following bugs:

"(node:56085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: iOS icons must be square, the dimensions of AppIcon1024x1024.png are 1013,1024"
"message": "(node:56085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: iOS icons must be square, the dimensions of AppIcon20x20@2x.png are 39,40"

I would try the build again, because we recently fixed some bugs that caused this issue. But there may be a chance that you don't have the right icon sizes. Let us know how it goes.

**Comment by koushikmohan1996** [comment]
Changing the icon fixed the issue. Thank you so much

**Comment by dragonwong** [comment]
@jimmylee May I know where can I get these messages?

> "(node:56085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: iOS icons must be square, the dimensions of AppIcon1024x1024.png are 1013,1024"
"message": "(node:56085) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: iOS icons must be square, the dimensions of AppIcon20x20@2x.png are 39,40"

**Comment by mikeumus** [comment]
Tip*, **don't forget to start out with square dimensions in your `app.png`** 

From which all your app icons will be generated or you might end up on this page wondering where you'ree getting the above errors.
