### ISSUE TITLE
Update react-native-maps to 0.16.x

### ISSUE THREAD

**Issue by joelbowen** [expo/expo#749]
Is this update on the roadmap? There are a number of [improvements](https://github.com/airbnb/react-native-maps/blob/master/CHANGELOG.md) including performance improvements for custom markers and minZoom / maxZoom restrictions which is what I am in need of right now.

Thanks,

**Comment by tcdavis** [comment]
Will be upgraded to 0.17.0 in SDK 22

**Comment by rishabhbhatia** [comment]
@tcdavis Hi Thomas, react-native-maps v0.17.0 Adds support to animateToBearing and animateToViewingAngle which is an urgent requirement to us. Is there a way I can bump the maps version myself & when is the expo sdk version 22 expected?

**Comment by ide** [comment]
Expo SDK 22 has been released so you can upgrade to that. In general you can't bump the maps version yourself because it relies on native code.

The more developers write pure JS modules and the more that Expo provides lower-level operations that let people write more pure JS modules, the less common this situation will be but it needs to be a community effort.

**Comment by rishabhbhatia** [comment]
@ide Thanks James upgrading to the new expo removes my project bottleneck. Big thank you to everyone at expo, have a great day.
