### ISSUE TITLE
EXGLView - compilation issue

### ISSUE THREAD

**Issue by theranjali-nilaweera** [expo/expo#750]
Hi, we are using expo  "expo": "^20.0.0", version and building in the detached mode.
In the pod file the versions been pulled down is as below
git => "http://github.com/expo/expo.git",
tag => "ios/1.20.5"

The iOS SDK been used to build on is - 10.2
nvm current output is 7.4

The ios build is giving an error as below in the command line when using "xcodebuild":

> ** BUILD FAILED **
>The following build commands failed:
	CompileC /my-project-prototype/Build/Intermediates/Pods.build/Release-iphoneos/ExpoKit.build/Objects-normal/armv7/EXGLView.o ExpoKit/ios/Exponent/Versioned/Modules/Api/GL/EXGLView.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

``

When the project is opened using xcode in the
 EXGLView.m file Line282 and 284 the below errors are shown

`+ (NSArray *)nsArrayForMatrix:(matrix_float4x4)mat //--- line #282
{

  const float *v = (const float *)&mat;  //--- line #284
  return @[@(v[0]), @(v[1]), @(v[2]), @(v[3]),
           @(v[4]), @(v[5]), @(v[6]), @(v[7]),
           @(v[8]), @(v[9]), @(v[10]), @(v[11]),
           @(v[12]), @(v[13]), @(v[14]), @(v[15])];
}`

> Expected a type 

> Cast of an indirect pointer to an Objective-C pointer to 'const flaot*' is disallowed with ARC

Any help will be really great. Thanks

**Comment by jankarres** [comment]
Same issue here.

**Comment by terribleben** [comment]
What version of Xcode are you using?

**Comment by theranjali-nilaweera** [comment]
XCode Version 9.0 (9A235)
For now we switched to the following versions and got it working. Didn't check the in between versions though. I was following #392 

 "expo": "18.0.0",
 "react": "16.0.0-alpha.12",
 "react-native": "https://github.com/expo/react-native#sdk-18.0.0",
 "react-native-auth0": "^1.2.0",

and changed the pod file manually to point to 
tag => "ios/1.17.1"

**Comment by githubandrewd** [comment]
You can replace matrix_float4x4 with float **. It is veeeery likely just a typedef from C. 

I don't know what consequences it may have, but if it does bug anything, it will probably be the Camera.


+ (NSArray *)nsArrayForMatrix:(float **)mat
{
  const float *v = (const float *)&mat;
  return @[@(v[0]), @(v[1]), @(v[2]), @(v[3]),
           @(v[4]), @(v[5]), @(v[6]), @(v[7]),
           @(v[8]), @(v[9]), @(v[10]), @(v[11]),
           @(v[12]), @(v[13]), @(v[14]), @(v[15])];
}

I had the same problem on Xcode 8.3.

I really hope this will be fixed or some answer will be given from the expo team, because replacing the source file doesn't seem to be smart.

**Comment by terribleben** [comment]
the matrix_4x4 type is defined in `matrix_types.h` for me:

![image](https://user-images.githubusercontent.com/1316332/31402018-8204d568-ada9-11e7-8c38-bbdcb3a97cc4.png)

It sounds like everybody who has reported this so far is targeting iOS < 11.0, is that correct? What happens if you target newest iOS? This matrix type is used by ARKit, which was introduced in iOS 11.0.

**Comment by estefaniaregalado** [comment]
I'm having the same issue.
![screen shot 2017-10-16 at 8 13 29 pm](https://user-images.githubusercontent.com/1701129/31642067-898a3aa8-b2ae-11e7-9d30-42c2ab8d518f.png)

**Comment by ide** [comment]
It sounds like upgrading to Xcode 9 and using the iOS 11 SDK addresses this issue -- is anyone having issues with Xcode 9?

**Comment by theranjali-nilaweera** [comment]
@ide Yes I also upgraded to iOS SDK 11 and targeted min SDK to 9 and it worked OK.
Thanks
