### ISSUE TITLE
[Web] launchImageLibraryAsync with allowsMultipleSelection=true does not work

### ISSUE THREAD

**Issue by kopax** [expo/expo#7526]
I am working with expo SDK36 and I have read the documentation for imagelibrary from A to Z.

This is how I use `launchImageLibraryAsync`:

```jsx
  const _onAddImagePressed = async (values) => {
    draftUpdate(values);
    if (Platform.OS !== 'web') {
      const { getCameraRollAsync } = require('../../../core/camera/utils');
      // import { getCameraAsync, getCameraRollAsync } from '../../../core/camera/utils';
      await getCameraRollAsync();
    }

    const options = {
      height: '300px',
      width: '300px',
      allowsEditing: true, // ios (crop) & android (crop/rotate) only
      allowsMultipleSelection: true, // web only
      base64: true,
      quality: 0.5,
    };
    try {
      const { base64, height, width, uri, cancelled, ...rest } = await launchImageLibraryAsync(options);
      console.log({
        base64: base64 ? base64.slice(0, 30) : base64,
        height,
        width,
        uri: uri.length > 100 ? uri.slice(0, 30) : uri,
        cancelled,
        rest,
      });
    } catch (e) {
      alert('something went wrong while processing camera roll');
    }
  };

```

This is `getCameraRollasync`:

```jsx
export async function getCameraRollAsync() {
  // permissions returns only for location permissions on iOS and under certain conditions, see Permissions.LOCATION
  const { status /* , permissions */ } = await askAsync(CAMERA_ROLL);
  console.log(status);
  if (status === 'granted') {
    return getCameraRollPermissionsAsync();
  }
  throw new Error('Camera roll permission not granted');
}
```

1. For some reason, the permissions does not work on the web, so I only ask them for natrive , otherwise I get `Uncaught (in promise) Error: Camera roll permission not granted` 
1. The return of `launchImageLibraryAsync(options)` look like: 
> {base64: undefined, height: 0, width: 0, uri: "data:image/jpeg;base64,/9j/4f/", cancelled: false, …}

I tried to split the base64 to see if it contains all the list with `console.log(base64.split('base64'));` but that is not the case.

**Comment by EvanBacon** [comment]
Related https://github.com/expo/expo/issues/7470

**Comment by kopax** [comment]
> Related #7470

How is this related ?

**Comment by LeoAltissimo** [comment]
I saw this part of the code, and allowMultipleSelection is adjusted only to define a multiple entry, but it does not return more than one file upon request.

**Comment by stephenhandley** [comment]
Yeah it just returns a single file even on web. 

@EvanBacon I'm trying to get a better idea for the roadmap around this allowsMultipleSelection flag in https://docs.expo.io/versions/latest/sdk/imagepicker/ ... It doesn't work for web for me and it looks like there are a couple open canny issues where its unclear whether it will eventually be implemented for ios/android:
https://expo.canny.io/feature-requests/p/imagepicker-support-allowsmultipleselection
https://expo.canny.io/feature-requests/p/allow-choosing-multiple-images-in-imagepicker

Selecting multiple images is a pretty common use case and given how commonplace native ios/android ui is in supporting multiple image selection I'm assuming this just isn't a priority rather than there being some technical limitation blocking implementation. could you provide some details on what the plans are? I'm currently using this in an app where it's important a user select multiple images and requiring multiple calls to this as a temp workaround is fine assuming this will eventually support multiple images, but if not I'll need to go another direction.

**Comment by znmto** [comment]
Can someone let us know if this is on the roadmap at least?

**Comment by brentvatne** [comment]
it is not on the roadmap. you can work on this if you want to @znmto - it is an open source project. we are prioritizing other projects at the moment.

**Comment by znmto** [comment]
Thank you for the clarification, @brentvatne
