### ISSUE TITLE
Network request failed

### ISSUE THREAD

**Issue by conan19842002** [expo/expo#7544]
I've got error "Network request failed" when using fetch in React Native on Android emulator/real device. The code is below:
```
fetch('http://localhost:3000/response', {
      method: 'POST',
      headers: {
          Accept: "aplication/json;charset=UTF-8",
          "Content-Type": "application/json"
      },
      body:JSON.stringify({name: "abc", email: "something@gmail.com"}),
      })
      .then((response) => response.json())
      .then((responseJson) => {

          alert('response object:' + JSON.stringify(responseJson));

          if(responseJson.valid === true){
              // do something

          }

      })
      .catch((error) => {
        console.error(error);
        alert(error);
      });

    });
```
I've tried to fix it by adding "app.use(cors());" on express server. This fix works when I simulate on web but still fails on emulator or real device.
I also tried replacing 'localhost' to my machine IP and my phone connected to the machine via USB on the same LAN but nothing worked.

**Comment by cruzach** [comment]
Unless this only happens in the Expo managed workflow, and not the bare workflow, this is most likely not a bug with Expo. If you can confirm that it only happens in a managed project, please fill out the entire bug report template and I'll reopen the issue- otherwise I suggest checking other similar issues that have been reported in the react native repo - https://github.com/facebook/react-native/issues/23986
