### ISSUE TITLE
BarCodeScanner camera is always portrait by default in landscape mode

### ISSUE THREAD

**Issue by rgangopadhya** [expo/expo#758]
Elevating this forum question https://forums.expo.io/t/barcodescanner-camera-is-always-portrait-by-default-in-landscape-mode/1110?u=dann1609

I am seeing the same issue with SDK 21.

**Comment by aalices** [comment]
`BarCodeScanner` will be using `Camera` underneath - this should fix the issue. This will be released within SDK 23.

**Comment by jsprow** [comment]
I'm having a similar issue using the `Camera` component with the `onBarCodeRead` prop.

Here's the code I'm working with:
```javascript
<Camera
  aspectRatio={1.33}
  barCodeTypes={[Camera.Constants.BarCodeType.code39]}
  flashMode={flashMode}
  onBarCodeRead={this.handleBarCode.bind(this)}
  ratio="4:3"
  ref={ref => this.camera = ref}
  style={{ flex: 1, maxWidth: '100%' }}
  type={Camera.Constants.Type.back}
/>
```
I have `ScreenPosition` locked into portrait, but the barcode reader is only able to register codes tall-wise. Strangely, when I lock it into landscape, the camera prefers the same orientation.

Things I've tried:
- Locking the orientation in `app.json`, instead of through the Component prop. Didn't fix it.
- Use the `BarCodeScanner` Component. Works great, but I need the camera to take a picture immediately after scanning the barcode. I tried to switch the components out using ternaries with `this.state`, but I couldn't get the preview to function reliably.
- Completely change my UI layout. This is the nuclear option, but I've been messing with it. If I can't find a good workaround, I'll end up doing this.

If anyone can give me a hand, I'd be grateful. Also, if I can provide any more info, let me know.

Thanks!

**Comment by aalices** [comment]
Hello @jsprow what SDK are you using?

**Comment by jsprow** [comment]
@aalices 25.0.0. If it makes a difference, I'm using the module within Create React Native App. Here's my package.json : 
```javascript
{
  "devDependencies": {
    "jest-expo": "25.0.0",
    "react-native-scripts": "1.11.1",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "0.52.2"
  }
```
