### ISSUE TITLE
[local-authentication] Android should match iOS `authenticateAsync` options where possible

### ISSUE THREAD

**Issue by alexbchr** [expo/expo#7583]
### Environment
Expo Diagnostics: 
```
Expo CLI 3.17.5 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.7.1 - /usr/bin/zsh
    Binaries:
      Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
```
Issue occurs on Android

### Steps to Reproduce

The new LocalAuthentication using Android's `BiometricPrompt` offers fallback authentication method based on device unlock method (PIN, Password, Pattern). iOS does not do that if `fallbackLabel: ''` is passed to `authenticateAsync()`, as stated by [the official Expo docs](https://docs.expo.io/versions/latest/sdk/local-authentication/#localauthenticationauthenticateasyncoptions).

### Expected Behavior

If `fallbackLabel` is set to an empty string, do not offer device fallback method like iOS. Also, just like iOS, it would be great to customize the `cancelLabel` option too.

**Comment by wesleyrafael** [comment]
I've just experienced this problem as well. Hope it can be fixed soon. Also congrats to the team for releasing a new sdk version a few days ago =)

**Comment by swayok** [comment]
LocalAuthentication.authenticateAsync() for Android lacks configuration badly.
For example: I have an app which has its own pin-code and optional biometric auth.
I expect LocalAuthentication.authenticateAsync() to ask only for fingerprint/faceid and NEVER fallback to Android’s pass code or anything else. But it is not possible and acually makes this functionality useless in most common cases. It even does not tell that passcode was used in returned result - it just behaves same way as fingerprint: {“success”: true}.In result app activates fingerprint auth in case when fingerprint test actually failed. And even more absurd situation - with activated fingerprint auth user can avoid fingerprint auth using Android’s passcode…
Also there are no possiblity to configure text in biometrics prompt which results in english text in app that does not support english.

I do know that everything I described above is possible to implement because I have apps where this local auth works exactly the way I need - localized and without fallback to passcode.

We all really need Android’s biometric prompt to have options similar to iOS.

**Comment by WilliamAlexander** [comment]
Yes the Android route needs to behave similar to iOS.
'authenticateAsync' needs to support the 'options' object in Android. 
The default 'Use Password'/'Use PIN' in Android fingerprint dialog needs custom text and tapping it will close dialog and return {success: false}
