### ISSUE TITLE
SDK 37: Android release build crash. (expo-updates)

### ISSUE THREAD

**Issue by sarmad1995** [expo/expo#7615]
### Environment

Expo CLI 3.17.11 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.3.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.13.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.3 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.4 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.17.11

I tested it for android for now. potentially can be same for ios

### Steps to Reproduce

Currently any `expo bare app with sdk37`

### Expected Behavior

Should have app-updates not configured by default.

### Actual Behavior

  I don't know if its intentional or not, but my guess is that it's by mistake. The expo `sdk 37` as configuration done for `expo updates` by default. and it shouldn't be that case. For example.
by default the config is done in `MainApplication.java`
```
 @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);

    if (!BuildConfig.DEBUG) {
      UpdatesController.initialize(this);
    }
  }
```
and so on.
this causes crash on release builds because the user doesn't expect that the `expo-updates` should be installed.

### Possible Fix

If anyone is having crash on release builds, please try to configure `app-updates` or you can also remove the configuration in your app.

**Comment by brentvatne** [comment]
We intentionally add expo-updates by default in ejected apps because we expect most users will want it. To remove it you can follow the instructions on https://github.com/expo/expo/blob/master/packages/expo-updates/README.md in reverse.

If it's crashing on release that is likely because you haven't run `expo publish` on the bare app yet. When you do, that version will be packaged in your release build :)

cc @esamelson, so you are aware

**Comment by tonuegbu** [comment]
@brentvatne Do you run the publish command before building on Android studio or after? I've removed expo-updates and the app still crashes when I install the apk on a phone.

**Comment by tonuegbu** [comment]
Just removed expo-updates and it's fine now. Had to regenerate android.bundle because I had already deleted it.
` react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
` 
created a new app.manifest as well.
