### ISSUE TITLE
[expo-notifications] Calling dismissNotificationAsync would not clear notification while app running in foreground

### ISSUE THREAD

**Issue by guanhuay** [expo/expo#7642]
## 🐛 Bug Report
I am trying to integrate the newly released SDK 37 expo-notifications into my project. I have to says, this feature is awesome and very easy to setup.

However, I discover one bug with it. It is while app running in foreground, calling the dismissNotificationAsync won't clear the notification.

Please refer to "Step To Reproduce" section for code sample.

### Environment

  Expo CLI 3.17.11 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.12.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 6.11.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.17.11

Running on bare workflow + expo unimodules
iOS target 9
Android target: min 21

### Steps to Reproduce

Basically, i setup Firebase FCM to receive message from firebase. When I sent message to the device with the given fcmToken, I was able to see the FCM payload by console log it.

However, when app is running in foreground, when I tap on notification when it shows up, it would not go away from the notification center and persist there.

Here is the code snippet:

```
const getNotificationPermissionStatus = async () => {
  const existingStatus = await Notifications.getPermissionsAsync();
  return existingStatus.granted || existingStatus.ios
    ? existingStatus === 3
    : false;
};

useEffect(() => {
  const requestNotificationPermission = async () => {
    let existingStatus = getNotificationPermissionStatus();

    if (!existingStatus) {
      return await Notifications.requestPermissionsAsync({
        android: {},
        ios: {
          allowAlert: true,
          allowSound: true,
          allowAnnouncements: true,
        },
      });
    }
  };

  requestNotificationPermission().then(() => {});
}, []);

// Config Notifications Handler
Notifications.setNotificationHandler({
  handleNotification: async () => {
    return {
      shouldShowAlert: true,
      showPlaySound: true,
      priority: AndroidNotificationPriority.HIGH,
    };
  },
});
const showNotification = async (content, trigger) => {
  try {
    const identifier = await Notifications.scheduleNotificationAsync({
      content,
      trigger,
    });
    // clear notification
    await Notifications.dismissNotificationAsync(identifier);
  } catch (error) {
    console.log(error);
  }
};

// Incoming Message Handler
useEffect(() => {
  const unsubscribeOnMessage = messaging().onMessage(
    async (remoteMessage) => {
      const {
        notification: { title, body },
      } = remoteMessage;

      const content = {
        title: title,
        message: body,
        sound: true,
        priority: AndroidNotificationPriority.HIGH,
      };
      await showNotification(content, null);
    }
  );

  return unsubscribeOnMessage;
}, []);

```

### Expected Behavior

Notifications.dismissNotificationAsync(identifier) should clear the notification on tap.

### Actual Behavior

Notification persist, have to manually tap the recycle bin to clear it.

### Reproducible Demo

Run this repo on Android ===> [From @brentvatne ](https://github.com/brentvatne/local-notif-ios-example)

**Comment by sjchmiela** [comment]
Hey @guanhuay!

Thank you for the words of appreciation — I'm glad you found the library easy to setup! 😍

Diving down into your issue I have a couple of notes:
- unfortunately, `dismissNotificationAsync` does not work on Android API < 23 (6.0, Marshmallow), so on older devices the function will just resolve,
- _iOS target 9_ — watch out, we do not officially support iOS 9 in unimodules and neither does the `expo-notifications` library. If you didn't mean _iOS 9_ then it should be ok, otherwise I wouldn't expect the notifications functionality to work on iOS 9 (I would be surprised if it compiled 🤔)
- the way you check the permissions response may be problematic in the long run:
  ```js
  return existingStatus.granted || existingStatus.ios
      ? existingStatus === 3 // existingStatus won't ever be 3 -- it's an object
      : false;
  ```
  what you probably meant was
  ```ts
  return existingStatus.granted || (existingStatus.ios?.status === IosAuthorizationStatus.PROVISIONAL);
  ```
  if you have TS with support for optional chaining and import `IosAuthorizationStatus` enum (which is highly recommended).
- `scheduleNotificationAsync`, as the name suggests (but it may be unclear), only schedules a notification, so immediately after the notification is scheduled (just after it is `await`-ed, the notification may not be shown yet). If you wanted to dismiss the notification right after it is shown, I would suggest using `handleSuccess` callback of the notification handler, like this:
  ```ts
  Notifications.setNotificationHandler({
    handleSuccess: notificationIdentifier => {
      // dismiss notification immediately after it is presented
      Notifications.dismissNotificationAsync(notificationIdentifier);
    },
    /* handleNotification: ... */
  });
  ```
  On the other hand, if you would want to dismiss the notification when the user taps on it, use `Notifications.addNotificationResponseReceivedListener`:
  ```ts
  Notifications.addNotificationResponseReceivedListener(response => {
    // Use this `if` to only dismiss notifications that have been tapped on
    if (response.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER) {
      Notifications.dismissNotificationAsync(response.notification.identifier);
    }
  });
  ```
- another concern I was wondering about was — why are you mixing `expo-notifications` and Firebase? If you intend to handle notifications this way (if I understand the code correctly, by listening to Firebase notifications and then using its payload to show the notification with `expo-notifications`) be aware that this probably won't work when the app is in background/quit. A production-ready solution would be to use `expo-notifications` to handle incoming notifications, i.e. pass a compliant `data` (spec can be found [in the docs](https://github.com/expo/expo/tree/master/packages/expo-notifications#android-push-notification-payload-specification)) — `expo-notifications` should show the notification for you, without you needing to listen for them in JS. (The best reason I can imagine for mixing Firebase and `expo-notifications` would be subscribing to FCM topics, which is not supported in `expo-notifications` right now, is it what you're doing?)

Using `expo-notifications` and a simple app I have confirmed that [this](https://gist.github.com/sjchmiela/d8f11af638f739ab648ad3c192f3568f) should work ok for iOS, but on Android the notification wouldn't be shown — to fix this you would need to use sth like:

```ts
  handleSuccess: notificationIdentifier => {
    // dismiss every notification immediately *after* it is presented
    setTimeout(() => Notifications.dismissNotificationAsync(notificationIdentifier), 100);
  },
```

Let me know if I have been able to help you!

**Comment by guanhuay** [comment]
> Hey @guanhuay!
> 
> Thank you for the words of appreciation — I'm glad you found the library easy to setup! 😍
> 
> Diving down into your issue I have a couple of notes:
> 
> * unfortunately, `dismissNotificationAsync` does not work on Android API < 23 (6.0, Marshmallow), so on older devices the function will just resolve,
> * _iOS target 9_ — watch out, we do not officially support iOS 9 in unimodules and neither does the `expo-notifications` library. If you didn't mean _iOS 9_ then it should be ok, otherwise I wouldn't expect the notifications functionality to work on iOS 9 (I would be surprised if it compiled 🤔)
> * the way you check the permissions response may be problematic in the long run:
>   ```js
>   return existingStatus.granted || existingStatus.ios
>       ? existingStatus === 3 // existingStatus won't ever be 3 -- it's an object
>       : false;
>   ```
>   
>   
>   what you probably meant was
>   ```ts
>   return existingStatus.granted || (existingStatus.ios?.status === IosAuthorizationStatus.PROVISIONAL);
>   ```
>   
>   
>   if you have TS with support for optional chaining and import `IosAuthorizationStatus` enum (which is highly recommended).
> * `scheduleNotificationAsync`, as the name suggests (but it may be unclear), only schedules a notification, so immediately after the notification is scheduled (just after it is `await`-ed, the notification may not be shown yet). If you wanted to dismiss the notification right after it is shown, I would suggest using `handleSuccess` callback of the notification handler, like this:
>   ```ts
>   Notifications.setNotificationHandler({
>     handleSuccess: notificationIdentifier => {
>       // dismiss notification immediately after it is presented
>       Notifications.dismissNotificationAsync(notificationIdentifier);
>     },
>     /* handleNotification: ... */
>   });
>   ```
>   
>   
>   On the other hand, if you would want to dismiss the notification when the user taps on it, use `Notifications.addNotificationResponseReceivedListener`:
>   ```ts
>   Notifications.addNotificationResponseReceivedListener(response => {
>     // Use this `if` to only dismiss notifications that have been tapped on
>     if (response.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER) {
>       Notifications.dismissNotificationAsync(response.notification.identifier);
>     }
>   });
>   ```
> * another concern I was wondering about was — why are you mixing `expo-notifications` and Firebase? If you intend to handle notifications this way (if I understand the code correctly, by listening to Firebase notifications and then using its payload to show the notification with `expo-notifications`) be aware that this probably won't work when the app is in background/quit. A production-ready solution would be to use `expo-notifications` to handle incoming notifications, i.e. pass a compliant `data` (spec can be found [in the docs](https://github.com/expo/expo/tree/master/packages/expo-notifications#android-push-notification-payload-specification)) — `expo-notifications` should show the notification for you, without you needing to listen for them in JS. (The best reason I can imagine for mixing Firebase and `expo-notifications` would be subscribing to FCM topics, which is not supported in `expo-notifications` right now, is it what you're doing?)
> 
> Using `expo-notifications` and a simple app I have confirmed that [this](https://gist.github.com/sjchmiela/d8f11af638f739ab648ad3c192f3568f) should work ok for iOS, but on Android the notification wouldn't be shown — to fix this you would need to use sth like:
> 
> ```ts
>   handleSuccess: notificationIdentifier => {
>     // dismiss every notification immediately *after* it is presented
>     setTimeout(() => Notifications.dismissNotificationAsync(notificationIdentifier), 100);
>   },
> ```
> 
> Let me know if I have been able to help you!

Hi Stanislaw,


Thanks for such a detail reply, I would definitely try out your suggestion tonight. But I just want to quickly answer your question.


1. For Android OS, I didn't intend to supported sdk 23 or below, I just have min sdk set to 21.

2. For IOS, I don't know why it shows my IOS target as 9, but in my pod file it was targeted to 10 for sure.

3. I use this "existingStatus === 3" because back in the time, my IDE was not able to resolve this variable IosAuthorizationStatus.PROVISIONAL for me, so I just temporarily make it 3.

4. I already tried place "await Notifications.dismissNotificationAsync(identifier);" in setNotificationHandler/handleSuccess, but it doesn't work, so I just place it in my showNotification right after the scheduleNotificationAsync() to see if it actually dismiss it.

5. Yup, I am trying to use FCM and subscribe to some topics. However for now, I don't intend to support this function when app running in background. But I definitely looking forward to see this feature in July release.

Great job and thanks for such an amazing libraries. Really appreciate expo and your hard work!

**Comment by guanhuay** [comment]
Great example for anyone new to expo-notifications
