### ISSUE TITLE
[iOS]  Huge markers in react-native-maps and bundled assets

### ISSUE THREAD

**Issue by moxorama** [expo/expo#7665]
### Environment

Expo CLI 3.17.11 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - /usr/local/opt/node@10/bin/node
      Yarn: 1.21.1 - ~/.yarn/bin/yarn
      npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.4 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.11

Target: Managed ios
### Steps to Reproduce

1) Build standalone app `expo build:ios -t simulator`
2) Open app in simulator  (I'm using iPhone 7)
3) Marker icon is HUGE

When I'm using expo as development environment - all ok, this bug is only in production builds.
I think this is related to this bug - https://github.com/expo/expo/issues/1182
### Expected Behavior

Marker icon should have correcrt size

### Actual Behavior

Marker icon has correct size in development environment, but has big size in production standalone App. If application gets new marker icon with OTA,  marker size also become correct.

### Reproducible Demo

https://github.com/moxorama/ios-huge-initial-markers-bugreport

**Comment by brentvatne** [comment]
it seems like an issue with react-native-maps:
- https://github.com/react-native-community/react-native-maps/issues/1422
- https://github.com/react-native-community/react-native-maps/issues/2340

perhaps a solution could be to explicitly specify the dimensions of the image?

**Comment by moxorama** [comment]
Ok, maybe this is bug in react-native-maps, but 

- When I'm not bundling asset with my app, or not preloading image during splash with Asset.loadAsync()- everything is ok.  Looks like Asset.loadAsync does something strange with image.

- I have to use icon attribute because it's fastest way to render marker image :( Is there any way to specify icon size?

**Comment by brentvatne** [comment]
i don't think this is anything about expo-asset - those links i shared to issues on react-native-maps indicate that in 'release mode' (so when the assets are on the local filesystem path because they are bundled in the app bundle rather than served from development service at a web url) this is an ongoing issue for folks who don't use expo-asset.

another workaround you could probably use is to just use web urls for the images rather than using `require`. or another way to do this is to ensure that the images you want to use here specifically don't match `assetBundlePatterns` and don't use `Asset.loadAsync`, then they will be loaded over http
