### ISSUE TITLE
Segment "Application Installed" event not firing

### ISSUE THREAD

**Issue by carriesmith** [expo/expo#768]
According to Segment's docs Application Installed, Application Opened, Application Updated events should be collected automatically by the latest version of our Android and iOS SDKS.
These events are not firing, though other track and screen events are.
Is Expo preventing these events from being sent? How can we make sure they do fire?
TY

**Comment by carriesmith** [comment]
Any updates, thoughts or suggested workarounds?

**Comment by btk** [comment]
Application Installed and Application Opened is easy;

As you would know any idenity creation is an "Application installed" in practice (though some users can download the app and remove it before even opening. Since Segment also don't have any way to listen that case you are safe here)

For application opened, I use a screen called "opened" and call it in the componentDidMount of the hub "App" component. 

Application Updated is kinda tricky. I started storing a version variable as a constant variable on my script and also on the AsyncStorage for this. Everytime user starts a session, I check if this two variable is same or not. It they don't match, I call an event for Version updated.

Also you can query this version update on the analytic tool you are destinating your Segment data. Since segment always also sends the version data with any screen/idenity/event call.

**Comment by ctgardner** [comment]
> For application opened, I use a screen called "opened" and call it in the componentDidMount of the hub "App" component.

Is this is a work-around or best practice? The Segment docs do suggest the **Application Installed**, **Application Opened** and **Application Updated** events are collected automatically. https://segment.com/docs/spec/mobile/#overview-of-events

**Comment by btk** [comment]
@ctgardner I'm not sure about how they collect the app being installed event. And they say for application installed event;

> **Application Installed**
> This event fires when a user first opens your mobile application. ...

So segment is also listening the first time app opening for the application installed event. So since it is not implemented for Expo wrapper, using it as how I proposed is the same as how Segment does it.

But it would be good if someone implements it.

**Comment by iagorm** [comment]
We still don't have this feature enabled, please someone from Expo's team view this issue, it is important. +1

**Comment by LouisJS** [comment]
+1

**Comment by LouisJS** [comment]
I'm not gonna detach my app ang get rid of all the Expo feature just for one analytics

**Comment by AdamJNavarro** [comment]
Hey @carriesmith,

In an effort to clean up and gain more clarity over our issues, we're closing old issues that may no longer apply to our currently supported versions. If you are able to still repro this, please open a new issue with a repro case and we'll be happy to investigate. Thanks again for your initial report!

Cheers,

Adam
