### ISSUE TITLE
Segment with Mixpanel : Switch to EU endpoint

### ISSUE THREAD

**Issue by LentnerStefan** [expo/expo#7739]
Hello,

I'm currently using Segment to send events to Mixpanel in my app and i'd like to switch to the european union endpoint :
https://segment.com/docs/connections/destinations/catalog/mixpanel/#sending-data-to-mixpanels-european-union-endpoint

Is there some way I can achieve this without ejecting, since I have to edit the AndroidManifest.xml ?

Thank you !

**Comment by cruzach** [comment]
Hi! Since this requires changes to `AndroidManifest`, you'll need to use the bare workflow for this. We recently made some pretty big additions to the bare workflow which bring it almost to parity with the managed workflow., so I recommend reading through [the SDK 37 release notes](https://blog.expo.io/expo-sdk-37-is-now-available-dd5770f066a6).

Otherwise, you may want to open a feature request on our [canny](https://expo.canny.io/feature-requests) for this, and see if it gets some traction 😄

**Comment by LentnerStefan** [comment]
Oh I didn't see this ! Thanks for your response 🙏
