### ISSUE TITLE
Can not resolve unimodules-font-interface

### ISSUE THREAD

**Issue by VitaliyGaliy** [expo/expo#7769]
Have issue with unimodules-font-interface in react native app

<img width="958" alt="Снимок экрана 2020-04-09 в 5 24 38 PM" src="https://user-images.githubusercontent.com/24389083/78905935-5d237580-7a87-11ea-993d-be9bff8993a9.png">

**Comment by cruzach** [comment]
Closing this since there's not enough information here to help. If you want to file a bug report, please provide everything we ask for in the template

I tested out the most recent release of `expo-font` (uses `unimodules-font-interface "~5.1.0"`) and had no problems. I would also recommend reading the docs and trying the example snacks there -https://docs.expo.io/versions/latest/guides/using-custom-fonts/
