### ISSUE TITLE
 Android Component Hijacking via Intent.

### ISSUE THREAD

**Issue by Mahesha-Bhat** [expo/expo#7783]
Intents are used to start activities and services, bind to services, and convey notiﬁcations to broadcast receivers. By default, a component can only receive intents from other components in the same application, but it can be conﬁgured to accept intents from outside applications by setting the **android:exported** attribute in the manifest. this leads to component hijacking, it can be solved by creating **pending intent** and wrap to our intent.
how can I solve this problem in expo?
please anyone help me with this.

**Comment by cruzach** [comment]
If you need finer-grained control over settings in AndroidManifest, or need to add custom java changes yourself, then you can use the [bare workflow](https://docs.expo.io/versions/latest/introduction/managed-vs-bare/#bare-workflow) 👍 

We use `android.app.PendingIntent`, so if you think there's a bug somewhere, please provide as much information as possible as to what you believe the bug is and how to fix it

**Comment by Mahesha-Bhat** [comment]
Implicit intent being created by the app. This may leave to an intent hijacking attack where a malicious application registers for the same action and category and could be able to intercept the intent to compromise data or alter behaviour.
Intent hijacking is possible via BroadcastReceiver through **Lhost/exp/exponent/ ExponentIntentService**
