### ISSUE TITLE
expo-font duplicated reference issue

### ISSUE THREAD

**Issue by sshtel** [expo/expo#7811]
### Environment

```
  Expo CLI 3.17.23 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.7 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.23
```

iOS

### Steps to Reproduce

To use custom Font, call `Font.loadAsync({ argon: require('../assets/font/argon.ttf')})`.

If an Icon But expo SDK causes this error
`fontFamily "ArgonExtra" is not a system font and has not been loaded through Font.loadAsync.`

1. `expo` package contains `expo-font` package
2. some external package requires expo-font
3. So there are duplicated expo-font packages
```
argon-react-native@1.4.0 /Users/steve/workspace/opensource/creative-tim/argon-react-native
├─┬ expo@37.0.7
│ └── expo-font@8.1.1 
└── expo-font@8.1.1 
```
4. While `Font.loadAsync()` uses expo-font in root of npm packages and loaded status is true,
Other Component tries to use `expo-font in expo/node_modules/expo-font` which is `loaded` status is false.
5. This causes `fontFamily "ArgonExtra" is not a system font and has not been loaded through Font.loadAsync.` error

Example repo: https://github.com/creativetimofficial/argon-react-native

### Expected Behavior

Font should be loaded properly

### Reproducible Demo

Example repo: https://github.com/creativetimofficial/argon-react-native

### workaround
```
argon-react-native@1.4.0 /Users/steve/workspace/opensource/creative-tim/argon-react-native
├─┬ expo@37.0.7
│ └── UNMET DEPENDENCY expo-font@8.1.1 
└── expo-font@8.1.1 
```
If I delete `expo/node_modules/expo-font` manually, this error is gone since there is only one `expo-font` package to refer.

### Suggestion 1

Well my suggestion is expo-font should be in different repository and managed separately.
I don't know why the `expo-font` is moved in `expo/package/expo-font` from its own repository `https://github.com/expo/expo-font`

### Suggestion 2
expo SDK can expose `expo-font` directly like
`import { Font } from 'expo';`
Then application does not need to use `expo-font` separately.

**Comment by brentvatne** [comment]
hello! this is an issue with your package manager, which i think is npm. you need to clear the lockfile and node_modules, which `expo upgrade` now will do for you automatically if you use npm (make sure you're using the latest version of expo-cli before you run it). the repository you linked to does not exhibit this issue you describe, i imagine you did not push the changes.

the suggestions will not work to prevent this type of issue. suggestion 1 would have no impact on it, the structure of the repositories is orthogonal. suggestion 2 is how we used to export the Font package but we do not do it anymore because the font package needs to be usable without the entire expo sdk package.

i've created an issue on expo-cli about providing warnings for people if they somehow end up in this state: https://github.com/expo/expo-cli/issues/1870

if you still have a problem after reading and following the advice above then please create an issue on the expo-cli repository with more information including a link to a project where it is reproducible (as mentioned above, the provided link does not)

**Comment by sshtel** [comment]
Thank you very much! `expo upgrade` works perfectly!

It changed many package versions and app.json file
