### ISSUE TITLE
Is it possible to use expo-yarn-workspaces in bare workflow?

### ISSUE THREAD

**Issue by cmaycumber** [expo/expo#7812]
I'm currently trying to create a monorepo that shares code between mobile and web and was wondering whether this is possible. 

Or are there any resources on best practices for using expo inside a monorepo with the bare workflow?

**Comment by brentvatne** [comment]
yes, it is. we use it in this repository for all of our projects. if you look through it you might be able to use similar patterns.

we don't currently provide guidance around it because this is pretty tricky to set up and maintain and requires the developer doing it to become pretty comfortable with the tools, and we don't have time to support it.

**Comment by brentvatne** [comment]
also, you might find this discussion interesting https://expo.canny.io/feature-requests/p/monorepo-boilerplate

**Comment by cmaycumber** [comment]
@brentvatne Thanks for pointing me in the right direction! This is great to hear. I'll take a look at that discussion you linked.
