### ISSUE TITLE
Self hosting app

### ISSUE THREAD

**Issue by AlefiyaG** [expo/expo#7859]
Hi Team,
I am trying to use the OTA feature for my React Native project. I just wanted to confirm if you support self hosting the application's bundle and assets. Due to company's policies we won't be able to fetch the bundle/assets from the Expo servers, will need to use our own servers.  

I saw this link
https://docs.expo.io/versions/latest/distribution/hosting-your-app/
but it mentions this in still in beta, so wanted to confirm if it's stable. Also would need some more help on how this would work with expo publish.

**Comment by byCedric** [comment]
Hi @AlefiyaG! Thanks for bringing this up, the self hosting feature is not in beta anymore and you can safely use it 😄 [The docs](https://docs.expo.io/versions/latest/distribution/hosting-your-app/) should guide you through this process. If something is unclear or run into issues, please let us know. To summarize from the guide:

- `expo publish` can't be used here, this will upload the bundle and assets to our servers.
- Instead of publish, use `expo export --public-url https://cdn.my.host`. This will create the bundles and assets in `/dist` so you can upload it to your own host.
- To make standalone builds talk to your host, use `expo build:ios --public-url https://cdn.my.host/ios-index.json` .

Hope it helps!

**Comment by AlefiyaG** [comment]
Thanks Cedric.
i tried running 
expo build:ios --public-url https://<localhost-server>/ios-index.json
command but i get the following error

Request failed with status code 400
Error: Request failed with status code 400
    at createError (/Users/alefiya/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/f058391/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/f058391/.nvm/versions/node/v12.10.0/lib/node_modules/expo-cli/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

So right now we are in trial phase. I have set up a local https server that serves files from the dist folder and i want to test it out on the ios app.  

**Expo version: 3.17.24**
have just created a dummy vanilla project using the **expo init** command.

**Comment by brentvatne** [comment]
you need to provide a path to your app that lives on a server somewhere - something you could conceivably open in a web browser

**Comment by AlefiyaG** [comment]
Hi Brent,
I am currently running a local server, sorry for the earlier message, i didn't mention it correctly. the path is:
https://127.0.0.0:8009/ios-index.json
and I can access that from my browser.

**Comment by brentvatne** [comment]
gotcha. that is still not valid because it's pointing to your local machine, 127.0.0.1 on our servers would be the server itself. you need to upload that somewhere, like s3

**Comment by AlefiyaG** [comment]
Thanks for your patience Brent. One of my team members got it working with a public url. I will also try it that out. Using a local server was an issue :(

Regards
Alefiya
