### ISSUE TITLE
No option for Show Performance Monitor in Developer Tools

### ISSUE THREAD

**Issue by hotdog2201** [expo/expo#7883]
Attempting to use the Performance Monitor from the Developer Tools, as listed on the documentation for debugging in Expo.

However, I find there is no Show Performance Option in the menu. 

I am using an iOS 13 physical device as a target, and have tried switching between production and development mode. 

![image](https://user-images.githubusercontent.com/8880953/79577558-ce34df80-80bc-11ea-9e05-648a5fefd585.png)

**Comment by byCedric** [comment]
Hi @hotdog2201, thanks for reporting this! Unfortunately, we had to temporary disable this feature on iOS devices running 13.4 due to an issue in React Native ([info](https://github.com/expo/expo/issues/7469#issuecomment-604907463)). All Android devices and iOS devices running <13.4 should have this feature enabled. If you can, you can open your project in the simulator and debug from there. As soon as everything is updated, we will enable this feature again for iOS 13.4! 😄

**Comment by darrylyoung** [comment]
> If you can, you can open your project in the simulator and debug from there.

It's worth noting, though, that if your Simulator is running iOS 13.4 then toggling the Performance Monitor will crash the Expo Client running on it, just as it did on actual devices before it was disabled. As far as I'm aware, right now, there's no way of monitoring performance via the Performance Monitor if you want to do so on iOS 13.4. I hope I'm wrong, though.

Regardless, I see that this issue has been reported upstream to React Native (thanks, guys!) so hopefully there's some movement there on this issue as it'd be great to monitor this stuff again.
