### ISSUE TITLE
Push notifications don't send when mixing push tokens from different experiences

### ISSUE THREAD

**Issue by br4in3x** [expo/expo#792]
### Summary
I have noticed an unexpected behavior of [Notifications.addListener](https://docs.expo.io/versions/latest/sdk/notifications.html#exponotificationsaddlistenerlistener): it's not triggering when I send request with an array of messages with stale or invalid tokens.

### Details
When I send a message object like so:
```
curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '{
  "to": "ExponentPushToken[XXX]",
  "title":"hello",
  "body": "world"
}
```
**it triggers** event on device, and the response is:
```
{"data":[{"status":"ok"}]}
```
Which is abosutely fine. 

But let's assume I have token `YYY`, which is **not valid**  (may be stale). And when I submit an array of objects, like so:
```
curl -H "Content-Type: application/json" -X POST https://exp.host/--/api/v2/push/send -d '[{
  "to": "ExponentPushToken[YYY]",
  "title":"hello",
  "body": "world"
},{
  "to": "ExponentPushToken[XXX]",
  "title":"hello",
  "body": "world"
}]'
```
An object with a following error recieved:
```
{
    "data": [
        {
            "status": "error",
            "message": "SNS failed to send the notification (reason: EndpointDisabled, status code: 400).",
            "details": {
                "error": "DeviceNotRegistered",
                "sns": {
                    "statusCode": 400,
                    "reason": "EndpointDisabled",
                    "__message": "Endpoint is disabled"
                }
            }
        },
        {
            "status": "error",
            "message": "The recipient \"ExponentPushToken[XXX]\" is associated with a different experience than \"@user/[app]\""
        }
    ]
}
```
And [Notifications.addListener](https://docs.expo.io/versions/latest/sdk/notifications.html#exponotificationsaddlistenerlistener) wasn't triggered on device with valid token `XXX`. 

However, if I send an array with first element key equal to `XXX` (notice that in given example above the key "key" of the first element was `YYY`), I get response:
```
{
    "data": [
        {
            "status": "ok"
        },
        {
            "status": "error",
            "message": "The recipient \"ExponentPushToken[YYY]\" is associated with a different experience than \"@anonymous/[app_id]\""
        }
    ]
}
```
And  [Notifications.addListener](https://docs.expo.io/versions/latest/sdk/notifications.html#exponotificationsaddlistenerlistener) triggers on the device with token `XXX` (which is valid token). This is what was expected.

### Conclusion
When I send array of messages in any order (including messages with not valid or stale tokens) method [Notifications.addListener](https://docs.expo.io/versions/latest/sdk/notifications.html#exponotificationsaddlistenerlistener) should be triggered on a device with valid token `XXX`.

**Comment by ide** [comment]
It looks like these push tokens are from two different projects. Could this be the case? It's not documented anywhere but the push server endpoint expects all push tokens to be for the same project (`@user/slug`).

**Comment by br4in3x** [comment]
@ide Thanks! Yes, technically they could, but.. May be here is another layer of the problem. I store keys in the database of our web-based project, and keys to that database is coming only from app -  and we have only one app. The app is in development, and may be those tokens coming from differenet versions of the app, or may be different versions appear after reintsallation of Expo client or cleaning it's cache?

I cleaned up server response before posting here, but you right, there was different ids of a project: for example, one was "@br4in3x/MySuperApp" and second like "@anonymous/MySuperApp-very-long-hash-string".

BTW, Expo version is 1.20.0 (API 21), running on Android 6.

**Comment by ide** [comment]
Project IDs that start with `@anonymous` are from projects made with create-react-native-app, which doesn't support push notifications. My recommendation would be to get rid of those push tokens and make sure that when you load your project it's always `@username/slug`.

**Comment by itslittlejohn** [comment]
I think I am having a similar issue. 

How can you ensure that a CRNA app loads with `@username/slug`? I've signed in using `exp login`, and push notifications have been working previously with my specific application, but now they do not.

Push notifications stopped working when I added the `expo.name` and `expo.slug` properties to `app.json` which caused the slug to be different than it was originally. After that I noticed the `the recipient is associated with a different experience` error (as above). Clearing the tokens from my server and re-registering now results in `OK` receipts from expo's server, but I haven't received a notification since then, even after removing the added properties, changing the slug back to what it was originally, etc. 

But I did notice that I am still seeing the `"id":"@anonymous/<app-name-some-guid>"` in the CRNA chrome dev tools on app start. I'm just assuming that somehow my app was originally configured to have my username in there instead of anonymous?

**Comment by br4in3x** [comment]
Hi @itslittlejohn! Yes, I solved this, but it seems like the worst solution. Anyway, I need a guarantee that notifications will be maybe not delivered but at least sent, so I ended up substituting bulk messaging with one-by-another.

This first block of code I had when I made this issue:

```ruby
def mobile_app(user, notify)
  expo = Exponent::Push::Client.new

  return if user.app_push_keys.blank?

  keys = user.app_push_keys.pluck(:expo)
  messages = []

  keys.each do |key|
    messages.push(
      to: key,
      title: notify[:title],
      body: notify[:body]
      data: notify[:data]
    )
  end

  expo.publish messages
end
```

And here is the actual version of the code:

```ruby
def mobile_app(user, notify)
  expo = Exponent::Push::Client.new

  return if user.app_push_keys.blank?

  user.app_push_keys.each do |key|
    expo.publish(
      to: key.expo,
      title: notify[:title],
      body: notify[:body],
      data: notify[:data]
    )
  end

  true
end
```

Unfortunately, until this issue is not resolved, I have to keep "the worst solution" =(

**Comment by itslittlejohn** [comment]
Interesting. So you are getting potentially more than one token per user and sending to all since you're not sure which is the right one. 

My issue is more how to get a notification to be received at all. 

I found this:
https://github.com/expo/xdl/blob/28bfdd84e2f72ec206e3322948728134ec6a63d4/src/Project.js#L1368-L1373

And it seems to indicate that CRNA will always use the `@anonymous/slug` approach?

But somehow, mysteriously, my CRNA app (dev and prod with `exp publish`) was receiving notifications perfectly fine and now it's not. So I find it hard to believe that CRNA just doesn't support push notifications. Looking for clarity on that point.

**Comment by ide** [comment]
CRNA happens to give you a token for push notifications but they are not part of the API and in the near future it’s likely that the client will throw a clear error instead of giving you a token if you aren’t logged in. You won’t have to make any changes to your app code — just will need to launch your project with exp/XDE.

**Comment by itslittlejohn** [comment]
Hi @ide, thanks for helping out. I downloaded XDE and was able to launch it right away. Immediately I noticed that the id in the output was correct (`@itslittlejohn/app-name`). But I still haven't been able to receive push notifications. I tried restarting the packager, tried publishing with `exp publish` but no dice. 

Any additional thoughts?

**Comment by ide** [comment]
If the server responds with "status": "ok" that means that Apple received the notification and they will make their best effort to send it. There is no more for you nor Expo to do at that point.

**Comment by itslittlejohn** [comment]
I've opened a separate issue as I feel like my current issue is somewhat unrelated (though you never know!).

https://github.com/expo/expo/issues/1373

Thanks for your help so far @ide .

**Comment by jhalborg** [comment]
> It's not documented anywhere but the push server endpoint expects all push tokens to be for the same project (`@user/slug`).

@ide - Due to the constraint that Apple imposed on you guys sometime last year that a user had to be logged in to the same account to download an experience, I've set up two separate accounts for our app - let's say `company` and `company-shared`. Whenever I want my colleagues to test out new features, I ask them to download Expo, log in to `company-shared`, and fiddle around with the update. This has been the case for push notifications, too, which means that their push tokens have been registered under `company-shared`. Does that mean that they won't receive notifications once I publish the app to our binaries, which are hosted under `company`? If so, how do I fix this?

**Comment by ide** [comment]
Send the notifications for different projects in different requests, i.e. record your slug along with the push token so you can differentiate.
