### ISSUE TITLE
Https delete request dose not work in Andorid & IOS 

### ISSUE THREAD

**Issue by ramisalem** [expo/expo#7925]
### Environment

 Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.6
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: ^4.1.1 => 4.3.7
    npmGlobalPackages:
      expo-cli: 3.11.7

 ExpoKit
### Steps to Reproduce

I have an issue with calling  https requests in expoKit  Android and IOS devices 
### Expected Behavior
The response  of each https request in IOS and Android devices should be the same response in expo web 

### Actual Behavior
An Issue with calling delete method in Android and IOS where it works in expo web without any issues
when calling the https request with delete method it does not send it perfectly to the server and returns an interesting response.
I have tired the same request in  postman, react-native, expo web, and reactjs both of them either return  status code of 204  not content but in expoKit android & IOS I get status code od  200 

### Reproducible Demo

https://snack.expo.io/@ram50/delete-dict

**Comment by byCedric** [comment]
Hi @ramisalem, thanks for reporting this! And thanks for the example 😄 I think this might be related to [some backend frameworks converting DELETE requests to GET](https://stackoverflow.com/questions/44266119/react-native-fetch-api-delete-request-fails-in-app-works-in-postman/44289924) if you don't provide a trailing slash. I [modified your snack just a little bit](https://snack.expo.io/@bycedric/delete-dict) so it includes the trailing slash, and it turns out I'm getting the proper 204 response 😄    

Hope it helps!

**Comment by ramisalem** [comment]
@byCedric Thank you very much

**Comment by byCedric** [comment]
You are welcome! Have fun developing your app 😄

**Comment by ramisalem** [comment]
Thanks for your words Have  a great time
