### ISSUE TITLE
[Bare] expo-notifications does not handle notification payload on Android

### ISSUE THREAD

**Issue by robertying** [expo/expo#7961]
### Environment

  Expo CLI 3.18.6 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.13.0 - ~/.nvm/versions/node/v13.13.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v13.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.13.1 => 16.13.1 
      react-native: 0.62.2 => 0.62.2 

- Standalone (bare workflow)
- Android

### Steps to Reproduce

Send a FCM message with both `notification` and `data` payload:

```js
    {
      notification: {
        title: "Test",
        body: "Hello world!",
        badge: "1",
        sound: "default",
      },
      data: {
        key: value,
      },
	}
```

When app is in the background, FCM itself handles the `notification` payload and shows the notification.

When app is in the foreground, FCM will not do anything, but expo-notifications does not handle the `notification` payload either. So an empty notification is shown.

### Expected Behavior

According to Firebase [doc](https://firebase.google.com/docs/cloud-messaging/android/receive#override-onmessagereceived), we should check the payload if the app's in the foreground.

```java
    // Check if message contains a data payload.
    if (remoteMessage.getData().size() > 0) {
        Log.d(TAG, "Message data payload: " + remoteMessage.getData());

        if (/* Check if data needs to be processed by long running job */ true) {
            // For long-running tasks (10 seconds or more) use WorkManager.
            scheduleJob();
        } else {
            // Handle message within 10 seconds
            handleNow();
        }

    }

    // Check if message contains a notification payload.
    if (remoteMessage.getNotification() != null) {
        Log.d(TAG, "Message Notification Body: " + remoteMessage.getNotification().getBody());
    }

```

### Actual Behavior

expo-notifications, however, only extract `data` from the message, so `notification` is not handled: 

https://github.com/expo/expo/blob/c37c9afa3674c6dd49f251f21b0532a69545f9e4/packages/expo-notifications/android/src/main/java/expo/modules/notifications/FirebaseListenerService.java#L88-L97

**Comment by sjchmiela** [comment]
Hey @robertying, thanks for submitting this issue!

`expo-notifications` uses the `data` property to hold all the notification-related data. So, to use `expo-notifications` to handle the notification (presentation, emitting etc.) instead of sending
```
{
  "notification": {
    "title": "Test",
    "body": "Hello world!",
    "badge": "1",
    "sound": "default"
  },
  "data": {
    "key": "value"
  }
}
```
one should send
```
{
  "data": {
    "title": "Test",
    "message": "Hello world!",
    "badge": "1",
    "sound": "default",
    "body": {
      "key": "value"
    }
  }
}
```

as per [the payload specification](https://github.com/expo/expo/tree/master/packages/expo-notifications#android-push-notification-payload-specification).

When using `expo-notifications`, one shouldn't (need to) use the built-in Firebase Cloud Messaging notification-showing functionality. There are still some differences (eg. FCM supports adding thumbnails to the notification, which `expo-notifications` does not support yet), but in general the module wasn't designed to play with `notification` payload.

Using only the `data` property to transfer notification information gives `expo-notifications` flexibility — we aren't constrained to the FCM-defined `notification` specification. We can also decide in runtime what to do with the incoming notification — whether to present it or not — the `"notification"` notification would have been presented by FCM.

Let me know if that answer your concern!

**Comment by robertying** [comment]
@sjchmiela thanks for clarifying this. I missed that section of the doc 😅. I will try this later.

I still have some other issues about this amazing module though. I don't know if they are worth separate issues, so maybe you can be the judge of that:

- expo-notifications as I see it, does not support `setSmallIcon` and `setColor` which are typically implemented by FCM itself

	`setSmallIcon` get icon from ApplicationInfo but doesn't seem to work for me.
	`setColor` is not supported.
	Can we fallback to use FCM's meta data instead?
	I'm now patching it to be:
	```java
	      ApplicationInfo app = getContext().getPackageManager().getApplicationInfo(getContext().getPackageName(), PackageManager.GET_META_DATA);
	      Bundle bundle = app.metaData;
	
	      int icon = bundle.getInt("com.google.firebase.messaging.default_notification_icon");
	      int color = bundle.getInt("com.google.firebase.messaging.default_notification_color");
	
	      builder.setSmallIcon(icon);
	      builder.setColor(ContextCompat.getColor(getContext(), color));
	```

- expo-notifications on Android does not support initial notifications as iOS does. Is this a planned feature or am i missing something?

Thank you!

**Comment by sjchmiela** [comment]
When it comes to `setSmallIcon`, as you probably have read, `expo-notifications` uses `getContext().getApplicationInfo().icon`, which, well, often is just a circle — that's why it seems to not be working (I think). I will add a way to specify a custom icon for that. 🙂 For `color` too!

When it comes to _initial notification_ support I have just ensured that Android implementation does support this feature the same as iOS. The only head scratcher I have encountered was that I didn't know that tapping on a coalesced view of notifications opens the respective application not triggering the notification open event. What I mean is that if you tapped on "Tap to open the app" in:

![device-2020-04-24-120241](https://user-images.githubusercontent.com/1151041/80200840-887b9800-8623-11ea-922a-6dd9d4bd43cc.png)

Android interprets it as "oh, the user wants to open the app". To actually tap on a notification I had to expand the view with the little chevron to the right of _InitialNotificationTest_, so I got:

![device-2020-04-24-120337](https://user-images.githubusercontent.com/1151041/80200927-a5b06680-8623-11ea-8a38-b8e95cdfb541.png)

Tapping on a notification in this view always triggered the _notification response received listener_, even if the app was closed.

**Comment by robertying** [comment]
Thank you @sjchmiela! 👍 I will try what you suggested, and if things still don't work for me, I'll just open another issue for them.

**Comment by arberK** [comment]
> ... **The only head scratcher I have encountered was that I didn't know that tapping on a coalesced view of notifications opens the respective application not triggering the notification open event.** What I mean is that if you tapped on "Tap to open the app" in:
> 
> ![device-2020-04-24-120241](https://user-images.githubusercontent.com/1151041/80200840-887b9800-8623-11ea-922a-6dd9d4bd43cc.png)
> 
> Android interprets it as "oh, the user wants to open the app". To actually tap on a notification I had to expand the view with the little chevron to the right of _InitialNotificationTest_, so I got:
> 
> ![device-2020-04-24-120337](https://user-images.githubusercontent.com/1151041/80200927-a5b06680-8623-11ea-8a38-b8e95cdfb541.png)
> 
> Tapping on a notification in this view always triggered the _notification response received listener_, even if the app was closed.

Hi, @sjchmiela , I have stumbled upon exactly this issue that you had. How do you recommend handling this case?

**Comment by sjchmiela** [comment]
Hey @arberK! If I understood you correctly, you're asking how one can handle (i.e. receive information) about the fact that a user tapped a group of notifications. Unfortunately, Android does not provide us with information about such event, so there's no way for `expo-notifications` ot provide you with required information. Good news is that it's an Android thing so users are used to it and don't expect your app to act when they tap on a group of notifications. 🙂

**Comment by sjchmiela** [comment]
Hey @robertying, you may be interested to know that `expo-notifications@0.1.4` adds support for custom notifications icons and colors [in a similar manner](https://github.com/expo/expo/pull/8035/files#diff-140c88ecd1cbf4f4746fe41900638bb2) as Firebase does it. 🙂
