### ISSUE TITLE
expo build and I.SIGN_IN_CANCELLED TypeError

### ISSUE THREAD

**Issue by rg4real** [expo/expo#7970]
I've faced a problem. I was building an app sucesfully using android defaul tools. I've uploaded the app to the store and it works on devices.

THen I've tried using expo build:android command and I got this error.

![image](https://user-images.githubusercontent.com/1548235/80127051-74d91e80-859c-11ea-8870-a551426b2f7e.png)

Cannot figure out what is the problem. The app was working perfectly before that but the building process changed that.

What did go wrong and what can be the problem?

Thank you very much.

**Comment by cruzach** [comment]
Sorry, but it's not clear from this issue what the problem could be. What do you mean by building with default Android tools, Android Studio? You can't build a bare project (any React Native project with `ios/` and `android/` directories) with `expo-cli` yet

I'm going to close this since there isn't enough information to help, but if you believe there's a bug then please open a new issue and fill out the whole bug report template, so we can help 😄
