### ISSUE TITLE
Bar code scanner in Expo Client doesn't work when device has only a front camera

### ISSUE THREAD

**Issue by divyanshu013** [expo/expo#801]
Hi guys, awesome work with expo.

I'm using expo on a Nexus 7 which unfortunately has only a front-facing camera. When I click on the **Scan QR Code** option the camera fires up (with the borders and the Cancel button) but all I'm able to see is a black screen. Could this be an issue with the camera since my device doesn't has a rear camera? The app works fine if I type the address manually. Let me know if I can help further with this issue.

Thanks!

**Comment by terribleben** [comment]
Hi, thanks for the report. This might be hard for us to reproduce until we can get our hands on a device like that, but I'll keep this issue open so we can track it.

**Comment by edubbulhoes** [comment]
Hi everyone!
For those who are having black camera when trying to open a project using device camera to read qr code, I am having the same issue and I managed to find a workaround solution.
- In your device, open a browser or any other application with a text input.
- In the text input, type exp://IP_ADDRESS:PORT and then select this entire text and copy it to your clipboard. This entire url is shown when you start the server in the terminal window, just bellow the QR CODE image. It is pretty easy to find.
- Open EXPO and go to your Projects tab. Just bellow SCAN QR CODE option should appear OPEN FROM CLIPBOARD option. Tap this and your application should open.

Hope this work for you as it worked for me, while this issue is not fixed.

My device is a Motorola Moto G version 1 (kinda old...), running Android 5.1
Cheers
