### ISSUE TITLE
scheduleLocalNotificationAsync is off by many seconds on Android

### ISSUE THREAD

**Issue by TrevorSundberg** [expo/expo#8025]
### Environment

  Expo CLI 3.17.23 environment info:
    System:
      OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.18.1 - /usr/bin/node
      npm: 6.13.7 - /usr/local/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.7 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.17.23

Target: Android

### Steps to Reproduce
Use `scheduleLocalNotificationAsync` with a time of 60 seconds, or:
```typescript
{time: new Date().getTime() + 60000}
```

Use a stopwatch to time it once the app opens, such as https://www.google.com/search?q=stopwatch

### Expected Behavior
Notification occurs at the scheduled time (accurate to the second).

### Actual Behavior
Notification is off by 20 to 40 seconds, about 50% of the time. As mentioned, sometimes the notifications are exactly on point, the repro should be ran a few times to confirm.

### Reproducible Demo
https://snack.expo.io/iNhNL9AJ0

**Comment by sjchmiela** [comment]
Hello @TrevorSundberg!

I'm sorry you have to deal with this problem. Most probably this comes from a way notifications are scheduled right now in Expo Client and standalone apps, i.e. they [are based on the since-boot clock](https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/expoview/src/main/java/host/exp/exponent/notifications/ExponentNotificationManager.java#L261) and not on the wall clock (as they [are scheduled in an upcoming `expo-notifications` module](https://github.com/expo/expo/blob/046264a00ee0c6a9b81bc04aa0277fa4d1a12346/packages/expo-notifications/android/src/main/java/expo/modules/notifications/notifications/service/ExpoNotificationSchedulerService.java)). 

I think Android power managing may also affect the timeliness of the notifications, `AlarmManager` has two interesting methods: [`set`](https://developer.android.com/reference/android/app/AlarmManager#set(int,%20long,%20java.lang.String,%20android.app.AlarmManager.OnAlarmListener,%20android.os.Handler)) and [`setAndAllowWhileIdle`](https://developer.android.com/reference/android/app/AlarmManager#setAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent)), where the latter _will be allowed to execute even when the system is in low-power idle (a.k.a. doze) modes_. Would you say that the low-power mode affects the notification time accuracy?

I think a temporary workaround (until we integrate `expo-notifications` in Expo Client and standalone apps) would be to eject to bare workflow and use `expo-notifications`, I strongly believe they don't suffer from this issue.

**Comment by cruzach** [comment]
hey @TrevorSundberg - to follow up on the comment above, we've integrated the new `expo-notifications` module into the managed workflow now 🎉 

I created a Snack here to try and reproduce this behavior: https://snack.expo.io/@charliecruzan/notifications5799

To test it, run the app on your device and tap Press to send notification -> all 3 notifications come in at their scheduled times (as evidenced by the logs), so I think it's safe to say this issue is resolved now, you just need to upgrade to SDK 38, and then follow the new docs for expo-notifications [here](https://docs.expo.io/versions/latest/sdk/notifications/). If you are still able to reproduce this bug with the new module, lmk, and I'll reopen the issue. thanks!
