### ISSUE TITLE
[expo-updates and expo-assets] what are the mandatory unimodules?

### ISSUE THREAD

**Issue by samithaf** [expo/expo#8027]
I am trying to wire up expo-updates and expo-assets so that I can use OTA in an application created using react-native init. 
As per the docs I need to install react-native [unimodules](https://github.com/unimodules/react-native-unimodules) before I install the expo-updates and expo-assets. However I could not find in docs, what are the mandatory uni modules that I need to consume expo-updates and expo-assets. If I know it then I can exclude unwanted modules like follows.

`addUnimodulesDependencies([exclude: ['expo-face-detector']])`

**Comment by byCedric** [comment]
Hi @samithaf! Those two are the only dependencies that you need. `expo-assets` is also only required when you want to include images or other assets in the update. You can see the `expo-updates` for bare projects [documentation over here](https://github.com/expo/expo/tree/master/packages/expo-updates#add-the-package-to-your-npm-dependencies). One thing you could also check out is creating a new bare project with `expo init` and excluding or reading the dependencies from there. All new bare projects have `expo-updates` installed by default. 😄 

Hope it helps!

**Comment by samithaf** [comment]
@byCedric thank you for the suggestion and but I created a bare project and went through the Gradle configuration and it's pulling all the unimodules and same goes with iOS project. See the following code from build.gradle file in a bare expo project. Since I think expo-updates is a fantastic feature it will be great if we can mention in the docs which modules you need.

```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    addUnimodulesDependencies()
```

**Comment by brentvatne** [comment]
@samithaf - it's not actually including face detector, it's only including the *interface file* for that. this is just 30 lines of objc in header files and similar on the android side: https://github.com/expo/expo/blob/master/packages/unimodules-face-detector-interface/ios/UMFaceDetectorInterface/UMFaceDetectorManager.h

we include the interfaces in `react-native-unimodules` because they are so small that they have no impact on your final app size and make it easier to install other expo sdk packages when you need to. see `react-native-unimodules` package.json: https://github.com/unimodules/react-native-unimodules/blob/3287d3ffa74cf3a403d13871db992e4db193f48e/package.json#L19-L34

the only ones with actual implementations are `expo-asset`, `expo-file-system`, and `expo-permissions`, and a very minimal `expo-image-loader` that just interacts with the react-native image-loader.

you can remove `expo-permissions` and `expo-image-loader` if you like, and most of the interfaces.

**Comment by samithaf** [comment]
@brentvatne thank you for the clarification. Also can I noticed that expo bare project is using `react-native 0.61.5` but not the latest stable. I am sure that it take lot of effort and time to keep everything up to date. 
However I am keen to know that if you have done any testing with latest version `react-native` and `expo-updates` and `expo-assets`. We are using `Swift 5` in our project and I will post a code snippet as well once the integration is complete so other people will find it useful.

**Comment by samithaf** [comment]
@brentvatne I just tried out `expo-updates` with latest stable `react-native` and it seems working fine. Also verified the release build with OTA updates. Here are all the files if anyone would like to use `expo-updates` with latest `react-native`

https://gist.github.com/samithaf/9a434d0e0feee6babdc35861d454c458

**Comment by samithaf** [comment]
I have created a working sample App (started from react-native init) and added Expo OTA, React Native Navigation as well. https://github.com/samithaf/react-native-app. CC @brentvatne

**Comment by brentvatne** [comment]
cool! good to hear. we don't update to the latest release of react-native right away because release doesn't always really mean stable - usually a number of significant bugs are found in the first month or so after the release, so we wait for that to shakeout. there are a lot of great features in 0.62 so i understand your enthusiasm to upgrade though! thanks for sharing the repo!

**Comment by brentvatne** [comment]
btw, you may want to give react-native-screens native-stack a try with react-navigation! it's pretty great. https://github.com/software-mansion/react-native-screens/tree/master/native-stack - it's a nice alternative to using react-native-navigation

**Comment by samithaf** [comment]
aha cool. I will have a look. To be honest we are working on pretty [large App](https://play.google.com/store/apps/details?id=au.com.bt.panorama&hl=en_AU) and already started using React native navigation last year. Then we stopped for a while and started again. 

But yes will have a look at react-native-screens project as well. We have fully native screens as well, so just need to see how all get wired up :)

**Comment by RichardFevrier** [comment]
> the only ones with actual implementations are expo-asset, expo-file-system, and expo-permissions, and a very minimal expo-image-loader that just interacts with the react-native image-loader.

Any plan to remove them in the future @brentvatne ?
