### ISSUE TITLE
[docs] InAppPurchases.getProductsAsync can only have one active promise at a time

### ISSUE THREAD

**Issue by slauzinho** [expo/expo#8039]
I'm not sure if this is the intended behavior but I don't see any mention of it in the docs.

So if you have two components that handle different products and you need to make two calls to `getProductsAsync` the second call will error out  by throwing `Error: Must wait for promise to resolve before recalling function.`. 

So we need to make sure we make those calls sequentially to avoid any bugs.

**Comment by cruzach** [comment]
looks like this applies to 4 of the methods available in the module (`connectAsync`, `getProductsAsync`,`purchaseItemAsync`, `getPurchaseHistoryAsync`)- https://github.com/expo/expo/blob/6d89f66930e8c5861d4d34c1af3548e9450bf7dd/ios/versioned-react-native/ABI36_0_0/Expo/EXInAppPurchases/ABI36_0_0EXInAppPurchases/ABI36_0_0EXInAppPurchasesModule.m#L283-L294

Would you like to open a PR for this?

**Comment by alef-carvalho** [comment]
same problem here

**Comment by waheedakhtar694** [comment]
@cruzach Any solution for this?

**Comment by cruzach** [comment]
I'm not sure that this is a bug- why would you want to make two calls in parallel to `getProductsAsync`? You should make one call, get the data for both products you plan to make available for purchase, and pass that data to the relevant components. 

I'm going to close this for now but can re-open if you can clarify what the bug is
