### ISSUE TITLE
hope has a option that build ios ipa wihtout bitcode 

### ISSUE THREAD

**Issue by yuanzougaofei97** [expo/expo#806]
hope has a option that build ios ipa wihtout bitcode because sometimes need enterprise distribution or real device test

**Comment by fxfactorial** [comment]
Can you give more detail please? Like you don't want bitcode turned on?

**Comment by yuanzougaofei97** [comment]
Expo is a good product that speeds up the build of mobile apps,  but now I think what's bothering 
 me most is building a without bitcode ios package that is very troublesome Now build:ios to build an ipa with bitcode, which is too big, over 140 MB,and can't be tested on a real machine. And I think using ios has a lot of scenarios is just within the enterprise,do not need to be released to the app store. Although with bitcode is indeed necessary, but I hope let users have a choice whether with bitcode to build the ipa.
                                                                                                                                                  thanks !

**Comment by terribleben** [comment]
Hi, we don't plan on adding this option because the Expo SDK depends on third party libraries that require bitcode.

Because of [app thinning](https://docs.expo.io/versions/latest/guides/building-standalone-apps.html#4-wait-for-it-to-finish-building), your app's size on any given device (or in the app store) is significantly smaller than the 100+ mb archive we generate for you. Although we do view binary bloat as a problem we'd like to address in the future, we're talking realistically about a ~30mb app at the time of writing, not 140 mb.

**Comment by justinsayone** [comment]
I recently added an iPhone X to my developer account and since then the IPA size has increased drastically. This is the only change I made. The size was around 30mb before this change. Does anyone have any idea why this happens?
