### ISSUE TITLE
Base workflow expo-splash-screen error

### ISSUE THREAD

**Issue by JasonRoyer** [expo/expo#8067]
### Environment
  Expo CLI 3.19.2 environment info:
    System:
      OS: macOS Mojave 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.0 - /usr/local/opt/node@12/bin/node
      Yarn: 1.6.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.8 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.19.2

Happens on both IOS and Android. Both in expo client and in xcode on a release version.
### Steps to Reproduce
Use expo-splash-screen in any created project

expo init 
    -bare
expo install expo-splash-screen
cd IOS
pod install
cd .. 
yarn expo-splash-screen "#ec03fc"

edit App.js (add the below code)
    import * as SplashScreen from 'expo-splash-screen';

    SplashScreen.preventAutoHideAsync()
    .catch(console.error);
run `expo start`
run either IOS or Android / or run from xcode/android studio

Get the following error, notice the splash screen is the correct pink/purple color. 

### Expected Behavior
Splash screen never goes away. (in my snack you can see i never hid the splash screen).

### Actual Behavior
undefined is not an object (evaluating '_ExpoSplashScreen.default.preventAutoHideAsync')
- node_modules/expo-splash-screen/build/SplashScreen.js:23:7 in preventAutoHideAsync
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch

If you print the keys for NativeModulesProxy in ./node_modules/expo-spash-screen/build/ExpoSplashScreen.js you will notice that `ExpoSplashScreen` does not exist and this is what the error is.

### Reproducible Demo

https://snack.expo.io/3zNZ!I0!E

**Comment by bkbooth** [comment]
I fixed this by running `pod install` in the `ios` folder. I missed this in the docs 🤦

**Comment by JasonRoyer** [comment]
I tried running `pod install` multiple separate times and it did not solve my problem. I even specifically looked for ` expo-splash-screen@0.2.0 from ../node_modules/expo-splash-screen/ios` in the console. I also tried downgrading expo-splash-screen to 0.1.1 and it still did not help.

**Comment by bkbooth** [comment]
Oh, turns out I'm still seeing that error when I run the app with `expo`. It's not supported in `expo` managed projects (https://github.com/expo/expo/blob/master/packages/expo-splash-screen/README.md#-installation-in-managed-expo-projects), so maybe that applies to bare projects run with `expo` too?

I'm not seeing this error anymore on device since doing `pod install` and running with `yarn ios`.

**Comment by byCedric** [comment]
Hi guys! Thanks for the issue and the suggestions 😄 Like @bkbooth mentioned, `expo-splash-screen` is only supported in the bare workflow. In managed, it will error out with the error you received. What this means is you have to start your project in bare mode, without the Expo client. Could you try if `yarn android` or `yarn ios` (instead of `expo start`) works for you? This will create your app and install it on either a simulator or connected devices.

Hope it helps!

**Comment by bkbooth** [comment]
Thanks @byCedric! I ran into this error having just ejected from the managed workflow and trying to get everything up and running in the bare workflow. In my case I'd forgotten to run `pod install` in the `ios` folder after installing `expo-splash-screen` ( still getting used to the new workflow). Everything seems to be working fine for me running it with `yarn android` and `yarn ios`.

It seems like @JasonRoyer ran into this in slightly different circumstances though.

**Comment by JasonRoyer** [comment]
@byCedric I thought based on https://docs.expo.io/bare/using-expo-client/ and https://docs.expo.io/bare/unimodules-full-list/ That expo-splash-screen could be used in the bare workflow inside the expo client. 

Even in the bare workflow expo client is still heavily used for dev purposes. Do the new Expo packages for the bare workflow count as "native code that isn't included in the Expo SDK"? Currently i am trying to switch from ExpoKit to a bare workflow because of SDK 37.

**Comment by byCedric** [comment]
@JasonRoyer You are right, you can use the Expo client in bare but there are some limitations. It's a bit confusing seeing `SplashScreen` listed in the unimodules list with "Available in ..." and I'm sorry for that.

- The listed unimodules is the "older" `import { SplashScreen } from 'expo';` module, not the `expo-splash-screen` package. And I think the older one isn't actually available for bare. So again, sorry for the confusion! I'll try to update the docs for this one.
- Because `expo-splash-screen` isn't working for managed at the moment, you can consider it more like "custom native code". I can't rule out that we will add this package eventually and make it work for managed too. But that's the limitation of the Expo client.

As for your errors, if you can, could you share some of them? Maybe we can help fixing that so you can enjoy the "full bare experience", without these annoying issues 😄

**Comment by byCedric** [comment]
@JasonRoyer I just opened a PR that should fix the interchangeability of `expo-splash-screen` in the Expo client, or managed workflow. Once this lands, it means you should be able to use the same package (`expo-splash-screen`) inside your bare project within the Expo client 😄 It just falls back to the older `import { SplashScreen } from 'expo'`, but with the same API as `expo-splash-screen`.

Hope this makes life easier!
