### ISSUE TITLE
Push notifications on iOS in production does not work.

### ISSUE THREAD

**Issue by georgeMorales** [expo/expo#8100]
Recently, push notifications do not work in iOS in production or compiled, in development it works perfectly but in production it does not.
It has always been working without a problem. I don't know if it will be when updating to sdk37 or if it is from the certificates ...
Expo push notification key is enabled in apple developer platform.
On android it works perfect.
Expo sdk 37
expo-server-sdk: "^ 3.2.0",

**Comment by cruzach** [comment]
We need more information to help you, most importantly is the error message that is present in the push receipt, it's most likely one of these - https://docs.expo.io/guides/push-notifications/?redirected#errors

That documentation page will also tell you how to get the push receipt. Since this isn't a bug report and is more of a question, I'm going to close this issue. Questions like this are better suited for our [forums](https://forums.expo.io/) (when you do find the error message, i suggest searching for other solutions there on our forums 😄 )
