### ISSUE TITLE
Fast Refresh is EXTREMELY slow when Remote Debugging is On

### ISSUE THREAD

**Issue by alishehzad2017** [expo/expo#8131]
So just yesterday fast refreshed worked fine when remote debugging was on for relatively complex apps.

But today it’s taking **~3 minutes** when **remote debugging is on**.

Even when I test it on a simple app that renders the text ‘Hello World!’ and I change the text to ‘Hello’ and save the file, the change takes effect after ~3 minutes.

I’m using an Android device with the app updated to it’s latest version. I’m currently using SDK 37 but this bug also occurs with my past apps with older SDK versions.

Why has this suddenly started happening today? Any help will be DEEPLY appreciated!

**Comment by byCedric** [comment]
Hi @alishehzad2017! That doesn't sound like a good developer experience, sorry for that. Unfortunately, this issue is a bit hard to solve. I'm not exactly sure what problem you encounter. The remote debugger is hitting the performance by "moving" the JS thread to your computer and hook into it by tcp.

You could try some of the issues and fixes mentioned in [this StackOverflow thread](https://stackoverflow.com/questions/42142933/react-native-debugger-is-too-slow). If everything fails, you could try resetting the data on your phone or use a simulator/emulator and see if the problem persists. Hope it helps a bit, if not let me know to see how we can help.

**Comment by alishehzad2017** [comment]
My phone clock was a few seconds behind as mentioned in the top comment of the StackOverflow link you posted. Syncing it solved the problem.

Thank you so much :)
