### ISSUE TITLE
Expo Payments not supporting authentication

### ISSUE THREAD

**Issue by aren-pulid0** [expo/expo#8178]
Due to SCA credit card payments new may need authentication.

Tipsi-Stripe already implemented it in new beta. It would be awesome if this upgrade could be done in expo's payment solution it would be great. And most likely it will be necessary very soon

**Comment by byCedric** [comment]
Hi @aren-pulid0, thanks for mentioning this! To clarify, are you using `expo-payments-stripe`? If so, I'll put this on our todo list. I can't give you a timeline, but we will get to it eventually! 😄

**Comment by ryanmitchell** [comment]
+1 on this - it would be great to sync in with the new tipsi beta to allow SCA support in expo

**Comment by cruzach** [comment]
Hi! Since the `expo-payments-stripe` module was deprecated with the release of SDK 42, I'm going to close this issue.

We collaborated with the team at Stripe to make the `@stripe/stripe-react-native` library work seamlessly in Expo projects, so we recommend you use that library instead. [Learn more in the API reference](https://docs.expo.io/versions/latest/sdk/stripe/), and check out this [excellent YouTube video that walks through integrating Stripe in your Expo app](https://www.youtube.com/watch?v=DZlAET7Tgx4&ab_channel=UnsureProgrammer). Thanks!
