### ISSUE TITLE
Constants.manifest type should reflect that it is null in bare workflow in development

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8231]
- Constants.manifest is null in bare workflow
- The type indicates that it is never null
- This will be a breaking change because people will need to check if manifest is available before accessing a property on it

**Comment by byCedric** [comment]
While working on the guide for environment variables, I noticed the docs also don't mention manifest is null in bare. I think we should update that too.

**Comment by duckbrain** [comment]
So this is intentional behavior? I was using this to get the `releaseChannel`, `version`, and `revisionId`.

I'm experimenting with generating a file to include the release channel and version with the build, but the `revisionId` is created on `expo publish`, so I don't see a way to inject that.

**Comment by timoisalive** [comment]
So, what's the deal, is `Constants.manifest` ever accessible in Bare workflow? How come does the documentation say anything about it...? And most of all, how should I access the manifest in Bare workflow?

**Comment by brentvatne** [comment]
@timoisalive - since sdk 41, yes it is in bare workflow. it does not, however, include the update manifest in all cases. it includes the "app config" -- the output of `expo config --type public`

use `Updates.manifest` to get the update manifest. only available after you have actually downloaded an update in the app

**Comment by timoisalive** [comment]
@brentvatne - Thanks for the quick reply! 👍

I am not primarily interested in the update information, but rather the "app config" information you mentioned.

If that data should always be available, I must have something else wrong, because I'm on sdk 42 and the `Constants.manifest` is `null`, at least when running locally.

 I've been developing on the managed workflow so far, but I should now start using a package with native code, so I tried `expo run:ios`, without yet installing the new native packages. This yields in an error for not finding the manifest, and I also get a warning:
 
 "Constants.manifest is null beacause the embedded app.config could not be read. Ensure that you have installed the expo-constants build scripts if you need to read from Contants.manifest."
 
However,  I find no documentation on how to "install expo-constants build scripts"...

**Comment by timoisalive** [comment]
I tried with a blank project.

I initialized a "Blank Managed TS project", added `console.log(Constants.manifest);` in the `App.tsx` and ran `expo start`. All good, the manifest logs.
 
Then did `expo run:ios` and got this:

![simulator_screenshot_E91942B4-F19A-4869-9584-E423FB46D9B1](https://user-images.githubusercontent.com/5088388/133744875-7d368c0e-9e09-4d39-bccf-b38b5b677b1f.png)

Is this expected behaviour?

**Comment by timoisalive** [comment]
And still confirming that the warning is the same if I directly initiate a Bare project, install `expo-constants` and log the manifest in `App.js`.

**Comment by timoisalive** [comment]
Any comment on the above @brentvatne ...?

**Comment by brentvatne** [comment]
@timoisalive - you are 100% correct. apologies, i missed a change to expo-constants while i was out on vacation. it seems that there was a regression caused by this pr: https://github.com/expo/expo/pull/14116

i've gone ahead and rolled back the latest version of expo-constants on npm to 11.0.1. you can downgrade explicitly to that version, or try your exact repro steps above again and notice it should work as expected

**Comment by timoisalive** [comment]
Thanks @brentvatne! It works now in a blank project, so I know it's fixed! But unfortunately I'm still getting the same errors in our project.... 😢 Will keep on debugging!

**Comment by anirudh-eka** [comment]
@timoisalive curious if you found a fix that worked for your project. We're facing the same issue too even with `expo-constants` at `11.0.1`

**Comment by eduardomarr** [comment]
same issue here on "expo-constants": "~11.0.1",

[anirudh-eka](https://github.com/anirudh-eka)

**Comment by eduardomarr** [comment]
> @timoisalive curious if you found a fix that worked for your project. We're facing the same issue too even with `expo-constants` at `11.0.1`

same issue here on "expo-constants": "~11.0.1",
