### ISSUE TITLE
Define a convention for a directory to exclude from npm package and formalize in expo-module-scripts

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8234]
In expo-splash-screen there is a directory called [assets](https://github.com/expo/expo/tree/master/packages/expo-splash-screen/assets) that includes 40mb of images that are used in the README. We don't want to publish those to npm, but expo-module-scripts will overwrite any changes to `npmignore` in prepare unless you remove the `@generated` annotation, which @ide recommends against because it increases maintenance burden.

So we should have some convention for a directory where we can put files like images to be used in README and then add that directory to the expo-module-scripts template .gitignore.

Related, we should update the expo-module-scripts README to clarify how npmignore and files in package.json should be treated.

**Comment by byCedric** [comment]
Is [whitelisting](https://medium.com/@jdxcode/for-the-love-of-god-dont-use-npmignore-f93c08909d8d#5360) the files we want to publish, per package, an option?

**Comment by ide** [comment]
We can do both but it's harder to keep part of a file (`files` in package.json) consistent across all modules than it is to keep an entire file (.npmignore) in sync. I think trying to keep "files" in sync will end up taking up our time because parts of package.json will be freeform and parts will be generated.

I see three approaches:
- Use .npmignore but be specific about what we want to include by inverting it: exclude `/` and then explicitly include `!/build/` and other files (`/*.json`?). If we were to do this, I'd want to make sure that specifying more files in `files` in package.json actually does include those files. That way people can add more files if their package needs them.
  - This seems like a nice solution but I would want to be careful not to be too constraining.
- Edit .npmignore in expo-splash-screen and remove `@generated`. This "forks" the .npmignore file and it will no longer receive updates from expo-module-scripts.
- Update the .npmignore template in expo-module-scripts to make it ignore a hardcoded folder like `/.npmignored/` and move `assets` under there.
