### ISSUE TITLE
Fresh install from Google Play not latest

### ISSUE THREAD

**Issue by James2516** [expo/expo#824]
When user install the app from Google Play and open it, it'd be the version we uploaded to the Google Play, instead of the latest published to expo server. 
User would have to close the app from recents list, then reopen it to get the latest version (and most user don't do that, they just install and start using right away).

Is there no way around this? So we should still regularly upload a new build to the Google Play (subjecting to review again)?

**Comment by ide** [comment]
That's correct. This is because when you build a standalone APK, your JS **at the time of building the APK** is embedded in the APK so that users can open your app without an internet connection or network latency.

Theoretically we could expose a way to customize this policy (ex: customize when to check for a new JS update on launch and how long to wait) but that adds non-trivial complexity to the implementation and debugging and it is not planned. Just sharing this to set expectations accordingly.

Regularly uploading new builds to Google Play is a good idea. In addition to the reason you mentioned, Expo drops support for old SDK versions after about half a year (as in, the Expo client won't be able to load old projects) so it's highly recommended to keep your project up to date anyway.

**Comment by James2516** [comment]
@ide 

> users can open your app without an internet connection

if they just installed the app, they probably have the internet connection to install the app anyway.

> check for a new JS update on launch

Isn't that already the case for every subsequent launches? Why can't the same mechanism be implemented for the initial app in the APK?

> Regularly uploading new builds to Google Play is a good idea

Still, reviews could take days and sometimes Expo's instant update is really useful to fix critical bugs.

**Comment by ide** [comment]
> if they just installed the app, they probably have the internet connection (in order to install the app) anyway.

We've found in practice this often isn't the case. Also people have much more patience waiting for a download from the Play Store than waiting for their app to open.

> Isn't that already the case for every subsequent launches? Why can't the same mechanism be implemented for the initial app in the APK?

Subsequent launches also concurrently check for updates in the background while launching the app. Initial launches and subsequent launches behave the same.

> Still, Google/Apple app reviews could take days and sometimes Expo's instant update is really useful to fix critical bugs.

That's true (for Apple reviews at least) and it'd be nice if we could have the best of all worlds but given reality, we've chosen to prioritize speed and predictability of launching apps.

**Comment by James2516** [comment]
> Subsequent launches also concurrently check for updates in the background while launching the app. Initial launches and subsequent launches behave the same.

Huh so the initial launch from fresh install is also concurrently checking for update while launching? Why didn't it update to the latest then (like subsequent launches)?

**Comment by ide** [comment]
When the app launches from cold boot it does two things concurrently: (1) it launches the local copy of the JS that it has (on the initial launch this is the embedded JS, on subsequent launches this is cached JS that may have been downloaded the previous time the app was launched) and (2) it checks for new JS in the background and if there is an update, the app downloads and caches the JS for the next time the app launches. The mental model for the initial launch and subsequent launches is the same.

From the docs:
> On Android, updates are downloaded in the background. This means that the first time a user opens your app after an update they will get the old version while the new version is downloaded in the background. The second time they open the app they’ll get the new version.

**Comment by James2516** [comment]
So this issue doesn't apply to iOS? which means i don't have to resubmit to Apple store unless there's a major Expo client update (currently at 21.0)?

**Comment by ide** [comment]
That's currently true but may change to become more consistent with Android. We'll update the docs when that behavior changes.

**Comment by James2516** [comment]
I noticed that after installing from Google Play, the app must be connected to the internet on first open otherwise it crashes immediately. 
Why is that the case? Couldn't it just fall back to the binary uploaded on Google play?

**Comment by ide** [comment]
Standalone Android apps currently always use the local copy of the JS and asynchronously update that local copy in the background, for the next time the app is launched. I just tested installing an app from Google Play, turning on Airplane Mode, and launching it for the first time. If you're seeing a crash it's likely because of some other reason and will need to debug further e.g. by looking at adb logs.

**Comment by James2516** [comment]
> On Android, updates are downloaded in the background. This means that the first time a user opens your app after an update they will get the old version while the new version is downloaded in the background. The second time they open the app they’ll get the new version.

@ide is this no longer true as of v25.0? Android seems to be getting the latest version on first load.

**Comment by ide** [comment]
Yes, updates are fetched in the background.
