### ISSUE TITLE
LocalAuthentication does not match UX of other Android Apps in SDK37

### ISSUE THREAD

**Issue by ConorWatsonSoar** [expo/expo#8246]
### Environment

``` bash
  Expo CLI 3.20.1 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.1 LTS (Bionic Beaver)
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.9.1/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.3
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
      react-navigation: ^4.2.2 => 4.2.2
    npmGlobalPackages:
      expo-cli: 3.20.1
```

Targeting Android via Standalone and Client. Reproduced on a Samsung Galaxy S10+, with the latest version of the Expo Client installed (v2.15.0).

### Steps to Reproduce

1. Start/Upgrade a Project with SDK37
2. Call `LocalAuthentication.authenticateAsync()`

### Expected Behavior

Android Authentication UI should appear on top of the screen that is currently requests Authentication.

| Regular Android Authentication |
| ------------------------ | 
| ![Regular Android Authentication](https://user-images.githubusercontent.com/58003329/81548927-ede6bd00-9375-11ea-8eeb-a104b20a639b.gif) | 

### Actual Behavior

Android Authentication UI appears in a separate screen before the user is navigated back to their original screen.

| SDK37 LocalAuthentication |
| ------------------------ | 
| ![SDK37 LocalAuthentication](https://user-images.githubusercontent.com/58003329/81548754-b11ac600-9375-11ea-978f-03beb447c261.gif) |

### Reproducible Demo

I have created a reproducible Snack demo [here](https://snack.expo.io/9f1tFbmgi). I can also confirm that this problem is exhibited when a standalone app has been built in SDK37. 

Interestingly, the UI appears correctly when using the Android simulator on the Snack. However running the Snack on my Samsung S10+ I can reproduce the unexpected behaviour, and my friend is also able to reproduce similar behaviour on his One Plus 7 Pro.

EDIT: I managed to get a hold of a Pixel 4, and the UI _does_ appear correctly on this device. It's possible it's a "Custom" UI issue?

**Comment by rafmst** [comment]
Any news on this? Its not something urgent, but we are thinking about implementing this at my company, would be nice to have this working

**Comment by sukso96100** [comment]
I can also see that UI appears in weird way. Since latest version of Localauthentication uses BiometricPrompt on Android, I think it should show system ui for biometric authentication like the photo below.
![Screenshot_20200524-124507_Toss](https://user-images.githubusercontent.com/1916739/82747310-982cfe80-9dd2-11ea-8617-0f4768d3942a.jpg)

On Samsung device with Android 10, Expo also shows the system biometric authentication ui. But in a bit weird way. Whether test it on expo client or standalone build, It shows the dialog on the seperate black empty screen. 
![Screenshot_20200519-151712_Settings](https://user-images.githubusercontent.com/1916739/82747348-fa85ff00-9dd2-11ea-89a0-545af5a283f3.jpg)


And it seems like it only happens on Samsung device with Android 10. I tested the snack on Appetize.io with Android 10. And it showed the prompt properly.
![Screenshot_20200524-153721_Chrome](https://user-images.githubusercontent.com/1916739/82747660-52723500-9dd6-11ea-85b7-780e5639b199.jpg)

**Comment by ConorWatsonSoar** [comment]
Seems like this is potentially an issue with Google [blacklisting](https://github.com/expo/expo/issues/7838#issuecomment-615486946) some of the major Samsung flagships. However there must be a solution as every Native app I use on the S10+ can display the Biometric Popup correctly.

**Comment by KiratiBhuva** [comment]
Hi, I am having the same issue with Samsung device, @ConorWatsonSoar did you find any solution for this issue?

**Comment by isidoro98** [comment]
Hey @ConorWatsonSoar @KiratiBhuva any updates on this ?
