### ISSUE TITLE
[SDK 37] - Firebase is not configured. Ensure that you have configured 'GoogleService-Info.plist' correctly.

### ISSUE THREAD

**Issue by Nilomiranda** [expo/expo#8277]
### Environment

```
Expo CLI 3.18.6 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.8.1 - ~/.nvm/versions/node/v12.8.1/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.10.2 - ~/.nvm/versions/node/v12.8.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.18.6
```
Targeting: iOS devices

### Steps to Reproduce

I'm not sure there's really a specific case here but setting up a project to use Firebase analytics
following from https://docs.expo.io/guides/setup-native-firebase/ and building the iOS app may throw the error.

The error is thrown the moment we invoke the Analytics function `setCurrentScreen` like below:

```
Analytics.setCurrentScreen(currentRouteName, currentRouteName)
```

### Expected Behaviour

Wasn't expecting any error to be thrown in regards to the configuration. But this is what happens when the function described above is called:

> Firebase is not configured. Ensure that you have configured 'GoogleService-Info.plist' correctly.

In case anyone is wondering, the `GoogleService-Info.plist` was simply downloaded from what Firebase generated and placed inside

`/assets/firebase/GoogleService-Info.plist`

Then, in `app.json`, in the ios configuration I point to the `plist` file, like this:

```json
"ios": {
      "supportsTablet": false,
      "bundleIdentifier": "#####",
      "buildNumber": "1.0.13",
      "googleServicesFile": "./assets/firebase/GoogleService-Info.plist"
    },
```

**Comment by antonjlin** [comment]
having this issue as well. please bump!

**Comment by shreyas-n** [comment]
@ide @fson please help! Currently experiencing this as well

**Comment by ide** [comment]
Please use just the :+1: reaction on issues. If an issue is marked as "Needs Triaged" it will be triaged amongst the other issues.

The best way to resolve an issue if it is truly important to you is to help diagnose the root cause. Issues that include diagnosis of the root cause will be tagged with "⭐️Root Cause Known".

**Comment by He1nr1chK** [comment]
I am experiencing this only on Android. My iOS app works fine. I started getting the warning when I upgraded to Expo 37 and changed to the bare workflow from ExpoKit. 

  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.1.0 - /usr/local/bin/node
      Yarn: 1.22.4 - ~/.yvm/shim/yarn
      npm: 6.14.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.3 => 37.0.3 
      react: ~16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ^0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.1

app.json

`...
"ios": {
            "googleServicesFile": "ios/GoogleService-Info.plist"
        },
        "android": {
            "googleServicesFile": "android/app/google-services.json"
        },
...`

**Comment by He1nr1chK** [comment]
Solved my issue by following this guide [https://docs.expo.io/guides/setup-native-firebase/](https://docs.expo.io/guides/setup-native-firebase/)

**Comment by Nilomiranda** [comment]
> Solved my issue by following this guide https://docs.expo.io/guides/setup-native-firebase/

Hey @He1nr1chK thanks for your attention. Unfortunately we already have the configuration in `app.json` following this guide and the problem still persists. 

Also, we only experience this in the iOS version of the deployed app. 

None of this happens during development using the expo client, so it's really hard to pin point the cause of this issue.

**Comment by He1nr1chK** [comment]
@Nilomiranda, I believe your issue lies in the location of your plist. As mentioned in the guide, you should open Xcode and drag the plist file into your project pane. When the popup appears your must ensure that the **Copy items if needed** option is selected. I think this has something to do with native firebase searching for this file in the iOS folder. Remember to update your app.json path to ios/GoogleService-Info.plist. Give it a try and and let me know if it works for you.

**Comment by xdajay** [comment]
@ide Please also note that as per documentation for **firebase analytics**, web firebase confirmation needs to be done for events to get logged in Expo client and manage flow doesn't require plist configuration, but the biggest problem is not the error, **but entire code flow breaks where ever the event is included.** For example: If the button pressed and which has screen navigation, it won't just navigate and will through runtime error.. not just that where ever event log is added, on error it won't even execute next line and load data. **Making it extremely hard to work in Dev Environment with Expo client.**  

@ide Please suggest some immediate work around this.

**Comment by brentvatne** [comment]
@xdajay - I appreciate your effort on the above description but I don't quite follow the issue that you are encountering. You need to include an event name to log anything.

In https://github.com/brentvatne/expo-firebase-analytics-integration-example we log an event like this: https://github.com/brentvatne/expo-firebase-analytics-integration-example/blob/master/App.tsx#L12

This works as expected in Expo client and in standalone app builds. So it's not clear to me what the issue is.

**Comment by xdajay** [comment]
@brentvatne  Got it solved! No longer getting this error and code isn't breaking. I forgot to follow this step: 

"To use this package, the native Firebase configurations needs to be added to your app. Please follow this guide on how to set up Native Firebase." 

**Suggestion**  Please in documentation also add this configuration step is also required for Managed workflow! Sometimes it gets really confusing as managed workflow requires least manual configuration.

Thanks

**Comment by Nilomiranda** [comment]
> @Nilomiranda, I believe your issue lies in the location of your plist. As mentioned in the guide, you should open Xcode and drag the plist file into your project pane. When the popup appears your must ensure that the **Copy items if needed** option is selected. I think this has something to do with native firebase searching for this file in the iOS folder. Remember to update your app.json path to ios/GoogleService-Info.plist. Give it a try and and let me know if it works for you.

But I don't have access to the ios project, unless I eject from Expo.

**Comment by He1nr1chK** [comment]
@Nilomiranda if you are still using the Expo client and have not ejected, read this section of the guide [https://docs.expo.io/versions/latest/sdk/firebase-analytics/#expo-client-limitations--configuration](https://docs.expo.io/versions/latest/sdk/firebase-analytics/#expo-client-limitations--configuration)

**Comment by He1nr1chK** [comment]
In that case I believe you have to configure the analytics like you would a web project and not a native project.

**Comment by Nilomiranda** [comment]
I'll close this for now, since I don't need to use Firebase analytics in the project anymore.

**Comment by sandrina-p** [comment]
I'm having the same issue, using expo managed workflow + Firebase Analytics. I don't have the error in dev mode, only in a test flight version. What should I do?

**Comment by sandrina-p** [comment]
I found the issue! I released an [OTA Updates](https://docs.expo.io/guides/configuring-ota-updates/) that included the analytics but forgot to release the iOS build to Test Flight. I forgot that when `app.json` (ìos.googleServicesFile`) is changed, it must be released a new iOS build. I released it and it fixed the problem 🙌

**Comment by frederikocmr** [comment]
Since you're trying to use `Analytics.setCurrentScreen()` or any other "native" call of the Analytics, it will not work on a Expo Go / Managed project, here you have a snippet from the docs explaining this part:


## Expo Go: Limitations & configuration

The use of Native Firebase Analytics requires that the google-services configuration is bundled and linked into your app. Since Expo Go loads projects on demand, it does not have the google-services configuration linked into its app-bundle.

Instead, Expo Go relies on a JavaScript-based implementation of Firebase Analytics to log events. This means that certain native life-cycle events are not recorded in the standard client, but you can still use `logEvent` to record events.

You may want to use Firebase Analytics in Expo Go to verify that you are logging events at the time you intend to and with the data that you want to attach without having to do a standalone app build. To set this up, ensure that the Firebase web configuration is set in `app.json` and that `measurementId` exists in your firebase config. If `measurementId` doesn't exist, then you need to enable or update Google Analytics in your Firebase project.

**app.json**

```json
{
  "expo": {
    "web": {
      "config": {
        "firebase": {
          "apiKey": "AIzaXXXXXXXX-xxxxxxxxxxxxxxxxxxx",
          ...
          "measurementId": "G-XXXXXXXXX"
        }
      }
    }
  }
}
```

> This limitation only applies to the Expo Go app in the App and Play stores; standalone builds, custom clients & bare apps support the full native Firebase Analytics experience.

**Comment by kelechionyeama** [comment]
> @xdajay - I appreciate your effort on the above description but I don't quite follow the issue that you are encountering. You need to include an event name to log anything.
> 
> In https://github.com/brentvatne/expo-firebase-analytics-integration-example we log an event like this: https://github.com/brentvatne/expo-firebase-analytics-integration-example/blob/master/App.tsx#L12
> 
> This works as expected in Expo client and in standalone app builds. So it's not clear to me what the issue is.

Hey!, thanks so much for this but how are those config files generated or downloaded from? when i check firebase ill need  an apple bundle id from xcode to create an ios app which i dont have nor dont understand how it relates to expo
