### ISSUE TITLE
[docs] [expo-server-sdk-node] Why "server-side"?

### ISSUE THREAD

**Issue by BrodaNoel** [expo/expo#8338]
Why are you saying that `expo-server-sdk-node` is a server side library?

I mean... I have a moderation-internal-site where I am developing a panel to send notifications.
Why should `expo-server-sdk-node` be used on the server side?
I don't see any limitation to use it in the frontend. I am missing something?

**Comment by ChronSyn** [comment]
Just from looking at the source (which appears to be only 1 file), it relies on zlib (part of node).

Additionally, I would imagine that in order to send notifications, you would have to potentially expose sensitive data (such as push tokens) to the front-end, rather than simply exposing a user id, which would be linked to your database.

Finally, it could also be that it requires server-to-server communication, in the same way stripe's server-side SDK's won't work on the front-end (as they are unable to communicate with the stripe API from there - though it's been a while since I last looked at it, this may no longer be the case)

**Comment by BrodaNoel** [comment]
Well... The `zlib` is enough excuse to make it server-side, but the security stuff is something that should be handled by the developer, not the library.
For example, my "frontend" is a web that is not published on internet. It works in my local env, in `localhost`.

But, again, the `zlib` is enough. Good catch.
