### ISSUE TITLE
[iOS] Video Pause/Play Laggy

### ISSUE THREAD

**Issue by Jay-Mithani** [expo/expo#8358]
## 🐛 Bug Report

The Expo Video component lags on play / pause.

### Environment

Expo SDK 37 (latest)
Expo AV 8.1.0 (latest)

### Expected Behavior

Video does not lag on play/pause

### Actual Behavior

Video lags on play/pause

### Reproducible Demo

**The following snack and video are loud**

Here is a snack:
https://snack.expo.io/@jaymithani/honest-coffee

Run this snack on a local iOS device and play/pause the video by clicking on it.

Here is a video on my local device https://imgur.com/a/tqfwk2E. I play the video once without play/pause just to show what it looks like. On the second time around, I play/pause and you can see the lag that occurs. The first time I pause, the video restarts. The second time, the video speeds up after the pause. The third time, there is a noticeable delay before the video actually pauses. 

Note: modifying the snack to use the video ref and/or zero seek tolerance does not help from what I can tell.

**Comment by byCedric** [comment]
Hi @Jay-Mithani, thanks for your issue report! The `shouldPlay` property is indeed used to play or pause the video, but the example is doing more than that. Because the property changed, the video element is rendered and reinitialized. If you need snappy responses, without losing the current time, ref's are definitely the way to go 😄 I [tweaked your code here](https://snack.expo.io/@bycedric/video-play-issue-8358), and that does exactly what you need! (and even works on web too!)

Hope it helps!

**Comment by Jay-Mithani** [comment]
Hey, thanks for your comment. It seems I am still experiencing the same issue in your tweaked code as well. I do not get the issue when running it in the virtual iOS device in the snack editor, though. After some testing it seems that the positionMillis on the status object returned when pausing is different from the positionMillis on the object returned upon playing again. Is there anything I can do to fix this?

**Comment by IliasseWahbi** [comment]
Hey, just to let you know - this issue has been recently fixed https://github.com/expo/expo/issues/5297
The delay is no more present
