### ISSUE TITLE
[docs] Write a guide about how to build a library with web support

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#8396]
https://twitter.com/josmithua/status/1262737636109754369

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/pull/3296

**Comment by josmithua** [comment]
Hi, anything in the works for this yet? I want to help write a guide by writing the steps as I go along, but it's hard since... I don't know the steps.

I'm trying to add web support to our native module [react-native-msal](https://github.com/stashenergy/react-native-msal) which we initialized with @react-native-community/bob. 

The first step was building a web implementation, so I moved the native one to a `.native.ts` file and wrote the web one in a regular `.ts` (as I read on some issue somewhere `.web.ts` doesn't work?).

The next step is getting the example app to work:

In `example/package.json` I added:

```diff
"scripts": {
+  "web": "expo start:web"
},
```
```diff
"dependencies": {
+   "react-dom": "16.13.1",
+   "react-native-web": "^0.13.12"
  },
```
```diff
"devDependencies": {
    "@babel/core": "^7.11.6",
    "@babel/runtime": "^7.11.2",
+   "babel-preset-expo": "^8.2.3",
-   "metro-react-native-babel-preset": "^0.63.0"
  }
```

In `example/src/index.tsx`:

```diff
import { AppRegistry, Platform } from 'react-native';
import App from './src/App';
import { name as appName } from './app.json';

AppRegistry.registerComponent(appName, () => App);

+if (Platform.OS === 'web') {
+  const rootTag = document.getElementById('root');
+  AppRegistry.runApplication(appName, { rootTag });
+}
```

Then in `babel.config.js`:

```diff
module.exports = {
- presets: ['module:metro-react-native-babel-preset'],
+ presets: ['babel-preset-expo'],
  plugins: [
    [
      'module-resolver',
      {
        alias: {
-         [pak.name]: path.join(__dirname, '..', pak.source),
+         [pak.name]: path.join(__dirname, '..', pak.module),
        },
      },
    ],
  ],
};
```

If I don't change the alias above to `pak.module`, I get an error that it cannot parse the typescript in `src`:

```
Failed to compile.
/Users/joshua/Projects/react-native-msal/src/types.ts 1:7
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

So I believe that is everything I have to do to add web support. I published a beta version of the package and tried it out and seems to work fine. However if I install the library in a managed expo project, I cannot run it in the expo client (it crashes). So I need to figure out how to support the expo client, but I suppose that is something for another issue.

**Comment by byCedric** [comment]
@josmithua I think you might be running into the [same issue I ran into with `sentry-expo`](https://github.com/expo/sentry-expo/pull/124). In the repository you mentioned, I see a single `src/index.tsx`. If you haven't split this out, this might be happening for you:

Your [`package.json` refers to the index file directly](https://github.com/stashenergy/react-native-msal/blob/master/package.json#L5-L9). This kind of "breaks" the `.native.tsx` or `.web.tsx` support because it's hardcoded to this single file. Could you try moving this to something like `msal.native.tsx` + `msal.web.tsx`, and replace `index.tsx` with something like:

```
export * from './msal';
export { default } from './msal';
```

This should force the bundler to resolve `msal` and take the `.native.tsx` and `.web.tsx` into account 😄

**Comment by josmithua** [comment]
Hi @byCedric, thanks for your reply!

That's kind of what I have currently in the [beta](https://github.com/stashenergy/react-native-msal/tree/beta) branch, is it not?

`index.ts` imports `publicClientApplication`, and I have `publicClientApplication.ts` and `publicClientApplication.native.ts`.

And no, Bob doesn't compile to a single file :).

**Comment by byCedric** [comment]
Ah sorry, I didn't see your beta branch! Let me try this out as well to see what's going on.
