### ISSUE TITLE
Update push notifications docs to remove references to this.props.exp.notification

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#843]
This is no longer used, you should use Notifications.addListener for all cases instead

**Comment by julezKiano** [comment]
Hi, Notifications.addListener doesn't fire when the app is completely closed and is reopened through a push notification. Therefore we can't determine the origin. With props.exp.notification we would get the origin returned as selected. Is there a way to determine if the application was opened due to a push notification?

**Comment by julezKiano** [comment]
Seems to fire on iOS only

**Comment by aatreya** [comment]
Not sure why this was closed - the latest docs (even as of SDK 28) are still referencing this.props.exp.notification:

https://docs.expo.io/versions/latest/guides/push-notifications.html

**Comment by outaTiME** [comment]
Yup @aatreya, still present in latest:

https://docs.expo.io/versions/latest/guides/push-notifications#notification-handling-timing

This generates a lot of confusion, only the listener should be used:

https://docs.expo.io/versions/latest/sdk/notifications#exponotificationsaddlistenerlistener

**Comment by feliperaul** [comment]
Wasted a lot of time on this :/

**Comment by n-sviridenko** [comment]
Still in the docs :( Luckily I found this issue quickly.

**Comment by howareyouami** [comment]
Thanks for that
