### ISSUE TITLE
Can't publish app after downgrading SDK Version

### ISSUE THREAD

**Issue by chongdog83** [expo/expo#848]
I've noticed if you upgrade your app to the latest SDK, then click publish in the XDE, then for some reason need to go back to the older version, when you publish again it will not update.

Logging into https://expo.io/, removing the project, then publishing again does not make it work.

For now, I am just changing my login and publishing under a different name so my friends can test.  Eventually, we will upgrade for real and this won't be an issue, just thought maybe someone should know.

**Comment by abi** [comment]
Yeah, it's a known unfortunate issue :( I ran into this last week too.

**Comment by alexcanessa** [comment]
Same issue here. Anyone?

**Comment by ide** [comment]
This is a know issue (just how things currently work). The current behavior is for clients to get the bundle for the latest SDK version they support. Ex: if your client supports SDK 21 and there's an SDK 21 bundle available, the client will always get it over an SDK 19 bundle. This might change in the future, this is just how it works today.

**Comment by ide** [comment]
Hi - to follow up on this, today we're starting to make it so that clients get the most recently published release that they can run.

### Example

Standalone apps support multiple SDK versions and here is a comparison of the old and new behaviors. For example, say your standalone app (or the Expo Client) supports SDKs 18-24 and you've published your project (version 1) using SDK 23. The client will download version 1 of your project since the client supports SDK 23 and that's the only version of your project available.

Later, you upgrade your project to SDK 24 and publish it (version 2). The client will download version 2 of your project. (Note: if you had upgraded to SDK 25, the client would not download the updated project because the client does not support SDK 25.)

However, you find a bug with version 2 of your project and decide to temporarily go back to SDK 23. You revert your commits and republish your project (version 3). (By the way [release channels](https://docs.expo.io/versions/latest/guides/release-channels.html) are a great way to roll back releases without republishing.)

**Previously:** the client would still download version 2 of your project because SDK 24 was newer than SDK 23. There was no way to go back to an older SDK version once you had published using a new one.

**Now:** the client downloads version 3 of your project because it's the most recently published version that the client supports. (If you had published using an SDK the client didn't support like SDK 17 or SDK 25, the client wouldn't download it.) So now it's easy to go back to an older SDK version by republishing.

### Check out release channels too!

I also want to reiterate that release channels are a great way to publish only to specific standalone apps (ex: give each their own release channel) and to roll back releases.
