### ISSUE TITLE
Question: Is it possible to hook react-devtools to debug CSS? if so how?

### ISSUE THREAD

**Issue by Eyesonly88** [expo/expo#849]
One of the tools I regularly use to debug CSS and dynamically interact with components during development is the `react-devtools` 👉 https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

I can't figure out how to hook it up with expo. It's just stuck like this:
![image](https://user-images.githubusercontent.com/767013/31980711-dc9f10f8-b9aa-11e7-9a12-319082e0dd30.png)

I have remote debugging enabled and try reloading the app and stop/start debugging but didn't work.

Is it even possible to make this work? if so I would be super grateful to know how 🙏 
P.S: it works fine using plain react-native project (i.e. not through CRNA/Expo)

**Comment by skevy** [comment]
Hi there!

Can you try setting the url (using exp or XDE) to "localhost", and make sure you're using the simulator, and then try using react-devtools again?

**Comment by brentvatne** [comment]
<img width="1113" alt="screen shot 2017-10-25 at 1 04 21 pm" src="https://user-images.githubusercontent.com/90494/32020454-0fe127b0-b985-11e7-9c35-77a8ecf5da7c.png">

confirmed it works as expected in simulator. the problem is on device, where react-native isn't able to do this yet (on ios). it should work fine on device on android. feel free to contribute a fix to this issue upstream https://github.com/facebook/react-native/issues/14431

**Comment by Eyesonly88** [comment]
Ah I see, thanks. 
I'll try to contribute a fix upstream then. Cheers.

**Comment by happy-thorny** [comment]
I managed to get it working on iOS device, but I guess it is universal solution. According to [react-devtools-core documentation](https://www.npmjs.com/package/react-devtools-core), add this before any react-related import in your main file (App.js or something that provides the topmost component):
`require('react-devtools-core').connectToDevTools({host: 'ip-of-machine-with-devtools-running'})`

By default [CRNA](https://github.com/react-community/create-react-native-app)'s main file is crna-entry.js which is located somewhere in node_modules. I didn't test the solution with crna-entry as main because i have it's copy as main which looks like that:
```
// src/index.js
require('react-devtools-core').connectToDevTools({host: '-ip-'})

import Expo from 'expo'
import App from './App'
import React from 'react'
import { View } from 'react-native'

class AwakeInDevApp extends React.Component {
  render() {
    return (
      <View style={{flex: 1}}>
        {React.createElement(App, this.props)}
        {process.env.NODE_ENV === 'development' ? <Expo.KeepAwake /> : null}
      </View>
    )
  }
}

Expo.registerRootComponent(AwakeInDevApp)
```
and modified package.json:
```
{
  ...
  "main": "./src/index.js",
  ...
}
