### ISSUE TITLE
MediaLibrary.createAssetAsync - Created asset is completely different from original file

### ISSUE THREAD

**Issue by justindmyers** [expo/expo#8567]
### Environment
iOS (Not tested on Android)

### Steps to Reproduce

* Create a new asset from an existing file: 
   * `MediaLibrary.createAssetAsync(uri);`
* Get asset info of newly created asset: 
   * `MediaLibrary.getAssetInfoAsync(asset); `
   * `FileSystem.getInfoAsync(asset.uri, { md5: true });`
* Compare against original file info: `FileSystem.getInfoAsync(uri, {md5: true });`

### Expected Behavior

Original file is copied over as an asset, unmodified or at least has a way to determine if a file has already been turned into an asset.

### Actual Behavior

Newly created asset is completely different than original file. MD5 hash, filename, and size no longer match as the file has been opaquely transformed for some reason. There's no way to compare if the original file actually exists as an asset because no asset properties match the original file properties.

It should also not create duplicate files. Currently you can pass the same uri into `createAssetAsync` and it will create a duplicate asset with a new filename.

### Reproducible Demo

Check the console output: https://snack.expo.io/@justindmyers/bold-beef-jerky

**Comment by tsapeta** [comment]
Could you try to use `asset.localUri` instead of `asset.uri` in `FileSystem.getInfoAsync`?

> It should also not create duplicate files. Currently you can pass the same uri into createAssetAsync and it will create a duplicate asset with a new filename.

I don't have good news – this is expected behavior. On iOS you can download an image from the internet, save it to photo library multiple times and you'll get them duplicated. That's how it works under the hood in the operating system and there is nothing we can do as far as I know.

**Comment by justindmyers** [comment]
> Could you try to use asset.localUri instead of asset.uri in FileSystem.getInfoAsync?

This is the only data I'm getting back from `createAssetAsync`, only `uri` exists, not `localUri`

```
height:1920
mediaType:"video"
creationTime:1531599764000
id:"E8C3A834-4C14-475C-A187-724DCA916EB1/L0/001"
width:1080
mediaSubtypes:[]
duration:13.965
filename:"IMG_0011.MOV"
uri:"assets-library://asset/asset.MOV?id=E8C3A834-4C14-475C-A187-724DCA916EB1&ext=MOV"
modificationTime:1591212801063
```

> I don't have good news – this is expected behavior. On iOS you can download an image from the internet, save it to photo library multiple times and you'll get them duplicated. That's how it works under the hood in the operating system and there is nothing we can do as far as I know.

I figured this might be the case. Obviously not a huge deal, just wanted to mention it.

--------

To note, I've tested this tons of ways in my standalone app and couldn't come up with any solution except for storing a reference between the initial file and the created asset in AsyncStorage and comparing the two.

**Comment by tsapeta** [comment]
Yeah, `createAssetAsync` doesn't return `localUri` because getting it is more expensive, but `getAssetInfoAsync` does return it. I'm just wondering whether `localUri` from asset info isn't the same as the `uri` you passed to `createAssetAsync` (if only the initial asset is local). Sorry if I was unclear 😉
