### ISSUE TITLE
Is normal I do a build:android or build:ios and this is published into production environment in the playstore and applestore?

### ISSUE THREAD

**Issue by ARChatco** [expo/expo#8569]
If the answer that is impossible..

is possible that happened because I did expo publish?

because I did something like did and my users in production(From stores) got some changes, and it was quite fast, and then when I get this APK or IPA and I publish manually, I spend a lot...

(Well after build:android I saw the message.. Publish complete)
If this is happening, how can I disable this automatically publish?

**Comment by byCedric** [comment]
Hi @ARChatco! Yes, this is definitely possible. What happens during a build is that it also creates a newly published version to make sure your manifest settings are up to date with the build. This is the default behavior, but you can turn this off using the `--no-publish`-flag (see `expo build:android --help` for more).

When you decide not to publish during build, keep in mind that any change in the manifest _is not taken into account_. It will use the latest published version and the manifest of that published version. Changes made to permissions, for example, won't be included. I would strongly suggest taking a look at [release channels to prevent accidental publishing to stores](https://docs.expo.io/distribution/release-channels/) instead of turning the publish off during build.

Hope it helps!
