### ISSUE TITLE
Do test in-app payments work on Expo client app running from development server ?

### ISSUE THREAD

**Issue by barnu5** [expo/expo#8571]
WORKING in app payments: If I build app with xcode. 

NOT WORKNG in app payments: Using Expo client iOS app (can't access payments at all)

Is this expected? Do test in-app payments work on a locally run app instance via expo client app?

**Comment by sergeichestakov** [comment]
Hey @barnu5, that is correct. IAP will not work inside the Expo client. This is because the In App Purchase library expects the ID of the app it's running on to match the Application/Bundle ID of the app you configured in App Store Connect and Google Play Console. This is part of the reason you currently have to eject in order to use it.

**Comment by barnu5** [comment]
Great response, thanks @sergeichestakov
