### ISSUE TITLE
FileSystem.readAsStringAsync does not work in jest

### ISSUE THREAD

**Issue by conan19842002** [expo/expo#8621]
FileSystem.readAsStringAsync does not seem to work in test environment. This is the code:
import * as VcfVerifier from '../utils/VcfVerifier';
import * as FileSystem from 'expo-file-system';

const DATA_PATH = "../../tools/vcf_test/";
beforeEach(async () => {
    jest.setTimeout(10000)
  })
describe('Test returned message', () => {
    it('does not have correct column number', async () => {
      
      
    const uri = DATA_PATH + 'example1.vcf';

    var fileString =  await FileSystem.readAsStringAsync(uri); // this returns undefined
   
    var msg = VcfVerifier.checkVcf(fileString);
            
    expect(true).toEqual(msg.includes("does not have correct column number"));
      
    });
  });

**Comment by byCedric** [comment]
Hi @conan19842002! I think it's because `expo-file-system` is a [mocked module when using `jest-expo`](https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/setup.js#L120). You should be able to load it with [`jest.requireActual`](https://jestjs.io/docs/en/jest-object#jestrequireactualmodulename), but keep in mind that this module was created for native platforms and not necessarily node (Jest's environment) so stuff might not work as expected.

If you want to test the `VcfVerifier.checkVcf`, I would recommend sticking with the [`fs.readFile`](https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback) that definitely works in node 😄 But, if you have a special requirement of using `expo-file-system`, let me know!

Hope it helps!

**Comment by conan19842002** [comment]
Hi, thank you for the answer. I unfortunately can't use fs since this would require native code and I'm testing on client side in Expo. Is there any a workaround on this matter please?

**Comment by brentvatne** [comment]
you could refer to how test-suite is set up: https://github.com/expo/expo/blob/master/apps/test-suite/tests/FileSystem.js. but this is not something that just works out of the box with jest. the code needs to run on your device to work, there is no node.js implementation of expo-file-system.

<hr />

if you'd like to continue discussing, please continue to expo forums - https://forums.expo.io. the issues are reserved for demonstrable bug reports.
