### ISSUE TITLE
expo-location returns bad reversed geocode

### ISSUE THREAD

**Issue by karimcambridge** [expo/expo#8724]
### Summary of Issue (just a few sentences)

iOS native geo coding simply sucks

```
[
  Object {
    "city": null,
    "country": "Saint Vincent and the Grenadines",
    "isoCountryCode": "VC",
    "name": "Saint Vincent and the Grenadines",
    "postalCode": null,
    "region": "Saint Vincent and the Grenadines",
    "street": null,
  },
]
```

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.21.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^37.0.12 => 37.0.12
      react: ^16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4
```

iOS & Android

### Reproducible Demo

```js
import * as Location from 'expo-location';
import axios from 'axios';

const
	geocode = await Location.reverseGeocodeAsync({ 13.144106416923435, -61.20818272233009 })
;
const result = await axios
	.get('https://maps.googleapis.com/maps/api/geocode/json', {
		params: {
			latlng: 13.144106416923435 + ',' + -61.20818272233009,
			key: 'xxx',
		}
	})
;
if(result) {
	console.log('expo result', geocode);
	console.log('axios result', result.data);
}
```

### Steps to Reproduce

- Simply run the code above, run a geocode from android and then run one from iOS, the iOS has a ridiculously less accurate result.

### Expected Behavior vs Actual Behavior

The iOS geocoding is super inaccurate

If we can simply have a function that turns on iOS to use google maps geocoding it will solve this issue.

**Comment by byCedric** [comment]
Hi @karimcambridge! Thanks for the issue report! Unfortunately, Apple is not "the best" method to perform the reverse geolocation lookup. And you are not alone in this ([this](https://stackoverflow.com/questions/31331093/clgeocoder-returns-wrong-results-when-city-name-is-equal-to-some-countrys-name), [that](https://stackoverflow.com/questions/11614721/clgeocoder-geocoding-is-hopelessly-inaccurate)). Because of this, I went ahead and create a [canny feature request for this](https://expo.canny.io/feature-requests/p/accurate-reverse-geocode-on-ios). Right now, I would recommend keep your manual API call if you need higher accuracy on iOS.

**Comment by tsapeta** [comment]
As you and Cedric said, iOS geocoding is not as accurate as Google Maps, but I'm sorry to say that we're not planning to implement such functionality in near future. The goal was to provide and expose system's APIs and that being said, if you need more accurate results then you should probably use it as you wrote in the demo, by https call to Google APIs.
I'm closing this issue, but also keeping canny feature request open, so maybe we will come back to this later if there will be such need from the community.
