### ISSUE TITLE
Logkitty vulnerability found in yarn.lock 

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [expo/expo#8725]
Whenever I start a new project at the expo this error occurs on github.

![image](https://user-images.githubusercontent.com/37240367/84023935-5ae27800-a95f-11ea-9fd8-80e07e961c4b.png)

When checking yarn.lock I find this line:

```
@react-native-community/cli-platform-android@^3.0.0-alpha.1":
  version "3.1.4"
  resolved "https://registry.yarnpkg.com/@react-native-community/cli-platform-android/-/cli-platform-android-3.1.4.tgz#61f964dc311623e60b0fb29c5f3732cc8a6f076f"

  dependencies:
    "@react-native-community/cli-tools" "^3.0.0"
    chalk "^2.4.2"
    execa "^1.0.0"
    jetifier "^1.6.2"
    logkitty "^0.6.0"
    slash "^3.0.0"
    xmldoc "^1.1.2"
```

How can i fix that?

**Comment by byCedric** [comment]
Hi @HidemitsuHashimoto! Don't forget to add some context of your environment (as described in the template) next time 😄 That would help us a lot. This particular issue [is already fixed in the React Native CLI](https://github.com/react-native-community/cli/issues/1189), so I would suggest upgrade to the latest version. If that doesn't work, please open a new issue with the required info to help you further 😄 

Hope it helps!
