### ISSUE TITLE
Expo SDK old dependencies

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [expo/expo#8726]
## 🐛 Bug Report
Logkitty vulnerability

### Summary of Issue (just a few sentences)
Whenever I start a new project at the expo this error occurs on github.

I saw it yarn lock that the expo SDK uses an outdated version of @react-native-community/cli-platform-android (^3.0.0-alpha.1)

How can i upgrade that?

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
"react-native@https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz":
  version "0.61.4"
  resolved "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz#69f3f63c36c9df52611847a67c9d94596c1754cc"
  dependencies:
    "@babel/runtime" "^7.0.0"
    "@react-native-community/cli" "^3.0.0-alpha.1"
    "@react-native-community/cli-platform-android" "^3.0.0-alpha.1"
    "@react-native-community/cli-platform-ios" "^3.0.0-alpha.1"
    abort-controller "^3.0.0"
    art "^0.10.0"
    base64-js "^1.1.2"
    connect "^3.6.5"
    create-react-class "^15.6.3"
    escape-string-regexp "^1.0.5"
    event-target-shim "^5.0.1"
    fbjs "^1.0.0"
    fbjs-scripts "^1.1.0"
    hermes-engine "^0.2.1"
    invariant "^2.2.4"
    jsc-android "^245459.0.0"
    metro-babel-register "^0.56.0"
    metro-react-native-babel-transformer "^0.56.0"
    metro-source-map "^0.56.0"
    nullthrows "^1.1.0"
    pretty-format "^24.7.0"
    promise "^7.1.1"
    prop-types "^15.7.2"
    react-devtools-core "^3.6.3"
    react-refresh "^0.4.0"
    regenerator-runtime "^0.13.2"
    scheduler "0.15.0"
    stacktrace-parser "^0.1.3"
    whatwg-fetch "^3.0.0"

### Reproducible Demo
![image](https://user-images.githubusercontent.com/37240367/84028195-af3d2600-a966-11ea-8f26-ce4bf44912f1.png)

- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve

As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!

**Comment by GregBlackLine** [comment]
+1 - this is coming up in scans from our security tools.

**Comment by whiteadi** [comment]
#metoo

**Comment by byCedric** [comment]
Hi, this is a dependency of `react-native`. As of now, the `react-native` version used in SDK 37 uses the semver range starting from `^3.0.0-alpha.1`. Luckily, the [logkitty issue is already solved](https://github.com/react-native-community/cli/issues/1189) in the react native cli, and should be available if you run `yarn update` or `npm update`.

If you don't receive this update, please double check if you use the latest `expo` and `react-native` packages.
```
"expo": "~37.0.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
```

I'm going to close this issue because it's already fixed in the external dependencies. In SDK 38 we fully resolve this by using the react native cli v4. In case you run into issues, please provide the output of either one of the following commands:

```
$ yarn why @react-native-community/cli-platform-android
$ npm list @react-native-community/cli-platform-android
``` 

Hope it helps!

**Comment by whiteadi** [comment]
yarn update does not exist :)

**Comment by gregdburns** [comment]
@byCedric I've updated to Expo SDK 38, but we're still seeing this show up in a scan:

"introduced by react-native@https://github.com/exp/react-native/architec/sdk-38.0.0.tar.gz > @react-native-community/cli-platform-android@4.7.0 > logkitty@0.6.1 and 1 other path(s)."

Did I misunderstand the resolution, or miss a step?  

Thanks!

**Comment by mdalzell** [comment]
@gregdburns Were you able to figure out the issue?  I'm on sdk-38.0.2 and still seeing the outdated version of `logkitty`

**Comment by brentvatne** [comment]
try running `yarn why logkitty` to see what is pulling it in. not sure what the equivalent is for npm, i think you just have to look at package-lock.json

**Comment by gregdburns** [comment]
@mdalzell here's what I've learned, but I'm still confused because the Expo team is saying that it should be fixed.

- Logkitty is used by @react-native-community/cli-platform-android@4.7.0
- The react native community library is used by React Native
- The issue is fixed in Logkitty v0.7.1, but this fix has not worked it's way through React Native -> Expo

There is one work around using npm resolutions (check this article: https://itnext.io/fixing-security-vulnerabilities-in-npm-dependencies-in-less-than-3-mins-a53af735261d), but this doesn't work for us because it fails when running the npm ci command (npm build works fine).

**Comment by brentvatne** [comment]
@gregdburns - in sdk-38 you can see that we depend on @react-native-community/cli-platform-android@^4.5.1 which will resolve to 4.7.0 (^ matches the latest minor version) as long as you clear the lockfile.

```
╰─$ yarn why logkitty
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "logkitty"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "logkitty@0.7.1"
info Reasons this module exists
   - "react-native#@react-native-community#cli-platform-android" depends on it
   - Hoisted from "react-native#@react-native-community#cli-platform-android#logkitty"
info Disk size without dependencies: "1.17MB"
info Disk size with unique dependencies: "3.36MB"
info Disk size with transitive dependencies: "4.09MB"
info Number of shared dependencies: 27
```

however, `expo-splash-screen` also includes a dependency on `@react-native-community/cli-platform-android@4.7.0` strictly. this leads to `logkitty` 0.6.1 being installed too:

```
=> Found "@expo/configure-splash-screen#logkitty@0.6.1"
info Reasons this module exists
   - "expo#expo-splash-screen#@expo#configure-splash-screen#@react-native-community#cli-platform-android" depends on it
   - Hoisted from "expo#expo-splash-screen#@expo#configure-splash-screen#@react-native-community#cli-platform-android#logkitty"
info Disk size without dependencies: "304KB"
info Disk size with unique dependencies: "2.49MB"
info Disk size with transitive dependencies: "3.22MB"
info Number of shared dependencies: 27
```

to fix this we will need to re-release the `@expo/configure-splash-screen`, `expo-splash-screen`, and `expo` packages in that order. i can do this later today, but until then resolutions should do fine and i think most developers should get used to using such things and make sure their ci process works with their workarounds in order to be able self-service when they encounter situations where they need to patch dependencies.

**Comment by gregdburns** [comment]
@brentvatne fair enough - thanks for your work on this!

**Comment by brentvatne** [comment]
@gregdburns - i just published expo@38.0.9, which includes a version of expo-splash-screen that includes a version of @expo/configure-splash-screen that includes a version of @react-native-community/cli-platform-android that includes a version of logkitty that should resolve this issue 😆 

please install expo@38.0.9 to fix it :)

**Comment by gregdburns** [comment]
@brentvatne - you rule my friend, thank you!  I'll post here as soon as I test and re-scan to confirm that everything looks good on our end.

**Comment by mdalzell** [comment]
Just upgraded and everything looks good.  Thanks everyone for the quick responses on a closed issue!

**Comment by gregdburns** [comment]
Confirming that it solved the issue on our end as well.  Thanks for the support!
