### ISSUE TITLE
[expo-gl][bare workflow] App crashes when rendering GLView on Android when Hermes is enabled

### ISSUE THREAD

**Issue by yaroslavnikiforov** [expo/expo#8728]
### Environment

| software         | version
| ---------------- | -------
| react-native | 0.62.2
| react-native-unimodules | 0.9.1
| expo-gl-cpp  | 8.2.0
| expo-gl | 8.2.0
| platform OS | Android

### Reproducible Demo

[GitHub](https://github.com/yaroslavnikiforov/hermes-expo-gl-test)

### Steps to Reproduce

1. react-native init <ProjectName>.
2. install react-native-unimodules.
3. install expo-gl-cpp and expo-gl.
4. Add GLView element with width and height style properties in render of App.js.
5. Enable the Hermes engine.

### Expected Behavior

Should work as with disabled Hermes.

### Actual Behavior

App crashes with an error:
```
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libexpo-gl.so caused by: dlopen failed: library "libjsc.so" not found result: 0 at ...
```

![Screenshot_2020-04-16-16-50-05-395_com miui bugreport](https://user-images.githubusercontent.com/42115630/84050664-b1c76c00-a9b6-11ea-8a04-b0b196a4c00b.jpg)

**Comment by tsapeta** [comment]
I confirm this issue exists and we are aware of that. Since `expo-gl` is written in C++ and it bypasses a bridge and calls JSC directly, it needs special care to make it work with other JavaScript engines, so it doesn't support Hermes yet.

We've taken some actions to fix it (#7948), but we can't do this entirely without React Native team cooperation – we're waiting for this PR https://github.com/facebook/react-native/pull/28634 to land.

I'll close this issue once I put some info to our docs and readme to clarify this module works only with JSC for now, but certainly Hermes support will eventually be added later.

cc @wkozyra95 who works on this

**Comment by wkozyra95** [comment]
Hi @yaroslavnikiforov 

We just published expo-gl version `9.0.0` (tagged as `next`), we do not consider it official support for hermes yet(it was not tested with hermes), but new implementation is using a common interface for JSC and hermes so it should work correctly with both VMs.

**Comment by yaroslavnikiforov** [comment]
@wkozyra95 thanks, will try it and give a feedback

**Comment by yaroslavnikiforov** [comment]
Great! Seems as it works now with expo-gl@9.0.0. The same steps to reproduce.
`
"dependencies": {
    "expo-gl": "^9.0.0",
    "expo-gl-cpp": "^9.0.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-unimodules": "^0.10.1"
  }
`

New reproducible demo: [GitHub](https://github.com/yaroslavnikiforov/expo-gl-9.0.0-hermes-test)
