### ISSUE TITLE
nodejs module "fs"

### ISSUE THREAD

**Issue by shaman-apprentice** [expo/expo#8730]
I tried to use [azure-storage](https://www.npmjs.com/package/azure-storage) with expo. It works fine in browser, but throws on Android and Smart Phone:

```
The package at "node_modules\azure-storage\lib\services\blob\blobservice.node.js" attempted to import the Node standard library module "fs". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/introduction/faq/#can-i-use-nodejs-packages-with-expo
Failed building JavaScript bundle.
```

I am surprised that the transpile process can browserify `fs` for web, but not for react-native. Help how to work around this, is very much appreciated.

Anyway, the link from the error message https://docs.expo.io/introduction/faq/#can-i-use-nodejs-packages-with-expo doesn't contain such an section. Hence this message should be updated. Unfortunately I couldn't find a similar section.

Thanks a lot for any help :)

P.S.:
I hope this question + hint for the falsy error message doesn't fall under the template "Please note that discussions opened as issues in the core Expo repository will be closed."

**Comment by byCedric** [comment]
Hi @shaman-apprentice! It looks like `azure-storage` only supports node and browser environments. Although it might look like React Native is a node-like environment, it's actually another one. I see that they added support for browsers by splitting out `common/common.js` into [`common.browser.js`](https://github.com/Azure/azure-storage-node/blob/master/lib/common/common.browser.js), [`common.node.js`](https://github.com/Azure/azure-storage-node/blob/master/lib/common/common.node.js) and [`common.core.js`](https://github.com/Azure/azure-storage-node/blob/master/lib/common/common.core.js). Because there is no `common.native.js` or `common.expo.js`, the react native environment falls back to the `common.node.js`. This is problematic, because like you mentioned, there is no `fs` in React Native or Expo.

I would recommend opening an issue there asking for support for React Native. They structured their code pretty well, so that shouldn't be a lot they have to change. But for now, this library seems incompatible with React Native.

As for the docs, I'll add the label docs to fix that issue. Thanks for mentioning that!

Hope it helps!

**Comment by shaman-apprentice** [comment]
I thought, that the browser version should work everywhere, but thinking about it, it makes total sense that things like `fs` need a different implementation. Thanks a lot for your detailed reply!

(In case anyone stumbles over this, I create a [related feature request at azure-storage here](https://github.com/Azure/azure-storage-node/issues/646).

**Comment by byCedric** [comment]
No problem! In this case, the browser version should work (I haven't tested it though). But because the browser implementation is defined with `.browser.js`, it's not picked up by react native. If they just add a `common.native.js` with the contents of `common.browser.js` re-exported, it might work 😄  Maybe it's something you are able to test? You can add it in `node_modules`, and just run it 😄

**Comment by shaman-apprentice** [comment]
In case they don't plan to support react-native, I will give it a try 👍
