### ISSUE TITLE
Notifications.addListener stop working after detach

### ISSUE THREAD

**Issue by riwu** [expo/expo#874]
```
export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      received: false,
    }
    Notifications.addListener((notification) => {
      console.log('received', notification);
      this.setState({ received: true })
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <TouchableHighlight
          onPress={() => Notifications.presentLocalNotificationAsync({
            title: 'Notification',
            ios: {
              sound: true,
            },
            android: {
              sound: true,
              priority: 'max',
              vibrate: true,
            },
          })}
        >
          <Text>Click for notification</Text>
        </TouchableHighlight>
        <Text>Listener called: {this.state.received.toString()}</Text>
      </View>
    );
  }
}
```

Function in `Notifications.addListener` gets called perfectly fine in https://expo.io/@riwu/expotest
But once I detach Expo, it [stop working](https://github.com/riwu/notification-listener) even though `Notifications.presentLocalNotificationAsync` still works and user is still able to receive the notification.

**Comment by riwu** [comment]
`Permissions.askAsync(Permissions.NOTIFICATIONS)` doesn't get resolved too, though `Permissions.getAsync(Permissions.NOTIFICATIONS)` works.

**Comment by terribleben** [comment]
Hi, thanks for the report. As mentioned [here](https://docs.expo.io/versions/latest/guides/detach.html#you-should-not-detach-if), you'll need to manage your own notifications in a detached app for now. This is because of the way Expo manages your certificates. We have a [highly upvoted feature request](https://expo.canny.io/feature-requests/p/push-notifications-on-detached-projects) to improve this, but haven't had time yet.

**Comment by riwu** [comment]
That is about **push** notification, not **local** notification which does not require push certificates.

Please reopen this, thanks.
