### ISSUE TITLE
Auth-session leads to app refresh on Android 11 

### ISSUE THREAD

**Issue by airic37** [expo/expo#8783]
### Summary of Issue (just a few sentences)
Pixel 3a XL running Android 11 Beta 1 expo-auth-session causes a new instance of the app to generate rather than returning to the original app after redirect. See #8117 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
Expo CLI 3.21.5 environment info:
    System:
      OS: Windows 10 10.0.17134
    Binaries:
      Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 2.0.0-rc.33 - C:\Users\smite\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-dom: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ^0.11.7 => 0.11.7

### Reproducible Demo
Confirmed running https://expo.io/@notbrent/hour-power?release-channel=lol on expo client 2.15.4 on my Pixel 3a XL running Android 11 Beta 1

**Comment by byCedric** [comment]
Hi @airic37! Thanks for the additional info and repro steps. Unfortunately, I have no access to either a Pixel 3a XL or an emulator at the moment. When I have I'll try to repro this, that's why I will keep the "issue needs review" label on this one. One question, have you checked [this comment](https://github.com/expo/expo/issues/8117#issuecomment-639152686)? Or doesn't it apply to your use case?

**Comment by airic37** [comment]
I don't think that comment applies in my test. I've opened expo directly from the app drawer and don't have any shortcuts saved.

**Comment by airic37** [comment]
I just confirmed in addition to my personal device I can recreate this on an emulated Pixel 3a XL running API 30
