### ISSUE TITLE
App crash on first launch without internet

### ISSUE THREAD

**Issue by riwu** [expo/expo#879]
https://play.google.com/store/apps/details?id=riwu.sampling.survey
source: https://github.com/riwu/synergy-lab-time-estimation/tree/master/client/android

If I install the app from Google Play and **turn off internet connection before opening for the first time**, the app crashes when opened. 
The app is able to run normally with internet connection.

Debugged it `adb logcat`, crash log as follow:
```
--------- beginning of crash
10-28 23:04:10.402  5934  5973 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
10-28 23:04:10.402  5934  5973 E AndroidRuntime: Process: riwu.sampling.survey, PID: 5934
10-28 23:04:10.402  5934  5973 E AndroidRuntime: java.lang.RuntimeException: Could not load app.
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at host.exp.exponent.kernel.ExpoViewKernel.handleError(ExpoViewKernel.java:76)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at host.exp.expoview.ExponentActivity$2.onError(ExponentActivity.java:115)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at host.exp.exponent.ExponentManifest$3.onFailure(ExponentManifest.java:258)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at host.exp.exponent.network.ExponentHttpClient$2$1.onFailure(ExponentHttpClient.java:95)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at expolib_v1.okhttp3.RealCall$AsyncCall.execute(RealCall.java:142)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at expolib_v1.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
10-28 23:04:10.402  5934  5973 E AndroidRuntime: Caused by: Could not load app.
10-28 23:04:10.402  5934  5973 E AndroidRuntime: 	... 7 more
10-28 23:04:10.403  1360  1392 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
10-28 23:04:10.403  5934  5975 D OpenGLRenderer: HWUI GL Pipeline
10-28 23:04:10.407  1500  3287 W ActivityManager:   Force finishing activity riwu.sampling.survey/.MainActivity
10-28 23:04:10.417  1500  1515 I ActivityManager: Showing crash dialog for package riwu.sampling.survey u0
10-28 23:04:10.442  1352  1352 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4096
10-28 23:04:10.447  5934  5975 D         : HostConnection::get() New Host Connection established 0x9eb64bc0, tid 5975
10-28 23:04:10.451  1352  1352 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4096
10-28 23:04:10.459  1352  1352 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4096
10-28 23:04:10.461  5934  5949 D GraphRequest: Warning: Request without access token missing application ID or client token.
10-28 23:04:10.486  1352  1352 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 4096
10-28 23:04:10.486  1500  2218 D WindowManager: relayoutVisibleWindow: Window{b86f3b5 u0 com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
10-28 23:04:10.496  1500  2059 D WindowManager: relayoutVisibleWindow: Window{c381498 u0 com.google.android.apps.nexuslauncher/com.google.android.apps.nexuslauncher.NexusLauncherActivity EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
10-28 23:04:10.533  1500  1755 I WindowManager: Failed to capture screenshot of Token{51dadce ActivityRecord{d9752c9 u0 riwu.sampling.survey/.MainActivity t153 f}} appWin=Window{54854c4 u0 riwu.sampling.survey/riwu.sampling.survey.MainActivity} drawState=1
```
Full log: https://gist.github.com/riwu/471766d93fca09b286087d2f40f5a5d9#file-crash-log
Gradle dependencies: https://gist.github.com/riwu/471766d93fca09b286087d2f40f5a5d9#file-gradle-dependencies

There were no build warnings but Android Studio gave a warning about https://stackoverflow.com/questions/42374151/all-com-android-support-libraries-must-use-the-exact-same-version-specification though i doubt that's the cause of crash since it works with internet connection.

**Comment by btk** [comment]
Might be related to: https://expo.canny.io/feature-requests/p/allow-standalone-apps-to-load-and-function-with-no-internet-connection

@dikaiosune says that; 
" I'm guessing you primarily mean the ability for a user to download the app while online, but then be offline when they use the app? Right now that's fully supported in Android standalone builds."

But first time launch of an android app might still be effected by that. If so they are currently working on fixing it, and @brentvatne might want to double check it with android apps first time launch, because I also face this with my current project.

**Comment by terribleben** [comment]
Hey there - on Android we [don't yet support offline-first-launch](https://docs.expo.io/versions/latest/introduction/why-not-expo.html#its-not-currently-possible-to-bundle-assets-inside-of-standalone-apps-for-many-apps-this-is-a-dealbreaker-for-example-if-your-app-includes-100mb-of-images-and-you-need-them-to-be-available-immediately-when-the-user-opens-the-app-you-will-need-to-detacheject-when-you-publish-your-app-all-assets-that-you-import-with-require-in-your-app-are-uploaded-to-cloudfront-and-loaded-on-demand-when-requested-in-your-app--similar-to-how-a-webpage-works-this-has-the-benefit-of-allowing-you-to-update-any-asset-over-the-air-without-re-submitting-to-app-stores-but-it-isnt-ideal-for-every-situation-some-assets-need-to-be-available-immediately-when-the-app-loads-and-sometimes-there-are-a-lot-of-these-assets-in-these-situations-the-only-option-available-to-you-right-now-is-downloading-and-caching-assets-when-your-app-loads-we-are-working-on-making-it-possible-to-bundle-assets-with-your-standalone-app-while-also-preserving-the-ability-to-update-them-ota) for ExpoKit (detached) apps. You can cache everything so that it works on subsequent launches, but not the first one. We're currently working on the feature request mentioned in the previous comment, but we don't have an ETA yet. Please upvote the feature request for now, and sorry for the frustration.

**Comment by ygorlazaro** [comment]
Hi @terribleben , is there any update about this?

**Comment by ygorlazaro** [comment]
We've been having a lot of problems while using the app. 'Cause our app style, we call this bug here as the Red Screen of Death...

**Comment by terribleben** [comment]
Hi @ygorlazaro, yes, there are some updates since this thread was originally closed last October. Expo [supports offline apps](https://docs.expo.io/versions/latest/guides/offline-support.html) in most circumstances. This was added a few months ago and we plan to continue improving it! 😄 

We still have more work to do on Expo. We maintain a list of the [biggest reasons not to use Expo](https://docs.expo.io/versions/latest/introduction/why-not-expo.html), and we hope that one day that list will be empty. For more specific features, you can always check our [feature requests board](https://expo.canny.io/feature-requests) to see if something's missing. And it's worth following our blog, which includes [release notes](https://blog.expo.io/expo-sdk-v25-0-0-is-now-available-714d10a8c3f7) every month.

**Comment by ygorlazaro** [comment]
Nice! @terribleben , but do you know if this fix solves the problem I am having? I mean, the app is always looking for a newer version of the expo servers, ignoring the version bundled.

I saw a lot of requests made like this: https://d1wp6m56sqw74a.cloudfront.net/%40my%2Fapp%2F0.9.32%2Fc91558226b004fa723d9d08e8420b623-24.0.0-android.js (fake url), from a bundleUrl prop I didn't put there.

**Comment by harisvsulaiman** [comment]
@ygorlazaro did you fix this?
