### ISSUE TITLE
[axpo-av][Android] Full screen issue on Pixel 3 - gray bar at the bottom

### ISSUE THREAD

**Issue by Razorholt** [expo/expo#8829]
The gray bar ( or is it part of the video background?) appears on Pixel 3 whether the video plays in fullscreen or not. 

![Screenshot_20200615-232606](https://user-images.githubusercontent.com/5605177/84732730-11e38280-af62-11ea-94a8-96d8bdf5573c.png)

Here is the code:
```
return (
    <View style={{ backgroundColor: "#000", flex: 1 }}>
      <Video
        ref={(r) => (this.vid = r)}
        style={{
          width: "100%",
          height: "100%",
        }}
        rate={1}
        source={{ uri: Video }}
        isMuted={false}
        isLooping={false}
        resizeMode="contain"
        shouldPlay={true}
        useNativeControls={false}
        onPlaybackStatusUpdate={(stat) => onPlaybackStatusUpdate(stat)}
      />
    </View>
  );
```
```
Object {
  "androidImplementation": "SimpleExoPlayer",
  "didJustFinish": false,
  "durationMillis": 94219,
  "isBuffering": false,
  "isLoaded": true,
  "isLooping": false,
  "isMuted": false,
  "isPlaying": false,
  "playableDurationMillis": 59100,
  "positionMillis": 7565,
  "progressUpdateIntervalMillis": 500,
  "rate": 1,
  "shouldCorrectPitch": false,
  "shouldPlay": false,
  "uri": "/movies/independent/guest-artist/guest-artist-trailer-1_i320.m4v",
  "volume": 1,
}
```

**Comment by byCedric** [comment]
hi @Razorholt! Thanks for your issue report. I don't we add a special video background to the video so I'm not sure where this is coming from. Could you create a small repro using Snack? That way we can test and maybe fix it faster 😄

**Comment by Razorholt** [comment]
https://snack.expo.io/@mobshed/a4e434

**Comment by IjzerenHein** [comment]
I didn't see it when I opened it up on the Android preview on Snack.

Which android Phones and API versions are you seeing this on?

**Comment by Razorholt** [comment]
Pixel 3, version 10

**Comment by IjzerenHein** [comment]
Did a bit of research and found that it is related to how the vide is encoded. The video height is 360, but the video-frame buffer is 368 pixels because it has to be divisible by 16. This is quite normal and shouldn't be a problem. However, normally these pixels are blank (transparent), but in this case they appear to be gray(ish). It's also possible that the vendor encoded additional information in those pixels.

![image](https://user-images.githubusercontent.com/6184593/89267766-f3336b00-d637-11ea-92a9-b0ca77527840.png)

And for some reason the Android surface copying mechanism (both MediaPlayer and ExoPlayer) seems to copy this additional part to the texture-surface, causing it to show up (it might be in an Android API-call which they both use and which is affected on certain android versions). Furthermore it only shows up when using resizeMode `contain`, as the other resize-modes fills the whole texture-view.

As for solutions, I found that re-encoding the video (e.g. using VLC) fixes the problem. So if this is a solution for you I would recommend that.

**Comment by Razorholt** [comment]
@IjzerenHein Thank you so much for taking the time to investigate this issue. I will adopt your suggested solution and encode the content using ffmpeg. Have a great day!
