### ISSUE TITLE
[expo-task-manager] not working when mobile is locked state 

### ISSUE THREAD

**Issue by hussainahmad** [expo/expo#8830]
## 🐛 Bug Report
First of all thanks for the wonderful library. I m using Expo location and expo task manger for tracking App. Which is working fine as expected. but when we mobile went into locked state It is not working. 

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.16.0 -
      npm: 6.4.1 -
      Watchman: 4.9.0 - 
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - 
    npmPackages:
      @testing-library/react-native: ^5.0.3 => 5.0.3 
      @types/react: ^16.9.21 => 16.9.36 
      @types/react-native: ^0.61.16 => 0.61.23 
      react: 16.9.0 => 16.9.0 
      react-native: 0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.11.7

**Comment by AdamJNavarro** [comment]
Hey @hussainahmad,

We appreciate the kind words about the library! As for the issue, we're going to need some more information before we can start our debugging efforts. Could you please let us know if this is happening on iOS, Android or both (and whether it is device/model specific). Additionally, please create a reproducible example of this behavior so that we can test it on our end.

Thanks,
Adam

**Comment by hussainahmad** [comment]
Hey @AdamJNavarro  Sorry for responding late, I created Demo  [Expo Task Manager](https://github.com/hussainahmad/Expo-Task-Manager)  for the above issue. after locking the mobile almost after 5 min this issue will arise.

**Comment by mitrosunay** [comment]
im facing same issue .. the task manager stops after 5 min. expo sdk 38 on android ..

**Comment by mitrosunay** [comment]
Hi folks, 
i come across the issue using the task.manager body out of the life cycle of react on redux - saga structure. 
Probably this crashes when the task.manager body used on component did mount cycle. 
For me its closed.

**Comment by AidanRRR** [comment]
Facing the same issue (also in addition with using foregroundService). It only works when the (Android) phone is unlocked.

**Comment by hussainahmad** [comment]
@AidanRRR  Thanks for the help , I m facing this issue on both platform.

**Comment by anantshukla** [comment]
Guys, were you able to resolve the issue?

**Comment by Usman3070** [comment]
Hi,
I have created an Alarm app with expo it works fine even in the background, but not working when I locked my phone.

**Comment by thientn4** [comment]
Hello, 
I found that this issue can be resolved for Android simulator. Background tasks not working is caused by Android's doze mode as explained below:
https://developer.android.com/training/monitoring-device-state/doze-standby|
This can be solved by manually disabling doze mode for an app as in the example below:
https://eatsleepride-support.groovehq.com/help/how-to-disable-doze-in-android-6-dot-0-marshmallow
However, my app will work much slower and I am trying to find out why.

**Comment by thenxkk** [comment]
Hi, it works for me, millions thanks.



> Hello, I found that this issue can be resolved for Android simulator. Background tasks not working is caused by Android's doze mode as explained below: https://developer.android.com/training/monitoring-device-state/doze-standby This can be solved by manually disabling doze mode for an app as in the example below: https://eatsleepride-support.groovehq.com/help/how-to-disable-doze-in-android-6-dot-0-marshmallow However, my app will work much slower and I am trying to find out how to fix that.
