### ISSUE TITLE
[expo-firebase-analytics] logEvent without properties param not working on Android standalone app

### ISSUE THREAD

**Issue by erickleal94** [expo/expo#8873]
### Calling Analytics.logEvent('event_name') without params throws an error on Android standalone app
I added an alert to show error in standalone app and it shows "java.util.set java.util.hashmap.keyset()' on a null object reference". When an empty object is added to the logEvent call, like Analytics.logEvent('event_name', {}) it works.

In Expo documentation the properties param is optional.

Running on iOS standalone app or Expo Client everything works fine.

**Comment by byCedric** [comment]
Hi @erickleal94! Thanks for the issue report. Could you share a bit more context about your project? E.g. SDK version or even better, a repro :) I tried reproducing this, but I couldn't. We had a known issue related to this, but it was fixed in #7897. If you are running an older version, I highly recommend upgrading it.

Hope it helps!

**Comment by IjzerenHein** [comment]
Closing, this issue was fixed by #7897
