### ISSUE TITLE
Unable to resolve module'./types' in expo/src/FacebookAds/withNativeAd.js

### ISSUE THREAD

**Issue by dooboolab** [expo/expo#888]
As said expo throws error in expo@22.0.0.
Unable to resolve module'./types' in expo/src/FacebookAds/withNativeAd.js

![image](https://user-images.githubusercontent.com/27461460/32234327-d60c55e4-be9f-11e7-823f-675c97090546.png)

When I looked in to that file, the js file is missing with it is referencing ./types.

![image](https://user-images.githubusercontent.com/27461460/32234410-024f3dce-bea0-11e7-8864-1c3e26147905.png)
![image](https://user-images.githubusercontent.com/27461460/32234414-06eace02-bea0-11e7-97b3-fb720635ae6e.png)

**Comment by terribleben** [comment]
This API works for me in [native-component-list](https://github.com/expo/native-component-list). Can you provide your package.json dependencies (or just compare with the one on that repo and see if there is a significant difference)?

**Comment by kingstenbanh** [comment]
I encounter the same issue. This issue still happens in SDK 23 and 22. I tried to downgrade to 21 and receive another error about FlowType. Can someone please help? I couldn't get pass the red screen of death. Expo seems to have a lot of issues and unstable lately.

**Comment by ide** [comment]
Not sure why this isn't working for you since almost no one else has encountered this issue but going to republish a new version of 23.0.1 with the './types' import removed.

Once it's published, install it by changing the version of expo under your package.json to "^23.0.1", delete `node_modules` to avoid funny business with yarn/npm, and reinstall. You might also want to follow these steps to clear the packager cache: https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352
