### ISSUE TITLE
Expo file system's `downloadAsync` creates blank, 0 bytes large file when server responded with 304

### ISSUE THREAD

**Issue by mtakac** [expo/expo#8907]
### Summary of Issue

Function `FileSystem.downloadAsync` from `expo-file-system` will download file even if the server responded with 304 Not Modified. It will just create empty (0 bytes) file in this case. I believe this is a bug and I think it shouldn't create the empty file if the server responded with 304.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /usr/local/bin/zsh
    Binaries:
      Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.12 
      react: 16.9.0 => 16.9.0 
      react-dom: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.21.5
```

Targeting both iOS and Android and the behaviour is same at both platforms.

### Reproducible Demo

I am not really sure how to provide a demo for this because it would require some server with uploaded file. If it's really necessary I think I could put something together using something like S3, but that seems like a bit of an overkill - hopefully the problem is clear enough.

### Steps to Reproduce

- call `FileSystem.downloadAsync` with url pointing to a server resource that will respond with 304 Not Modified.
- the call will succeed (as expected) but it will also create a blank file of 0 b size (not expected) 

### Expected Behavior vs Actual Behavior

I expect the `FileSystem.downloadAsync` not to create any files if 304 was returned from the server.
Righ now, it does create an empty file.

**Comment by barthap** [comment]
It creates the file regardless of response HTTP response code and content length, just because `downloadAsync()` has to return a valid file uri, even if the file itself is empty. Changing this behaviour would be breaking change and we don't want it.

The file is always replaced, each time `downloadAsync()` is called so you don't have to worry about deleting it (but you can if you want). You can always check file size using response `content-length`.

The only problem you can encounter is that your already downloaded resource gets replaced by empty file, when server decides you don't have to download it again and responds with 304. To overcome this, you can download to temporary location and then use `moveAsync()` when response status is 200.
