### ISSUE TITLE
[docs] update google-sign-in configuration docs to match current app.json schema

### ISSUE THREAD

**Issue by Ysrbolles** [expo/expo#8927]
1. SDK Version: 37
2. Platforms(Android/iOS/web/all):

I got an error when login with Google. The error message is an Alert as below:

**login: Error:GoogleSignIn.null: DEVELOPER_ERROR**

Thanks so much!

**Comment by AdamJNavarro** [comment]
Hey @Ysrbolles,

Thanks for opening your first issue in the Expo repo! We're going to need some more information before we can get into debugging and resolving the issue here. Can you provide the relevant code you've written that is throwing the error, let me know what platform the error is being thrown on and also ensure that you've properly followed all the necessary configuration steps as described [here](https://docs.expo.io/versions/v37.0.0/sdk/google-sign-in/#configuration).

Cheers,
Adam

**Comment by monceeef** [comment]
Is this happening in production? Because the certificate used is different from development, Make sure to recheck the SHA signature from your certificate and see if it's authorized in whatever you are using for google auth (Firebase or GC)

**Comment by Ysrbolles** [comment]
Hello @AdamJNavarro , 
I have this problem on android and I've properly followed all the configuration steps like you said but i still get the same error

`
componentDidMount() {
    this.initAsync();
  }
initAsync = async () => {
    await GoogleSignIn.initAsync({});
    this._syncUserWithStateAsync();
  };

  _syncUserWithStateAsync = async () => {
    const user = await GoogleSignIn.signInSilentlyAsync();
    this.setState({ user });
  };

  signOutAsync = async () => {
    await GoogleSignIn.signOutAsync();
    this.setState({ user: null });
  };

  signInAsync = async () => {
    try {
      await GoogleSignIn.askForPlayServicesAsync();
      const { type, user } = await GoogleSignIn.signInAsync();
     
      if (type === 'success') {
        this._syncUserWithStateAsync();
      }
    } catch ({ message }) {
      alert(type)
      alert('login: Error:' + message);
    }
  };`

and this the app.json

`{
  "expo": {
    "name": "AgriEdgeApp",
    "slug": "AgriEdgeApp",
    "sdkVersion": "37.0.0",
    "platforms": [
      "ios",
      "android",
      "web"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "bundleIdentifier": "expo.AgriEdgeApp.AgriEdgeApp",
      "buildNumber": "1.0.0"
    },
    "android": {
      "package": "expo.AgriEdgeApp.AgriEdgeApp",
      "googleServicesFile": "./google-services.json",
      "versionCode": 1
     
    },
    "description": ""
  }
}
`

**Comment by Ysrbolles** [comment]
Hello @AdamJNavarro ,
I have this problem on android and I've properly followed all the configuration steps like you said but i still get the same error

```
componentDidMount() {
this.initAsync();
}
initAsync = async () => {
await GoogleSignIn.initAsync({});
this._syncUserWithStateAsync();
};

_syncUserWithStateAsync = async () => {
const user = await GoogleSignIn.signInSilentlyAsync();
this.setState({ user });
};

signOutAsync = async () => {
await GoogleSignIn.signOutAsync();
this.setState({ user: null });
};

signInAsync = async () => {
try {
await GoogleSignIn.askForPlayServicesAsync();
const { type, user } = await GoogleSignIn.signInAsync();

  if (type === 'success') {
    this._syncUserWithStateAsync();
  }
} catch ({ message }) {
  alert(type)
  alert('login: Error:' + message);
}
};
```

and this the app.json

````
{
"expo": {
"name": "AgriEdgeApp",
"slug": "AgriEdgeApp",
"sdkVersion": "37.0.0",
"platforms": [
"ios",
"android",
"web"
],
"version": "1.0.0",
"orientation": "portrait",
"icon": "./assets/icon.png",
"splash": {
"image": "./assets/splash.png",
"resizeMode": "contain",
"backgroundColor": "#ffffff"
},
"updates": {
"fallbackToCacheTimeout": 0
},
"assetBundlePatterns": [
"**/*"
],
"ios": {
"bundleIdentifier": "expo.AgriEdgeApp.AgriEdgeApp",
"buildNumber": "1.0.0"
},
"android": {
"package": "expo.AgriEdgeApp.AgriEdgeApp",
"googleServicesFile": "./google-services.json",
"versionCode": 1

},
"description": ""
}
}
```

**Comment by Ysrbolles** [comment]
Hello @monceeef 

I get this issue  after build my app, How can I get the SHA in expo ?

**Comment by EvanBacon** [comment]
I would highly recommend using `expo-auth-session` ([Google guide](https://docs.expo.io/guides/authentication/#google)) in favor of `expo-google-app-auth` or `expo-google-sign-in`. I'm currently working on deprecating the later two in favor of the new `expo-auth-session` which has all of the same core functionality entirely written in JS so it's easier to debug when things go wrong. `expo-google-sign-in` is almost entirely a bare-workflow only module which makes it really hard to use in the Expo client. Auth Session also supports web and the Expo client via the [`useProxy`](https://docs.expo.io/versions/latest/sdk/auth-session/#authrequestpromptoptions) option which emulates web auth in development for cases where you cannot add a custom native redirect URI.

For persisting the credentials, I recommend using `expo-secure-store` on native and `AsyncStorage` from react-native-web on web.

**Comment by EvanBacon** [comment]
Further, you can retrieve the sha-1 by running `openssl rand -base64 32 | openssl sha1 -c` in your terminal. Cite: https://docs.expo.io/versions/v37.0.0/sdk/google/#using-it-inside-of-the-expo-app

**Comment by Ysrbolles** [comment]
Okay Thank you I will try to use it, because i don't find a solution for `expo-google-sign-in`


and thank you for the sha1 command

**Comment by Ysrbolles** [comment]
Hello @EvanBacon 

when  i use `expo-auth-session` , and try to connect with Google i get this error "Authorization error / Error: redirect_uri_mismatch" what this mean ??

**Comment by Ysrbolles** [comment]
The problem is fixed.

1. Get Android hashes from Expo
`expo fetch:android:hashes`

2. Copy Google Certificate Fingerprint and save it in your app.json under
```
{
    "expo": {
        "android": {
            "config": {
                "googleSignIn": {
                    "certificateHash": "<Google Certificate Fingerprint>"
                }
            }
        }
    }
}
```

3. Add the same Fingerprint in your Android app settings in Firebase console

**Comment by cruzach** [comment]
Hey @Ysrbolles , I updated the docs since we were missing the step where you add your certificate hash to the googleServices file. To do that: go to your Firebase project's settings, scroll down to "Your apps" and select your Android app. Under `SHA certificate fingerprints`, click `Add fingerprint`, and paste the value of you get for `Google Certificate Fingerprint` when running `expo fetch:android:hashes`. Then you should re download the google services file and replace the existing one in your app with the new one 😄

**Comment by grifotv** [comment]
@Ysrbolles @cruzach is it possible to get the hashes for a bare workflow app without `expo fetch:android:hashes` ? Is there an alternative way? thanks!

**Comment by giriprabu** [comment]
You can get the hash from expo.io -> credentials

**Comment by timoisalive** [comment]
I'm trying to get the GoogleSignIn working on Android (iOS works) in Bare workflow, but I keep on getting the `GoogleSignIn.null: DEVELOPER_ERROR` when running `GoogleSignIn.signInAsync()`.

I'm not sure if the reason is the Google Certificate Fingerprint, and I'm also not 100% sure which one should I be using to run the app locally (`expo run:android`), or ultimately in Google Play. I have now tried the sha-1 that I get from:
- `expo fetch:android:hashes`
- `openssl rand -base64 32 | openssl sha1 -c`
- Expo.dev Classic Android Credentials

...but none of them seem to make a difference. Also I'm unsure if the sha-1 should be included in `app.json` under Android config or not, as it is mentioned above in this thread but not in the GoogleSignIn documentation. I've tried with and without, but no luck.

I used to get the same error on iOS, but I got it fixed by adding the Google provided `com.googleusercontent.apps.XXX` URL scheme into `CFBundleURLSchemes` in `Info.plist`, but adding the same in `AndroidManifest.xml` (according to these instructions https://github.com/expo/fyi/blob/master/setup-android-uri-scheme.md) did not help.

@EvanBacon is recommending above to use `expo-auth-session`, and I guess that's my only option if I don't get this working, but wouldn't want to put a lot of effort since GoogleSignIn should probably work just as well...

Any ideas are welcome, thanks! 👍
