### ISSUE TITLE
Suspicious permissions added in release build for Android

### ISSUE THREAD

**Issue by ErikHellman** [expo/expo#8942]
### Summary of Issue (just a few sentences)
When building a release build for Android, suspicious permissions are added that we can't remove with a custom AndroidManifest.xml. This caused our app to be suspended by Google.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
  Expo CLI 3.21.9 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
      npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.7
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-navigation: ^3.11.1 => 3.11.1

### Reproducible Demo
Any build we make seem to add the following `uses-permission` tags to the manifest of the release APK:
```
    <uses-permission android:name="<application ID>.permission.C2D_MESSAGE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="host.exp.exponent.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
     <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.STORAGE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.USE_BIOMETRIC" />
    <uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" />
```

Especially `android.permission.REQUEST_INSTALL_PACKAGES` causes the review on Google Play Store to trigger and potentially suspend the app. Major issue for us as we can't fix this ourself at the moment.

**Comment by byCedric** [comment]
Hi @ErikHellman! I'm so sorry for the trouble with Google Play and the permissions. I think this is the first time we have a report about a suspended app using the `REQUEST_INSTALL_PACKAGES` permission. Maybe Google Play is focusing even more on this recently. Let's get this sorted for you asap! If you can provide more info on your project, that would be great. Or, if you are able to give me (or someone else from our support team) temporary and private access to the project, that might be even better. Because this is sensitive info, please send us a message at secure@expo.io to keep it as safe as possible.

Right now I suspect this permission is added when using the [`expo-device` package](https://docs.expo.io/versions/latest/sdk/device/). It looks like the permission is required to check if [sideloading is enabled or not](https://docs.expo.io/versions/latest/sdk/device/#deviceissideloadingenabledasync). You can't disable this permission yourself because it's [requested in the manifest here](https://github.com/expo/expo/blob/master/packages/expo-device/android/src/main/AndroidManifest.xml#L3).

I'd be happy to help you further through the secure channel. And again, sorry for the trouble.

**Comment by wkozyra95** [comment]
I'm not 100% sure which permissions are necessary, but some of those like REQUEST_INSTALL_PACKAGES are probably required in a client and not blacklisted for standalone builds

those packages should be added here https://github.com/expo/expo-cli/blob/master/packages/xdl/src/detach/AndroidShellApp.js#L772

**Comment by ErikHellman** [comment]
Thanks for a quick response! 

The permissions that are added are not listed in our `app.json`, so this is a really suspicious behaviour even without Google reacting to it. They really shouldn't be there in a release build. For instance, `android.permission.STORAGE` isn't even a valid permission and has no effect. `android.permission.RECEIVE_BOOT_COMPLETED` should really not be used by any regular app, since it will effectively trigger the app to startup at boot time without the user having launched it. `REQUEST_INSTALL_PACKAGES` should **REALLY** not be present at all!

Unfortunately I can't share access to the project at this point, but we do need some way to get rid of these permissions in our next release.

**Comment by ErikHellman** [comment]
@byCedric I created PR that hopefully fixes this. Would it be possible to have this merged ASAP so we can make a new release? Thanks!

https://github.com/expo/expo-cli/pull/2307

**Comment by byCedric** [comment]
Hey @ErikHellman! Thanks for the PR, I'll take a closer look at that one today. Are you able to share the response from Google with us by `secure@expo.io`? With this, we can enhance our documentation and describe why Google might find this suspicious. I also searched for a temporary workaround for you, and other people having issues with the permissions.

**Temporary workaround for bare and React Native projects**
Unfortunately, this solution only works for bare and React Native projects. You could eject only to release your app and revert to the managed code once you have the build. But these are the steps you can do:
1. Open `./android/app/src/main/AndroidManifest.xml`
2. Add `xmlns:tools="http://schemas.android.com/tools"` in the root `<manifest>` tag at the top of the file
3. Add the permission you want to exclude with `<uses-permission android:name="..." />`
4. Add the `tools:node="remove"` attribute to all permissions you _**don't want to include**_.

E.g. if you want to remove the `android.permission.REQUEST_INSTALL_PACKAGES` permission, you have to include it like the example below. It tells Expo and/or React Native to exclude that specific permission dependency when building the app.
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" package="...">
  ...
  <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove" />
  ...
</manifest>
```

**Why are these permissions added?**
I think it's also good to explain why these permissions are added in the first place. Expo modules provide a "bridge" between the React Native JS abstraction and native APIs, like [filesystem/storage](https://github.com/expo/expo/blob/master/packages/expo-file-system/android/src/main/AndroidManifest.xml#L6-L8), [local authentication](https://github.com/expo/expo/blob/master/packages/expo-local-authentication/android/src/main/AndroidManifest.xml#L2-L3), or [location](https://github.com/expo/expo/blob/master/packages/expo-location/android/src/main/AndroidManifest.xml#L2-L4). These permissions are added by default because without them they can't function properly. Unfortunately, it looks like the `REQUEST_INSTALL_PACKAGES` was added to [`expo-device`](https://github.com/expo/expo/blob/master/packages/expo-device/android/src/main/AndroidManifest.xml#L3), although it should have been handled as the [an opt-in Android permission](https://docs.expo.io/workflow/configuration/#android). It's used by [`Device.isSideLoadingEnabledAsync()`](https://docs.expo.io/versions/latest/sdk/device/#deviceissideloadingenabledasync)) to check it apps are sideloadable in Android.

**Our next steps**
That being said, we take permission and app rejections because of this very seriously. Looking back, I think it's safe to say that we failed to explain what Android permission we need in specific modules. For that, we are sorry. The next steps for us are:
- Fix the `REQUEST_INSTALL_PACKAGES` in `expo-device` and make it opt-in in case you still want to use that method.
- Audit the existing packages and all required permissions for those packages
- Improve documentation on the permissions we added by default, or explain which permission are opt-in and for what purpose.

I'll also try to reach out to the Android team and see if we can get additional information on which permissions are considered suspicious by Google, but I'm not sure how far they are willing to go.

Again, thanks for reporting this issue!

**Comment by ErikHellman** [comment]
Hi @byCedric! I love the prompt response here. Awesome! :) 

There is not much information about the message from Google to share. They claim "Deceptive Behaviour" as the reason and I managed to get an unofficial response that it is because these permissions. The email about the suspension of the app points to this page for more information: https://support.google.com/googleplay/android-developer/answer/9888077#1&2&3&4&5&6&7&87&9

Unfortunately I'm not able to share more than that for reasons outside my control. 

We'll try the bare solution as you describe and hopefully we can get a new APK through that method.

A comment about these permissions, especially `REQUEST_INSTALL_PACKAGES`. Trying to sideload code inte an app outside of Google Play Store is a violation of the Terms of Service. My guess is that Google have started going after apps that are uploaded with this permission, which is why this started happening now. 

The support page for "Deceptive. Behaviour" also mentions system popups as a cause, so `SYSTEM_ALERT_WINDOW` is also something that should be removed by default.

**Comment by byCedric** [comment]
Ok, that's no problem. I'll try to contact them as well and see if any of the permissions are matching the links you sent, thanks for that.

> A comment about these permissions, especially REQUEST_INSTALL_PACKAGES. Trying to sideload code into an app outside of Google Play Store is a violation of the Terms of Service. My guess is that Google have started going after apps that are uploaded with this permission, which is why this started happening now.
Yes, and I totally agree with that. I think this method was created to detect if this is possible, not to actual sideload something like that. Some "pro" apps are checking if devices are rooted or have sideload enabled to restrict access to certain areas. Again, the `expo-device` module doesn't and won't support sideloading apps for this reason as well.

> The support page for "Deceptive. Behaviour" also mentions system popups as a cause, so SYSTEM_ALERT_WINDOW is also something that should be removed by default.

Totally agree with this one as well. I haven't investigated this deeply but as far as I can see now, it's added by [React Native for debugging](https://reactnative.dev/docs/removing-default-permissions) purposes. Because it's for debugging, it's a good candidate to remove as well.

I'm not sure why Google is taking a more aggressive stance on this, but it's something that we are working on! Let me know if the bare workaround works for you, if not feel free to mention me!

Hope it helps!

**Comment by jedahan** [comment]
The more each of these permissions can be opt-in or opt-out (with appropriately documented caveats of what functionality will be disabled), the better. <3

**Comment by ErikHellman** [comment]
Is there any update on this? We're currently blocked on this completely. Ejecting from expo turned out to be more complicated than we imagined, and we're very hesitant on releasing a new app with only one of these unneeded permissions being present.

It would be really great if Expo would provide an option to remove permissions explicitly.

**Comment by RodolfoGS** [comment]
Hi @ErikHellman, try removing the permission https://github.com/expo/expo/issues/8942#issuecomment-649622756

**Comment by ErikHellman** [comment]
> Hi @ErikHellman, try removing the permission [#8942 (comment)](https://github.com/expo/expo/issues/8942#issuecomment-649622756)

As I wrote, ejecting from Expo turned out to be more complicated than we expected. We can still build with the Expo toolchain, but we can't remove the permissions we want to get rid of.

**Comment by RodolfoGS** [comment]
> **Temporary workaround for bare and React Native projects**
> Unfortunately, this solution only works for bare and React Native projects. **You could eject only to release your app and revert to the managed code once you have the build**.

@ErikHellman I think that you can eject, remove the permission, send a build to Google Play Console to remove the permission and then send another build managed.

**Comment by ErikHellman** [comment]
> @ErikHellman I think that you can eject, remove the permission, send a build to Google Play Console to remove the permission and then send another build managed.

While technically feasible. it would require us to decompile parts of the apps in order to recompile it again with a modified manifest. It is not practical and far from a suitable solution here.

**Comment by RodolfoGS** [comment]
@ErikHellman maybe you can create a new project (an empty project), eject it, remove the permission, build and send it to google play just for remove the permission (maybe you can send only as beta or alpha version). Then, create a managed build.
But I not sure if it works, I'm not an Android developer expert and I don't work at Expo. Sorry, I'm trying to make the best, but I can't help much with it.

**Comment by byCedric** [comment]
Hi @ErikHellman! I can't give you an ETA on this one yet. It's a really tough and delicate topic that we want to do right. There is some variation between normal Android libraries and React Native libraries. Any (big) change related to this may cause a lot of breaking changes in all existing apps, that's why we need to do this carefully.

Right now, PR #8969 would solve the `REQUEST_INSTALL_PACKAGES` issue but we don't have a fix for the `SYSTEM_ALERT_WINDOW` (yet). This permission is required in the Expo Client, to render the performance monitor, so we can't simply remove it.

Your best path forward at the moment would still be the bare workflow when creating the APK. It shouldn't be a big difference for your workflow, you only need to do this when creating the APK. If you are having problems with the bare workflow, we'd be happy to hear what problems and help you further.

RodolfoGS's alternative with [APKTool](https://stackoverflow.com/questions/54050467/how-to-remove-a-permission-from-an-apk-file) should also work. You shouldn't have to do this often, only when creating a new standalone build. If you have one with the extracted APK, you can use OTA for future updates until this is properly resolved.

Hope it helps!

**Comment by ErikHellman** [comment]
Hi @byCedric! 

I totally get that this is a complex issue to solve. The workarounds you mention are possible for a one-time workaround, but I need to find a sustainable solution. 

However, I do have another suggestion. The expo-section in the `app.json` today allows us to explicitly add permissions to the final APK. How about adding a `permission-filter` array which would let us filter out the permissions we want to explicitly remove? That way you wouldn't have to break any apps using the existing toolchain.

This should be fairly simple process that would involve some XML processing only. 

What do you think?

**Comment by Muhammad-Alaa-Kareem** [comment]
Hi everybody,

Is this bug related to all versions of expo? I am using 36.00.
Also, I want to know if this problem happens for publishing APK, or both APK and Android App Bundle.

Thanks

**Comment by Muhammad-Alaa-Kareem** [comment]
Hi everybody,

Thanks @byCedric for your suggestions. 

I would share my experience to using APKTool.
In [APKTool](https://ibotpeaches.github.io/Apktool/), after decoding your apk using `apktool d yourApp.apk` statement, you can remove a permission by adding `tools:node="remove"` like this: 
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" tools:node="remove"/>`

You should add the attribute `xmlns:tools="http://schemas.android.com/tools"` to the <manifest> element like this, if it doesn't exist:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools" .....>`

Also, you need to increase the **versionCode** in apktool.yml file and optionally **versionName** according to the [link](https://stackoverflow.com/questions/54050467/how-to-remove-a-permission-from-an-apk-file) provided by @byCedric

After building your application using `apktool b bar `you should zipalign and re-sign your apk. You can use the steps (_ALIGNING_ and _SIGNING_) in this [tutorial](https://www.construct.net/en/tutorials/manually-signing-android-apps-29). Of course, you will use your previous keystore taken via `expo fetch:android:keystore` So, you will not use _CREATE A KEY_ step.

Hope this helps!

**Comment by byCedric** [comment]
Hi people, I'm going to close this issue in favor of the umbrella issue. What we have done so far:

- Audited Android permissions of all Expo modules
- Refactored some packages with missing or wrong permissions (including [the `REQUEST_INSTALL_PACKAGE` permission](https://github.com/expo/expo/pull/8969))
- Be more transparent about the permissions added per module and [how this works in general](https://github.com/expo/expo/pull/9141).
- We will merge the PR to expand the permission blacklist (https://github.com/expo/expo-cli/pull/2307) soon!

We are also discussing stuff like "can we make the `WRITE_*` permission optional if they also need a `READ_*` permission" (just like `expo-contacts` for example). If you find any unexpected permission in your app, please comment that on the umbrella issue.

Again, thanks for reporting and participate in this issue!
