### ISSUE TITLE
iOS standalone doesn't use CFBundleShortVersionString specified in infoplist

### ISSUE THREAD

**Issue by jayeszee** [expo/expo#895]
It seems that expo is using the "version" field of my app.json instead of the CFBundleShortVersionString of my infoplist. The reason I want to use the CFBundleShortVersionString instead of version is because I deploy both to android and iOS and they are different in version numbers. Any ideas?

**Comment by terribleben** [comment]
Hi there! Here's the exact behavior:

- Android's `versionName` is your app.json version.
- iOS `CFBundleShortVersionString` is your app.json version.
- Android `versionCode` is configurable via `android.versionCode` in app.json.
- iOS `CFBundleVersion` is configurable via `ios.buildNumber`.

It sounds like we don't support the behavior you want, but maybe the above is helpful. I think your best bet is probably to align the app version across platforms, since you are pretty much deploying the same app to both platforms.

If you think we should build some other behavior you are also welcome to track that via a [feature request](https://expo.canny.io/feature-requests).
