### ISSUE TITLE
Warning box on the android app is not disappearing after fixing the error.

### ISSUE THREAD

**Issue by d-e-v-esh** [expo/expo#9043]
## Description

The yellow warning panel is not registering refreshes as it should. Refreshing the app after fixing issues does not make that yellow warning panel in the expo android app disappear. 

## Expected Behavior

The warning panel should disappear when the warning issue is fixed but it is not registering the refreshes. This is making things confusing while writing code to know if I fixed the error or not.
In this case when I first run the FlatList element without a key, it presented me with a warning down below which is normal. But when provided the FlatList element with a key then the warning should disappear.

## Observed Behavior

When I provided the FlatList element with a key then the warning did not disappear like in all the tutorials I was following. So I saved the project and reopened it and the warning went away and when I reopened it without giving the FlatList element the key then it reopened with a warning.
This happened all kinds of warnings not just missing key and key extractor.

```
```
## Environment

  Expo CLI 3.20.9 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.1.0 => 4.3.9

----------------------------------------------------------

Device Model: Redmi Note 4
Andioid Version: Android 7.0 NRD90M
MIUI Version: MIUI Global 11.0.2

-----------------------------------------------------------

java --version
java 11.0.7 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

----------------------------------------------------------
Gradle 6.3

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60
Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.7 (Oracle Corporation 11.0.7+8-LTS)
OS:           Windows 10 10.0 amd64

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

-- Enable USB debugging and connect the device.
-- Go to the project folder and run this 
```
expo start --localhost --android
```
You can try getting some error anyhow but can also try this simple code. The key line ```keyExtractor={(friend) => friend.name}``` line is commented out.
```
import React from 'react';
import { Text, StyleSheet, View, FlatList } from 'react-native';

const friendsList = [
  { name: 'Friend expo/expo-cli#1', age: 20 },
  { name: 'Friend expo/expo-cli#2', age: 21 },
  { name: 'Friend expo/expo-cli#3', age: 22 },
  { name: 'Friend expo/expo-cli#4', age: 23 },
  { name: 'Friend expo/expo-cli#5', age: 24 },
  { name: 'Friend expo/expo-cli#6', age: 25 },
  { name: 'Friend expo/expo-cli#7', age: 26 },
  { name: 'Friend expo/expo-cli#8', age: 27 },
];

const ListScreen = () => {
  return (
    <FlatList
      // keyExtractor={(friend) => friend.name}
      data={friendsList}
      renderItem={({ item }) => {
        return (
          <Text>
            {item.name} is {item.age} years old
          </Text>
        );
      }}
    />
  );
};

const styles = StyleSheet.create({
  text: {
    fontSize: 30,
  },
});

export default ListScreen;
```

**Comment by byCedric** [comment]
Hi @d-e-v-esh! Thanks for the issue report, but this behavior is intended with Fast Refresh. There are two things here at play:

1. When you (accidentally) create a syntax error and save the file, you will see a red box. But, if your app runs with a syntax error, it crashes your app and you'll need to reload. To fix that, [Fast Refresh doesn't actually run the syntax error](https://docs.expo.io/versions/v36.0.0/react-native/fast-refresh/#error-resilience), and thus the red box disappears when fixing that error.

2. [Fast Refresh tries to keep the local state in your components](https://docs.expo.io/versions/v36.0.0/react-native/fast-refresh/#tips), useful if you quickly want to tweak the layout for search results for example. Because you aren't actually editing the yellow box, the state here is also stored. This makes the yellow box persistent when using Fast Refresh.

You can disable Fast Refresh, but that forces you to manually reload the app every time you make a change. If you think this is behavior is incorrect, feel free to open an issue in the [react-native repository](http://github.com/facebook/react-native).

Hope it helps!
