### ISSUE TITLE
Chromecast functionality!

### ISSUE THREAD

**Issue by cjcmattsson** [expo/expo#9052]
Would love an update on how/if you guys are working on Chromecast functionality :)
https://expo.canny.io/feature-requests/p/support-for-chromecast

Thanks!

**Comment by EvanBacon** [comment]
We will update the canny if we plan on adding support for this package. You can use Chromecast native SDK by ejecting to the bare-workflow. We are a small team so we're prioritizing improving the bare-workflow rather than making new modules. 

Further, have you tried using the JS API for Chromecast? Here is a package that works using the built-in Networking API https://github.com/alxhotel/chromecast-api

**Comment by danielcotton** [comment]
Sorry to necro this issue; but would you accept a Chromecast unimodule into the SDK if someone were to contribute it?

Just trying to work out if this is simply a lack-of-time thing, or if there's also an architectural reason
