### ISSUE TITLE
[SDK 38] [expo-notifications] Malformed data payload on iOS

### ISSUE THREAD

**Issue by gggdomi** [expo/expo#9059]
### Summary of Issue (just a few sentences)

When receiving a notification with data, we don't get the data object we expect on iOS.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
Expo CLI 3.21.13 environment info:
  System:
    OS: macOS 10.15.3
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    expo: ^38.0.0 => 38.0.4
    react: 16.11.0 => 16.11.0
    react-dom: 16.11.0 => 16.11.0
    react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2
    react-native-web: ~0.11.7 => 0.11.7
```

### Reproducible Demo

- Start the snack from https://docs.expo.io/versions/latest/sdk/notifications/ on iOS
- Click "Press to Send Notification"
- The notification data (see screenshot below) is malformed
- On android the snack does not work (see #9058), but the notification data seems to be as expected in my codebase.

### Expected Behavior vs Actual Behavior

Expected Behavior : `Data: { data: 'goes here' }`

Actual Behavior : see screenshot

![image](https://user-images.githubusercontent.com/11262934/86325192-f35ad800-bc3f-11ea-9045-61a029efb314.png)

**Comment by RodolfoGS** [comment]
I think that the flag `useNextNotificationsApi` is missing, but I don't know if you can add a custom app.json file in a Snack.

**Comment by lukmccall** [comment]
This snack won't work for now, cause `app.json` needs to contain `useNextNotificationsApi ` flag. I've added note about it ;) Thanks for reporting it 🏅

**Comment by gggdomi** [comment]
Thanks for your answer @lukmccall 
Are you sure this should be closed ?
- the issue is on iOS, and I believe useNextNotificationsAPI flag is for Android only
- I’ve witnessed the same beahvior in production with the flag on, the snack was just an easy way to reproduce

**Comment by summerkiflain** [comment]
everything about expo-notifications is Effed up!
I receive `data` like `response.notification.request.content.data` on android /  from local notifications and from push notifications,
but receiving `data` like `response.notification.request.content.data.body` on iOS only from push notifications, local notifications on iOS return `data` like android.

It should be inside `body` everywhere, iOS push notification's `data` includes `aps` key also, I suppose there will be something similar from fcm also, so that can be included or just put data inside body for the sake of consistency and update the docs.
