### ISSUE TITLE
Bare - expo-updates Updates.checkForUpdateAsync() fail when no release-channel published

### ISSUE THREAD

**Issue by CharlyPoppins** [expo/expo#9099]
## 🐛 Bug Report

**expo-updates** fail on Updates.checkForUpdateAsync() when bundles have not been published to release channel yet with **expo publish --release-channel xxxx**

### Summary of Issue

I've catch this exception with Sentry.

On Android : Failed to download manifest from URL: https://exp.host/@****/***

On iOs : {"message":"Experience \"@****/****\" for platform \"ios\" and release channel \"****\" does not exist or is not published.","errorCode":"EXPERIENCE_NOT_FOUND","metadata":{"fullName":"@****/****","platform":"ios","sdkVersions...

(sorry I don't have the full message)

With bare workflow and expo-updates release embed the local code without the need to publish. 

Do this case need to be handled by expo-updates or do we need to handle this in our code ? (and how?)

Let me know if I can help providing more information.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

Expo CLI 3.21.5 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.7.0 - ~/.nvm/versions/node/v13.7.0/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v13.7.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.10 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: ~0.61.5 => 0.61.5
      react-navigation: ^4.3.7 => 4.3.7

"expo-updates": "^0.2.7"

**Comment by SleeplessByte** [comment]
This is to be expected. You _must_ run `expo publish` or `expo publish --release-channel XXX` _before_ creating your build in order to correctly inject the update values. The other option is `expo export`, or removing `expo-updates` completely.

**Comment by CharlyPoppins** [comment]
I got a bit confused with the **no-publish workflow**.
> In this workflow, release builds of both iOS and Android apps will create and embed a new update at build-time from the JS code currently on disk, rather than embedding a copy of the most recently published update.

What is the better way : 
- **expo publish** then **build standalone**
or
- **build standalone** then **expo publish**

**Comment by SleeplessByte** [comment]
I believe it's always:

`expo publish` then **build standalone**

**Comment by jonathanstiansen** [comment]
@SleeplessByte that's not correct anymore, in fact if you publish first with the no-publish workflow it's functionally useless.
Since it's got a built in bundle with a newer timestamp then the published one, so it never retrieves it.

@CharlyPoppins Any reason you closed this? Publishing after (or not at all) should be valid

@brentvatne can you comment if it's intended to have this error if you build but not publish, with expo-updates 2.0? We are having the same issue - sentry is reporting it.

**Comment by jonathanstiansen** [comment]
@CharlyPoppins as I'm reading your error though, you seem to need an experience-id to get this working.

**Comment by CharlyPoppins** [comment]
@jonathanstiansen you're right i re-open the issue.

> This means you no longer need to run expo publish before creating a release build for the first time.
from https://blog.expo.io/over-the-air-updates-from-expo-are-now-even-easier-to-use-376e2213fabf

Reading this I expect to NOT PUBLISH and Updates.checkForUpdateAsync() to respond there is no update available instead of throwing an error.

**Comment by SleeplessByte** [comment]
It's not useless, as it sets up some values in the configuration. I think there might be some bugs with it not being present at all 🤷‍♂️

At this moment it's still publish then build, even if you build with no publish.

**Comment by byCedric** [comment]
Hi @CharlyPoppins (and others), thanks for the issue report. I'm not sure if I follow your use case correctly, so please do correct me. You are using a bare Expo project, and implemented the `checkForUpdateAsync`. But you haven't pushed or published any code yet, right?

If this is true, that's a limitation of our current backend. If you haven't pushed anything yet, there is no project in the backend. That's created once you publish some code, you can use the template code for starters.

The no-publish flow was created to allow developers to create an IPA or APK directly without publishing anything. But that doesn't mean you can check for updates because we simply don't know the project yet 😄 

If you think this is an error on our side, let us know and I'll reopen the issue.

**Comment by CharlyPoppins** [comment]
Hello @byCedric,

as said in https://github.com/expo/expo/issues/9099#issuecomment-660947577 it's confusing.

Doc should explicitly said : 
- you don't have to publish if you are not using OTA updates
- you must publish before creating release (even if expo-updates create and embed a new update) if you want to use OTA updates

**Comment by lucaspelle1909** [comment]
It didn't work, I still have the same error

**Comment by lucaspelle1909** [comment]
In SDK 39, publish with release-channel doesn't work: [issue](https://github.com/expo/expo/issues/10304)

**Comment by sungsong88** [comment]
I have the same issue as OP, but it only happens occasionally. I'm using `expo publish --release-channel my_app_10101`. 
I see the users having this issue are on Android 9.
