### ISSUE TITLE
eslint-config-universe react-hooks possible bug?

### ISSUE THREAD

**Issue by kickbk** [expo/expo#9125]
### Summary of Issue
I am not sure this is a bug, perhaps I'm doing something wrong, but after installing [eslint-config-universe](https://github.com/expo/expo/tree/master/packages/eslint-config-universe), I am not seeing warnings for incorrect react-hooks violations.

#### Setup

```
expo init test
Choose a template: expo-template-tabs
cd test
// Next, I follow instructions
yarn add --dev eslint-config-universe
yarn add --dev eslint prettier @typescript-eslint/eslint-plugin @typescript-eslint/parser
// Added to package.json
{
  "eslintConfig": {
    "extends": "universe/native"
  }
}
// Created .eslintrc.js with
module.exports = {
  extends: 'universe/native',
};
// Customized Prettier as instructed, but that's not important
```

#### Introduce the error and check if we get a warning

Added useEffect hook with a missing dependency to App.tsx
```
export default function App() {
  const [me, useMe] = React.useState();
  React.useEffect(() => {
    console.log('me', me);
  }, []); // <<< Expecting the validation warning to complain about 'me' as a missing required dependency
```

### Expected Behavior vs Actual Behavior

The expected validation warning does not appear.

I dug into https://github.com/expo/expo/tree/master/packages/eslint-config-universe. Correct me if I'm wrong, but by declaring  `extends: 'universe/native'` I'm assuming we are loading https://github.com/expo/expo/blob/master/packages/eslint-config-universe/native.js. If that's the case, that file extends `'./shared/react.js'` which in turn loads the `'react-hooks'` plugin and declares `'react-hooks/rules-of-hooks': 'error'`, and `'react-hooks/exhaustive-deps': 'warn'` rules.
So aren't we supposed to see the warning?

Am I missing something that was perhaps not mentioned in the docs?

**Comment by byCedric** [comment]
Hi @kickbk, thanks for the issue report! It looks like we never published this version on NPM, so the code you are looking into is newer than the latest published version on NPM. Thanks for letting us know, we should fix that.

Meanwhile, you can also manually enable it in your project:
- `yarn add --dev eslint-plugin-react-hooks`
- Update your `.eslintrc.js` to:
```
module.exports = {
  extends: 'universe/native',
  plugins: ['react-hooks'],
  rules: {
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'warn',
  },
};
```

As a side note, I would recommend to either use the `eslintConfig` in `package.json` _or_ the `.eslintrc.js` file. Having multiple configurations for eslint makes maintenance harder than should be 😄 

Hope it helps!

**Comment by kickbk** [comment]
Bedankt @byCedric. That works. I am not crazy after all :) I should have compared with NPM.
I know it's unrelated, but would you recommend using eslint-config-airbnb in addition to eslint-config-universe? Are there any benefits? Is it an overkill? I imagine it's a personal choice, but my gut feeling is telling me universe is all we really need.

**Comment by byCedric** [comment]
Haha, geen probleem! I wouldn't combine Airbnb and Universe configurations, some of the rules might collide. There is no good or bad choice here, but they are slightly different.

- Airbnb is focusing more on a [specific style outlined here](https://github.com/airbnb/javascript), it's also flagging "errors" for proper code but written in a slightly different style.
- Universe is more focusing on errors instead of style, [only flagging actual errors and leaving a bit more room for code styling](https://github.com/expo/expo/tree/master/packages/eslint-config-universe#philosophy).

As you said, it's mostly a personal choice. Some people (including me) like the Airbnb guide, but I can imagine Universe creating less friction and leaving more for the developer to decide 😄

**Comment by byCedric** [comment]
Quick update on the release, we are holding off for a bit because we have some breaking changes in master. We don't want to cause issues here, so it will be a new major release. For now, I would recommend the manual integration. ([see example](https://github.com/expo/expo/pull/8455#issuecomment-655071826))

**Comment by ide** [comment]
As I understand it, the Airbnb linter configuration takes more of a stance of: if there is a possibility something could go wrong, treat it as a lint error.

The Expo linter configuration's stance is more: minimize how much attention the linter takes away from an expert programmer. False positives and needing `// eslint-ignore` costs attention. If something is unequivocally an error (syntax error, for example), report it as an error. If it's not a hard error but the rule never or almost never has false positives, report it as a warning. Otherwise leave it up to the programmer to do the right thing

Also the Expo linter configuration is designed according to our conventions, which are subjective to a degree. For example, we use Prettier but with 100 columns (`because: Types & Generics<Take<Up, Space>>`). If you like them then the linter is probably a good fit. If you don't like one or two rules you can usually override those yourself in your app's ESLint config. If you don't like the philosophy of the linter then it's probably more pleasant to use/write a different config.

**Comment by kickbk** [comment]
@ide, I like the approach you guys took in regard to eslint (and Prettier). eslint-config-universe bundles the linting nightmare into one (apparent) line of extend code. It's **very** elegant. Honestly, I would consider giving it more prominence in your docs, or perhaps even add an option in expo init to add it to the mix, such as `Expo init myApp -lint`.

Regarding `exhaustive-deps` being noisy - I saw you guys had to add a bunch of exceptions in your code to disable it. I also wouldn't be surprised if at some point useEffect will handle dependencies automatically. Probably the right choice to leave it out.
