### ISSUE TITLE
Jest tests failing with type error after upgrading to expo-jest 38.0.0 & expo 38.0.0

### ISSUE THREAD

**Issue by sophiaritchie** [expo/expo#9129]
### Summary of Issue 
Jest test type exception after upgrading to expo sdk 38.0.0 and expo-jest to v 38.0.0, expo types is on latest 25.1.3

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
``` Expo CLI 3.21.5 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^38.0.8 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz => 0.62.2
```

### Reproducible Demo
Running our jest tests fails with a type error
```
 jest --verbose --coverage --coverage-reporters=text

internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:117:11)
    at Object.resolve (path.js:139:9)
    at Object.<anonymous> (..\node_modules\jest-expo\bin\jest.js:20:30)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! Test failed.  See above for more details.
```

 
### Steps to Reproduce
Run npm test with updated sdk

### Expected Behavior vs Actual Behavior

Should be able to run the tests without a type error. In the expo docs it seems that it should work with our setup: https://docs.expo.io/guides/testing-with-jest/

**Comment by byCedric** [comment]
Hi @sophiaritchie, thanks for your issue report! We are aware of [unexpected behavior with NPM and Yarn related to the `bin` section in the `package.json`](https://github.com/expo/expo/issues/8983#issuecomment-651149439). This is patched already but we still need to publish this. You can work around the issue in 3 ways:

- Patch the `./node_modules/.bin/jest` with [this piece of code](https://github.com/expo/expo/blob/master/packages/jest-expo/bin/jest.js#L20-L23)
- Use Yarn instead of NPM, NPM has a slightly different behavior as mentioned in the link above.

Sorry for the inconvenience, we hope to ship the patch soon!
