### ISSUE TITLE
Can't get Phone number

### ISSUE THREAD

**Issue by imdeepakchahar** [expo/expo#9134]
@expo-contacts
**Code:**

```
(async () => {
      const { status } = await Contacts.requestPermissionsAsync();
      if (status === "granted") {
        const { data } = await Contacts.getContactsAsync({
          fields: [Contacts.Fields.PhoneNumbers],
        });

        if (data.length > 0) {
          const contact = data[0];
          console.log(contact);
        }
      }
    })();
```
**Output**
```
Object {
  "contactType": "person",
  "id": "13001",
  "imageAvailable": false,
  "lookupKey": "364r12832-",
  "name": "null null",
}
```

**Comment by byCedric** [comment]
Hi @imdeepakchahar, thanks for the issue report. Unfortunately, we need a bit more info to help you find the issue here. Please create a new issue and fill in the issue template. It's good that you added the code, but we need more info. For example, I have no idea which SDK you are using, what platform this happens, your project type (managed/bare) etc.

I've tested this with the example from the docs and I can't reproduce this. You can see a [modified example here](https://snack.expo.io/@bycedric/basic-contacts-usage).

Hope this helps

**Comment by JeremiahUL** [comment]
Why are you closing it when you need enough info... I am having the same issue. Many people that raised the same issue , it was hastily closed the same way. This happens on Android ... There is no way to get phone number with the above code even after permissions have been accepted.
I want to open an issue but there are so many duplicate issues that were closed quickly without a solution

**Comment by brentvatne** [comment]
@JeremiahUL - we require that you fill in the issue template in order to help. it is a very small ask in exchange for us helping out with a request, it gives us the information that we need in order to be able to help. if you just take a few minutes to fill out the issue template correctly then we will not close the issue.

**Comment by brentvatne** [comment]
for your reference, here is the issue template. compare it to the original post and see how much information has been left out:

```
## 🐛 Bug Report

### Summary of Issue <!-- (just a few sentences) -->


### Environment - output of `expo diagnostics` & the platform(s) you're targeting


### Reproducible Demo

<!--
- This should include as little code as possible, please don't simply link your entire project
- Sharing a link to a [Snack](https://snack.expo.io/) is a GREAT way to provide a reproducible demo :) 
- If a reproducible demo, or a complete list of steps from blank project to bug, are not provided, it is very likely your issue will be closed
- If you need more guidance, please see https://stackoverflow.com/help/mcve
-->
<!--
As an added benefit- creating a repro may help you identify the source of the bug, which means we are one step closer to fixing it! Thanks for helping us help you!
-->
 
### Steps to Reproduce


### Expected Behavior vs Actual Behavior
```

**Comment by JeremiahUL** [comment]
Yes Brent. No issues. I totally understand

**Comment by shohan-ch** [comment]
Just changed the contacts field type to phoneNumbers
