### ISSUE TITLE
Sharing functionality in Expo

### ISSUE THREAD

**Issue by frodoe7** [expo/expo#9138]
### Summary of Issue 
This is a report about some limitation in the Expo Sharing plugin (not literally a bug)

here's the code in brief
Sharing.shareAsync("localFilePath", { dialogTitle : "Title" })

### Expected Behavior vs Actual Behavior

What expected is to share the image include the title

The actual behavior , it only shares the image without the title

----

also note , this code
Sharing.shareAsync("invalid Or not exist path", { dialogTitle : "Title" })
only share the title without the image

---

How to share both!

**Comment by cruzach** [comment]
Hi! This is working for me correctly in this snack (tested on a OnePlus) - https://snack.expo.io/@charliecruzan/sharing-with-title

I'm going to close this issue since, without the information we ask for in the issue template, it can be really hard to try to help. If you can edit the issue to include all of the info we ask for, I'll be happy to reopen it

**Comment by StevenWonder** [comment]
I have a similar problem.

I run your snack and see the title `Share` instead of `my special title`

**Comment by ericyliu** [comment]
the snack no longer works, but I am having the same issue in my project
