### ISSUE TITLE
Playing one sound many times

### ISSUE THREAD

**Issue by thomasarbona** [expo/expo#915]
I'm trying to play one sound many times with, i'm create the Sound like this:
```js
SOUNDS[key] = new Expo.Audio.Sound();
await SOUNDS[key].loadAsync(sounds[key]);
```
And I have this function to play the sound:
```js
export async function playSound(key) {
  if (SOUNDS[key]) {
    SOUNDS[key].setPositionAsync(0);
    SOUNDS[key].playAsync();
  }
}
```

The sound works well the first time, but the other times it seems that the sound isn't playing from the start but with a shift of some milliseconds (only half of the sound can be heard).

Tested on iOS.

**Comment by dikaiosune** [comment]
Hi! It would help us a lot if you could create a minimal reproduction of this issue on https://snack.expo.io. Thanks!

**Comment by thomasarbona** [comment]
Hi, thank's for your help!
https://snack.expo.io/BJYuMG11f

**Comment by sjchmiela** [comment]
Hi, @thomasarbona! I've investigated your issue a little bit and here's what I found:

1. The URL link to the audio file you provided has expired. 😄
2. I'd recommend preparing the Audio session before playing the sounds, i. e. calling something like this:

    ```js
    export async function prepareSound() {
      await Expo.Audio.setIsEnabledAsync(true);
    
      await Expo.Audio.setAudioModeAsync({
        playsInSilentModeIOS: true,
        allowsRecordingIOS: false,
        interruptionModeIOS: Expo.Audio.INTERRUPTION_MODE_IOS_DO_NOT_MIX,
        shouldDuckAndroid: false,
        interruptionModeAndroid: Expo.Audio.INTERRUPTION_MODE_ANDROID_DO_NOT_MIX,
      });
    }
    ```
3. I'd also recommend awaiting the results of the `setPositionAsync`, AFAIK calling async functions just like regular functions this doesn't give us certainty of the order of execution, try calling:

    ```js
    function longAsync() {
      return new Promise(resolve => setTimeout(() => {
        console.log('Long task has completed.');
        resolve();
      }, 500));
    }
    
    function shortAsync() {
      return new Promise(resolve => setTimeout(() => {
        console.log('Short task has completed.');
        resolve();
      }, 100));
    }
    
    async function playAnalogy() { // async is not needed here as long as we don't use await
      longAsync();
      shortAsync();
    }
    ```
    the output of the above is
    ```
    Short task has completed.
    Long task has completed.
    ```
    which is not the exact order of the execution. Awaiting would ensure that the position is properly set before calling `playAsync`.

4. The issue you found doesn't come from Expo SDK. Try opening the audio file in Safari: the player there behaves exactly like the Snack you provided: first it plays the whole file, then it cuts first milliseconds. I guess it's an iOS bug. (Future reference: I've also tried setting `seekToTime`'s tolerance to `kCMTimeZero`, didn't help. 😞 )

There are three imperfect solutions I can think of:
- one would be to reload the `Sound` on every `play`. Example implementation: https://snack.expo.io/HyX29l71z Unfortunately it introduces a little delay on every tap.
- another solution would be to listen to playback status updates and reload the sound immediately after it finishes to play (https://snack.expo.io/H1WiQG71M, set `RELOAD_TRUE_STOP_FALSE = true`). Unfortunately it reloads the file from the Internet every time (it seems, activity indicator refreshes after every play).
- third solution is similar to the former, but instead of reloading the sound we stop it. Unfortunately it introduces a short buzz in the beginning of the sound. (https://snack.expo.io/H1WiQG71M, set `RELOAD_TRUE_STOP_FALSE = false`).

None of these solutions provide a real quick repeatable tap-to-sound behaviour, sorry. 😞

**Comment by thomasarbona** [comment]
Hi, @sjchmiela. Thank you for your awesome answer!
I think i'm going to use your last solution, preload multiple copies, it seems the best for me.

**Comment by terribleben** [comment]
Thanks @sjchmiela for addressing this issue here: https://github.com/expo/expo/commit/0caf4d47bae0bc32b9facfe415be0dd8fb9288d7 

This change will ship with SDK 24.

**Comment by terribleben** [comment]
Shipped

**Comment by harrison0723** [comment]
Does SDK 24 intend to solve this issue with `replayAsync()`?  I still encounter this iOS bug, seemingly randomly 😕

**Comment by harrison0723** [comment]
Okay after long hours of debugging, my best guess is that I didn't `unloadAsync()` my audio files in `componentWillUnmount()` in react. It seems like the audio glitches only start happening after the 3+ load of the same component which plays the audio. 

Can anyone confirm this hypothesis? Is there memory leak if I don't `unloadAsync()` the audio files? How can I check?

**Comment by harrison0723** [comment]
In my specific case, it also seems like if I load one fewer audio file (~20kb), glitches never happen. The general audio responsiveness (by tap) is also faster. I couldn't reproduce the audio glitch on a snack for some reason though. That's why I thought it's a memory issue, as my app is fairly large.
