### ISSUE TITLE
expo-local-authentication : In android 9 bottom sheet is showing and in some devices a screen with pattern/password is showing.

### ISSUE THREAD

**Issue by RameshDev92** [expo/expo#9250]
## 🐛 Bug Report

###In Android version 9 if both patter/password and Finger print authentication is enabled then it is showing bottom sheet.In some devices it is showing a full screen with bio metric options.
Is it possible to show Full screen in all devices.

Is it possible to show the second image in the below images for all devices.

1.
![auth1](https://user-images.githubusercontent.com/47237110/87690758-78e59880-c7a7-11ea-8e64-ec50720a97d0.jpg)

2.
![auth2](https://user-images.githubusercontent.com/47237110/87690916-a3375600-c7a7-11ea-81a8-d32f246b1635.jpg)

**Comment by brentvatne** [comment]
as far as i know it depends on the ui that is provided by the vendor

**Comment by byCedric** [comment]
Hi @RameshDev92! Unfortunately, when Google created the new Biometric prompt, they decided that the UI for these screens shouldn't be handled by the developers or apps. Instead, they went for a vendor-specific implementation of the UI. You can [read more about that here](https://android-developers.googleblog.com/2019/10/one-biometric-api-over-all-android.html).

The different UI is probably caused by the AndroidX compatibility package. This is a package that allows us to use Biometric prompt in older Androids, using the UI Google made for this package. There is no way for us to always use the compatibility dialog or only show you the fullscreen window, it's different per vendor.

Hope it helps!
