### ISSUE TITLE
White Screen Appears Before Splash Screen on Android

### ISSUE THREAD

**Issue by superKalo** [expo/expo#9282]
### Summary of Issue 

With the following configuration in app.json:

```
    "updates": {
      "enabled": true,
      "fallbackToCacheTimeout": 45000
    },
```

When I start my standalone app on Android, white screen appears before the splash screen appear.

### Environment

Managed workflow. Android standalone build.

```
  Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
      Yarn: 1.22.4 - ~/.nvm/versions/node/v14.5.0/bin/yarn
      npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6514223
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: 38.0.8 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: 0.13.3 => 0.13.3
    npmGlobalPackages:
      expo-cli: 3.22.0
```

### Reproducible Demo

It happens on the blank project I just created with `expo init`.

It happens on the standalone Android app only.
 
### Steps to Reproduce

You can reproduce it with the blank expo project. Just add the following in the `app.json` and build a standalone Android app:

```
    "updates": {
      "enabled": true,
      "fallbackToCacheTimeout": 45000
    },
```

### Expected Behavior vs Actual Behavior

I expect the splash screen on Android to appear immediately when the app gets started. Like it does on iOS.

Or at least the initial white screen to respect the `backgroundColor` configured in my splash screen (in my case - 'red').

**Comment by karimcambridge** [comment]
Yea, why is this? I was to report this, it's been like this ever since I started expo on sdk 36, using 38 now.

**Comment by eduardoalba0** [comment]
Same here

**Comment by eduardoalba0** [comment]
Hello, I created a new expo project and realized that I had two package managers, yarn and npm. I deleted the npm .lock file and started using only the yarn manager and now the white screen is gone. Check if you have the same problem as me. Hope this helps.

**Comment by xdajay** [comment]
Same here, Just updated to SDK 38 from 37 and still having this issue on android.

**Comment by malhotradinesh07** [comment]
Having the same issue.

**Comment by martinezguillaume** [comment]
Native resize mode is what you are looking for: https://github.com/expo/expo/tree/master/packages/expo-splash-screen#native-resize-mode

**Comment by divonelnc** [comment]
@martinezguillaume I can't find a way to use that in a non-ejected app in the documentation. Do you have any pointers?

**Comment by martinezguillaume** [comment]
Oh sorry ! It’s only available for bare workflow for now ...

**Comment by xdajay** [comment]
did anyone check with SDK 39?

**Comment by superKalo** [comment]
I just tested this one with SDK v39. The issue is still there.

**Comment by mrs2296** [comment]
Because Android intends the splash screen to be rendered as the window background, there is a moment before the SplashScreenView can be rendered where this background is visible.  If you are using this library in the bare workflow then you can ameliorate this issue by double checking that you have adjusted the splashscreen_background color in colors.xml to match that of the splash screen image.

```xml
<resources>
  <color name="splashscreen_background">#(AA)RRGGBB</color> <!-- #AARRGGBB or #RRGGBB format -->
</resources>
```
Alternatively, if you have a splashscreen.xml containing only a drawable for the background color then you can set the color directly in styles.xml instead.

```diff
 <style name="Theme.App.SplashScreen" parent="Theme.AppCompat.Light.NoActionBar">
   <!-- Below line is handled by '@expo/configure-splash-screen' command and it's discouraged to modify it manually -->
   <!-- Customize your splash screen theme here -->
-  <item name="android:windowBackground">@drawable/splashscreen</item>
+  <item name="android:windowBackground">@color/splashscreen_background</item>
 </style>
```
However, I have found the best solution to be native, and by native, I mean without Expo Splash Screen.  Issue #7505 describes the jittery resizing of the splash screen image when using the NATIVE render mode, and this results from a similar discrepancy between the window background and the image view that causes the white background with other render modes.  Specifically, the window background occupies the entire screen (behind the status and navigation bars) whereas the SplashScreenView is bounded on the bottom by the navigation bar.  Thus, when the SplashScreenView is rendered, occluding the window background, any relatively positioned items in the drawable will be shifted slightly higher than those of the background.  So by eliminating Splash Screen altogether and rendering null from your entry component until loading has finished (rendering nothing until where you would normally call hideAsync works because Android views have a transparent background by default), you can circumvent these issues and eliminate the need for the library on Android.

The README states the following regarding this issue, yet #7505 has not had any activity since it was opened in May.
> We are aware of this issue and unfortunately haven't been able to provide a solution as of yet. This is on our immediate roadmap...
So I imagine that there has not been enough time to look at some of these issues with the splash screen.  As for standalone, I also encountered this, the white background flashing, issue, and can only assume, having limited experience using the Expo managed build servers, that the backgroundColor property from the manifest is not making it through the transformation to the xml files?

**Comment by senthil-zappz** [comment]
its default behaviour of the android app loading process. but it can be disabled by adding this in the styles.xml
	<item name="android:windowDisablePreview">true</item>
it works. when the white screen comes before the splash, the loading will be immediate, now it takes a fraction of time to bring the app up, after adding this into styles.xml without white screen.

**Comment by nithishpk** [comment]
having the same issue with expo.
