### ISSUE TITLE
playSoundOnCapture false not working on video recording

### ISSUE THREAD

**Issue by kevinrichard31** [expo/expo#9353]
I seen many people where playSoundOnCapture={false} not working. im facing the same issue with french Android phone on react Native 0.62.1. Im using camera 1 api, not the camera2api

I don't have shutter sound on instagram/fb or native camera app. Come from france, we don't have those restrictions.
I don't have shutter sound on takePictureAsync(), but I have the audio effect on recordAsync() and stopRecording() 

So if someone could fix this issue...

thanks

**Comment by cruzach** [comment]
@kevinrichard31 are you using the `expo-camera` module? `playSoundOnCapture` isn't an available prop for `Camera`, so I'm guessing you're using RNCamera? https://react-native-community.github.io/react-native-camera/docs/rncamera. Closing since this doesn't seem to be the right place for the issue, unless I'm mistaken (if I am, please provide all the info we ask for in the bug report template so I can better understand the issue 😄 )

**Comment by kamarajcalm** [comment]
how to disable shutter sound on expo camera
