### ISSUE TITLE
After Build APK cannot get Notifications.getExpoPushTokenAsync => token [SDK expo versvion 38]

### ISSUE THREAD

**Issue by gotzillas** [expo/expo#9378]
After Build APK cannot get Notifications.getExpoPushTokenAsync => token [SDK expo versvion 38]
Error message => Fetching the token failed: Given String is emply or null

**Comment by cruzach** [comment]
Hi, we need you to follow the issue template in order for us to help you, since it asks for all the info we need to begin debugging. 

Your error message indicates you may not have set up FCM yet, ([similar to this issue](https://github.com/expo/expo/issues/9347)), so I recommend double-checking that you've followed [this guide](https://docs.expo.io/push-notifications/using-fcm/). If you have, please provide a reproducible demo and we can investigate, thanks!
