### ISSUE TITLE
Getting error when submitted app in apple app store.

### ISSUE THREAD

**Issue by mehtaanshul** [expo/expo#948]
I am not getting any error when i test my app (in iOS devices) using expo both in development mode and without development mode but when i submitted my app in apple app store they sent the following  screenshot .
![photo_2017-11-08_19-35-35](https://user-images.githubusercontent.com/17105835/32677500-a86804ca-c684-11e7-944f-72b3b5029144.jpg)

**Comment by brentvatne** [comment]
hi there! this problem is due to some upstream react-native changes that only occur when development mode is disabled.

you can disable development mode in xde, then reopen the app and notice you will have the error. follow the instructions from the release notes: https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6 -- screenshotted for you below:

<img width="739" alt="screen shot 2017-11-10 at 12 36 45 pm" src="https://user-images.githubusercontent.com/90494/32677619-f56f3ade-c613-11e7-94b5-bbf680f8c0d9.png">

the error might not be due to you using `View.propTypes.style` in your code, but in a library that you depend on! so search in node_modules for that code as well, and update those libraries that use it

**Comment by mehtaanshul** [comment]
I have tested the app by disabling the development mode and i am not getting any errors.But still Apple sent me that screenshot when i submitted the app in app store.

**Comment by brentvatne** [comment]
@mehtaanshul - can you join slack and dm me? i'm brent on slack.expo.io -- easier to take this into a conversation there and then i can post result of our conversation here

**Comment by mehtaanshul** [comment]
ok
