### ISSUE TITLE
Error: Unable to resolve module `./node_modules\expo\AppEntry` from ``: 

### ISSUE THREAD

**Issue by Hiti3** [expo/expo#9487]
I will not rewrite what was allready written and closed and accepted like it works because it does not...

MORE INFO: https://github.com/expo/expo/issues/5069

**Comment by byCedric** [comment]
Hi @Hiti3, thanks for the heads up. AFAIK, this is [fixed with method Evan mentioned](https://github.com/expo/expo/issues/5069#issuecomment-539761295). If that doesn't work for you, please open a new issue providing the information we ask in the issue template. Without that, we have no way to help you find the issue.

Hope it helps!
