### ISSUE TITLE
[docs] Error 400 on sign in on IOS 

### ISSUE THREAD

**Issue by basicvisual** [expo/expo#9498]
The documentation doesnt work for IOS ? In android it works quite fine . 
Using it inside of the Expo app
https://docs.expo.io/versions/latest/sdk/google/ 

sdk 38.0.2 
Error caption 
![image](https://user-images.githubusercontent.com/48718797/88938819-1354da00-d286-11ea-83ed-a3c26271a528.png)
warning caption `Deprecated: Native Google Sign-In has been moved to Expo.GoogleSignIn ('expo-google-sign-in') Falling back to `web` behavior. `behavior` deprecated in SDK 34`

**Comment by byCedric** [comment]
Hi @basicvisual, I'm not 100% sure what's going on here. I need to know the information we ask in the issue form, else we can't to a lot.

- Have you followed the [steps from the docs](https://docs.expo.io/versions/latest/sdk/google/#using-it-inside-of-the-expo-app)?
- If you see that message, you probably need to use `expo-google-sign-in` package instead of `import { GoogleSignIn } from 'expo';`. 

If you think this is an issue on our end, please open a new issue with the information filled in from the template. (e.g. repro, environment info, steps to reproduce).

Hope it helps!

**Comment by basicvisual** [comment]
@byCedric i have followed the documentation . and the code snippet i am following is as follows  
It also gives out a warning 
`
Deprecated: Native Google Sign-In has been moved to Expo.GoogleSignIn ('expo-google-sign-in') Falling back to `web` behavior. `behavior` deprecated in SDK 34 ` even if i have the package installed. 


```
import { StyleSheet,Text,View,ActivityIndicator,Button} from 'react-native';
import React, { Component } from 'react';
import EditScreenInfo from '../components/EditScreenInfo';
import * as Google from 'expo-google-app-auth';
class LoginScreen extends Component{
  //Google authentication 
  signInWithGoogleAsync = async()=> {
    try {
      const result = await Google.logInAsync({
        androidClientId: '',
        behavior: 'web',
        iosClientId:'', //YOUR_IOS_CLIENT_ID_HERE
        scopes: ['profile', 'email'],
      });
  
      if (result.type === 'success') {
        return result.accessToken;
      } else {
        return { cancelled: true };
      }
    } catch (e) {
      return { error: true };
    }
  };

  render (){
    return ( <View style = {styles.container}>
      <Button title = 'Sign with google' 
      onPress={()=>this.signInWithGoogleAsync()}/>
    </View>
    );
  }
}
export default LoginScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  } 
});
```
