### ISSUE TITLE
Android: Exception occurs when playing video

### ISSUE THREAD

**Issue by trungtrungkang** [expo/expo#951]
Hi,
Out client did reports a lot of issue about NullPointerException and OutOfMemory:
<img width="964" alt="screen shot 2017-11-11 at 10 17 39 am" src="https://user-images.githubusercontent.com/57247/32685747-f401e6c2-c6c9-11e7-8b3b-8c8222308258.png">
<img width="961" alt="screen shot 2017-11-11 at 10 18 42 am" src="https://user-images.githubusercontent.com/57247/32685749-f58319e4-c6c9-11e7-9dab-ef236f6251bc.png">

Whether they are Expo bugs or not?

**Comment by jimmylee** [comment]
Hey @trungtrungkang thank you for reporting this, I've assigned @jesseruder who is our internal expert on Android related issues at the moment to take a look at this and get back to you.

**Comment by phtoussaint** [comment]
Hi! 

we are also encountering the same nullpointerexception issue. It happens from time to time and makes our expo app crash.

**Comment by sjchmiela** [comment]
Hi, guys! Thanks for the report.

`NullPointerException` bug has recently been fixed in https://github.com/expo/expo/commit/f12f25f4740c2c9453e46328ebe8b47f2a5049af. 🎊  The fix will be released in SDK 24 soon.

When it comes to `OutOfMemoryError` I could not replicate it (I played a sound in a loop for 10 minutes with 100 ms update interval, the memory used by the application varied between 78 and 90 MBs).

In what circumstances does the memory exception error occur?

**Comment by sjchmiela** [comment]
I'll close this (I believe the issue may have been resolved) for now, feel free to reopen this if the problem occurs again!
