### ISSUE TITLE
Expo android api target level 28 change to 29

### ISSUE THREAD

**Issue by AbdnhVmpr** [expo/expo#9536]
I am using expo version 38\. I built an standalone app to be uploaded on play store. When I tried uploading the apk file. I got the error:

**expo your app currently targets api level 28 and must target at least api level 29**

How can I solve this problem?

**Comment by k3rn31p4nic** [comment]
Since Aug 3rd, it's mandatory to target API level 29. Currently, expo's targets API level 28. This is already known and a PR is already in progress https://github.com/expo/expo/pull/9446.

As per [this comment](https://github.com/expo/expo/issues/9531#issuecomment-668119333), the builders should be updated by this week. We've to wait until they are updated.

**Comment by cruzach** [comment]
Hi, this update was deployed to the SDK 38 Android builders just now (August 5th, 14:38 UTC). Any apps built with `expo build:android` on SDK 38 after that time will be targeting Android API 29, or if you use `turtle-cli` you will need to upgrade to `turtle-cli@0.17.1` and then rebuild. Thanks for your patience!
