### ISSUE TITLE
Notifications.getExpoPushTokenAsync() never resolves (Android Only)

### ISSUE THREAD

**Issue by ewein** [expo/expo#9551]
### Summary of Issue 
The Expo method **Notifications.getExpoPushTokenAsync(**) never resolves and just hangs. However, this is only on Android, it works as expected on iOS. Using Expo Client. 

"expo": "^38.0.0",
"expo-notifications": "~0.3.3"
**useNextNotificationApi: true** is set in app.json

### Expected Behavior
I expect the promise from **Notifications.getExpoPushTokenAsync()** to resolve and return the pushToken under the data parameter.

**Comment by barthap** [comment]
1. Are you using Expo client, or bare workflow?
2. Which notification API you use? New or Legacy? If new, did you set `useNextNotificationApi: true` in `app.json`?
3. If you are using the new API, try to console log result of `await Notifications.getDevicePushTokenAsync()` - does it hang too?

**Comment by ewein** [comment]
I have updated the post with the data you requested. The call never resolves so nothing prints out when I try to console.log.

**Comment by mvorst** [comment]
I'm having the same issue when I build and deploy the APK on Android. It works perfectly fine when running on Android within the expo client. In my case it could be a signing problem so this may be a coincidence, but the symptom it the same.

I've set useNextNotificationApi: true

"expo": "~38.0.8"
"expo-notifications": "~0.3.3"

In my case I log to my server since I'm deploying the APK. It logs correctly when I run it within the expo client, but fails to log after Notifications.getExpoPushTokenAsync after deploying the APK.

**Comment by ewein** [comment]
> I'm having the same issue when I build and deploy the APK on Android. It works perfectly fine when running on Android within the expo client. In my case it could be a signing problem so this may be a coincidence, but the symptom it the same.
> 
> I've set useNextNotificationApi: true
> 
> "expo": "~38.0.8"
> "expo-notifications": "~0.3.3"
> 
> In my case I log to my server since I'm deploying the APK. It logs correctly when I run it within the expo client, but fails to log after Notifications.getExpoPushTokenAsync after deploying the APK.

This is exactly what I am experiencing as well.

**Comment by mvorst** [comment]
After adding more logging I discovered that my app.json was missing the link to the google-services.json file.

You might want to verify that you have googleServicesFile set properly.

**Comment by barthap** [comment]
`google-services.json` is used only in bare workflow. Expo client uses its own Google config.

**Comment by mvorst** [comment]
> `google-services.json` is used only in bare workflow and when building APK. Expo client uses its own Google config.

That explains why it worked until I built the APK.

**Comment by RuchitMicro** [comment]
I am facing the same issue when I build my apk I never get my expo push token. In SDKVersion 36 I never had to upload and google-services.json files from fcm nor do I want to use Google's Firebase to send a notification. I want to use expo services to send notifications to my app users.

**Comment by RuchitMicro** [comment]
I was using SDK version 36 and faced no problem, I never had to do the google-service.json thing. Later today while uploading the app I found that play store has an API level error and I have to revert SDK version 38 where this notification is a persisting issue.

Can anybody please explain me how the push notifications work.
I learned that expo push notifications allows easy setup to send push notifications in standalone APKs & IOS apps but all I am doing is scrapping solution to what I am doing wrong.

**Comment by AdamJNavarro** [comment]
Hey @RuchitMicro,

Once GCM was shut down, we switched over to FCM behind-the-scenes which is why you need to configure your standalone app to have FCM credentials. You don't have to do anything code-specific with firebase/fcm. You'll continue to use Expo's notif module and service as you were.

If you configure FCM and still run into an issue, please feel free to open a new issue and we can investigate.

Cheers,
Adam
