### ISSUE TITLE
[SDK 38] How to create weekly, monthly, yearly,... notifications in both android and iOS

### ISSUE THREAD

**Issue by minhdang-idev** [expo/expo#9584]
In the documentation of SDK 37, Expo supports scheduleLocalNotificationAsync function which allows me to create monthly and yearly repeat notifications:
```

schedulingOptions (object) --
An object that describes when the notification should fire.

time (date or number) -- A Date object representing when to fire the notification or a number in Unix epoch time. Example: (new Date()).getTime() + 1000 is one second from now.
repeat (optional) (string) -- 'minute', 'hour', 'day', 'week', 'month', or 'year'.
```

But in the documentation of SDK 38, there is no longer scheduleLocalNotificationAsync. scheduleNotificationAsync is added as a replacement. But the documentation doesn't mention how to schedule weekly, monthly and yearly. The parameter NotificationTriggerInput includes CalendarTriggerInput but it's for iOS only:

```export type NotificationTriggerInput =
  | null
  | DateTriggerInput
  | TimeIntervalTriggerInput
  | DailyTriggerInput
  | CalendarTriggerInput;
```
Meanwhile, DailyNotificationTrigger includes type: 'daily'; I am wondering if this "type" parameter also supports "monthly", "weekly", "yearly"? I can't find in the documentation to clarify that.

```
export interface DailyNotificationTrigger {
  type: 'daily';
  hour: number;
  minute: number;
}
```

So if type supports "daily", "weekly", "monthly", "yearly", should they also be added to the documentation? In that case, to make weekly/monthly/yearly notifications, I may use CalendarTriggerInput for iOS app and DailyNotificationTrigger for android, is that correct?

Thank you in advance!

**Comment by sjchmiela** [comment]
Hey, in order to make the module simple from the beginning and bug-free we didn't add support for all period-based notifications. In the old version of the API yearly notifications were implemented as "with time interval equal to 365 days"

https://github.com/expo/expo/blob/db1369230ddf17b020d46367bec30905547a22a5/android/expoview/src/main/java/host/exp/exponent/notifications/NotificationHelper.java#L619-L621

which could be a problem for leap years.

`DailyTrigger` was added by ~thorbenprimke in https://github.com/expo/expo/pull/8199 — if you want, you could submit another PR adding more period-based triggers. You could also schedule notifications with long time intervals, if you want. 🙂

**Comment by sjchmiela** [comment]
I'll let myself close this issue. We may add more interval-based notification triggers as the time passes, but it is not the top priority right now. If anyone would like to add more of these triggers there are two pull requests that serve solely this purpose: #8199 and #9973 you could base your work on. Until then please add feature request to https://expo.canny.io. We'll get to it in the future!
