### ISSUE TITLE
Expo Push Notifications not working (after expo build:android)

### ISSUE THREAD

**Issue by RuchitMicro** [expo/expo#9623]
> ### Short story
> 
> Hey all, I think I have found the solution to this problem. We will try to resolve the problem ASAP.
> 
> ### Long story
> 
> We use Firebase as the notifications backend, which publishes its own native libraries that help developers use the service. For SDK37 we have upgraded those dependencies (regular thing), but in the throes of the release we haven't taken the time to read the CHANGELOGs from cover to cover.
> 
> The `com.google.firebase:firebase-messaging:20.1.2` with which SDK37 has shipped (so Expo client 2.15.0 too) has introduced a change, which we didn't account for — it uses another native library, Firebase Installations SDK to identify devices. In most scenarios this isn't a problem, but in our case, in which the API key is restricted to only the services we know should be allowed, [it may break Firebase Cloud Messaging](https://firebase.google.com/support/release-notes/android#2020-02-27), which, unfortunately, it did.
> 
> To mitigate this we will either downgrade the library to `20.1.0` (I have confirmed it fixes the issue) and release an updated version of Expo client or update the project's configuration and hope it fixes the problem over the air.
> 
> Resources:
> - https://stackoverflow.com/a/58496014/1123156
> - https://stackoverflow.com/a/60565682/1123156
> - https://stackoverflow.com/a/60698697/1123156
> - https://firebase.google.com/support/release-notes/android#2020-02-27
> 
> _Originally posted by @sjchmiela in https://github.com/expo/expo/issues/7606#issuecomment-608446477_

**Comment by RuchitMicro** [comment]
Is this fixed yet?
I am facing the same sort of issue in the new [expo-notifications](https://docs.expo.io/versions/v38.0.0/sdk/notifications/)

**Comment by RuchitMicro** [comment]
I have found out that what I am looking for is answered but I am not satisfied with what it has offered. According to [this link](https://github.com/expo/expo/issues/7727#issuecomment-616674874) I have to now do an extra step of creating FCM projects and get their respective `google-services.json` files for my builds (expo build:android) which previously I never had to do (SDK Version 36). Please mention this in docs if this is a new compulsory step. Honestly, the docs are confusing as there are 2 links floating everywhere without any context of the new expo-notification and legacy expo notifications.

**Comment by byCedric** [comment]
Hi @RuchitMicro, I'm sorry to hear about your issues and discontent with Expo's push notifications on Android. I fully agree that we didn't communicate perfectly around the GCM/FCM issue we had in the past. This is something we try to improve in the future, so thanks for mentioning this.

As for the FCM setup, we do have an extensive guide to setting up the Push Notifications. Did you find these as well? If so, was there anything unclear? If not, where did you look (so we can make it more visible as well)?

- [General setup guide](https://docs.expo.io/push-notifications/push-notifications-setup/)
- [FCM specific setup guide](https://docs.expo.io/push-notifications/using-fcm/)

Again, sorry for your trouble and I hope we can take any frustration away in the future. I assume your issue was fixed, so I'll close this one. If you still have trouble, feel free to reply.

**Comment by IvanVelazquezz98** [comment]
Hola, tengo una duda, si o si necesito utilizar FireBase para que funcione la obtencion del token en mi proyecto? en emulador y expo go funciona pero en apk no.
