### ISSUE TITLE
Auth session returns dismiss before browser closes

### ISSUE THREAD

**Issue by SimenBakken** [expo/expo#9677]
### Summary of Issue 
When using "useAuthRequest()", the response is of type: "dismiss" even before the browser window closes when the flow is completed. This only happens with standalone build for android, both expo environment and iOS works perfectly. I have tried all fixes in the related issue #6679, and we would like to not use proxy, so startAsync() wont work.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

- Only on android in standalone release mode
- Both in simulator, on device and trough play store internal testing

Expo CLI 3.23.3 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~38.0.8 => 38.0.9
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

### Reproducible Demo

 
Link to code that reproduces the issue: https://snack.expo.io/@simenbakken/auth-session-bug

### Steps to Reproduce
- Create a new managed project 
- Implement auth session from tutorial for Azure: https://docs.expo.io/guides/authentication/#azure

### Expected Behavior vs Actual Behavior
Expected:
Browser opens on login button press and user enters credentials. When login flow is completed, the browser closes, and the text field is updated with response from Azure.

Actual:
Browser opens on login button press and user enters credential. When login flow is completed, the browser closes, and the text field is always {"type":"dismiss"} even if login is successful (only and android as discussed above, iOS and expo dev works as expected). It seams like dismissed is returned even before browser is opened, as sometimes if i create an Alert.alert() after await promptAsync(), i can catch a glimt of the alert as the browser opens.

**Comment by Reverendheat** [comment]
Been having this same issue as with a new project.. just commenting for visibility.

**Comment by brentvatne** [comment]
can either of you provide a reproducible example that we can just run without needing to sign up with some oauth provider?

**Comment by Reverendheat** [comment]
I'm not sure of a good way to replicate without getting a trial license at least with Azure or some other OAuth provider.

**Comment by brentvatne** [comment]
another oauth provider where you can share the credentials would be helpful

**Comment by SimenBakken** [comment]
Okay so I have completed some extensive testing, and it looks like the problem only occurs if the redirectUrl object in the snack above contains capital letters. As long as all letters in redirectUrl are lower case everything seams to work as expected. So to sum up:

- redirectUrl: "testapp://LoginStack" always returns dismissed
- redirectUrl: "testapp://loginstack" works as expected

**Comment by Reverendheat** [comment]
Ahh mine must be a different issue, currently all lowercase. Glad yours is working!

**Comment by JustinLawrenceMS** [comment]
I am having the same problem as well.  My redirectUrl doesn't have capital letters but it does have hyphens and underscores.  I am using a redirectUrl that is generated by AuthSession::getRedirectUrl.  It's strange because the problem is intermittent.  Works fine on Apple products.  Only Android is affected.  

The problem appears identical to this:  https://github.com/expo/expo/issues/6679

But the solutions from that thread aren't working for me either.

I suppose I could custom generate a redirectUrl without underscores or hyphens, but without create a new account and redeploying my app, I'm not sure how.  Let me try that.

**Comment by rikkitissier** [comment]
Also having the same issue, though I'm using `WebBrowser.openAuthSessionAsync`. Works everywhere except the production Android. None of the existing workarounds/suggested fixes have worked thus far.

**Comment by rikkitissier** [comment]
I believe I have discovered the cause of the error in my case.

I was using `Linking.makeUrl('/auth')` (note slash), which in the expo environment results in a URL like `exp://0.0.0.0/--/auth`. In production it results in `myscheme:///auth (note three slashes). This works fine on iOS but it didn't occur to me that it could be the cause of the problem outlined above.

Changing the call to `Linking.makeUrl('auth')` (no slash) and rebuilding the app seems to have solved it.

**Comment by JustinLawrenceMS** [comment]
Changing the returnUrl to all lowercase alphabetic characters had no effect.  Android is still broken for me.

**Comment by JustinLawrenceMS** [comment]
Calling the handler inside the contructor method fixed it for me.  Not a bug in my case, and it's well documented, if a bit out of the way and tldr;

https://reactjs.org/docs/react-component.html

**Comment by rikkitissier** [comment]
Apparently I jumped the gun with my previous reply saying I had fixed it. No matter what I try, `Linking.makeUrl('auth')` (no slash) is returning a URL with three slashes in production, e.g. `myscheme:///auth`. This continues to work fine on iOS, but continues to fail on Android.

I have resorted to this approach - it may not be bulletproof but I cannot ship an app with broken auth :D

```
let schemeUrl = Linking.makeUrl(`auth`); // To ensure expo builds the URL for me in dev mode
if (!__DEV__) {
	schemeUrl = `${Expo.Constants.manifest.scheme}://auth`; // To ensure production URL is correct
}```

**Comment by JustinLawrenceMS** [comment]
Are you implementing react component class?

**Comment by rikkitissier** [comment]
I do although my auth happens in a redux action function.

**Comment by SimenBakken** [comment]
@rikkitissier I had the same issue with the three slashes. Forgot to mention this in my original fix. I implemented a helper function to create all deep links to out app (we have a lot of different liks), witch forces lowercase and replaces the three slashes with double slash.

`export const DeepLink = (path) => {
  const url = Linking.makeUrl(path).replace("///", "//").toLowerCase();
  return url;
};`

**Comment by rikkitissier** [comment]
Thanks for the confirmation @SimenBakken. Your fix is probably more future-proof than mine, so I'll switch over. Thanks!

**Comment by jfbn** [comment]
I too am experiencing this issue.
I don't have uppercase letters in the redirect uri, and I don't have 3 slashes in a row.

It works on iOS but on Android it doesn't work in emulator or in production.

**Comment by sealabcore** [comment]
We are also experiencing this issue.
* The oAuth flow works on iOS simulator, Android Emulator, iOS production and iOS and Android in the expo client.
* The oAuth flow doesn't work on Android production physical devices.

We tried everything in https://github.com/expo/expo/issues/6679 and everything in this issue as well. 

Has anybody had any other luck on different fixes for this? Here's our code snippet. It returns `type: dismiss` from `promptAsync()`. Opens the Android browser and immediately closes.
```
const discovery = authSessionDiscovery(newUser);
const request = await loadAsync(authSessionConfig(), discovery);
const response = await request.promptAsync(discovery, { useProxy: false });
```

**Comment by sealabcore** [comment]
Spent a bit more time with this and I was able to fix the issue we were having.

Turns out Android production builds require something to be after the custom scheme. For example, `app-name://` will not work in production Android builds, but `app-name://auth` will work.

Though, the caveat is that you have to also fix the additional bug in the expo library that was adding an extra `/` that was causing issues changing the redirect url to be `app-name:///auth` so the fix was to add `auth` to the redirect url, AND to remove the extra slash that the expo library adds.

Broken code:
`const redirectURL = Linking.makeUrl();`

And, this was our fix:
`const redirectURL = Linking.makeUrl('auth').replace('///', '//');`

Thanks @SimenBakken and @rikkitissier !

**Comment by jfbn** [comment]
Issue still persists. On Android emulator AND physical device, openAuthSessionAsync resolves with {type: "dismiss"} right away.

**Comment by MrPumpking** [comment]
I've been struggling with this too. From what I've found, the `redirectUri` scheme [has to match your Android package](https://developers.google.com/identity/protocols/oauth2/native-app#step-2:-send-a-request-to-googles-oauth-2.0-server) (ex. for package name `com.example` the redirectUri would be `com.example:/oauthredirect`). After making my `scheme` key match the Android package, I was able to sign in successfully, but there was another problem. After successful login I was prompted to select the app I'd like to continue with, and there were 2 options available - both being my app, with the difference that only one works. Not sure how to get around this one, so I guess I'll be switching to `expo-google-app-auth` for the time being.

**Comment by Jamedjo** [comment]
Could it be the link is handled by `<activity name="net.openid.appauth.RedirectUriReceiverActivity">` instead of by `Linking.addEventListener('url', _redirectHandler)`?

For me it turned out that `dismiss` wasn't really being returned straight away, just appeared so because switching back to the app with the sign in window open in chrome causes a AppState transition and this gets picked up by `_onAppStateChangeAndroid` causing `Promise.race([ openBrowserAsync(startUrl, browserParams), _waitForRedirectAsync(returnUrl), ])` to return early. This was because expo doesn't have a way to detect Android dismiss, so treats returning to an active state without getting a redirect as a `{ type: 'dismiss' }`.

The real problem was that the ` _redirectHandler` in `_waitForRedirectAsync(returnUrl)` is never getting called. Similarly if I add my own `Linking.addEventListener('url', f)` and `Linking.getInitialURL().then(f)` calls I don't get notified of `com.me.myapp://` style links but do for `myapp://` links. Both open the app to the current page, with only the later being routed via react-navigation.

I found this by playing around in `node_modules/expo-web-browser/build/WebBrowser.js` with Sentry tracing, since I wasn't sure how to otherwise debug the native build:

```
import * as Sentry from 'sentry-expo';
function SentryLog(message, variables) {
  Sentry.Native.withScope(function(scope) {
    scope.setContext('variables', variables);
    Sentry.Native.captureMessage(message);
  });
}
```

**Comment by Jamedjo** [comment]
> After making my scheme key match the Android package, I was able to sign in successfully, but there was another problem. After successful login I was prompted to select the app with which I'd like to continue with, and there were 2 options available - both being my app, with the difference being that only one works. 

I get similar behaviour when setting scheme to match `com.org.myapp`:

* An app chooser presents my app twice
* Clicking one of them causes `expo-web-browser`'s `_redirectHandler` to be called and hits react-navigation. Skipping react-navigation from `getStateFromPath` allows sign in to proceed correctly.
* Clicking the other re-opens the app without hitting any `Linking.addEventListener('url', ...)` calls, suggesting it might be being processed by `net.openid.appauth.RedirectUriReceiverActivity` instead.

**Comment by Jamedjo** [comment]
> can either of you provide a reproducible example that we can just run without needing to sign up with some oauth provider?

@brentvatne I've produced a more minimal example of this bug as I experience it: 

1.  Download https://snack.expo.io/@jamedjo/auth-session-deep-linking-bug as a zip
2. Build with `expo build:android --type apk` and run on an android device
3. Click URLs from https://codepen.io/jamedjo/pen/JjbJdxZ to simulate a redirect to `com.example.authsessionbug://oauthredirect`.

That style of scheme is hardcoded in [Google.useAuthRequest](https://github.com/expo/expo/blob/6ded8414295317864ff15cdf95fac81decaf0dc3/packages/expo-auth-session/src/providers/Google.ts#L276), but fails to trigger the `Linking.addEventListener('url', ...)` listener set at [WebBrowser.ts#_waitForRedirectAsync](https://github.com/expo/expo/blob/6ded8414295317864ff15cdf95fac81decaf0dc3/packages/expo-web-browser/src/WebBrowser.ts#L292).

**Comment by Jamedjo** [comment]
@EvanBacon Would it make sense to add a second `intent-filter` to the manifest, or is sharing the `net.openid.appauth.RedirectUriReceiverActivity` intent intentional?

I was able to get this to work by fixing the conflict with `net.openid.appauth.RedirectUriReceiverActivity` in the manifest via [apktool](https://ibotpeaches.github.io/Apktool/).

First I replaced `<data android:path="oauthredirect" android:scheme="com.my.app"/>` with `<data android:host="*" android:path="/oauthredirect" android:scheme="com.my.app"/>`, because the it looks like the [path is ignored if host is not defined and path must start with a `/`](https://developer.android.com/guide/components/intents-filters#DataTest). This allows a second intent to handle `com.my.app` alongside the existing `openid` one.

Next I added a new intent filter under the `host.exp.exponent.MainActivity` activity:

```xml
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:host="*" android:path="/expo_oauthredirect" android:scheme="com.my.app"/>
            </intent-filter>
```
Lastly I used `patch-package` to update `node_modules/expo-auth-session/build/providers/Google.js` to match the new intent with `///` to send `expo_oauthredirect` as a path instead of a host/authority:

```patch
diff --git a/node_modules/expo-auth-session/build/providers/Google.js b/node_modules/expo-auth-session/build/providers/Google.js
index 9cac987..6fba1b4 100644
--- a/node_modules/expo-auth-session/build/providers/Google.js
+++ b/node_modules/expo-auth-session/build/providers/Google.js
@@ -145,7 +145,7 @@ export function useAuthRequest(config = {}, redirectUriOptions = {}) {
             return config.redirectUri;
         }
         return makeRedirectUri({
-            native: `${Application.applicationId}:/oauthredirect`,
+            native: `${Application.applicationId}:///expo_oauthredirect`,
             useProxy,
             ...redirectUriOptions,
         });
```

To update the apk:
```bash
apktool decode myapp-original.apk
vim myapp-original/AndroidManifest.xml
apktool build myapp-original -o myapp.apk
expo credentials:manager -p android
/path/toAndroid/Sdk/build-tools/$VERSION/apksigner sign -ks @username__myapp.bak.jks myapp.apk
/Android/Sdk/platform-tools/adb install myapp.apk
```

To test the intent-filters in the manifest:
```bash
adb shell pm resolve-activity --components 'com.my.app:///expo_oauthredirect'
```

**Comment by alexanderwanyoike** [comment]
I realised that I was getting this specific issue when I used `useAuthRequest` in order to faciliate the authentication mechanism. I replaced this implementation with much simpler implementation that uses `AuthSession.startAsync`. More information about it [here](https://docs.expo.io/versions/latest/sdk/auth-session/#authsessionstartasyncoptions). My use case is for stripe connect authorization and it seemed to work on Android. Im yet to test this implementation on iOS but im confident about the implementation. You will have to ensure that the return url scheme is configured on your application. I reckon setting that up should be straight for and is described [here](https://docs.expo.io/versions/latest/sdk/auth-session/#installation). I really think this issue might be with the `useAuthRequest` hook.

```typescript
 const connect = async () => {
        const response = await AuthSession.startAsync({
            authUrl: discovery.authorizationEndpoint,
            returnUrl: "com.example://test.com"
        });

        if (response.type === "success") {
            const {code} = response.params;
            authorizeStripe({code});
        }
 }
```

**Comment by abdulrahman18** [comment]
> Okay so I have completed some extensive testing, and it looks like the problem only occurs if the redirectUrl object in the snack above contains capital letters. As long as all letters in redirectUrl are lower case everything seams to work as expected. So to sum up:
> 
> * redirectUrl: "testapp://LoginStack" always returns dismissed
> * redirectUrl: "testapp://loginstack" works as expected
> 
> @Reverendheat Hope this fixes the issue your having as well.

Thanks @Reverendheat now It's working fine on my android device.

**Comment by thomas-coldwell** [comment]
Hi folks this seemed to work for me - https://github.com/expo/expo/issues/10860#issuecomment-841144525

**Comment by tlmader** [comment]
Workaround for Android Expo Standalone + Cognito User Pools + Amplify using @thomas-coldwell 's approach here: https://github.com/expo/expo/issues/10860#issuecomment-917732407
