### ISSUE TITLE
iOS 13 freezes for 5-10 seconds when return from background

### ISSUE THREAD

**Issue by hufftheweevil** [expo/expo#9689]
### Summary of Issue
When the app moves from `background` to `active`, the app loads onto the screen, but the UI is non-responsive. All attempts to use the interactive parts of the UI are ignored. After between 5-10 seconds, the UI becomes responsive again.

It appears that this bug only occurs on iOS 13, and perhaps only on the iPhone XR. It does not occur on many other iOS devices tested. And it does not occur on Android.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

- Expo CLI 3.23.3 environment info:
    - System:
      - OS: Windows 10 10.0.18363
    - Binaries:
      - Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
      - npm: 6.14.3 - C:\Program Files\nodejs\npm.CMD
    - IDEs:
      - Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
    - npmPackages:
      - expo: ^38.0.0 => 38.0.9
      - react: 16.11.0 => 16.11.0
      - react-dom: 16.11.0 => 16.11.0
      - react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      - react-native-web: ~0.11.7 => 0.11.7

Platform: iOS 13.6 (17G68) on iPhone XR

### Reproducible Demo
 
See steps below.

### Steps to Reproduce

Run `expo init`
Edit the `App.js` to include any interactive element (such as a `<Button/>`)
Run `npm start` and open the app on an iPhone XR with iOS 13.6
Switch to another application
Switch back to the App and attempt to use the interactive UI element

### Expected Behavior vs Actual Behavior

After switching from `background` to `active`....
Expected: The app should be interactive as soon as the app is active.
Actual: The app is not interactive for several seconds.

**Comment by brentvatne** [comment]
are you using debugging in chrome?

**Comment by hufftheweevil** [comment]
I don't understand - why would I be using Chrome? Do you mean for the Expo Developer Tools?

**Comment by brentvatne** [comment]
i'm referring to this: https://docs.expo.io/workflow/debugging/#remote-debugging-with-chrome-developer-tools

**Comment by hufftheweevil** [comment]
Oh, that is something new to me - I've never tried it. I will try it first thing tomorrow and see if I have any further information to share.

**Comment by brentvatne** [comment]
interesting, i was thinking if it was enabled then it may cause this issue.

the behavior you describe doesn't happen on a new app, i think it must be related to some code in your app if it's not being caused by debugging. if you can share an app on github where this happens, i'd be happy to look into it.

**Comment by hufftheweevil** [comment]
It occurs for me on a brand new app. Here is a repo that used `expo init` and I only added a button: https://github.com/hufftheweevil/my-app

**Comment by brentvatne** [comment]
i can’t reproduce it and this is the first i’ve heard of such an issue, so i’m not sure how to proceed here. @byCedric any ideas?

**Comment by byCedric** [comment]
I'm afraid not, it shouldn't be Windows related because the app's bundle is already loaded. Such excessive delays are usually caused by the JS thread (on the device) being stuck doing something. Like Brent mentioned, I sometimes have that when I debug the JS thread and connect it to my computer.

One thing that you could try, but it's a long shot, is to run your app in production mode and see if the same thing happens. To do that, you can perform the following steps:

1. Remove the `.expo` folder from your project
2. Upgrade to CLI `3.24.0` (optional, might include a change that impacts this) 
3. Reinstall your `node_modules` by removing the `node_modules` folder and `yarn.lock` or `package-lock.json` files, and install again.
4. Start your project with `$ expo start --lan --no-dev --clear` (starts it in production mode, using your interna/wifi network, and cleans the cache)

**Comment by hufftheweevil** [comment]
I just realized today that my Expo Client app wasn't up to date. I had 2.14. After updating to 2.16, the issue went away.
