### ISSUE TITLE
Handle iOS 14 privacy changes especially with respect to IDFA

### ISSUE THREAD

**Issue by piyuaryan** [expo/expo#9692]
According to Apple's WWDC 2020,

> iOS 14 will curb access to users' unique Identifier for Advertisers (IDFA). Before, apps could freely graze on IDFAs; now, they must seek specific permission, via a stark pop-up message whose format is rigidly dictated by Apple, to "track you across apps and websites owned by other companies".

https://www.forbes.com/sites/johnkoetsier/2020/06/24/apple-just-made-idfa-opt-in-sending-an-80-billion-industry-into-upheaval/#cf69f5c712c9
 
First, my app doesn't show ad nor it tracks users. But expo doesn't have option to disable IDFA so far.
So, any work around how to handle this?
The iOS popup message is going impact our app's UX really badly and would create wrong impression of us tracking users across the internet.

Apologies if I should have posted this in forum.expo but I believe expo sdk changes will be required for solution. Hence created the issue here.

Thanks.

**Comment by byCedric** [comment]
Hi @piyuaryan, thanks for expressing your concerns about this! It's a topic that we acknowledge is one that we should change. 

Because we include the Segment SDK and Amplitude SDK in managed apps, an IDFA token is sort-of required. I fully agree with you about this having a really really bad UX impact on your app. That's why we considered 2 things, either remove these SDKs from managed or try out their new SDKs that don't require an IDFA token. We chose the latter, upgrading to a newer SDK.

- For Segment, we already made some changes, [you can see that here](https://github.com/expo/expo/pull/9606). 
- For Amplitude, by default, the iOS SDK collects [these listed properties](https://help.amplitude.com/hc/en-us/articles/115002380567-User-Properties-Event-Properties) (IDFA is not included) and uses IDFV (Identifier for Vendor) for the device id, although as the developer you can set it to anything you want. This should address the issue, but just to be sure we contacted them to see if they are planning to completely remove the code that _could_ get the IDFA, in case that’s what Apple is looking for.

We will probably address this in either a separate blog post or the release post for a new SDK.

Hope this helps!

**Comment by piyuaryan** [comment]
Thanks very much @byCedric.
This helps a lot.
I'll keep an eye for the blog post regarding this and new SDK.
Cheers.

**Comment by DatMoser** [comment]
Is there any update on this? The docs for submitting for the App-Store still recommend to check idfa-usage because of Facebook and GoogleAdMob SDKs. My app does not use any of these and I'm now wondering if the app (sdk 41) already complies to Apple's new ios 14 privacy guidelines or if I actually have to eject to bare workflow and remove these sdks manually? I could not find anything about this in the latest sdk41 blog post.

Considering the fact that these privacy guidelines just came into effect, it would be nice to know if my next update might get rejected because of that. 😬

**Comment by rikur** [comment]
Is "Device ID" still required in iOS declaration if using bare workflow and no authentication/ads/analytics etc?
