### ISSUE TITLE
Seems Low in Performance, My Videos FPS is not very good. even on release builds.

### ISSUE THREAD

**Issue by FawadMahmood** [expo/expo#9699]

**Comment by byCedric** [comment]
@FawadMahmood, without an example or more information we have no clue what's going on in your app. There are a lot of things that might impact performance, like unnecessary rerenders etc. This issue only contains a question and no information whatsoever, that's why I'm closing this issue. If you think this is an issue in our Video API, please provide an example where the performance is not matching the expected performance (e.g. with a [snack](http://snack.expo.io/), or github repo) and information about your environment or app.
