### ISSUE TITLE
Can't schedule iOS location notification

### ISSUE THREAD

**Issue by mgburns** [expo/expo#9739]
### Summary of Issue 
I'm unable to schedule a notification with a `location` trigger for iOS.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting

```
  Expo CLI 3.24.0 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~38.0.9 => 38.0.9 
      react: ~16.11.0 => 16.11.0 
      react-dom: ~16.11.0 => 16.11.0 
      react-native: ~0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.24.0
```

Targeting iOS 12 and up.

### Reproducible Demo

```
import * as Notifications from "expo-notifications";

// Will schedule as a `UNCalendarNotificationTrigger` if `repeats` is present in the trigger
Notifications.scheduleNotificationAsync({
  content: {
    title: "Test notification",
  },
  trigger: {
    type: "location",
    repeats: true,
    region: {
      type: "circular",
      identifier: "loc-1",
      notifyOnEntry: true,
      notifyOnExit: true,
      radius: 50,
      center: {
        latitude: 38.992014,
        longitude: -77.03174,
      },
    },
  },
});

// Won't schedule at all if `repeats` is missing
Notifications.scheduleNotificationAsync({
  content: {
    title: "Test notification 2",
  },
  trigger: {
    type: "location",
    region: {
      type: "circular",
      identifier: "loc-2",
      notifyOnEntry: true,
      notifyOnExit: true,
      radius: 50,
      center: {
        latitude: 38.992014,
        longitude: -77.03174,
      },
    },
  },
});

Notifications.getAllScheduledNotificationsAsync().then(console.log);
```
 
### Steps to Reproduce

Load the code sample above in a bare Expo app and run it on a real iOS device. Observe the scheduled notifications logged to the console have only one notification with a trigger type of `UNCalendarNotificationTrigger`.

### Expected Behavior vs Actual Behavior

I would expect two location notifications to be scheduled, one repeating and one not.

**Comment by sjchmiela** [comment]
Hey @mgburns!

I'm sorry to say that `expo-notifications` doesn't yet support adding notifications with location-based triggers. If you checked out [`NotificationTriggerInput` documentation](https://docs.expo.io/versions/v39.0.0/sdk/notifications/#notificationtriggerinput) you'd notice there's no location trigger there.

If you tried to catch errors of `scheduleNotificationAsync` you'd see the error has a meaningful description (next time try `Notifications.scheduleNotificationsAsync(…).catch(console.log)` or `try {} catch (e) {}`).

If you want you could try to implement location-based notification trigger inputs yourself, I'll be happy to review such a pull request. If you needed any pointers let me know.

Otherwise you can always submit a feature request at https://expo.canny.io. 🙂 

PS. I'm not saying we will never add such a feature to the library ourselves! It's just not on the immediate priorities list.
