### ISSUE TITLE
Splash screen flickers in Android dark mode

### ISSUE THREAD

**Issue by clems36** [expo/expo#9758]
### Summary of Issue

On Android, when dark mode is on, a black flicker occurs while the splash screen is displayed. This does not happen with dark mode disabled.

### Environment

```
Expo CLI 3.23.1 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.9
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-navigation: ^4.0.10 => 4.4.0
```
`"expo-splash-screen": "^0.3.1",`

### Expected Behavior vs Actual Behavior

The first GIF is with dark mode off, the second one with dark mode on. 
Note: here i'm not talking about the black screen that appears before the login page.
![ezgif com-resize (1)](https://user-images.githubusercontent.com/6041593/90265025-45536800-de52-11ea-95d1-e5b7aeea7f1d.gif)
![ezgif com-resize](https://user-images.githubusercontent.com/6041593/90265144-70d65280-de52-11ea-9f02-aaa3e58d0ed0.gif)

**Comment by gnprice** [comment]
This looks potentially related to #10436.

**Comment by brentvatne** [comment]
hey @clems36 - i cannot reproduce on the latest version of expo-splash-screen. i suspect that it has resolved since you posted this issue, but it's hard to tell because you didn't include a [mcve](https://stackoverflow.com/help/mcve), so i had to guess with respect to your app configuration.

![Screen Recording 2020-10-23 at 4 10 35 PM](https://user-images.githubusercontent.com/90494/97061152-b39b6180-154a-11eb-8037-a31fa0f5a6b0.gif)

i used this repo: https://github.com/brentvatne/splash-attempt-repro

if you are still encountering this, please post a new issue and provide a mcve.

**Comment by clems36** [comment]
Hey @brentvatne thank you for answering. After updating to SDK 39 + latest version of `expo-splash-screen` the bug is indeed gone. The only thing left is #10436 which I've temporarily resolved by using a timeout as suggested by bbarthec.
