### ISSUE TITLE
[expo-local-authentication] iOS Touch/FaceID is shown on grey background.

### ISSUE THREAD

**Issue by svenlombaert** [expo/expo#9789]
### Summary of Issue 
I just started using expo-local-authentication (switched from react-native-touch-id) and have an issue on iOS. When the native dialog shows to use your touch/faceID, it is shown on a non-transparent grey background.

### Environment - output of `expo diagnostics` & the platform(s) you're targeting
```
  Expo CLI 3.9.0 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 13.1.0 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.14.7 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmPackages:
      @testing-library/react-native: ^5.0.3 => 5.0.3
      @types/react: ^16.9.34 => 16.9.34
      @types/react-native: ^0.62.7 => 0.62.7
      react: 16.11.0 => 16.11.0
      react-native: 0.62.2 => 0.62.2
    npmGlobalPackages:
      expo-cli: 3.9.0
```

Targeting iOS and Android in a bare react-native app.

 
### Steps to Reproduce
Call `await LocalAuthentication.authenticateAsync()` on any screen on iOS

### Expected Behavior vs Actual Behavior
Left is the screen where I trigger it, right is what happens.
<img src="https://user-images.githubusercontent.com/2846986/90384659-33f0a280-e082-11ea-98ae-7583074b406f.PNG" width="50%" /><img src="https://user-images.githubusercontent.com/2846986/90384644-2f2bee80-e082-11ea-805a-81446b72c164.PNG" width="50%" />

Edit: I am using react-native-navigation, might be important

**Comment by salhotra** [comment]
What I do is show a modal to block the screens underneath before calling the authentication method. And on success callback, I hide the modal.

Sidenote: There will be another case you might wanna handle if you haven't already. When you tap on the cancel label, you'll get stuck. So you can show an alert which says something like "You need to authenticate with your biometric data or phone passcode to access the app". And on that alert, you can have a button that recursively calls the authentication method again.

**Comment by svenlombaert** [comment]
@salhotra  I have the same flow when authentication is actually set-up, but the above screens are when a user is activating the faceId. I'd just expected that the grey background that you see on the right image would actually have some opacity to see the screen underneath, or just no background at all.

**Comment by salhotra** [comment]
Ah now I get it. You need the grey background to be translucent. Strange that you see that non-transparent grey background. For me, there was no background at all. That's why I added a modal with [react-native-blur](https://github.com/react-native-community/react-native-blur) on it. I'm using "expo-local-authentication": "9.1.1" on a bare project with unimodules. Not too sure how this can help you but putting it out there in case it does.

**Comment by svenlombaert** [comment]
I have the same set-up with you, bare react-native project. I am using react-native-navigation though, so might be related to that. Hoping someone else would have the same issue or could point out where it might go wrong.

**Comment by affcue25** [comment]
Is anyone familiar with the unknown error of expo local authentication TouchID/FaceID, when installed in multiple apps, it stops triggering TouchID/FaceID in the first installed app, but works in last installed app. 
But that works perfectly in android for multiple apps. 
Does anyone know the solution? I have different meta data for apps in my app.json.

**Comment by newfylox** [comment]
@affcue25 I'm starting to think that I have that issue. FaceID was working great on 2 of my client phones but since a couple of week, when they press the button to show the FaceID prompt, it just does nothing. Nothing is showing, no errors in my Sentry account.

On an iPhone 8 it works with fingerprint and all my Android phones are working.

I don't know if it's related to your strange bug but looking on google bring me here (you message)
