### ISSUE TITLE
iOS icons sometimes not properly generated for app store in standalone build (ITMS-90022: "Missing required icon file.")

### ISSUE THREAD

**Issue by brentvatne** [expo/expo#980]
If you upload your app to testflight and see the Expo icon in some icon sizes, this is a known issue and we will work to resolve it first thing this coming week (week of Nov 19)

**EDIT: As of Nov 21, 11:30am PST this issue should be resolved. Please run your build again and let us know if you have the same issue.**

**Comment by terribleben** [comment]
For anyone who spots this issue, I would appreciate the following info:

- The build id which produced the issue (required)
- A screenshot of the contents of your ipa or simulator build, showing the actual icons it contains (optional)

**Comment by terribleben** [comment]
As far as we can tell, the failure is due to flaky behavior of an image utility library we use to generate different icon sizes from your app's icon. When the library intermittently fails on our build machine, the resulting .ipa is missing some icon sizes, so Apple displays this warning.

We're currently working on switching to a different (more reliable) library so this doesn't happen. We'll deploy this as soon as we build and test it.

We hope to have the fix up soon. Until we deploy a reliable fix, here are some things you can do:

- Make sure you have the latest non-beta version of Application Loader (just to ensure this is not a red herring error). If your app was working fine before, then this is probably not the issue. Either way it's good to keep this tool up to date.
- Try using a different color profile for your icon file. Ideally the same as the one that comes with Expo's template "tabs" project. The error seems to occur intermittently when the provided icon has a different color profile than our build system's color profile.

**Comment by Doppy** [comment]
Build Id: 3b22d523-a586-4993-94e3-aa184ac1b7a8

![image](https://user-images.githubusercontent.com/1094681/33064513-81124aa0-ced8-11e7-88e1-aacf3b7a08f5.png)

**Comment by LastxTemplar** [comment]
Was this fixed?

**Comment by alexrussell** [comment]
FWIW I think I can shed a little light on conditions under which it breaks - 512x512 icons are far more resilient to this breakage. Once I switched to using 1024x1024 icons (because Application Loader was complaining about a missing 1024 version) I now always get the Expo logo. So I imagine there's a memory issue at play here as well as whatever else may be happening.

**Comment by alexrussell** [comment]
Also, because it was asked for:

Build ID: `0dfff835-ae0c-4049-aef5-4f7d8bf17b63` @ approx 13:45 UTC 21 Nov
Submitted with a `1024x1024` icon with no transparency, got the following icons back out:

![icons](https://user-images.githubusercontent.com/412784/33078618-22d285de-cecb-11e7-8563-7c3a6c889ed8.png)

As you can see, they're *all* Expo logos.

---

Build ID: `e91488eb-8d53-4198-851b-994589cc2083` @ approx 10:15 UTC 21 Nov
Submitted (erroneuosly!) with a 512x512 icon with transparency, got the following icons back out:

![icons old](https://user-images.githubusercontent.com/412784/33078750-8c6c7252-cecb-11e7-9dac-761a466de043.png)

As you can see, all except one are my own icon.

**Comment by Dygerati** [comment]
I encountered this error upon uploading to the App store the first build, and then I rebuilt and actually successfully uploaded the 2nd IPA file. However it just failed the review process citing this issue:

>We noticed the app icon displayed on the device and the large icon displayed on the App Store do not sufficiently match, which makes it difficult for users to find the app they just downloaded.

Then shows me the offending icon: Icon-60@2x.png. It's the expo logo, instead of mine.

**Comment by terribleben** [comment]
Hello everyone, can you try another `exp build:ios`? We have deployed a tentative fix to our build servers, but will leave this issue open until people get a chance to verify.

**Comment by terribleben** [comment]
@cseelus we deployed a new version of the builder at about 11:30am PST, and this build log is from before that time. Can you try again?

**Comment by cseelus** [comment]
@terribleben Ok, seems the builder works again 👍🏼

**Comment by chownation** [comment]
@terribleben works for me as well, thanks!

**Comment by Doppy** [comment]
@terribleben work for me too! many thanks!

**Comment by alexrussell** [comment]
Works for me now with a 1024x1024 icon. Good work! 👍

**Comment by terribleben** [comment]
Great that it's working for you all. I will close this for now, but please reach out if you see any fishy behavior.

Anybody just now finding this thread: Make sure you have a build that was created after the time when I posted [this comment](https://github.com/expo/expo/issues/980#issuecomment-346136355).

**Comment by maharjanaman** [comment]
Hello, I'm having similar issue with exp-cli version 48.0.2 and exp sdk version 21. Application loader I'm using is of 3.7 version.

**Comment by krzysztofp** [comment]
Got this today, exp-cli version 48.0.2, 
![image](https://user-images.githubusercontent.com/1634660/35284142-523de3fc-005a-11e8-9c31-0b441a14b392.png)

**Comment by namsu95** [comment]
I've just met exactly same error message as @krzysztofp did. 
Exp-cli version 48.0.2 and 47.3.17 showed me the same error. Expo sdk version is 24 and App loader is 3.7.

**Comment by terribleben** [comment]
Hey there, we are tracking the recent issue [here](https://github.com/expo/expo/issues/1309).

**Comment by saiHemanthGitHub** [comment]
@terribleben i am getting the same issue from past 2 days and i am not able to solve this issue.
![screen shot 2018-05-17 at 12 10 42 pm](https://user-images.githubusercontent.com/12952098/40160465-5c3478e2-59cb-11e8-8c3d-2f12a6f3bffe.png)

**Comment by AtNovember** [comment]
i got same issue!
