### ISSUE TITLE
Facebook Login Status

### ISSUE THREAD

**Issue by predescu** [expo/expo#981]
I couldn't find any way to check the Facebook Login status.

I want to use something like:
```
FB.getLoginStatus(function(response) {
  if (response.status === 'connected') {
    // the user is logged in and has authenticated your
    // app, and response.authResponse supplies
    // the user's ID, a valid access token, a signed
    // request, and the time the access token 
    // and signed request each expire
    var uid = response.authResponse.userID;
    var accessToken = response.authResponse.accessToken;
  } else {
    // the user isn't logged in to Facebook.
  }
 });
```
https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus

Does anyone have any solution?
Thanks.

**Comment by terribleben** [comment]
Hi, the Facebook Login API returns a [token and an expiration date](https://docs.expo.io/versions/latest/sdk/facebook.html#returns). So at some future time, given the token and the current date, you should have all the information you need to determine whether the user is logged in. In the docs we recommend persisting this information using the AsyncStorage API so that you can perform this check later.

**Comment by edwh** [comment]
Aren't there are cases where a token can be invalidated, such as when a user changes their password?  If so then it isn't sufficient to just assume it will be valid until the expiry.

**Comment by todmar13** [comment]
The user can log out of facebook on the device, in which case the token is then invalid for getting login status.
