### ISSUE TITLE
Installing expo breaks node_modules - Unable to resolve react-native/Libraries/Renderer/shims/ReactNativeBridgeEventPlugin"

### ISSUE THREAD

**Issue by Hiroki1116** [expo/expo#982]
As soon as I install Expo SDK with `yarn add expo`, I see the folloing error message in Expo XDE

`Unable to resolve react-native/Libraries/Renderer/shims/ReactNativeBridgeEventPlugin" from ".//node_modules/react-native-gesture-handler/GestureHandler.js"`

![error-expo](https://user-images.githubusercontent.com/9676341/32996988-e125b1c4-cdd5-11e7-9e50-268a6c1d88b7.png)

This error persists until I remove `expo` with `git checkout -- .` and refresh node_module  with `rm -rf node_modules && yarn install`.

(I started this project with `"expo": "^22.0.2"`. Running `yarn add expo` makes it `"expo": "^23.0.0"` in package.json)

![json](https://user-images.githubusercontent.com/9676341/32997113-4cdcd658-cdd7-11e7-9b87-6452c00c789b.png)

Has anyone encountered a similar issue?

Any advice will be appreciated!

**Comment by whitebird** [comment]
@Hiroki1116 I have the exact same issue with the same preceding steps. I wish to only use the ImagePicker from Expo.
<img width="381" alt="screen shot 2017-11-20 at 12 35 02" src="https://user-images.githubusercontent.com/1058174/33016771-10070cf8-cdf0-11e7-8c55-62a08a8dd292.png">

**Comment by ide** [comment]
@Hiroki1116 It looks like you are using React Native 0.49.5 with the JS for Expo SDK 23, which won't work because Expo SDK 23 was based on React Native 0.50.

You also can't add Expo to an existing React Native project -- Expo uses React Native but Expo is not a React Native library. See the documentation for more about how developing with Expo works: https://docs.expo.io/versions/latest/introduction/project-lifecycle.html.
