### ISSUE TITLE
Updating SDK 35 to 36

### ISSUE THREAD

**Issue by kchangch** [expo/expo#9934]
I have updated my app from SDK 35 to 36 and I'm getting this issue "No component found for view with name "ARTShape"". I know that changes made in 36 was the removal of ART library from expo. How can I work around this? I have been also looking into my code and there is no place where I use ARTShape. How can this be fixed? Please help.

**Comment by cruzach** [comment]
hi @kchangch, it's probably one of your dependencies that's relying on that ( I think some of the progress indicator libraries rely on ART). We document some ART replacements [in the docs](https://docs.expo.io/versions/latest/sdk/art/).

I'm closing this issue since we keep github reserved for bug reports
