### ISSUE TITLE
Lost keystore passwords

### ISSUE THREAD

**Issue by mpgallage** [expo/expo#9988]
Hi there,

I built an app using expo. And when I built android app I let the expo generate my keysotre and I have a copy of the keystore. But in next release I chose expo to generate keystore again and now I have a new key store.

The problem is I don't have the old keystore password. ***fetch:android:keystore*** only gives me the new keystore password. How can I find the old password?

Thanks

**Comment by byCedric** [comment]
Hi @mpgallage! Unfortunately, we don't keep a backup due to security reasons. If you lost the keystore or the passwords/aliases, the keystore becomes not that useful. But, there are things you can do to recover your app.

Unfortunately, you have to contact Google and ask them to replace the certificates for your app. You should contact Google from the account that owns the app. It's a security check from Google to prevent app-takeovers. [Stavros Oikonomidis wrote an excellent guide for this on Quora](https://www.quora.com/How-do-I-make-a-new-Certificate-Keystore-key-after-losing-the-key-of-my-Android-app). You can just download the current keystore and passwords for step 1, or create them yourself and upload it to our build service.

Hope this helps!

**Comment by mpgallage** [comment]
Hi @byCedric, Thank you very much for the response. It certainly helps me to recover the ownership of my app.

Thanks!
Malaka
